### ISSUE TITLE
--savetiddlers causes an error

### ISSUE THREAD

**Issue by pmario** [Jermolene/TiddlyWiki5#1]
created `index.html` with `tw5.sh` -> file is ok.

node tiddlywiki.js --load tmp/tw5/index.html --savetiddlers tmp/tiddlers

`tmp/tiddlers` directory exists

```
/media/Daten/Git/tiddly/cook.js/tiddlywiki.js:100
                    var tiddlers = tiddlerInput.parseTiddlerFile(data,type,fields);
                                 ^
TypeError: Object #<Object> has no method 'parseTiddlerFile'
    at /media/Daten/Git/tiddly/cook.js/tiddlywiki.js:100:34
    at [object Object].<anonymous> (fs.js:115:5)
    at [object Object].emit (events.js:64:17)
    at afterRead (fs.js:1111:12)
    at Object.wrapper [as oncomplete] (fs.js:254:17)

```

node version 0.6.5, latest cook.js git repo.

`test.sh` doesn't produce usefull output.

**Comment by Jermolene** [comment]
Hi @pmario nice to be reminded of this PR from your bio on tw.com. I love that it has had so many back references from people just writing things like "the #1 cause of problems".
