### ISSUE TITLE
Feature request: New here and new journal here should have way to create new from template

### ISSUE THREAD

**Issue by giffmex** [Jermolene/TiddlyWiki5#1006]
Maybe this is already possible. So could there either be a way to create new here based on skeleton template, or instructions on how to do it, if that is already possible. Otherwise I am going to need to stick with Skeeve's old plugin that does that.

By the way, the advanced search toolbar button is a great feature, as is the idea of dragging links into an edit window. Awesome! Thanks! Haven't had time to seriously play with 5.1.3 or 4 yet. Won't have time to breathe until mid-September. But I like what is happening!

**Comment by pmario** [comment]
@giffmex ... can we close this issue?

**Comment by giffmex** [comment]
Yes

David Gifford
Mexico team leader, Mexico City

*Resonate Global Mission*
*Engaging People. Embracing Christ.*
A Ministry of the Christian Reformed Church
resonateglobalmission.org

**Comment by Jermolene** [comment]
Thanks @pmario @giffmex
