### ISSUE TITLE
Add TableOfContents to core

### ISSUE THREAD

**Issue by Jermolene** [Jermolene/TiddlyWiki5#1009]
At the moment, the TableOfContents tab seen on http://tiddlywiki.com is not part of the core, and so doesn't appear in `empty.html`. This has caused much confusion.

The original reason for not putting the table of contents into the core sidebar was because it looks a bit inscrutable and useless until you've begun tagging tiddlers with TableOfContents.

We could help by including a message when there's no tiddlers tagged TableOfContents that guides the user to create the table of contents.

There would be some backwards compatibility issues; people who upgrade to the new version who have already created a table of contents tab would end up with two table of contents tabs.

**Comment by pmario** [comment]
@Jermolene  imo this can be closed

**Comment by Jermolene** [comment]
Thanks @pmario
