### ISSUE TITLE
TypeError: Argument 1 of MutationObserver.observe is not an object.

### ISSUE THREAD

**Issue by ittayd** [Jermolene/TiddlyWiki5#1052]
I get this when I reload my wiki (in Firefox)

**Comment by MatthewValentine** [comment]
Although I have not tested this, the solution to this problem appears to be very simple. In mathjax/init.js, towards the bottom there is a line `var n = document.getElementsByClassName('story-river')[0];`

This should be changed to read `'tc-story-river'` rather than `'story-river'`.

**Comment by crayzeewulf** [comment]
The fix mentioned by @MatthewValentine worked for me in TW5. Thanks.

**Comment by tobibeer** [comment]
Has this fix been added? If not, please reopen the issue.

**Comment by phbp11** [comment]
yes for me it works perfectly deleting the plugin
hello
