### ISSUE TITLE
Introduce hooks mechanism

### ISSUE THREAD

**Issue by Jermolene** [Jermolene/TiddlyWiki5#1064]
Some plugins need to be able to alter quite fundamental aspects of TiddlyWiki's behaviour. For example, a plugin that @welford is working on needs to modify the default tiddlers that are displayed at startup.

It is proposed to introduce a new global hooks mechanism that can be used across the core to enable plugins to hook into and modify default functionality.

The example of modifying the list of default tiddlers would be something like this:

```
$tw.hooks.addHook("th-opening-default-tiddlers-list",function(list) {
list.push("Another tiddler");
return list;
});
```

Then, within the function openStartupTiddlers() in `$:/core/modules/startup/story.js`, we'd invoke the hooks like this:

```
storyList = $tw.hooks.invokeHook("th-opening-default-tiddlers-list",storyList);
```

**Comment by inmysocks** [comment]
This issue should be closed because it was acted upon already.

**Comment by tobibeer** [comment]
@Jermolene: anymore actionable items on this atm?

**Comment by Jermolene** [comment]
Thanks @tobibeer
