### ISSUE TITLE
Enhancement: add tag via ENTER

### ISSUE THREAD

**Issue by tobibeer** [Jermolene/TiddlyWiki5#1084]
Allow the user to add a tag pressing the ENTER key in the tag input, irrespective of any suggestions in the tag selectbox.

**Comment by tobibeer** [comment]
Appears rather simple to achieve with https://github.com/Jermolene/TiddlyWiki5/issues/1970#issuecomment-162662053. Will work on that and see if I can'T make a PR to talk code of that EventWidget.

**Comment by pmario** [comment]
this one may be closed. ... related to PR #2592

**Comment by Jermolene** [comment]
Thanks @pmario

**Comment by tobibeer** [comment]
@pmario, imho, tickets should only be closed after a given PR holding a solution is merged.

**Comment by pmario** [comment]
@tobibeer 
I agree. I did open a new issue, as a summary, for the PRs, that we discussed at the "PR session" hangout, several weeks ago. 

see: "open PRs that should be merged" #2642 ... 

It covers all the PRs that I pulled from your repo, to test them. So I could be sure, bumping them should be with no risk ;)
