### ISSUE TITLE
http://tiddlywiki.com/#%22BJTools%22%20by%20buggyj - and ???

### ISSUE THREAD

**Issue by bs27975** [Jermolene/TiddlyWiki5#1087]
http://tiddlywiki.com/#%22BJTools%22%20by%20buggyj

"buggyj has created several useful plugins, including a WYSIWYG HTML editor, a configurable calendar and tag lists with draggable ordering."

Great! WHERE! WHAT! HOW!

A link to the plugins or where to find them or how to use them or SOMETHING would be useful here.

**Comment by pmario** [comment]
imo can be closed, since those links have been added.

**Comment by pmario** [comment]
bump .. @bs27975 please close!
