### ISSUE TITLE
"sameday" operator inconsistent timezone handling

### ISSUE THREAD

**Issue by Jermolene** [Jermolene/TiddlyWiki5#1096]
The sameday filter operator treats its operand as a UTC date/time, and converts it to a local time before use. This means that the date targeted may be different than the one specified in the operand.

Reported here:

https://groups.google.com/d/topic/tiddlywiki/28DxHYLt6-0/discussion

One fix is for the sameday filter operator to treat its operand as local time but we need to assess whether that has any other implications.

Also see #190.

**Comment by nameanyone** [comment]
+1. Just stumbled upon this issue.

**Comment by tobibeer** [comment]
Definitely. With dates being converted to "the wrong time" via UTC, any date filtering or other reading of dates needs to convert back to local time. Always both, not just one:

* **write**: convert to UTC
* **read**: convert back to local time

What implications would you be thinking of, @Jermolene, other than that we're currently doing it wrong by only **writing** to UTC but not (always) **reading** in local time.

**Comment by Jermolene** [comment]
Consolidated in #2061
