### ISSUE TITLE
Clearer indication of current palette in ControlPanel

### ISSUE THREAD

**Issue by twMat** [Jermolene/TiddlyWiki5#1099]
Tab Appearence > Palette

I suggest thin frame around selection, or perhaps contrasting background, instead of dot.

Or, if dot is kept, I suggest right-shifting all color boxes so that dot is more visible (compare with Tab Appearence >Theme) and also change color to black and make it bigger.

Please inform me if I've posted this in the right place because I have quite a few other bits regarding the Controlpanel as listed in this google dev group discussion:
https://groups.google.com/forum/?fromgroups=#!topic/tiddlywikidev/jA21ARJ_mY4

Thank you!

<:-)

**Comment by tobibeer** [comment]
@twMat, see preview on pull request => better?

**Comment by tobibeer** [comment]
aaanyhow, so the image is here:

https://github.com/tobibeer/TiddlyWiki5/pull/3#issuecomment-142024166

**Comment by twMat** [comment]
(Ironically, I'm again getting uncertain of where to reply - here or in #1953 )

Anyway, the #1953 proposal is a definite improvement over current. However, IMO both Palette, Story view and Theme tabs (and probably even more) should be harmonized visually - for a user it is really just a radiobutton "one from many" type selection and it is not so elegant to expose the users to every variant possible, IMO. For this reason I say we first agree on one "style" that can then be applied to all relevant cases (immediately or gradually). Personally, I would not mind #1953 for all.

**Comment by tobibeer** [comment]
What my pull request does, primarily is to add the missing "tc-chosen" class, so the eventual styling is but a matter of preference and, above all, adjustable... unlike now.

**Comment by Jermolene** [comment]
Fixed in #1954
