### ISSUE TITLE
reveal widget: allow popups to work with column-count layouts

### ISSUE THREAD

**Issue by tobibeer** [Jermolene/TiddlyWiki5#1102]
For much improved readability I was trying implement the CSS3 `column-count` directive and stumbled over the problem of reveal popups being swallowed by the column.

Can the reveal widget be changed so that when of type "popup" it is not rendered within the element flow but somewhere independent on the page?

http://tb5.tiddlyspot.com/#ColumnsAndPopups
![col](https://cloud.githubusercontent.com/assets/97566/5106703/30d44bd6-6ffb-11e4-8787-2346e5dd8400.jpg)

Here's how it currently works having to read the list row by row...
http://tb5.tiddlyspot.com/#Solutions

**Comment by tobibeer** [comment]
Sorry, but I need to reopen this. Popups really need to be taken out of the flow!
Here is another example setting `tc-tiddler-frame` to `overflow:hidden`: [Tiddler Ribbon](http://tb5.tiddlyspot.com/#Tiddler%20Ribbon)

**Comment by Jermolene** [comment]
>  Popups really need to be taken out of the flow!

Doing so will break many, many things. I'd suggest opening a new ticket when you've got a specific proposal that can be reviewed.

**Comment by tobibeer** [comment]
> Doing so will break many, many things.

What do you see breaking?

> I'd suggest opening a new ticket when you've got a specific proposal that can be reviewed.

Open a new ticket #1432 and gave it a more general title, closing this one.

**Comment by tobibeer** [comment]
A related discussion on problems with cutoff in the sidebar too..

https://groups.google.com/forum/#!topic/tiddlywiki/gm-uCdS_O0w

>  My desire (is) to take popups out of the document flow by rendering them somewhere else entirely. One possibility would be to just leave an anchor widget in the place where the popup is now rendered that links it to the popup being rendered completely independent of the story or sidebar.

**Comment by tobibeer** [comment]
added addendum to OP:

> The [appear widget](http://tobibeer.github.io/tw5-plugins/#appear) now provides a **handler** mechanism that allows to take popups out of the flow and thus prevent the cut-off.
