### ISSUE TITLE
playing nice with VCS ?

### ISSUE THREAD

**Issue by tgirod** [Jermolene/TiddlyWiki5#1108]
Okay, this one is far fetched, but here it goes.

In my short quest for collaborative editing in tiddlywiki, I tried to track changes in a tw file with a git repository. Then, I forked the repo several times, did some concurrent (but not conflicting) edits and tried to merge it back together.

Unfortunately, it didn't work - it looks like editing a tiddler produce changes at various places in the file, and git doesn't do well with merging these.

This makes me wonder if it would be possible to alter how tw stores information in order to make edits more VCS friendly.

**Comment by pmario** [comment]
I think this issue can be closed. There is a fix, that is presented here. nodejs is VCS friendly and the tw "single file" structure imo won't change in the foreseeable future. @tgirod

**Comment by pmario** [comment]
@tgirod 
@Jermolene .... bump for close!

**Comment by sukima** [comment]
There is an even simpler solution. Simply add the story list to your VCS ignore file. I added these to my `.gitignore` and never had to worry about this problem. Been using TW for static generation for a long time now. (https://github.com/sukima/dev-tritarget-org/)

```
tiddlers/\$__StoryList.tid
tiddlers/\$__ShowEditPreview.tid
```
