### ISSUE TITLE
Support variable passing for notifications

### ISSUE THREAD

**Issue by danielo515** [Jermolene/TiddlyWiki5#1121]
Currently $tw.notifier.display accepts an option parameter, but is not used.
I really like how this module works, but it is very limited if it only can display static tiddlers. Giving a string to concatenate to the tiddler text, for example, will make it much more usable.

``` javascript
$tw.notifier.display("$:/language/Notifications/upload/error",{text:errorText});
```

**Comment by Jermolene** [comment]
Thank you @pmario
