### ISSUE TITLE
CountWidget Should create variables

### ISSUE THREAD

**Issue by danielo515** [Jermolene/TiddlyWiki5#1132]
The count widget should behave like the list widget, creating variables with the count. This way you can use it like the set widget, but for counting.

IMO this should be just a filterOperator, since this behavior is redundant.

**Comment by pmario** [comment]
@danielo515 .. there is the count operator, which imo should close this issue?  http://tiddlywiki.com/prerelease/#count%20Operator

**Comment by danielo515** [comment]
@pmario the count operator dates from 8th February 2017 while this issue is from 2014, so probably it does not make sense anymore.
However I'm start to be worried about the super-powers of the list widget, which seems to replace more and more widgets as time passes.

Regards
