### ISSUE TITLE
Make all Sidebar tabs configurable (feature request)

### ISSUE THREAD

**Issue by gernert** [Jermolene/TiddlyWiki5#1138]
# Make all Sidebar tabs configurable

When the Sidebar tabs are configurable one can add certain tabs like:
- 'System tags' ( #569)
- 'Table of contents' ( #1009)
- ... 

on demand.

And you can leave out tabs you do not use (personally I don't like the dual 'Recent' tabs so I want to get rid of one).

It will ease implementing feature request #1066 (Search results in a tab of the Sidebar) as well.

**Comment by pmario** [comment]
imo `$:/tags/SideBar` does exactly that. @gernert pls close

**Comment by danielo515** [comment]
@pmario could you please elaborate? Many of the tabs are currently hardcoded

**Comment by pmario** [comment]
they are all tagged: `$:/tags/SideBar` or `$:/tags/MoreSideBar` ... 

So if you remove the tag the tabs are gone. 
If you add the tag to new tiddlers they appear. 
If you use `list-before` or `list-after` fields, you can set the exact position.

**Comment by danielo515** [comment]
> So if you remove the tag the tabs are gone.

But where is the user friendly UI to do it? It would be much better to have it on the control panel. This is a common customization requirement, common enough to give it an UI

**Comment by gernert** [comment]
This one is very old. I agree with @pmario.

**Comment by tobibeer** [comment]
As perhaps a future alternative, I would propose a unified UI, i.e. a single list for both tabsets where you have radio buttons, one for the sidebar and one for more and can drag and drop items in a single list. No need for two.
