### ISSUE TITLE
Route to static  files in the --server mode

### ISSUE THREAD

**Issue by peko** [Jermolene/TiddlyWiki5#1148]
Most of my notes needs an attachment feature (mostly huge pdfs). I found no good way for this.

So I'm just added an new [static route](https://github.com/peko/TiddlyWiki5/blob/master/core/modules/commands/server.js#L227-L240) for "files" subfolder. 

It is ok to do it like this, or there is a better way / or plugin?

**Comment by sukima** [comment]
@Jermolene:
>but the routes are not currently extensible.

They are now in PR #2502 😁 

This PR also addresses @peko's issue. It adds a static assets route as a plugin. Hope this helps. 😉

**Comment by pmario** [comment]
@peko .. imo can be closed see #2502

**Comment by pmario** [comment]
@Jermolene ... IMO can be closed. It seems to be done in #2510

**Comment by Jermolene** [comment]
Thanks @pmario
