### ISSUE TITLE
Dev / GitHub: advisable to use branches for plugins?

### ISSUE THREAD

**Issue by tobibeer** [Jermolene/TiddlyWiki5#1149]
I feel like I really don't want to have a number of repositories, forking [TiddlyWiki5](https://github.com/Jermolene/TiddlyWiki5) for each single plugin.

So, I was thinking of having two dedicated repositories for tw5...
1. for core contributions and related branches
2. for my plugins, managing individual plugins in plugin-related branches 
   - without ever making pull requests, unless that is being wished

This suggests a slightly different approach over [Developing plugins using Node.js and GitHub](http://tiddlywiki.com/dev/#Developing%20plugins%20using%20Node.js%20and%20GitHub|).

What do you think?

**Comment by pmario** [comment]
@tobibeer .. is this one still valid?

**Comment by tobibeer** [comment]
Before closing, every plugin I make is in its own repo and built from a "template" repo. Then there's **http://tobibeer.github.io/tw5-plugins** a wiki with all plugins and examples and other places like **tb5** which include plugins.

As for the core, I am creating a branch for each modification I intend to make a PR for, as one should.

The end. ;-)

**Comment by danielo515** [comment]
Dear @sukima 

> I even wrote a Yeoman script to manage this process (two staged development and production): https://www.npmjs.com/package/generator-tiddlywiki

Damn! I just started to do the same thing: https://github.com/danielo515/yeoman-generator-tw5-plugin

I was planing to use sub-generators to easily scaffold different components of the plugin, like startup modules, widgets, js macros....
I'll take a look at your repo. Why you didn't make this public before?
