### ISSUE TITLE
allow to import dragged clipboard without html

### ISSUE THREAD

**Issue by tobibeer** [Jermolene/TiddlyWiki5#1150]
When dragging selected content from other pages, even within TiddlyWiki, the importer creates a tiddler that has all the html markup within it.

It would be great if that could (optionally) be configured, or via checkbox, or an alternative import so that the created contents are stripped from any html, thus plain-text and perhaps links, if possible.

**Comment by pmario** [comment]
@tobibeer imo can be closed. Just tested it with latest FF and it works as expected in the OP. ...

**Comment by tobibeer** [comment]
@pmario: I suppose this boils down to what the browser actually puts to the clipboard? No Idea.

But here are screenshots, one from Firefox (nice):

![win10_firefox](https://user-images.githubusercontent.com/97566/33308029-25baf4cc-d419-11e7-922f-9727fa3a7efc.jpg)

And one from Chrome (bah):

![win10_chrome](https://user-images.githubusercontent.com/97566/33308030-25fb684a-d419-11e7-83f3-c58df755b67a.jpg)

**Comment by Jermolene** [comment]
Hi @tobibeer! Good to see you back.

I guess the solution would be to incorporate an HTML sanitizer?

**Comment by pmario** [comment]
>I guess the solution would be to incorporate an HTML sanitizer?

I thought, TW already has a sanitizer built in? Or do you mean something different?

**Comment by pmario** [comment]
>I guess the solution would be to incorporate an HTML sanitizer?

I thought, TW already has a sanitizer built in? Or do you mean something different?

**Comment by Jermolene** [comment]
I meant something that would simplify the HTML to the semantically simplest form (eg dropping styles and classes). You're right, "sanitizing" in TW is accomplished by parsing and re-rendering content, and wouldn't help here.

**Comment by tobibeer** [comment]
At least, the assumption being that we're more concerned about content than we are about more or less truthful represenatation (that would rather call for a screenshot, imho).

**Comment by tobibeer** [comment]
> Hi @tobibeer! Good to see you back.

Hello in return. Sry, for the awful silence. Turns out, moving to a new flat and renovating the whole thing can actually be quite disruptive all the while your job keeps you busy as well. ;-)

**Comment by pmario** [comment]
>moving to a new flat and renovating the whole thing

So it's time for a "house warming party" :)

**Comment by pmario** [comment]
@Jermolene -- This one can be closed. The issue is solved. We show the text and html version now and the user can decide

**Comment by Jermolene** [comment]
Thanks @pmario
