### ISSUE TITLE
"pathprefix" is not honored in XmlHttpRequests -> information lost

### ISSUE THREAD

**Issue by aheusingfeld** [Jermolene/TiddlyWiki5#1153]
When I start tiddlyweb via `nohup tiddlywiki /mnt/oc-data/data/ahe/files/ahembp15/tiddlers --server 8080 $:/core/save/all text/plain text/html "test" "test123" 192.168.1.2 "/wiki"` (`pathprefix` set to `/wiki`), the web interface is reachable at `http://192.168.1.2:8080/wiki/`. Unfortunately it seems that the `XmlHttpRequest`s don't recognize the pathprefix but are instead still send to `http://192.168.1.2:8080/`. As requests to the root are not forwarded to tiddlywiki, the information entered in the webUI is not saved to the files on the server.

Here is a screenshot of the error messages that occur when editing a tiddler:
![screen shot 2014-11-28 at 21 11 32](https://cloud.githubusercontent.com/assets/534272/5231960/65250e3a-7743-11e4-9087-8ee62bd908a3.PNG)

**Comment by Lucas-C** [comment]
I'd love to have this too,
or at least an example of rewrite rules (for Nginx, Apache... whatever),
as I don't quite see how they could help to handle this issue.

Indeed, the JS code makes requests relative to the website root,
and I don't see any way to distinguish between a TiddlyWiki request for /status
(that should be routed to TiddlyWiki server)
and a user accessing an existing /status page a the root of the website.

**Comment by Lucas-C** [comment]
I tried the instructions on this page:
http://tiddlywiki.com/static/Using%2520a%2520custom%2520path%2520prefix%2520with%2520the%2520client-server%2520edition.html

    echo '$protocol$//$host$/lucas/tiddly' > lucastiddly/config/tiddlyweb/host

But that didn't made any difference.
Maybe because the tiddlyweb plugin "is inert when run under Node.js." (from https://github.com/Jermolene/TiddlyWiki5/tree/master/plugins/tiddlywiki/tiddlyweb).

**Comment by Lucas-C** [comment]
As I don't really see how to create "a tiddler called $:/config/tiddlyweb/host'' that contains $protocol$//$host$/path/to/my/wiki/" by hand, I also tried this:

    echo -e 'title: $:/config/tiddlyweb/host\n\n$protocol$//$host$/lucas/tiddly' > lucastiddly/tiddlers/\$__config_tiddlyweb_host.tid

**Comment by Jermolene** [comment]
Hi @Lucas-C and welcome, sorry you've run into problems.

> As I don't really see how to create "a tiddler called $:/config/tiddlyweb/host'' that contains $protocol$//$host$/path/to/my/wiki/" by hand, I also tried this:

That's a reasonable way of creating the required file, and looks correct. Have you restarted the wiki and reloaded it in the browser? Can you see what HTTP requests it is making.

> Maybe because the tiddlyweb plugin "is inert when run under Node.js."

The tiddlyweb plugin only runs in the browser, but it gets its configuration information from the serverside wiki: serving the main HTML file bundles up all the current tiddler values into the HTML file. Then the tiddlyweb plugin does the subsequent synchronisation with the server.

**Comment by Lucas-C** [comment]
Thanks for your help @Jermolene !

I confirm that even restarting the server & reloading the page does not make a difference.

Here is the server output:
```
$ tiddlywiki lucastiddly --server 8081 $:/core/save/all text/plain text/html "" "" 127.0.0.1 /lucas/tiddly Serving on 127.0.0.1:8081
(press ctrl-C to exit)
syncer-server: Dispatching 'save' task: $:/StoryList
FileSystem: Saved file /opt/lucastiddly/tiddlers/$__StoryList.tid
```
There are 2 failed HTTP requests:
GET $my.website.domain.name/lucas/tiddlystatus -> 404
GET $my.website.domain.name/lucas/tiddlyrecipes/undefined/tiddlers/$:/StoryList -> 404

And there are the visual error messages:

![screenshot from 2015-06-20 17 28 19](https://cloud.githubusercontent.com/assets/925560/8267911/fe550e2e-1771-11e5-9d2a-99d1f535dd17.png)

**Comment by Jermolene** [comment]
Hi @Lucas-C I think the problem is that you need a terminating `/` at the end of your path in `$:/config/tiddlyweb/host`

**Comment by Lucas-C** [comment]
Yes ! Thank you !
That did the trick, all is working fine now

**Comment by Jermolene** [comment]
Thanks @Lucas-C
