### ISSUE TITLE
Ctrl panel layout: Palette: Marking of selection

### ISSUE THREAD

**Issue by twMat** [Jermolene/TiddlyWiki5#1159]
Tab Appearence > Palette

Instead of dot, I suggest thin frame around selection, or perhaps contrasting background.
But if dot is kept, I suggest right-shifting all color boxes so that dot is more visible (compare with Tab Appearence >Theme) and also change color to black and make it bigger. 

[Punctuation](http://tidbits.tiddlyspace.com/#[[Unicode%20-%20punctuation]]) side-by-side overview.
.

**Comment by pmario** [comment]
you should +1 - https://github.com/Jermolene/TiddlyWiki5/pull/1954 ... which unfortunately needs more work since it wasn't merged yet.

**Comment by tobibeer** [comment]
@twMat, I updated #1954. If you would agree that it meets your needs, give it a thumbs up and perhaps consider closing this one.

**Comment by pmario** [comment]
@twMat .. I think this one can be closed. 5.1.16 got a new layout.

**Comment by twMat** [comment]
>@twMat .. I think this one can be closed. 5.1.16 got a new layout.

Sorry, I was away for a second. Sure, I'll close it right away ;-)
