### ISSUE TITLE
Ctrl panel layout: move "Toolbar Buttons"  from tab Settings to tab Appearence>Toolbars 

### ISSUE THREAD

**Issue by twMat** [Jermolene/TiddlyWiki5#1169]
Tab Settings

Move part "Toolbar Buttons" to tab Appearence > Toolbars. You decide which buttons you want and if you want them to appear as buttons or words. Reasonalbe to have that in the same place and if you're looking for "how do I change the toolbar icons into text" you have the word "toolbar" in your head as you turn to the Controlpanel to look so you're likely to find it fast if... etc.

**Comment by felixhayashi** [comment]
Good point

Should be considered here: https://github.com/Jermolene/TiddlyWiki5/issues/1689.
