### ISSUE TITLE
color picker preview showing opacity and also handling #ff0

### ISSUE THREAD

**Issue by tobibeer** [Jermolene/TiddlyWiki5#1178]
Would be nice if the preview of the edit-text color would be able to...
- preview short hex values and also named colors, e.g. `#ff0` and `red`, instead of just `#ffff00`
- preview opacity as defined via `rgba(256,256,0,0.3)`
  - even though a mostly awful system-color-picker won't support picking it

http://tb5.tiddlyspot.com/#Adding%20A%20ColorPicker%20For%20Editing%20Images

**Comment by pmario** [comment]
IMO solved with the 5.1.14 image editors?? @tobibeer

**Comment by tobibeer** [comment]
Not sure if anything actually changed. However, the browser color picker must be handled by the browser. So, closing.
