### ISSUE TITLE
Idea for importing via drag'n drop of tiddler (i.e not the link)

### ISSUE THREAD

**Issue by twMat** [Jermolene/TiddlyWiki5#1180]
If I understand things right, you can currently not import a tiddler by direct D&D instead must be its "title link".

I propose adding a small "handle", perhaps just left of the title, that is really an image with an embedded link to the current tiddler. The handle can be invisible until onhover, when an icon shows, perhaps a small handle or a link or some such (or maybe the permalink symbol?) Invisibility can be achieved by e.g an embedded image with the same color as the tiddler background (...hm, that can be treated as a parameter in an embedded image...) or a png image (png can handle transparency).

Or maybe the whole left margin - or the whole four side margin - could be such a link so you actually can just grab it, no onhover icon needed?

For this to be effective, it would have to be core because implementing it in your own TW won't help you much. Wouldn't even help others because they wouldn't find out about it.

**Comment by pmario** [comment]
@twMat ... is this still a valid issue, with all the changes in 2 1/2 years and the new d&d handling in 5.1.14?

**Comment by twMat** [comment]
@pmario - yeah.... I feel a better idea would simply be to have "titles as links" be default and will push for this instead. If anyone has opinions on that matter, I'd love to hear them [here](https://groups.google.com/forum/#!topic/tiddlywiki/d1IH79DtSXM).

- closing.
