### ISSUE TITLE
Add 'sortbylist' filter operator

### ISSUE THREAD

**Issue by tobibeer** [Jermolene/TiddlyWiki5#1184]
allow to sort by the list field, when defined, otherwise by a specified field

this is useful for recursions with mixed modes, where in one case tags can have lists with (some) tagging tiddlers listed, while other tags don't have that

**Comment by pmario** [comment]
seems to be the sortby operator: http://tiddlywiki.com/#sortby%20Operator  right?
close?

**Comment by Jermolene** [comment]
I think so, yes.
