### ISSUE TITLE
#!hashbang and disqus compatibility 

### ISSUE THREAD

**Issue by tobibeer** [Jermolene/TiddlyWiki5#1188]
Disqus provides a social feedback which, however, fails with TiddlyWiki, both five and classic. The reason: TiddlyWiki entirely runs on location hashes, thus anchors, for the outside world.

Reading this [requirements page for ajax applications](https://help.disqus.com/customer/portal/articles/472107-using-disqus-on-ajax-sites) I see that Disqus does support them so long as they use hashbang `#!`.

Now, it would be really nice, if TiddlyWiki made this one exception for URL encoding, thus providing the grounds for a disqus integration.

When decoding the location hash on startup and noticing a starting `!`, the core could test for both a tiddler by that name (for backwards compatibility) and, failing that, always remove an initial bang after the hash.

Being able to communicate around TiddlyWiki has been a pain point for a long time and, surely, not everyone likes or wants disqus... but, what other ways would you suggest right now?

**Comment by pmario** [comment]
@Jermolene ... This issue talks about disqus ... which we do not use. ... There are some open discussions at Talk, how we can improve TW links with Discourse. ... 

So we should close this one with a wontfix.

**Comment by Jermolene** [comment]
Thanks @pmario
