### ISSUE TITLE
More flexible view/edit templates (was `$:/tags/PlainText`)

### ISSUE THREAD

**Issue by tobibeer** [Jermolene/TiddlyWiki5#1189]
Allow to tag a tiddler with this system tag so as to render it in plain text. This would allow to have css and template tiddlers not be wikified but rather showing the code.

**Comment by pmario** [comment]
@Jermolene .. I think this issue can be closed. It can be resolved using the existing "cascade" mechanism.

**Comment by Jermolene** [comment]
Thanks @pmario – very satisfying to tick off these old tickets
