### ISSUE TITLE
Add "plugins" tab to "Community" tiddler

### ISSUE THREAD

**Issue by danielo515** [Jermolene/TiddlyWiki5#1190]
People ask many times where can they find plugins. There are lots of plugins developed by the community, but it is very hard to find them in the community tiddler. You have to read each description to know if you can find a plugin there. Also the categories are no intuitive to me. Having a tab for  TW sites that contains plugins will help much people.

Regards.

**Comment by danielo515** [comment]
This seems to be abandoned. I think the first step is to tag all the tiddlers referring to plugins as plugin. What do you think? @Jermolene , @twMat , @felixhayashi , @pmario ?

**Comment by felixhayashi** [comment]
I agree. tiddlywiki.com already lists plugins in the TOC but only the official plugins are tagged with plugins which creates the impression that only 8 plugins exist for tiddlywiki. Nobody looks at community resources for plugins when there is a TOC section called plugins…

**Comment by twMat** [comment]
> tag all the tiddlers referring to plugins as plugin.

+1 or some other equally intuitive tag.

Note also that @erwanm 's search aggregator (and news aggregator) [are proposed[(https://groups.google.com/d/msg/tiddlywiki/D176WyP6y-s/kEORrEIGAwAJ) to be on the tiddlywiki.com domain so maybe this should be linked in... shomehow...

**Comment by felixhayashi** [comment]
>> Hi @danielo515 I agree. I think we discussed this in Hangout 71.

> Sadly I did not see the full hangout 71

This is where annotations would be useful. @pmario stopped at hangout 70 :)) Maybe for future hangouts a shared google drive document would be an idea, where everybody can record what is said so it is not the burden of a single person to do this job…

**Comment by pmario** [comment]
Hi Felix.
I've been busy with some "non TW" stuff lately. .. I also suffered from my own laziness not annotating the hangouts. They really need to be searchable.

So I promise to release at least one new annotation today ;)

**Comment by pmario** [comment]
@danielo515 @Jermolene ... IMO can be closed: There IS a [plugins tab](https://tiddlywiki.com/#Community:Community%20%5B%5BCommunity%20Plugins%5D%5D) at the Community tiddler.

**Comment by Jermolene** [comment]
Thanks @pmario
