### ISSUE TITLE
Missing documentation for translation

### ISSUE THREAD

**Issue by gernert** [Jermolene/TiddlyWiki5#1193]
I tried to follow [1]

It says:

---

*There is a special edition of TiddlyWiki that simplifies creating and maintaining translations:*

*http://tiddlywiki.com/editions/translators/*

*Note that no knowledge of Node.js or GitHub is required.*

*See http://tiddlywiki.com/dev for technical details of creating and maintaining translations.* 

---

The first part http://tiddlywiki.com/editions/translators/ makes translating very easy. This resulted in a Dutch translation [2].

The second part (technical details) sends you to the developer documentation [3]

And although in [1] was stated "Note that no knowledge of Node.js or GitHub is required" the prerequisites for [3] are Node.js and GitHub!

I assume the translators edition is so new the documentation is not available yet. Which means that [1] must be split in two parts:

1. Translation via the translators edition
1. Translation via Node.js and Github

This brings me to a few questions about working with the translators edition:

1. How to go further with [2]? I think I can't do anything at the moment
1. How to deal with new strings to be translated? Waiting for a new release of TW (and associated translators edition)?
1. Am I right that working so (waiting for the new release) the translation will be always one release behind?

[1] http://tiddlywiki.com/#Translate%20TiddlyWiki%20into%20your%20language:[[Translate%20TiddlyWiki%20into%20your%20language]]
[2] http://tw5dutch.tiddlyspot.com/
[3] http://tiddlywiki.com/dev/#How%20to%20create%20a%20translation%20for%20TiddlyWiki:[[How%20to%20create%20a%20translation%20for%20TiddlyWiki]]

**Comment by gernert** [comment]
@Jermolene

I updated the Dutch translation for TW5.1.8

**Comment by Jermolene** [comment]
Hi @gernert thanks, I've updated the prerelease at http://tiddlywiki.com/prerelease

**Comment by gernert** [comment]
@Jermolene
Looks good to me so I think you can update the Dutch language plugin.

**Comment by gernert** [comment]
@Jermolene

I updated the Dutch translation for TW5.1.9
The update is available at http://tw5dutch.tiddlyspot.com/

**Comment by Jermolene** [comment]
Thanks @gernert, I've committed those changes:

https://github.com/Jermolene/TiddlyWiki5/commit/bc885027c3503d427752a8b7d33dd18e1611482a

I've pushed a revised prerelease to http://tiddlywiki.com/prerelease

**Comment by gernert** [comment]
@Jermolene

I updated the Dutch translation for TW5.1.10
The update is available at http://tw5dutch.tiddlyspot.com/

**Comment by Jermolene** [comment]
Hi @gernert thank you, much appreciated.

**Comment by Jermolene** [comment]
By the way @gernert I've uploaded a new preview to http://tiddlywiki.com/prerelease
