### ISSUE TITLE
TW5 and TiddlySpace / TiddlyWeb

### ISSUE THREAD

**Issue by tobibeer** [Jermolene/TiddlyWiki5#1194]
(How) does that work right now, exactly, in terms of...
- bags
- shared ownership
- syncing
- ?!?

**Comment by RichShumaker** [comment]
I have been searching for the past few days for a way to put TW5 onto a Raspberry Pi and this thread seems to be the fulcrum.  I was looking for a simple TW5 'save to server' but that is handled through TiddlyWeb which leads to this thread discussion.  I have checked out TANK and I really like what Chris has done.
I will follow this rabbit hole over to @azrael808 to see how that is going.

I understand why this is more complicated than just a simple 'save to web' feature.
If anyone has an easy way to set up TW5 on a RasPi to serve the TW5.HTML content and save the data back to the RasPi Server please let me know.

Thanks everyone.

**Comment by Jermolene** [comment]
Hi @RichShumaker 

> If anyone has an easy way to set up TW5 on a RasPi to serve the TW5.HTML content and save the data back to the RasPi Server please let me know.

If you want to save the entire standalone TW HTML file then it may be worth looking at the PHP backend:

http://tiddlywiki.com/#Saving%20on%20a%20PHP%20Server

It's quite old code, dating back to TiddlyWiki Classic, and it's not at all secure, but with those caveats it should get you up and running quickly.


> I will follow this rabbit hole over to @azrael808 to see how that is going.

Apologies, @azrael808 I'm very overdue to respond to your ticket, I'm afraid it got caught in my Christmas backlog.

**Comment by RichShumaker** [comment]
Found an old thread from April 2014 on the TW Google Groups in regards to BidiX PHP script mentioned above.  It didn't work at that point and I have posted there to see if anyone has gotten it to work.
I have switched Gears for now and I am up and running with Node.js on the Raspberry Pi with TW.
It seems that simple server side saves of HTML files will require some code I can not create at this time.  I was hoping that BidiX php script would work as that gets someone up and running in under 20 minutes.  I spent 3 hours today getting Node.js on the RasPi.  Mostly waiting time but still that is a huge time difference.  I also don't see a huge gain in Node.js yet.  I think I will soon as I found RasPi Camera Node.js stuff that I might be able to integrate and then we would have TW with RasPi camera's.
I am still hopeful to get TiddlyWeb on the RasPi once it can work with TW5 files.

**Comment by tobibeer** [comment]
@RichShumaker, when writing this not too long ago (as I just started in december)...

http://tb5.tiddlyspot.com/#Your%20own%20TiddlySpot-like%20upload%20server

...I tested it and it worked for me. Maybe you need to set some access rights for **store.php** so that it is allowed to perform the save operation (to subfolders)?

**Comment by RichShumaker** [comment]
It works!!!
I set the permissions for the folder to 777 even though that is probably
overkill and everything saved just right.
I am adding a note to the other thread I read so the next person who finds
that thread will know.

Here is an image of the page for set up in case anyone has a question about
the details needed.
The part that confused me early on was the backups autofill in with
TiddlySpot.
Should that be a github issue?

​
So at this point I can never hang out with Tobias as I own him a keg of
beer(if he drinks beer) for all his help.
Thanks again Tobias.

Rich Shumaker

**Comment by tobibeer** [comment]
Daniel Baird confirmed [in the groups](https://groups.google.com/d/msg/tiddlywiki/QcYV_AQE9YY/UqHDnU4xR74J) that `744` would probably be an ok setting for that script.

**Comment by pmario** [comment]
>It works!!! I set the permissions for the folder to 777 even though that is probably overkill and everything saved just right.

Please do not suggest to set unix permissions for PHP scripts to 777 ... its extremely dangerous!

**Comment by RichShumaker** [comment]
I have set them to 744 and it all works fine.
I won't suggest 3 7's anymore I promise Mario, and I understand the danger.
Part of this will be used by kids and I am interested in the 'issues' or 'hacks' that can occur.
Currently I have the store.php one level higher than I have the TiddlyWiki's and I need to remember how to set that as the starting point for the browser to obscure it more(not necessary now as it is me on a home network).  So has anyone hacked this set up and what are the vulnerabilities with Tiddly/Web and store.php?

Thanks again everyone for your help and warning.

Rich Shumaker

**Comment by GJRobert** [comment]
Hello there.
Now that TiddlySpace is going to be discontinued by the end of 2016. Will there be a new showcase or implementation of "TiddlyWiki 5 in the Sky for TiddlyWeb"? Thanks a lot in advance for answering this question from a "casual user"...

**Comment by pmario** [comment]
TS is gone. may be can be closed?

**Comment by tobibeer** [comment]
unfortunately so, I guess the answer is: yes

**Comment by cdent** [comment]
Even though tiddlyspace is dead, tiddlyweb is not and it would still be useful to clean up how tw5 and tiddlyweb interact. Not sure if this is the right issue for it, but wanted to be clear that tiddlyweb lives on.
