### ISSUE TITLE
extend search filter to allow [search:title:caption:foo:text[]]

### ISSUE THREAD

**Issue by tobibeer** [Jermolene/TiddlyWiki5#1195]
I have been using fields to make custom fields more structurally available, namely a **url** and **summary** field. Now I am facing difficulties searching / filtering more than one at a time.

It would be great (and I'd do it myself, if it was wanted) to be able to specify a search filter that can handle a number of fieldnames, even all, e.g.

`[search:title:caption:foo:text[]]` — fields title, caption, foo and text
`[search:$all[]]` — all fields

maybe overkill but this is also thinkable
`[search:$custom[]]` — [custom fields](http://tb5.tiddlyspot.com/#Fields%3A%20Non-Core) only
`[search:$standard[]]` — [standard fields](http://tb5.tiddlyspot.com/#Fields%3A%20Standard) only

and then...
`[search:title:tags:$custom[]]` — title and tags, and custom fields

**Comment by pmario** [comment]
@Jermolene .. IMO can be closed. The search filter was extended quite a bit. Not 100% as described in the OP, but imo close enough: https://tiddlywiki.com/#search%20Operator

**Comment by Jermolene** [comment]
Thanks @pmario
