### ISSUE TITLE
Client-server bug with long connections

### ISSUE THREAD

**Issue by Jermolene** [Jermolene/TiddlyWiki5#1196]
There appears to be a long standing bug with broken connections between the client and server, as reported by @xcazin:

> I believe it happens when network connection between node and the browser is lost for a while, so that you are not sure whether changes have been fully processed. 
> 
> In these situations, draft tiddlers actually get deleted on the server once the edited tiddler is saved, but TW5 seems to think they still exist and thus try to open them in vain on reload. Just restarting node on the same repository is enough to get everything in place again.
> 
> Sorry to not be more precise. If it still confusing, I'll try to take note more closely next time.

From https://groups.google.com/forum/#!topic/tiddlywiki/bYcHP3gyiT4

**Comment by pmario** [comment]
@Jermolene ... Is this still an issue. There have been quite some changes in the syncer since the issue was created.

**Comment by Jermolene** [comment]
Thanks @pmario – @xcazin I'll close this, but happy to re-open if it is still an issue.

**Comment by xcazin** [comment]
Thanks @Jermolene. FYI, I didn't experienced the issue anymore (I now mostly work with 5.2.0-prerelease on my node instances).
