### ISSUE TITLE
TableOfContentsMacro doesn't work with titles containing square brackets

### ISSUE THREAD

**Issue by Jermolene** [Jermolene/TiddlyWiki5#1200]
As discussed on this thread, the `<<toc>>` macro fails with tiddler titles that contain square brackets:

https://groups.google.com/d/topic/tiddlywiki/QehLCoZyNGk/discussion

**Comment by pmario** [comment]
We have a warning in place now. So probably a "wontfix" ...since we can't.

**Comment by pmario** [comment]
@Jermolene .. may be closed with wontfix

**Comment by pmario** [comment]
@Jermolene .... bump

**Comment by Jermolene** [comment]
Thanks @pmario
