### ISSUE TITLE
Are drafts supposed to behave almost independent of tiddler?

### ISSUE THREAD

**Issue by twMat** [Jermolene/TiddlyWiki5#1202]
I vaguely recall reading something about this but can't find anything now, so please forgive if old hat:

Drafts can be saved (in edit state, save doc) resulting in it becoming a tiddler of its own, parallel to the original. Until it is edit+done whereupon the original gets replaced.

**Comment by felixhayashi** [comment]
> Hi @twMat I very much like those three tabs in the edit template. They are doable with the current draft mechanism (albeit I haven't integrated a comparison engine yet).

Stumbled upon this topic and I think it makes sense to link it to this google discussion and vice versa

https://groups.google.com/d/msg/tiddlywiki/V18SC8SDNOw/moR6BNo8kCEJ

**Comment by sukima** [comment]
I would be remiss if I didn't mention this as a plugin: https://github.com/kpdecker/jsdiff

**Comment by felixhayashi** [comment]
@sukima looks really nice

**Comment by twMat** [comment]
I keep getting frustrated and confused from this double identity issue. If I'm working and I click a link to the tiddler, then I want the Draft to show up if there is one, not the original tiddler. The current behaviour is outright bad and leads to misinformation because you easily assume that what you're looking at is all there is, like for most tiddlers. What if I decide to delete it? Yes, that might open the draft (potentially causing even further confusion from weird scrolling all over the page to a draft that I did not realize was open) but it's not for sure that I realize it is an edited draft I'm now looking at before I delete it. And had I included a Delete tool in my viewmode toolbar then... yeah, whatever it is that would happen.

This current double identity behaviour is just not good.

@Jermolene indicates that my mockup, some 5 posts up, should be doable. Is it difficult? I made the mistake (I "mocked up" badly!) to include the "comparison" tab as this is not part of the actual proposition I make here.

**Comment by Jermolene** [comment]
Hi @twMat perhaps a useful fix would be to change the behaviour of the navigator widget so that navigating to a tiddler that has a draft will open the draft instead of the tiddler?

**Comment by Jermolene** [comment]
> @Jermolene indicates that my mockup, some 5 posts up, should be doable. Is it difficult? I made the mistake (I "mocked up" badly!) to include the "comparison" tab as this is not part of the actual proposition I make here.

Yes, doing it without the "comparison" tab is straightforward. I do want to integrate a library that can generate visual diffs so that we can do the comparison here and in the import dialogue.

**Comment by twMat** [comment]
@Jermolene - yes, having the navigator widget navigating to the draft instead would probably be much better. But there is also the problem with physical distance between the two which is addressed in my mockup.

**Comment by Jermolene** [comment]
Hi @twMat yes, the idea of fixing the navigator widget is a separate thing: #1710

**Comment by danielo515** [comment]
I have to admit that the draft behaviour have confused me more than once. Sometimes you save your wiki with a tiddler in draft mode,then you close it and forget about it. It's very confusing then to hit the edit button of that tiddler and navigate to a totally different place. Also is confusing to hit the edit key and end with the same tiddler opened in edit and view modes, hit save and you will end with the same tiddler opened twice. Then closing one closes both!

**Comment by Jermolene** [comment]
Hi @danielo515 I think #1710 might help a little. Another idea is that perhaps tiddlers in view mode should indicate that they have an active draft, to make it more obvious that a tiddler is already being edited.

**Comment by twMat** [comment]
@Jermolene - just so I understand; something along the idea of my illustration above, which I believe is a more user intutive display of a tiddlers states, - what makes it inappropriate to actually implement?

Regarding the physical distance between an original and a draft: That idea you've suggested to deal with the request for tiddler sections, i.e your idea to (merely) visually append tiddlers, might be useful here. IMO a draft appearing at the bottom of the original is easier to grasp, even if it includes the full toolbar, than if it is physically distanced from the original. I guess this would also be reflected in tab *Open* then.

**Comment by Jermolene** [comment]
Hi @twMat as I said above, I don't see a difficulty with adding tabs to the edit template to allow the user to switch back to consult the original version of the tiddler.

But it's dawning on me that you might mean something else: that the distinction between drafts vs. normal tiddlers be replaced with a single tiddler template with ubiquitous tabs that allow switching between edit and view modes? I'm not so sure that that is workable. For example, what would happen if switching tabs with unsaved changes?

**Comment by pmario** [comment]
>@Jermolene - just so I understand; something along the idea of my illustration above, which I believe is a more user intutive display of a tiddlers states, - what makes it inappropriate to actually implement?

@twMat I like your suggestion as an option that I can enable and disable. 

Most of the time I want to have different tiddlers, that I can open as separated tiddlers. I want to see them all at the same time. But I like your approach too, because it keeps information about tiddler state in one place. 

But as Jeremy mentioned, your mockup doesn't touch the OP problem. It's just a different edit template, that shows "Draft of tiddler" and "old tiddler" very close together.

**Comment by twMat** [comment]
>a single tiddler template with ubiquitous tabs that allow switching between edit and view modes? 

To me this is the more natural interface, yes. But, sure, if the user explicitly *wants* both then when not. For instance, there could be a there could be a "split out" for a tab into a separate tiddler (like you can split out a tab in e.g Chrome into a separate window.

>I'm not so sure that that is workable. For example, what would happen if switching tabs with unsaved changes?

Perhaps if we get tiddler versioning working?

Or, simpler (?) the Draft tab could actually be a draft of a temporary copy or the original, until Saved. The copy is not created until you start editing. Thus you can switch tabs and the temp copy/draft is still there. I guess it could disappear on close.

...and such a parallel draft that is really a temp copy, could allow the *preview* feature to be viewed parallel to either the Draft OR the original. Pretty neat actually.

**Comment by danielo515** [comment]
I think I like the idea of @twMat,

I can see this work flow on my day to day. In fact is not very different switching a tab from clicking a button to edit a tiddler. Maybe a read mode is needed to a cleaner UI

**Comment by pmario** [comment]
@danielo515 
The mockup is edit mode only.

**Comment by twMat** [comment]
>The mockup is edit mode only. 

Assuming you're referring to my illustration; I have, from the beginning, meant that these tabs should be permanently visibile both in edit mode and in viewmode (like on Wikipedia). They would replace the edit button.

-

**Comment by pmario** [comment]
hmm, why should draft be visible in view mode. you can't edit anyway.

**Comment by twMat** [comment]
No, sorry, not the tab content - only the very *tab* for opening the draft should be visible in viewmode. It could as well be a button (I don't care) it's just that a tab would then "match" the tabs appearing in editmode...

...where you have two tabs: the edit tab (with contents showing as you enter edit mode), and the tab Original. (And in each, the preview of the Draft could be accessible).

(Should I make a mockup showing the different states?)

**Comment by pmario** [comment]
imo plugin territory.

**Comment by Jermolene** [comment]
Hi @twMat as per my comment above, if you are in fact proposing a new way to handle editing that is an alternative to the existing draft mechanism then it is indeed plugin territory.

**Comment by pmario** [comment]
@Jermolene should be labeled "discussion"

**Comment by tobibeer** [comment]
@pmario: being that, wouldn't it rather make sense to close it and move to the groups @twMat ...should some aspects require more attention?

Alternatively, @twMat could possibly create more focused, individual, actionable issues that may have come up in the course of this one, should there not be such an open issues yet, and then close this one.

**Comment by pmario** [comment]
This discussion started Dec. 2014 ... When Mat wasn't the TW magician, that he is now :)

**Comment by pmario** [comment]
@twMat ... we do have the "diff-view" now. .. Not exactly the UI you suggested. But the new toolbar options provide a side-by-side view of new and old including highlighted changes. .. 

So I think this issue may be closed now.

**Comment by twMat** [comment]
@pmario While *what I mean* is still not solved - i.e the double manifestations of what is perceived to be *one* tiddler in different modes *is* confusing - I do think this thread is too unfocused and unactionable. I'll close it and might return with a better proposition.
Thanks.
