### ISSUE TITLE
Block elements inside `<p>` elements cause problems

### ISSUE THREAD

**Issue by Jermolene** [Jermolene/TiddlyWiki5#1206]
TiddlyWiki generates `<p>` tags to wrap paragraphs.

In some situations it will embed `<div>` and other block tags within the `<p>` tags. HTML strictly doesn't allow block elements within a `<p>` tag. When the browser encounters them, it automatically closes the opened paragraph tag, creating an extraneous paragraph.

The original report is here:

https://groups.google.com/d/msg/tiddlywikidev/fXv2ZFURSp0/jyHey_gldLsJ

The best solution I can see at the moment is for TW to generate `<div>` elements instead of `<p>` elements.

**Comment by buggyj** [comment]
Could this at least be put in as an option?

**Comment by Jermolene** [comment]
Hi @buggyj apologies for the late reply.

At what level would the option be controlled?

I think the best fix is for the rendering process to be prevented from performing illegal nesting, by tracking the ancestry of newly created elements.

**Comment by pmario** [comment]
@Jermolene ... tested it with current chrome on ubuntu and it seems to work fine. So still a problem?

**Comment by tobibeer** [comment]
Also not sure if there's anything actionable here unless we opt to replace any p w/ divs, which then comes with other implications.

**Comment by tobibeer** [comment]
Also not sure if there's anything actionable here unless we opt to replace any p w/ divs, which then comes with other implications.

**Comment by buggyj** [comment]
One possibility would be to have a '$p' widget, which would determine if its child widgets were of block type, if so it would insert divs instead of p elements.

**Comment by Jermolene** [comment]
I think @buggyj is correct. In fact, I think the current approach of attempting to resolve inline vs. block mode entirely at parse time has not worked well for handling nesting issues.

**Comment by kookma** [comment]
I am not sure if this problem has been addressed or the issue still there.
I am using 5.1.22 for creating static website and has a lot of extra p tags! How can I prevent generating these p tags? It seems this is an old discussion so I appreciate to let me know if it has been solved in other PRs!

**Comment by Jermolene** [comment]
Hi @kookma this is a closed issue that is more than two years old. Reactivating this issue will send notifications to all the people involved. It's usually better to start a new issue, and give us the specific set up so that we can help more easily.
