### ISSUE TITLE
~ is a valid character in an URL

### ISSUE THREAD

**Issue by tgirod** [Jermolene/TiddlyWiki5#1208]
http://webber.physik.uni-freiburg.de/~jeti/studenten_seminar/stud_sem05/bak.pdf

This link will be parsed up to ~ character. It is fairly easy to solve the problem by adding [[ ]] around the whole link, though.

**Comment by pmario** [comment]
v5.1.14 renders the whole string as expected in the OP. @tgirod .. pls close
