### ISSUE TITLE
Hiding mime-types from users

### ISSUE THREAD

**Issue by buggyj** [Jermolene/TiddlyWiki5#1217]
I think that mime-types are off putting to non technical users -  having a type called `tiddlytext-classic` is much more user friendly than `text/x-tiddlywiki` especially with type blocks i.e.

```
$$$tiddlytext-classic
.....
$$$
```

maybe there could be a translations (ie store the mime-type in the tiddler but display as a user friendly name)

**Comment by pmario** [comment]
@Jermolene .. should be labeled: "improvement" or "feature request"

**Comment by buggyj** [comment]
`$tw.utils.registerFileType("text/x-tiddlywiki","utf8",".classic");`

this should probably go in the boot

**Comment by pmario** [comment]
>$tw.utils.registerFileType("text/x-tiddlywiki","utf8",".classic");

but `.classic` would then be used as a file extension if used together with: http://tiddlywiki.com/#Customising%20Tiddler%20File%20Naming .. So that's not what we want.

**Comment by pmario** [comment]
@Jermolene ..  I think this one can be closed. 

It is a long standing issue and has not caused "support" problems with users. .. Aliasing as discussed using the `.classic` file extension has never been implemented and it shouldn't (see my last comment).

Imo aliasing causes additional complexity so the issue should be closed with a non fix. 

There are a lot of threads at Talk-Tiddlywiki which discuss hiding different elements of the UI in view and edit mode see: https://talk.tiddlywiki.org/search?q=hiding

**Comment by Jermolene** [comment]
Thanks @pmario
