### ISSUE TITLE
Change alert for when cancelling import

### ISSUE THREAD

**Issue by twMat** [Jermolene/TiddlyWiki5#1219]
[ Do you wish to delete the tiddler "$:/Import"? ]

"_Delete!?_ No, I just want to cancel! Ooow I probably ruined the whole TW importing mechanism now?"

quote from Winston Churchill, circa 1939.

**Comment by Spangenhelm** [comment]
:+1: This may be one year old but still a valid point imo but i am wondering if the fix is as easy as we might think!

**Comment by Jermolene** [comment]
It's not as simple as adding `<$action-deletetiddler>` widgets to `$:/core/ui/ViewTemplate/import` because we also need to remove the `$:/Import` tiddler from the story.

**Comment by tobibeer** [comment]
@Jermolene, can messages be given more than one parameter and how? If so, then `tm-delete-tiddler` needs an additional parameter called `silent`.

**Comment by Jermolene** [comment]
@tobibeer yes I think that would be the best solution

**Comment by Jermolene** [comment]
> can messages be given more than one parameter and how

Have a look at the existing messages that use more than one parameter.

**Comment by tobibeer** [comment]
At second thought, I think we just need to use two widgets in the button.

* `<$action-deletetiddler>`
* `<$action-sendmessage message="tm-close-tiddler">`

**Comment by twMat** [comment]
No, wait - isn't it simply to rephrase the alert? What I was/am reacting to ths the word "delete". It should just say "cancel";

[ Do you wish to cancel the tiddler "$:/Import"? ]

**Comment by tobibeer** [comment]
There is no canceling a tiddler. As for deleting the import tiddler, I think it actually makes sense to ask the user, because it does serve as a "last imported" log.

**Comment by twMat** [comment]
Sorry, I misphrased. I mean it should alert;

[Do you wish to cancel the importing?]

if it is important to inform that this also deletes $:/Import then this could be elaborated on under a [more info >] reveal button. For me, and I'd guess most simple end users, it is mostly a matter of proceeding with the importing or not.

**Comment by Jermolene** [comment]
The reason for the wording being "delete" is that we literally delete the `$:/Import` tiddler in order to cancel the import. I think it's both more usable and easier to implement to remove the confirmation rather than to rephrase the confirmation.

**Comment by twMat** [comment]
> I think it's both more usable and easier to implement to remove the confirmation

+1

**Comment by pmario** [comment]
@Jermolene .. imo should be labeled "improvement"

**Comment by tobibeer** [comment]
Played around a bit on tiddlywiki.com and made a quick edit right here on github + pull request: #3031

**Comment by twMat** [comment]
@pmario - thanks for resolving this.
Closing.
