### ISSUE TITLE
Unsaved fields should save on done, or alert

### ISSUE THREAD

**Issue by twMat** [Jermolene/TiddlyWiki5#1220]
What the title says. I'm currently converting one of my main TWCs to TW5 and -g'dang- I find myself forgetting to save the fields time and time again. I think the reason is because in all other fields, you just type and leave the field "open" - and then click Done.

**Comment by felixhayashi** [comment]
Hi @twMat, isn't this fixed in 5.1.10 now?

**Comment by twMat** [comment]
@felixhayashi - you're right! Good catch a year later, or maybe just an amazing memory :-)

Closing.

**Comment by felixhayashi** [comment]
> or maybe just an amazing memory :-)

@twMat – Ehem, yes! … Ok, admittedly, I actually found this by accident :)
