### ISSUE TITLE
Tab switch causes screen jump

### ISSUE THREAD

**Issue by twMat** [Jermolene/TiddlyWiki5#1225]
[For the record. Save for a rainy day.]

Go to tw.com with it's current default display of a few tiddlers one of the lower ones, currently Community, containing tabs.

In tab Open, click Community (for the sake of this demo, don't scroll). In tiddler Community click on tab Articles. Keep your eyes on the screen and... click on tab Meetups.

It's a matrix switch twitch! ;-)

Maybe tab switching (in river column) should cause animated scroll?

Related: Opening a tab where the content goes below browser edge should probably scroll the tiddler so it's upper edge meets browser edge like when you open the tiddler itself from e.g sidebar.

**Comment by pmario** [comment]
@Jermolene ... imo should be labeled "improvement" or "cantfix" since the behavior is defined by the browser

**Comment by tobibeer** [comment]
@pmario / @Jermolene  This smells cantfix, since we surely won't reserve blank space for a tiddler (even if we could), because some as of yet non-active tab has more content to show only to avoid scrolling.

Otherwise, the question might be, can we afford / implement a more smoth transitioning effect to unfold / fold additional contents that grow beyond or below the current height?

**Comment by pmario** [comment]
IMO can be solved if we use 

```
.tc-tab-content {
  min-height: 100vh;
}
```

Or something similar.

**Comment by tobibeer** [comment]
@pmario: try that out on TiddlyWiki.com and scroll down to the first tabset. It doesn't help at all with the jumpiness.

**Comment by pmario** [comment]
I did test it. ... It does exactly what it's supposed to do. It adds enough space to the bottom of short tabs, so the page doesn't need to scroll. ... 

If that's too much whitespace for the user, we would need to fill it with a nice default background image or some random text like: "By the way: You look great today !"

**Comment by tobibeer** [comment]
Ok, but i you also notice the vast blank below GettingStarted?

I guess, my point was to shift focus away from differences in height to... transitioning from one to the other.

**Comment by twMat** [comment]
Seems to be solved. Closing.
