### ISSUE TITLE
Renaming the filename for the empty-wiki download

### ISSUE THREAD

**Issue by Drakor** [Jermolene/TiddlyWiki5#1234]
Hi,

following the discussions [on the google groups](https://groups.google.com/forum/#!searchin/tiddlywiki/empty/tiddlywiki/pHp2RoHYHmU/73AIiRsg-PsJ) (and [here](https://groups.google.com/forum/#!searchin/tiddlywiki/New$20User$20Experiment/tiddlywiki/rDRWHh9r6TA/v9IC6pNa7U0J)) as well as in #1231 and on hangout no.72, people seem to agree that new users downloading the empty wiki from the `GettingStarted` tiddler should not be confronted with a cryptic filename. 
Therefore I suggest changing it to `tiddlywiki-<<VERSION>>-empty.html` as that makes the file easily findable in any folder and indicates the version of the wiki. (I certainly have more than one version of TW in my download folder.)

I will also make a pull request in a little while.

/Andreas

EDIT: I also wanted to be the author of issue 1234 =)

**Comment by pmario** [comment]
@Drakor ... is this still valid, since the related PR  has been closed?

**Comment by tobibeer** [comment]
ping @Drakor

**Comment by pmario** [comment]
A long time ago, we used to have browser created random names, which imo caused that issue.

I think this one can be closed since users can use any name, if the filename param is set: https://tiddlywiki.com/#%24%3A%2Feditions%2Ftw5.com%2Fsnippets%2Fdownload-empty-button

**Comment by Drakor** [comment]
Yes, it seems you are correct. Thanks!
