### ISSUE TITLE
Images nomenclature

### ISSUE THREAD

**Issue by giffmex** [Jermolene/TiddlyWiki5#1246]
Two proposals for documentation:
1. External images

I would like to suggest that the term 'external images' be renamed to 'external image tiddlers', and use the phrase 'external image' only to refer to the image file itself that is being referenced by the external image tiddler.

Justification: For new users and even for some of us who have been around a while, it is difficult to remember that 'external image' does not refer to an image at all, but a tiddler. The clarity and simplicity gained from adding the extra word makes it worth it.
1. I would also like to propose that a new term be found for the term 'embedded images.' Everywhere else on the web, embedded images are images that are found elsewhere but viewable in the present webpage via an img link. But in TiddlyWiki we find the exact opposite: what the rest of the world calls embedded images don't even really have a name in the TiddlyWiki documentation, except maybe 'images in wikitext'. And what TiddlyWiki calls embedded images are images baked into the file itself.

I would agree that the term 'embedded' makes more sense for an image baked into the file itself. To embed something assumes the thing is actually there, embedded into something else. So what everyone else calls embedded images are not really embedded in webpages but referenced and accessed by them. Nevertheless, this terminology is well established, and TiddlyWiki's is not. So it makes better sense to change TiddlyWiki's term for something that doesn't confuse the user.

I am not sure what term could be used. Here are some possibilities: pasted images? inscribed images? installed images? internal images? 

I am sorry I have not been able to be more involved in the TiddlyWiki community with hangouts, documentation and discussion at the Google group. And given my new job responsibilities since September and the illnesses (not severe, but tiring) that myself and my wife and daughter have been going through I doubt that is going to change much. So please don't perceive this issue as piling more work on those of you who are doing the work, and not being willing to chip in. I see the suggestions above as one important way of chipping in, and hope these suggestions are helpful rather than distracting from the task of perfecting TW documentation. Blessings.

**Comment by pmario** [comment]
@Jermolene ... I'm not sure if any of this happened. IMO should be labeled "improvement"

**Comment by tobibeer** [comment]
@giffmex confident to make the edits + pull request?

**Comment by giffmex** [comment]
No, I never really wanted to use GitHub for more than making suggestions. I
have been out of even that for a long time - this is a three year old
suggestion. Sorry!

David Gifford
Mexico team leader, Mexico City

*Resonate Global Mission*
*Engaging People. Embracing Christ.*
A Ministry of the Christian Reformed Church
resonateglobalmission.org

**Comment by tobibeer** [comment]
You really just need to edit it on TiddlyWiki.com until you're happy with the edits and then click the link to make a suggestion from the info panel. There is not much more to it, at all.

**Comment by giffmex** [comment]
ah, ok. I will see if I can get to that in a couple weeks.

David Gifford
Mexico team leader, Mexico City

*Resonate Global Mission*
*Engaging People. Embracing Christ.*
A Ministry of the Christian Reformed Church
resonateglobalmission.org
