### ISSUE TITLE
wrong parameter order may overwrite template tiddler with state

### ISSUE THREAD

**Issue by tobibeer** [Jermolene/TiddlyWiki5#1252]
Not sure how to tackle this problem: I just accidentally ommited a macro parameter and the result was that overwriting the contents in that input field pretty much overwrote what supposedly was a template. :D

One way to avoid this could be to instruct users on always using named parameters when there's a template involved.

**Comment by pmario** [comment]
@tobibeer ... I know, that this is still valid, but not actionable and using named params works. imo pls close

**Comment by tobibeer** [comment]
@pmario: I guess the actionable bit would be to extend the docs... and so I did #3022.

Closing this one in favor of the PR:
