### ISSUE TITLE
Escape pressed twice quickly causes a JS error

### ISSUE THREAD

**Issue by aelocson** [Jermolene/TiddlyWiki5#1266]
With a tiddler in edit mode, if you press the Escape key twice in quick succession (i.e. press it a second time before the UI has fully caught up with the first press), you get an unhandled TypeError ("draftTiddler is undefined").

I can reliably reproduce this in Firefox, Chrome and IE on Windows, and in Firefox on Ubuntu.

**Comment by tobibeer** [comment]
same here ...fixed, thanks
