### ISSUE TITLE
Edit tiddler at cursor position

### ISSUE THREAD

**Issue by mardukbp** [Jermolene/TiddlyWiki5#1284]
Whenever I want to edit a long tiddler at a certain position I have to scroll up in order to click the edit button and then scroll down to where I was. In [MoinMoin](http://moinmo.in/) it is possible to double-click where you want to edit the text. This would be a great improvement for TiddlyWiki.

**Comment by mardukbp** [comment]
I [found](http://sheep.art.pl/Textarea%20Scrolling#72) the JavaScript code that implements the functionality that I want in MoinMoin. It is very well explained. Hopefully it will be easy to integrate with TiddlyWiki.

**Comment by twMat** [comment]
>I found the JavaScript code that ...

Now that is very interesting! I am working on something else where this might just be a key component. Soon to be revealed ;-) Thank you for posting it markdukbp

**Comment by tobibeer** [comment]
This sure would be real nifty and a big productivity gain.

Unfortunately it ain't easy, at all. The problem alone with identifying where a user actually clicked ain't exactly trivial, requiring core-changes ...just in case someone wanted to try and create a plugin.

For example, a widget in TiddlyWiki being rendered would need to know...

* that it is rendered inside a widget that has click-edit functionality
    * so the transclude widget needs extension in that it can be made "editable", either implicitly or explicitly linked with a given field of a certain tiddler
* the line in the source of the tiddler('s text) that it is being called to render
    * so the parser would need to tell that to the widget which then stores that information adequately to the rendered DOM element so that later on we can process that information to open the editor at the right line
    * obviously, so long as all other fields are one-liners, that part is trivial for something like the title
        * so implementing click-editing for the title alone could be a good start to explore this functionality

In a tiddler in the story alone, there can be (conditional) viewtemplate sections that get rendered into the tiddler, but don't correspond to the tiddler's tiddler body / text field, but perhaps only to a field, or not even any of the tiddler's fields at all.

It can sure be done. Unfortunately, easy ain't exactly the word I'd use when it comes to implementing this functionality. Copy and paste from MoinMoin will only yield non-executable code over here.

**Comment by pmario** [comment]
@mardukbp 
see: http://tiddlywiki.com/prerelease/editions/text-slicer/  Is this an option for you? It's the "tiddlywiki way" to deal with long tiddlers.

**Comment by tobibeer** [comment]
@pmario one thing has little to do with the other, so let's try and keep things separate.

**Comment by pmario** [comment]
I think it's impossible to implement the desired behaviour. We have had this request for TWc several times already and nobody implemented it. The rendered text representation has absolutely nothing to do with the wikitext that produces it. ... at least not at the moment. 

eg: if you have a list widget that transcludes several tiddlers. Positioning the cursor is impossible. But the slicer works just fine for this usecase.

**Comment by tobibeer** [comment]
> The rendered text representation has absolutely nothing to do with the wikitext that produces it. ... at least not at the moment.

Not true with the above knowledge over line numbers.

> ...at least not at the moment.

That's more like it. So, if anyone wanted to make this a plugin, it would mean that this crucial information be provided by the core appropriately, otherwise such a plugin would have to hack / overwrite it... if there ever was someone to create it.

> But the slicer works just fine for this usecase.

How does the slicer help with editing the right content at the right place? => seems a different issue.

**Comment by pmario** [comment]
>How does the slicer help with editing the right content at the right place? => seems a different issue.

 - go to: http://tiddlywiki.com/prerelease/editions/text-slicer/#Sample%20Text  
 - slice the tiddler ... on the left there will be an outline
 - the outline has clickable elements. 
 - You can edit every element as a tiddler now. 

The UI needs some improvements, but the functionality is there.

**Comment by tobibeer** [comment]
But it is a totally different thing. I don't want to slice. I just want to edit.

**Comment by twMat** [comment]
How about an alternative approach:

Add "edit anchors", perhaps manifested as editbuttons appearing on hover in the tiddler view mode margin, that when clicked opens edit and scrolls to the added position. These could actually be inserted automatically following some "rules" such as at beginning of every...;

* paragraph (and perhaps additional anchors every X characters)
* list widget
* text transclusion

Manual anchors could perhaps also be inserted. 

Regarding longer tiddlers; I often find my tiddlers to be longer than my laptop screen but it would  typically not be justified to use someting like text-slicer.

**Comment by mardukbp** [comment]
+1 for "edit anchors" at section headers. Slicing a tiddler is not always desirable.

**Comment by tobibeer** [comment]
> Add "edit anchors", perhaps manifested as editbuttons appearing on hover in the tiddler view mode margin, that when clicked opens edit and scrolls to the added position.

That would even be more visual and would help those who want visual indicators. Technically, however, it is requires very much the same code-base as the OP.

**Comment by Jermolene** [comment]
Hi @twMat I think you are describing the text-slicer functionality: think of the mechanism for introducing the anchors being the process of slicing the text into individual chunks.

**Comment by pmario** [comment]
@Jermolene .. imo should be labeled "feature request"

**Comment by twMat** [comment]
Note: The OP would be almost solved if #1267 was implemented, i.e where the editor text "scrolls along with" the preview text.

**Comment by rmunn** [comment]
With the [event catcher widget](https://tiddlywiki.com/#EventCatcherWidget) it's be possible to do this now:

```plaintext
\define dblclickactions()
<$action-sendmessage $message="tm-edit-tiddler" $param=<<storyTiddler>> />
\end

<$eventcatcher selector="*" $dblclick=<<dblclickactions>> tag="div">

Body of tiddler goes here

</$eventcatcher>
```

You could even edit the `$:/core/ui/ViewTemplate/body/default` tiddler and wrap it in an `$eventcatcher` widget similar to the above, and that would work for every tiddler in your wiki. I've tested this in version 5.3.2-preview and it works.

**Comment by mardukbp** [comment]
Awesome! Thanks for the follow-up after so many years!
