### ISSUE TITLE
Sidebar, horizontal scroll: wrap instead

### ISSUE THREAD

**Issue by twMat** [Jermolene/TiddlyWiki5#1286]
[OP edited to make more actionable.]

The side menu lists shows horizontal scrollbars when (even a single) tiddler title is longer than the sidebar is wide. This is not elegant.

I propose this CSS is the default for the sidebar lists, or even lists in general:

```
.hyphenate {
  overflow-wrap: break-word;
  word-wrap: break-word;
  -webkit-hyphens: auto;
  -ms-hyphens: auto;
  -moz-hyphens: auto;
  hyphens: auto;
}
```

[The article](https://justmarkup.com/log/2015/07/dealing-with-long-words-in-css/) where I found this concludes this as a perfect solution (see end of article) and states;

> This solution will show hyphens for every browser supporting it and will break lines in every other browser – perfect. ... [tested] in 26 different browsers [...]

**Comment by twMat** [comment]
Note updated OP and that @Jermolene 's reply is thus not quite relevant.

However, regarding;
>Rather than making this be yet another configuration option, I'd prefer to see it as a plugin. 

I understand why it should not be a configuration. Given the clean solution in the OP (and that the current behaviour is not good) I do think it should be implemented in standard distro rather than as a plugin.

**Comment by pmario** [comment]
I think, this is very much personal taste. ... I didn't even recognise the bottom scroll bar. For me it's out of sight most of the time. I need to scroll down to see it. 

I personally would prefer to get a title text in one line with 'ellipsis' at the end eg: "This is a lo..." __and__ if I hover the title I want the tooltip to show the whole text. ... 

I think multi line tiddler titles in the sidebar are not elegant :) ... So as I said. ... personal taste.

**Comment by twMat** [comment]
> title text in one line with 'ellipsis' ...

Sure. The point is only to have a better solution than the current which results in the inelegant horizontal scroll.

**Comment by pmario** [comment]
Yea. The problem for me is. The bar is ugly, but at least useful. Everything else is degrading the functionality. ... As I wrote personal taste.

**Comment by pmario** [comment]
@Jermolene .. imo should be labeled "improvement"

**Comment by pmario** [comment]
@Jermolene .. imo should be labeled "improvement"

**Comment by twMat** [comment]
Yes, please label "improvement".

Further, given the opinionated nature of the OP and that Jeremy explicitly dismisses this, I'm OK with closing this. (Note: that's reasoning only concerns this particular issue ;-)
