### ISSUE TITLE
CSS ids are understood as list with text/vnd.tiddlywiki

### ISSUE THREAD

**Issue by felixhayashi** [Jermolene/TiddlyWiki5#1288]
Hi @Jermolene,

*this is not really important, I just want to create awareness on this. as it created a hard-to-find-bug for me*

> CSS ids are understood as list with text/vnd.tiddlywiki

Yes of course, this is obvious, usually, but here is the problem:

The only way to include images in a tw-wiki css file is to compile the images into base64. However, if I want to use existing tw images (included in the wiki) I cannot precompile the css but instead have to use the `makedatauri` macro. Something like this:

    .network-frame {
      .taskgraph-button { 
        &.surface.enabled {
          bottom: 90px;
          right: 15px;
          background-image: url(unquote('<$macrocall $name="makedatauri" type="image/png" text={{$:/plugins/felixhayashi/taskgraph/media/surface.png}} />'));
        }
      }
    }

The macro only works with the tiddler type being `text/vnd.tiddlywiki` instead of `text/css`.

Now at that point, I cannot use ids anymore for unique elements in my css file for e.g. `#footer`, `#sideInfo`.

A workaround is to only work with classes. or use ids with a prefix like `/**/#`.

Regards
Felix

**Comment by tobibeer** [comment]
> Anyways this is solved for me now. thanks

Good, so you can close this issue.

> I create styles with SASS and the parser wouldn't like this. 

Any pointers on what exactly you're implementing and how? Would be interesting to learn a little about that (in the context of TiddlyWiki).

**Comment by felixhayashi** [comment]
> Any pointers on what exactly you're implementing and how? Would be interesting to learn a little about that (in the context of TiddlyWiki).

Just building a website with tiddlywiki, nothing special. It's just that my workflow is to compile sass (http://sass-lang.com/) into css. I can post the website later in february as tiddlywiki showcase.

**Comment by tobibeer** [comment]
So, you have some external application that turns your sass files into tiddlywiki stylesheets which you then import ...or simply overwrite. Correct?

**Comment by felixhayashi** [comment]
Hi @tobibeer,

yes correct, I use a taskrunner called gulp and the code for the part we are talking about is:

    gulp.task("compile", ["clean"], function () {

      // ...
        
      // compile styles
      gulp.src("plugins/**/*.scss")
        .pipe(sass({ style: "expanded" }))
        .pipe(gulp.dest("../dist/"));
        
      // ...
        
    });

**Comment by tobibeer** [comment]
Wow, there's some concise processing going on, interesting. Should delve more into all the node magick. Are you using that mildly outdated node.js port called node-sass, rather than the ruby gem?

**Comment by felixhayashi** [comment]
nope I am using the ruby package
