### ISSUE TITLE
"New here" button doesn't work in edit mode

### ISSUE THREAD

**Issue by twMat** [Jermolene/TiddlyWiki5#1295]
In trying to keep tiddlers small it's important to be able to split them into new tiddlers, also from edit mode. For this reason I've included the "New here" button in edit toolbar. However, this creates the tag *"Draft of '...' "*. I propose the tag created should be with the tiddler title, not the draft title.

Even if I haven't tried it, I'm guessing it would be the same problem with "New Journal" and maybe Export tiddler and other tools.

**Comment by Jermolene** [comment]
Hi @twMat as things stand, we'll need a slightly different instance of the "new here" button for use in edit templates. Something like this:

```
title: $:/core/ui/Buttons/new-here-edit-mode
tags: $:/tags/EditToolbar
caption: {{$:/core/images/new-here-button}} {{$:/language/Buttons/NewHere/Caption}}
description: {{$:/language/Buttons/NewHere/Hint}}

\define newHereButtonTags()
[[$(actualTiddler)$]]
\end

\define newHereButton()
<$set name="actualTiddler" value={{!!draft.of}}>
<$button tooltip={{$:/language/Buttons/NewHere/Hint}} aria-label={{$:/language/Buttons/NewHere/Caption}} class=<<tv-config-toolbar-class>>>
<$action-sendmessage $message="tm-new-tiddler" tags=<<newHereButtonTags>>/>
<$list filter="[<tv-config-toolbar-icons>prefix[yes]]">
{{$:/core/images/new-here-button}}
</$list>
<$list filter="[<tv-config-toolbar-text>prefix[yes]]">
<span class="tc-btn-text"><$text text={{$:/language/Buttons/NewHere/Caption}}/></span>
</$list>
</$button>
</$set>
\end
<<newHereButton>>
```

**Comment by twMat** [comment]
Wonderful, it works great! Thank you Jeremy!

**Comment by tobibeer** [comment]
Hi Mat, can this be closed?

**Comment by twMat** [comment]
Good point, thank you. I will do so now, assuming the button "Close and comment" does this. Otherwise @Jermolene can please do so.
