### ISSUE TITLE
File names are case-insensitive on Windows

### ISSUE THREAD

**Issue by dullroar** [Jermolene/TiddlyWiki5#1303]
TW will alllow you to create both a *Foo* tiddler and a *foo* tiddler, but if you're running under node on Windows, whichever one is saved last will be the sole contents of the single *foo.tid* file.

After discussion it was agreed TW should not allow this behavior in the first place. If you create a tiddler *Foo* and then try and create a second tiddler *Foo*, you will get a popup asking if you want to overwrite *Foo*. However, if you create *Foo* and then create *foo*, it will allow that, and silently overwrite the underlying *Foo.tid* file. Instead, it should give the same overwrite popup.

**Comment by Jermolene** [comment]
I think this can be fixed by changing `generateTiddlerFilename()` in https://github.com/Jermolene/TiddlyWiki5/blob/master/plugins/tiddlywiki/filesystem/filesystemadaptor.js so that it uses a case-insensitive check for clashes with existing filenames.

**Comment by pmario** [comment]
hmmm. 
TW should be case sensitive with tiddler names. Since the tiddler name is the only unique ID the core uses. Limiting the ID range imo isn't good.

**Comment by Jermolene** [comment]
@pmario this is about the way that the file system adaptor generates filenames from tiddler titles. The approach taken at the moment is incompatible with case-insensitive file systems. The proposed fix doesn't affect the behaviour of tiddler titles.

**Comment by dullroar** [comment]
@pmario, while I agree with your sentiment the real problem is ***data loss*** occurs if you are running TW under node on Windows and use two (or more) tiddlers named the same but differing only by case. In fact, *Foo, foo, fOO, fOo, FoO*, etc., would all save down to a single *foo.tid* file, with last save winning.

**Comment by dullroar** [comment]
@Jermolene, it looks like there was already an attempt to Do The Right Thing in `generateTiddlerFilename()` that fails because it relies on Javascript's `indexOf`, which of course is case-sensitive. Since I found the problem and have a Windows environment, I will take a stab at fixing it and generate a pull request.

**Comment by pmario** [comment]
>In fact, Foo, foo, fOO, fOo, FoO, etc., would all save down to a single foo.tid file, with last save winning.

yes, right. But the fix imo needs to be in the "filesystemadaptor.js" as Jeremy proposed.

**Comment by dullroar** [comment]
@pmario, I agree and am working on the fix even as I type this. :)

**Comment by pmario** [comment]
@dullroar There seems to be a commit, but no pull request. Is this still an issue?

**Comment by dullroar** [comment]
It was closed by pull request #1311.
