### ISSUE TITLE
Bug in generateTiddlerFilename

### ISSUE THREAD

**Issue by dullroar** [Jermolene/TiddlyWiki5#1304]
Consider the following code:
```javascript
FileSystemAdaptor.prototype.generateTiddlerFilename = function(title,extension,existingFilenames) {
	// First remove any of the characters that are illegal in Windows filenames
	var baseFilename = title.replace(/<|>|\:|\"|\/|\\|\||\?|\*|\^|\s/g,"_");
	// Truncate the filename if it is too long
	if(baseFilename.length > 200) {
		baseFilename = baseFilename.substr(0,200) + extension;
	}
	// Start with the base filename plus the extension
	var filename = transliterate(baseFilename) + extension,
		count = 1;
```
Notice that `extension` is added if the `baseFilename` length is more than 200 characters, but notice it is then added again unconditionally when initializing `filename`. I have confirmed that saving a tiddler under node with a tiddler name length > 200 characters results in a file name with a duplicate ".tid.tid" extension being saved. Expect a pull request with the fix.

**Comment by Jermolene** [comment]
Thanks @dullroar
