### ISSUE TITLE
global template for tiddler links

### ISSUE THREAD

**Issue by tobibeer** [Jermolene/TiddlyWiki5#1318]
Implement a unified, standard, generic template that defines how a link to a tiddler is rendered, not a number of macros implementing their own version of that code...

```
title: $:/core/ui/LinkTemplate

<$link to={{!!title}}>
<$view field="title"/>
</$link>
```

macros and templates would thus use...

```
{{||$:/core/ui/LinkTemplate}}
```

This will allow to globally enhance / modify / overwrite all link instances rather than modifying a number of separate macros and templates, e.g. so as to display a **caption**, **short**, **acronym** or **nice title** when rendering a link rather than the underlying full, perhaps cryptic, if not id-like title that may be required for uniqueness.

This could also be handy for translated editions of tw.com where the links should perhaps show localized titles rather than the underlying defaults from tw.com, in addition to also showing custom titles, of course.

**Comment by Jermolene** [comment]
Thanks @tobibeer interesting idea.

Are you imagining that one would be able to modify this template in order to automatically modify all the displayed links? In other words, is this a template that is used by the link widget to generate it's output, or it this a template that we'd use for things like the sidebars?

**Comment by tobibeer** [comment]
> Are you imagining that one would be able to modify this template in order to automatically modify all the displayed links?

Yes, which makes it one to handle with a bit of care, perhaps not overloading it all too exessively. ^^

> In other words, is this a template that is used by the link widget to generate it's output, or it this a template that we'd use for things like the sidebars?

Yes, the link widget sounds like a good starting point and then perhaps checking on other macros and templates as to whether or not this template should be used like...

`{{||$:/core/ui/LinkTemplate}}`

**Comment by Jermolene** [comment]
>> Are you imagining that one would be able to modify this template in order to automatically modify all the displayed links?
> Yes, which makes it one to handle with a bit of care, perhaps not overloading it all too exessively. ^^

The trouble here is that there's a recursion if the template that the list widget uses itself includes an invocation of the list widget.

Also, the list widget has child widgets; would they no longer be rendered if a template was defined?

> Yes, the link widget sounds like a good starting point and then perhaps checking on other macros and templates as to whether or not this template should be used like...

Those are two mutually exclusive options. Are you proposing that the link widget be templatable, or that we use a template to render our links?

**Comment by tobibeer** [comment]
> The trouble here is that there's a recursion if the template that the list widget uses itself includes an invocation of the list widget.

We're not talking about recursively calling the same list-widget instances, though, are we? If that would happen, the user should see the resursion warning indicating that he messed up that template.

> Also, the list widget has child widgets; would they no longer be rendered if a template was defined?

Not following. Where / How does this affect (children of) the list widget?

> Are you proposing that the link widget be templatable, or that we use a template to render our links?

The latter, I think. I want to be able to interfere before a link even gets rendered. However, I now notice that I didn't even touch the link widget when trying to put a flag icon for a tiddler's language in front of links to it. What I did was modifying the templates that implement the link widget... but now I see I never touched things on a widget level, only those templates rendering various lists. So, if you wish, I was one level up the widget tree.

At second thought, I'm not sure I'm even asking for going all the way to link widget level, precisely because those lists seem to implement their variants anyway, even though the output is mostly the same.

I think I'll have to do some experimenting at what makes sense and whether or not this would actually mean one template or perhaps two (or more ?).

**Comment by pmario** [comment]
@tobibeer ... did you do "some more experimenting" .. Is the issue still valid?

**Comment by tobibeer** [comment]
@pmario: Issue still valid, though no experimenting yet. Will close for now, since I sparked the idea and noone else yet had a "me too" moment. I'll possibly experiment extending the LinkWidget at some point combined w/ a global variable for the template, so it can be overruled in a given context w/o needing to touch the LinkWidget itself or specify parameters for individual instances.

**Comment by pmario** [comment]
I did create a "uni-link" plugin https://wikilabs.github.io/editions/uni-link/ that was inspired by this discussion https://groups.google.com/d/msg/tiddlywiki/Z7dRU3HrzSs/N2H7bgwlAQAJ 

IMO it seems to be very close to your proposal. ... 

It implements an uni-link widget and an uni-link macro. It modifies the "prettylink" parser in a 100% backwards compatible way. .. So If "new content" imported into a TW that doesn't have the plugin installed, it still works. ...

**Comment by pmario** [comment]
Prettylinks show `subtitle, caption, title` but if the macro is modified users can pretty much do what they want.

**Comment by tobibeer** [comment]
> uni-link

Will take a look, but I think it's more of a workaround than a core extension. Basically, what I would want to do is define my own template for how internal links get rendered. Your uni-link appears to implement a specific variant. However, I want the flexibility to have the user define their variant for rendering internal links, possibly external links as well.

**Comment by pmario** [comment]
>Your uni-link appears to implement a specific variant

uni-link widget, calls the macro, that you can modify. ... And it takes care that links used that way show up in the "References" tab, which is the main reason, why a widget is needed. 

You can change the macro at your will.

**Comment by tobibeer** [comment]
Ha! Ok... I better take a closer look then. Thanks.
