### ISSUE TITLE
filter all tiddlers with tags that in turn tag to a common parent tag

### ISSUE THREAD

**Issue by tobibeer** [Jermolene/TiddlyWiki5#1325]
somewhat related to #1324 (semantic tagging)

**situation**

imagine various tiddlers tagging to different author tiddlers which in turn tag to an **Authors** tiddler

**problem**

get a list of all tiddlers that have an author-tag assigned (those that tag to **Authors**) and sort the list by whichever criterion, e.g. to output a flat list of all "articles" in the **Authors** tiddler (yet not as a nested list!)

**Comment by Jermolene** [comment]
Hi @tobibeer I'm not sure what you're asking for here - do you want help coming up with a filter to do this?

**Comment by tobibeer** [comment]
Yes, a filter sounded like the right candidate to handle the requirement.
Thinking of it some more, the solution actually appears to be as simple as...

`[tag[Authors]tagging[]sort[title]]`

One question that remains is how I could possibly figure out in a **ListItemTemplate** which author tag(s) are assigned to the tiddler.

```
<dl>
<$list filter="[tag[Authors]tagging[]]"/>
<dt>
<!-- how to get those tags tagging to Authors?!? -->
<$list filter="?!?"/>
<$link to=<<currentTiddler>>><$view field=title/></$link>
</$list>
</dt>
<dd>
<$link to=<<currentTiddler>>><$view field=title/></$link>
</dd>
</$list>
</dl>
```

**Comment by Jermolene** [comment]
Hi @tobibeer 

> One question that remains is how I could possibly figure out in a ListItemTemplate which author tag(s) are assigned to the tiddler.

untested, but perhaps something like this:

```
<dl>
<$list filter="[[Authors]tagging[]]" variable="author"/>
<dt>
<$list filter="[<currentTiddler>tag<author>]" variable="author"/>
<$link to=<<author>>><$view tiddler=<<author>> field=title/></$link>
</$list>
</dt>
<dd>
<$link to=<<currentTiddler>>><$view field=title/></$link>
</dd>
</$list>
</dl>
```

**Comment by tobibeer** [comment]
that doesn't work, because the outer list actually iterates "articles", not authors

**Comment by tobibeer** [comment]
that brings me back to the initial problem that I don't get an overall list of "articles" that I can sort by, say, modified... but instead nested lists grouped by author

**Comment by tobibeer** [comment]
Ok, I've figured it out...

**demo**: [list category items with categories @ filters](http://filters.tiddlyspot.com/#list%20category%20items%20with%20categories)

Below, the outer list gathers all items, e.g. publications, tagging to any tiddler tagged **Authors** sorted by title. The inner list then loops all **Authors** associated with a publication.

```
title: Authors

<$list filter="[all[current]tagging[]tagging[]sort[title]]" variable="item">
<$tiddler tiddler=<<item>>><$link><$view field=title/></$link></$tiddler>
<blockquote><b><<currentTiddler>>:</b>
<$list filter="[<item>tags[]] +[tag<currentTiddler>]" variable="category">
<$link to=<<category>>><$view tiddler=<<category>> field=title/></$link>
</$list>
</blockquote>
</$list>
```
