### ISSUE TITLE
expose iterator to list widget

### ISSUE THREAD

**Issue by tobibeer** [Jermolene/TiddlyWiki5#1328]
Expose temporary iterator variables during list processing...

* `<<iterator>>`
    * set to the current index, e.g. `1` 
* `<<iterator-even>>`
    * set to `true` for an even index
* `<<iterator-last>>`
    * set to `true` for last index

Always expose the default iterator variables, but — especially for nested lists — allow to declare a custom iterator variable prefix via a new *iterator* attribute of the list widget, as below...

**Examples**

```
<$list filter="[tag[foo]]" iterator="my-foo">

<$reveal type=match default=1 text=<<my-foo>>>
only show for item at index 1, with 1 meaning "first" (no js lingo)
</$reveal>

<$reveal type=nomatch default=1 text=<<my-foo>>>
show for all except first index
</$reveal>

<$reveal type=match default=true text=<<my-foo-even>>>
only show at even indexes
</$reveal>

<$reveal type=nomatch default=true text=<<my-foo-even>>>
only show at uneven indexes
</$reveal>

<$reveal type=match default=true text=<<my-foo-last>>>
only show for last index
</$reveal>

</$list>
```

**Comment by tobibeer** [comment]
If ok, I may go ahead and write some code...

**Comment by tobibeer** [comment]
Demo at: http://tbdemo.tiddlyspot.com/#Iterator

**Comment by tobibeer** [comment]
**done**, demo at: http://tbdemo.tiddlyspot.com/#Iterator

**Comment by Jermolene** [comment]
Hi @tobibeer excellent stuff, well done. It's a great idea, and the implementation looks good. Please go ahead and make a pull request.

**Comment by tobibeer** [comment]
done & closing...
