### ISSUE TITLE
implement $action-insert widget

### ISSUE THREAD

**Issue by tobibeer** [Jermolene/TiddlyWiki5#1329]
Especially for ordering lists, implement the `$action-insert` widget to insert a _tiddler_ either _before_ or _after_ a _target_ tiddler in a _list_ field...

**Attributes**
- `tiddler`
  - **required**
  - specifies the tiddler to be inserted
- `before`
  - optional
  - specifies a target tiddler before which to insert
  - _default:_ `<blank>`
- `after`
  - optional (use as default when neither `before` or `after` are declared)
  - specifies a target tiddler after which to insert
  - _default:_ `<blank>`
- `list`
  - optional
  - the list field for which the operation is performed
  - _default:_ use `list` field of `<<currentTiddler>>` when not specified
  - if target is not a member of the `list` field...
    - inserts `tiddler` first with `before`
    - inserts `tiddler` last with `after`
  - allow to specify a custom list field, e.g.:
    - `list=someTiddler!!my-list-field`
    - `list=!!my-list-field` using `<<currentTiddler>>`

Programatically, the `tiddler` is first removed from the list value and then inserted anew before or after the specified target tiddler.

**Examples**
- `<$action-insert tiddler=foo/>`
  - inserts **foo** at the end of the `list` field of `<<currentTiddler>>`
- `<$action-insert tiddler=foo before=bar/>`
  - inserts **foo** before **bar** in the `list` field of `<<currentTiddler>>`
  - if **bar** does not exist, inserts **foo** as first
- `<$action-insert tiddler=foo after=bar/>`
  - inserts **foo** after **bar** in the `list` field of `<<currentTiddler>>`
  - if **bar** does not exist, inserts **foo** as last
- `<$action-insert tiddler=foo list=!!my-list/>`
  - inserts **foo** last in the custom `my-list` list field of `<<currentTiddler>>`
- `<$action-insert tiddler=foo list=bar!!my-list/>`
  - inserts **foo** last in the custom `my-list` list field of tiddler **bar**

**Comment by Jermolene** [comment]
Hi @tobibeer good idea. I'd suggest implementing it as a plugin in the first instance.

**Comment by pmario** [comment]
@tobibeer .. imo can be done with the listops Operators: http://tiddlywiki.com/#Filter%20Operators

**Comment by tobibeer** [comment]
I haven't tested it but I am confident list-ops can handle it. After all, that was the point of it.
