### ISSUE TITLE
typed fields

### ISSUE THREAD

**Issue by tobibeer** [Jermolene/TiddlyWiki5#1331]
Define a standard interface to declare properties for fields, e.g. under `$:/config/fields/` such as...
- **edit**
  - the EditTemplate to be used for displaying the field content
    - defaults to a plain input field
- **view**
  - the ViewTemplate to be used for displaying the field content
    - defaults to plain text
- **format**
  - an output format for view-mode, e.g. `wikified`
  - a date-format-string specifying one or more allowed input format(s)
- **required**
  - whether or not a value is expected for that field and the corresponding error handling
    - at least a visual indication, e.g. a red background and an info-bubble
- **length**
  - a maximum length to be respected for input fields
- **tagfield**
  - whether to interpret the field in the sense of #1324
- **new**
  - when `true`, the field is added to all new tiddlers
- **default**
  - a default value set when undefined, e.g. used by any new-tiddler methods
- **type**
  - the field type out of a number of types...
    - `text` — the default, just text
    - `checkbox` — something to check and stored as `true` or `false`
    - `select` — select one out of a number of predefined values
    - `multi-select` — select an arbitrary number out of predefined values
    - `list-popup` — like the tag editor
    - `radio` — select one out of a number of options using radio buttons
    - `url` — a valid url format (validation tells you if it is)
    - `number` — a valid number format (validation tells you if it is)
    - `date` — (validation tells you if it is)
  - types could be implicitly handled by the edit- or view-template so there may not be a need to specifically declare it

These properties can then be used to handle fields in a number of ways, e.g. by customizing custom editors, e.g. date pickers or templates using $select widgets, $checkbox widgets, etc..

A plugin may either define other namespaces that hold such field definitions or implement a unique prefix for its purposes.

**Comment by pmario** [comment]
@Jermolene .. imo should be labeled "feature request"

**Comment by pmario** [comment]
@Jermolene -- IMO may be closed.

I think this also can be done with cascades now. Especially [Customizing EditTemplate field rendering](https://tiddlywiki.com/#Customizing%20EditTemplate%20field%20rendering) to define custom input elements based on field-names.

**Comment by Jermolene** [comment]
Hi @pmario a few aspects of the OP are still not addressed directly by the core (eg defining fields that are automatically added to new tiddlers), but I agree that we've made progress on quite a few (eg it is now possible to define custom field editors).
