### ISSUE TITLE
Tag dropdow should list titles also not yet used as tags

### ISSUE THREAD

**Issue by twMat** [Jermolene/TiddlyWiki5#1333]
When typing to create a new tag, the dropdown list should also show titles of existing tiddlers whose titles have not previously been used as tags.

Currently, I must go look for, or exactly remember, the title in order to get the tag right. No problem for "Foo" but yes problem for dates or just longer titles particularly including punctuation etc. And, if I do close the tiddler and discover that I got it wrong (which I might not discover!), then I must go back, erase the tag and do it over again - again risking to get it wrong!

**Comment by Jermolene** [comment]
Hi @twMat I'd encourage you to experiment with the filter expression that's used to generate the new tag dropdown. It's here:

http://tiddlywiki.com/#%24%3A%2Fcore%2Fui%2FEditTemplate%2Ftags

The line containing the filter expression is near the bottom:

```
<$list filter="[!is[shadow]tags[]search{$:/temp/NewTagName}sort[title]]">
```

**Comment by tobibeer** [comment]
I made a test here...

http://tbdemo.tiddlyspot.com/#Better%20Tag-Select

But somehow chaining the filter runs doesn't work as I expect they would?

**Comment by tobibeer** [comment]
Made a test here...

http://tbdemo.tiddlyspot.com/#Better%20Tag%20Select

I think I'm quite in favor.

**Comment by Jermolene** [comment]
@tobibeer you've got this filter:

```
<$list filter="[!is[shadow]tags[]search{$:/temp/NewTagName}][!is[shadow]!is[system]search:title{$:/temp/NewTagName}] +[sort[]]">
```

I think the `[!is[shadow]` at the start of the filter is a hangover from long ago. It's not needed now - the default source list is all non-shadow tiddlers anyway. So I think you could use:

```
<$list filter="[tags[]search{$:/temp/NewTagName}] [!is[system]search:title{$:/temp/NewTagName}] +[sort[]]">
```

Also is this a good time just to check that everyone is happy that the tag search works across all fields, not just the title?

**Comment by tobibeer** [comment]
I think it should only be the title, because the content is irrelevant to tagging, imho.

**Comment by Jermolene** [comment]
OK @tobibeer would you like to make a pull request?

**Comment by twMat** [comment]
>I think it should only be the title, because the content is irrelevant to tagging, imho.

Agree. Thank you for looking into this Tobias.

**Comment by tobibeer** [comment]
> make a pull request?

Sure.
