### ISSUE TITLE
macro output modifer

### ISSUE THREAD

**Issue by tobibeer** [Jermolene/TiddlyWiki5#1336]
As discussed here...

https://groups.google.com/d/msg/tiddlywiki/QXaD2i6tWeo/haZcsIx_YgMJ

...allow to modify the format with which macro output is rendered, e.g:

```
<<some-macro<text> param>>
<<some-macro<wikify> param>>
<<some-macro<wikify-to-text> param>>
```

Perhaps an enhanced, more future-proof version would look like...

```
<<some-macro<format=text><foo=bar> param>>
<<some-macro<format=wikify><foo=bar> param>>
<<some-macro<format=wikify-to-text><static-mode=who-knows-what> param>>
```

...whereas `format` could be interpreted as the default global attribute, so as to be able to omit it.

**Comment by mklauber** [comment]
Just want to ask/clarify would the goal of this be global?  That is, if a macro is invoked as a param, we can still specify if we want the result to be text or wikified?  I've got a use case that I'm pretty sure would require this, so if someone can point me in the right direction, I'd be willing to take a stab at it.

**Comment by Jermolene** [comment]
Hi @mklauber the original problem was that we currently have an ambiguity: `<<macroname>>` in ordinary text always wikifies the result (ie processes formatting markup), while `<$widget attribute=<<macroname>> foo=bar>` as an element attribute always returns the plain, unwikified text.

The original proposal is to devise a syntax for indicating whether a macro invocation should be wikified or not. @tobibeer's proposal builds on that with a more general proposal for adding a set of attributes to macro invocations.

I prefer the idea of the original proposal, a simple syntax that's reserved for indicating the rendering type, and not extending it as @tobibeer proposes. The extended syntax is more fiddly to type, and I think confusingly duplicates the syntax of macro parameters.

To answer your original question, then, yes, with this proposed change you'd be able to do something like this:

```
<$widget attribute=<<mymacro<wikify> param>>>
...
</$widget>
```

**Comment by mklauber** [comment]
Correct me if I'm wrong, but I think I should be looking at https://github.com/Jermolene/TiddlyWiki5/blob/master/core/modules/parsers/wikiparser/rules/macrocallinline.js
and/or 
https://github.com/Jermolene/TiddlyWiki5/blob/master/core/modules/parsers/wikiparser/rules/macrocallblock.js

Based on a cursory look, I'd need to update those to expect an optional regex pattern, extract it if so, and then match the parser to `$tw.Wiki.parsers`

**Comment by pmario** [comment]
@Jermolene ... imo should be labeled "feature request"

**Comment by pmario** [comment]
@tobibeer ... I think the wikify-widget solves this issue? http://tiddlywiki.com/#WikifyWidget

**Comment by tobibeer** [comment]
@pmario: I believe so, yes. Thank you.
