### ISSUE TITLE
core slider macro

### ISSUE THREAD

**Issue by tobibeer** [Jermolene/TiddlyWiki5#1337]
As sliders will be used in a number of usecases, also by plugins, implement a generic slider macro.

Would this be a suitable candidate?

[$:/.tb/macros/slider @ tb5](http://tb5.tiddlyspot.com/#%24%3A%2F.tb%2Fmacros%2Fslider)

**Demo**

http://tb5.tiddlyspot.com/#SliderMacro
http://tb5.tiddlyspot.com/#slider-examples

**Parameters**

Here are the parameters it currently defines...
1. `label` — the button label
2. `content` — the slider contents as a text-reference
3. `state` — the state variable
4. `tooltip` — a button tooltip
5. `label-hide` — label to show when slider is open
6. `animate` — whether to animate the slider
   - default: `yes` (after all, we're in candyland now)
7. `class` — a class for the slider contents
   - in addition to `slider-contents`
8. `btn-class` — a class for the slider button
   - default: `tc-btn-invisible tc-tiddlylink`
   - in addition to `slider-btn` and `slider-btn-show` when hidden and `slider-btn-hide` when shown
9. `element` — the html element for the rendered contents
   - default: `div`
10. `plain` — when set to `plain="true"` renders content as is instead of as a text-reference

**Code**

```
title: $:/core/macros/slider
tags: $:/tags/Macro

\define slider(label, content, state, tooltip, label-hide, animate: "yes", class, btn-class:"tc-btn-invisible tc-tiddlylink", element:"div", plain)
<$reveal type="match" state="$state$" text="">
<$button set="$state$" setTo="show" class="slider-btn slider-btn-show $btn-class$" tooltip="$tooltip$">$label$</$button>
</$reveal>
<$reveal type="match" state="$state$" text="show" animate="$animate$">
<$button set="$state$" setTo="" class="slider-btn slider-btn-hide $btn-class$" tooltip="$tooltip$"><$reveal type="match" text="" default="$label-hide$">$label$</$reveal><$reveal type="nomatch" text="" default="$label-hide$">$label-hide$</$reveal></$button>
<$element$ class="slider-contents $class$"><$reveal type="nomatch" text="" default="$plain$">$content$</$reveal><$reveal type="match" text="" default="$plain$">

{{$content$}}

</$reveal></$element$></$reveal>
\end
```

**Comment by Jermolene** [comment]
I agree that a core slider macro would be useful.

Your example looks reasonable, but what are the suffixes and prefixes for? I'd be concerned that they'd make the documentation more complicated for something that's only a benefit in a few situations.

**Comment by tobibeer** [comment]
The prefixes and suffixes allow to do this....

```
open >
< close

> open
< close

+ text
- text
```

Also added that missing button **tooltip**.

**Comment by Jermolene** [comment]
> The prefixes and suffixes allow to do this....

Sorry @tobibeer I'm being dense but I'm not sure what you mean. It still looks like passing three separate parameters for a single value wouldn't be common.

**Comment by tobibeer** [comment]
For example, I have a list that renders dynamic titles, so I want to have those sliders as either...

* **item1 »** — closed state
* **item2 «** — opened state

or...

* **+ item1** — closed state
* **- item2** — opened state

or 

* **item1 »** — closed state
* **« item2** — opened state

or even

* **{{icon-open}} item1** — closed state
* **{{icon-close}}  item2** — opened state

Hence prefixes and suffixes for either state and the actual, dynamic title in the middle.

**Comment by Jermolene** [comment]
Sorry @tobibeer I'm still not quite seeing why the caption needs to be split into three to accomplish that. Is it because you're transcluding the middle "text" part of each caption? It just seems that the same effect could be achieved by the caller using a macro to assemble the captions.

**Comment by tobibeer** [comment]
> It just seems that the same effect could be achieved by the caller using a macro to assemble the captions.

We're dealing with two states, they can't be passed down in one parameter. I would not burden users with that macro overhead while it's not an uncommon usecase to do the above.

**Comment by Jermolene** [comment]
> We're dealing with two states, they can't be passed down in one parameter. I would not burden users with that macro overhead while it's not an uncommon usecase to do the above.

Sorry @tobibeer I'm still not seeing it. Can you give an example of how the macro above would be invoked to use the suffix/prefix?

**Comment by tobibeer** [comment]
http://tb5.tiddlyspot.com/#slider-examples

**Comment by Jermolene** [comment]
Hi @tobibeer that makes it look as though the suffix/prefix are necessary for producing that catalogue of sliders. But are they needed for end users who are using one style or another of slider?

**Comment by tobibeer** [comment]
These are different styles and I would not be able to easily implement them without the slider macro catering for it. At least, there would have to be an alternative **label-hide**, then that would work. Will try that.

**Comment by Jermolene** [comment]
Hi @tobibeer I'd have thought that the thing to do would be to wrap the macro invocation in another macro:

```
\define mySliderMacro(prefix,body,suffix)
<< realSliderMacro "$prefix$$body$$suffix$">>
\end

\define realSliderMacro(text)
do something with $text$
\end
```

**Comment by tobibeer** [comment]
I have changed the OP and the examples to now use an alternative **label-hide** parameter. Please have another look. I think this is better, indeed.

http://tb5.tiddlyspot.com/#slider-examples

However, we need at least two labels to be able to have alternate text displayed for the button when the slider is open. Perhaps also a **tooltip-hide**?

**Comment by twMat** [comment]
Sliders are incredibly useful. @tobibeer, thank you for working on this!!!

Since you're working on it right now:

1. Erics superior NestedSlidersPlugin also allowed nesting and I think this is a very natural 'application'. (Actually, I think a user would assume this works.)
2. I think all sliders I've seen thus far force a linebreak, typically both before and after the displayed content, which in effect turns the content into a new *paragraph*. For example your demo lists the examples like paragraphs so I'm guessing this is the case there. But sometimes it is desirable with just a small "line-expansion" +++[e.g. >][e.g. <] like this little explanatory insertion===, which doesn't warrant a full new paragraph.

BTW, sliders would be valuable in documentation of tW for turning to different levels of expertise, allowing a quick overview or deeper digging for those who prefer.

**Comment by tobibeer** [comment]
> I think all sliders I've seen thus far force a linebreak, typically both before and after the displayed content, which in effect turns the content into a new paragraph. 

We could add another **mode** attribute that defaults to `block` but also allows `inline`.

> NestedSlidersPlugin also allowed nesting

Can you perhaps do some tests with the macro implemented here and see if that works as expected...

http://tb5.tiddlyspot.com/#slider-examples

?

However, sliders are not popups, imho. There should be a dedicated popup macro for that.

**Comment by tobibeer** [comment]
> We could add another mode attribute that defaults to block but also allows inline.

Added an **element** parameter instead, defaults to `div`. Also added a **plain** parameter to render the contents as is, instead of as a text-reference.

**Comment by tobibeer** [comment]
I finally got to fix the bug where the label would scramble up if it contained a WikiLink. It was as simple as to use triple quotes in the macro. ;-)

I also modified it so that sliders in a list widget can now be used to create an accordion style menu where only one item would be open at a time.

@Jermolene, now that I am into the plugin creation process, I think I may go ahead and release this as a plugin ...and you can consider / evaluate it for the core later?

It's just that we'd already have a plugin-based slider macro by then. So, not sure. Perhaps I give it a more tb-like name, e.g. **slidr**? :D

**Comment by pmario** [comment]
@tobibeer ... should there be a PR? .. or should it stay as a plugin from your site?

**Comment by tobibeer** [comment]
@pmario: not sure, what would be your preference?

**Comment by pmario** [comment]
>@pmario: not sure, what would be your preference?

Just did a very short play with your examples. IMO plugin territory, since those types of implementations are allways opinionated and very close to the actual usecase.

I did create something similar, for my [A script and todo manager workflow / UI experiment + video howto's](https://groups.google.com/forum/#!topic/tiddlywiki/_VQw8yIKWn8) 

I did call it "toggle me" macro. ... IMO it does a very similar thing, but in a completely different way. 

For more info also see: video 15 / 16 / 17 if you have time ;)

**Comment by twMat** [comment]
Note: We should abandon the term "slider" for this as it apparently is not the standard term. I even recall someone on the boards getting very upset about us calling it so. I'm not sure but maybe the correct term is [accordion](https://www.w3schools.com/howto/howto_js_accordion.asp)?

---

Side note: Fantastic to see you back @tobibeer - and running amok right away :-D

**Comment by tobibeer** [comment]
> Fantastic to see you back @tobibeer - and running amok right away :-D

Thanks! Happy to be back. @twMat

**Comment by Jermolene** [comment]
Again, I think this is plugin territory -- which of course immediately leads to the present problems of all these wonderful plugins not being discoverable in the official plugin library....

**Comment by gernert** [comment]
What about a 'simple' slider in the core and more sophisticated sliders like Tobias' one as plugin?
Like in TWc a standard simple slider and Eric's NestedSlider plugin.

**Comment by tobibeer** [comment]
Looking at the time passed since the initial suggestion, I think it's actually time I make it more "discoverable" ...as a plugin, for now.
