### ISSUE TITLE
Editing long tiddlers with 5.15

### ISSUE THREAD

**Issue by HowardRM** [Jermolene/TiddlyWiki5#1338]
The problem is only on iOS using TWMobile, not on Firefox on my Mac, but I have raised it on the TWMobile forum and followed Tobias' and Chris' suggestions without resolving the problem.  Tobias suggested that I raise it here.

I have some long tiddlers (background notes which there is no reason to split) in some of my TW5 files.   These have been no problem to edit until TW5.15 (TW5.14 is OK).   The problem is that, when I edit them about two screens down the tiddler, the background (surrounding the tiddler) flashes black on every keystroke, towards 3 screens down this changes to the text jumping on every keystroke (it returns to the cursor point each time).  The latter is not just a small jump, it is quite substantial and very distracting.

I have closed all other tiddlers, hidden the sidebar and changed the sidebar tab to a bespoke one with fixed contents, but the problem remains.   I use a customised palette but changing to Vanilla makes no difference.

When I say it is OK on TW5.14 but not 5.15, I mean that importing a fully working 5.14 wiki into the 5.15 empty gives the problem straightaway - it is a comparison of the same content on the two versions.   The tiddlers I have tested before I posted this issue are straightforward text without any widgets or other sophisticated features.

**Comment by Jermolene** [comment]
Hi @HowardRM thanks for the report. Do you get the same problem with the latest 5.1.7 version?

**Comment by HowardRM** [comment]
Hi Jeremy

Yes, but at the suggestion of Chris, I tried the file with Safari on my iPad & the problem did not occur, so it may be. TWMobile issue.

Regards

Howard

**Comment by Jermolene** [comment]
There was a change in 5.1.5 that may be the culprit:

https://github.com/Jermolene/TiddlyWiki5/commit/d1bbe7253c135ceed138fd02c82b0f861d5dda6b

It would be helpful if I could reproduce the problem. Could you upload a faulty wiki to tiddlyspot perhaps?

**Comment by Xiander** [comment]
Hi Howard, Hi Jeremy,

in normal case i am using twedit on ipad to edit my TW-files, and i have the same problem as described in the first entry.
I open a TW5.17 file in safari from dropbox with a long tiddler, and if i switch in edit mode place the cursor at the end and start writing, the tiddlerscreen jumps in the middle, so i cant see the beginning of the tiddler and also not where my cursor is....the cursor is behind the virtual keybord...
it is not the same problem as the first, but also odd.
i will try to upload a testwiki to tiddlyspot...

Best wishes

Xiander

**Comment by Xiander** [comment]
Hi,
here is the link:
http://xiandertestentry.tiddlyspot.com

I hope to help solve the problem

Best regards 

Xiander

**Comment by tobibeer** [comment]
Please make sure don't have this: [$:/hack-142-scroll-pagescroller.js](http://tb5.tiddlyspot.com/#%24%3A%2Fhack-142-scroll-pagescroller.js)
As described here: [TopBar With Icon Links](http://tb5.tiddlyspot.com/#TopBar%20With%20Icon%20Links)

**Comment by Xiander** [comment]
I only use the official TW without any makros (at the moment:-))
here is the link to a testwiki: http://xiandertestentry.tiddlyspot.com
Best regards
Xiander

**Comment by HowardRM** [comment]
After your suggestion that the problem lies with the edit-text widget, I tried converting my problem wiki to 5.17 but replacing the new edit-text widget with that from 5.14.   All my long tiddlers now behave normally during editing.   I am sure there was a good reason for the change but on Firefox and TWMobile I haven't found any negative consequences of the change

Regards

Howard

**Comment by Xiander** [comment]
Hi Howard,
i also have no Problem in Firefox on my PC...only in TWEdit and also in Safari on the Ipad.
At the moment i have no idea how to replace only the edit-text-widget with Version 5.14, i just have to read something about that.
Thank you and best regards
Xiander


> Am 18.01.2015 um 18:15 schrieb HowardRM <notifications@github.com>:
> 
> After your suggestion that the problem lies with the edit-text widget, I tried converting my problem wiki to 5.17 but replacing the new edit-text widget with that from 5.14. All my long tiddlers now behave normally during editing. I am sure there was a good reason for the change but on Firefox and TWMobile I haven't found any negative consequences of the change 
> 
> Regards 
> 
> Howard 
> 
> Sent from my iPad 
>

**Comment by Jermolene** [comment]
Hi @Xiander I'm sorry for the delayed response.

I'm unable to reproduce the problem with TWEdit 2.4.1 and the stock TiddlyWiki 5.1.7 from tiddlywiki.com. I'm on iOS 8.1.3, perhaps you're using an older version?

**Comment by Xiander** [comment]
Hi Jeremy,

i am using iOS 8.1.3 and TWEdit 2.4.1 too; my IPAD has the ModellNumber: MC980FD/A. 
I´ve created a short movie available on youtube:

https://www.youtube.com/watch?v=st0jiJU0E-4&feature=youtu.be

- first you see the problem by using TW5.1.7 with TWEdit 2.4.1 with the example published on tiddlyspot(http://xiandertestentry.tiddlyspot.com) 
- and second what happens if i open the link from tiddlyspot in safari and want to edit (i know, i can not save directly)
Sorry for the quality of the movie, but it was the fastest way for me to capture the screen with a mobilephone and i think it is visible what i want to show you.

By the way, in the last week i have replaced the edit-text-widget in a 5.1.7 file with the Version from 5.1.4 as howard discribed above and the problems you see in the movie are disappears.

Best regards

Xiander

**Comment by HowardRM** [comment]
Jeremy, Xiander

I am having exactly the same problem using the latest versions of TWEdit and IOS8.1.3 - I have just retested.   Since I substituted the 5.1.4 edit-text widget for the latest one in my main wiki, I have had no problems.

I cannot master loading to Tiddlyspot (don't know why) but I have loaded the latest test wiki (with fault) onto Box.com - access by using "mail@howardmorrison.plus.com" and "x123456789".   It is simply called TW5.17 and the tiddler "EmotionPsychologistsViewpoint" demonstrates the problem - try editing the last paragraph.

Hope this helps

Howard

**Comment by Xiander** [comment]
Hi Howard,
yes that is the same, but is very intersting, that it is only on the "Emotion..."-Tiddler; it is the one you have created in the new TW-Version.
I tried to edit a old Tiddler in my file (created in a older Version of TW) and there is no Problem. I think the problem is related to creating a tiddler with the new Version...

Best regards
Xiander

**Comment by tobibeer** [comment]
> I think the problem is related to creating a tiddler with the new version.

I don't think that's possible. What I can imagine is that the problem might relate to a certain kind of markup element being used. Have you tried different variants, e.g. "just text", "with lists", "with macros", "only one tiddler open", etc... ?

**Comment by Xiander** [comment]
Hi Tobias,
i have not done any changes in the file on tiddlyspot...only download an empty TW5, create a long tiddler, save them and edit...

Greetings
Xiander

**Comment by tobibeer** [comment]
Could you do some more testing with which tabs are open in the sidebar or with the type of contents in that long tiddler?

**Comment by Xiander** [comment]
Hi Tobias,
ok something done:
- it makes no differnece which sidebar is open
- the content type is by default empty, but also no difference if i choose
any of the four texttypes
- but if i am using "show preview" i can editing without the
Problem..."hide preview" the problem is coming again..

something else? :-)

Xiander

2015-02-11 12:05 GMT+01:00 Tobias Beer <notifications@github.com>:

**Comment by tobibeer** [comment]
As for "types of content", I actually didn't mean the type of the tiddler but what you enter into the body, whether just alphanumerical text or rather special wikitext markup, e.g. lists, headings etc... perhaps the problem doesn't occur with all markup? But then, if you say that switching content types to something other than the default doesn't have an effect then it sounds like the issue possibly can't be that.

**Comment by Jermolene** [comment]
@tobibeer have you seen the commit I pointed to above? There's some other open issues with similar symptoms (eg #1365), it's pretty clear that the removal of that setTimeout() call is the causing this problem. I'm just trying to figure out the details of what's going on.

**Comment by tobibeer** [comment]
I have noticed but wasn't sure what to make of it. I have the feeling that the last line is what's causing the problem. Why would we be scrolling anyway? I don't think anything should scroll when changing the size of a textarea.

**Comment by Jermolene** [comment]
@tobibeer look at how the automatic resizing is done. The height of the text area is temporarily set to a tiny number, a layout triggered with an access to offsetHeight, allowing us to read the clientHeight of the text box, and thus compute the correct height for it. The problem in all of that is that temporarily the text area has shrunk vertically. Depending on the page scrolling position, the browser will respond to the adjustment in height by scrolling back up the page. Hence we remember and restore the scroll position before the resizing takes place. Does that make sense?

**Comment by tobibeer** [comment]
I am seeing the same jumpy behavior on all kinds of demos showing me auto-resizing for textareas.

Here's my take: This problem only occurs when the textarea is (significantly) longer than the viewport. Have a scrollbar to the textarea itself and be done with it. That way I also get a proper feel for its content length... to which the page scrollbar simply doesn't correspond!

**Comment by tobibeer** [comment]
Not sure I quite understand the method, but this one seems to not show any jumpiness:

http://www.brianchu.com/blog/2013/11/02/creating-an-auto-growing-text-input — http://jsfiddle.net/2UDdh/43/light

**Comment by Jermolene** [comment]
> Here's my take: This problem only occurs when the textarea is (significantly) longer than the viewport. So, in that case, stop expanding it and have a scrollbar to the textarea itself and be done with it. That way I also get a proper feel for its content length, to which the page scrollbar simply doesn't correspond.

Well, that would mean abandoning the goal of trying to avoid exactly those nested scrollbars. But I agree that the side effect of getting a feel for the content length is nice.

> Not sure I quite understand the method, but this one seems to not show any jumpiness:

@tobibeer I don't think we need to adopt a different technique. I think we've established that restoring the setTimeout fixes the problem. I want to understand what's going on, including the other scenarios that led to the removal of the setTimeout.

**Comment by pmario** [comment]
@Jermolene .. is this still a problem or is it fixed?

**Comment by tobibeer** [comment]
@HowardRM: only 95% sure, but I believe this is no longer an issue at this point. If you agree, please close.

**Comment by HowardRM** [comment]
Yes this is no longer an issue.   Thanks
