### ISSUE TITLE
empty/#GettingStarted - touch-ups (but also proposal for some global bits)

### ISSUE THREAD

**Issue by twMat** [Jermolene/TiddlyWiki5#1344]
We should prettify  [empty/#GettingStarted](http://tiddlywiki.com/empty#GettingStarted) a bit further. I think maybe there should be a separate div class for GettingStarted, but there are also some aspects I would like to be more global.

Take a peek at the link above and compare it to this:

![gettingstarted_empty1](https://cloud.githubusercontent.com/assets/4534056/5674579/5695f8c2-97ad-11e4-9f11-bd012a5d363d.png)

Thus...
1. the ediing fields should be full width, like they are in the Controlpanel. This is easily achieved by inserting `<div class="tc-control-panel">` ...but is it apporpriate to use this class when it's not the controlpanel?
2. Invisible frame borders in GettingStarted... but really in most tables, particularly in Controlpanel.
3. Fainter edtibox-borders (Again, propose global.)
4. A consequence of invisible borders is one needs to valigned the DefaultTiddlers to top. I also moved the DefaultTiddlers help text. Why is this in italics btw? I can't change it.
5. Not seen in illustration, but I would also like to expand the left column slightly so "Title of this TiddlyWiki" wouldn't wrap.
6. Phrase "retain story ordering" is unclear, both regarding "retain" and what is meant by "story ordering". I suggest something along "reopen last saved tiddlers" but maybe shorter? Or maybe all of the words don't have to be on the button? "...[reopen last saved] tiddlers." Or perhaps "...[reopen saved view]" - "view" is not fully clear either, but IMO clearer than "story ordering" and it does reuse the word from the term "story view".

This is an important tiddler welcoming the user and in some way a second chance to make a good first impression. Again, so to say. :-)

**Comment by Jermolene** [comment]
Thanks @twMat that looks good.

> 1. the ediing fields should be full width, like they are in the Controlpanel. This is easily achieved by inserting `<div class="tc-control-panel">` ...but is it apporpriate to use this class when it's not the controlpanel?

I think it's fine; what we've got here is a mini-control panel.

> 2. Invisible frame borders in GettingStarted... but really in most tables, particularly in Controlpanel.

Yes I agree that would be better

> 3. Fainter edtibox-borders (Again, propose global.)

Yes, looks good.

> 4. A consequence of invisible borders is one needs to valigned the DefaultTiddlers to top. I also moved the DefaultTiddlers help text. Why is this in italics btw? I can't change it.

That text is in italics because it's an aside. I think the italics are included in the translatable string, so we'd have to go through and change each language.

> 5. Not seen in illustration, but I would also like to expand the left column slightly so "Title of this TiddlyWiki" wouldn't wrap.

Agreed.

> 6. Phrase "retain story ordering" is unclear, both regarding "retain" and what is meant by "story ordering". I suggest something along "reopen last saved tiddlers" but maybe shorter? Or maybe all of the words don't have to be on the button? "...[reopen last saved] tiddlers." Or perhaps "...[reopen saved view]" - "view" is not fully clear either, but IMO clearer than "story ordering" and it does reuse the word from the term "story view".

Reusing "story view" would be confusing, as it is a different thing. I'm open to suggestions.

**Comment by pmario** [comment]
@twMat You nentioned this issue at GG [Proposal for a new GettingStarted page, for empty.html](https://groups.google.com/forum/#!topic/tiddlywiki/H6Gmby9gvYg)
 
>1 the ediing fields should be full width, like they are in the Controlpanel. This is easily achieved by inserting <div class="tc-control-panel"> ...but is it apporpriate to use this class when it's not the controlpanel?

This is already part of Tw

>2 Invisible frame borders in GettingStarted... but really in most tables, particularly in Controlpanel.

This is hard to achieve and would need to change the whole base theme. The ControlPanel would need a complete rework. ...IMO way out of the scope of my GettingStarted PR

>3 Fainter edtibox-borders (Again, propose global.)
>4 A consequence of invisible borders is one needs to valigned the DefaultTiddlers to top. I also moved the DefaultTiddlers help text. Why is this in italics btw? I can't change it.

Same as 2

>5 Not seen in illustration, but I would also like to expand the left column slightly so "Title of this TiddlyWiki" wouldn't wrap.

Will be automatically done, if the user changes the story width.

>6 Phrase "retain story ordering" is unclear, both regarding "retain" and what is meant by "story ordering". I suggest something along "reopen last saved tiddlers" but maybe shorter? Or maybe all of the words don't have to be on the button? "...[reopen last saved] tiddlers." Or perhaps "...[reopen saved view]" - "view" is not fully clear either, but IMO clearer than "story ordering" and it does reuse the word from the term "story view".

I will do that

**Comment by pmario** [comment]
> 2. Invisible frame borders in GettingStarted... but really in most tables, particularly in Controlpanel.

This can easily be tested in the ControlPanel -> Appearence -> Palette --> Show Editor and search for `table-border`
Set it to `none`

![image](https://user-images.githubusercontent.com/374655/182664789-9abf175f-4e04-4282-bd11-ee853950d62f.png)


This is a global setting. I think it doesn't work for most tables. So I think it's the contrary of the OT. .. It may be used for some tables. eg: the table in GettingStarted. ...

**Comment by pmario** [comment]
I did some more test. .. The input fields in FireFox and Edge are different. 

Edge seems to use the outline colour for selected input and text fields.

![image](https://user-images.githubusercontent.com/374655/182676052-9f96a04a-8c86-48c0-a7f0-b2fc3110662f.png)

FireFox does not

![image](https://user-images.githubusercontent.com/374655/182675829-a85f7902-efff-4730-9e44-420e393c32a1.png)

-------

I did test a little bit of CSS --> Edge and FF behave the same way

```
input:focus, textarea:focus {
 outline: 1px solid blue;
}

input, textarea {
 border: 1px solid lightgray;
}
```

The 1px solid lightgray border also removes the emboss-effect in FF

**Comment by pmario** [comment]
@twMat  ... Can you check my little CSS code. .. What do you think. .. For the input box only. 

Table will be a different experiment

**Comment by pmario** [comment]
@Jermolene ... Could you test the CSS snippet in Safai?

**Comment by pmario** [comment]
@twMat The following snippet will remove the table border:

```
table.tc-table-no-border,
table.tc-table-no-border th, 
table.tc-table-no-border td {
  border: initial;
}
```

Using it with a wikitext table will work like this: 

```
|tc-table-no-border|k
|asdf| asdf|
|asdf|asdf |
```

@Jermolene .. We could add `|tc-table-no-border|k` to the table in empty.html GettingStarted. .. What do you think?

**Comment by twMat** [comment]
> @twMat ... Can you check my little CSS code. .. What do you think. .. For the input box only.

In Brave I get this:

<img width="469" alt="image" src="https://user-images.githubusercontent.com/4534056/182894849-bfe5007c-0098-4842-a003-ff12760098a4.png">

Hm, I do think this is an improvement BUT the improvement is that single line edit fields and multiline have a similar looking border - good, they really should. However, this is probably a bit too faint. This becomes especially clear when the table borders are removed:

<img width="464" alt="image" src="https://user-images.githubusercontent.com/4534056/182898512-b5fb7c4a-2250-444d-aca7-8aa7df32a1e9.png">

So, IMO both editor types should have a tad darker border. OR we could do like with the multiline does inside the Controlpanel, i.e give the editor background a gray nuance. (I don't understand why *only* the multiline editor is gray currently???)



...so I'm thinking it would be better to

**Comment by twMat** [comment]
Apropos wrapped links like:

<img width="145" alt="image" src="https://user-images.githubusercontent.com/4534056/182904494-c1a36871-5925-4617-9950-d400728ebaa9.png">

For everything styled as a controlpanel, I would like to this:

`.tc-control-panel td:first-of-type a {white-space: nowrap;}` (for easy spotting during testing insert `background:red !important;`)

The `td:first-of-type` ensures only the leftmost column is targeted where, typically, links work as indices which is exactly the ones that should not be wrapped. 

Thoughs?

**Comment by pmario** [comment]
hmmm, I'm curious. Why is this line-break such a problem? 

I personally think the left image is easier to read, because there is less whitespace between the text and the second column. The problem with the right image will be even worse, if the table border would be removed. 

![image](https://user-images.githubusercontent.com/374655/183064669-a7383065-83c3-446e-a63d-8457346896ad.png)

**Comment by pmario** [comment]
I could be happy with something like this: 

![image](https://user-images.githubusercontent.com/374655/183066140-7c2112ec-3f31-4bab-b95c-ca694089ce19.png)


CSS

```
table.tc-table-no-border,
table.tc-table-no-border th, 
table.tc-table-no-border td {
  border: initial;
}

.tc-table-no-border td:first-of-type a {
  white-space: nowrap;
}

.evenRow{
  background: #eee;
}


input:focus, textarea:focus {
  outline: 1px solid blue;
  border-radius: 2px;
}

input, textarea {
 border: 1px solid lightgray;
}
```

**Comment by pmario** [comment]
But I do like this even more

![image](https://user-images.githubusercontent.com/374655/183066581-360ac6af-b442-4af4-83f6-691b1dfd6905.png)


```
table.tc-table-no-border,
table.tc-table-no-border th, 
table.tc-table-no-border td {
  border: initial;
}

/***
.tc-table-no-border td:first-of-type a {
  white-space: nowrap;
}
***/

.evenRow{
  background: #eee;
}


input:focus, textarea:focus {
  outline: 1px solid blue;
  border-radius: 2px;
}

input, textarea {
 border: 1px solid lightgray;
}
```

**Comment by twMat** [comment]
>Why is this line-break such a problem?

Well, it makes no clear sense *why* that type of "heading" or "index" string should be broken. And why *there*? It's not as if these "indices" are long sentences. 

Second, when such a line is broken, then the (single line) editor suddenly has unjustified spaced above and below it. It just looks odd when some editors don't and some do.

**Comment by twMat** [comment]
Do you really think this looks good?

<img width="150" alt="image" src="https://user-images.githubusercontent.com/4534056/183067715-ac3b8dbb-905b-44a0-a414-28b49dc1bbdb.png">

It triggers the same cognitive processes as this illusion does, i.e "what line delimits what?"

<img width="155" alt="image" src="https://user-images.githubusercontent.com/4534056/183068032-6a82eef0-a1fa-4270-bb45-7ebe1460904a.png">

**Comment by twMat** [comment]
One option to distinguish the editors would be to use a lightgray background for (i.e *in*) them as is done in - for some reason- *some* of the editors in the Controlpanel

**Comment by twMat** [comment]
Here's one layout that captures much of what I'm after

<img width="492" alt="image" src="https://user-images.githubusercontent.com/4534056/183069430-f2a108bb-5966-4861-9af6-2cb7cd362311.png">

**Comment by pmario** [comment]
For me the main problem with `nowrap` is with mobile screens: 


**nowrap active**
![image](https://user-images.githubusercontent.com/374655/183069268-82bb17cd-7a12-4cda-911c-3714c28fcc79.png)

**default wrap active**
![image](https://user-images.githubusercontent.com/374655/183069466-f7dc3e44-73c0-466b-8257-2389dfbf8f97.png)

**Comment by twMat** [comment]
>For me the main problem with nowrap is with mobile screens

But isn't this exactly what responsive design is about? I have very limited experience in "responsive design" (because I only only use TW on my full screens). But isn't a @mediaquery or whatever it is called a way to just set up two variants depending on screen width? For a small screen I can fully see why line breaks are justified!

**Comment by pmario** [comment]
>Here's one layout that captures much of what I'm after

Yea, I see. But the problem is, that the context of the "Default tiddlers" is lost. So if there are 2 consecutive elements with multiline editors and some text above and below we can't see, where one starts and the other one ends. 

![image](https://user-images.githubusercontent.com/374655/183071103-885b6c22-7d05-44f9-a845-9583c3cf814f.png)

IMO that's better

![image](https://user-images.githubusercontent.com/374655/183071819-4f98eaba-4b36-488f-a88d-8675eed2d334.png)

**Comment by pmario** [comment]
CSS used above: 

```
table.tc-table-no-border,
table.tc-table-no-border th, 
table.tc-table-no-border td {
  border: initial;
}

table.tc-table-no-border {
  border: 1px solid #f0f0f0;
}

.tc-table-no-border td:first-of-type a {
  white-space: nowrap;
}

.evenRow {
  background: #f0f0f0;
}


input:focus, textarea:focus {
  outline: 1px solid blue;
  border-radius: 2px;
}

input, textarea {
 border: 1px solid lightgray;
}
```

**Comment by pmario** [comment]
>But isn't this exactly what responsive design is about? I have very limited experience in "responsive design" (because I only only use TW on my full screens). But isn't a @Mediaquery or whatever it is called a way to just set up two variants depending on screen width? For a small screen I can fully see why line breaks are justified!

That's right. ... 

May be OT: I have seen a video lately [Andy Bell – Be the browser’s mentor, not its micromanager](https://www.youtube.com/watch?v=5uhIiI9Ld5M&t=7s) where he covers the problems with mediaqueries. 

It completely changed my view about mediaqueries. ... They are pretty much useless for the number of different screen-sizes we have at the moment. See: https://youtu.be/5uhIiI9Ld5M?t=885

**Comment by twMat** [comment]
> Yea, I see. But the problem is, that the context of the "Default tiddlers" is lost. So if there are 2 consecutive elements with multiline editors and some text above and below we can't see, where one starts and the other one ends.

Hm, one of us misunderstand something (it might be me). My suggestion is what I showed in my image, which doesn't have several multiline editors so what do you mean with "lost context"? How does my design change the context for the Default tiddler stuff at all?

Actually, I would really prefer for the table cell content to be valigned:top and for the Default tiddler infotext to be relocated like shown here, or like in the OP (which has all the text below the editor). This is much clearer than current, without a lot of borders and lines and with distinct editors.

<img width="555" alt="image" src="https://user-images.githubusercontent.com/4534056/183074632-dc407304-8582-43a8-9927-e26760c6f48d.png">

**Comment by pmario** [comment]
hmmm, We are getting better ;)

**Comment by twMat** [comment]
> Andy Bell ... problems with mediaqueries.

OK, I've obviously only had time with a quick peek (interesting stuff, thanks!) but he seems to advocate dynamic font sizes instead of textual reorganization that depends on viewport size - but in our simple case it really is (almost) a binary situation: Cut the row or not, and at worst the line is still not long.

**Comment by twMat** [comment]
> hmmm, We are getting better ;)

Yay :) Is it still missing something?

**Comment by Jermolene** [comment]
> Do you really think this looks good?
> 
> <img alt="image" width="150" src="https://user-images.githubusercontent.com/4534056/183067715-ac3b8dbb-905b-44a0-a414-28b49dc1bbdb.png">
> 
> It triggers the same cognitive processes as this illusion does, i.e "what line delimits what?"
> 
> <img alt="image" width="155" src="https://user-images.githubusercontent.com/4534056/183068032-6a82eef0-a1fa-4270-bb45-7ebe1460904a.png">

Nicely put! I agree that the stripy rows don't work well here, perhaps because the table has a small number of rows and they are of irregular height.

Generally, in TW5 we try to use whitespace and margins to define the visual hierarchy; adding borders and backgrounds should be a last resort.

**Comment by twMat** [comment]
> Generally, in TW5 we try to use whitespace and margins to define the visual hierarchy; adding borders and backgrounds should be a last resort.

OK, so would you say that this is better - and good?

<img width="555" alt="image" src="https://user-images.githubusercontent.com/4534056/183110323-c2aedd18-d262-4378-b6c5-f0f190d3b4ba.png">

**Comment by Jermolene** [comment]
> OK, so would you say that this is better - and good?

Looks pretty good, definitely better than what we have at present.

**Comment by twMat** [comment]
>adding borders and backgrounds should be a last resort.

Actually, why is multiline editor in Ctrlpanel with a gray background in that case? This is how the Ctrlpanel looks on my machine (win, brave)

<img width="644" alt="image" src="https://user-images.githubusercontent.com/4534056/183111060-b4df734c-f74e-44a9-9067-37e8e861fdb2.png">

**Comment by Jermolene** [comment]
> Actually, why is multiline editor in Ctrlpanel with a gray background in that case? This is how the Ctrlpanel looks on my machine (win, brave)

Isn't that the default styling we use for all multiline text boxes? I don't think that there's anything special about control panel here.

Note that I didn't say that we shouldn't use borders and backgrounds, just that they should be a last resort.

**Comment by CodaCodr** [comment]
> Actually, why is multiline editor in Ctrlpanel with a gray background in that case?

That's probably the `tc-edit-texteditor` class, which I'm a big fan of. It adds an inset box-shadow which _usually_ means you can lose the borders, too. Looks great on `<select>` elements, too.

In the screenshot below, I've added it to the preceding single line inputs:

![image](https://user-images.githubusercontent.com/436812/183114418-3182c59e-2037-49c5-bf90-7893ed4fe26d.png)

It's used for the title field in tiddlers. I use it _everywhere_ -- that and `tc-edit-tags` which does a similar job.

**Comment by pmario** [comment]
@twMat Can you post the code and the CSS that you used for this image: https://github.com/Jermolene/TiddlyWiki5/issues/1344#issuecomment-1206376992

**Comment by pmario** [comment]
>That's probably the tc-edit-texteditor class, which I'm a big fan of. It adds an inset box-shadow which usually means you can lose the borders, too. Looks great on <select> elements, too.

I'm not happy with box shadows. They look outdated and the time for 3d buttons is over for some time already.

**Comment by twMat** [comment]
@pmario wrote:

>@twMat Can you post the code and the CSS that you used for this image: https://github.com/Jermolene/TiddlyWiki5/issues/1344#issuecomment-1206376992
  
```
<div class="tc-control-panel">

|tc-table-no-border|k
|<$link to="$:/SiteTitle"><<lingo Title/Prompt>></$link> |<$edit-text tiddler="$:/SiteTitle" default="" tag="input" class="foo"/> |
|<$link to="$:/SiteSubtitle"><<lingo Subtitle/Prompt>></$link> |<$edit-text tiddler="$:/SiteSubtitle" default="" tag="input" class="foo"/> |
|<$link to="$:/DefaultTiddlers"><<lingo DefaultTiddlers/Prompt>></$link><br><<lingo DefaultTiddlers/TopHint>> |<$edit tag="textarea" tiddler="$:/DefaultTiddlers" class="foo"/><br>//<<lingo DefaultTiddlers/BottomHint>>// |
</div>
```


```
.tc-control-panel input,
 .tc-control-panel textarea {
  border: 1px solid lightgray;
  background: #f4f4f4 !important;
}

.tc-control-panel td:first-of-type {
  text-align:right;
  vertical-align:top;
  width:1%; /*shrink column to fit content*/
}

.tc-control-panel td:first-of-type a {
  white-space: nowrap;
}


/* from pmario */

input:focus, textarea:focus {
  outline: 1px solid blue;
  border-radius: 2px;
}

table.tc-table-no-border,
table.tc-table-no-border th, 
table.tc-table-no-border td {
  border: initial;
}
```

**Comment by twMat** [comment]
@CodaCodr - yeah, boxshadows, I have a love-hate relationship with them. The love part is that the "empty space"-look conveys that it's a space that should be typed into clearly than what a mere rectangle does.

**Comment by twMat** [comment]
@Jermolene 

> Note that I didn't say that we shouldn't use borders and backgrounds, just that they should be a last resort.

OK. I'm hoping input fields and text areas could have the same consistent lightgray background colour in the controlpanels and the gettingstarted table. IIs there / what is the justification to use the gray color in the Controlpanel text areas, e.g under ctrlpanel>info>basics ? Doesn't this justification also apply to the input fields?

**Comment by pmario** [comment]
```
.tc-control-panel td:first-of-type {
  text-align:right;    <- can be done with tw table wikitext
  vertical-align:top;    <-  tw table wikitext
  width:1%; /*shrink column to fit content*/    <-   that was the one I did miss 
}
```

**Comment by pmario** [comment]
>> Mat wrote
>> Actually, why is multiline editor in Ctrlpanel with a gray background in that case? This is how the Ctrlpanel looks on my machine (win, brave)
>
>Jeremy wrote
>Isn't that the default styling we use for all multiline text boxes? I don't think that there's anything special about control panel here.

There is a problem with the `vanilla/base` CSS. ... It sets `textarea` and `input` to `<<colour background>>` where it should set it to `background: <<colour tiddler-editor-background>>;` which is the setting it's meant to be.

**Comment by pmario** [comment]
@Jermolene ... 

- I'll create a PR that sets the GettingStarted tiddler to table settings shown in the image below. 
- The input and textarea background settings will be a different PR
- The fix for FireFox and Edge input selection will be a different PR too

The CSS will be as follows .. But I will have a closer look first, if there are existing settings we can use

```
table.tc-table-no-grid,
table.tc-table-no-grid th, 
table.tc-table-no-grid td {
  border: initial;
}

table.tc-table-no-grid td:nth-child(1) {
  width: 1%; 
}
```

![image](https://user-images.githubusercontent.com/374655/183313807-7e127aba-f2ef-4ca6-8eaa-2cf4e8f649e5.png)

**Comment by twMat** [comment]
It just struck me that this tiddler would even more appropriately be *titled* "Set up this TiddlyWiki" - i.e that mid-tiddler headline should be the tiddler title and we can skip the "GettingStarted" title all together. That way there's no need for any mid-tiddler headline which would further clean up the text.

Besides, it is a bit confusing that GettingStarted is something different on tiddlywiki.com

**Comment by Jermolene** [comment]
Hi @twMat 

> It just struck me that this tiddler would even more appropriately be _titled_ "Set up this TiddlyWiki" - i.e that mid-tiddler headline should be the tiddler title and we can skip the "GettingStarted" title all together. That way there's no need for any mid-tiddler headline which would further clean up the text.
> 
> Besides, it is a bit confusing that GettingStarted is something different on tiddlywiki.com

Both "HelloThere" and "GettingStarted" date back to the very early days of TWC (hence the CamelCase). I'd be a little concerned that by now they are embedded in documentation. For example, searching for "GettingStarted" at https://groktiddlywiki.com/read/ yields 5 tiddlers that link to it.

We can change things like this but we need to be aware that TiddlyWiki is not just an isolated thing; it is now embedded in a cloud of community tools and documentation, all with subtle dependencies between them.

**Comment by pmario** [comment]
>It just struck me that this tiddler would even more appropriately be titled "Set up this TiddlyWiki"

As Jeremy wrote, we can't change that name. The $:/DefaultTiddlers shadow contains GettingStarted as it's initial value. So as a plugin author you can be sure that users will see it if they import a new plugin into empty.html for testing. ... 

The plugin can contain a GettingStarted tiddler, that transcludes the "original" shadow tiddler and adds some stuff to it's own GettingStarted. .. 

```
<$transclude tiddler={{{ [all[shadows][GettingStarted]] }}} mode=block/>

My plugin getting started content
```

That's not perfect, if you use several plugins, but better than nothing. ... That mechanism could be improved, if we would add a list and define a tag that plugin authors could use to "register" in GettingStarted. ... BUT that would be a completely different PR:

**Comment by pmario** [comment]
@Jermolene ... My question is: Would you merge a PR that contains a new GettingStarted with the table formatting as shown in https://github.com/Jermolene/TiddlyWiki5/issues/1344#issuecomment-1207500258 ?

**Comment by Jermolene** [comment]
> @Jermolene ... My question is: Would you merge a PR that contains a new GettingStarted with the table formatting as shown in [#1344 (comment)](https://github.com/Jermolene/TiddlyWiki5/issues/1344#issuecomment-1207500258) ?

Yes those are worthwhile improvements.

**Comment by pmario** [comment]
@twMat ... I think this one can be closed because the GettingStarted improvement was merged already. And the consistent colouring of the input elements is a "by-product" of **make input and button elements consistent for all browsers #6910**, which also has been merged. 

At the moment I'm creating a bit more docs for a PR that will add some more table utility classes. So all the changes, that we made to the GettingStarted tiddler should be easy for users too, by adding some utility classes to the table. 

You do have a suggestion somewhere, where you discuss more possibilities to format with table wikitext syntax .. But I don't find it atm

**Comment by twMat** [comment]
@pmario - thank you. 

> more table utility classes ... so easy for users too

Ah, great idea!

>more possibilities to format with table wikitext syntax

This? #2941 - yes, that would make wikitext tables much more intuitive and easier to control.
