### ISSUE TITLE
Improve or remove quote syntax in filter steps

### ISSUE THREAD

**Issue by aelocson** [Jermolene/TiddlyWiki5#1346]
* https://github.com/Jermolene/TiddlyWiki5/pull/1294#issuecomment-68206051
* https://groups.google.com/forum/#!topic/TiddlyWikiDev/-ifnhFCXq58

The regular expression for parsing a filter step (filters.js: `operandRegExp`) accepts `"This"` and `'This'`, but it then treats the quotation marks as part of the operand.

It should either:
* strip the quotation marks from the operand, so that `"Hello There"` is equivalent to `[[Hello There]]`, or
* not bother parsing quotation marks as a special case at all.

**Comment by tobibeer** [comment]
:+1:  **not bother** — less syntax variants, less exeptions

**Comment by Jermolene** [comment]
There is one reason that supporting quotes might be useful: it allows tiddler titles to be referenced that would otherwise be illegal because they contain double square brackets.

**Comment by aelocson** [comment]
@Jermolene, that's true, and no other escape mechanism is available, so I think you're right.

@tobibeer, the syntax is fine so long as we document its purpose.

**Comment by aelocson** [comment]
I have a fix ready for this.
