### ISSUE TITLE
js macro with undefined return value throws global js error

### ISSUE THREAD

**Issue by tobibeer** [Jermolene/TiddlyWiki5#1348]
**demo**

http://tbdemo.tiddlyspot.com/#undefined%20macro%20return%20value

Not sure where to add that `||""` in the core code.

```
/*\
title: $:/.tb/macros/example.js
type: application/javascript
module-type: macro

<<undefined>>
\*/
(function(){
"use strict";
exports.name = "undefined";
exports.params = [];
exports.run = function() {
	return;
};
})();
```

**Comment by Jermolene** [comment]
JavaScript macros are defined as returning a string; returning any other data type is really a bug with the macro. Anyhow it's an easy fix, just coming up.

**Comment by tobibeer** [comment]
Thanks Jeremy, I understand the reasoning.
It's just that some things are nice to not show up as bugs. ;-)
