### ISSUE TITLE
Change z value for either toolbar, tagpill or title

### ISSUE THREAD

**Issue by twMat** [Jermolene/TiddlyWiki5#1362]
**[edit: it seems all problems described below can't be reproduced. Only what is illustrated in the first image, i.e concerning the *more* button dropdown. Note also that this is for the prerelease i.e 5.1.8]**

----
I attempted to correct this by manipulating e.g `.tc-tiddler-title` in `$:/themes/tiddlywiki/snowwhite/base` but cannot identify what controls this.

![stickytitle_vs_toolbar](https://cloud.githubusercontent.com/assets/4534056/5696840/919d62d8-99de-11e4-97ac-7df8606d3a76.PNG)
.
.
![stickytitle_vs_toolbar2](https://cloud.githubusercontent.com/assets/4534056/5696842/9b1bce6c-99de-11e4-86f2-3250c9d133e3.PNG)
.
.
![tagpill_vs_toolbar](https://cloud.githubusercontent.com/assets/4534056/5696847/e3909e3e-99de-11e4-87f1-5befa4cbacff.PNG)

**Comment by tobibeer** [comment]
I think the problem is very much the same as #1102... which is that the popup itself is rendered precisely where the button is, rather than somewhere "safely" in the dom, outside of the element flow.

In other words, so long as popups are rendered as elements of the story you will have this problem... I believe,

**Comment by Jermolene** [comment]
I think actually this is just the z-index we've got on `.tc-tiddler-title`, which was added so that the sticky titles work properly. It should be possible to finesse things so that it works though.

**Comment by twMat** [comment]
Ok, guessing you guys are ahead of me by now, but these are my findings so far:

Title (both in view and edit mode) have same z as pill dropdown, i.e 1000. Setting z to e.g 999 in `.tc-tiddler-title` makes the *pill* dropdown display nicely on top.

The *more* tool seems trickier. I cannot find any .tc-tiddler-toolbar but I do find the following. I add a z-index and try around but no change. Anyone has ideas of other places to look? :

* .tc-tiddler-controls button svg,
* .tc-tiddler-controls button.tc-selected svg 
* .tc-drop-down

However, I can't come up with a scenario where you would not want a popup to be on top which makes me wonder if there could be some kind of global value for popups? This would solve it except for when two popus overlap.

**Comment by tobibeer** [comment]
Is this fixed? I can't reproduce.

**Comment by twMat** [comment]
>@twMat Is this fixed? I can't reproduce.

Strangely, the answer seems to be both yes and no; 

I can't quite recall but I suspect it may only concern the *prerelease* which I missed to mention in the original post (but have now added). However, the only problem I can reproduce is illustration one, i.e the *more* toolbar button. The other two I cannot reproduce now (and ironically those are the ones I found out how to solve as described in previous post).

**Thus, for now I conclude the OP is revised to be what is seen in the first illustration.**

**Comment by pmario** [comment]
Did a short test. FF 35, win 8.1 -- the first image is an issue with http://tiddlywiki.com/prerelease/

**Comment by tobibeer** [comment]
Ah, was looking in the wrong spot. Sorry. Yes it is still an issue.

**Comment by twMat** [comment]
Because sticky is not official (...which I hope it will be), I'm closing this.
