### ISSUE TITLE
swarms of tiddlers — ad-hoc & packaged

### ISSUE THREAD

**Issue by tobibeer** [Jermolene/TiddlyWiki5#1364]
In the sense of [this discussion](https://groups.google.com/forum/#!topic/tiddlywiki/m6qGAjukiQs) and [this comment](https://groups.google.com/d/msg/tiddlywiki/m6qGAjukiQs/RQ6T1jo9-tkJ) and [reminded by Rich Shuhmaker](https://groups.google.com/d/msg/tiddlywikidev/7avA60bauFc/LwbwxaT72BoJ), allow authors and users alike to create, import and manage (at least) two types of **swarms of tiddlers**:
1. **ad-hoc**
   - an ad-hoc swarm can be bundled via the export tab
   - a link is provided encapsulating all tiddlers from the query draggable to another wiki for import
   - the json representation of the swarm is extended via some form of **swarm-origin** that indicates at each tiddler the wiki being the origin of the swarm
   - tiddlers also have the **swarm-spawned** field set to the current date
   - this link can also be otherwise generated via an appropriate widget / macro call
2. **packaged**
   - a packaged swarm is one with a plugin-like info wrapper that gives details as to the swarms contents
   - the actual tiddlers in the swarm are packaged as shadow tiddlers to a swarm
   - a later import of the same swarm will perhaps allow to compare versions
     - not sure if there's something equivalent for plugins
   - packaged swarms should be listed either in a dedicated tab in the control panel or under **plugins** in a dedicated section, preferably the former to make sharing swarms more top-level rather than buried in a long list of more technical extensions
### Related Terminology

https://groups.google.com/d/msg/tiddlywikidev/7avA60bauFc/wmiLG2G_qbAJ

**Comment by pmario** [comment]
@Jermolene ... feature request ?

**Comment by tobibeer** [comment]
Plugin territory, I think... Tinka translated to tobi-land.

**Comment by pmario** [comment]
You may have a look at bundler-plugin: https://wikilabs.github.io/editions/bundler/
