### ISSUE TITLE
Transclusion edit in "zoomin" story view edit results in scroll reset

### ISSUE THREAD

**Issue by calvertvl** [Jermolene/TiddlyWiki5#1365]
Given a transcluded tiddler via a template with edit capability (e.g. tag pills and some other read-only at the top, and various edit fields including lots of checkboxes to tag the transcluded tiddler that require you to scroll to see them all), any change to the transcluded tiddler causes the scroll position to reset to the top of the host tiddler.

This only occurs in the "zoomin" story view. I tested in 5.1.18 and it is still present for that view; the other two do not exhibit this issue in 5.1.18 (I did not test them in earlier versions).

The issue was introduced in 5.1.15, and I used git bisect to identify two major changes in refresh behavior as described below for the specific commits identified:

This commit makes the on-edit refresh "twitchy" (but no loss of position):
commit 9bbd599f5c85eebefba78fb4f088d00effcbb5fa

```
Refine refreshing of tiddler widget

We need to refresh if there is a change in the state that we copy to
variables.
```

This subsequent commit makes the on-edit refresh reset the scroll position:
commit d1bbe7253c135ceed138fd02c82b0f861d5dda6b

```
Remove flicker when resizing textareas

The `EditTextWidget.prototype.fixHeight()` function was defering its
work with `nextTick()`, which led to flickering on all browsers when
typing triggers a resize.
```

(removed some extra unneeded text)

**Comment by calvertvl** [comment]
Corrections to the above:
* my version numbers were screwed up. 5.1.5 introduced the issue, and it was still present in git (5.1.8-prerelease) when I checked.

Also, checking now it does apply to all views in 5.1.7, and I just checked the current master branch in git and it has the same problem.

* Scroll position reset is sometimes top of host tiddler, and sometimes top of page...if in zoomin mode with the menu/title shown at the top instead of the side, it will reset to the top of the page. It also seems to do this if it is the first tiddler in another mode.

* Edit action: this only appears to apply to checkboxes; the edit-text widget doesn't appear to exhibit the issue.

* Similar perhaps-related issue: when editing a (long) tiddler in zoomin view, right-clicking in the edit area sometimes resets scroll to the top of the tiddler. This does not apply to the other views.

**Comment by Jermolene** [comment]
@calvertvl apologies for the delayed response.

What are the simplest steps to reproduce the problem on tiddlywiki.com?

**Comment by pmario** [comment]
@calvertvl .. still a bug?

**Comment by tobibeer** [comment]
@calvertvl: possible to create a MTC (a minimal test case)? Otherwise, if no longer relevant, please close. (@Jermolene)

**Comment by pmario** [comment]
@Jermolene ... 3 years no info about how to reproduce. ... IMO we need to close it.

**Comment by Jermolene** [comment]
Thanks @pmario
