### ISSUE TITLE
Closing window when editing a post causes the draft to be empty when reloaded - nodejs

### ISSUE THREAD

**Issue by psylinse** [Jermolene/TiddlyWiki5#1370]
Under nodejs, when I:
- start editing a post 
- close the window without saving
- Reopen the window

The draft of the last edited post is completely empty. If I save it, it nukes all of my data. If I hit the trashcan, it deletes the draft and the original. Canceling works like expected.

What should the expected behavior be? I'm happy to take a stab at this. Sorry if this is duplicated, I tried to find a relevant issue. I did not test under HTML only wikis.

Here is a video showing the issue: https://www.youtube.com/watch?v=_R05R5bPdD4

**Comment by tobibeer** [comment]
What's perhaps missing is a "save as draft" button that commits the draft tiddler and closes it.

**Comment by jetaggart** [comment]
Not quite. My use case is more of: I keep a tiddler open for a while, such as keeping notes for work. Sometimes I close a lot of tabs at once and nuke my tiddler tab. When I come back the draft is in a broken state. It has no content. If I save that I lose everything, if I dismiss it, I lose whatever I typed between the last time I saved. 

I hope that makes sense.

**Comment by pmario** [comment]
There should be a warning, that you want to close an unsaved TW tab. ... If you ignore the warning, that's your decision. As a result you loose content.

It would be possible, to temporarily save the content in the browser local storage but this is a problem for encrypted wikis. There has been some discussion about this issue but imo no consensus on how to solve it.

**Comment by jetaggart** [comment]
I've added a video to the issue description showing the issue. Youre right, it does warn, if you've changed text. In the video, it doesn't warn (I didn't edit anything) and when I come back, *all* of the content is gone. This is true if I edit, ignore the warning (i.e. system crash), and come back.

**Comment by tobibeer** [comment]
The video makes the problem so much more transparent. Good job.
Why would it be empty though? Smells like a bug.

**Comment by pmario** [comment]
ok. you didn't mention, that you use a nodejs server in the background. .... This is a completely different system. 

With a node js server probably every keystroke is sent back to the server. 
So the draft should always be saved
Your editor is codemirror. ... So it seems there is a syncing problem. 

first try: 
- remove the codemirror plugin from your tiddlywiki.info file
- restart the server
- try to reproduce the problem again

may be initializing cm editor is the problem here.

**Comment by pmario** [comment]
@psylinse ... This issue is 3 years old. ... Do you still have this problem with latest version?

Please check and close if the issue is gone.

**Comment by psylinse** [comment]
I have not used tiddlywiki for some time, so as far as I know it's not an issue. I'll go ahead and close this issue, thanks!
