### ISSUE TITLE
allow $list widget in $button, $select, etc...

### ISSUE THREAD

**Issue by tobibeer** [Jermolene/TiddlyWiki5#1371]
For action widgets like a ButtonWidget or a SelectWidget, allow to use the **ListWidget** as a child to, in turn, contain a variable number of ActionSetField widgets which consecutively fire when the action is triggered. Perhaps the refresh can be delayed until after all actions fired.

**Comment by buggyj** [comment]
The propagation of invokeActions thru the widget tree should be programmable - i.e.  controllable by a widget parameter.

**Comment by tobibeer** [comment]
@buggyj, what's precisely do you mean by "invokeActions"? Can you give an example (process)?

**Comment by buggyj** [comment]
@tobibeer 
the button widget calls the invokeActions widget method ie
`
		if(self.invokeActions(event)) {
			handled = true;
		}
`
which results in calls to invokeAction() in the child action widgets.  If the list widget is to be used then it must propagate this call like so
`
ListWidget.prototype.invokeAction = function(triggeringWidget,event) {
	this.invokeActions(event);
	return true; // Action was invoked
};
`
and the same will apply to the transclude widget (as it will be used with a template to create the list of action widgets).

So I am saying that there should be a parameter for the List and Transclude widgets to gate this behavior like so:
`
`
ListWidget.prototype.invokeAction = function(triggeringWidget,event) {
	if (this.getAttribute("propgateActions")  this.invokeActions(event);
	return true; // Action was invoked
};
`

**Comment by ng110** [comment]
I have also been looking at this, but rather than changing each type of widget to propagate the action, I have modified the invokeActions() function in the prototype widget.js so that it recurses through all descendant widgets.  I'm not sure if there's a reason why you would want to be more discriminating about how the action is propagated.  I haven't fully tested yet but so far it seems to work.  You do still need to add the original invokeActions() call to the triggering widget though.  Currently, only the button widget has this.

As well as refreshing after all the actions, you probably need to refresh before the actions, otherwise the change of state produced by the triggering widget doesn't get used by the action widgets.  e.g. an action-setfield inside a select widget doesn't know about the new selected value when it is applying the setfield action.

**Comment by tobibeer** [comment]
@buggyj @ng110 — thanks for the details, got it now

> you probably need to refresh before the actions, otherwise the change of state produced by the triggering widget doesn't get used by the action widgets

good point

>>   if (this.getAttribute("propgateActions")  this.invokeActions(event);

> I'm not sure if there's a reason why you would want to be more discriminating about how the action is propagated.

Me neither, why / when not propagate?

If there was an action widget in an element that supports propagation, e.g. list and reveal, then it should fire when **invokeActions** is called on the list or reveal by an outer widget.

What's more important to me is that **invokeActions** doesn't just look at immediate children in the dom, skipping any potential html wrapper. So, the question is one of execution order, although I'd think it's a simple, traverse descendants first, then siblings.

@ng110 — Would you perhaps make a tentative pull request that we might discuss / improve on?

**Comment by ng110** [comment]
@tobibeer:  I'm new to Github (not a developer) and was just trying to figure out how to do a pull request for this when I came across this discussion.  I have messed things up a bit by putting it on my master branch, but I'll make the pull request anyway...

**Comment by tobibeer** [comment]
Don't pull on master, it will most surely be rejected. Instead, save those changes elsewhere, create a branch — possibly referencing this issue's number in the branch-name — and then save those changes to the branch.

**Comment by ng110** [comment]
Too late I'm afraid - I already did.  I knew I should have stuck with a simpler way to submit this!  I'll now have to figure out how to clean up my master branch.

Anyway, you can have a look at the code for now at least.

**Comment by tobibeer** [comment]
anyhow, as for this pull request, I'm pretty sure you can close it, because it won't be accepted like this ...not for code quality, but for the fact that I don't think Jeremy will try to merge master with master, chances are too great that the heads will be off and then it's a mess

**Comment by buggyj** [comment]
>> if (this.getAttribute("propgateActions") this.invokeActions(event);
I'm not sure if there's a reason why you would want to be more discriminating about how the action is propagated.

**Comment by tobibeer** [comment]
> I have player widgets that are action-widget that also have buttons with action-widgets as children.

I think right there is your issue. I don't think a ui, i.e. a player, should be an action widget. So, conceptually there might a problem in that approach. Why did you design it that way to begin with?

**Comment by buggyj** [comment]
@tobibeer 
> I think right there is your issue. 

the issue is backwards compatibility, my plugin is just an example of want would happen if there is not backwards compatibility.

> I don't think a ui, i.e. a player, should be an action widget. So, conceptually there might a problem in that approach. Why did you design it that way to begin with?

I think that talking about design decisions is instructive (for all involved) and am happy to talk about the approach I took in this case, but it is irrelevant to this thread. Maybe something for the forum?

**Comment by tobibeer** [comment]
The thing is, it seems you require the propagation to be explicit. However, the cases for which this seems required are... let's say... very few exceptions, if only one. I personally think there should be room for breaking things... especially when in the fringes of use-cases... use-cases that have been out of the scope for the core as it was. That's how customizations may go, same for modified core templates. Those things may change and I think they should.

**Comment by buggyj** [comment]
like I said, I don't mind modifying my code. Unfortunately it seems that we will have to wait at least a couple of weeks for a decision.

**Comment by tobibeer** [comment]
We'll do, if you feel like discussing the details of your player a little more in the dev group, I'll gladly join. Or, you open up another issue here. Same, same.

**Comment by buggyj** [comment]
I have just reviewed changes to my widgets I would need if invokeAction are propagated - there are none!  I was thinking that my actions widget would also propagate invokeAction but they implement invokeAction() which means they override the default that would  be defined in the Widget widget.

In short I was wrong about my widgets breaking.

**Comment by tobibeer** [comment]
@buggyj ...after a bit more thinking, I believe it's a good thing to be explicit about propagating actions, however, I would only set it for the outermost widget, e.g. the button... which will have it search and fire all actionable widgets it contains.

**Comment by pmario** [comment]
@tobibeer ... there is a PR associated, that got merged. Can we close the issue?

**Comment by tobibeer** [comment]
Thanks @pmario. Closed.
