### ISSUE TITLE
draw on transparent image rather than the original

### ISSUE THREAD

**Issue by tobibeer** [Jermolene/TiddlyWiki5#1377]
discussion: https://groups.google.com/d/msg/tiddlywiki/MsLl6vnhzwE/DM1rYLDUF64J

At image tiddlers, rather than be able to directly draw over them — which doesn't seem a very practical idea anyway — provide a "draw on me" type of button.

This creates another tiddler with the ability to draw on a transparent overlay instead, showing the related image below in a see-through manner.

Not sure how and if it's possible to create a dynamically sized transparent image of a given size as a canvas, though.

**Comment by pmario** [comment]
@Jermolene ... "feature request"?

**Comment by tobibeer** [comment]
I think such a feature should be explored first in a plugin manner.
