### ISSUE TITLE
Saving | Problem setting the Backups-URL

### ISSUE THREAD

**Issue by elEglon** [Jermolene/TiddlyWiki5#1387]
Trying to set up TiddlyWiki 5.1.7 on my server I run into the following problem:
As described I prepare the store.php as needed and store it in the same folder as my TiddlyWiki (index.htm). When I open the Saving-Tab I can fill in the Wiki Name. While filling this field, the Backups-Field automaticly gets filled with http://"Wikiname".tiddlyspot.com/backup. Trying to modify the index.html and embedding my URL static (http://www.mywebsite/wiki/store.php) doesn't work either.
Any kind of hint is very appreciated, thank you
Eglon

**Comment by tobibeer** [comment]
See if you get it working following these instructions:

http://tb5.tiddlyspot.com/#store.php

**Comment by elEglon** [comment]
Thank you a lot tobibeer!
Protecting my folder via .htpasswd caused my problem. But as described, using 5.1.7 you are not able to set your own Server URL?
Thank you
Eglon

**Comment by tobibeer** [comment]
I just tested it and it all works just fine for me.

Make sure that **wikiname** and **password** form a valid user as defined at the beginning of **store.php**.

Here's what worked for me...

http://goto.bplaced.net/tw5/5.1.7.html#%24%3A%2FControlPanel

Let me know if there is anything wrong about the instructions in that other post.

As for using a **.htaccess**, I'm not sure how that works for uploading. Does it prompt you again for another username and password?

**Comment by elEglon** [comment]
Thank you again!
I can see, that you've got other settings (Backups: relative to Server URL).
I use the store.php V1.6.1

Would you please provide me with the first lines of the storage.php?

I use:

$AUTHENTICATE_USER = false;	// true | false
$USERS = array(
	'User1'=>'secret1', 
	'User2'=>'Pass2', 
	'whatever3'=>'Pass3'); // set usernames and strong passwords
$DEBUG = false;				// true | false
$CLEAN_BACKUP = true; 		// during backuping a file, remove overmuch backups
$FOLD_JS = true; 			// if javascript files have been expanded during download the fold them
error_reporting(E_ERROR | E_WARNING | E_PARSE);

Thank you,
Eglon

PS Habe versucht, Dich zu erreichen; Dein Kontaktformular lässt mich aber keine Zahl finden, die ich zur Freigabe der Mail nutzen könnte. Habe notgedrungen eine Nachricht über Facebook abgesetzt.

**Comment by tobibeer** [comment]
Sorry, that contact form is broken as I accidentaly let that free hosting run out ...haven't found a backup yet, might not even have any. Ouch. ^^

Version is **1.6.1**, too:

```
$AUTHENTICATE_USER = true;	// true | false
$USERS = array(
	'tb5'=>'XXXXXXXX',
	'UserName2'=>'Password2', 
	'UserName3'=>'Password3'); // set usernames and strong passwords
$DEBUG = false;				// true | false
$CLEAN_BACKUP = true; 		// during backuping a file, remove overmuch backups
$FOLD_JS = true; 			// if javascript files have been expanded during download the fold them
```

Are you sure you have set up the access permissions for the script and backup folder correctly?

**Comment by elEglon** [comment]
Strange,

same here (tried $AUTHENTICATE_USER both ways).

The permissions are set as described.
Everything works, but the settings for the Backups still have to be set static.
I'll have to compare the download of store.php and empty.html with my data.

Thank you again!

Eglon

**Comment by excogitation** [comment]
@elEgion have you found a solution? According to tobibeer it should be working but I seem to have run into the same problem.

Does your console also show:
POST https://user:password@test.de/wiki/ 403 (Forbidden)

**Comment by elEglon** [comment]
@excogitation step by step:

I took the main file from here: http://tiddlywiki.com/ (empty.html V 5.1.7)
I took the store.php (V 1.6.1) from here: https://code.google.com/p/bidix/source/browse/trunk/TiddlyHome/_th/lib/store.php

My PHP Version: 5.3

I changed line 4261 in empty.html from "http://$(userName)$.tiddlyspot.com/backup/" to the link to my store.php

I hope, that will help you.

**Comment by tobibeer** [comment]
@elEglon, please don't change or refer to the underlying html like that. Instead, take a look at what tiddler you want to modify. In this case the [ShadowTiddler](http://tiddlywiki.com/#ShadowTiddlers) **$:/core/ui/ControlPanel/Saving**. The way you changed the underlying html, TiddlyWiki will overwrite it with the next upgrade. Perhaps you want that, probably you don't.

Also, be aware that the changes you made were purely cosmetic. They did not change any configuration. For the backup directory, what matters is what is defined at **$:/UploadBackupDir**, thus what you enter into the input field for **Backup Directory**.

Whatever is displayed up at **Backups** is pretty irrelevant. Well, it's relevant for you to be able to click a link and then easily go to that url. I guess that's its purpose.

To fix this for a custom store.php, there could be some js macro that...

1. uses a defined url — **Server URL**
2. truncates the file bit — **store.php**
3. extends it with a relative path — **Backup Directory**
4. outputs a thus constructed target — **Backups**
    * eventually shown as a link

**Comment by excogitation** [comment]
Changing the text that is shown in the backups row won't get my problem fixed.

It seems to be a problem with my shared host settings as I always encounter 403 using the POST method with php scripts.

**Comment by tobibeer** [comment]
Did you set the access rights to [store.php](http://tb5.tiddlyspot.com/#store.php) and the backup folder correctly?

**Comment by excogitation** [comment]
@tobibeer I even tried with 777.

**Comment by excogitation** [comment]
It turns out in my case it's a modsec configuration my hoster has deployed against injection attacks. I'll eventually get it resolved. Thanks for the help.

**Comment by pmario** [comment]
@excogitation  ... the issue seems to be resolved. .. please close!

**Comment by tobibeer** [comment]
@excogitation / @elEglon: any final (server) changes you can report on that made it work for you? Otherwise, perhaps give it another try at a differerent hosting.

@Jermolene : Close?

**Comment by pmario** [comment]
@Jermolene .... bump close?

**Comment by Jermolene** [comment]
Thanks @pmario
