### ISSUE TITLE
conditional filter

### ISSUE THREAD

**Issue by tobibeer** [Jermolene/TiddlyWiki5#1391]
Provide a way to evaluate a filter run and — if the resulting list would be empty — fallback to the next run...

```
<<list-links filter:"[all[current]tags[] || [[foo]]">>
```

In other words, if the left hand expression yields an empty list, use the right hand expression. This could theoretically be chained, so that...
- `filter= "<run1> <run2> || <run3> || <run4> <run5>"` would return the list after...
- `<run2>`, provided it was not empty ...if it was empty...
- `<run3>` would be performed with respect to `<run1>`, if that was empty as well, then
- `<run4>` would be performed on the list of `<run1>` and eventually return nothing if also empty
- `<run5>` would be performed on whichever output of the above would give

This can be useful to avoid having to use the **SetWidget** so as to evaluate a filter and then conditionaly do pretty much the same thing twice depending on whether or not a filter yields tiddlers.

Perhaps difficult to grasp, but if you want to see an example where this would help, take a look at the variable `addtags` in [tagfilter](http://tagfilter.tiddlyspot.com), which is supposed to check whether there are any tags to be added, but fails to do so, as the second run of the filter tries to create an intersection with a list that is obviously empty when we start. So, in that case, I don't want the second run to kick in at all, but rather fall back to using something else.

**Comment by Jermolene** [comment]
Thanks @tobibeer I think this is a good idea.

**Comment by felixhayashi** [comment]
maybe use double "|" (||) since in almost all languages a single in a conditional expression means the right side is evaluated no matter what the left result was. Also in unix a single "|" is used as pipe symbol to pipe the input into the right command.

**Comment by tobibeer** [comment]
@felixhayashi makes total sense, I would not mind a different symbol, what's important is the function

besides, `||` semantically works much better, standing for OR in JavaScript ...which applies neatly

modified the OP accordingly

**Comment by felixhayashi** [comment]
>  what's important is the function

right - and it is really useful imo!

**Comment by Jermolene** [comment]
This is actually a prefix for a run of filters, like "+" and "-", and not a filter operator per se. That may make it more consistent to use a single character.

**Comment by felixhayashi** [comment]
Well, it is up to you to decide - I just wanted to mention that there are two wide spread connotations coming with a single "|" and it wouldn't cause much trouble parsing two pipe symbols instead of one... Also, I didn't think of it as a prefix - it looks a bit strange then "  |[  ". I rather envisioned it like tobi put it: "[all[current]tags[] || [[foo]]". This makes it more recognizable, since the double "||" allow many users to grasp the concept fast as boolean expressions are widely spread.

In any case, the idea is nice.

**Comment by tobibeer** [comment]
@Jermolene 

> This is actually a prefix for a run of filters, like "+" and "-", and not a filter operator per se.

It's surely like the `+` or `-` symbols. Do we actually have a name for those? I would not call them prefixes such as `!`, because the latter refers to the run but `+` and `-` refer to an operation with respect to a number of runs. Hence, I don't think there is an actual need for a single letter symbol.

In JavaScript, you can also do...

`1 + 1`

and

`1 || 1`

Rather than...

`1 | 1`

**Comment by twMat** [comment]
IMO this is implemented now with `~`
@tobibeer  Close issue?

**Comment by Jermolene** [comment]
Thanks @twMat
