### ISSUE TITLE
Cannot import katex plugin

### ISSUE THREAD

**Issue by tgirod** [Jermolene/TiddlyWiki5#1393]
What I did:

- open the KateX tiddlywiki page
- drag the `$:/plugins/tiddlywiki/katex` link into my tiddlywiki -> `$:/Import` opens with one import in queue
- click [import]

Now, when I try to use katex syntax, nothing happens. If I use `<$latex>` it says "undefined widget". I went to the control panel to look at the plugin. It is there, and there is a list of shadow tiddlers contained by the plugin, but all those links point to non-existant tiddlers (which is not the case on the katex page).

I think I followed the instructions. Am I doing something wrong ?

**Comment by gernert** [comment]
Refresh your TW.

**Comment by tobibeer** [comment]
...and then close this issue. ^^

**Comment by tgirod** [comment]
okay my mistake. Maybe a word saying that the plugin won't work until the page is refreshed could help ;)

**Comment by tobibeer** [comment]
It's all there: http://tiddlywiki.com/#Plugins ^^
