### ISSUE TITLE
Why the instructions to use TW with node webkit have been moved?

### ISSUE THREAD

**Issue by danielo515** [Jermolene/TiddlyWiki5#1397]
They used to be on tiddlywiki.com. I went crazy until I decided to check it out the developer edition.
I found them here: 
http://tiddlywiki.com/dev/#TiddlyWiki%20on%20node-webkit

Why are those instructions removed from the main site? They are still referenced on http://tiddlywiki.com/#node-webkit

**Comment by tobibeer** [comment]
I guess because it's entirely developer centric.

**Comment by danielo515** [comment]
Since this seems to be an arbitrary decision that will not be rolled back, I'm closing the issue.
