### ISSUE TITLE
sort by search-term precedence

### ISSUE THREAD

**Issue by tobibeer** [Jermolene/TiddlyWiki5#1399]
Create a new sort filter that sorts tiddlers first listing those whose title starts with a given string, e.g.:

```
[tsort:foo[]]
```
1. first lists all tiddlers starting with `foo`, sorted
2. then all others, sorted

And then...

```
[tsort:foo[somefield]]
```

In the sense of a more generic sort filter with option suffixes that can be combined, perhaps it could be:

```
[sort:cs:^foo[field]]
```

...i.e. sort case sensitively whereas all starting with `foo` first.

The way to trigger it could be some some enclosing markup, rather than some dedicated suffix.

**Comment by pmario** [comment]
IMO this is achieved by: http://tiddlywiki.com/#%24%3A%2Fcore%2Fui%2FDefaultSearchResultList

```
\define searchResultList()
//<small>{{$:/language/Search/Matches/Title}}</small>//

<$list filter="[!is[system]search:title{$(searchTiddler)$}sort[title]limit[250]]" template="$:/core/ui/ListItemTemplate"/>

//<small>{{$:/language/Search/Matches/All}}</small>//

<$list filter="[!is[system]search{$(searchTiddler)$}sort[title]limit[250]]" template="$:/core/ui/ListItemTemplate"/>

\end
<<searchResultList>>
```

**Comment by tobibeer** [comment]
I believe the point to doing it in one filter operation was to only have one output list, not two, avoiding duplicate entries, where you might even end up seeing the same 10 titles twice.

**Comment by pmario** [comment]
I'm using https://wikilabs.github.io/editions/advanced-search-plus/ plugin. ... Which desperately needs some documentation :) ... Or I'll create a video, which may be less work. 

It lets me save serach results in new tabs. Using the "filter" tab allows reqexps, so I can pretty much do what I want and save the resulting list for later use.

**Comment by pmario** [comment]
This is my way to say: "plugin terretory" ;)

**Comment by tobibeer** [comment]
Surely, it can be explored plugin-wise. But search is quite a core issue.

There's also an older PR that asked for specifying a custom number of fields. So, ideally, it should be possible to define a single search filter with all the desired options.

**Comment by Jermolene** [comment]
The OP seems like plugin territory as things stand, but I'd be interested in figuring out ways to improve the core primitives to make it possible to do it. It seems that what might be needed here are operators to merge lists in various ways (eg to keep or discard duplicates).

**Comment by tobibeer** [comment]
I'll see what plugin I can come up with.
