### ISSUE TITLE
reveal depending on character length or value

### ISSUE THREAD

**Issue by tobibeer** [Jermolene/TiddlyWiki5#1400]
Reveal content only when...
- the character length
- the numeric value

...of **state** (or **default**) is of a given value compared to perhaps a new parameter for numerics called **value** (or **text** if must be).
### Possible Markup

**len**

```
<$reveal type="len" default=<<foo>> value="3">
only when foo has 3 characters
</$reveal>

<$reveal type="len gt" default=<<foo>> value="2">
only when foo has more than 2 characters
</$reveal>

<$reveal type="len lt" default=<<foo>> value="10">
only when foo less than 10 characters
</$reveal>

<$reveal type="len ge" default=<<foo>> value="3">
only when foo has 3 or more characters
</$reveal>

<$reveal type="len le" default=<<foo>> value="3">
only when foo has 3 or less characters
</$reveal>
```

**val**

```
<$reveal type="val" default=<<foo>> value="3">
only when numeric value of foo is 3
</$reveal>

<$reveal type="val gt" default=<<foo>> value="2">
only when numeric value of foo is greater than 2
</$reveal>

<$reveal type="val lt" default=<<foo>> value="10">
only when numeric value of foo is less than 10
</$reveal>

<$reveal type="val ge" default=<<foo>> value="3">
only when numeric value of foo is 3 or greater
</$reveal>

<$reveal type="val le" default=<<foo>> value="3">
only when numeric value of foo is 3 or smaller
</$reveal>
```

By default, if the value is non-numeric the reveal should hide. There could be another identifier to interpret non-numerics as a number, like so.

```
<$reveal type="val le 100000" default=<<foo>> value="3">
only when numeric value of foo is 3 or smaller, interpreted as 100000 when non-numeric
</$reveal>
```

**Comment by pmario** [comment]
can be achieved with: minlength operator: http://tiddlywiki.com/#minlength%20Operator
as used in eg: http://tiddlywiki.com/#%24%3A%2Fcore%2Fui%2FAdvancedSearch%2FStandard

```
<$list filter="[{$:/temp/advancedsearch}minlength{$:/config/Search/MinLength}limit[1]]" emptyMessage="""<div class="tc-search-results">{{$:/language/Search/Search/TooShort}}</div>""" variable="listItem">
```

**Comment by tobibeer** [comment]
We should definitely introduce this in a few spots, most prominently for adding tags. Imho, the popup should not show anything at all w/o a single title typed. I have half as many tags as there are tiddlers and now imagine the time it takes to just see that one open w/o any constraints.

**Comment by tobibeer** [comment]
Min being the crucial usecase, I will consider puting the rest of the requirements into a plugin. So, closing.
