### ISSUE TITLE
Codemirror error when typing < or >

### ISSUE THREAD

**Issue by danielo515** [Jermolene/TiddlyWiki5#1406]
How to reproduce the problem
- Install the codemirror plugin in any empty tw5 
- Create the example $:/config/CodeMirror file that appears in first place
- Save and reload
- Create a new tiddler, hit `i` (for enter in edit mode) and then type `>` or `<`
- A nice error appears

**Comment by pmario** [comment]
It seems you have the vi mode active. ... Do you have a version somewhere, that we can use. So we don't need to build our own, that is different to yours.

**Comment by danielo515** [comment]
Yes, the vim mode is active of course. As I said, the first configuration example includes the vim mode selected.

Anyway, here you have a minimal configuration example:

https://googledrive.com/host/0B-USg0ow4LCZVjFTQ0lLVGtOODg/empty_codemirror.html

**Comment by sukima** [comment]
I too had VI mode issues with CodeMirror; it wasn't just TiddlyWiki.

Sadly, I eventually gave up under the assumption that the CodeMirror folks are coveted Emacs lovers and just use a browser plugin to open VIM as an external editor instead.

So far no VI implementation seems to compare to VIM so I always go back to it even if it means lots of copy/pasting.

**Comment by pmario** [comment]
There's probably a problem, if both keyboard handlers are included. 

      "$:/plugins/tiddlywiki/codemirror/keymap/vim.js",
      "$:/plugins/tiddlywiki/codemirror/keymap/emacs.js"

For me the plugin doesn't do anything useful. eg. save, ..

**Comment by danielo515** [comment]
Hello mario, did you checked the example I provided? I removed the emacs requirment and it still failing. The plugin does useful things such as vim keybindings.

**Comment by lsfxz** [comment]
This can be (somewhat) fixed by doing what https://github.com/codemirror/CodeMirror/commit/f97df90d832fa523d26f26131e6646567f5a83d0 does:
add 
`if (!keyName) { return; }`
in $:/plugins/tiddlywiki/codemirror/keymap/vim.js, line 4128 before
`function onKeyFound() {`

**Comment by pmario** [comment]
@danielo515 ... codemirror has be rewritten in 5.1.16. ... I did test this issue, and it seems to be gone now. .. please close

**Comment by BurningTreeC** [comment]
@Jermolene, I believe this issue can be closed

**Comment by Jermolene** [comment]
Thanks @BurningTreeC
