### ISSUE TITLE
nsort and nsortcs fail given non-numeric values

### ISSUE THREAD

**Issue by aelocson** [Jermolene/TiddlyWiki5#1410]
The `nsort` and `nsortcs` filter operators are documented as differing in their case-sensivity with regard to non-numeric fields. But in practice, if any of the fields they encounter is non-numeric, both filters simply output their input unchanged.

This seems to be because `wiki.sortTiddlers` puts too much faith in its `isNumeric` parameter, allowing its comparison function to return a nonsensical result of `NaN`.

**Comment by tobibeer** [comment]
What am I doing wrong here?

```
if(isNumeric || !(isNaN(a) && isNaN(b))) {
	a = Number(a);
	b = Number(b);
	return
		isNaN(a) && !isNaN(b) ? (isDescending ? -1 : 1) :
		!isNaN(b) && isNaN(a) ? (isDescending ? 1 : -1) :
								 isDescending ? b - a : a - b;

````

**Comment by aelocson** [comment]
You're testing whether `a` and `b` are NaN before you've converted them to something that might be NaN.

I think you need to do a precheck to determine the nature of `a` and `b` and adjust the state accordingly:

		if(isNumeric) {
			var aNumber = Number(a);
			var bNumber = Number(b);
			if(isNaN(aNumber) === isNaN(bNumber)) {
				isNumeric = !isNaN(aNumber);
			} else {
				isNumeric = false;
				if(isNaN(aNumber)) {
					b = "";
				} else {
					a = "";
				}
			}
		}
		if(isNumeric) {
			a = aNumber;
			b = bNumber;
			return isDescending ? b - a : a - b;
		} ...

This succeeds in sorting the non-numeric values alphabetically and shunting them all to the end, but it still doesn't produce any difference in the output of `nsort` and `nsortcs`. That's because the comparison is being done by `localeCompare`, which requires an extra parameter to make it case-sensitive.

**Comment by tobibeer** [comment]
I think you may be mistaking the idea behind **isNumeric**. It is a flag that indicates the sort module to treat the values as numerals. It is not a state for you figure out if something is a numeral. Of course, that's what needs doing, but isNumeric is a mere parameter to the sort algorhithm that says "numbers first".

**Comment by aelocson** [comment]
Sorry, I don't quite understand. Maybe I *am* mistaken!

But surely the primary purpose of `isNumeric` is to sort `9` before `10` (as opposed to placing `10` before `9` as in a pure string sort).

The problem arises when one or more of the items to be sorted is not numeric. Where should it be placed in the order? The fact that `nsort` and `nsortcs` exist as two separate operators implies that the system is intended to do at least *something* in this situation.

The existing documentation never shows more than one non-numeric item per example, so we can't deduce what's *meant* to happen. However, it makes sense to divide the items into two partitions – numeric and non-numeric – and sort each partition separately, with the numeric partition appearing before the non-numeric partition in the filter's output. That's what my suggestion above was trying to do.

Having that said, I made a mistake: one call to the anonymous sort function can change the value of `isNumeric` for the subsequent calls. So the anonymous sort function needs to start by taking a local copy of `isNumeric`, and must then touch only the copy.

**Comment by tobibeer** [comment]
> The existing documentation never shows more than one non-numeric item per example, so we can't deduce what's meant to happen.

Non-numerics should be placed after numerics, imho ...at least, that's what the examples show and what I tried to implement.

> one call to the anonymous sort function can change the value of isNumeric for the subsequent calls

Again, **isNumeric** does not refer to or store whether the values actually are numeric, it is merely a flag telling the sort operation to put numerics first, sorted, the rest alphabetically as usual, imho.

Testing if **a** or **b** are numerics is what I tried in the above code. That's all that should be needed as far as I can see... however it doesn't work.

As said elsewhere, I don't like that **nsort** and **nsortcs** are independent filters, they should be one sort filter with an **n** and a **cs** option.

**Comment by tobibeer** [comment]
Ok, now I tried...

```
var x,y,self = this;

//...

x = Number(a);
y = Number(b);
if(isNumeric || !(isNaN(x) && isNaN(y))) {
    return
        isNaN(x) && !isNaN(y) ? (isDescending ? -1 : 1) :
        !isNaN(x) && isNaN(y) ? (isDescending ? 1 : -1) :
                                 isDescending ? y - x : x - y;
```

...but it's still not sorting correctly.

**Comment by tobibeer** [comment]
Slowly getting there, but still not working...

```
x = Number(a);
y = Number(b);
if(isNumeric && (!isNaN(x) || !isNaN(y))) {
    return
        isNaN(x) && !isNaN(y) ? (isDescending ? -1 : 1) :
        !isNaN(x) && isNaN(y) ? (isDescending ? 1 : -1) :
                                 isDescending ? x - y :  y - x;
```

It's quite bugging me that I can't figure this seemingly simple thing out. ^^

Taking a break.

**Comment by aelocson** [comment]
> Try with tiddlers like: 1, 0100, 100, 01.

The problem with those is that `0100` and `100` have the same numerical value, so the order in which they sort is unpredictable.

> Non-numerics should be placed after numerics, imho

I entirely agree.

> Again, isNumeric does not refer to or store whether the values actually are numeric, it is merely a flag telling the sort operation to put numerics first, sorted, the rest alphabetically as usual, imho.

Sorry, I've confused you by reusing the `isNumeric` parameter for a different purpose within the anonymous function, i.e. to keep track of which of the two partitions the current pair of items are in.

The approach you're taking looks simpler, but at the moment it's not moving non-numerics to the end at all.

**Comment by tobibeer** [comment]
> The problem with those is that 0100 and 100 have the same numerical value, so the order in which they sort is unpredictable.

But that's not the problem I'm having. The problem I'm having when testing seems to be that no sorting appears to be happening whatsoever.

**Comment by aelocson** [comment]
Your latest update is only initialising `a` and `b` when the sort field is *not* the title.

**Comment by aelocson** [comment]
No, ignore me, that's total nonsense. I'm trying to do too many things at once, which means I don't have time to investigate this just at the moment. I'll try and get to it later if you haven't figured it out in the meantime.

**Comment by aelocson** [comment]
Bizarrely, the other thing I was trying to do has suddenly gone away, so I've popped back to this.

Your code contains two mistakes:

* You've got `isDescending ? x - y :  y - x` instead of `isDescending ? y - x : x - y`.
* You've got `return` on a line of its own, triggering semicolon insertion.

**Comment by aelocson** [comment]
And I was entirely wrong about `localeCompare` needing an extra parameter, of course. I somehow overlooked the calls to `toLowerCase()`.

**Comment by tobibeer** [comment]
Ok, I pushed an updated and it seems to work now.

One thing I find rather confusing is this...

```
a = "Foo";
b = "bar";
console.log(a == b ? 0 : a < b ? -1 : 1);
console.log(a.localeCompare(b));
```

ouputs...

```
-1
1
```

Shouldn't both yield the same results? [developer.mozilla.org/localeCompare](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/localeCompare)

**Comment by aelocson** [comment]
That's down to the default values of the `sensitivity` and `caseFirst` options to `localeCompare`.

**Comment by tobibeer** [comment]
It's just that I thought that's what case-sensitivity was for, but I guess I was wrong.

**localeCompare** does...

```
["A","B","a","b"].sort(function(a,b){
    return a.localeCompare(b)
});

a
A
b
B
```

Whereas traditionally it would have been...

```
["A","B","a","b"].sort(function(a,b){
    return a == b ? 0 : a < b ? -1 : 1;
});

A
B
a
b
```

I mean, I prefer the local compare variant because the other one is really hard to understand for a lay-person.

**Comment by aelocson** [comment]
Absolutely, especially once you go beyond the bounds of ASCII characters. The traditional method fails abysmally with Unicode.
