### ISSUE TITLE
Change info alerts for save to server

### ISSUE THREAD

**Issue by twMat** [Jermolene/TiddlyWiki5#1411]
The automatic saving to server (or at least tiddlyspot) first gives an alert "Starting to save wiki" which fades pretty fast. After some seconds comes alert "Saved wiki". Local TWs only get the immediate and single alert; "Saved wiki"

This server alerting is unfortunate because it is easy to confuse the first message to be the conclusive one. When you intend to close the TW afterwards, you can mistakenly do so before it is fully uploaded.

This issue is closely related to #1269 and ideally both are solved in one go. (Or are the two alerts really an attempted *solution* for that issue ?)

As commented in #1269 I propose the ideal solution would be some kind of progress bar, but @tobibeer indicates this is not good.

A simpler solution could be to *keep* the initial message displayed during the whole upload only to have it changed into the "Wiki saved" when done. For this I also propose the initial message is changed to read perhaps "TiddlyWiki is saving, please wait..."

**Comment by tobibeer** [comment]
It's very much the same issue, I guess.

**Comment by pmario** [comment]
+1 for some "please wait ..." info.

**Comment by twMat** [comment]
@tobibeer @pmario 
I'm closing this thread and instead adding to #1269
