### ISSUE TITLE
Dragging plugins in Safari doesn't always work

### ISSUE THREAD

**Issue by buggyj** [Jermolene/TiddlyWiki5#1415]
the issue is reported in 
https://groups.google.com/forum/#!topic/tiddlywiki/zT-PaPL-r8E

Synopsis:
dragging the markdown plugin from tiddlywiki.com into a node.js tw running on local host results in a 'Untiled' tiddler containing the name of the plugin.
versions: tw: 5.17,  OS X Yosemite, all updates installed, browsers: Firefox (v35.0) and Safari (v8.0.2).

**Comment by Jermolene** [comment]
I can duplicate the problem in Safari, but not in Firefox.

In fact, it seems that dragging of some plugin tiddlers in Safari is broken, but others work OK.

The problem occurs in both the standalone and Node.js configurations.
