### ISSUE TITLE
Titles starting with $:/ should be recognized as links

### ISSUE THREAD

**Issue by twMat** [Jermolene/TiddlyWiki5#1416]
Unless, or until, the full #1342 is implemented, I propose that any tiddler starting with `$:/` should automatically be linkified. To avoid auto linkification, use ~

**Comment by pmario** [comment]
Have a look at: http://tiddlywiki.com/prerelease/ and see what happens if you use this: $:/asdf/asdf

see:  autolinks system tiddlers #1341

**Comment by twMat** [comment]
Not much to say other than; excellent,  thanx Mario, and case closed!
