### ISSUE TITLE
SaveTiddler/SaveTiddlers command doesn't handle images with uppercase extensions correctly

### ISSUE THREAD

**Issue by dullroar** [Jermolene/TiddlyWiki5#1418]
Depending on their source, many image files end up getting saved with uppercase file names and extensions, especially those from digital cameras using SD cards or similarly formatted media using FAT file systems (for example, my Canon uses `IMG_0001.JPG` naming format).

If these images are directly dragged and dropped using Explorer/Finder, they will work in general in terms of displaying them within the TW, but they will break the `SaveTiddlers` or `SaveTiddler` commands such as documented under [ExternalImages](http://tiddlywiki.com/#ExternalImages). The break is in `filesystemadaptor.js` at line 116 (v5.1.7):

```javascript
fs.writeFile(fileInfo.filepath,tiddler.fields.text,{encoding: typeInfo.encoding},function(err) {
```

The breakage is caused because `typeInfo` is underfined for "JPG". Here is the entire stack trace:

```
syncer-server: Dispatching 'save' task: Looking Down the Valley.JPG

$:/plugins/tiddlywiki/filesystem/filesystemadaptor.js:116
.writeFile(fileInfo.filepath,tiddler.fields.text,{encoding: typeInfo.encoding}
                                                                    ^
TypeError: Cannot read property 'encoding' of undefined
    at $:/plugins/tiddlywiki/filesystem/filesystemadaptor.js:116:74
    at FileSystemAdaptor.getTiddlerFileInfo ($:/plugins/tiddlywiki/filesystem/filesystemadaptor.js:76:3)
    at FileSystemAdaptor.saveTiddler ($:/plugins/tiddlywiki/filesystem/filesystemadaptor.js:105:7)
    at Syncer.dispatchTask ($:/core/modules/syncer.js:458:21)
    at Syncer.processTaskQueue ($:/core/modules/syncer.js:401:9)
    at null._onTimeout ($:/core/modules/syncer.js:380:26)
    at Timer.listOnTimeout [as ontimeout] (timers.js:112:15)
```

A workaround is obviously to rename the extension to "jpg" or "jpeg", which does work. However, when importing lots of images from something like a camera that would be a PITA.

I wonder if the fix would be to declare "JPG" and "JPEG" to also be supported extensions and simply extend the fix from commit 73a4747? Of course, that could argue that similar situations ("GIF", etc.) may have to be handled, and also that there is a limit ("Jpg", "jPg", "jpG", etc. would be explicitly ***not*** handled, although most of those would be rare cases).

**Comment by tobibeer** [comment]
> I wonder if the fix would be to declare "JPG" and "JPEG" to also be supported extensions

Rather than add more, file extensions should be checked in a case-insensitive manner. Not?

**Comment by dullroar** [comment]
That would be ideal, yes, but I wonder how deep the hooks for that would have to go, given that it is being stored in a JS dictionary and hence the key is case-sensitive. So every place that saved and looked it up out the dictionary (and there are quite a few places that look it up) would have to handle it, and we would have to remember to handle it on any new uses.

Or we'd have to find/implement a case-insensitive dictionary to use to store the type info (interesting idea, actually - hmmm). Or some other storage mechanism that would allow to search it with a case-insensitive regex, perhaps.

That was why I was suggesting just extending the fix in 73a4747 - at least it's presumably bounded by current TW-supported image types - GIF, ICO, JPG, PNG and SVG - leaving us with 12 "supported" extensions:

* gif, GIF
* ico, ICO
* jpg, jpeg, JPG, JPEG
* png, PNG
* svg, SVG

Obviously, though, adding any future image types (TIFF? RAW?) would require adding a pair or more for each (I've seen TIFF files with both `.tif` and `.tiff` extensions). So certainly, this is the "quick and dirty" approach. That always the constant tension between the architect in me ("Let's get it right, regardless of time and cost!") and the former consultant in me ("Let's plant a flag in the ground and call it conquered at the earliest possible point." :grinning: )

**Comment by tobibeer** [comment]
Seems inconsistent to add those as filetypes, even if convenient in some commit. We should touch every bit of code that handles / checks filetypes to do so in a case-insensitive manner. Perhaps introduce `$tw.utils.isFileType`.

As for `jpg` and `jpeg`, those sure are two variants whereas one might point to the other in the form of an alias, if ever needed.

**Comment by Jermolene** [comment]
I think we need to refactor the file extension handling so that it's a bit better encapsulated before we can fix this ticket properly. In particular, we should use `.toLowerCase()` on extensions before looking them up in the dictionary.

**Comment by dullroar** [comment]
I concur, but that means there are many places in the code that access the dictionary directly now, and there should instead be a "wrapper" they would use instead. Not terrible, just sprinkled in quite a few places from what I can see (luckily easily searchable). If you want, I could take a stab, since I seem to be finding (and in one case already fixing) all the "case-aware-but-case-insensitive" file system stuff.

**Comment by Jermolene** [comment]
Hi @dullroar it would be great if you could do it, thank you. As you say, the relevant code should be easily searchable.
