### ISSUE TITLE
Enhancement: $:/TopSideBar — Tiddler Positioning & PageTemplate

### ISSUE THREAD

**Issue by tobibeer** [Jermolene/TiddlyWiki5#142]
### Tiddler Positioning

For as long as the browser window has no toolbars, tiddlers open in the exact same spot in terms of the top-left corner. However, once the story is so long as to activate scrollbars, the tiddler opens slightly higher up.

This turns into a "visual glitch" when you use the optional `$:/TopSideBar` with `position:fixed`. Then, once we're on scrollbars, the tiddler is partly hidden underneath.
### PageTemplate

Currently the topbar can be activated using a tiddler `TopSideBar` as referenced in `$:/core/ui/PageTemplate`.

```
<!-- The optional topbar -->
{{$:/TopSideBar}}</div>
```

Please amend the PageTemplate such that these things come with a default classname, which will be important for plugins, e.g...

```
<!-- The optional topbar -->
<div class="tw-topmenu">{{$:/TopSideBar}}</div>
```

Although partly only relevant for using `position:fixed;` it should also come with default styles, e.g.

```
.tw-topmenu {
    padding: 5px 5em; 
    width:100%;
    z-index:99;
}
```

**Comment by twMat** [comment]
@Jermolene  - can I just ask if there has been any progress on this, even if only conceptually? Left and top bars etc are such prominent UI features, and frequently requested, that I think it warrants some priority.

Or how about this thought; Considering the adaptaion to mobile and small screen devices, maybe we don't need to stick to the side-by-side paradigm for page elements and instead use a simpler(?) stack-on-top approach working in layers?

**Comment by pmario** [comment]
imo don't resurrect ~2 year old issues. please create a new one.
