### ISSUE TITLE
Move all language plugins into their own separate editions

### ISSUE THREAD

**Issue by Jermolene** [Jermolene/TiddlyWiki5#1423]
The present approach of including all the available translations in tiddlywiki.com/index.html is not sustainable. The recent addition of Punjabi and Hindi bumped the size from 3.6MB to 4.4MB.

It is proposed to create a separate edition to distribute each language, and to provide links from the TOC of tw5.com. It is also proposed to add a new "kitchensink" edition that includes all available plugins, themes and languages.

**Comment by tobibeer** [comment]
Can this be closed or do you keep it as a reminder for the kitchensink?

The **Languages** tiddler appears to be terribly outdated, even on Prerelease. Perhaps these tiddlers should come from / with the language editions?

**Comment by Jermolene** [comment]
It can be closed. The "kitchensink" edition is http://tiddlywiki.com/editions/full
