### ISSUE TITLE
custom empty message for the story

### ISSUE THREAD

**Issue by tobibeer** [Jermolene/TiddlyWiki5#1428]
> There is the emptyMessage attribute of the list widget that could be used to display custom content in case the story river is empty. The content wouldn't be displayed as a tiddler (there'd be no toolbar buttons etc.). So, one possibility is to update the list widget for the main story river to read an empty message from $:/config/EmptyStoryMessage. We should also expose it in control panel.
> https://github.com/Jermolene/TiddlyWiki5/pull/1407#issuecomment-71647756

**Comment by pmario** [comment]
+1 for this approach.

**Comment by tobibeer** [comment]
Two things:

1) If emptyMessage is to be the desired fallback I would appreciate if there was support for an **emptyMessage** like this:

`<$list filter="foo" emptyMessage={{SomeTiddler||SomeTemplate}}/>`

2) Currently, setting an **emptyMessage** for the **$list** widget in [$:/core/ui/ViewTemplate](http://tiddlywiki.com/#%24%3A%2Fcore%2Fui%2FViewTemplate) doesn't appear to do anything. => Bug?!?

~

However, I must say, I see drawbacks to this over #1407 and I already hear people asking for that other way of doing things ...and asking for updates to that then plugin so as to keep up with the core code it is going to hijack.

**Comment by Jermolene** [comment]
> 1) If emptyMessage is to be the desired fallback I would appreciate if there was support for an emptyMessage like this:

The proposal is to change `$:/core/ui/PageTemplate/story` so that the list widget invocation reads something like this:

```
<$list filter="[list[$:/StoryList]]" history="$:/HistoryList" template="$:/core/ui/ViewTemplate" editTemplate="$:/core/ui/EditTemplate" storyview={{$:/view}} emptyMessage={{$:/config/EmptyStoryMessage}}/>
```

> 2) Currently, setting an emptyMessage for the $list widget in $:/core/ui/ViewTemplate doesn't appear to do anything. => Bug?!?

The empty message for that list widget will only appear if there are no view template segments.

**Comment by pmario** [comment]
I did a test and it worked.

**Comment by tobibeer** [comment]
Yes, I was obviously looking at the wrong spot. Sorry.

**Comment by tobibeer** [comment]
If I use...

```
title: $:/config/EmptyStoryMessage

{{GettingStarted||$:/core/ui/ViewTemplate}}
```

I pretty much get what I prefered anyway. So :+1:

**Comment by Jermolene** [comment]
Great, @tobibeer glad to hear it
