### ISSUE TITLE
allow to take popups out of the flow! (possible with reveal widget?)

### ISSUE THREAD

**Issue by tobibeer** [Jermolene/TiddlyWiki5#1432]
Currently, popups are rendered in the document flow, right where the reveal widget is rendered.

This is highly problematic as it yields...

* popups cut-off when the element in which they are contained has overflow:hidden
* popup contents being styled as the surrounding container demands, e.g. the sidebar, the tiddler title

Popups should thus not be rendered in the document flow, but in some place where they are independent from the elements for which they are triggerd / at which they are displayed.

Somewhat like modals, however... placed at some target anchor.

**Comment by Jermolene** [comment]
Do you mean that you want popups to behave more like the present implementation of wizards?

**Comment by Jermolene** [comment]
The reason why this is a deep change is that there is currently no direct way for a widget to generate output elsewhere in the DOM; the widget might not, in fact, even be rendering into the DOM at all. Moving to something like the wizard mechanism would mean switching to messages to trigger popups (currently it's modifications to state tiddlers that trigger popups).

I don't think that this is a problem with the reveal widget per se. Remember that the reveal widget and the button widget that work together to make a popup don't need to be in the same part of the widget tree.

**Comment by tobibeer** [comment]
> Do you mean that you want popups to behave more like the present implementation of wizards?

I am not sure what that means. I mean that popups must never be rendered in the document flow at the position where they are declared. They should rather be direct children to the document body or rather to a dedicated popups container.

**Comment by tobibeer** [comment]
> I don't think that this is a problem with the reveal widget per se. Remember that the reveal widget and the button widget that work together to make a popup don't need to be in the same part of the widget tree.

Are you suggesting to use a **$:/tags/PageTemplate** element to place popups?

**Comment by Jermolene** [comment]
> They should rather be direct children to the document body or rather to a dedicated popups container.

A widget can't do that; the DOM nodes that it generates are emitted inline with its position in the widget tree. I suggest looking at the implementation of wizards; they use a different approach which does result in the wizard being a child of document.body.

> Are you suggesting to use a $:/tags/PageTemplate element to place popups? This sounds problematic, if only with there being that extra-declarative effort needed — in the form of non-clickable html comments — to relate them to what triggers them.

No, I'm not suggesting that. I'm saying that the underlying problem that you're trying to fix may be fixed by moving the reveal widget of the popup around in the widget tree.

> What hinders a reveal to render stuff elsewhere in the dom? 

I'd suggest having a look at how widgets are implemented in TW5.

> For a user, what matters it if the popup is rendered alongside the reveal or not?

There are a bunch of differences. In terms of the DOM, the browser coordinate translations will not be inherited, nor inheritable CSS properties like CSS transforms.

**Comment by tobibeer** [comment]
> A widget can't do that; the DOM nodes that it generates are emitted inline with its position in the widget tree. I suggest looking at the implementation of wizards; they use a different approach which does result in the wizard being a child of document.body.

What would be an example of such a wizard?

Could a widget not leveraging some core module and tell it to add some output to a dedicated destination or remove it from there? ...specifically a popup target?

> No, I'm not suggesting that. I'm saying that the underlying problem that you're trying to fix may be fixed by moving the reveal widget of the popup around in the widget tree.

In [Tiddler Ribbon](http://tb5.tiddlyspot.com/#Tiddler%20Ribbon), I need to set `tc-tiddler-frame` to `overflow:hidden` so as to cut off the edges of the ribbon. How would I possibly take the reveal out of the widget tree for the story column if not by moving it somewhere else in the page template?

> There are a bunch of differences. In terms of the DOM, the browser coordinate translations will not be inherited, nor inheritable CSS properties like CSS transforms.

A popup rendered away from the reveal in the dom requires a relation to the reveal that triggered its creation. Hence, we know where to place it once we open it, by virtue of a deferred object having a well defined relation to it.

**Comment by Jermolene** [comment]
> What would be an example of such a wizard?

Apologies, I meant to say "modal"

> Could a widget not leveraging some core module and tell it to add some output to a dedicated destination or remove it from there? ...specifically a popup target?

As I say, widgets can only output dom nodes at their point in the tree. 

> How would I possibly take the reveal out of the widget tree for the story column if not by moving it somewhere else in the page template?

I'm not suggesting moving out of the story column, just pointing out that the button and the reveal widgets can be moved around independently.

> A popup rendered away from the reveal in the dom requires a relation to the reveal that triggered its creation. Hence, we know where to place it once we open it, by virtue of a deferred object having a well defined relation to it.

That doesn't really address the issue of the changes between the two approaches. I'm just saying that these two implementations are not interchangeable.

**Comment by tobibeer** [comment]
> As I say, widgets can only output dom nodes at their point in the tree.

Why would you say this restriction is necessary? As you say yourself, modals and messages work differently as well.

> I'm not suggesting moving out of the story column, just pointing out that the button and the reveal widgets can be moved around independently.

But the problem is precisely that both are in the (context of the) same tiddler (in the story) which prevents me from giving it **overflow:hidden**. The same would be true if I wanted to do that in the sidebar... we get cut-off tag buttons.

**Comment by Jermolene** [comment]
> Why would you say this restriction is necessary? As you say yourself, modals and messages work differently as well.

It's not really a restriction; it's how the widget rendering process works. It's a means to render a tree of DOM elements, and it's operation is defined in terms of the necessary transformations.

Modals work with messages to an external component, which is a completely different mechanism to the button/reveal combo used for dropdowns.

> But the problem is precisely that both are in the (context of the) same tiddler (in the story) which prevents me from giving it overflow:hidden. The same would be true if I wanted to do that in the sidebar... we get cut-off tag buttons.

I understand the problem, and I've been asking whether the modal mechanism resembles the solution you want. I think it does, and with very little refactoring we could implement a form of popups in that way. I think you mind find it helpful to look at how the popup mechanism currently works in popup.js.
> Why would you say this restriction is necessary? As you say yourself, modals and messages work differently as well.

It's not really a restriction; it's how the widget rendering process works. It's a means to render a tree of DOM elements, and it's operation is defined in terms of the necessary transformations.

Modals work with messages to an external component, which is a completely different mechanism to the button/reveal combo used for dropdowns.

> But the problem is precisely that both are in the (context of the) same tiddler (in the story) which prevents me from giving it overflow:hidden. The same would be true if I wanted to do that in the sidebar... we get cut-off tag buttons.

I understand the problem, and I've been asking whether the modal mechanism resembles the solution you want. I think it does, and with very little refactoring we could implement a form of popups in that way. You may mind find it helpful to look at how the popup mechanism currently works in popup.js.

**Comment by tobibeer** [comment]
>  I think you might find it helpful to look at how the popup mechanism currently works in popup.js.

Will do. I get the feeling that the reveal widget rendering the popup contents needs to actually be part of the button itself so that the button has a chance to control its behavior in terms of where things get rendered ...coupling both by virtue of referring to the same state.

**Comment by tobibeer** [comment]
At first, I thought the solution could be this:

1. a new system tag: **$:/tags/Popup**
2. all those being rendered via the PageTemplate in a defined spot
3. any popup ever used should be in its own tiddler, tagged accordingly

Why? So as to not have sidebar styles applied to popup contents in the sidebar, or story styles applied to popup contents in the story or tiddler title styles applied to popup contents in the tiddler title.

The problem, however, with the above is blatantly obvious: We need to dynamically create those popups, e.g. as we render tiddlers in the sidebar, as we render tiddlers in the story.

So, the only option we have, literally, is for the widget that creates a popup to always render it in a defined container outside the flow, and that's it.

> Widgets can only output dom nodes at their point in the tree.

This seems literally false, meaning: more of a restriction that you appear to try and impose on them. Yes, there would have to be some other form of garbage collection, but there is nothing that will stop a (custom) widget from rendering things about anywhere in the dom.

**Comment by tobibeer** [comment]
Also, if that would mean that the reveal widget and its ways of rendering dom elements cannot be used for that, then we should explore to use other widgets, e.g. list or actually: a popup widget.

**Comment by Jermolene** [comment]
Hi @tobibeer the mechanism you describe is very similar to that for wizards: they popup out of the flow of the DOM.

> This seems literally false, meaning: more of a restriction that you appear to try and impose on them. Yes, there would have to be some other form of garbage collection, but there is nothing that will stop a (custom) widget from rendering things about anywhere in the dom.

@tobibeer in TW5 widgets are stateless, period. That's not some arbitrary decision that we can change at whim, it's how TW5 is designed.

Yes we could redesign widgets to allow them to insert arbitrary dom nodes, and handle all the clean-up, but that would be a different design, with different goals. I'd encourage you to explore alternative designs for the TW core, but it's most useful if you are familiar with the existing design.

**Comment by tobibeer** [comment]
@Jermolene

> TW5 widgets are stateless

Can you expand a little on what this actually means?

I have yet to see the details of how modals work, and whether or how we can have a popup mechanism equivalent to those.

In any case there needs to be something, e.g. a widget, which anchors the popup.

**Comment by tobibeer** [comment]
@felixhayashi, since you have some experience with tw modals, would you say their implementation provides a basis / reference for implementing the kind of popups — sometimes we call them "dropdowns" — that don't inherit the styles of wherever their anchor is positioned?

For example, below the links have sidebar colors... and that's just a minor glitch / inconsistency.

![inherit](https://cloud.githubusercontent.com/assets/97566/11654904/8c773f3e-9da9-11e5-9300-669e42bb23a2.jpg)

**Comment by tobibeer** [comment]
I am not arguing the grey style for links or text in popups opened in the sidebar would not work well at that spot. I'm just saying that this should not be a given / there needs to be a way around it without overriding a myriad of styles.

**Comment by tobibeer** [comment]
To see the variable mechanism at work, take a look at:

http://2119.tiddlyspot.com

Here, the icons in tag buttons show the proper contrast color.

**Comment by felixhayashi** [comment]
> @felixhayashi, since you have some experience with tw modals, would you say their implementation provides a basis / reference for implementing the kind of popups — sometimes we call them "dropdowns" — that don't inherit the styles of wherever their anchor is positioned?

I think what Jeremy means with stateless is that they do not create dom-content outside their body (that later needs to be destructed). Also this would not work because it will get overridden in a refresh anyway, just like adding dom nodes using the console or jquery will fail for this reason.

Modals are special because they operate at the very root. The modal mechanism could also work for a popup mechanism to spawn detached popups. HOWEVER, these popups would not be in the original widget tree hierarchy anymore (just like modal content is actually a clone). So they could not propagate events to their original parent widget as they are detached. Because popup do not block the screen, they would more resemble TW alerts (just placed at where the user clicked)…

**Comment by tobibeer** [comment]
> Also this would not work because it will get overridden in a refresh anyway

Placed somewhere in the PageTemplate the occasions of a refresh arbitrarily stealing popups should be rare... in any way, not more numerous than with the current "in-flow-popups".

> So they could not propagate events to their original parent widget as they are detached.

Fair enough. I do not see any need for this, anyway. Click outside, gone. Do whatever you can do in the popup... independent of any widget calling for it.

> Because popup do not block the screen, they would more resemble TW alerts (just placed at where the user clicked)…

I think they should mostly resemble a tiddler in the story, e.g. be "white"... but we could have different popup classes that would cater for different contexts, e.g. we may actually want a popup triggered in the sidebar or topmenu to be styled differently, however, not necessarily with the styles of the surrounding context.

----

What I don't quite get is: We do need an anchor widget and this widget will have to take care of creating the popup. Because: What else will? It may simply ask the wiki to "create a popup", which returned to the widget can be stored in some variable as a reference.

**Comment by pmario** [comment]
You may know, that I'm not a big fan of popups. ... but modals are even worse! ... 

The reveal widget at the moment allows us, to seamlessly remove popups and create multi column list at the right spot in the dom. Just a little bit of CSS and the right templates are needed, to convert them into sliders. 

If you implement a completely new mechanism, imo it will break TWs backwards compatibility and all existing modifications. I'd not been very happy with this.

... So if you want a completely new behaviour here, it needs to be a new theme, with an incompatibility warning. 

> a new system tag: `$:/tags/Popup`

At the moment pupups is a special handling for reveal widget. So after we implement your proposal we need to be able to change a `$:/tags/Popup` to a `$:/tags/Slider` and it still needs to work, as it does today.

**Comment by tobibeer** [comment]
@pmario, the system-tag mechanism will not work as popups need to be dynamically created at some place, so scratch that idea. Unless, perhaps, we always ask for any new popups to be populated from a template tiddler rather than any contained contents.

This actually sounds like the way it could work:

1. the reveal widget) defines an anchor for a popup and a condition for which it is displayed
2. a popup widget inside the reveal widget specifies a template to be rendered elsewhere, in a well defined placeholder, if only specified via some css selector ...by all means, not in-place.
    * the only task for this popup widget is to call a $wiki menthod which renders the popup from a template and anchors it at the calling widget

**Comment by tobibeer** [comment]
Closing in favor of #2120.

**Comment by tobibeer** [comment]
added Addendum to OP:

> The [appear widget](http://tobibeer.github.io/tw5-plugins/#appear) now provides a **handler** mechanism that allows to take popups out of the flow and thus prevent the cut-off.
