### ISSUE TITLE
Introduce a toolbar button macro

### ISSUE THREAD

**Issue by tobibeer** [Jermolene/TiddlyWiki5#1433]
This is way too complicated...

```
<$set name="tv-config-toolbar-icons" value="yes">
<$set name="tv-config-toolbar-text" value="yes">
<$set name="tv-config-toolbar-class" value="">
{{MyButton}}
</$set>
</$set>
</$set>
```

Provide a core button macro that simplifies the process.

**Comment by Jermolene** [comment]
Thanks @tobibeer

**Comment by tobibeer** [comment]
Quick question: would you prefer we made a comment if we started to work on a ticket? Could you do the same?

**Comment by Jermolene** [comment]
> Quick question: would you prefer we made a comment if we started to work on a ticket? Could you do the same?

Yes, I think it's worth mentioning it if you want to warn other people not to approach a ticket, and it's out of the blue. If there's a need to formalise it then we should use the "assignee" feature that GitHub provides, perhaps.

**Comment by tobibeer** [comment]
I'd leave that assignee option to you. Will leave comments now.

**Comment by Jermolene** [comment]
Great, thanks @tobibeer

**Comment by tobibeer** [comment]
Appears to be more difficult that I thought, if not essentially impossible / barely usable...

https://groups.google.com/forum/?fromgroups=#!topic/tiddlywikidev/MmUQWukFNgw

**Comment by pmario** [comment]
@Jermolene -- I think we can close this one. There is an interactive documentation [How to create dynamic toolbar buttons](https://tiddlywiki.com/#How%20to%20create%20dynamic%20editor%20toolbar%20buttons), including keyboard shortcuts

**Comment by Jermolene** [comment]
Thanks @pmario
