### ISSUE TITLE
Installing node with apt-get breaks existing batch scripts

### ISSUE THREAD

**Issue by Jermolene** [Jermolene/TiddlyWiki5#1434]
Using apt-get to install Node.js and npm (with `sudo apt-get install nodejs npm`) results in the Node executable being called `nodejs`. This means that the existing documentation and batch files won't work without modification.

**Comment by roma0104** [comment]
@Jermolene I am not sure if this is a bug.  More of an inconvenience cause by distro package managers.  It affects almost all Debian based distros and is a binary naming conflict between the nodejs package and this extremely niche package: https://packages.debian.org/wheezy/node  

ArchLinux names the binary `node`
And if I remember right from my last foray, so does Gentoo.

Fedora and OpenSuse I am not certain... their package databases are terrible. (Which is not surprising having personally ventured to the hell of their package managers.)

Not sure what you stance would be, but we could sticky a note in build notes that suggests creating a symbolic link: `sudo ln -s /usr/bin/nodejs  /usr/bin/node`, which I personally do, or simply point this out to the users.  Unless the happen to be a ham radio buff too I think the conflict would be limited.

**Comment by Jermolene** [comment]
> Not sure what you stance would be, but we could sticky a note in build notes that suggests creating a symbolic link: `sudo ln -s /usr/bin/nodejs /usr/bin/node`, which I personally do, or simply point this out to the users. 

Good idea. Would you like to send a pull request for mods to `Installing TiddlyWiki on Node.js`?

**Comment by tobibeer** [comment]
Apart form the above docs, will there be anything else being done on this issue? It's a bit odd to see the commits but not a PR. Anyway, can this be closed?

**Comment by pmario** [comment]
We can see the commits, because the issue number was mentioned in the commit message. may be no PR was done or the merge didn't close this issue.

**Comment by Jermolene** [comment]
This was merged from #1685

**Comment by chronitis** [comment]
Apologies for resurrecting a long-closed issue, but it is worth noting that Debian/Ubuntu provide a package `nodejs-legacy` which exists only to create the `/usr/bin/node` -> `/usr/bin/nodejs` symlink noted here. It's probably easier to tell people to install that than need to manually create the link.
