### ISSUE TITLE
Introduce `$:/tags/StartupAction`

### ISSUE THREAD

**Issue by Jermolene** [Jermolene/TiddlyWiki5#1438]
At the end of core startup processing, initiate the action widgets contained within all tiddlers tagged `$:/tags/StartupAction`.

Some examples of what could be done, starting with setting the theme according to whether the wiki is loaded over http(s):// or file://

```
<$action-setfield $tiddler="$:/theme" $value=<<myStartupThemeChooser
  file:"$:/themes/tiddlywiki/snowwhite"
  http:"$:/themes/tiddlywiki/hidefurniture">>/>
```

Change the palette if the vanilla theme was selected:

```
<$reveal type="match" state="$:/theme" text="$:/themes/tiddlywiki/vanilla/">
<$action-setfield $tiddler="$:/palette" $value="$:/_myFunkyPalette"/>
</$reveal>
```

Display a license agreement modal if the user hasn't already agreed:

```
<$reveal type="nomatch" state="$:/_hasAgreedLicense" text="yes">
<$action-sendmessage $message="tm-modal" $param="$:/_myLicenseAgreement"/>
</$reveal>
```

**Comment by tobibeer** [comment]
:+1:  very useful indeed, especially for implenting "read-only" mode.

**Comment by inmysocks** [comment]
The startup-acitons.js in the TriggerActions plugin I made should have this functionality. I think I have tracked down any big problems, but it should be tested by other people also. I need to write up more documentation for it and unfortunately I haven't found a good way to demo it. I will work on that this weekend.

Example site: http://ooktech.com/jed/ExampleWikis/TriggerActions/
Github: https://github.com/inmysocks/TW5-TriggerActions/blob/master/startup-actions.js

**Comment by inmysocks** [comment]
I moved the startup part of the plugin into its own plugin and added a demo site http://ooktech.com/jed/ExampleWikis/StartupActions/
It supports any action widget and all of the widget messages and can do contitional actions using the reveal widget like suggested in the original post. I am not sure if there is something I should do next.

**Comment by TiddlyTweeter** [comment]
@Jermolene & @inmysocks ... was "$:/tags/StartupAction" as discussed here ever implemented? I can't find note of it if it was.

_Or should I just use Jed's gizmo for now?_

**It seems to me the action would be very helpful**

- Especially if your offline and online (CSS) versions differs yet need regularly updating. Saves all the hassle of manually switching stuff off.

FWIW, on one TW I use a @tobibeer gizmo to load random tiddlers on startup (just putting it in the Default Tiddlers section). But it doesn't always work--I don't know why.  I'd prefer a method I know always works.

Best wishes
Josiah

**Comment by tobibeer** [comment]
@inmysocks : did you ever get to make a PR for this / can this be closed?

**Comment by inmysocks** [comment]
@tobibeer I made #1573 for this, but I haven't looked at it in a long time.

**Comment by inmysocks** [comment]
@Jermolene this should be closed since it got added to the core.

**Comment by Jermolene** [comment]
Thanks @inmysocks
