### ISSUE TITLE
safe way to pass parameters

### ISSUE THREAD

**Issue by tobibeer** [Jermolene/TiddlyWiki5#1439]
allow to pass any wikitext to a macro as a parameter, including wikitext that has macros in it, e.g. to showcase that, perhaps via triple square brackets:

```
<<foo [[[<<bar>>]]]>>
```

perferably a variable number of matching square brackets greater than two so as to even allow nesting:

```
<<foo [[[[<<bar [[[<<baz>>]]]>>]]]]>>
```

**Comment by Jermolene** [comment]
Hi Tobias



On Sat, Jan 31, 2015 at 11:53 AM, Tobias Beer <notifications@github.com>
wrote:

> allow to pass any wikitext to a macro as a parameter, including wikitext
> that has macros in it, e.g. to showcase that
>
> Perhaps...
>
> <<foo [[[<<bar>>]]]>>
>
> The current macro call parser is embarrassingly simple, and won't allow a
literal ">>" within the macro call text under any circumstances:

https://github.com/Jermolene/TiddlyWiki5/blob/master/core/modules/parsers/wikiparser/rules/macrocallinline.js

The workaround is to use the widget syntax:

<$macrocall $name="foo" bar=""""<<bar>>"""/>

Best wishes

Jeremy.



> ?
>


> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Jermolene/TiddlyWiki5/issues/1439>.
>



-- 
Jeremy Ruston
mailto:jeremy.ruston@gmail.com

**Comment by tobibeer** [comment]
I see, there is no way for the macro parser to handle this, except via some escaping and then we'd have a different nesting problem.

```
<<foo [[[[<<bar [[[<<baz>++++>]]]>++>]]]]>>
```

So, macrocall it is, thanks.

**Comment by Jermolene** [comment]
That's correct, yes. I'd certainly like to improve the macrocall parser, though;

**Comment by tobibeer** [comment]
> I'd certainly like to improve the macrocall parser, though

In which way(s)? Are there open tickets reflecting that yet?

**Comment by Jermolene** [comment]
> In which way(s)? Are there open tickets reflecting that yet?

I don't think there are any relevant tickets; it hasn't come up before. The parser should be updated to work along the lines of the html parser (which is also used for parsing widgets):

https://github.com/Jermolene/TiddlyWiki5/blob/master/core/modules/parsers/wikiparser/rules/html.js

Unlike the macrocall parsers, it is doesn't try to match the entire HTML tag with a single regexp. Instead, it implements the `findNextMatch()` method with custom logic to look for the tag and it's attributes.
