### ISSUE TITLE
Remarks about the french edition

### ISSUE THREAD

**Issue by Spangenhelm** [Jermolene/TiddlyWiki5#1442]
Hi, as i was trying to update my tw with the 5.1.7 version of the [french edition](http://tiddlywiki.com/languages/fr-FR/empty.html) i have found that there are a few problems:

The default open tiddlers are
HelloThere
GettingStarted
Community

but HelloThere and Community do not exist and should therefore be removed from the default list, otherwise they uselessly appear as empty tiddlers.

Also plugins like the github ribbon, google analytics, browser-sniff etc.. + the contribution banner + languages other than french should not installed by default, as this is supposed to be an "emtpy" version according to [tiddlywiki's docs](http://tiddlywiki.com/#Empty%20Edition)

Ps: my suggestion about the unification of different versions of tw in one place is still open (https://github.com/Jermolene/TiddlyWiki5/issues/1030) does anybody has an opinion on it ?

Thank you

**Comment by Jermolene** [comment]
@xcazin do you know what's going on here?

**Comment by xcazin** [comment]
Hi @Jermolene, @Spangenhelm 
I must say I didn't remember how empty.html was generated for the different languages. I probably copied and falsely edit a tiddlywiki.info. I'll try to figure out what is wrong from looking at German editions and send a pull request (at least for 5.1.8) once I get it right.

**Comment by Spangenhelm** [comment]
Hi @Jermolene @xcazin 

> xcazin do you know what's going on here?

Nope, he was not aware, this is why: before i posted this issue i have tried to look for the right person to contact directly (or at least to call/mention here to get its attention) but i did not find any mention of anybody in tw's site or elsewhere as translators..

I assume that if there is no mention of maintainers because there is no "official" ones ?

**Comment by xcazin** [comment]
Hi @Spangenhelm 

Yes, tiddlywiki.com documentation, as well as translations, are considered collective work. If not, who would be the author of a tiddler that has been improved several times?

This also means that you're welcome to improve [the fr-FR edition](http://tiddlywiki.com/prerelease/languages/fr-FR/index.html) (you may want to start with [the warning](http://tiddlywiki.com/prerelease/languages/fr-FR/index.html#Informations%20pour%20les%20traducteurs))!.

**Comment by Jermolene** [comment]
@xcazin I've just pushed a new prerelease, and http://tiddlywiki.com/prerelease/languages/fr-FR/empty.html still has a broken default tiddlers.

I notice that `languages-bld.sh` in Jermolene/build.jermolene.github.io has this:

```
--rendertiddler $:/core/save/empty languages/fr-FR/empty.html text/plain \
```

While the `tiddlywiki.info` for the fr-FR edition has these two build commands:

```
"--rendertiddler","$:/editions/fr-FR/download-empty","empty_fr.html","text/plain",
"--rendertiddler","$:/editions/fr-FR/download-empty","empty_fr.hta","text/plain"],
```

So, I think the solution is for `language-bld.sh` to use a `--build index empty static` command to avoid duplicating the build commands. The build script will also need an `--output` command to set the output directory correctly.

**Comment by Jermolene** [comment]
I think this is now fixed in 8b53839e4ed3a05b5cb5946701060007317e7d41. I've uploaded a new prerelease for you to try:

http://tiddlywiki.com/prerelease/languages/fr-FR/empty.html

**Comment by Spangenhelm** [comment]
@xcazin

> ...tiddlywiki.com documentation, as well as translations, are considered collective work.

Totally, but let me answer you with a question: why did jeremy called you in ?
Well it is because you are "the person to contact when talking about this edition", simply as that! So my point is: unless you don't want to, for any reason, at least __you__ should be mentionned in the french edition's contact. You are fully qualified for it: first and main translator !

You have done an incredible work on the translation (i will help if i can) so thank you so much !

**Comment by xcazin** [comment]
Hi @Jermolene 
> I think this is now fixed in 8b53839. I've uploaded a new prerelease for you to try:
> http://tiddlywiki.com/prerelease/languages/fr-FR/empty.html

Very clean, thank you very much for looking into this. I must say I didn't understand at first what happened with the building scripts, then I failed to follow up after the penny had dropped :-)

**Comment by Spangenhelm** [comment]
Hi @Jermolene, what do you think about adding someone to contact when having problems with an edition ?

**Comment by xcazin** [comment]
> Hi @Jermolene, what do you think about adding someone to contact when having problems with an edition ?

Aside from the fact that the someone would not always be available, I'm curious to know what added value it would bring to the community over starting a specific thread on the tiddlywiki google group (where everyone can weight in) or opening an issue on github (in case your problem is actionable) like you rightly did here?

**Comment by tobibeer** [comment]
@xcazin :+1:  on either grous or github

If anyone feels eligible to a task, I'm sure they will chime-in when it comes to matters of their concern... if they don't, then we're only waiting for some slightly breaucratic review mechanism to kick-in... I think that is a bit of a dead end in an open-source environment, despite risks of inconsistencies.

**Comment by Spangenhelm** [comment]
@xcazin @tobibeer i was thinking of a problem of translation itself (not tw related so to me it did not have its place here but i did not think about ggroups)

Thank you for your time gentlemens ;-)
