### ISSUE TITLE
Reverting shadows

### ISSUE THREAD

**Issue by tobibeer** [Jermolene/TiddlyWiki5#1444]
list all overwritten shadows in the ControlPanel / perhaps the UpgradeWizard, too and provides the ability to select all those which one wants to upgrade to the lastest core / plugin version

"upgrading" possibly meaning: replacing the text with the current text but keeping all fields and tags

**Comment by Jermolene** [comment]
It makes sense to have a list of overridden shadow tiddlers with the ability to revert them individually or en masse. However, I'm not so sure about "replacing the text with the current text but keeping all fields and tags" - why wouldn't we revert them by deleting the modified tiddler, allowing the shadow to show through?

**Comment by tobibeer** [comment]
> why wouldn't we revert them by deleting the modified tiddler, allowing the shadow to show through

because you may just want to add a different tag (sidebar) or a list-before (some other tiddler than the default) rather than mess with the actual text

**Comment by Jermolene** [comment]
> "upgrading" possibly meaning: replacing the text with the current text but keeping all fields and tags

I think that that operation is a bit brittle; the user still ends up with a modified shadow, and the user interface would be very hard to explain.

**Comment by tobibeer** [comment]
It's actually the reason why I made this proposal in the first place. I merely want to shuffle tabs around without actually preventing their inner workings from being stuck in a given version.

**Comment by Jermolene** [comment]
That is intended to be done by overriding the tag shadow tiddlers like `$:/tags/ViewTemplate` with a new `list` field. It's fine to override those tiddlers because all they are there for is to provide a `list` field.

**Comment by tobibeer** [comment]
that works if I want to move things about in the same tabs, but not if I want to move tools to secondary and tabs to primary.

**Comment by Jermolene** [comment]
Yes, but I think that in that case we're better off looking at improving the customisation of tabs, not implementing this slightly complicated behaviour for semi-reverting to shadow tiddlers. Not that it's not useful in some situations, just that I don't think it should be in the core. If it turns out to be useful in a plugin that's the time to put it in the core.
