### ISSUE TITLE
ButtonWidget must not fire click actions of tiddlyLinks in the label

### ISSUE THREAD

**Issue by tobibeer** [Jermolene/TiddlyWiki5#1445]
This must not open the GettingStarted tiddler...

```
<$button>GettingStarted</$button>
```

Consider the case where you want a label that possibly renders a tiddlyLink as text and an icon, e.g.

```
<$button><<currentTiddler>> {{$:/core/images/chevron-right}}</$button>
```

Possibly, the actual problem is the lack of a wikitext parser to render something as plain text only: #699.

### Context

I was trying to create the documentation for the slider macro, but the last example fails...

http://tb5.tiddlyspot.com/#SliderMacro

In other words, this doesn't work for the closing label...

```
\define slider-label(prefix,suffix)
$prefix$<$text text="$(currentTiddler)$"/>$suffix$
\end

<$tiddler tiddler="GettingStarted">
<$macrocall
$name="slider"
label=<<slider-label "" " {{$:/core/images/chevron-right}}">>
content="!!text"
state="$:/state/slider/GettingStartedPrefixes"
label-hide=<<slider-label "" " {{$:/core/images/chevron-down}}">>
/>
</$tiddler>
```

Maybe something's wrong in my [slider macro](http://tb5.tiddlyspot.com/#%24%3A%2F.tb%2Fmacros%2Fslider), but I can't see what.

**Comment by Jermolene** [comment]
Hi @tobibeer the culprit here is the `<<currentTiddler>>` construction, and the way that it wikifies the title of the current tiddler. It's often better to use `<$text text=<<currentTiddler>>/>` which avoids the wikification. (As we've discussed before, it would be good if there was a briefer syntax for this).

**Comment by tobibeer** [comment]
I wish I could use the $text widget but it won't work in my case as it breaks the macro relies on it:

http://tobibeer.github.io/tb5/#SliderMacro

...very last example.

**Comment by Jermolene** [comment]
It looks like the problem with that example is that you're expecting the results of the macro to be wikified when used as a widget/element attribute. That doesn't work, as previously discussed. There's definitely some holes that we need to fill but they are around macro invocation, and not quite the problem that is raised by this issue. Can we close this ticket?

**Comment by tobibeer** [comment]
I'd sure like to close this issue if I knew how I can prevent a tiddlyLink form being rendered within a button... without breaking it.

**Comment by Jermolene** [comment]
My proposed solution is a solution for the problem you cited in the bug report. I've explained what the problem is with the other example you offered.

I don't think I understand your second example. Why don't you just do this:

```
\define slider-label(prefix,suffix)
$prefix$$(currentTiddler)$$suffix$
\end
```

**Comment by tobibeer** [comment]
> Why don't you just do this:
> `$prefix$$(currentTiddler)$$suffix$`

Because it renders **GettingStarted** as a clickable link inside that button... which is the actual problem as described in the issue.

I have updated that example to actually demonstrate the other side of the problematic coin:
http://tb5.tiddlyspot.com/#SliderMacro

It's a bit of a deuce ...with two losing outcomes.

**Comment by Jermolene** [comment]
> I have updated that example to actually demonstrate the other side of the problematic coi

Sorry @tobibeer I'm not sure that I'm seeing the problem there. Can you just show me the part that's not working as you expect?

> It's a bit of a deuce ...with two losing outcomes. ^^

Not really. It just confirms what we already know: we need a way to render wikified text as an element/widget attribute. That's the bug, it's misleading to think of it as something to do with the ButtonWidget and the GettingStarted link.

**Comment by tobibeer** [comment]
> Can you just show me the part that's not working as you expect?

If you click on GettingStarted in the very last example of that page... instead of an opening slider, GettingStarted is being opened. That is due to it being rendered as an internal-link and me having no discernable way of yielding "GettingStarted" as a mere text.

**Comment by Jermolene** [comment]
@tobibeer what I am saying is that you reported a problem with links inside the button widget. We've now established that the problem isn't quite that: it's that there isn't a way to set a widget/element attribute to the wikified result of a transclusion or macro invocation -- which is a known problem. With that diagnosis, I don't think it's useful to have a ticket that emphasises a symptom that isn't really relevant to the problem under discussion.

**Comment by tobibeer** [comment]
I am almost certain that the link inside the button is my problem...

```
<$tiddler tiddler=GettingStarted>
<$button>
<<currentTiddler>>
</$button>
</$tiddler>
```

**Comment by Jermolene** [comment]
@tobibeer the example you've given renders as expected: it wikifies the tiddler title and places it within a button. So of course you end up with a link inside a button; it's what you asked for.

How are you expecting the example you've given to render?

**Comment by tobibeer** [comment]
I know, in the above I could use $view... but I cannot do so in a macro.

**Comment by Jermolene** [comment]
Right, so the example above isn't relevant then?

**Comment by tobibeer** [comment]
Mhhh, my problem isn'T that I can't set wikified results, because I do want wikified results (that image), I need a way for some parts of that to yield just text and others not to.

**Comment by Jermolene** [comment]
I don't think that this ticket describes that problem, does it?

If you think that this is a bug, then please open a ticket with the steps to reproduce and clarify the difference between the actual and expected behaviour.

I don't think that that is the case; I think that your wikitext is functioning as documented, but that essentially you need to do something that is not supported. If that's the case, then we need to study a simple example to see if we can evolve a proposal for extending the core to support it.

**Comment by pmario** [comment]
@tobibeer 

what's about this?

```
<$tiddler tiddler="GettingStarted">
<$button>
<$view field=title>
</$button>
</$tiddler>
```

**Comment by tobibeer** [comment]
@pmario, as I said, this is not actually the issue, the issue is that I cannot use the $view widget in the macro that is to construct the widget parameter, because that parameter contains both, wikitext and what is not supposed to be such, e.g. "MyCaption {{SomeImage}}".

**Comment by tobibeer** [comment]
Though unresolved, I am closing this issue, as I don't see the discussion leading towards a solution.

**Comment by pmario** [comment]
Your OP was this.

>This must not open the GettingStarted tiddler...

>```
<$button>GettingStarted</$button>
```

right?

IMO it doesn't open the GettingStarted tiddler at tiddlywiki.com

**Comment by tobibeer** [comment]
o.O

**Comment by tobibeer** [comment]
added addendum to OP:

> The eventual problem boiled down to not having used triple quotes. Then again, I set out to create a more powerful widget for sliders and popups: [tobibeer/appear](http://tobibeer.github.io/tw5-plugins/#appear). So, for me, this macro approach for sliders is now obsolete.
