### ISSUE TITLE
date picker / date filters / typed fields

### ISSUE THREAD

**Issue by tobibeer** [Jermolene/TiddlyWiki5#1449]
Being a journal is a core aspect of TiddlyWiki. Maybe plugin territory, to facilitate working with journals and dates, provide the following modules...
### Date Picker

Implement a date(-time)-picker for fields whose type is set to date(-time). Requires an ability to declare typed fields. Rather than adapt anything, perhaps build a basic calendar widget that can be used as a datepicker, e.g. via link-catcher, with (optional) controls to move through the months or clicking the year / month to edit and go to.
### Date Filters

**date**
- `<$list filter="[date:journaldate[201501]]"/>`
  - returns all tiddlers where the field **journaldate** is set to January 2015
- `<$list filter="[date:journaldate[20150101]]"/>`
  - returns all tiddlers where the field **journaldate** is set to 01. January 2015

**week**
- `[week:1:1:BLANKS[201501]]`
  - returns a list of all days of the...
    - first week (1st suffix)
      - optional, default: 1
    - starting monday (2nd suffix)
      - optional, default: 1= monday (0 is sunday)
    - returning blanks (3rd suffix)
      - optional, default: `<no blanks>`
      - for any days that are actually not part of that month, return blanks `""`
      - this is optional as you may NOT want blanks in a calendar showing weeks
      - if blanks are not possible, return something like `NONE`
    - for January 2015 (operand)

**weeks**
- `[weeks[201501]]`
  - returns a list of the week numbers of January 2015
### Example Month Calendar

```
<table>
<tr>
<$list filter="Week Mo Tue Wed Thu Fr Sa Sun">
<th><currentTiddler></th>
</$list>
</tr>
<$list filter="[weeks[201501]]" variable="week">
<tr>
<th>
<<week>>
</th>
<$list filter="[week:1:1:BLANKS[201501]]" variable="weekday_date">
<td>
<$list filter="[date<weekday_date>]"/>
</td>
</$list>
</tr>
</$list>
```

**Comment by pmario** [comment]
imo plugin territory, since the user expectations to the functions and formatting may differ very much. So if we can find a "de facto" standard it could be implemented in the core.

**Comment by pmario** [comment]
`<$list filter="Week Mo Tue Wed Thu Fr Sa Sun">`

needs to be translatable

**Comment by pmario** [comment]
<$list filter="[weeks[201501]]" variable="week">

Calculating the week number follows different rules between US and Europe.

**Comment by tobibeer** [comment]
>> `<$list filter="Week Mo Tue Wed Thu Fr Sa Sun">`

> needs to be translatable

Sure thing, easily done. This was just to give an idea of how a calendar can be rendered using these filters.

> Calculating the week number follows different rules between US and Europe, so a "calculate the dates" library ma be needed.

Who would have expected anything but that. ^^

We could sure say it's plugin territory. To me, a date picker is a prime candidate for a standard component, just like a button, checkbox, select, radio, etc.... It's entirely annoying that there is no browser standard for that. It should be so ubiquitous and tightly integrated with the the core that it will likely yield a mess with different implementations and feature sets. It will simply be too difficult to come to terms with it and development would be horribly slow and a lot more constrained, which would be a total bummer, especially for things that are a little more complex like this.

In just the same way, I would expect for [drag-sorting (nested) lists](http://draggable.tiddlyspot.com/#Mockup) to become a feature of the core list widget at some This will be so ubiquitously useful that not having it or requiring this or that plugin would simply complicate things for no reason I can discern at the moment.

**Comment by felixhayashi** [comment]
In case of a date picker I also think it would be a great addition to the core - just like the color picker is activated when creating the color field a date picker pops up for the "date" field. It is true that date pickers come with a bunch of options but this could be made configurable via the configurations-tiddler somehow. It is more critical how to store the underlying time data.

> So if we can find a "de facto" standard it could be implemented in the core.

Imo it would be best to use Unix time (http://en.wikipedia.org/wiki/Unix_time) as it allows precise date calculations, the only drawback being, it doesn't look good when not formatted. So maybe we could agree on using unix time and at the same time have a date format widget that formats the time string into e.g. "%H:%M:%S". Then the date picker could always store the time data in unix time, js widgets could do exact date comparisons based on that field and if necessary a formatter widget can be used to translate the time data into user friendly date strings.

**Comment by pmario** [comment]
Working with dates, needs to be exact and right. eg: First day of the Week (So, Mo), Week number ... So the core date picker has to be generic, without anything that breaks in the US.

See my "suggestion: store modified, created dates as UTC ISO string #280" about a year ago.

**Comment by felixhayashi** [comment]
Thanks for referencing this @pmario. ISO strings are of course a good choice too!

I just wanted to highlight that there are two main parts that need to be clarified. In fact I added some more crucial points:

1. **Format**: Which underlying format to use? Good alternatives ISO or Unix Time
2. **Theme**: How should the date picker look like? This should be configurable from the wiki configuration tiddler. E.g. `display week numbers: true`
3. **Field**: Which field should trigger the date picker? As Tobi suggested, some fields should trigger the picker similar like "color" initiates a color picker dialog. Maybe all fields starting with "date." as prefix?
4. **Widget**: A widget that allows formatting of the timestamp. Something like `<$date format="%H:%M:%S" field="date.due" />`

-Felix

**Comment by tobibeer** [comment]
> Imo it would be best to use Unix time (http://en.wikipedia.org/wiki/Unix_time) as it allows precise date calculations

Ok, so TiddlyWiki currently has a date-time format for modified and created. What (standard) does it subscribe to? Any spec somewhere? Just reading the unix-time wikipedia entry doesn't answer that or what differences we may need to account for. Does the current format pose problems and which precisely?

**Comment by tobibeer** [comment]
> Format: Which underlying format to use? Good alternatives ISO or Unix Time

Perhaps a crucial point. However, the straight forward answer is: the current format, as is... even if lacking timezone-support.

> Theme: How should the date picker look like? This should be configurable from the wiki configuration tiddler. E.g. display week numbers: true

That would possibly increase the template code a lot, but then using the newly added iterator variables it would now be possible to skip the first column when someone decided to set **week-numbers:false**

> Field: Which field should trigger the date picker? As Tobi suggested, some fields should trigger the picker similar like "color" initiates a color picker dialog. Maybe all fields starting with "date." as prefix?

The way I see it, there needs to be (a spec) for a core namespace for field configuration, i.e. **$:/config/fields/foo** ...specifying what type of field **foo** is, what editing widget to use and possibly what rendering widget as well.

> Widget: A widget that allows formatting of the timestamp. Something like `<$date format="%H:%M:%S" field="date.due" />`

This should be handled by the above configuration, so there could be a `$:/config/fields/date.due` which instructs TiddlyWiki to use the **$:/core/ui/Editors/DateTime** picker instead of just a **$:/core/ui/Editors/Date**, perhaps differing only in having an underlying widget attribute of some calendar widget set to **time:true**.

> Javascript-Project: Which existing date picker application to choose? Should be a small lib solely focussing on date picking.

I don't think we should chose any. We need to leverage our custom widget-technology so as to keep things extensible within our own framework. No "standard" will cater for it... perhaps as a starting point, but not as something to simply "adjust".

**Comment by tobibeer** [comment]
> Have you explored the way that "color" fields get a color picker automatically?

Summarized the process here: [editing the color field @ dev5](http://dev5.tiddlyspot.com/#editing%20the%20color%20field)

So, yes **tiddlerfields** should probably be first-class-tiddler's and applied as modify them to my needs, extended with an ability to declare a given template to edit or view a field. There could / should be a catch-all default to be able to override the default editor for fields.

**Comment by Jermolene** [comment]
OK @tobibeer I suggest we open a new ticket titled "Expose and extend tiddler field metadata as tiddlers". One issue is that we need the metadata during boot before we load any tiddlers. Also the current metadata implementation doesn't support dynamic changes to the field metadata.

**Comment by pmario** [comment]
@tobibeer ... for me this seems to be a "wontfix" until browsers support native date pickers. And because there are several plugins out there, that can be used. eg: http://kixam.github.io/TW5-datePicker/ which uses moments.js, which should calculate dates right.

**Comment by tobibeer** [comment]
>  I suggest we open a new ticket titled "Expose and extend tiddler field metadata as tiddlers". One issue is that we need the metadata during boot before we load any tiddlers. Also the current metadata implementation doesn't support dynamic changes to the field metadata.

=> #1331
