### ISSUE TITLE
Integrated plugin library

### ISSUE THREAD

**Issue by Jermolene** [Jermolene/TiddlyWiki5#1450]
It would be useful to be able to install plugins directly from tiddlywiki.com into a standalone or client-server TiddlyWiki.

For example, a new "+" button in the Plugins tab of Control Panel could bring up a categorised list of plugins available on tiddlywiki.com.

Each plugin would have an "install" button that would automatically install the plugin (and any dependent tiddlers). Ideally, where needed, a banner would appear reminding the user to save and reload in order for the newly installed plugins to be recognised.

If the same version of the plugin is already installed, the button would be disabled and labelled "installed". If the library plugin is a newer version, the button would be enabled and labelled "upgrade".

It should be possible for users to add other plugin sources by adding a specially tagged configuration tiddler.

**Comment by tobibeer** [comment]
> into a standalone or client-server TiddlyWiki

Would that refer to a wiki hosted on the www rather than the local filesystem ...or does it have to be some node.js served wiki?

**Comment by Jermolene** [comment]
> Would that refer to a wiki hosted on the www rather than the local filesystem ...or does it have to be some node.js served wiki?

The idea would be that a standalone wiki could access the tiddlywiki.com library whether it is being used on a local file:// URI or an http:// URI for a service like TiddlySpot.

The Node.js configuration ships with the plugin library as part of the repo, and so doesn't need to access tiddlywiki.com for installing core plugins. Installing third party plugins can be done through the browser in the usual way.
