### ISSUE TITLE
global "focus filter"

### ISSUE THREAD

**Issue by tobibeer** [Jermolene/TiddlyWiki5#1459]
Certain applications, e.g. GTD, would benefit a lot from an ability to dynamically set a global filter that constrains all lists to only those matching that filter, e.g. only *status:#next*, only *realm:-work* or both.

Imagine a "focus" tab in the sidebar, or a corresponding button popup in the toolbar with predefined filter options which when clicked constrain all (filtered) lists to just that.

Feasible?

This would also be a way to provide more flexibility to as well hide things by default in the sense of #1210, e.g. "Admin" pages that are only visible when one clicks a checkbox to remove **[tag[Admin]]** from that global "focus filter" and thus have these things listed and searchable.

**Comment by Jermolene** [comment]
> Feasible?

A global filter for determining the visibility of a tiddler title in the sidebar is an interesting idea. On the face of it, we'd need a way for the filters used in the sidebar to access the results of that global visibility filter. We could imagine doing that by (a) being able to set a variable to the list resulting from the global filter and (b) within a filter, being able to reference a list within a variable (eg, `[listvar[tv-global-sidebar-filter]is[system]]`).

The trouble with that approach is that it wouldn't be at all efficient. The list inside the variable would be long, and would have to be recomputed on every tiddler store change, and whenever it actually changed we'd have to refresh the descendent widgets. So, I think this is the kind of thing that's worth experimenting on, but I'm not inclined to pursue it for the core.

**Comment by tobibeer** [comment]
> So, I think this is the kind of thing that's worth experimenting on, but I'm not inclined to pursue it for the core.

Duly noted, hence closing.
