### ISSUE TITLE
www shorthand

### ISSUE THREAD

**Issue by tobibeer** [Jermolene/TiddlyWiki5#1460]
Consider:

```
[www[forced.link.com]]
[www[tw|tiddlywiki.com]]
```

All of these currently interpret the argument as a relative path:

```
[ext[forced.link.com]]
[ext[www.forced.link.com]]
[ext[tw|tiddlywiki.com]]
```

It would be nice to tell the parser that it's a url we're giving it other than by doing a full `http://` alongside possibly superfluous prettification:

```
[[forced.link.com|http://forced.link.com]]
[[www.forced.link.com|http://www.forced.link.com]]
[[tw||http://tiddlywiki.com]]
```

**Comment by pmario** [comment]
if `www` adds `http://` then `wwws` would add `https://` ?? ... IMO kind of ugly.

If an `https://` link is available, imo it should be used. The problem here is, that TW can't decide. At least I don't know, if it can :)

**Comment by tobibeer** [comment]
TiddlyWiki doesn't have to decide on the protocol nor does a user. Instead, when that window opens at that location, the browser decided as it always does if I omit that.

**Comment by Jermolene** [comment]
The problem here is that the `[ext[]]` syntax will interpret URIs that don't start with a protocol as being relative. The proposed solution is new syntax `[www[]]` and `[wwws[]]` that automatically apply a default protocol to their arguments.

I think it's a bit clumsy, and barely improves on a custom `<<http "link" "tooltip">>` macro.

**Comment by tobibeer** [comment]
> I think it's a bit clumsy, and barely improves on a custom `<<http "link" "tooltip">>` macro

True, indeed. However, my point was to have a core function of it, e.g...

```
<<www foo.com>>
```

or

```
<<www foo.com foo>>
```

...so that you don't need to invent that wheel whenever you want it.

**Comment by Jermolene** [comment]
Well I'd certainly be less against a macro than a new bit of wikitext syntax, I still think this might be the sort of macro that belongs in a community macro bundle. The macros we ship in the core are really the ones that the core needs; we don't try to ship all the useful macros out there.

**Comment by tobibeer** [comment]
ok, added here: http://tobibeer.github.io/tb5/#www

**Comment by pmario** [comment]
I like the idea of the macro.
