### ISSUE TITLE
`[list[$:/StoryList]]` doesn't work for default tiddlers under node.js

### ISSUE THREAD

**Issue by kejadlen** [Jermolene/TiddlyWiki5#1474]
I'm running TiddlyWiki via Node.js, and changing the default tiddlers setting to `[list[$:/StoryList]]` doesn't seem to work. I installed this by running `tiddlywiki tw --init server` and have been running it from there.

If there's any additional information I could provide that would help, let me know.

**Comment by pmario** [comment]
Did you try: `<<list-links [list[$:/StoryList]]>>`

**Comment by pmario** [comment]
With my first test I did miss "changing the default tiddlers setting" ... I can confirm. There is a problem.

**Comment by Jermolene** [comment]
Thanks @kejadlen

**Comment by kejadlen** [comment]
Thanks! Confirmed that this fixes the issue for me.
