### ISSUE TITLE
indexes[] filter should not sort by default

### ISSUE THREAD

**Issue by tobibeer** [Jermolene/TiddlyWiki5#1477]
remove: https://github.com/Jermolene/TiddlyWiki5/blob/master/core/modules/filters/indexes.js#L26

**Comment by Jermolene** [comment]
I hate to say it, but wouldn't this be an incompatible change? The reason that we sort the results is that there is no reliable ordering for JavaScript object keys. If we leave them unsorted then we'll be exposing JS engine peculiarities, which I'd rather avoid.

**Comment by tobibeer** [comment]
> The reason that we sort the results is that there is no reliable ordering for JavaScript object keys.

For what I see, the keys are added as entered. Sorting by default brakes a basic paradigm and makes a simple data stack principle impossible.

**Comment by Jermolene** [comment]
See here:

http://stackoverflow.com/a/5525812/3111487

"As it happens, most browsers do return properties in the same order as they were inserted, but it is explicitly not guaranteed behaviour so you should not rely upon it."

So, it's browser specific behaviour that we should try to hide. Otherwise we'd have problems like tests running differently on different browsers.

**Comment by tobibeer** [comment]
I see. So if at some point we wanted a stack of **key => value** pairs, it would have to be an explicit one... an then we'd be able to adjust the indexes filter to explicitly use that sorted index. In other words it would have to be stored in some index-list field, for example.

**Comment by Jermolene** [comment]
Yes that would be one approach.

**Comment by tobibeer** [comment]
It's strikes me as incredibly odd that the Chrome developers would have chosen this ridiculous path.

**Comment by Jermolene** [comment]
It's counter-intuitive and counter-experiential, which is not a good start!

I think that in practice browsers almost all emulate some ancient behaviour of Netscape 4. Pointing out that properties aren't ordered always feels like being a bit of a spoil sport :)

**Comment by tobibeer** [comment]
I mean, I sure wasn't expecting some "alphabetical" order as that would surely be a matter of variance... but a basic FIFO... why the friggin flog not? Someone must have been on a powertrip to beg the ECMA crew for a proper stack-spec. ^^

**Comment by tobibeer** [comment]
@Jermolene, atually, no matter whether we believe the browser behavior being erratic, we're still taking away a native option to handle JSON differently and I think it's not a good idea, because there sure is an inherent order to a json document, just as there is in html... whether Chrome dev's at some point thought it wouldn't mean anything or not, because it's "so-very-unspecified" ...even if it was implemented by all major browsers in but one way.

For example, someone could try and fix the JSON parsing by prepending an empty string to all indexes, which appears to work accross browsers... or even implement a `JSON.parse()` variant that does this.

Some TiddlyScript could also prepend such superfluous empty strings in json tiddlers could to force the default browser behavior to be what one would reasonably expect. This would, however require us triming **indexes** upon parsing.

Anyhow, my point is mostly that `[sort[]]` is as arbitrary as leaving it to the browser to decide on sorting! So, we should not predefine it either.

**Comment by tobibeer** [comment]
Two more reasons not to sort:

1. performance
2. default array sort => not actually desirable

**Comment by Jermolene** [comment]
Hi @tobibeer I'm not sure why you're talking about Chrome. The issue here is that we should try to avoid exposing browser-specific behaviour to the user because it will leave to people building wikis that may work differently on different browsers.

> because there sure is an inherent order to a json document, just as there is in html

There is an ordering to items in a JSON array but there's no ordering to object properties; JSON has to inherit JavaScript semantics here.

> one might try and implement a different kind of JSON parsing by prepending an empty string to all indexes

I think we need to stick to standard JSON for interoperability.

**Comment by tobibeer** [comment]
still, using default array sort just yields rather weird ascii ordering ...for proper sorting we have actual sort filters

**Comment by Jermolene** [comment]
Yes, but at least it's consistent ordering. Using sort filters would slow things down somewhat, too.

**Comment by tobibeer** [comment]
Consistent with what? With having all uppercase letters listed alphabetically before any lowercase ones? I don't think a user will ever understand that. So, if we want sorting, let's use sorting as we know it / implemented it for a reason... but preferably not with the indexes filter... because it's actually not always needed.

**Comment by Jermolene** [comment]
> Consistent with what?

Consistent across different browsers.

> With having all uppercase letters listed alphabetically before any lowercase ones? I don't think a user will ever understand that. So, if we want sorting, let's use sorting as we know it / implemented it for a reason... but preferably not with the indexes filter... because it's actually not always needed... or wanted.

We're going round in circles a little. We must sort the indexes filter to avoid exposing browser-specific behaviour. Using a more elaborate sort is undesirable because of the performance implications.

**Comment by tobibeer** [comment]
So, to have testable results across browsers we implement an undesireable crutch where they failed to adhere to a sensible, existing standard.

Yes, I'll keep spinning that circle... because someone in the chrome dev team screwed up big time and failed to acknowledge a need to fix it... which they eventually will when someone else had enough of undefined non-standards.

Anyhow, so we have borwser dependent behavior. Is that news? Why would that be a problem for testability in itself? It's been existing since forever. Otherwise, why are we allowing all that browser-specific css? That's entirely the same ballpark to me. If I look at tw in safari, it's essentially broken as safari fails to work some "Helvetica Neue" font on Win where-ever it's pulling that from, or not.

![safari](https://cloud.githubusercontent.com/assets/97566/6138597/da47cf3a-b182-11e4-85f7-83f867dca2b6.jpg)
![safari2](https://cloud.githubusercontent.com/assets/97566/6138598/da4bf772-b182-11e4-85da-e53b133ca76d.jpg)

...just saying. Either we cater for browser quirks or we don't. I understood that we don't... i.e. no polyfills, css fixes, or whatever quirks browser dev's think is making their day. Why would this be any different?

**Comment by Jermolene** [comment]
> because someone in the chrome dev team screwed up big time and failed to acknowledge a need to fix it... which they eventually will when someone else had enough of undefined non-standards.

I don't understand this bit. What have the Chrome dev team got to do with this issue?

> Either we cater for browser quirks or we don't. I understood that we don't... i.e. no polyfills, css fixes, or whatever quirks browser dev's think is making their day. Why would this be any different?

I don't think it's as black and white as that. This is JS not CSS. There's very little implementation dependent behaviour in JavaScript, and we absolutely do need to steer clear of it. Remember the ambition is to create something that will work for the next 25 years. There's going to be browsers in that time that are very different to contemporary ones.

**Comment by tobibeer** [comment]
>> because someone in the chrome dev team screwed up big time and failed to acknowledge a need to fix it... which they eventually will when someone else had enough of undefined non-standards.

> I don't understand this bit. What have the Chrome dev team got to do with this issue?

From what I have read, they're pretty much the (only) ones to introduce special handling for numerical keys, putting them before string keys, thus screwing up the order of keys to an object, where all other browsers would return them in the way they were added.

"Non-standard" meaning that "undefined" is not a reliable state to build anything on top, hence the problem of (no longer) having an array of object properties... returned the way they were **pushed** into it ...just like any other array. So, yes, some Chrome/Chromium dev's must have thought they were doing something really smart all the while screwing everyone else, because "the standard doesn't specify it".
