### ISSUE TITLE
Macro mode returning wikified

### ISSUE THREAD

**Issue by tobibeer** [Jermolene/TiddlyWiki5#1479]
It should be possible to call a macro forcing it to return wikified results...

### The Problem

```
\define lingo(title)
{{$(lingo-base)$$title$}}
\end
```

This will only return the string "{{$:/language/Foo/Bar/Baz}}" rather than the actual contents of the TextReference in the below...

```
<$edit-text field="some-field" placeholder=<<lingo Bar/Baz>> tag="input" default=""/>
```

### Possible Solution

Perhaps...

```
<<<macro param:value param:value>>>
```

And...

```
<$macrocall $name=macro param:value param:value $wikify:true/>
```

Not sure how **$type** and **$output** play into all this, hence #1478. However, they're unusable in the above example anyway.

**Comment by tobibeer** [comment]
having just read it, is `<<<foo>>>` what you were meaning with https://github.com/Jermolene/TiddlyWiki5/issues/693#issuecomment-49542333?

**Comment by Jermolene** [comment]
> It should be possible to call a macro forcing it to return wikified results...

I would express the problem as being that macro invocations used as element/widget attributes are always returned as plain text, and not subject to wikification.

The reason is performance: wikification (ie parsing and rendering) is slow. So I think we might need to do it more indirectly: a way to assign the wikified results of a macro invocation to a variable, which can then be used as an attribute.

**Comment by tobibeer** [comment]
> So I think we might need to do it more indirectly: a way to assign the wikified results of a macro invocation to a variable, which can then be used as an attribute

We already have that with the set widget, and it doesn't help with the case of the lingo macro. Maybe the other way around? TextReferences containing variables?

```
{{<foo>!!bar}}
```

**Comment by Jermolene** [comment]
> We already have that with the set widget

No, we don't. The set widget doesn't wikify values.

> and it doesn't help with the case of the lingo macro

Like this:

```
\define lingo(title)
{{$(lingo-base)$$title$}}
\end

<$set-wikified name="myPlaceholder" text=<<lingo Bar/Baz>>>
<$edit-text field="some-field" placeholder=<<myPlaceholder>> tag="input" default=""/>
</$set>
```

> TextReferences containing variables? 

I don't think that those ideas are backwards compatible. `{{<foo>!!bar}}` is transcluding a tiddler called `<foo>`.

**Comment by pmario** [comment]
Why don't us use the mechanism, that is used everywhere else?

```
\define lingo-base() $:/language/ControlPanel/Basics/

<<lingo Title/Prompt>>
```

**Comment by tobibeer** [comment]
Because it doesn't work when you actually try it... with a placeholder attribute.

**Comment by Jermolene** [comment]
@tobibeer - would my proposal for the `<$set-wikified>` widget meet your needs?

**Comment by tobibeer** [comment]
It would, but then it would entirely defeat the purpose which is to use a shorthand for that attribute where it is desired. If I need to have a special set-wikified widget, I might just use the long(-distance) notation for the text-reference.

**Comment by Jermolene** [comment]
@tobibeer I'm confused. You're pointing to a fundamental problem: that it's not possible to pass the results of wikifying text as an element/widget attribute. You've proposed a solution and I've explained why I favour a different solution. I think you're saying that the solution I've proposed is too long-winded, and so you might not use it. But isn't that a matter of writing some macros that wrap up the desired behaviour? Remember, the widget syntax isn't intended to be shorthand: that's what wikitext and macro calls are for.

**Comment by tobibeer** [comment]
Sounds all highly complicated. Why do we need to work things out on yet another widget layer? How precisely will that help here? How much nesting are we shooting for with macros and whatever templates / widget-components they're going to wrap up? There's gotta be some limit of when things become inexplicably long-winded and nested and essentially non-understandable by anything but a TiddlyWiki parser.

I sure I don't have the picture of all processing implications but at this moment I am not seeing why it has to be a new widget that is of need... or how it will practically help in this case. Are we going to have macros that set variables for inner widgets which hopefully expose the entire feature set of the widget being implemented? There is a point of too much redundancy and essentially impracticality.

Cut short: At this moment I am missing a capability of basic `<<macros>>`, not of widgets, not even a macrocall widget. I need that placeholder attribute to be filled with something evaluated differently than what that plain macro is giving me right now ...essentially, the macro is denying me the whole featureset of the corresponding macrocall widget and that is possibly my entire problem.

Maybe I'm wrong but I feel like I need for that $output our $type or both to be accessible for a macro requiring such modifiers... eventually wikifying that stuff, not with yet another seemingly superfluous widget... which may sure prove practical in other cases, but not in this one.

Also, I would prefer for it to be an extension to the set widget rather than a new set-wikified widget...

`<$set name="foo" wikified="bar"/>`

...so as to keep the number of components as small as possible.

**Comment by Jermolene** [comment]
> Sounds slightly complicated. I think we may not need to work things out on the widget layer.

Sorry, what sounds complicated? The proposed set-wikified widget? It's a precise answer to your request, I think.

> At this moment I am missing a capability of basic <<macros>> where that placeholder attribute needs to be filled with something evaluated differently than what that plain macro is giving me right now ...essentially, the current macro syntax is not exposing the featureset of the corresponding macrocall widget and that is possibly the entire problem.

But didn't I give an example of how that problem could be solved with the set-wikified widget?

> ...so as to keep the number of components down.

Good to keep the number of components down, but we also need to keep the components simple. There are a lot of options with wikification (eg, passing variables to the wikified text) that would clutter up the existing set widget, which is already quite complicated by supporting both filters and simple values.

**Comment by tobibeer** [comment]
> Sorry, what sounds complicated? The proposed set-wikified widget? It's a precise answer to your request, I think.

Mhhh, how would this...

```
<$set-wikified name="myPlaceholder" text=<<lingo Bar/Baz>>>
<$edit-text field="some-field" placeholder=<<myPlaceholder>> tag="input" default=""/>
</$set>
```

... be anymore concise or prgamatic than...

```
<$edit-text field="some-field" placeholder={{$:/language/Foo/Bar/Baz}} tag="input" default=""/>
```

?

The problem being discussed is that something as simple as the lingo macro is unusable in the context of a widget attribute.

**Comment by Jermolene** [comment]
But @tobibeer this already means something different, doesn't it? We can't just spontaneously change how transcluded attributes work.

```
<$edit-text field="some-field" placeholder={{$:/language/Foo/Bar/Baz}} tag="input" default=""/>
```

> The problem being discussed is that something as simple as the lingo macro is unusable in the context of a widget attribute.

Sorry if I wasn't clear. I'm against providing a syntax for specifying that transcluded attributes be wikified for several reasons:

* Performance. Widget attributes are computed each time a widget node is refreshed, and wikification is a very slow process. Making it into a separate widget allows us to be smarter about the refreshing
* Complexity. The core widget code is already complex enough, and extending the attribute syntax would add significant further complexity
* It would be fiddly to extend the syntax to allow for potential options (eg text type, render type)

**Comment by tobibeer** [comment]
Please reconsider with the above changes to the macro definition.

**Comment by Jermolene** [comment]
> Actually, I don't even need to modify the above syntax for each and every attribute but rather to tell the macro definition itself to return its output wikified.

That's potentially a good way to move the syntax fiddliness around, but it doesn't address the performance and complexity concerns.

**Comment by tobibeer** [comment]
I don't see how introducing another widget doing precisely the required wikification will improve performance or complexity.

**Comment by Jermolene** [comment]
Well, it's a separate widget, not more complexity in the base widget.js. The performance benefit is what I said above: widgets can have refresh logic, while widget attributes are refreshed unconditionally on each refresh cycle.

As ever when we come to matters that are concerned with the existing implementation, I'd recommend reading the code if you want to be able to make the most useful implementation proposals.

**Comment by EvanBalster** [comment]
+1 on *any* kind of "wikify" widget that could feed into an attribute.  I'm trying to generate SVG paths and it simply isn't possible without extending TiddlyWiki at the moment.
