### ISSUE TITLE
Improving the import mechanism

### ISSUE THREAD

**Issue by felixhayashi** [Jermolene/TiddlyWiki5#1487]
Hi,

The import mechanism is one of the strengths of tiddlywiki.
However, I want to make a few suggestions what imo is still missing. Maybe it can serve as a roadmap...

**Split view comparison**

In the google groups the topic "[TW5] Comparing Tiddlers side by side" (https://groups.google.com/d/topic/tiddlywiki/V18SC8SDNOw/discussion) came up and actually such a thing would really make sense for the import mechanism, especially when working in a team and tiddlers often need to be imported from other wikis (also by dropping the whole wiki), overriding existing tiddlers with the same name. Without a split view comparison (existing|incoming) it is hard to identify the changes and make correct decisions on which version to keep. Highlighting changes is another milestone but even a simple split view with some meta data display (modified date etc) would be helpful.

**Selecting which tiddlers to accept**

Importing a wiki.html or a whole bunch of tiddlers means to go through all the checkboxes and making decisions for every tiddler whether to keep it or not. Something like a filter would be helpful here. Or grouping incoming tiddlers separating system tiddlers and non-system tiddlers while adding a global toggle above each group saying "select all/none"

**Renaming when importing**

It would be nice to give the incoming tiddler a new name at the time it is imported. Otherwise it is: Importing, going to the tiddler, edit mode, rename, save.

-Felix

**Comment by Jermolene** [comment]
These are all good ideas. I hadn't thought of the third one but it makes a lot of sense.

**Comment by felixhayashi** [comment]
Hi Jeremy,

> These are all good ideas.

Thanks. At the moment I am working with a team of five people on a website based on tiddlywiki where we all share our wikis and one chosen person ("coordinator") integrates the content importing it from the other wikis. So I thought it would be good sharing my experiences/difficulties in form of an issue here.

> I hadn't thought of the third one but it makes a lot of sense.

I forgot to add that this renaming should be optional of course.

-Felix

**Comment by Spangenhelm** [comment]
Hi @felixhayashi, really smart as usual ! Though i'm afraid that it would take too long to put those modifications in place and what about the size of all this ? (talking more about the spilt view here)

**Comment by danielo515** [comment]
Dear @Spangenhelm ,

What do you mean with to fat? There are just a couple of lines of code to accomplish this. Are you talking about the wide of the split view? Nothing worse than the preview IMO

**Comment by pmario** [comment]
@felixhayashi 
Did you consider to use TiddlyWeb as a backend?

**Comment by Jermolene** [comment]
@Spangenhelm I'm very keen to add a 3rd party library for displaying text diffs so that we can do tiddler versioning properly.

**Comment by Spangenhelm** [comment]
@danielo515 
>There are just a couple of lines of code to accomplish this.

That is what i was talking about, i was afraid that those modifications would need too much kilobytes to add to tw, making it heavier (or "fat"), thanks for the explanation. About the text diffs i have your context plugin in mind, with some mods is there no way to use it for this?

@Jermolene 
+1 for tiddler versionning !

**Comment by felixhayashi** [comment]
@pmario 

> Did you consider to use TiddlyWeb as a backend, which imo would make collaboration easier?

We don't want to use a backend/server in order to keep things as simple as possible.

@Spangenhelm 

Minified libraries are usually the size of a small image so I think the increase in size is acceptable compared to the benefits (https://groups.google.com/d/msg/tiddlywiki/V18SC8SDNOw/moR6BNo8kCEJ).

**Comment by Spangenhelm** [comment]
@felixhayashi Oki dooki, let's go then!

**Comment by felixhayashi** [comment]
> Oki dooki, let's go then!

:)

**Comment by saqimtiaz** [comment]
It would also be helpful to be able to bulk assign tags (user defined in the import interface) to tiddlers being imported. 
Example: assigning the "notes" tag when importing notes or, assigning a tag like "lastimport" to make it easier to then go through and organize everything that was just imported.

**Comment by pmario** [comment]
I think the ["bundler" plugin](https://wikilabs.github.io/editions/bundler/) is the first step in that direction. 

The core provides 2 functions that can be used to improve the import UI. 

 - An updater mechanism, that is activated, as soon as you "drop" new tiddlers.
 - An import hook, that is activated for every tiddler, that is imported / selected. 

The problem here is automatically unselected tiddlers can't be reactivated. ... The current selection mechanism is lying here. ... which will be a new issue soon.

**Comment by danielo515** [comment]
The core provides hooks for plugins focused on the import mechanism, called import modules.
Currently there is one hook, but there is a problem with the import mechanism that should be addressed: #758

After that, each plugin can do whatever is necessary during the import phase.

**Comment by pmario** [comment]
>Currently there is one hook, but there is a problem with the import mechanism that should be addressed: #758

I knew, that I've see it somewhere. ... Yes. that's the problem I'm talking about. I intend to create a PR, since I need if for the bundler-plugin. ... I just don't have a clear proposal, how to communicate with the user facing UI .. yet ... It still feels a bit hacky atm.

**Comment by pmario** [comment]
@Jermolene .. Option 1 and 3 are implemented already. I did copy option 2 to #5013 so we don't forget it. 

So IMO this one can be closed, since we may handle it with #5013

**Comment by Jermolene** [comment]
Thanks @pmario

**Comment by pmario** [comment]
@Jermolene ... IMO you forgot to close it :)

**Comment by Jermolene** [comment]
> @Jermolene ... IMO you forgot to close it :)

Doh! Thank you
