### ISSUE TITLE
Decent "mobile" Hardware isn't able to use TW

### ISSUE THREAD

**Issue by pmario** [Jermolene/TiddlyWiki5#1490]
From: #1405> 

> > I did test tiddlywik with the raspberry pi 2 - 4 core ... And tiddlywiki is unusable (in my opinion). 3 seconds to open a tiddler. Every keystroke needs about 1 second.
> 
> Yes indeed. I suspect that static renderings are always going to be best for these very constrained environments.
> 
> > It would be nice, if we could add some tests, that tell us about performance regressions. ...
> 
> Yes, that would be nice, contributions welcome!

CPU: Broadcom BCM2836 ARMv7 Quad Core Processor, running at 900 MHz
RAM: 1GB SDRAM @ 450 MHz

There are not many existing mobile phones, with these specs. ... + The default browser is capable of using the GPU for rendering. Chromium is a bit snappier for rendering tiddlers, but has a problem with the "every keystroke triggers a full page redraw" problem, since it doesn't use the GPU. ...

I did a test with LibreOffice - Writer, It needs about 3 seconds to start but working with it is just a breeze. ..LibreOffice needs to use the Jave Environment. IMO we do have a performance problem.

**Comment by Jermolene** [comment]
Thanks @pmario. I think we need to address this on two fronts: improving support for static renderings (and making them more interactive), and improving performance. For the latter, we need to base any improvements on some decent, repeatable measurements.

**Comment by roma0104** [comment]
I customarily develop on a considerable less powerful netbook and have little to no problems with delay tiddler rendering/text entry even when disabling hardware acceleration.  It is obviously more sluggish than my desktop machine, but I have never had any performance issues editing tiddlers.

Toshiba NB505: 
Intel Atom 1.6GHz 
1GB RAM
Debian Jessie x86_64
Chromium 39
Iceweasel (Firefox) 31

The one exception that comes to mind is when I have Developer Mode on Chromium on and I am logging many objects for debugging.  Once I closed the Developer window the lag from text entry disappears.  

I don't even experience this kind of lag running on my old EeePC 900a with ArchLinux.  --edit: I also don't have this problem with my Windows 7 Starter on my Toshiba running under Chrome or IE.

I guess what I am getting at is: 'Is this a problem we can fix?'  From my arm-chair position this sounds like a OS issue or at least a problem with the efficiency of hosting application.  At the same time I am running clean TW5.  Are you using a large TW5 application and would be willing to share it ?

**Comment by tobibeer** [comment]
I think there might actually be a problem with the pi and the pi only.

**Comment by roma0104** [comment]
Doesn't the Pi run its OS directly from a SD card usually?  The browser could be crunching down on caching issues if the SD card is slow.  Would some lightweight, memory-resident-only OS solutions like PuppyLinux that avoid/cannot do any disk writes show the same performance issues?  Or try it with caching disabled?

I need to buy myself a Pi at some point...

**Comment by pmario** [comment]
>Are you using a large TW5 application and would be willing to share it ?

tiddlywiki.com

**Comment by pmario** [comment]
Hardware has improved, but I still think we have room for improvements. .. But may be it needs to be a completely new mobile-theme. ... so I'll close this one.
