### ISSUE TITLE
Add an option for popup events to prevent closing when clicked inside

### ISSUE THREAD

**Issue by felixhayashi** [Jermolene/TiddlyWiki5#1497]
When using a textinput field (<$edit-text) or a drop down (<$select) in a popup, often you don't want the popup to be closed when clicked somewhere inside. However, the popup should be closed when clicking somewhere outside the popup. It would be nice, if the popup verifies whether it has been clicked in its own bounds and when the reveal widget has the option remove set to `remove="clicked-outside"` in contrast to `remove="clicked"` it won't close.

**Comment by tobibeer** [comment]
:+1:

**Comment by Jermolene** [comment]
Yes, good idea. I think CSS classes might be a more flexible way of marking the desired behaviour. That would make it possible to have regions of a popup that behave differently.

**Comment by felixhayashi** [comment]
Hi Jeremy,

> Yes, good idea. I think CSS classes might be a more flexible way of marking the desired behaviour. That would make it possible to have regions of a popup that behave differently.

Great idea! This also decouples the code as you do not need to pass additional parameters to the `popup.js` from the reveal widget.

-Felix

**Comment by pmario** [comment]
@felixhayashi ... imo this is possible. see the "search" popup

**Comment by tobibeer** [comment]
@pmario: it seems there is some minimalistic documentation missing that would explain how to achive both goals:

* have one popup close when clicked outside and inside
* have another popup close only when clicked outside

**Comment by pmario** [comment]
@Jermolene --  I think this can be done with `tc-popup-keep` as defined with the [RevealWidget](https://tiddlywiki.com/#RevealWidget)

**Comment by Jermolene** [comment]
Thanks @pmario
