### ISSUE TITLE
canceling a modal

### ISSUE THREAD

**Issue by tobibeer** [Jermolene/TiddlyWiki5#1499]
As suggested here: https://github.com/felixhayashi/TW5-TiddlyMap/issues/45#issuecomment-74035545, allow to...
- ESC out of a modal
- click the curtain outside a modal to close it

**Comment by felixhayashi** [comment]
Not my intention anymore.. see https://github.com/Jermolene/TiddlyWiki5/issues/1215#issuecomment-114479363

**Comment by tobibeer** [comment]
begs the question of whether or not a *modal* is the proper tool for advancing in a *workflow* ...I think it's not a, *modal*, to me, is a popup thingy that begs for your confirmation ...if necessary, in a two-step process

**Comment by pmario** [comment]
according to #1215 there seems to be consensus, that this is not wanted and not backwards compatible?
