### ISSUE TITLE
full transclusion of codeblock fails

### ISSUE THREAD

**Issue by Skeeve** [Jermolene/TiddlyWiki5#1507]
Create these tiddlers:

full:

```
<h1><$view field="title"/></h1>
<$transclude/>
```

script:

``````
try this:

```
cd ~
ls -al
```
``````

fail:

```
{{script||full}}
```

Notice that the codeblock in "fail" is rendered as single code lines

**Comment by pmario** [comment]
did you try: transclude mode block ?  http://tiddlywiki.com/#TranscludeWidget

**Comment by tobibeer** [comment]
Did some testing and found [one case](http://tobibeer.github.io/tw/test/block/#Script040) that is a bit peculiar:

http://tobibeer.github.io/tw/test/block/#Script-Compare

Where [this fails](http://tobibeer.github.io/tw/test/block/#Script040)...

```
<$tiddler tiddler="Script">

!!<$view field="title"/>
<$transclude/>
</$tiddler>
```

But [this doesn't](http://tobibeer.github.io/tw/test/block/#Script120)...

```
<$tiddler tiddler="Script">

!!{{!!title}}
{{!!text}}
</$tiddler>
```

**Comment by Jermolene** [comment]
@Skeeve the problem you've reported is just that you're using an inline mode transclusion. You could fix it by adding an extra line break before the transclude widget, but it's probably clearer to use the `mode` attribute that @pmario suggests

@tobibeer I pasted the following into a new tiddler on tiddlywiki.com and couldn't observe any difference between the two examples:

```
<$tiddler tiddler="About">

!!<$view field="title"/>
<$transclude/>
</$tiddler>

<$tiddler tiddler="About">

!!{{!!title}}
{{!!text}}
</$tiddler>
```

**Comment by tobibeer** [comment]
@Jermolene, I believe it's got something to do with whether the tiddler content ends with a "block-mode" element which thus break, e.g. monospaced codeblocks would break as well as blockquotes.

http://tobibeer.github.io/tw/test/block/#BlockQuote-Compare

**Comment by Skeeve** [comment]
Am 14.02.15 16:05, schrieb Jeremy Ruston - notifications@github.com:
> @Skeeve the problem you've reported is just that you're using an inline mode transclusion. You could fix it by adding an extra line break before the transclude widget,
Nope. Tried it. Didn't work.


>   but it's probably clearer to use the `mode` attribute that @pmario suggests
That helped.

**Comment by pmario** [comment]
@Skeeve so it's solved?

**Comment by Skeeve** [comment]
Am 14.02.15 23:33, schrieb Mario Pietsch - notifications@github.com:
> @Skeeve so it's solved?
>
1. The code is working differently when transcluded and when shown directly
2. Jeremy thinks, the transclusion works in block mode when an 
additional linefeed is before the transclude widget

So I geuss the answer to your question should be "no".

It seems to me I'm using a workaround.

**Comment by pmario** [comment]
IMO that's the intended behaviour. The transclude widget inherits the current rendering mode, which is intended behaviour.

If it is inline the transcluded block will be rendered inline. That's what you see. .. So you have to use the block mode. 

IMO this issue will be a "won't fix"

**Comment by Jermolene** [comment]
That's right, I don't think there's a bug here, exactly. It's a confusing area, and I'd welcome proposals for improvement, but at the moment I don't see anything I could fix.

**Comment by pmario** [comment]
@Jermolene .. pls close this one.

**Comment by Skeeve** [comment]
I agree to close. Maybe put a hint somewhere in the documentation that there's a difference between having a return or not having a return after the transclusion?
