### ISSUE TITLE
How to set message parameters for LinkCatcherWidget

### ISSUE THREAD

**Issue by tobibeer** [Jermolene/TiddlyWiki5#1508]
Have the documentation specify precisely how parameters are passed to the (optional) message.

**Comment by Jermolene** [comment]
The linkcatcher widget doesn't currently support setting the parameters of the generated message.

**Comment by tobibeer** [comment]
How would a message be handled without any parameters?

**Comment by Jermolene** [comment]
Sorry @tobibeer I don't know what you mean. Maybe it would help to have a look at the linkcatcher source code?

**Comment by tobibeer** [comment]
@Jeremolene, I was trying to call a certain message upon catching that link — and failed miserably, with all kinds of configurations.

Reading the documentation, I have no clue which attribute(s) to set so as to have a message perform right. I took it that it should be straight forward for you to clarify that in the docs.

Of course, I could dig in the linkcatcher and some message code, but there are those moments when you just wish to just use things. As for messages, that ubiquitous "param" attribute right now escapes a deeper understanding with me owed to its unspecified nature ...and then trying to matching that to some further linkcatcher attribute(s), it would really be nice to not deconstruct a codebase to figure things out, for once.

**Comment by Jermolene** [comment]
@tobibeer I don't really understand what you're asking. What is it that you are trying to do but can't?

Is this ticket really just saying "Please improve the docs for the linkcatcher widget"? If so, there's no more reason to file a ticket against it than any other tiddler on tiddlywiki.com that needs improvement.
