### ISSUE TITLE
Language Switcher API

### ISSUE THREAD

**Issue by roma0104** [Jermolene/TiddlyWiki5#1513]
I would like for [GSD5](https://github.com/roma0104/gsd5) to have multilingual support and leveraging TW5's current language would be fantastic.  However, there doesn't appear to be means of accomplishing this.  

If a was much better Spanish speaker than I currently am, and I decided to switch to es_ES the language switching mechanism appears to search out for `$:/languages/es_ES` and its dependencies and stops there.  That leaves GSD5 with two options: stay US/GB English or basically redeploy the language switcher.  Neither ideal.

My proposal is to make the TW5 language switcher aware of supplemental 'language packs' which it loads at language changes as well.  Without changing the current language design, the switcher would use the current language's tiddler as a prefix to search for additional language packs.

Using the previous example:  If I decided to switch to es_ES the language switching mechanism would search out for `$:/languages/es_ES`, its dependencies and any other language plugin with the title prefix `$:/languages/es_ES` before returning.  GSD5 might create a language plugin `$:/languages/es_ES/gsd5/core` that would now bring multilingual support to its users.

This would allow any plugin author to bring their plugin to a greater audience.  Would this be something that we would be interested in implementing?  Suggestions, comments?

**Comment by pmario** [comment]
I think this is a good idea!

Using your example, you suggest a naming convention like this: `$:/languages/<langCode>/<uniqueID>/<moduleName>`

langCode .. is defined by the official language packs. eg: es_ES ...
uniqueID .. can be a plugin name, project name ... must be unique
moduleName .. is free for the developer to use. can be eg: core or core/beta ... so additional sub categories should be possible.

right?

**Comment by roma0104** [comment]
I think suggesting a name convention that suggests the following is a great idea.  
`$:/languages/<langCode>/<uniqueID>[/<uniqueID][...]`

Beyond that I do not know if any more structure should be required for language addons.  Sorry if my example is confusing, my project's actually plugin name is `gsd5/core`.  This was a design concept to allow GSD5 to be extended and categorised in the future like this: `gsd5/newplugin1`, `gsd5/newplugin2`.

**Comment by Jermolene** [comment]
Hi @roma0104 thanks.

There is an existing ticket for making plugins translatable: #786

The key difference between your proposal and the solution discussed in #786 is that your approach has each GSD5 language packaged as a separate plugin, rather than packing all the translations into the parent plugin.

I can imagine that for something of the complexity of GSD5 it would be best to have separate language plugins, but I'd like to evolve a solution that supports both approaches.

Let's discuss the options here, and once we've come up with a solid proposal we'll create a new ticket, and close this one and #786.

**Comment by roma0104** [comment]
Thank you Jeremy.
I tend a skim over the issues for this particular issue but apparently missed it.

I think this is a problem that is within my skill range and wouldn't mind carrying the flag on this.  I will post a more complete proposal for others to look at and suggest at a later time.

**Comment by Jermolene** [comment]
Thanks @roma0104

**Comment by roma0104** [comment]
# Goal

Extend the Language Switcher mechanism to provide multilingual services to plugins.

# Proposal

The current language switching mechanism is straightforward and provides a mean of translation to all TW5 core tiddlers.  The mechanism listens for changes to `$:/language` and once triggered, unloads the current language plugin, loads the new language plugin specified and finally calls a refresh of the tree.

This current design does not provide plugins a means of utilizing this feature to create language-aware strings.  The following design changes will hopefully solve this issue and allow plugin authors to create high quality plugins.

## Requirements

* Avoid changes that would break the current model of language switching
* Support additional language tiddlers that are packaged within plugins.
* Support additional language tiddlers that are packaged in standalone plugins.

## Languages Within Parent Plugins

Additional language strings that are packaged within the parent plugin must adhere to the following tiddler naming schema: `$:/plugins/<publisher>/<plugin-name>/language/<locale-code>/<name-of-translatable-string>[/<unique-id>][...]`

A control tiddler named `$:/plugins/<publisher>/<plugin-name>/language/` must be created with the following fields: 

**default**
The value of the default field must the default language for the plugin.  In the event TiddlyWiki5's language is changed to a language the plugin does not support, the plugin will fail-safe to the default language. 

**support**
A space separated list of double-bracketed locale codes for supported language strings.

Strings that are made 'language-aware' by calling a Javascript macro that accepts three parameters: the name of the language control tiddler, target locale code, and the name of the translatable string.  

When called, the macro finds the control tiddler, compares the value of the target locale code against the supported locale list.  If no match is found, it fails to the default locale code. The macro returns an un-rendered transclusion string created by concatenating the title of the control tiddler, the target locale code, and the name of the translatable string.

For convenience, the plugin author could wrap the Javascript macro to avoid repetitious macro calls by hard-coding the first two parameters.  

```
\define my-plugin-translate(stringName)
<<tw5-translate controlTiddler:"$:/plugins/roma/my-plugin/language" localeCode:$(languageTitle)$ stringName:$(stringName)$>>
\end  
```

## Languages As Standalone Plugins

Additional language strings are packaged into plugins with the exact requirements of official language plugins with two minor changes.

Supplemental language plugins must be named using the following schema: `$:/language/<locale-code>/<plugin-name>[/<unique-id>][...]`

The plugin `type` is set to `language-pack` in `plugin.info`.

When languages are changed the existing language switcher loads the official language plugin.  And then loads any `language-pack` that has the prefix of loaded language.  

Example:
If language is switched to `es_ES`, the official language plugin `$:/language/es_ES` is loaded, then `$:/language/es_ES/my-plugin`, and `$:/language/es_ES/cool-plugin`

**Comment by Jermolene** [comment]
Hi @roma0104 thanks for this.

I'm beginning to think that the ability to package translatable strings as part of the parent plugin adds a lot to the complexity. Without that capability, all we'd need to do is to have language plugins expose their locale, and then when switching languages, switch in all the language plugins that have the correct locale.

I'm wondering whether an easier approach to supporting "integral" language packs might be to have the language plugins embedded as an actual sub-plugin within their parent plugin.

Then, all we'd need to do is consider these shadow plugins in the language switcher, as well as regular non-shadow plugins.

**Comment by roma0104** [comment]
@Jermolene I agree that integrated language tiddlers are bit complex due to amount of anonymity tiddlers have with regards to their origin.

I had thought about finding means to nest plugins but I was not sure if the recursive ability existed.  Though I admittedly have never tried, it looks like the same mechanism that loads user tiddlers also loads plugins?  Firstly, is there a way to package nested plugins in an automated way?  I think I know how I would go about hacking them together but it would be realistically unfeasible to ask author to JSON-ify their language plugin by hand.

**Comment by pmario** [comment]
@Jermolene .. label: "newfeature"?

**Comment by tobibeer** [comment]
unless it's a one liner, i'm definitely thinking that plugins should not ship with their localisations but that those need to be packaged / made available outside the plugin context... via a harmonized model that should equally hold true for core plugins.

**Comment by tobibeer** [comment]
"Put them in the core language plugin" surely is not a sensible option. I will not make pull requests whenever a string in my plugins needs localization.

**Comment by linonetwo** [comment]
I forget to mention this in #7821, so needs @roma0104 to close this issue now.

**Comment by Jermolene** [comment]
Thanks @linonetwo @roma0104
