### ISSUE TITLE
Wiki crashes on malformed tm-navigate message

### ISSUE THREAD

**Issue by Drakor** [Jermolene/TiddlyWiki5#1515]
Hi,
this is something I came across and it surprised me that it caused the wiki to become unusable.

## Problem
A malformed tm-navigate message, as can be created with a button or other message sending widgets, which does not include the correct properties on the event object, causes TiddlyWiki to crash when trying to edit and save a tiddler, or save the entire wiki.
In my opinion the user should be able to still save his recent changes, even when he has to reload the wiki for the problem to go away. But ideally the tm-navigate message should be handled in a way that it can't crash the wiki.

## How to repeat the problem:

Go to [tiddlywiki.com](http://www.tiddlywiki.com) (5.1.7) and make a new tiddler, containing:

    <$button message="tm-navigate" param="test">Crash me</$button>

Then save the tiddler and click the button. From this moment, the wiki becomes unusable with the problems described above.

/Andreas

**Comment by tobibeer** [comment]
Smells like a bug whereas tm-navigate should never navigate to a tiddler called `<emptyString>`.

**Comment by Jermolene** [comment]
Thanks @Drakor
