### ISSUE TITLE
[mistakenly posted - please delete]

### ISSUE THREAD

**Issue by twMat** [Jermolene/TiddlyWiki5#1524]
[message erased as it was too stoopid]

**Comment by pmario** [comment]
hmmm, 

IMO this is not an issue. If you don't want a link, don't use the syntax that creates one. So instead of [[no link needed]] use "no link needed". ... If you don't want a pretty link, don't use the syntax.

**Comment by twMat** [comment]
Darn, you're right. It was one of those things where something did cause a problem and you (ok, I) started testing out what works and what didn't and ...ah, never mind.

@Jermolene - please delete this embarassing thread. Sorry for the hassle.

**Comment by pmario** [comment]
:)
