### ISSUE TITLE
Prerelease: clicking on a tiddler moves it to the top

### ISSUE THREAD

**Issue by felixhayashi** [Jermolene/TiddlyWiki5#1526]
Hi @Jermolene,

I just downloaded the newest prerelease to work on the default sidebar tab pull request and I noticed that clicking on a tiddler moves it to the top. It is hard to copy and paste tiddler content and editing a tiddler is impossible. I hope it is not regarded as a new feature...

-Felix

**Comment by felixhayashi** [comment]
Ok I see you are aware of this behaviour (https://github.com/Jermolene/TiddlyWiki5/commit/83011ddcffe5b7dbcdbdb1c029adaf790f41862b)...

**Comment by tobibeer** [comment]
@felixhayashi, I have a hard time to follow... what does "moves it to the top" mean? ...if I know that I can perhaps follow what those dependent issues are.

**Comment by felixhayashi** [comment]
Hi @tobibeer 

just go to tiddlywiki.com/prerelease scroll down and click somewhere on a tiddler (e.g. the body or its outer frame).

**Comment by tobibeer** [comment]
oh, I see... that's surely not desirable, especially for editing

**Comment by Jermolene** [comment]
I've uploaded a prerelease so you can try out the fix:

http://tiddlywiki.com/prerelease/

**Comment by felixhayashi** [comment]
it works thanks
