### ISSUE TITLE
Option to define the default sidebar tab

### ISSUE THREAD

**Issue by felixhayashi** [Jermolene/TiddlyWiki5#1528]
As discussed in google groups https://groups.google.com/d/msg/tiddlywiki/CgmcRls_mkE/gOu_qzExXNkJ.

I am on it :)

**Comment by pmario** [comment]
imo can be closed, since PR is merged.

**Comment by felixhayashi** [comment]
true

**Comment by Jermolene** [comment]
Apologies, I was midway through some minor tweaks to #1529 in https://github.com/Jermolene/TiddlyWiki5/commit/42499ea6ffa524af6cf6dc86f4024798ec48eea9 when I fell ill.

**Comment by sukima** [comment]
Hope your feeling better!

**Comment by felixhayashi** [comment]
> Apologies, I was midway through some minor tweaks to #1529 in 42499ea when I fell ill.

Hi Jeremy, good to know you are recovering! (and thanks for tweaking the pull request).

-Felix

**Comment by Jermolene** [comment]
Thanks @felixhayashi @sukima, I'm mightily better now, but will be taking it easy for a few days.

**Comment by felixhayashi** [comment]
> but will be taking it easy for a few days.

:+1:
