### ISSUE TITLE
Run core js files through js uglifier to make tw smaller

### ISSUE THREAD

**Issue by felixhayashi** [Jermolene/TiddlyWiki5#1535]
Hi,

is there a particular reason that the wiki js code is not minimized? I mean, surely it is useful for debugging but then I rather prefer a minimized wiki and a non minimized wiki for development. I think it would make tw half the size of what it is now if all whitespace and comments were removed.

Using uglify.js, only the header would get a `@preserve` tag to keep the comments actually needed by tw. Then the uglyfier creates a new directory called min and replaces all js with minimized js at the same spot.

-Felix

**Comment by pmario** [comment]
+1 As long as we create and maintain a working source.map implementation for easy debugging. 
Otherwise -1

**Comment by Jermolene** [comment]
@felixhayashi the rationale for a long time has been that it encourages exploration and hacking to ship readable code. But minification gets more and more attractive the more that the core grows. Previous tests I've done suggest that we'd get a 60% saving on the JS code.

However, ideally, I'd want to be able to do the minification in the browser, to maintain the ability to make plugins within the browser. So I think we'd need to integrate the minification tool more thoroughly into TW. Uglify is a good candidate because it also exposes a JS parser, which is useful for creating annotated source docs like http://underscorejs.org/docs/underscore.html

**Comment by felixhayashi** [comment]
> the rationale for a long time has been that it encourages exploration and hacking to ship readable code.

Thanks @Jermolene for explaining. That's what I expected :)

> However, ideally, I'd want to be able to do the minification in the browser, to maintain the ability to make plugins within the browser.

Minification does not hinder you to develop in the browser or not? To lookup the code and the comments everybody can use github.

> I'd want to be able to do the minification in the browser

Sorry, I do not understand this one. Wouldn't that mean, we do not actually minimize the traffic for downloading tw? I mean, minification only makes sense if the wiki gets smaller for downloading...

**Comment by Jermolene** [comment]
> Minification does not hinder you to develop in the browser or not? 

Well, it makes it harder to debug through the core code. It's possible to use sourcemaps to link to the source code, but it is fiddly to set up.

But I was really talking about the build process: in order to maintain the ability to develop plugins in the browser, I'd want to do the uglification via a module integrated into TiddlyWiki, rather than only doing it as part of a traditional command line build process.

**Comment by felixhayashi** [comment]
> Well, it makes it harder to debug through the core code.

Debugging is a valid argument of course. I always develop with uglification turned off and when published, it is automatically turned on again. Not sure if this can be done for tw as a whole.

> I'd want to do the uglification via a module integrated into TiddlyWiki

But how can I minify the wiki then if I do not develop in the browser and want to automate the process (not clicking a "save minified wiki" button or similar).

Anyways just wanted to mention that the average tiddlywiki user who is not interested in any exploring/coding/debugging at all (since he/she is not a  programmer) would benefit from a minification since all that matter to him/her is download speed and how fast the browser parses the js.

So we will see what the future brings, if tw keeps growing like that, I see no other choice.

**Comment by pmario** [comment]
> I mean, minification only makes sense if the wiki gets smaller for downloading...

I think the download size shouldn't be the driving force for minification. A propper server sends html in a gziped format. So there shouldn't be that much difference. ... On the other hand a smaller file looks more appealing to me (as a user).

**Comment by pmario** [comment]
>But I was really talking about the build process: in order to maintain the ability to develop plugins in the browser, I'd want to do the uglification via a module integrated into TiddlyWiki, rather than only doing it as part of a traditional command line build process.

IMO this should be a plugin. 80% of the users are just users. Why should they carry uglify2.js with them, if they never need it.

**Comment by felixhayashi** [comment]
> A propper server sends html in a gziped format. 

I totally missed that @pmario. Still when attaching a wiki to an email (I do this often to exchange content with my team at university) or uploading it to dropbox (embarrassing to say, but my upload speed is quite weak :pensive:) I would appreciate smaller sizes.

> IMO this should be a plugin.

Yes, I strongly agree.

**Comment by pmario** [comment]
>  I would appreciate smaller sizes.

Me too. But we need to enable source maps in return. .. If I'm doing development for my own stuff, I can work with a debug (full source) version. .. that's ok. 

But if we have a (future) support request on google groups, it's easy to open a TW, hit F12 and have a look. With a minified core, we would need to export import the user content into a debug version, which definitely is more work and it may corrupt the source of the issue. 

As Jeremy wrote 

> Well, it makes it harder to debug through the core code. It's possible to use sourcemaps to link to the source code, but it is fiddly to set up.

... IMO we should establish a "build robot" that kicks in if we do a push to the main repo. ... This robot could do automatic testing, building the source map, deploy to "prerelease" if tests are ok. ... 

@Jermolene what do you think?

**Comment by felixhayashi** [comment]
@pmario ok understood.

> ... IMO we should establish a "build robot" that kicks in if we do a push to the main repo.

Yes, it wouldn't work otherwise. Doing that manually is annoying. In my plugin's build script I added a minify command that is executed before github push.

**Comment by Jermolene** [comment]
I think that supporting sourcemaps is pretty horrible and brittle. We can make it easy to use sourcemaps on tiddlywiki.com, but it will be incredibly awkward to support people wanting to use them against arbitrary versions of tiddlywiki hosted elsewhere.

**Comment by pmario** [comment]
@Jermolene .. I see.
What about the build robot? I was thinking about a travis-ci integration. ... But I'm not sure about the automatic deployment yet.

**Comment by sukima** [comment]
Has anyone looked into just a form of loss-less compression over minification? I might not be as idal as a lossy compression but would allow the compression to be done in the browser on the fly and still have discoverability in the same way base64 works for dicoverability.

Food for thought.

**Comment by pmario** [comment]
@Jermolene .. label: "newfeature"

**Comment by danielo515** [comment]
What about publishing a minified edition ? At least those who want minification would be able to download such edition

**Comment by Jermolene** [comment]
@danielo515 setting up and maintaining the minified edition would be a lot of additional work for core developers, and I've still yet to hear a compelling reason, given the other issues I've raised above:

* Minification makes debugging harder
* Minification doesn't give much benefit over GZIP compression, which is largely transparent
* Minification in the browser will take significant engineering to package a minifier as a plugin; alternately, if we just support minification under Node.js, it would add a new core dependency (there are none at present)

**Comment by danielo515** [comment]
Hello @Jermolene 

I don't see why it should have such overhead. I was thinking about something as simple as a robot or a travis-ci script that compiles all the core scripts, creates a empty.html file and uploads it to a subfolder under gh-pages branch of tiddlywiki. 
Maybe for the shake of simplicity this can be done at the same time the rest of the editions are built. I don't mean an edition in the traditional sense, I am talking about as a final step compress all the core code and bundle an html file in a subfolder, that's all.

**Comment by pmario** [comment]
I did some simple math. 

The TW core contains 268 *.js files which are combined 678kByte in size. Zipping those files results in a 286kByte zip file. ... So assuming minification reaches the same result, we actually gain 392 kbyte in size. 

So if a newbee user includes a single jpg image file with eg: 500kByte, all the size optimization is gone. ... Many users are not even able to scale there mobile images down. So they will include a 4mByte file. ... 

IMO that's not worth it. 

---

Other stuff, that just causes increased maintenance

Every tw *.js file has a "metadata header" as a block comment, that is essential for the processing of the modules. Those header can't be compressed. So the will weaken the minification rate. 

Every uglifier with default settings strips that code. ... So special handling is needed here. 

To make the core code debug-able, we need source-maps. Setting everything up in the right way is quite some work. Properly configured infrastructure is needed to host the stuff. ... Not being able to support our users is a no-go. So source map is a MUST have!!

**Comment by danielo515** [comment]
I am not talking a out making this​ the default editions. I'm talking about a minified versions for those power users that understand what does it mean. Not so much overhead for that one in my opinion

**Comment by flibbles** [comment]
I arrogantly and pompously suggest that my new plugin, https://flibbles.github.io/tw5-uglify/, is the solution to this issue, and thus this issue can be closed forever.

The core (or an empty wiki) can be minified by anyone in two minutes using drag-n-drop and a few mouse clicks.
People can decide for themselves if their server will serve uglified code.
Plugin developers can minify their plugins without the use of gulp.

(But I can't help you with all that ECMA Script 6 stuff of yours, @felixhayashi. You'd still need gulp for that.)

**Comment by Jermolene** [comment]
Thanks @flibbles @pmario
