### ISSUE TITLE
Allow shorthand macrocall syntax to specify an output format

### ISSUE THREAD

**Issue by aelocson** [Jermolene/TiddlyWiki5#1538]
[On the group](https://groups.google.com/forum/#!topic/tiddlywiki/AAMLCYRy1iw), I mentioned that it would be nice to be able to assign the result of a macro call to a variable. I suggested the following approach:

```
<$macrocall $variable="x" $name="m1" p1="this" p2="that" $output="text/plain">
    <$macrocall $name="m2" arg=<<x>>/>
</$macrocall>
```

The macrocall widget currently ignores its content, so I was suggesting there that the content could form the scope of the variable.

However, when I came to write this up as an issue on GitHub, I was struck by the similarity with the set widget. You can of course already write:

```
<$set name="x" <<m1 p1:this p2:that>>>
    <$macrocall $name="m2" arg=<<x>>/>
</$set>
```

This set me thinking, and my conclusion is that what we actually want is a way to tell the `<<…>>` syntax to return a simple text node rather than a wiki-parsed widget tree. We want to be able to say `$output="text/plain"` in the shorthand macrocall syntax, because that's the only syntax available for obtaining an attribute value via a macro call.

Perhaps we could simply reserve macro parameters whose names start with `$` for system use, just as we do with widget attributes, and then support `$output` as a system parameter:

```
<$set name="x" value=<<m1 p1:this p2:that $output:"text/plain">>>
    <$macrocall $name="m2" param=<<x>>/>
</$set>
```

**Comment by Jermolene** [comment]
Hmmm I was also wondering about integrating the new functionality into the `<$set>` widget. Something like:

```
<$set name="x" $macrocall="mymacro" param1=<<myparam>> param2="this">
<<stuff>>
</$set>
```

The problem is that it would introduce an inconsistency in the `$`-isation of attribute names: the `<$set>` widget already uses non-`$` attributes, so we couldn't use them for the parameters of the macro call.

I'm not so keen on extending the attribute syntax to wikify macro output because I think it would need a rather thorough refactoring of the widget implementation to ensure we had decent refresh behaviour.

I wonder about a completely new widget:

```
<$set-macro $tiddler="dest" $field="myfield" $name="mymacro" param1="something">
<<stuff>>
</$set-macro>
```

But now that I've typed it, I do see that it's a bit clumsy.

**Comment by aelocson** [comment]
> I'm not so keen on extending the attribute syntax to wikify macro output

Ah yes – sorry, I was overlooking the fact that, unlike the MacroCallWidget's execute method, `attr=<<macro>>` never parses the macro's result string.

I do like your idea of a completely new widget, as this is a new combination of existing functionality.

How about `<$let>`?

    <$let $variable="myvar" $name="mymacro" param1="something">
    <<stuff>> using <<myvar>>
    </$let>

As you suggest, the widget could also accept a `$tiddler`–`$field` attribute pair to allow the macro's result to be assigned to a field instead.

**Comment by aelocson** [comment]
Another possibility is a widget that renders its own content into a variable, then transcludes a template that makes use of that variable:

    <$capture variable="myvar" template="SomeOtherTiddler">
        <<mymacro param1:this param2:that>>
    </$capture>

This would allow the capturing of arbitrary WikiText, not just macro calls. (Macros can of course contain arbitrary WikiText, but this would allow a level of indirection to be omitted.)

Alternatively, both the content to be captured and the template could be children. This is structurally messier, but perhaps easier to use in practice:

    <$capture variable="myvar">
        <$cage>
            <<mymacro param1:this param2:that>>
        </$cage>
        template using <<myvar>>
    </$capture>

**Comment by pmario** [comment]
imo wikify widget does that: http://tiddlywiki.com/#WikifyWidget

**Comment by tobibeer** [comment]
@pmario: care to comment with a working example?

**Comment by pmario** [comment]
I don't have a simple example, for the use of the wikify widget. Most of the time `{{template}}` transclusions just work for me. 

I would need to have a closer look, at [the thread](https://groups.google.com/forum/#!topic/tiddlywiki/AAMLCYRy1iw) mentioned in the OP. ... 

Skimming the thread, makes me think. "You are doing it wrong" ... But I'm sure I don't understand the usecase atm. 

I'm sure, that there are cases, which can only be solved, using the `wikify` widget. ... I do have one, but it is super complicated, and can't be used as documentation ;)

**Comment by Jermolene** [comment]
Thanks @pmario
