### ISSUE TITLE
Recent changes to the scrolling mechanism can prevent normal scrolling

### ISSUE THREAD

**Issue by aelocson** [Jermolene/TiddlyWiki5#1543]
If I click a link to a tiddler that is already partly visible, then no scrolling occurs – unless what was visible of it was less than (I guess) the 50-pixel threshold introduced in 65d81921f9e9b8b0f32f384b59dad3aba0bc31fc.

For example, at http://tiddlywiki.com/prerelease/, go to HelloThere and click the link to Discover TiddlyWiki (DTW). Then scroll back up so that you can see both HelloThere's link to DTW and the tags area of DTW, and click the link again. Nothing happens.

But if you scroll back up so that you can just see the top of DTW, and click the link again, DTW scrolls up to the top in the expected way.

**Comment by cmari2** [comment]
Another version of the same, I think: in previous versions, when at the bottom of a long tiddler, clicking the link for that tiddler, either on the "open" tab in the sidebar or in a breadcrumb, used to shift focus back to the top of the tiddler. I found this useful.

**Comment by felixhayashi** [comment]
Hi. I once triggered a long discussion about the scrolling behaviour and I think this is highly related to this topic. Please see https://github.com/Jermolene/TiddlyWiki5/issues/1290

How this scrolling behavior looks in action can be seen at http:/bit.ly/tiddlymap. The github repo for the plugin is at https://github.com/felixhayashi/TW5-TopStoryView.

-Felix

**Comment by danielo515** [comment]
I am experiencing the same issue. It's specially annoying on mobile, where the sidebar is on the top. If you click any of the search results any scroll happens.

**Comment by Jermolene** [comment]
The primary purpose of the changes to the scroll behaviour was to avoid the unnecessary scrolling at startup that you see at http://tiddlywiki.com.

I'm open to refining it further, as long as the startup behaviour remains fixed. @aelocson do you have any thoughts as to an alternate algorithm?

**Comment by Jermolene** [comment]
> I am experiencing the same issue. It's specially annoying on mobile, where the sidebar is on the top. If you click any of the search results any scroll happens.

@danielo515 did you mean "if you click any of the search results **no** scroll happens"?

**Comment by danielo515** [comment]
> @danielo515 did you mean "if you click any of the search results no scroll happens"?
Hello @Jermolene 

If the list is long enough, it only scrolls to the very very top of the tiddler, and I cant' even see the title. If the list is not long enough then no scroll happens.

Regards

**Comment by tobibeer** [comment]
What might be good was if a tiddler shortly flashed, mildly when a link to it is clicked.

**Comment by felixhayashi** [comment]
At tiddlymap.org I use the TW5-TopStoryView plugin to always scroll to the top and I combine it with the TW5-HotZone plugin to add a short flash.
