### ISSUE TITLE
Making the introduction video reference more appealing.

### ISSUE THREAD

**Issue by felixhayashi** [Jermolene/TiddlyWiki5#1547]
Hi,

I personally find the introduction video link styling (a big red bar) very aggressive; looks like an error.

How about another way to embed the video. Since tiddlers actually look like sheets of paper, it would make sense to use a newspaper layout to embed images or video urls (floating in the text, subtitle, slightly separated). See the comparison below:

![comparison](https://cloud.githubusercontent.com/assets/4307137/6426815/809645b4-bf6c-11e4-8b0f-d66bd5836f84.png)

If @Jermolene is interested in this approach I can provide you with the css or create a pull request. I use this styling for one of my projects to embed images and videos and the floating can be changed by adding a class "left" or "right".

-Felix

**Comment by twMat** [comment]
I believe Jeremys argument against including an embedded youtube clip is that it would send a ping to youtube when it's loaded. Someting like that at least. And people may not be fully comfortable with that. Maybe you have a way to avoid this?

Come to think of it, IMO even a mere image link, i.e that looks like a youtube clip, would look better than the current button.

Regarding the newspaper feel - I like this idea, but it would deviate from the layout for the rest of the document so I don't think it would fit - or? 

However, I *would really* like a full "old newspaper theme"... but that's another issue (...no pun intended)

<:-)

**Comment by felixhayashi** [comment]
Hi Mat!

> Come to think of it, IMO even a mere image link, i.e that looks like a youtube clip, would look better than the current button.

Sure, a snapshot of the video or a cover sheet image would also work.

> Regarding the newspaper feel - I like this idea, but it would deviate from the layout for the rest of the document so I don't think it would fit - or? 

I just wanted to say people are familiar with images being embedded like this :)

> However, I would really like a full "old newspaper theme"... but that's another issue (...no pun intended)

Certainly would look great!

-Felix

**Comment by Spangenhelm** [comment]
Hi, you are right about the red button, usually the red color is being used for errors or dangers so it feels abnormal to find it here.

> Regarding the newspaper feel - I like this idea, but it would deviate from the layout for the rest of the document so I don't think it would fit.

Totally agree on that. Some people might be interested about a theme plugin but not for the main site, which must stay "sober".

**Comment by Jermolene** [comment]
I think the best solution is a new YouTube macro that incorporates a button/reveal combination to show a static screenshot overlaid with the play icon, that when clicked reveals the actual YouTube iframe.

**Comment by felixhayashi** [comment]
Hi @Jermolene,

Thanks for looking at this thread.

That would be great of course, very generic. It would be nice if the screenshot + overlay combi would possess a certain class so it can be styled.

-Felix

**Comment by Jermolene** [comment]
I'm uploading a new prerelease to http://tiddlywiki.com/prerelease. Here's what it looks like:

![screenshot 2015-03-22 17 36 32](https://cloud.githubusercontent.com/assets/174761/6770527/04252dec-d0ba-11e4-822a-24f4c44ba557.png)

I think it looks a bit dull that the thumbnail is the same drab colours as the main screen, but to fix that we'd need to fix the video too.

**Comment by felixhayashi** [comment]
Very charming!

**Comment by felixhayashi** [comment]
Hi @Jermolene 

maybe you can add something like this so we can always give videos a nice caption:

     <div class="tc-youtube-thumbnail"><div class="tc-youtube-caption">A video introduction</div>

The caption class being:

    element {
       background-color: gray;
       color: white;
       text-align: center;
   }

looks like

![selection_557](https://cloud.githubusercontent.com/assets/4307137/6770560/b8d6e40c-d0c3-11e4-9316-523d71e17dfe.png)

**Comment by twMat** [comment]
>I think it looks a bit dull that the thumbnail is the same drab colours as the main screen,

Maybe add a thin framing border... perhaps blue (for link), dark gray or ribbon red? I have no idea if it would look decent but it may live up it a bit.

BTW, the image needs a bit of left margin. (You just got lucky with your text wrap ;-)

**Comment by felixhayashi** [comment]
Mat I really miss your pointy head on github

**Comment by twMat** [comment]
That pointy guy is a rambling cone head, while *I* obviously am a terse "snappy and actionable" contributor with no room for such silly signatures.

**Comment by Jermolene** [comment]
Thanks @twMat good ideas. Here you go:

![screenshot 2015-03-22 18 02 18](https://cloud.githubusercontent.com/assets/174761/6770619/a44b675c-d0bd-11e4-92f6-3cff864482a5.png)

I've updated the prerelease, too.

**Comment by felixhayashi** [comment]
@Jermolene 

> Thanks @twMat good ideas.

Please also add my idea (https://github.com/Jermolene/TiddlyWiki5/issues/1547#issuecomment-84665369) :)

@twMat 

> with no room for such silly signatures.

Of course, I deeply apologize for referring to your alter ego. I was being ignorant.

>:-)

**Comment by Jermolene** [comment]
> I missed that you put caption below

Otherwise it overlaid the "TiddlyWiki" heading, which looked rough.

**Comment by felixhayashi** [comment]
> Otherwise it overlaid the "TiddlyWiki" heading, which looked rough.

Good point.

**Comment by Spangenhelm** [comment]
Hi everybody, the result looks good although it seems like the margin on the left of the video is not well rendered in Chromium 41 under linux, see the screenshot below:

![capture du 2015-03-22 19 52 06](https://cloud.githubusercontent.com/assets/6536752/6770818/f890db80-d0cc-11e4-955f-34db44230c88.png)

Can someone confirm it ? Because it may come from my modified system font configuration..

Thank you

**Comment by felixhayashi** [comment]
> Hi everybody, the result looks good although it seems like the margin on the left of the video is not well rendered in Chromium 41 under linux, see the screenshot below:

Same here with FF and Chrome in Linux Mint 17

![selection_560](https://cloud.githubusercontent.com/assets/4307137/6770907/294a6ce4-d0cf-11e4-849e-e111f7590a2c.png)

**Comment by Spangenhelm** [comment]
I have found what happened: it is because of my 150% zoom in my web browser. (under Linux Mint 17 too ;-)

**Comment by felixhayashi** [comment]
> it is because of my 150% zoom in my web browser

I have no zoom though

> under Linux Mint 17 too

Great choice

**Comment by Jermolene** [comment]
I've added a margin to the youtube preview, and uploaded a new prerelease.

**Comment by felixhayashi** [comment]
looks nice

**Comment by Spangenhelm** [comment]
+1 looks perfect even with the zoom, thanks Jeremy
