### ISSUE TITLE
"New Journal Here" modifies am/pm strings in tiddler title.

### ISSUE THREAD

**Issue by pmario** [Jermolene/TiddlyWiki5#1553]
see: https://groups.google.com/forum/#!topic/tiddlywiki/u2jluvbj9jE

To reproduce: 
- Set: ControlPanel: Title of new journal tiddlers:   `$(currentTiddler)$ - MM/DD/YYYY`
- create new tiddler named: `am pm`
- use "new journal here" button

depending on the local time either "am" or "pm" is modified. 
- the same happens, if you use "Development" in the tiddler title. 
- at eg: 10:00 local time it will result in "Develoament" :)

**Comment by Jermolene** [comment]
This quirk is because the title for new journal tiddlers is processed as a date format string. If you need to include text that would normally be substituted then you can escape it with backslash: "Develop\ment".

**Comment by Jermolene** [comment]
So I guess it's a documentation issue :smile:

**Comment by pmario** [comment]
If you use "Develomp\ment" in a tiddler title, the backslash in not escaped. ... So not really a solution. 

I think, there isn't an easy fix. ... since the date formatter would need to be extended in a compatible way. The problem is, that the date template doesn't contain an indicator, if something is plain text or a date formatting rule. eg. asdf-am-asdf is a valid template and asdfamasdf is valid too :/

**Comment by Jermolene** [comment]
Hi @pmario 

> If you use "Develomp\ment" in a tiddler title, the backslash in not escaped. ... So not really a solution.

It works for me, try it - if you use the backslash in the new journal template then it will be escaped during the date format string substitution. So the tiddler title ends up as "Development"

**Comment by pmario** [comment]
>It works for me, try it - if you use the backslash in the new journal template then it will be escaped during the date format string substitution. So the tiddler title ends up as "Development"

That's right, but the tiddler title itself is ugly and can't be used any more.

**Comment by Jermolene** [comment]
Sorry @pmario what do you mean by "the tiddler title itself is ugly and can't be used any more."? As I say, there's no backslashes in the resulting tiddler title.




Best wishes




Jeremy






—
jeremy.ruston@gmail.com

**Comment by pmario** [comment]
This is the Template: 

```
$(currentTiddler)$ - MM/DD/YYYY
```

No user will name a tiddler like this:"I a\m Mario" , just to be sure, that the "New Journal" button doesn't cause a problem.

**Comment by Jermolene** [comment]
Hi @pmario ah, I see what you mean. The ability to use `$(currentTiddler)$` within the journal template is kind of accidental, and problematic for exactly the reasons that you describe. I wouldn't advise using it.

**Comment by pmario** [comment]
hmmm, but it is super convenient. .... What, if we would create 2 new config tiddlers eg: 

`$:/config/NewJournalHere/pre` and `$:/config/NewJournalHere/post`, which could be used in `$:/core/ui/Buttons/new-journal-here`

eg: 

create a tiddler `$:/config/NewJournalHere/pre` with content: `$(currentTiddler)$ - `
create a tiddler `$:/config/NewJournalHere/post` with content: ` - x`  ... just for testing

change `$:/core/ui/Buttons/new-journal-here` to 

```
\define newJournalHereNow()
$(pre)$$(njhnow)$$(post)$
\end
\define journalButtonTags()
[[$(currentTiddlerTag)$]] $(journalTags)$
\end
\define journalButton()
<$set name="njhnow" value=<<now "$(journalTitleTemplate)$">>>
<$button tooltip={{$:/language/Buttons/NewJournalHere/Hint}} aria-label={{$:/language/Buttons/NewJournalHere/Caption}} class=<<tv-config-toolbar-class>>>
<$action-sendmessage $message="tm-new-tiddler" title=<<newJournalHereNow>> tags=<<journalButtonTags>>/>
<$list filter="[<tv-config-toolbar-icons>prefix[yes]]">
{{$:/core/images/new-journal-button}}
</$list>
<$list filter="[<tv-config-toolbar-text>prefix[yes]]">
<span class="tc-btn-text"><$text text={{$:/language/Buttons/NewJournalHere/Caption}}/></span>
</$list>
</$button>
</$set>
\end
<$set name="pre" value={{$:/config/NewJournalHere/pre}}>
<$set name="post" value={{$:/config/NewJournalHere/post}}>
<$set name="journalTitleTemplate" value={{$:/config/NewJournal/Title}}>
<$set name="journalTags" value={{$:/config/NewJournal/Tags}}>
<$set name="currentTiddlerTag" value=<<currentTiddler>>>
<<journalButton>>
</$set></$set></$set></$set></$set>
```

and test the new "New Journal Here" button ... what do you think.

**Comment by pmario** [comment]
If the `<<now>>` macro would accept some more $1, $2, $3 replacement parameters, imo it would be also possible.

**Comment by Jermolene** [comment]
Interesting idea. My only concern is whether the UI might end up a little complicated to explain.

**Comment by tobibeer** [comment]
I think we need two things:

1. the date format template
2. a template for the title with a suitable placeholder for the dateformat, even `$(dateFormat)$`

When a new journal title is generated, the only thing affected by the date format is the date format bit, nothing else.

However, this would possibly be backwards incompatible, since the previously 1 template would need to be split up in two... and there's no automagic way to migrate.

**Comment by pmario** [comment]
I have no idea, how to solve it atm. move it to my scratchpad and close.
