### ISSUE TITLE
 Calling for pagetemplate specs

### ISSUE THREAD

**Issue by twMat** [Jermolene/TiddlyWiki5#1559]
@Jermolene 

Ref #142 and possibly other issues, I'm wondering about the status and intention for allowing additions of user defined page template elements such as a left sidebar, a horizontal top bar, etc. Particularly these two mentioned are recurring requests for TW applications (and, along with a footer, very common features on webistes) but ideally we should have a generic approach to allow for "any" additional pagetemplate element.

I see two "simpler" approaches (or half-meausres?): One would be premade templates that the user could choose from (thus *not* a general approach). I.e a few variants where the current is just one; one with a left sidebar, another with a top bar, another with both of those, etc. This way we would not need to rely on automatic positioning (which I understand is what is problematic) of the elements but could instead specify positions for each.

Another idea would be to 'give consent' to the prevailing small screen situation and not bother with side-by-side elements but instead use layers and have some method to position elements in each respective layer. With the small screens, side "slide-ins" are popular and AFAI can tell, this would simplify a lot.

Regardless of preference, I'm hoping that @Jermolene could give some kind of formulation/specification for what is desired so that people know what to work on. If there are no clear ideas, then bringing it up for discussion (on the boards?) to get input may be a good first step? Thank you :-)

**Comment by sukima** [comment]
Can this be further discussed? I had the same problem that @tobibeer had and ended up using [his hack](http://tobibeer.github.io/tb5/#%24%3A%2Fhack-142-scroll-pagescroller.js) which doesn't seem very canonical.

**Comment by Jermolene** [comment]
Hi @sukima I think the best approach for this and for some other layout related issues like #1282 would be adopt a flexbox-based layout for the screen. That would allow us to have variable sized sidebars docked to any side of the screen, with the main viewport automatically resizing the consume the remaining space.

**Comment by twMat** [comment]
Closing this issue because it is not specific and probably not actionable. The main gist is still relevant for an issue tho but I don't have the knowledge to formulate it properly.
