### ISSUE TITLE
add a special case of empty "list-after" to place a tagged tiddler at the very end of the list

### ISSUE THREAD

**Issue by rubaboo** [Jermolene/TiddlyWiki5#1562]
Similar to how it is with list-before.

**Comment by tobibeer** [comment]
PR?

**Comment by pmario** [comment]
the new drag and drop mechanism in the tag pill will automatically modify the list field. So it's easy to change the order 

imo this issue can be closed now.

**Comment by rubaboo** [comment]
This is not about tag pills. "list-before" and "list-after" are used to manipulate the order of tiddlers tagged with the same tag. For example, order of buttons on a toolbar. Say, I am adding a button to the ViewToolbar, I want it at a certain positoin in the ViewToolbar, but don't want to modify the "list" field of $:/tags/ViewToolbar to achieve that.

**Comment by pmario** [comment]
list fields are always associated with tags. So every list, that is based on tags can be drag & dropped now. 

So just add `<<tag "$:/tags/ViewTemplate">>` to a tiddler and you'll get a UI to manipulate the tiddler structure. ... IMO this mechanism will take over in the future.

**Comment by tobibeer** [comment]
> just add `<<tag "$:/tags/ViewTemplate">>` to a tiddler and you'll get a UI to manipulate the tiddler structure with d&d

Ha! While that is a neat trick, I suggest we have something inthe controlpanel for reordering the most important ones of those.

**Comment by flibbles** [comment]
I don't know nothin' about no drag'n'drop, but I do know that having this behavior for list-after would be nice for my projects, where I use hundreds of custom tags for specifying small tiddler lists, and order _usually_ doesn't matter, but would sometimes like to have one particular tiddler always at the end of the list without having to resort to `[nsort[]]`.

This change is only two lines of code:

```javascript
title: $:/core/modules/wiki.js
. . .
exports.sortByList = function(array,listTitle) {
. . .
				if(beforeTitle === "") {
					newPos = 0;
>>>>>>>>>>>
				} else if(afterTitle === "") {
					newPos = titles.length;
>>>>>>>>>>>
				} else if(beforeTitle) {
					newPos = titles.indexOf(beforeTitle);
. . .
}
```
Oh, and the small change to list-after's documentation string.

Doesn't break anything as far as I can tell. It's intuitive. If you agree with this change, I can make a pull request if you'd like.

-Flibbles

**Comment by pmario** [comment]
hmm. create a PR

**Comment by pmario** [comment]
+ docs

**Comment by flibbles** [comment]
Done. Let me know if there's anything I've forgotten about.

**Comment by pmario** [comment]
PR #3219 has been merged. @rubaboo ... can you close this issue?

**Comment by Jermolene** [comment]
Thanks @pmario
