### ISSUE TITLE
Letting more widgets invoke actions/send messages

### ISSUE THREAD

**Issue by inmysocks** [Jermolene/TiddlyWiki5#1563]
I have been experimenting adding the ability to invoke actions to these widgets:

link
radio
checkbox
select

The link widget invokes actions just like a button widget, when you click on the link it opens the link and invokes any action widgets contained in the widget.

I added a currentOption variable to the radio widget so that takes the value of the option being switched to so you can use the value that is being switched as well as the one switched away from when invoking action widgets.

I couldn't come up with a way to separate the list of actions checking vs unchecking actions for the  checkbox widget without using the reveal widget, but I think that is a reasonable solution.

The select widget triggers any actions in side the option tags for the selected option. I still need to add support for using value lists, currently it when you have a value= part in an option and I don't know why.

Here is the current code: https://github.com/inmysocks/WidgetsInvokeActions

Are there any other widget I should try to add this to and does anyone have suggestions before I do a pull request?

The select widget isn't read until I fix the value list problem, but the others should be good.

**Comment by sukima** [comment]
Pull request?

**Comment by inmysocks** [comment]
The select widget works with value lists now.

sukima, I would like to include this functionality in the core link, radio, checkbox and select widgets. I would like to get feedback from other people before submitting the change.

**Comment by felixhayashi** [comment]
Hi @inmysocks 

> I would like to include this functionality in the core link, radio, checkbox and select widgets.

Hi Jed,

as said before, I really appreciate you added the invokeActions stuff to the widgets to allow putting actionwidgets in the body. I always wanted to create a pull request for that and never found the time so :+1: 

> I couldn't come up with a way to separate the list of actions checking vs unchecking actions for the checkbox widget without using the reveal widget, but I think that is a reasonable solution.

I think you should not worry about that, I mean while it would be nice to include the current state in the event object (checkbox on or off) the handler can simply have a look at the current state of the field.

-Felix

**Comment by felixhayashi** [comment]
> I would like to get feedback from other people before submitting the change.

It is maybe better to create the pull request already with correct naming of the functions then we can see a diff of the code which makes comparison easier.

**Comment by sukima** [comment]
Make pull request is getting feedback. Then we can discuss it, code review, comments, rebase, add commits, and eventually merge.

**Comment by tobibeer** [comment]
I would recommend not to close an issue before a PR is merged.

**Comment by AnthonyMuscio** [comment]
I am keen to get actions on the radio widget and found this Issue

**Comment by Jermolene** [comment]
Hi @AnthonyMuscio as I commented [over at #1564](https://github.com/Jermolene/TiddlyWiki5/pull/1564#issuecomment-145329189), there's currently no viable way to implementing actions for widgets such as the radio widget which modify the wiki store at the same time as triggering their actions.
