### ISSUE TITLE
Weird bug

### ISSUE THREAD

**Issue by felixhayashi** [Jermolene/TiddlyWiki5#1566]
Hi, can anybody confirm this please (related to #1565):

This will produce an error in CHROME (linux mint 17; Chrome 40)

    $tw.wiki.addTiddler(new $tw.Tiddler({
      title: "test",
      modified: {},
      created: {},
    }));

But **not** an error in Firefox (Linux, FF 36)

Thanks

-Felix

**Comment by pmario** [comment]
imo modified and created are strings. so you can't assign objects.

**Comment by pmario** [comment]
imo you should use `$tw.wiki.getModificationFields()` and `$tw.wiki.getCreationFields()`
like so:

```
$tw.wiki.addTiddler(new $tw.Tiddler(
      {title: "test"}, 
      $tw.wiki.getModificationFields(),
      $tw.wiki.getCreationFields(),
));
```
