### ISSUE TITLE
Trim whitespace from text and target of pretty links

### ISSUE THREAD

**Issue by reflectionalist** [Jermolene/TiddlyWiki5#1569]
## Summary

The issue is best demonstrated by example.  The following Wiki text

```
I think [[TiddlyWiki | http://tiddlywiki.com]] is awesome.
```

would render as

> I think [TiddlyWiki ](http://tiddlywiki.com)is awesome.

Note the trailing space of the linked text (move your mouse to the linked text to see the problem).  The issue can be avoided by removing the space before the `|`, so the following Wiki text

```
I think [[TiddlyWiki| http://tiddlywiki.com]] is awesome.
```

renders fine as

> I think [TiddlyWiki](http://tiddlywiki.com) is awesome.

However, disallowing spaces before the `|` is annoying.  Note also that the issue disappears when the linked text is not followed by non-space characters.  So the following Wiki text

```
I like [[TiddlyWiki | http://tiddlywiki.com]]  

Because it is awesome!
```

renders fine.  But the issue reappears inside triple quotes.  So the following Wiki text

```
"""
I like [[TiddlyWiki | http://tiddlywiki.com]]  
because it is awesome!
"""
```

would result in an extra space in the linked text again.
## Reproduction

The exact effect cannot be accurately demonstrated using Markdown here.  So it is best to copy and paste the code above into a Tiddler to see the exact result.
## Expectation

The expected behavior is that linked text is displayed without any trailing space regardless of any space before `|` in the Wiki text.
## Context

OS: Kubuntu 14.04 LTS (64bit)
Browsers: The main issue exist in both Firefox (36.0) and Chromium (40.0.2214.111).  However, the code invovling triple quotes above renders fine in Firefox but not in Chromium.

**Comment by Jermolene** [comment]
Thanks @reflectionalist 

If I'm understanding correctly, the desired fix is for pretty links to trim any whitespace from the end of the link text. The motivation is to be able to insert additional whitespace to improve the readability of the wikitext.

Would you also want to trim whitespace from the start of the link text?

Your example that includes whitespace before the link target may also indicate a problem: the space is considered to be part of the link target, so `[[TW | TiddlyWiki]]` will attempt to link to a tiddler called ` TiddlyWiki` (with a leading space).

**Comment by reflectionalist** [comment]
> If I'm understanding correctly, the desired fix is for pretty links to trim any whitespace from the end of the link text. The motivation is to be able to insert additional whitespace to improve the readability of the wikitext.

Exactly!

> Would you also want to trim whitespace from the start of the link text?

I just tried your example, it TW indeed attempts to link to a tiddler whose title has a leading space.  So yes.

**Comment by pmario** [comment]
Since trailing whitespace in tiddler title is allowed and can't be changed, whithout breaking backwards compatibility. IMO this issue can't be fixed!

see: https://github.com/Jermolene/TiddlyWiki5/issues/751#issuecomment-111979579 and the whole thread

**Comment by tobibeer** [comment]
Sry, I will never agree to leading or trailing blanks in titles (or filenames!) as valid. Why bother supporting this? Instead, this always asks for encoding under the hood, in the sense that the same encoding can then be leveraged in wikitext to produce ...a blank.

**Comment by pmario** [comment]
>Sry, I will never agree to leading or trailing blanks in titles (or filenames!) as valid. Why bother supporting this? Instead, this always asks for encoding under the hood, in the sense that the same encoding can then be leveraged in wikitext to produce ...a blank.

I'm with you. ... but

"Backwards compatibility" beats all arguments. 

... And the fix for reliably removing whitespace in titddler titles is at the hart of the `new Tiddler()` function. So it will affect absolutely everything and it will break some existing code.

**Comment by tobibeer** [comment]
There is no compatibility requirement for broken parts. They need to be replaced or simply thrown out.

**Comment by tobibeer** [comment]
> So it will affect absolutely everything and it will break some existing code.

Please give an example.

**Comment by Jermolene** [comment]
The OP is specifically about trimming the displayed text portion of the pretty link syntax. I can't think of any other places where we trim white space when we extract delimited text from wikitext (eg, in table cells the leading and trailing whitespace is significant).

**Comment by tobibeer** [comment]
I definitely cannot envision someone seriously wishing to link a title with a leading or trailing blank. So, fixing both the pretty title as well as the target of a link... I see zero problems with that. You can, in fact add as many newlines, spaces, tabs... whitespaces, as you want. I don't think it would bother me, at all if all of those where "trum". :D

**Comment by pmario** [comment]
@Jermolene ... IMO a "won't fix", would be a clear statement. ... There have been several other reqeusts for trimming whitespace, which where all rejected.

**Comment by Jermolene** [comment]
Thanks @pmario
