### ISSUE TITLE
Sync error while processing drafts

### ISSUE THREAD

**Issue by kejadlen** [Jermolene/TiddlyWiki5#1570]
Even though these drafts don't exist anymore, I'm getting errors like the following when opening my personal hosted TiddlyWiki:

```
Sync error while processing 'Draft of 'New Tiddler: Error: ENOENT, unlink '/home/ubuntu/tiddlywiki/tiddlers/Draft_of_'New_Tiddler'.tid'
```

In the above example, it's a new tiddler, but I'm also seeing it for other pages that I've edited. Are the quotes in the path significant?

**Comment by Jermolene** [comment]
Hi @kejadlen thank you, that's helpful. The quotes are part of the title of draft tiddlers.

Just to confirm,  if you start the server and then navigate to the index file in a browser, you are reliably experiencing the error you quoted? Do you see any other messages on the command line?

**Comment by kejadlen** [comment]
Yep, every time I reload the page, I get those errors popping up.

On startup, I don't see anything out of the ordinary:

```
Serving on 127.0.0.1:8080                                                
(press ctrl-C to exit)                                                   
syncer-server: Dispatching 'save' task: $:/StoryList                     
FileSystem: Saved file /home/ubuntu/tiddlywiki/tiddlers/$__StoryList.tid 
```

I'm also running TiddlyWiki in multiple browsers simultaneously - would that affect anything?

**Comment by Jermolene** [comment]
> I'm also running TiddlyWiki in multiple browsers simultaneously - would that affect anything?

Interesting. I don't test in multi-browser configurations at the moment. I assume you get the error even when you've only got the wiki open in a single browser window?

Also, just to be clear, does the error occur as soon as the page loads, or do you have to perform an interaction to trigger it?

Could you also report any messages that you're seeing in the browser JS console after reloading the file?

**Comment by kejadlen** [comment]
Curious - I'm not seeing it anymore. Perhaps restarting the tiddlywiki server fixed the issue? I'll keep an eye out if I see this bug again.

I see this error immediately after reloading the page, in one of those yellow notification boxes in the top left.

**Comment by nameanyone** [comment]
I get this all the time, running the nodejs version, open in a single browser tab. Error pops up on page refresh. Restarting TW clears it up. Can I catch some useful debug info next time this happens?

**Comment by Jermolene** [comment]
Thanks @nameanyone what I'd really appreciate is some foolproof steps to reproduce the problem - it looks like it's a combination of having a tiddler in draft mode when network connectivity is lost, but the details have eluded me so far.

**Comment by nameanyone** [comment]
Same here, or I would've reported it long time ago. Always strikes unexpectedly. I'll try to be more attentive.

**Comment by pmario** [comment]
@kejadlen ... there have been changes in the latest server code. is this still a problem?

**Comment by kejadlen** [comment]
Haven't used TiddlyWiki in a while, so I can't say, sorry!

**Comment by pmario** [comment]
@Jermolene ... pls close, server code has changed quite a bit since 2015.

**Comment by Jermolene** [comment]
Thanks @pmario
