### ISSUE TITLE
additional action to reload external images for a tiddler

### ISSUE THREAD

**Issue by achary** [Jermolene/TiddlyWiki5#1576]
This is a new feature request rather than an issue.

When working with tiddlers that have display external images, and when these images are being edited in external editor, I've found no other way to refresh it's preview in tiddlywiki than reloading the whole page loosing the currently opened tiddlers etc. Even editing and saving tiddler doesn't cause re-load external images.

It will be quite convenient to have "reload" action under "More actions" dropdown menu of a tiddler that reloads the tiddler content including external images for this tiddler.

cheers,
adam

**Comment by Jermolene** [comment]
Hi @achary 

The common technique to force a browser to reload an image is to add a cache-buster query string:

```
<img href="myimage.jpg?cachebust=1982738741238971239
```

(See http://stackoverflow.com/questions/1077041/refresh-image-with-a-new-one-at-the-same-url for more discussion)

The technique could be adapted for TW with a macro like this:

```
\define image-inner(url,attributes)
[img $attributes$ [$url$$(cachebuster)$]]
\end

\define image(url,attributes)
<$set name="cachebuster" value=<<now "YYYYMMDDhhmmss">>>
<<image-inner>>
</$set>
\end
```

You'd use the macro like this:

```
<<image "myimage.jpg">>
<<image url:"myimage.jpg" attributes:"width=20 height=30">>
```

Then you'll be able to refresh a tiddler by flicking it in and out of edit mode. A useful trick is that you can force a refresh of the whole display by switching themes or language.

**Comment by pmario** [comment]
@achary .. does the suggestion solve your problem. .. If yes please close.

**Comment by pmario** [comment]
@Jermolene ... you did provide a work around. .. So imo can be closed!

**Comment by Jermolene** [comment]
Thanks @pmario
