### ISSUE TITLE
Installation fails

### ISSUE THREAD

**Issue by Kenarso** [Jermolene/TiddlyWiki5#1580]
I will install TW5 with nods on Raspberry Pi2, because I cant use TW with apache.
But during the installation (I follow the instruction from here) at the4e command 
sudo npm install -g tiddlywiki
a list of errors.
====================
pi@raspberrypi ~ $ sudo npm install -g tiddlywiki
npm http GET https://registry.npmjs.org/tiddlywiki

npm ERR! Error: failed to fetch from registry: tiddlywiki
npm ERR!     at /usr/share/npm/lib/utils/npm-registry-client/get.js:139:12
npm ERR!     at cb (/usr/share/npm/lib/utils/npm-registry-client/request.js:31:9)
npm ERR!     at Request._callback (/usr/share/npm/lib/utils/npm-registry-client/request.js:136:18)
npm ERR!     at Request.callback (/usr/lib/nodejs/request/main.js:119:22)
npm ERR!     at Request.<anonymous> (/usr/lib/nodejs/request/main.js:212:58)
npm ERR!     at Request.emit (events.js:88:20)
npm ERR!     at ClientRequest.<anonymous> (/usr/lib/nodejs/request/main.js:412:12)
npm ERR!     at ClientRequest.g (events.js:156:14)
npm ERR!     at ClientRequest.emit (events.js:67:17)
npm ERR!     at HTTPParser.parserOnIncomingClient [as onIncoming] (http.js:1256:7)
npm ERR! You may report this log at:
npm ERR!     <http://bugs.debian.org/npm>
npm ERR! or use
npm ERR!     reportbug --attach /home/pi/npm-debug.log npm
npm ERR!
npm ERR! System Linux 3.18.7-v7+
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "tiddlywiki"
npm ERR! cwd /home/pi
npm ERR! node -v v0.6.19
npm ERR! npm -v 1.1.4
npm ERR! message failed to fetch from registry: tiddlywiki
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /home/pi/npm-debug.log
npm not ok
pi@raspberrypi ~ $
---------------------------------------------
Anyone an idea?

**Comment by Jermolene** [comment]
Hi @Kenarso I've not encountered this problem, but Google suggests one possible resolution:

http://stackoverflow.com/a/23025752/3111487

**Comment by Kenarso** [comment]
Sorry, but I don´t understand your opinion.
I should use first the command "npm config set registry http://registry.npmjs.org/" abd then "npm install -g tiddlywiki" ?
I try it, but the follwing ist the result

pi@raspberrypi ~ $ sudo npm config set registry http://registry.npmjs.org/
pi@raspberrypi ~ $ sudo npm install -g tiddlywiki
npm http GET http://registry.npmjs.org/tiddlywiki
npm http 200 http://registry.npmjs.org/tiddlywiki
npm http GET http://registry.npmjs.org/tiddlywiki/-/tiddlywiki-5.0.0-alpha.7.tgz
npm http 200 http://registry.npmjs.org/tiddlywiki/-/tiddlywiki-5.0.0-alpha.7.tgz

And then nothing happens. Thats all.

**Comment by Jermolene** [comment]
Hi @Kenarso the last two lines of the error message you quote indicates that npm is trying to download a very old version of TW (5.0.0-alpha.7 was released about two years ago). The first error messages you quote include the following:

```
npm ERR! node -v v0.6.19
npm ERR! npm -v 1.1.4
```

That suggests that you're using a very old version of node.js and npm - v0.6.19 is from June 2012.

So, I guess you need to try to install more recent versions of node and npm, and try to install TiddlyWiki again.

**Comment by Kenarso** [comment]
OK, then I think I can´t use node with Tiddlywiki on my Raspberri PI 2. Because I can only use the versions that are in the repositiries. But perhaps I built my on new package for the raspberri Pi if i Have time enough.
Thx for your help

Update
-------
OK, noe I found a way that i can install. 
But I cant get the page.
When i use the IP from my serve for example: 192.168.18.52:8080 then I get the the error, that the access denied
When I use the IP 192.168.18.52:80
then I get the info, that the  web server is in function.
Thats all.

**Comment by Jermolene** [comment]
By the way, over at #1583 there's some discussion from somebody who is running TW a Raspberry Pi.

**Comment by Basilmir** [comment]
Did you install node.js and nom via a precompiled package or did you compile them on the Pi 2?

**Comment by Kenarso** [comment]
Thx for your help, but I closed the installation. I think thats not the right software for me.
Thx at all.
