### ISSUE TITLE
Tiddlywiki runs slowly and lags behind when using --password 'something' on node.js and nginx server?

### ISSUE THREAD

**Issue by Basilmir** [Jermolene/TiddlyWiki5#1583]
Installed Raspbian, nginx and the nodejs package from their repository using apt-get. Everything is super! But I noticed this distinct slowness when accessing the app. It's like a 7-10 sec pause before everything loads.

I installed and used tiddlywiki server many times in the past. And it's true, there it was again that 7-10 sec delay when you refresh the page. The app seems to run fine, POST and GET is instant once it's up and running in the Web Browser, but the delay is there if I refresh the page.

NOTE: If I restart the Pi and wait for it to restart the first time I access the app URL the delay seems to double, about 15 sec. Nginx html pages seem lightning fast in comparison. Running other examples seems to be lightning fast too on this quad-core 900mhz ARM v7 with 1GB of ram.

I'm starting the wiki with an 

su - pi -c "tiddlywiki myappfolder --server --password Something"

Any thoughts on this? It take around 20 seconds to refresh the page entirely, essentially reload the app from scratch, the transfer itself is 1.8 mb.

**Comment by Jermolene** [comment]
There's a lot more processing by TW5 to generate the main index.html than is needed for serving a static file. Nonetheless, that sounds like an excessive delay. Are subsequent refreshes any faster?

One thing that might help to debug things is to use something like https://github.com/node-inspector/node-inspector to let you use a browser on another computer to connect to the Blink developer tools on the Pi. Then you might be able to use the performance tools to see what's going on.

**Comment by Basilmir** [comment]
True, I understand that maybe the package is needs some kind of computation, but taking this long... I'm thinking maybe nodeJS is not optimized for this hardware? The trick is, if I launch a Hello world! example the response is instant, and that kind of rules out nodeJS as lagging behind. If it was doing something behind the scene it would be doing it first time, every time you run an app.

Once the Pi is up and running first page load:
1ms DNS 
1ms Connecting 
1ms Sending Request 
31000ms (31s) Waiting (for response) 
3850ms (3.85s) Receiving (size 1.8mb)

Once it's loaded the first time since booting clicking refresh brings up the same results:
1ms DNS 
1ms Connecting 
1ms Sending Request 
16000ms (16s) Waiting (for response) 
3560ms (3.56s) Receiving (size 1.8mb)

Firefox and Firebug.

Is there a kind of log or console for nodeJS to see if it raises any errors?

**Comment by Basilmir** [comment]
Waaait... something is up. I was trying to make the server accessible to everyone in the hope of flushing out the problem. Just started my server with:

su - pi -c "tiddlywiki myappfolder --server "
instead of
su - pi -c "tiddlywiki myappfolder --server --password Something"

My tiddlers are all visible, so that password thing seems to have done nothing to encrypt them (no biggie, only test ones online) but load times are down to 2 seconds form 20 seconds before, also the size of the download is down from 1.8MB to 474KB.

1ms DNS 
1ms Connecting 
1ms Sending Request 
873ms Waiting (for response) 
683 Receiving (size 474.7KB)

**Comment by Jermolene** [comment]
Hi @Basilmir apologies for the delayed response.

The `--password` command doesn't do what you think it does. It causes the serialised wiki html file to be encrypted, which is indeed a time-consuming operation.

You probably want to set a password for access to the wiki. You'd do that with the username and password parameters to the server command:

http://tiddlywiki.com/#ServerCommand

**Comment by Basilmir** [comment]
I see, so it's basically encrypted in transit and arrives encrypted in the client's browser, which in turn uses that password to decrypt it. Interesting, To the end user, it's similar to what SSL does exept for the browser part. 

I'll look into ServerCommand, but I'll probably need SSL for that to make something more than just an authenticator. 

One more thing, when I tried out these features I remember being very confused about the server user password command and this --password option thinking they were one and the same. It'd be better to consider changing --password to something like --encryptwithpassword or --encryptionkey so it stands apart from the other command that does only user/password authentication.

**Comment by Jermolene** [comment]
Hi @Basilmir 

> I see, so it's basically encrypted in transit and arrives encrypted in the client's browser, which in turn uses that password to decrypt it. Interesting, To the end user, it's similar to what SSL does exept for the browser part.

Yes. It's really only useful when one is working with the single file edition. As you suggest, if SSL is being used then there's no benefit in encrypting the page content.

> One more thing, when I tried out these features I remember being very confused about the server user password command and this --password option thinking they were one and the same. It'd be better to consider changing --password to something like --encryptwithpassword or --encryptionkey so it stands apart from the other command that does only user/password authentication.

Yes, the command names are a little confusing. The docs could be improved, too; the password command docs just say "Set a password for subsequent crypto operations".

**Comment by Basilmir** [comment]
One more thing... It just occurred to me that this --password Something encrypts the Tiddlywiki package, however, once the package is in the client's browser and he enters the password to decrypt it, if one adds a tiddler and that tiddler is communicated (POST) back to the server to saving, is this communication encrypted in any form?

**Comment by Jermolene** [comment]
Hi @Basilmir no, the client-server sync protocol is plaintext JSON over HTTP. The `--password` command is intended for producing encrypted static HTML TiddlyWiki files like http://tiddlywiki.com/encrypted.html (password is "password"). In the client-server configuration encryption, if needed, should be provided with HTTPS.

**Comment by Basilmir** [comment]
@Jermolene Ok got it!

PS. Loading http://tiddlywiki.com/encrypted.html experiences the same 'lag' as I was getting on my setup. Good to know it's not related to the Pi but rather to the heavy computation going on.

**Comment by pmario** [comment]
@Basilmir ... did you solve the problem?

`su - pi -c "tiddlywiki myappfolder --server --password Something"` .. can't be used in the nginx configuration, that you describe. 

If you need encryption you'll need to configure TLS SSL at the nginx level.

**Comment by pmario** [comment]
@Jermolene ... IMO can be closed

**Comment by Jermolene** [comment]
Thanks @pmario
