### ISSUE TITLE
[tw.com] Doc needed for general overview on lists

### ISSUE THREAD

**Issue by twMat** [Jermolene/TiddlyWiki5#1584]
For tw.com documentation I wish there was an (even more) introductory _overview_ on the concept of lists. It is such a super fundamental concept in TW so it warrants minimizing confusion. Perhaps a tiddler titled "Lists in TiddlyWiki" that with a few words treats and compares all the different occurences of "lists" (application contexts, etc). See below for example.

...and/or, even: A tiddler "Lists and Filters in TiddlyWiki" including (or linking to) the above and also the nice introductory tiddler [Filters](http://tiddlywiki.com/prerelease/#Filters) (5.1.8) and describing the relation between the concepts of "lists" and "filters".

So, for the overview of the concept of _lists_, I mean e.g:
- That the lists described in "Lists in WikiText" is about html-type lists (right?)
- ...as opposed to ListWidget which is what dynamically generates lists by using filters.
- That list-links Macro is a "one off, for convenience" (right?) special macro to produce a list already formatted.
- That ListField isn't a listing tool, but a predefined field name to manually specify the ordering in a list (...mentioning also list-after, list-before etc)<br>
  ...etc (list Operator, listed Operator,.. more?)

BTW,
- [Title List](http://tiddlywiki.com/prerelease/#Title%20List) - is there really a need to introduce a specific name for this? I don't recall seeing it mentioned in discussions. I see more terms like "list of tiddlers" or similar)
- [GroupedLists](http://tiddlywiki.com/prerelease/#GroupedLists) ...is that a good name? If intended for a less-technical reader, I propose "Lists in Lists" or if for a more technical reader "Nested Lists".

**Comment by Jermolene** [comment]
Thanks @twMat 

> Title List - is there really a need to introduce a specific name for this? I don't recall seeing it mentioned in discussions. I see more terms like "list of tiddlers" or similar)

We've slowly been adopting more consistent terminology. Some of it seems a bit pernickety, but we need to be pretty careful to avoid ambiguity. Here we use "title list" because that's what it is: a list of titles, and not a list of tiddlers.

* GroupedLists ...is that a good name? If intended for a less-technical reader, I propose "Lists in Lists" or if for a more technical reader "Nested Lists".

The GroupedList term is a fairly standard usage and refers nicely to the results rather than the mechanism.

**Comment by twMat** [comment]
Ok, fair enough regarding *title list* and *GroupList*.

Assuming it is well written, would there bring value if someone auhored such an "introductory overview on the concept of lists", or would it be superfluous in your opinion?

**Comment by Jermolene** [comment]
Independently of the question of nomenclature, I think there's a strong case for conceptual disambiguation tiddlers like this, by the way.

**Comment by twMat** [comment]
>I think there's a strong case for conceptual disambiguation tiddlers like this, by the way.

Good to hear! My intention then is to write a draft for this, for someone more knowledgable to review.

**Comment by twMat** [comment]
@Jermolene 

>>GroupedLists ...is that a good name? If intended for a less-technical reader, I propose "Lists in Lists" or if for a more technical reader "Nested Lists".

>The GroupedList term is a fairly standard usage and refers nicely to the results rather than the mechanism.

Ironically, apropos my proposal for the term "Nested Lists", I just stumbled over tiddler [ListWidget](http://tiddlywiki.com/prerelease/#ListWidget) which reads:

`Grouped Lists
See NestedLists for how to generate nested and grouped lists using the ListWidget.`

...where NestedLists is non-existing.

**Comment by Jermolene** [comment]
Ha! Exactly the sort of inconsistency we need to resolve :)

**Comment by pmario** [comment]
@Jermolene .. label "improvement"?

**Comment by tobibeer** [comment]
@twMat: dare to draft a draft?

**Comment by twMat** [comment]
@tobibeer - ok, I'll make an attempt... if you promise to review it before it's sent to el maestro! ;-) 
Thanks for bringing this up again.

**Comment by twMat** [comment]
@Jermolene - with the help of @tobibeer and people on the [board](https://groups.google.com/forum/#!topic/tiddlywiki/oP3r1yx4C14), I've put together this:

http://introductiontolists.tiddlyspot.com/

Note that the list examples don't render anthing and the links are dead because it is intended to be on tiddlywiki.com with sample data.

I don't know how to make a PR for a new file, so hoping this suffices - yes?

Please inform me if it is not up to par and what is needed.

If accepted, feel free to close this thread.

**Comment by twMat** [comment]
This was [adopted](https://tiddlywiki.com/#Introduction%20to%20Lists). Closing.
