### ISSUE TITLE
de-DE encrypt dialog has some english text artefacts

### ISSUE THREAD

**Issue by pmario** [Jermolene/TiddlyWiki5#1585]
encrypt dialog has some english text artefacts. I can't find, where the dialog is created. 

![encrypt-dialog-english-artefacts](https://cloud.githubusercontent.com/assets/374655/6688817/9b1d8256-ccb6-11e4-8134-e182e7d04293.gif)

**Comment by andreasabeck** [comment]
It's created in boot.js (https://github.com/Jermolene/TiddlyWiki5/blob/master/boot/boot.js) line 497 & 501. I guess that's the same in all languages then due to missing localisation...

**Comment by pmario** [comment]
@andreasabeck .. hi andreas,
would be great, if you could do a pull request. 

And sign the CLA with a separate PR first. 
https://github.com/Jermolene/TiddlyWiki5/blob/master/licenses/cla-individual.md

**Comment by andreasabeck** [comment]
It's in my fork:
https://github.com/andreasabeck/TiddlyWiki5/commit/b051f930c7cea0b40320bd66731239ab4ed5a60b

Will do a PR when CLA is merged. Github should allow several forks of the same project ;-)

**Comment by pmario** [comment]
PR has been merged. so can be closed :) thx
