### ISSUE TITLE
Error retrieving skinny tiddler list: XMLHttpRequest error code: 504

### ISSUE THREAD

**Issue by hch-im** [Jermolene/TiddlyWiki5#1589]
I always get this error message. 

> Error retrieving skinny tiddler list: XMLHttpRequest error code: 504

I do not know if it was reported before.

**Comment by Jermolene** [comment]
Hi @hch-im HTTP 504 means "Gateway Timeout", which means a problem with an intermediate proxy, rather than a problem with TiddlyWiki itself.

Can you see the command line to see any messages that TiddlyWiki is displaying?

**Comment by pmario** [comment]
@hch-im ... any news on this one, or can we close it?

**Comment by tobibeer** [comment]
@Jermolene, this doesn't appear to be in (urgent) need of resolving?

**Comment by pmario** [comment]
@Jermolene .. we didn't get further info. So pls close!

**Comment by Jermolene** [comment]
Thanks @pmario
