### ISSUE TITLE
[tw.com] Change the banner from "version" to "spread tw"

### ISSUE THREAD

**Issue by twMat** [Jermolene/TiddlyWiki5#1590]
@Jermolene 

I found the nice [HelpingTiddlyWiki](http://tiddlywiki.com/prerelease/#HelpingTiddlyWiki) tiddler, informing/encouraging people to spread the word. Excellent! But it is too hidden considering attracting new users and coders is probably one of the most valuable things the majority of the individuals in the community can do. (Not everyone is a programmer like you guys..)

I propose we use the banner on tw.com as a link to the HelpingTiddlyWiki tiddler (not on tw.com/prerelease tho). The banner could read something like "Help spread TiddlyWiki" and even if the whole banner actually is the link, the word "spread" could appear as the actual link (blue etc) so people actually //understand// they should click it.

Currently, the banner shows the version number. In the pre-release (5.1.8) the subtitle shows the version number instead of the "a non-linear personal..." I don't know if this is a practice only for pre-releases or if it is part of the update - but //if// the "a non-linear..." is supposed to //stay// then perhaps something like this would work

![twversion](https://cloud.githubusercontent.com/assets/4534056/6719342/2a01ba6a-cdba-11e4-98e3-d759799a108a.png)

IMO both subtle and clear.

**Comment by Jermolene** [comment]
Interesting. I'd agree with the basic premise: that the version number isn't particularly useful information to put in the ribbon. It's a bright, eye-catching bit of real estate and we should use it for something worthwhile.

I'm not sure if "HelpingTiddlyWiki" is the best use of the ribbon. One could argue that that link is only valuable to people who have already fallen in love with TiddlyWiki enough to want to help it, and therefore its a waste of the immediacy of the ribbon.

Another alternative would be to use the ribbon as the "GettingStarted" link (perhaps especially useful now that the getting started tiddler is below the fold).

>  I don't know if this is a practice only for pre-releases or if it is part of the update

Yes, using the subtitle for the version is specific to the prerelease.

**Comment by twMat** [comment]
Glad you agree on the basic premise!

>One could argue that that link is only valuable to people who have already fallen in love with TiddlyWiki enough to want to help it, and therefore its a waste of the immediacy of the ribbon.

You da boss... but... I strongly disagree. The following is a bit patronizing so feel free to skip it but I say it because I think TW *deserves to be known by the millions*. I care a lot about the spreading of it.

My proposal is not primarily about the "please help with development" aspect, but more about the "help spread the word" aspect. The banner has the potential to be a powerful reminder, a *cognitive reinforcer*, to keep this message active in their heads. Look at ads for, say, Coca Cola. The ads don't bring any *new* information. There is never even a sale. And yet these ads are absolutely necessary for their continued success. It *affects* people - and what is particularly interesting is that the ads, for sure, *more* affects those who already like it than those who dislike it because; One might think that what superficially states "Enjoy Coca Cola" has an actual meaning of "Buy Coca Cola" - but it is not the ad content as much as the ad itself that makes the difference. The real magic of the ad is: "**keep on thinking about** Coca Cola" !

Gazillions is spent on this strategy because it works. I think the banner has potential to be a bit like this, a reinforcing and recurring *reminder about spreading TW* - for exactly those who already love TW.

Sorry for being patronizing... but, I firmly believe that *attracting* people is the most valuable thing to do for the development of TW as 'people' is a premise for most other things. Money can buy attention but, with our limited means, doing what we can to encourage our members to do the spreading is probably the most efficient way to go.

Ok, that's enough of my bluntness. Only for this particualar issue, of course ;-)

**Comment by Jermolene** [comment]
Very eloquent @twMat!

Let's try it. I've uploaded a new prerelease for you to look at: http://tiddlywiki.com/prerelease

**Comment by Jermolene** [comment]
![screenshot 2015-03-22 09 56 24](https://cloud.githubusercontent.com/assets/174761/6768854/b8fc1938-d079-11e4-9cfb-658bbf250a4c.png)

**Comment by pmario** [comment]
@twMat well said :)
The prerelease looks good to me. .. but

this link doesn't work for me. ff on win

```
 [[Tweet about TiddlyWiki|https://twitter.com/intent/tweet?text=I+love+TiddlyWiki+because...&source=tiddlywiki5]]
```

**Comment by Jermolene** [comment]
Hi @pmario what happens when you click the link? It works in Firefox 36 OS X. Are you logged into Twitter in the same browser?

**Comment by pmario** [comment]
uuuuuups, .. The first time, that addblockplus caused a problem. It seems it removed the link.

**Comment by Jermolene** [comment]
Ah, pesky adblockers...

**Comment by pmario** [comment]
In the contrary. I haven't seen annoying, blinking and what not adds for years. ... If I help a friend with computers, this is the first plugin, that I recommend. ... and then I remove the unwanted additional toolbars :/

The filter that blocks the link is:  `##a[href^="https://twitter.com/intent/tweet?"]`

so it blocks adding automatic text suggestions.

**Comment by twMat** [comment]
I'm *really* happy that you guys agree! I think it is the right, and a very important, decision! Thank you!

**Comment by Jermolene** [comment]
I use them too, but the trouble I have with ad blockers is that it gives you yet another layer to debug when stuff doesn't work. Most sites are fine, but every so often you run into things like this that remind you how brutal they are: to disable all links to Twitter's tweet intent is a pretty a blunt instrument.
