### ISSUE TITLE
Sidebar tab Open reads "close all" even when nothing is open

### ISSUE THREAD

**Issue by twMat** [Jermolene/TiddlyWiki5#1593]
{{!!title}}  ;-)

**Comment by pmario** [comment]
imo nit picking. .. dealing with it makes the templates more complicated and slower as they already are.

**Comment by Jermolene** [comment]
We could disable "close all" when there are no tiddlers displayed but I'm not sure that it's worth it; the visual appearance wouldn't be much different.

**Comment by twMat** [comment]
If it's not worth the effort or the increased code, then I agree. If it is not worth it from an aesthetical point, I disagree because the other tabs are blank if empty. But I do agree it is nit picking. 
Please close thread if dismissed.

**Comment by Jermolene** [comment]
Cheers @twMat
