### ISSUE TITLE
present _canonical_uri field should trigger default type to text/html

### ISSUE THREAD

**Issue by twMat** [Jermolene/TiddlyWiki5#1594]
yeah.

**Comment by pmario** [comment]
imo wrong.

* In normal cases the server that sends the content needs to set the right mime type, so browsers can deal with it out of the box. 
* If the thiddler with the _cannonical_uri has a type field, it should be used by TW

Assuming, that a _cannonical_uri contains html content is just a guess.

**Comment by twMat** [comment]
Ok, I may be wrong about html specificially, but my question is; which of the available types *is* the *most* likely type for a _canonical_uri? Is it the current default (text/plain)? ...Or does my question not make little sense (like it would be asking "what is the most likely image format"). 

Would it make sense to have some mechanism to analyze the suffix of the _canonical_uri field *value*?  I.e if it ends with //.jpg// then set default to [etc]. .....but I admit I thought there was a clear and likely answer for this issue but if it is more intricate then the effort may not be worth implementing.

**Comment by Jermolene** [comment]
`_canonical_uri` is completely independent of the tiddler type. It is used with HTML tiddlers, image tiddlers, and in the future for arbitrary binary tiddlers.

As you note, one could imagine sniffing any file extension from the URI to infer the type. I think that the way to tackle these cases is to provide more configurability for the import/drop functionality. It would be nice to set up a cascade of rules: for example, "If URI ends with .jpg then set type to image/jpeg" etc.

**Comment by twMat** [comment]
> [...] for the import/drop functionality.

You mean so a url import is *automatically* inserted into a _canonical_uri field if it fulfill any of the cascading tests? That would be great! New issue?

**Comment by Jermolene** [comment]
> You mean so a url import is automatically inserted into a _canonical_uri field if it fulfill any of the cascading tests? That would be great! New issue?

Yes, that's the idea. Probably not worth creating an issue for it at this stage.

**Comment by pmario** [comment]
@Jermolene .. did we do anything for this one?

**Comment by tobibeer** [comment]
@twMat, I think the issue with its current title is invalid. So, either title and description are updated to [a more valid requirement](https://github.com/Jermolene/TiddlyWiki5/issues/1594#issuecomment-84376801), or it should possibly be closed.

**Comment by twMat** [comment]
Closing and replacing with #3034
