### ISSUE TITLE
help-panel needs to be a language specific plugin

### ISSUE THREAD

**Issue by pmario** [Jermolene/TiddlyWiki5#1596]
At the moment the Help Panel is English only. .. IMO it needs to be a language specific plugin.

**Comment by Jermolene** [comment]
Hi @pmario yes, I've not addressed the translatability of the help plugin yet - one of the difficulties is that we don't yet have a mechanism for plugins to hook into the translation mechanism and make their own strings be translatable.

**Comment by pmario** [comment]
I think the panel is gone for now. so can be closed atm.
