### ISSUE TITLE
Bug: TW Snowwhite theme dropdowns/popups partly hidden

### ISSUE THREAD

**Issue by felixhayashi** [Jermolene/TiddlyWiki5#1599]
Open a drop down from tiddler's toolbar. Scroll down.
Tested in 5.1.8-prerelease

# Screenshot 1

![selection_544](https://cloud.githubusercontent.com/assets/4307137/6760638/192f8c8e-cf4b-11e4-92ef-65f0e58deb67.png)

# Screenshot 2

![selection_543](https://cloud.githubusercontent.com/assets/4307137/6760622/ec2b4bc4-cf4a-11e4-8ae9-17b12afa21f6.png)

**Comment by Jermolene** [comment]
Hi @felixhayashi this problem appears to be related to the use of sticky titles. In my experiments, no amount of z-index on the dropdown sorts things out. Help appreciated.

**Comment by felixhayashi** [comment]
Hi @Jermolene 

I'll take a look at it. By the way, did you notice that the "more" dropdown icon disappears when being clicked?

-Felix

**Comment by Jermolene** [comment]
Hi @felixhayashi 

> By the way, did you notice that the "more" dropdown icon disappears when being clicked?

No, I'm not seeing that. What browser and theme are you using?

**Comment by felixhayashi** [comment]
I am using Linux Mint 17 and it happens when I visit tiddlywiki.com and tiddlywiki.com/prerelease without switching the theme or doing anything but clicking the more button. The page's more button works fine (after I actived it).

It doesn't happen in Chrome though.

I created a fresh firefox profile (no addons etc) to verify the problem and the problem persists.

Some screenshots:

![selection_547](https://cloud.githubusercontent.com/assets/4307137/6765779/a41f7252-cfee-11e4-8fb9-da730e151f4f.png)

![selection_549](https://cloud.githubusercontent.com/assets/4307137/6765781/b94e4a7c-cfee-11e4-9405-c30710169d07.png)

This works:

![selection_548](https://cloud.githubusercontent.com/assets/4307137/6765782/bc8a96c8-cfee-11e4-96cb-27bfe783f13e.png)

**Comment by Jermolene** [comment]
Thanks @felixhayashi, I was able to duplicate on Firefox OS X.

But ugh, pesky Firefox! I get fed up with the number of times that Firefox is the odd browser out that doesn't work the same as the others. Specifically here, Firefox doesn't like the drop-shadow that we use to indicate a selected toolbar button:

```
filter: drop-shadow(0px -1px 2px rgba(0, 0, 0, 0.25));
```

If one removes that filter then the buttons reappear.

So, I guess, the only solution would be adopt some different highlighting for selected toolbar buttons.

**Comment by felixhayashi** [comment]
Hi @Jermolene 

yes, frontend development is often annoying :(

I think the problem here is the svg

If you assign the filter attribute to the button in a selected state it works fine something like

    .tc-tiddler-controls button.tc-selected {
      filter: drop-shadow(0px -1px 2px rgba(0, 0, 0, 0.25));
    }

**Comment by Jermolene** [comment]
Thanks @felixhayashi that does seem to work, committing a fix now.

**Comment by felixhayashi** [comment]
> Thanks @felixhayashi that does seem to work, committing a fix now.

:+1: 

As for the z-index:

The problem is, all tiddler classes in the river share the same z-index so the tiddler further below will be automatically set above any content of the preceding frame.

> Boxes with the same stack level in a stacking context are stacked back-to-front according to document tree order. 
> http://www.w3.org/TR/CSS21/visuren.html#layers

Giving the dropdown an "position absolute and a high z-index" does not solve it since it remains in the stacking context of the parent node.

So what we need would be to assign lower tiddler classes in the river a higher z-index (+1). Maybe there is a way we can do this with css.

**Comment by Jermolene** [comment]
Thanks @felixhayashi it would be hard to have the z-index change according to the position of the tiddler in the story.

I notice that this problem is really caused by the sticky titles setting, and I do wonder whether it was a wise move to make that be a default, particularly when Firefox's implementation is soooooo buggy.

**Comment by felixhayashi** [comment]
Hi @Jermolene 

> when Firefox's implementation is soooooo buggy.

hehe. Still I am glad FF exists ;)

> I notice that this problem is really caused by the sticky titles setting

I didn't find a simple way to solve this. Since the sticky titles all share the same stacking context (same z-index and same parent context) the latter title and its children will be displayed above the former title. 
A guy in the web once had a similar problem (http://archivist.incutio.com/viewlist/css-discuss/60671)

#### Bad Solution 1:

Setting the z-index explicitly for each element with z-index: i++ will solve the problem as figured before:

    <div style="z-index: 1;" class="tc-titlebar">
    ...
    <div style="z-index: 2;" class="tc-titlebar">

#### Bad Solution 2:

Using the `nth-child` property to define the defaults for the first 100 tiddlers statically in the css

    .tc-tiddler-title:nth-child(0) {
        z-index: 2;
    }
    .tc-tiddler-title:nth-child(1) {
        z-index: 1;
    }
    ...

If the css were generated automatically via less or sass, this would be an option (see [stackoverflow](http://stackoverflow.com/questions/27320030/less-decrement-z-index-from-high-to-low-value))

#### What didn't work

    body {
        counter-reset: zstep 100;
    }
    
    .title {
       counter-increment: zstep -1;
       z-index: counter(zstep);
    }

> and I do wonder whether it was a wise move to make that be a default,

Sadly the dropdown boxes are a real deal breaker :(

**Comment by Jermolene** [comment]
Bad solution no. 2 may not be such a terrible idea.

> If the css were generated automatically via less or sass, this would be an option (see stackoverflow)

We generate the CSS from wikitext, so it's possible to write a macro that uses the list widget to generate the rules. Because there's no way at the moment to iterate through a numerical range, one would have to do something like this:

```
<$list filter="0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 ... 97 98 99">
`.tc-tiddler-title:nth-child(` <<currentTiddler>> `) {
    z-index: -`<<currentTiddler>>`;
}`
</$list>
```

**Comment by felixhayashi** [comment]
> We generate the CSS from wikitext, so it's possible to write a macro that uses the list widget to generate the rules. 

Oh, I forgot. Then this may be feasible. But we cannot use negative z-index values because we would go below the default stacking context and consequently hide all title divs.

The problem is, how do we generate the complementary numbers (nth child increases, z-index decreases). Unfortunately `z-index: 100-<<currentTiddler>>` does not work in css. (In the future, a [for-]loop widget would be really useful).

**Comment by felixhayashi** [comment]
Oh, wait! I think I have a great idea

**Comment by felixhayashi** [comment]
Works like a charm :)

Here is the idea:

First the assumption: A tiddler's dropdow (created at any place in the tiddler but in our case in the title) will never be large enough to reach the tiddler that comes after the next tiddler

The we can create the following rule:

    .tc-tiddler-frame:nth-child(2n) {
        position: relative;
        z-index: 501;
    }

`position: relative` is needed to create a stacking context. `z-index: 501` beats the stacking level of the dropdown.

What do you think @Jermolene?

**Comment by Jermolene** [comment]
Cunning stuff. I guess I worry that all of this complexity is liable to make it hard to debug problems with stacking order. I'm increasingly thinking of making "Sticky titles" be a theme tweak for Snow White, making it "off" by default, and annotating it with a note that it causes problems in edge cases in Firefox.

**Comment by felixhayashi** [comment]
> Cunning stuff. 

thanks (even if my last answer was mere nonsense :D)

> I guess I worry that all of this complexity is liable to make it hard to debug problems with stacking order. I'm increasingly thinking of making "Sticky titles" be a theme tweak for Snow White, making it "off" by default

Maybe that is the best think to do until we find a proper solution that is not a hack. 

> that it causes problems in edge cases in Firefox.

I think the dropdown was also partly hidden when using chrome

**Comment by pmario** [comment]
I suggest to post an issue at the firefox mailing list. Most likely they know a proper solution.

**Comment by Jermolene** [comment]
> I think the dropdown was also partly hidden when using chrome (which makes sense)

I don't see any problematic interaction between sticky titles and dropdowns in Chrome.

> I suggest to post an issue at the firefox mailing list. Most likely they know a proper solution.

You're right, I'm not a very good citizen at reporting bugs.
