### ISSUE TITLE
[tw.com] links to non-existing tw.com/projects

### ISSUE THREAD

**Issue by twMat** [Jermolene/TiddlyWiki5#1600]
This tiddler (5.1.7 & 5..1.8)
http://tiddlywiki.com/plugins/tiddlywiki/markdown/index.html#MarkdownExample

is referencing a lot of links to
http://tiddlywiki.com/projects/markdown/

but **/projects** does not seem to exist.

**Comment by Jermolene** [comment]
The example text is a copy of the Markdown manual: http://daringfireball.net/projects/markdown/basics

So the links are actually to pages on daringfireball, but are rendered as relative links.

The best thing is probably to choose a different chunk of sample Markdown text. What we need is a chunk of Markdown that incorporates as much Markdown syntax as possible.

**Comment by twMat** [comment]
I'll try to help if I can but I must understand what the problem is:
- is simply that someone must write it?
- or, even simpler, that one could just edit that copy? Or is that not fair use?
- or do you want a copy from somwhere else?

...and when you say "What we need is a chunk of Markdown that incorporates as much Markdown syntax as possible."

- is the current listing not extensive enough? I'm not versed enough in Markdown but I thought that listing kind of captured it and that other lists are really variants and extensions (but are they then applicable to TW?)

...Maybe it's even enough for tw.com with a simple link to that, or any other, good summary page?

**Comment by Jermolene** [comment]
Hi @twMat I think any of your first three solutions would be reasonable.

> ..Maybe it's even enough for tw.com with a simple link to that, or any other, good summary page?

The idea of including the Markdown demo tiddler is so that the user can verify that the plugin is working, as well as being able to see the syntax. It doesn't really need to be hugely extensive, but needs enough Markdown-specific syntax that the user can see at a glance that it's not ordinary TW5 wikitext.
