### ISSUE TITLE
5.1.8 prerelease serious error when creating new tiddler with tiddlyfox and dumpvariables

### ISSUE THREAD

**Issue by felixhayashi** [Jermolene/TiddlyWiki5#1601]
1. Download standalone prerelease
2. have tiddlyfox installed
3. paste `<<dumpvariables>>` into a "New Tiddler"

![selection_545](https://cloud.githubusercontent.com/assets/4307137/6761107/e1dc50b4-cf4f-11e4-8fa9-542e9223f981.png)

**Comment by pmario** [comment]
I did a test with win 8.1 FF 36.01 -> works for me, so can't confirm.
FF 36.03 -> also works here. may be you have some evil addOns?

AddOns used by me:
 * AddblockPlus
 * Chatzilla
 * TiddlyFox

**Comment by Jermolene** [comment]
Hi @felixhayashi I can't reproduce this either. The error message suggests that the error is triggered by the attempt to open the file for saving. Does the same file work OK for creating other tiddlers?

**Comment by felixhayashi** [comment]
Hi @pmario @Jermolene 

> also works here. may be you have some evil addOns?

I think that was the case, I disabled some of them and the error message is gone. Sorry & Closed.

**Comment by Jermolene** [comment]
Great glad to hear it.
