### ISSUE TITLE
New parse rule for `[[[Foo]]]` bracketed links

### ISSUE THREAD

**Issue by twMat** [Jermolene/TiddlyWiki5#1607]
```
^^[[[Foo]]]^^
~~[[[Foo]]]~~
''[[[Foo]]]''
etc
```

resuts in links to [Foo

Particularly `^^[[[Foo]]]^^` is nice to use when referencing. E.g Wikipedia uses this format.

**Comment by Jermolene** [comment]
What would you expect to be the effect of triple square brackets?

**Comment by twMat** [comment]
A [[link](http://en.wikipedia.org/wiki/TiddlyWiki)].

I like this format a lot actually. It's a bit like parantheses but for more formal stuff, for instance used next to Wikipedia headings where it states [[edit](http://en.wikipedia.org/wiki/TiddlyWiki)], or superscripted references[[5](http://en.wikipedia.org/wiki/TiddlyWiki)], linking to footnotes. (Can't show superscript in git tho.)

**Comment by Jermolene** [comment]
OK, so the proposal is to add a new parse rule that matches triple square brackets and renders with one set of square brackets around the link.

**Comment by twMat** [comment]
Excellent.

BTW, I had to edit my last message above a zillion times. Do all those edits end up in your (the conversation participants) mailbox?

**Comment by andreasabeck** [comment]
I guess there are several possibilities to change the greedyness of that pattern to allow either the additional square brackets to be included or not. Changing it will probably break other wikis which rely on the current behaviour.

At the moment the only way is probably to give an alternate link text:
```[[[Foo]|Foo]]`
```

**Comment by twMat** [comment]
@andreasabeck (hm, your username doesn't appear in the popup-dropdown - ?)

I'm guessing you missed Jeremys post.

Regardless, I don't understand what "break other wikis" would mean. What other wikis? If you're referring to backward compatability then... well, in those I guess they're suffering from the very problem I address, i.e a broken [link

**Comment by andreasabeck** [comment]
@twMat yes, I missed that one cause I was typing at the same time. Yes I was thinking about backward compatibility - anyway, introducing a new tripple square bracket parse rule that shouldn't harm too much.

Hm, the more complicated question is probably why I don't appear in the popup ;-)

**Comment by felixhayashi** [comment]
> BTW, I had to edit my last message above a zillion times. Do all those edits end up in your (the conversation participants) mailbox?

Yes, please stop the spamming

**Comment by twMat** [comment]
>Yes, please stop the spamming

Ouch. I'm really sorry. How embarrassing.

**Comment by felixhayashi** [comment]
@twMat 

> Ouch. I'm really sorry.

why? :) :)

**Comment by pmario** [comment]
-1 for a new parser rule.

Imo you can use `[ [[adsf]] ]` or `[[[Foo]|Foo]]` as Andreas suggested and you are done. 

So there are already 2 different ways in the core to solve the problem. Why do we need a third one?

**Comment by pmario** [comment]
IMO this will also produce a consistency problem. 

eg:

 * `{{}}` means transclusion
 * `{{{}}}` means filtered transclusion

and now

 * `[[]]` ... is a link
 * `[[[]]]` ... is a link with a edgecase parser rule. 

So either `{{{}}}` or `[[[]]]` cause a problem in consistency of using a "tripple something"

**Comment by Jermolene** [comment]
@pmario you are quite right; we have discussed the proposal that `[[[ myfilter ]]]` would create a link to multiple tiddlers identified by a filter, enabling a bunch of tiddlers to be dragged and dropped at once, as well as opening multiple tiddlers with a single click.

**Comment by twMat** [comment]
>enabling a bunch of tiddlers to be dragged and dropped at once, as well as opening multiple tiddlers with a single click.

Were that implemented, I agree it would be a more valuable use of triple brackets.

I don't agree that `[ [[adsf]] ] or [[[Foo]|Foo]]` are full alternatives to the otherwise intuitive `[[[Foo]]]`. 

Another less good possibility - that I mention mostly because it's fun to know - could be either of the following, assuming they don't conflict with something:

```
[&#8203;[[Foo]]]
[&zwnj;[[Foo]]]
[&#8204;[[Foo]]]
[&zwj;[[Foo]]]
[&#8205;[[Foo]]]
```

@felixhayashi - ok, good you just joked. Still I wonder, if I edit a message that contains `@someone`, would re-edits also then not be emailed?

**Comment by felixhayashi** [comment]
> Still I wonder, if I edit a message that contains @someone, would re-edits also then not be emailed?

Good point, I will check that

**Comment by Jermolene** [comment]
> Good point, I will check that

Re-editing a post that mentions someone does not send a new email. I've been tripped up by it several times.

**Comment by twMat** [comment]
One more test. I am not at'ing anyone now.

**Comment by pmario** [comment]
>Were that implemented, I agree it would be a more valuable use of triple brackets.
>I don't agree that [ [[adsf]] ] or [[[Foo]|Foo]] are full alternatives to the otherwise intuitive [[[Foo]]]. 

It's not intuitive at all. It creates an inconsistency, that can't be fixed anymore.

**Comment by twMat** [comment]
@pmario , ok I won't push the issue further.

**Comment by tobibeer** [comment]
@twMat I think that entity called **zero width joiner** or `&zwj;` is perfectly fine for this fringe-usecase. Wouldn't you agree?

**Comment by twMat** [comment]
>@twMat I think that entity called zero width joiner or &zwj; is perfectly fine to go about solving this fringe-usecase. Wouldn't you agree?

I don't agree with "perfectly fine" (because who keeps track of &zwj; ?) but I do agree it is a fringe case and I'm closing the issue.
