### ISSUE TITLE
Decouple styles in editting mode and rendered text

### ISSUE THREAD

**Issue by reflectionalist** [Jermolene/TiddlyWiki5#1608]
## Summary

It seems currently the style in editting mode is coupled with that for rendered text.  Or, both are ruled by one style.  As a result, it is impossible to modify the style in editting mode without affecting that of rendered text.
## Reproduction

For example, I prefer monospace font in editting mode.  But changing font family to monospace (in the theme, I am not sure if there is a better way to do it) also changes the font of rendered text to monospace.
## Expectation

I expect to adjust the style in editting mode and rendered text independently.  For inspiration, try [StackEdit](http://stackedit.io).
## Context

OS: Kubuntu 14.04 LTS (64bit)
Browsers: Firefox (36.0) and Chromium (40.0.2214.111)

**Comment by Jermolene** [comment]
Hi @reflectionalist do you want to be able to use a monospaced font within the text editor edit box, or do you want to use it within the editor preview pane?

Assuming the former, try creating a stylesheet tiddler called `$:/mystyles`, the tag `$:/tags/Stylesheet` and the following content:

```
textarea {
	font-family: Monaco, Consolas, "Lucida Console", "DejaVu Sans Mono", monospace;
}
```

**Comment by pmario** [comment]
I'd support the request for a second line in ControlPanel: Appearence: ThemeTweaks

Should I create a pull request?

**Comment by Jermolene** [comment]
@pmario OK, thanks

**Comment by reflectionalist** [comment]
**@Jermolene**

Thanks for the quick response.  I want to use monospace font in the edit box.  So your code snippet solves the problem.  But I'd  second **@pmario**'s proposal.
