### ISSUE TITLE
Proposal: SetWidget syntax change + enhancement

### ISSUE THREAD

**Issue by felixhayashi** [Jermolene/TiddlyWiki5#1610]
It is very(!!) annoying to set multiple variables as it spams the code.

    <$set name="key1" value="val1" />
    <$set name="key2" value={{!!fieldxy}} />
    <$set name="key3" value={{!!bla}} />
    ....
    </$set>
    </$set>
    </$set>

Would something like the following be possible (e.g.  like it already exists for the set field widget or the send message widget)

    <$set key1="val1" key2={{!!fieldxy}} key3={{!!bla}} />
    ....
    </$set>

I know that this new syntax would mean that keys "name" and "value" would be misinterpreted and break backwards compatibility. 

Therefore we could either treat "name" and "value" specially or introduce a new set widget to the core called e.g. "<$multi-set" or "<$xset" or something like this.

Thanks
-Felix

**Comment by Jermolene** [comment]
Hi @felixhayashi as you've noted, the backwards compatibility problem with the proposal is the ambiguity with the existing syntax.

A backwards compatible version of the proposal might be:

```
<$set $key1="val1" $key2={{!!fieldxy}} $key3={{!!bla}} />
....
</$set>
```

It's annoyingly inconsistent with other widget usage of the `$` prefix, but it is at least backwards compatible.

The other option of implementing the widget under a different name is attractive, except that I don't think we've got a good enough name yet - `<$multi-set>` is my favourite so far, but it's not easy to type. I did wonder about using `<$let>` but I think it's too confusingly similar.

**Comment by felixhayashi** [comment]
Hi @Jermolene 

thanks for responding on this.

> It's annoyingly inconsistent with other widget usage of the $ prefix, but it is at least backwards compatible.

I agree, people will confuse/forget when to use the $ and when not.

> <$multi-set> is my favourite so far, but it's not easy to type.

Good point, a key widget like $set should be easy to type. The idea of using let is truly appealing as (1) it shows the close relation to set, (2) fast to type (3) is used in other languages to define a constant which is also fine for our case and (4) the letter "l" is far away from "s" on euro-keyboards so it cannot be confused. 

> <$let> but I think it's too confusingly similar.

I think it is a plus that they sound similar. Set is clearly documented so I think the risk that somebody confuses let with the former set is minimal and does not compete with the advantages of the term mentioned above.

If you still do not like "let" what about

`<$mset`
`<$var`
`<$bind`
`<$prop`

-Felix

**Comment by Jermolene** [comment]
Hmm `<$var` is good, how about `<$vars` to make clearer that multiple variables are being set?

**Comment by felixhayashi** [comment]
> Hmm <$var is good, how about <$vars to make clearer that multiple variables are being set?

Hehe, a second before you commented, I had the same thought and edited my post - so yes, I agree on that ;)

**Comment by felixhayashi** [comment]
Should I do a pull request or do you want to handle this?

**Comment by Jermolene** [comment]
Please do go ahead with a pull request - I'll merge after 5.1.8 is out.

**Comment by felixhayashi** [comment]
ok

**Comment by felixhayashi** [comment]
Hi @Jermolene 

I now created the corresponding pull request.

-Felix

**Comment by felixhayashi** [comment]
@Jermolene 

I also added a widget description to the tiddlywiki.com docs

-Felix
