### ISSUE TITLE
nsort confused by non numeric values

### ISSUE THREAD

**Issue by Evolena** [Jermolene/TiddlyWiki5#1611]
I've an issue with the nsort filter. When one of the tiddlers has a non numeric value for the field sorted, all the sort is messed.

See for example these tiddlers below (json export). The field used for the sort is `id`, and the tiddler Demorthèn has `id_test` (instead of 3, which is why this one is missing in the order). When deleting Demorthèn or setting its id to a numeric value, the sort becomes correct.

```
[
        {
        "text": "Cet ordre de chevalerie, très lié à la couronne talkéride, est voué à la lutte contre les feondas et peut à l'occasion assurer la régence d'un domaine.",
        "created": "20150305232345646",
        "id": "12",
        "modified": "20150323143456803",
        "tags": "factions",
        "title": "Chevaliers Hilderins"
    },
    {
        "text": "Les Ronces sont un ordre très ancien dont les activités sont partagées entre la lutte contre les feondas et la gestion d'organismes bancaires.",
        "created": "20150305232318695",
        "id": "11",
        "modified": "20150323143425355",
        "tags": "factions",
        "title": "Chevaliers Ronces"
    },
    {
        "text": "Les populations honorant les cultes et traditions ancestrales de Tri-Kazel.",
        "created": "20150302132429049",
        "id": "id_test",
        "modified": "20150303212752111",
        "tags": "factions",
        "title": "Demorthèn"
    },
    {
        "text": "Les partisans d'une société régie par des principes académiques & scientifiques. ",
        "created": "20150302132443705",
        "id": "2",
        "modified": "20150303212735104",
        "tags": "factions",
        "title": "Magience"
    },
    {
        "text": "Les marchands sont essentiellement pragmatiques : partisans de la circulation des biens et des personnes, et de législations qui leur permettent de s'enrichir. Ils peuvent s'accommoder d'un peu de corruption, mais veulent des routes sûres. ",
        "created": "20150302132558952",
        "id": "8",
        "modified": "20150303212726562",
        "tags": "factions",
        "title": "Marchand"
    },
    {
        "text": "Plusieurs courants se partagent ou se disputent les lieux sans qu'il soit véritablement possible de discerner la domination de l'un d'eux. ",
        "created": "20150302132624550",
        "id": "9",
        "modified": "20150303212719309",
        "tags": "factions",
        "title": "Mixte"
    },
    {
        "text": "Aucun des grands courants idéologiques ne dominent ce lieu. ",
        "created": "20150302132639551",
        "id": "4",
        "modified": "20150303212712147",
        "tags": "factions",
        "title": "Neutre"
    },
    {
        "text": "La noblesse défend des valeurs de tradition, hiérarchie, autorité. Certains nobles sont très dévoués à leur souverain, d'autres estiment qu'ils sont seuls maîtres sur leurs terres. ",
        "created": "20150302132704070",
        "id": "7",
        "modified": "20150303212704735",
        "tags": "factions",
        "title": "Noblesse"
    },
    {
        "text": "Rattachés au culte demorthèn, les Osags en sont peut-être l'expression la plus radicale. ",
        "created": "20150302132721238",
        "id": "5",
        "modified": "20150303212657489",
        "tags": "factions",
        "title": "Osags"
    },
    {
        "text": "Les individus qui dominent sont en rupture avec la société, pour des raisons d'intérêt ou d'opinion. Le territoire est une zone grise, où la violence est endémique. ",
        "created": "20150302132750586",
        "id": "10",
        "modified": "20150303212649830",
        "tags": "factions",
        "title": "Rebelles & Criminels"
    },
    {
        "text": "Peuple nomade par excellence, ses communautés sont en mouvement constant.",
        "created": "20150302132736677",
        "id": "6",
        "modified": "20150303212642094",
        "tags": "factions",
        "title": "Tarish"
    },
    {
        "text": "Les adeptes de la religion de l'Unique. ",
        "created": "20150302132414056",
        "id": "1",
        "modified": "20150323141610429",
        "tags": "factions",
        "title": "Temple"
    },
    {
        "text": "Ces guides et messagers arpentent les chemins de la péninsule, assurant le lien entre les communautés les plus isolées. Ils connaissent souvent des raccourcis.",
        "created": "20150305232334829",
        "id": "13",
        "modified": "20150323143520545",
        "tags": "factions",
        "title": "Varigaux"
    },
    {
        "created": "20150323224412975",
        "text": "<$list filter=\"[tag[factions]nsort[id]]\">\n<div class=\"tc-menu-list-subitem\">\n<$link to={{!!title}}>{{!!title}}</$link> ({{!!id}})\n</div>\n</$list>",
        "title": "Test nsort",
        "modified": "20150323224510300"
    }
]
```

**Comment by Jermolene** [comment]
Hi @Evolena

I'm having trouble duplicating this problem. I pasted the above JSON into a `.json` file and imported it into a new TiddlyWiki. When I opened the tiddler "Test nsort", I see the following order, which seems to be correct:

![screenshot 2015-03-31 13 51 08](https://cloud.githubusercontent.com/assets/174761/6919215/206cef7c-d7ad-11e4-8e07-36d8e9b5cd69.png)

**Comment by Evolena** [comment]
Indeed... strange, it was messed before I send it (with Firefox, which may have been updated to 36.0.4 since then). What's happening if you change the numeric value to something else in an aother tiddler?

**Comment by Jermolene** [comment]
Hi @Evolena 

> What's happening if you change the numeric value to something else in an aother tiddler?

The non-numeric values get moved to the end of the list.

**Comment by Evolena** [comment]
Here is my result:

![capture](https://cloud.githubusercontent.com/assets/7150102/6929389/9e462e98-d7fa-11e4-9704-0c16ce79d49b.JPG)

**Comment by Jermolene** [comment]
Hi @Evolena this is getting quite strange. I just re-ran the test in Firefox 36.0.4 on OS X and saw the expected behaviour.

Just to be clear, the steps I'm performing are:

1. Copy the above JSON into a file with a `.json` extension
2. Drag the file into http://tiddlywiki.com/prerelease
3. Import the tiddlers
4. Open "Test nsort"
5. Edit one of the other tiddlers to change the ID from a numeric id to an alpha ID, and to an alphanumeric ID

**Comment by Evolena** [comment]
More and more strange.

As I used the "import" button in the page tools, I tried the drag and drop (always in tw5.com to be sure there is no side effect from my own TW).

And here is the result (with no further change):

![capture2](https://cloud.githubusercontent.com/assets/7150102/6946335/d3f220ec-d89f-11e4-846b-f0102fd2ec74.JPG)

(Firefox 37.0 now)

**Comment by Jermolene** [comment]
Hi @Evolena just a thought, but one way to tackle this might be to try to add a test that shows the problem to https://github.com/Jermolene/TiddlyWiki5/blob/master/editions/test/tiddlers/tests/test-filters.js (or even a whole new test script). I suspect that maybe it's got something to do with the browser-dependent ordering of a hashmap showing through.

**Comment by danielo515** [comment]
Are you using the same browser? Different javascript engines orders the objects properties in different ways. Some of them respects a numeric order and others seems to be random. I experienced many headaches before I realized this.

**Comment by Evolena** [comment]
I used the same browser on the same PC, except for the updates.

For the tests, if I have some brain free time, I will look at it, but I don't know Javascript (I can only copy and modify a few bit).

**Comment by Jermolene** [comment]
Hi @Evolena no worries. Then I guess the priority would be to get to the point where I can duplicate your results. Could you perhaps prepare a test wiki on tiddlyspot that demonstrates the problem? Much appreciated!

**Comment by pmario** [comment]
@Evolena .. is this still a problem with 5.1.14. .. I just tested it with your data. What ever I change, it seems to work. FF 53.0.2 , ubuntu 17.04

**Comment by pmario** [comment]
@Evolena ... I did test again today with 5.1.17.   filter: `[tag[factions]nsort[id]]`  it works as expected. 
Do you still  have a problem? ... If not please close the issue!

**Comment by Evolena** [comment]
When importing these tiddlers in a 5.1.7 empty tiddlywiki, the problem is present.
With a 5.1.8 , 5.1.9 or 5.1.17 empty tiddlywiki, I can't reproduce it.
So it was not a browser issue, and something in 5.1.8 seems to have solved it.
