### ISSUE TITLE
[Feature Request]: Tiddler templates, pre-filled values from a new tiddler bookmark.

### ISSUE THREAD

**Issue by Innomen** [Jermolene/TiddlyWiki5#1613]
I would also like the ability to have a bookmark a tiddler template, like imagine a save link tiddler where clicking it would create a new tiddler with a tag preselected, the date inserted, and the link text. A bit like how sharing buttons work in social media plugins/bookmarklets.

I want to be able to "share and comment" direclty into my tiddlywiki.

Sorry if that's confusing hehe.

**Comment by Jermolene** [comment]
Hi @Innomen the technical issues here are the same as #1612. Can we close this ticket and focus the discussion over there?

**Comment by Innomen** [comment]
Thank you for even asking, that's mega thoughtful of you. By all means :)
