### ISSUE TITLE
Theme tweak - remove setting for "Story width"

### ISSUE THREAD

**Issue by twMat** [Jermolene/TiddlyWiki5#1621]
As described [here](https://groups.google.com/forum/?fromgroups=#!topic/tiddlywiki/Q_vNTcXdzdA), the possibility to set *Story width* (Ctrlpanel > Appearence > Theme tweaks) is confusing. Further, the position of the *sidebar* and (to my surprise) *Tiddler width* are independent of the *Story width*.

This makes me question if there is a point in including *Story width* in the *Theme tweaks* at all.

**Comment by Jermolene** [comment]
The story width **is** used in the default vanilla theme. It sets the width of the story river container. Although individual tiddlers are independently sized, and don't take their size from the container, content at the top or bottom of the story column does take this width.

To see this happen, create a new tiddler at http://tiddlywiki.com with the tag `$:/tags/AboveStory` and the content:

```
This is above the story

----
```

Then you'll see how the width of the horizontal rule is determined by the story width setting.

I do agree that this is all highly confusing, but I think the options for resolving it are limited: either a complete overhaul of how the parts fit together (with the attendant pain in the upgrade process), or we improve the documentation provided on the theme tweaks tab.

**Comment by twMat** [comment]
Thanks for clarification! That was a clever use of horiz rule! And good to learn about `$:/tags/AboveStory`!

>either a complete overhaul of how the parts fit together

Is that what would be required if we want to make room for e.g a left sidebar, a top menu and a footer?

**Comment by Jermolene** [comment]
Hi @twMat the big plan in that area is to adopt a flexbox-based layout that will give us much more flexible, responsive toolbars that can be pinned to any side of the browser window.

**Comment by twMat** [comment]
Closing this issue due to in-actionability and un-snapinessity. Even twaddle now.

>the big plan in that area is to adopt a flexbox-based layout

I welcome this very much. Some time ago, @pmario provided a link to some astonishting [CSS examples](http://www.csszengarden.com/) and it would be fantastic if we had a structure that allowed for this kind of pure CSS "layouting" - it would probably simplify creating both themes, editions and TW based websites.

**Comment by Jermolene** [comment]
> the big plan in that area is to adopt a flexbox-based layout

@twMat one of the drivers is to solve a long standing problem with TW5 on systems that show physical scrollbars: there are two scrollbars bunched together at the right, with a counter-intuitive relationship with the two panels. I don't know whether the double-scrollbar problem is ticketed, but it might be useful if it were.

**Comment by twMat** [comment]
> I don't know whether the double-scrollbar problem is ticketed

#1282 . Perhaps also [#144](https://github.com/Jermolene/TiddlyWiki5/issues/144)

**Comment by Jermolene** [comment]
Thanks @twMat
