### ISSUE TITLE
ToC 3'd level titles should not be bold

### ISSUE THREAD

**Issue by twMat** [Jermolene/TiddlyWiki5#1627]
![skarmklipp](https://cloud.githubusercontent.com/assets/4534056/6920047/5e76ad44-d7bc-11e4-82ca-893afc5e27a1.PNG)

For some reason the ToC macro adds **bold** on 3'd level. I propose it should not do this.

In general, either; the deeper the level the less prominant the appearence, OR, consistent prominence on all levels with the possible exception of top level.

**Comment by roma0104** [comment]
I agree that the bolding of sub-items is a bit... unexpected and a little counter-intuitive.  I personally like the latter suggestion for alternatives.  I think the indention is sufficient for 3+ levels; the bold top level items make it easy to skim over topics.

**Comment by tobibeer** [comment]
:+1:  the indentation should be enough => PR?

**Comment by pmario** [comment]
imo can be easily changed with a custom stylesheet definition: 

```
.tc-table-of-contents li li li a {
	font-weight: normal;
}
```

**Comment by twMat** [comment]
@pmario , I'd favor removing the current intentional setting of bold in $:/themes/tiddlywiki/vanilla/base
to make it default to normal, i.e remove this bit:

```
.tc-table-of-contents li li li a {
	font-weight: bold;
}
```

**Comment by tobibeer** [comment]
@twMat: the PR right here on GitHub should theoretically be a manner of 5 minutes.

**Comment by twMat** [comment]
> @twMat: the PR right here on GitHub should theoretically be a manner of 5 minutes.

@tobibeer - Done! I've actually never succeeded in making a PR for anything but *docs*. Maybe it worked now because it was only a stylesheet?... 

Anyway, I'm closing this now. Please comment if it would be better to leave it open.
