### ISSUE TITLE
Retain Story Ordering doesn't work on Node.js

### ISSUE THREAD

**Issue by Belphemur** [Jermolene/TiddlyWiki5#1631]
Hello,

It seems  ``[list[$:/StoryList]]`` doesn't work with a Node.js installation.
For now I configured TiddlyWiki to save the whole story in the url as a workaround.

**Comment by Jermolene** [comment]
Thanks @Belphemur this is fixed for 5.1.8 - see #1474

**Comment by Belphemur** [comment]
Ho didn't find it in the open one ^^'
Thanks for this

**Comment by Jermolene** [comment]
No worries @Belphemur GitHub search is usually pretty unhelpful!
