### ISSUE TITLE
vertical tabs cause overflow problem

### ISSUE THREAD

**Issue by pmario** [Jermolene/TiddlyWiki5#1632]
to recproduce: use FF

* create a tiddler eg: `test`  with the content `{{Motovun Jack.svg}}`
* create at tidder eg: `issue`  content: `<<tabs "test" "SampleProblem" "$:/state/tabx" "tc-vertical">>`
* select the tab: test

The image will be out of bounds, since the .svg has a default size hardcoded, that exceeds the available space. ... The same problem comes up if you visit: http://tiddlywiki.com/languages/de-DE/#ErsteSchritte  with the iframe. Since the iframe in the tab is also bigger than the available space.  

IMO the fix is to add overflow:auto since it causes the embedded elements to rescale to 100% instead of there initial size. 

```
.tc-tab-content.tc-vertical {
  ...
  ...
  overflow: auto; 
}
```

**Comment by pmario** [comment]
The rescale is caused by: 

```
.tc-tiddler-frame img, .tc-tiddler-frame svg, .tc-tiddler-frame canvas, .tc-tiddler-frame embed, .tc-tiddler-frame iframe {
    max-width: 100%;
}
```

**Comment by Jermolene** [comment]
Hmm the Firefox behaviour seems wrong: the `max-width: 100%` on `.tc-tiddler-frame img` should refer to the size of the container (ie the tab content container), not the containing tiddler.

**Comment by pmario** [comment]
I'm not so sure, if it's wrong. There is no overflow setting for the tiddler content and the FF default is `visible` see: https://developer.mozilla.org/en/docs/Web/CSS/overflow

There may be differences in how the standards are interpreted. ...

But anyway, speculation doesn't fix the problem, while an `overflow:auto` does. .. and imo it doesn't hurt, since it is the desired behaviour most of the times. 

There is a second problem with floats, but I'll create a new issue for this one.

**Comment by kookma** [comment]
Seems the issue of overflow is returned in TW 5.1.22

I discussed this in forum:
https://groups.google.com/d/msg/tiddlywiki/6iu874L0h5U/jNHkMi1JCQAJ
