### ISSUE TITLE
overflow: scroll (help panel) causes probelms on all systems except Mac

### ISSUE THREAD

**Issue by pmario** [Jermolene/TiddlyWiki5#1633]
The help panel in the prereview displays scroll bars, even if they are not needed. All browsers I did test on win8.1, FF, IE, Chromium

```
.tc-help-panel {
...
	overflow: scroll;
...
}
```

IMO the problem here is, that the Safari browser on a Mac doesn't show them.

**Comment by Jermolene** [comment]
Yes, it's not ready for primetime. As of a day or two ago, it's only included in the prerelease edition.

**Comment by pmario** [comment]
can be reopened if panel is activated again.

**Comment by Jermolene** [comment]
Hi @pmario the help panel is still present on the prerelease, and available for installation via the plugin library. Is the fix as easy as `overflow: auto`?

**Comment by pmario** [comment]
At: http://tiddlywiki.com/editions/full/index.html it looks like this for me with FF and win10.

![tw-help-panel-problem](https://cloud.githubusercontent.com/assets/374655/12992257/8e28dbc4-d113-11e5-82d5-d5fb5921d930.gif)

You can see the scroll bars, even if the content fits into the popup. ... So a overflow:auto does the trick here. .... but if the content is bigger, I personally would prefer a "help tiddler" instead of a popup.
