### ISSUE TITLE
Tiddler river stretches off viewport horizontally

### ISSUE THREAD

**Issue by twMat** [Jermolene/TiddlyWiki5#1640]
Tiddler river stretches off viewport (causing full horizontal scroll) if sidebar is hidden and *Story left position* is greater than default. Setting *Story width* or other value does not matter since (..and I think this is it) :

    <<if-no-sidebar "

	.tc-story-river {
		width: auto;
	}

    ">>

**Comment by tobibeer** [comment]
Auto is not a good idea anyway. Otherwise you get really wide tiddlers where the text becomes pretty unreadable.

**Comment by twMat** [comment]
This solves the problem:

In $:/themes/tiddlywiki/vanilla/base 

```
<<if-no-sidebar "

	.tc-story-river {
		width: calc(100% - {{$:/themes/tiddlywiki/vanilla/metrics/storyleft}});
	}

">>

```

Note that using 100vw instead of 100% does not work properly as it doesn't take width of eventual vertical scrollbars into account. ([ref](https://www.sitepoint.com/community/t/100vw-and-scrollbars/196480)).

I hoped to do a pull request but clicking "New pull request" informs about something that reminds me of the contents in the barn house outside with branches, forks and even some scary master streaking around. Hope posting here will do.

**Comment by Jermolene** [comment]
Thanks @twMat
