### ISSUE TITLE
Plugins library popup don't fit on screen

### ISSUE THREAD

**Issue by danielo515** [Jermolene/TiddlyWiki5#1642]
Tested on chrome 41.0.2272.118 on windows 7

When I open the plugins library popup it does not fit on the screen. Since it is not possible to scroll down, I have to do an invalid search to be able to close the popup. The scroll bar affects to the "background" TW file instead of the modal popup.

**Comment by Jermolene** [comment]
Thanks @danielo515.

**Comment by Jermolene** [comment]
By the way @danielo515 I've posted a new prerelease if you'd like to check it out.

**Comment by danielo515** [comment]
Hello @Jermolene 

It works now as expected. Many thanks.
