### ISSUE TITLE
Provide minified version

### ISSUE THREAD

**Issue by danielo515** [Jermolene/TiddlyWiki5#1643]
I love to use TW as framework for small fast applications. I have experience with it and it provides many functions and features by default that requires a lot of work to implement. But the size of the resultant files/applications is a bit bloated. 1.3MB for a small utility is too much to share it comfortably, or to upload it to any place. For those people that want to have the developed tool online (like me) this is a deal breaker, specially on mobile.

Providing a minified version of the core will help a lot with this task. But as important as this is to allow the in the built process to select those parts that are not needed, like images/icons and other ui stuff.

Regards.

**Comment by roma0104** [comment]
Assuming you are using plugins that might have some custom javascript wouldn't minifying core result in name mangling?

**Comment by danielo515** [comment]
Hello @roma0104 

With minified I just mean no comments (just headers), no line endings, no indentation. Not compression.

Regards

**Comment by felixhayashi** [comment]
Hi @danielo515 

this is probably related to https://github.com/Jermolene/TiddlyWiki5/issues/1535

**Comment by felixhayashi** [comment]
What you could certainly do is to run all core files through minifier yourself using a task runner like "gulp" and the uglifycss/js gulp module.

For example gulp code see e.g.  https://github.com/felixhayashi/TW5-TopStoryView/blob/master/src/gulpfile.js

**Comment by danielo515** [comment]
Hello @felixhayashi 

That is definitively on my list, but I'm not very familiar with gulp or uglify, and I'm not sure what parts can be minifed without damaging TW functionality. I'm scared of "change" vital variable names. Have you tried?

**Comment by Jermolene** [comment]
Hi @danielo515 I think this is a duplicate of #1535 isn't it?

**Comment by danielo515** [comment]
Hello @Jermolene 

Definitively the same topic. Sorry.

**Comment by felixhayashi** [comment]
Hi Danielo,

install gulp and create a gulpfile in your tw-repo root


    /********************************************************************
     * Imports
     *******************************************************************/

    var gulp = require("gulp");
    var gutil = require("gulp-util");
    var sass = require("gulp-sass");
    var addsrc = require("gulp-add-src"); // https://github.com/gulpjs/gulp/issues/396
    var uglify = require("gulp-uglify");
    var esprima = require('gulp-esprima');
    var debug = require('gulp-debug');
    var gulpif = require('gulp-if');
    var argv = require('yargs').argv;
    var del = require("del"); // rm -rf
    //~ var jsdoc = require("gulp-jsdoc"); // not maintained!

    /********************************************************************
     * Tasks
     *******************************************************************/

    // clean will not be run twice, even though it is called as a dependency twice.
    // @see https://github.com/gulpjs/gulp/blob/master/docs/recipes/running-tasks-in-series.md
    gulp.task("clean", function (cb) { 

      var options = { force: true };
      del(["dist/"], options, cb);
      
    });

    gulp.task("compile", ["clean"], function () {
            
      // uglify js
      gulp.src(["./core/modules/**/*.js"])
          .pipe(uglify({ compress: false, preserveComments: "all" }))
          .pipe(gulp.dest("./dist/"));
        
    });

    gulp.task("default", ["compile"]);

This is just a quick script to minify all scripts in the core and copy the output to a "dist" folder. You can then use the minified core to do whatever you want..

-Felix
