### ISSUE TITLE
How stable is refreshStart and refreshEnd for storyviews

### ISSUE THREAD

**Issue by felixhayashi** [Jermolene/TiddlyWiki5#1649]
Hi @Jermolene,

It seems that two new callbacks where introduced that are triggered by the list widget `refreshStart` and `refreshEnd`. Did this happen with the birth of the stackedStoryView and are they allowed to be used as API? Because I think I could use these for the development of the  "top story view".

-Felix

**Comment by Jermolene** [comment]
Hi @felixhayashi yes, support for those methods was added to support the stacked storyview, and they are intended to stay.

**Comment by felixhayashi** [comment]
thanks for telling me.
