### ISSUE TITLE
Problem with rearranging the story list (also affects stacked view)

### ISSUE THREAD

**Issue by felixhayashi** [Jermolene/TiddlyWiki5#1650]
@twMat created an issue (for the "top story view"; see https://github.com/felixhayashi/TW5-TopStoryView/issues/4) that also affects the stacked view since you also rearrange tiddlers here on a dom basis (when clicking internal links of tiddlers already existing in the river you bring them up front). 

The issue basically boils down to "dom changes are not reflected in the list widget that is associated with the story list which means everywhere the story list is displayed (e.g. "open tiddlers") it is not matching the dom representation.

> Problem is rearranging the story list

> * The previously inserted tiddler frame is removed and inserted again
> * will result in unnecessary animations in "open tiddlers" list (remove, insert)
> * also it will trigger another refresh that may cause a loop (which I prevent by checking if the switched element is now the first in the list...)

> https://github.com/felixhayashi/TW5-TopStoryView/issues/4#issuecomment-91517251

-Felix

**Comment by felixhayashi** [comment]
My current solution (excerpt):

    TopStoryView.prototype.placeAtTop = function(listItemWidget) {  
      
      var title = listItemWidget.parseTreeNode.itemTitle;
      var listElementIndex = this.listWidget.findListItem(0, title);
      
      if(listElementIndex !== 0) { // not at top yet
        
        var storyList = $tw.wiki.getTiddlerList("$:/StoryList");
        var index = storyList.indexOf(title);
        if(index !== -1) {
          storyList.splice(index, 1);
        }
        storyList.splice(0, 0, title);
        
        $tw.wiki.addTiddler(new $tw.Tiddler(
          {title: "$:/StoryList"},
          $tw.wiki.getTiddler("$:/StoryList"),
          {list: storyList}
        ));
        
        // update the index of the list widget to match the changed list field
        // so it does not trigger anymore changes for the river
        this.listWidget.removeListItem(listElementIndex);
        this.listWidget.insertListItem(0, title); // TODO: if behaviour = bottom the put at position = length

      }
 
    };

**Comment by felixhayashi** [comment]
IMO The problem arises because it is not the story view that decides where a tiddler should originally be displayed but the navigation widget.

I already brought that up here: https://github.com/Jermolene/TiddlyWiki5/issues/1290#issuecomment-69083210

**Comment by Jermolene** [comment]
Hi @felixhayashi 

> @twMat created an issue (for the "top story view"; see felixhayashi/TW5-TopStoryView#4) that also affects the stacked view since you also rearrange tiddlers here on a dom basis (when clicking internal links of tiddlers already existing in the river you bring them up front).

To make it possible to click a tiddler to bring it the front in the stacked story view I made a number of modifications to the view template and the link widget. I've subsequently retracted the changes to the view template, but the additional features are still present on the link widget.

The modifications were to replace the static `<div>` of the tiddler frame with an instance of the `<$link>` widget that points to the current tiddler. Thus clicking on a tiddler navigates to it, bring it to the front.

The changes worked well in the stacked story view but I retracted them because they interfered with the established behaviour of the classic story view.

> The issue basically boils down to "dom changes are not reflected in the list widget that is associated with the story list which means everywhere the story list is displayed (e.g. "open tiddlers") it is not matching the dom representation.

Your storyview is moving around the DOM nodes generated by the list widget? That approach is definitely problematic. The list widget refresh code expects the DOM nodes to stay where they are!

Anyhow, to your point that the navigator widget can't be controlled by the current storyview, I think we may well ultimately need to extend the storyview model somehow. But for the moment I think we can go a long way by making the navigator widget more configurable, and wiring the new configuration attributes up to config tiddlers that can be exposed in the control panel. If you're happy with that approach I'll create a new ticket with more detail about what needs to be done.

**Comment by felixhayashi** [comment]
Hi @Jermolene 

> Your storyview is moving around the DOM nodes generated by the list widget? That approach is definitely problematic.

I know and I stopped doing it. Instead, I rearrange the story list.

> The list widget refresh code expects the DOM nodes to stay where they are!

Well, fortunately, only partly. It needs a correct reference to the targetElement and I did not touch that. But moving the targetElement to other places in the dom does no harm. All operations (like e.g. calling `listItemWidget.removeChildDomNodes();` will still reference the proper target element).

But as said, also the stacked storyview faces the problem that bringing an item to the front does not come with a rearrangement of the actual story list (e.g. "open tiddlers" is not rearranged)...

> Anyhow, to your point that the navigator widget can't be controlled by the current storyview, I think we may well ultimately need to extend the storyview model somehow.

yes. But I have to say, the current architecture is nicely designed. Its only flaw is that it cannot control how items are inserted in the first place.

> But for the moment I think we can go a long way by making the navigator widget more configurable, and wiring the new configuration attributes up to config tiddlers that can be exposed in the control panel. If you're happy with that approach I'll create a new ticket with more detail about what needs to be done.

Of course I would be happy :) but no rush here. At the moment I simply hide the original frame-insert, that is done by the navigation widget, and initiate a new insert from the storyview widget that gets shown and animated.

-Felix

**Comment by Jermolene** [comment]
> Well, fortunately, only partly. It needs a correct reference to the targetElement and I did not touch that. But moving the targetElement to other places in the dom does no harm. All operations (like e.g. calling listItemWidget.removeChildDomNodes(); will still reference the proper target element).

I think that things will go wrong subsequently during a selective refresh cycle.

> But as said, also the stacked storyview faces the problem that bringing an item to the front does not come with a rearrangement of the actual story list (e.g. "open tiddlers" is not rearranged)...

No, it does rearrange the tiddlers by navigating to the one that was clicked on (with the click-to-navigate mod I mentioned above).

> initiate a new insert from the storyview widget that gets shown and animated.

You've got the storyview modifying the storylist? Under what circumstances? If you're doing it in the refresh cycle I think you'll end up running into problems.

**Comment by felixhayashi** [comment]
> I think that things will go wrong subsequently during a selective refresh cycle.

Of course you have by far the better insight. Thanks for warning me.

> You've got the storyview modifying the storylist? Under what circumstances? If you're doing it in the refresh cycle I think you'll end up running into problems.

Yes, I am highly aware of that and I am quite careful here. `handleListChanges` will only refresh if the story list does not match the internal state (`this.findListItem(t,this.list[t]);`). Therefore I update the internal state (via `insertListItem` etc.) and the story list tiddler to prevent any recursion or other problems.

-Felix

**Comment by felixhayashi** [comment]
> No, it does rearrange the tiddlers by navigating to the one that was clicked on (with the click-to-navigate mod I mentioned above).

Ah ok. Sorry, I overread this. But still the "open tiddlers" list in the sidebar does not reflect the changes.

**Comment by Jermolene** [comment]
The crux of it is that navigating to a tiddler doesn't change the story list ordering. In the case of the stacked storyview, we get around this by reordering the tiddlers though changing their z position.

But a useful option for the navigator widget would be to be able to automatically move navigated tiddlers to the top or bottom of the story list.

**Comment by felixhayashi** [comment]
> But a useful option for the navigator widget would be to be able to automatically move navigated tiddlers to the top or bottom of the story list.

PLEASE PLEASE PLEASE! It would so great if you enable these options (please have a look at https://github.com/Jermolene/TiddlyWiki5/issues/1651#issuecomment-91634492). In the NavigatorWidget, it is really easy to decide where to insert the tiddler in the list (simply by changing the index) but rearranging stuff from within the story view is really tricky/hacky.

I highly depend on this behaviour for my TiddlyMap plugin and it is such a burden to rearrange stuff after navigation took place. It would be awesome if this configuration was added before 5.1.8 is released.

If you want to, I could do a pull request.

1. It is straight forward. The NavigatorWidget would need to read the user config and apply it to the the `splice` operation of `addToStory()` which is called by `handleNavigateEvent`.

1. Then I would create a selectbox in the tw-config saying
  "How to open internal links that were clicked in the river?"
  * at top of the river
  * at bottom of the river
  * above the current tiddler (where the link was clicked)
  * below the current tiddler (where the link was clicked)

2. Another checkbox for "How to open links that were clicked from outside the river?"
  * at top of the river
  * at bottom of the river

-Felix

**Comment by felixhayashi** [comment]
Ok, I started working on it...

**Comment by felixhayashi** [comment]
Looks pretty good :)

I'll create a pull request this evening I think

**Comment by felixhayashi** [comment]
Hi @Jermolene 

it all works pretty well I have to say -- and the changes are minimal. I finished testing now and will start to polish the changes. Afterwards I'll upload everything as pull request so you can have a look :)

-Felix

**Comment by Jermolene** [comment]
Hi @felixhayashi great. We'll merge after 5.1.8 is out.

**Comment by felixhayashi** [comment]
>Hi @felixhayashi great. We'll merge after 5.1.8 is out.

Hi @Jermolene no chance that this makes it into 5.1.8? :( I understand that you do not want to introduce any risky stuff but this is really basic... I mainly changed `addToStory()` of the NavigatorWidget which looks like this at the moment:

    NavigatorWidget.prototype.addToStory = function(title,fromTitle) {
      var storyList = this.getStoryList();
      if(storyList) {
        // See if the tiddler is already there
        var slot = storyList.indexOf(title);
        // If not, we need to add it
        if(slot === -1) {
          // First we try to find the position of the story element we navigated from
          var fromIndex = storyList.indexOf(fromTitle);
          // Determine where to insert the tiddler
          if(this.openLink === "top") {
            slot = 0;
          } else if(this.openLink === "bottom") {
            slot = storyList.length;
          } else if(this.openLink === "above") {
            slot = fromIndex;
          } else {
            // Use "below" as default
            slot = fromIndex + 1;
          }
          // Add the tiddler
          storyList.splice(slot,0,title);
          // Save the story
          this.saveStoryList(storyList);
        }
      }
    };

Sorry, I do not want to pressure you in any way. I highly respect your agenda. In case you decide against it, I hope 5.1.9 does not take as long to be released as 5.1.8 did.

-Felix

**Comment by felixhayashi** [comment]
Hi @Jermolene 

please see a demo here http://wkpr.de/hosting/tmp/navigation-demo/

Change the settings in the Configuration

![selection_600](https://cloud.githubusercontent.com/assets/4307137/7107963/9acf8e2c-e177-11e4-953a-70bfff801997.png)

I think it is a great addition and I only modified the `addToStory()` method.

-Felix

**Comment by felixhayashi** [comment]
I'll close this in favour of #1662
