### ISSUE TITLE
Making the navigator widget more configurable

### ISSUE THREAD

**Issue by felixhayashi** [Jermolene/TiddlyWiki5#1651]
As discussed here: #1650 

> we may well ultimately need to extend the storyview model somehow. But for the moment I think we can go a long way by making the navigator widget more configurable, and wiring the new configuration attributes up to config tiddlers that can be exposed in the control panel. If you're happy with that approach I'll create a new ticket with more detail about what needs to be done.

**Comment by felixhayashi** [comment]
It would be nice, if a user could configure whether to

* open a link from the river (same for editing a tiddler)
  * at top of the river
  * at bottom of the river
  * above the current tiddler (where the link was clicked)
  * below the current tiddler (where the link was clicked)
* open a link from outside the river
  * at top of the river
  * at bottom of the river

**Comment by pmario** [comment]
@felixhayashi 
The PR is merged. Can this issue be closed?

**Comment by felixhayashi** [comment]
> The PR is merged. Can this issue be closed? 

:cry: goodbye #1651

**Comment by pmario** [comment]
hey. it's merged. IMO you did a good job \o/

**Comment by felixhayashi** [comment]
Thanks @pmario :smiley: I was just joking around a bit, I am really glad it was successfully merged!

**Comment by tobibeer** [comment]
:+1:  really nice!

**Comment by felixhayashi** [comment]
Thanks :)
