### ISSUE TITLE
The "export tiddler" alternatives should be phrased as singulars

### ISSUE THREAD

**Issue by twMat** [Jermolene/TiddlyWiki5#1653]
The various alternatives under *toolbar > export tiddler* should probably read in singular form as it only is the current tiddler being exported. Not a purely cosmetic issue actually as the plural form risks causing confusion on if it is the single tiddler or e.g the whole river being exported.

**Comment by Jermolene** [comment]
Hi @twMat the same translatable strings are used for all three places that the export button appears. Wherever possible, I try to avoid adding new strings - we're running at nearly 600 translatable strings. We could use different strings for each of the three locations, or have separate singular/plural versions. Or we can try to phrase the strings such that they work better.

Currently we have:

* "CSV tiddlers file"
* "JSON tiddlers file"
* "Static HTML tiddlers"
* "Single tiddler ".tid" file"

It might be better to simplify them to:

* "CSV file"
* "JSON file"
* "Static HTML"
* "".tid" file"

**Comment by twMat** [comment]
I think your suggested simplification is a good idea.

...but my "question premise/assumption" is that the command is only exporting a single tiddler, i.e the current one? And when you talk about "the three locations" - I don't understand what "three" refers to.

...but actually, no need to spend time on explaining these particular intricacies - I only want the toolbar popup to state the correct thing and I think your suggestion solves this. Thank you.

**Comment by Jermolene** [comment]
Hi @twMat 

The export icon appears in three different places:

1. The tiddler toolbar, for exporting individual tiddlers
2. The page control toolbar, for exporting all tiddlers
3. Filtered Advanced Search results, for exporting selected tiddlers

So, the problem is coming up with wording that works in all three contexts.

**Comment by twMat** [comment]
Aha, now I understand. Thanks.

BTW, I take it you implement your proposed solution so I guess we can close this issue then. Thank you.

**Comment by tobibeer** [comment]
can be closed
