### ISSUE TITLE
new journal tiddler button and already existing tiddler

### ISSUE THREAD

**Issue by tgirod** [Jermolene/TiddlyWiki5#1655]
Right now, pressing the "new journal tiddler" button will create a new tiddler with the current date as name, which might clash with an existing one.

Perhaps it would be better to check if there is already a tiddler named after the current date, and if so open it in edit mode.

**Comment by Jermolene** [comment]
> Perhaps it would be better to check if there is already a tiddler named after the current date, and if so open it in edit mode.

That is the behaviour that I see:

1. Visit tiddlywiki.com
2. Switch to the tools tab
3. Click "new journal"
4. Type some text in the resulting tiddler and click "done"
5. Click "new journal" again
6. The existing journal tiddler should be opened in edit mode

**Comment by tgirod** [comment]
ok, my mistake, I probably messed up with the tiddler title without noticing ... Sorry for the noise.
