### ISSUE TITLE
change event when Tiddlywiki switches into mobile version

### ISSUE THREAD

**Issue by felixhayashi** [Jermolene/TiddlyWiki5#1660]
It would be great to be informed by the core via a change event that tiddlywiki has switched from mobile to large screen and vice versa to be able to react to visual changes.

**Comment by Jermolene** [comment]
Hi @felixhayashi there is now a JavaScript API for this, but it's not well supported by browsers yet:

https://developer.mozilla.org/en-US/docs/Web/API/Window/matchMedia

There are hacks and workarounds but they are pretty dirty.

What's your usecase?

**Comment by felixhayashi** [comment]
Hi @Jermolene 

the page I am working on for my university needs to be responsive also in terms of the contents to be displayed. For example, we restructure the topics in the navigation bar (removing unnecessary rubrics; adding a search rubric that opens a tiddler for search results; making tiddler contents smaller) when switching in mobile mode. Of course I can use CSS to hide stuff, but if I were informed via a changedTiddler (e.g. `$:/temp/media` changes its text to "mobile"). I could use reveal widgets and all the other wikitext magic to react to layout changes.

-Felix

**Comment by Jermolene** [comment]
I'd strongly recommend using CSS for that. Even if we did have the JS events they're not going to perform as well as the CSS; CSS changes instantly, while we'd have to wait for the async JS event to be raised, and then wait for a refresh cycle before the screen is updated.

**Comment by felixhayashi** [comment]
> I'd strongly recommend using CSS for that. Even if we did have the JS events they're not going to perform as well as the CSS;

I use responsive design with css for many of my websites. CSS is good at hiding and changing layout but what I need here is to change the way TW behaves with respect to its content and calculations when in mobile mode...

> CSS changes instantly, while we'd have to wait for the async JS event to be raised, and then wait for a refresh cycle before the screen is updated.

At the moment I registered a resize event listener that changes a tiddler once tw switches into mobile

    var resizeHandler = function(event) {
      if(prevInnerWidth < 960 && window.innerWidth >= 960) {
        //... update a special tiddler to trigger refresh and inform about switching in/out mobile
      }
      prevInnerWidth = window.innerWidth;
    };

But if you think it is not a good idea to add something like this to the core, I'll add it as plugin.

-Felix

**Comment by Jermolene** [comment]
The hack you are using is a great approach for a plugin but would need to be a bit more flexible for the core.

Using CSS is undoubtedly clunky seeming but it's not too painful. Why not have two (or more) entirely separate navigation bars, and switch between them with CSS?

**Comment by felixhayashi** [comment]
> Using CSS is undoubtedly clunky seeming but it's not too painful. Why not have two (or more) entirely separate navigation bars, and switch between them with CSS? 

It is not just about the navigation bars. We want to control what content the user is able to find via search in mobile and what content is displayed in tiddlers and which templates are used.

> The hack you are using is a great approach for a plugin but would need to be a bit more flexible for the core.

I'll go the plugin path then :)

-Felix

**Comment by Jermolene** [comment]
> It is not just about the navigation bars. We want to control what content the user is able to find via search in mobile and what content is displayed in tiddlers and which templates are used.

To be honest, since mobile vs. desktop doesn't change after startup, that sounds more like a use case for startup actions, as discussed in #1438.

**Comment by felixhayashi** [comment]
> To be honest, since mobile vs. desktop doesn't change after startup, that sounds more like a use case for startup actions, as discussed in #1438. 

Cool stuff. I didn't know such a mechanism exists. I will certainly use it (if not for this then in another situation). However, I also want to support scenarios where a screen is resized after the wiki booted. Therefore I need to attach a listener that keeps track of window events. But thank you very much for your input regarding the whole matter. I appreciate it.
