### ISSUE TITLE
"new here" should open new tiddler below the current one

### ISSUE THREAD

**Issue by Jermolene** [Jermolene/TiddlyWiki5#1665]
Currently, the new tiddler is created at the top of the story river. And also for "new journal here".

**Comment by felixhayashi** [comment]
Hi @Jermolene 

maybe align this should be align with the changes in https://github.com/Jermolene/TiddlyWiki5/pull/1662 ? So the system looks at the user configuration first to decide where to place it...

-Felix

**Comment by Jermolene** [comment]
Yes @felixhayashi (I should have referenced #1662 as the expected fix for this).

**Comment by felixhayashi** [comment]
Ah ok :)
