### ISSUE TITLE
Add jQuery.fracs support

### ISSUE THREAD

**Issue by silvyn** [Jermolene/TiddlyWiki5#1670]
Hi,

I wondering if it will possible to add **jQuery.fracs** (as plugin maybe), more information : http://larsjung.de/jquery-fracs/ (and https://github.com/lrsjng/jquery-fracs).

With many opened tiddler, this will help user to find content more easily.

Cheers,
Sylvain

**Comment by pmario** [comment]
TW doesn't use jQuery. ... but a similar "bird eye view" would be cool as a plugin.

**Comment by Jermolene** [comment]
Hi @silvyn it is indeed a very nice feature, but it is not something that I think would go into the core in the first instance. I'll close this ticket because we like to try to keep the tickets actionable issues.

**Comment by pmario** [comment]
@silvyn 
The stacked view, shown here https://youtu.be/7tRvAj1ZG9s?t=1362 may be of interest for you.
