### ISSUE TITLE
ToC macros should not recurse indefinitely

### ISSUE THREAD

**Issue by rubaboo** [Jermolene/TiddlyWiki5#1671]
Would it make sense to add "!currentTiddler" to toc*body macros' filters? It's a bit over my head, can't make a pull request...

**Comment by Jermolene** [comment]
Hi @nameanyone thanks, I'd forgotten about this problem. There's no recursion detection with macro invocations. I think the best fix is for the TOC to transclude a template for its body. Then we'll inherit the existing recursion detection that works with transclusion.

**Comment by tfeb** [comment]
Just to add to this: the ToC looping problem is pretty toxic: I inadvertantly constructed such a loop (I wanted a tag which was the tag of tiddlers which were tags, and put that in the ToC) and it essentially killed firefox (pinwheel on the mac, and it wasn't clear if it was going to unfreeze itself).

**Comment by tobibeer** [comment]
I would say something as complex as a toc (or generally speaking: a tree) should not be constructed from recursive list widgetry ...but rather compute the entire output in one go and then construct the tree at once accordingly.

**Comment by Jermolene** [comment]
The new text-slicer plugin includes a much more elaborate implementation of the TOC that does use separate template tiddlers for each node in the tree. By using recursive transclusion, instead of recursive macros, an error is automatically displayed, instead of hanging the browser. When the text-slicer work has progressed a bit more, I'd like to backport some of it to replace the current TOC macros.

https://github.com/Jermolene/TiddlyWiki5/tree/master/plugins/tiddlywiki/text-slicer/templates/interactive

**Comment by tobibeer** [comment]
One issue with recursion seems that it seems impossible to confugre a tree or toc to be free from duplicates, even though they may exist. Stopping at any duplicate would not eat up the children, I believe, as they would still show up at the first instance. It would only show an incomplete list whereever any duplicates would have occured, as the duplicate would no longer there be there (or perhaps just not show any children, perhaps with an indication that it is a duplicate and a modifier to jump to the other entry for which it is but a truncated clone).

**Comment by Jermolene** [comment]
> One issue with recursion based on widget trees 

I'm not sure what you mean here. The two forms of recursion being discussed are recursive transclusion, and recursive macros. Both of them are based on widget trees.

>  it is impossible to confugure a tree or toc to be free from duplicates

What do you mean by duplicates? Is it the same as a loop?

If so, the point that I was making that the text-slicer plugin includes an alternative implementation of the TOC macro that truncates loops in the tree.

**Comment by tobibeer** [comment]
Consider a tagging tree. TiddlyWiki does not prevent a tiddler somewhere deep in that tree from being a leaf in two or more of its branches... hence, duplication.

**Comment by Jermolene** [comment]
> Consider a tagging tree. TiddlyWiki does not prevent a tiddler somewhere deep in that tree from being a leaf in two or more of its branches... hence, duplication.

That's precisely what I was saying: the current TOC macros (based on recursive macros) do not prevent duplicates. The new TOC macros in the text-slicer plugin (based on recursive templates) do detect and prevent duplicates.

**Comment by tobibeer** [comment]
Thanks, that is what I meant then.

**Comment by pmario** [comment]
>Consider a tagging tree. TiddlyWiki does not prevent a tiddler somewhere deep in that tree from being a leaf in two or more of its branches... hence, duplication.

I consider this behaviour to be a feature, not a problem. IMO it always depends on the point of view of the user. The nature of TW is non linear. So if there are 2 or more ways to enter one tiddler, I'm fine with that.

**Comment by Jermolene** [comment]
@pmario I don't think that @tobibeer is talking about the same tiddler appearing in multiple places in the tree, he's talking about loops where a tiddler is its own ancestor.

**Comment by tobibeer** [comment]
actually, I was not talking about loops but about trees that have not only duplicate leaves but duplicate branches (due to duplicate tags with subtrees) which, in extreme cases can even extrend infinitely, yes ...with the same tag being in its own tagging ancestry

**Comment by Jermolene** [comment]
> with the same tag being in its own tagging ancestry

That sounds like what I was calling a loop, I think?

**Comment by tobibeer** [comment]
I don't think so. More like me having an arm identical to my left arm attached to my foot, rather than at my left arm's pinky.

**Comment by pmario** [comment]
imo we fixed this problem in 5.1.14 https://github.com/Jermolene/TiddlyWiki5/pull/2650. So please close.
