### ISSUE TITLE
ToC point to "Draft of"

### ISSUE THREAD

**Issue by nameanyone** [Jermolene/TiddlyWiki5#1672]
Currently, if the tiddler is being edited, a link from ToC brings up the same tiddler in view mode.

**Comment by pmario** [comment]
A tiddler and the "Draft tiddler" actually are 2 different tiddlers. So imo that's by design. .. What would you expect? and why?

**Comment by Jermolene** [comment]
Hi @nameanyone the "problem" is that editing a tiddler doesn't actually affect the tiddler itself. It just creates a draft that is linked to that tiddler. There can actually be multiple drafts linked to the same tiddler. Echoing @pmario, what were you expecting to happen?

**Comment by nameanyone** [comment]
I was not aware of multiple drafts situation. From the user experience perspective, I only ever see either the tidddler or it's draft, not both at once and not multiple drafts. So when I had a tiddler in edit mode, and clicked on ToC entry, it was a surprise to see it in view mode at the same time. I was expecting to just have the story scroll to where I had it open in edit mode.

When there are multiple drafts, their contents are not in sync and the last saved wins?

**Comment by Jermolene** [comment]
>  From the user experience perspective, I only ever see either the tidddler or it's draft, not both at once and not multiple drafts

Yup, the draft mechanism implementation is semi-hidden; casual users needn't be aware of it, but people writing complex custom wikitext would come up against the need for `!has[draft.of]` from time to time.

> When there are multiple drafts, their contents are not in sync and the last saved wins?

That's correct. Pretty much all that happens is that clicking the confirm/tick button replaces the target tiddler with the draft tiddler.

**Comment by nameanyone** [comment]
I take it the request (to repoint the ToC link to the draft when one is open) doesn't make sense then. Please close the ticket if that's the case. Thanks!

**Comment by Jermolene** [comment]
It's actually quite easy to make the drafts appear in the ToC; there are specific steps taken at the moment to exclude them. The harder thing would be to exclude ordinary tiddlers that have at least one corresponding draft.

**Comment by pmario** [comment]
@nameanyone 
as Jeremy pointed out, there would be an easy possibility to make the draft tiddlers part of any toc() macro.

If you open the tiddler `$:/core/macros/toc`  and search for `!has[draft.of]` and remove it. .. All draft tiddlers will show up in the toc. ... 

The disadvantage is, that overwriting this core macro will not update future core macro changes. So your changes will always win. Only this one tiddler will be affected. 

The good thing here is, that if you remove the `$:/tags/Macro` tag or delete your tiddler, the core will take over again.
