### ISSUE TITLE
bug: tw.com PDF demo not worky

### ISSUE THREAD

**Issue by twMat** [Jermolene/TiddlyWiki5#1673]
On tw.com, [Motovun Jack.pdf](http://tiddlywiki.com/#Motovun%20Jack.pdf) does not appear in:

[updated Oct 2016] 
Edge or IE.

**Comment by pmario** [comment]
For me it works with win 8.1, FF 37.01, FF 37.02 and Chromium Version 40.0.2186.0
TW 5.1.8

**Comment by pmario** [comment]
IE 11 without any pdf plugin doesn't show anything.

**Comment by Jermolene** [comment]
@twMat the issue here is that browser support for embedded PDFs varies wildly. There should probably be a note to that effect on tw.com

**Comment by twMat** [comment]
A FF crash+restart later, it now works on FF37.0.2 (no idea why not the first time).
Chrome 42.0.2311.90 m and IE 11.0.9600.17728 show only large white tiddler. I use no plugins for these two browsers.
I'm on Win 8.1 x64

>embedded PDFs varies wildly.

Still surprising Mario, using same OS, gets it to work on Chrome.

>There should probably be a note to that effect on tw.com

Agree. Should I create new issue?

**Comment by Jermolene** [comment]
> Agree. Should I create new issue?

I think it's reasonable to continue to use this ticket for the documentation issue because that's our response to the issue.

A pull request is even better though :smile:

**Comment by pmario** [comment]
>Still surprising Mario, using same OS, gets it to work on Chrome.

I'm using Chromium .. not Chrome, so there may be some differences.

**Comment by roma0104** [comment]
Not sure when it happened but about two weeks ago I tried to open an embedded PDF tiddler and the content is not rendered for me either.  It sizes the tiddler viewport to the size needed to display the content but doesn't draw it.

Both Chrome/W7 and Chromium/Chrome/ArchLinux & Debian experience this issue.  Firefox does not have this problem.

You can right click and save the file locally, no corruption that I can see.  Open the pdf directly in Chrome, I can view it without an issue.  Seems to be related to being viewed in a tiddler.

**Comment by roma0104** [comment]
Update, I also have a blank tiddler on IE/W7 too.

**Comment by Jermolene** [comment]
Hi @roma0104 I've found that browsers are not always consistent stable when embedding PDFs. It's a relatively new capability for most browsers and I guess the kinks haven't been ironed out.

**Comment by roma0104** [comment]
Yeah I got to looking at bugs on Chromium, I cannot find the exact bug that
might be affecting this, but looks like they has had a rash of pdf bugs in
Chrome around the time this issue appeared, definitely seems like a browser
issue.  I also scrapped a test embed pdf, same issue as with the tiddlers.

**Comment by twMat** [comment]
Update, or perhaps another use case as I'm now on Win10:

It appears to work well on FF and Chrome.
Still blank on IE and also Edge - both in default mode, except I've manipulated several Win10 security settings.

**Comment by pmario** [comment]
Imo that's a browser problem.

**Comment by twMat** [comment]
>Imo that's a browser problem.

My guess is that you're right - but you and I suffer the consequences from it...

**Comment by atulgrover** [comment]
I my case the pdf tiddler works fine on windows 10 desktop browsers.... but has failed on almost all mobile device browsers (FF, Opera, UC, ....) There ought to be a way to render the pdf on mobile browser...

**Comment by sukima** [comment]
> A FF crash+restart later, it now works on FF37.0.2 (no idea why not the first time).

I recall a strange situation where my latest updated FF refused to load WebGL sites. Ir wasn't till I trashed all my profile information and went back to factory default (FF calls this a *refresh*) and it worked. Seems FF can at times get a bit messy in the configuration department and it could do a bit of spring cleaning from time to time. ¯\\\_(ツ)\_/¯

**Comment by sukima** [comment]
> There ought to be a way to render the pdf on mobile browser...

What about using a tad bit of browser sniffing and when on mobile instead of embedding the PDF (in an iframe) could a link be presented instead that when clicked would open the PDF like any other website? Would this work with `data:application/pdf;`?

**Comment by Jermolene** [comment]
Hi @sukima TiddlyWiki displays embedded PDFs using the `<embed>` tag. We could link to them instead but (a) as you suggest, it's not clear that all browsers can display a data URI in that way and (b) there's no obvious way we can sniff for the ability to display PDFs correctly.

In general, I'd rather not load the core with fallback code for browsers that are lagging in support for broadly accepted HTML5 features. Instead, we can create plugins that modify the core behaviour to work with such browsers. So, we might have a plugin providing a `position: sticky` polyfill for Firefox, or one for changing the way that PDFs are displayed for older browsers.

**Comment by tobibeer** [comment]
So, is this a won't fix?

**Comment by pmario** [comment]
@Jermolene .. imo "cantfix" ... its a browser problem

**Comment by pmario** [comment]
@Jermolene ... pls close, we can't fix it. It's a browser problem.

**Comment by Jermolene** [comment]
Thanks @pmario
