### ISSUE TITLE
transclusion looses elementary paragraph division

### ISSUE THREAD

**Issue by twMat** [Jermolene/TiddlyWiki5#1675]
Tiddler A contains something with multiple paragraphs, e.g:

```
foo

bar
```

Tiddler B contains:

```
frotz {{Tiddler A}}
```

this results in Tiddler B showing:

```
frotz foo bar
```

I.e the paragraph division is replaced with a space character.

**Comment by Jermolene** [comment]
Hi @twMat 

I'm afraid this is our old friend "confusing block vs. inline rules".

You're generating an inline mode transclusion because it's part of a paragraph (in this case the text "frotz" starts the paragraph).

To make an inline mode transclusion, put the transclusion on a line by itself after the previous block mode structure:

```
frotz

{{Tiddler A}}
```

Or you can use the `<$transclude mode="block"/>` widget syntax.

**Comment by pmario** [comment]
yes, because you told it to do so. The transclusion is in inline mode
use: 

```
foo

{{Tiddler A}}
```

**Comment by pmario** [comment]
several seconds to late :)

**Comment by twMat** [comment]
Thank you both for the explanations.

Would *inline-block* not be better for transclusions then? As a user I expect a transclusion to mirror the appearence of the source as closely as possible.

A separate issue, but since we're at it: As you know, the proposed solution to put the transclusion at a (two) separate row(s) below causes an empty line in view. (A problem recurring for a few elements, other than transclusion, too). It is not appropriate to *force* a user to display such empty lines.

**Comment by pmario** [comment]
you can use the transclude widget http://tiddlywiki.com/#TranscludeWidget in block mode. So you can write. 

```
frotz <$transclude tiddler="B" mode="block"/>
```

**Comment by pmario** [comment]
Now you can argument, that widgets are complicated and it should be wikitext. ... 

yes. ... this is an open issue:  Transclusion syntax for forcing block vs. inline mode #905

**Comment by twMat** [comment]
>widgets are complicated and it should be wikitext. 

In deed. And thank you for the ref to the other thread. I'm happy to see it is a recoginzed problem and that Jeremy classes it as an improvement issue.

I'm closing this thread and continuing in the other one.
