### ISSUE TITLE
reveal widget position is not updated when in a scrollable

### ISSUE THREAD

**Issue by le-pako** [Jermolene/TiddlyWiki5#1679]
Hi,

There seems to be an inconsistent behavior when using a reveal widget within a scrollable.
The widget keeps positioning the popup at the same place, independently of the position of its containing element. I verified this with Firefox 37 and Chrome 42.0.2311.90, on Mac OS X (10.9.5) 64bit.

I wrote an example here : http://le-pako.github.io/reveal-position.html

Regards

**Comment by Jermolene** [comment]
Hi @le-pako I think the fix is to give the scrollable widget `position: relative;`:

```
.scroll{
width: 300px;
height: 34px;
background-color: #f4f4f4;
position: relative;
}
```

I'll update the docs to make things clearer.

**Comment by le-pako** [comment]
Thanks Jeremy,
The fix does update the popup's position, but now it appears underneath the containing div :disappointed: See it updated in the same site.

**Comment by Jermolene** [comment]
Hi @le-pako if you mean that the popup is clipped within the scrollable, it seems that that is the price for pinning the popup to the content of the scrollable. Fixing it would be quite hard: one would presumably want the popup to extend outside the container but to disappear when the popup trigger element is scrolled out of view. On the face of it, that would need some JavaScript logic.

**Comment by le-pako** [comment]
Indeed I meant the popup is clipped. I see what you're saying about expecting the popup to disappear when scrolled out, but at the same time I can't seem to find a way to have a dropdown popup within a scrollable horizontal bar. 
Would you have any pointers for a solution that would leave it visible?

Thanks!

**Comment by Jermolene** [comment]
Hi @le-pako 

> Would you have any pointers for a solution that would leave it visible?

As I say, I think it's really quite a difficult problem (even outside TW). The best approach may be to think of it like a master-detail arrangement: clicking and selecting an item in the scrollable list would cause the details of that item to appear in a panel below/alongside the scrollable list.
