### ISSUE TITLE
Typo in ButtonWidget tiddler in full wiki

### ISSUE THREAD

**Issue by Ishindri** [Jermolene/TiddlyWiki5#1681]
In the ButtonWidget tiddler in the full wiki at www.tiddlywiki.com, in the note at the bottom about using tc-btn-invisible, 'invisible' is missing an 'i'.  I copy-pasted the class name and was trying to figure out why my buttons didn't work right until I realized this.

**Comment by Jermolene** [comment]
Thanks @Ishindri much appreciated.
