### ISSUE TITLE
Issues with CamelCase in captions fields with the tab macro

### ISSUE THREAD

**Issue by Spangenhelm** [Jermolene/TiddlyWiki5#1697]
Hi, we can not use CamelCase words in captions fields with the tab macro otherwise they get transformed in links..

Left side: a tiddler called "Test" with "TiddlyWiki" as caption field
Right side: a tiddler called "TestTest" without caption field

![capture du 2015-05-05 02 02 25](https://cloud.githubusercontent.com/assets/6536752/7465097/d15637d4-f2ca-11e4-8cf8-372218ecb92d.png)

I suppose that it is not normal. Thank you

**Comment by Jermolene** [comment]
One of the differences between using the ''title'' field and the ''caption'' field is wikified. The advantage is that it enables you to embed images and other formatting within a tab. The autolinking behaviour is a confusing side-effect but I don't see much of a way of avoiding it without losing the ability to embed images.

**Comment by Spangenhelm** [comment]
I feel stupid i did not think about the tilde that we can use to prevent wikifying... :blush:

**Comment by BramChen** [comment]
@Jermolene How about if we set the `tv-wikilinks` variable to `no`? 


```
<$set name="tv-wikilinks" value="no">
<$transclude tiddler=<<currentTab>> field="caption">
<$macrocall $name="currentTab" $type="text/plain" $output="text/plain"/>
</$transclude>
</$set>
```

**Comment by Jermolene** [comment]
@BramChen - that is ingenious, congratulations.

**Comment by Spangenhelm** [comment]
:+1: @BramChen

**Comment by BramChen** [comment]
Thanks @Spangenhelm, but this does credit to @Jermolene (see [5b38c21](https://github.com/Jermolene/TiddlyWiki5/commit/5b38c21a417d2e5e2b85aed8010c88af32420e24)).

**Comment by Spangenhelm** [comment]
Fair enough ;-) Thanks for him !
