### ISSUE TITLE
2 new unused images in prerelease ??

### ISSUE THREAD

**Issue by pmario** [Jermolene/TiddlyWiki5#1700]
There are 2 big jpg files in the prerelease, that seem to have no function. 

Blurry Lawn.jpg
Newnham Horizon.jpg 

They are both linked from your flikr stream, with copyright set (c) only. 

Both images are downloaded and saved to my HD if I do: 

```
node .\tiddlywiki.js .\editions\tw5.com --output output --build index
```

Are they needed?

**Comment by Jermolene** [comment]
Hi @pmario the function of the files is to be demos for the page background feature in control panel. In the standalone HTML configuration the images are external, and so don't contribute to the wiki size. But they are loaded in the client-server configuration (thanks to #1000).

**Comment by pmario** [comment]
ok
