### ISSUE TITLE
Story freezing in zooming mode

### ISSUE THREAD

**Issue by buggyj** [Jermolene/TiddlyWiki5#1704]
How to reproduce:
goto www.tiddlywiki.com
change to zoomin mode
click the 'open' tab on the right
click 'community' 
click the 'x' in front of the 'HelloThere' to close it
click 'getting started' 
story is stays on the 'community' instead of showing 'getting started'

**Comment by Jermolene** [comment]
Hi @buggyj - what OS and browser are you using?

**Comment by buggyj** [comment]
I'm using ff 37.0 and xubuntu 14.04

**Comment by Jermolene** [comment]
Thanks @buggyj I've got it now.

**Comment by buggyj** [comment]
was fixed - fix for issue - Story freezing in zooming mode #1704 #1706
