### ISSUE TITLE
Navigator widget should navigate to draft if it exists

### ISSUE THREAD

**Issue by Jermolene** [Jermolene/TiddlyWiki5#1710]
If the navigator widget receives a message to navigate to a tiddler that has a draft then the navigation should be redirected to the draft.

See discussion here: https://github.com/Jermolene/TiddlyWiki5/issues/1202#issuecomment-99925603

**Comment by nameanyone** [comment]
That's exactly what I was asking for in #1672. :)

**Comment by Jermolene** [comment]
@nameanyone :smile:

**Comment by twMat** [comment]
>If the navigator widget receives a message to navigate to a tiddler that has a draft then the navigation should be redirected to the draft.

How would one access the non-draft at all?

An alternative approach might be to alert the user in view mode:

(just an image, I don't have a working prototype)

![image](https://cloud.githubusercontent.com/assets/4534056/26169074/b2c339cc-3b3c-11e7-9a22-03391ce36354.png)

**Comment by tobibeer** [comment]
-1 for the OP, +1 for @twMat

**Comment by twMat** [comment]
@Jermolene - do you still feel your OP is desirable?

My proposal would be trivial to implement. If you think it is a good idea, then I could do it.

**Comment by Jermolene** [comment]
I also prefer @twMat's proposal :)

**Comment by pmario** [comment]
@Jermolene ... We do have a "red link" at the bottom of the page, if a draft exists, but is closed. IMO this can be closed

**Comment by twMat** [comment]
I agree with @pmario

**Comment by Jermolene** [comment]
Thanks @pmario @twMat
