### ISSUE TITLE
Tag manager could provide more information

### ISSUE THREAD

**Issue by danielo515** [Jermolene/TiddlyWiki5#1715]
The Tag manager interface is pretty empty. Please look at the screenshot below. It would be more useful if it includes some more information. For example the amount of tiddlers tagged with that particular tag.

![image](https://cloud.githubusercontent.com/assets/2270425/7539615/780e28b8-f5a8-11e4-81bf-81dc5fea3b68.png)

**Comment by danielo515** [comment]
I think this should be labeled as enhancement at least. And maybe with help wanted?

**Comment by pmario** [comment]
IMO this is the tag manager. It should be doing one thing well. Managing tag settings. 

There is already a view, that tells you how many tiddlers are tagged with that tag. 

See right sidebar: More: Tags   menu. So what is the advantage, to duplicate this info?

![tag-manager-github-issue](https://cloud.githubusercontent.com/assets/374655/8435150/03f65f46-1f50-11e5-9fea-7e0fdf2b972b.gif)

**Comment by sukima** [comment]
:+1: @pmario

**Comment by Jermolene** [comment]
I was imagining the tag manager as an extended version of what you see in the sidebar. There's certainly a case for making it a stricter subset by adding the tag totals to the tag manager. In fact, I wonder if we might not remove the tag totals from the sidebar; they are pretty slow to compute.

**Comment by sukima** [comment]
> I wonder if we might not remove the tag totals from the sidebar; they are pretty slow to compute.

Good idea!

**Comment by pmario** [comment]
>I wonder if we might not remove the tag totals from the sidebar; they are pretty slow to compute.

If it improves tab switching in the main view. +1 go for it and switch the info to the manager.

**Comment by danielo515** [comment]
Thank you @Jermolene for understanding my point of view.

@pmario , the tag list at the sidebar is nice, but when you click on the button that opens the tag manager you expect, at least, the same information. A tag manager seems incomplete without a count of each tag, for example. There is no need to duplicate information, but I don't see the problem of having this information in both places. But, if I have to chose one place, I prefer the tag manager.

It will also make sense an option to remove a tag, but that It's a bit harder I think.

**Comment by pmario** [comment]
> the tag list at the sidebar is nice, but when you click on the button that opens the tag manager you expect, at least, the same information.

In the sense that a UI should be "least surprise", you are right here. I didn't see it in that way. ... but ... I personally don't see the value of the counter information at all. 

Tags are shown automatically, if any tiddler is tagged with that tag. ... So every tiddler, that is listed has at least one tiddler below it. That's all, that's important. IMO the number itself has no meaning.

**Comment by danielo515** [comment]
Hello @pmario ,

I think you are limiting the usage of the tag manager to your own use case. For me it's important to know the number of each tag. Some times you add a tag, and then you do not use it never again. Maybe because you do not have more topics about that or maybe because it was a bad tag choice. I usually review tags and it's usage (aka number) to review my way of organizing and tagging. If a tag is used only once, then maybe you can remove that tag. If you have the same number of tiddlers tagged javascript and snippets, maybe you can merge them into a single tag. Having information about your metadata is as important as the metadata itself, and gives you a good overview of how you are organizing your information.

Regards

**Comment by danielo515** [comment]
Implemented on #1857
