### ISSUE TITLE
Irritates a bit: fluid layout is the default of the master branch

### ISSUE THREAD

**Issue by felixhayashi** [Jermolene/TiddlyWiki5#1719]
Hi @Jermolene,

just noticed that the fluid layout (which is really great!) is the default configuration of the master branch. Maybe this will cause some irritation when people that sync their wikis with the master branch discover a complete change of design (my case). I like the feature very much but imo it would be better to only highlight the feature as new option, without actually activating it? Just wanted to give you some feedback on this.

-Felix

**Comment by sukima** [comment]
I thought `master` was considered beta and meant to have drastic changes. Perhaps it is better to tie updates to a branch of a specific version. Thoughts?

**Comment by felixhayashi** [comment]
Hi @sukima 

> I thought master was considered beta and meant to have drastic changes.

Yes, its beta, but I do not think Jeremy actually wants to make the fluid layout the standard and also people who test beta or want to benefit from newest changes are valuable and should not be scared away. I personally really like the fluid layout in some scenarios but it makes it really hard to read text because it stretches way too far over a widescreen.

**Comment by Jermolene** [comment]
Hi @felixhayashi apologies, I intended to change the default just for the `prerelease` edition. I'll fix shortly.

**Comment by felixhayashi** [comment]
Thanks @Jermolene. I didn't intend to criticize this nice new feature it was just such a drastic layout change that I got confused a bit when I updated all my wikis.

-Felix

**Comment by Jermolene** [comment]
Not at all @felixhayashi, I'm grateful to you for pointing it out; I could have sworn I'd done it correctly!

**Comment by felixhayashi** [comment]
ok :)
