### ISSUE TITLE
Slider is just a button

### ISSUE THREAD

**Issue by danielo515** [Jermolene/TiddlyWiki5#1735]
On the reveal widget documentation there is a reference to a slider. I can't see any difference between any other normal reveal button. It's just a button! I expected a slider like those that are used as switches in several mobile Os

**Comment by twMat** [comment]
it refers to a sliding drop down. Like e.g the tiddler *Info panel*

**Comment by Jermolene** [comment]
Hi @danielo515 as @twMat says, going back to TWC we've used "slider" to mean a block of content that can be "opened" and "closed"; TWC had a specific `<<slider>>` macro but in TW5 we combine the button and reveal widgets to make a slider.

If you want to make a button that looks like a sliding control, you'd want something like this:

http://www.sitepoint.com/css3-toggle-switch/

**Comment by danielo515** [comment]
Thanks Mat and Jeremy 

But I'm still confused about the difference between the slider and a normal reveal widget. For me they look the same.

**Comment by Jermolene** [comment]
A "slider" is a term that we use to refer to a combination of an ordinary reveal widget and an ordinary button widget.

**Comment by danielo515** [comment]
Ok, makes sense. Is that defined at any place?

**Comment by Jermolene** [comment]
Hi @danielo515 we have this:

http://tiddlywiki.com#RevealWidget

> "Slider"
>
> A slider appears as a single button that can be used to toggle the display of the contained content.

**Comment by danielo515** [comment]
Hello @Jermolene , this is TWC terminology. You can not define what a Slider is just saying that a Slider appears. Slider is a concept that has another meaning nowadays, so if we are going to use it in a different way we should, at leas, provide an exact definition.

Regards

**Comment by felixhayashi** [comment]
I think "toggle button" or "switch" would be more appropriate...

**Comment by pmario** [comment]
Other UIs imo name it "accordion"
