### ISSUE TITLE
Infos of tiddler don't stay open

### ISSUE THREAD

**Issue by Spangenhelm** [Jermolene/TiddlyWiki5#1739]
Hi, when i am using my tws i click on the 'info" button in a tiddler then it opens up correctly but when i click on a tab inside it then the informations area closes by itself and i don't know why, all my four tws does the same but not the one on the main site. It must come from a modification i have made but which one ??!

Thank you

**Comment by Jermolene** [comment]
Hi @Spangenhelm does it still happen if you start TiddlyWiki in safe mode?

http://tiddlywiki.com/#SafeMode

My hunch would be to look to see if any shadow tiddlers whose title starts with `$:/core/ui/TiddlerInfo` have been modified. I'd also look carefully at any JavaScript modules you might have installed.

**Comment by Spangenhelm** [comment]
Hi @Jermolene the safe mode helped me found what was happening and apparently the problem comes from this tiddler: `$:/core/ui/ViewTemplate/title` which is strange because i have not modified it manually. Maybe it comes from an old version and has been imported on mistake. Anyway i have deleted it to restore its shadow and it is now corrected and works fine again.

Thank you for your help
