### ISSUE TITLE
Toolbar for tiddler text editor

### ISSUE THREAD

**Issue by danielo515** [Jermolene/TiddlyWiki5#1747]
Hello, 

Since it is a planned feature to allow external widgets access edit text selection and content we are going to have lots of plugins customizations to add editor buttons. It will be easier for anyone that just wants to add a button to a toolbar to just create the button and tag it accordingly like we do with other Toolbars. This toolbar should be placed over the edit text  widget on the edit template and should be only visible if there is any button to display. 

Maybe this bar should even render the button to assure a button style  consistency and the button creator provide only the logic and content of his/her button. 

What do you think?

**Comment by Jermolene** [comment]
Hi @danielo515 it is indeed the plan to support an extensible toolbar for the tiddler text editor.

**Comment by danielo515** [comment]
Nice to hear that!
Then we can use this ticket as a reminder, and a notification to interested users.

**Comment by Jermolene** [comment]
See #2315 for an implementation.

**Comment by siulung4073** [comment]
Great thanks!
