### ISSUE TITLE
Auto-focus can occur inappropriately

### ISSUE THREAD

**Issue by danielo515** [Jermolene/TiddlyWiki5#1748]
It is desirable an option to deactivate it.  Also there are some events that triggers an auto focus without any sense. Changing the story view for example. 

How to reproduce this:
* Go to TW.com
* Search bar gets the focus automatically
* Change the view to zoom view. Search bar gets the focus again

Other place where this happens is on the plugin library
* Open the plugin library
* Change the tab
* Each search field gains the focus on every tab change

This is particularly annoying on mobile, where this focus makes the on-screen keyboard to popup.

**Comment by Jermolene** [comment]
Hi @danielo515 I'm afraid that this is not a very useful bug report. The title doesn't describe the problem clearly, and the description doesn't explain how to reproduce the problem. There's no way that I can take useful action on it as you've written it.

There are some notes on bug reports here: http://tiddlywiki.com/static/ReportingBugs.html

That tiddler links to this blog post which is a good summary: http://mhay68.tumblr.com/post/1648223018/what-makes-a-good-bug-report

The key is to try to give me (or anyone else) enough information to reproduce and understand the bug.

**Comment by danielo515** [comment]
Hello @Jermolene 

Sorry for the lack of information. The title seems to be correct for me. I have edited the steps to reproduce it and the description. Let me know if it is meaningful  now.

**Comment by Jermolene** [comment]
@danielo515 apologies for the late reply, and thank you for improving the report.

The title "Auto focus is annoying" is poorly phrased because it doesn't convey the right information. All problems are likely to be annoying, after all.

**Comment by Jermolene** [comment]
Anyhow, the auto-focus feature is just exposing the underlying browser `autofocus` attribute. Browsers try to focus these elements whenever they are rendered. The refresh cycle that occurs when you change the story view, for example, triggers a refresh of the entire page, which is what causes the autofocus to be reprocessed.

The best approach for fixing it properly is via #1537; with that mechanism in place we can more intelligently apply the auto-focus logic.

**Comment by danielo515** [comment]
Thank you very much for adding this!
