### ISSUE TITLE
Include link text for links retrieved with getTiddlerLinks()

### ISSUE THREAD

**Issue by felixhayashi** [Jermolene/TiddlyWiki5#1749]
Maybe it makes sense, if not only the linked tiddlers are retrieved when using `$tw.wiki.getTiddlerLinks` and $tw.wiki.getTiddlerBacklinks` but also any alias the user defined in relation with the link ("[[alias|SomeTiddlerTitle]]").

I have to admit, I don't know how to deal with situations where two aliases point to the same tiddler...

**Please note (2015-12-22)**: This issue is originally about making the link alias available (to machines). At some point in the discussion, we instead began talking more about *semantic annotations*, which is a different topic: #2144.

**Comment by Jermolene** [comment]
Hi @felixhayashi the trouble is that computing the link text is actually a complex operation compared to computing link targets. Consider something like this:

```
<$link to="HelloThere">
This is
<strong>
a
</strong>
link
</$link>
```

To compute the link text requires walking through the parse tree nodes and concatenating the text. getTiddlerLinks() is highly performance sensitive, because it's called many times to compute missing and orphan links, so we don't want to make it any slower.

It would make more sense to make a new method that did the additional processing. You could look at the existing getTiddlerLinks() code as a starting point.

**Comment by felixhayashi** [comment]
Hi Jeremy

thanks for responding

> To compute the link text requires walking through the parse tree nodes and concatenating the text

No, there exist native properties that just return the combined text without markup:

> The Node.textContent property represents the text content of a node and its descendants.
> https://developer.mozilla.org/en-US/docs/Web/API/Node/textContent

For compatibility reasons:

   var text =  el.innerText || el.textContent;

My hotzone plugin uses this property to quickly extract the title from the tiddler frame:

    /**
     * Extracts the tiddler title from dom elements holding it.
     * 
     * @param {Element} target - The tiddler frame element.
     * @return {string} The title or undefined
     */
    var extractTitleFromFrame = function(target) {
        
      if(!(target instanceof Element)) return;
      if(!$tw.utils.hasClass(target, config.classNames.tiddlerFrame)) return;

      var el = target.getElementsByClassName(config.classNames.tiddlerTitle)[0];
      if(el) {
        var title = el.innerText || el.textContent;
        return title.trim();
      }

    };

-Felix

**Comment by Jermolene** [comment]
> No, there exist native properties that just return the combined text without markup:

That's a DOM function. Here we're dealing with a parse tree.

**Comment by felixhayashi** [comment]
> That's a DOM function. Here we're dealing with a parse tree.

Ehm ok. Then this would really be resource intensive I guess.

> because it's called many times to compute missing and orphan links, so we don't want to make it any slower.

I agree that performance is a top prio here. Should I leave this ticket open anyways, so it may be picked up in the future by anyone? It is clearly not a must-have for me but would be a nice-to-have (for tiddlymap it would make sense in some occasions to be able to directly infer the edge name from the link alias).

-Felix

**Comment by Jermolene** [comment]
@felixhayashi we would definitely never change `getTiddlerLinks()` to incorporate this suggestion because of the performance impact. The only change I can envisage making to deal with the original request is to add helper functions to make it easier to perform tasks like this directly on the widget tree.

**Comment by tobibeer** [comment]
Is there anything left to be done about this?

**Comment by felixhayashi** [comment]
Nope

**Comment by ybabel** [comment]
@Jermolene does recent comment's change your minds ? 
https://github.com/felixhayashi/TW5-TiddlyMap/issues/119

**Comment by Jermolene** [comment]
Hi @ybabel I'm not against helping @felixhayashi fix that issue, but the proposal here is not a viable solution; we can't make such a deep change to the existing function `wiki.getTiddlerLinks()`.

**Comment by ybabel** [comment]
thanks.
I think it's more about adding a `getTiddlerLinksAndType(tiddler)` than changing the existing `wiki.getTiddlerLinks()`
We where talking about adding a new parser rule like https://github.com/Jermolene/TiddlyWiki5/blob/f8027a37080c06bc4ee02295a6dbe4a997417b2b/core/modules/parsers/wikiparser/rules/prettylink.js but with extended regex to match something like `[[pretty-title|tiddler-title]](qualifier|qualifier|qualifier)` or `[[Displayed Link Title|Tiddler Title]]->tmap:"demo:uses"`
I tried to looked how to do that myself but it seems out of my coding skills right now.

**Comment by felixhayashi** [comment]
Hi, I created a general issue for this topic: #2144 
I'll also reopen this one.

-Felix

**Comment by Jermolene** [comment]
I think @felixhayashi this one should stay closed. The OP makes a very specific proposal which has been categorically rejected. #2144 fixes the same underlying problem, but it doesn't really have a direct relationship with the OP here.

**Comment by felixhayashi** [comment]
Yes, I am also much in favour of #2144 but wasn't sure whether this one here was rejected. Now that you make it clear, I'll close it.
