### ISSUE TITLE
Storyview Pop scrolls wrong when switching between view and edit

### ISSUE THREAD

**Issue by twMat** [Jermolene/TiddlyWiki5#1757]
Reproducing this is so straight on that I'm very surprised the issue has not been reported somewhere (or did I miss something)?
- Have multiple tiddler open, e.g [like this](http://tiddlywiki.com/#:[tag[HelloThere]]), and set story view to _Pop_.
- Scroll down to at least **below the very top two** tiddlers, and scoll to clearly see the tiddler (not just it's title sticking up a little).
- Click edit. This misplaces the tiddler so it is not correctly placed in the viewport where expected.
- The misplacement even more severe when you click Save or Undo (the tiddler is scrolled out of view).

Chrome and FF, Win8.1 and Win10

**Comment by Jermolene** [comment]
Good spot, @twMat, that's certainly pretty weird.

**Comment by felixhayashi** [comment]
> Click edit and notice the new positioning of the tiddler.

@twMat hmm, I didn't notice anything wrong. Has this been fixed maybe?

It may also be related to

* #2009 
* #2167

**Comment by tobibeer** [comment]
Well, I didn't notice what is reported, but when you close the editor again some weird scrolling is taking place and the tiddler that had been edited is not at all scrolled to. Perhaps I should open another ticket for that.

**Comment by twMat** [comment]
Updated description.

@felixhayashi, I suspect you didn't scroll down enough. For instance, I (now) notice that if the Ctrlpanel is left in position after setting to *Pop*, and you click edit on the one below (i.e second pos in river) then there is no crazy scroll.

**Comment by felixhayashi** [comment]
Ok confirmed, sorry @twMat.

**Comment by pmario** [comment]
@twMat ... Is this still a problem. I have no idea how to reproduce it.

**Comment by twMat** [comment]
@pmario , yeah it is still there. FF, Chrome Win10

**Comment by pmario** [comment]
@twMat I think this one is fixed now? The scroll mechanism has been changed in 5.1.16

**Comment by twMat** [comment]
>@twMat I think this one is fixed now? The scroll mechanism has been changed in 5.1.16

Great! Closing.
