### ISSUE TITLE
NPM failing to install on a Raspberry Pi 2

### ISSUE THREAD

**Issue by dittoslash** [Jermolene/TiddlyWiki5#1759]
pi@archen ~ $ sudo npm install tiddlywiki
npm http GET https://registry.npmjs.org/tiddlywiki

npm ERR! Error: failed to fetch from registry: tiddlywiki
npm ERR!     at /usr/share/npm/lib/utils/npm-registry-client/get.js:139:12
npm ERR!     at cb (/usr/share/npm/lib/utils/npm-registry-client/request.js:31:9                                                                         )
npm ERR!     at Request._callback (/usr/share/npm/lib/utils/npm-registry-client/                                                                         request.js:136:18)
npm ERR!     at Request.callback (/usr/lib/nodejs/request/main.js:119:22)
npm ERR!     at Request.<anonymous> (/usr/lib/nodejs/request/main.js:212:58)
npm ERR!     at Request.emit (events.js:88:20)
npm ERR!     at ClientRequest.<anonymous> (/usr/lib/nodejs/request/main.js:412:1                                                                         2)
npm ERR!     at ClientRequest.g (events.js:156:14)
npm ERR!     at ClientRequest.emit (events.js:67:17)
npm ERR!     at HTTPParser.parserOnIncomingClient [as onIncoming] (http.js:1256:                                                                         7)
npm ERR! You may report this log at:
npm ERR!     <http://bugs.debian.org/npm>
npm ERR! or use
npm ERR!     reportbug --attach /home/pi/npm-debug.log npm
npm ERR!
npm ERR! System Linux 3.18.10-v7+
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "tiddlywiki"
npm ERR! cwd /home/pi
npm ERR! node -v v0.6.19
npm ERR! npm -v 1.1.4
npm ERR! message failed to fetch from registry: tiddlywiki
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /home/pi/npm-debug.log
npm not ok

**Comment by dittoslash** [comment]
npm-debug.log:

info it worked if it ends with ok
verbose cli [ '/usr/bin/nodejs', '/usr/bin/npm', 'install', 'tiddlywiki' ]
info using npm@1.1.4
info using node@v0.6.19
verbose config file /root/.npmrc
verbose config file /usr/etc/npmrc
verbose config file /usr/share/npm/npmrc
verbose cache add [ 'tiddlywiki', null ]
silly cache add: name, spec, args [ undefined, 'tiddlywiki', [ 'tiddlywiki', null ] ]
verbose parsed url { pathname: 'tiddlywiki',
verbose parsed url   path: 'tiddlywiki',
verbose parsed url   href: 'tiddlywiki' }
verbose addNamed [ 'tiddlywiki', '' ]
verbose addNamed [ null, '' ]
silly name, range, hasData [ 'tiddlywiki', '', false ]
verbose raw, before any munging tiddlywiki
verbose url resolving [ 'https://registry.npmjs.org/', './tiddlywiki' ]
verbose url resolved https://registry.npmjs.org/tiddlywiki
http GET https://registry.npmjs.org/tiddlywiki
ERR! Error: failed to fetch from registry: tiddlywiki
ERR!     at /usr/share/npm/lib/utils/npm-registry-client/get.js:139:12
ERR!     at cb (/usr/share/npm/lib/utils/npm-registry-client/request.js:31:9)
ERR!     at Request._callback (/usr/share/npm/lib/utils/npm-registry-client/request.js:136:18)
ERR!     at Request.callback (/usr/lib/nodejs/request/main.js:119:22)
ERR!     at Request.<anonymous> (/usr/lib/nodejs/request/main.js:212:58)
ERR!     at Request.emit (events.js:88:20)
ERR!     at ClientRequest.<anonymous> (/usr/lib/nodejs/request/main.js:412:12)
ERR!     at ClientRequest.g (events.js:156:14)
ERR!     at ClientRequest.emit (events.js:67:17)
ERR!     at HTTPParser.parserOnIncomingClient [as onIncoming] (http.js:1256:7)
ERR! You may report this log at:
ERR!     <http://bugs.debian.org/npm>
ERR! or use
ERR!     reportbug --attach /home/pi/npm-debug.log npm
ERR!
ERR! System Linux 3.18.10-v7+
ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "tiddlywiki"
ERR! cwd /home/pi
ERR! node -v v0.6.19
ERR! npm -v 1.1.4
ERR! message failed to fetch from registry: tiddlywiki
verbose exit [ 1, true ]

**Comment by sukima** [comment]
I am extremely doubtful that anything at all works with **node v0.6.19** or **npm v1.1.4**

I think your in desperate need of an upgrade!

**Comment by dittoslash** [comment]
pi@archen ~ $ sudo npm install npm -g.
npm http GET https://registry.npmjs.org/npm

npm ERR! Error: failed to fetch from registry: npm

**Comment by dittoslash** [comment]
pi@archen ~ $ sudo apt-get update
Hit http://raspberrypi.collabora.com wheezy Release.gpg
etc etc
pi@archen ~ $ sudo apt-get install npm nodejs
Reading package lists... Done
Building dependency tree
Reading state information... Done
nodejs is already the newest version.
npm is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 81 not upgraded.

**Comment by pmario** [comment]
try this: http://weworkweplay.com/play/raspberry-pi-nodejs/

**Comment by tobibeer** [comment]
done? => close

**Comment by Jermolene** [comment]
I'll close on the basis that it was an unsupported version of Node.js
