### ISSUE TITLE
a href={{!!url}}  should open new tab

### ISSUE THREAD

**Issue by twMat** [Jermolene/TiddlyWiki5#1761]
Links normally opens in new browser tabs but `<a href={{!!url}}>url</a>` doesn't.
I cannot see any reason why the latter should not behave like the former and propose we harmonize these. Not opening a new browser tab means leaving the TW.... :-/

This also makes sense since we cannot use a href as internal links within tiddlers.

**Comment by twMat** [comment]
I discovered this is probably a pure html issue; writing instead <a href={{!!url}} target="_blank">url</a> gives the correct behaviour. I.e not a TW issue and I am therefore closing this issue.

**Comment by pmario** [comment]
just for reference: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a#attr-target

**Comment by twMat** [comment]
Thanks. That *is* a good reference.
