### ISSUE TITLE
Apply chosen "Tiddler Opening Behaviour" also to "new tiddler/here"

### ISSUE THREAD

**Issue by twMat** [Jermolene/TiddlyWiki5#1764]
@felixhayashi 
Extend the power of the new (5.1.9) [Tiddler Opening Behaviour](http://tiddlywiki.com/prerelease/#%24%3A%2Fcore%2Fui%2FControlPanel%2FSettings%2FLinkToBehaviour) to apply also to commands "new tiddler" (="navigation from _outside_ the story river") and "new here" (="navigation from _within_ the story river")

**Comment by felixhayashi** [comment]
@twMat Good point! This looks like an unwanted inconsistency. Maybe Jeremy knows how to fix this fast? Otherwise, I'll file a pull request as soon as I find the time.

**Comment by Jermolene** [comment]
The fix would be to update `handleNewTiddlerEvent()` in navigator.js to honour the new settings. I don't think there's any quicker way!

**Comment by tgirod** [comment]
:+1: In 5.1.8, adding and using the "new tiddler here" button would be much easier if the created tiddler appeared just below the current tiddler.

**Comment by Jermolene** [comment]
Hi @tgirod 

> adding and using the "new tiddler here" button would be much easier if the created tiddler appeared just below the current tiddler.

That's a separate bug that's fixed for 5.1.9 - try http://tiddlywiki.com/prerelease

**Comment by twMat** [comment]
IMO this is now sufficiently solved. "new tiddler" opens correctly but there's still an inconsistency in that "new here" always opens below the current tiddler. I'm guessing few are bothered by this.
Closing.
