### ISSUE TITLE
RenderTiddlers dont take into account macro

### ISSUE THREAD

**Issue by fmezou** [Jermolene/TiddlyWiki5#1770]
Hi,
I use the renddertiddler command, whith Node.js,  to generate and How-to file from several How-to tiddlers. I create the below macro to have a unique typography for file name.
I noticed that the macro is not take into account by the renddertiddler command. The macro is replace by an empty text.

```
\define file(_) <font color=blue>//$_$//</font>
```

TiddlyWki version 5.1.8

**Comment by pmario** [comment]
Your tiddler, that contains the macro is tagged: `$:/tags/Macro`?

**Comment by fmezou** [comment]
Yes,  il is.

Envoyé à partir de mon smartphone Sony Xperia™ 

---- Mario Pietsch a écrit ----

**Comment by fmezou** [comment]
You will find a test case. I confirm that the macro named file is stored in a tiddler tagged `$:/tags/Macro` (see the following snapshot)
![macro](https://cloud.githubusercontent.com/assets/12201157/8020625/a99e7746-0c7f-11e5-8dec-7898b0d676d6.png)
 
Tiddler : MacroTest
```
\define !file(_) <font color=red>//$_$//</font>

The [[appdeploy]] script uses two [[applist]] files to verify which applications were installed and if it needs to be updated: the first one is named <<!file applist-all.txt>> and ''must be exist'' even if it is empty; the second is named  <<file applist-&lt;set&gt;.txt>> where `<set>` is the argument passed to appdeploy on the command line (e.g. `.\appdeploy dummy`).
```

renddertiddler command result:
```html
<p>The <a class="tc-tiddlylink tc-tiddlylink-resolves" href="#appdeploy">appdeploy</a> script uses two <a class="tc-tiddlylink tc-tiddlylink-resolves" href="#applist">applist</a> files to verify which applications were installed and if it needs to be updated: the first one is named <font color="red"><em>applist-all.txt</em></font> and <strong>must be exist</strong> even if it is empty; the second is named   where <code>&lt;set&gt;</code> is the argument passed to appdeploy on the command line (e.g. <code>.\appdeploy dummy</code>).
</p>
```

And the snapshot...

![snapshot](https://cloud.githubusercontent.com/assets/12201157/8020592/c252854e-0c7e-11e5-9f89-c55d2d81c941.png)

Thanks for your help.
Regards

**Comment by pmario** [comment]
see: https://developer.mozilla.org/de/docs/Web/HTML/Element/font  may be works with the browser, but not with nodejs library.

try this instead: http://tiddlywiki.com/#Styles%20and%20Classes%20in%20WikiText  It uses the style tag.

**Comment by Jermolene** [comment]
@fmezou you are correct that the global macros are not by default available within templates rendered by the `rendertiddler(s)` command.

That's why the templates used for static rendering in the core all explicitly include the global macros:

https://github.com/Jermolene/TiddlyWiki5/blob/master/core/templates/static.tiddler.html.tid#L24

The reason that we do it this way is that it makes it easier to arrange for a different set of global macros to be used for static rendering. For example, one might have a different implementation of the `<<tabs>>` macro that renders output suitable for some jQuery plugin.

**Comment by fmezou** [comment]
@Jermolene , thank for help. I include a line with the $importvariables widget and it works.
And I should have read more closely the [Macro](http://tiddlywiki.com/#Macros)  section and especially [Macro Definitions in WikiText](http://tiddlywiki.com/#Macro%20Definitions%20in%20WikiText).

@pmario, I will take your advice to prevent compatibility issue.

Thank you for your help.
Regards
