### ISSUE TITLE
The sidebar hide tiddlers list when click on tags > tag_name

### ISSUE THREAD

**Issue by nderambure** [Jermolene/TiddlyWiki5#1772]
When the sidebar is on right, and tab "Tags" is open, clicking on one with some tiddlers inside shows a truncated list, hidden by a parent element. It's seems that it's linked to the element with flex property.
Anyone can reproduce ? (using 5.1.8)

**Comment by Jermolene** [comment]
I think this is the problem triggered by the fix for #1632.

@pmario I'm afraid I think we should revert that change and investigate alternative workarounds for the original problem.
