### ISSUE TITLE
refactor CSS in $:/themes/tiddlywiki/vanilla/base

### ISSUE THREAD

**Issue by nameanyone** [Jermolene/TiddlyWiki5#1773]
A number of .tc-drop-down's descendants (but not all) have their pading redefined, like so:

    .tc-drop-down p {
        padding: 0 14px 0 14px;
    }

This leads to an unfortunate situation where, for example, a block of code inside a drop-down is misaligned and doesn't have any margin on the left. Easy to fix for each particular case, but would you consider refactoring the code so it's not necessary to fix each possible element's margin/padding separately?

**Comment by Jermolene** [comment]
Hi @nameanyone that sounds sensible. Would you be in a position to make a pull request?

**Comment by nameanyone** [comment]
Maybe, I'll have to review the current usage of drop-downs and see why padding was done like this in the first place.

**Comment by nameanyone** [comment]
I see why it's done this way. Dropdown has zero padding but a paragraph inside it has generous padding on the sides, to make a nice looking menu with row higlighting stretching from side to side. This makes sense when dropdowns are mostly used as menus, as is the case in the core and on tiddlywiki.com.

I, on the other hand, was reusing the class to style a popup, as you have in the example (http://tiddlywiki.com/prerelease/#RevealWidget). The result doesn't look good with a mix of various elements making up the contents. I think the best would be to not reuse `.tc-drop-down`, but to create my own class for popups instead.

These are two distinct use cases, a menu and a generic content enclosed in a box. We can't style the dropdown and paragraph to suit both purposes equally well.

Feel free to close this ticket, @Jermolene.

**Comment by Jermolene** [comment]
Hi @nameanyone 

> . I think the best would be to not reuse .tc-drop-down, but to create my own class for popups instead.

Yes, that makes sense.
