### ISSUE TITLE
EditTextWidget Docs either confusing or wrong

### ISSUE THREAD

**Issue by sukima** [Jermolene/TiddlyWiki5#1776]
According to the [EditTextWidget](http://tiddlywiki.com/#EditTextWidget) documentation ([source](https://github.com/Jermolene/TiddlyWiki5/blob/master/editions/tw5.com/tiddlers/widgets/EditTextWidget.tid#L32-L42)):

> One trap to be aware of is that the edit text widget cannot be used to edit a field of the tiddler that contains it. Each keypress results in the tiddler being re-rendered, which loses the cursor position within the text field.
>
> Instead, place the edit text widget in a template that references the tiddler you want to modify.
>
> For example, if you wanted to edit the value of the "myconfig" field of the tiddler "AppSettings", you might do so by creating a separate tiddler "ChangeAppSettings" that contains the following:
>
> `<$edit-text tiddler="AppSettings" field="myconfig"/>`

Following the advise I've created the following tiddlers:

```
created: 20150607024110937
modified: 20150607024129485
tags: 
title: ChangeAppConfig
type: text/vnd.tiddlywiki

<$edit-text tiddler="AppSettings" field="myconfig"/>
```

```
created: 20150607023829776
modified: 20150607024104600
myconfig: foobar
tags: 
title: AppSettings
type: text/vnd.tiddlywiki

; `myconfig`
: {{!!myconfig}}

; `{{ChangeAppConfig}}`
: {{ChangeAppConfig}}

; `{{||ChangeAppConfig}}`
: {{||ChangeAppConfig}}
```

But this doesn't work! In fact the only way I could get it to work was to use a temp tiddler like so:

```
created: 20150607023829776
modified: 20150607025949106
tags: 
title: AppSettings
type: text/vnd.tiddlywiki

; `ChangeAppConfig!!myconfig`
: {{ChangeAppConfig!!myconfig}}

; `<$edit-text tiddler="ChangeAppConfig" field="myconfig"/>`
: <$edit-text tiddler="ChangeAppConfig" field="myconfig"/>
```

```
created: 20150607024110937
modified: 20150607025952056
myconfig: bar
tags: 
title: ChangeAppConfig
type: text/vnd.tiddlywiki

This is a dummy tiddler used to store fields. Ignore it. Better yet, make it a shadow tiddler.
```

I was going to edit the docs but the idea of off loading the fields from a throw away tiddler seemed wrong based on the current docs. So I was thinking maybe the code is broken. Or maybe the docs are wrong. Either way what is the proper way to allow a EditTextWidget to change a field that is to be transcluded in the same tiddler?

**Comment by Jermolene** [comment]
Hi @sukima your original code doesn't work because there's an obvious recursion. It's not a good idea to use the same tiddler for state data (the "myconfig" field) while also using it for content (the "text" field). The problems drop away when you use separate tiddlers.

**Comment by sukima** [comment]
So the docs need updating to explain that. I’ll work on a pull request later tonight.
