### ISSUE TITLE
Tiddler to delete in french edition

### ISSUE THREAD

**Issue by lolole13** [Jermolene/TiddlyWiki5#1781]
Hi everyone ! 

I am doing some translation in the french edition and I just saw that "A Gentle Guide to TiddlyWiki" tiddler is still in here. http://tiddlywiki.com/languages/fr-FR/index.html#A%20Gentle%20Guide%20to%20TiddlyWiki 
This tiddler seems not to be in the main edition so it is not useful to translate it any more. 

The solution is to simply delete it but some rights might be needed.  

Thanks for all.

**Comment by Jermolene** [comment]
@xcazin would you be able to deal with this? Many thanks

**Comment by xcazin** [comment]
Hi @lolole13, thank you for spotting this inconsistency. Actually, most of the content that was in the HelloThere tiddler recently moved into "A Gentle Guide to TiddlyWiki". @idoine did move it in the fr-FR edition, of which a more recent version is about to be pulled in #1766 (but as you see, there is a non-related issue that I've not been able to solve yet).

**Comment by idoine** [comment]
My translated full release is ok. I could send it you xcazin, if you wish ?
I have translated everything except References.

**Comment by xcazin** [comment]
@idoine "everything"?!? Wow. Not sure I'll have time to review and submit a pull request before 5.1.9, but please, do send translated tiddlers my way asap (in one json file if you can). Your previous submission will be included in the next release though: http://tiddlywiki.com/prerelease/languages/fr-FR/index.html

**Comment by idoine** [comment]
Everything except ... "References" which are the biggest work, but I learn the soft at the same time. 
I've learned to use the github "pull request" but for the moment, I just drag and drop my work without sending an import file. If you could explain how to do, I'll be fine. 
I would like to put tiddlywiki with 3 or 4 others opensource softs in a little package with our new system network (opensource) which could be published and tested in september.
Thanks for your link and sorry for my bad english ^^
^^

**Comment by xcazin** [comment]
Hi @idoine,

Maybe you can send me a whole tiddlywiki file containing your latest additions, and I'll figure a way to export the relevant tiddlers (that I'll document when I find more time).

**Comment by idoine** [comment]
Do this link to my dropbox file is a quite good answer ?
https://dl.dropboxusercontent.com/s/96jbcs63sy1y5sf/TiddlyWikiFullfr-518.html?dl=0

Two usefull tags :
- "mv" for Tiddlers, I translate or modify translation after send them to github
- "vmg" for recents "pull request"

**Comment by xcazin** [comment]
Cool! Tagging modified tiddlers is the way to go. See how it becomes easy to export them afterwards: ![capture d ecran 2015-06-22 a 09 32 37](https://cloud.githubusercontent.com/assets/1314688/8277330/ea66b894-18c1-11e5-8689-6be9d86c309a.png)
Then, it's a matter of removing the tags all in once. Still not sure what is the best option between the RenameTags trick or the actionsetfield widget.

**Comment by idoine** [comment]
Ok, Thanks. It's very easy. :)
I could look after better rules policies, and I try to design my titles better before send you more.

**Comment by idoine** [comment]
Hello, you could find here, every exported translated tiddlers in Json format
https://dl.dropboxusercontent.com/s/pl7zxk690zeled7/fr-tiddlers-fromIdoine.json?dl=0

Have a good day ;)

**Comment by Jermolene** [comment]
Is it ok to close this ticket now?

**Comment by idoine** [comment]
yes, it is
