### ISSUE TITLE
CodeMirror with sample config crashes

### ISSUE THREAD

**Issue by sukima** [Jermolene/TiddlyWiki5#1790]
I searched the issues and could not find. Close if this is a duplicate.

If you attempt to use the sample config given by the CodeMirror plugin TiddlyWiki crashes. Tried on both Firefox and Chrome.

Here is a [screencast](http://youtu.be/x-ZajGihMf8) showing how to reproduce the following:
1.  Go to http://tiddlywiki.com/plugins/tiddlywiki/codemirror/
2.  Open tiddler `$:/plugins/tiddlywiki/codemirror/usage`
3.  Copy the **first** config example
4.  Open tiddler `$:/config/CodeMirror`
5.  Edit and paste above into it.
6.  Set the type to `application/json`
7.  Save
8.  Edit another tiddler

In Firefox The error is _map is undefined_ in chrome _style is undefined_. I have a hunch this is related to the vim plugin (which is the sole reason for me to use the CodeMirror plugin).

![screen shot 2015-06-13 at 15 57 48](https://cloud.githubusercontent.com/assets/70075/8145837/26b69db4-11e7-11e5-93b3-68ab617c8e39.png)

**Comment by pmario** [comment]
@sukima ... cm has changed, pls test again?!

**Comment by sukima** [comment]
The updated codemirror no longer support Vim bindings. Should I open a new issue about that?
