### ISSUE TITLE
TW overwrites existing tiddler without a warning -> data loss

### ISSUE THREAD

**Issue by pmario** [Jermolene/TiddlyWiki5#1791]
To reproduce: 
- create 2 tiddlers `asdf` and `asdf<space>`
- open the second one `asdf<space>` in edit mode
- save
- the first one `asdf` will be overwritten without any warning

console code to test:

```
$tw.wiki.addTiddler(new $tw.Tiddler({title: "asdf", text: "asdf"}, $tw.wiki.getModificationFields()));
$tw.wiki.addTiddler(new $tw.Tiddler({title: "asdf ", text: "blabla"}, $tw.wiki.getModificationFields()));
```

expected behaviour
- If you use the following code to create 2 tiddlers 
- and rename `Abc` to `abc` you'll get a warning. <- OK

```
$tw.wiki.addTiddler(new $tw.Tiddler({title: "abc", text: "abc"}, $tw.wiki.getModificationFields()));
$tw.wiki.addTiddler(new $tw.Tiddler({title: "Abc", text: "blabla"}, $tw.wiki.getModificationFields()));
```

also see: https://github.com/Jermolene/TiddlyWiki5/issues/751#issuecomment-111760263

**Comment by felixhayashi** [comment]
Hi @pmario 

Everything works as expected. As a user (without code) I get warnings.

> create 2 tiddlers asdf and asdf 

this is not possible per design.. There will be always one tiddler asdf. And of course the second will override the first one without warning.

> console code to test:

Console code is different from user editing. It should never issue a warning.

> If you use the following code to create 2 tiddlers 
> and rename Abc to abc you'll get a warning. <- OK
> $tw.wiki.addTiddler(new $tw.Tiddler({title: "abc", text: "abc"}, $tw.wiki.getModificationFields()));
> $tw.wiki.addTiddler(new $tw.Tiddler({title: "Abc", text: "blabla"}, $tw.wiki.getModificationFields()));

But tiddlywiki does not have a renaming operation. What you did is create two independent tiddlers..

-- sorry maybe I completely misunderstand you here.

-Felix

**Comment by pmario** [comment]
The second example is the expected behaviour. I did include the code, to speed up tiddler creation. You can create them by hand if you want.

**Comment by pmario** [comment]
You are right. The first example can be only created if someone programmatically created a tiddler with a trailing space. eg: plugin authors. .. Then if a user manually wants to fix the problem, they unknowingly loose data, which imo is a bug. ... especially since the second example already works in the right way. So the core already knows what to do.

**Comment by felixhayashi** [comment]
Hi @pmario 

Ahh why didn't you write in the issue description that there is a trailing space at the end. I looked at the code and the titles of

    $tw.wiki.addTiddler(new $tw.Tiddler({title: "asdf", text: "asdf"}, $tw.wiki.getModificationFields()));
    $tw.wiki.addTiddler(new $tw.Tiddler({title: "asdf ", text: "blabla"}, $tw.wiki.getModificationFields()));

looked identical :D

**Comment by felixhayashi** [comment]
I really dislike trailing spaces and I think they should be removed in any case, even if added by javascript tiddler-creation.

**Comment by felixhayashi** [comment]
Ok now I know why I misread your description @pmario 

GitHub removes spaces from inline code :D 

    `   hallo      `  `hallo`

will result in `   hallo      `  `hallo`

;)

**Comment by pmario** [comment]
I did modify the OP a bit. So it should be more obvious :)

**Comment by danielo515** [comment]
Hello @pmario, 

I don't understand your first example. It happens to me very often that I have two tiddlers, one with space and other without space and they remain as independent tiddlers. This happens to me on mobile because mobile keyboards has the bad habit to add spaces automatically. So I don't understand the data loss report

**Comment by danielo515** [comment]
Hello @pmario 

Now I got your point. The issue is that you can create tiddlers with trailing spaces programmatically (eg. through a plugin) but you can't do the same with the edit template. That is what was happening to me. Are you sure that editing a tiddler with trailing spaces removes them?

**Comment by sukima** [comment]
I think this is related to issue #751

**Comment by Jermolene** [comment]
> the first one `asdf` will be overwritten without any warning

There's maybe an easy fix: to add a warning for this particular situation. It's a bit of an edge case, but we could detect that a rename due to trimming has occured, and check that we're not overwriting an existing tiddler.

**Comment by ng110** [comment]
> I really dislike trailing spaces and I think they should be removed in any case, even if added by javascript tiddler-creation.

I would strongly disagree with this.  If I'm handling tiddlers programmatically, it will create all sorts of problems if they change their title after I've written them (I'm having enough trouble with character encodings!).

For me the best solution to this bug would be to just not do the trimming.  The extra whitespace is hidden when rendered anyway (just as it is for extra white spaces in the middle of a title which don't get trimmed).

**Comment by pmario** [comment]
@felixhayashi 
>I really dislike trailing spaces and I think they should be removed in any case, even if added by javascript tiddler-creation.

But that's a different topic in the other tread  #751. This one is a "user edits a title and looses data, because there is no warning" issue.

@Jermolene 

>>the first one asdf will be overwritten without any warning

>There's maybe an easy fix: to add a warning for this particular situation. It's a bit of an edge case, but we could detect that a rename due to trimming has occured, and check that we're not overwriting an existing tiddler.

Yea, I think that would be good.

**Comment by diego898** [comment]
I posted a near duplicate at #3033, I closed that one and am just referencing it here.

**Comment by pmario** [comment]
Close this one, since we can't get a consensus.
