### ISSUE TITLE
Add a variable placeholder to the save template to allow custom filtering (2 issues)

### ISSUE THREAD

**Issue by nameanyone** [Jermolene/TiddlyWiki5#1800]
Not sure if this is applicable to other save templates. I'm using TW5 with Node.js, so I'd really like to see a placeholder at the end of `saveTiddlerFilter()` in `$:/plugins/tiddlywiki/tiddlyweb/save/offline`, like this:

    ... +[sort[title]] $(publishFilter)$

That would allow me to save a filtered "for publishing" version by simply defining a global `publishFilter()` macro.

Issue 2:
After I finished writing this, I decided to test it and found that a global macro has no effect in this case. `publishFilter()` macro only works if defined in `$:/plugins/tiddlywiki/tiddlyweb/save/offline` itself. Is this to be expected?

**Comment by pmario** [comment]
related to:  SyncFilter should build from certain tags instead of hardcoded #1746

**Comment by sukima** [comment]
I think what you want is editions.

In my case I have the following structure:

    .
    ├── wiki
    │   ├── tiddlers
    │   │   ├── $__DefaultTiddlers.tid
    │   │   └── ...
    │   └── tiddlywiki.info
    └── wiki-dist
        ├── tiddlers (empty)
        └── tiddlywiki.info

Thw wiki-dist `tiddlywiki.info` has a directive to point to the former wiki:

```json
{
    "description": "Basic HTML edition",
    "plugins": [
        "tiddlywiki/codemirror",
        "tiddlywiki/highlight",
        "tiddlywiki/railroad"
    ],
    "themes": [
        "tiddlywiki/vanilla",
        "tiddlywiki/snowwhite"
    ],
    "includeWikis": [
        "../wiki"
    ]
}
```

And I use the server on the wiki edition and run the renderTiddlers for the production output using the wiki-dist edition.

I use my `package.json` to do that with:

```json
{
  "name": "my-project",
  "private": true,
  "scripts": {
    "start": "tiddlywiki wiki --server",
    "build": "tiddlywiki wiki-dist --rendertiddler '$:/core/save/all' index.html text/plain",
  },
  "devDependencies": {
    "tiddlywiki": "^5.1.8"
  }
}
```

Then I can develop of publish by running `npm start` and `npm run build` respectivly.

**Comment by nameanyone** [comment]
@sukima,
Thank you for the detailed explanation. However, doesn't `index.html` end up being a complete "snapshot" of `wiki`? My goal is not simply to produce a single file copy of my wiki. I want to produce a subset. I might try the editions way, but I already have a tag-based solution, and I like the convenience and flexibility of it. No editions to maintain, just tag some tiddlers "Publish" and hit a "Publish" button. 

The only thing I don't like about it is I have to have a completely indepent template, which I created by copying `$:/plugins/tiddlywiki/tiddlyweb/save/offline` and adding to the end of the filter macro defined there. I could also just override the shadow. Either way, I now have to watch for changes in the default `$:/plugins/tiddlywiki/tiddlyweb/save/offline` and  maintain my template current.

Which is not ideal. So far I've managed a lot of customizations without overriding any core tiddlers. Other people seem not to have a problem with that. As a result, their customizations tend to get broken all the time by the core upgrades. I run the current github pre-release, update it daily and can't remember a case where I had to fix something because of a change in the core. I did catch and point out a bug or two this way though, the moment they were introduced :).

**Comment by nameanyone** [comment]
Checked  #1746, think my proposal here could be the answer to that as well. Keeps the configuration singular, yet customizable by the end user. A plugin could override `publishFilter()` macro temporarily, if it needs to.

**Comment by Jermolene** [comment]
Hi @nameanyone the reason that the reference to `$(publishFilter)$` didn't work inside `$:/plugins/tiddlywiki/tiddlyweb/save/offline` is because the `tm-download-file` and `tm-save-file` messages render the specified tiddler directly. They do not add the `<$importvariables>` widget needed to bring in the global macros. The usual way around that would be to include the `<$importvariables>` widget in the top level template that you're saving. In other words, instead of having your save button point to `$:/plugins/tiddlywiki/tiddlyweb/save/offline`, you would point it at a wrapper tiddler containing:

```
<$importvariables filter="[[$:/core/ui/PageMacros]] [all[shadows+tiddlers]tag[$:/tags/Macro]!has[draft.of]]">
<$transclude tiddler="$:/plugins/tiddlywiki/tiddlyweb/save/offline"/>
</$importvariables>
```

However, I'm guessing in your case you want to avoid modifying the existing save button. So perhaps its best to create an entirely new "publish" button for this?

**Comment by nameanyone** [comment]
Yes, I already have a Publish button and a template. However, I have to duplicate the content  of `$:/plugins/tiddlywiki/tiddlyweb/save/offline` in my template, rather than transcluding it, since I have no way of passing my variable to it. So, @jermolene, are you ok to add the variable to the end of `saveTiddlerFilter()`? I can do a pull request for that. Do you have a better name for it, or is `$(publishFilter)$` ok?

**Comment by Jermolene** [comment]
Hi @nameanyone apologies for the late response, yes please do go ahead with the pull request

**Comment by nameanyone** [comment]
@Jermolene: Submitted. This issue can be closed. Please review #1746 for possible closure as well. Thank you.
