### ISSUE TITLE
Application Auto Closes

### ISSUE THREAD

**Issue by bloodnines** [Jermolene/TiddlyWiki5#1852]
When opening the TiddlyWiki application on my Mac using Yosemite 10.10.3 the application window opens quickly, and is completely white. It then follows up too Hide the application window and the whole thing becomes unresponsive to any interaction, requiring it too be being force closed. 

It was running perfectly fine until a while ago. About a week.

**Comment by pmario** [comment]
So this happens if you go to http://tiddlywiki.com right?

**Comment by bloodnines** [comment]
My bad, I Apologize. I meant to post this within the TiddlyDesktop.
