### ISSUE TITLE
New filter "recent"

### ISSUE THREAD

**Issue by nameanyone** [Jermolene/TiddlyWiki5#1854]
Check it out [here](https://github.com/nameanyone/TiddlyWiki5/blob/master/core/modules/filters/recent.js). I modeled it after "sameday.js". It selects tiddlers with a specified date field (default "modified") within the last N days (default 0, meaning today).

@Jermolene, Would you accept a pull request if I only submit this one file, without any accompanying tw.com documentation? Thanks.

**Comment by Jermolene** [comment]
Hi @nameanyone I'd prefer to have the docs (and examples) included so that the change is clear to everyone.

**Comment by Jermolene** [comment]
But the `recent` filter looks a good idea, btw.

**Comment by nameanyone** [comment]
@Jermolene ,
Submitted pull request #1863 complete with documentation and examples.

**Comment by nameanyone** [comment]
Cought this using the new filter: [FilterParameter.tid](https://github.com/Jermolene/TiddlyWiki5/blob/fdbde1b389a46df684cd89bb876df843860d150e/editions/tw5.com/tiddlers/filters/syntax/FilterParameter.tid) has an invalid creation date.

**Comment by Jermolene** [comment]
Good catch @nameanyone, thanks.

**Comment by Jermolene** [comment]
Closed now that #1863 is merged
