### ISSUE TITLE
`$tw.loadWikiTiddlers` should store `tiddlywiki.info` metadata of included wikis

### ISSUE THREAD

**Issue by PaulPorfiroff** [Jermolene/TiddlyWiki5#1870]
### Summary

On Node.js TW5 I'm using `includeWikis` field in `tiddlywiki.info` file to construct an hierarchy of editions. Currently root edition contains server plugin definitions and it's descendants do not contain plugin property at all.

Updating from [v5.1.8](https://github.com/Jermolene/TiddlyWiki5/releases/tag/v5.1.8) to [v5.1.9](https://github.com/Jermolene/TiddlyWiki5/releases/tag/v5.1.9) led to an exception at [$:/core/modules/commands/server.js:304](https://github.com/Jermolene/TiddlyWiki5/blob/cc4d2319421eca1be03dcc79d5f16a9aa15e70ff/core/modules/commands/server.js#L304) when starting server for descendants.

### Steps to reproduce

E.g. suppose we've got two editions:

```
~/TW5/editions/BaseEdition
~/TW5/editions/ChildEdition
```

`BaseEdition` contains `tiddlywiki.info`:

```json
{
    "plugins": [
        "tiddlywiki/tiddlyweb",
        "tiddlywiki/filesystem"
    ]
}
```

And `tiddlywiki.info` of `ChildEdition` is just:

```json
{
    "includeWikis": [{
        "path": "../BaseEdition"
    }]
}
```

Now running the command:

```
tiddlywiki ~/TW5/editions/ChildEdition --server
```

Gives an exception at [$:/core/modules/commands/server.js:304](https://github.com/Jermolene/TiddlyWiki5/blob/cc4d2319421eca1be03dcc79d5f16a9aa15e70ff/core/modules/commands/server.js#L304) because of undefined `$tw.boot.wikiInfo.plugins`.

### Conclusion

My guess the problem is [$tw.loadWikiTiddlers](https://github.com/Jermolene/TiddlyWiki5/blob/cc4d2319421eca1be03dcc79d5f16a9aa15e70ff/boot/boot.js#L1594) leaving only the children's edition `wikiInfo` at the end of the call, for which `wikiInfo.plugins` in my case is undefined. It's clear that the same stays for `wikiInfo.themes` and `wikiInfo.languages`. So it seems currently there is no easy and fast way of accessing parental `wikiInfo`. Probably, caching of some sort would be useful here?

**Comment by Jermolene** [comment]
Hi @PaulPorfiroff thanks for the report.

The problematic code in server.js is trying to be too clever for it's own good. It tests for the plugins themselves, rather than the tiddlers containing them; the idea was to cope with a renamed plugin. I think it's probably better to just check for the tiddlers `$:/plugins/tiddlywiki/tiddlyweb` and `$:/plugins/tiddlywiki/filesystem`. I'll fix that momentarily.
