### ISSUE TITLE
adding a delete button in the view toolbar

### ISSUE THREAD

**Issue by tgirod** [Jermolene/TiddlyWiki5#1871]
It would be nice to be able to add a delete button in the view toolbar, to quickly delete a tiddler.

Right now, my use case is this:

- One tiddler contains a list of tiddlers of interest
- Click on the one I want to delete, to open it
- click on the edit button
- click on the delete button
- confirm

**Comment by Jermolene** [comment]
Good idea.

**Comment by tgirod** [comment]
everytime you do this I'm amazed by your reactivity :)

**Comment by Jermolene** [comment]
Thanks - this one was quite an easy one :)

**Comment by danielo515** [comment]
I think this have been asked more than once (I did a long time ago I think,specially for plugin tiddlers). Glad to see that it is now implemented.
