### ISSUE TITLE
feature request: \rules should be able to be global like macros

### ISSUE THREAD

**Issue by pmario** [Jermolene/TiddlyWiki5#1875]
see: https://groups.google.com/d/msg/tiddlywiki/kBqnMRQbjEQ/VA4gHxbuzloJ

There should be an easy way to globally define wiki parsing rules. eg:

`\rules except wikilink`

**Comment by Jermolene** [comment]
My thinking is to do this via #345. We'd have a few standard vocabularies registered at tw.com (perhaps one that has  the current rule set, and one that excludes CamelCase links). Users would be able to create their own vocabularies.

**Comment by pmario** [comment]
Ahh, you are right. From time to time I forget about this possibility :)

**Comment by Jermolene** [comment]
I've just committed an initial implementation that has some issues: d5e690a06d523a2047eaf9b623b633bb72c18af9

To try it out, change `$:/config/WikiParserRules/Inline/wikilink` to "disable" and rebuild. Changes only take effect after a restart.

There's also a UI in the control panel:

<img width="894" alt="screenshot 2015-07-30 12 31 20" src="https://cloud.githubusercontent.com/assets/174761/8982211/e8a39a5a-36b6-11e5-842a-260688f7834d.png">

Issues include:

* Disabling many rules will cause TiddlyWiki to completely break; we probably shouldn't have easily accessible buttons that do bad things
* Should we have a description for each rule? Should it be translatable?

I'm inclined to think that the best approach is to bury the existing control panel tab deeper into "Advanced", and to add a simple checkbox for "Automatically link CamelCase words" in the "Settings" tab.

**Comment by pmario** [comment]
>* Disabling many rules will cause TiddlyWiki to completely break; we probably shouldn't have easily accessible buttons that do bad things

May be a warning, that extensive use of these options may break TW. ... But I don't understand why. Most rules should be save. ... and those who break stuff need the warning. 

>* Should we have a description for each rule? Should it be translatable?

Descriptions need to be translateable. imo the rules don't. eg: prettylink should be prettylink, because if users use translated words here, imo it will be impossible to support it.

**Comment by Jermolene** [comment]
> But I don't understand why. Most rules should be save

Disabling html tags (which includes all widgets), macro definitions, macro invocations etc. all prevent the UI from rendering properly. Things like bold and italic, or tables, are pretty much fine.

> Descriptions need to be translateable

It's a big overhead to make them translateable, and I wonder how necessary it really is. The CamelCase setting would be translatable, and the others seem like very specialised, advanced settings.

**Comment by pmario** [comment]
>It's a big overhead to make them translateable, and I wonder how necessary it really is. The CamelCase setting would be translatable, and the others seem like very specialised, advanced settings.

I'd like to lower the number of system tiddlers, not increasing them.

**Comment by pmario** [comment]
>Disabling html tags (which includes all widgets), macro definitions, macro invocations etc. all prevent the UI from rendering properly. 

So HTML gets its own section and "You need to know, what you are doing!" warning.

**Comment by Jermolene** [comment]
> So HTML gets its own section and "You need to know, what you are doing!" warning.

It's not just html tags, probably half the rules are dangerous to disable. That's why I'm suggesting the alternative approach: keep all the rules accessible behind a warning in the Advanced tab, but pull up the useful ones to the "Settings" tab (currently just the rule for CamelCase, but maybe we'll find more).

**Comment by pmario** [comment]
You are right. 

 - All rules should be accessible. 
 - The useful ones go to the Settings tab and 
 - the dangerous ones go to Advanced. 
    - There may be a "Please backup first!" warning too :)

**Comment by felixhayashi** [comment]
> Disabling html tags (which includes all widgets), macro definitions, macro invocations etc. all prevent the UI from rendering properly. 

IMO **only** rules that are at the very end of the "logic chain" should be made accessible. Like strikethrough, bold, codeinline, wikilink. Those are the ones that no other logic depends on and only exist to support the user visually or represent shortcuts.

If //probably half the rules are dangerous to disable// then I would not do it. Imagine, the wiki gets saved and doesn't load anymore on refresh. 

-Felix

**Comment by Jermolene** [comment]
> Imagine, the wiki gets saved and doesn't load anymore on refresh.

The configuration is ignored in safe mode, so there is a way out.

I've got one candidate reason for why a user may need to switch on or off something like the html parser rule: if you've got a plugin that implements a compatible but extended rule; **MySuperHtmlParserPlugin**. That plugin might ship with a configuration shadow tiddler that disables the ordinary html parser rule. If the user wanted to switch back to the built-in rule without disabling the plugin then they would need access to checkboxes for all the available parse rules.

**Comment by felixhayashi** [comment]
> The configuration is ignored in safe mode, so there is a way out. I've got one candidate reason […]

Well, in that case I take back my objections :)

**Comment by pmario** [comment]
feature has been implemented.
