### ISSUE TITLE
Extend automatic system tiddler linking to digits and underscore

### ISSUE THREAD

**Issue by twMat** [Jermolene/TiddlyWiki5#1877]
In #1767  @pmario  explains regarding automatic SystemTiddlerLink detection.

```
There is a rule syslink.js that detects system tiddler links. It basically applies these rules:

    starting with a literal $:
    then any number of character not a whitespace, < or |
    closing with anything that is, again, not a whitespace, < or |

As Jeremy wrote ^^ and basically everything except whitespace < | are allowed for system tiddlers to be recogniced as automatic WikiLinks.
```

...but in my TWaddle site, I typically use the prefix 

`$:/_` (specifically, I use `$:/_TWaddle/`)

This is however not recognized as a WikiLink. Can it please be made to accept this.

Neither are suffixing digits or numbers included. Pretty serious IMO.

`$:/foo2`

**Comment by sukima** [comment]
I don't understand. `[[$:/_TWaddle/]]` works for me:

<img width="986" alt="screen shot 2015-07-13 at 09 30 49" src="https://cloud.githubusercontent.com/assets/70075/8650619/0be29e8a-2942-11e5-8d3d-3b836d7f28fc.png">

**Comment by Jermolene** [comment]
I think it makes sense to extend the automatic system tiddler link rules to include underscore and digits.

**Comment by twMat** [comment]
@sukima 

You see the difference if you type in the following two

$:/.foobar

$:/_foobar

The first is recognized, the second isn't. People insert the point or the underscore to make e.g all their own system tiddlers list together.

@Jermolene - great.

**Comment by sukima** [comment]
Oh I guess because the auto linking doesn't work for terms that are not CamelCased I just always got into the practice of putting brackets around all my links.
