### ISSUE TITLE
Extend camelcase linkify to include the prefixing @ (as in @JeremyRuston) 

### ISSUE THREAD

**Issue by twMat** [Jermolene/TiddlyWiki5#1878]
If we are to continue with CamelCase automatic linkification, then;

I propose to include the @ character in automatic recognition of wikilinks (CamelCases) so that all characters in `@JeremyRuston` are included. This is problematic in lists where you cannot always manually add brackets.

**Comment by Jermolene** [comment]
I don't see the difference between this and #1879

**Comment by twMat** [comment]
Hm, my mistake (based on the my false belief that CamelCase autolinking happened to a word with the two or more capital letters placed *anywhere* like in **x**JeremyRuston... which is why I thought @JeremyRuston should work likewise. Sorry for confusion. Issue closed.
