### ISSUE TITLE
Introduce parser rule for @mentions

### ISSUE THREAD

**Issue by twMat** [Jermolene/TiddlyWiki5#1879]
Considering how the @ character has become a de facto standard to call someones attention and how @ is often a case where people probably _expect_ linkification, I propose we consider to make it automatially create wikilinks, i.e so that `@Jeremy` would linkify automatically, unless prefixed with `~`.

It is very reasonable to assume that we will want the TWederation to behave similar to githibs when typing @ in text, i.e with popup name list so this is perhaps a step in this direction.

**Comment by Jermolene** [comment]
Hi @twMat this functionality was added to TiddlySpace via a plugin. I think we'd likely take the same approach with TW5, rather than adding it to the core.

**Comment by twMat** [comment]
>plugin

Assuming "plugin" is still the opinion, I'm closing. I do still think the OP is a good idea (...particularly that I'm now again working with Jed on TWederation where I think "attention" will be a big deal.)
