### ISSUE TITLE
CamelCase links shouldn't nest inside other links

### ISSUE THREAD

**Issue by twMat** [Jermolene/TiddlyWiki5#1880]
`<$link to="foo">Linking in WikiText</$link>`

..produces a link to foo... but with an "internal" link to WikiText. I.e if you click on the word WikiText you come to tiddler WikiText but if you click elsewhere on the link you come to foo.

(Yet another problem with CamelCase autolinking, btw)

**Comment by felixhayashi** [comment]
This happend soo often to me. I highly agree that wikilink should not happen inside a link widget. It's not nice to always use the view widget inside the link widget to prevent autolinking.

**Comment by twMat** [comment]
> use the view widget inside the link widget to prevent autolinking.

Aha, I did not know this was how to circumvent it! Good at least it's possible.

**Comment by Jermolene** [comment]
Hmmm we could fix the original problem by making `<$link>` also set the `tv-wikilinks` variable to "no" for the scope of its children. The trouble is that I think there are situations where you want to be able to nest links.

```
<$link to="foo"><$set name="tv-wikilinks" value="no">Linking in WikiText</$set></$link>
```

One could create a macro that encapsulates the link and set widgets.

**Comment by twMat** [comment]
>The trouble is that I think there are situations where you want to be able to nest links.

I have a hard time imagining this. Can you give an example? 

For those special and, presumably, rare occasions, maybe one could split up the link into discrete parts and link accordingly (and position them together)?

**Comment by Jermolene** [comment]
@twMat imagine something like a Trello board: you want to be able to handle clicks on the cards themselves, and on the board that contains them.

**Comment by twMat** [comment]
Aha, a case where the visiting clicker //does not assume// that the inner link should open the outer. Critical difference, IMO. But I agree it might make sense there - even if, for that particular case, you probably still deal with a lot of divs and stuff so you would/could handle it in more conventional(?) ways.

Anyway, for the more everyday TW use I think my OP would simplify a lot and I assume it's an issue everyone stumbles over when they face it first. .

**Comment by Jermolene** [comment]
> Anyway, for the more everyday TW use I think my OP would simplify a lot and I assume it's an issue everyone stumbles over when they face it first. .

I'm not sure. It's a lot of additional complexity and special features just to simplify an edge case. The solution I proposed would prevent camelcase links within a `<$link>` widget but wouldn't prevent other wikitext from being processed; I think that that might seem confusing to users.

**Comment by twMat** [comment]
> It's a lot of additional complexity and special features just to simplify an edge case

What is it you call an "edge case"? It makes me wonder if maybe I've done something else wrong to find this a rather common occurence, as does appearently @felixhayashi . The problem arises, for me, in common `$list` proceedings where I transclude the title. As titles, it is reasonable to want them presented as links and, unless I'm satisfied with `<<list-links>>` then I must use `$link`.
Is there a better way?

>The solution I proposed would prevent camelcase links within a <$link> widget but wouldn't prevent other wikitext from being processed; I think that that might seem confusing to users.

As a non-expert I would (naively) assume the WikiLink was "engulfed" by the surrounding link and think nothing more of it, unless I needed such nested links.... which, to me, seems like the edge case.

**Comment by felixhayashi** [comment]
> The problem arises, for me, in common $list proceedings where I transclude the title.

I agree with Mat. Same for me, it more than once irritated me. But I can totally understand that @Jermolene doesn't want to add extra complexity for this.

**Comment by Jermolene** [comment]
Ah, it's just dawned on me where you're going wrong: you're using `<<variable>>` to render the index of a list. The problem is that the double angle brackets syntax always wikifies the content of the variable.

It's better to use either the `<$text>` or `<$view>` widgets, which allow you to render the variable value without wikifying it.

It's a long time since we discussed it, but I'd like to introduce a shorthand syntax for rendering a variable without wikification.

**Comment by tobibeer** [comment]
Seeing as how the solution is to use the `<$text>` or  `<$view>` widgets, should this be closed?

**Comment by twMat** [comment]
After a bit of back tracking here is a *for the record* of what happened in my case;

I initially used `<$link to="$tid$">$tid$</$link>`

Likely after @felixhayashi 's first post above, I added a view widget around this - but partly misunderstanding things like so:
`<$link to="$tid$"><$view field="title" format="text">$tid$</$view></$link>`

...which explains (for myself now) why I never quite understood @Jermolene 's answer about `<<variable>>`.

Eventually, after my regular trials with utf-8 permutations, I hit the magic letter combo:
`<$link to="$tid$"><$view tiddler="$tid$" field="title" format="text"></$view></$link>`

So, yup, closing this up now.

**Comment by tobibeer** [comment]
@twMat, allow me to remove unnessessary redundancies:

`<$link to="$tid$"><$view field="title"/></$link>`

**Comment by twMat** [comment]
><$link to="$tid$"><$view field="title"/></$link>

Actually not sure this is correct. I found I needed to specify which tiddler also for the viewwidget (or it took the current one) and, at least in docs, it doesn't explicitly say that "text" is default for format - not to be confused with the text *field* being the default field.

**Comment by tobibeer** [comment]
> I found I needed to specify which tiddler 

Mhhh, I could have sworn it was not necessary. You are right, the way I wrote it would make a link to the tiddler you're currently in.

So, yes...

`<$link to="$tid$"><$view tiddler="$tid$" field="title"/></$link>`
