### ISSUE TITLE
json data tiddlers included in tiddlywiki.files corrupted

### ISSUE THREAD

**Issue by buggyj** [Jermolene/TiddlyWiki5#1882]
In my plugins I use json data tiddlers eg I have a tiddlywiki.files 

`
{
	"tiddlers": [
		{

			"file": "styles.json",
			"fields": {
				"type": "application/json",
				"title": "$:/plugins/bj/visualeditor/styles.json",
				"module-type": "library"
			}
		},
		{
			"file": "config.json",
			"fields": {
				"type": "application/json",
				"title": "$:/plugins/bj/visualeditor/config.json",
				"module-type": "library"
			}
		},
		{
			"file": "verbatim.json",
			"fields": {
				"type": "application/json",
				"title": "$:/plugins/bj/visualeditor/verbatim.json",
				"module-type": "library"
			}
		}
	]
}
`
With 5.1.9 these are corrupted. It seem that this commit 53072dd7aa635bd0010d1a6af90d2b2c971353b7
causes the json tiddlers to be parsed via the deserializeTiddlers() method

This issue is stopping me from upgrading my plugins

**Comment by Jermolene** [comment]
Hi @buggyj 

OK so we need to refine the `tiddlywiki.files` format to distinguish between "raw" files and tiddler files.

Perhaps we could use `"file": "blah.json"` for a raw file, and `"tiddlerfile": "blah.json"` for a file that is to be passed through deserializeTiddlers() method.

**Comment by buggyj** [comment]
@Jermolene ,
seems to be a solution

**Comment by Jermolene** [comment]
This is fixed in 73210a7b8c52e79dbebbe78f1b6e47a7c4f6b7d6 and earlier commits
