### ISSUE TITLE
Reversing sort in List doesn't work?

### ISSUE THREAD

**Issue by girvo** [Jermolene/TiddlyWiki5#1888]
Hi all,

Love TiddlyWiki. I used to use it, years ago, but stopped because it didn't age particularly well, so I'm super impressed with TW5 and the Node.js server -- absolutely amazing work.

Using the `<$list/>` widget, I'm attempting to reverse the `sort` order, however it doesn't appear to work.

The exact usage in Wiki syntax I'm attempting to use is this:

```
! Journal
<$list filter="[tag[Journal]sort[-created]]" />
```

However the "reverse" modifier on the filter (`-`) merely makes the sort no longer actually sort, rather than reversing the order. Has the syntax changed?

Cheers.

**Comment by twMat** [comment]
Changed from "years ago" (=TWC), sure, but have you looked in the documentation? 

[Check this out.](http://tiddlywiki.com/#sort%20Operator%20(Examples):%5B%5Bsort%20Operator%5D%5D%20%5B%5Bsort%20Operator%20(Examples)%5D%5D)

**Comment by girvo** [comment]
I did look in the docs, but only came across "Classic" documentation unfortunately. That's brilliant, thanks so much :)
