### ISSUE TITLE
[tw.com] Doc; missing transclusion in doc on StartupMechanism

### ISSUE THREAD

**Issue by twMat** [Jermolene/TiddlyWiki5#1889]
Missing transclusion at bottom of text in [StartupMechanism](http://tiddlywiki.com/#StartupMechanism)

**Comment by sukima** [comment]
To clarify: [`StartupMechanism.tid` line 30](https://github.com/Jermolene/TiddlyWiki5/blob/master/editions/tw5.com/tiddlers/mechanisms/StartupMechanism.tid#L30) references `{{Startup Modules.svg}}` but the [`Startup Modules.svg`](https://github.com/Jermolene/TiddlyWiki5/blob/master/editions/dev/tiddlers/images/Startup%20Modules.svg) tiddler is only available in the **dev** edition.

**Comment by twMat** [comment]
Yes, thanks @sukima

**Comment by Jermolene** [comment]
I think that StartupMechanism should have been moved from the main site to /dev.
