### ISSUE TITLE
Disable keyboard shortcuts

### ISSUE THREAD

**Issue by c0ffeeartc** [Jermolene/TiddlyWiki5#1892]
Hello, I'm using vimperator plugin and site shortcuts get in the way (Esc when editing).
Is there a way to disable them ?

**Comment by danielo515** [comment]
What is vimperator plugin? Could you point to a demo page?

**Comment by c0ffeeartc** [comment]
Sure:
https://addons.mozilla.org/en-us/firefox/addon/vimperator/
https://github.com/vimperator/vimperator-labs

It's for vim-like behaviour for Firefox.

**Comment by Jermolene** [comment]
Hi @c0ffeeartc to disable keyboard shortcuts, set the two tiddlers $:/config/shortcuts/cancel-edit-tiddler and $:/config/shortcuts/save-tiddler to empty.

**Comment by c0ffeeartc** [comment]
Thank you.


I couldn't/don't know how to find `$:/config/shortcuts/cancel-edit-tiddler` and `$:/config/shortcuts/save-tiddler` or get up to date version with them.
But in plain text editor changing `index.html`

```
;currentTiddler&gt;&gt;&gt;\n&lt;$keyboard key=\&quot;escape\&quot; message=\&quot;tm-cancel-tiddler\&quot;
```
to
```
;currentTiddler&gt;&gt;&gt;\n&lt;$keyboard key=\&quot;\&quot; message=\&quot;tm-cancel-tiddler\&quot;
```
disabled the key

**Comment by Jermolene** [comment]
Apologies, the fix will be part of 5.0.10, which will be released in the next few weeks. Your workaround will be fine until then.

**Comment by pmario** [comment]
5.0.10?

**Comment by Jermolene** [comment]
Ahem, thanks @pmario, I meant 5.1.10.
