### ISSUE TITLE
the modal blur makes everything much slower

### ISSUE THREAD

**Issue by felixhayashi** [Jermolene/TiddlyWiki5#1893]
Hi @Jermolene 

Since a long time I noticed that everything got slower when modals are displayed. What is everything? Entering text, widget calculations, scrolling, selecting text... everything. tested on several machines with both FF and Chrome.

Now I did some thorough investigation and I noticed that when I disabling blur, everything speeds up by many times: no lagging, no delay.

Doing a bit of research on this it turns out that blur is recognized as a real performance killer:

E.g.

<<<
It's supported on Chrome, but it comes with a big performance penalty when used on the whole page.
<<< http://stackoverflow.com/questions/371209/full-page-blur-in-css

<<<
Has anyone tried to do this with a full screen background image .. there is a serious reduction in Chrome performance.
<<< http://stackoverflow.com/questions/371209/full-page-blur-in-css

<<<
Results were staggering: the performance drop was so extreme that I’m not sure we could implement the blur effect at the scale of a full page (which was our case). Scrolling was slow, and even typing in form fields felt sluggish.
<<< http://blog.kaelig.fr/post/47025488367/css-filters-in-the-real-world

**So I highly suggest to replace the blur with a simple background rgba opacity!**

-Felix

P.S. performance is also going down for also other grafically intense CSS3 features.

**Comment by Jermolene** [comment]
Hi @felixhayashi I'd be happy to revert to a simple translucent background.

**Comment by felixhayashi** [comment]
Many thanks @Jermolene!

**Comment by danielo515** [comment]
Thanks god the blur have been removed! I thought several times about asking for this. Many thanks. This was specially noticeable on mobile.

**Comment by felixhayashi** [comment]
Hola @danielo515,

yes, until recently, I didn't even know it was the blur that was causing it. I was going crazy…

-Felix
