### ISSUE TITLE
replace filter "recent" with "days"

### ISSUE THREAD

**Issue by rubaboo** [Jermolene/TiddlyWiki5#1895]
@Jermolene,

Would like to hear your thoughts on replacing "recent" filter with "days", as suggested by @felixhayashi at #1863.

Here are some use cases to illustrate "days" filter:

| usage | meaning |
| --- | --- |
| days[-7] | modified within last 7 days |
| days:due[7] | due (a field) within 7 days from now |
| !days[-7] | modified more than 7 days ago |
| !days:due[7] | due in more than 7 days from now |

If you like the idea, could you keep "recent" in pre-release for now, I am not sure what your timing is for 5.1.10.

@felixhayashi , you are welcome to pick it up, I don't know when I'll get a chance to implement this. 

Thanks!

**Comment by felixhayashi** [comment]
Thanks @nameanyone for offering me to work on the code! Sadly, I am also short of time at the moment. In any case, I much favour the days filter and thanks for creating this issue.

> Second thoughts: how do I decide if negation is worth implementing? The same effect can be achieved by a separate Filter Run with a minus sign.

I still think including the minus sign syntax is a nice shortcut...

**Comment by nameanyone** [comment]
Ok, check it out, let me know what you think. I'll post to the forum as well.

https://copy.com/pO624sG8Y6TRVAjP

**Comment by felixhayashi** [comment]
Hi @nameanyone 

Great job on the filter, I like it very much!

– Plus I really enjoy all the crazy enhancements you implemented in your wiki!

Especially…

* …the collapse tiddler thingy is what I always wanted. Extremely smart basing it on "hide-body", I would have used css but you solution is much nicer.
* …display tiddlers in two column is a great feature. I think Tiddlywiki could actually benefit from another storyview called "wall" which puts all tiddlers in tiling style (http://www.the-webdesign.net/wp-content/uploads/2013/12/naldz-design-full-screen-website.jpg). As a remark, I think the two column style would work better if the tiddler frames have equal size when using "float".
* Also you also put the search field into a tab, which I much favour. Maybe checkout http://spangenhelm.github.io/TW5-EnhancedSearchResults.
* …the "stretch editor" vs. scrolling editor, very nice.

-Felix

**Comment by nameanyone** [comment]
Submitted #1898. Thank you @felixhayashi for the idea. I'm really happy with this one. As you said, it has much potential for all sorts of useful lists: old, overdue, recent, upcoming, et cetera.

**Comment by felixhayashi** [comment]
Me too, again much thanks for implementing this!

**Comment by tobibeer** [comment]
> I really enjoy all the crazy enhancements you implemented in your wiki!

Curiosity has me asking where to find it. ;-)
