### ISSUE TITLE
TiddlyWiki translation file in Korean, Korea Republic (ko-KR)

### ISSUE THREAD

**Issue by araname** [Jermolene/TiddlyWiki5#1896]
I translated tiddlywiki in Korean, Korea Republic (ko-KR).

https://drive.google.com/file/d/0B7MoHh-LPDuCeW0tQm9Mb1VQYXpCMzk4M2UyRFhJeEF0cTJJ/view

**Comment by pmario** [comment]
Why did you close the issue?
