### ISSUE TITLE
After closing a modal, the wiki is significantly slowed down

### ISSUE THREAD

**Issue by felixhayashi** [Jermolene/TiddlyWiki5#1897]
Hi @Jermolene,

there is another modal issue with TW5 causing TiddlyWiki to become all laggy and stagnant after the modal is closed. 

This issue is critically important to me since I highly depend on modals for TiddlyMap.

**I would highly appreciate if you could have a look at it**:
## The problem

_Sidenote: (I am aware of this problem since 5.1.6 I believe, but never realized it occurs because of clicking actions)_
1. When a modal is opened
2. and a user clicks at a non-widget place (meaning not a button or a textfield or else) but e.g. on a plain text inside the dialog or e.g. on the darkend surrounding (outside) of the dialog,
3. and then immediately clicks (without clicking anywhere else) a button (in the footer) that closes the dialog (per default it is "cancel")
4. and then without clicking anywhere scrolls the river
5. everything is stagnant
   6 until he/she clicks somewhere (on a non-widget place) eg. on a tiddler frame.

**Video:** https://youtu.be/q_4O7X3DM1M

The video shows how I open http://tiddlywiki.com and go to the modal demo "WidgetMessage: tm-modal" then I open a modal click somewhere, close it and do scrolling which is laggy! Then I click somewhere and it works again! The problem is, if I click on a widget area (e.g. into a textfield or TiddlyMap), it stays stagnant!

Many thanks
-Felix

**Comment by Jermolene** [comment]
Hi @felixhayashi apologies for the late response. What browser are you using?

**Comment by felixhayashi** [comment]
Hi @Jermolene 

Much thanks for responding!

I am using **Firefox** and **Chrome** (both **latest versions**, but as said, this problem also occured with previous versions). I tested it on a **laptop and on a dektop pc**. On **Linux** Mint and on **Windows 7**.

I have no clue what is causing this but in my tests, it clearly shows that the stagnation occurs when the timeout is executed (I increased the value for `duration` to five seconds, and after that time, the function was executed and it became stagnant – until I clicked somewhere else, but not on a widget(!)).

```javascript
window.setTimeout(function() {
  if(wrapper.parentNode) {
    // Remove the modal message from the DOM
    document.body.removeChild(wrapper);
  }
},duration);
```

-Felix

**Comment by Jermolene** [comment]
Hi @felixhayashi strange: I can't duplicate the problem with http://tiddlywiki.com on my laptop with either Chrome or Firefox. That makes me wonder if it is a graphics card problem...

Do you see the problem with the current prerelease?

**Comment by felixhayashi** [comment]
> I can't duplicate the problem with http://tiddlywiki.com on my laptop

Yes, very strange, I just tested the problem description again on two different Laptops (one windows, one linux) and one Desktop PC using **tiddlywiki.com** (linux).

**But I have to correct myself**, it does not seem to occur in firefox (anymore; maybe something happened in FF 39 or I mistakenly thought it also occurs there). However in Chrome it happens. This speaks against a graphics card problem. As for the power, the graphic card in my PC is quite strong... But apart from the graphic card, my computers are rather medium (high end from 6 years ago). Maybe a modern powerful machine/laptop is too strong to show stagnation effects?

> Do you see the problem with the current prerelease?

Yes, also just for Chrome. It seems that chrome doesn't like something about the way the wrapper and its children are removed but it doesn't really make sense.

I'll test it on more computers the next days and report back.

---

Sidenote: How nice @Jermolene, you actually added a "fold unfold this tiddler" toolbar button!

**Comment by Jermolene** [comment]
> Sidenote: How nice @Jermolene, you actually added a "fold unfold this tiddler" toolbar button!

Thanks! It's one of those things that I'd been meaning to do for a while.

**Comment by Jermolene** [comment]
@felixhayashi it may be worth looking to see what you can see in Chrome dev tools - there's a view that shows you the frame rate, which I guess should let you see the sluggish scrolling, and perhaps identify what's going on to consume the time.

**Comment by felixhayashi** [comment]
Sorry for the late response @Jermolene 

Great idea, below are the results. If you look at the detailed screenshots you'll see that that the number of listeners jumps up from 237 to 2051(!!!) also heap size doubles, same for the number of nodes!

Super strange.

### Overview

![2015-08-16 13 32 17](https://cloud.githubusercontent.com/assets/4307137/9293060/d4be76be-441b-11e5-8ffd-a68fc16668f1.png)

### Details of the point where I close the modal

You can see that the number of listeners jumps up from 237 to 2051(!!!) also heap size doubles, same for the number of nodes!

![2015-08-16 13 34 51](https://cloud.githubusercontent.com/assets/4307137/9293066/31cf754c-441c-11e5-9a21-408ab274d8a5.png)

![2015-08-16 13 35 06](https://cloud.githubusercontent.com/assets/4307137/9293067/35937386-441c-11e5-8b4e-d39a7ba7af1c.png)

**Comment by felixhayashi** [comment]
@Jermolene 

I found somebody with the same problem from a totally unrelated scenario!!

https://code.google.com/p/chromium/issues/detail?id=507863

He also says

> I think the important thing to note that it depends on a long sequence of events. The large inline script doesn't degrade performance in isolation. Removing the element does not necessarily cause it: it only happens in event handler. And it is WEIRD that clicking the page "fixes" the slowdown.

This means: **I am not crazy** This bug is real.

**Comment by felixhayashi** [comment]
Chromium guys confirmed this: 

> For whatever reason in the slow case we end up spending a ton of time in LayoutView::hitTest for EventHandler.cpp/scheduleHoverStateUpdate and then ThreadProxy::BeginMainFrame is stuck in a mode where its taking a ton of time. As the reporter states, clicking gets us out of the bad state and frames are fast again. I've attached a trace.

I'll leave this issue open to report on it.

**Comment by Jermolene** [comment]
Wow, interesting, thanks the research @felixhayashi

**Comment by felixhayashi** [comment]
Hi @Jermolene,
seems the chrome bug has been fixed. Will close this now.
Best wishes!
Felix
