### ISSUE TITLE
Add class "transcluded" to transcluded content's wrapping element

### ISSUE THREAD

**Issue by nameanyone** [Jermolene/TiddlyWiki5#1899]
Currently there is no way to distinguish content that has been transcluded.

**Comment by pmario** [comment]
Yes, that's by design, but you can use `{{tiddler||template}}` to us a specific template, that fits your need.

**Comment by pmario** [comment]
The existing TW page layout already has the so called "divitis". If you look at the number of stacked elements, this is already a big problem for custom styling. IMO there need to be less elements, not more.

**Comment by Jermolene** [comment]
See my comment on #1900

**Comment by nameanyone** [comment]
Sorry, it was late at night I posted this :). I see now it doesn't make sense. I wasn't proposing to add another element. I just looked at a transclusion that was inside a `<p>`, and that fooled me. But the `<p>` was generated by empty lines around the transclusion, not by the TranscludeWidget.

**Comment by Jermolene** [comment]
No problem @nameanyone this is a pretty mind-bending area.
