### ISSUE TITLE
In plugin library, for each plugins dropdown info, activate first tab by default if there is no readme.

### ISSUE THREAD

**Issue by twMat** [Jermolene/TiddlyWiki5#1902]
In the plugin library, if you click the arrow for a plugin you see its "list" of tabs, defaulting to display "readme". If there is no "readme" but instead some other tiddler intended to be displayed, it doesn't activate this by default, resulting in only a gray (unativated) tab and no text.

I propose the first tab is _activated_ by default if there is no "readme". It is not obvious that a user should click on a single gray tab.

**Comment by Jermolene** [comment]
I'd accept a pull request to make this change if it was simple enough (I don't know how it could be done off the top of my head).

On the other hand, the present arrangement does serve to encourage plugin authors to provide a readme tiddler, which I think is a useful convention.

**Comment by twMat** [comment]
>I'd accept a pull ...

I'll see what I can find.

>On the other hand, the present arrangement does serve to encourage plugin authors to provide a readme tiddler, which I think is a useful convention.

Yes, even if I noted that it could not be a **R**eadme, which forced me to break my naming convention.

**Comment by twMat** [comment]
Ok, here's an idea that is unpolished because I must know if the approach is at all acceptable.

Tiddler **$:/core/ui/ControlPanel/Plugins**

states

```
<$macrocall $name="tabs" state=<<tabs-state-macro>> 
   tabsList={{!!list}} default="readme" template="$:/core/ui/PluginInfo"/>
```

I propose exchanging `default="readme"` to use 

```
default=<$list filter="[{!!list}+suffix[eadme] {!!list} +nth[1]]"/>
```

Yes, I'm botching the syntax but I'm just talking overall idea now. Because ot the botchery, I'd better explain it tho; The filter first searches for something with suffix **e**adme which catches both "readme" and "Readme" (and more). The full list is appended again. Whatever item comes first is returned, if any. 

Reasonable?

**Comment by Jermolene** [comment]
> Yes, even if I noted that it could not be a Readme, which forced me to break my naming convention

The core naming convention for plugin information tabs is to use lower case titles. Is that too restrictive?

>  The filter first searches for something with suffix eadme which catches both "readme" and "Readme" (and more)

I'm not superkeen on going to all this trouble just to make the user put up with inconsistent capitalisation of information tabs between different plugins. Can you explain the motivation a bit more?

**Comment by twMat** [comment]
In answer to both your questions;

The OP is about the problem that the *only* content displayed as a, by default, *open* tab is "readme". If the user doesn't have exactly "readme" then NO tab is open and the user sees a row of gray/closed tabs. At that state it is not even clear one is supposed to click on them (grayed out fields in menus often mean "blocked".)

My proposal is to at least always let *some* tab open by default. The proposed solution makes "eadme" be the first choice for this and if there isn't any such, then anything works and it takes the first element in the list field.

...

IMO it is super important for the spreading of TW the project that it is as painless as possible for people to *bother* to turn their private solutions into plugins and share them. Especially if we want people who don't really care about TW *per se* to bother to make/share "niche application plugins". Now, the tabs brought up in this thread are not "super important" but they are a small piece in this because an open tab is a possible place for the plugin creator to promote further things/creations.

**Comment by Jermolene** [comment]
> The OP is about the problem that the only content displayed as a, by default, open tab is "readme". If the user doesn't have exactly "readme" then NO tab is open and the user sees a row of gray/closed tabs.

But isn't the problem here that plugins without a "readme" information tab are unfriendly to the user? So all good plugins should have a standard "readme" tab. Why should the core adapt to plugins that don't conform to the conventions, but instead go out of their way to use a non-standard name? Is there a good reason why a plugin might not have a "readme" tab?

**Comment by twMat** [comment]
So if there is no tab titled readme, then no tab "deserves" to get displayed by default?

Besides, are there any official guidelines for meta-data for plugins mentioning *readme*? There are plugins in standard distro that don't have a "readme", namely the themes. And I notice that none(?) of the standard distro plugins have a *source* field, wich IMO is important. In TiddlySpace, the equivalent to "readme" was - I believe - a tiddler titled *About*. IMO, a "readme" file might be a standard... but *not here* in our context with tabs. But, regardless, to conclude that *no* tab should  open by default then doesn't make sense to me.

If we want to foster people to use "readme" specifically, I think it would make more sense at the stage of *creating* the plugin. I guess the only ready made tool for this currently is @Drakor (Andreas Hahn)'s Tinka. If this was adopted into something official, the plugin "format" could probably be controlled to a much greater extent, prompting for a readme and even checking that the code  follows desired "rules". Plus, an official packer could offer additional stuff like components for updating mechanisms, statistics, etc.

**Comment by Jermolene** [comment]
> So if there is no tab titled readme, then no tab "deserves" to get displayed by default?

We're already in the situation where we've got plugins that don't have any information tabs. We can only fix that by actually adding a readme tab.

Your proposal is to cope with the situation where a plugin provides at least one information tab, but none of them are titled "readme". Why would we want to cater for such a plugin? Surely that plugin should just comply with the convention and provide a "readme".

>  IMO, a "readme" file might be a standard... but not here in our context with tabs

Is your concern here that "readme" was the wrong convention to pick? Why?

> If we want to foster people to use "readme" specifically, I think it would make more sense at the stage of creating the plugin

Yes, that's what's normally done: wizards and getting started templates.

> If this was adopted into something official, the plugin "format" could probably be controlled to a much greater extent, prompting for a readme and even checking that the code follows desired "rules"

I think you've got that the wrong way around. The place to check for plugins conforming to rules is when they are submitted to the plugin library, not when they are first created.

**Comment by twMat** [comment]
>Is your concern here that "readme" was the wrong convention to pick? Why?

AFAICT, TW plugins are limited to be used *only* in the TW environment. Why should we enforce a strict "readme convention" inside our own yard? Am I missing something?

I look at it as an end user - and **IMO the plugin creation process should be brought *as close as possible* to the end user** because I believe plugins are super important for the spreading of the TW project. The plugin creator, or I should say the *potential* plugin creator, should face as few obstacles as possible and enforcing a *readme* seems just unnecessary given the context. Or?

I'd compare it to setting *default tiddlers*(!) This is a front end / end user matter, and of course the user should be allowed to set these himself. BTW, we decided not to use *readme* as the default tiddler.


...

>The place to check for plugins conforming to rules is when they are submitted to the plugin library, not when they are first created.

Of course they must be checked at submit stage. But a plugin creator would obviously prefer to know already during creation that "this will not be accepted because" so he can correct it at that stage where it is easier. A bit like going someplace and hearing "Oh, you need X to enter". I would much rather hear this at home so I can pocket the X.

But one could also imagine *different* plugin library rules for different situations. When the TWederation gets going, I can imagine that "plugins for the X community TW must fulfill Y". It would simplify things if a "plugin packer" could check the rules (perhaps using a template provided from the X community) to guide the plugin crator *as* he is creating the plugin.

...

Hm, my wild argumentation makes it seem as if this tab issue is a super big deal which it is not. But IMO the underlying point to make plugin creation an end user matter *is* a super big deal.

**Comment by twMat** [comment]
I note  it is now possible to have other tabs open by default.
Thank you!
