### ISSUE TITLE
keyboard support when creating tiddles?

### ISSUE THREAD

**Issue by ipsod** [Jermolene/TiddlyWiki5#1907]
Is TW keyboard support as bad as it seems?  When trying to add tags or fields, I actually have to touch a mouse.  Is the user actually supposed to have to touch their mouse and left-click it after typing each tag?

**Comment by pmario** [comment]
I think feedback is very valuable, if we can act on it. .. but to act on real feedback there are some major points needed. 

 - Describe your problem
 - Describe, what you expect AND how it will improve TW in general. 

May be someone, that is interested in your point of view, may try to fix it. 

Looking at your initial questions, my answers are: yes, yes, and yes. .... and do you feel better now?

If you could describe what you expect, we could start to talk about possibilities to improve keyboard handling. But the main problem is, that the browsers give you very limited possibilities out of the box. ...

**Comment by twMat** [comment]
Hi @ipsod ,
fellow @danielo515 has created the [keyboard-snippets](http://braintest.tiddlyspot.com/#keyboard-snippets) plugin. I'm only just beginning to use it so I can't give a fair evaluation yet but I recommend you try it out (+ give feedback to @danielo515 )

**Comment by ipsod** [comment]
That looks great, I'll give it a try.  Thank you, @twMat!

**Comment by ipsod** [comment]
The keyboard-snippets plugin doesn't seem to do much for anything but the main text-editing box.

I don't know how hard this would be without jQuery, or if using jQuery is an option, but I know how I'd fix tag-creation with jQuery.

One option would be to have an onChange event for the tag box that simply looked for a comma.  If there is a comma, it creates the tag, opens up a new tag field, and sets focus on the tag field.  Another option would be to have an onFocus event that starts watching keypresses for {enter}, and when it is pressed, then create the tag, open a new tag field, and set focus on the new tag field.

**Comment by pmario** [comment]
@ipsod 
this may be an option too: https://groups.google.com/d/msg/tiddlywiki/Z860-Yfspcc/rwVepjhhKysJ

>1. Visit tiddlywiki.com
2. Click the "+" in the sidebar to create a new tiddler
3. Give it the tag $:/tags/EditTemplate
4. Copy the following content into the text field

>Tags: <$edit-text field="tags" tag="input" class="tc-edit-texteditor"/>

>5. Clink the tick to store the tiddler
6. Edit the tiddler HelloThere
7. Look for the new "tags" field at the bottom of the tiddler
8. Note that you'll need to wrap any tags containing spaces with double square brackets, [[like this]].

**Comment by danielo515** [comment]
Hello,
Thanks @twMat for mentioning my plugin, but as @ipsod said, at it's current state is not of much help on this scenario. I have to admit that is a bit frustrating to have to use the mouse to accept a tag entry. I'm open to extend the keyboard plugin to accept some more complex functionality and the ability to modify some more tiddler fields other than text field.

**Comment by tobibeer** [comment]
:+1: 

I'm all for a much more keyboard centric editing experience. All this mouse-moving is highly inefficient. This also applies when wanting to tab through the controls ...hindered by something like the add-tag popup.

**Comment by BurningTreeC** [comment]
@Jermolene - This issue dates back to 2015 and I believe it's solved with the coming release

**Comment by Jermolene** [comment]
Thanks @BurningTreeC
