### ISSUE TITLE
Static TW: incorrect display, possibly from ScrollableWidget

### ISSUE THREAD

**Issue by twMat** [Jermolene/TiddlyWiki5#1910]
In loading  http://tiddlywiki.com/alltiddlers.html#search%20Operator

i.e the **static** version of tw.com, there is "text appearing between tiddlers". I think it may stem from the tiddler **ScrollableWidget** tiddler there (just above the linked to tiddler). I'm guessing it's not a bug but more something that is disabled in static resulting in the content not being contained to e.g scrollboxes the way it should.

It seems to be a minor problem, perhaps limited to that context, but just maybe it has other consequences.

**Comment by tobibeer** [comment]
This should do...

```
.tc-scrollable-demo {
    overflow:scroll;
}
```

**Comment by twMat** [comment]
#1944 seems deleted and original problem remains. I updated the link to one more clearly illustrating the problem; note the text appearing between the tiddlers.

**Comment by Jermolene** [comment]
Thanks @twMat
