### ISSUE TITLE
Translators edition:  problem when single tiddler is outputed

### ISSUE THREAD

**Issue by araname** [Jermolene/TiddlyWiki5#1915]
Ignore CamelCase syntex is removed in some tiddlers, like GettingStarted.tid, SiteTitle.tid if command build output-files.

**Comment by Jermolene** [comment]
Hi @araname my apologies, but can you provide some further information? I think you are referring to the translators edition, and to the `~` syntax for suppressing CamelCase links, but I don't quite understand what problem you are reporting. It would be helpful if you could list the steps to reproduce the problem, and explain what happened and what you expected to happen.

**Comment by araname** [comment]
In en-GB translation,
1. enter tiddlywiki translators --init translators 
2. enter tiddlywiki translators --server
3. save wiki
4. enter tiddlywiki translators --verbose --unpackplugin $:/languages/en-GB --load tiddlywiki.html --build output-files
5. `~` syntex is removed in 'GettingStarted.tid' and 'SiteTitle.tid'. Also contents in 'tc-control-panel' are replaced with default tiddlers list, and link of 'control panel' is removed.

**Comment by Jermolene** [comment]
Hi @araname thank you, that's very helpful.

I believe that the problem occurs if a multiline tiddler like GettingStarted is edited using the single-line editor. Doing so removes the line breaks, resulting in the problems that you describe.

The fix would be to disable the multi-line editing option, either for all tiddlers, or just those that have multi-line content.

**Comment by araname** [comment]
This bug is resolved with pull request #2433.
