### ISSUE TITLE
Does not save, have tried everything 

### ISSUE THREAD

**Issue by wallyreport** [Jermolene/TiddlyWiki5#1916]
I am running debian, I usually use Google Chrome Version 41.0.2272.76 (64-bit).

I have also tried Midori, and Iceweasel 31.5 (Iceweasel is Firefox).

I have been googling, and looking through these forums. Apparently this is long-time problem with tiddlywiki. 

I have tried saving in many different ways. No matter what, when I reload the file, my changes are gone. I have right-clicking and save as, I have tried "save page" from the browser. I have tried the circled check mark. No matter what, the wiki will not save.

**Comment by Jermolene** [comment]
Hi @walterbyrd. I'm sorry you've been having problems. I've posted a detailed answer to your post on the TiddlyWiki Google Group:

https://groups.google.com/d/topic/tiddlywiki/O-k7iVyN5MQ/discussion

**Comment by inmysocks** [comment]
@Jermolene I believe that this issue should probably be closed, both because changes to saving made since it was created and according to the post on google groups the issue was resolved.

**Comment by pmario** [comment]
@wallyreport please close the issue, if it worked out for you. [GettingStarted](https://tiddlywiki.com/#GettingStarted) lists all the possible save-mechanisms

**Comment by Jermolene** [comment]
Thanks @pmario
