### ISSUE TITLE
Update normalize.css to the latest version

### ISSUE THREAD

**Issue by twMat** [Jermolene/TiddlyWiki5#1918]
Considering the "funny" differences between browsers, is there any direct code implemented to make a TW look the same in all browsers?

If not, maybe we might consider [normalize.css](http://necolas.github.io/normalize.css/). I downloaded it just to see it's file size and appears to be about 40kb unzipped (i.e very small relative to *empty* which is about 1.4 MB and seems over all very attractive given who developed it and who uses it, license etc.

**Comment by Jermolene** [comment]
Hi @twMat funnily enough, TiddlyWiki already includes normalize.css in `$:/themes/tiddlywiki/vanilla/reset`:

http://tiddlywiki.com/#%24%3A%2Fthemes%2Ftiddlywiki%2Fvanilla%2Freset

That tiddler is transcluded by the main vanilla stylesheet.

It looks like normalize.css has had a couple of minor updates, so it might be worth upgrading. I've amended the ticket title accordingly.

**Comment by twMat** [comment]
Well then, not much more to say, hehe! Case closed!
Thank you!
