### ISSUE TITLE
Extend link widget to link to a filtered list

### ISSUE THREAD

**Issue by Jermolene** [Jermolene/TiddlyWiki5#192]
Extend the link widget so that it can link to multiple tiddlers at once by specifying a filter identifying the target tiddlers. This would allow us to implement "open all tiddlers with this tag" option to the tag dropdown, and would allow us to drag all tiddlers with a particular tag by dragging the tag pill.

**Comment by wcndave** [comment]
I am also really missing this feature having just upgraded from classic.  Never imagined this would disappear.  I tag things to members of family, and now have no way to list all the tiddlers for a particular member.

**Comment by bdiegel** [comment]
I really miss the 'open all' by tag feature because this is critical to my workflow. Any known workarounds?

**Comment by bdiegel** [comment]
Update: I found the [Demo for Jon](http://gwiz.tiddlyspot.com/#Demo%20for%20Jon:%5B%5BDemo%20for%20Jon%5D%5D) example and [makelist widget](http://gwiz.tiddlyspot.com/#:MakeListWidget%20%5B%5BMakeList%20Target%5D%5D) from @matabele. This was a suitable workaround for now. 

I created an `Open All by Tag` tiddler with a few changes from the cited example:

        \define getTiddlers()
        <$makelist tiddler="$:/StoryList" set="!!list" filter="[tag[$(tag)$]]">
        <$button message="tw-make-list" class="btn-invisible">$(tag)$</$button>
        </$makelist>
        \end
        
        All Tags:

        <$list filter="[all[tiddlers]tags[]!is[system]sort[title]]">
        <$set name="tag" value=<<currentTiddler>>>
        <<getTiddlers>>
        </$set>
        </$list>

**Comment by matabele** [comment]
The $action-listops widget (now included in the core) may be used for this functionality, using the $filter= attribute option

 \define getTiddlers()
<$button class="btn-invisible">$(tag)$
<$action-listops $tiddler="$:/StoryList" $field="list" $filter="[tag[$(tag)$]]"/>
</$button>
 \end

**Comment by gernert** [comment]
@bdiegel 
As an alternative you can overwrite/extend $:/core/ui/TagTemplate see ['Open All' option for tag pills](https://groups.google.com/d/msg/tiddlywikidev/QHaoSn-4Zn4/E93TwOTDEwAJ)

**Comment by twMat** [comment]
From OP
>would allow us to drag all tiddlers with a particular tag by dragging the tag pill.

The discussion (and I) have let this important point slip by. Group dragging by using a pill would be very valuable. **In effect it would enable even complete beginners to make "semi-plugins"**!!!!

**Comment by pmario** [comment]
>... would allow us to drag all tiddlers with a particular tag by dragging the tag pill.

IMO this already works and "open all tiddlers with this tag" has its own open issue. @Jermolene .. close?

**Comment by pmario** [comment]
@Jermolene bump for close. Dragging a tagpill allows us to drag & drop import all tagged tiddlers. .. Dragging a tag pill to the Open tabs opens all tiddlers. ... So imo this one can be closed.

**Comment by Jermolene** [comment]
Thanks @pmario
