### ISSUE TITLE
text-slicer functionality should be a tiddlywiki --command too

### ISSUE THREAD

**Issue by pmario** [Jermolene/TiddlyWiki5#1920]
Is the text-slicer usable as a tiddlywiki --command ?

see little discussion here: https://github.com/Jermolene/TiddlyWiki5/commit/0be82ea7fbc4777cf04947ef8522ae4043b3eb5e

**Comment by Jermolene** [comment]
Apologies @pmario I went ahead and implemented this as soon as you mentioned it yesterday: c4244e8f0493a2d58c3a92ef6939a7029c599bff - not a very clearly labelled commit.

**Comment by pmario** [comment]
:)
