### ISSUE TITLE
possibility to fold custom viewTemplates too

### ISSUE THREAD

**Issue by Evolena** [Jermolene/TiddlyWiki5#1922]
It would be nice to be able to specify that some custom viewTemplates are to be folded alongside the body. Maybe with the use of a field or system tag in viewTemplates tiddlers?

For example, on the preview of sliced-text plugin, the document resulting from a slicing is not folded (except for the date of the slicing, which is its body), because it is mainly displayed via the template $:/plugins/tiddlywiki/text-slicer/templates/export-full-doc, not in the body template.

**Comment by Jermolene** [comment]
Hi @Evolena I fixed this in 76c12a9eccc7d78e488779ce5537ef7d4ce46e81, and then in 026c84197f0c1e14618250a403455564943746af updated the view template segment in the text-slicer plugin to be foldable.

**Comment by Evolena** [comment]
It's a working solution, but it requires to add code to each new tiddler we want to add to the viewTemplate, if we don't want to have strange behaviour when folding.
I'd expected something managed directly in the $:/core/uiViewTemplate tiddler, selectable by the filter of the list `<$list filter="[all[shadows+tiddlers]tag[$:/tags/ViewTemplate]!has[draft.of]]" variable="listItem"><$transclude tiddler=<<listItem>>/></$list>` (that's why I mentioned field or system tag).

**Comment by Jermolene** [comment]
Ah, that makes sense @Evolena. I had a quick look at it, but I think it's going to be hard without introducing a new macro into the view template (which has performance implications). The problem is that we've got the segment title in the variable listItem, and there's no easy way I can see to use the filter in the list widget to access the equivalent of `{{<<listItem>>!!foldable}}`. What do you reckon?

**Comment by tobibeer** [comment]
@Jermolene, for a possible solution, see...

https://github.com/Jermolene/TiddlyWiki5/issues/1974#issue-109046037

**Comment by Evolena** [comment]
(be careful, this one is closed too, so none of the two are visible)

**Comment by tobibeer** [comment]
Oh, overlooked that see that, will reopen the other one.
