### ISSUE TITLE
_canonical_uri field lost for if external text tiddler is loaded. 

### ISSUE THREAD

**Issue by pmario** [Jermolene/TiddlyWiki5#1926]
to reproduce:

- go to http://tiddlywiki.com/prerelease/
- open debug tools <f12>
- console: `$tw.wiki.getTiddler("Alice in Wonderland").fields`
- results in: `17:02:10.014 Object { text: "", _canonical_uri: "./text/Alice%2520in%2520Wonderland.…", tags: Array[1], title: "Alice in Wonderland" }`
- open: http://tiddlywiki.com/prerelease/#Alice%20in%20Wonderland
- console: `$tw.wiki.getTiddler("Alice in Wonderland").fields`
- result -> `_canonical_uri` is gone. ... that's not expected and probably a bug.

**Comment by Jermolene** [comment]
Apologies, this was fixed as part of ecdae4ceff796e261bea909cc3a1ed06bf987371

**Comment by pmario** [comment]
cool. thx to @twMat for pointing it out!
