### ISSUE TITLE
request: There should be a warning if a tiddler title contains "probelmatic" characters

### ISSUE THREAD

**Issue by pmario** [Jermolene/TiddlyWiki5#1934]
request: There should be a "temporary" warning if a tiddler title contains "probelmatic" characters. ... mainly closing braces that confuse filters. 

see: https://groups.google.com/forum/#!topic/tiddlywiki/nB9TlvZ0YXo  for more info. 

also see:  Bug with permalink/permaview + bracket in the title #622   ... once we solve this issue, we can remove the warning.

**Comment by Jermolene** [comment]
It's a good idea. We can display a warning segment along the lines of the existing warning for classic wikitext tiddlers.

**Comment by twMat** [comment]
+1

**Comment by pmario** [comment]
close, since latest pre-release contains this mechanism
