### ISSUE TITLE
$set widget with filter does not refresh properly

### ISSUE THREAD

**Issue by EvanBalster** [Jermolene/TiddlyWiki5#1937]
(Copied from the Google Group)

Changes in the filter result of a <$set> widget do not cause its content to be redrawn.  This differs from the behavior of the <$list> widget, which does drive a refresh.

Example code:  (Can be tested on TiddlyWiki.com)

```
!!Edit Text
<$edit-text tiddler="BugDemo"/>

<$button set="!!prop" setTo="yes">Force Update</$button>

!!!Displayed with $set widget
<<<
<$set name="TEXT" filter="BugDemo +[get[text]]"><<TEXT>></$set>
<<<

!!!Displayed with $list widget
<<<
<$list variable="TEXT" filter="BugDemo +[get[text]]"><<TEXT>></$list>
<<<
```

To reproduce, just edit the text in the box and observe the refreshing behavior.  ...Is this intentional?

**Comment by tobibeer** [comment]
[link to discussion](https://groups.google.com/forum/?fromgroups=#!topic/tiddlywiki/uNeLW76wmWM)

**Comment by EvanBalster** [comment]
I managed to modify the set widget to fix the problem described here.  It doesn't break the wiki and seems to work with all my test-cases.

I don't really know how to go about submitting this to the project...

```
/*\
title: $:/core/modules/widgets/set.js
type: application/javascript
module-type: widget

Set variable widget

\*/
(function(){

/*jslint node: true, browser: true */
/*global $tw: false */
"use strict";

var Widget = require("$:/core/modules/widgets/widget.js").widget;

var SetWidget = function(parseTreeNode,options) {
	this.initialise(parseTreeNode,options);
};

/*
Inherit from the base widget class
*/
SetWidget.prototype = new Widget();

/*
Render this widget into the DOM
*/
SetWidget.prototype.render = function(parent,nextSibling) {
	this.parentDomNode = parent;
	this.computeAttributes();
	this.execute();
	this.renderChildren(parent,nextSibling);
};

/*
Compute the internal state of the widget
*/
SetWidget.prototype.execute = function() {
	// Get our parameters
	this.setName = this.getAttribute("name","currentTiddler");
	this.setFilter = this.getAttribute("filter");
	this.setValue = this.getAttribute("value");
	this.setEmptyValue = this.getAttribute("emptyValue");

	// Set context variable
	this.setVariable(this.setName,this.getValue(),this.parseTreeNode.params);

	// Construct the child widgets
	this.makeChildWidgets();
};

/*
Get the value to be assigned
*/
SetWidget.prototype.getValue = function() {
	var value = this.setValue;
	if(this.setFilter) {
		var results = this.wiki.filterTiddlers(this.setFilter,this);
		if(!this.setValue) {
			value = $tw.utils.stringifyList(results);
		}
		if(results.length === 0 && this.setEmptyValue !== undefined) {
			value = this.setEmptyValue;
		}
	}
	return value;
};

/*
Selectively refreshes the widget if needed. Returns true if the widget or any of its children needed re-rendering
*/
SetWidget.prototype.refresh = function(changedTiddlers) {
	var changedAttributes = this.computeAttributes();
	if(changedAttributes.name || changedAttributes.filter || changedAttributes.value || changedAttributes.emptyValue
		|| (this.setFilter && this.getValue() != this.variables[this.setName].value)) {
		this.refreshSelf();
		return true;
	} else {
		return this.refreshChildren(changedTiddlers);		
	}
};

exports.setvariable = SetWidget;
exports.set = SetWidget;

})();
```

**Comment by Spangenhelm** [comment]
> I don't really know how to go about submitting this to the project...

You must be talking about doing a "pull request", this means that you will have to edit the file you want to modify (here: `$:/core/modules/widgets/set.js`) in Jeremy's repository, this will fork/copy everything to your account (on a branch) that will allow you to do the modifications on your side, once done you can submit a pull request to jeremy to have him include it to the main project.
I suggest you to take a look at the pending pull-requests to better understand how it works

Hope it helped and that your mods will be accepted! (as a bonus you would have your name in the "contributors" section of the next release, just for the pride lol)

**Comment by tobibeer** [comment]
Another bonus would be that it is much simpler to diff your modifications with what's in the core.

**Comment by EvanBalster** [comment]
Ah, yeah -- it's still tabs in source but comment formatting seems to have changed it.  I'll look into making a pull request soon.

**Comment by tobibeer** [comment]
Hi @EvanBalster, I went ahead and made a PR, as I needed this functionality in another PR, I hope that's ok.

**Comment by EvanBalster** [comment]
Thanks Tobias!  I've been using the new modification extensively and it seems to be stable...
