### ISSUE TITLE
Storyview Zoomin - remake to only one tid open at a time?

### ISSUE THREAD

**Issue by twMat** [Jermolene/TiddlyWiki5#1938]
Depending on the answer to this question, it is a proposal or not; 

The doc tiddler [Performance](http://tiddlywiki.com/#Performance) reads (my emphasis):

> Don't have too many tiddlers open at once. Every tiddler you have open will require processing to keep it up to date as the store changes (for example, while you type into a draft tiddler). **It is particularly easy when using zoomin story view to end up with dozens of tiddlers listed** in the Open tab in the sidebar. Get into the habit of periodically closing all open tiddlers with the close all button

Is there any particular reason why storyview Zoomin keeps the tiddlers open? I mean, they show one at a time so if the above is an issue could they not simply be closed an push/popped from history?

Admittedly, that doc tiddler has this as a suggestion for older/slower browers, but I'm thinking that if it is important enough to be 1 out of 4 suggestions _and_ it is a storyview that might be particularly suitable for **mobile**, then it's worth bringing it up.

If _"Yeah Mat, that's a brilliant observation."_... then consider this is a proposal.

**Comment by Evolena** [comment]
I think that even in zoomin view it can still be useful to have access to opened tiddlers.

However, this "only one tiddler opened" could be a new view.

**Comment by tobibeer** [comment]
Interesting point which seems to beg for a "last seen" tab instead of an "open" tab ...or for the latter to actually function as such when some **$:/config/num-display-tids** is set to 1.

**Comment by pmario** [comment]
`$:/config/max-open-tids` could be an option.

**Comment by Jermolene** [comment]
Thanks 3 year old @twMat! I've finally got around to doing this in #3412, so I'm closing this.
