### ISSUE TITLE
saving a tiddler with non-empty input fields

### ISSUE THREAD

**Issue by tobibeer** [Jermolene/TiddlyWiki5#1939]
It happens rather frequently that one forgets to actually add a new tag or new field while editing.

As these contents are not actually saved at the tiddler upon storing it, a notification should indicate to the user that there are uncommited inputs and abort the saving process until resolved, e.g. a message alongside the [save button turning red](https://github.com/Jermolene/TiddlyWiki5/issues/1939#issuecomment-140396544).

**Comment by hegart-dmishiv** [comment]
I noticed this issue when watching [Francis Meetze's new tutorial video](https://youtu.be/a7-pcOSfDFM), and I have done it myself a few times as well. I agree it would be good if there was a some sort of warning that fields are populated but not "added" to the tiddler.

**Comment by twMat** [comment]
Rather than a popup, how about coloring the save tiddler button tick red?

**Comment by tobibeer** [comment]
@twMat, yes that's a much better ui. The important point being: notify the user and stop rather than proceed.

**Comment by nameanyone** [comment]
Why not simply add the fields automatically (or with a confirmation) on saving? Would make the process more streamlined IMO. Coloring the button red will not be to everyone's taste. My buttons are already colored, for example.

![capture3](https://cloud.githubusercontent.com/assets/212368/9966820/ca095c6a-5df3-11e5-943f-4b95de2fc228.PNG)

**Comment by tobibeer** [comment]
tbh, I think that is the most sensible approach as well, the user entered it so chances are he or she only forgot to actually add the field or tag, thus the confirmation would default to "yes, proceed and save" but allow "no, abort" as well... something like an "ok, cancel" thingy.

Thing is, people don't much fancy alerts, so... well, what to do about that. Indeed, just saving things silently is an option, and perhaps not the worst.

**Comment by Jermolene** [comment]
I think the ideal fix would be to make it impossible for the problem to occur.

In the case of tag input, courtesy of action widgets, before sending the `tm-save-tiddler` message, we could add any pending tag via a `tm-add-tag` message. Similarly, we could send a `tm-add-field` message to add any pending fieldname.

**Comment by tobibeer** [comment]
yes, scratch my last comment... if these messages gracefully and silently continue should there be nothing to be added (user already clicked the button), that sounds like the right thing to do.

**Comment by twMat** [comment]
>In the case of tag input, courtesy of action widgets, before sending the tm-save-tiddler message, we could add any pending tag via a tm-add-tag message. Similarly, we could send a tm-add-field message to add any pending fieldname.

+1

Wod also fix #1220

**Comment by hegart-dmishiv** [comment]
What would you terminate a tag entry with? The [TAB] key? Adding multiple tags using [TAB] between them would make sense, and is used often in other UI's I've encountered.

**Comment by tobibeer** [comment]
I think that's a different issue, if not an existing one somewhere ;-)

**Comment by hegart-dmishiv** [comment]
Currently, to enter a new tag on a tiddler, we navigate to the field represented by the placeholder text "another tag" and type in our new tag name (or use the drop-down), then click on the "Add" button. It is this last step, clicking on "Add" which is at stake in this issue, as far as I understand it. What I was proposing is that, instead of clicking "Add", why not just press the [TAB]] key on the keyboard to apply the newly created tag, as in, to set the "another tag" field to dirty? This would also assist with issue [#1682](https://github.com/Jermolene/TiddlyWiki5/issues/1682).

**Comment by tobibeer** [comment]
I understand that you meant that, it's just not exactly related to this issue ...and... it's also not what the generic use of the tab key would be ...which is to move on to the next field.

**Comment by hegart-dmishiv** [comment]
Sorry, I see it as being precisely relevant to this issue. How else are you going to ensure that the tag you've just typed is "added" to the (draft) tiddler without the need to click the "Add" button. As tags can contain spaces, pressing [SPACEBAR] shouldn't be recognised as the terminator for a tag. Pressing [ENTER] after the new tag would probably do it, and would avoid the situation you mention (and I acknowledged above) of interfering with keyboard-based navigation, such as for visually-impaired users.

**Comment by tobibeer** [comment]
This issue is about saving the tiddler despite the user not explicitly having clicked any add buttons, which atm carries the values over to the input fields of the next tiddler being edited ...possibly the least desireable option of all.

Yes, ENTER would do well, also for a possible selection from the popup list.

**Comment by hegart-dmishiv** [comment]
Okay, from a coding perspective, why not trigger `tm-add-tag` with the [ENTER] key?

**Comment by tobibeer** [comment]
This can sure be done, and, as I was trying to say, there probably already is an issue for improving usability and keyboard support. But, this issue is about the moment a user forgot to click add or hit enter as you suggest. In other words, even with your proposed functionality, this issue would still be the same.

**Comment by hegart-dmishiv** [comment]
Sorry, I'm with @Jermolene on this one. "...make it impossible for the problem to occur". That way, if the user forgot to click "Add" it won't matter anyway, because the tag(s) will already have been added, by pressing [ENTER] after each one.

**Comment by tobibeer** [comment]
I imagine you might not have had that experience all to often yet. Of course, being able to hit enter in the new-tag or new-field(-value) inputs would reduce the number of times this is being forgotten quite noticably, I imagine.

Jeremy saying "make it impossible for the problem to occur" ...I imagined he was referring to any red save buttons or alert boxes, rather than a user forgetting to sub-commit a new value... which doesn't appear to be something that can quite be made impossible.

**Comment by hegart-dmishiv** [comment]
I guess I was just thinking that it is easier to remember to press [ENTER] as you're on the keyboard already, typing in a tag name, than to reach for the mouse to click the "Add" button, and as you say, such a change "would reduce the number of times this is being forgotten". I'd hazard a guess that those who already have their hand on the mouse, using the drop-down list of existing tags, are less likely to forget to click "Add". Mobile device users also need to be considered.

**Comment by tobibeer** [comment]
> I just tested, and tags selected from the drop-down don't need to be "Added" as tm-add-tag fires automatically for that event.

That is true and good. However, currently, having to mostly use a pointer to access the popup and leave it is rather suboptimal, usability wise. I'd hope one could...

* type a few letters to constrain items on the list
* hit the DOWN key from the input, to focus the popup
* select the right option via DOWN / UP arrows
* hit ENTER to add
* automatically be back at the focussed input to continue adding or moving on

...for both tags or field-name, while using the arrow keys in the popup should not make the screen scroll and, having selected a field-name, the input should automagically move on to the field-value-input.

**Comment by tobibeer** [comment]
:+1:  Great, thank you Jeremy. I think that's a quick win for everyone.

**Comment by Jermolene** [comment]
I've uploaded a prerelease with the fix:

http://tiddlywiki.com/prerelease

Try clicking "+" to create a new tiddler, and then entering text in the new tag box, and the new field name/value boxes, and then click the tick. The new field and tag should be added.

**Comment by Jermolene** [comment]
@hegart-dmishiv the issue of keyboard controls for adding tags and fields has a couple of existing tickets: #980 and #1907.

**Comment by tobibeer** [comment]
Works great in prerelease and significantly simplifies things. (Nice to see that help-panel, first time I noticed; especially like it being a plugin.)

**Comment by twMat** [comment]
Thanks @Jermolene - works great!

**Comment by nameanyone** [comment]
@Jermolene Works when I "click the tick", but not when I confirm changes using Ctrl+Enter. Would this be an easy fix to add? Thank you.

**Comment by Jermolene** [comment]
Good catch @nameanyone. Annoyingly, it precludes the current implementation of this feature, so I'm re-opening this ticket.

**Comment by BurningTreeC** [comment]
@Jermolene - does this Issue still persist? I believe it's resolved

**Comment by Jermolene** [comment]
We mitigated this problem by automatically committing tags and fields for which the user had yet to click the "Add" button.
