### ISSUE TITLE
[tw.com] Please open up the path folders for peeking

### ISSUE THREAD

**Issue by twMat** [Jermolene/TiddlyWiki5#1941]
I don't know if this is possible but it would be nice if each level in the url was directly peekable. For example, here's a working url

http://tiddlywiki.com/prerelease/editions/tw5.com-docs/

but merely moving up one parent to 

http://tiddlywiki.com/prerelease/editions/

gives 404.

**Comment by pmario** [comment]
since tiddlywiki is hosted by github, imo this is not possible, except, if you create an index.html that contains links to the different editions.

**Comment by tobibeer** [comment]
Perhaps the static editions tiddler can be copied over there as an index.html during the build-process?

**Comment by Jermolene** [comment]
To fix this we would need to ensure that there is a valid `index.html` in each directory you see here:

https://github.com/Jermolene/jermolene.github.io
