### ISSUE TITLE
Make empty.html of old releases accessible

### ISSUE THREAD

**Issue by tobibeer** [Jermolene/TiddlyWiki5#1945]
Not seeing that this is available right now, especially for testing and comparison it would be good to be able to access old empty versions of TiddlyWiki in a painless manner, similar to how it used to be with TWc.

For simplicity's sake, the files could be named like the release tiddlers, so that propper links to the files can be easily constructed.

**Comment by pmario** [comment]
It's easy to create them: https://github.com/Jermolene/TiddlyWiki5/releases

IMO there shouldn't be links to outdated versions in the net. Comparing releases is easiest with github. So I'm not sure if we should provide links to outdated versions.

**Comment by tobibeer** [comment]
I disagree. Testing against an old version should not require anyone to compile it first.

**Comment by pmario** [comment]
>Testing against an old version should not require anyone to (figure out how to) compile it first.

Except the process is so simple that everyone can easily do it. IMO testing against old version and finding problems involves "programming" very fast. So imo we should make the "do it yourself" process much simpler. 

IMO everything, that convinces users to sign on at github and contribute there is a win in the long run.

**Comment by tobibeer** [comment]
It's very simple. Either they'll be officially added to some adequate place, or I'll just add them to mine and make those links available, because it's that easy and I think it should be.

**Comment by Jermolene** [comment]
I think that there should be an easily accessible archive of old releases of TiddlyWiki5; such a thing would be useful for lots of purposes.

In fact, there is, in the commit history for the repo(s) used (via GitHub Pages) for serving TW5:

https://github.com/Jermolene/jermolene.github.io
https://github.com/Jermolene/old.jermolene.github.com

The trouble is that I haven't been tagging each release. That can be done retrospectively; one needs to go through the commit history, matching the commit dates to the release dates of TW5. If anyone can volunteer to help, I'd be very grateful.

**Comment by pmario** [comment]
@Jermolene -- Can be closed. We do have a TW archive now. https://tiddlywiki.com/#TiddlyWiki%20Archive

**Comment by Jermolene** [comment]
Thank you @pmario
