### ISSUE TITLE
Add http://search.tiddlywiki.com and http://news.tiddlywiki.com

### ISSUE THREAD

**Issue by Jermolene** [Jermolene/TiddlyWiki5#1948]
As discussed [here](https://groups.google.com/d/topic/tiddlywiki/D176WyP6y-s/discussion), it is proposed to adopt @erwanm's Community Search and News apps as official community resources.

The idea is to use DNS to point the URLs above at the respective apps.

**Comment by Jermolene** [comment]
@erwanm's apps are currently hosted in the same instance of GitHub Pages. However, as far as I know each DNS entry would need a separate GitHub Pages instance. The easiest way to do that might be to create new GitHub organisations "TiddlyWiki-News" and "TiddlyWiki-Search"; each would get their own batch of GitHub Pages.

**Comment by erwanm** [comment]
@Jermolene if it's more convenient, I could also have my script upload the html file to the server (with ftp or any other way which can be automatized).

**Comment by Jermolene** [comment]
Hi @erwanm I wouldn't want to have an automated process committing changes into the https://github.com/Jermolene/jermolene.github.io repository, because of the risk that problems will affect the main content. I think the easiest solution is to use a separate repo for the new stuff.

**Comment by pmario** [comment]
@Jermolene -- IMO can be closed

- We do have a forum: https://talk.tiddlywiki.org
- A link aggregator: https://links.tiddlywiki.org/ 
- TW Newsletter: https://tiddlywiki.com/#TiddlyWiki%20Newsletter .. not sure if that is still active
- CPL from the Chinese community: https://tiddly-gittly.github.io/TiddlyWiki-CPL/#Index:Index
