### ISSUE TITLE
Rename the "Open" tab in the sidebar to "Opened"

### ISSUE THREAD

**Issue by hegart-dmishiv** [Jermolene/TiddlyWiki5#1949]
Further to [this discussion in the forums](https://groups.google.com/d/msg/tiddlywikidocs/9OJLyGBn9-c/K_EaaW4qCgAJ), it seems to me that, if we're wanting to reinforce the use of the terms *"story"*, *"river"* or *"story river"* within TiddlyWiki, it might be prudent to use them more noticeably. For instance, the "Open" tab in the sidebar activates tiddlers that are already *"open"* in the *"story river"*. Wouldn't it then make sense to rename the "Open" tab to "River" instead? This would strongly reinforce the concept, IMHO.

Currently it is difficult for new users to determine if we're using "Open" as a verb (*"click here to open a tiddler"*) or an adjective (*"these are the tiddlers that are open"*).

**Comment by felixhayashi** [comment]
I would not say so. Naming it *river* would be wrong because the river is where the tiddlers are displayed. As you say, this is a list of tiddlers that are *open* in the river, but it is not the river itself.

**Comment by hegart-dmishiv** [comment]
But it is a representation of the river, isn't it? It lists all the titles of the tiddlers that are currently open in the river, thereby giving an indication of what is in the river.

**Comment by tobibeer** [comment]
I think the "term" river would be confusing and "open" is fine.

The answer two the question "open where?" would be "in the story river"... so if that was in the tooltip of the open tab, then that's just fine for me. So, where are the tooltips?

**Comment by hegart-dmishiv** [comment]
As to the assertion that *"the river is where the tiddlers are displayed"*, it took me quite some time to work that one out, hence the [discussion in the forums](https://groups.google.com/d/msg/tiddlywikidocs/9OJLyGBn9-c/K_EaaW4qCgAJ). I had been using TW for a few days, and had seen mention of *"story"*, *"river"*, and *"story river"*, but couldn't understand what people were talking about. To me, tiddlers just opened in the centre of the screen, to the left of the sidebar. The concept of a "river" is something quite new to me, and I've been using computers since the 1970's. Can you point to any other software that uses the term *"river"* to define the place where content is viewed from?

**Comment by tobibeer** [comment]
It's just the term being used, "story" coming from TiddlyWiki2 and having been a major component to the architecture of it. If you come across a better term, we can use that. I haven't heard of one yet.

**Comment by hegart-dmishiv** [comment]
I'm not proposing a better term, I'm just saying that if it needs to be used at all, let's use it consistently, and in a way that makes it very clear to new users what it's all about.

**Comment by pmario** [comment]
I think @hegart-dmishiv is right, that the concept of the "story river" is new and kind of unique to TW. ... I've seen quite some posts, where the terms "story",  "river" and "story river" confused new users. .. So I think it needs some explanation in the ["Concepts" section at tiddlywiki.com](http://tiddlywiki.com/#Concepts)

But I don't think, that the "open tab" should be renamed. A tooltip: "tiddlers currently open in the story river" may be useful. btw. I thought we had tooltips there :/

**Comment by hegart-dmishiv** [comment]
@pmario, Jermolene has already added [a definition of *"Story River"* in the prerelease for TW 5.1.10](http://tiddlywiki.com/prerelease/#Story%20River).

My concern with your question, Mario, and as enunciated by @tobibear above as "open where?" answer: "in the story river", is that the very next question will inevitably be "what's a story river?"

**Comment by tobibeer** [comment]
Thing is, Hegart, using the term "story" or "river" in the tab makes it even less clear what the tab is about than "open". And, honestly, maybe we really don't need the term story or river anymore. We can simply say "open tiddlers"... sparing the extra dictionary term.

**Comment by Jermolene** [comment]
The term "story river" is mainly used in the code, and I agree that it probably isn't necessary in the docs. The user interface is constructed intentionally so that the user doesn't immediately have to learn TiddlyWiki's special vocabulary.

The term "river" is a nod to Dave Winer's idea of a river of news.

The term "story" is because as the reader navigates links in a TiddlyWiki they unfold their own narrative.

**Comment by hegart-dmishiv** [comment]
@tobibeer,
> and simply say "open tiddlers"... sparing the extra dictionary terms
Once again, this is grammatically incorrect. I cannot "open tiddlers" using the "Open" button unless they are already "open" in the story river. That's why I now suggest the tab be renamed to "Opened". It then becomes blatantly obvious that these are the opened tiddlers.

**Comment by tobibeer** [comment]
I don't understand. Behind me is an "open door", even though it is probably also an "opened door".

**Comment by hegart-dmishiv** [comment]
File > Opened

Nope, never seen that before in computing. When we talk about "open", it is a verb (a doing word), not an adjective (a describing word).

**Comment by Jermolene** [comment]
I think of the "Open" tab as listing those tiddlers that are open in the story river - in other words as an adjective, not a verb (I may not be using those words correctly!). That's consistent with the other tabs, which are all labelled with nouns or adjectives.

Anyhow, I think it's clear enough for users - there's a much more egregious example in the iPhone, where recent calls live under a tab labelled "Recents"!

**Comment by hegart-dmishiv** [comment]
Fair enough, thanks for the discussion everybody who participated. I must be the strange one, thinking that I could open a tiddler from the "Open" tab. I'll close this ticket now then.

**Comment by hegart-dmishiv** [comment]
![save_failed](https://cloud.githubusercontent.com/assets/14275188/9981588/3c2d504e-6015-11e5-96b6-9e1ab38cb793.png)

**Comment by tobibeer** [comment]
:-)

You really don't "open" a tiddler form the open tab, you just scroll it into view. Sure, in a one-tiddler-at a time story-view, "open" has a funny meaning... more like "crumbs".

**Comment by felixhayashi** [comment]
@hegart-dmishiv As a linux user, I do not trust windows dialogs :)

**Comment by hegart-dmishiv** [comment]
Apologies @tobibeer, I didn't mean to say that your "open tiddlers" comment was grammatically incorrect, just grammatically ambiguous. It is more the ambiguity that was at issue here.

**Comment by tobibeer** [comment]
nay worries, all smooth sailing on this pond ...and, yes, clarity is a high treasure worth achieving
