### ISSUE TITLE
problematic: edit-text widget in textarea mode for tiddler field that is not text

### ISSUE THREAD

**Issue by felixhayashi** [Jermolene/TiddlyWiki5#1955]
Hi @Jermolene 

When operating in nodejs and using a textarea for entering some sentences and using a tiddler field that is not "text" as output will result in a creation of a tid file that simply dumps the newline which will damage the wiki. On the next reload, at best the newline is ignored in the worst case, the tid file as a whole is ignored (=loss of data) or parsed wrong, which becomes even worse, when the entered multiline text contained colons.

I only now started to realize that edit-text widgets used with non-text fields as targets will break the tiddler. How should one expect a new user to know that? My first thought on this would be to rigorously do `str.replace(/[\n\r]/g, " ");` on all data that is stored in non-text fields to avoid multilines getting dumped into the store (which is not designed for multilines; with the text field as an exception).

-Felix

**Comment by Jermolene** [comment]
Hi @felixhayashi I think this is the problem we've been discussing #1947; it's nothing to do with the edit-text widget; it's just that the .tid file format doesn't support fields containing line breaks.

Just to be clear, the store is fine with linebreaks in fields (they work OK with the standalone configuration) . It's just the saving to .tid file format that's the problem.

**Comment by felixhayashi** [comment]
Hi @Jermolene 

> I think this is the problem we've been discussing #1947; 

How strange that almost the same discussion was started 3 days ago, then sorry for opening this issue, I'll have a look at #1947 then.

> Just to be clear, the store is fine with linebreaks in fields (they work OK with the standalone configuration) . It's just the saving to .tid file format that's the problem.

Yes, the html store is fine and has no problem with that. It's the tid file I was talking about.

**Comment by pmario** [comment]
@felixhayashi So we can close this issue?

**Comment by felixhayashi** [comment]
Yes

**Comment by felixhayashi** [comment]
Hmm I think it makes sense to open this issue as it is highlights a potential thread: users are able to use the `edit-text widget` in multiline mode on single-line fields.

**Comment by Jermolene** [comment]
@felixhayashi I think #1947 is a bug report that covers exactly the problem being discussed here. We don't need both tickets to track the problem of replacing the `.tid` file format.

**Comment by felixhayashi** [comment]
Ok
