### ISSUE TITLE
Labeling plugins in terms of degree of customisation of core 

### ISSUE THREAD

**Issue by buggyj** [Jermolene/TiddlyWiki5#1956]
Plugins may add to or modify the core plugin - how they do this can be ranked:
0.adds templates, widgets, etc (changes to functionality are via config tags, if at all) 
1.adds templates, widgets, etc (changes to functionality are via existing config tiddlers)
2. modifies core templates
3. modifies core widgets / macros / parser rules
4. modifies core javascript modules (other than widget/macros/parser rules)
5. replaces core plugin or bootloader components

could use colours - white, green, yellow, orange, red, black

This could be used to give advise (give strength of advise) when updating the core - eg 3 and 4 strongly advise the user to check for compatible versions of plugins before upgrading.

**Comment by tobibeer** [comment]
I think the easiest would be for the plugin to be required to flag certain components with a given tag indicating its intrusiveness, e.g. those tagged `$:/plugin-level/3` would correspond to 3. above.

That way "0" would be implicit", and everything else explicit. The plugin manager would show the highest risk but could also show components sorted by "vulnerability".

**Comment by Jermolene** [comment]
@buggyj were you thinking that these labels would be applied manually, or automatically generated? I'd worry that self-declared data might not be accurate.

**Comment by buggyj** [comment]
obviously replacing core tiddlers can be detected. It might be difficult to automatically workout if a plugin is monkey patching the core (or widgets), and this is the type of plugin that needs to be either inactivated or updated at same time as updating the core. I would think that it would be better to have some, maybe inaccurate user information rather than inaccurate information generated by the system.

**Comment by tobibeer** [comment]
I think manually would be the process. Marking individual components than just the whole package would make a revision process more straight forward.

**Comment by pmario** [comment]
I think it needs to be assigned automatically. 

I also think it should be only 3 colours eg: green, yellow, read and it should be single options instead of collections. 

eg: 

[ ] .. this plugin adds templates
[ ] .. this plugin adds widgets
[ ] .. this plugin adds macros 
...
[ ] .. this plugin modifies core templates
[ ] .. this plugin modifies core widgets
[ ] .. this plugin modifies core macros 
...
[ ] .. this plugin modifies core javascript modules
[ ] .. this plugin modifies core bootloader

So we may have more elements at the beginning, but we don't need to modify any of them if some new elements are added. ... and ... all of those options can be detected automatically except the "added" stuff. But those are not critical, if they are wrong.

**Comment by Infurnoape** [comment]
I get the impression that there isn't going to be any enforcable core monkey patch protection any time soon? This is just another suggestion making it clear in the readme of monkey plugins that it includes a core override. ooh ooh ooh eee eee eee.
For example:
WARNING : This plugin includes a tiddler that overrides a core shadow tiddler. The core version of the overridden tiddler is kept but is inactive. Updating your TiddlyWiki will update the overridden core tiddler which is hidden. Deleting this plugin will re-activate the overridden core shadow tiddler.

This plugin comprises:

Templates
Stylesheet
Core override

**Comment by buggyj** [comment]
I don't think that automatic code analysis in javascript would be easy. I think that it is up to the developer to say what level of update 'risk' their plugin has, and we need to decide what the update process should do for each level (e.g advising the user to check with the developers release notes for compatibility). As plugins come as a package I think that we only need to give one number to our plugins.

**Comment by pmario** [comment]
> I think that it is up to the developer ..

IMO that's the same as: "This info is wrong most of the time."

**Comment by pmario** [comment]
>I don't think that automatic code analysis in javascript would be easy. ...

IMO we already have this info. See the ControlPanel

**Comment by buggyj** [comment]
Closing - not actionable at the moment, needs decision.
