### ISSUE TITLE
allow variable, but interpreted macro defaults

### ISSUE THREAD

**Issue by tobibeer** [Jermolene/TiddlyWiki5#1958]
Example: Currently this is possible...

```
\define foo(bar:<<variable>>,baz:{{TextReference}})
$foo$
$bar$
\end
```

However, this is very limiting in that the macro cannot use these parameters as attributes for widgets, e.g.:

```
\define foo(bar:<<variable>>,baz:{{TextReference}})
<$link to="$bar$">
<$view tiddler="$baz$" field="title">
</$link>
\end
```

If I was to remove the quotes, the widgets would fail if parameters containing spaces were passed.

Therefore, divise a syntax that allows to have variable defaults actually interpreted rather than replaced as literal text interpreted later.

Or, better still, always interpret variable macro parameters, because what's the point of not doing so other than the above limitations?

**Comment by pmario** [comment]
you know, that there is a typo? `<$link to="$bar§>`  see the `§`

**Comment by tobibeer** [comment]
fixed, thanks

**Comment by pmario** [comment]
imo https://tiddlywiki.com/#Macro%20Definitions%20in%20WikiText Parameters vs Variables fixes this problem. 

Pls close if ok.

**Comment by Jermolene** [comment]
I don't think that this is fixed, but the OP calls for a syntax to be devised and we have yet to see one, so therefore we can close it.
