### ISSUE TITLE
order of toolbar commands

### ISSUE THREAD

**Issue by tobibeer** [Jermolene/TiddlyWiki5#1961]
As **more** should always be the first to the left, **edit** and **close** should be the last to the right.

![toolbar](https://cloud.githubusercontent.com/assets/97566/10080071/e55b366a-62ed-11e5-8364-662407c25cae.jpg)

I'd perhaps prefer this sequence...
- $:/core/ui/Buttons/more-tiddler-actions
- $:/core/ui/Buttons/permalink
- $:/core/ui/Buttons/permaview
- $:/core/ui/Buttons/open-window
- $:/core/ui/Buttons/fold
- $:/core/ui/Buttons/fold-others
- $:/core/ui/Buttons/close-others
- $:/core/ui/Buttons/export-tiddler
- $:/core/ui/Buttons/new-here
- $:/core/ui/Buttons/new-journal-here
- $:/core/ui/Buttons/clone
- $:/core/ui/Buttons/info
- $:/core/ui/Buttons/delete
- $:/core/ui/Buttons/edit
- $:/core/ui/Buttons/close

The buttons in the more-popup should thus probably be listed in reverse order, the topmost being the most to the right, when visible.

**Comment by twMat** [comment]
...OK, popping the obvious question here: Would it be too costly to make this customisable? I have definitely silently wished for this a few times and considering how customisable TW aims to be and how *prominent and ubiquitous the toolbar is*, it is actually surprisingly static.

A very natural place to set the order for it would be in the Ctrlpanel>Toolbars tab where you set show/hide.

Considering the checkboxes there, maybe this would make it relevant as an application for the #1957 and the lists in $:/tags/ViewToolbar etc.


>As more should always be the first to the left, edit and close should be the last to the right.

IMO not self-evident and it is very reasonable that a user will want his "favorite self made button" at some extreme end.

**Comment by Jermolene** [comment]
Hi @twMat the toolbar button order is already very customisable: just edit the `list` field of the tiddler `$:/tags/ViewToolbar`. That's a shadow tiddler, but it's very safe to override it.

There's no UI at present; that's waiting on having a drag-and-drop reordering feature.

**Comment by tobibeer** [comment]
I think a dedicated ui would be overkill for a 1 time operation... unless it was a generic "reorder that list" ui.

**Comment by Jermolene** [comment]
> unless it was a generic "reorder that list" ui.

That's what I meant, yes.

**Comment by pmario** [comment]
We can drag & drop sort this list now. So every user can adjust it, as they want to have it. 

IMO it's fixed.

**Comment by Jermolene** [comment]
Thanks @pmario
