### ISSUE TITLE
generic EventWidget

### ISSUE THREAD

**Issue by tobibeer** [Jermolene/TiddlyWiki5#1970]
demo: http://eventwidget.tiddlyspot.com

----

_will be gradually updated based on comments_

This is a concept proposed to tackle #980, amongst others, via a generic event widget, by default placed inside **any** other widget for which it defines event bindings.

**Event Actions**
- any parameterized action widgets contained are executed whenever an associated event fires
  - associated actions and messages can be nested inside lists
  - perhaps a unique event-id should be specified to ensure we're firing for the right event widget

**Parameters**
- **events**  — specifies one or more javascript events for which the widget registers an event listener, e.g. _keydown_, _click_, etc...
- **target**  — specifies an element relatively, e.g. `parent.parent`, or absolutely via `<css-selector>` on which to register the events, default: `parent`
- **keys** — defines the key or key-combination for which keyboard events fire
  - also defines modifier keys like SHIFT, CTRL, ALT for pointer events
  - key combinations are noted using plus, e.g. CTRL+C
  - can be as complex as `key:"ESC CTRL+UP"`
    - meaning: fire both on pressing either ESC or the combination CTRL+UP
- **id** — a unique event id that allows for any associated action widgets to specify exactly for which event widget to fire
- **bubble** — whether or not the event allows to bubble up the widget tree to any parent widgets / DOM elements
- **not** — specifies a selector within the event widget div for which the event will not fire
- **type**, **state**, **text**, **default** — like the reveal widget, allows to specify conditions that need to be met upon which to actually trigger the event
- **set-state** — a text-reference set to the event name when it fires, e.g. **mouseover** / **mouseout**
- **focus** — (perhaps) allows to specify a `<css-selector>` of an element on the page that is focused when the event fires, e.g. to move form the search input to the search results using the DOWN key
  - not quite sure how to formulate the condition that would bring the focus back up to the input via UP key only, perhaps just ESC or CTRL-UP

**Comment by tobibeer** [comment]
existing event experiments / solutions...

* double click to edit
    * https://groups.google.com/d/msg/tiddlywiki/nY4wwuCWUpY/SUvcdwkuCgAJ
* mouseover / mouseout
    * https://groups.google.com/d/msg/tiddlywiki/gm-uCdS_O0w/TjQOXaSpCwAJ

also added **set-state** parameter above

**Comment by tobibeer** [comment]
@Jermolene, made a basic demo here:

http://eventwidget.tiddlyspot.com

First codebits in above commit.

**Comment by matabele** [comment]
@tobibeer 
Hadn't seen this before -- will be useful. I particularly like the ability to trigger different action widgets with different events -- this kind of logic is difficult to implement in TW5.

Worth more time and effort :-)

**Comment by tobibeer** [comment]
I should perhaps rather make q PR to talk code, rather than... clickety examples in some demo wiki.

**Comment by sukima** [comment]
![Talk is cheap. Show me the code. ~Linus Torvalds](http://izquotes.com/quotes-pictures/quote-talk-is-cheap-show-me-the-code-linus-torvalds-273528.jpg)

**Comment by tobibeer** [comment]
:D

**Comment by diego898** [comment]
I think this is a great idea!

**Comment by Jermolene** [comment]
Thank you @pmario
