### ISSUE TITLE
expose system info

### ISSUE THREAD

**Issue by tobibeer** [Jermolene/TiddlyWiki5#1977]
Provide an appropriate means to access important system information, e.g. for use in filters and conditional templates:

```
[system:href[]regexp:title[^http\:\/\/my-site\.com]]
```

The **href** would be important. What else? Maybe day, time, daytime in tw format?

### Plugin Solution ###

Inspired by [publicsidebar](http://publicsidebar.tiddlyspot.com), I created a plugin using much the same mechanism: [tobibeer/sysinfo](http://tobibeer.github.io/tw5-plugins/#sysinfo).

**Comment by twMat** [comment]
>What else?

* If not already assumed/implied in href: origin, host, hostname
* ...and perhaps connection status (online/offline)
* Maybe browser (...sniffer result)?
* screen size... maybe even device type
* Ref #1979 - detect communication rights.

**Comment by Jermolene** [comment]
The "browsersniff" plugin exposes a bunch of information about the current browser via shadow tiddlers starting `$:/info`; you can see them listed in the "Shadows" tab of the sidebar on http://tiddlywiki.com.

The same technique could be used to expose other information.

> ...and perhaps connection status (online/offline)

It's unfortunately not at all easy to figure that out. You'll find some JS libraries that try to do a decent job, but browser support is poor.

**Comment by tobibeer** [comment]
> It's unfortunately not at all easy to figure that out. You'll find some JS libraries that try to do a decent job, but browser support is poor.

Writing the current location into a tiddler doesn't sound hard. By the way, are these shadows created / updated on the fly? / on startup? (How) Can one create shadows on the fly?

**Comment by Jermolene** [comment]
@tobibeer the shadows are created on the fly at startup, so the technique is only suitable for values that don't change over a session. Have a look at the source code to see how it's done:

https://github.com/Jermolene/TiddlyWiki5/blob/master/plugins/tiddlywiki/browser-sniff/browser.js

As you can see, there's a module-type "info" that the core automatically invokes during startup.

**Comment by tobibeer** [comment]
Ok, so setting whether we're local / on localhost or over the web on startup would be a valuable information.

**Comment by tobibeer** [comment]
@Jermolene, I find "are we local or via http" to be a very rudimentary information. So, the questions would be...

1. Do you see this in plugin territory (similar to browsersniff)?
    1. Would you think of it as an extension / amendment to browsersniff?
2. Do you see this as a core feature to populate `$:/info/location`?
    1. Would you populate it in a similar manner as browsersniff does?
    1. Would it perhaps rather make sense to put it under `$:/temp/`?
        * after all, we don't want users to either override those or have them saved

**Comment by Jermolene** [comment]
Hi @tobibeer 

> 1. Do you actually see this in plugin territory (similar to browser-sniff)?

The browser-sniffing was only made a plugin because it requires an external JS library, and we felt that was too heavy for the core.

But the ability to read the document location is more fundamental, and doesn't need a JS library, so I think it belongs in the core.

>    1. Would you think of it as an extension / amendment to browser-sniff?

No.

> 2. Do you see this as a core feature to populate `$:/info/location`?

Yes, the idea would be to use the same `$:/info` mechanism that is used in the browsersniff plugin. It enables plugins to register information that is then packed into a shadow tiddler at startup. That means that this technique is only suitable for information that doesn't change after startup.

>    1. I assume you would populate it in a similar manner as browser-sniff does.
>        * but at what point in the boot sequence?

I'd recommend looking at the implementation in `$:/core/modules/startup/info.js`.

>    1. Would it perhaps rather make sense to put it under `$:/temp/`?
>        * after all, we don't want users to either override those or have them saved

That's why the info is saved as shadow tiddlers, to avoid showing up in lists and being saved.

**Comment by pmario** [comment]
>I find the "are we local or via http" information to be rather fundamental.

hmmm,

`http://localhost.lan` is local for me. So imo we need to specify the term "local" and "via http" a bit closer. 

Also be aware, that there is no `c:\` in linux world ;) IMO macros and plugins need to be OS agnostic. ... IMO browser / OS sniffing is error prone.

**Comment by tobibeer** [comment]
> http://localhost.lan is local for me. So imo we need to specify the term "local" and "via http" a bit closer.

So long as the current location can be read from a tiddler, I — as in the developer / publisher — have a way to define some filter that allows me to have the wiki behave differently in my dev / publishing environment as compared to a deployed site. That's all I need. No need for any advanced `localhost` detection.

**Comment by tobibeer** [comment]
I just created & published [sysinfo](http://tobibeer.github.io/tw5-plugins/#sysinfo), which goes a different route — similar to [publicsidebar](http://publicsidebar.tiddlyspot.com) — as compared to using more stateful tiddlers, e.g. **$:/info/foo**.

I am aware of refresh limitations of this approach...

http://tobibeer.github.io/tw5-plugins/#sysinfo-Limitations

...but I think I'm fine working with it this way.

Seeing as how Jeremy does not quite favor these kinds of macros, I won't make any pull request for it.

For me, this concludes working on this topic, as I have no further need for a different kind of core support. Therefore, I'm closing this now. But, feel free to veto.

**Comment by tobibeer** [comment]
I think I'll actually reopen this, because there os certain basic system info that is better provided by the core, e.g.: **href**.

Why? Well, if a plugin-info wanted to show links that

* in a user wiki show as **external** links
* in the plugin documentation wiki show as **internal** links

...it can hardly depend on **sysinfo**.

@Jermolene: So, a basic href may still need adding to **$:/info/href**, or some such, i.e. so long as we're still not keen on any &lt;&lt;sysinfo>> macros in the core.

**Comment by tobibeer** [comment]
finally available in the core as of https://github.com/Jermolene/TiddlyWiki5/commit/2f590a365e5b6bfecc1170fdbeaaf398795a2feb
