### ISSUE TITLE
User setting of communication rights

### ISSUE THREAD

**Issue by twMat** [Jermolene/TiddlyWiki5#1979]
Considering how important security/selfownership/integrity is for TW, I wish there was a global user setting to accept in and/or out signalling.

Concrete use examples include iframes and plugin libraries (and much more).

Later considerations
* "Private mode" button to disable all com.
* Fine tuning ("accept only communication with tw.com")
* Notification per call ("you're about to contact http...") - possibly with info about which widget/tiddler is calling

**Comment by tobibeer** [comment]
What's the purpose / scope of this? ...who needs it and why?

**Comment by twMat** [comment]
Main purpose is user control on the potentially sensitive matter of showing yourself outside of TW. 

For instance if you install a plugin, it is not desirable that using it triggers external communication without your knowledge. A plugin might have a tiddler with, say, an iframe that loads from an external source and in the process also transfers data from your system even if just a ping. You might wish to be notified before this initiates.

It could be for privacy reasons but also for practical reasons; a network that is slow or expensive on this device. Or maybe the screen is so small that you dont' want to load, say, any external images or any exernal things at all (disable all external links).

By enabeling user control on the matter, it would hopefully also let us relax what can be accepted to include in plugins. For example, I'm hoping we eventually have ways of "measuring usage" to get e.g statistics over plugin usage. This is probably not desirable unless the user cannot permit/disable it (...in which case it would be very desirable, for the TW project, IMO)

**Comment by tobibeer** [comment]
Feels a bit like overengineering. You may ask the core and plugin authors to not do update magik in the background but always invoke that via user action, e.g. some "check for updates" button. This would rather be desireable for the servers of those who provide plugins, because it won't have each and every TiddlyWiki constantly request plugin data only to check if there's anything to update.

But then, if there were such features and you wouldn't want a "talky-talky" plugin to do the talky-talky... then just disable it et voila. Other than that, you'll have to see in each and every case how this can be made "optional" or "opt-in'ish"... I don't quite see any generic approach to this or a necessity thereof, atm.

**Comment by twMat** [comment]
Hm, I'm frankly surprised that you (or anyone) would object to this. While it perhapas isn't explicity stated, I think integrity issues are high on the TW agenda and being able to turn off communication is IMO an prime example.

An "update check" is more or less a feature but many things are much more subtle and the user can hardly know anything is happening. For instance loading of an external image.

Again, the other side of the coing is that providing user control in this would IMO also "morally" allow us greater flexibility that would otherwise perhaps be dubious, such as collecting information. It is a big difference to explicitly permit or deny a plugin to collect info compared to being forced to either install and accept it or just not be able install it.

That said, you have a greater technical understandign than I do and maybe it is much more complicated than I imagine it.

**Comment by tobibeer** [comment]
@twMat, I'm not objecting, just not seeing a practical approach atm. In other words: What would you find actionable in this issue and how do you imagine going about it?

Integrity and privacy seem somewhat separated concerns to, although there is some overlap. If a plugin was to threaten your wiki's integrity by doing some talky-talky, then that should not be a plugin to have.

Other than that, as I said, if a plugin does critical operations, e.g. modifying core components via updates etc., then that should indeed always be performed only on user request. I would not, however, have some configuration stuff that somehow tries to constrain what's possible, while that will hardly work anyways.

>  For instance loading of an external image.

I am sorry Mat, but this is clearly something rather common and, if anything, perhaps infringing upon that other locations privacy and licensing, but not a user looking at it. Now, you can say "yes, but there are facebook buttons" ...and then you are free to just not use any plugin that gives you such a button that does more than you want. So, there's nothing actionable for the core here.

So, the question is "user control" over what exactly? "Do not show external images"? Really? Is that what we should waste precious development time on?

> It is a big difference to explicitly permit or deny a plugin to collect info compared to being forced to either install and accept it or just not be able install it.

Again, that discussion you would have to take up with every individual plugin author. Don't you think?

So, yes, I imagine this to be very complex, especially when it's a bit unclear what the scope of this is and how it would possibly affect so many places to virtually achieve nothing, e.g. some "disable external images". I couldn't  be bothered implementing or testing anything like that, as I see virtually no benefit. All I'm saying.

Besides, it really sounds like you want to do what your browser should do. If you don't want a page to display resources from another one, let alone talk to any other one... that's what you have browser security and plugins for.

**Comment by Jermolene** [comment]
Hi Mat
> Considering how important security/selfownership/integrity is for TW, I wish there was a global user setting to accept in and/or out signalling.
> 
> Concrete use examples include iframes and plugin libraries (and much more).
> 
> Later considerations
> 
> "Private mode" button to disable all com.
> Fine tuning ("accept only communication with tw.com <http://tw.com/>")
> Notification per call ("you're about to contact http...") - possibly with info about which widget/tiddler is calling
The trouble is that browsers don’t make it possible to control the actions of loaded JavaScript to that degree. When JavaScript is executed there is virtually no ability to constrain what it can do.

Having said that, it is the sort of feature that might be implemented in TiddlyDesktop.

It’s possible that Service Workers might in the future provide a way of implementing these sort of constraints. Service workers give JavaScript code the ability to control and intercept network calls made by the browser.

Best wishes

Jeremy.

**Comment by twMat** [comment]
@tobibeer -

>What would you find actionable in this issue and how do you imagine going about it?

I actually thought this was not a particularly complicated matter (...for someone in the know) because I assumed controlling in/out communication was a rater common issue for various software and because I assumed it mostly relied on a limited set of mechanisms in a browser and over the web. So, basically I imagine some page setting to enable blocking these assumed mechanisms. For an eventual fine tuning I assumed there are a limited number of commands etc in javascript/htm that cause in/output, and that one therefore would just have to "disable" these, somehow.

> If a plugin was to threaten your wiki's integrity by doing some talky-talky, then that should not be a plugin to have.

Well, how would a user know this about the plugin? And what if the context changes and he merely temporarily doesn't want external communication? The user would not only have to understand the issue when installing every plugin works but also keep it in mind actively all the time... that's asking a lot.

Anyway, as @Jermolene points out it is appearently not possible to control it well anyway, so I'm closing the issue.

Thank you both for your input! :-)

**Comment by Jermolene** [comment]
Hi @twMat I should just point out that your intuition continues to serve you quite well: the idea of one block of code executing another block with constraints on what it can do is called "sandboxing", and remains an area of great interest. "Containers", if you've read about them, are essentially sandboxes implemented in the Unix file system.

Sandboxing on the web is very limited, apart from iframes. One could imagine a plugin architecture that was based on running each plugin in its own iframe, but the trouble is that such plugins would be too isolated to do the kind of cool stuff that we see in plugins like @felixhayashi's TiddlyMap.

**Comment by twMat** [comment]
@Jermolene - encouraging to hear, thank you! The thought of locally iframed plugins is a an interesting idea I've never considered.

**Comment by tobibeer** [comment]
> The thought of locally iframed plugins is a an interesting idea I've never considered.

Yes, that would surely constrain communication to well defined pipelines.
