### ISSUE TITLE
Detect attempted TWC use in TW5

### ISSUE THREAD

**Issue by twMat** [Jermolene/TiddlyWiki5#1982]
While it may be too costly to do a wider detection system, I do propose a simple trigger for the tag *systemConfig* - i.e if a user adds this particular tag, show a notification that 

>The tag systemConfig indicates you are trying to install a plugin designed for TiddlyWiki **Classic** (TWC). Please note that TiddlyWiki is a complete rewrite of the older TWC and plugins designed for TWC are not likely to work in TiddlyWiki. See XXX for further information.

The ideal would be if this could be immediately detected but otherwise in the initial page load process. 

I think this is justified in standard distro because it is a definite indicator of misuse and misunderstanding - and it is done by someone who is a beginner but who is at the stage of *really trying to use and modify* things according to needs. This is a very sensitive stage IMO. If I try out a software, a prerequisite is that it looks like it has potential but if it fails when I actually try to make it work for *me* and already at this stage... then *"Why bother with it. Next!"* (The reason for failing is *irrelevant*. The user cannot know if it is a bug or him doing something wrong or incompatibility with his system etc.)

Mixing up TWC and TW5 is also a fundamental problem that even a competent coder might make and we can (absolutely) not demand that people participate on the boards to get clarity in things like this.

Are there other cases where mixups between TWC and TW5 can/ought to detected and treated?

**Comment by tobibeer** [comment]
Already there. Close?

![warning](https://cloud.githubusercontent.com/assets/97566/10243963/645a8d26-68fc-11e5-8e32-8f9a83952851.jpg)

**Comment by twMat** [comment]
Haha!!!!
Closed!
