### ISSUE TITLE
tw.utils.extend potential pitfall when adding a string as argument

### ISSUE THREAD

**Issue by felixhayashi** [Jermolene/TiddlyWiki5#1987]
It will slice the string and add all characters with their indeces in the string

![2015-10-03 14 37 46](https://cloud.githubusercontent.com/assets/4307137/10262929/b2578a84-69dc-11e5-9a92-d9fd53781fcf.png)

Just wanted to record this as an issue…

**Comment by Jermolene** [comment]
Hi @felixhayashi I'm not sure that it's worth keeping an issue open to record this. Although surprising at first, this is how strings are coerced to objects in JavaScript; it's just one of many surprising things about JavaScript, really. (See http://wtfjs.com).

**Comment by tobibeer** [comment]
I'm a bit curious about what you expected, @felixhayashi ^_^

**Comment by felixhayashi** [comment]
> JavaScript, really. (See http://wtfjs.com).

That's an interesting site, thanks.

> Hi @felixhayashi I'm not sure that it's worth keeping an issue open to record this. Although surprising at first, this is how strings are coerced to objects in JavaScript;
> I'm a bit curious about what you expected, @felixhayashi ^_^

Well, I know that JS would deal with a string in this way, it's not that I am totally new to the language. But is nobody concerned that a extend function doesn't skip non-object arguments? this will create hard to spot errors if a programmer's code injects a string by accident extend (can always happen) and extend does something like this.

-Felix

**Comment by Jermolene** [comment]
Hi @felixhayashi 

> But is nobody concerned that an extend function doesn't skip non-object arguments? this will create hard to spot errors if a programmer's code injects a string by accident extend (can always happen) and extend does something like this.

Would skipping the string argument really be any easier to track down that coercing it to an object? Anyhow, I'm not against a pull request to make extend skip non-object arguments.

**Comment by tobibeer** [comment]
> nobody concerned that an extend function doesn't skip non-object arguments

depends, perhaps skipping isn't even the best idea, setting whatever string is passed as an undefined parameter could even be another option

**Comment by Jermolene** [comment]
It's good to write defensive and robust code, but I think there are diminishing returns in trying to anticipate and ameliorate the impact of a method being called with the wrong arguments.

**Comment by felixhayashi** [comment]
I asked this at the jQuery repo (their extend function behaves like TW's extend) and they said that the new ES6 `Object.assign()` also behaves like this. So while I still find it confusing/dangerous, I think it is fine to leave TW's extend as is and close this. Thanks for participating in this discussion.

**Comment by Jermolene** [comment]
Thanks @felixhayashi

**Comment by felixhayashi** [comment]
> meats the standard,

\* "meets the standard" :D
