### ISSUE TITLE
Editing Pane does not adjust size when "Hide sidebar" is clicked and a preview pane is enabled.

### ISSUE THREAD

**Issue by nbrown8941** [Jermolene/TiddlyWiki5#1995]
If the user is editing a tiddler and has enabled the "Show Preview" function and then hides the sidebar the length of the editing pane is not adjusted. Especially in longer tiddlers this results is a large amount of white space beneath the content. 

Steps To Reproduce:

1. Make sure that the sidebar is being displayed.
2. Open a longer tiddler (Using links to navigate between tiddlers)
3. Click "Edit this tiddler"
4. Click "show preview"
5. Click "Hide sidebar"
6. Scroll down and note the white space in the editing pane (the pane is still the same length as when it was 1/3 the width.

Expected Behavior: 

The editing pane should resize to fit its contents. The behavior should be the same as when the user hides the sidebar while the preview pane is hidden.

Workaround:

The user can click "hide preview" and then "show preview" and the edit pane will have been resized.

Screenshots:
![image](https://cloud.githubusercontent.com/assets/11408003/10286365/6a1cfd50-6b5b-11e5-9b05-0980f9c23418.png)
![image](https://cloud.githubusercontent.com/assets/11408003/10286421/a5e876e8-6b5b-11e5-8465-1778306a19ee.png)

Environment:

Windows 7
Chrome Version 45.0.2454.101 m

**Comment by Jermolene** [comment]
Interesting, thank you @nbrown8941 

The problem is with the automatic resizing of the edit-text widget. Removing the sidebar causes a reflow but doesn't trigger the edit-text widget to recalculate the appropriate height.

The fix is probably for `EditTextWidget.prototype.refresh()` to call `EditTextWidget.prototype.fixHeight()` even if no other refreshing is needed.

**Comment by Jermolene** [comment]
Hi @nbrown8941 I've pushed an updated prerelease that includes the fix:

http://tiddlywiki.com/prerelease

Can you let me know if it's good for you?
