### ISSUE TITLE
BUG: an unspecified macro parameter must not be passed as empty-string

### ISSUE THREAD

**Issue by tobibeer** [Jermolene/TiddlyWiki5#2000]
especially for JavaScript macros, the wikitext parser must not pass any unspecified parameters as `""` (string) but rather as `undefined`

**Comment by tobibeer** [comment]
#2000, wow :tada:

**Comment by pmario** [comment]
I'm not so sure about it.

You can use this:

```
\define hello(a:"undefined", b)
hello $a$ $b$
```

if your really want this behaviour.

**Comment by tobibeer** [comment]
I'm a little confused over your reply, Mario. There's `undefined` and then there's `"undefined"` ...only one being a string, in fact "a thing" at all, the other amounting to nothing defined at all.

**Comment by Jermolene** [comment]
Hi @tobibeer 

> especially for JavaScript macros, the wikitext parser must not pass any unspecified parameters as "" (string) but rather as undefined

You say "especially", are there other situations where this proposal applies?

The trouble is that it isn't backwards compatible.

It doesn't fix the problem, but did you know that a macro can specify a "default" value for a parameter? For example:

```
exports.params = [
	{name: "format", "default": "text"}
];
```

**Comment by tobibeer** [comment]
> It doesn't fix the problem, but did you know that a macro can specify a "default" value for a parameter?

I believe I've seen that, but I don't think this will allow to cover undefined vs. empty-string, as the parser will always pass empty string down to the macro, defined or not.

**Comment by Jermolene** [comment]
No, it still doesn't allow a macro to distinguish between a missing parameter and an empty parameter.

**Comment by pmario** [comment]
@tobibeer 

Detecting "empty" vs "non existing" parameters, is a general problem for JS libraries. 

I wanted to point out, that we need a consistent behaviour for wikitext macros and js macros. For wikitext macros, we only have "strings" as parameters and TW chooses sensible a default ... an empty string.

If you a assign `undefined` to a variable and then serialize it into a string, most of the time you'll get a runtime error or the string `undefined`. 

 - A runtime error is forbidden because TW fails silently if sensible
 - The text `undefined` will be wrong, so imo an empty string is a sensible fallback value and compatible with the wikitext version.

**Comment by tobibeer** [comment]
> I wanted to point out, that we need a consistent behaviour for wikitext macros and js macros.

We really don't. I can't see what would give rise to such a requirement.

**Comment by tobibeer** [comment]
Anyhow as to [Mario's first reply](https://github.com/Jermolene/TiddlyWiki5/issues/2000#issuecomment-147503240), this appears not about any defined default value but rather about the parser passing down `"undefined"` as the value when it's `undefined`.

So, following a pure javascript logic, this...

```
\define hello(a:"undefined", b)
hello $a$ $b$
\end

<<hello>>
```

Should actually produce...

```
hello undefined undefined
```

...but for obvious reasons it does not as we sure don't want it to.

So, the one and only chance for a js macro to know that a value is undefined is to not pass `undefined` as a string, for which I don't quite see a necessity at the parsing end. Or is there?

**Comment by tobibeer** [comment]
On the other hand, when I look at the RevealWidget it does quite the opposite of what I expect in...

```
RevealWidget.prototype.readMatchState = function(state) {
	this.isOpen = state === this.text;
};
```

Here, comparing against `text=""` will fail when there is no text field yet. This is quite troublesome for the reveal widget as now I have two conditions to check...

1. is there a state field?
2. does it have a specific value?

**Comment by Jermolene** [comment]
> What makes this a requirement? I hope it is not that consistency is somehow more important than expressivity. Simple wikitext macros and js macros already are fundamentally different, otherwise we would not need the latter. So why pretend they are not? The basic wikitext macro parser could very well silently transform undefined into "", which I believed it should do... but the above suggests it actually shouldn't.

JS macros and wikitext macros share a good deal of their implementation, that's why they need to be consistent.

**Comment by tobibeer** [comment]
It would be sufficient for a js macro to simply query for an array of those parameters that were actually undefined. If a macro author needs that (distinction), I do not see why we shouldn't allow it.
