### ISSUE TITLE
Can't sync tiddler titled `$:/templates/TableTiddler` under Node.js

### ISSUE THREAD

**Issue by danielo515** [Jermolene/TiddlyWiki5#2002]
Hello,

The following tiddler is not being saved under any instance of node, and I don't know why.

```
color: #ff00ff
created: 20151008113634545
creator: pene
modified: 20151008120306941
modifier: pene
tags: table
title: $:/templates/TableTiddler

```

I have exported it in order to be able to get the text file. The draft tiddler is saved without problems, but when I hit save, the draft tiddler is deleted, but the original tiddler is never saved to the FS.

Other tiddlers are being saved perfectly. 
Using TW 5.1.9

Regards

**Comment by tobibeer** [comment]
Not sure if that's what it is but I recently noticed that the core save filter isn't ok as it won't save any `[refix[$:/temp]]` whereas it should be `[refix[$:/temp/]]`... removing a bunch of tiddlers like yours from my node instance.

**Comment by Jermolene** [comment]
Thanks @danielo515 and @tobibeer good catch.
