### ISSUE TITLE
Introduce new theme with tighter spacing and less whitespace

### ISSUE THREAD

**Issue by Jermolene** [Jermolene/TiddlyWiki5#2008]
It is proposed to add a new theme that uses less whitespace and smaller fonts to pack more information.

This is the new "Tight" theme:

![screenshot 2015-10-09 17 56 11](https://cloud.githubusercontent.com/assets/174761/10400174/18bb700c-6eaf-11e5-83b9-9a10d7cefcee.png)

This is the standard "Snow White" theme for comparison:

![screenshot 2015-10-09 17 56 19](https://cloud.githubusercontent.com/assets/174761/10400178/22bd5110-6eaf-11e5-8110-736e04964927.png)

**Comment by inmysocks** [comment]
I like it.

**Comment by tobibeer** [comment]
If not existing, we might want a Theme-Preview tiddler somewhere with all the elements, e.g. buttons, tabs, etc... 

Do I understand right that the eventual story width depends on screen size? Then it might get a bit wide for some.

I guess, making the sidebar look plain as well possibly looked too simplistic, I guess.Not sure about the font, especially the bold headings look to emphasized. Perhaps make them a bit brighter, use the title font (if different), or even not bold?

**Comment by tobibeer** [comment]
Also, does a theme like this ship with "empty"? This one doesn't appear to be particularly appealing, to me. But maybe it is for others.

**Comment by inmysocks** [comment]
For shipping with the empty edition, I think that since we have the plugin library mostly figured out we could ship the empty edition with only snowwhite and just include good instructions for how to use the library to get other themes.

**Comment by Jermolene** [comment]
Hi @tobibeer - the empty edition just ships with the Vanilla and Snow White themes. Users will install the "Tight" theme through the plugin library.

> If not existing, we might want a theme-preview-tiddler somewhere with all the elements, e.g. buttons, tabs, etc...

The main effect of the theme is the layout of the page, a perhaps a full preview would be useful.

> Do I understand right that the eventual story width depends on screen size? Then it might get a bit wide for some.

The "Tight" theme is based on "Vanilla", and inherits the same themetweaks with respect to the story width.

> I guess, making the sidebar look plain as well possibly looked too simplistic. Otherwise, perhaps make it white too, with some left border'ish divider?

Don't forget that themes aren't supposed to be colour schemes; that's what palettes are for. Themes are concerned with layout.

I didn't make many changes to the sidebar but interested to see any experiments in that area.

> Not sure about the font, especially the bold headings look too emphasized / not too "pretty". After all this theme is very text-prominent, so the font defines greatly how things eventually look. Perhaps make headings a bit brighter / use the title font (if different) / even not bold? The fonts in the standard theme look a lot better.

The motivation for making the headings bold was so that they would stand out while still being relatively small. It's actually the same Helvetica Neue font as Vanilla, but different weights are used. I'd encourage you to experiment with the settings.

> For a general purpose theme, I also feel like the body begs for more padding. It feels a bit like it should not be so "tightly" pushed against the window edge or sidebar. But maybe that was the idea for the eventual usecase. At least the padding top, left and then also right should be as much as the top padding in the sidebar, if only so that things align, initially / when scrolled to.

Well, yes, the idea was to create a theme that tried to cram as much text as possible onto the screen. It's something that I need for a project now, and I'm releasing it because of the feedback we've had over the years that the default TW5 theme has too much whitespace compared to TWC.

**Comment by kookma** [comment]
can this issue be closed?

**Comment by Jermolene** [comment]
Thanks @kookma
