### ISSUE TITLE
integrate to a nodejs app

### ISSUE THREAD

**Issue by leizard** [Jermolene/TiddlyWiki5#2012]
Hi, I'm a node js beginner. I want to implement a wiki function in my app. Could I integrate TiddyWiki to my app as a function. If I could, what settings and customization need to be done ?

**Comment by leizard** [comment]
I think I ve solved it by using TiddlyWiki as a single page HTML app. Thank you

**Comment by tobibeer** [comment]
It's perhaps still recommendable to use node.js to manage the tiddlers individually, e.g. via some version control system, and then bake your wiki with it.

Also, what do you mean with "as a function"?

* to provide help?
* for a user of your app to edit?
