### ISSUE TITLE
Save and replace the old file

### ISSUE THREAD

**Issue by leizard** [Jermolene/TiddlyWiki5#2013]
When I edit the tw.html and press the save button. I want it to save and auto-replace the old file instead of having a windows popup and save to new file. How can I archive this ?
Thank you.

**Comment by felixhayashi** [comment]
You can use Firefox and install the TiddlyFox Firefox-Addon

* Old version: https://addons.mozilla.org/en-US/firefox/addon/tiddlyfox/
* Experimental version: https://github.com/TiddlyWiki/TiddlyFox

You can also run TiddlyWiki in nodejs mode then changes are autosaved in every browser.

-Felix

**Comment by leizard** [comment]
Hi @felixhayashi, thank you for replying.
I want it works in every browser and I have to use TW as a single page HTML app. It has the autosave settings but it doesnt seem to work.

**Comment by felixhayashi** [comment]
> I want it works in every browser and I have to use TW as a single page HTML app.

Autosave only works in firefox at the moment.

**Comment by leizard** [comment]
thank you @felixhayashi

**Comment by tobibeer** [comment]
This may help: [Downloads Overwrite Existing Files](https://chrome.google.com/webstore/detail/downloads-overwrite-exist/fkomnceojfhfkgjgcijfahmgeljomcfk?hl=en) for Chrome (not tested)

**Comment by felixhayashi** [comment]
> thank you @felixhayashi

no problem :)

**Comment by leizard** [comment]
Hi @tobibeer, thank you for your suggestion.
I should have made it clearer. I intergrate TW single page HTML in my app. Each user have their own copy of the TW HTML file. So when one user edit the HTML file and press the save button, the file should save to its current copy. Is there any chance that I can hook the save event of the save button and make it to save the way I want ?
Thank you for supporting

**Comment by felixhayashi** [comment]
> Is there any chance that I can hook the save event of the save button and make it to save the way I want ?

Unfortunately no, the only thing you can achieve via JavaScript is to trigger a download. You cannot tell any browser where to save the file. This would be a potential security threat for any system.

**Comment by Jermolene** [comment]
Hi @leizard 

> I should have made it clearer. I intergrate TW single page HTML in my app. Each user have their own copy of the TW HTML file. So when one user edit the HTML file and press the save button, the file should save to its current copy. Is there any chance that I can hook the save event of the save button and make it to save the way I want ?

You should be able to use the built-in "TiddlySpot" saver; it works by sending the entire wiki back to the server with an HTTP POST request.

You'll need code on your server to intercept that POST request, and save the HTML to file to the appropriate location for the user.

**Comment by leizard** [comment]
Thanks @felixhayashi , @Jermolene. It makes more sense now. I think I will try implement the way @Jermolene suggest and feed back ASAP.
Thank you again.

**Comment by pmario** [comment]
@leizard This seems to be an interesting usecase. I hope you'll share some results (your app) too :)

**Comment by leizard** [comment]
Thank you everyone for supporting me. Now I have another question.
When I clone a TW HTML page copy, I want the URL input in the Saving setting to be auto-filled with my server URL info. Is there any chance to do that ?

**Comment by tobibeer** [comment]
@leizard,

Testing [that chrome addon](https://github.com/Jermolene/TiddlyWiki5/issues/2013#issuecomment-147331355), I eventually came to realize that chrome has a bug that actually prevents it form working, replacing one problem with another.

I reported it to the chromium issue tracker here: [Issue 542559: BUG: download link forgets download directory](https://code.google.com/p/chromium/issues/detail?id=542559).

**Comment by leizard** [comment]
Hi @tobibeer, thank you for pointing that out.
Anyway, I'm working on the solution that @Jermolene suggested, which is using "TiddlySpot" saver and HTTP POST the entire wiki file to my server. So that I think I would not worry about the browser 's saving bug.

**Comment by pmario** [comment]
@leizard ... can you close this issue?

**Comment by Jermolene** [comment]
Thanks @pmario
