### ISSUE TITLE
Description of "TiddlyWeb and TiddlySpace components" and "Local filesystem syncadaptor" is confusing

### ISSUE THREAD

**Issue by maweki** [Jermolene/TiddlyWiki5#2019]
This might be me, but I found the description of this module confusing and it lead to me being stumped about unexpected behaviour for a few days.

So "TiddlyWeb and TiddlySpace components" says: "This plugin runs in the browser to synchronise tiddler changes to and from a TiddlyWeb-compatible server (including TiddlyWiki 5 itself). It is inert when run under Node.js."

I am running a tiddly-wiki-instance on node. I thought I wouldn't need this plugin, because I am running my instance under node.

Conversely, the plugin "Local filesystem syncadaptor" is described as "The filesystem plugin is used under Node.js to synchronise tiddler changes back to the file system. It is inert when used in the browser.".

So I thought "used in the browser" and "run under Node.js" meant, that I have it either run as a single html-file or from a node instance. But, and this might be a real issue and not a misunderstanding from my side, **if you disable "TiddlyWeb and TiddlySpace components", your changes from the interface are not saved back to the node instance**.

**Comment by pmario** [comment]
You are right. It's confusing. 

There is an open issue, that may solve the problem, but no solution atm. see: " Move tiddlywebadaptor and filesystemadaptor into the core" #1011

**Comment by maweki** [comment]
I guess this would solve the problem. The issue I had was that once "TiddlyWeb and TiddlySpace components" was disabled, saving back settings to the server didn't work, therefore re-enabling the plugin didn't work.

This makes the setting irreversible without access to the filesystem of the actual server. In that case, I'd think we maybe could add a warning that one is ill-advised to disable those core-modules or elaborate in the module description the functionality of the modules.

**Comment by pmario** [comment]
Just to be sure. 

 - You disabled the plugins from the TW control panel and not from `tiddlywiki.info`?
 - Since the plugins where active, it did save back to the server. 
 - Reloading the page created a TW site, that couldn't save back to the server since the plugins are deactivated now. 

I thought you where talking about a `tiddlywiki.info` configuration like this: https://github.com/Jermolene/TiddlyWiki5/blob/master/editions/tw5.com-server/tiddlywiki.info#L4

@Jermolene So imo this is a request for a new "do not disable this plugin, because we need it" feature.

**Comment by maweki** [comment]
Yes, this. I then needed to remove the disabled-plugin-tiddler from the filesystem of the server in order to regain control of the wiki.

Not being able to disable the plugin would be alright as well. As I said, I mainly was confused because I thought disabling the plugin that says "is inert when run under Node.js." was ok for an instance that was running under node so I didn't expect the behaviour of the wiki to change, but it "broke".

The saving-back-stuff, so I thought, was contained in the syncadapter-plugin that says "synchronise tiddler changes back to the file system".

**Comment by pmario** [comment]
>As I said, I mainly was confused because I thought disabling the plugin that says "is inert when run under Node.js." was ok for an instance that was running under node so I didn't expect the behaviour of the wiki to change, but it "broke".

Yes, changing the plugin info would be the first step. ... 

Can you please suggest a concrete wording, that would have helped you to understand the plugin functionality in the right way?

A pull request would be the best option here ;)

**Comment by tobibeer** [comment]
@maweki, for a while as a workaround for not knowing anything much about node commands, I was simply running this in the browser console to remove the server plugins and then save the wiki as as standalone clicking the **save** button...

```
$tw.wiki.deleteTiddler("$:/plugins/tiddlywiki/tiddlyweb");
$tw.wiki.deleteTiddler("$:/plugins/tiddlywiki/filesystem");
```

As of today I'll do this...

```
{
    "description": "tb5 contents",
    "plugins": [
        "tiddlywiki/tiddlyweb",
        "tiddlywiki/filesystem",
        "tiddlywiki/highlight"
    ],
    "themes": [
        "tiddlywiki/vanilla",
        "tiddlywiki/snowwhite"
    ],
    "build": {
        "index": [
            "--output","C:/GIT/tobibeer.github.io/tb5/",
            "--rendertiddler","$:/plugins/tiddlywiki/tiddlyweb/save/offline","index.html","text/plain"
        ]
    }
}
```

Notice how using `tiddlywiki --build` against this **tiddlywiki.info** will push the desired output file directly to my GitHub pages repository without any tiddlyweb plugins on board.

However, calling `tiddlywiki --server` will make the wiki available with the tiddlyweb plugins so I can edit things in the browser and have them pushed back to my local fs.

**Comment by pmario** [comment]
@tobibeer You should also link to your `$:/plugins/tiddlywiki/tiddlyweb/save/offline` tiddler, so we can see what it does. 

imo that's useful for #1011, but slightly OT here, since the OP is about some confusing plugin info description.

**Comment by maweki** [comment]
@tobibeer In my use case I have a node instance running on a raspberry pi and I have a git-repository of my tiddlers that are automatically committed and pushed. So for my use case, I would never want tiddly-wiki in a single file on the client.

**Comment by tobibeer** [comment]
ah, ok, yes, OT :-)

@pmario: it's the standard one from the tiddlyweb plugin

**Comment by pmario** [comment]
@maweki .. to make sure you see it :)

> Can you please suggest a concrete wording, that would have helped you to understand the plugin functionality in the right way?

**Comment by maweki** [comment]
@pmario Thanks. I've seen it. I just have to really try out what both modules *actually* do in order to find a less confusing wording. You don't need a pull-request to add "deactivating will break things". ;)

**Comment by maweki** [comment]
I've added a pull-request, adding a description for the thing that got me stuck.

I have yet to understand what the "Local filesystem syncadaptor" actually does since disabling it didn't make a difference for my use.
