### ISSUE TITLE
feature request: serverbuild command for node.js to serve a given build target

### ISSUE THREAD

**Issue by tobibeer** [Jermolene/TiddlyWiki5#2022]
As proposed here https://github.com/Jermolene/TiddlyWiki5/issues/1011#issuecomment-147946461 / an alternative for #1011:

Provide a `--serverbuild` command that essentially extends the `--server` command with a specified **build** target (as its first parameter?).

This appears to do away with requirements for extra server editions.

**Comment by Jermolene** [comment]
Hi @tobibeer to be clear, are you suggesting something like this:

```
tiddlywiki mywiki --serverbuild my-build 8080 $:/core/save/all text/plain text/html MyUserName passw0rd
```

And is the idea that the commands in the build section "my-build" would be executed before the server is started?

If so, why wouldn't one just do this:

```
tiddlywiki mywiki --build my-build --server 8080 $:/core/save/all text/plain text/html MyUserName passw0rd
```

**Comment by tobibeer** [comment]
> If so, why wouldn't one just do this

Good question. I think I can do that already. Closing.
