### ISSUE TITLE
extended filter syntax for variable arguments

### ISSUE THREAD

**Issue by tobibeer** [Jermolene/TiddlyWiki5#2029]
It happens ever so often that...
- one argument to a filter operator is highly limiting
- the suffix is all too limited in what it can be used for

I propose an extension to the filter syntax allowing to specify any given number of arguments for a filter opertor, e.g:

```
filter='[all[current]myfilter(foo:"bar" baz:<<mumble>> frotz:{{gronk}})]'
```

or ...

```
filter="""[all[current]myfilter(subfilter:"[[a][b][c]]")]"""
```

As an example syntax to insert items **A**, **B**, **C** after **ThisItem**:

```
filter="""[list[foo!!bar]insert(after:"ThisItem" items:"[[A][B][B]]")]"""
```

Below **SomeItem** is replaced with **NewItem**:

```
filter="""[list[foo!!bar]replace(what:"SomeItem" with:"NewItem")]"""
```

**Comment by tobibeer** [comment]
Ok, reading up on [Metabele's mangling widgets / filters](https://groups.google.com/forum/?fromgroups=#!folder/TiddlyWiki/tiddlywikidev/KR0ROFxHDRU), I believe there may already be some way to sneak multiple arguments into a filter, e.g.:

This takes the last three items of the list, namely **A**, **B**, **C**, and inserts them after **ThisItem**, if found, eventually removing **ThisITem**:

```
filter="[list[foo!!bar] A B C +insertafter:3[ThisItem] -ThisItem"
```

...could work just the same as the above:

```
filter="""[list[foo!!bar]insert(after:"ThisItem" items="[[A][B][B]]" remove="true")]"""
```

So, perhaps this is a viable way to pass multiple "arguments" to a filter operater by having them be list items.

**Comment by tobibeer** [comment]
What do you think, would using list items as arguments be a good design choice?

**Comment by tobibeer** [comment]
Consider even...

```
filter="""[
if(a={{foo!!bar}} is="") AND
if(b=<<baz>> not="mumble") OR
if(c={{frotz}} gt="3" as="int")
]"""
```

**Comment by Jermolene** [comment]
Hi @tobibeer this hasn't come up for a while, but my opinion is that we should avoid making the filter syntax any more complex. I think the best way for us to allow people to express complex logic is via an existing language, particularly JavaScript. There are now JavaScript parsers that are 2KB in size, so it's not unreasonable for us to parse a safe subset of JS for sandboxing.

So, I'd like to figure out how we'd support filters written in other languages. Then we can have plugin filter languages, and experiment with different approaches. (Given the important of list processing, maybe a language related to Lisp might be useful).

**Comment by saqimtiaz** [comment]
@tobibeer @Jermolene This has been resolved by support for multiple filter operands introduced in #4964

**Comment by Jermolene** [comment]
Thanks @saqimtiaz
