### ISSUE TITLE
complex conditions ...how?

### ISSUE THREAD

**Issue by tobibeer** [Jermolene/TiddlyWiki5#2033]
The current reveal mechanism simply seems too limited for complex conditions while multimple branches in the decision tree lead to undesirable verbosity but most of all refreshing of elements, e.g. inputs losing focus.

So, how can I possibly do...

```
<$list filter="[<answer>has[text]] OR ([<answer>!has[text]] AND [<state>has[text]])">

show answer editor only when we already have an answer or a state tells it to show
<$list>
```

?

This won't do, as the edit-text widget in the answer template loses focus with the first typed character...

```
<$list filter="[<answer>has[text]]" variable="none">
{{||$:/_my/templates/answer}}
</$list>
<$list filter="[<answer>!has[text]]" variable="none">
<$list filter="[<state>has[text]]" variable="none">
{{||$:/_my/templates/answer}}
</$list>
<$list filter="[<state>!has[text]]" variable="none">
<$button set=<<state>> setTo="yes" class="toggle-comment">
<$action-setfield $tiddler=<<answer>> text=""/>
Comment
</$button>
</$list>
</$list>
```

I tried reveals, yielding essentially the same problem.

**Comment by tobibeer** [comment]
I managed to get the above example working like so...

```
<$list filter="[<state>has[text]]" variable="none">
{{||$:/.sf/templates/answer}}
</$list>
<$list filter="[<state>!has[text]]" variable="none">
<$list filter="[<answer>!has[text]]" variable="none">
<$button set=<<state>> setTo="yes" class="toggle-comment">
Comment
</$button>
</$list>
</$list>
<$list filter="[<state>!has[text]]" variable="none">
<$list filter="[<answer>has[text]]" variable="none">
{{||$:/.sf/templates/answer}}
</$list>
</$list>
</$list>
```

**Comment by Jermolene** [comment]
> Anyhow, I'd definitely appreciate a more general approach.

The approach here seems right to me, and pretty general. Are you concerned that it's verbose?

**Comment by tobibeer** [comment]
Yes, I think the verbosity here is a wee bit of a trouble-maker, yielding the initial problem ...with no simpler way to express things more concisely, things at times even seem impossible, let alone impossible to manage.

On top of things, something like a reaveal in a reveal will create additional elements that may break html syntax, so I am bound to figuring things out using the list filter mechanism to get to the desired output unwanted elements, but not more.

I think these types of problems are tied in with #2029 and whichever older issues on this may be lingering about.

**Comment by Jermolene** [comment]
> Yes, I think the verbosity here is a wee bit of a trouble-maker,

At the widget layer, brevity is less of a goal than generality and flexibility. The idea has always been to use macros and specific wikitext syntax to express common idioms that benefit from abbreviation.

This particular example really seems to be another call for a more flexible filter syntax, as we've been discussing over at #2029.

> something like a reaveal in a reveal will create additional elements that may break html syntax

It's true that the reveal widget always creates a DOM element, but you know that you can control the element tag that is used?

**Comment by tobibeer** [comment]
> It's true that the reveal widget always creates a DOM element, but you know that you can control the element tag that is used?

Yes, I think I was the one to make the initial at the time a bit too highly debated PR for it. ;-)

**Comment by tobibeer** [comment]
@Jermolene, I think I have come to a solution (!). Here's how that could work:

A new **filter** filter could run a given filter expression against the input set:

```
<$set name="planets-in-system" value="[tag[planet]field:solar_system<this_system>]">
{{{ [tag[star_system]field:quadrant[Alpha Quadrant]filter:this_system<planets-in-system>]] }}}
</$set>
```

How would this work?

1. define a variable called **planets-in-system** specifying a filter expression referencing a variable called **this_system**
2. evaluate this filter expression against the titles fetched as **star_system** in the **Aplha Quadrant**
    * while replacing the variable **this_system** with each item in this input set

This would allow to join an arbitrary number of conditionals / filters in one filter expression.

**Comment by Jermolene** [comment]
Thank you @pmario
