### ISSUE TITLE
Actual use of TextReference as attribute of ButtonWidget does not match documentation

### ISSUE THREAD

**Issue by afeldspar** [Jermolene/TiddlyWiki5#2038]
The documentation for the [ButtonWidget](http://tiddlywiki.com/#ButtonWidget) says that the "set" attribute takes a TextReference as its value.

The documentation for [TextReference](http://tiddlywiki.com/#TextReference) says that they can be used:  "As IndirectAttributes of an element or widget (eg, `<$widget attrib={{Title!!description}}/>`)" .

Based on this, one would expect to write a button that sets a field as follows:

```
<$button set={{MyTiddler!!bazstate}} setTo="curlybaz" >
set the baz
</$button>
```

But this form does not work.

The following two forms work:

```
<$button set=MyTiddler!!bazstate setTo="nocurlybaz" >
set the baz
</$button>
```

```
<$button set="MyTiddler!!bazstate" setTo="quotebaz" >
set the baz
</$button>
```

but there is nothing in the documentation to indicate that these should work, when the only example shown of a TextReference being used as a widget attribute shows it in the curly brackets.

**Comment by inmysocks** [comment]
I agree that the documentation is missing a lot when it comes to text references. The curly braces are a transclusion so presumably the text reference is contained in MyTiddler!!bazstate when using curly braces, so {{MyTiddler!!bazstate}} becomes MySecondTiddler. There was some disagreement about how explicit the text reference explanation should be.

**Comment by Evolena** [comment]
Try

```
<$button set={{MyTiddler!!bazfield}} setTo="curlybaz" >
set the baz
</$button>
```
with MyTiddler having a field **bazfield** = `MyTiddler!!bazstate`, to illustrate @inmysocks answer.

*Stricto sensu*, the TextReference is only the `tiddler!!field` part, but it is most used in combination with a transclusion.
It would certainly be useful to find how to explain that better in the docs.

**Comment by afeldspar** [comment]
If I'm understanding this correctly - which I think I am, thanks to your explanation, the core of the explanation is:  "When you use a TextReference to a field as the 'set' attribute of a ButtonWidget, you are referring to //the field itself//, not transcluding the //contents// of the field.  Because you are not transcluding, you leave out the curly brackets."

If that explanation is correct, then I think this issue could be resolved just by including that explanation (in somewhat neater language, perhaps) in the documentation for the ButtonWidget.

**Comment by pmario** [comment]
@afeldspar .. IMO can be closed. Additional info has been merged.

**Comment by Jermolene** [comment]
Thanks @pmario
