### ISSUE TITLE
Consistent display of tiddlers links in lists, in particular toc macros (generic use of $:/core/ui/ListItemTemplate)

### ISSUE THREAD

**Issue by erwanm** [Jermolene/TiddlyWiki5#2044]
Currently the way internal links are displayed is consistent in the following types of lists:

* search results
* "More" tab in sidebar (All, Drafts, Orphans, ...)
* dropdown list from a tag pill ($:/core/ui/TagTemplate)
* TiddlerInfo tabs from the tiddler view toolbar

This consistency is achieved by using the template $:/core/ui/ListItemTemplate in all these lists. This is very useful when one wants to customize tiddlers links in lists, for example:

* use case 1: in the [CommunitySearch wiki](http://erwanm.github.io/tw-community-search), all extracted tiddlers links are "forwarded" to the original wiki. A custom version of $:/core/ui/ListItemTemplate concatenates the wiki address and the tiddler title in order to show a permalink  to the target wiki, instead of showing the internal link.
* use case 2: In my task management system, some tiddlers have a field "task-status" which can be "active" or "done". A custom version of $:/core/ui/ListItemTemplate shows a checkbox in front of the tiddler link if the tiddler has the "task-status" field, in order to change the status easily from any list where the task tiddler appears.

However the toc-xxx macros (defined in $:/core/macros/toc) do not use $:/core/ui/ListItemTemplate. It seems relevant to extend the consistency described above to these types of lists, by making the toc macros use $:/core/ui/ListItemTemplate as well. However 

* which field should be displayed? Currently toc macros use "caption" if defined and "title" otherwise, whereas $:/core/ui/ListItemTemplate always uses the title. This question seems to depend on the conclusion of #922.
* currently the different types of macros use the same macro toc-caption to show an entry, in particular both the "toc-linked..." (items as links) and "toc-unlinked" (items as plain text). The proposed change would require the former to use $:/core/ui/ListItemTemplate and not the latter.
* css styles compatibility?

What do you experts think? There might also be other pitfalls I didn't think about. 

Below a copy of `toc-caption` and `$:/core/ui/ListItemTemplate` for convenience:

````
\define toc-caption()
<$set name="tv-wikilinks" value="no">
<$transclude field="caption">
<$view field="title"/>
</$transclude>
</$set>
\end
```

```
<div class="tc-menu-list-item">
<$link to={{!!title}}>
<$view field="title"/>
</$link>
</div>
```

**Comment by Jermolene** [comment]
Hi @erwanm, interesting, thanks.

As you note, it would be hard to switch `$:/core/ui/ListItemTemplate` to use the caption field without changing the semantics of the sidebar lists. I think perhaps list items are distinct from toc items; perhaps we need a separate `$:/core/ui/TableOfContentsLinkTemplate`

I've wondered if it wouldn't be useful to create a widget that specifies a template to be applied all links within its scope. It would make it easier to render hover previews, for example, without needing the links to be marked up specially.

**Comment by erwanm** [comment]
I thought about a potential workaround for the caption/title problem: would it be possible for `$:/core/ui/ListItemTemplate` to use the field provided with a variable, say `<<field-to-use-as-title>>`, and if this variable is not defined, use `title` by default?

(actually I was trying to experiment with this when I stumbled on [this problem](https://groups.google.com/forum/#!topic/Tiddlywiki/5Wzk60R12Jw))

**Comment by Jermolene** [comment]
Hi @erwanm parameterising the template in that way is reasonable. But the conditional coding is likely to impact the performance of the template; using switchable templates for links avoids that problem.

**Comment by erwanm** [comment]
Hi @Jermolene, I tried to implement this on http://test-generic-list-item.tiddlyspot.com/.

Basically I used a "sub-template" `$:/core/ui/ListItemLinkTemplate` which only creates a link with the text provided in a variable. This way both the `$:/core/ui/ListItemTemplate` and the toc macros use it (by assigning either caption or title to the variable), and any customization on all the list items links can be done by modifying only `$:/core/ui/ListItemLinkTemplate`.

* in terms of performance, I was assuming that adding a transclusion is better than adding a condition with a filter, is that correct?
* there is a problem that I wasn't able to solve with the tabbed toc: an extra line break inserted before the link.
 * a similar problem occurs when using the "custom version" of `$:/core/ui/ListItemLinkTemplate`
* I also simplified the toc macros by using macrocall: this way no need for a "linked" and an "unlinked" version.

**Comment by erwanm** [comment]
Sorry @Jermolene, just after my previous comment I found a better way to do it without having to transclude another tiddler. I realized it's possible by using only a macro in `$:/core/ui/ListItemLinkTemplate` like this:

```
\define view-title-if-undef-field(field:"title") <$view field=$field$/>

<div class="tc-menu-list-item">
  <$link>
    <$macrocall $name="view-title-if-undef-field" field=<<tv-view-field-as-link>> />
  </$link>
</div>
```
I created another wiki with this solution here: http://test-generic-list-item-v2.tiddlyspot.com/

There are still some issues with line breaks though, I assume this is about css classes.

**Comment by tobibeer** [comment]
> I've wondered if it wouldn't be useful to create a widget that specifies a template to be applied all links within its scope. 

Sounds by far the cleanest approach to me.
I would make it generic, though, not just link-specific, e.g.:

```
<$template for="links" template="$:/core/ui/ListItemTemplate">
applied here
</$template>
```

**Comment by Jermolene** [comment]
Hi @erwanm 

>  I realized it's possible by using only a macro in `$:/core/ui/ListItemTemplate` like this:

There are significant performance implications to introducing a macro. The trouble is that when the value of a macro changes it has to be entirely reparsed, which is much slower than just processing widget refresh calls.

Anyhow, I'd suggest exploring with the new "performance monitoring" setting that's in 5.1.10-prerelease.

**Comment by erwanm** [comment]
@Jermolene oh ok, I didn't know. Then I guess the first version at http://test-generic-list-item.tiddlyspot.com/ is the best I can come up with.

About the widget which applies a template to links within its scope, it could certainly be useful but I don't see how this would help with the case I described. As far as I understand such a widget would only apply locally, whereas customizing `$:/core/ui/ListItemTemplate` has an effect in many places where lists of links are used.

**Comment by tobibeer** [comment]
@erwanm, there's actually two sides to this

1) one to override a global template
2) to override the applicability of a (global) template

I think the second one is by far more flexible, by design. Wouldn't you agree?

**Comment by erwanm** [comment]
@tobibeer if you mean that there should be only one "best way" to override a global template, I don't quite agree actually ;)

To me the two approaches serve different purposes: the latter offers more flexibility indeed, but on the contrary the former offers more generality. 

As far as I understand, in order to obtain the same result as modifying $:/core/ui/ListItemTemplate but with a `<$template>` widget instead, I would have had to modify at least 4 or 5 other shadow tiddlers (`$:/core/ui/ListItemTemplate` is used in 16 tiddlers apparently). Since it's best to override as few core tiddlers as possible in order to keep the code maintainable w.r.t core updates, I don't see how the widget would be a better option in cases like the two I described above. 

nevertheless it's completely possible that something eludes me with this solution, I certainly haven't explored all the mysteries of TW yet!

**Comment by tobibeer** [comment]
The toc macro should probably introduce its own `$:/core/ui/TocItemTemplate` which one could easily override to transclude the `$:/core/ui/ListItemTemplate` or a customized version of it.

Those 16 occurences would change / go away and perhaps be replaced by something like...

```
<$list filter="foo" template=<<tv-list-item-template>>/>
```

It appears that, rather than a widget-wrapper, we'd perhaps be better advised to use "template variables" to cater for more customizability?

There'd be a global spot defining...

```
\define tv-list-item-template() $:/core/ui/ListItemTemplate
```

And then you could override it wherever you needed, e.g. in the toc macros:

```
<$set name=tv-list-item-template value=<<tv-toc-item-template>>>
toc macro stuff
</$set>
```

**Comment by erwanm** [comment]
@tobibeer this seems likes a very good solution to me, it can be used in different ways, locally or globally, etc.
I didn't realize that there was this possibility to define a variable globally, interesting.

**Comment by erwanm** [comment]
Cleaning up non-actionable (and minor) issue
