### ISSUE TITLE
$tw.utils.count(obj) vs. Object.keys(obj).length

### ISSUE THREAD

**Issue by felixhayashi** [Jermolene/TiddlyWiki5#2046]
Hi @Jermolene,

since it is used at several places in the core, especially during refresh, I think it would make sense and improve speed if `$tw.utils.count(obj)` is abandoned in favor of `Object.keys(obj).length` in the core. Or am I missing something?

-Felix

**Comment by Jermolene** [comment]
Hi @felixhayashi that sounds reasonable; let's have some performance tests before we go ahead though.

**Comment by felixhayashi** [comment]
Hi @Jermolene 

`Object.keys()` is faster on my computer in Chrome:

```javascript
var rounds = 10000000;

console.time("count");
for(var i = rounds; i--;) {
  $tw.utils.count({ a: 1, b: "2", c: true });
}
console.timeEnd("count");

console.time("keys");
for(var i = rounds; i--;) {
  Object.keys({ a: 1, b: "2", c: true }).length;
}
console.timeEnd("keys");
```

Results:

![2015-10-26 15 47 03](https://cloud.githubusercontent.com/assets/4307137/10732123/d4d45e9c-7bf8-11e5-8edd-85c1476e35b7.png)

Have a try :)

**Comment by Jermolene** [comment]
Hi @felixhayashi great, do go ahead with a pull request.

**Comment by felixhayashi** [comment]
Hi @Jermolene 

> Hi @felixhayashi great, do go ahead with a pull request.

Ok, I am done. PR exists.
