### ISSUE TITLE
Example Issue

### ISSUE THREAD

**Issue by tgrosinger** [Jermolene/TiddlyWiki5#2050]
This is not actually an issue, it just nicely demonstrates the checklist

- [ ] Item 1
- [x] Item 2
- [x] Item 3

**Comment by tgrosinger** [comment]
Sorry, meant to create this in a different project

**Comment by tobibeer** [comment]
Some context: https://groups.google.com/d/msg/tiddlywikidev/9_dkrbY7-EM/Am9b4xDRAAAJ
