### ISSUE TITLE
Can we extend filtering to allow iterated filters without nested lists?

### ISSUE THREAD

**Issue by inmysocks** [Jermolene/TiddlyWiki5#2051]
This isn't the same as using multiple filter runs. If you want to use a filter to find all tiddlers with a field (any field, not a specific field) that contains a string currently you need to do something like this:

```
<$list filter='[!is[system]]' variable=TiddlerName>
<$list filter='[<TiddlerName>fields[]]' variable=FieldName>
<$list filter='[<TiddlerName>get<FieldName>search:title[SearchString]]'>

<<TiddlerName>>

</$list>
</$list>
</$list>
```

which will give you the correct list, but if a tiddler has multiple fields that match the search criteria it will be listed once for each match.

What I would like to be able to do is put all of that into one list widget like this:

```
<$list filter='[!is[system]]' variable=TiddlerName, filter='[<TiddlerName>fields[]]' variable=FieldName, filter='[<TiddlerName>get<FieldName>search:title[SearchString]]'>

<<TiddlerName>>

</$list>
```

where it acts the same as the nested list and does each filter in order applying it to every output from the previous filter, but the output is a single list so that the entire output can be sorted and duplicate entries can be removed and so on.

I don't know how difficult it would be to extend the list widget to do this. The simplest implementation wouldn't be difficult but ensuring that it doesn't break anything else may be difficult.

**Comment by Jermolene** [comment]
@inmysocks I edited your post to add code formatting.

I was thinking along slightly different lines: to add a new `source` attribute to the list and set widgets that contains a literal list of titles to be used as the source list for the filter.

Then your example could be done like this:

```
<$set name="TiddlerName" filter="[!is[system]]">
<$set name="TiddlerName" source=<<TiddlerName>> filter="[fields[]]">
<$list source=<<TiddlerName>> filter="[get<FieldName>search:title[SearchString]]">

<<TiddlerName>>

</$list>
</$set>
</$set>
```

**Comment by inmysocks** [comment]
That looks good. The source aspect of it would be a simpler change than what I was thinking, but for that example we would also need to allow filter operators to be passed a list. Both would be large improvements but would be separate improvements.

Doing that would allow what I would like and would make filters even more flexible. The biggest problem I can see is if you have two separate lists like this:

```
<$set name="TiddlerName" filter="[!is[system]]">
<$set name="SearchString" filter="[<SomeDataTiddler>indexes[]]">
<$set name="FieldName" source=<<TiddlerName>> filter="[fields[]]">
<$list source=<<TiddlerName>> filter="[get<FieldName>search:title<SearchString>]">

<<TiddlerName>>

</$list>
</$set>
</$set>
</$set>
```

I that you have a typo and the second variable is supposed to be FieldName.

**Comment by Jermolene** [comment]
Hi @inmysocks isn't the problem with your example that the `get` filter operator expects a single value, not a list?

**Comment by tobibeer** [comment]
I think he wants / needs all three filters to actually be one chained filter expression, that allows to "catch" outer matches depending on whether or not there are inner matches. This is essential to any (even recursive) matching.

Consider a tree with some root items. Now, you only want to show those (root) items that...

* match themselves
* have matching children

Currently there is no way to construct such a filter. For example, imagine this toc...

* foo
    * **bar**
        * baz
* mumble
* **frotz**
    * gronk

As we do a search and we find that **bar** and **frotz**, all **bold**ly, match the query.

The missing link is the ability to display the search results tree thusly:

* foo
    * **bar**
* **frotz**

**Comment by inmysocks** [comment]
One thing I have thought about making to avoid some trouble is a getfields operator that acts like the fields operator but instead of the field names it returns the field contents. The thing I am finding most frustrating about this is that I can't describe the problem so I can't determine which solutions are equivalent outside my narrow examples. So forgive me if I am a bit imprecise here.

@Jermolene I hadn't thought of it like that. I am not certain if it addresses what I am thinking about, once again no complete description of the problem, but I don't think my example is as clear as I should have made it. In the inside I would like to be able to have the tiddler name, the name of the matching fields and the contents of the matching fields. Currently this can only be done in ways that list the tiddler once for each matching field. The generic search and replace tool I have been working on runs into this problem. Looking at it closer I don't know how you would associate the contents of each matching field with the field title and containing tiddler. I think that both parts of what you suggest would be very helpful but it may not completely address what I am thinking about.

@tobibeer since I have not had much success making a complete description of the problem I can't be sure but your description may be complete. I am having trouble thinking about it at the moment.

**Comment by tobibeer** [comment]
@inmysocks, try to think in and describe the actual goal(s) you wish to achieve more, the what (and possibly why) on the most general level, and to only talk implementation (the how) after that is clearly defined

So...

> Can we extend filtering to allow iterated filters without nested lists?

...talks about how you think of doing something, a solution, rather than what and why ...your requirement(s) ...the key is always to understand first what the true requirement is on a non-technical level
