### ISSUE TITLE
list accessors for variables and text references

### ISSUE THREAD

**Issue by tobibeer** [Jermolene/TiddlyWiki5#2057]
As discussed in #2035, provide a way to interpret content as a list, e.g.:
- `<<myListVariable[1]>>`
- `{{!!my-list-field[0]}}`
1. operations interpreting a field or a variable as a list use `$tw.utils.parseStringArray()` to convert the value as needed
   1. for efficiency, consider caching
2. similarly, writing a list to a variable or field stringifies the list
   - @Jermolene: where? in action widgets? which "list" is it that we would stringify?
## Considerations
1. Shall we use array indexes starting from `0` or more "natural" indexes starting at `1`?
2. Shall we allow to also read the length, e.g. `{{!!my-list-field[].length}}`?
   - or perhaps a more "natural" `{{!!my-list-field[].count}}`?
3. Should we even go so far as to allow chaining? e.g.:
   - `{{myListVariable[1]!!some-field}}` or even:
   - `{{myListVariable[1]!!list[1]!!some-field}}`

**Comment by pmario** [comment]
@Jermolene ... As I wrote a combination of enlist and nth can read list-like elements: `[enlist[one two three]nth[1]]` and [format:titlelist](https://tiddlywiki.com/#format%20Operator) can write to list-like fields. 

So imo this one can be closed

**Comment by Jermolene** [comment]
Thank you @pmario
