### ISSUE TITLE
codemirror markdown.js gives "undefined" error executing boot module

### ISSUE THREAD

**Issue by cjp** [Jermolene/TiddlyWiki5#2059]
## Error

![Error executing boot module $:/plugins/tiddlywiki/codemirror/mode/markdown/markdown.js: undefined]
(https://cloud.githubusercontent.com/assets/161960/10936960/e578e01c-82bd-11e5-850c-76b5844f9a86.png)
> Error executing boot module $:/plugins/tiddlywiki/codemirror/mode/markdown/markdown.js: undefined

## Test Environments

* FIrefox 41.0.2, Mac OS X 10.11.1 `Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:41.0) Gecko/20100101 Firefox/41.0`
* Google Chrome, 46.0.2490.80 (Official Build) (64-bit), Mac OS X 10.11.1 `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.80 Safari/537.36`

## Process

I first ran into this problem using TiddlyWiki5 under node.js, but just duplicated it the standalone way.

1. Create new TiddlyWiki5 from Download Empty on http://tiddlywiki.com
2. Install CodeMirror plugin. Reload.
3. Create tiddler `$:/plugins/tiddlywiki/codemirror/mode/markdown/markdown.js` with `module-type: library` and `application/javascript` from the text at https://raw.githubusercontent.com/codemirror/CodeMirror/master/mode/markdown/markdown.js.
4. Create tiddler `$:/config/CodeMirror` containing:

        {
          "require": [
              "$:/plugins/tiddlywiki/codemirror/mode/javascript/javascript.js",
              "$:/plugins/tiddlywiki/codemirror/mode/markdown/markdown.js"
          ],
          "configuration": {
              "showCursorWhenSelecting": true
          }
        }

5. Create tiddler `$:/config/EditorTypeMappings/text/x-markdown` containing `codemirror`.
6. Save. Load saved.

## Notes

This problem does not occur with codemirror's clike.js. It seems to be related specifically to markdown.js. I also attempted to use the markdown.js code that was current at that time of the TW 5.1.9 release; same behavior occurred.

Not being very adept at js, I'm not really certain on the next troubleshooting steps.

**Comment by cjp** [comment]
`$:/plugins/tiddlywiki/codemirror/mode/markdown/markdown.js` requires `$:/plugins/tiddlywiki/codemirror/mode/xml/xml.js` and `$:/plugins/tiddlywiki/codemirror/mode/meta.js`. Once those are in place (with `module-type: library` correctly set) and are properly added to `$:/config/CodeMirror`, it works.

**Comment by Jermolene** [comment]
Hi @cjp thanks for the detailed report, very helpful for others.

**Comment by MickMorley** [comment]
Hi, this is happening to me when adding `$:/plugins/tiddlywiki/codemirror/mode/powershell/powershell.js` and it looks like the `$:/plugins/tiddlywiki/codemirror/mode/meta.js` is not updated to the latest syntax from https://raw.githubusercontent.com/codemirror/CodeMirror/master/mode/meta.js.  i.e. - it is missing the PowerShell declaration `{name: "PowerShell", mime: "application/x-powershell", mode: "powershell", ext: ["ps1", "psd1", "psm1"]}, `

I've updated `$:/plugins/tiddlywiki/codemirror/mode/meta.js` by copying https://raw.githubusercontent.com/codemirror/CodeMirror/master/mode/meta.js directly from the codemirror repository.

`$:/plugins/tiddlywiki/codemirror/mode/powershell/powershell.js`  is set to `module-type: library` and are added to `$:/config/CodeMirror`

The issue still persists.

![a](https://cloud.githubusercontent.com/assets/19698105/25720797/24e2405e-30dc-11e7-8311-812fc1d558e9.JPG)

**Comment by MickMorley** [comment]
The code from `https://raw.githubusercontent.com/codemirror/CodeMirror/master/mode/powershell/powershell.js` is incorrect.

I've copied the declaration statement from `https://raw.githubusercontent.com/codemirror/CodeMirror/master/mode/javascript/javascript.js` and applied it to `$:/plugins/tiddlywiki/codemirror/mode/powershell/powershell.js`. All is working now.

**Comment by ywiyogo** [comment]
I still don't understand how to fix the error. Could you explain me how to fix it in my html file of tiddlywiki?

**Comment by BurningTreeC** [comment]
@ywiyogo what kind of error do you get and which codemirror plugin version are you using? what's the version of your tiddlywiki where you get the error?

**Comment by ywiyogo** [comment]
I have the same error message as above: 
```
Internal JavaScript Error
Well, this is embarrassing. It is recommended that you restart TiddlyWiki by refreshing your browser
Error executing boot module $:/plugins/tiddlywiki/codemirror/edit-codemirror.js: undefined
```
My TiddlyWiki has 5.1.9 and the CodeMirror plugins has version 5.1.16.

**Comment by ywiyogo** [comment]
Ok, I realized that my tiddlywiki version is kind of old. After updating the Tiddlywiki to 5.1.16, the error does not appear again.
Thanks @BurningTreeC to mention the tiddlywiki version.
