### ISSUE TITLE
virtual fields

### ISSUE THREAD

**Issue by tobibeer** [Jermolene/TiddlyWiki5#2064]
To cater for #2063, with efficient caching in mind, introduce *virtual fields* that are not actual fields of tiddlers but rather — perhaps on the basis of a filter expression — are more like "formula fields" that store / cache their computational output with respect to each tiddler.

They could be addressed via TextReferences like so:

```
{{!!!count-tagging}}
```

For each virtual field, there should be a way to configure:

* a virtual field name
    * `count-tagging`
* a filter expression specifying the kind of "formula" defining how the virtual field is computed
    * `[<currentTiddler>tagging[]count[]]`
* perhaps a filter expression specifying tiddlers to which the formula is applied

This would also provide a flexible basis catering for tabular displays that allow column-wise sorting / filtering, instead of recalculating the fields at every possible turn.

For efficiency, it may be needed to not have those constantly live-updated but at defined moments.

**Comment by tobibeer** [comment]
An alternative to using evaluated filter expressions, especially with respect to mathematical formulas, could be to actually use widget syntax, as is the case for the calc widget from https://github.com/mklauber/tiddly-mathjs.

**Comment by mklauber** [comment]
Of particular help is that <$calc> widgets are nestable.  Therefore, if you can embed an expression in one field, you can transclude that field (and thus that expression) into another field and use it as part of another expression.

**Comment by twMat** [comment]
(solved with the upcoming wikify widget #2337 ? Or maybe that's a totally different matter...?)

**Comment by Jermolene** [comment]
@twMat I don't see a relationship between this idea and the wikify widget; there may be some use cases that could be solved with either approach, but in general they wouldn't be substitutable.

From my perspective, this virtual fields idea is a non-starter because it changes/breaks the principles of the core to the extent that it would be a rewrite of the wiki and tiddler objects.

**Comment by twMat** [comment]
Ok, thanks.

**Comment by tobibeer** [comment]
> non-starter
