### ISSUE TITLE
has:field

### ISSUE THREAD

**Issue by tobibeer** [Jermolene/TiddlyWiki5#2065]
Allow to filter tiddlers by whether or not they have a field, regardless of any field value. For that purpose, we could allow to specify a suffix to the **has** filter, e.g.
- `has:field[f]`<br>all items where the field f is defined, empty or otherwise
- `!has:field[f]`<br>all items items that do not have field f
  - so, no items where the field exists but is blank

currently:
- `has[f]`<br>all items where the field f is defined and non-empty
- `!has[1]`<br>all items where the field f is not defined or empty
## related discussion

https://groups.google.com/d/msg/tiddlywiki/XP_uCVmE760/ix1jb_XWAgAJ

**Comment by Jermolene** [comment]
Adding the suffix is a good idea, but we should also establish the suffix that corresponds to the current default, suffix-less form. Perhaps `has:value[f]` might be equivalent to `has[f]`.

**Comment by tobibeer** [comment]
:+1:

**Comment by pmario** [comment]
@Jermolene ... I think this one can be closed, since the function has been implemented in 5.1.14

**Comment by Jermolene** [comment]
Thanks @pmario
