### ISSUE TITLE
building from a fork

### ISSUE THREAD

**Issue by tobibeer** [Jermolene/TiddlyWiki5#2071]
I want to build from my fork of the TiddlyWiki5 repo. Is there a simple way to switch between / register my fork folder and then later back to the installed version for the `tiddlywiki --build` command in the node  console?

**Comment by Jermolene** [comment]
One way would be to run `npm link` in the repo you want to use; you could create a batch file to switch.

**Comment by tobibeer** [comment]
Ah, thanks, I believe that's what I've seen before. Just couldn't find a reference.

How would I switch back to the installed one: navigate to the install folder and run npm link?

**Comment by Jermolene** [comment]
Hi @tobibeer yes exactly that. I assume that nam link can take a directory as an argument, rather than having to navigate there first.

**Comment by tobibeer** [comment]
Ah, ok, so a batch file it is ;-)

**Comment by pmario** [comment]
why do you need to mess around with npm here?
Just us `git checkout` from your branch

**Comment by pmario** [comment]
What does the command `git remote -v` show you in your tw5 repo?

mine looks like this: 

```
jermolene       https://github.com/Jermolene/TiddlyWiki5.git (fetch)
jermolene       https://github.com/Jermolene/TiddlyWiki5.git (push)
origin  git@github.com:pmario/TiddlyWiki5.git (fetch)
origin  git@github.com:pmario/TiddlyWiki5.git (push)
tobibeer        https://github.com/tobibeer/TiddlyWiki5.git (fetch)
tobibeer        https://github.com/tobibeer/TiddlyWiki5.git (push)
```

So I can build from your repo, Jeremys and mine and any other, if I connect it.

**Comment by tobibeer** [comment]
Mine looks like this:

```
Jermolene       https://github.com/Jermolene/TiddlyWiki5.git (fetch)
Jermolene       https://github.com/Jermolene/TiddlyWiki5.git (push)
origin  https://github.com/tobibeer/TiddlyWiki5.git (fetch)
origin  https://github.com/tobibeer/TiddlyWiki5.git (push)
upstream        https://github.com/Jermolene/TiddlyWiki5.git (fetch)
upstream        https://github.com/Jermolene/TiddlyWiki5.git (push)
```

as for `npm link`, I'm just following instructions

I imagine **npm** simply registers the tiddlywiki package as found in a given folder, rather than the one previously installed globally via **npm** (from the npm repo) ...but then I wouldn't know, just guessing

**Comment by tobibeer** [comment]
@Jermolene, ok, I am having trouble setting it back to the installed version.

This won't work:

```
cd C:\Users\Owner\AppData\Roaming\npm\node_modules\tiddlywiki
npm link
```

Error:

```
C:\Users\Owner\AppData\Roaming\npm\node_modules\tiddlywiki>npm link
npm ERR! Windows_NT 10.0.10240
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "link"
npm ERR! node v4.2.1
npm ERR! npm  v2.14.7

npm ERR! May not delete: C:\Users\Owner\AppData\Roaming\npm\node_modules\tiddlywiki
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Owner\AppData\Roaming\npm\node_modules\tiddlywiki\npm-debug.log
```

I can rerun this...

```
npm install -g tiddlywiki
```

...but that doesn't seem the right approach.

**Comment by tobibeer** [comment]
@pmario, any experience with the above?

**Comment by Jermolene** [comment]
It looks like `npm unlink` might be the answer:

http://stackoverflow.com/questions/19094630/how-do-i-uninstall-a-package-installed-using-npm-link

**Comment by tobibeer** [comment]
Ah, of course, that was it, grr... taking notes.

**Comment by pmario** [comment]
Your question was: "building from a fork". Imo there is absolutely no need to mess with npm link. ... I'm obviously missing something.

**Comment by tobibeer** [comment]
Possibly you are. If I just run...

`tiddlywiki --some-commands`

...in the console, it picks up the default install as expected, not the fork I am trying to build some test output for. Of course, I could also just point to the tiddlywiki.js file of the fork, but why do all the typing?

**Comment by pmario** [comment]
ok. I see. 

I'm using: `node tiddlywiki.js --some-command ` which imo is much easier and doesn't require to globally install tw. 

Changing the tiddlywiki branch is as easy as `git checkout <your-feature-branch-here>`. 
If I'm connected to your github repo, I can easily pull your content and test it. Same with stuff from Jeremy, or my own branches.

**Comment by tobibeer** [comment]
Not sure I understand how node finds it, I guess it just looks for it in parent folders. Never really thought about not doing a global install.

One situation that would be more difficult without a global install would be my repos where there is no tiddlywiki install, but just a plugin or tb5 content.

**Comment by pmario** [comment]
Finding plugins, themes, languages and editions should be as easy as setting proper env variables. see: http://tiddlywiki.com/#Environment%20Variables%20on%20Node.js

**Comment by tobibeer** [comment]
@pmario, I'm having trouble with exactly that. I'd be happy if you could look at...

https://groups.google.com/d/msg/tiddlywikidev/0-A6hRGJh_I/ZhOSeD9BBgAJ

Thanks.

**Comment by tobibeer** [comment]
Ok turns out I'm not all the way there yet when it comes to `npm unlink`, it doesn't actually seem to work. Maybe I actually do always need to reinstall the core distro after having first `npm link`ed the fork? But what purpose would `npm unlink` serve then?

```
C:\GIT\TiddlyWiki5>npm link
C:\Users\Owner\AppData\Roaming\npm\tiddlywiki -> C:\Users\Owner\AppData\Roaming\npm\node_modules\tiddlywiki\tiddlywiki.js
C:\Users\Owner\AppData\Roaming\npm\node_modules\tiddlywiki -> C:\GIT\TiddlyWiki5

...

C:\GIT\tw5-dict>tiddlywiki --build
syncer-server: Dispatching 'load' task: Tobias Beer
syncer-server: Dispatching 'save' task: $:/StoryList
FileSystem: Saved file C:\GIT\tw5-dict\tiddlers\system\StoryList.tid

...

C:\GIT\TiddlyWiki5>npm unlink
unbuild tiddlywiki@5.1.10-prerelease

...

C:\GIT\tw5-dict>tiddlywiki --build
module.js:339
    throw err;
    ^

Error: Cannot find module 'C:\Users\Owner\AppData\Roaming\npm\node_modules\tiddlywiki\tiddlywiki.js'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Function.Module.runMain (module.js:467:10)
    at startup (node.js:134:18)
    at node.js:961:3
```

**Comment by pmario** [comment]
i'll test it with my repos.

**Comment by pmario** [comment]
Tiddlywiki has some expectations to the directory structure. 

As the variable name says `TIDDLYWIKI_PLUGIN_PATH` should point to the directory, that contains the plugins. 

TW expects every plugin to have its own directory. Inside this dir all files are located and `plugin.info` is expected. 

So depending on the CLI you use the right paths have to be set: 

`TIDDLYWIKI_PLUGIN_PATH=D:\path\to\your\plugins`

```
- \pmario\myPlugin1
    +- plugin.info
    +- readme.tid
    +- myVersion.js
```

´plugin.info´ defines the "namespace" inside the TW. So mine would be `$:/plugins/pmario/` There is no need that this namespace is used in the physical directory structure, but it makes the work much easier. The TW "best practice" is `$:/plugins/userName/`

`plugin.info` looks like:

```
{
	"title": "$:/plugins/pmario/my-plugin-name-here",
	"description": "Several basic plugins.",
	"author": "MarioPietsch",
	"core-version": ">=5.0.0",
	"list": "readme"
}
```

The plugins are included like this with `tiddlywiki.info`

```
{
	"description": "Some useful info here",
	"plugins": [
		"tiddlywiki/browser-sniff",
                "pmario/myPlugin1"               <--------
        ],
	"languages": [],
	"includeWikis": [],
	"build": {
		"index": [
			"--rendertiddler","$:/core/save/all","index.html","text/plain"]
	}
}

```

This works for me. eg: The edition path looks like this.

`TIDDLYWIKI_EDITION_PATH=D:\path\to\your\editions` ... So all my TW stuff can be within one rep, if I want it that way. 

hope that helps.

**Comment by pmario** [comment]
This director structure also allows me to use (coyp/paste) plugins from other authors:

`TIDDLYWIKI_PLUGIN_PATH=D:\path\to\your\plugins`

```
- \pmario\myPlugin1
- \tobibeer\anyPluginX
```

`tiddlywiki.info`

```
{
    "description": "Some useful info here",
    "plugins": [
        "tiddlywiki/browser-sniff",
        "pmario/myPlugin1",
        "tobiberr/anyPluginX"               <--------
        ],
    "languages": [],
    "includeWikis": [],
    "build": {
        "index": [
            "--rendertiddler","$:/core/save/all","index.html","text/plain"]
    }
}
```

**Comment by pmario** [comment]
There is one more thing, that caused a lot of problems for me: I'm using the `GitBash` on a windows system.

path definition for win: `TIDDLYWIKI_PLUGIN_PATH=D:\path\to\your\plugins`
gitBash windows : `TIDDLYWIKI_PLUGIN_PATH=/d/path/to/your/plugins`
unix: `TIDDLYWIKI_PLUGIN_PATH=/path/to/your/plugins`

!!! be aware of the backslashes and forward slashes, depending on your OS or your CLI tool !!

**Comment by tobibeer** [comment]
@pmario, thank you for reiterating all that. Unfortunately, none of that was unclear to me.

> As the variable name says `TIDDLYWIKI_PLUGIN_PATH` should point to the directory, that contains the plugins.

I was assuming this means a folder equivalent to the [plugins folder](https://github.com/Jermolene/TiddlyWiki5/tree/master/plugins) in the tw repo, so that any actual plugin folder would be within a given **&lt;author>** folder below the registered folder, e.g. **tobibeer/dict**.

> This director structure also allows me to use (coyp/paste) plugins from other authors:

The way I see it, I will simply fork those repos and have them on my system as does the author. I do not want to copy & pasta plugin folders around. I simply want to use an environment variable to point to the right folder, so it gets picked up during the build process.

~

Did you try to include the **dict** plugin based on it's current repo structure (without first copying it into any other of your plugin folders!)?

https://github.com/tobibeer/tw5-dict

My problem is that I cannot set an environment variable pointing to:

`TIDDLYWIKI_PLUGIN_PATH: C:\GIT\tw5-dict\`

It simply never gets picked up in any wiki folder where I declare it in the **tiddlywiki.info** as `tobibeer/dict`.

### (How) Do I need to restructure my repo for that to work?

Also, I will have a number of plugin repositories, namely one per plugin.

So, I expected my environment variable to look like:

`TIDDLYWIKI_PLUGIN_PATH: C:\GIT\tw5-dict;C:\GIT\tw5-filter-join;C:\GIT\tw5-filter-count`

> There is one more thing, that caused a lot of problems for me: I'm using the GitBash on a windows system.

I'm only using the windows console, or the node console, or powershell, all of which follow the windows paradigm. Besides, I would have thought that I do not need to declare those variables in my commands each time, so long as I have global environment variables set correctly.

**Comment by tobibeer** [comment]
@pmario, thanks for your patience... figured the problem out (didn't update the env variable to the new folder structure, arghhhh), see https://github.com/Jermolene/TiddlyWiki5/issues/2079

**Comment by pmario** [comment]
>The way I see it, I will simply fork those repos and have them on my system as does the author. I do not want to copy & pasta plugin folders around. I simply want to use an environment variable to point to the right folder, so it gets picked up during the build process.

The environment variable can contain an array of directories !! but be aware of the different separators, depending on the OS :/

**Comment by pmario** [comment]
>Besides, I would have thought that I do not need to declare those variables in my commands each time, so long as I have global environment variables set correctly.

That should be the case. Global definition in windows should work.

**Comment by pmario** [comment]
>@pmario, thank you for reiterating all that. Unfortunately, none of that was unclear to me.

I tried to write it in a way, that we may be able to use some of the stuff and your findings to improve the docs :)

**Comment by tobibeer** [comment]
@pmario, Actually, it turns out that the true problem here was that I needed to logoff / logon for changes to the system environment variables to be updated in my console... sad but true ... they call it Windumb 10. :D
