### ISSUE TITLE
unable to register plugin repo / folder at environment variable

### ISSUE THREAD

**Issue by tobibeer** [Jermolene/TiddlyWiki5#2079]
After having created my actual first plugin...

docs: http://tobibeer.github.io/tw5-dict
repo: https://github.com/tobibeer/tw5-dict

...I want to use it in another repo / wiki folder, namely [tb5](http://tobibeer.github.io/tb5) ([repo](https://github.com/tobibeer/tb5)).

For this, I assumed I can set an environment variable in my OS for the tiddlywiki CLI to pick it up:

[Environment Variables on Node.js](http://tiddlywiki.com/#Environment%20Variables%20on%20Node.js)

However, if I add **dict** to my tb5 **tiddlywiki.info** like so:

```
"plugins": [
    "tobibeer/dict"
]
```

and then set...

```
TIDDLYWIKI_PLUGIN_PATH: C:\GIT\tw5-dict
```

...it never gets picked up. I tried a with number of folders all the way to `TIDDLYWIKI_PLUGIN_PATH: C:\GIT\tw5-dict\plugins\dict`, none ever worked.

Notice how the plugin resides in...

`C:\GIT\tw5-dict\plugins\dict`

and not in...

`C:\GIT\tw5-dict\plugins\tobibeer\dict`

This is apparently necessary, because if I try and use the latter, I can no longer build or serve the wiki folder **tw5-dict** as it throws this error:

```
C:\GIT\tw5-dict>tiddlywiki --build
fs.js:549
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                                                  ^
Error: ENOENT: no such file or directory, open 'C:\GIT\tw5-dict\plugins\tobibeer\plugin.info'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.fs.readFileSync (fs.js:397:15)
    at $tw.loadPluginFolder (C:\Users\Owner\AppData\Roaming\npm\node_modules\tiddlywiki\boot\boot.js:1487:34)
    at $tw.loadWikiTiddlers (C:\Users\Owner\AppData\Roaming\npm\node_modules\tiddlywiki\boot\boot.js:1661:23)
    at $tw.loadTiddlersNode (C:\Users\Owner\AppData\Roaming\npm\node_modules\tiddlywiki\boot\boot.js:1701:27)
    at $tw.boot.startup (C:\Users\Owner\AppData\Roaming\npm\node_modules\tiddlywiki\boot\boot.js:1827:7)
    at C:\Users\Owner\AppData\Roaming\npm\node_modules\tiddlywiki\boot\boot.js:2005:12
    at $tw.boot.decryptEncryptedTiddlers (C:\Users\Owner\AppData\Roaming\npm\node_modules\tiddlywiki\boot\boot.js:1397:2)
    at $tw.boot.boot [as boot] (C:\Users\Owner\AppData\Roaming\npm\node_modules\tiddlywiki\boot\boot.js:2003:11)
```

...which is confusing, as the recommendation appears to be "mimick the tiddlywiki repo" and in this aspect I actually can't.

## Related Discussion

https://groups.google.com/d/msg/tiddlywikidev/0-A6hRGJh_I/ZhOSeD9BBgAJ

**Comment by tobibeer** [comment]
Now I tried to move the docs from the main repo folder to...

`C:\GIT\tw5-dict`

to 

`C:\GIT\tw5-dict\editions\docs`

Having done so, I no longer get the above error... when building the wiki. However, now the plugin doesn't get built into the output. :D

**Comment by pmario** [comment]
Your directory structure seems to be wrong

**Comment by pmario** [comment]
see: https://github.com/Jermolene/TiddlyWiki5/issues/2071#issuecomment-158044505

**Comment by tobibeer** [comment]
@pmario, I tried rearranging the folder stucture here:

https://github.com/tobibeer/tw5-dict/tree/include-plugin-repo-structure

Now it runs the `--server` command without error but does **not** build / include the plugin, neither when running the server at:

`tw5-dict/editions/docs`

being at:

`C:\GIT\tw5-dict\editions\docs`

nor when running the server for:

`tb5`

residing directly at:

`C:\GIT\tb5`

...both of the above including the plugin at their **tiddlywiki.info**.

**Comment by tobibeer** [comment]
Ah, wait, I double checked everything again, and now it works. *facepalm*
