### ISSUE TITLE
Add tiddler types for audio and video

### ISSUE THREAD

**Issue by braykov** [Jermolene/TiddlyWiki5#2083]
Current TiddlyWiki tiddler types contain Text and Image formats, but no audio or video.
Add these for easier embedding of music and video.

**Comment by Jermolene** [comment]
Hi @braykov there are actually two separate layers at which different content types can be registered within TiddlyWiki:

* The boot kernel defines the low level file types that TiddlyWiki understands - [see them here](https://github.com/Jermolene/TiddlyWiki5/blob/master/boot/boot.js#L1818-L1841). A type being defined here tells TiddlyWiki whether to treat it as binary or text, for example
* The core UI defines tiddlers for each tiddler type that is to be selectable in the "type" dropdown in the edit template - they are defined [here](https://github.com/Jermolene/TiddlyWiki5/tree/master/core/language/en-GB/Types)

Are all the file types that you are interested in included in the first list?

There's a strong reason to keep the size of the dropdown reasonably small; we don't want users to have to scroll to see the entire list. So I think we should restrict it to the types that are commonly used, in particular the types that are commonly worked with interactively. Users can still manually type other types.

Creating `_canonical_uri` tiddlers manually is tedious in any case; I'd be quite interested in adding a special new UI for creating them.

**Comment by braykov** [comment]
I am particularly interested in audio/mp3,mp4,ogg. They are all included in the first group.
If  I had to choose a single type, that would be .ogg.

**Comment by pmario** [comment]
> So I think we should restrict it to the types that are commonly used, in particular the types that are commonly worked with interactively. Users can still manually type other types.

>If I had to choose a single type, that would be .ogg.

hmmm. While the [.ogg](https://en.wikipedia.org/wiki/Ogg) format is the one, that imo fits best to the TW project, because of its "free nature", its the one, that's the least known type. 

IMO [.mp3](https://en.wikipedia.org/wiki/MP3) is the de-facto standard and was the matter of a lot of copyright problems. Hence the .ogg format was created. ... but according to wikipedia

>In Europe mp3 is patent free and in the United States, the technology will be substantially patent-free on 31 December 2017

So there should be no problem, to implement them. .. But imo the "best audio" format discussion is a "hot" topic. If we support one extension, we basically need all of them. 

@Jermolene is it possible to include additional file extensions as plugins? 

This would also solve a lot of problems with other file types, that are often requested. Users can decide, what's important for them, so the dropdown list and the core can be small, and we don't need to carry things around, which we don't use often.

**Comment by tobibeer** [comment]
> Users can decide, what's important for them, so the dropdown list and the core can be small, and we don't need to carry things around, which we don't use often.

:+1:  => "everything is a tiddler"

**Comment by Jermolene** [comment]
> @Jermolene is it possible to include additional file extensions as plugins?

Yes, indeed, such a plugin would just contain tiddlers such as `$:/language/Docs/Types/video/ogg`, see the [core types](https://github.com/Jermolene/TiddlyWiki5/tree/master/core/language/en-GB/Types) for the fields required.

**Comment by s-light** [comment]
> The boot kernel defines the low level file types that TiddlyWiki understands:

[new location](https://github.com/Jermolene/TiddlyWiki5/blob/master/boot/boot.js#L2235-L2271) 
you can search for `registerFileType` or `text/plain` to find the code lines.

---


do i understand this correct that `video/webm` is currently not supported?
(as it is missing from the core list)
woud be nice for some local videos..

if i try it i get this message
> Trying to load external content from file:///home/stefan/xyz//VID_20190422_203909.webm
>
>If this message doesn't disappear, either the tiddler content type doesn't match the type of the external content, or you may be using a browser that doesn't support external content for wikis loaded as standalone files. See https://tiddlywiki.com/#ExternalText

**Comment by Jermolene** [comment]
Hi @s-light we currently add file types to the boot kernel list as they are requested by users. It looks like we've currently got webp images, but not webm videos. It would be great if you  would like to prepare a PR? See our contributing.md file for guidelines.

**Comment by s-light** [comment]
thanks @Jermolene  - i will try the PR - but will need some weeks to get to it ;-)

**Comment by s-light** [comment]
@Jermolene i have created the PR.
hope that it is all fine as i have done it.

**Comment by Jermolene** [comment]
Thanks @s-light

**Comment by s-light** [comment]
as i see it this issue is fixed.
from what i have seen i think all mayor file types for audio & video are supported..
so this could be closed?! @braykov

**Comment by Jermolene** [comment]
I think we can indeed close it for now. Please open a new ticket to request any further new types.
