### ISSUE TITLE
join filter — concatenates input titles using an item template

### ISSUE THREAD

**Issue by tobibeer** [Jermolene/TiddlyWiki5#2084]
## ADDENDUM

An enhanced version of the join filter is now published as a plugin [tobibeer/join](http://tobibeer.github.io/tw5-plugins/#join).

## Original PR

Joins input items into a concatenated string based on a template specified in the operand.
* default template: `%title%` = the item title

@Jermolene, let me know if you think of this as a core candidate, then I'll add the docs / tests and make a PR.

## Demo

http://joinfilter.tiddlyspot.com

## Example

```
\define options-filter() [!is[system]$(options)$sort[title]]

\define filtered-list()
<$set name="template" value="""tag[%title%]""">
<$set name="options" filter="[prefix<path>get[text]join<template>]">
<ul>
<$list filter=<<options-filter>>>
<li>
<$link><$view field="title"/></$link>
</li>
</$list>
</ul>
</$set>
</$set>
```

In the above example, the path refers to the path of state tiddlers which store selected tagnames, so all selected tagnames get concatenated to form a compound filter expression.

**Comment by Jermolene** [comment]
Hi @tobibeer similarly I think this is best explored in a plugin so that you can iterate improvements more rapidly as it is adopted.

**Comment by tobibeer** [comment]
It's a fairly straight forward filter. Atm, I don't have any improvements for it in mind. I can sure publish it at tb5.

**Comment by tobibeer** [comment]
reopening because of https://github.com/Jermolene/TiddlyWiki5/pull/2035#issuecomment-155508991

@Jermolene: 

> I can agree that there might be use cases for concatenating list items, but I don't think this is the place to implement it. Why not a filter operator, for example?

**Comment by tobibeer** [comment]
Closing this PR, **join** is now published as [tobibeer/join](http://tobibeer.github.io/tw5-plugins/#join)
