### ISSUE TITLE
count filter

### ISSUE THREAD

**Issue by tobibeer** [Jermolene/TiddlyWiki5#2085]
1. counts items in the input set
1. **or**: verifies the number of items in the input against a specified count
    1. **either**: allowing the list to fall through if count is matched
    2. **or**: with suffix `is`, returns the matching count

This is handy when using the list widget for conditional templating, e.g.:

* "filter matches" vs. "filter does not match"

@Jermolene, let me know if you see this as a core candidate, so I'll add docs / tests & make a PR.

## Demo

http://count.tiddlyspot.com

**Comment by Jermolene** [comment]
Hi @tobibeer this definitely looks useful, but I think it makes more sense to explore it as a plugin for the moment.

**Comment by tobibeer** [comment]
As with the **join** filter, I think this also is a fairly straight forward filter. Meaning: I don't have any improvements for it in mind, atm. I can sure publish it at tb5.

**Comment by tobibeer** [comment]
@Jermolene, this would also provide a solution for the problem that had me make the PR #2035 ("format" for set widget), while not needing some list variable accessor.

**Comment by tobibeer** [comment]
Added addendum to OP: 

> I have released (a modified/enhanced version) of the count filter as [tobibeer/count](https://github.com/tobibeer/tw5-count) at: http://tobibeer.github.io/tw5-plugins/#count

**Comment by tobibeer** [comment]
@Jermolene: I just tried to hide the top row of controls / buttons if the import tiddler if the list of tiddlers to be imported had less than 7 entries. There doesn't seem to be a way to do that in the core, except with something like the / a **count** filter.
