### ISSUE TITLE
template lookup via field

### ISSUE THREAD

**Issue by tobibeer** [Jermolene/TiddlyWiki5#2086]
I have recently played with a mechanism that is a lot more flexible to handle, which is to lookup a desired tiddler not via its title but via a **field** specifying an identifier. This allows to rename the tiddler to anything we want while keeping all references in-tact.

So, here's the idea for templating...

```
{{||the-template}}
```

Today, the above requires to use a tiddler named **the-template** as your template. Well, I truly don't want those to pollute my actual tiddlers namespace, but then using system tiddlers like so...

```
{{||$:/_my/templates/the-template}}
```

...is quite ugly to read and difficult to type and remember.

So, here's the idea:

```
title: $:/_my/templates/the-template
tw-template: the-template

foo
```

And then have...

```
{{||the-template}}
```

...do the required magic, i.e. first check for a tiddler that has a field **tw-template** set to the identifier `the-template` and, failing that, use a tiddler called **the-template**.

**Comment by inmysocks** [comment]
I like the idea, and if we can implement it I would like to have some sort of generic alias implementation instead of just for templates if possible. One suggestion I have is to find a way to implement it so that it isn't bound to a single field. That is just to keep from having too many special fields in the core.

I think that this would only require a relatively small change to the transclude widget so that to get the variable this.transcludeTitle correctly. Unfortunately to make the non-title field contents the default name to use it would mean that filtering is required for every transclusion. Each transclusion using a tiddler title would have to check every tiddler with the field tw-template (or whatever field is used) before falling back to the title.
It would only have linear complexity which shouldn't be a huge problem, but since this would affect every transclusion we should check to be sure.

**Comment by Jermolene** [comment]
I think this is indeed a proposal for a specialised form of aliasing. If we're going to add aliasing, I'd rather it was done more generally than just for transclusion templates. So I'd suggest that this area be explored via a plugin for the moment.

**Comment by tobibeer** [comment]
To me, there are two things here.

## A) Templating

Explicitly extend the templating mechanism to do these kinds of lookups, as currently we are limited to tiddler-titles-only with `{{||template-name}}`.

I don't see how the core would provide a hook to extend that to do a lookup as described above and I explicitly would not want an alternative syntax, so any plugin would have to (find a way to) hijack the core templating function (=> not good!?).

If we wanted to leverage a tbd core aliasing function for that, we can later on easily implement it for templating... but that is quite distinct from the functionality itself. I would not want to use a more generic aliasing for templates like:

`{{||%tw-template:template-name%}}`

This is also too complicated, although it sure allows to rename whichever tiddler corresponds to that `key:value` pair and still have any template references working.

## B) Field Aliasing

Have a new form of text-reference that first looks up the right tiddler and then whichever field or index value is requested, for example:

* `{{%fieldname:identifier%!!some-field}}` or
* `{{%fieldname:identifier%##some-index}}`
* e.g. `{{%uuid:$(uuid)$%##some-index}}`

In the end, the above is basic **transclusion**, (not templating), and so the way to leverage aliasing for templating would possibly look like:

```
<$transclude tiddler="%tw-template:template-name%"/>
```

I would definitely want the wikitext shorthand for templating to only optionally allow specifying a lookup field & value, e.g:

`{{||%tw-template:template-name%}}`

...but the default should work as we do today:

`{{||template-name}}`

...based on a defined field, e.g. `tw-template`, automagically cascading through the options in the background, not having to be explicit about it.

**Comment by Jermolene** [comment]
>  I explicitly would not want an alternative wikitext syntax.

That's the problem right there; you've stated the requirements in a way that only allows you to proceed by hacking the core. That's fine, but as things stand it's a long way from being accepted. This is a speculative, experimental proposal for the core:

* It doesn't help any of the outstanding problems that we face
* It displays a lack of understanding of how the `{{}}` syntax generates both a tiddler widget and a transclude widget
* It doesn't give any consideration for performance or backwards compatibility

So it's hard for me to give it serious attention at this point. Why not do some more exploration before pitching it for the core?
