### ISSUE TITLE
get:list-items

### ISSUE THREAD

**Issue by tobibeer** [Jermolene/TiddlyWiki5#2091]
Allow to fetch all titles listed in a list-field.

For this purpose, a **listitems** suffix for the **get** filter can be implemented:

`{{{ [get:listitems[some-field]] }}}`

The above thus retrieves all titles referenced in the list-field called **some-field** with respect to the titles in the input set.

**Comment by Jermolene** [comment]
Hi @tobibeer good idea, although perhaps it should be "list-items" to match `each:list-item[field]`?

**Comment by tobibeer** [comment]
Did not double-check. I agree.

**Comment by tobibeer** [comment]
On second thought, I think that was an oversight on my end.

Seeing as how **each:list-item** in #2073 (for #1369),  already does what this issue asks for, I don't think we need to amend the **get** filter atm.

@Jermolene, Would you agree? If not, I will reopen.

**Comment by Jermolene** [comment]
I was imagining that the difference would be that "each:list-item" would return the unique list items, but "get:list-items" would return the entire list, in sequence, complete with duplicates.

**Comment by tobibeer** [comment]
We could do that but I'd wait for anyone to actually need it because, for one, the sequence would be quite arbitrary and then a way to actually count those occurrences may be more valuable in the end.

For now, I'd prefer sticking with the paradigm that titles in the input of a filter are a set, e.g.:

`{{{ foo foo foo }}}``
