### ISSUE TITLE
Formal test cases for backwards compatibility in the core

### ISSUE THREAD

**Issue by inmysocks** [Jermolene/TiddlyWiki5#2096]
I think that tiddlywiki is complex enough to warrant collecting a set of test cases to ensure backwards compatibility for future changes to the core. Some changes I would like based on the discussion in #2037 would require a change to the core function to filter tiddlers and while it shouldn't affect backwards compatibility I realized that there isn't currently any way to check that other than manually checking the code.

I think that most, if not all, test could be written in wikitext and we may even be able to package them as a plugin that you could import into a wiki with proposed changes to check if it breaks anything. An exhaustive set of tests may not be feasible, but the task will only get bigger in the future and I think that putting something like this together would be very helpful for development.
I am planning on starting by putting together a tree showing function dependencies. Luckly, tiddlywiki is a good tool to use for this. 

But, before I get too far, has anything like this already been made that I just haven't seen yet?

**Comment by tobibeer** [comment]
Ever played with the **test** edition yet?

https://github.com/Jermolene/TiddlyWiki5/tree/master/editions/test

There are plenty of automated tests here:

https://github.com/Jermolene/TiddlyWiki5/tree/master/editions/test/tiddlers/tests

These need amending with new functionality and all should pass for a new release.

**Comment by pmario** [comment]
A big +1 to put some efforts in here. 

>There are plenty of automated tests here:

hmm, imo we have a hand full of tests and are far far away from plenty. Comparing TW to other open source projects, we are "close to no tests".

**Comment by tobibeer** [comment]
I would sure encourage everyone to amend missing tests. The mechanism itself is there.

**Comment by inmysocks** [comment]
I had not seen that. I will try to put together some documentation to help make the tests.

**Comment by pmario** [comment]
@Jermolene ... This one can be closed. We do have the "test edition", which will be extended if necessary.

**Comment by Jermolene** [comment]
Thank you @pmario
