### ISSUE TITLE
grouped filter runs

### ISSUE THREAD

**Issue by tobibeer** [Jermolene/TiddlyWiki5#2101]
Extend the filter syntax so that filter runs can be grouped via parentheses:

```
<$list filter="""
[tag[Recipes]]
+([rating[★]] [rating[★★]])
+([tag[Spring]] [tag[Summer]])
+([meal[Dinner]] [meal[Snack]])
"""/>
```

Meaning: Select all tiddlers...
- that have the tag **Recipes**
- **AND** where the **rating** field contains either `★` or `★★`
- **AND** where the tiddler has one of these **Seasons** as a tag: **Spring**, **Summer**
- **AND** where the **meal** type field contains either `Dinner` or `Snack`

For peformance reasons it should possibly be:

```
<$list filter="""
+([tag[Recipes]rating[★]] [tag[Recipes]rating[★★]])
+([tag[Recipes]tag[Spring]] [tag[Recipes]tag[Summer]])
+([tag[Recipes]meal[Dinner]] [tag[Recipes]meal[Snack]])
"""/>
```

That makes me think that it may also be nice, if there could be a defined "filter base" that defines the basic input set for all filterRuns in a filterString, e.g.:

```
<$list filter="""
base([tag[Recipes]])
+([rating[★]] [rating[★★]])
+([tag[Spring]] [tag[Summer]])
+([meal[Dinner]] [meal[Snack]])
"""/>
```

**Comment by peterdoerrie** [comment]
Would love to see this!

**Comment by pmario** [comment]
@Jermolene ... IMO this is solved by the `:filter[[]]` run prefix, which does exactly that. So issue should be closed.

**Comment by Jermolene** [comment]
Thank you @pmario
