### ISSUE TITLE
HighlightPlugin broken on current master

### ISSUE THREAD

**Issue by tobibeer** [Jermolene/TiddlyWiki5#2102]
**2015-11-26:** Looking at it on [the current prerelease](http://tiddlywiki.com/prerelease/plugins/tiddlywiki/highlight/#%24%3A%2Fcore%2Fmodules%2Fcommands%2Fhelp.js) does not show the broken behaviour.

How to reproduce:
1. using the master as of https://github.com/Jermolene/TiddlyWiki5/commit/4a8511c6f21ed0123bf790e668f153db75618bce
   - this is unrelated to this commit, it just serves as a pointer to where things don't work
2. build / serve  the **highlightdemo** edition
3. take a look at some js tiddler, e.g. **$:/core/modules/commands/help.js**

![broken_highlight](https://cloud.githubusercontent.com/assets/97566/11419069/512bf47a-9425-11e5-91c6-ab3a78480a64.jpg)

**Comment by sycom** [comment]
I think this one can be closed?
