### ISSUE TITLE
Filtered transclusion parsing is too greedy

### ISSUE THREAD

**Issue by tobibeer** [Jermolene/TiddlyWiki5#2109]
The parser for list transclusions has some unexpected results, e.g.:

```
{{{ foo }}} = {{{ foo }}}
```

yields:

[}}} = {{{ foo](http://tiddlywiki.com)

...with some extra line-breaks as of 5.1.10-prerelease.

Note that none of these expose the same problem:

```
x {{{ foo }}} = {{{ foo }}} x

x {{{ foo }}} = {{{ foo }}}

{{{ foo }}} = {{{ foo }}} x
```

**Comment by Jermolene** [comment]
By the way, it's instructive to look at the [offending regexp](https://github.com/Jermolene/TiddlyWiki5/blob/master/core/modules/parsers/wikiparser/rules/filteredtranscludeinline.js#L29) graphically via [regexper](http://regexper.com/#%5C%7B%5C%7B%5C%7B(%5B%5E%5C%7C%5D%2B%3F)(%3F%3A%5C%7C(%5B%5E%5C%7C%5C%7B%5C%7D%5D%2B))%3F(%3F%3A%5C%7C%5C%7C(%5B%5E%5C%7C%5C%7B%5C%7D%5D%2B))%3F%5C%7D%5C%7D(%5B%5E%5C%7D%5D*)%5C%7D(%3F%3A%5C.(%5CS%2B))%3F)

<img width="913" alt="screenshot 2015-12-06 19 20 24" src="https://cloud.githubusercontent.com/assets/174761/11615085/6b776d56-9c4e-11e5-819e-1ee8ce1ccd5d.png">

**Comment by tobibeer** [comment]
Capture group 5 appears to be the (undocumented and also not working) source of the problem then. In fact, a simple test...

```
<div>{{{foo bar |baz}}color:red;}.tc-tiddlylink-existing</div>
```

...has me believe that none of the groups 2, 4 or 5 are working.

Shall we remove all of them?

**Comment by tobibeer** [comment]
I take it, the regexp would have to be at least:

```
/\{\{\{([^\|]+?)(?:\|([^\|\{\}]+))?(?:\|\|([^\|\{\}]+))?\}\}([^\}]+)\}(?:\.(\S+))?/mg
not
/\{\{\{([^\|]+?)(?:\|([^\|\{\}]+))?(?:\|\|([^\|\{\}]+))?\}\}([^\}]*)\}(?:\.(\S+))?/mg
```

**Comment by tobibeer** [comment]
> regexper

Thanks for this.

**Comment by AnthonyMuscio** [comment]
As @pmario  pointed out this may be related to this TW 5.2.3 persistent bug https://talk.tiddlywiki.org/t/is-this-a-bug-in-filtered-transclusion-i-am-seeing-on-tiddlywiki-com/3578/6?u=tw_tones

My main concern is not the examples provided but is this bug making things fragile in other use cases?

**Comment by pmario** [comment]
@Jermolene -- I think we can close this one with a wontfix?

> Jeremy [comments at Talk TiddlyWiki](https://talk.tiddlywiki.org/t/is-this-a-bug-in-filtered-transclusion-i-am-seeing-on-tiddlywiki-com/3578/4?u=pmario)
>
>The triple brace syntax for filtered transclusion works differently according to whether it is invoked in “block mode” or “inline mode”.
>
>Block mode is triggered if the transclusion appears at the start of a block and is immediately followed by a line break. Otherwise the transclusion will be rendered in inline mode.
>
>In block mode, the output is displayed as one link per line. In inline mode, the output is squooshed together into a single line. Inline mode is more useful when using a template.

**Comment by Jermolene** [comment]
Hi @pmario the OP is still a problem. I agree that it is unlikely to be fixed because of backwards compatibility concerns
