### ISSUE TITLE
can't make pull request to upstream

### ISSUE THREAD

**Issue by tobibeer** [Jermolene/TiddlyWiki5#2113]
I don't know what might be the cause. There are two small things I'd make a PR for, but they always end up pulling to my own fork's master (origin) rather than [jermolene/TiddlyWiki5](https://github.com/Jermolene/TiddlyWiki5) (upstream).

* https://github.com/tobibeer/TiddlyWiki5/pull/5
* https://github.com/tobibeer/TiddlyWiki5/pull/6
* https://github.com/tobibeer/TiddlyWiki5/pull/7
* https://github.com/tobibeer/TiddlyWiki5/pull/8
* https://github.com/tobibeer/TiddlyWiki5/pull/9
* https://github.com/tobibeer/TiddlyWiki5/pull/10
* https://github.com/tobibeer/TiddlyWiki5/pull/11

Any ideas what could be going on / how to fix appreciated.

**Note:** Before creating branches, I ensured that my master was up to date with upstream/master.

**Comment by tobibeer** [comment]
Not exactly sure, but the problem may be that I have two upstream repositories, one called upstream and the other "Jermolene"... would not know where GitHub gets the hickup, but I will see that I remove one or the other.

**Comment by tobibeer** [comment]
@Jermolene, I figured I will from now on always do a PR in the WebUI, not from the Windows client... at least that shows me whether GitHub is able to perform a PR or not ...at the repo I wish to post it.

**Comment by pmario** [comment]
`git remote -v` will give you the info

**Comment by tobibeer** [comment]
Yes, it all looked good, it just didn't pick either of those "upstream" repos to make the PR against but always origin. No idea how to tell it in the windows client to use the right upstream. Even after selecting am upstream branch in the ui, it still made the PR against my origin repo. I think this are possibly shortcomings, if not bugs in the Windows client.

**Comment by pmario** [comment]
If you use github for windows GUI, you don't have a chance. This program imo is crap. ... 

There are only a hand full of commands needed in the CLI to make it work well. 

```
git pull jermolene master
... make your changes
git push origin master
create the PR with github web interface. 
```

**Comment by tobibeer** [comment]
:+1: exactly my point ;-)
