### ISSUE TITLE
core PopupWidget

### ISSUE THREAD

**Issue by tobibeer** [Jermolene/TiddlyWiki5#2120]
## Addendum

The [appear widget](http://tobibeer.github.io/tw5-plugins/#appear) now provides a **handler** mechanism that allows to take popups out of the flow and thus prevent the cut-off.

## Original Issue

Based on the considerations of #1432, it is necessary to be able to have popups that are created outside the flow, i.e. not at the place where a reveal widget is rendered, most importantly to have their style and rendering be independent from the anchoring element context.

For this purpose, this is an issue to discuss the specifics of creating a new, generic PopupWidget, which has (at least) the following attributes...

* **template**
    * the template tiddler used for rendering a popup
* **class**
    * a css class assigned to the actually created popup, not the PopupWidget
        * overriding any default class, i.e. `tc-popup`

possibly considering the following requirements...

1. a popup element is immediately rendered as the PopupWidget renders...
    1. which can be deferred, like now, using a RevealWidget or ListWidget
1. by calling a $wiki method that...
    1. knows the default place where to render popups (some placeholder in the PageTemplate)
    1. renders a popup at the PopupWidget being its anchor
    1. returns a reference to the rendered element to the PopupWidget
        1. also stores a reference to the PopupWidget (being the anchor) at the actual popup
1. the actual popup-element has a click handler which...
    1. closes any child-popups, should a rendered popup contain and render another PopupWidget, thus rendering a nested child popup
    1. this requires for the $wiki method handling popups to be aware of a PopupWidget instance to exist within the global popup-placeholder and to thus notify any associated parent PopupWidget of its existence
        1. any PopupWidget may only have a single parent PopupWidget, not more
        1. note that, here, "parent" does not mean "parent in the dom"
        1. put differently, at a given level, only one child popup can be "spawned"
        1. so, if a child popup is created from a PopupWidget within a popup, then any existing child popup already open with respect to that popup is to be closed, so that there is only ever one child per popup level
        1. level 0 being anywhere in the pagetemplate except withing the placeholder for popups
    1. it also requires a propper destructor for both the PopupWidget as well as the rendered popup
        1. should the PopupWidget be destroyed, then so must be any rendered popups, including child popups
        1. should a rendered popup be destroyed, then so must be any child popups
1. clicking anywhere but a popup should always close all rendered popups of all levels
1. which core elements should use the new popup mechanism or perhaps benefit from the old needs step-by-step consideration
1. the place where the $wiki method renders actual popups could, in fact, be the first instance of a PopupWidget in the document that does not specify any (**template**) attribute
    1. so one that just reads `<$popup/>`
    1. that way we only need to make sure that this place is as permanent as possible within the PageTemplate, with the least impact, could be in the StoryColumn, but outside from any tiddlers / list widgets populating the story-river
    1. this would actually decouple the $wiki object from the $popup widget as it can now know and talk to another nothing but widget instance, otherwise output some info that we're missing this crucial spot

**Comment by tobibeer** [comment]
added

> * 6. the place where the $wiki method renders actual popups could, in fact, be the first instance of a PopupWidget in the document that does not specify any (**template**) attribute
>    1. so one that just reads `<$popup/>`
>    1. that way we only need to make sure that this place is as permanent as possible within the PageTemplate, with the least impact, could be in the StoryColumn, but outside from any tiddlers / list widgets populating the story-river

**Comment by tobibeer** [comment]
My last comment made it entirely possible to create this widget as a plugin without any further core support. :D

**Comment by tobibeer** [comment]
@Jermolene, seeing as how there already is abundant popup placement handling in the RevealWidget, it could somewhat "easily" be amended to externalize popups in the above way.

For example, we could introduce a **template** attribute that instructs the reveal widget to render a template for the popup, however, elsewhere, not in place. In other words, it would be empty,e.g.:

```
<$reveal
	type="nomatch"
	state="$:/state/SampleReveal2"
	text="show"
	template="$:/pop-template"/>
```

There should not be any additional popup widget essentially duplicating all the reveal widget code.

Fwiw, it would very much benefit from a **template** mechanism anyway. ;-)

I will see if I can make a prototype.

**Comment by Jermolene** [comment]
Hi @tobibeer I'll emphasise again: we can't have widgets that have side effects on the DOM outside of their place in the tree. We have to do that via a startup module, as we do with the modal wizard mechanism.

I think there are a few approaches for exploring your issues:

* Taking advantage of the fact that the reveal widget picks up the popup coordinates from the state tiddler. Thus it is possible to position a popup arbitrarily
* Taking advantage of the fact that the reveal widget and the button don't need to be adjacent in the DOM
* Enhancing the modal mechanism to allow it to be used in popup-like situations

**Comment by tobibeer** [comment]
Thanks for the feedback, I think I'll explore amending the RevealWidget like so:

The "remote" handler that manages all open popups goes into something like:

```
title: $:/core/ui/PageTemplae/popups
tags: $:/tags/PageTemplate

<reveal handle=popups/>
```

And then use the RevealWidget **anywhere** like so:

```
<$reveal
    type="nomatch"
    state="$:/state/SampleReveal2"
    text="show"
    handle="true"
    template="$:/pop-template"/>
```

...revealing an error text should there be no widget that defines `handle=popups`.

**Comment by tobibeer** [comment]
So, the handler instance would simply handle the contents that other reveal-widgets define, as deferred to from any actual instance declaring its contents and state... and do the talky-talky back and forth.

**Comment by tobibeer** [comment]
Actually, the consequence of all this seems not some popup widget or modifications in the RevealWidget, but a new **HandlerWidget**:

**In Placeholder Mode**

```
title: $:/core/ui/PageTemplate/popup-handler
tags: $:/tags/PageTemplate

<$handler for=popups/>
```

And then anywhere...

**In Anchor Mode**

```
<$reveal
    type="nomatch"
    state="$:/state/SampleReveal2"
    text="show">
<$handler handler="popups" option="value">
CONTENT
</$handler>
</$reveal>
```

Unfortunately, this widget will need to replicate the popup placement code in the RevealWidget... unless that can somehow be "required".

**Comment by tobibeer** [comment]
Only just now found **$:/core/modules/utils/dom/popup.js**. Will do some code reading to figure out the design implications this brings and how the popup mechanism actually works ...already seeing it implements much of the requirements above.

**Comment by tobibeer** [comment]
I'm starting to think it quite needs to be the other way around:

```
<$handler handler="popups" option="value">
<$reveal
    type="nomatch"
    state="$:/state/SampleReveal2"
    text="show">
CONTENT
</$reveal>
</$handler>
```

So, it actually takes the entire reveal and renders it into the handler placeholder.

**Comment by tobibeer** [comment]
> I'll emphasise again: we can't have widgets that have side effects on the DOM outside of their place in the tree. We have to do that via a startup module, as we do with the modal wizard mechanism.

It is impossible to have this a startup module, since the popup contents are of dynamic nature in a way where an arbitrary number of dynamic popups is bound to an equally as arbitrary, dynamically created range of states. Therefore, the only option is precisely to find ways to have widgets render their output at some other place designed to adequately receive and handle it.

**Comment by Jermolene** [comment]
@tobibeer

> It is impossible to have this a startup module, since the popup contents are of dynamic nature in a way where an arbitrary number of dynamic popups is bound to an equally as arbitrary, dynamically created range of states

I think that that assumption is broken by the existing wizard/modal mechanism. I'd recommend studying it.

> Therefore, the only option is precisely to find ways to have widgets render their output at some other place designed to adequately receive and handle it.

It's not the "only option"; it's the one option that requires you to redesign TW5 from scratch :)

**Comment by tobibeer** [comment]
> the existing wizard/modal mechanism. I'd recommend studying it.

I already had a hunch that I may want to do just that.

> It's not the "only option"; it's the one option that requires you to redesign TW5 from scratch :)

If that's what it takes. :D

Anyway, it's the task at hand... and I have yet to explore the best way to make it work.

**Comment by tobibeer** [comment]
```
<$reveal @popups option="foo">
output wherever the flub @popups is
</$reveal>
```

**Comment by tobibeer** [comment]
Added addendum to OP:

> The [appear widget](http://tobibeer.github.io/tw5-plugins/#appear) now provides a **handler** mechanism that allows to take popups out of the flow and thus prevent the cut-off.

This covers the OP for me, so I am closing this. If anyone wants this to be core functionality, or core functionality doing the same, please reopen or create another issue.
