### ISSUE TITLE
Set widget not updating properly

### ISSUE THREAD

**Issue by felixhayashi** [Jermolene/TiddlyWiki5#2121]
Procedure:

1. Insert the code below into a tiddler's body
1. Activate preview
1. Switch the select value
1. See only the list widget updates

```html
<$set name="temp" value="foobar">

<$select
    tiddler=<<temp>>
    field="f">
  <option>A</option>
  <option>B</option>
</$select>

<$list filter="[<temp>get[f]]" />

<$set name="title" filter="[<temp>get[f]]">
<<title>>
</$set>

</$set>
```

Is this by design to avoid intensive recalculation?

**Comment by tobibeer** [comment]
This is fixed. See pre-release.

**Comment by felixhayashi** [comment]
Thanks @tobibeer 

Do you know since when this got fixed? I recently updated my local TW5 master branch and there it is not working yet…

-Felix

**Comment by tobibeer** [comment]
Did you test it on prerelease and did it work as I think it does? If yes, then what did you update your TW5 master to?
