### ISSUE TITLE
Allow Operand Listings to Include 'Titles With Spaces'

### ISSUE THREAD

**Issue by matabele** [Jermolene/TiddlyWiki5#2122]
Following from this discussion: https://github.com/Jermolene/TiddlyWiki5/pull/2037 -- there is a need to enable listings to include titles with spaces in the operand of filter operators.

Consider extending the syntax to fix it. In particular, allow a new style of inner brackets that indicates a list that quotes with double square brackets. 

For example:     `+[append(HelloThere [[Title with spaces]])]`

The implementation would be pretty simple: a matter of allowing round brackets as a synonym for the inner square brackets of a filter operand.

A further suggestion was to allow for double inner brackets -- items could then include indices.

For example:   `+[append((one a(1) [[and two]] three))]`

**Comment by tobibeer** [comment]
No double inner brackets, please. The operand parsing must be left to any filters, not to the filter syntax! In other words, `a(1)` is a valid input title.

**Comment by Jermolene** [comment]
>  The operand parsing must be left to any filters, not to the filter syntax! 

@tobibeer the suggestion here is to add support for a new delimiter for operands. It's definitely a matter for the filter parser, not individual filter operators.

> In other words, a(1) is a valid input title.

If we stick with single round brackets, then a(1) will not be allowed within a round-bracket delimited operand.

**Comment by tobibeer** [comment]
>  It's definitely a matter for the filter parser, not individual filter operators

Yes, but if round brackets are already a much needed part of an operand, it will break, e.g. [eval](http://tobibeer.github.io/tw5-plugins/#eval). So, it would take at least two, if not three round brackets to be safe, e.g. `[append(((one a(1) [[and two]] three)))]`... since math expressions may heavily depend on brackets and then break at the very first, or even two.

**Comment by matabele** [comment]
What if the parens were added to the square brackets, rather than replacing them?

For example: `+[append[(HelloThere [[Title with spaces]])]]`

Is there a need for `)]` anywhere within a filter operand?

**Comment by Jermolene** [comment]
@matabele that would clash with the current syntax; `+[append[(HelloThere)]` is currently valid syntax for passing a tiddler titled `(HelloThere)` as operand to the `append` filter operator.

**Comment by tobibeer** [comment]
> Is there a need for )] anywhere within a filter operand?

Actually, so long as the parser is properly tokenizing things, the round brackets are not a problem so long as they will not break within an operand that is specified via `some-filter[(operand)+(more)]`.

I think the more troublesome issue for me is that my [split](http://tobibeer.github.io/tw5-plugins/#split) filter uses a suffix that involves round brackets which will definitely break. I could change it to something else, e.g. backslashes maybe.

http://tobibeer.github.io/tw5-plugins/#split-Syntax

This filter has only been around for a less than 4 weeks and I don't think anyone's life depends on the current prefix suffix syntax... so I think I could change it.

**Comment by tobibeer** [comment]
As announced [here](https://groups.google.com/forum/#!topic/tiddlywiki/VgzE8fYXS24), I have dropped using round brackets with [tobiber/split](http://tobibeer.github.io/tw5-plugins/#split) as of [version 0.7.0](https://github.com/tobibeer/tw5-split/releases/tag/0.7.0).

In other words, as for me, we're good to go using and abusing those for this issue.

**Comment by matabele** [comment]
@Jermolene @tobibeer 
A thought -- perhaps, to fix this, rather than alternative parens, we should employ 'alternative' square brackets (like the list[] operator.) All that's required is to recognise an operand value in TextReference form, and act accordingly.

The list[] operator could also be taught to accept either square or curly brackets around the TextReference -- thus improving consistency.

**Comment by tobibeer** [comment]
@matabele, as [suggested here](https://github.com/Jermolene/TiddlyWiki5/pull/2224#issuecomment-171920818), I don't think the idea in your last comment will improve things... and I am starting to think that maybe not even this entire ticket is worth pursuing, since...

It is **very easy** to model the desired behavior as said [here as well](https://github.com/Jermolene/TiddlyWiki5/pull/2224#issuecomment-171920818):

> It appears real simple to use:
>
> 1) the vars widget
>
> ```
> <$vars titles="""foo [[bar baz]] mumble""">
> {{{ [cycle<titles>] }}}
> </$vars>
> ```
>
> 2) a text-reference
>
> ```
> {{{ [cycle{FromSomewhere!!AList}] }}}
> ```
>
> ...and you're safe.

**Comment by matabele** [comment]
@tobibeer @Jermolene 
>It appears real simple to use:
1) the vars widget
2) a text-reference

I agree -- I'll pull this ticket as soon as a consensus has been reached.
