### ISSUE TITLE
Allow Listings to Include Multiple Instances of Items 

### ISSUE THREAD

**Issue by matabele** [Jermolene/TiddlyWiki5#2123]
There have been numerous discussions with respect this topic
https://github.com/Jermolene/TiddlyWiki5/issues/2097
https://groups.google.com/forum/#!topic/tiddlywiki/Xq1AmRm-ubw

Points made include:
1. Existing behaviour (remove duplicates) must remain by default (suppressing this behaviour should be optional)
2. Filter expressions are difficult to evaluate unless duplicates are removed only at the end of each filter run (a behaviour which can be easily suppressed)
3. Suggested syntax for suppressing the removal of duplicates
   -  `+[operator[operand]+]`
   -  `++[operator[operand]]`
   -  `&[operator[operand]]`
4. Updates necessary for several core functions which enforce uniqueness
5. Need for a `unique()` function which must be applied by default
6. Several existing filter operators will need modification, as uniqueness can not be assumed

**Comment by matabele** [comment]
It appears that the two functions which impose uniqueness are: parseStringArray() and pushTop().

Both functions could be modified to accept an additional 'allow' parameter, which if set to "true", would suppress the code for removing duplicates.

**Comment by CodaCodr** [comment]
See also this group discussion:

https://groups.google.com/forum/#!topic/tiddlywiki/KzDgSIrPOXI

**Comment by pmario** [comment]
@Jermolene ... This one can be closed, since we can avoid de-duplication now.

**Comment by Jermolene** [comment]
Thank you @pmario
