### ISSUE TITLE
Apparent Syntax Inconsistency -- list[] Filter Operator

### ISSUE THREAD

**Issue by matabele** [Jermolene/TiddlyWiki5#2124]
When specifying a field other than the default 'list' field -- the current syntax uses square brackets to delimit the TextReference:

`+[list[MyTiddler!!my-list]]`

This can be confusing -- as other filter operators use single curly brackets to delimit the TextReference:

`+[tag{Settings!!mytag}]`

**Comment by tobibeer** [comment]
The two are separate things. One defines how a filter — here the list filter — expects its operand to be defined. The other defines a generic way to pass content to the operand.

As for the **list** filter, I imagine it's been implemented before the operand transclusion syntax was available. As for backwards compatibility, there's not much of a chance to get rid of that now. 

If it is the functionality you would expect from  `[list{Settings!!mytag}]` that you actually find missing, we could create a new filter that operates in this mode, e.g. `[titles{Settings!!mytag}]`... which always interprets the operand as the kind of "stringified" titles we find in the **list** or **tags** field.

**Comment by matabele** [comment]
For backward compatibility -- the list[] operand could be modified to also accept the generic syntax using curly brackets (whilst keeping it's existing syntax)

**Comment by tobibeer** [comment]
> For backward compatibility -- the list[] operand could be modified to also accept the generic syntax using curly brackets (whilst keeping it's existing syntax)

How precisely would you suggest it does that?

**Comment by tobibeer** [comment]
Let me illustrate:

```
title: foo
list: bar baz [[mumble frotz]]

{{{ [list{foo!!list}] }}}

=> Passes `bar baz [[mumble frotz]]` as the operand

{{{ [list[foo]] }}}

=> Passes `foo` as the operand
```

**Comment by matabele** [comment]
Currently `[list[]]` passes the TextReference `{currentTiddler!!list}` as the operand -- and `[list[Days of the Week!!short]]` returns "Mon Tue Wed thu Fri Sat Sun`. This looks to be a TextReference.

**Comment by tobibeer** [comment]
It is indeed a //text reference//. However, the other syntax is **not**, it is a //transclusion//. Using the same operand with the transclusion syntax passes something entirely different to the filter operand:

* `[list[Days of the Week!!short]]`
    * operand: `Days of the Week!!short`

* `[list{Days of the Week!!short}]`
    * operand: `Mon Tue Wed thu Fri Sat Sun`

How do you imagine consolidating this?

**Comment by matabele** [comment]
More consistency would be gained by adopting the schema used for the field[] operator (where the field name is passed by the suffix) -- thus list[] would  function as the field[] operator, but treating the field as a list.

For example: 

 `[list[MyTiddler]]` -- returns the list contained in the 'list' field of 'MyTiddler' (suffix defaults to 'list')
 `[list:my-field[MyTiddler]]` -- returns the list contained in the 'my-field' field of 'MyTiddler'
 `[list{MyTiddler!!my-field}]` -- returns the lists contained in the 'list' fields of the list of tiddlers referenced

**Comment by Jermolene** [comment]
> More consistency would be gained by adopting the schema used for the field[] operator (where the field name is passed by the suffix) -- thus list[] would function as the field[] operator, but treating the field as a list.

I think I agree; the list operator was added quite early, before suffixes were supported, and then of course I couldn't go back and fix it because it was in use in the wild.
