### ISSUE TITLE
Feature request: Support for WebTorrent 

### ISSUE THREAD

**Issue by EdDixon** [Jermolene/TiddlyWiki5#2130]
I thought before I start the journey of building this and others as a plugins (xAPI still very much on my list), I should draw your attention to this Jeremy as another good technology possibly well aligned with TidddlyWiki's goals and possibly worthy of consideration as being added to the core. You had also mentioned earlier this year modifications to the core to help in the xAPI effort and I would like to follow up with you on those, as I suspect those modifications would be useful in this as well. This technology could add value as a decentralized means of providing communication within a distributed set of TiddlyWiki's over any TCP/IP-based network without the need for an established server, helping in my goal in communicating and distribution of educational content in a one teacher to many student's (as well as student to student) use cases for education. Short term it might be best to develop this as a plugin and then consider its inclusion. Either way, I thought I should announce my intention here in case anyone is working on anything similar.
https://github.com/feross/webtorrent
Thanks,

**Comment by tobibeer** [comment]
Hi @EdDixon...

* What is your intention?
* In which way do you envision TiddlyWiki to implement web-torrent?
* Could you perhaps sketch a (few) simple diagram(s) to illustrate the kind of communication pattern(s) you have in mind?

**Comment by pmario** [comment]
I'm also not really sure, what you want to achieve here.

WebRTC is a protocol, that is included in the browsers already. So if you just need a text or video chat, eg FireFox can do this out of the box. IMO no need to implement something into TW. see: http://techcrunch.com/2015/01/13/firefox-35-launches-with-simplified-hello-video-chat-service/

**Comment by EdDixon** [comment]
Again if this would be better implemented as a plugin I will approach it
that way but I feel this may well align with some of Jeremy's goals for TW5
just based on some of the comments and work he has done. I do understand
the need to keep the core as small and flexible as possible. What I hope to
use this for is as a means to transfer tiddlers from one TW5 instance to
another in a peer to peer fashion. Thereby allowing those and the
educational materials contained within them in my use case to also be
served in a serverless fashion. Removing the need for a centralized server
to provide hosting of a learning management system is what lead me to
discover TiddlyWIki in the first place and all my efforts have been towards
that goal. While WebRTC was designed to facilitate real time communication
which is used and beneficial to learning management systems this is not my
desired goal. I would like to use this as a mechanism to provide sharing of
educational contents within the TW5 file over webRTC as a webTorrent to
others without a need to install any other services or clients in that
process.

**Comment by tobibeer** [comment]
Ok, I think I slowly get the gist. I imagine you intend it as...

1. a kind of browser-only tiddler sharing technology
2. where each WebRTC node acts as a pseudo-server for tiddlers in some way
3. WebRTC peers can connect to each based in links they exchange
4. hopefully allowing a configurable link-syntax, handled by such a plugin
    1. e.g. to be able to specify a filter

This would definitely make for a great plugin.

The biggest challenges appear to be...

1. to communicate the WebRTC link once generated in the browser, however that works
    1. some "start WebRTC" button might generate the link, save it in a tiddler, save the wiki, and thus present it to visitors
2. to make that link dynamic (pass a filter) to allow query-like requests of nodes talking to each ohter

**Comment by pmario** [comment]
.. I get the info now too :)

The only problem I see is, that WebRTC needs a server to establish a connection. So if you want to control the whole stack, you need to run your own "connection server". Details about WebRTC see: http://www.html5rocks.com/en/tutorials/webrtc/infrastructure/ ... The main problem, that makes everything more complex is "security". ... To establish connections with firewall enabled makes the process much more complex, as it could be in an ideal world. ... 

>What I hope to use this for is as a means to transfer tiddlers from one TW5 instance to another in a peer to peer fashion. Thereby allowing those and the educational materials contained within them in my use case to also be served in a serverless fashion.

So the "impossible" point is: "serverless" ... You'll need one to connect. The communication itself is P2P. 

The good thing here is, that there are many organisations, that run free "connection" servers. eg: Mozilla. We can use there and others free offerings. ... but without internet connection or your own servers, there will be no WebRTC eg: local lan only.

**Comment by EdDixon** [comment]
@pmario which is why I am looking at WebTorrent as opposed to just a typical WebRTC stack. The entire server for the system in runs on nothing but javascript or like TW5 nodeJS making each TW5 a node in the system both client and server capable of distributing the content load if all of this works the way I understand it.

**Comment by Jermolene** [comment]
Hi @EdDixon webtorrents is interesting, thanks for pointing it out.

However, it looks like it is structurally a layer of JS above WebRTC that enables a modified BitTorrent protocol to run. It doesn't change anything about the needs of the underlying WebRTC protocol; we still need a ping server, and that need is rather baked into the way that routers and NATs work.

Anyhow, there's no shortage of WebRTC servers out there, and the dependency is very slight: the server is used for setup, but doesn't see the traffic.

I'm very interested in WebRTC; the Tiddlyfication of it would be the ability to use it do peer to peer syncing of tiddlers.

**Comment by daraniya** [comment]
Been watching this for a while... WebTorrent sounds like a system to allow for decentralized websites, allowing for anonymity. WebRTC is never going to allow that, as it leaks too much info, including your IP address. Being able to share data, or a website without worrying about hosting, being tracked, etc...

**Comment by EdDixon** [comment]
@daraniya Hi, The typical use case I am working towards would be within a trusted network and I am not expecting to get anonymity from the use of the torrent protocol. I do understand how that could be a consideration for use over internet to those with that need and have that expectation though. However, from the WebTorrent FAQ site "WebTorrent, on the other hand, doesn't require clients to trust a centralized server. Given a .torrent file or magnet link, the WebTorrent client downloads the file without trusting servers or peers at any point." So, even that might be possible I am sill getting up to speed about it all myself.

**Comment by EdDixon** [comment]
Years later as my brain still recovers, I log in to find I have a few lingering issues long forgotten. So, without objection closing this. The integration with the Beaker Browser I think provided the functionality I was looking for. To be honest, not sure it was so long ago.
