### ISSUE TITLE
Popup position, own refresh cycle after main refresh

### ISSUE THREAD

**Issue by tobibeer** [Jermolene/TiddlyWiki5#2131]
Popup positions must only be recalculated and refreshed after the main refresh cycle has finished.

Otherwise there may be contents, e.g. in list widgets, that are going to be rendered after a supposedly new popup position has been computed and the popup(s) re-rendered.

Personally, I think there should be no need at all to persist popup positions as states. They simply are recalculated on redraw with no statefulness attached, whatsoever... when it comes to their position.

Possibly, this was required for the current popup mechanism as it tried to decouple the button from the reveal whereas eventually they really should not be decoupled, but rather merged in a parent popup widget.

**Comment by tobibeer** [comment]
Admittedly, this is an edge case, since the problematic list I am talking about is one showing popup state tiddlers.

**Comment by Jermolene** [comment]
Hi @tobibeer there are certain situations where popup positions need recalculating, but the point of the current popup mechanism is that it largely avoids this problem: one arranges the button and the reveal to be in the same coordinate system (eg sharing a position: relative parent), and then the popup will always be in the right position as long as the relative positions of the button and reveal don't change.

> Possibly, this was required for the current popup mechanism as it tried to decouple the button from the reveal whereas eventually they really should not be decoupled, but rather merged in a parent popup widget.

I disagree. Merging the reveal and the button loses a lot of the required flexibility.

I'm inclined to close this ticket until you've got a specific proposal.

**Comment by tobibeer** [comment]
> I'm inclined to close this ticket until you've got a specific proposal.

I agree, actually thought I had closed it already for it's edge-casy-ness.
