### ISSUE TITLE
sticky popups

### ISSUE THREAD

**Issue by tobibeer** [Jermolene/TiddlyWiki5#2134]
Allow popups to be "sticky", i.e. so clicking inside them won't close them, e.g. to allow editing inputs within a popup.

```
<$button popup="$:/temp/pop">Click to edit!</$button>
<$reveal type="popup" state="$:/temp/pop" class="pop-edit">
<$edit-text tiddler="HelloThere" autoHeight="true" focus="true"/>
</$reveal>
<style>.pop-edit textarea{width:600px;min-height:200px;}</style>
```

Actually, clicking inside a popup should (by default) never close it! Not?

**Comment by matabele** [comment]
There is a technique to create a sticky popup -- used in the following example:

```
<$button tag="input" default="" popup="$:/state/demo"/>
<$reveal state="$:/state/demo" type="popup" text="" default="" class="tc-popup-keep tc-block-dropdown">
<$linkcatcher to="$:/StoryList!!list">
<div class="tc-table-of-contents">
<$button class="tc-btn-invisible">
<$action-deletetiddler $tiddler="$:/state/demo"/>
close</$button>
<<toc-selective-expandable 'Reference'>>
</div>
</$linkcatcher>
</$reveal>
```

**Comment by tobibeer** [comment]
I take it, the key here is "tc-popup-keep". This seems to work as desired. So, closing.

**Comment by tobibeer** [comment]
Mhhh, ok, maybe we leave this open until `tc-popup-keep` is documented.

**Comment by tobibeer** [comment]
@matabele ...btw, that's one nifty popup, nice.

**Comment by matabele** [comment]
@tobibeer ... yes, the problem with titles with spaces is annoying -- couldn't see an easy fix. The code I used for this quick tool was generic -- I sometimes use this code with user input (hence the unnecessary input tag in this case.)

**Comment by Jermolene** [comment]
> Mhhh, ok, maybe we leave this open until tc-popup-keep is documented

Good thinking, pull requests welcome!

**Comment by Spangenhelm** [comment]
Shall we close this gentlemen ?

**Comment by tobibeer** [comment]
@Spangenhelm, gone it is. :-) :+1:
