### ISSUE TITLE
Nested wikitext not working

### ISSUE THREAD

**Issue by benrshep** [Jermolene/TiddlyWiki5#2140]
Nesting wikitext does not work as documented. [[''Test''|link]] does not render bold

**Comment by tobibeer** [comment]
Where did you read that this would work?

Here's how you can achieve that:

```
''[[link]]''
```

Add to some [StyleSheet](http://tiddlywiki.com/#Using%20Stylesheets):

```
strong > a {
font-weight:bold !important;
}
```

Could possibly be in the vanilla StyleSheet.

**Comment by pmario** [comment]
IMO the StyleSheet should be as follows, to avoid the **toxic** `!important` rule.

```
strong .tc-tiddlylink {
 font-weight:bold;
}
```

As always: If stylesheets are modified, extensiv testing should be done, to be sure, that it's without unwanted side effects.

**Comment by pmario** [comment]
@benrshep ... If it works for you, please close the issue.

**Comment by Jermolene** [comment]
Thanks @pmario
