### ISSUE TITLE
expose milliseconds to $tw.utils.formatDateString()

### ISSUE THREAD

**Issue by tobibeer** [Jermolene/TiddlyWiki5#2141]
What placeholder to use?

**Comment by Jermolene** [comment]
Perhaps `0tttt` and `tttt`, with "t" standing for "thousandths"?

**Comment by tobibeer** [comment]
Sounds good.

**Comment by pmario** [comment]
@Jermolene ... This one can be closed. We use XXX for miliseconds. see: https://tiddlywiki.com/#DateFormat

**Comment by Jermolene** [comment]
Thank you @pmario
