### ISSUE TITLE
Release 5.1.10 before Christmas

### ISSUE THREAD

**Issue by Jermolene** [Jermolene/TiddlyWiki5#2143]
I'd like to try to get 5.1.10 released in the next couple of days. There is a brief opportunity to merge any uncontroversial pull requests that I've missed over the last few weeks (thanks to @tobibeer for pointing me at some of them, please everyone bump any issues that you'd like considered).

A hastily merged pull request can cause years of regret, so I'm really keen to stick to the simple stuff; if we need much discussion of an issue then it's probably better to push it to 5.1.11.

**Comment by pmario** [comment]
#2136 de-DE some language fixes should be fine :)

**Comment by Jermolene** [comment]
Thanks @pmario

**Comment by felixhayashi** [comment]
Hi Jeremy,

Really important for me is: https://github.com/Jermolene/TiddlyWiki5/pull/1933

I have tested it the last months in FF and Chrome and it works very well. Mario and Tobias also said it worked for them. Without this fix it is not possible to edit Tiddlers when working fullscreen with TiddlyMap which is a big drawback.

Thanks!

-Felix

P.S. I think https://github.com/Jermolene/TiddlyWiki5/pull/2048 should be an easy one.

**Comment by felixhayashi** [comment]
**Warning** @Jermolene: Alerts cannot be closed anymore. Maybe introduced with https://github.com/Jermolene/TiddlyWiki5/pull/1981 (just guessing from the title and the recent merge).

**Comment by tobibeer** [comment]
@felixhayashi, mhhh... confused. Will look into it.

**Comment by felixhayashi** [comment]
@tobibeer, it's really just a quick guess…

**Comment by tobibeer** [comment]
I'm pretty sure that that's the reason, just not how that went unnoticed.

**Comment by Jermolene** [comment]
Thanks for the help everyone.

Partly because I've ended up merging so many pull requests in the last 24 hours, I've decided to postpone the release until early next week.

Therefore, there's a few days to:

* Kick the tyres of the latest prerelease at http://tiddlywiki.com/prerelease -- perhaps try an experimental upgrade of some of your regular wikis
* Propose any community links that I've missed. Please don't be shy about nominating your own creations here; I'd like to present a broad selection of resources and examples

**Comment by matabele** [comment]
You might be interested in merging this: https://github.com/Jermolene/TiddlyWiki5/pull/2156

I've just completed the documentation, and @felixhayashi is interested in getting this into the core as soon as possible.

Seems to work -- haven't managed to find any edge cases that cause problems.

**Comment by tobibeer** [comment]
@matabele,

> My preference for the core -- to leave the $radio widget as is, and replace the $checkbox widget with the $checklist widget.

Admittedly, I did not read through the entire code ...and always argued from a functional pov. With regards to that, I wonder, can't we afford both widgets, checkbox and checklist? ...on the premise of reducing the checklist functionality to mere list-handling and none other? ...so no aspirations of replacing checkbox, but rather providing checkbox-mgt for list fields and that's it?

**Alternatively** to a checklist widget aspiring to **replace** checkbox, I think I'd still favor a clear **mode** attribute to checkbox over a checklist widget that provides all it's functionality **plus** list-mgt. One that is not needed by default, so checkboxes behave in their "simple" non-list ways of today, but if specified allows users to gracefully handle list-fields as well.

**Comment by matabele** [comment]
The "Filter Operators" page seems to be missing in the tw5.com edition pre-release. Try looking up filters in the reference section of the Contents tab.

**Comment by matabele** [comment]
@tobibeer 

The predominant use of the $checkbox `field` attributes seem to be for settings; the values for the `checked`, `unchecked` and `default` attributes most often being simple one word strings such as yes/no, enable/disable or show/hide. 

* The $checklist widget can handle these cases (although I haven't included a `default` attribute.) My aim was to cut out anything that wasn't to do with handling list items with checkbox lists (but, if necessary this could be added.)
* The $checklist widget can, of course, replicate any functionality with regards the 'tags' fields (only attribute name changes from `tag` to `item` and `invertTag` to `invert`.)
* That leaves only toggling between two strings with spaces; which is the primary purpose of the $radio widget.

In any case, any decision to replace the $checkbox widget will be made in the future.

**Comment by felixhayashi** [comment]
> I wonder, can't we afford both widgets, checkbox and checklist? ...on the premise of reducing the checklist functionality to mere list-handling and none other? ...so no aspirations of replacing checkbox, but rather providing checkbox-mgt for list fields and that's it?

This is what I am arguing [here](https://github.com/Jermolene/TiddlyWiki5/pull/2156#issuecomment-167402561). The checklist widget is a great addition and I am very happy @matabele took the initiative and implemented it, but the checkbox still has its purpose.

**Comment by felixhayashi** [comment]
Hi @Jermolene 

The multiple selection feature of the select widget throws an error: `Uncaught TypeError: Cannot read property 'indexOf' of null`

-Felix

**Comment by felixhayashi** [comment]
Also there is a recursion error in TW that you have not responded to yet. Just to make sure you are aware of it: #2025

**Comment by tobibeer** [comment]
Eric also reported the multiple select problem [here](https://groups.google.com/d/msg/tiddlywiki/W85Ok3QDB6U/MdKeQRMFCgAJ) voicing another meaningful expectation of being able to specify a "number of displayed lines" for a multiple-select-widget.

**Comment by matabele** [comment]
Don't know if this is an old bug? 

When checking a checkbox in the story river --  the river sometimes scrolls (jumps) down away from the active checkbox -- on other occasions the river remains stationary (the desired behaviour.)

This behaviour can be annoying when checking a list of checkboxes -- as the river has to be scrolled before checking the next box in a column of checkboxes.

Can not work out why the this behaviour is inconsistent.

**Comment by matabele** [comment]
@Jermolene 

I have changed the name of the `list` attribute of the ActionListops widget to `field`. Other users felt that this was the natural choice, and maintains consistency with the Checkbox widget: https://github.com/Jermolene/TiddlyWiki5/pull/2156

It might be an idea to make this change before users become accustomed to `list` -- relevant PR:
https://github.com/Jermolene/TiddlyWiki5/pull/2160
https://github.com/Jermolene/TiddlyWiki5/pull/2161
https://github.com/Jermolene/TiddlyWiki5/pull/2162

**Comment by tobibeer** [comment]
@matabele, thanks for reacting to @felixhayashi's response. I think the change makes sense and helps improve consistency.

**Comment by felixhayashi** [comment]
> I have changed the name of the list attribute of the ActionListops widget to field.

Thanks @matabele, you are right, makes sense for ActionListops widget as well. Looking forward to use this widget!

> I think the change makes sense and helps improve consistency.

Thanks for confirming @tobibeer

**Comment by tobibeer** [comment]
@Jermolene, I think we should fix this for 5.1.10:

#2172 — search popup not opening
