### ISSUE TITLE
Check if all fields are empty before deleting a tiddler without prompting

### ISSUE THREAD

**Issue by Spangenhelm** [Jermolene/TiddlyWiki5#2158]
Hello everyone, atm tiddlywiki only checks if the body of the tiddler is empty or not before deleting a tiddler without an alert (using the classic delete button), this can be dangerous for data safety for the reason that if we have filled-up ten fields but that there is nothing in the body it can be lost by a single wrong click !
If i'm correct the body and the title are fields too so basically the system should check if every field is empty (or containing a default value = not modified, eg the title) before deleting without notice!

**Comment by twMat** [comment]
+1

**Comment by tobibeer** [comment]
:+1:  sounds reasonable

**Comment by pmario** [comment]
I did track it down to the function: `wiki.isDraftModified()` at https://github.com/Jermolene/TiddlyWiki5/blob/master/core/modules/wiki.js#L1169

It only checks differences, if the original tiddler exists. So if a "New Tiddler" is just to be created, the check fails. .. a bit more investigation needed.
