### ISSUE TITLE
The Checkbox widget "default" attribute doesn't appear to operate as expected

### ISSUE THREAD

**Issue by matabele** [Jermolene/TiddlyWiki5#2163]
The purpose of the `default` attribute of the Checkbox widget would appear to be; to set the value of the target field to the default value before a selection has been made. This does not appear to be the case.

1. Create a new test tiddler 
2. Insert a Checkbox widget to toggle the value of a field
3. Set the default to the `checked` value
3. Transclude the value of the field (to make the contents visible)
4. Close the tiddler 
5. Notice that the checkbox is checked (as it should, if the field value matched the `checked` default value)
6. But the field value remains undefined until a selection has been made
7. At which point, the value reflects the `unchecked` value, rather than the default value
8. Thereafter, the behaviour is as expected. 

Seems the action of the `default` attribute is redundant. Or, am I misunderstanding the purpose of the `default` attribute?

Sample code used as follows:

```
<$checkbox field="testing" checked="default value" unchecked="other value" default="default value">Switch</$checkbox>

{{!!testing}}
```

**Comment by tobibeer** [comment]
@matabele, mhhh... clearly if you were to change the default to nothing at all you'd get the opposite result. So, it's seems way to declare how "undefined" is to be interpreted. Whether an undefined "default" state eventually means "checked" ...is for whichever other code to take care of, I believe.

**Comment by matabele** [comment]
@tobibeer 

This means the `default` attribute does nothing (except, perhaps, mislead.) If a selection has never been made -- the attribute sets the checkbox to a meaningless value, and thereafter it doesn't apply.

Why have the `default` attribute (and its associated code) at all?

**Comment by tobibeer** [comment]
> Why have the default attribute (and its associated code) at all?

I believe to specify what the default (/undefined) state is to look like in a ui, regardless of any actually stored data. A checkbox being checked does not necessarily require for a user having to check it in the first place.

**Comment by matabele** [comment]
@tobibeer 

This can not have been the original intention. There is code to compare the `default` attribute value with the `checked` and `unchecked` values. If this was for appearance only, this would be unnecessary, as the user could simply specify default="true/false".

**Comment by tobibeer** [comment]
>  If this was for appearance only, this would be unnecessary, as the user could simply specify default="true/false".

For something to be true/false there needs to be a logical assessment first. In wikitext, there is no generic true/false in wikitext, so we're always checking text against other text. Hence, we're checking against a default value of type text.

**Comment by matabele** [comment]
@tobibeer 

But, entering two strings of text (which may be long) to match isn't the easiest way to do this. The user could simply enter `default="whatever"`, and the code could take it from there:

`return (this.checkboxDefault) ? true : false;`

**Comment by tobibeer** [comment]
Usually, you would not use literal strings with these widgets, but placeholders in the form of Text-References or variables composed elsewhere. Again, html attributes do not have literal true or false assignments. It's all (interpretation of ) text.

**Comment by matabele** [comment]
@tobibeer 

I am working on revising the $checkbox widget (taking out the `tag` and `invetTag` attributes) and still don't really see the point of the `default` attribute, and even if the default setting is to remain, the implementation seems unnecessarily complex and will often be more difficult to use than a simpler mechanism. 

What I really need to know is: What do users expect from this attribute?  ... Then I can code accordingly.

**Comment by tobibeer** [comment]
Atm, I'd leave it to @Jermolene to give feedback on this as I am not actually aware of the design considerations that brought about the "default" attribute ...and merely inferred the best reason I could think of.

**Comment by Jermolene** [comment]
Hi @matabele the purpose of the 'default' attribute for the checkbox widget is to provide a fallback value for the specified field if the tiddler or field doesn't exist.

It is used in the computation of the current status of the checkbox: the basic logic is to mark the checkbox as checked if the tiddler field value is equal to the value of the "checked" attribute, and mark it as unchecked if the tiddler field value is equal to the value of the "unchecked" attribute. If the tiddler or field doesn't exist, the logic proceeds as if the field did exist, and had the specified default value.

**Comment by matabele** [comment]
@Jermolene 

Ah ... many thanks. What is perhaps confusing, is that: when the checkbox is checked, and the field is missing or undefined. To me, it would make better sense if the checkbox were unchecked should the field be missing or undefined (whatever the possible values.)
