### ISSUE TITLE
Crazy scrolling when a draft exists in river and edit button is pressed again

### ISSUE THREAD

**Issue by felixhayashi** [Jermolene/TiddlyWiki5#2167]
When a tiddler is opened in draft mode somewhere in the river (let's say at the very bottom) and also its original tiddler (denoted by `draft.of`) is contained in the river, clicking on the edit button will produce a chaotic scroll action. This results from the draft tiddler being removed and added while also being navigated to.

E.g. in the current TW5 release at http://tiddlywiki.com (v5.1.9)
1. scroll down till you see the `Community` tiddler.
2. Open the tiddler in edit mode
3. Go to the search box and search for the `Community` tiddler and open this tiddler (it will open at the top of the river).
4. Open the `Community` tiddler in edit mode
5. Crazy scrolling takes place

I suggest the following to remedy the problem:

After a click of the edit button it should first be checked if a draft of this tiddler exists in the river. If yes, simply navigate to this draft, if not, open the draft and navigate to it.

-Felix

**Comment by twMat** [comment]
HA! You might just have discovered the mysterious scrolling problems I've had forever with TW5 but never managed to pinpoint or reproduce (and therefore never been able to even describe). It makes sense; I typically have many tiddlers open (as well as many tabs, broswer windows... and a zillion parallel thoghts...)

**Comment by felixhayashi** [comment]
> HA! You might just have discovered the mysterious scrolling problems 

Nice!

> (as well as many tabs, broswer windows... and a zillion parallel thoghts...) 

This is how it is supposed to be. Never be afraid to lose sight of previously opened content, never close tabs, always keep them open for later return, yet, most importantly: never look back! Be brave and laugh in the face of the beast called "information overflow", just keep on opening tabs and windows, gain as much knowledge as you can before your RAM runs out and you need to reboot. People may say this is madness – this ain't madness, this is Spartaaa!

**Comment by twMat** [comment]
You're reading my mind verbatim. The limit of imagination is RAM.

BTW @Jermolene - the problem is also in 5.1.10 prerelease

**Comment by pmario** [comment]
Nice catch!

If I'm searching for "Community" in step 3 I can see the following search results: 

 Community 
 Draft of 'Community'

So I think, if I click the "Community" button, it should immediately jump to the draft tiddler. ... IMO there is a reason, why I opened it and if I want to see it rendered, I need to close it, or finish my editing first. 

So I propose: 

 - If any tiddler is in "draft mode", clicking the link to the tiddler should show the draft and not the tiddler.

**Comment by twMat** [comment]
>So I propose:
>
>*   If any tiddler is in "draft mode", clicking the link to the tiddler should show the draft and not the tiddler.

+1
The would also diminish the dual nature of tiddlers when editing. I've  [said it before](http://twaddle.tiddlyspot.com/#The%20current%20editor%20concept); I think the editing implementation in TW is conceptually confusing.

**Comment by felixhayashi** [comment]
> So I think, if I click the "Community" button, it should immediately jump to the draft tiddler. ... IMO there is a reason, why I opened it and if I want to see it rendered, I need to close it, or finish my editing first. 

But then you will never be able to open the original tiddler unless you cancel the draft completely or save it which might override changes that were made to the original tiddler in the meantime e.g. by a plugin. See https://github.com/Jermolene/TiddlyWiki5/issues/2108.

Moreover, sometimes you may actually want to open the original tiddler because you are not sure what you changed in the draft tiddler. Imagine you clicked the edit button on Monday, modified a lot of content and closed the wiki. On [Friday](https://www.youtube.com/watch?v=kfVsfOSbJY0) you open your wiki and want to look at the original tiddler but your wiki doesn't allow this and forces you to look at the draft. First you think "What? I don't want to look at a draft, I want to see the original tiddler". Then you accept it and say "Ok, so here is the draft. Should I cancel it or should I accept the changes. Hmm let me look at the original tiddler to check what I actually changed…" TW keeps navigating to the draft and you start to think "How on earth can I open the original tiddler, I need to look at it and compare my changes" – you feel lost, frustrated and vowe to never use TW again.

I think the soft approach to the problem I suggested in the OP, which is just to scroll to the draft if it is present in the river, solves it pretty well and doesn't restrict the user in his/her possibilities to control the wiki.

**Comment by tobibeer** [comment]
> I think the soft approach to the problem I suggested in the OP, which is just to scroll to the draft if it is present in the river, solves it pretty well and doesn't restrict the user in his/her possibilities to control the wiki.

:+1: If both are open, the story should scroll to the one clicked.

**Comment by pmario** [comment]
>If both are open, the story should scroll to the one clicked.

agreed!

**Comment by Jermolene** [comment]
Given the implementation of `$:/StoryList`, we can't enforce any restrictions on having a draft and the original tiddler open at once. The best we can do is to handle these cases sensibly during navigator operations. It sounds as though the problem under discussion here is with `handleEditTiddlerEvent()` in navigator.js, I'll investigate further.

**Comment by Jermolene** [comment]
OK it's taken quite a lot of investigation to figure this out. It's actually nothing to do with draft tiddlers; it's a more fundamental problem with the classic storyview.

The first point is the way that the classic storyview handles the removal of items from the list: it defers actually removing the corresponding DOM nodes until the deletion animation has completed.

The second point is that @felixhayashi's sequence of steps in the original post result in the following sequence of insertions and deletions:

```
* Open the tiddler in edit mode
insert Draft of 'Community'
remove Community
navigateTo Draft of 'Community'
* Go to the search box and search for the Community tiddler and open this tiddler (it will open at the top of the river).
insert Community
navigateTo Community
* Open the Community tiddler in edit mode
remove GettingStarted
remove HelloThere
remove TiddlyWiki Pre-release
remove Community
insert TiddlyWiki Pre-release
insert HelloThere
insert GettingStarted
navigateTo Draft of 'Community'
```

The problem occurs with that final "navigateTo" at the point where we calculate the position of the tiddler "Draft of 'Community'" in the story river. The trouble is that the preceding four removals are still pending at that point, so the position of the tiddler is pushed down to accommodate the not-yet-deleted tiddlers.

There are several potential fixes, but they all involve a fair amount of refactoring, and so I won't try to fix this before 5.1.10.

**Comment by felixhayashi** [comment]
Hi @Jermolene 

> The trouble is that the preceding four removals are still pending at that point, so the position of the tiddler is pushed down to accommodate the not-yet-deleted tiddlers.

Ah, ok.

> There are several potential fixes, but they all involve a fair amount of refactoring, and so I won't try to fix this before 5.1.10.

:+1:
Would be nice if you could post/explain your approaches once you decide to pick this up so I also get the chance to update the "top storyview" which, like classic, is also affected by this problem.

-Felix

**Comment by Jermolene** [comment]
> Would be nice if you could post/explain your approaches once you decide to pick this up so I also get the chance to update the "top storyview" which, like classic, is also affected by this problem.

The problem is with the classic storyview. When we delete items from the list, during the animation the DOM elements should be moved to the end of the container, and CSS used to put them in the correct position.

In any case, I'd like to revisit the classic storyview to add a proper animation for switching between view and edit modes.

**Comment by twMat** [comment]
Solved? I can't find an old enough TW to tell and when trying the outlined steps in a new TW there *is* a small twitch but I don't think it is the one discussed in this thread... and I think the current small twitch barely warrants an issue so can someone help to decide if this issue should be closed?

**Comment by Jermolene** [comment]
Hi @twMat yes it looks much better, but it would be good to have @felixhayashi confirm.

**Comment by felixhayashi** [comment]
Hi @Jermolene, @twMat following my steps outlined in the OP there is a short unessary scroll but I don't think this is what I was referring to when I openend this ticket long time ago. I will close this.
