### ISSUE TITLE
search popup not opening

### ISSUE THREAD

**Issue by tobibeer** [Jermolene/TiddlyWiki5#2172]
Here's how I would recommend reproducing the sporadic non-opening of the new search results popup on [5.1.10 prerelease](http://tiddlywiki.com/prerelease/).

1. enter a search term
2. click on a result in the search results popup
3. click the input to enter another search term

=> the popup is no longer popping up

In other words, whenever the search input gains focus and it already contains a search term, the results popup needs to:

1. stay open
2. otherwise be opened

**Comment by tobibeer** [comment]
@Jermolene, I think we should try to fix this for 5.1.10 (#2143).

**Comment by Jermolene** [comment]
Although a small change, this one is quite subtle, and so I'd appreciate help with testing it to make sure it doesn't impact other aspects of popup behaviour.

I've uploaded a new prerelease: http://tiddlywiki.com/prerelease

**Comment by tobibeer** [comment]
@Jermolene, thanks a lot. The popup now works as I would expect. :+1: 

I also tested all examples for [tobibeer/appear](http://tobibeer.github.io/tw5-plugins/#appear) involving popups and those also work as expected.

**Comment by Jermolene** [comment]
Thanks @tobibeer!
