### ISSUE TITLE
enhanced dictionary tiddlers (indexes, separators and split-delimiters)

### ISSUE THREAD

**Issue by tobibeer** [Jermolene/TiddlyWiki5#2176]
1) It may happen that we want to declare indexes that contain a colon.

Currently, there appears to be no way to achieve that by either `escaping \: the: colon` or otherwise wrapping the index, e.g. as `[[foo:bar]]:baz`.

2) We may actually need or prefer to specify a custom separator. For this, a field e.g. `tc-data-separator` could be used to specify the character(s) we actually want to use to delimit keys from values, e.g.:

```
title: foo
type: application/x-tiddler-dictionary
tc-data-separator: =>

key=>val
foo=>bar
```

3) Likewise, it may be required to use multi-line data. Currently it appears that a dictionary cannot hold multiline content, e.g. for forcing inner content to be parsed in block mode.

This could be achieved through another field, e.g `tc-data-split`:

```
title: foo
type: application/x-tiddler-dictionary
tc-data-separator: \n
tc-data-split: \n++++\n

key
value
++++
foo

!! Bar

<$baz>

* mumble
** frotz
*** gronk
</$baz>
++++
yada
yada
```

4) Eventually, it may make a difference whether we trim a key or not.

**Comment by Jermolene** [comment]
@tobibeer the tiddler dictionary format is designed for ease of typing. In situations where it is not suitable one can use JSON data tiddlers instead.

**Comment by tobibeer** [comment]
ok, I take this as too much
