### ISSUE TITLE
[Feature Request]: Allow selecting and deleting tiddlers directly from the search by filter

### ISSUE THREAD

**Issue by Spangenhelm** [Jermolene/TiddlyWiki5#2178]
Hi guys, i was thinking about implementing a delete option directly from a list generated with a filter (available in the advanced search tiddler) this way it would be really easy to mass delete only specificly selected tiddlers:
- by using a checkbox for each item to select
- a "select-all" option (in case of a lot of tiddlers to delete -> this is the main purpose of course) is mandatory to me to maximize the ease and the speed of the process!
- and so is a clear warning before the definitive deletion ! (and maybe a message before to remind the user to save to prevent data loss would not be useless)

As a bonus this new feature could be adapted to be used for mass tag adding/deleting/renaming !

**Comment by twMat** [comment]
I like this idea. You headline this as a "feature request" but in your description it sounds like you're about to implement it yourself - ? Regardless, I think it would be a valuable addition to common tiddler management.

**Comment by tobibeer** [comment]
I'd also like to see basic batch processing options in the Advanced Search (/Filter) tabs... whether through checkboxes or direct buttons or both or "delete all" buttons or the likes ...perhaps needs some basic mockups to figure out what would be the best ui.

**Comment by Spangenhelm** [comment]
Hi guys, glad that you like the idea!
@twMat haha i wish i could do so myself but for example i have no idea how to create a "select-all" option.. (it needs to be done in js no? then i'm lacking knowledge and practice to do so :lollipop:)

@tobibeer about the ui: except displaying the checkbox before the name to ease the process of selecting no matter the length of the names i don't think it needs anything special, the hardest part will be to elaborate the filter first to target the right tiddlers to delete, then most of the time we will be able to only use the "select-all" button no ?

In fact i have just realised that a filter "constructor" would be a great help (under the shape of a form with buttons and select inputs for options) but that's another story..

Btw happy new coding year ;-)

**Comment by gernert** [comment]
Related to #192 (Extend link widget to link to a filtered list)?

**Comment by inmysocks** [comment]
Would something like the [tiddlertool](http://ooktech.com/jed/ExampleWikis/TiddlerTools/) I made be a possible solution? Compared to what is being discussed it seems like overkill but hopefully it is a starting point for deciding what works.

**Comment by Jermolene** [comment]
Thanks @Spangenhelm. I think this is a take on the broader idea of a tiddler manager that presents tiddlers in a filtered list or grid view with select checkboxes, enabling multiple operations such as deleting, bulk renaming, exporting, etc. As you've noted, the advanced search box includes the groundwork for this functionality already. We've discussed the idea in one or two hangouts, and I could have sworn that there was a ticket for it. @inmysocks' tiddlertool is pretty close to what I've had in mind.

**Comment by Spangenhelm** [comment]
@gernert i'm unsure..

@inmysocks +1 ! I don't know why but the layout is somewhat broken with my browser (chromium), apart from this: good job !

Thanks @Jermolene if there is a ticket already open i haven't found it, if you do i will close this one ;-)

**Comment by pmario** [comment]
@Spangenhelm ... Can you have a look at: https://tiddlywiki.com/#%24%3A%2FManager ? If it fits your needs, you may close this issue?

**Comment by Jermolene** [comment]
Thanks @pmario
