### ISSUE TITLE
Simplify (and actually fix) PageScroller

### ISSUE THREAD

**Issue by tobibeer** [Jermolene/TiddlyWiki5#2180]
Please fix and simplify in [PageScroller.prototype.scrollIntoView()](https://github.com/Jermolene/TiddlyWiki5/blob/72941f3e9a916948222ff7be540d896e2b1901f6/core/modules/utils/dom/scroller.js#L53-L120), e.g. by reducing [getEndPos()](https://github.com/Jermolene/TiddlyWiki5/blob/72941f3e9a916948222ff7be540d896e2b1901f6/core/modules/utils/dom/scroller.js#L74-L94) to a mere:

```
var getEndPos = function(targetPos,targetSize,currentPos,currentSize) {
    return targetPos < 50 ? 0 : targetPos;
}
```

I created a demo that appears to work just fine here: http://scroller.tiddlyspot.com ...which actually does away with ''getEndPos'' entirely. [Here's a commit](https://github.com/tobibeer/TiddlyWiki5/blob/anchor-support/core/modules/utils/dom/scroller.js#L63-L69) showing the much simplified end result ([compare here](https://github.com/Jermolene/TiddlyWiki5/compare/master...tobibeer:anchor-support)).

I have been irritated by this scrolling behavior for a long time.

Let's simply have the element scroll to one consistent spot: the top of the view-port. And that's it.

I am currently trying to implement anchor links and cannot use PageScroller at all, because it doesn't actually scroll elements into view, except when my link is below the target to be scrolled to. So, I always need to scroll down more to even have the very top come into view at the bottom. You see, an anchor link doesn't have a dimension.

But why would the target size be of concern for a scroller to scroll an element into view? All that counts appears to be the top-left corner ...and we're done.

**Comment by Jermolene** [comment]
Hi @tobibeer 

One trouble is that we can't just set the scroll position to the top of the tiddler; consider what happens with a tiddler that is shorter than the screen and at the end of the story list. When we scroll to it we can't scroll that tiddler to the top of the viewport, the best we can do is to ensure that the tiddler is visible at the bottom of the viewport.

> I am currently trying to implement anchor links and cannot use PageScroller at all, because it doesn't actually scroll elements into view, except when my link is below the target to be scrolled to. So, I always need to scroll down more to even have the very top come into view at the bottom. You see, an anchor link doesn't have a dimension.

I think you'd want to get a reference to the tiddler frame, and point the page scroller at that, rather than at the anchor itself.

**Comment by tobibeer** [comment]
> One trouble is that we can't just set the scroll position to the top of the tiddler; consider what happens with a tiddler that is shorter than the screen and at the end of the story list. When we scroll to it we can't scroll that tiddler to the top of the viewport, the best we can do is to ensure that the tiddler is visible at the bottom of the viewport.

While true, this problem is independent from scrolling to an element. If we can't get further down, then we can't get further down, and can perhaps imagine ways of doing so nonetheless, independently.

Atm, I fail to see any reasons for these distinctions.

> I think you'd want to get a reference to the tiddler frame, and point the page scroller at that, rather than at the anchor itself.

The point of anchors is to be able to scroll to them.

**Comment by Jermolene** [comment]
@tobibeer the purpose of the page scroller is to animate scrolling the page so that as much of an element as possible is visible in the viewport. That's why we need to take into account the edge case of an element that can't be positioned at the top of the viewport because it is too close to the bottom of the page.

**Comment by tobibeer** [comment]
>  That's why we need to take into account the edge case of an element that can't be positioned at the top of the viewport because it is too close to the bottom of the page.

I would understand that ...but, afaics, that is not at all what the code is doing. Instead, in merely scrolls an element's upper corner to the lower edge... which is what I find quite irritating.

As for scrolling up too small an element that does not have anything following it... wouldn't we rather need some spacer that is about as tall as the viewport to avoid the issue?

**Comment by felixhayashi** [comment]
> As for scrolling up too small an element that does not have anything following it... wouldn't we rather need some spacer that is about as tall as the viewport to avoid the issue?

The top story view adds such a spacer to be able to display a small element at the very top.

See [TopStoryView.prototype.recalculateBottomSpace](https://github.com/felixhayashi/TW5-TopStoryView/blob/master/src/plugins/felixhayashi/topstoryview/top_story_view.js#L178).

**Comment by Jermolene** [comment]
> .but, afaics, that is not at all what the code is doing. Instead, in the second else if, in merely scrolls an element's upper corner to the lower edge... which is what I find quite irritating

You mean this:

```
// If the target is big, then just scroll to the top
			} else if(currentPos < targetPos) {
				newPos = targetPos;
```

All that's happening there is that we scroll long tiddlers to the top. What else would you do in that case?

> As for scrolling up too small an element that does not have anything following it... wouldn't we rather need some spacer that is about as tall as the viewport to avoid the issue?

I'm not so keen on the technique; it gives the page non-standard behaviour.

**Comment by tobibeer** [comment]
> Instead, in the second else if, in merely scrolls an element's upper corner to the lower edge... which is what I find quite irritating

Sorry, I was pointing at the wrong case, I mean the [first else-if](https://github.com/Jermolene/TiddlyWiki5/blob/72941f3e9a916948222ff7be540d896e2b1901f6/core/modules/utils/dom/scroller.js#L79-L81).

**Comment by tobibeer** [comment]
Anyhow, with the modifications as in [the demo](http://scroller.tiddlyspot.com/) I did not find any suspicious behavior... so, I really don't know what those cases actually try to handle... rather than... well, kinda break.

**Comment by Jermolene** [comment]
@tobibeer what is the part that you don't understand? Are you still arguing that the code should just scrollTo the top/left of the targetted element?

**Comment by tobibeer** [comment]
I am not only arguing that, I'd really like to know under what circumstances the code as-is is doing any good. Because I can't think of any.

**Comment by Jermolene** [comment]
But @tobibeer the cases where it is causing problems is where you are trying to use it for something for which it was not designed. And there's a simple fix: target the tiddler frame instead of the anchor element. Isn't that all there is to it?

As to the scrolling behaviour, just read the code: there are some subtleties, such as if the target is below the viewport we only perform the minimal scrolling to bring the element into view. But the motivation is obvious if you consider the actual use case that the code is written for.

**Comment by tobibeer** [comment]
> Isn't that all there is to it?

As said, the tiddler is **not** my target: an element inside it is... and the core functions to scroll an element into view should be so generic as to cater for that simple use-case.

> As to the scrolling behaviour, just read the code: there are some subtleties, such as if the target is below the viewport we only perform the minimal scrolling to bring the element into view.

As the demo illustrates, there appears to be no point to any of that... at least, I fail to construct a case where there is. The only minimal scrolling happening is the one that is pretty much broken, i.e. where we hardly see the very top of an element at the very bottom of the viewport.

> But the motivation is obvious if you consider the actual use case that the code is written for.

I did read the code and try to make sense of it. I simply fail to see / construct a case where the current core code would behave better than [the linked demo]( http://scroller.tiddlyspot.com) (which does away with any of the sophisticated cases that actually cause the above mentioned troubles / broken behaviour).

**Comment by Jermolene** [comment]
Let me try to explain. Here's the original code:

```

	// We'll consider the horizontal and vertical scroll directions separately via this function
	// targetPos/targetSize - position and size of the target element
	// currentPos/currentSize - position and size of the current scroll viewport
	// returns: new position of the scroll viewport
	var getEndPos = function(targetPos,targetSize,currentPos,currentSize) {
			var newPos = currentPos;
			// If the target is above/left of the current view, then scroll to it's top/left
			if(targetPos <= currentPos) {
				newPos = targetPos;
			// If the target is smaller than the window and the scroll position is too far up, then scroll till the target is at the bottom of the window
			} else if(targetSize < currentSize && currentPos < (targetPos + targetSize - currentSize)) {
				newPos = targetPos + targetSize - currentSize;
			// If the target is big, then just scroll to the top
			} else if(currentPos < targetPos) {
				newPos = targetPos;
			// Otherwise, stay where we are
			} else {
				newPos = currentPos;
			}
			// If we are scrolling within 50 pixels of the top/left then snap to zero
			if(newPos < 50) {
				newPos = 0;
			}
			return newPos;
		},
```

The logic is as follows:

* If the target is above/left of the current view, then scroll to its top/left
* If the target is smaller than the window and the scroll position is too far up, then scroll till the target is at the bottom of the window. This is so that we minimise the scrolling of the page to make small targets visible
* If the target is bigger than the window, then just scroll to the top
* Otherwise, stay where we are. This is the case where the scroll position is already within the target element

Does that help? Which parts of the logic are unclear?

**Comment by tobibeer** [comment]
It's difficult to say it otherwise: Show me a case where all that matters. My demo has all of this removed and works just the same.

**Comment by Jermolene** [comment]
> Show me a case where all that matters

This is getting a bit surreal. I've enumerated the four different cases, and explained the situation where they apply. It boils down to two things: (a) we can't just set the scroll position to the top left corner because of the problem of elements that are smaller than the viewport at the bottom of the scrollable region and (b) we try to minimise scrolling that is needed to bring an element into view.

**Comment by tobibeer** [comment]
> (a) we can't just set the scroll position to the top left corner because of the problem of elements that are smaller than the viewport at the bottom of the scrollable region

the current core code does not cater for this either and there is literally no problem about it as the browser cannot scroll to that position anyway

> (b) we try to minimise scrolling that is needed to bring an element into view

how exactly is anything minimized? there is a position a thing is supposed to show up ...the distance to it is a given measure => there is literally nothing to be minimized about that

**Comment by tobibeer** [comment]
I'd really appreciate if you could show precisely (not use descriptive language) where the core code works, well, better... rather than not.

**Comment by Jermolene** [comment]
> the current core code does not cater for this either and there is literally no problem about it as the browser cannot scroll to that position anyway

The current code does indeed cater for that case, as I've pointed out above. The fact that the browser can't scroll to such a tiddler affects the scroll animation; we have to choose a reachable end point for the animation.

> However, I'd really appreciate if you could take that moment to show precisely — rather than use descriptive language already present in the code — where the core code works, well, better... rather than not so well.

Compared to your replacement, the existing core code has the following differences:

* For elements smaller than the viewport that are currently below/right of the viewport, just scroll enough to make the element visible (rather than scrolling it to the top/left)
* When the viewport is within an element bigger than the viewport, don't scroll at all (so that navigating to a tiddler that you are already reading doesn't scroll)
* If scrolling to within 50 pixels of the top, snap to the top

Is the problem that those descriptions are not clear, or that you disagree with the logic?

**Comment by tobibeer** [comment]
> For elements smaller than the viewport that are currently below/right of the viewport, just scroll enough to make the element visible (rather than scrolling it to the top/left)

This is highly problematic for me. I always expect the element to scroll to a defined position ...somewhere up top.

> When the viewport is within an element bigger than the viewport, don't scroll at all (so that navigating to a tiddler that you are already reading doesn't scroll)

This I also find problematic, because the navigation re-calibrates my focus to where I asked it to.

> If scrolling to within 50 pixels of the top, snap to the top

I can see how this is helpful, but the 50 pixels should be configurable.

**Comment by tobibeer** [comment]
Eventually, a scroller that does not scroll to the element asked to scroll to... in any perceivable way or in a way that the element would always pop up at a defined spot ...is quite problematic, I'd think.

**Comment by tobibeer** [comment]
To me, having a scroller that does not scroll an element to a reliable spot is the problem, not one that would "scroll too much".

**Comment by Jermolene** [comment]
@tobibeer the behaviour under discussion has been in TW5 for many years. You're only complaining about it now that you are trying to use the mechanism for something that it is not designed for.

I think a better characterisation of the situation is that you're trying to use a core mechanism for a purpose for which it is not designed, and going on to propose to break the current functionality in order to make it behave as you need.

**Comment by tobibeer** [comment]
> You're only complaining about it now that you are trying to use the mechanism for something that it is not designed for.

I am not complaining about it. I simply don't see a benefit ...and instead: very real problems.

> break the current functionality in order to make it behave as you need.

Again, I invite you to play with the demo and point out precisely where you would argue it is "broken"... from a functional / ux point of view rather than one coming from the angle that says "but the code works differently today".

**Comment by tobibeer** [comment]
> If the target is smaller than the window and the scroll position is too far up, then scroll till the target is at the bottom of the window. This is so that we minimise the scrolling of the page to make small targets visible

Here's how we make small targets visible:

1. we scroll them to the defined scroll position like all other elements
2. if we cannot, because there is no content that follows it, then we cannot, and neither can the browser or any complex computations considering height

> If the target is bigger than the window, then just scroll to the top

Same as first case.

> Otherwise, stay where we are. This is the case where the scroll position is already within the target element

Makes no sense to stay, I asked it to scroll that element (the title) to the default scroll position. Clicking with nothing happening is confusing. If we got something to scroll, even if just a few pixels, then we should scroll and thus focus the target element.

**Comment by tobibeer** [comment]
To "minimize scrolling" is not a meaningful design goal. To scroll to a defined target is.

**Comment by felixhayashi** [comment]
> To scroll a given target to a defined position is. And that's what all the fuzz is about.

Sorry to disturb, I didn't follow all the discussion (I'll catch up once I find the time) but again, isn't this related to: 

Proposal to change the default navigating behaviour of tiddlywiki
https://github.com/Jermolene/TiddlyWiki5/issues/1290

@Jermolene Maybe at some point we could merge the "top" storyview into the core so it exists as alternative for everybody who wants this behavior?

**Comment by tobibeer** [comment]
@felixhayashi, this issue is not quite about the same thing as #1290, at least not from what I read in the OP of that issue.

In fact, your request is not even quite standard browser behavior... because browsers — just like TiddlyWiki — cannot scroll an element further up than there is a page containing content to be scrolled up.

This is rather about the cases where the core currently implements some odd strategy along the lines of "do the least amount of scrolling necessary" ...the reasoning behind which I entirely fail to understand, tbh.

It is **not** about the case where not even the browser could scroll an element further up (for lack of any content that follows that element)... which could only be remedied by having the story be followed by a spacer that is as least as tall as the delta of `viewport-heigh - height of last element`.

**Comment by felixhayashi** [comment]
Thanks @tobibeer for this clarification.

> This is rather about the cases where the core currently implements some odd strategy along the lines of "do the least amount of scrolling necessary" ...the reasoning behind which I entirely fail to understand, tbh.

If this is what the discussion is about (again sorry, I didn't completely follow it), then I agree with you.

> In fact, your request is not even quite standard browser behavior... because browsers — just like TiddlyWiki — cannot scroll an element further up than there is a page containing content to be scrolled up.

True. But I felt it makes sense to add this padding (I think you also do) in the top storyview plugin to create a better experience. By the way, I think tb5 should update to the latest version, there were many bugs that were solved after you started using it on your site(!).

**Comment by tobibeer** [comment]
> But I felt it makes sense to add this padding (I think you also do) in the top storyview plugin to create a better experience. 

I do. Being able to reliably scroll to an element is most important. Which is why I am very much challenging the current behavior / scrolling strategy.

While I don't see a problem with superfluous padding, perhaps highlighting a target after being scrolled to — as you do with your live view — is a better option than artificially lengthening the story.

**Comment by rcrath** [comment]
@tobibeer thanks for the link in:

>By the way, there is a pretty much working solution referenced in #2180. You'll find a working example at the bottom of this tiddler:
http://scroller.tiddlyspot.com/#Linking%20in%20WikiText

But when I copied the code over, it does not appear as a link at all.  Is there a plugin that needs to be installed too?  Sorry for being clueless if that is the case.  Also, having the TOC at the bottom of the page is odd, although seventeenth century books used to put it at the end..  If I understand right the target has to come before the reference to it, which would preclude putting the TOC at the top.

I also looked at the slicer TIddlywiki.  If that becomes a plugin, I could certainly see using that, although updating would be an issue.  I don't make these long pages as canonical texts, but as scratchpads that I add to and transclude from and so forth.  I am guessing I would have to rerun the slicer if I added any new headings?

**Comment by Jermolene** [comment]
I've come round to @tobibeer's suggestion, and propose to change the scrolling behaviour in two ways:

* to always scroll to align the top/left of the target element with the top/left of the viewport
* to dynamically track the target element during the scroll operation (the current code measures the target position at the beginning of the scroll and doesn't adjust it to take into account dynamic changes to the DOM during the scroll)

My primary motivation for the change is to improve scrolling behaviour when dynamic DOM changes are occuring (eg with the Twitter plugin which asynchronously renders tweets).
