### ISSUE TITLE
run callback after tm-navigate

### ISSUE THREAD

**Issue by tobibeer** [Jermolene/TiddlyWiki5#2181]
How to run code / some callback function, not only after **tm-navigate** is done slicing the history tiddler but effectively after **scrollIntoView()** is done scrolling to some target element?

**Comment by Jermolene** [comment]
Hi @tobibeer there's a few places where one could imagine a callback:

* Within the navigator widget, after the story and history lists have been manipulated
* Within the storyview, after a navigation has been processed

Which are you trying to do? Perhaps what you want is a custom storyview?

**Comment by tobibeer** [comment]
I think I am actually way before any navigator or storyview. Right now, I have created an anchorlinks wikirule that handles all of:

* `[#[anchorname]]`
* `[#[anchorname|tiddler name]]`
* `[#[anchorname#pretty title]]`
* `[#[anchorname#pretty title|tiddler name]]`

This simply instantiates a LinkWidget which, on top of all the current things stores a `this.anchor` property. Now, when clicking such a link I want a different **handleClickEvent**:

* **simple case:** scroll to the anchor
* **complex case:** open the tiddler, then scroll to the anchor

The second part is where I am a little at loss.

I found one way to work it by doing:

`setTimeout(scrollToAnchor,$tw.utils.getAnimationDuration() + 100);`

...which waits for the specified animation duration, and then a little more, and then goes about scrolling to the anchor ...with a fixed/simplified [scrollIntoView](https://github.com/Jermolene/TiddlyWiki5/blob/72941f3e9a916948222ff7be540d896e2b1901f6/core/modules/utils/dom/scroller.js#L53-L120) — see #2180 — that actually scrolls to the element I am asking it to scroll to.

**Comment by tobibeer** [comment]
@Jermolene, I have updated the [demo for #2180](http://scroller.tiddlyspot.com/#Linking%20in%20WikiText) in [the latest commit](https://github.com/Jermolene/TiddlyWiki5/compare/master...tobibeer:anchor-support) to demonstrate [linking headings](http://scroller.tiddlyspot.com/#Linking%20in%20WikiText) (very bottom).

**Comment by twMat** [comment]
>... linking headings 

I say Yay! ...but Big J Nay

;-)

**Comment by tobibeer** [comment]
> Big J Nay

@twMat, I know @Jermolene doesn't want TW2-style sections in the core, but links to headings are quite a different ball-game.

**Comment by Jermolene** [comment]
> complex case: open the tiddler, then scroll to the anchor

> The second part is where I am a little at loss.

But that's rather the point of why adding anchor support is difficult! I'm afraid if I had a solution then I would have mentioned it during the previous discussions we've had on this topic.

The core of TW5 is an intricate little machine, with parts folded over onto themselves in surprising ways. If you really want to add robust support for anchors then you're going to need to redesign the core in a much more systematic way, with a more sophisticated model for navigation.

It's an interesting area to explore. There's a good chance you'll be able to hack something together that works in the 80% of cases that meet your own goals. But to go into the core these changes need to be robust.

**Comment by tobibeer** [comment]
> But that's rather the point of why adding anchor support is difficult! I'm afraid if I had a solution then I would have mentioned it during the previous discussions we've had on this topic.

I think the solution of using setTimeout with respect to fetching the animationDuration first is working quite fine.

> It's an interesting area to explore. There's a good chance you'll be able to hack something together that works in the 80% of cases that meet your own goals. But to go into the core these changes need to be robust.

I think the linked demo is just that: quite robust. Feel free to test.

**Comment by Jermolene** [comment]
> I think the solution of using setTimeout with respect to fetching the animationDuration first is working quite fine.

It's a terrible, terrible hack in terms of the design of the core. But if it works as a plugin, that's great.

**Comment by tobibeer** [comment]
> It's a terrible, terrible hack in terms of the design of the core. But if it works as a plugin, that's great.

Where exactly would be the hack in that? I wait for as long as the animation is scheduled and then do the scrolling. Simple.

It works as a plugin that hijacks about 3-4 different core components.

**Comment by tobibeer** [comment]
The link widget can provide basic support for scrolling to an element with a given id / name / even class. There is no hacky magick to that. Simply implement an enhanced "handleClick" and we can scroll wherever we want... using the LinkWidget... while also opening a given target tiddler should it not be open yet.

**Comment by Jermolene** [comment]
> Where exactly would be the hack in that? I wait for as long as the animation is scheduled and then do the scrolling. Simple.

The hack is that you're trying to synchronise two interdependent processes using timers.

> The link widget can provide basic support for scrolling to an element with a given id / name / even class. There is no hacky magick to that. Simply implement an enhanced "handleClick" and we can scroll wherever we want... using the LinkWidget... while also opening a given target tiddler should it not be open yet.

The trouble is that scrolling the page is the concern of the story view attached to the list widget. It's a violation of basic encapsulation and separation of concerns to have an independent subsystem that is also manipulating the scroll position.

**Comment by tobibeer** [comment]
> The trouble is that scrolling the page is the concern of the story view attached to the list widget. It's a violation of basic encapsulation and separation of concerns to have an independent subsystem that is also manipulating the scroll position.

Not sure I understand. How would one possibly initiate scrolling to a place without a user event, e.g. click? If we need a click, it barely matters what widget is triggering it, be it a link or button or other. The link widget seems to be the right one since we may need to open a tiddler first to scroll to anything in it.

We can sure pass another attribute via tm-navigate, e.g. "toAnchor"... but the current architecture makes passing these things all the way to the storyview nearly impossible.

**Comment by Jermolene** [comment]
> Not sure I understand. How would one possibly initiate scrolling to a place without a user event, e.g. click? If we need a click, it barely matters what widget is triggering it, be it a link or button or other. The link widget seems to be the right one since we may need to open a tiddler first to scroll to anything in it.

What if navigation is initiated by the user changing the browser location hash? It would be odd for the link widget to handle that.

>  the current architecture makes passing these things all the way to the storyview nearly impossible

But, as we've already discussed, if you want to implement anchors then you've got to change the current architecture.

> Also, tm-navigate does no "after navigation" handling... it is done by the list widget listening to the history and then handling the change via the story. So, are you saying we also need to attach the anchor to the history?

I'm not sure what you're asking. As I've said near the top, there are multiple places where this hook could be applied.

**Comment by tobibeer** [comment]
> It would be odd for the link widget to handle that.

I don't see anything wrong about the link-widget asking a PageScroller to scroll to a target. That is what all anchor-links do when a user stays on a page. This is virtually independent from the story... so long as we're not doing both at the same time: opening a tiddler and then scrolling to it.

The only thing that prevents decoupling the two is whatever animation is done by some story module. In any case, it will still require a Link(Widget) to construct a link to a given target... no matter what implementation, under the hood, takes care of (optionally) rendering a target tiddler beforehand.

> I'm not sure what you're asking. As I've said near the top, there are multiple places where this hook could be applied.

Eventually, I am saying that this is highly useful functionality, not only for the use-case of navigating to headings. Seeing how you seem to discard a rather well working implementation as hacky, is a bit mind-boggling to me ...and actually leaves me with having to be hacky² about it, hijacking the necessary core components.

Can the proposed implementation be improved? Certainly. Can the architecture be improved? Sure. Do we have to have it all perfect from day 1, all the while discarding highly useful capabilities? I think we should not.

Anyway, I'll turn it into a hacky little plugin then.

**Comment by tobibeer** [comment]
Actually, **navigateSuppressNavigation** should not only suppress navigation but render without animations.

**Comment by Jermolene** [comment]
> I don't see anything wrong about the link-widget asking a PageScroller to scroll to a target

Well, one issue is that one would presumably want to be able to scroll to anchors by navigating to a location hash, as well as clicking on a link.

> The only thing that prevents decoupling the two is whatever animation is done by some story module

I think that's the kind of thing you might need to be familiar with in order to design a robust solution. It's the storyview that's doing the animation.

> Seeing how you seem to discard a rather well working implementation as hacky, is a bit mind-boggling to me

But it's not a well working implementation. It breaks the current behaviour. I've explained endlessly why the current implementation is as it is. Your replacement is not an equivalent.

**Comment by tobibeer** [comment]
> Well, one issue is that one would presumably want to be able to scroll to anchors by navigating to a location hash, as well as clicking on a link.

Sure, but that does not have to be step 1. We can always design ways to amend the permalink / permaview syntax to cater for that... later.

> I think that's the kind of thing you might need to be familiar with in order to design a robust solution. It's the storyview that's doing the animation.

Then, clearly, the architectural pathways from widget to story module need amending so as to pass along anchor targets to be navigated to... allthewhile fixing PageScroller (#2180) to actually arrive at a defined element ...which it currently does not.

> But it's not a well working implementation. It breaks the current behaviour.

It may not adhere to a pattern, but I have yet to see anything "broken".

**Comment by Jermolene** [comment]
> Sure, but that does not have to be step 1. We can always design ways to amend the permalink / permaview syntax to cater for that... later.

If we're going to change the core to implement a new feature then the new feature needs to be mapped out in its entirety before we commit to it. We can't add things speculatively to the core, without being confident that we know how to finish them.

> Then, clearly, the architectural pathways from widget to story module need amending so as to pass along anchor targets to be navigated to... 

Yes, I think an implementation is going to touch quite a lot of areas of the core.

> allthewhile fixing PageScroller (#2180) to actually arrive at a defined element ...which it currently does not.

I don't know why you phrase it like that. It's not supposed to have the functionality that you want. As I've said, scrolling to an anchor is a different use case.

> It may not adhere to a pattern, but I have yet to see anything "broken" about it.

Your replacement implementation has different behaviour than the original. The behaviour of the original is intentional, and by design. Therefore your implementation is broken.

**Comment by tobibeer** [comment]
> We can't add things speculatively to the core, without being confident that we know how to finish them.

Sure, anchor links are all the more useful with permalink support... being able to click a button next to a heading to set the permalink would be quite nice... but there is no "finishing" here. We can always invent more ways to make things more useful.

> As I've said, scrolling to an anchor is a different use case.

To me, it is not... and as explained [in this comment](https://github.com/Jermolene/TiddlyWiki5/issues/2180#issuecomment-169103410) and below, I think the current implementation is optimizing the wrong thing... or rather, not optimizing things at all. It's catering for the "please don't scroll if you don't have to" mindset rather than the "I asked you to scroll somewhere, so please scroll to the thing as you always do, to the one defined spot... not somewhere below or not at all".

**Comment by tobibeer** [comment]
>  The behaviour of the original is intentional, and by design. Therefore your implementation is broken.

Then I am clearly asking to change the intention and the design that goes with it... because, not only do we not gain anything, but in fact, we over-complicate and actually break the generic use-case of "scroll to a defined position".

In terms of browser standards, what this code does is not at all how browsers navigate... well, anchors.

**Comment by Jermolene** [comment]
> Then I am clearly asking to change the intention and the design that goes with it... 

As mentioned over on #2180, you're asking for a change to the default scrolling behaviour of the classic story view, but you're justifying it by wanting the underlying API to function differently in another context.

**Comment by tobibeer** [comment]
>  but you're justifying it by wanting the underlying API to function differently in another context.

Yes, because it is the underlying API that is implementing the problematic behavior that any storyview relies on.

**Comment by Jermolene** [comment]
If any storyview wants different scrolling behaviour then we'd change the scroller, but we'd do it by adding the new functionality, not by breaking the existing functionality.

**Comment by tobibeer** [comment]
I consider the current scrolling implementation non-browser compliant in the sense that it implements a behavior different from what users are generally used to... to scroll a given element to a defined, reliable position up top. That's what's broken for me, usability-wise, as well as in terms of extensibility.

**Comment by Jermolene** [comment]
> I consider the current scrolling implementation non-browser compliant in the sense that it implements a behavior different from what users are generally used to...

Really? Please give me an example of scrolling behaviour on tiddlywiki.com that isn't consistent with ordinary browser behaviour.

> to scroll a given element to a defined, reliable position up top. That's what's broken for me, usability-wise, as well as in terms of extensibility.

You're saying that there is something broken in the usability of scrolling in navigation at the moment?

Or are you saying that there's a usability problem when you try to reuse a scroller designed for sized elements with elements of zero size?

**Comment by tobibeer** [comment]
> Or are you saying that there's a usability problem when you try to reuse a scroller designed for sized elements with elements of zero size?

You have listed the cases from the core module and I have explained why they don't matter one bit. The implementation in the demo works precisely as expected, in addition also for non-tiddler elements, where core scroller simply fails.

If the core cases are of any relevance it should be easy to construct a case where http://scroller.tiddlyspot.com does **not** work as expected. I challenge you to produce such a case and predict that you cannot. At least, I cannot produce such a case. If you can, please let me know how to reproduce any problematic behavior that the core does indeed handle (more gracefully).
