### ISSUE TITLE
how make tiddlylinks in a modal open a tiddler?

### ISSUE THREAD

**Issue by tobibeer** [Jermolene/TiddlyWiki5#2188]
...and perhaps also close the modal?

**Comment by Jermolene** [comment]
Wrap the content of the modal in a navigator widget targeting the right story list and history list.

**Comment by Jermolene** [comment]
If you want the modal to close on clicking a link then it sounds like dropdown semantics would be more appropriate.

**Comment by tobibeer** [comment]
> Wrap the content of the modal in a navigator widget targeting the right story list and history list.

Will play with that... never did anything with the navigator widget yet.

> If you want the modal to close on clicking a link then it sounds like dropdown semantics would be more appropriate.

I was thinking that too. On the other hand, I like how modals have a different ui which I'd like to be able to use.
