### ISSUE TITLE
tw2parser edition demo is broken

### ISSUE THREAD

**Issue by Jermolene** [Jermolene/TiddlyWiki5#2189]
Opening the tw2parser demo page causes a JavaScript crash:

http://tiddlywiki.com/prerelease/plugins/tiddlywiki/tw2parser/index.html

@buggyj could you have a look at this? It appears that the plugin has fallen foul of some refactoring of the wiki.js module

**Comment by buggyj** [comment]
@Jermolene Ok I'll take a look.

**Comment by pmario** [comment]
title typo?

**Comment by Jermolene** [comment]
Thanks @pmario

**Comment by Jermolene** [comment]
Thanks @buggyj

**Comment by buggyj** [comment]
@Jermolene fixed - I'll generate a pull request

**Comment by buggyj** [comment]
@Jermolene needs to be closed

**Comment by Jermolene** [comment]
Thanks @buggyj
