### ISSUE TITLE
Rename TiddlyWiki5 distribution to TiddlySpace as `$:/tw5`

### ISSUE THREAD

**Issue by Jermolene** [Jermolene/TiddlyWiki5#219]
To make it a little bit harder for people to accidentally tamper with it.

**Comment by pmario** [comment]
TiddlySpace is gone sou this one can be closed. @Jermolene

**Comment by pmario** [comment]
bump TS is gone!

**Comment by pmario** [comment]
@Jermolene .. Please close this one. TiddlySpace is long gone

**Comment by Jermolene** [comment]
Thanks @pmario
