### ISSUE TITLE
core hash filter to url encode / decode titles

### ISSUE THREAD

**Issue by tobibeer** [Jermolene/TiddlyWiki5#2194]
Please consider the [hash](http://tobibeer.github.io/tw5-plugins/#hash) filter for the core, as it is rather essential to construct proper links to other wikis. Could also be done using a macro, but then we may want to do simple bulkops in lists.

> * **hash[]**
>    * a filter to URI-encode tiddler titles to permalink or permaview hashes or decode hashes back to titles
> * **encodes** an input title or operand to a permalink hash
>     * encodes more than one input title to a permaview hash
> * **decodes** permalink or permaview hashes or fully qualified urls
>     * returning tiddler titles

**Comment by tobibeer** [comment]
For example, I was going to create a multitids tiddler `$:/language/Docs/ParserRules/` containing references to the core documentation for each parser to be displayed under:

**ControlPanel > Advanced > Parsing**

However, those titles contain spaces, so I don't quite see a way to link to the corresponding documentation tiddler on TiddlyWiki.com, based on those titles without something like the **hash** filter.

On the other hand, we may actually want simple tiddler titles on TiddlyWiki.com for each parser rule which contains the information, then transcluded in a more prosaic **Block Quotes in WikiText**.

Another usecase would be creating a proper link under info / sources at tiddlywiki.com, see **$:/editions/tw5.com/TiddlerInfo/Sources** ...rather than using the view-widget for a purpose it is not qualified to cater for.

**Comment by tobibeer** [comment]
Turns out I just learned something new which — for some reason — I didn't know worked that way... beforehand. While this does away with some of the need of a hash filter, it sure helps creating proper links...

```
[ext[http:/some.tiddlywiki.com#A Title With Spaces]]
```

...I thought those url encoded brackets were needed.

I guess I confused the problem of double encoded links to static pages with creating links for plain tiddlers. Anyway, being able to construct a proper permalink from a set of titles sure has value... as has decoding.

**Comment by twMat** [comment]
I am not read up on this so FWIW;

AFAICT the ideal would be a built-in URI coder/decoder so the user would never have to bother with this. I.e whenever a url is added, it is parsed(?) automatically into the appropriate format and is an encoded string e.g fetched from somewhere (such as the browser address field) and displayed, it is parsed to display unencoded.

Non-sense?

**Comment by tobibeer** [comment]
@twMat, I don't see how core code could go about guessing: users need to be specific about the type of url they are feeding to whatever module is doing anything smart about those.

**Comment by twMat** [comment]
I figured that the "users need" is not really his own need but to satisfy some external thing that requires the particular URL form. 

Whenever something does require a specific url form... how is this found out currently? That same "method" to find out, could perhaps be used by the core. 

Alternatively, might one perhaps always use uri encoded URL's? for external communication? Whenever a user enters a normal URL in TW, it is always converted to URI but displayed to user as what he wrote.

The idea was to releve the user of bothering with the matter. But maybe it's not doable, I have no idea.

**Comment by tobibeer** [comment]
> So, whenever something does require a specific url form... how is this found out currently?

It's not something, as in "some code", that requres a specific url form... it is that I, the user, and mildly knowledgeable about html know that I need this url (double)-encoded or even decoded to get from A to B and back.

There is not a "method" here... there are use-cases... and use cases are catered for by core components... sometimes widgets, sometimes filters, sometimes macros, sometimes parser rules... etc.

> The idea was to releve the user of bothering with the matter. But maybe it's not doable, I have no idea.

Unfortunatley, I think there's no way around this other than actually document when and why there is (double-)encoding... and consequently, once we do those, we want — in other situations — do the reverse.

**Comment by twMat** [comment]
But why/forwhat does a use need this url encoded/decoded?
...i.e is it for something internal in TW - in which case my point is that whatever requires a "less-than-the-simplest-url-format" should instead have a "pre-mechanism" that mangles it into this format. 

...or is it to communicate with something external... in which case it is *still* via the TW and in which case I figure there could still be a middle-step that does the conversion. This assumes there is a way for the system to "know" which format is needed, but I'm guessing this is identifiable.

**An example** in the *existing* mechanisms dealing with uri encoding that I have the same objections on, which might clarify what I mean:

To me it seems weird that we, according to e.g tiddler [datauri Macro](http://tiddlywiki.com/#datauri%20Macro, must manually specify; 

`background: url(<<datauri "Motovun Jack.jpg">>);`

Can TW not instead automatically convert any image that is enclosed in `url( ... )` inside a stylesheet? I mean - "Motovun Jack.jpg" is not really an image, it's a *tiddler* encapsulating an image so we've already adapted it for TW. A user should thereafter not be forced to *further* adapt it, this is what the environment system should do, IMO.

I'm not "against" your OP per se - it just seems to me that we're on the wrong path in having the user deal with this to begin with when I believe the "system" could be made to do it.

It may well be that my reasoning is based on misunderstandings from my side.

**Comment by tobibeer** [comment]
> why/ for what does ... need ... url encoded/decoded?

That's simply how urls work, servers or clients environments simply are not built or and compatible with "any characters you can throw at them", see [http://stackoverflow.com/questions/1856785/characters-allowed-in-a-url](Characters allowed in a URL). And so if we wish to pass pass along complex requests / "messages" / configurations, even if "just a tiddler title", it needs encoding.

> is it to communicate with something external

Both. TiddlyWiki also handles this when extracting titles or other url'ified parameters from the url hash.

> `background: url(<<datauri "Motovun Jack.jpg">>);`
> Can TW not instead automatically convert any image that is enclosed in url( ... ) inside a stylesheet?

Take a good look at what this macro does, @twMat. It base64 encodes the image to be read directly via the link, rather than fetched from the server. That is not even the kind of encoding I am proposing in this PR!

So, you see, there are actually different encoding / decoding needs when it comes to urls, not just "tiddler titles" or "filters" ...even entire binary data, such as images.

It's very simple: the characters alloed in urls are restricted. Therefore, to pass along complex data using a url, you need encoding at one end and decoding at the other.

As for the dataurl macro, there is no possible guessing that you do want some tiddler to be turned into a base64 encoded version. Your macro could literally be doing anything to whatever that tiddler contains to create a valid url from it... e.g. pointing to some external server. There is no means of guessing.

> I'm not "against" your OP per se - it just seems to me that we're on the wrong path in having the user deal with this to begin with when I believe the "system" could be made to do it.

There is no right or wrong pass here. It's simply what is required for passing along parameters via urls... and if and when and how those parameters need encoding a user absolutely **must** decide, according to their use-case.

In your example, it was about turning an image into base64 encoded data. In my case it was about turning a bunch of titles into what the core depends and relies on in how it deciphers where you want to go in the wiki.

**Comment by twMat** [comment]
@tobibeer - I severely updated my post above because it poorly communicated what I meant. Please reveiw.

**Comment by tobibeer** [comment]
@twMat, there is no internal vs. external URL, there only is one URL that caters both for external participants as a reference as well as internal as a pointer to whichever target the url represents.

I never quite fully looked at why static urls need **double** encoding... but it appears they do. And right now, without the above proposed solution there is literally no way to construct a link to a static tiddler file from a given title... unless you do javascript.

**Comment by tobibeer** [comment]
> `background: url({{Motovun Jack.jpg}});`
> ...because the user has specified that it is an image and it is implicit that he want's the system to re-interpret the url into the needed format when this image is to be used for background url

That would require not only special parsing (a new wikirule) for this kind of in-css retrieval, it would also possibly break what Jeremy at times refers to at "layering". The wikitext parser is mostly agnostic about its context, except perhaps for a tiddler's types and then wikitext rules like pragmas that define how things are parsed.

Knowing that StyleSheets, however do not require, in fact, at times must not be of the type `text\css` you've got the dilemma where there literally is hardly room for your parsing rule to kick-in.

It would also be quite specific, that is constrained in terms of use cases... in other words with little general gain, at least as far as I can see. How often does a user need to do this kind of encoding and when you do, how much of a hassle is to know and be aware of how you turn an image into the base64 representation?

**Comment by twMat** [comment]
Ok, I'm resting my case because I suspect my skepticism is based on faulty premises and I'm not well read on the matter.

**Comment by tobibeer** [comment]
It was decided to use more native sounding filters:

https://github.com/Jermolene/TiddlyWiki5/commit/b4b77d1681023d4ccc0e157df1ce67d0d388cd5a

**Comment by Jermolene** [comment]
The problem here was that `hash` is not the best name for the filter. I understand you chose it because it is associated with encoding the content of the hash portion of a URL, but to many people, hash as an operation implies a hashing function. There is already a readily understood name for the operation, so I went with it.
