### ISSUE TITLE
Typing $:/ in tag field - show ALL system tags

### ISSUE THREAD

**Issue by twMat** [Jermolene/TiddlyWiki5#2200]
When setting up a system tiddler you must annoyingly often recall the exact name for the needed tag - _"It must be $:/tag_s_/ not -tag", "It must be ../Stylesheet with only one capital S"_, not to mention the impossibility of remembering longer path names. And you don't get any clue in the tag dropdown unless you've used it previously.

I propose that if the user begins to type in `$:/` or perhaps `$:/tag` (ok, `$:/tags`) then the [system tags](http://tiddlywiki.com/#SystemTags) are seen in the drop down, i.e even if they have not been applied by the user previously, and the usual refinement is done as more letters are typed in.

**Comment by felixhayashi** [comment]
:+1:

**Comment by Spangenhelm** [comment]
Yeah @twMat i can't agree more !

The way it is now is not practical if, for example but not only in this case, you want to share a tw with someone who knows/care nothing about it, the fact that some weird tags may show up from nowhere can be disturbing when you don't expect them and you don't know what they are used for.
This kind of thing is part of the admin/tech side so it should be hidden to the regular user.
It reminds me the issue i had opened at my first days with tw:(https://github.com/Jermolene/TiddlyWiki5/issues/456)

**Comment by tobibeer** [comment]
I very much agree with @Spangenhelm that while given system tags starting to type `$`, they should not appear at all if we don't do that... since they have a design purpose and not so much a usage purpose.

**Comment by twMat** [comment]
@Spangenhelm and @tobibeer 

Ok, so maybe then remove the system tags from the normal dropdown suggestions and only show them when typing $...

In that case, I add to the OP the suggestion that previously used system tags should appear at top of dropdown list above the rest (unused) system tags (...when one begins to type $...)

**Comment by felixhayashi** [comment]
Maybe make it even safer: only when `$:/` is typed ;)

**Comment by pmario** [comment]
@twMat ... I think this is standard behaviour now?!

**Comment by twMat** [comment]
@pmario 
at least it is much improved.
thanks
