### ISSUE TITLE
Add preMessage parameter to listwidget

### ISSUE THREAD

**Issue by twMat** [Jermolene/TiddlyWiki5#2202]
Use case

```
1) list filter all categories and display the category name as a "headline"
2) (sub-) list filter, per category, all its items
```

Currently, if some categories do not have items then you get headlines with _nothing_ under them. There is the _emptyMessage_ parameter giving you the possibility to write out e.g "no items" - but often neither a headline to nothing nor a headline to an emptyMessage is desirable.

I propose to introduce a _preMessage_ paramter that only shows when the filter results in >0 items. This _preMessage_ can, for instance, show the transcluded category name or anything else.

Possibly also a _postMessage_ parameter, but I'd say the need for _pre-_ is much greater.

Note: TWC "forEachTiddler" featured this.

**Comment by tobibeer** [comment]
Good idea. Rather important. :+1:

I think it should be both *preMessage* **and** *postMessage*,e.g.:

```
<$list filter="[tag[Foo]]" pre="<dl>" post="</dl>">
<dt><$link><$view field="title"/></$link></dt>
<dd><$macrocall $name="def" term={{!!title}}/></dd>
</$list>
```

**Comment by twMat** [comment]
Additional use case; html tags such as `<table>` and `</table>` as pre- and post-.

**Comment by twMat** [comment]
For info: OP still holds, but meanwhile a **workaround** is posed by @ericshulman [here](https://groups.google.com/d/msg/tiddlywiki/Bwjyzg0X6VA/HF-ca_ZgEgAJ)

**Comment by tobibeer** [comment]
@twMat, I think your workaround is a different thing ...more of a **"withItemsPreMessage"**.

**Comment by Jermolene** [comment]
I'm not keen on this proposal as it further complicates some logic that's already fairly complicated. A better solution is to be seeking ways to filter out the empty categories from the outer list.

**Comment by twMat** [comment]
@Jermolene - thanks for replying. 

Ok. I think the conclusion is that there will not be a change in this. Should I therefore close the thread? The underlying problem is still there to some extent but clearly the specific proposal is dismissed.

Again, thanks for input everyone!

**Comment by pmario** [comment]
@twMat ... With a workaround in place, is it necessary to keep it open?

**Comment by pmario** [comment]
ok. Now I start to understand, what you want. ... but I think, that's a macro or a transcluded template, that is needed here. ... 

If the pre- and post- messages are added to the list-widget, they would be limited, to the 1 use-case you described. ... I need to think about it.

**Comment by pmario** [comment]
The underlying mechanism is similar to the "Recent" tab, that uses the `<<timeline>>` macro

**Comment by pmario** [comment]
> ... In fact, I was reminded of it just the other day! 

That's interesting. Can you post a "rendered" example list. No widget code. .. Just, how the finished list should look like. ... and some info, how the tiddlers involved should look like. eg: tag, fields, .. that are needed for the rendered list. 

You can use a markdown code-block eg:

```
 - level 1
   - level 1.1
 - level 2
```

2nd usecase is: 
 
 - Tobias used the example with html-tags as pre- and post- elements. 
 - You added the `<table>` example, which is the same thing.

**Comment by pmario** [comment]
>Does this make sense?

yes

**Comment by pmario** [comment]
I wanted to point out, that extending the list widget in a generic way. .. That means covering every possible usecase will be a nightmare. ... eg: 

a) pre- and post- elements need a parameter, to specify, if they are used. ... which gives us 4 states for those 2 elements: 1 .. not used, 2 .. pre active, 3 ... post active and 4 ... both active

b) There is the empty message. Which gives us 2 possibilities. 1 ... if list is empty show empty message. 2 ... if list is empty -> show nothing. 

c) now we need to tell a) the state of b) .. as requested in the OP. ... What to do if list is empty / full AND how to use pre- and post- ... This makes 8 possibilities instead of 4 for a)

d) to cover every possible combination we will have 16 states. .. a) and b) can work alone or a) and b) neet to work together. .... 

As I wrote it's a nightmare. ... The only way I see is using a macro tiddler, where the user has full control and can define the needed possibilities, depending on the use-case.

**Comment by pmario** [comment]
Anyway ... The prefered way to implement extension like this one is, to create a plugin first and once we did several iteratioins and found out, how we can conveninetly use it, it may land in the core. 

I did a similar thing with the uni-link plugin. Which works well already, but it's not finished to be part of the core ... yet.

**Comment by Jermolene** [comment]
I'd stand by my [earlier comment](https://github.com/Jermolene/TiddlyWiki5/issues/2202#issuecomment-217730190) that this proposal adds significant further complexity to the list widget. I'm sympathetic to the OP but I think there are other ways to address it.

**Comment by twMat** [comment]
I'm probably just naïve but:

Might it be possible to "simply" treat the preMessage/postMessage as **first/last items** in the list output, and add separate styling for them? i.e they kind of have ubiquitous placeholders there but they are not always used. (Or was that idea obvious and exactly what would be so complicated?)

Example, including output

```
<$list filter="one two three" preMessage=zero>

</$list>

zero
one
two
three
```

The above didn't use the postMessage and the styling for the preMessage (i.e `zero`) is undefined, defaulting to the same style as the actual list items.
