### ISSUE TITLE
have all widgets refresh when their currentTiddler changes

### ISSUE THREAD

**Issue by tobibeer** [Jermolene/TiddlyWiki5#2206]
As hinted at [here](https://github.com/Jermolene/TiddlyWiki5/pull/1379#issuecomment-159921511), I think that...

> a macrocall widget (or any widget, really) should always refresh if its **currentTiddler** is in **changedTiddlers**, not just if there are any **changedAttributes** to it.

**Comment by pmario** [comment]
@tobibeer ... Is the related "here-link" still a problem with latest TW? .. Do we still need this issue?

**Comment by Jermolene** [comment]
Thanks @pmario @tobibeer I'm closing this because there's no rationale for it.
