### ISSUE TITLE
Harmonize checkbox behaviour for tags and fields

### ISSUE THREAD

**Issue by twMat** [Jermolene/TiddlyWiki5#2211]
Edit: See modified proposition two posts down

---

I checked around regarding checkbox issues but can't find this one - which seems weird as it IMO borders on a bug or at least very unintuitive:

Insert the following in a tiddler and save:

```
<$checkbox tag="checked" 
checked="checked" unchecked="unchecked" default="unchecked">
</$checkbox>

<$checkbox field="status" 
checked="checked" unchecked="unchecked" default="unchecked">
status: {{!!status}}</$checkbox>
```

(yeah, I could have named the field "check" instead of "status" but enough is enough)

Anyway, check around a few times.

IMO the field version works correctly, - effectively a toggle between the two values 
but the tag version seems to disregard the unchecked parameter.

Am I missing something?

---

Edit: See modified proposition two posts down.

**Comment by tobibeer** [comment]
@twMat, please carefully read the documentation again:

http://tiddlywiki.com/#CheckboxWidget

**Comment by twMat** [comment]
Hm... @tobibeer is right. The documentation does, hm, state it... but I can't say it explains it. It definitely opens up for misunderstandings when all attributes are presented in one list like that.

Regardless, the behaviour would still be more harmonious if the two displayed a more similar behaviour. SO...

**Modified OP: **Introduce the unchecked paramter for tags**. 

IFF this parameter is explicitly included, tags behaves like the fields in this respect (i.e like a toggle) and if left out, i.e no mention of unchecked paramter, then the behaviour is as current.

This should not be backwards incompatibl because the change is to *introduce* the use of the *unchecked* parameter for the *tag* type.

**Comment by tobibeer** [comment]
@twMat, I'm afraid your proposal does not make much sense to me.

Your example in the OP should **neither** specify a **checked** nor an **unchecked** attribute when using the **tag** attribute. If you want a tag-toggle, use the **tag** and **invertTag** attributes.

We've recently had about a "mode" attribute... but ultimately... the checkbox widget works how it works now. So the most improvements we can get is by improving the docs. So, yes, the documentation would do good with concise examples for all cases. No prose, but clear examples.

Also, the attributes that actually make up a "mode" should be grouped in the attributes table under heading rows, e.g. "tag-mode" and "field mode".

**Comment by matabele** [comment]
@twMat 
Have a look at my new Checklist widget [here] (http://checkbox-list.tiddlyspot.com/). The behaviour is as you suggested when the `alt=` attribute is specified.

The consensus appears to be to introduce this new widget for the handling of lists (including the 'tags' list) -- but leave the legacy Checkbox widget as is (to maintain backward compatibility.)

**Comment by matabele** [comment]
@twMat 
There's a PR for the Checklist widget here: https://github.com/Jermolene/TiddlyWiki5/pull/2156 -- final version still under discussion -- any suggestions welcome.

**Comment by pmario** [comment]
@twMat ... Is this a problem, or was it a problem interpreting the docs?

**Comment by twMat** [comment]
solved
thanx
