### ISSUE TITLE
do not focus edit fields when wiki embedded in an iframe

### ISSUE THREAD

**Issue by tobibeer** [Jermolene/TiddlyWiki5#2220]
I don't know if this is even possible, but if a wiki is embedded in an iframe, none of its EditExtWidgets should ever be given auto-focus.

**Comment by pmario** [comment]
>EditExtWidgets 

There are no EditExtWidgets?? @tobibeer IMO this issue in not actionable at all. pls close.

**Comment by Jermolene** [comment]
Thanks @pmario.
