### ISSUE TITLE
In tooltips, write out also the object name

### ISSUE THREAD

**Issue by twMat** [Jermolene/TiddlyWiki5#2225]
It is confusing to not know what various elements are *called* in the UI. It is it *Info button tool* or *InfoTool* or is it *TiddlerInfo* or...? (And these are my *qualified* guesses - a newcomer would be much more clueless! It is not even obvious what a the *toolbar* refers to.)

**Proposal** - Complete (all) existing tooltips with a sufffixing `[objectname]`

Thus, hovering over the tiddler *Info* button would say `Show information for this tiddler [Info button]`. The objectname could be in faint gray.

Ideally the objectname is as similar as possible to the (unique part of) the tiddler/macro/... used for defining the particular object.

This should be directly helpful but it should also help "foster" the correct use of the nomenclature.

**Comment by tobibeer** [comment]
> Proposal - Complete (all) existing tooltips with a prefixing <objectname>:

I'd agree that's helping communication a lot. Not exactly sure if "all existing tooltips" is an actionable scope. I'd start with a PR changing the relevant spots for this one and in the context of that exercise (maybe) find other context where this nomenclature would be helpful.

**Comment by twMat** [comment]
It there a way to list all tooltips?

**Comment by tobibeer** [comment]
You can search for `tooltip="` and `tooltip:"` in shadows.

**Comment by twMat** [comment]
(Minor update to OP to put the objectname as *suffix* instead.)

>You can search

Seems it is mostly `tooltip={` )

I'm thinking one can use the fact that a button also has a text version (as set in [$:/core/ui/ControlPanel/Settings/ToolbarButtons](http://tiddlywiki.com/empty#%24%3A%2Fcore%2Fui%2FControlPanel%2FSettings%2FToolbarButtons) ) and transclude this either;

* into the tooltip - but in a first try it seems the presented tooltip doesn't evaluate the any included translcusion and instead writes out<br>
** e.g `Close this tiddler {{$:/language/Buttons/Close/Caption}}`.
* or as a CSS `:after` pseudo element to the class (?) that the tooltip uses<br>
** e.g `.tooltip-class:after {content:"the objectname";}`

Annoyingly, I fail to find any tooltip class. I figure it must be styled somewhere, no? `tooltip` is a parameter to the buttonwidget... but where do I actually find the implementation of the buttonwidget? I realize this is js terriitory so I probably will not get far even if I find it but I'm thinking maybe there's tooltip style set there.

**Comment by tobibeer** [comment]
> Thus, hovering over the tiddler Edit button would say Edit this tiddler [Edit button]. The objectname could be in faint gray.

I'd think that is total overkill. Let's not exaggerate here. An edit button is an edit button. As for some TiddlerInfo Panel... now that may be a term worth knowing.

**Comment by twMat** [comment]
Ah, sorry, this was more an experimental attempt at a general approach. I agree wiht the specific case of the edit button and some others. The benefit was that there are already a defined captions. I'm not even sure that what is stated in the caption is the right text for the OP.

**Comment by tobibeer** [comment]
I think we might instead want to have a "layout documentation" tiddler on TiddlyWiki.com that shows layout wireframes or screenshots and explains the different elements... giving them names.

**Comment by twMat** [comment]
Yea... something like that. The problem with some docs, or I should say; with some *topics*, is "perceived immediacy" - the guidance is not there when you need it *but* it's too much hassle to go surf for it so you try something... and fail... but you thnk it is *still* more hassle to go surf than to try again... and fail... but you think it is still... etc.

I'm thinking maybe a docs type *plugin* would be better for this (actually maybe even all TW docs should be a plugin) to give guidance in various forms. For the issue at hand maybe it could be a matter of hoveringn over elements to get a popup with info... perhaps even using a certain [preview plugin](http://tobibeer.github.io/tw5-plugins/#preview) :-)

**Comment by tobibeer** [comment]
While it's true that "go look" is a barrier to take... it becomes all the more difficult if you can't even tell someone "look there"... because there is no "there" to point to.

> actually maybe even all TW docs should be a plugin

I very much agree, incuding the node.js docs that made it into the core empty.html... possibly for lack of a better place.

To me, everything should be a plugin. One major beast that belongs into that category (to me) is even the entire ControlPanel and all the lingo that goes into it. That would certainly shrink TiddlyWiki by a very considerable amount.

**Comment by twMat** [comment]
I'm closing this thread for now to let the matter mature.

>To me, everything should be a plugin. One major beast that belongs into that category (to me) is even the entire ControlPanel and all the lingo that goes into it. That would certainly shrink TiddlyWiki by a very considerable amount.

ControlPanel as a plugin - what an interesting thought! So should there be a much slimmed down version in standard distro? One that users would overwrite with another controlpanel plugin?

I think it is a very good idea - for one thing I think we'd see a variety of customized ctrlpanel plugins considering that it is a tiddler we all must, i.e this means there are probably many opinions on how it could be improved.

Have you posted an issue on this idea? Maybe the most pervasive (I hope I'm using that word right) way to convince @Jermolene of it would be to actually present two plugins; the minimal one and another one being a replica of the current but in plugin form. No small task though, hehe.

**Comment by tobibeer** [comment]
@twMat, I have not thought about a minimal controlpanel… the most important settings are shadows that I can adjust… or drop-in a controlpanel for setting things up

also, consider this: in nodejs you could have an editing / setup edition that serves a controlpanel… and then there' sugar wiki you present your visitors… with no such thing.
