### ISSUE TITLE
Missing docs on fields; list-before / -after

### ISSUE THREAD

**Issue by twMat** [Jermolene/TiddlyWiki5#2232]
I just noted there is no documentation on the somewhat frequently referred to fields "list-before" and "list-after".

Is there a reason for this or should perhaps tiddler [TiddlerFields](http://tiddlywiki.com/#TiddlerFields) or tiddler [ListField](http://tiddlywiki.com/#ListField) be updated?

**Comment by tobibeer** [comment]
see: [Order of Tagged Tiddlers](http://tiddlywiki.com/#Order%20of%20Tagged%20Tiddlers)

**Comment by pmario** [comment]
Those fields are [mentioned now at several places](https://tiddlywiki.com/#tag%20Operator:%5B%5Btag%20Operator%5D%5D%20%5B%5BOrder%20of%20Tagged%20Tiddlers%5D%5D%20%5B%5BIntroduction%20to%20Lists%5D%5D%20%5B%5BHow%20to%20add%20a%20new%20tab%20to%20the%20sidebar%5D%5D%20ListField%20TiddlerFields)

**Comment by twMat** [comment]
thanx
