### ISSUE TITLE
Selected field name should trigger field value proposal list

### ISSUE THREAD

**Issue by twMat** [Jermolene/TiddlyWiki5#2233]
**Use case**: Wanting a new viewtemplate field to show up before the *text field*. I type in `list-before`... but then what? I'm forced to go and search for what the real name for the *text field* is.

Same thing with user created field - *"either memorize, or go search"*. Not very user friendly.

**Proposal**: Like with field names, I propose a dropdown select. For the core fields that are "likely" to be used by regular users, pre-populate with standard values - e.g in the case of list-before / -after, prepopulare with the other template fields.

**Comment by tobibeer** [comment]
Please, keep in mind that the sort of thing  you are trying to do here is most likely a one-time setup type of thing. It's not what you do every day. While I understand your point, I'd rather not have a ui for each and every piece to the dev-/setup-puzzle.

At that stage, you're going to have to know that you possibly need to look for this stuff under the shadows tab searching for `viewtemplate/` ...to figure out what it's called, so long as you did not remember it's `$:/core/ui/ViewTemplate/text` in your case.

> Same thing with user created field - "either memorize, or go search". Not very user friendly.

That is true, but the type of thing you're doing is no longer **user** stuff. It is development stuff. Of course, you're still going to be a user... but the type of modification you're doing is actually, well, development of some sort.

As for your dropdown, where would you possibly want to see it? How would the core know what `list-before` you're referring to. Perhaps any tiddlers having the same tags?

Also, again, this calls for field-configuration where TiddlyWiki could be told to treat the `list-before` or `list-after` fields in a given manner. What I mean is: I sure hope things like these do not end up hard-coded into the ui.

**Comment by twMat** [comment]
You're right, it's too edge casey.
Thanks!
Closing thread.
