### ISSUE TITLE
Upgrading wiki with modified shadow tiddler causes the "embarrassing" message 

### ISSUE THREAD

**Issue by braykov** [Jermolene/TiddlyWiki5#2234]
I have the highlight plugin added to a wiki version 5.1.9.
I have modified this shadow tiddler `$:/plugins/tiddlywiki/highlight/highlightblock.js` so that the tab character is 4 spaces instead of 3.
When I upgrade this wiki to version 5.1.10 there is no error message. But later when I open the upgraded wiki, I get the red "embarrassing" error message.

**Comment by tobibeer** [comment]
Hi @braykov, you're going to need to post your modifications to `$:/plugins/tiddlywiki/highlight/highlightblock.js` for anyone to look into this.

**Comment by braykov** [comment]
It is very simple. I am changing this line only. I remove one space. Originally there are four in the string:
```
hljs.configure({tabReplace: "   "});	
```

**Comment by tobibeer** [comment]
hi @braykov, of if it's that simple, did you try to change the same line in the new version, rather than use your overwritten one? Perhaps there were changes to `$:/plugins/tiddlywiki/highlight/highlightblock.js`.

**Comment by braykov** [comment]
Hi, yes, eventually I had to delete my changed shadow tiddler, then upgrade, then make the change again. But I don't think I understand your question.

**Comment by tobibeer** [comment]
That was the question. ;-)

It appears that the actual code of that module has changed significantly so as to break when you tried to use your old version.

If that fixes it for you, perhaps add some **addendum** to your OP and close.

**Comment by braykov** [comment]
OK, it appears this is a normal behavior. I always make backups before upgrading, so next time this happens, these are the actions.

**Comment by felixhayashi** [comment]
**offtopic**: Branimir is that your dog in the picture? It always makes me smile when I see it :) :+1:

**Comment by braykov** [comment]
:-) Oh, no. But it is my dog on the google profile.

**Comment by felixhayashi** [comment]
> :-) Oh, no.But it is my dog on the google profile.

Oh, I thought they were the same animal :) Anyway, nice picture! ;)
