### ISSUE TITLE
creator and created must not be set when modified

### ISSUE THREAD

**Issue by tobibeer** [Jermolene/TiddlyWiki5#2246]
If an existing tiddler that does not have a **creator** or **created** field is modified, neither of these fields must be set. They must only be set when a new tiddler is created.

**Comment by pmario** [comment]
I think `creator` for an existing tiddler should not be touched anymore. 
but
I think `modified` should be touched client side. It can be avoided since 5.1.14 with "timestamps" sidebar button. 

So imo issue can be closed

**Comment by Jermolene** [comment]
Thanks @pmario. I'm closing this because there is no agreed, actionable proposal.
