### ISSUE TITLE
How to secure edit mode with a login on a server

### ISSUE THREAD

**Issue by nytche** [Jermolene/TiddlyWiki5#2249]
Hello,
I managed to install and run tiddlywiki with nodejs on my personal server. but I don't understand how to protect edit mode with a login, like any other website. For me, there are only two modes, all or nothing:
- I set up the server with a login/password, then the server is only available for this user, and not readable for other persons.
- I don't set up a login/password when I run tiddlywiki, and everybody can edit the wiki.
  Am I right? did I missed some configuration? I don't know where to find the corresponding information, thx for any help.

**Comment by felixhayashi** [comment]
Hi,

correct, this is not possible out of the box at the moment. The "all or nothing" is due to TiddlyWiki being primarily a personal note-taking software, which does not require fine grained access control. Definitely something needed as more and more people start to use it as a blog or CMS.

**Comment by pmario** [comment]
@Jermolene -- IMO can be closed. We do have a basic form of [Web Server Authorization](http://localhost:8080/#WebServer%20Authorization:%5B%5BWebServer%20Authorization%5D%5D%20ServerCommand) which supports "Read-only Mode"

**Comment by Jermolene** [comment]
Thank you @pmario
