### ISSUE TITLE
Put Request Handler in Server.js in it's own function

### ISSUE THREAD

**Issue by Arlen22** [Jermolene/TiddlyWiki5#2252]
In order to easily load TiddlyWiki as an Express.js module, it would be helpful to separate the request handler (currently in prototype.listen) into its own function. 

It seems that wrapping it in a function that sets the self variable and then returns the handler function should work fine.

Then, when to call it, you would call `server.getRequestHandler()`, which would return the request handler which can be mounted in ExpressJS.

This is in `commands/server.js`

**Comment by sukima** [comment]
@Arien22 This description is bit difficult to follow. Would you mind showing some code or better yet offer a pull request since you have already researched this.

**Comment by Arlen22** [comment]
Resolved in #2627
