### ISSUE TITLE
Titles containing URL get interpreted as external links

### ISSUE THREAD

**Issue by twMat** [Jermolene/TiddlyWiki5#2255]
( @inmysocks - fyi )

`[[Best TW - http://www.tiddlywiki.com]]`

this is interpreted as an external link. I propose that if the http is prefixed with something and it all is encapsulated in `[[...]]` then this is interpreted as local tiddler title.

The problem arose in experiments with TWederation and I think titles that use URL's might become more frequent the more we federate.

**Comment by Jermolene** [comment]
Hi @twMat thanks, that's definitely a bug; the regexp for matching external links should be anchored to the start and end of the link string.

**Comment by r1chard5mith** [comment]
Should I have somehow submitted my pull request under this ticket number? I couldn't see a way to do that so it's made a new ticket, sorry if that was the wrong thing to do.

**Comment by tobibeer** [comment]
@Jermolene: this appears fixed?

**Comment by twMat** [comment]
Yes, appears fixed.
