### ISSUE TITLE
Plugin Library broken in 5.1.10

### ISSUE THREAD

**Issue by Jermolene** [Jermolene/TiddlyWiki5#2260]
To verify, visit http://tiddlywiki.com, and navigate to the control panel, click the "Plugins" tab and click the "Get more plugins" button. The listed URL for the plugin library points to the 5.1.9 plugin library.

This is a serious problem, and means that I need to release 5.1.11 in the next few hours with this fixed. I shall publish a prerelease shortly.

**Comment by felixhayashi** [comment]
@Jermolene Are there any plugins contained in the library that actually depend on 5.1.10?

**Comment by matabele** [comment]
@Jermolene 

Any chance of merging these?

1. https://github.com/Jermolene/TiddlyWiki5/pull/2251 adds a couple of operators to the x-listops filters

2. https://github.com/Jermolene/TiddlyWiki5/pull/2227 is a small filename change which has been giving some of us git problems for six months
- Until (2) is fixed, all of my PR have to include fix (2)
- (1) includes (2)  -- if you merge (1) you don't need (2) separately

**Comment by felixhayashi** [comment]
> Any chance of merging these?

@matabele nice try :D :+1:

**Comment by felixhayashi** [comment]
![2016-01-29 19 32 09](https://cloud.githubusercontent.com/assets/4307137/12684411/182034c6-c6bf-11e5-81fe-d673410336f4.png)

**Comment by matabele** [comment]
@felixhayashi 
I was mainly interested in https://github.com/Jermolene/TiddlyWiki5/pull/2227 -- the sooner this is merged, the less chance I have of making a mess of my git once more :-)

**Comment by twMat** [comment]
Every listed plugin reads 5.1.10 though... is this irrelevant?
