### ISSUE TITLE
Refactor search features to be more reusable

### ISSUE THREAD

**Issue by Jermolene** [Jermolene/TiddlyWiki5#227]
First we make a `<<search>>` macro that encapsulates the current search logic, including a parameter that contains content that is displayed when the search box is blank. Then we use that in the sidebar, with the tabs as the fallback content.

We also create a new shadow tiddler `$:/Search` that uses that macro to create a standalone search interface.

If you wanted to add search as a sidebar tab you'd create a new tiddler tagged `$:/tags/SideBar` and give it the content `{{$:/Search}}`.

**Comment by pmario** [comment]
IMO the existing "Search" behaviour is much more flexibel and extensible as it was in 2013. So imo should be closed!

**Comment by pmario** [comment]
@Jermolene ... I think this one can be closed. There are several plugins which imo solve the problem for users.

See: https://wikilabs.github.io/editions/field-search/
and: https://talk.tiddlywiki.org/t/advanced-search-in-fields-plugin-new-updates/2019

**Comment by pmario** [comment]
@Jermolene ... bump see my post from Feb. 22.

**Comment by Jermolene** [comment]
Thanks @pmario
