### ISSUE TITLE
Feature request: "Snip out segment" tool

### ISSUE THREAD

**Issue by twMat** [Jermolene/TiddlyWiki5#2270]
**Request**
I'd like a means to select a text segment within a tiddler and choose a button to extract that text into a separate, new, tiddler. Ideally the tool would be usable in both edit mode and view mode.

**Background**
Currently, the TW UI is not optimal for working with longer tiddlers. There are a few examples of this (not immediately relevant for the OP) but one is the lack of the requested tool. This will make it easier to *gradually* conform the text into tiddlers as the needs for those segments elsewhere arise. This is, for instance, not handled with the [text slicer](http://tiddlywiki.com/editions/text-slicer/index.html) edition

**Comment by tobibeer** [comment]
Something like the current ability to drag selected tag which starts the importer?

Perhaps that could be simplified with a modifier key, e.g.: drag-n-drop with CTRL creates a new tiddler while actually removing the selected text from the draft... an perhaps using some template / macro to generate the title.

**Comment by twMat** [comment]
Closing
Ref the upcoming Excision tool in 5.1.12 

Yay! :-D

**Comment by Jermolene** [comment]
Nice to sometimes be able to close tickets!
