### ISSUE TITLE
Documentation for 'tm-open-window' missing

### ISSUE THREAD

**Issue by gernert** [Jermolene/TiddlyWiki5#2273]
In 'Messages' tm-open-window is missing.
Since the list is made by `<<list-links` "[tag[Messages]]">>` it means there is no tiddler 'WidgetMessage: tm-open-window' tagged with 'Messages'.

**Comment by Jermolene** [comment]
Hi @gernert long time no see! I hope all is well. Might you be able to come to next month's [TiddlyWiki Meetup](https://tiddlywiki-europe-2016.eventbrite.co.uk)?

**Comment by gernert** [comment]
Hi @Jermolene. All well here; just less active in the groups, but not in using TW ;-).
Other activities planned for the mid July weekend.
