### ISSUE TITLE
has filter produces wrong result on tags field

### ISSUE THREAD

**Issue by felixhayashi** [Jermolene/TiddlyWiki5#2274]
> **output**    those input tiddlers in which field F has a non-empty value

The following should not output anything in a newly created empty tiddler.

```
{{{ [field:title<currentTiddler>has[tags]] }}}
```

This correctly produces nothing in a newly created tiddler

```
{{{ [field:title<currentTiddler>has[foobar]] }}}
```

**Comment by mklauber** [comment]
PR Up at https://github.com/Jermolene/TiddlyWiki5/pull/2284

**Comment by mklauber** [comment]
Merged, should be fixed

**Comment by pmario** [comment]
@felixhayashi ... should be fixed. pls close!?
