### ISSUE TITLE
Be explicit about browser support targets

### ISSUE THREAD

**Issue by edrex** [Jermolene/TiddlyWiki5#2278]
es2015, move fast and break things, etc. List supported browsers in docs. In future, display badges for CI build status across supported browsers (testling or sauce)

**Comment by pmario** [comment]
Since MS dropped old support for old browsers, https://www.microsoft.com/en-us/WindowsForBusiness/End-of-IE-support we don't need to maintain them too. 

It seems we are good with ES2015: http://kangax.github.io/compat-table/es5/ and browser support.

**Comment by edrex** [comment]
ES2015 is actually what es6 is called now, since they moved to a yearly rolling release schedule for the spec. es5 is basically what we're all used to.

**Comment by pmario** [comment]
uups. thx for the catch. It's the same site, but a different page :) http://kangax.github.io/compat-table/es6/

**Comment by linonetwo** [comment]
We use [https://github.com/browserslist/browserslist](https://github.com/browserslist/browserslist) with transpiler to automatically target older browsers while not wasting our knowledge and the productivity of the latest ES.

For example

```
"browserslist": [
    "last 1 version",
    "> 1%",
    "IE 10"
  ]
```

**Comment by pmario** [comment]
I did find this project https://github.com/lebab/lebab

>Lebab transpiles your ES5 code to ES6/ES7. It does exactly the opposite of what [Babel](https://babeljs.io/) does. If you want to understand what Lebab exactly does, [try the live demo](https://uniibu.github.io/lebab-ce/).

Which may be able to help us to "modernize" or codebase if we want to.

**Comment by pmario** [comment]
@edrex @Jermolene Can we close this issue in favour of: **Updating the JavaScript dialect used by the TiddlyWiki core #7353**

**Comment by Jermolene** [comment]
Thanks @pmario
