### ISSUE TITLE
tiddlywiki not following semantic versioning usage

### ISSUE THREAD

**Issue by buggyj** [Jermolene/TiddlyWiki5#2279]
Althought tiddlywiki follows the form of semantic versioning, it is not follow the usage: ie
majorapi.minorapi.bugfix

from http://semver.org/ -

Given a version number MAJOR.MINOR.PATCH, increment the:

    MAJOR version when you make incompatible API changes,
    MINOR version when you add functionality in a backwards-compatible manner, and
    PATCH version when you make backwards-compatible bug fixes.

so the versions of tiddlywiki should have be 5.1.0 then 5.2.0, ... when there was a feature added and 5.2.0 to 5.2.1 when there was a bug fix.

So the last release should have had the form 5.x.1 as it was a bugfix release.

Thjis may matter to plugin authors who don't want to re-release their plugins for a patch release.

**Comment by felixhayashi** [comment]
I agree. @buggyj Do you know whether a minor version resets the patch version to 0 ? Or are patch and minor incremented separately until a major is incremented? I mean say @Jermolene released 2 patches and one feature in one go. starting from `5.1.14` would this result in `5.2.16`?

**Comment by pmario** [comment]
IMO in TW the 5.x.y will not change anymore. 

IMO we would need 5.major.minor.patch

**Comment by buggyj** [comment]
@felixhayashi 5.1.14 would go to 5.2.0 

@pmario I think your suggestion is a good one.

**Comment by Jermolene** [comment]
We're not alone in abusing sem-ver, so I'm not worried about non-compliance per se, but of course we should analyse any issues that stem from the way that we do do versioning.

Part of the history of the current system is that with TiddlyWiki there were/are hardly ever releases that are literally only bug fixes with no new functionality (of course, 5.1.12 was a counter-example). Therefore I wanted to be able to keep the major "5" as part of the branding, and use the minor "1" for incompatible changes. So 5.2.x might be a later version where we make minor but incompatible changes to the filter syntax.

> Thjis may matter to plugin authors who don't want to re-release their plugins for a patch release.

Why would plugin authors need/want to re-release their plugins when a new version of the core is released?

**Comment by felixhayashi** [comment]
> @pmario I think your suggestion is a good one.

but this would require two version parsing approaches that need to be integrated in tw.

> Why would plugin authors need/want to re-release their plugins when a new version of the core is released?

@Jermolene in the last hangout I attended you mentioned that the plugin lib is bound to a specific core version. I think this makes sense and is also done so in other projects (e.g. Ubuntu maintains a separate package library per major release). So if TW does something that breaks backwards compatibility or introduces major changes to the GUI (leading to 5.2.0), plugin authors could in theory react to that by releasing a new version of their plugin and binding it to the core version 5.2.0.

**Comment by Jermolene** [comment]
Hi @felixhayashi 

> in the last hangout I attended you mentioned that the plugin lib is bound to a specific core version

That only applies to the core plugin library. Plugins in the core library automatically get given the current core version number during the build process.

Plugin authors working on third party libraries can version and update their plugins however they like.

> So if TW does something that breaks backwards compatibility or introduces major changes to the GUI (leading to 5.2.0), plugin authors could in theory react to that by releasing a new version of their plugin and binding it to the core version 5.2.0.

Right now, the simplest thing would be for the plugin author to maintain two plugin libraries, one for their 5.1.x plugins, and one for their new 5.2.x plugins. One could imagine more sophisticated arrangements, but they'd require work that might be hard to justify until we run into the problem.

**Comment by buggyj** [comment]
@Jermolene 
As there is no fixed api for plugins I feel that I have to rebuild and test my plugins when a new version of tw5 is released (rather than just testing). I have quite a few plugins so it is no small effort. My plugins are released with the latest version of tiddlywiki, giving the user confidence that the plugin works with the latest version of tiddlywiki. I would not have to do this if there were a small bugfix in tiddlywiki, and this information were conveyed to the user. This is of course the purpose of semantic versioning.

**Comment by buggyj** [comment]
I have adapted my release process to be in line with the 'linear versioning' of tiddlywiki, so hopefully things won't now change!
