### ISSUE TITLE
getting "slice undefined" error when choosing "markdown" in "content type" field

### ISSUE THREAD

**Issue by rcrath** [Jermolene/TiddlyWiki5#2283]
to reproduce on nodejs version TW5 5.1.11 running on linux:

## steps
1. create new tiddler
2. fill out tags, leaving content empty
3. choose "markdown" in "content type" field

## error message

```
Internal JavaScript Error

Well, this is embarrassing. It is recommended that you restart TiddlyWiki by refreshing your browser
Uncaught TypeError: Cannot read property 'slice' of undefined
```

**Comment by buggyj** [comment]
I am unable to reproduce this using ubuntu 14.04 with v5.1.11  - I am using the mardowndemo edition with the additions of the server components 
		"tiddlywiki/tiddlyweb",
		"tiddlywiki/filesystem"

do you have any other details (system, plugins)

**Comment by rcrath** [comment]
Today it seems to be opening markdown fine.  will close unless it happens again.
