### ISSUE TITLE
Add core branch for widget enhancements

### ISSUE THREAD

**Issue by Jermolene** [Jermolene/TiddlyWiki5#2285]
Establish a new branch of the repo for experimentation with improvements to the architecture of widgets. Include a build of the branch in the [pre-release build](https://github.com/Jermolene/build.jermolene.github.io/blob/master/prerelease-bld.sh).

Issues to be addressed include:
- #2280 Added a widget destructor function

(@felixhayashi @sukima @buggyj and others: please remind me of any other related tickets)

**Comment by buggyj** [comment]
@Jermolene I think you have to create the branch so that @felixhayashi can resubmit his pull request to the new branch.

**Comment by pmario** [comment]
@Jermolene ... IMO can be closed. We do have: https://tiddlywiki.com/prerelease/

**Comment by Jermolene** [comment]
Thanks @pmario I think this ticket was after we introduced the prerelease, the idea was to start publishing a build of the proposed new branch for widget experiments. We still don't build any other branches of the repo, and might want to explore building PRs for example, but this ticket doesn't really help with that discussion.
