### ISSUE TITLE
tw5.com edition is broken - references to files outside the scope of tw5.com

### ISSUE THREAD

**Issue by fnurl** [Jermolene/TiddlyWiki5#2292]
The created tw5.com edition of TiddlyWiki using the npm package i.e.

```
% tiddlywiki ~/tw5.com --init tw5.com
```

and then running it with

```
% tiddlywiki ~/tw5.com --server
```

The following error is produced:

```
fs.js:584
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open '/Users/languages/ca-ES/icon.tid'
    at Error (native)
    at Object.fs.openSync (fs.js:584:18)
    at Object.fs.readFileSync (fs.js:431:33)
    at /usr/local/lib/node_modules/tiddlywiki/boot/boot.js:1469:17
    at $tw.utils.each (/usr/local/lib/node_modules/tiddlywiki/boot/boot.js:69:12)
    at $tw.loadTiddlersFromPath (/usr/local/lib/node_modules/tiddlywiki/boot/boot.js:1465:15)
    at /usr/local/lib/node_modules/tiddlywiki/boot/boot.js:1504:40
    at $tw.utils.each (/usr/local/lib/node_modules/tiddlywiki/boot/boot.js:69:12)
    at $tw.loadTiddlersFromPath (/usr/local/lib/node_modules/tiddlywiki/boot/boot.js:1502:15)
    at /usr/local/lib/node_modules/tiddlywiki/boot/boot.js:1504:40
```

The reason is the file `tw5.com/tiddlers/images/eternal/tiddlywiki.files` which contains relative references to files outside the tw5.com tree. For those looking for a workaround, removing the file `tiddlywiki.files` fixes the problem.

**Comment by pmario** [comment]
For me it seems you want to start an existing edition. .. but the --init command will set everything to an init state. So - Can you describe, what you want to achieve?

**Comment by fnurl** [comment]
The idea was to be able to access the documentation tiddlers locally. So I have a personal wiki in `~/wikis/personal` and then the tw5.com wiki in `~/wikis/tw5.com`

Then in the `tiddlywiki.info` of the personal wiki I would have

    "includeWikis" : [{ "path": "../tw5.com", "read-only": true }],

However, because of the external references, the tw5.com edition does not work without the workaround.

**Comment by Jermolene** [comment]
Hi @fnurl you can also include the documentation as a plugin - just add "tiddlywiki/tw5.com-docs" to your tiddlywiki.info file.

**Comment by pmario** [comment]
>Hi @fnurl you can also include the documentation as a plugin - just add "tiddlywiki/tw5.com-docs" to your tiddlywiki.info file.

how exactly?

**Comment by Jermolene** [comment]
@pmario something like this:

```
{
	"description": "My wiki",
	"plugins": [
		"tiddlywiki/tw5.com-docs"
	],
	"themes": [
		"tiddlywiki/vanilla",
		"tiddlywiki/snowwhite"
	]
}
```

**Comment by Jermolene** [comment]
Thanks @pmario

**Comment by bimlas** [comment]
Sorry for bumping dead thread, but I have the same problem.

```
$ tiddlywiki my-tw5.com --init tw5.com
$ cd my-tw5.com
```

Add `tw5.com-docs` to plugins (how can I do this programatically?).

```
    "plugins": [
        "tiddlywiki/nodewebkitsaver",
        "tiddlywiki/browser-sniff",
        "tiddlywiki/railroad",
        "tiddlywiki/evernote",
        "tiddlywiki/tw5.com-docs"
    ],
```

```
$ tiddlywiki --build index
fs.js:114
    throw err;
    ^

Error: ENOENT: no such file or directory, open 'C:\Users\bimlas\languages\ca-ES\icon.tid'
    at Object.openSync (fs.js:443:3)
    at Object.readFileSync (fs.js:343:35)
    ...
```

`C:\Users\bimlas\languages\ca-ES\icon.tid`: The current working directory is `C:\Users\bimlas\Downloads\my-tw5.com`.

TiddlyWiki 5.1.19, Windows 7 if it matters.

**Comment by pmario** [comment]
>Create tiddlywiki.com with my plugin installed for demo.

You should not re-publish the content from tiddlywiki.com on a different domain name. ... If you want to show your plugin you should use empty.html

**Comment by bimlas** [comment]
My idea is that I can best present a Table of Contents plugin in an environment that users know well. This is tiddlywiki.com thus I would like to introduce the plugin through it.

Why trouble if I use it? Because Google would interpret as a duplicate page or have moral reasons?

**Comment by pmario** [comment]
I think an intro-page should have the bare minimum, that is necessary to present the functionality. 
eg: https://wikilabs.github.io/editions/tocP/  

This is empty.html with the tocP macro and the tocP macro only. So users will not be distracted, by stuff, that was specifically built for tiddlywiki.com. 

If users see the page they think your plugin does all the adjustments, and if something doesn't work, they will never find, where something is wrong. 

AND you'll also have to update every change from tiddlywiki.com, otherwise your version will be out of sync and will present potentially "wrong" info
