### ISSUE TITLE
Problem with vertical tabs in table of contents

### ISSUE THREAD

**Issue by malgam** [Jermolene/TiddlyWiki5#2305]
Vertical tabs with short labels are displayed horizontally when displayed as a table of contents in the sidebar.  This problem was not present in version 5.0.14-beta, but I noticed the behaviour when I ugraded an old tiddlywiki to version 5.1.11.

To reproduce the problem, create a table of contents tiddler with the following contents:

`<<tabs "tab1 tab2 tab3 tab4" "tab1" "$:/state/tab" "tc-vertical">>`

Then tag it with $:/tags/SideBar and the 4 tabs will be arranged in the sidebar in a horizontal row  instead of a column as expected.  The tabs display correctly when the tiddler is viewed in the story river.

I was able to correct the problem by adding the following custom css:

```
.tc-tab-buttons.tc-vertical {
    display: flex;
    flex-direction: column;
}
```

**Comment by Jermolene** [comment]
Hi @malgam I wasn't able to reproduce the problem with the following steps at http://tiddlywiki.com using Chrome. What browser/operating system are you using?

<img width="1424" alt="screenshot 2016-02-22 12 09 12" src="https://cloud.githubusercontent.com/assets/174761/13216603/1bc6625c-d95d-11e5-92f0-0fcbae86a6dc.png">

**Comment by malgam** [comment]
Jeremy,

I'm using Firefox (44.0.2) on Ubuntu (15.10).  To test the problem, I started with a new empty.html and just added the tiddler as described above.  I have also found the same behaviour on Chrome (also on Ubuntu).

Note that it is only a problem with very short tiddler titles ("tab1",...).

Mal

**Comment by Jermolene** [comment]
Great, thank you @malgam I'm seeing the same problem with sufficiently short titles.

<img width="1420" alt="screenshot 2016-02-22 12 33 44" src="https://cloud.githubusercontent.com/assets/174761/13217140/9c73086c-d960-11e5-88b0-ef56ee841d5b.png">

**Comment by Jermolene** [comment]
Hi @malgam I think the problem is now fixed. I've uploaded a new prerelease for you to try:

http://tiddlywiki.com/prerelease

**Comment by rahulkashyap411** [comment]
Dear Jeremy,

I came to this issue because I'm having same problem with Tiddly desktop where the vertical tab is not working. 
Is it perhaps I'm using the 13th release of the tiddly desktop and you had several commits since then? In that case, could you please consider releasing a latest version?
Any help would be appreciated. 

Thanks,
-Rahul
