### ISSUE TITLE
[Minor] Rename $:/core/icon into $:/core/images/icon

### ISSUE THREAD

**Issue by twMat** [Jermolene/TiddlyWiki5#2306]
$:/core/icon should be renamed into $:/core/images/icon so it has the same distinct icon prefix as all other core icons.

I noticed it missing during a prefix search for core icons.

**Comment by Jermolene** [comment]
Hi @twMat I can understand the confusion but there are actually two separate naming conventions here, covering two separate situations:

* `$:/core/icon` is the standard way of naming the icon for a plugin: `<pluginname>/icon` (for example, there is also `$:/plugins/tiddlywiki/text-slicer/icon`)
* Within the core plugin, there is the convention that general purpose images have the prefix `$:/core/images/*`

So, if we renamed `$:/core/icon` to `$:/core/images/icon` then we'd break the first convention, and thus the icon would not be found by the system.

**Comment by twMat** [comment]
Ok, thanks for explanation.
