### ISSUE TITLE
wiki links in markdown

### ISSUE THREAD

**Issue by RMBLRX** [Jermolene/TiddlyWiki5#2307]
I currently use tiddlywiki in conjunction with a bitbucket wiki and dump my tiddlers as plaintext (savetiddlers) into the wiki directory.  The only problem I have with this is that wiki links differ between them, since TW uses # before the wiki name and BB just uses the name itself.  I was wondering whether it would be possible to not require the hashtag (essentially just automatically inserting it for all relative linking when it's not present).

I believe this is handled here: TiddlyWiki5/plugins/tiddlywiki/markdown/wrapper.js

**Comment by tobibeer** [comment]
> since TW uses # before the wiki name and BB just uses the name itself

I imagine you meant "before the tiddler title" or more precisely "before the permalink" (in the url)... anyhow, I have no idea what the second part means

> possible to not require the hashtag

I assume you are not referring to "hashtag" in the semantic tagging sense but to something else, i.e. a url hash?

**Comment by RMBLRX** [comment]
In markdown, I would like to be able to use [tiddler](tiddler) instead of [tiddler](#tiddler) so that it's recognized as a wikilink on both platforms.

**Comment by tobibeer** [comment]
@RMBLRX ah, ok... thx for clarifying

**Comment by avks** [comment]
Any progress on this?

**Comment by MaxGyver83** [comment]
I'm also interested in this.

In case the problem isn't clear:

I want my Markdown tiddler links to work everywhere (p.e. in `vim`). This means, a link should look like a link to a file, p.e. `[Tiddler](tiddler.md)`. When I hover the mouse over such a link in TiddlyWiki, I see <http://localhost:8090/tiddler.md>. This link does not work. TiddlyWiki only understands links like `[Tiddler](#tiddler)` (or `[[tiddler]]`). Then it points to <http://localhost:8090/#tiddler>.

It would be nice if TiddlyWiki could understand `[Tiddler](tiddler.md)` and convert it under the hood to `[Tiddler](#tiddler)`.

**Comment by pmario** [comment]
@MaxGyver83 ... I think you need to open a new issue here. This one is closed. So your comment will "go missing".
