### ISSUE TITLE
Changing the Wiki Title appends the new name to the old until the page reloads

### ISSUE THREAD

**Issue by NigelThorne** [Jermolene/TiddlyWiki5#2309]
Using tiddlywiki  from node. 

Create a new wiki. 
Load it in browser. (I use chrome) 
Change the browser title. 
see it's confused. 

Reload page in browser. 
See it's fixed.

**Comment by sukima** [comment]
Unable to reproduce. Are you sure your file system permissions are correct?

![tw-2309](https://cloud.githubusercontent.com/assets/70075/13416754/fa0036bc-df32-11e5-934c-ae06c1a192de.gif)

**Comment by NigelThorne** [comment]
I just tried again with a new instance... and it worked fine. I can't
reproduce it either.

It's fine to close this. If I come across it again at any points I'll work
out reproduction steps and re-raise it.




---
"Man, I'm going to have so many chickens when this lot hatch!"

**Comment by Jermolene** [comment]
Thanks @NigelThorne
