### ISSUE TITLE
negative move filters wrap around the list, but positive one's don't.

### ISSUE THREAD

**Issue by mklauber** [Jermolene/TiddlyWiki5#2312]
given a list `A B C D` if I run `A B C D +[move:-1 [A]]` I get `B C A D`.  However, if I were to do `A B C D +[move:1[D]]` it doesn't wrap around, and I get `A B C D`.  I feel like these two operations should behave similarly.  At the very least I'd like a way to move towards the start of the list without wrapping.

**Comment by tobibeer** [comment]
@matabele, this sounds like one for you.

Actually, it sounds like two problems:

1) If we wrap it should go both ways forward and back

2) shouldn't this:

```
{{{ A B C D +[move:-1 [A]] }}}
```

yield 

```
B C D A
```

?
