### ISSUE TITLE
Change Tiddlywiki url path 

### ISSUE THREAD

**Issue by frankrousseau** [Jermolene/TiddlyWiki5#2336]
Hello TiddlyWiki community,

  I would like to setup TiddlyWiki behing a url path that is not the root path. I mean I would like to access it via this url:

    https://mydomain.tld/apps/tiddlywiki

Is it possible? How can I do it? By default, all requests performed by tiddlywiki are done on the root path.

Goal: port TiddlyWiki on [Cozy](https://cozy.io).

**Comment by Jermolene** [comment]
Hi @frankrousseau my apologies for the late response. I'm a fan of Cozy, and would love to help get TiddlyWiki running well on it.

> I would like to setup TiddlyWiki behing a url path that is not the root path.

There are instructions for doing this here:

http://tiddlywiki.com/#Using%20a%20custom%20path%20prefix%20with%20the%20client-server%20edition

Let me know how you get on.

**Comment by frankrousseau** [comment]
Thank you for your answer! I don't know well TiddlyWiki, so can you tell me more about the second part?

*Configure the client by creating a tiddler called $:/config/tiddlyweb/host that contains $protocol$//$host$/path/to/my/wiki/*

Where can I perform this and make sure it happens for every user that installs TiddlyWiki on their Cozy?

**Comment by frankrousseau** [comment]
`pathprefix` doesn't look to work too. It keeps on returning me 404 errors. Here is the code I added to make TiddlyWiki work: 

https://github.com/frankrousseau/TiddlyWiki5/blob/master/server.js#L21-L33

**Comment by Jermolene** [comment]
Hi @frankrousseau you may find that the easiest way to create the tiddler `$:/config/tiddlyweb/host` is to do it in code at the top of `startServer()`, something like this:

```
$tw.wiki.addTiddler(new $tw.Tiddler({
title: "$:/config/tiddlyweb/host",
text: "http://127.0.0.1/apps/tiddlywiki5"
}));
```

**Comment by frankrousseau** [comment]
Ok, I changed the code. I had to create the tiddler after the server starts to avoid any error in the command line. But it still returns 404 errors when I try to reach `http://localhost:port/apps/tiddlywiki5`.

Code: https://github.com/frankrousseau/TiddlyWiki5/blob/master/server.js#L34-L53

**Comment by Jermolene** [comment]
Hi @frankrousseau it looks like one problem is that one code path leads to ` $tw.boot.boot();` being called twice, but a subtler one is that the `--init` command and the `--server` command need to be separate invocations of `tiddlywiki.js`. In fact, all that the `--init` command does is copy files from `editions/*` into the target folder; you may be better off doing that elsewhere. So, the flow should be:

* Check if the target folder has a `tiddlywiki.info` file
* If not, copy the files of appropriate edition to the target folder (ideally, give the user the choice of which edition they want to use)
* Then start up `tiddlywiki.js`, pointing to the target folder, and passing the `--server` command as you are at present

Let me know how it goes

**Comment by frankrousseau** [comment]
I made the required changes by chosing the *server* edition. But it still doesn't work:

Some popups are displayed:

```
 syncer-browser - 23:02:26 27 3 2016

[Exception... "" nsresult: "0x805e0006 ()" location: "JS frame :: $:/core/modules/utils/dom/http.js :: exports.httpRequest :: line 63" data: no]
```

```
 syncer-browser - 23:02:28 27 3 2016

Sync error while processing '$:/StoryList': [Exception... "" nsresult: "0x805e0006 ()" location: "JS frame :: $:/core/modules/utils/dom/http.js :: exports.httpRequest :: line 63" data: no]
```

**Comment by Jermolene** [comment]
Hi @frankrousseau thanks for your patience and sorry it's been such a kerfuffle. I'll be on a proper computer tomorrow and will have a proper look at your code and give it a try.

**Comment by frankrousseau** [comment]
Ok thx! Don't worry, I don't know well the Tiddlywiki architecture. It doesn't make things easier.

**Comment by Jermolene** [comment]
Hi @frankrousseau I think there are a couple of issues with your current code:

1. You need to add the path prefix parameter to the end of the `--server` invocation:

```

  process.argv = process.argv.concat([
    dirPath,
    '--server',
    port, // port
    '$:/core/save/all', // roottidler
    'text/plain', // rendertype
    'text/html', // servertype
    '', // username, nothing, auth is handled by Cozy
    '', // password, nothing auth is handled by Cozy
    '127.0.0.1', // host
    '/apps/tiddlywiki5'
  ]);
```

2. You need to include the port number in the tiddlyweb/host config:

```
  $tw.wiki.addTiddler(new $tw.Tiddler({
    title: "$:/config/tiddlyweb/host",
    text: "http://127.0.0.1:9444/apps/tiddlywiki5/"
  }));
```

http://127.0.0.1:9444/apps/tiddlywiki5/ should then work as expected.

**Comment by frankrousseau** [comment]
Sorry but it doesn't work. My browser tells that some requests keep requesting 127.0.0.1 without port. The result is that the UI is displayed but error messages are displayed too.

**Comment by Jermolene** [comment]
Hi @frankrousseau I'm still seeing the old code at https://github.com/frankrousseau/TiddlyWiki5/blob/master/server.js, could you perhaps update it so that I can give it a go?

**Comment by frankrousseau** [comment]
Yep, sorry. It's now done.

**Comment by Jermolene** [comment]
Hi @frankrousseau thanks for your patience. I downloaded your latest code and modified line 12 to point at my own folder path. Everything seems to work fine; there is indeed one 404, but that's expected behaviour (it's the WebDAV saver sniffing for webdav support).

![screenshot 2016-03-30 10 50 18](https://cloud.githubusercontent.com/assets/174761/14138447/380672b6-f665-11e5-92e1-c91009ee5950.png)

Perhaps you could screenshot the errors you're still seeing?

**Comment by frankrousseau** [comment]
Sorry it was a problem of rights. I'm able to make it work locally, now I'm looking for making it work on my online Cozy.

**Comment by frankrousseau** [comment]
I didn't do extensive tests but it looks like TiddlyWikki is working on Cozy. Thank you for your help! We will have user feedback, so I will probably contact you soon for other questions. Whatever thank you a lot. Having such a great app is Cozy is a super news.

**Comment by Jermolene** [comment]
Hi @frankrousseau I'm sorry it was such a long journey to get things running, but glad things are working now. Do please let me know if I can help.
