### ISSUE TITLE
Introduce wikify widget

### ISSUE THREAD

**Issue by Jermolene** [Jermolene/TiddlyWiki5#2337]
It is proposed to introduce a new `<$wikify>` widget that assigns the result of parsing and rendering a string of wiki text into a variable. Internally, the widget must cache the parse and widget trees so that it can be refreshed efficiently.

Attributes:
- `name`: name of the variable to assign
- `text`: text to parse and render
- `type`: content type of the text (defaults to `text/vnd.tiddlywiki`)
- `mode`: parse mode  `block` (the default) or `inline`
- `output`: type of output returned:
  - `text`: return just the plain text of the rendered output (ie HTML tags are omitted)
  - `html`: return the rendered HTML of the output
  - `parsetree`: return a formatted JSON representation of the parse tree
  - `widgettree`: return a formatted JSON representation of the widget tree

The `parsetree` and `widgettree` options will allow the removal of the corresponding widgets in the `tiddlywiki/internals` plugin.

@tobibeer I am aware of your `<$setvars>` widget; does it offer similar functionality? It looks like it's got a great deal more complexity and flexibility than what is being proposed here.

Note that this proposal addresses a common request to be able to use the wikified result of a macro as the value of an attribute of a widget. This can now be done by wrapping the widget with a wikify widget like this:

```
<$wikify name="my-wikified-macro" text=<<my-original-macro>>>
<$text text=<<my-wikified-macro>>/>
</$wikify>
```

**Comment by nome** [comment]
Cool, thank you! :-) Looks like this solves many of the issues discussed at https://groups.google.com/forum/#!topic/tiddlywikidev/txUKSUjPiug

**Comment by Jermolene** [comment]
Fixed in #2315

**Comment by Jermolene** [comment]
Commit: 2adf09129dddd4df231d18b4198fb2a9663fdf5c

**Comment by EvanBalster** [comment]
This changes EVERYTHING.  <3

**Comment by majidaldo** [comment]
I've already registered a 'reaction'.. but This is SOO important! Seriously!

This. Changes. EVERYTHING!

**Comment by tobibeer** [comment]
@Jermolene, love this... :+1: 

Lego-like stuff, possibly the easiest form of core support for parametric wikification I can think of. My gut says the wikify widget is plenty more intuitive than setvars ...to those uninitiated to either. Basic, yet very powerful.

PS: Sorry for my absence. Will do some playing around now that it's out there. I very much like a strong core and tend to only ever install (even my own) plugins when I really really need them.

**Comment by Jermolene** [comment]
Hey @tobibeer very good to see you back. Might you be able to come to the UK for the meet-up in July?

One thing that would be *terrific* now that you're back is to truly to get some of the hints and tips from your site(s) into TW.com.

Delighted that you like the wikify widget. I'm kind of surprised it's taken this long; the prompt was getting the keyboard shortcuts included in the tooltips for the editor toolbar. It was complicated because of the way that the keyboard shortcuts have an extra layer of indirection to allow customisation. Now that it's here I expect the wikify widget will find many other uses....
