### ISSUE TITLE
Setting to deactivate missing tiddler links

### ISSUE THREAD

**Issue by twMat** [Jermolene/TiddlyWiki5#2340]
For public TWs, missing tiddler links are as inelegant as dead external links (or even worse as clicking them creates a very unfamiliar situation for a visitor.) 

The setting to deactivate automatic CamelCase linking is good but not enough. I want to be able to write `[[myTiddler]]` and in my "admin TW" have it display in the current missing manner - but when the TW is published, the missing tiddler links should appear as plain text.

**Proposal**: a setting next to `Ctrlpanel > CamelCase wiki links` to deactivate the navigation and formatting for missing tiddler links.

This would simplify use of TW for public sites which, of course, is valuable for fhe TW project at large.

**Comment by sukima** [comment]
Well there is the [`tv-wikilinks` variable](http://tiddlywiki.com/#tv-wikilinks%20Variable). Or possibly add a CSS rule for `.tc-tiddlylink-missing` that renders the text correctly.

**Comment by twMat** [comment]
That was news to me - thank you @sukima ! I take it as a definite indication that the context I bring up in the OP is recognized. I still think it is justified to make it as a global setting in core for the sake of making TW more "keyturn" for public use.

**Comment by sukima** [comment]
Yes, `tv-wikilinks` would disable all links (even the non-missing ones) and it is mainly a per tiddler/node scope instead of app wide. The `.tc-tiddlylink-missing` would fix the rendering of missing links but it would not prevent clicking them AFAIK.

So perhaps a third option is needed in this one use case? I however, am currently happy with the default behavior for my blog(s).

**Comment by Jermolene** [comment]
Hi @twMat I agree it would be useful to be able to suppress missing links; I can imagine many people would want such a setting included in a read-only theme, for instance. Implementing it would require some modifications to the link widget but nothing too drastic.

**Comment by twMat** [comment]
Thank you guys for this!
