### ISSUE TITLE
[#1290 revisit] Nav to tiddler should align viewport with tiddlers top edge

### ISSUE THREAD

**Issue by twMat** [Jermolene/TiddlyWiki5#2343]
@felixhayashi @Jermolene 

**"Pre-proposal"** Close #1290 and replace it with this one which raises the same issue/OP.
#1290 has resulted in good things _but_  the OP itself is still not resolved and the lengthy and now partially outdated discussion makes re-reading it problematic.

<hr>

**Issue**
Navigation-result varies depending on if the tiddler is navigated to from above or below in story river, and whether the tiddler is taller than viewport. To reproduce on tw.com:
- Leave default tiddlers open but edit second tiddler (i.e GettingStarted) by erasing all content and saving.
- Use the sidebar Open tab to navigate around between those three tiddlers.
- Depending on where you navigate _from_, the short tiddler is positioned differently; aligning its top _or_ its bottom edge with viewport.
  <br><br>

![tw1](https://cloud.githubusercontent.com/assets/4534056/14068170/043a9e3a-f47b-11e5-89f7-f4efbf86c0a2.gif)

**Proposal**
- Make default navigation align tiddlers top edge with viewport top. 
- To prevent showing "empty river bottom" use overriding rule stating not to scroll down so much that last tiddlers bottom edge leaves viewport edge (with some offset).

**Why is the current navigation behaviour bad?**
- When "bottom-aligned", you don't know if you see the whole content so you're (1) _forced_ to scroll and (2) only to find out you scrolled for nothing!

Further, quoting from @felixhayashi #1290 

> - This is not a standard web behavior: When using internal website links to page anchors (#), any browser will scroll always until the anchor is at the top of the page and not just till it is in the viewport somewhere at the bottom.
> - It is the philosophy of tiddlywiki to create tiddlers with small information chunks and link them. So when aiming at creating a wiki with tiddlers all having small content bodies, and navigating to these tiddlers, they may not be immediately recognized after the navigation-scroll as the user always looks at the top of the webpage first where he/she expects the content to be and the navigated tiddler might instead be displayed at the very very bottom.
> - Referring to the example given above, if Tiddler C has a size of 70% of the page height and D 30% then the user might think he/she falsely scrolled to C instead of D since D is displayed at the top.
> - Frameworks like bootstrap use "hot zones" to unfold the table of contents on the sidbar if an anchor makes it into the "hot zone" (scroll this site for an example http://getbootstrap.com/components/). If an anchor link is clicked, the anchor is focused at the top (in the hot zone) and the toc unfolds. In tiddlywiki, this is not possible, because we never know if a tiddler that is navigated to makes it to the top unless its body is longer than the pageheight or it is newly opened. So it is not possible to define a zone where we can say "this tiddler in the story-river is currently focussed" to trigger an event.

**Comment by sukima** [comment]
Well written! This is the exact problem I ran into with my [homepage](https://tritarget.org/). I am interested in possible solutions. Was going to look into the math of `scrollIntoView` function in the [NavigatorWidget](http://tiddlywiki.com/#NavigatorWidget) but I am attending a conference this week.

![twscrollbug](https://cloud.githubusercontent.com/assets/70075/14063705/82b89076-f3ab-11e5-8d0c-e62248ca0812.gif)

**Comment by sukima** [comment]
I just tried reproducing this as you described:

>* Leave default tiddlers open but edit second tiddler (i.e GettingStarted) by erasing all content and saving.
>* Use the sidebar Open tab to navigate around between those three tiddlers.
>* Depending on where you navigate from, the short tiddler is positioned differently; aligning its top or its bottom edge with viewport.

But I did not see the problem on TiddlyWiki.com. Do you think you could offer [an animated GIF](http://www.cockos.com/licecap/)?

(Firefox 45.0.1 Mac OS X 10.11.3)

**Comment by twMat** [comment]
@sukima - I updated the OP to include an animation (btw, neat gif recorder!). 

If you agree this clearer than your animation then maybe it's better to only have this one in the thread, i.e to remove yours to avoid distraction. And if you erase your post just above this one, I'll erase this one - again to minimize outdated info.

Win10, FF and Chrome, latest versions

**Comment by sukima** [comment]
So your animation is the same thing I experienced. When I did it I thought the scrolling was correct. This is because the GettingStarted content was removed the bottom of the tiddler is at the bottom of the view port.

So the question is this correct or unexpected? I think your suggestions:

>* Make default navigation align tiddlers top edge with viewport top.
>* To prevent showing "empty river bottom" use overriding rule stating not to scroll down so much that last tiddlers bottom edge leaves viewport edge (with some offset).

would make sense and it would have eliminated the confusion I had. I understand the current behavior but it is a bit unorthodox. Having it scroll to the top of the tiddler regardless would act more as expected by me.

I do also think that my animation show a possible edge case in that the tiddler scrolls into view only half way and you don't see the full text.

**Comment by twMat** [comment]
>I do also think that my animation show a possible edge case in that the tiddler scrolls into view only half way and you don't see the full text.

Not sure I understand how your case differes - _but_ it did make me note a critical point that:

- When "bottom-aligned", you don't know if you see the whole content so you're (1) forced to scroll and (2) only to find out you scrolled for nothing!

Updated the OP.

**Comment by felixhayashi** [comment]
Hi guys,

The topstoryview plugin solves #1290 by scrolling to the top and adding a padding for the last tiddler in the river so it can be scrolled till it reaches the top (the padding is adjusted everytime another tiddler becomes the last tiddler).

**Comment by pmario** [comment]
If I adjust my browser zoom level to 100%, it always scrolls to the top, if there is enough content at the end of the river. ... Did you try this?

--------

So for me, browser zooming seems to be involved too. ... As I wrote in #1290. What ever is the default, it will be wrong for someone, with a different usecase. ..

So if there is a plugin that fixes the problem -> use it!

For me this is clearly plugin territory. The core should implement the easiest and most light weight solution, that does the job. And it should provide hooks for plugin or / and theme authors to change the behaviour in any given way.

**Comment by twMat** [comment]
@felixhayashi 
>The topstoryview plugin

Aha! That's great!

@pmario 
>If I adjust my browser zoom level to 100%, it always scrolls to the top, if there is enough content at the end of the river. ... Did you try this?

Really? Are you sure you're repeating the OP steps?

>The core should implement the easiest and most light weight solution, that does the job. 

The question is of course what *is* that "job" you refer to. As long as we have a core that caters to be "small *and* user friendly" then I think the OP is very reasonable default behaviour. That said, I'd personally like a separation between "minimal distro" and "user friendly distro".

**Comment by sukima** [comment]
> The topstoryview plugin solves #1290

@felixhayashi Where is this plugin? I searched the the plugins from http://tiddlywiki.com to no avail.

**Comment by twMat** [comment]
>Where is this plugin?

@sukima - Felix refers to [tiddlymap.org](http://tiddlymap.org) but I took the liberty of putting up a [tiddlyspot](http://topstoryview.tiddlyspot.com). - @felixhayashi , the password to that tiddlyspot is "password" - if you want to take it over then go ahead or if you want me to erase it just say it.

**Comment by felixhayashi** [comment]
Hi @sukima,

sorry, forgot to post a link to the repo: https://github.com/felixhayashi/TW5-TopStoryView

@twMat Thanks for creating a demo and pointing to all relevant links in the first tiddler :) I should not always refer to tiddlymap.org but instead create demo pages for each plugin I created separately, you are right. I will deal with it, once I have more time.

**Comment by twMat** [comment]
For reasons unclear to me, the [BackWallMacro](http://backwall.tiddlyspot.com/) depends on having TopStoryView installed or clicking a link will not cause any scrolling.

The BackWallMacro basically uses tc-tagged to style a tiddler with a `background:url() fixed top` style. I'm guessing the current scroll mechanism interprets this as if the tiddler is already at top - and TopStoryView does something else.

@Jermolene 
Is there any particular reason why a mechanism like in TopStoryView should not be implemented into core?

**Comment by Jermolene** [comment]
> Is there any particular reason why a mechanism like in TopStoryView should not be implemented into core?

@twMat I'm not sure what TopStoryView does beyond replacing the current "ScrollIntoView" semantics with "ScrollToTop", which is the subject of this thread.

I've tried to explain the motivation for the current situation before:

* from a user experience perspective, I'm trying to avoid the perceptual jolt from scrolling more than necessary
* from a technical perspective, "ScrollToTop" isn't possible for the last tiddler in the story view unless it's taller than the screen

I don't think that the reasons given in the OP for changing the current behaviour add up to much beyond "I don't like the current behaviour". That's OK because resolving conflicting requirements is what plugins are for.

**Comment by pmario** [comment]
@twMat .... I think this one changed for the latest versions?!

**Comment by twMat** [comment]
Thank you everyone.
Closing.
