### ISSUE TITLE
tag (tiddler) titles containing pipe char "|"

### ISSUE THREAD

**Issue by CodaCodr** [Jermolene/TiddlyWiki5#2351]
Reading the docs, I don't see any mention/warning against using the pipe char in a tag name (I'd likely not choose to name a tiddler with it knowing how it i used in [[friendly link|something else]] but using it in a tag got past my mental TW parser).  

The tag in question "(a | b)"

It's interesting to note, however, that it worked pretty much everywhere -- until I tried to pass it into a macro that had this line (or similar -- I had a fun hour or so trying to figure out was going on since the macro worked fine for a hundred or so other tags but failed on the pipe one)

<$macrocall $name="tag" tag="$t$" />

Which, when rendered in a button, rendered as 

{{(a | b)||$:/core/ui/TagTemplate}}

**Comment by pmario** [comment]
Reading your issue, I understand, what happened. ... Can you suggest, what should happen to solve your problem? 

There are several more problems with special characters in tiddler titles eg: `]]>)` and so on. 

The wikitext docs may be a place to add some more info http://tiddlywiki.com/#WikiText:WikiText%20[[Linking%20in%20WikiText]]

**Comment by CodaCodr** [comment]
Nothing should happen to the code base -- the parser is working fine and has worked fine for a long time so, unless Jeremy et al can find an easy fix, I'd do nothing.

That said, a consolidated and focused single tiddler in the documentation that lists disallowed (problematic under some circumstances) characters would be good.

The only reason I posted the issue was to point out that pipe "broke" the intended UI (giving a poor UX).  If Jeremy believes that is enough cause to revisit the parser, all well and good.

**Comment by Jermolene** [comment]
Hi @CodaCodr this has come up before, and I think is worth addressing. For 5.1.12, I've added a warning in the edit template if the tiddler title contains a dangerous character.

One question, though, is whether this is the best list of bad characters: `| [ ] { } " '`

https://github.com/Jermolene/TiddlyWiki5/commit/12661f5cdaca19135801ca9b47449e0eeadfb0c4



<img width="1096" alt="screenshot 2016-03-31 11 13 30" src="https://cloud.githubusercontent.com/assets/174761/14172790/e8731100-f731-11e5-93ca-afce60c3e593.png">

**Comment by CodaCodr** [comment]
Hmm - would "< >" be problematic too?

Reminder though, these were tag names so tag creation should be caught also (since they're usually not created via New Tiddler code - at least, not from a UI perspective).

**Comment by pmario** [comment]
I did create a group topic. So we'll see :) https://groups.google.com/forum/#!topic/tiddlywiki/4t9nt9t_7Xs

**Comment by sukima** [comment]
> Hmm - would "< >" be problematic too?

@CodaCodr I successfully used those in [my TiddlyWiki](http://tritarget.org/wikis/EmberConf2016.html#%3Cselect%3Eing%20Good%20Ember%20Patterns)
