### ISSUE TITLE
Extend <$set> widget to allow saving filter results as a single entry

### ISSUE THREAD

**Issue by twMat** [Jermolene/TiddlyWiki5#2363]
The `<$set>` widget generates a list as output when used with the `filter` attribute. That has the side effect that the output is formatted according to standard TW list rules: space separation, and double square brackets to quote titles containing spaces.

Thus, a filter that outputs a single result such as `Filter Result` will be formatted as `[[Filter Result]]` in the output.

This can be fixed by adding a means to save just the first entry in the list as a single title, without any of the quoting.

[ref discussion](https://groups.google.com/forum/#!topic/tiddlywiki/gEbutPLs1vs)

**Comment by Jermolene** [comment]
Fixed in b35544bf4946596e60f7b0c7f0a55fa490ac2a24
