### ISSUE TITLE
Minor desciption change for tiddler makedatauri.js

### ISSUE THREAD

**Issue by twMat** [Jermolene/TiddlyWiki5#2372]
Hope it's better to post a **pull request** here than not at all. (What's with clicking "New Pull Request" only to instead get some "Compare Changes" page where I must.. etc, etc.)

Git link: [makedatauri.js](https://github.com/Jermolene/TiddlyWiki5/blob/086506012d98e9db34c7d96dc27aea249a9bdbc8/core/modules/macros/makedatauri.js) 

line 6: Macro to convert the content of a tiddler to a data URI

change to

line 6: Macro to convert a string of text to a data URI

**Comment by sukima** [comment]
@twMat, you compare changes because guthub needs to know what you want inckude in the pull request. It assumes you have already made the changes and pushed them up to your own fork. Alternativly you can use github’s web editor which would allow you to make a PR as part of the change in one shot.

**Comment by sukima** [comment]
Seems [closing an issue via commit message](https://help.github.com/articles/closing-issues-via-commit-messages/) doesn't work anymore?! :confused:

**Comment by sukima** [comment]
Oh! it needs to be `Closes #2372` not `Closes issue #2372`.

![Stupid Computers](http://i907.photobucket.com/albums/ac272/Iri5hka/errishuman_zpsbd7cf0fd.jpg)

**Comment by twMat** [comment]
@sukima - thanks for this!

>Seems closing an issue via commit message doesn't work anymore?!

I'm obviously not really the one to answer things about github - but maybe it's only the owner of the repository, and the issue starter, who can close threads via this method? That would make sense to me at least.

Closing now tho. Again, thanks!
