### ISSUE TITLE
InfoPanel tab "sources" missing, both in InfoPanel tiddler and in translatable strings

### ISSUE THREAD

**Issue by PauDeLuca** [Jermolene/TiddlyWiki5#2374]
Hi!

Translating the tiddler InfoPanel I've noticed the following:

-InfoPanel tab "Sources" is missing from the list of tabs described in the body of the tiddler. I will handle it adding a description to it in the spanish edition and propose a description in the main edition to pull.

-InfoPanel tab "Sources" is missing as translatable string. I can solve it in the spanish edition by searching the original tiddler and adding a translated tiddler to languages/es-ES, but I don't know how to include it in the translation plugin.

**Comment by PauDeLuca** [comment]
«To close the info panel, click anywhere outside it.»

It actually behaves otherwise: anywhere you click, outside the panel, or inside (to switch tabs, for instance), will close the panel.

**Comment by Jermolene** [comment]
Hi @PauDeLuca what browser and operating system are you using? Switching tabs shouldn't hide the info panel.

The "source" tab is part of the tiddlywiki.com edition, not part of the core, and so is not translatable.

**Comment by PauDeLuca** [comment]
Hi, and thanks again for your patience.

―«The "source" tab is part of the tiddlywiki.com edition, not part of the
core, and so is not translatable.»
I see... I have though mentioned it in in the spanish translation of
InfoPanel:

''Fuentes'' (If it's not a translatable string, I will then leave it as
''Sources'' - En el caso de tiddlers que forman parte de la documentación
oficial, se indica su origen en la página de TiddlyWiki, donde se lo
encuentra como página HTML estática. En tal caso, para facilitar
contribuciones que mejoren la documentación, se muestra también la ruta del
archivo original en GitHub.

(its approximate translation in english, which I would add to the original
InfoPanel):
''Sources'' - In the case of the tiddlers that belong to the official
documentation, link to the origin of the tiddler, shown as a static
HTML-page within www.tiddlywiki.com.

In order to help contributors to improve the documentation, a link is
shown, as well, to the original file in the GitHub repository|.

====================

I'm using Firefox 45 on LinuxMint 17.3 Cinnamon 64bit.

P.-)


2016-04-14 9:11 GMT+02:00 Jeremy Ruston <notifications@github.com>:

**Comment by tobibeer** [comment]
@PauDeLuca, is there anything left open about this?

**Comment by PauDeLuca** [comment]
Not, as far as I know.

2016-09-30 22:44 GMT+02:00 Tobias Beer <notifications@github.com>:

**Comment by tobibeer** [comment]
feel free to close it

**Comment by PauDeLuca** [comment]
To close what? This got solved, closed and merged ages ago.
I'm on mobile. Let me check next week when I'm back at my desk. Now I don't
see much
P.

El sábado, 1 de octubre de 2016, Tobias Beer <notifications@github.com>
escribió:
> feel free to close it
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.<
https://ci3.googleusercontent.com/proxy/0Y14uUdGZ7WSZ6yl1PGHnqIemi0nGMYW9YrKBLIgqhfdnHe9qgkST8TosvpCoqerbijT7jcrmh6XQZ4sm58_bbAFg4FjqlkN55MYGXfdFe2tSqAJbCn6QVEn17kEg9J6dDig6vsVwn6Vvfsr0oPVs64O8CHFdw=s0-d-e1-ft#https://github.com/notifications/beacon/AJ3Vd6X6wtOHqAsDZxgar-wr_S7fr4Lfks5qvgPsgaJpZM4IHEXA.gif>

**Comment by pmario** [comment]
@Jermolene ... This issue can closed, since it has been solved

**Comment by Jermolene** [comment]
Thank you @pmario
