### ISSUE TITLE
Some concept-definition needed, please

### ISSUE THREAD

**Issue by PauDeLuca** [Jermolene/TiddlyWiki5#2377]
Translating about widgets and messages, I seem to trip over my own coding illiteracy. I would be thankful if I could get some help to understand the following concepts, in order to better adjust my translation and, if possible, add the corresponding tiddlers, to soften a bit the learning curve for future "lay" users. (I guess it's a common phenomenon that as a technology spreads and gains audience, the expected technical knowledge of this audience is lower... my grandma has a huuuge TV, but she doesn't know how it works, nor why TVs are now so thin).

-Story river:
-Story list:
-History list:
-Store:

By now, I'm referring to them as StoryRiver, StoryList, HistoryList and TiddlerStore, so I get them displayed as absent tiddlers, reminding me to complete the info.

Thanks again!

**Comment by Jermolene** [comment]
Hi @PauDeLuca 

The "story river" is defined on tw.com, but as `Story River`, not `StoryRiver`. It's just the colloquial name for the main sequence of tiddlers that are displayed within TiddlyWiki.

The story list and the history list are part of the navigation mechanism. The story list is a tiddler that holds a list field containing the titles of each tiddler displayed in the story river. The history list keeps track of the navigation history.

The tiddler store is the internal data structure in which tiddlers are stored.

**Comment by pmario** [comment]
- Story river 
  - Is the element of the page layout that contains all visible tiddlers. The default behaviour is, that you can scroll up and down. So with some imagination it looks like a river :)

- StoryList is a tiddler, that contains a field named "list". If you open the link and then open the tiddler in edit mode, you'll see the list field. It contains a list of all open tiddlers. 
  - see: http://tiddlywiki.com/#%24%3A%2FStoryList
  - the "list" field concept: http://tiddlywiki.com/#ListField

- HistoryList .. is a system tiddler, that contains the "access history" for one session
  - see: http://tiddlywiki.com/#%24%3A%2FHistoryList
  - TW has the possibility to go back and forth with the browser buttons. HistoryList is used to make this happen. 
     - see: http://tiddlywiki.com/#%24%3A%2FControlPanel:%24%3A%2FControlPanel%20%24%3A%2Fcore%2Fui%2FControlPanel%2FSettings%2FNavigationAddressBar
     - Control Panel: Settings: Navigation Address Bar   and Navigation History. 

- Store is the core internal tiddler store. It is not visible. It's just the tiddler storage area

**Comment by Jermolene** [comment]
@pmario snap!

**Comment by PauDeLuca** [comment]
Thank you both, @pmario and @Jermolene!
