### ISSUE TITLE
Add "replace" animation to Classic story view

### ISSUE THREAD

**Issue by twMat** [Jermolene/TiddlyWiki5#2378]
To try it yourself, on e.g tw.com, change [$:/config/AnimationDuration](http://tiddlywiki.com/#%24%3A%2Fconfig%2FAnimationDuration) to 1000.

Then click edit and undo and note the various animation effects and side-effects. The problem is particularly problematic in FF:

![twanimation](https://cloud.githubusercontent.com/assets/4534056/14561420/79941194-0316-11e6-8975-2cb51da49790.gif)
(disregard the color shifting caused by the recording software)

1) The, presumably intentional diagonal downswipe, IMO merely confuses matters. Especially so when combined with the typically autmatic reposition-scrolling.
2) In FF it also triggers a horizontal scrollbar to flash by in the sidebar.
3) In FF there is also some "bonus animation" with the sidebar titles.

However the animated re-positioning of the tiddler beneath is very good though.

I propose to remove the diagonal swipe effect, which IMO doesn't contribute constructively. Hopefully this will also solve (2) and (3)

I believe the animation is created in [$:/core/modules/storyviews/classic.js](http://tiddlywiki.com/#%24%3A%2Fcore%2Fmodules%2Fstoryviews%2Fclassic.js)

If there is to be another animation instead, I'd suggest something that rather draws attention _to_ the tiddler, than _off_ it.

IMO this is a rather important UI matter because it affects everyone and all the time and gives the impression of a glitch rather than a feature.

[Win10, FF, Chrome]

**Comment by pmario** [comment]
IMO this is the same problem we already had with the tiddler title. .. I'll have a look, if I find the issue.

**Comment by pmario** [comment]
Yea it seems to be similar to: #282
The scrollbar is an overflow hidden problem and may be solved easily.

**Comment by pmario** [comment]
>I propose to remove the diagonal swipe effect, which IMO doesn't contribute constructively. Hopefully this will also solve (2) and (3)

no. there is no connection. It's not an animation problem. Its a css problem

**Comment by twMat** [comment]
Thanks for looking into it!

>no. there is no connection. It's not an animation problem. Its a css problem

Ok, should I split this issue into two separate ones?

**Comment by pmario** [comment]
probably. the proposal for the diagonal swipe is just a design decision and can be solved with different CSS. 

The scrollbar imo is a bug, but should be relatively straight forward to fix. 

the jumpy behaviour of the tiddler titles imo is only a problem on wide screens. The smaller the screen, the less problematic it seems for me. ... This fix seems to be more difficult at the first look

**Comment by pmario** [comment]
I did some tests. ... IMO instead of the "remove" element in the sidebar animation we would need a new "replace" animation. .... but I'm not sure yet, if we can detect when to use it.

**Comment by Jermolene** [comment]
Hi @pmario apologies for the late response: you are correct, the problem is that the current classic story view treats a tiddler transitioning between edit and view modes as being different tiddlers leaving and entering, and doesn't recognise a distinct "replace" animation.

It's the number 2 issue I'd like to fix with the classic storyview; number 1 is that I really miss the TiddlyWiki Classic animation that zooms from the link to the final resting place of the tiddler in the story river.

**Comment by pmario** [comment]
>Hi @pmario apologies for the late response: you are correct, the problem is that the current classic story view treats a tiddler transitioning between edit and view modes as being different tiddlers leaving and entering, and doesn't recognise a distinct "replace" animation.

I had a look at the code and it seems to be very hard to detect, if "replace" or "add" should be used. IMO when animation starts, this info is already lost. But I may be wrong here.

**Comment by Jermolene** [comment]
@pmario I was thinking of detecting the special case of a tiddler being replaced by its draft, or vice versa. We'd have to shift the animation itself to happen inside the (recently added) `storyview.refreshEnd()` method.

**Comment by pmario** [comment]
I think, the problem isn't the `storyview` ... It's the jumpy behaviour in the sidebar. Where it removes the link. 

The gif shows it.

**Comment by twMat** [comment]
>number 1 is that I really miss the TiddlyWiki Classic animation that zooms from the link to the final resting place of the tiddler in the story river.

This was a (very!) important touch to catch my attention for TW when I first stumbled over it ca 2006. (*"What? How did the [story river] already know I was going to open that tiddler!?"*) However, the old animation was *from* the link to the river, and as you *opened* the tiddler, not when you closed it. Critical difference IMO.

IMO, the only animated *direction* that makes sense when *closing* is - if anything! - *inwards* like shrinking or folding. An exception might be some "user-swiped" direction.

**Comment by Jermolene** [comment]
> However, the old animation was from the link to the river, and as you opened the tiddler, not when you closed it. Critical difference IMO.

I'm not sure what you mean here. I was saying that I would like to improve the animation for navigating to a tiddler so that something animates from the link to the open tiddler. It sounds like you think that I was suggesting changing the animation for closing a tiddler.

> IMO, the only animated direction that makes sense when closing is - if anything! - inwards like shrinking or folding. An exception might be some "user-swiped" direction.

Sorry, I'm still confused! It sounds like you're suggesting that the animation for removing tiddlers from the story should be changed, is that right?

**Comment by twMat** [comment]
Either we're both in agreement here or my OP has not been clear enough:

My OP is only about the animation for *closing/removing* the tiddler in the river (and title in sidebar). This is why I commented that your reference to the (wonderful) animation for opening a tiddler in TWC was not quite relevant.

Or do I misunderstand something?

**Comment by Jermolene** [comment]
OK @twMat. For me, improving the navigation animation is a more important improvement than changing the "replace" animation.

**Comment by pmario** [comment]
@twMat ... Latest version seem to be better. Espcially the "Open" sidebar animaion is gone. So no scrollbar action anymore. ... No sure if we need to keep this one?

Browser scrolling / animaiton performance has imporoved for me too. using latest FF

**Comment by twMat** [comment]
@pmario - yes much has been cleaned up. I'm still unsure why there has to be a left side-swipe when a tid is closed (as opposed to, say, a zoom out or a fade out) but I guess that's an intentional decision.
Thanks for bringing this and all the other stuff to attention.
