### ISSUE TITLE
Save tid should cleanse river from multiple or missing instances

### ISSUE THREAD

**Issue by twMat** [Jermolene/TiddlyWiki5#2381]
[Low importance]

Two illustrations of what I think would need pretty much the same solution:

**Case 1**: a tiddler, say GettingStarted, is open in tiddler river. Create a new tid titled likewise. After saving (i.e overwriting), *two* instances of this new GettingStated are displayed.

**Case 2**: Editing an existing tiddler, say Draft of 'A'
...then clicking tiddler link for same tiddler A in the sidebar so it opens parallel to the draft...
...then changing the title in the draft into, say B, and saving...
...results in showing the new tiddler B but also *"missing tiddler A"*.

To display (case 1) two instances of one tiddler and (case 2) a missing tiddler - this is more confusing than informative.

**Proposal** Saving a tiddler should also cleanse river from multiples or "missing-because-of-just-renamed" tiddlers.

**Comment by pmario** [comment]
probably dupes of #44 and #45

**Comment by twMat** [comment]
>probably dupes of #44 and #45

Hm, they do in deed seem close butI would think there is a critical difference in that those issues are about *edit mode* but I'm talking about effects *after* the tiddlers are saved. I would think it is easier to "clean up" in the saving process than during edit. Any thoughts on this?

**Comment by Jermolene** [comment]
Hi @twMat I think the problems you point out are bugs. The logic concerned lies in navigator.js; you may want to have a look at it. There's a lot of the high level logic of TiddlyWiki expressed in that file, and the fixes needed here would be pretty good jumping off points if you planned to work towards a pull request.............

**Comment by twMat** [comment]
Sure, I'll take a look.
