### ISSUE TITLE
Link to local images with relative path does not work

### ISSUE THREAD

**Issue by somenxavier** [Jermolene/TiddlyWiki5#2397]
This
```
[img[./media/favicon.ico]]
```

does not work. It works just absolute paths

**Comment by somenxavier** [comment]
It works without `.`

**Comment by Jermolene** [comment]
Hi @somenxavier 

Relative paths like that won't work when running under Node.js (see #1000), but works for me with the standalone edition:

<img width="1087" alt="screenshot 2016-04-25 08 48 23" src="https://cloud.githubusercontent.com/assets/174761/14777102/c6a08bee-0ac2-11e6-8ca0-8d3368e3cf9e.png">

**Comment by somenxavier** [comment]
`..` in path works, but not starting with `.`. In my case, `media/foo.jpeg` works but `./media/foo.jpeg` does not.

**Comment by Jermolene** [comment]
Hi @somenxavier apologies for the delayed response. With your `./media/foo.jpeg` example, what do you see if you perform the steps shown in the screen capture above:

# Include `[img[./media/foo.jpeg]]` in a tiddler
# Right click on the output and choose "inspect element"
# Ensure that the `<img>` tag is selected as in the screen capture above
# Type `$0.src` in the console window

What result do you get?

**Comment by somenxavier** [comment]
Close
