### ISSUE TITLE
[support] Is there any way of exporting all tiddlers to html static page?

### ISSUE THREAD

**Issue by somenxavier** [Jermolene/TiddlyWiki5#2398]
I have a web server. I want to export all my tiddlywiki (just one file which I edit in firefox) as static pages. Is there any way of doing that. If it's possible I want to not install npm....

**Comment by twMat** [comment]
Yes, check out the [docs here](http://tiddlywiki.com/#How%20to%20export%20tiddlers). If you find this sufficient please close the thread. Support issues are normally discussed on the [boards](https://groups.google.com/forum/?fromgroups=#!forum/tiddlywiki).

Hope this helps <:-)

**Comment by somenxavier** [comment]
Thanks a lot, for response. Yes, it's enough.
Sorry for discuss here...
