### ISSUE TITLE
Add support for TextReference to tm-notify

### ISSUE THREAD

**Issue by CodaCodr** [Jermolene/TiddlyWiki5#2403]
@Jermolene 

I was surprised that

`<$action-sendmessage $message="tm-notify" $param={{!!my-field}}/>`

failed.  Can support for TextReferences be added here? (pretty please?)

R

**Comment by pmario** [comment]
I did a test with `my-field: aaa`
tiddler `aaa` contains "some text"

If I click the button. It just works for me as expected. see: http://tiddlywiki.com/#WidgetMessage%3A%20tm-notify:[[WidgetMessage%3A%20tm-notify]]%20ActionSendMessageWidget

```
<$button>
<$action-sendmessage $message="tm-notify" $param={{!!my-field}}/>
Click me!
</$button>
```

**Comment by CodaCodr** [comment]
My bad... I should have been more clear.

Using your example, I want the text "aaa" to be displayed.  IOW, allow a TextReference to *supply* the text, not be a reference to a tiddler's title.

Reasoning: It's a waste of resources to use an entire tiddler for the purposes of a simple one-liner message.

Hope that's clear?

**Comment by pmario** [comment]
I think you should rename your issue title as a feature reqest for tm-notify http://tiddlywiki.com/#WidgetMessage%3A%20tm-notify 

-------------

>Reasoning: It's a waste of resources to use an entire tiddler for the purposes of a simple one-liner message.

TW uses tiddlers to store state on/off information, because tiddlers are in the gene of TW. 

IMO your desire to use a `message or text` parameter is valid, your reasoning is not ;)

**Comment by CodaCodr** [comment]
Well, it's clear that the documentation is correct: tm-notify expects a tiddler title.  That's how I discovered *why* it didn't work as I'd expected (and, as I said, surprisingly so).

I am asking that tm-notify support a TextReference, *directly*, not a tiddler *title* that indirectly (by implication) refers to a text field, *elsewhere*.  With this added, it would be a TextReference used as a reference to some text (QED).

TextReference -> message

TiddlerTitle (tiddler!!text) -> message

And I fail to see how choosing an alternative (additional) point in TW's hierarchy to implement a feature is invalid. But that's just me. ;)

**Comment by pmario** [comment]
I had a short look at the [source code](https://github.com/Jermolene/TiddlyWiki5/blob/master/core/modules/utils/dom/notifier.js#L36). It should be relatively straight forward to implement the desired functionality.

As you can see, the function does nothing, if the parameter that comes with the message is not a tiddler title. ... So we could just use the parameter and display it as a text 

but

This would be backwards incompatible. Which is a 100% no-go for Jeremy. 

There seems to be an `options` parameter too, which imo isn't documented and probably not really used atm. I'll have a closer look. ....

-------
@Jermolene 
The proposal atm is: For consistency, the `tm-notify` message should allow an additional parameter similar to [tm-modal](http://tiddlywiki.com/#WidgetMessage%3A%20tm-modal). eg:

```
<$action-sendmessage $message="tm-notify" text="some text"/>
or
<$action-sendmessage $message="tm-notify" text={{!!some-text}}/>
```
If `$param` is set, it takes precedence. 
If `$param` is undefined, text will be used.
If both are missing ... do nothing.

**Comment by Jermolene** [comment]
Hi I think the most consistent way of enhancing `tm-notify` would be to treat it the same as `tm-modal`; that means that additional parameters would be passed as variables to the modal.

@CodaCodr with that enhancement in place, you could create a notification template tiddler that then, say, does something like `<$view field=<<my-field>>/>`. Then you'd create a macro for invoking the notification, passing the approach value for the variable `my-field`.

**Comment by Jermolene** [comment]
Thank you @pmario
