### ISSUE TITLE
color field not updated properly in editTemplate

### ISSUE THREAD

**Issue by CodaCodr** [Jermolene/TiddlyWiki5#2409]
I have this macro:

```
\define new-group-tag-pill(grp)
<$button class="tc-btn-invisible tc-tag-label new-group-label">
<$action-sendmessage 
  $message="tm-new-tiddler"
  $param="$:/.rgt/prompts/template/new-group-tag"
  tags="z-prompts"
  title="New $grp$ Group Tag"
  color="#f00"
  group=$grp$
/>
{{$:/core/images/star-filled}}</$button>
\end
```
The color field is copied to the newly created tag tiddler as specified such that the tag appears red when the tag itself is rendered in the TW UI.  However, the color field in the tag tiddler (when viewed through the editTemplate) is not populated - it's defaulting to the black setting.  

It's interesting that saving the created tag tiddler does not change the red color either -- so it's certainly being assigned correctly internally (just viewing via the edit template is "wrong").

**Comment by Jermolene** [comment]
Try setting the `color` field to `#ff0000`; as I recall it, browsers are fussy about the RGB format they understand for the `<input type=color>` element.

**Comment by CodaCodr** [comment]
Yep, found that.  For the record:

`color: "red"` fails
`color: "#f00"` fails
`color: "#ff0000"` works

Thanks

**Comment by CodaCodr** [comment]
And for ultra-completeness:

`color: {{tiddler-title/$arg$!!field-name}}` works

Which is, you know, *gold* :)
