### ISSUE TITLE
Editing a missing tidder creates a 'draft of' tiddler with an undefined text field

### ISSUE THREAD

**Issue by buggyj** [Jermolene/TiddlyWiki5#2412]
First reported here (causing an error in the markdown plugin):
https://groups.google.com/forum/#!topic/tiddlywiki/XvK9Bc-WW4Q

Reproduce:
go to tiddlywiki.com and create a link to a non-existing tiddler from another tiddler, then click on the link thus creating a 'missing tiddler' in the story/river. Click the 'pen' icon to edit, change the type to application/json. In the preview 'undefined' is seen.

Cause:
When a new tiddler is created by editing the 'phantom' tiddler (shown as 'missing' in the story) the navigator assumes that the tiddler already exists and reuses the (null)tiddler with that tiddler name. 

Note that this causes a 'red box' if you change the type to text/x-markdown (with the plugin installed), so is not a trivial error.

**Comment by oskapt** [comment]
I'm the original reporter of this to the group. I'm happy to test or help out in any way.

**Comment by Jermolene** [comment]
Thanks @oskapt @buggyj
