### ISSUE TITLE
Nest/Wrap style definitions with tc-tagged

### ISSUE THREAD

**Issue by twMat** [Jermolene/TiddlyWiki5#2424]
I wish to customize tiddlers via _nested_ styles like so

```
.tc-tagged-foo {
   {{stylesheet1}}
   {{stylesheet2}}
}
```

where those internal `stylesheetx` are stylesheet tiddlers in themselves.

This would simplify styling tiddlers and would allow _reusing_ existing styles, even from non-tiddly contexts, rather than the current situation where one must _copy and re-write_, each single definition to prepend it with `tc-tagged-`.

Note: This type of nesting is not possible with vanilla CSS but is a basic and prominent feature in many CSS frameworks, and for good reason.

**Comment by Jermolene** [comment]
Hi @twMat have you tried it? It should work, if you've got the transclusion parse rule switched on.

**Comment by twMat** [comment]
@Jermolene  - thanx for fast reply!

>transclusion parse rule switched on

I'm not sure what that means, I can't find anything relevant under Ctrlpanel>Advanced>Parsing so maybe you mean something else? Here's a [test case](http://tc-tagged-nesting.tiddlyspot.com/) to illustrate what I'm trying.

**Comment by twMat** [comment]
Could it be that it currently only work if the transcluded tiddlers contain only the "attributes+values" rather than the full definitions?

**Comment by buggyj** [comment]
you could have it defined the other way around:
in mycol.text:: .tc-tagged-<<currentTiddler>> {color:cyan;}
then in tctag.text::{{||mycol}}

**Comment by twMat** [comment]
@buggyj - I appreciate your reply but I'm not sure I understand. Is this what you're suggesting;

```
title: tctag
text: {{||mycol}} {{||mybg}} ...etc
```

```
title: mybg
text:
.tc-tagged-tctag {background:yellow;}
.tc-tagged-tctag:hover {background:red;}
```
etc?

This is not very useful because one has to rename every style definition into "tc-tagged-tctag" and one would have to add a "tc-tagged-<tag>" to each definition for every new tag. 

Or do I misunderstand your kind suggestion?

**Comment by Jermolene** [comment]
Going back to the OP, transclusion in stylesheets works just the same as in wikitext. In other words, the stylesheet processor just sees the text after the transclusions have been performed. So, of course the text transcluded by your `{{stylesheet1}}` must be syntactically valid in CSS to appear within a style definition.

**Comment by twMat** [comment]
@Jermolene , thanks for replying and you're right of course - it yields invalid resulting syntax - but this is why I make the request. Since everyone is forced to apply the very *special* definition ".tc-tagged..." for tiddler styling, it makes sense to simplify its use. And I understand e.g Less [features nesting](http://lesscss.org/features/#features-overview-feature-nested-rules) like this, and is also js based.

However, that particualr OP "syntax" was just an example. Here are other imaginable variants to put into a Stylesheet; 
 
```
.tc-tagged-... {
   <<tc-tagged "stylesheet1">>
   <<tc-tagged "stylesheet2">>
}
```
or 

```
<<tc-tagged
   {{stylesheet1}}
   {{stylesheet2}}
>>
```

I could probably create a halting macro based on pure wiki components for this (a listwidget with lots of `splitbefore` and that cannot handle deviations well) but given the **imporant role of tc-tagged**, I think a real solution is both better and justified in core.

The above presumes the whole "tc-tagged" concept for styling a tiddler. A much more elegant UI would be a *style field* used like so: `style : stylesheet1 stylesheet2`. The style of a tiddler is "meta-data" as much as e.g the color field.

**Comment by pmario** [comment]
The transclusion at your test site works fine. It's just the CSS that's wrong. 

If you inspect (F12 browser debug tools) your tidddler, you'll see, that the browser gets the CSS rules assigned. But the parser invalidates them so they are ignored.

You can't nest CSS code that way. 

see: http://tc-tagged-nesting.tiddlyspot.com/#tctag

```
.tc-tagged-tctag { 
  .mybg {background:yellow;} 
  .mybg:hover {background:red;} 
  .mycol {color:cyan;}
}
```

If you copy paste the above text into a linter see: http://csslint.net/ you'll see, that there are errors

If you fix your `tctag` tiddler

```
.tc-tagged-tctag  {{mybg}}
.tc-tagged-tctag  {{mycol}}
```

and your `test` tiddler. 

```
<div class="mybg" >Heyo</div>
```

your examples work just fine.

**Comment by pmario** [comment]
There's still a problem with the `{{mybg}}` transclusion. It may not do what you expect. ... but it creates valid CSS

**Comment by twMat** [comment]
@pmario - yes, the transclusion works and the CSS does not because vanilla CSS does not permit this syntax. I already know this perfectly well (but thanks anyway!)

**My (actual) request is to be able to use a stylesheet (-tiddler) to simply style another tidder**... but without having to manually mess around with tc-tagged for each definition. I want us to be able to simply find cool styles on the web, copy them to a stylesheet tiddler and then apply it to the current tiddler with the click of a tool button.

...as I've attempted to implement here: [Style Button](http://stylebutton.tiddlyspot.com/)

As you'll note it is not ready for release yet but I think the idea should be clear if you play around with it. Please don't miss the example given via the tiddler "Isse with multi-definition styles". CSS is pretty powerful and can IMO take us towards the broader vision of erasing the likely impression that a tiddler is pretty much a digital "post-it note" - where it could (should?) really be *any* chunk of information. In the example I bring up there, the tiddler *is* a table. @inmysocks did a demo some time ago where tiddlers were svg objects (not sure I express that exactly correct). My point, here, is just that CSS'ing a tiddler should be super easy for the user, so we can take advantage of what CSS offers. There's just so much cool stuff ;-)

So; I ask, what *can* we do? I noted that Less does feature nested CSS (and it's js!) so I'm thinking it should at least be theoretically *possible* also in TW. But, as noted in my last post; The above thoughts presume the whole "tc-tagged" concept for styling a tiddler. But why coudn't the

`<div class="tc-tiddler-frame tc-tiddler-view-frame tc-tiddler-exists   tc-tagged-..."  style="transition: none; opacity: 1;">`

...just accept a stylesheet (somehow) ? A macro(?) could traverse through a stylesheet and exxtract the definition names and put them into this div (somehow).

Thanks for engaging Mario. Your thoughts are very valuable!

**Comment by pmario** [comment]
OK. I think I do understand your usecase a bit better now. 

But I think the whole tc-tagged- mechanism is flawed by design and can't produce predictable results. That's why it shouldn't be used at all, at the moment. ... imo it's broken. We need to fix it first or even better **replace it with a mechanism that is designed for "user defined tiddler styling"** and don't stress a mechanism that wasn't designed for it. 

IMO that's one reason why you face a lot of problems, which make the proposed solutions more and more complicated instead of easier. 

reasoning: 

As you know CSS rules are interpreted by the browser from **right to left**. So if I have 
`class="tc-tagged-abc tc-tagged-bbb"` everything which is defined by `-abc` will overwrite stuff form `-bbb`

The problem now is, that the user can't see the order the styles are applied, because the tag list is sorted alphabetically. The `tags` field in the tiddler store is not sorted. It depends on the order the tags are created. .... 

So with a mechanism like this we simply can't produce reliable results. That's just an other problem we have here.

----------------

One more problem are tag titles. eg: if you tag a tiddler with "abc$%&" you get this class: `tc-tagged-abc%24%25%26`  IMO no user will ever get that right. ... 

IMO using tags for tiddler styling is wrong and causes problems now. I did file an issue about "tc-tagged- classes need escaping" #958 2 years ago.

-----------

There are several other open issues, that contain `tc-tagged`. All seem to have similar problems. ... 

So my proposal is, **we need to fix the underlying problem and stop to fighting the symptoms.** 

-----------

You know, I'm (no fan of hidden tags)[https://github.com/Jermolene/TiddlyWiki5/issues/1366#issuecomment-70085704]. IMO for a reason. 

Your "Style Button" test case: http://stylebutton.tiddlyspot.com/ contains hidden tags. ... Which for me just points out, that there is something wrong, that needs to be improved. (By the way, those hidden tags made me waste quite some time to understand the exact mechanism that your example uses. ... I should have read the whole explanation text first. So that's my problem ;)

**Comment by twMat** [comment]
Yupp... agree with everything you say.

But if no tc-tagged, what would be a realistic optional route to go?

...and keeping in mind that styling a tiddler is 100% end-user-territory so should have a friendly-and-not-quirky UI; Using //fields// is both minimal (no frills) and established practice for meta-data (like style identifiers) - and they're an excellent *intermediary UI* for some prettier front-end that manipulates the values (like my *Style Button* attempt).

(@Jermolene - please don't miss the **Note** I make towards the end of this post.)

Specifically, I'd like a (single) *style field* used like so:

1. `style : <one or multiple stylesheettiddlers>` 
Stylesheettiddlers might, or not, have to be tagged with `$:/tags/Stylesheet.`
This is superior in that a user could easily copy-paste stylesheets from the web. It is also true to tiddler philosophy in treating the tiddler as the smallest unit.

2. `style : <one or multiple CSS classes>`
This has the implementation advantage that the value could be directly transcluded into a `<div class="...">` 
I think it also allows control over the order of the classes, ref the problem you point out.  The user would, of course, still have to consider "css interpreted from right to left". (A construction like my Style Button could present the selected styles at top of the dropdown list in the order that the system reads them and the user could reposition them therein.)

3. `style : < "a combo of stylesheettiddlers and classes and styleproperties+values">`
I.e all three *kinds* of style identifiers. Some indicator woudl be needed to differentiate them, for example. An (extreme case) style field might look like
`style : $:/mystylesheet  {color:blue} .tc-styleclass-myclass`

4. ...or to omit the need to indicate *kind* of style identifier, there could be three individual fields:
`stylesheets : styletiddler1 styletiddler2 ...`
`styleclasses : class1 class2 ...`
`styleproperties : color:blue; background:pink; ...`

**Note**: For the tiddlers outer div, there are already both a `class` and a `style` property defined so I'm thinking it should not be too difficult to implement something that just takes the tiddlers `styleclasses` field and `styleproperties` field and injects their values there.

<hr>
Other UI routes, IMO too quirky from an end-user standpoint, might be:

* tiddler-local macrocalls
* a pragma rule (?) `\style`, again with either of the three style identifier *kinds* 

<hr>
@pmario - sorry for the time you spent on my little hide-the-tags trick ;-)

**Comment by pmario** [comment]
@twMat ... Having [data-tags]-styling in place. Do we still need this issue?

**Comment by twMat** [comment]
@pmario , given your new styling additions and because I've kind of lost the point with the OP I'm closing. Who knows, might reopen one day.
