### ISSUE TITLE
Convention for formatting widget calls to avoid extraneous spaces while retaining readability.

### ISSUE THREAD

**Issue by rubaboo** [Jermolene/TiddlyWiki5#2429]
Can we start eliminating space characters systematically by adopting a code formatting convention? (and replacing them with margin where visual separation is desirable).
I can start submitting as soon as we agree on a format.

See  #2171 for background.

Here is another example:
![screenshot_2016-05-08_16-37-49](https://cloud.githubusercontent.com/assets/212368/15101118/8126b708-153c-11e6-89d2-e96c8fb49314.png)

**Comment by nameanyone** [comment]
How do you like this, for example (from $:/core/ui/EditTemplate/body/editor):
```
<$edit

  field="text"
  class="tc-edit-texteditor"
  placeholder={{$:/language/EditTemplate/Body/Placeholder}}

><$set

  name="targetTiddler"
  value=<<currentTiddler>>

><$list

  filter="[all[shadows+tiddlers]tag[$:/tags/EditorToolbar]!has[draft.of]]"

><$reveal

  type="nomatch"
  state=<<config-visibility-title>>
  text="hide"
  class="tc-text-editor-toolbar-item-wrapper"

><$transclude

  tiddler="$:/core/ui/EditTemplate/body/toolbar/button" mode="inline"

/></$reveal></$list></$set></$edit>
```

Very readable and produces smaller html output by eliminating newlines.

**Comment by Jermolene** [comment]
Hi @nameanyone yes, extraneous spaces are definitely a problem, and that looks like a reasonable approach for avoiding them while retaining readability.

For clarity, the uneven spacing in the editor toolbar is intentional; it's intended to group together related buttons.

So please do go ahead, many thanks!

**Comment by nameanyone** [comment]
> the uneven spacing in the editor toolbar is intentional

Yes, that is clear. Thank you.

**Comment by pmario** [comment]
@rubaboo ... Your PR got merged. I think we can close this one.

**Comment by rubaboo** [comment]
Sure, thanks. Hopefully I'll submit more PRs of this kind, still see spaces, in the SideBar for example.

![image](https://user-images.githubusercontent.com/212368/40622504-d1ff4ed8-6256-11e8-9b48-efda438b2035.png)
