### ISSUE TITLE
Zoomin view order is odd when closing tiddlers

### ISSUE THREAD

**Issue by giffmex** [Jermolene/TiddlyWiki5#243]
Behavior is odd when closing tiddlers in zoomin view. One would expect and desire that closing a tiddler would take the user back to the previous tiddler opens. Instead, closing tiddlers appears to take the user to the first tiddler opened, and if one has several tiddlers open, one must tunnel down in order to reach the tiddler that was opened prior to the closed tiddler.

I realize that the Open tab is an alternative way to get to the desired tiddler, but that assumes the user has that tab open and uses that method to navigate. 

If possible, it would be ideal that in zoomin view, closing a tiddler will take one to the top of the previously opened tiddler.

**Comment by pmario** [comment]
I did a test with 5.1.8-prerelease and it has the exact behaviour described in the desired behaviour of the OP. So imo this issue can be closed.

**Comment by Jermolene** [comment]
@pmario this isn't actually fixed. The current behaviour when closing a tiddler in zoomin story view is to move to either the previous or, if not present, the next entry in the story list. Some of the time that's reasonable, but not always, and especially not if you've been navigating between tiddlers.
