### ISSUE TITLE
Shift-Ins in the editor

### ISSUE THREAD

**Issue by rubaboo** [Jermolene/TiddlyWiki5#2452]
Shift-Ins does not paste clipboard. Ctrl-V does. Observed in the current release of Firefox on Windows. See discussion https://groups.google.com/d/msg/tiddlywiki/GlsruQyPOag/02j2NR2CBQAJ.

**Comment by pmario** [comment]
@Jermolene .. SHIFT-Insert works for me in FF windows 11 and Edge win 11 ... IMO can be closed

**Comment by Jermolene** [comment]
Thanks @rubaboo @pmario
