### ISSUE TITLE
AdvancedSearch/Filter needs more visible buttons

### ISSUE THREAD

**Issue by twMat** [Jermolene/TiddlyWiki5#2464]
$:/core/ui/AdvancedSearch/Filter

With the additional buttons in the coming 5.1.12, the button size and subtle colour needs to be changed for increased visibility.

**Comment by Jermolene** [comment]
Hi @twMat which additional buttons are you referring to? I don't think there's any additional buttons in the advanced search tiddler. Are you just suggesting that the advanced search buttons be restyled to match the editor toolbar buttons?

**Comment by twMat** [comment]
Sorry for being unclear; I am referring to that the buttons seen when you enter something in the search filter are very small and faint;
![tabort](https://cloud.githubusercontent.com/assets/4534056/15582131/b96663fc-236f-11e6-8db9-22f3344649ab.PNG)

**Comment by danielo515** [comment]
I totally agree. They are even harder to reach on mobile
