### ISSUE TITLE
Text editor can not be resized in prerelease

### ISSUE THREAD

**Issue by danielo515** [Jermolene/TiddlyWiki5#2470]
Hello.

Despite the new toolbar bar is quite useful, it comes with an uncomfortable consequence: you can not resize the editor text area. If you do you it will trigger the iframe navigation bars and you will end with the same size for the text area but with two horrible navigation bars. 

This can be a minnor issue for many, but I usually feel constraint by a small text area, so I like the ability to extend it.

**PD:** I just noticed that Github has implemented a toolbar also, and it is not using iframes. Seems that we are on the editor toolbars era!

**Comment by Jermolene** [comment]
Hi @danielo515 

> you can not resize the editor text area. If you do you it will trigger the iframe navigation bars and you will end with the same size for the text area but with two horrible navigation bars.

I've noticed the same thing, but didn't think it mattered given the way that TiddlyWiki automatically resizes the textarea to fit the content. What are the situations where you want to resize it manually?

> I just noticed that Github has implemented a toolbar also, and it is not using iframes

They don't need to use an iframe because they can easily preserve the textarea selection status when a toolbar button is pressed. With TiddlyWiki's more generic architecture there's nowhere to store the status.

**Comment by danielo515** [comment]
Hello @Jermolene 

> I've noticed the same thing, but didn't think it mattered given the way that TiddlyWiki automatically resizes the textarea to fit the content. What are the situations where you want to resize it manually?

It is a matter of taste. The default size of the text area is too small for my liking, and I want to make it bigger just to feel better. Is like drawing in a full piece of paper vs a small piece of paper, even if thepaper gets bigger as you need it.

In fact, the fact that tiddlywiki resizes the text area automatically also annoys me a bit. Usually there is a minimum and a maximum size that a text area should have to be comfortable to me.

Not a major problem, just wanted to point it out.
Regards.

**Comment by Jermolene** [comment]
>  The default size of the text area is too small for my liking, and I want to make it bigger just to feel better

There is a `minHeight` attribute on the edit widget, but there is no user interface for setting it globally.

**Comment by danielo515** [comment]
But can be set globally then? Despite the user interface. I'll check the code

**Comment by Jermolene** [comment]
`minHeight`is set via a JS constant at the moment. We'd need a pull request to instead pull it out of a settings tiddler.

**Comment by Crazor** [comment]
@danielo515 Did you look into this any further?

**Comment by danielo515** [comment]
Dear @Crazor, no I didn't 
Right now you can set the height manually within the toolbar, don't remember how

**Comment by pmario** [comment]
IMO have a look here: http://tiddlywiki.com/#EditTextWidget
