### ISSUE TITLE
Table-of-Contents macro crashes on recursive loops

### ISSUE THREAD

**Issue by yuzijie** [Jermolene/TiddlyWiki5#2472]
Hi, I have noticed that if you put an “Examples” tag on the “HelloThere” tiddler and click through the table of contents on the sidebar, it will crash tiddlywiki easily after you click “HelloThere” again.

I understand the reason why it happens like that, but I would like to see an option for Table-of-Contents macro to limit the number of levels it can trace.

Currently, all tiddlers that are tagged with tiddler A are shown under tiddler A in the TOC tree. Inspired by the “toc-link” field, it will be really helpful for organizing tiddlers if there is another field in the parent tiddler, e.g. “toc-filter”, that can **ignore** some child tiddlers in the hierarchy using filters. For instance, ignore tiddlers with certain tags.

**Comment by Jermolene** [comment]
Hi @yuzijie 

> I understand the reason why it happens like that, but I would like to see an option for Table-of-Contents macro to limit the number of levels it can trace.

The implementation would be easier if we just detected and disabled recursive loops (ie the limit would be 1).

> Currently, all tiddlers that are tagged with tiddler A are shown under tiddler A in the TOC tree. Inspired by the “toc-link” field, it will be really helpful for organizing tiddlers if there is another field in the parent tiddler, e.g. “toc-filter”, that can ignore some child tiddlers in the hierarchy using filters. For instance, ignore tiddlers with certain tags.

That's an interesting idea. I'd be concerned about the performance impact because the TOC macros are already pretty slow. It may be best to fork them to create a variant with the new functionality.

**Comment by pmario** [comment]
should be fixed in 5.1.14 @Jermolene

**Comment by pmario** [comment]
@Jermolene ... bump!

**Comment by Jermolene** [comment]
Thanks @pmario
