### ISSUE TITLE
Tid TiddlerFields needs mention of "caption"

### ISSUE THREAD

**Issue by twMat** [Jermolene/TiddlyWiki5#2478]
Tiddler **TiddlerFields** [gitlink](https://github.com/Jermolene/TiddlyWiki5/blob/086506012d98e9db34c7d96dc27aea249a9bdbc8/editions/tw5.com/tiddlers/concepts/TiddlerFields.tid) needs mention of "caption" (field).

I wanted to write a pr but the `<<lingo>>` part made me unsure how to proceed. What, generally, should one do in pr's when there are undefined lingo parts? (A brief search on http://tiddlywiki.com/dev/ does not reveal this.)

**Comment by pmario** [comment]
https://github.com/Jermolene/TiddlyWiki5/blob/086506012d98e9db34c7d96dc27aea249a9bdbc8/editions/tw5.com/tiddlers/concepts/TiddlerFields.tid#L7

imo there is a lingo base definition.

**Comment by Jermolene** [comment]
Hi @twMat we don't use the `<<lingo>>` macro in the tiddlywiki.com documentation; it's used within the core UI to support translation.

**Comment by twMat** [comment]
@pmario Mario, yes to my surprise something did show up using the `<<lingo>>` marco.

@Jermolene - not sure what you mean but I (think) that I just posted a PR and you decide if it makes sense. If you see no pr from me, please alert me.

Thanx guys.
