### ISSUE TITLE
How to block editing on Node.js?

### ISSUE THREAD

**Issue by zedoul** [Jermolene/TiddlyWiki5#2482]
Hi,

I am running tiddlywiki5 on Node.js using Heroku (devtropes.herokuapp.com). Since I do not want to anyone to fix the content, I tried to find a way to block editing mode.

I would appreciate if someone let me know how to disable editing when it is running on the server.

Thanks

**Comment by sukima** [comment]
I'm guessing this request does not follow the ideals of TiddlyWiki. If I wanted such a feature I would look at different content management systems.

That said you could have the main page be the compile single html version where changes can only be saved locally and the node server in a sub-directory that is behind Basic HTTP auth so only you (with the password) can make server edits. This is a bit of a awkward workaround.

I found it better to run TW on my local computer to make edits then build the static HTML file and ftp that to my webserver.

**Comment by zedoul** [comment]
@sukima OK

**Comment by tobibeer** [comment]
I think these are definitely goals highly worth pursuing, eventually:

1. a dedicated read-only mode vs. the full blown (current) author mode
2. basic auth to switch from read-only to author-mode

Not sure what other tickets already exist to address those requirements or whether there are any plans on tackling that on the core level. I mean, it's not like a full blown multi-user environment is the goal, with user management and registration, but rather just an ability to safely define login credentials and have them take effect.
