### ISSUE TITLE
Tags in edit mode should use `contrastcolour` macro

### ISSUE THREAD

**Issue by braykov** [Jermolene/TiddlyWiki5#2483]
I have a tag and in tag manager I gave it the colour yellow.
Here is how the tag looks like in different areas:
* in the tag manager - color is yellow, text color is black
* on the tiddler in view mode - color is yellow, text color is black
* in the tiddler in edit mode - color is yellow, text color is white!!!

So only when editing a tiddler, the tag is unreadable.

**Comment by Jermolene** [comment]
The problem is that the rendering of tags in edit mode doesn't currently use the `contrastcolour` macro, which is the thing that selects the foreground colour with the best contrast for the tag pill colour.

**Comment by gernert** [comment]
@Jermolene 
I get the impression it does not work correctly. See also the discussion https://groups.google.com/d/msg/tiddlywiki/0YhVJ39w5sI/U6-PSy88BgAJ
