### ISSUE TITLE
resizable textarea in preview mode

### ISSUE THREAD

**Issue by rcrath** [Jermolene/TiddlyWiki5#2486]
When working on a longer tiddler, often times the textarea view and the preview mode are different to the extent that the preview dose not show the area visible in textarea at all.  Easy way, I think: make textarea resizable horizontally in preview mode, which would also adjust the flow of the preview.  Harder way (I think) have preview scroll to always align with cursor in textarea (would involve floating the preview window or something like that though.  A simple drag for width on the textarea would be great.  

A partial workaround is to collapse the sidebar when working in preview mode, which keeps things visible a little longer due to wider areas of both preview and textarea.

**Comment by Jermolene** [comment]
Hi @rcrath

> When working on a longer tiddler, often times the textarea view and the preview mode are different to the extent that the preview dose not show the area visible in textarea at all.

The editor is radically improved in the upcoming 5.1.12 release; you an see a preview here: http://tiddlywiki.com/prerelease.

The problem you're raising still exists, but is a little ameliorated when using the option to have a fixed height for the text editor. It would be better still if the preview panel scrolled independently.

> Easy way, I think: make textarea resizable horizontally in preview mode, which would also adjust the flow of the preview.

That would be quite a neat solution. There's currently no support for draggable UI elements, but it's something that would be useful in a few different places.

> Harder way (I think) have preview scroll to always align with cursor in textarea (would involve floating the preview window or something like that though.

That would be great, but again there's no easy way to implement it at the moment.

**Comment by rcrath** [comment]
ok.  THanks.  Will close in lieu of the new version coming up.
