### ISSUE TITLE
Filtered Etag header on putSaver probe response causes crash

### ISSUE THREAD

**Issue by koivunej** [Jermolene/TiddlyWiki5#2487]
Version: 5.1.11

I've made a crude attempt at packaging TiddlyWiki5 as a sandstorm.io app and got a new wiki launched. Due to design of sandstorm.io the http responses sent by TiddlyWiki nodejs server are proxied and this proxy currently loses Etag headers on "204 OK" response sent to the initial putSaver probe which I think was introduced in #2290.

Missing Etag header from response causes `TiddlyWebAdaptor.prototype.parseEtag` being called with `null`, which causes TypeError on trying to invoke `indexOf("/")` on `null`. This exception is uncaught and we end up in `window.onerror` handler and the "Internal Javascript Error" messagebox.

While the _Internal Javascript Error_ messagebox is informative and describes the situation to the user, I report this as a bug because:

1. I think there's some error handling built in to the probe already that is not getting used here because the existence of header is not checked
2. Closing the "Internal Javascript Error" and going through the default GettingStarted document about verifying that syncing works only seems to work: there's no follow up error reported if you create a new tiddler, it just won't get saved

The sandstorm.io issue is being tracked as https://github.com/sandstorm-io/sandstorm/issues/2160.

Full async stacktrace from chromium:

```
tiddlywebadaptor.js:299 Uncaught TypeError: Cannot read property 'indexOf' of null
TiddlyWebAdaptor.parseEtag @ tiddlywebadaptor.js:299
$tw.utils.httpRequest.callback @ tiddlywebadaptor.js:173
request.onreadystatechange @ http.js:45
XMLHttpRequest.send (async)
exports.httpRequest @ http.js:63
TiddlyWebAdaptor.saveTiddler @ tiddlywebadaptor.js:161
Syncer.dispatchTask @ syncer.js:459
Syncer.processTaskQueue @ syncer.js:402
(anonymous function) @ syncer.js:381
setTimeout (async)
Syncer.triggerTimeout @ syncer.js:379
Syncer.processTaskQueue @ syncer.js:415
(anonymous function) @ syncer.js:356
setTimeout (async)
exports.nextTick @ utils.js:462
Syncer.enqueueSyncTask @ syncer.js:356
(anonymous function) @ syncer.js:230
$tw.utils.each @ VM241:6671
Syncer.syncToServer @ syncer.js:226
(anonymous function) @ syncer.js:38
exports.dispatchEvent @ wiki.js:123
(anonymous function) @ wiki.js:156
setTimeout (async)
exports.nextTick @ utils.js:462
exports.enqueueTiddlerEvent @ wiki.js:151
addTiddler @ VM241:7472
exports.startup @ info.js:43
$tw.boot.executeNextStartupTask @ VM241:8532
$tw.boot.executeNextStartupTask @ VM241:8536
$tw.boot.startup @ VM241:8489
(anonymous function) @ VM241:8638
$tw.boot.decryptEncryptedTiddlers @ VM241:7918
$tw.boot.boot @ VM241:8636
_boot @ VM241:8645
(anonymous function) @ VM241:8655
```

**Comment by Jermolene** [comment]
Hi @koivunej great to hear that you've been working on this. I'm a huge admirer of Sandstorm, and it's very exciting to have an integration.

I think the new `put.js` code introduced in #2290 may be a red herring here. It implements a "saver" that works with web servers that support WebDav. (A "saver" is a function that saves the entire wiki back to a server (or file system). It is used as an alternative to the client-server configuration (in which individual tiddlers are saved back to the server)). Assuming you're using the client-server configuration in the Sandstorm integration the put saver will never be used. The probe is successful if it receives a 204 response along with a header called "dav"; when executed in the client-server configuration I'd expect it to receive a 404 response.

If that's correct, we're left with the crash introduced in the TiddlyWebAdaptor when PUTting a new tiddler. The best way to deal with it isn't obvious: the client-server configuration won't work properly without etag headers, so all we can do is just to fail with an error message; and in turn the "Internal JavaScript Error" handler is the only means we've currently got to signal an error to the user. I guess the best we can do would be to trap the absence of the etag header and raise an error with a more useful description.

**Comment by koivunej** [comment]
> Hi @koivunej great to hear that you've been working on this. I'm a huge admirer of Sandstorm, and it's very exciting to have an integration.

Very encouraging to hear this! Quick detour to this integration: I'm currently looking at the ETag issue for sandstrom mentioned already. Unless I hit into more problems after that I should be able to have a single-user non-shareable package ready for broader testing. At that point I'll probably submit an issue and PR with the code should the end result makes sense to integrate source control and packaging wise. 

As a disclaimer, I am only learning sandstorm as I go so I am not sure about any of and do not know for example how integration to tiddlywiki5 development cycle could/should happen.

> Assuming you're using the client-server configuration in the Sandstorm integration the put saver will never be used. The probe is successful if it receives a 204 response along with a header called "dav"; when executed in the client-server configuration I'd expect it to receive a 404 response.

Yes, the client-server is what I'm trying to get working and I must've confused the probe then. WebDAV should be supported by sandstorm already on HTTP level at least, so it might even be simpler alternative for integration which needs to be tested once I get the client-server working.

> I guess the best we can do would be to trap the absence of the etag header and raise an error with a more useful description.

My first thought was that in the case of any other error than missing `ETag` header from the response there might already be better error message for the user. Being busy learning sandstorm I did not confirm this myself. However if there is none already, I do not think this ETag case requires more specific handling as this is rather special case.

So I guess we can close this issue as wontfix or something like that?

**Comment by Jermolene** [comment]
Hi @koivunej 

>  I should be able to have a single-user non-shareable package ready for broader testing

Excellent stuff.

> As a disclaimer, I am only learning sandstorm as I go so I am not sure about any of and do not know for example how integration to tiddlywiki5 development cycle could/should happen.

No worries, feel free to ask any questions here or on the developer mailing list.

At the very lease we should add a link to your work under the "Platforms" section of the tw.com table of contents.

> it might even be simpler alternative for integration which needs to be tested once I get the client-server working

The client-server configuration with synchronisation of single tiddlers is generally more efficient. Users with an investment in the standalone file configuration often prefer the option of saving the entire wiki, though.

> So I guess we can close this issue as wontfix or something like that?

Makes sense. I'll be looking forward to seeing your work.

**Comment by Aevit** [comment]
I have met the same problem.  

Here is my environment:  

> OS: OS X 10.13.2
> Browser: Chrome 65.0.3325.181
> node: v8.1.2
> npm: 5.3.0

![tiddlywiki_etag_null_error](https://user-images.githubusercontent.com/1490969/37901841-1d82346e-3125-11e8-809f-ede29c92ed8f.jpg)
