### ISSUE TITLE
Broken link on the "Community" tiddler

### ISSUE THREAD

**Issue by ssokolow** [Jermolene/TiddlyWiki5#2491]
"TiddlyWiki Groups" on the Community tiddler on http://tiddlywiki.com/ points to a nonexistant tiddler.

**Comment by Jermolene** [comment]
Thanks @ssokolow, funnily enough those links were just fixed a couple of days ago in the prerelease :)

http://tiddlywiki.com/prerelease/#Articles:Articles%20Examples
