### ISSUE TITLE
SyncMechanism tiddler is references but missing

### ISSUE THREAD

**Issue by ssokolow** [Jermolene/TiddlyWiki5#2492]
The SavingMechanism tiddler references the SyncMechanism tiddler but it doesn't exist.

(And I think that's been the state of things for at least six months. I remember being discouraged by running into that brick wall last time I decided to start learning how TW5 works.)

**Comment by Jermolene** [comment]
Hi @ssokolow thanks, this is one of the dangling bits left over from splitting out the developer documentation. It used to link to http://tiddlywiki.com/dev/#SyncAdaptorModules

I kept the SavingMechanism material in the main wiki because it has details that are relevant for wikitext users, while the sync mechanism material is entirely focussed on JS users.

**Comment by ssokolow** [comment]
Probably a good idea to make the existence of the developer wiki more clear.

I'd have started developing on TW5 well over a year ago if I didn't keep coming back to the root wiki to check for sufficient developer documentation, only to leave each time, assuming that it had been postponed due to lack of manpower. 

(In fact, I was just gearing up to bombard the mailing list with questions that wiki probably answers and the only reason I'm finally willing to implicitly commit to producing something buy publicly talking about it is that I finally have something I need done where implementing it acceptably with some non-TW5 thing would be more painful than learning how TW5 works by reading a ton of undocumented code.)

**Comment by Jermolene** [comment]
Hi @ssokolow 

> Probably a good idea to make the existence of the developer wiki more clear.

What would you suggest? It's currently documented under "Community".

> (In fact, I was just gearing up to bombard the mailing list with questions that wiki probably answers and the only reason I'm finally willing to implicitly commit to producing something buy publicly talking about it is that I finally have something I need done where implementing it acceptably with some non-TW5 thing would be more painful than learning how TW5 works by reading a ton of undocumented code.)

Please don't be afraid to ask questions here or in the dev group.

**Comment by ssokolow** [comment]
> What would you suggest? It's currently documented under "Community".

That would explain it. I'd usually poke around under Reference, conclude that this must be the extent of the (clearly very incomplete) developer docs and then turn to Community looking for the mailing lists. 

I'd suggest putting some sort of "You may also have been looking for..." link at the bottom of the "Reference" and "Customize TiddlyWiki" pages.

As for Community, I just generally have trouble with it for the following reasons:

* The design screams "feed aggregator to show off what the community has made" when what I'm looking for is "clear, categorized listing of how to communicate with the community" similar to the [rust-lang.org Community page](https://www.rust-lang.org/en-US/community.html).
* A layout consisting of two excessively narrow columns, using low-contrast blue-on-blue headings isn't very amenable to skim-reading.
* When people see "forums", they think software like phpBB, so that tab should either be renamed or focused by default to make it clear that it's using the pre-Internet meaning of the term. As-is, it's like storing your e-mail addresses in a file named "phone numbers".
* Aside from being grouped into Tutorials, Resources, Examples, and Articles, there's no categorization of the entries, so I usually end up losing hope after scrolling through too many entries that are either irrelevant to my goals or aimed at people who haven't gotten the general idea from playing around with TWc for several years.

> Please don't be afraid to ask questions here or in the dev group.

It's more that asking another human feels too much like I'm committing to produce something, since now other people know my intentions. (I'm already demotivated enough by self-jetlagging habit I'm fighting to break out of.)

**Comment by ssokolow** [comment]
To clarify one of my points about the Community tab, the problem is that I see "Community creations" and "Community communication" as being distinctly different categories because one is a list of official and semi-official communication channels with a high bar for entry while the other is a list of 3rd-party content which anyone can join as long as the content is relevant.

 (In the same way that I think it's insane and confusing for GNOME applications to put Preferences in the Edit menu because that menu is intuitively document-scoped, not application-scoped. Just because you "edit" preferences and you "edit" the document doesn't mean that they're the same conceptual token in the user's semantic network.)

Because of that, seeing what appears at first glance to be a Planet-style feed aggregator in the tab that's shown by default, combined with all but one tab reinforcing that fact, leads me to conclude I've taken a wrong turn and to look elsewhere rather than wasting my time on what is extremely likely to not contain what I want.

**Comment by ssokolow** [comment]
Also, even now that I *know* that the dev wiki is somewhere in the Community tab, I *still* can't seem to find it. The other half to the official documentation most definitely shouldn't be harder to find than 3rd-party links.

**Comment by Jermolene** [comment]
Hi @ssokolow thanks for the feedback. I've made some minor changes for the moment; I'll have to put off refactoring the "Community" section wholesale until after 5.1.12

* 8dece4b4f68deb4bd3628a0c1ffb856afc68bdc1
* dd1e213b528dbea9bcc4ad72726dc8a8a8c8c120
