### ISSUE TITLE
Contents of Markdown tiddlers are not saved under node.js

### ISSUE THREAD

**Issue by mihock** [Jermolene/TiddlyWiki5#2499]
After creating a Markdown tiddler under node.js, a file with the name of the tiddler (name_tiddler.md) is saved to the file system. The file itself, however, is empty, and after restarting tiddlywiki, the tiddler is not shown anymore. 

Tiddlywiki and Markdown parser version: 5.1.12
npm version: 2.15.8
Browers used: Firefox and Safari

**Comment by Jermolene** [comment]
Hi @mihock I can confirm that this is a bug under 5.1.12. I'm working on a fix and will make new 5.1.13 release shortly.

**Comment by Jermolene** [comment]
Fixed in #2504
