### ISSUE TITLE
.tid extension is added to file on each edit

### ISSUE THREAD

**Issue by znoxx** [Jermolene/TiddlyWiki5#2503]
I've updated filesystemadaptor.js from github. Currrently I have 5.1.12 from npm and this is only file update.
When I create a new tiddler, it is saved with .tid filename.
The  I restart node.js app and try to update the tiddler. It is updated/saved, but in folder I see:

`-rw-r--r-- 1 root root  167 Jul 19 11:15 Number_one.md.tid`
` -rw-r--r-- 1 root root  178 Jul 19 11:17 Number_one.md.tid.tid`

Second, after each restart of app, I see:
`-rw-r--r-- 1 root root  109 Jul 19 11:15 $__StoryList.tid.tid`
 `-rw-r--r-- 1 root root  138 Jul 19 11:17 $__StoryList.tid.tid.tid`
 `-rw-r--r-- 1 root root   42 Jul 19 11:18 $__StoryList.tid.tid.tid.tid`

Actual functionality is working, looks there is no data loss, but, well, it's pretty strange.

**Comment by sukima** [comment]
This is a bug and was introduced in commit https://github.com/Jermolene/TiddlyWiki5/commit/c4c7b1868c57f3fd2f6f72b9b127645327a91913 it seems.

To reproduce, save a tiddler and then kill the node server and restart it. It sees the existence of the previous file and appends a `.tid`.

Oddly, I thought this was managed in commit bf74d13d ([Line 131](https://github.com/Jermolene/TiddlyWiki5/commit/bf74d13df544e323066cde9a019cbf1855d3db04#diff-304453faeba2d7a772361746dc041c98R131)).

commit bf74d13d introduced the same notion with a `strEndsWith` utility function. So whoever works on this bug the logic could be extrapolated into a helper function:

```javascript
function addFileExtention(file, extention) {
  return $tw.utils.strEndsWith(file, extention) ? file : file + extention;
}
```

**Comment by sukima** [comment]
@Jermolene If you view this issue fixed it in Pull Request #2504

**Comment by znoxx** [comment]
@sukima, @Jermolene I've downloaded file from #2504 and replaced the file.
Issue looks like resolved

When to expect the new build in npm ? =)

**Comment by znoxx** [comment]
May be closed too fast, sorry.
