### ISSUE TITLE
tiddlyspot saving

### ISSUE THREAD

**Issue by drdnght** [Jermolene/TiddlyWiki5#251]
Internal JavaScript Error
Well, this is embarrassing. It is recommended that you restart TiddlyWiki by refreshing your browser
NS_ERROR_DOM_BAD_URI: Access to restricted URI denied

in the new alpha 17 when filling in the details under control panel -> saving

when blank it saves the file locally as expected, when details are filled in, (even when wrong details or correct I get this error)

tiddlyspot opens where I am, but I am behind a corporate firewall so could be relevant

**Comment by araujokth** [comment]
Hi all,

I am having the same problem reported above but for some reason the solution is not working for me. I am trying to setup a tiddlywiki on my own server following the instructions given here: http://tiddlywiki.com/static/Saving%2520on%2520a%2520PHP%2520Server.html 

In my server I uploaded the modified store.php and I verified that it was correctly uploaded.However, in step 5, when saving I get the same error message as reported above. I tried opening it with chrome, but it just says "Starting to save the wiki" but nothing happens after that.

One thing I found strange was that in "Saving" I get that "Backups" is set to	http://XXX.tiddlyspot.com/backup/ (where XXX = the name I set for Wiki Name) and I cannot see how this can be modified. I thought that that should point to a folder on my server instead, or?

Thank you all for the help!

**Comment by Jermolene** [comment]
Hi @araujokth the backup link is hardwired to tiddlyspot.com, but it's only provided as a convenience; you can navigate in your browser directly to your server if required.

As noted elsewhere, the initial upload won't work under Firefox, and must be done in Chrome. To diagnose the hang that you're seeing, try opening the browser developer tools on the network tab before navigating to tiddlywiki. You should be able to see the network requests generated by trying to save changes.

**Comment by grayeul** [comment]
One issue I had -- and browser debug was not terribly helpful to me, for 
some reason, was that I had to increase the maximum file upload size in 
the php configuration on the server.  Mine was setup (probably default) 
of 2M max, and the default TW5 file is bigger than that.

bob

**Comment by araujokth** [comment]
Hi @Jermolene and @grayeul. Thanks for the tips! 

@Jermolene, through the debug I was able to see what is happening and the issue is that for some weird reason I cannot access my server using Chrome (I get ERR_NAME_NOT_RESOLVED), but only Firefox and IE. Since I had always been using Firefox to access my server and the Tiddlywiki, I never imagined that this was the problem. Trying to check for a solution for this now.  Thanks again!

**Comment by Jermolene** [comment]
Great, @araujokth, glad you tracked it down.

**Comment by araujokth** [comment]
Hi again,

I have gotten the server to work but I am getting this error message and was not sure what could be done to fix it. Did this ever happened to any of you?

"XMLHttpRequest cannot load http://SERVERNAME/store.php. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'null' is therefore not allowed access."

**Comment by Jermolene** [comment]
Hi @araujokth does the error message give any further details beyond the text "Error while saving"? Again, it may be useful to look at the HTTP request in the browser dev tools. In particular, can you see what the response text looks like?

**Comment by araujokth** [comment]
in the dev tools what I get is:

 "saver-handler: $:/core/modules/utils/logger.js:30 saver-handler: Saving wiki with method save through saver upload"

and the "Error while saving" is a "pop-up" message in the browser which does not allow me to copy it.

**Comment by Jermolene** [comment]
Hi @araujokth can you try opening the "network" tab in your browser dev tools and then repeat the attempt to save. You should see an entry in the "network" tab that gives the details of the underlying network operation. For example, the image below shows the network tab when I save a standalone wiki to TiddlySpot.

![screenshot 2015-02-24 17 30 58](https://cloud.githubusercontent.com/assets/174761/6353654/f2ebd658-bc4a-11e4-9bab-36fe2a0381b3.png)
