### ISSUE TITLE
Lazy loading with node.js not working

### ISSUE THREAD

**Issue by guillefix** [Jermolene/TiddlyWiki5#2511]
As I said here: https://groups.google.com/forum/#!topic/tiddlywiki/uZmFE-oj6po I'm following the instructions to do this, by adding the `$:/core/save/lazy-all` option.

The tw loads with the metadata from the tiddlers. However, when I click on a tiddler it shows empty, or when I try `$tw.wiki.getTiddlerText("tiddler name")` it returns `null`.

Any idea why this may be?

**Comment by danielo515** [comment]
Hello @guillefix ,

I think I have found the root cause of this problem and I have posted an issue about it: #2514 
The fix is quite easy, but it requires an update of the core.

Regards.

**Comment by danielo515** [comment]
This has been fixed after closing #2514 and will be fine in the next release.
This ticket should be closed, but I also think that an emergency release should be made, this breaks almost all wikis that depend on a sync adaptor.

**Comment by tobibeer** [comment]
@guillefix, with #2514 merged into the core, please close this ticket (even if there's not been a new release yet).
