### ISSUE TITLE
Blocked plugin because version 0.9 is older than 0.8 ?

### ISSUE THREAD

**Issue by danielo515** [Jermolene/TiddlyWiki5#2516]
Why tiddlywiki does not recognises version 0.9 as a newer version than 0.8? 
Below you can see an evidence:

![image](https://cloud.githubusercontent.com/assets/2270425/17277509/ea10be4a-5744-11e6-8e80-a755499fe946.png)

plugin.info is quite simple:

```
{
	"title": "$:/plugins/danielo515/tiddlypouch",
	"description": "tiddlypouch for TiddlyWiki",
	"author": "Danielo Rodriguez",
	"core-version": ">=5.1.0",
	"list": "readme",
    "version": "0.9"
}
```

**Comment by pmario** [comment]
did you have a look at the created and modified fields. may be the problem comes from them?

**Comment by pmario** [comment]
code can be found here: https://github.com/Jermolene/TiddlyWiki5/blob/master/core/modules/upgraders/plugins.js#L54

here: https://github.com/Jermolene/TiddlyWiki5/blob/master/boot/boot.js#L346
and: https://github.com/Jermolene/TiddlyWiki5/blob/master/boot/boot.js#L365

you can debug it.

**Comment by tobibeer** [comment]
Possibly the parser always expects this version format:

major.minor.patch

Your version numbers do not provide a patch-level.

Possibly the regexp for the version number in

https://github.com/Jermolene/TiddlyWiki5/blob/master/boot/boot.js#L346

should be changed to something like:

```
^((\d+)(?:\.(\d+)(?:\.(\d+))?)?)(?:-([\dA-Za-z\-]+(?:\.[\dA-Za-z\-]+)*))?(?:\+([\dA-Za-z\-]+(?:\.[\dA-Za-z\-]+)*))?$
```

...making the minor or patch level optional

**Comment by pmario** [comment]
>...making the minor or patch level optional

not possible see: http://tiddlywiki.com/#TiddlyWiki5%20Versioning

**Comment by pmario** [comment]
@tobibeer good catch :)

**Comment by Jermolene** [comment]
TiddlyWiki tries to observe http://semver.org, which as far as I can tell does not permit the minor or patch numbers to be omitted.

**Comment by danielo515** [comment]
Just created #2574 to make this clearer.

Regards
