### ISSUE TITLE
tiddler fields loose '$' character at save 

### ISSUE THREAD

**Issue by pmario** [Jermolene/TiddlyWiki5#2517]
see: https://groups.google.com/forum/#!topic/tiddlywiki/I9bhXqn46wg

to reproduce: 

 - create a new tiddler with a field
 - eg: `test: $$asdf$$`
 - save
 - reload

one $ char is gone field is: `$asdf$` 
It also works with: `$$aaa` or `aaa$$`

try the value: `asdf$&` -> funny result because of js `string.replace()`

**Comment by pmario** [comment]
problem seems to be in the template: https://github.com/Jermolene/TiddlyWiki5/blob/master/core/templates/html-div-tiddler.tid#L7

and: https://github.com/Jermolene/TiddlyWiki5/blob/master/core/modules/widgets/fields.js#L79

**Comment by pmario** [comment]
see: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/replace#Description

**Comment by pmario** [comment]
pr incoming

**Comment by pmario** [comment]
@Jermolene .. any hints?

**Comment by stewils76** [comment]
This seems to still be an issue.  Just double checked to make sure.
Using 	5.1.13 and saving to tiddlyspot.
Error occurs in both Chrome and firefox on windows 7.

**Comment by pmario** [comment]
will be fixed in 5.1.14 just tested it with latest master.
