### ISSUE TITLE
syncAdaptor.isReady breaks backwards compatibility with all sync adaptors 

### ISSUE THREAD

**Issue by danielo515** [Jermolene/TiddlyWiki5#2522]
Making the method syncAdaptor.isReady mandatory (which has no error handling in case it doesn't exists) breaks backwards compatibility with literally all the sync adapters. For example :
https://github.com/wshallum/couchadaptor/issues/18#issuecomment-237170790

I though that retrocompatibility was one of the most important things to maintain after the reach of version 5.1.0 which is not considered beta anymore.

In my opinion core should ignore this method if it does not exist

**Comment by Jermolene** [comment]
Thanks @danielo515, that was an oversight. Fix coming up.

**Comment by danielo515** [comment]
Thank you @Jermolene! That was fast
