### ISSUE TITLE
Missing icon for 'fold-bar button'

### ISSUE THREAD

**Issue by gernert** [Jermolene/TiddlyWiki5#2525]
I can edit 'standard' (documentation) tiddlers and create a pull request.
When I try to do the same with 'code' tiddlers it looks like I am not allowed to edit and create a pull request.

Therefore a 'manual' pull request.
I propose to change:

```
title: $:/core/ui/Buttons/fold-bar
tags: $:/tags/ViewToolbar
caption: {{$:/language/Buttons/Fold/FoldBar/Caption}}
description: {{$:/language/Buttons/Fold/FoldBar/Hint}}

<!-- This dummy toolbar button is here to allow visibility of the fold-bar to be controlled as if it were a toolbar button -->
```

to:

```
title: $:/core/ui/Buttons/fold-bar
tags: $:/tags/ViewToolbar
caption: {{$:/core/images/chevron-up}}{{$:/language/Buttons/Fold/FoldBar/Caption}}
description: {{$:/language/Buttons/Fold/FoldBar/Hint}}

<!-- This dummy toolbar button is here to allow visibility of the fold-bar to be controlled as if it were a toolbar button -->
```

Although a dummy button, it needs an icon to be 'visible' for the user.

**Comment by Jermolene** [comment]
Thanks @gernert.

> I can edit 'standard' (documentation) tiddlers and create a pull request.
> When I try to do the same with 'code' tiddlers it looks like I am not allowed to edit and create a pull request.

Hmm, I'm not sure what's going on there, you should have equal access to all the files of the repo.

**Comment by gernert** [comment]
@Jermolene 
At http://tiddlywiki.com/

* When I edit GettingStarted, I can click 'edit this tiddler on Github' and I am redirected directly to the GettingStarted tiddler with an Edit button.
* When I do the same with $:/core/ui/Buttons/fold-bar, I am redirected to https://github.com/Jermolene/TiddlyWiki5/tree/master/editions/tw5.com/tiddlers. I tried searching for $:/core/ui/Buttons/fold-bar, found it but, did not see an Edit button.

May be I had to fork there? Anyway, not as easy as editing GettingStarted.
