### ISSUE TITLE
Page background color not showing through transparent background image

### ISSUE THREAD

**Issue by twMat** [Jermolene/TiddlyWiki5#2529]
[Minimal Test Case](http://bgproblem.tiddlyspot.com/)

The background colour is set by choosing a premade palette with dark bg. Image used as bg is a png with transparent parts. I was expecting the bg colour to be visible through the transparent parts of the png like is seen when the image is transcluded onto the colored tiddler body bg.

**Comment by Jermolene** [comment]
Thanks @twMat, fix upcoming.

**Comment by Jermolene** [comment]
@twMat I've uploaded a new prerelease for you to try out: http://tiddlywiki.com/prerelease

**Comment by twMat** [comment]
Wow, that was *fast*! :-) Thanks, it seems to work well there.
