### ISSUE TITLE
 [edit toolbar] excise selected text to new tiddler gives "old title 1" as tag

### ISSUE THREAD

**Issue by hchaase** [Jermolene/TiddlyWiki5#2531]
When you clone a tiddler and change the title from "old title 1" to whatever.

When you use **"excise selected text to new tiddler .."** and check the **"Tag new tiddler with the title of this tiddler"**, it will get the "old title 1" as tag, not the new title.

As the new title don't exist yet I can understand why it could be cumbersome to fix. Another solution could be to write a warning in the dialogue box.

![2016-08-09 15_17_13-hcs zettelkasten zettelkasten in the form of tiddlywiki a non-linear personal](https://cloud.githubusercontent.com/assets/2864323/17517605/65b5c1b6-5e44-11e6-943d-0eeb1c549557.png)

![2016-08-09 15_17_29-hcs zettelkasten zettelkasten in the form of tiddlywiki a non-linear personal](https://cloud.githubusercontent.com/assets/2864323/17517604/65b4cafe-5e44-11e6-8f96-0b0652acfb2b.png)

**Comment by sukima** [comment]
Any tiddler that is a **draft** is technically doesn't exist yet. Even tiddlers who's title is changed still technically doesn't exist till the save is done. Personally I would not expect the excise to work on draft tiddlers even existing tiddlers who's drafts were changes but not saved yet.

I can understand the confusion but the feature (IMHO) is working as designed. Perhaps better help text / documentation would fit this situation.

**Comment by hchaase** [comment]
> I can understand the confusion but the feature (IMHO) is working as designed. Perhaps better help text / documentation would fit this situation.

I think we agree. As I said: 
>  I can understand why it could be cumbersome to fix
If there are no objections I will update the doc
