### ISSUE TITLE
The Editor Toolbar Prevents Control Backspacing in Firefox

### ISSUE THREAD

**Issue by ghost** [Jermolene/TiddlyWiki5#2532]
When the editor toolbar is open in a Tiddler hitting Ctrl+Backspace does nothing in the editor window. With the toolbar closed it deletes a whole word as expected. Checking the box in the settings menu immediately enables or disables use of Ctrl+Backspace.

Ctrl+Backspacing in other text fields, like TiddlyWiki search bar are unaffected.

Version: 5.1.13
Browser: Firefox (does not affect Chrome, other browsers are untested)
OS: Windows 7 x64

-TCJ

**Comment by nameanyone** [comment]
Shift-Ins is another one: #2452.

**Comment by mdemoss** [comment]
I have the same problem, and I'm using the CodeMirror plugin as a work-around.

**Comment by henrikh** [comment]
I have just updated to Firefox 65 from the official release channel. The issue is no longer present at my end.

**Comment by Jermolene** [comment]
Thanks @henrikh

**Comment by pmario** [comment]
Hi, @ghost ... can you verify, that it works with latest FF 65. ... If yes please close the issue!

**Comment by pmario** [comment]
@Jermolene ... can you please close this issue?

**Comment by Jermolene** [comment]
Thanks @pmario @henrikh
