### ISSUE TITLE
Add mathematical operations to filter syntax

### ISSUE THREAD

**Issue by Jermolene** [Jermolene/TiddlyWiki5#254]
It should be possible to sum the values of a field from multiple tiddlers.

Something like:

```
title: Project Finances

[tag[expense]sum[cost]] --> 150
```

```
title: Expense A
tag:expense
cost:100
```

```
title: Expense B
tag:expense
cost:50
```

In general, is there (will there be) operators for (numerical) fields such as sum, average, greater than, less than, equal to, etc?

Just throwing out more ideas that come to mind:

```
title: Project Finances
Budget:200
expenseA:100
expenseB:50
expenseC:200
```

```
{{expenseA + expenseB}}  --> 150

or 

[title[Project Finances]sum[expenseA, expenseB]] --> 150

or 

[title[Project Finances]sum[fieldsearch[expense*]]] --> 350

or

[title[Project Finances]avg[expenseA, expenseB]] --> 75

or

[title[Project Finances]calc[Budget - sum[expenseA, expenseB]]] --> 50
```

Thanks to chishaku for the original suggestion:

https://groups.google.com/d/msg/tiddlywiki/cvwNcZqX3HY/zk7SMeTDvfEJ

**Comment by danielo515** [comment]
This feature is planned for anytime soon or should we use custom is for this?

**Comment by Jermolene** [comment]
Hi @danielo515 I don't have any immediate plans to add mathematics filters to TW5, but remain keen to do so. I'd be happy to discuss a pull request.

**Comment by AndyRazz** [comment]
Hi @Jermolene,
Been using TW since version 3 and like it a lot. I'm tentatively putting my hand up to have a look at this, or perhaps what you suggest here https://groups.google.com/forum/#!topic/TiddlyWiki/uIBhuGB7Oc8.
A

**Comment by Jermolene** [comment]
Thanks @AndyRazz! You might want to check out @EvanBalster's awesome Formula plugin:

http://evanbalster.com/tiddlywiki/formulas.html

https://groups.google.com/d/topic/tiddlywiki/7jtgYsV6iXE/discussion

**Comment by AndyRazz** [comment]
Thanks for pointing me in the right direction @Jermolene it looks perfect.

**Comment by pmario** [comment]
@Jermolene .... imo done by Evan: .... close?

See the Formula wiki for the latest documentation:  http://evanbalster.com/tiddlywiki/formulas.html
Report issues and view source GitHub:  https://github.com/EvanBalster/TiddlyWikiFormula
