### ISSUE TITLE
TW on Node forgets my images

### ISSUE THREAD

**Issue by LourensR** [Jermolene/TiddlyWiki5#2542]
I have TW on Node with lazyloading but since last release 5.1.13 my images do not show up anymore.
When I import a new image, it is visible but the next start image is gone.

Is there a setting which I should change?

On closer inspection it seems my pictures are white only.

![empty-image](https://cloud.githubusercontent.com/assets/21083377/17739723/52c599a2-6496-11e6-87bb-113f2297e17c.jpg)

**Comment by Jermolene** [comment]
Hi @LourensR I think this is the problem fixed in #2514, could you kindly check whether the problem still exists with the latest prerelease in 'master'?

**Comment by LourensR** [comment]
Yeah @Jermolene 
that did the job! thanks for your fast and personal support!
