### ISSUE TITLE
pluginreloadwarning.tid should be more configurable

### ISSUE THREAD

**Issue by danielo515** [Jermolene/TiddlyWiki5#2545]
I have to admit that I like a lot the idea behind pluginreloadwarning.tid, but it is too tied to the core implementation.

In my opinion, it should be more configurable, for example, displaying the message of certain tiddler. That way, plugins requiring a page reload could use the reload warning. 

It would be ideal if the core provides an interface to set the message and display the warning.

I'm curious about how it is triggered, I have searched across the entire wiki and I did not found it

**Comment by pmario** [comment]
have a loot at: `pluginreloadwarning.tid` https://github.com/Jermolene/TiddlyWiki5/blob/master/core/ui/PageTemplate/pluginreloadwarning.tid#L6

**Comment by danielo515** [comment]
Thanks @pmario 
You mean that it relies on TW filter and no JS logic is required here. Quite smart, but very unflexible.

**Comment by pmario** [comment]
kind of. `haschanged` imo is "js logic"

**Comment by Jermolene** [comment]
The language strings inside the plugin reload warning are already translatable, which I think is adequate configurability.
