### ISSUE TITLE
Camel case inside buttons should not be turned into a link

### ISSUE THREAD

**Issue by danielo515** [Jermolene/TiddlyWiki5#2546]
The issue is very easy to reproduce:

Go to tiddlywiki.com and create a tiddler with the following content:

```
<$button> MyAwesomeTiddler plus some text </$button>
``` 

You cas see how `MyAwesomeTiddler` text is clickable and you can open a tiddler named `MyAwesomeTiddler`  if you click on it. The main focus of a button is to be a clickable element, having another clickable  element inside is confusing.

This happens on chrome, not sure how other browsers handle click event shadowing.

**Comment by pmario** [comment]
```
<$button> ~MyAwesomeTiddler plus some text </$button>
```

done

**Comment by danielo515** [comment]
I was talking about the default behavior, but yes, it's doable that way.

**Comment by pmario** [comment]
>I was talking about the default behavior, but yes, it's doable that way. 

ok. let's say we change the behaviour. The effect would be, that I need to use 
`<$button> [[MyAwesomeTiddler]] plus some text </$button>`  to create a wikilink within a button. ... But this behaviour is completely inconsistent to the rest of the TW. .. while my solution is consistent.

**Comment by danielo515** [comment]
That was a very authoritative answer.
I admit that you are right, but I still finding odd that you can have links inside buttons. I'm not talking about the way of generating them, I mean that I find it totally odd on any situation. But at the end, Tiddlywiki is all about customization and options, so maybe it is ok to keep it as it is.

Regards

**Comment by pmario** [comment]
I was also thinking about it again. ... There may be some difficulties if you have dynamically generated button. ... see:

```
<$list filter="[tag[test]]" variable=test>
<$button><<test>></$button>
</$list>
```

So if a tiddler named "CamelCase" is tagged test, we have a problem. .. I did test it and I didn't find a way to disable the wikiling. Even placing the `\rules except wikiling` pragma into templates. 

@Jermolene .. any hints

@danielo515 you may reopen the issue :)

**Comment by Jermolene** [comment]
Hi @pmario the problem with your example is really that using `<<test>>` is unsafe because of unintended wikification: camel case gets links and a tiddler called `<$hr/>` will render a horizontal rule. It's better to use `<$text text=<<test>>/>`.
