### ISSUE TITLE
Introduce fallback storyview

### ISSUE THREAD

**Issue by twMat** [Jermolene/TiddlyWiki5#2555]
I deleted a non-standard Storyview (+reload). This seems to result in no storyview active as indicated from no scrolling taking place when clicking titles and no storyview name seen in Ctrlpanel.

If the symptoms come from missing fallback *and* if it is cheap to introduce such (considering the edgyness of the case), then I propose to introduce Classic storyview as fallback default.

**Comment by Jermolene** [comment]
Hi @twMat you are correct; if `$:/view` is not set to the name of one of the currently loaded storyviews, then no storyview is used.

It's an easy fix. The new behaviour is that the storyview defaults to the classic storyview. However, the invalid value in `$:/view` is not fixed, so the storyview dropdown will still show no storyview selected.

**Comment by twMat** [comment]
Excellent. Thanks for fix!
