### ISSUE TITLE
Add Mermaid plugin

### ISSUE THREAD

**Issue by AnderRasoVazquez** [Jermolene/TiddlyWiki5#2556]
[**Mermaid**](https://github.com/knsv/mermaid) generates diagrams and flowcharts from text in a similar manner as markdown. When I tried it on [Haroopad](http://pad.haroopress.com/) (a markdown editor) I loved it. Here are some [**demos**](http://knsv.github.io/mermaid/#flowcharts-basic-syntax), I think you will like it too.

Keep up the good work! =)

**Comment by twMat** [comment]
@AnderRasoVazquez - that looks terrific. IMO it should be a plugin, not least considering its size (at least the impression I get from it's size - how big is it actually? ...and where the heck do I see file size in Github anyway...). 

Also, if you didn't see it, there is the Railroad diagrams in TW core (...which probably also ought to be a plugin, btw)

**Comment by Jermolene** [comment]
Thanks @AnderRasoVazquez I hadn't seen Mermaid.

@twMat the issue title mentions adding Mermaid as a plugin; the railroad library is already packaged in a plugin, it's not in the core.

http://tiddlywiki.com/#%24%3A%2Fplugins%2Ftiddlywiki%2Frailroad

**Comment by twMat** [comment]
>@twMat the issue title mentions adding Mermaid as a plugin; the railroad library is already packaged in a plugin, it's not in the core.

Humble excuses to both of you and thanks for info.

**Comment by danielo515** [comment]
How have you read my mind @AnderRasoVazquez? I have also discovered mermaid some weeks ago and I was planning to create a plugin. For me it is the diagram tool that tiddlywiky needs and lacks. 

But if anyone else wants to implement that plugin I will not complain, I'm pretty busy with Noteself at the moment.

**Comment by danielo515** [comment]
Mermaid it's quite big because it depends directly from D3 library, which is very big.
By the way there is already a plugin that includes the D3 library, so Mermaid could be the first real use case of the `depends` field of plugin.info

**Comment by pmario** [comment]
@AnderRasoVazquez 
Hi, have a look at this thread. https://groups.google.com/forum/#!topic/tiddlywikidev/vC-CbAP9pVw

**Comment by Jermolene** [comment]
Thank you @pmario
