### ISSUE TITLE
On Node.js, new tiddlers with Type text/plain are saved in a file with double extension '.txt.tid'

### ISSUE THREAD

**Issue by JulioCantarero** [Jermolene/TiddlyWiki5#2558]
I did a clean test in a new TW5 new server instance using version 5.1.13. I am running TW5 on Node.js in Windows 10.
When I create a new tiddler with Type text/plain, it is saved in a file with double extension '.txt.tid'. This shows in the server log (see last line):

```
$ tiddlywiki --server --verbose
Serving on 127.0.0.1:8080
(press ctrl-C to exit)
Boot log:
  Startup task: load-modules
  Startup task: info after: load-modules before: startup
  Startup task: startup after: load-modules
  Startup task: story after: startup
  Startup task: commands platforms: node after: story
syncer-server: Dispatching 'save' task: $:/StoryList
FileSystem: Saved file D:\TW5onNode.js\Test\tiddlers\$__StoryList.tid
syncer-server: Dispatching 'save' task: $:/StoryList
FileSystem: Saved file D:\TW5onNode.js\Test\tiddlers\$__StoryList.tid
syncer-server: Dispatching 'save' task: Draft of 'New Tiddler 1'
FileSystem: Saved file D:\TW5onNode.js\Test\tiddlers\Draft_of_'New_Tiddler_1'.tid
syncer-server: Dispatching 'save' task: Draft of 'New Tiddler 1'
FileSystem: Saved file D:\TW5onNode.js\Test\tiddlers\Draft_of_'New_Tiddler_1'.tid
syncer-server: Dispatching 'save' task: Draft of 'New Tiddler 1'
FileSystem: Saved file D:\TW5onNode.js\Test\tiddlers\Draft_of_'New_Tiddler_1'.tid
syncer-server: Dispatching 'save' task: Draft of 'New Tiddler 1'
FileSystem: Saved file D:\TW5onNode.js\Test\tiddlers\Draft_of_'New_Tiddler_1'.tid
syncer-server: Dispatching 'save' task: Draft of 'New Tiddler 1'
FileSystem: Saved file D:\TW5onNode.js\Test\tiddlers\Draft_of_'New_Tiddler_1'.tid
syncer-server: Dispatching 'save' task: Draft of 'New Tiddler 1'
FileSystem: Saved file D:\TW5onNode.js\Test\tiddlers\Draft_of_'New_Tiddler_1'.tid
syncer-server: Dispatching 'delete' task: Draft of 'New Tiddler 1'
FileSystem: Deleted file D:\TW5onNode.js\Test\tiddlers\Draft_of_'New_Tiddler_1'.tid
syncer-server: Dispatching 'save' task: $:/StoryList
FileSystem: Saved file D:\TW5onNode.js\Test\tiddlers\$__StoryList.tid
syncer-server: Dispatching 'save' task: Test Problem with TXT Type in Filenames
FileSystem: Saved file D:\TW5onNode.js\Test\tiddlers\Test_Problem_with_TXT_Type_in_Filenames.txt.tid
```

AFAIK, prior to 5.1.13 or 5.1.12, TW5 was saving these tiddlers in a simple '.tid' file. 
Actually, this problem also happens with existing TXT tiddlers in upgraded TW5 on NOde.js, whose files are renamed to ".txt.tid" when the TXT tiddler is edited, leaving an undeleted Draft Of file behind.

**Comment by Jermolene** [comment]
Thanks @JulioCantarero I can confirm the problem.

@sukima this looks like another side effect of your recent changes, please could you look into this? Many thanks!

**Comment by Awerick** [comment]
Anything new on this issue?
The problem still exists (so it is independent from the closed #2647):
**TiddlyWiki:** version 5.1.14-prerelease

This also affects markdown files (when using the markdown plugin):
Markdown files get the suffix `.md.tid` instead of only `.md`. This is not intended, right?

This also leads to an error message when aborting an edit – which is supposed to delete the draft:
> `FileSystem: Saved file /home/awerick/tiddlywiki/tiddlers/Draft_of_'New_Tiddler_1'.md.tid`
> `syncer-server-filesystem: Dispatching 'delete' task: Draft of 'New Tiddler 1'`
> **`Sync error while processing 'Draft of 'New Tiddler 1'':`**
> **`Error: ENOENT, unlink '/home/awerick/tiddlywiki/tiddlers/Draft_of_'New_Tiddler_1'.md'`**

**Comment by pmario** [comment]
>Markdown files get the suffix .md.tid instead of only .md. This is not intended, right?

tiddlers always need to have a `.tid` extension, because they have a special format. .. so this is intentional.

If you want it to have x.md you will need to add a x.meta file, that contains the tiddlywiki header. eg: title, tags, field ,,, and so on

**Comment by Jermolene** [comment]
Hi @Awerick 

> Markdown files get the suffix .md.tid instead of only .md. This is not intended, right?
> This also leads to an error message when aborting an edit – which is supposed to delete the draft:

Thanks, you've uncovered another problem with the filesystem adaptor. I'll post an update soon.

**Comment by Jermolene** [comment]
Hi @Awerick @pmario I've done a major refactoring of the file system adaptor, which should fix the deletion problem raised by @Awerick, as well as the OP.

https://github.com/Jermolene/TiddlyWiki5/commit/3708f6c8e4f4bf2ea1cb10b0fa685888485f788a

The prerelease isn't on npm so you'll have to install it as detailed here:

http://tiddlywiki.com/#Installing%20TiddlyWiki%20Prerelease%20on%20Node.js

**Comment by Jermolene** [comment]
Sorry @JulioCantarero, I closed this in error, please close it yourself when you've confirmed the fix.

**Comment by Awerick** [comment]
Ah! Thanks @pmario, I misunderstood this issue and TW's file concept then, sorry:
When I read that plaintext files should not have a double extension (`.txt.tid`) but only `.tid`,
I mistakenly assumed markdown files should also not have a double extension (`.md.tid`) and it should be `.md`. But now I understand the intention of the `.tid` (and that both types use it).

@Jermolene:
 -  Thanks! Drafts are now deleted correctly (no error message when aborting an edit).
 -  However: TiddlyWiki now creates a new, empty directory for each new tiddler! (Bug!?)
 -  Furthermore the new commit changes the default behavior for new files, correct?

    Previously new files _that had not the default type (`text/vnd.tiddlywiki`)_ (e.g. plaintext files and markdown files) were created with the extension `.<TYPE>.tid`. Now new files are created with the extension `.<TYPE>` and with an additional `.<TYPE>.meta` file. (– Is there actually an option to choose the default behavior for this manually?)

    Is this a "solution" for this issue? I understand the intention of this issue to _keep_ the previous behavior (using `.<TYPE>.tid`) with the only change, that plaintext files should not be saved as `.txt.tid` but only `.tid`. – But maybe I still misinterpret the intention of this issue?

**Comment by pmario** [comment]
@Awerick 
There have been quite some changes to the filesystemadaptor now. For every known tiddler type, there will be an extension and a meta file now. Except for tiddlywiki files they are still .tid. 

The important thing is, that the filename has not much to do with the tiddler name. So the `title` field defines the tiddler name. The file name is just a "placeholder" to identify it as a file. 

So if you like you can create a new `tiddler.x.y.z.txt.tid` with some experimentation ;)

**Comment by Jermolene** [comment]
Hi @Awerick 


> -  Thanks! Drafts are now deleted correctly (no error message when aborting an edit).

Great.

> -  However: TiddlyWiki now creates a new, empty directory for each new tiddler! (Bug!?)

That problem should be fixed now.

> -  Furthermore the new commit changes the default behavior for new files, correct?

Correct.

>    Previously new files _that had not the default type (`text/vnd.tiddlywiki`)_ (e.g. plaintext files and markdown files) were created with the extension `.<TYPE>.tid`. Now new files are created with the extension `.<TYPE>` and with an additional `.<TYPE>.meta` file. (– Is there actually an option to choose the default behavior for this manually?)

Known file types are now saved as a separate *.ext and *.ext.meta file. The goal here is to make it easier to edit the tiddler files with proper syntax colouring in a separate editor, and easier to re-use tiddler files.

>    Is this a "solution" for this issue? I understand the intention of this issue to _keep_ the previous behavior (using `.<TYPE>.tid`) with the only change, that plaintext files should not be saved as `.txt.tid` but only `.tid`. – But maybe I still misinterpret the intention of this issue?

My goal with the recent commit was to fix a number of issues that had accumulated thanks to my mistakenly merging some PRs that broke previous behaviour.

**Comment by JulioCantarero** [comment]
I tried 5.1.14-prerelease using node.js on Windows 10 and the previous problem with txt files did not happen. Thank you!
