### ISSUE TITLE
Filter operator `indexes` should not change the order of an array

### ISSUE THREAD

**Issue by danielo515** [Jermolene/TiddlyWiki5#2559]
Data tiddlers can be both, Objects or Arrays.

The main difference (sorry for being so simplistic) between Objects and Arrays is that Arrays respects the order. This does not happens with the filter operator `indexes`. You have to use `nsort` to obtain a correctly ordered array, because by default they are treated as text.

Exapmle:

MyData

``` js
[1,2,3,4,5,6,7,8,9,10,11,12,13]
```

Then, if you access those indexes this way:

```
 <$list filter="[[MyData]indexes[]]">
{{!!title}},
</$list>
```

You get the following output:
`0, 1, 10, 11, 12, 2, 3, 4, 5, 6, 7, 8, 9,`

Quite incorrect in my opinion.

Regards

**Comment by Jermolene** [comment]
Hi @danielo515 the "indexes" filter operator treats sorts the indexed property names as strings. You'd need to use `nsort[title]` to get them in numerical order.

**Comment by tobibeer** [comment]
@Jermolene, I agree with @danielo515 that it is both unfortunate and not intuitive that the **indexes** filter would impose sorting. Is there truly a need for this?

**Comment by Jermolene** [comment]
The reason we sort the indexes is because otherwise the order would be defined by the browser. Most but not all browsers return properties in the order they were defined. We have to sort them to ensure that they appear in a consistent order regardless of browser.

**Comment by danielo515** [comment]
But something that all browsers and all the JS interpreters respect is the order of an array, but TW is doing exactly the opposite.

Not a big problem, but counterintuitive. 
Regards

**Comment by tobibeer** [comment]
@Jermolene, I see a strong case for the ability to retrieve indexes exactly in the order they are defined.

Possibly the core utils lack a function to retrieve indexes / field names in the very order in which they are defined, i.e. using an array, e.g. some `$tw.utils.getFieldsIndex()`

If one then wanted sorting, one could simply do so via:

```
[foo]indexes[]sort[]]
```

**Comment by Jermolene** [comment]
Hi @tobibeer 

> I see a strong case for the ability to retrieve indexes exactly in the order they are defined

It's not possible to guarantee the retrieval order of object properties in JavaScript:

http://stackoverflow.com/questions/5525795/does-javascript-guarantee-object-property-order

That's precisely why the indexes are sorted: to avoid users accidentally creating wikitext that works differently on different browsers.

**Comment by tobibeer** [comment]
@Jermolene, I understand. What stops us from caching an (additional) index array or simply retrieving that upon request, rather than use but an object for tiddler fields, as we do now?

**Comment by danielo515** [comment]
>It's not possible to guarantee the retrieval order of object properties in JavaScript

But arrays does, and having an array at the root of a Json document is legal JSON. That's why I think it should behave exactly as JS will do in that case. It's not natural to order the properties of an array because they are sorted by default

**Comment by pmario** [comment]
@Jermolene ... IMO this is a wont-fix, since it cannot be changed in a backwards compatible way and we do have the `nsort` operator, which is the desired way to do it.

**Comment by Jermolene** [comment]
Thank you @pmario
