### ISSUE TITLE
Cancel button of password prompt  triggers a submit

### ISSUE THREAD

**Issue by danielo515** [Jermolene/TiddlyWiki5#2561]
Hello,

I'm not sure why, but if you click the cancel button on a password prompt it triggers both the click handler of the cancel button and the submit handler of the form.

This is very inconvenient because when the user clicks cancel what it is expected is to cancel the action, not to try both, to cancel and submit the data.

Regards

**Comment by Jermolene** [comment]
Thanks @danielo515

**Comment by danielo515** [comment]
Hello @jermolene,

thank you for a rapid fix. Does this mean that if you don't provide one the default type is submit? 

Regards
