### ISSUE TITLE
Usage of the template in the tabs macro should behave like a normal template

### ISSUE THREAD

**Issue by danielo515** [Jermolene/TiddlyWiki5#2565]
Hello,

Recently I found myself misunderstanding the template variable of the tabs macro.
Normally a template tiddler gets the tiddler being transcluded as parameter. This mean, inside the template the tiddler being transcluded becomes the currentTiddler. This is from tw documentation:

```

A template tiddler that contains the WikiText to be displayed. It can contain transclusions that reference fields in the current tiddler
A target tiddler that identifies which tiddler is to be treated as current when resolving references to fields
```

The above description is what I understood as normal and what I always expect to happen. 

The tabs macro in the other hand behaves differently: It accepts a template as last parameter that lends you to think that the provided template will be used to display the content of the tabs.  But instead it transcludes the template as if it was a normal tiddler, without assigning any context to it other than the current tiddler. So, if you use a template like this:

```
I'm on the tab {{!!title}} and this is my text {{!!text}}
```

You will get the same content on all the tabs plus a beautiful Recursive transclude error.

I have to admit that re-reading the documentation of the tabs macro I found this:

```
template
Optionally, the title of a tiddler to use as a template for transcluding the content of the selected tab
Within the template, the title of the selected tab is available in the currentTab variable.

The currentTiddler variable is not affected by the tabs macro.
```

I don't understand the motivation behind this. That avoids the reuse of any template that you already have, and forces you to create alternative versions for tabs.

Regards

**Comment by Jermolene** [comment]
Hi @danielo515 I answered this same question over on the mailing list. The sort answer is that the tabs macro intentionally leaves the currentTiddler variable untouched. This enables it to be used in contexts like the tiddler info panel, where we need to transclude the individual tabs without changing the currentTiddler.

It's worth remembering that the double curly braces syntax is a shortcut for a combination of the tiddler widget and the transclude widget, as discussed in the docs.

**Comment by danielo515** [comment]
Hello @Jermolene 

That is an usage very tied to the TW core and doesn't look to be suitable for most users. I can understand that it is constructed to fit core needs, but I feel that there is a lot of stuff that is released as if it were for "end users usage" which may not be suitable for the average user. 

In any case, this one has an easy fix, and maybe we can include it as a small snippet inside TW docs.

Regards

**Comment by Jermolene** [comment]
> That is an usage very tied to the TW core and doesn't look to be suitable for most users. I can understand that it is constructed to fit core needs, but I feel that there is a lot of stuff that is released as if it were for "end users usage" which may not be suitable for the average user.

Hi @danielo515 that's an interesting opinion, but I don't think it's right. Using the tabs macro to present detailed information about a parent tiddler is a very common application. I appreciate that your original expectation was that the tabs macro would set the currentTiddler variable, but surely you can see that the system is more flexible by using the separate currentTab variable?

**Comment by danielo515** [comment]
Hello Jeremy,

After my first frustration, and specially after finding an alternative solution, I certainly see the advantages.

Regards

**Comment by Jermolene** [comment]
Thanks @danielo515

**Comment by tobibeer** [comment]
It feels to me that rather than "currentTab" the tabs macro should have introduced a "storyTiddler" instead

the problem Danielo's facing is not that he can't easily display information about the tiddler containing the tabs, but rather that it proves difficult to render the tiddler representing the tab contents reliably, which is what one might reasonably expect a tab to do
