### ISSUE TITLE
TypeError: saver.info.capabilities is undefined

### ISSUE THREAD

**Issue by VicDemos** [Jermolene/TiddlyWiki5#2569]
Initial data: 1. Windows 10 2. Google chrome, Firefox and TiddlyWiki Desktop. While trying to export this error occurs "Internal JavaScript Error Well, this is embarrassing. It is recommended that you restart TiddlyWiki by refreshing your browser TypeError: saver.info.capabilities is undefined" . Is there a solution to this problem?
![export error](https://cloud.githubusercontent.com/assets/21632415/18201697/4543762a-7114-11e6-8083-769870e86183.png)

**Comment by pmario** [comment]
tiddlywiki `<<version>>` ?

**Comment by VicDemos** [comment]
tiddlywiki version 5.1.13

**Comment by pmario** [comment]
Is this still a problem with latest version 5.1.17?

**Comment by pmario** [comment]
Which plugins did you install?

**Comment by pmario** [comment]
@Jermolene ... This one can not be reproduced anymore and there has been no feedback from the OP author. So IMO can be closed.
