### ISSUE TITLE
nodejs tw saving tiddlers with .tid.tid extensions

### ISSUE THREAD

**Issue by buggyj** [Jermolene/TiddlyWiki5#2571]
This is a from the thread
https://groups.google.com/forum/#!topic/tiddlywiki/LK02DUdI-rQ

saving a  tid (New Tiddler 6) shows double extension error: -

syncer-server: Dispatching 'save' task: Draft of 'New Tiddler 6'
FileSystem: Saved file /data/radice/playTw519/plugins/bj/tiddlyclip/build/demo/tiddlers/Draft_of_'New_Tiddler_6'.tid.tid
syncer-server: Dispatching 'delete' task: Draft of 'New Tiddler 6'
FileSystem: Deleted file /data/radice/playTw519/plugins/bj/tiddlyclip/build/demo/tiddlers/Draft_of_'New_Tiddler_6'.tid.tid
syncer-server: Dispatching 'save' task: $:/StoryList
FileSystem: Saved file /data/radice/playTw519/plugins/bj/tiddlyclip/build/demo/tiddlers/$__StoryList.tid.tid.tid.tid
syncer-server: Dispatching 'save' task: Draft of 'New Tiddler 6'
FileSystem: Saved file /data/radice/playTw519/plugins/bj/tiddlyclip/build/demo/tiddlers/Draft_of_'New_Tiddler_6'.tid.tid
syncer-server: Dispatching 'save' task: $:/StoryList
FileSystem: Sa

**Comment by buggyj** [comment]
This is appear to be the result of a programming error: 
in strEndsWith (utils.js):
`
exports.strEndsWith = function(str,ending,position) {
    if(str.endsWith) {
        return str.endsWith(ending,position);
    } else {
        if (typeof position !== 'number' || !isFinite(position) || Math.floor(position) !== position || position > str.length) {
            position = str.length;
        }
        position -= str.length;
        var lastIndex = str.indexOf(ending, position);
        return lastIndex !== -1 && lastIndex === position;
    }
};
`
which needs correcting to
`
n strEndsWith, it should I think be:-

exports.strEndsWith = function(str,ending,position) {
    if(str.endsWith) {
        return str.endsWith(ending,position);
    } else {
        if (typeof position !== 'number' || !isFinite(position) || Math.floor(position) !== position || position > str.length) {
            position = str.length;
        }
        position -= ending.length;
        var lastIndex = str.indexOf(ending, position);
        return lastIndex !== -1 && lastIndex === position;
    }
};
`

**Comment by sukima** [comment]
I thought this was fixed in PR #2504

**Comment by sukima** [comment]
@buggyj Those two examples look the same. Would you happen to have a patch I could look at? What programming error are you referring to?

**Comment by sukima** [comment]
@buggyj never mind, I think I see it. See PR #2572 does that fix the problem?

**Comment by buggyj** [comment]
I guess this was missed because it is a polyfil, and so depends on what version of node is installed (at some point the function was probably added to the v8 engine).

**Comment by buggyj** [comment]
I have xubuntu 14.04 with node v0.10.37

**Comment by buggyj** [comment]
I have testing #2572, and it seems to fix this problem
