### ISSUE TITLE
Rendering problem at: http://tiddlywiki.com/alltiddlers.html#Release%205.1.9

### ISSUE THREAD

**Issue by pmario** [Jermolene/TiddlyWiki5#2573]
win10, ff 48.02 and chrome 52.0.xxx

Go to http://tiddlywiki.com/alltiddlers.html#Release%205.1.9  and scroll down a little bit

**Comment by tobibeer** [comment]
What is the precise issue you're having? Please describe.

**Comment by pmario** [comment]
don't you see it? go to the link, and scroll down.   the formatting of the recent tab is completely messed up.
![bildschirmfoto vom 2016-09-06 09-43-06](https://cloud.githubusercontent.com/assets/374655/18265520/737b0d28-7416-11e6-928e-b0917c09d3dc.png)

**Comment by pmario** [comment]
this screen shot is ubuntu 16.04 ff 48

**Comment by tobibeer** [comment]
> don't you see it?

Haha, that's somewhere half way down on a page that is about as long as Long Island. :D

**Comment by Jermolene** [comment]
Thanks @pmario
