### ISSUE TITLE
Serve the plugin library also from https

### ISSUE THREAD

**Issue by danielo515** [Jermolene/TiddlyWiki5#2582]
Hello,

The plugin library is a very convenient way of installing and upgrading plugins. Sadly, it is served using plain `http`, which makes it unusable for any wiki serverd through `https`.

Could it be possible to serve it from `https` and fallback to `http` if it fails?

Regards

**Comment by pmario** [comment]
Seems to be not possible atm if we use tw custom domain:  `http://tiddlywiki.com/library/v5.1.13/index.html`

See: https://konklone.com/post/github-pages-now-sorta-supports-https-so-use-it

IMO it should be possible if we use. `https://tiddlywiki.github.io` as a second option

**Comment by Jermolene** [comment]
Fixed in #3005
