### ISSUE TITLE
set and or filter operators

### ISSUE THREAD

**Issue by tobibeer** [Jermolene/TiddlyWiki5#2591]
Implement two filter operators **set** and **or** which act as follows:

```
[all[current]has[foo]set[Foo]or[Bar]]
```

Meaning: Whatever the input titles, if there are any, return **Foo** via **set** and if there are none at all, return **Bar** via **or**.

In detail:

**set** returns the title(s) specified in the operand if there are any input titles, otherwise an empty set
**or** returns the title(s) specified in the operand if there are no input titles otherwise passes the input unchanged

Both should provide a "list" suffix where the operand being a stringified list is returned as a list, e.g.:

```
<$vars this="Foo [[Bar Baz]]" that="Mumble [[Frotz Gronk]]">
{{{ [all[current]has[foo]set:list<this>or:list<that>] }}}
</$vars>
```

If you give it a thumbs up, I'll go ahead and make a PR.
# Demo

http://2591.tiddlyspot.com
## Context

[Google Groups discussion on dynamic tabs](https://groups.google.com/d/msg/tiddlywiki/_Pz0upw0_ng/K9xOtWiQEQAJ)

**Comment by inmysocks** [comment]
Recently I have run into a few situations where this would be very useful. I have been trying to come up with something like this and failing so I would really like this to be implemented.

And the list suffix is a great idea and I support adding that to things even if the set and or operands aren't used.

Wouldn't it be simpler to just have 'or' be '!set'? or is there some difference between negating the set and or that I am missing?

The only thing I would want added to it is to have it so you could somehow do a sequence of sets in a single filter. So [all[current]has[foo]set:list<someList>set:list<someOtherList>set:list<aThirdList>] would return <aThirdList> if [all[current][has[foo]], <someList> and <someOtherList> were all not empty.

My thought is that you could do something like 

<$set name=someList filter='[tag[bar]]'>
<$set name=someOtherList filter='[tag[baz]]'>
<$set name=aThirdList filter='[tag[bar]]'>
<$list filter='[all[current]has[foo]set:list<someList>set:list<someOtherList>set:list<aThirdList>]'>

</$list>
</$set>
</$set>
</$set>

could be done without a bunch of nested list widgets.

**Comment by tobibeer** [comment]
Hi @inmysocks, thanks for your feedback. As for...

> would return `<aThirdList>` if `[all[current][has[foo]]`, `<someList>` and `<someOtherList>` were all not empty

that is precisely how it would work already


I could live with the negated filter. However, I very much dislike the way it spells, i.e. it reads very unintuitive to me.

In other words, there is no meaningful negation to **set** as there is no logical operation to be negated. Instead it is doing a **transformation**, i.e. "make something from something else" whereas **or** would "make something out of nothing". Implementing **or** as **!set** would establish another case where there is no negation going on. Instead we would overload one operator to do quite different things.

**Comment by inmysocks** [comment]
I have been looking at filters as logical operations a lot lately so I have been thinking in those terms. To describe set I would use 'if empty than output' and 'if not empty than output' for or, which is why I said it would be a negation. I agree that it does read better as set and or so unless someone else has input just go with that.

I would like there to be a way to give a complete filter as the operand instead of having to use a separate $set widget, but I don't think that would work with the way parsing works.

**Comment by tobibeer** [comment]
Hi @inmysocks, my last reply wasn't quite correct, so I fixed it.

**Comment by tobibeer** [comment]
> I would like there to be a way to give a complete filter as the operand instead of having to use a separate $set widget, but I don't think that would work with the way parsing works.

Yeah, I feel you, but that's just something "for another day" / ticket. ;-)

One thing with filters as operands is: What is their input? or rather: Do they get some defined input?

You can see what I mean in the syntax documentation of [tobibeer/filter](http://tobibeer.github.io/tw5-plugins/#filter-Syntax).

**Comment by tobibeer** [comment]
added demo http://2591.tiddlyspot.com to description

**Comment by Jermolene** [comment]
Thank you @pmario
