### ISSUE TITLE
Feature Request: Put request callback in separate property on SimpleServer.prototype

### ISSUE THREAD

**Issue by Arlen22** [Jermolene/TiddlyWiki5#2602]
## Feature Request

https://github.com/Jermolene/TiddlyWiki5/blob/master/core/modules/commands/server.js

In SimpleServer.prototype.listen, it would be useful if the request handler provided to create server would be moved onto the prototype itself so that it can be called by external code which wants to use the server. 

This one change makes it very simple to code an Express module which can be loaded and used to serve the TiddlyWiki as part of an Express application. 

Otherwise, you either have to copy the request handler into the Express module, or change server.js manually each time there is an update. Either way it is more cumbersome.

``` js
SimpleServer.prototype.listen = function(port,host) {
    http.createServer(this.requestHandler.bind(null, this)).listen(port,host);
};
SimpleServer.prototype.requestHandler = function(self, request,response) {
    // Compose the state object
    var state = {};
    //...
};
```

https://gist.github.com/Arlen22/bbd852f68e328165e49f is the gist of how to actually serve TiddlyWiki from ExpressJS.

**Comment by Jermolene** [comment]
Hi @Arlen22 sounds reasonable, please go ahead and create a pull request.

**Comment by Arlen22** [comment]
Ok, you can find it at #2607.
