### ISSUE TITLE
Searching should require search string to be a minimum length

### ISSUE THREAD

**Issue by Jermolene** [Jermolene/TiddlyWiki5#2603]
Part of the reason for the poor performance of search in large wikis is that the incremental search function kicks in after a single character has been typed, often returning almost every tiddler within the wiki.

It is proposed to add a threshold minimum length for the search string, below which the search results are not computed or displayed.

#1493 proposes a new `textlength` filter as the means to implement this threshold.

**Comment by tobibeer** [comment]
As [extensively discussed](https://github.com/Jermolene/TiddlyWiki5/commit/989cee50594a76a0f30d1d2124ce9e5e5808c6cf#commitcomment-19426876), while the result list for full text search should be constrained, the result list for titles-only should not be. I want to be able to type `#` and be presented a list with all tiddlers prefixed '#'.

**Comment by Jermolene** [comment]
@tobibeer I think you make two proposals in the linked discussion:

* Introduce a separate minimum length for title searches
* Add shadow and system sections to the search results

My position remains that I think having two separate minimum lengths makes for needless complexity. If your wiki is small enough to get decent performance for a single character title search then it's probably going to be OK to do single character body searches.

**Comment by tobibeer** [comment]
I believe my proposals are rather:

1. use minimum search on the search results level,<br>» specifically in [$:/core/ui/DefaultSearchResultList](http://tiddlywiki.com/#%24%3A%2Fcore%2Fui%2FDefaultSearchResultList)
2. allow granular control for minlength with each list in the search results template
3. (re)use the same search results template for all of standard, system or shadow search
4. to not list title matches in all matches again, but instead have three sections,<br>» [one each for title, tag and text matches](https://github.com/Jermolene/TiddlyWiki5/commit/989cee50594a76a0f30d1d2124ce9e5e5808c6cf#commitcomment-19432486)

As for **1.**, I have explained that it is quite important (for me) to be able to search for a **single character prefix** for **title matches** (min-length = 0), whereas it is equally as important to define a **min-length > 1** for **text matches**.

Therefore, for me, it is **not** OK at all to either keep having to use single character search for full text matches or to not be able to find title matches at the first character typed.

I find the introduced complexity to be both simple and necessary.

**Comment by tobibeer** [comment]
In this same context, I would also much prefer if we introduced a general length filter, rather than one constrained to min-length, e.g.:

http://2603-len.tiddlyspot.com

**Comment by Jermolene** [comment]
> apply minimum search on the search results level,

I don't think that this is entirely possible; have you looked at the fix that I've pushed? Can you see a way to code it without changing  [$:/core/ui/SideBarLists](http://tiddlywiki.com/#%24%3A%2Fcore%2Fui%2FSideBarLists) or [$:/core/ui/AdvancedSearch/...](http://tiddlywiki.com/#%24%3A%2Fcore%2Fui%2FAdvancedSearch%2FSystem)?

> allow granular control for minlength with each list in the search results template

You haven't addressed my concern about usability. I think it's confusing to have the two parts of the search results behave differently. I understand that you want this feature, but I don't think it's a good candidate for inclusion in the core.

> (re)use the same search results template for all of standard, system or shadow search

Why?

> to not list title matches in all matches again, but instead have three sections,

We have discussed this before. I don't think it's a good idea. I tried omitting the title matches from "all matches" section, and found that it was confusing because scanning the search results looked like some of the results were missing

> Therefore, for me, it is not OK at all to either keep having to use single character search for full text matches or to not be able to find title matches at the first character typed.

Why don't you roll your own thing?

> In this same context, I would also much prefer if we introduced a general purpose length filter, rather than one constrained to minlength, e.g.:

I'm open to adding a `maxlength` filter if you think it's useful.

**Comment by tobibeer** [comment]
>> apply minimum search on the search results level

> I don't think that this is entirely possible

In what regard?

> have you looked at the fix that I've pushed?

My comments at https://github.com/Jermolene/TiddlyWiki5/commit/989cee50594a76a0f30d1d2124ce9e5e5808c6cf suggest so.

> Can you see a way to code it without changing $:/core/ui/SideBarLists or $:/core/ui/AdvancedSearch/...?

As commented, I think the way forward is to:

1. modify **$:/core/ui/DefaultSearchResultList**
2. (re)use the same search results template for all of standard, system or shadow search

> Why?

1. to reduce complexity<br>» and the places where min-length would require specification
2. for consistency, i.e. to have the same, optimized search configuration regardless of whether we search for standard, system (non-shadow) or shadow tiddlers
3. for harmonization<br>» so that search results are present in a consistent manner

> We have discussed this before. I don't think it's a good idea. I tried omitting the title matches from "all matches" section, and found that it was confusing because scanning the search results looked like some of the results were missing

If the section was called "text matches" that problem would not exist.

> Why don't you roll your own thing?

Because....

1. this commit is in a prerelease state
2. overwriting key core components comes with severe and quite frustrating problems knowing it could easily be made configurable
3. suggestions resembling "you can always bake your own core" are entirely unhelpful

> I'm open to adding a maxlength filter if you think it's useful.

As suggested, for user input validation, all of minlength, maxlength or just length are useful.

**Comment by Jermolene** [comment]
> As commented, I think the way forward is to:

> modify $:/core/ui/DefaultSearchResultList

But that's not sufficient, is it? Won't we still need the other modifications I've already pushed?

> (re)use the same search results template for all of standard, system or shadow search

You mean in `$:/AdvancedSearch`, I assume? I've no objection to that, although I don't recall why I didn't re-use `$:/core/ui/DefaultSearchResultList` there; perhaps there's a problem with that approach.

> If the section was called "text matches" that problem would not exist.

I disagree; partly because not everyone reads and fully understands the implications of labels

> suggestions resembling "you can always bake your own core" are entirely unhelpful

@tobibeer that was in response to your argument that we should re-engineer the core plugin to make it less monolithic; is it relevant here?

**Comment by tobibeer** [comment]
> But that's not sufficient, is it? Won't we still need the other modifications I've already pushed?

I don't think we do. I'll just go ahead and implement the solution as I would suggest to do it, after all, and make a PR with a demo. If you are inclined to merge it, you can, and if you're not, you're not.

>> If the section was called "text matches" that problem would not exist.

> I disagree; partly because not everyone reads and fully understands the implications of labels

I'm all fine with keeping the "All matches" section, I just don't think the verbosity is helpful. However, my key pain point is that I want different a min length for the result list for title matches. Whether we further split the "All matches" list up into tags and text matches or not is quite secondary to me.

> that was in response to your argument that we should re-engineer the core plugin to make it less monolithic; is it relevant here?

Depends on what you tried to suggest with "roll your own thing". There sure comes a point when that means I will start baking and then using a different core ...and then I will have to make people understand that and why my things run on **$:/tb-core** and not the actual TiddlyWiki core. Not a desirable approach in my eyes. Sometimes I get the feeling you're indeed rather curious about how such an undertaking would unfold.
