### ISSUE TITLE
<email@foo> should not be parsed as tag

### ISSUE THREAD

**Issue by twMat** [Jermolene/TiddlyWiki5#2604]
This (e.g a copy-pasted email) does not show the headline in the correct format

```
Bob <bob@foo.bar>
Topic: Hi

!Headline
```

I'm guessing the bracketed email address is interpreted as a tag. Note: the problem is not seen unless the closing bracket is followed by some character (here the topic line).

I propose this standard email-format is interpreted as an exception so that one can easily copy-paste emails into a tiddler.

[Feel free to improve the title of this issue]

**Comment by tobibeer** [comment]
Perhaps the perspective title of the issue should be turned around.

In other words, to fix it, we probably want to parse emails, including angle brackets, so pixi* would need a dedicated parser for that so long as the link parser doesn't handle email.

**Comment by pmario** [comment]
remove the brackets and you are good to go. ... There are several problems like this one, even with wikitext syntax. ... everything which is covered in those braces may be interpreted in the wrong way, as long as html syntax is allowed as "wikitext"

**Comment by twMat** [comment]
>In other words, to fix it, we probably want to parse emails, including angle brackets, so pixi* would need a dedicated parser for that so long as the link parser doesn't handle email.

I don't know how to phrase such a request but if you do and you think it renders my issue here superfluous then I'd be happy to close this here. However, your proposal seems like a much bigger animal, no?

**Comment by twMat** [comment]
>remove the brackets and you are good to go. ... 

I must say I'm not very fond of these types of non-replies. What competitor to TW would see this solution as sufficient for their users? Surely not EverNote or OneNote or any other commercial app.

>There are several problems like this one, even with wikitext syntax. ... everything which is covered in those braces may be interpreted in the wrong way, as long as html syntax is allowed as "wikitext"

That is an important observation. Do we have any "policy" on how to handle this? Is the user currently expected to simply not use such braces in wikitext?

`<string@string.string>` is a clearly identifiable pattern so it seems justified to introduce it as a special case, particularly considering the prevalence of it.

Are there other such distinct and common patterns/cases?

**Comment by pmario** [comment]
>That is an important observation. Do we have any "policy" on how to handle this? Is the user currently expected to simply not use such braces in wikitext?

`<anytext>` is valid tw syntax and TW expects it to be closed somewhere with `</anytext>` .. that's the `html` rule. If we don't want it, we can use the `except html` rule at the beginning of the wikitext. 

Like so:

```
\rules except html

Bob <bob@foo.bar>
```

**Comment by pmario** [comment]
`extlink.js` contains a `mailto:` rule for things as eg: `mailto:bob@example.com` ... 

**So a proposal could be** that `<bob@example.com>` could be a convenience shortcut for `mailto:..` and should be handled accordingly. I could live with this one, ..

..but creating exceptions for valid html rules is a no go for me, since there is no end and there are hundreds of edge cases depending on the users "use case"

**Comment by tobibeer** [comment]
oh boy, I really said pixi*, mhhh, work on my mind, even if it's lunch break ;-)

**Comment by tobibeer** [comment]
> So a proposal could be that <bob@example.com> could be a convenience shortcut for mailto:.. and should be handled accordingly.

That's pretty much what I meant. We just need a parser that identifies the pattern and creates the link widget or whatever it is accordingly.

**Comment by pmario** [comment]
Hi Mat. I have to say sorry, because it seems to be a real bug. ... `@` seems to be invalid in tag names. 

This is the specs that defines html tag names are: 

* https://www.w3.org/TR/html5/syntax.html#elements-0
* https://www.w3.org/TR/xml/#NT-Name

So may be the `html.js` parser needs some more checks, because `<anytext>` may be not true ;)

**Comment by Jermolene** [comment]
I agree that `<jeremy@example.com>` shouldn't be parsed as an HTML element. I'll shortly push a fix, and then separately I think we should add a parser for email addresses delimited by angle brackets.

**Comment by twMat** [comment]
Really happy to see it resolved so quickly! Thanks guys!

**Comment by danielo515** [comment]
I'm late for the party here, but anyway. What mat talks about seems like an invalid html tag. Since TW is a superset of html y don't understand why should we deal differently with an invalid tag.

**Comment by Jermolene** [comment]
Hi @danielo515 the problem was that `<jeremy@example.com>` was being erroneously parsed as an HTML tag; there was a bug in the parser which is now fixed.
