### ISSUE TITLE
Export .tid file only exports 1 tiddler

### ISSUE THREAD

**Issue by cawoodm** [Jermolene/TiddlyWiki5#2608]

**Comment by cawoodm** [comment]
TW Desktop

![image](https://cloud.githubusercontent.com/assets/498834/19349691/a7e27c8a-9154-11e6-9362-e3070a429c7c.png)

**Comment by Jermolene** [comment]
Hi @cawoodm 

A limitation of the `.tid` file format is that it is only be able to contain a single tiddler. The CSV, JSON, and Static HTML file formats can all contain multiple tiddlers.

The reason that the `.tid` file format is listed here is that we're showing a generic list of all the available exporters, regardless of any limitations. You'll see the same list in the "Filter" tab of advanced search; there again, using `.tid` only makes sense if you just want to export the first result.

**Comment by cawoodm** [comment]
OK, then arguably it should not appear in the "Export All" menu.

**Comment by Jermolene** [comment]
Hi @cawoodm 

> OK, then arguably it should not appear in the "Export All" menu.

Yes, definitely. Fixing it would require more logic so that the menu listing the available formats can modify itself according to the various locations it is displayed (export wiki, export tiddler, export search).

**Comment by danielo515** [comment]
Maybe a better solution would be to make possible to export a bundle of Tiddlers, maybe a zip...

**Comment by Jermolene** [comment]
> Maybe a better solution would be to make possible to export a bundle of Tiddlers, maybe a zip...

Exporting multiple files in a ZIP is on the roadmap; I integrated JSZip some time ago for another project but with half an eye on that.

**Comment by cawoodm** [comment]
If .tid content is encoded you could conceivably include multiple tiddlers
in one file by inventing a separator. Might mean that older TWs can't
import it properly but that's progress for ya.

**Comment by pmario** [comment]
>If .tid content is encoded you could conceivably include multiple tiddlers in one file by inventing a separator. Might mean that older TWs can't import it properly but that's progress for ya.

What you describe here is export as `.json`.

**Comment by tobibeer** [comment]
hi @cawoodm, #1947 may also be interesting in terms of tid file complexities

**Comment by pmario** [comment]
@cawoodm, @Jermolene -- This one can be closed, since the "export all" button does not show the ".tid" format anymore. 

![image](https://github.com/Jermolene/TiddlyWiki5/assets/374655/49b2af0d-9403-4871-8c32-9ffa82b83f9c)

**Comment by Jermolene** [comment]
Thank you @pmario
