### ISSUE TITLE
Import Tiddlers as dragged .json file fails with SyntaxError

### ISSUE THREAD

**Issue by cawoodm** [Jermolene/TiddlyWiki5#2609]
Dragging the following tiddlers.json file into TW Desktop fails:
```
[
{"title":"Tiddler1","text":"Text of tiddler},
{"title":"Tiddler2","text":"Text of tiddler}
]
```
Internal JavaScript Error

Well, this is embarrassing. It is recommended that you restart TiddlyWiki by refreshing your browser
Uncaught SyntaxError: Unexpected token

![image](https://cloud.githubusercontent.com/assets/498834/19350045/76fc0bfc-9156-11e6-962d-98140b968407.png)

**Comment by Jermolene** [comment]
Thanks @cawoodm, fixed for 5.1.14
