### ISSUE TITLE
Improve support for handling bulk tiddler files under Node.js

### ISSUE THREAD

**Issue by Jermolene** [Jermolene/TiddlyWiki5#2610]
TiddlyWiki reads tiddlers from wiki folders when run under Node.js. The basic strategy of the core is to load all the tiddlers that it can find in a recursive directory search of the `tiddlers` subdirectory of the edition directory.

As [described on tw.com](http://tiddlywiki.com/#TiddlyWikiFolders), the `tiddlywiki.files` feature makes it possible to override this default behaviour and pull in files from outside the the edition directory entirely. It currently supports two capabilities:

* Listing individual files to be read as tiddlers, along with the ability to override the field values with new values, and to prefix and/or suffix the `text` field of the tiddler. This capability is extensively used in TW5 in order to include external JS/CSS/WOFF files as tiddlers
* Listing individual directories to be recursively read. This capability was introduced as part of the development of the `tw5.com-docs` edition, and isn't otherwise used in TW5 itself

Listing individual files is tedious and error prone. For example, the KaTeX plugin [manually includes references to 20 WOFF font files](https://github.com/Jermolene/TiddlyWiki5/blob/470238acbf71e5bc44ada1f9e185af04d296b00b/plugins/tiddlywiki/katex/files/tiddlywiki.files#L3-L123). 

It is proposed to extend the "directories" feature of `tiddlywiki.files` to specify more precise control over how the files in the directory should be converted into tiddlers:

* A relative or absolute reference to the directory
* A regular expression determining which files should be read
* An "isTiddlerFile" flag to determine whether the file should be deserialised as a tiddler file (true), or treated as raw data (false)
* A listing of fields to be overridden for each tiddler, with the generalised capability to add a prefix or suffix to any field
* The ability to transfer file metadata such as the filename and modification/creation times into tiddler fields

These capabilities will enable some common use cases such as pulling all the PDFs or images within a directory into tiddlers with a title based on the filename.

There are a couple of disadvantages with the proposal:

* Using regular expressions within a JSON file can be awkward as one has to escape the backslash character
* When externally loaded tiddlers are modified the file system adaptor creates a new file in the usual location, and doesn't try to modify the external file. The problem is that the tiddler that ended up being loaded is the result of combining the information loaded from the file with information extracted from `tiddlywiki.files`; there's no single location to write back any changes

Here is an example of how the WOFF files might be handled by the KaTeX plugin with the proposed improvements:

```
{
	"directories": [
		{
			"path": "./fonts/",
			"filesRegExp": "^.*\\.woff$",
			"isTiddlerFile": false,
			"fields": {
				"title": {"source": "file-name", "prefix": "$:/plugins/tiddlywiki/katex/fonts/"},
				"type": "application/font-woff"
			}
		}
	],
	"tiddlers": [
		{
			"file": "katex.without-font-face.min.css",
			"fields": {
				"type": "text/plain",
				"title": "$:/plugins/tiddlywiki/katex/katex.min.css"
			}
		},{
			"file": "katex.min.js",
			"fields": {
				"type": "application/javascript",
				"title": "$:/plugins/tiddlywiki/katex/katex.min.js",
				"module-type": "library"
			},
			"prefix": "(function(document) {\n",
			"suffix": "\n})($tw.node ? $tw.fakeDocument : window.document)\n"
		}
	]
}
```

I needed this feature for my own work with TW5 but I recall others asking for something similar in the past.

**Comment by pmario** [comment]
Looks good. ... I do have one suggestion too!

* add an `ignore` array. eg: 
  * If `path` is the only parameter `filesRegExp` defaults to `^.*$` .. aka every file 
  * If `path` is `./` ... this directory and every subdirectory.
  * path is always recursive
* ignore has lower priority than the other elements.
  * that allows us to say ignore path, except one file x

minimal: Don't include anything in this directory and all subdirs. ..

```
    "ignore": [
        ["path": "./"]   
    ],
```

more advanced:

```
    "ignore": [
        [ "path": "./fonts/",
          "filesRegExp": "^.*\\.woff$"
        ],
        ["path": "./node_modules/"],
        ["file": "./relative/file/name.txt"],
        ["path": "./"]   
    ],
```

**Comment by pmario** [comment]
> * Using regular expressions within a JSON file can be awkward as one has to escape the backslash character

We could us a mechanism like: https://github.com/isaacs/minimatch

**Comment by Jermolene** [comment]
Hi @pmario interesting idea

Presumably the scope of ignoring a path would be just within the processing of the `tiddlywiki.files` file in which it appears?

What are the use cases that you're thinking of?

> We could us a mechanism like: https://github.com/isaacs/minimatch

I looked at that funnily enough, but I think it's bigger than we need. Having to use regexp's for advanced features doesn't seem unreasonable.

**Comment by sukima** [comment]
> Using regular expressions within a JSON file can be awkward as one has to escape the backslash character

A lot of node projects are moving away from JSON configurations files in favor of pure JavaScript. Mainly because the effort to convert is almost zero. it has the same syntax and it allows you to have all the JS goodies like regular expressions, conditionals (think different environments controlled by `process.env.NODE_ENV`, debugging, and *comments*.

For example:

```json
{
    "directories": [
        {
            "path": "./fonts/",
            "filesRegExp": "^.*\\.woff$",
            "isTiddlerFile": false,
            "fields": { … }
        }
    ],
    "tiddlers": [ … ]
}
```

Becomes:

```js
module.exports = function() {
    return {
        directories: [
            {
                path: "./fonts/",
                filesRegExp: /^.*\.woff$/, // We only want woff fonts
                isTiddlerFile: false,
                fields: { … }
            }
        ],
        tiddlers: [ … ]
    };
};
```

The choice to `JSON.parse` or `require()` could be based on the file name (`tiddlywiki.files` vs `tiddlywiki.js`). Also note that node's `require()` knows how to [parse JSON nativly](https://www.bennadel.com/blog/2908-you-can-use-require-to-load-json-javascript-object-notation-files-in-node-js.htm) which would allow one to test if they have an object or if they need to execute the function:

```js
if (typeof payload ===
 'function') {
  payload = payload();
}
```

Just a thought. _Power and flexibility for very little cost_.

**Comment by pmario** [comment]
> Presumably the scope of ignoring a path would be just within the processing of the tiddlywiki.files file in which it appears?

I thought `tiddlywiki.files` can be anywhere. Also the root of the plugin directory?!

**Comment by pmario** [comment]
>What are the use cases that you're thinking of?

I'd like to have a eg: `package.json` file in the plugins / editions / themes directory, which `tiddlywiki --build --server --xxx` should ignore.

**Comment by Jermolene** [comment]
Hi @sukima very interesting. I generally favour declarative JSON files because that makes it easier to build a GUI on top. But, supporting `.js` files as an option might be a good approach, if you'd be interested in exploring it.

**Comment by Jermolene** [comment]
> I thought tiddlywiki.files can be anywhere. Also the root of the plugin directory?!

They can be within a plugin folder (eg `./mywiki/plugins/myplugin/tiddlywiki.files`), but not at the root of the `plugins` folder (eg `./mywiki/plugins/tiddlywiki.files`).

**Comment by Jermolene** [comment]
> I'd like to have a eg: `package.json` file in the plugins / editions / themes directory, which` tiddlywiki --build --server --xxx` should ignore.

Understood.

On reflection, I think there is a problem with using `tiddlywiki.files` to define files that should be ignored from the usual recursive loading process. Currently, the presence of a file called `tiddlywiki.files` suppresses the usual recursive tiddler loading process for that folder, and instead processes the files according to the specification in `tiddlywiki.files`.

Under your proposal, the semantics would be significantly more complex: The usual recursive loading process would be be suppressed if there is both a `tiddlywiki.files` file, *and* it contains a valid `tiddlers` or `directories` entry. The complexity comes from introducing the need to process the file even for directories that are being loaded in the usual way.

So, I think we could consider adding an `ignore` array to the processing of `directories` within the `tiddlywiki.files` file, but I'm not so keen on supporting an `ignore` array during the usual recursive tiddler loading process.

**Comment by pmario** [comment]
>Currently, the presence of a file called tiddlywiki.files suppresses the usual recursive tiddler loading process for that folder, and instead processes the files according to the specification in tiddlywiki.files.

If that's true, an empty `tiddlywiki.files` file will stop processing that directory? ... just ignoring it? ... that's what I want :) ... I'll need to play with it.

**Comment by Jermolene** [comment]
Hi @pmario, yes, an empty `tiddlywiki.files` file containing `{}` will stop processing that directory.

**Comment by sukima** [comment]
@Jermolene Re: using JS files: https://github.com/Jermolene/TiddlyWiki5/pull/2617
