### ISSUE TITLE
TiddlyWiki Components

### ISSUE THREAD

**Issue by tobibeer** [Jermolene/TiddlyWiki5#2612]
for more sophisticated core customization, provide for a fourth plugin-type, namely "component" and package most all core ui elements into such *Component* plugins, e.g. core/sidebar, core/advancedsearch, core/controlpanel, core/viewtemplate, core/pagetemplate, etc...

That way, it would make it easy to replace core ui elements, rather than override them and double the load

**Comment by danielo515** [comment]
That sounds very promising. But I'm afraid Jeremy will not like the idea because it's a lot of extra work with no clear improvement

**Comment by Jermolene** [comment]
> for more sophisticated core customization, provide for a fourth plugin-type, namely "component" and package most all core ui elements into such Component plugins, e.g. core/sidebar, core/advancedsearch, core/controlpanel, core/viewtemplate, core/pagetemplate, etc...

Why do we need a new plugin type? Couldn't all of those things be packaged as ordinary plugins?

> That way, it would make it easy to replace core ui elements, rather than override them and double the load

We have a monolithic core because it makes it easier to get TiddlyWiki running, and to verify and reset configurations.

I disagree with concerns about the impact of overriding core shadow tiddlers. The amount of space consumed is tiny compared to the size of the users content.

If anyone really cares about the size of the core then, as we have endlessly discussed, there is nothing stopping someone else forking the core plugin and splitting it into smaller parts. Personally I am not interested in being responsible for supporting users who struggle with the resulting complexity.

**Comment by pmario** [comment]
@tobibeer .. I think the "process" works like this: 

* Create "standard plugins", that contain the stuff, as you described it. 
* If all the components play together and basically replace the whole core, just remove the core. 
* If the program still runs as expected, it's done.

**Comment by tobibeer** [comment]
> Why do we need a new plugin type?

Because these things are not plugins in the ordinary sense. They are full ui components.

> Couldn't all of those things be packaged as ordinary plugins?

They could, and they should, but they **are not**. Besides, there is the issue of where to put localisations for these things and how to distribute those. The current deal is all or nothing on both fronts, ui and localisation.

> We have a monolithic core because it makes it easier to get TiddlyWiki running, and to verify and reset configurations.

The initial package can be as monolithic as it needs be or is desirable for a robust core distro. But that does not mean that it should be impossible to "chisel away" all the baggage that a fine sculptor does not need.

> I disagree with concerns about the impact of overriding core shadow tiddlers. The amount of space consumed is tiny compared to the size of the users content.

For a load optimized solution, this is far from the truth. The basic TW has already now grown to  a stunning 1.75 MB with no easy way to do away with all the overload a given implementation has no use for. Being forced to overwrite core shadows rather than remove them in bulk adds a significant lot more to get a basic (alternative) package to a workable state.

> If anyone really cares about the size of the core then, as we have endlessly discussed, there is nothing stopping someone else forking the core plugin and splitting it into smaller parts. 

**I care** and I care a lot about this and I don't think at all that I am alone in this. As for forking the entire thing, that is **the problem** rather than **the solution**. It means that just for changing  a few strings, I have to change the core localisation plugin, whih the core localisation even isn't, rather than define some extension. It means that just to change the sidebar, I need to repackage the entire core. To me, TiddlyWiki can be a whole dimension more modular than it already is. And that's a good thing to have and work on.

**Comment by Jermolene** [comment]
> For a load optimized solution, this is far from the truth. The basic TW has already now grown to a stunning 1.75 MB with no easy way to do away with all the overload a given implementation has no use for. Being forced to overwrite core shadows rather than remove them in bulk adds a significant lot more to get a basic (alternative) package to a workable state.

@tobibeer if you want to propose that something needs to be done from a performance perspective, then you'll need some numbers to back up those assertions. I'm still unconvinced that the few 100KB of unused tiddlers has a significant performance impact, and I'm very concerned about the resulting increase in system complexity.

> I care and I care a lot about this and I don't think at all that I am alone in this. As for forking the entire thing, that is the problem rather than the solution. It means that just for changing a few strings, I have to change the core localisation plugin, whih the core localisation even isn't, rather than define some extension. It means that just to change the sidebar, I need to repackage the entire core. To me, TiddlyWiki can be a whole dimension more modular than it already is. And that's a good thing to have and work on.

@tobibeer I've said repeatedly that without convincing numbers I'm not personally interested in pursuing this problem. My point about forking it is that somebody needs to run some experiments to see if any of this is worth doing.

As usual, it might be helpful if you could describe your underlying goals.

Anyhow, the OP is about introducing a new plugin type: let's stick to that simple proposal. I'm arguing that there is no need for a new type of plugin in order to explode the core plugin into multiple plugins. Your response has not persuaded me that there is a case for a new type of plugin. Therefore I think this ticket should stay closed. If you want to continue trying to persuade me to take an interest in breaking up the core plugin then I think that's really a separate topic than the OP.

**Comment by tobibeer** [comment]
> If you want to continue trying to persuade me to take an interest in breaking up the core plugin then I think that's really a separate topic than the OP.

It really is not. Language extensibility (or a lack thereof) is but one symptom of it, albeit rather prominent, the "syndrome" being: take it or leave it ...**all** ...otherwise: "do your own thing", meaning: build your own, custom core (or full custom language plugin) ...rather than just remove (and quite easily load back) any of those components which — for some well considered reason or another — you don't need. We don't have to break it down to every core filter or parser to being a "component" plugin, although we easily could.

**Comment by Jermolene** [comment]
> It really is not. Language extensibility (or a lack thereof) is but one symptom of it, albeit rather prominent, the "syndrome" being: take it or leave it ...all ...otherwise: "do your own thing", meaning: build your own, custom core (or full custom language plugin) ...rather than just remove (and quite easily load back) any of those components which — for some well considered reason or another — you don't need.

@tobibeer it's not a case of take it or leave it. The situation is that you are advocating splitting the core plugin into smaller parts. My response is that I don't see the evidence to support the amount of work to perform the split, and then the extra work of supporting a more complex configuration of TiddlyWiki. You are persisting in your request, and so I'm merely saying that you should do the necessary investigation to get the evidence to back up your proposal.

> We don't have to break it down to every core filter or parser to being a "component" plugin, although we easily could.

But every core filter and parse rule is already a component, being a tiddler module. They are a type of component. They are not the unit of granularity of installation for end users, but that is for the reason given above: assembling a correct, functioning configuration of individual modules would be much harder than maintaining a configuration based on plugins.

The point is that you already have the flexibility you need of the core being split into small pieces. The question is over the performance impact of carrying around tiddlers from the core plugin that are overridden elsewhere.

To be honest, your proposal of splitting the TiddlyWiki core into arbitrary clumps isn't a terribly appetising solution to the hypothetical problem: we're unlikely to choose the optimum clumping.

Better would be to *compile* the plugins within a TiddlyWiki; write a little process that whips through all the plugins, and figures out the shadow tiddlers are overridden, and simply removes them from their plugins. Rename the plugin with a suffix on the name to show what's been done, and you've got a meticulously efficient way of shipping a minimal TiddlyWiki, and we don't have to change the core architecture...

**Comment by tobibeer** [comment]
> the extra work of supporting a more complex configuration of TiddlyWiki

I get that and it could well be that I am underestimating that. However, anyone removing core components as suggested here would be quite aware that it requires deep knowledge of TiddlyWiki to do so, eg. to build something like a "read-only" representation.

> You are persisting in your request, and so I'm merely saying that you should do the necessary investigation to get the evidence to back up your proposal.

WinDirStat or whatever there is for mac will show you how, by packaging up things into components, so as to create something like a read-only wiki  — e.g. one w/o an EditMode (and controls), without a Editor Toolbar, with but a simple ViewMode (w/o controls), w/o a ControlPanel, or PageControls except saving and language switching, w/o Sidebar, w/o Search, advanced or simple — will reduce the core to a tiny wee footprint. By the way, the svg in **mono-block.tid** is possibly some 25kb too big for the purpose.

For something like a questionnaire which only needs editing via edittext and other widgets and then saving and perhaps language switching, I truly do not need the bulk of what currently are TiddlyWiki (ui) components and all the dependent baggage that comes with each.

I could possibly make a test and strip it down to 400k or less. So, what would be the gain of doing that exercise? That it's possible? Of course it is.

> But every core filter and parse rule is already a component, being a tiddler module. They are a type of component. They are not the unit of granularity of installation for end users, but that is for the reason given above: assembling a correct, functioning configuration of individual modules would be much harder than maintaining a configuration based on plugins.

When you've arrived at the point of wanting to do that, you very well know what to do. And you'll know that to use some filter, well, you need to have it installed.

> The point is that you already have the flexibility you need of the core being split into small pieces. The question is over the performance impact of carrying around tiddlers from the core plugin that are overridden elsewhere.

Precisely, overwriting only ever increases an already big core. I have no way to chisel.

> To be honest, your proposal of splitting the TiddlyWiki core into arbitrary clumps isn't a terribly appetising solution to the hypothetical problem: we're unlikely to choose the optimum clumping.

The purpose of the exercise would not be to ship a leaner core. The purpose would be to be able to do so, if one knowingly wanted precisely that.

> Better would be to compile the plugins within a TiddlyWiki; write a little process that whips through all the plugins, and figures out the shadow tiddlers are overridden, and simply removes them from their plugins. Rename the plugin with a suffix on the name to show what's been done, and you've got a meticulously efficient way of shipping a minimal TiddlyWiki, and we don't have to change the core architecture.

I think I might just do that, with some filter that allows me to define all the things I want removed. However, I would much prefer to be able to do that when baking / serving / building a TiddlyWiki (custom core) under node, rather than do that in the browser through some re-compile plugin that I don't even want shipped with it all.

This would not be an end-user process. It would be something designers do. There could be some browser plugin to achieve the same, surely, but that would just be the freestyle performance on top in the "because we can" category.
