### ISSUE TITLE
loading utf-16 hta tiddlywikis is broken

### ISSUE THREAD

**Issue by welford** [Jermolene/TiddlyWiki5#2615]
loading hta files still seems to work, if I change the extenstion of a TW html file to .hta the following command works:

`tiddlywiki .\tw --load .\notes.hta --output .\blog --build tag`

However if I save notes.hta using the hta file itself (this changing the format to utf-16) it no longer loads notes.hta 

I worked on this previously, would be willing to fix again, but I am about a year out of date on TW work.

original work:
https://github.com/Jermolene/TiddlyWiki5/pull/538/commits

**Comment by welford** [comment]
this looks to be fixed in latest.

**Comment by pmario** [comment]
So can this issue be closed?

**Comment by welford** [comment]
apologies, meant to close it with the last comment.
