### ISSUE TITLE
[Request] Allow Scrollable Tiddler Preview While Editing

### ISSUE THREAD

**Issue by duarteframos** [Jermolene/TiddlyWiki5#2616]
Currently while editing a tiddler, the body textarea bellow the toolbar can be resized manually or automatically, but the tiddler preview on the right is 'static' and can't be scrolled independently.
This makes it extremely difficult (if not downright impossible) to edit and see the preview of the same arbitrary part of the text at the same time, especially for long tiddlers.

My suggestion would be to make the tiddler preview div scrollable. Currently I have something like this in my stylesheet. `.tc-tiddler-preview-preview {overflow-y:scroll; height:900px;}`

However the height would ideally be the same used for the editor textarea (instead of the hardcoded `900px` I have above), but that is above my skill level.

Is this technically possible? Could the preview be automatically resizable to match the editor height, or if not at least allow manual resize perhaps?

I've read about some [changes to this area of code](https://github.com/Jermolene/TiddlyWiki5/pull/2583) so maybe this is opportune now. What do you guys think, is this desirable, would it be feasible?

**Comment by Jermolene** [comment]
Hi @duarteframos thanks; I think others including @danielo515 have raised the same issue.

The CSS solution that you propose hadn't occurred to me. I'll shortly push a fixed based on that idea.

**Comment by duarteframos** [comment]
Wow that was lightning fast!
Thanks for the quick fix, looking forward to the next version :)

**Comment by danielo515** [comment]
The idea is very useful, and It is very promising. How can I see this working? Is it on the pre release?

**Comment by Jermolene** [comment]
Hi @danielo515 

> The idea is very useful, and It is very promising. How can I see this working? Is it on the pre release?

Yes, you can see it by editing a tiddler with some longish text (like "TiddlyWiki Pre-release"), turning on the preview, and selected a fixed editor height.

**Comment by duarteframos** [comment]
Seems to be working pretty well, thanks again for the fix.
Editing will become much easier now, my mouse wheel sends thanks.

Also QRCode generation is pretty cool :smile_cat:

**Comment by sukima** [comment]
>Editing will become much easier now

Confirmed, fixed!

>Also QRCode generation is pretty cool 😸

@duarteframos, What?! Where?! OMG what is this magic?!

**Comment by duarteframos** [comment]
> What?! Where?! OMG what is this magic?!
Hehe check the [upper right corner of the tiddler toolbar](http://tiddlywiki.com/prerelease/) there's a button for QRCode generation. For the URL, raw content or parsed content

**Comment by danielo515** [comment]
I was surprised too by the existence of the qr code button. Definitely cool. Now we need a QR code tiddler importer that uses the phone camera, and BOOM a new and exciting way of sharing tiddlers without any kind of internet connection.
