### ISSUE TITLE
Portuguese translation has wrong DateFormat

### ISSUE THREAD

**Issue by nmota** [Jermolene/TiddlyWiki5#2620]
When you install the Portuguese language years show as "AAAA" and time of edit is displayed in English format.

**Comment by duarteframos** [comment]
I made the Portuguese translation (for pt_PT at least) so must have been my mistake. Thanks for the fix

**Comment by nmota** [comment]
@duarteframos  I've made a new pull request with more translations updates and a fix for this, do you mind reviewing it?

**Comment by duarteframos** [comment]
@nmota Everything seems to be in order, no objections from my part.

From my superficial review I found only one small mistake, a double-space in `languages/pt-PT/ControlPanel.multids line 112` `+Settings/InfoPanelMode/Caption: Modo painel  de informação da tiddler` between "painel" and "de".

I had already made some further updates beyond the last trunk merge that I posted in the [pt_PT translation thread at the forum](https://groups.google.com/forum/#!starred/tiddlywiki/esj5IB935oo)

I don't think Jeremy ever merged them, and they included your year date format fix. They are most likely in conflict now, but no problem.

I had a few more fixes and updates lined up to be introduced, but not sure what is the best course of action now so no conflicts are created.

Did you edit these directly through github or did you use the tiddliwiki translation edition?

Anyway many thanks for the help

**Comment by nmota** [comment]
I cloned tiddlywiki repo and used the translation edition to edit the translations then followed the instructions [here](http://tiddlywiki.com/prerelease/editions/translators/) to update the appropriate files.

I feel like I overstepped you here. Sorry for that. 

Maybe we can arrange a way so we can both collaborate on the translations.

**Comment by duarteframos** [comment]
No problem, it was my fault for not making sure it was submitted properly.

I don't really use or know how to properly use the node.js version, so I generally submit only HTML files, but a better way to collaborate or coordinate would certainly be helpful.

For now I'll until these are committed, then I'll make all the updates I had in mind
