### ISSUE TITLE
Add support for filtered attributes to HTML elements and widgets

### ISSUE THREAD

**Issue by Jermolene** [Jermolene/TiddlyWiki5#2624]
As [documented on tiddlywiki.com](http://tiddlywiki.com/#HTML%20in%20WikiText:%5B%5BHTML%20in%20WikiText%5D%5D%20%5B%5BWidgets%20in%20WikiText%5D%5D), attributes of HTML elements and widgets can take any of the following forms:

* Unquoted strings that do not contain spaces (eg `attr=value`)
* Strings quoted with single, double or triple-double quotes (eg `attr='value'`, `attr="value"` or `attr="""value"""`)
* Macro invocations (eg `attr=<<myMacro>>`)
* Transclusions (eg, `attr={{MyTiddler!!field}}`)

It is proposed to extend the syntax to support filtered attributes. This example displays the title of the current tiddler with the prefix `$:/myprefix/`:

```
<$text text={{{ [<currentTiddler>]addPrefix[$:/myprefix/]] }}}>
```

The contents of the triple curly braces is a filter string and the value assigned to the attribute is the first item in the result list, or the empty string if there were no results from the filter.

For a <20 line change to the core, I think this change will open up a lot more flexibility by allowing the flexibility of filter operations to be used to prepare attribute values and parameter values for macros.

**Comment by tobibeer** [comment]
Great idea. It should be possible to not have the list results stringified.

**Comment by Jermolene** [comment]
> It should be possible to not have the list results stringified

As per our earlier discussion, the question of stringification doesn't arise. The new triple curly braces operator returns a single item from the list, and not the entire list. Therefore it doesn't get or need quoting.

**Comment by tobibeer** [comment]
ah, didn't read carefully enough...

> the value assigned to the attribute is the first item in the result list

In that case, I believe It should be possible to have the full list results as a stringifiedList, not just the first item (why only the first?).

**Comment by Jermolene** [comment]
>  I believe It should be possible to have the full list results as a stringifiedList, not just the first item

Of course. But I don't think it would be anywhere near as useful, would it? You'd be back to the problem that you raised with the set widget (when used with a filter), whereby single results containing spaces would end up getting quoted.

> (why only the first?)

Because it's the most useful, and as you've pointed out elsewhere, one can use list operations within the filter to manipulate the result to be anything you need.

**Comment by tobibeer** [comment]
> Because it's the most useful, and as you've pointed out elsewhere, one can use list operations within the filter to manipulate the result to be anything you need.

...except a filter ...or stringified list:

```
<$vars my-filter={{{constructed from this }}}>
<$list filter=<<my-filter>>>
</$vars>
```

Of course, you wouldn't do the above, but one may need some kind of constructed, configurable filter (or list of titles) fed elsewhere, e.g. to write into some list field via action-setfield.

**Comment by pmario** [comment]
>Of course, you wouldn't do the above, but one may need some kind of constructed, configurable filter (or list of titles), e.g. to write into some list field via action-setfield.

but can't this  be done with the http://tiddlywiki.com/#ActionListopsWidget widgets, where no var is needed?

**Comment by Jermolene** [comment]
By introducing a couple of new operators, it would be easy to get a filtered attribute to return a list:

```
[tag[Hello]enquote[]join[ ]]
```

The `enquote` operator would wrap double square brackets around any entries containing spaces. The `join` operator would join all the items together (in this case, with a single space as the separator).

**Comment by tobibeer** [comment]
> but can't this be done with the http://tiddlywiki.com/#ActionListopsWidget widgets, where no var is needed?

I think the point is to be able to define the configuration elsewhere (the variable) and then use that where needed (the action).
