### ISSUE TITLE
CSS handling - wrong order

### ISSUE THREAD

**Issue by pmario** [Jermolene/TiddlyWiki5#2629]
The [base theme](https://github.com/pmario/TiddlyWiki5/blob/master/themes/tiddlywiki/vanilla/base.tid#L39) defines the [reset.css](https://github.com/pmario/TiddlyWiki5/blob/master/themes/tiddlywiki/vanilla/reset.tid) as the first element, that should be initialized. -> OK

But if you look at the browser debugger F12, you'll see, that [html: font-family](https://github.com/pmario/TiddlyWiki5/blob/master/themes/tiddlywiki/vanilla/reset.tid#L13) starts at "inline: 192". ...

It seems plugin styles are in front of the reset -> BUG

To see what's going on: use FireFox. Chrome doesn't show it. 
- go to tiddlywiki.com ..  has the problem too.
- F12 debug view
- Inspector tab. ... select any element eg: `<body>`
- have a look at the CSS rules  and scroll down to the bottom.
- click the "Inline:192" link for the html rule
- scroll up, and you'll see the CSS definitions defined in the plugins -> BUG
  - they are loaded too early. This causes strange behaviour with plugin CSS rules.

Verify the bug with different browsers:
- create a plugin that modifies html style. eg: `html { font-family: hugo; }`
- include the plugin into an edition. 
- you'll see that reset overwrites `font-family: hugo` 
  - tested with FF and Chrome on windows

**Comment by pmario** [comment]
Expected behaviour:

 - execute base.tid styles
 - execute plugin styles
 - execute theme styles. 

So imo themes should always win!

**Comment by tobibeer** [comment]
> So imo themes should always win!

I would say, plugins definitely need to come last. If they overrule other styles, including themes, then that is or must be intentional, otherwise it's a bug / poor implementation in the plugin and needs to be fixed in the plugin. In other words, a theme is a more basic overall implementation than a plugin, which is more specific. To have the generalisation overwrite the exception makes no sense from my pov.

**Comment by pmario** [comment]
In normal cases themes and plugins shouldn't interfere. A theme defines the overall "theme" so if a theme is set to dark, a plugin can't be light. ... theme needs to win. Same as in every operating system. Programs need to reflect the theme of the OS and not vice versa.

**Comment by tobibeer** [comment]
> Same as in every operating system. Programs need to reflect the theme of the OS and not vice versa.

That is simply not true. If a program comes in a totally different style than the OS otherwise presents itself, then the OS must not interfere with the program's desire to present itself that way. Whether you ike it or not is not the issue. It's the end user who decide if they enjoy a user interface that looks quite different from the default OS. For some applications, this approach is even mandatory. They want none of the OSs defaults to interfere with presentation. Or, at least they want to interfere where necessary. The OS is the base, the app implementing (on top of) it. The same is true for themes, since a theme affects the overall presentation of TiddlyWiki while the usual plugin only affects aspects of it.

**Comment by gernert** [comment]
@pmario
@tobibeer

In principle I agree with Tobias.
At the moment $:/core/ui/PageStylesheet contains:

```
<$list filter="[all[shadows+tiddlers]tag[$:/tags/Stylesheet]!has[draft.of]]">
<$transclude mode="block"/>
</$list>
```

So I use the filter used in $:/core/ui/PageStylesheet to see the order of the stylesheets in my TWs:

`<$list filter="[all[shadows+tiddlers]tag[$:/tags/Stylesheet]!has[draft.of]]"/>`

which gives in one my TWs:

$:/plugin/ajh/tiddlyviewer/stylesheet
$:/plugins/danielo/tagSearch/css
$:/plugins/danielo515/ContextPlugin/Stylesheet/results
$:/plugins/tobibeer/preview/styles
$:/plugins/tobibeer/xlist/styles
$:/plugins/tongerner/breadcrumbs/style-no-breadcrumbs
$:/themes/tiddlywiki/snowwhite/base
$:/themes/tiddlywiki/vanilla/base
$:/plugins/tongerner/uptoolbar/styles
$:/plugins/tongerner/tristate/stylesheet
$:/plugins/tongerner/toolbar/styles
$:/plugins/tongerner/tabstory/styles
$:/plugins/tongerner/layout_adjustment/styles
$:/plugins/ahahn/tinka/style
$:/themes/tongerner/bluish/styles
$:/_aa.giff/GalleryCSS
$:/_stylesheet/customtables
$:/LogStyleSheet
$:/PagedListStyleSheet
$:/PersonBookStyleSheet
$:/plugins/danielo/context/css
$:/plugins/danielo/encryptTiddler/styles
$:/TagMenuStyleSheet
Button test style
Changing default link color 
...
(the rest in alphabetical order).

In principle the stylesheets are just in alphabetical order, but note that I deliberately use list-after $:/themes/tiddlywiki/vanilla/base (to overrule theme styles) in the following plugins:

$:/plugins/tongerner/uptoolbar/styles
$:/plugins/tongerner/tristate/stylesheet
$:/plugins/tongerner/toolbar/styles
$:/plugins/tongerner/tabstory/styles
$:/plugins/tongerner/layout_adjustment/styles 

So does Andreas Hahn in his Tinka plugin:

$:/plugins/ahahn/tinka/style

Just my 2 cents.

---

At tiddlywiki.com the above mentioned filter gives:

$:/plugins/tiddlywiki/railroad/railroad-diagrams.css
$:/themes/tiddlywiki/snowwhite/base
$:/themes/tiddlywiki/vanilla/base
$:/_tw5.com-styles
$:/editions/tw5.com/doc-styles

I am confused: The last 2 don't fit in the alphabetical order and do not contain a list-after field.
Can one of you explain the order of the stylesheets here?

**Comment by pmario** [comment]
We are way OT here. The OP is about wrong behaviour of the core, which needs to be fixed. 

---------

>And, of course, plugins can define styles. And, of course, these styles at times need to overrule core theming. There is absolutely no argument here.

We can agree to disagree here.

**Comment by pmario** [comment]
>$:/plugins/tiddlywiki/railroad/railroad-diagrams.css
$:/themes/tiddlywiki/snowwhite/base
$:/themes/tiddlywiki/vanilla/base
$:/_tw5.com-styles
$:/editions/tw5.com/doc-styles

If that's the real order, it's completely wrong. ... `base` calls `normalize.css`, which is the reset. normalize must be the first CSS that's executed by the browser. 

---------

I found out, about the problem, because I want to get rid of `normalize` elements that are redundant, for my own base theme. Most of the stuff is overwritten by vanilla/base, so it doesn't need to be there at all.

**Comment by pmario** [comment]
$:/tags/Stylesheet ... dropdown allows drag and drop ordering now. So every uses can adjust to the prefered behaviour.

**Comment by Evolena** [comment]
Also #3113 should help?
