### ISSUE TITLE
feature request: floating tiddlers

### ISSUE THREAD

**Issue by tgirod** [Jermolene/TiddlyWiki5#263]
I often find myself moving back-and-forth between the tiddler I'm editing and other tiddlers I've opened. When some tiddlers are long-ish, it translates to a lot of scrolling, which is not really convenient.

This could be made easier if it was possible to float one or more tiddlers - they would move to a second column and stay visible, like the sidebar.

**Comment by giffmex** [comment]
Stroll, Muuri have multiple columns, and there are plugins for floating tiddlers. Please close this issue.

**Comment by giffmex** [comment]
> I'd like to add support for a multicolumn layout that makes use of the extra space of wider screens. I think all the pieces are already there: imagine a second story list displayed within the sidebar, and a dropdown to select which story list should be used for navigation.

Enter Stroll two years ago!

**Comment by pmario** [comment]
@giffmex A link to the latest version would be nice.

**Comment by pmario** [comment]
@Jermolene ... bump for close. There are is the BTCs multi column wiki, which imo does what the OP requests and a lot more. see: https://burningtreec.github.io/tiddlywiki-multi-columns/

**Comment by Jermolene** [comment]
Thanks @pmario
