### ISSUE TITLE
Modals do not accept macros

### ISSUE THREAD

**Issue by yuzijie** [Jermolene/TiddlyWiki5#2633]
Hi,

I have noticed that when tiddlers are shown as modals, macros such as `tabs` will vanish. It seems that custom macros can not be displayed in modals. Please check on that, thanks.

**Comment by Jermolene** [comment]
Hi @yuzijie thanks for the ticket, I guess you found now that this problem has been fixed for v5.1.14:

https://github.com/Jermolene/TiddlyWiki5/commit/87fa7f972cae859c466dea8a531d50f060e7d910
