### ISSUE TITLE
Week calculation fails between 23:00 and 24:00

### ISSUE THREAD

**Issue by pmario** [Jermolene/TiddlyWiki5#2634]
see issue: https://groups.google.com/forum/#!topic/tiddlywiki/t7hl4BI2W1k
and my suggestion: https://groups.google.com/d/msg/tiddlywiki/t7hl4BI2W1k/8ra5fVQqAAAJ

some more test needed. PR is incoming

**Comment by pmario** [comment]
see PR #2635

**Comment by Jermolene** [comment]
@pmario It would be much appreciated if you could include a full description for issues like this rather than relying on links.
