### ISSUE TITLE
Static html export: internal and external links not working

### ISSUE THREAD

**Issue by Suzy1970** [Jermolene/TiddlyWiki5#2636]
The static html export of an entire Tiddlywiki does not have working / clickable links, both external and internal - this is the latest version Tiddlywiki (5.1.13). I am using Firefox to export it (latest version - 50.0).

**Comment by Jermolene** [comment]
Hi @Suzy1970 that's strange. I couldn't duplicate the problem with the following steps performed with Firefox 50.0 (macOS):

1. Visit http://tiddlywiki.com/
2. Select "Tools" tab in right hand sidebar
3. Choose "Export All" icon
4. Choose "Static HTML" menu item (it takes a few seconds to generate the HTML file)
5. Open the HTML file in Firefox, and click links to navigate between tiddlers

Perhaps there's an add-on interfering with things?

**Comment by Suzy1970** [comment]
It worked for me when exporting http://tiddlywiki.com/ as static html files, so not a Firefox issue there. I don't have any plugins installed in my own TW though. I tried importing a json from my own TW into a new TW download, but same result - links not working.

**Comment by Jermolene** [comment]
Hi @Suzy1970 might you have some custom style definitions? If you're able to share one of the static HTML files I'd be happy to examine it.

**Comment by Suzy1970** [comment]
I do have a few custom styles but I deleted the tiddler with them and it makes no difference! I have attached the exported html file (with custom css) - had to put it in a .zip:
[twProgramTipsstatic.zip](https://github.com/Jermolene/TiddlyWiki5/files/601817/twProgramTipsstatic.zip)

**Comment by Jermolene** [comment]
Hi @Suzy1970 great, it turns out that the problem is subtle :)

One of your tiddlers appears to include the string `<html contenteditable="true">` such that it is being rendered directly (ie it is not in a code block). The browser is then honouring the contenteditable attribute for the entire page. That means that clicking on links positions the cursor to edit, rather than following the link.

I'd be interested to see the source text of the tiddler in question. Hopefully, the solution will be to wrap backticks around the string above.

**Comment by Suzy1970** [comment]
That was the issue! It was a line in the tiddler "Turn any browser tab into a basic text editor" - in this paragraph:

Unbeknown to many, a (very) simple text editor is built directly into the Chrome browser. Enter **data:text/html, &lt;html contenteditable&gt;** in your browser’s omnibox and you’ll be presented with an editable page just like Notepad and TextEdit. You can even save the document (as an html page) by hitting Ctrl+S. It’s worth bookmarking the link – although it’s basic it will work 100 percent of the time, giving you a fail-safe option in an emergency.

I put backticks around the bolded sentence (**data:text/html, &lt;html contenteditable&gt;**) and now the links work in the exported static html file. I copied and pasted that from a website, and would not have thought to look for that as a problem! (I notice that it has the same issue here when copying and pasting that code - have to escape the angled brackets - `&lt; &gt;` - to avoid the code being read literally.)
