### ISSUE TITLE
Multids format is failing on latest 5.1.14

### ISSUE THREAD

**Issue by danielo515** [Jermolene/TiddlyWiki5#2652]
For some reason a multid tiddler with this config:

```
title: $:/
# put here simple configurations of tw general

config/Plugins/Disabled/$:/plugins/danielo515/tiddlypouch: yes
```

Generates the following tiddler:

```html
<div title="$:/config/Plugins/Disabled/$">
<pre>plugins/danielo515/tiddlypouch: yes</pre>
</div>
```

As you can see, it is taking the `:/` as newline. I don't know why

**Comment by pmario** [comment]
The first colon `:` is the problem. .. Did it work with .13?

**Comment by danielo515** [comment]
Yes, absolutely. In fact, it broke the building process of NoteSelf, which worked until I  upgraded. 
Why are colons a problem? They are valid in tiddler's titles 
Regards.

**Comment by Jermolene** [comment]
Hi @danielo515 TiddlyWiki has always looked for the first colon; your example has always been interpreted as the key `config/Plugins/Disabled/$` and the value `/plugins/danielo515/tiddlypouch: yes`. Think about it; how could the system possibly know that the second colon should be the delimiter, and not the first?

**Comment by danielo515** [comment]
Hello @jermolene 
Of course I will think about it, and opening this issue is the first step, but I think that some others should think about it too. It could be as simple as taking the latest colon as delimiter, because that is what it is. 
The thing  that we should think about is that colons are valid as part of tiddler titles, and are actively used by the core. Multid format should be able to support it

**Comment by Jermolene** [comment]
Hi @danielo515 

>  It could be as simple as taking the latest colon as delimiter, because that is what it is.

That change would break backwards compatibility:

```
something: This is some text: it includes a colon
```

In a situation like that, your suggestion would end up with a title of `something: This is some text` and text of `it includes a colon`.

Do we at least agree that the current behaviour has not in fact changed in any recent version?

> The thing that we should think about is that colons are valid as part of tiddler titles, and are actively used by the core. Multid format should be able to support it

I'd be happy to consider a workable proposal.

**Comment by pmario** [comment]
@danielo515 ... did you solve this problem?

**Comment by Jermolene** [comment]
Thanks @danielo515 @pmario I think this can be closed in the absence of an actionable proposal.
