### ISSUE TITLE
Feature request: Rename tags globally

### ISSUE THREAD

**Issue by jstamant** [Jermolene/TiddlyWiki5#2655]
It would be nice if users could rename existing tags through the tag manager.

I'm new to TiddlyWiki. So far I'm really liking it, but I immediately noticed from setting up a table of contents, that renaming nodes in my tiddler hierarchy is going to be tedious.

Right now, the only way I know how to rename a node in my ToC is by changing its title and changing the equivalent tag in all of its child tiddlers. This could be simplified so much by allowing me to change the tag globally from the tag manager.

Perhaps a simpler example could be that I have 100 action items tagged as `to-do`, but I'd like to change that tag to `TODO`. Manually re-tagging them all is clearly not the solution...

**Comment by gernert** [comment]
It can be done in wikitext, see https://groups.google.com/d/msg/tiddlywiki/OCntQ79DuwM/_vYCTYRXfaUJ
(Also available in my toolbar plugin http://tw5toolbar.tiddlyspot.com/)

**Comment by Jermolene** [comment]
Thanks @jstamant. Fixed for v5.1.14 in:

https://github.com/Jermolene/TiddlyWiki5/commit/e8bb897e263feea1a671ce035af68d0c6bc246b5

You can try out the new feature at http://tiddlywiki.com/prerelease

**Comment by tjfwalker** [comment]
v5.1.14 is now the current release, warranting the closure of this issue, right?

**Comment by Jermolene** [comment]
Thanks @tjfwalker :)
