### ISSUE TITLE
Feature Request: Local file saving

### ISSUE THREAD

**Issue by zeigerpuppy** [Jermolene/TiddlyWiki5#2656]
Is it possible to save files for a TiddlyWIki to a local file storage.I would like to do this for security and then sync the files manually.  Ideally no data should pass to the web, only be saved locally.

**Comment by pmario** [comment]
Hi, have a look here: http://tiddlywiki.com/#TiddlyWiki%20on%20Node.js:%5B%5BTiddlyWiki%20on%20Node.js%5D%5D%20TiddlyDesktop

**Comment by zeigerpuppy** [comment]
Thanks, that looks great!

**Comment by pmario** [comment]
hi, is the issue still valid. If not please close it.

**Comment by pmario** [comment]
@zeigerpuppy ... bump

**Comment by Jermolene** [comment]
Thanks @pmario
