### ISSUE TITLE
Problem after upgrade

### ISSUE THREAD

**Issue by mrvmeck** [Jermolene/TiddlyWiki5#2661]
I use TW5.  I have several Tiddlywiki files that I use in my business, which I access through Dropbox primarily using a desktop computer and a laptop.  My operating system is Windows 10.

After I upgraded from Tiddlywiki version 5.1.11 to 5.1.13, I ran into a problem that I have been unable to correct using the usual fixes.  The problem is difficult to describe.  Essentially, the programs acts as though there are two screens operating over the top of each other.  Upon opening, the left panel opens two identical sets of the tiddly's that I have set to open when the program initializes.  In the right panel, which has the default menu with a few modification, the two tiddlies overlap each other.  I move one, and the other remains in place.  The links in that panel do not appear to function.  To help with my explanation, I have provided the following screenshot. (I don't usually use screenshots, so I hope that I provided it correctly.)

![screenshot 2016-12-15 06 45 15](https://cloud.githubusercontent.com/assets/13434552/21226338/42710122-c292-11e6-8b3c-2d43c013460b.png)

I use a second Tiddlywiki for different purposes.  I upgraded that Tiddlywiki also, and that file appears to have the same problem.  On my desktop computer, I did something yesterday that caused the problem to correct itself, but I have been unable to reproduce that result, and I'm not sure exactly what action caused the change.  

For the moment, I have returned to the earlier version.  I'm sure that there is a solution, but it may be beyond my ability.

Can you help?

Mervin Mecklenburg

**Comment by pmario** [comment]
**Make a backup first!** ... Messing around with page-templates may "brick" your wiki!!

If you open the tiddler named: `$:/core/ui/PageTemplate/sidebar`   it will look similar to your screenshot. 

So did you change something in the sidebar page template? any plugin, that does?

Did you change: `$:/core/ui/SideBarLists`

Just guessing. It's hard to say what's going on, with just a screenshot. 

The easiest way to see which shadow tiddlers have been changed is: 

 - open: `ControlPanel: Info: Basics`  tab
 - see: "Number of overridden shadow tiddlers:" in the tab. (last value)
 - click the search icon. .

check those tiddlers.

**Comment by Jermolene** [comment]
Hi @mrvmeck the screenshot looks like what happens if you try to save changes using Firefox's File/Save menu item. If so, the easiest fix is to import your wiki into a blank empty wiki (or use the upgrade wiki).

**Comment by pmario** [comment]
@mrvmeck ... could you fix your problem. If yes, please close the issue!

**Comment by Jermolene** [comment]
Thanks @pmario
