### ISSUE TITLE
Unable to configure TiddlyWeb plugin

### ISSUE THREAD

**Issue by opennota** [Jermolene/TiddlyWiki5#2674]
Starting from an "empty" `index.html`, I install the "TiddlyWeb and TiddlySpace components" plugin, then go to the control panel and enter `http://localhost:8080/` into the "Host configuration" field in the Server tab. After that, neither the Login button nor the Refresh button do not work, and when I save changes and reload the wiki, there's no more "TiddlyWeb and TiddlySpace components" plugin in the plugin list. And the server does not ever receive any requests. Tried both Firefox and Google Chrome browsers.

**Comment by pmario** [comment]
Hi, Which configuration did you try?
Please share a link.

**Comment by opennota** [comment]
I'm not sure I understand. All I do is fill in this form: http://i.imgur.com/H7rKiJQ.png

**Comment by opennota** [comment]
Ah, got it. For TiddlyWeb to work you need to download index.html from a server, not open locally. And then there's no need to touch the host configuration.

**Comment by tobibeer** [comment]
@opennota, can you please put a small summary together of what it was you actually tried to achieve here? I'm failing to grasp the bigger picture. Thank you. :-)

**Comment by opennota** [comment]
@tobibeer 
I'm writing a server like [rsc/tiddly](https://github.com/rsc/tiddly), but self-hosted, not for GAE.
