### ISSUE TITLE
EditTextWidget behaviour when targeted field is missing

### ISSUE THREAD

**Issue by suiryc** [Jermolene/TiddlyWiki5#2680]
Hi,

The EditTextWidget comes with a `default` value which is _The default text to be provided when the target tiddler doesn't exist_. For other widgets (like SelectWidget or CheckboxWidget), it is the value to use when the target field is missing.
So for example if the tiddler exists but the field is missing, `default` kicks in for the latter widgets but not EditTextWidget.

Shouldn't the behaviour be the same for all those kind of widgets ? That is
* for the `text` field, which is the tiddler itself, use the `default` if the tiddler is missing
* for other fields, use the `default` if the targeted field is missing (even if the tiddler itself exists)
* for indexes, use the `default` is the targeted index is missing

Actually there is also the RadioWidget to take into account (does not seem to handle a `default` value), and I believe the SelectWidget copes for a missing field but not a missing index.

**Comment by tobibeer** [comment]
Here's a question I would ask in return: When did this pose a problem to you?

I think it makes sense for the SelectWidget to cover both cases, missing tiddler or field, which I think also holds true for the CheckboxWidget.

As for the EditTextWidget that is not the case, since the target field might literally be an empty string.

The RadioWidget lacks a default for a good reason, the reason being that it is only shown as active when the target reference matches in value.

**Comment by suiryc** [comment]
> any other scenarios?

Not that I can think of at the moment.

As explained in my example (see previous comment), a missing field other than `text` (which represents the tiddler itself somehow) behaves the same as having the field with an empty value as far as the EditTextWidget is concerned.

A little exemple to test:
```
<$checkbox tiddler="$:/temp/test" field="field-1" checked="true" unchecked="false" default="true"> Option 1</$checkbox>

<$edit-text tiddler="$:/temp/test" field="field-2" default="Some default value"/>

<$select tiddler="$:/temp/test" field="field-3">
<option value="1">Choice 1</option>
<option value="2">Choice 2</option>
</$select>
```
If you select a dropdown value or uncheck the checkbox, the text (default) value disappears.

**Comment by tobibeer** [comment]
Thanks for explaining, makes sense to me and I don't see a reason not to fix this

So, to sum it up, the actionable bit here would be:

### For the EditTextWidget, the default should apply not only if the target tiddler is non-existing but also when the applicable *field* or *index* are non-existing.

**Comment by pmario** [comment]
@suiryc ... I did just test the different default settings with TW v5.3.1. 

- The edit-text widget works exactly as you described it. So it's as intended
- The CheckboxWidget does have a lot more options now than in 2016
  - So checkout the new examples. There are a lot of them: https://tiddlywiki.com/#CheckboxWidget
- The RadioWidget seems to work as expected. 

>After reading your response I suddenly realise I don't really know how TiddlyWiki actually handles a missing field vs. a field with an empty value. I hoped it would be seen as two different situations, since it indeed also makes sense to have an empty string as value.

If a tiddler and the field exist but the field is empty -> That's a valid state -- as you "hoped" ;)

@suiryc ... I think this issue could be closed.

**Comment by suiryc** [comment]
@pmario Indeed, compared to 2016, the edit-text widget works as expected, and more options have been added to other widgets :)

Thanks
