### ISSUE TITLE
Export "normal" tiddlywiki to node.js-version of tiddlywiki

### ISSUE THREAD

**Issue by gesundelehre** [Jermolene/TiddlyWiki5#2688]
Can someone help me with that and tell me how i should go about doing this? I have not really an idea how i should go about it. Should i export all tiddlers somehow and them import them afterwards again? If so, how do i go about it in the most easy way?

Thanks in advance, Greetings

**Comment by ibnishak** [comment]
Did you try starting an empty NodeJs TW5 in browser and dragging & dropping the single html file version (the "normal" tiddlywiki) to it?

**Comment by gesundelehre** [comment]
how should i drag the file to it?

PS: i also should find a way for all the plugins to also be imported as well to the node.js-version

Thanks in advance

**Comment by Jermolene** [comment]
Hi @gesundelehre 

> how should i drag the file to it?

Use your file manager (ie Finder on Mac, Explorer on Windows) to drag the file into the browser. You should see a green bar at the top of the TiddlyWiki window as you drag the file.

**Comment by gesundelehre** [comment]
Thanks it worked.
I'll now close this thread.
