### ISSUE TITLE
each Operator should contain unique keyworkd

### ISSUE THREAD

**Issue by danielo515** [Jermolene/TiddlyWiki5#2689]
The each Operator can be used to select unique values on a list.
When someone wants such a thing, usually looks for list and unique. The first term appears, but the second, which is the most important one, does not. I think it would help discovery of this functionality to include a sentence about using each operator to create list of unique elements.

Regards

**Comment by tobibeer** [comment]
This should possibly a separate tiddler, e.g. under **Learning**.

**Comment by danielo515** [comment]
Thank you @Jermolene !
