### ISSUE TITLE
Replacement icon for timestamp on/off

### ISSUE THREAD

**Issue by telmiger** [Jermolene/TiddlyWiki5#2690]
As a follow-up to a discussion with @Jermolene [here](https://github.com/Jermolene/TiddlyWiki5/commit/d1121787c090ec8f5fc592b83c3dbad1075fe0ec#commitcomment-20333934) I propose to replace the icons for the new timestamp on/off function with a stopwatch instead of an hourglass. 

Here is a screenshot showing the two icons and another one showing them in context with others from the core icon set:

<img width="47" alt="bildschirmfoto 2017-01-02 um 11 23 21" src="https://cloud.githubusercontent.com/assets/3194567/21587538/eb65e884-d0dd-11e6-8ecc-09ca3211647d.png">

<img width="281" alt="bildschirmfoto 2017-01-02 um 11 22 59" src="https://cloud.githubusercontent.com/assets/3194567/21587541/f0218dd8-d0dd-11e6-8e57-382a2e763ce9.png">

I hold back further explanations as I think the icons should speak for themselves.

You can get the icons from http://tid.li/tw5/hacks.html#timestamp-on6.svg and http://tid.li/tw5/hacks.html#timestamp-off6.svg if you would like to test in your own wikis.

Let me know if you see potential for improvements. If you like my icons, I would be happy to submit them in any convenient form!

**Comment by Jermolene** [comment]
Hi @telmiger the stopwatch works well, and the "pause" icon is ingenious and effective.

In terms of consistency with the other icons, there are a couple of issues:

* The brush width for the stroked circle looks a tiny bit narrower than the remaining icons. The existing core icons are designed at 128x128, with most lines being 16 wide
* The three floating buttons at the top of the stopwatch are quite square; I wonder if they could be rounded off, like the top of the existing clipboard icon?
* The hand of the stopwatch is similarly quite spiky. I wonder if we can round off the fat end of the hand, leaving the point as it is?

Finally, might it be possible for the outline of the two states of the icon to be distinct. Maybe losing the buttons in the paused state?

**Comment by telmiger** [comment]
Hi @Jermolene, thank you for the feedback!

Here comes version 7 with adapted stroke width and general size, rounded buttons (completely round) and rounded hand. New icons in the upper rows:

<img width="268" alt="bildschirmfoto 2017-01-02 um 14 25 17" src="https://cloud.githubusercontent.com/assets/3194567/21590008/1522225e-d0f8-11e6-884e-61c6afbc7719.png">

The change I like best personally is the start and stop buttons disappearing in paused state!

Preview also on: http://tid.li/tw5/hacks.html#Icon%20Test

What remains to be done:
* the hand looks somewhat smaller now so I would try to make it a bit bigger
* reduce file size

**Comment by Jermolene** [comment]
Hi @telmiger looks great thanks

> reduce file size

https://jakearchibald.github.io/svgomg/ is handy; I keep meaning to write a script to apply it to all the core images

**Comment by danielo515** [comment]
Dear @jermolene it would be very useful if you share your procedure/settings for creating compatible tiddlywiky icons. I usually spend a lot of time trying to make them work. 

Thanks and regards

**Comment by Jermolene** [comment]
Hi @danielo515 in which part of the process do you run into difficulties?

Briefly, I use a macOS app called Sketch to create the individual SVG files. Each icon should be square, and the major line width should be an eighth of the width/height. Then I open the SVG files in a text editor and manually convert them to the .tid format you see in core/images by prepending the field information, removing the `<xml>` tag, and adjusting the size in the `<svg>` tag to 22pt by 22pt.

**Comment by danielo515** [comment]
Hello @Jermolene ,
I use inkscape which adds a lot of boilerplate, even in the simplified+condensed SVG format.
I usually follow the same workflow as you, but several times I have positioning and view-port issues. The main problem usually is that inkscape applies transformations, which makes adaptation to tid format harder.

**Comment by telmiger** [comment]
This was done a long time ago.
