### ISSUE TITLE
Text of global macros is not loaded when using TiddlyWeb plugin

### ISSUE THREAD

**Issue by opennota** [Jermolene/TiddlyWiki5#2693]
TiddlyWeb plugin loads an array of skinny tiddlers from the server. Some of these tiddlers can be global macros (that is, the tiddlers with the `$:/tags/Macro` tag), but their text is not loaded, so any calls to these macros return nothing. At least, until you open the tiddler with the macro, which triggers the loading of the full tiddler.

I'm not sure if the TiddlyWeb plugin should load the fat macros itself, or the skinny list of tiddlers sent by the server should contain the fat tiddlers if they are tagged `$:/tags/Macro`.

**Comment by tobibeer** [comment]
I would agree that tiddlers matching certain filters should never be returned skinny, e.g.

```
[all[current]tag[$:/tags/Macro]]
```

**Comment by opennota** [comment]
Thanks. I think I can live with that.

**Comment by tobibeer** [comment]
@opennota: Not sure, since you closed the issue, did I actually mention a capability that already exists?

**Comment by opennota** [comment]
@tobibeer 
User-defined filters to force non-skinny loading? I don't know.
A TiddlyWeb-compatible server which forces macros to be non-skinny? Yes.

**Comment by Jermolene** [comment]
> A TiddlyWeb-compatible server which forces macros to be non-skinny? Yes.

That's correct: the current design assumes that the server will bake into the HTML file those tiddlers that are required for startup.

**Comment by danielo515** [comment]
This does not only affects TiddkyWeb, it affects any mechanism that uses a sync adaptor, for example Tiddlypouch or any other similar. While I agree that this can be addressed directly on the sync adapter (or the server) in the specific case of the macros can be easily fetched once tiddliwiki has started.
In any case, documenting this on the developer edition, on the sync adapter section would be very helpful. 

Regards

**Comment by rsc** [comment]
FWIW, in response to https://github.com/Jermolene/TiddlyWiki5/issues/2693#issuecomment-270177227, in the case of $:/tags/Macro, it is not required that they be in the HTML; they can also be included in full in the "skinny" tiddler list. I'd actually prefer to put them in the HTML for the rsc/tiddly server, but I haven't worked out how to modify the initial HTML to insert/remove/update tiddlers yet. (I'm sure it's not too hard, just haven't tried.)
