### ISSUE TITLE
What is the default mode of transclude widget?

### ISSUE THREAD

**Issue by danielo515** [Jermolene/TiddlyWiki5#2696]
The definition of the mode is here:

https://github.com/Jermolene/TiddlyWiki5/blob/master/editions/tw5.com/tiddlers/widgets/TranscludeWidget.tid#L19

But it does not says what is the default state. I think that it was block, but I can't remember it and documentation is not clear.

**Comment by Jermolene** [comment]
Hi @danielo515 the default setting depends upon whether the widget itself is being parsed in block or inline mode. That's what this paragraph is trying to say:

> Usually, the mode is determined by whether the transclude widget itself has been parsed in block or inline mode. This can be overridden with the mode attribute.

So, this will transclude in block mode:

```
I am a paragraph.

<$transclude tiddler="Another tiddler that will be transcluded in block mode"/>

I am another paragraph.
```

But this will transclude in inline mode:

```
I am a sentence. <$transclude tiddler="Another tiddler that will be transcluded in inline mode"/>. I am another sentence.
```

**Comment by danielo515** [comment]
Ok, I just went directly to the parameters tab, I did not saw that sentence.

**Comment by pmario** [comment]
can the issue be closed?

**Comment by danielo515** [comment]
Sure, but keep in mind that it is a bit confusing as it is now.
