### ISSUE TITLE
TW Documentation: please, please, please add more examples

### ISSUE THREAD

**Issue by braykov** [Jermolene/TiddlyWiki5#2699]
The docs have such a fine and elaborate syntax, yet examples are so scarse.
Please add examples alongside. I spent hours searching how to construct a filter where it would list tidllers having one tag OR another. I gave up.
Tips are welcome.

**Comment by Jermolene** [comment]
Hi @braykov I agree that the documentation would benefit from more examples. The way that things work is that those enhancements need to be contributed by individuals in the community.

I'm closing this ticket because it is not directly actionable. There's an ongoing discussion about documentation on the mailing list; that's probably the best place to make this request.

**Comment by braykov** [comment]
OK, I understand.

**Comment by tobibeer** [comment]
Rather than examples buried at filter documentation, I thinkthi AND, OR or NOT logic, etc for filters deserves its own tiddler under *Learning*.

**Comment by braykov** [comment]
My problem with all the docs is that it has a perfect Search feature, but I couldn't find anything using it.
I tried "list" "filter" "tag" "OR", etc. and it just lead me to tiddlers I was not looking for.
After spending a huge amount of time browsing blindly I found the "Introduction to filter notation" tiddler which never actually showed in my search results. So the magic word was "combination" :)
I know this is not the place to discuss, sorry. Just wanted to explain the problem.

**Comment by Jermolene** [comment]
Hi @braykov I'm inclined to agree about the limitations of search; I find it handy when I know what I'm looking for, but not very useful for exploring.

In this case, the table of contents might have been the most use; clicking "Reference", then "Filters" brings up a tiddler with a prominent link to `Introduction to filter notation`.

**Comment by braykov** [comment]
Not at all. The Search is great. I should tell you it is the only best feature all in our team like about TW.
I am trying to force them to use it, but everything except the Search is "still damn too complex". So I am appointed to take care of the TW documents and the others just read it.
Regarding the filtering I was looking for, I think there is something about organisation. 
I went through titles like "Filters", "Filter Operators", "tag Operator" and "tag Operator (Examples)" but they were no use for me because non of them referred the place I was looking for. There should be something like "For more info see: "this" or "that". Or another type of breadcrumbs leading me to related examples or higher level of explanation (like "Intro ...")
I know, I should have joined the Hangouts :-)
