### ISSUE TITLE
Please allow variable number of arguments for macros

### ISSUE THREAD

**Issue by Skeeve** [Jermolene/TiddlyWiki5#270]
Sometimes it could be helpful could we have a variable number of arguments to a macro.

As far as I know, javascript supports this: http://stackoverflow.com/questions/2141520/javascript-variable-number-of-arguments-to-function

**Comment by tobibeer** [comment]
@Skeeve as this is particularly useful for developers, did you make a pull request already or did this get lost in the backlog?

**Comment by Skeeve** [comment]
https://github.com/Jermolene/TiddlyWiki5/pull/277

**Comment by felixhayashi** [comment]
Nice! Thanks @Skeeve 

So I guess I can remove this from my code... :smirk:

    // unfortunately tw forces us to specify params in advance so I will
    // reserve some argument slots here.. lets say five.
    exports.params = (function(maxArgs) {
      var arr = [];
      for(var i = 0; i < maxArgs; i++) {
        arr.push({ name : ("arg" + i) });
      };
      return arr;
    })(5);

-Felix

**Comment by Skeeve** [comment]
Am 16.01.15 17:18, schrieb Felix Küppers - notifications@github.com:
>
> Nice! Thanks @Skeeve <https://github.com/Skeeve>
>
> So I guess I can remove this from my code... :smirk:
>
>
|I do guess so too.|

**Comment by tobibeer** [comment]
@Skeeve 

* I'm a little lazy today, so: How to use this precisely?
    * Can you give an example and perhaps put it up on the documentation?
* Perhaps this issue can be closed then.

**Comment by Skeeve** [comment]
Am 16.01.15 17:39, schrieb Tobias Beer - notifications@github.com:
>
> @Skeeve <https://github.com/Skeeve>
>
>   * I'm a little lazy today, so: How to use this precisely?
>       o Can you give an example and perhaps put it up on the
>         documentation?
>   * Perhaps this issue can be closed then.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/Jermolene/TiddlyWiki5/issues/270#issuecomment-70281366>.
>
The issue is closed as far as I know and not only you are lazy, me too ;)

https://javascriptweblog.wordpress.com/2011/01/18/javascripts-arguments-object-and-beyond/

**Comment by tobibeer** [comment]
Ah, yes, it's closed... all the way up. Anyhow, not trying to reverse engineer what's happening at this point. I'd rather like to see some specifics and examples on how parameter parsing works ad what is exposed and how (to a js macro or wikitext macro) what isn't, see #1373.

A little something like that: http://paramparser.tiddlyspace.com ...only just tw5.
