### ISSUE TITLE
No Tiddler Renaming For New Tiddler

### ISSUE THREAD

**Issue by tobibeer** [Jermolene/TiddlyWiki5#2700]
When creating a new tiddler, the new "tiddler renaming" section with the checkbox in the edit-template must not be displayed for tiddlers that are only just being created, i.e. non-existing.

**Comment by Jermolene** [comment]
> When creating a new tiddler, the new "tiddler renaming" section with the checkbox in the edit-template must not be displayed for tiddlers that are only just being created, i.e. non-existing.

Hi @tobibeer it's already the case that the renaming checkbox doesn't appear for a newly created tiddler. Have you run into a situation where it doesn't work properly?

**Comment by tobibeer** [comment]
@Jermolene, looks like I not only did bake *tb5* on some outdated prerelease state but that the current version does not show this behavior anymore.

**Comment by Jermolene** [comment]
Cheers @tobibeer
