### ISSUE TITLE
invoke actions when clicking external link

### ISSUE THREAD

**Issue by tobibeer** [Jermolene/TiddlyWiki5#2711]
**PJO** [wishes to track, how often he or she clicked an external link](https://groups.google.com/forum/?fromgroups=#!topic/tiddlywiki/xEZSQvaNpqg).

@pmario suggests a new message along the lines of **tm-navigate-external-link**, which I believe I prefer.

@Jermolene comments:

> The element widget doesn't include any event handlers, so we'd need a special "open external link" widget.

**In other words, both of the below suggestions initally suggested are more or less inadequate...**

----

For that, we could extend [$:/core/modules/parsers/wikiparser/rules/prettyextlink.js](https://github.com/Jermolene/TiddlyWiki5/blob/master/core/modules/parsers/wikiparser/rules/prettyextlink.js) to allow specifying **actions**, e.g.:

```
[ext actions=variableName[<title>|<url>]]
```

Would that be something we want in the core? Then I might go ahead and make a PR.

----

Overloading as in the below suggestion appear to be preferable as by @Jermolene's [comment](https://groups.google.com/d/msg/tiddlywiki/xEZSQvaNpqg/xFs99cbQEwAJ).

Another possible solution could be to extend the core ButtonWidget to allow the click event to propagate down to any `[ext[<url>]]` it contains. Currently, this appears to be prevented. At least, trying the below on [tb5](http://tobibeer.github.io/tb5) using the **calc** macro doesn't work:

```
\define link() [ext[$(url)$]]
\define logtid() $:/logs/$(url)$

<$vars url="http://google.com">
<$tiddler tiddler=<<logtid>>>

<$button class="tc-btn-invisible">
<<link>>
<$list filter="[<logtid>has[text]]">
<$action-setfield $text=<<calc !!text +1>>/>
</$list>
<$list filter="[<logtid>!has[text]]">
<$action-setfield $text="1"/>
</$list>
</$button>

<$link><$view field="title"/></$link>
</$tiddler>
</$vars>
```

**Comment by ibnishak** [comment]
Another approach would be creating a widget in the lines of [$:/core/modules/widgets/link.js](http://tiddlywiki.com/#%24%3A%2Fcore%2Fmodules%2Fwidgets%2Flink.js) for external links. This will allow usage of similar attributes as link widget for external links and keep things uniform. Actions can be declared under a button widget wrapped by the proposed external widget.

Nevertheless bringing actions attribute to more stuff is always welcome. Having Select/radio/checkbox widgets to have the same would be wonderful, in lines of Jed's invoke actions plugin.

**Comment by ibnishak** [comment]
Another possible approach to same issue would be creating a external link widget in the lines of existing [link widget](http://tiddlywiki.com/#%24%3A%2Fcore%2Fmodules%2Fwidgets%2Flink.js) with same or similar attributes. When you want to invoke actions, you can do it the same way existing link widget invokes it, which is by stacking them inside button widget and wrapping the button widget with link widget. eg:
```
\define myactions()
<$action-setfield $tiddler="$:/state/sidebar" text="no"/>
\end

<$link to="HelloThere">
<$button class="tc-btn-invisible tc-tiddlylink" actions=<<myactions>>>
HelloThere
</$button>
</$link>
```

This has the added advantage of keeping things uniform.

Nevertheless, bringing action attribute to more and more items is always welcome. Select/radio/checkboxes can also do well with actions in line with invoke actions plug-in by Jed.

**Comment by tobibeer** [comment]
Thanks for the feedback, @ibnishak. I don't think nesting buttons within links should be a recommended practice.

I'm also not sure that a dedicated new widget is warranted for this usecase alone.

**Comment by pmario** [comment]
>Would that be something we want in the core? Then I might go ahead and make a PR.

I personally don't want to support tracking behaviour built into the core. This is clear plugin territory. 

There may be plugins for google analytics and preferably piwik, since they do respect the users "do not track" settings. If the TiddlyWiki core would start to spy on users, I consider this "toxic" behaviour. 

just my 2 cents. 
-mario

**Comment by tobibeer** [comment]
In his post PJO did not mention an external services. He mentioned counting his own clicks.

**Comment by Jermolene** [comment]
Hi @tobibeer the new parse rule is not in itself sufficient; we'll need some combination of widgets with the required functionality. Otherwise, what sequence of widgets would the new parse rule generate?

**Comment by tobibeer** [comment]
@Jermolene, ah, I understand... there is no (widget) event to intercept. There only are `<a/>` elements which we can only intercept via some window.click handler and inspecting the target. Not sure, would that be the element widget in that case? So, possibly far too generic to handle an exotic usecase like this.

**Comment by Jermolene** [comment]
The element widget doesn't include any event handlers, so we'd need a special "open external link" widget.

**Comment by tobibeer** [comment]
From what I can see, #2721 covers this well.

**Comment by pmario** [comment]
@Jermolene ... Just stumbled upon this issue ... IMO it can be closed since it's old and we actually did merge a related PR  #2721

**Comment by Jermolene** [comment]
Thanks @pmario
