### ISSUE TITLE
filter allowing duplicates

### ISSUE THREAD

**Issue by tobibeer** [Jermolene/TiddlyWiki5#2713]
Is there any way to pass a filter string to the core and have titles returned with duplicates? Looking at [filterTiddlers](https://github.com/Jermolene/TiddlyWiki5/blob/master/core/modules/filters.js#L158-L161), I am not seeing how this would be possible.

I want the user to be able to specify a list of values using a filter, e.g. `1 2 3 4 5 4 3 2 1` whereas the list is to be returned exactly as it is, with duplicates.

How to do?

This is crucial for fetching a list of values, rather than a set of values.

The filter could also be:

```
[tag[foo]get[my-special-value-field]]
```

So, the point is, that I want / need as many values as there are titles. ❗️ 

## Suggested Solution

Perhaps use: `{{list{ 1 2 3 4 5 4 3 2 1 }}}` ...at least for the filtered transclusion? Not sure how to make existing filter declarations "list-aware".

## Background

I'd be releasing a neat little sparklines plugin, but w/o a reliable mechanism to **generate** a **list** of values from a filter, I don't think I want to / should release it just yet.

**Comment by tobibeer** [comment]
I guess this is a duplicate of #2097.

**Comment by tobibeer** [comment]
re-opening this in hopes of coming to a simple solution, quickly

**Comment by tobibeer** [comment]
Perhaps as...

```
{{list{ 1 2 3 4 5 4 3 2 1 }}}
```

?!?

**Comment by pmario** [comment]
I think at the moment, there also is a sort() function associated with every list. ... I'll post a link to the source if I find it. ... So will be a pretty tough change, to get it backwards compatible.

**Comment by tobibeer** [comment]
With a new syntax there is no backwards compatibility issue.

**Comment by pmario** [comment]
>With a new syntax there is no backwards compatibility issue.

I can't find the code atm, but the core has some hardcoded sorting and de-duplication going on.

**Comment by CodaCodr** [comment]
See this group discussion:

https://groups.google.com/forum/#!topic/tiddlywiki/KzDgSIrPOXI

**Comment by pmario** [comment]
@Jermolene -- Can be closed.   Duplicated titles in filters are possible now.
