### ISSUE TITLE
Request: StringSlicerWidget

### ISSUE THREAD

**Issue by twMat** [Jermolene/TiddlyWiki5#2715]
I'd like a good way to slice out segments of text, probably equivalent to the javascript [slice string](http://www.w3schools.com/jsref/jsref_slice_string.asp) method.

I have previously experimented with this in pure wikitext wich demanded various recursive loops and several nested filters because the current string operators are very limited. One problem is that while we can regexp to *test* the existance of a string segment, we cannot directly store it in a variable.  I suspect the many filters and loops are costly and it was complicated to set up. Considering there is a js-native solution for this, I'm guessing it would not be overly difficult for someone in the know.

**Comment by tobibeer** [comment]
Hi Mat, do you mind sharing one more more practical use cases / examples where this would have saved your day?

**Comment by tobibeer** [comment]
While not quite as performing or as pretty as:

`{{{ [[foo bar baz]slice[5,3]] }}}`

You can already use [tobibeer/split](http://tobibeer.github.io/tw5-plugins/#split) like so:

`{{{ [[foo bar baz]split:last at[5]split:first at[4]] }}}`

**Comment by twMat** [comment]
Hm, my reference to native js *slice* might be misleading. Given the key role of *texts*, I'm thinking more about being able to slice out between arbitrary specified strings like words, html-tags, etc in texts. I attempted this in [Cherrypicker](http://cherrypicker.tiddlyspot.com/), including the thoughts for un-implemented ideas I mention there. Another concept, not yet published, is [TriEdit](http://triedit.tiddlyspot.com/). I've attempted other stuff too that have not really come to fruition because of this. One major idea is to slice out e.g macros or style defs for reuse elsewhere.

Would your split operator be able to perform this? E.g in this text to slice out the strings between 
Overall I think TW is a lacking in "string tools" considering TW is much about text.

**Comment by tobibeer** [comment]
Hi @twMat, I just released the new  [version 0.7.2](https://github.com/tobibeer/tw5-split/releases/tag/0.7.2) of [tobibeer/split](http://tobibeer.github.io/tw5-plugins/#split) which now allows you to do:

`{{{ [[foo bar baz]split:at[5,3]] }}}`

**Note**: Unlike substr, this literally starts with the 5th character in your string, not the 6h.

**Comment by tobibeer** [comment]
Hi @twMat, yes, [tobibeer/split](http://tobibeer.github.io/tw5-plugins/#split) can do that for you, so long as you have defined opening and closing strings.

{{{ [[<foo>bar</foo>]split:last[<foo>]split:first[</foo>]] }}}

**Comment by twMat** [comment]
[tobibeer/split](http://tobibeer.github.io/tw5-plugins/#split) - first trials look very promising. It seems even to handle very provocative characters in the text string, like various brackets and triple quotes, etc. This might just be what I'm hoping for! Thank you @tobibeer :-)

Side note ref. OP: An alternative to a *native* widget for, in this case, string slicing might be if tiddlywiki.com *categorized* community resources like Tobias' plugin, Not sure how categorization woudl be handled practically though, as the existing tag practice doesn't quite allow it.

**Comment by tobibeer** [comment]
@twMat, fyi, I'm planning to also implement these new suffixes for [tobibeer/split](http://tobibeer.github.io/tw5-plugins/#split):

* `split:before[<this>]`
    * returns everything **up until** the **first** match of `<this>` (using `indexOf()`)
* `split:after[<this>]`
    * returns everything **after** the **first** match of `<this>` (using `indexOf()`)
* `split:beforelast[<this>]`
    * returns everything **up until** the **last** match of `<this>` (using `lastIndexOf()`)
* `split:afterlast[<this>]`
    * returns everything **after** the **last** match of `<this>` (using `lastIndexOf()`)

...whereas `<this>` corresponds to the string you wish to match / at which you want to split.

### Examples

`{{{ [foo.bar.baz]split:before[.] }}}`
foo

`{{{ [foo.bar.baz]split:after[.] }}}`
bar.baz

`{{{ [foo.bar.baz]split:beforetlast[.] }}}`
foo.bar

`{{{ [foo.bar.baz]split:afterlast[.] }}}`
baz

All of the above can already be done, however in a more complicated manner, at times requiring to also use [tobibeer/join](http://tobibeer.github.io/tw5-plugins/#join) to tie split items back together.

**Comment by tobibeer** [comment]
@twMat, by the way, please be careful with terminology... at least, I don't think you're actually after a widget, at all.

**Comment by twMat** [comment]
@tobibeer - with those additional suffixes, several ideas of mine will be a breeze to make! Wonderful easy to understand semantic commands. Wow!

>@twMat, by the way, please be careful with terminology. At least, I don't think you're actually after a widget with your request, are you?

First off, true, I don't fully understand what characterizes a widget. The premise was that I think we need an effective tool for slicing out segments in text, given (again) how *central* texts are in TW. So, given the complexity of traversing through a text to find specific start/end points etc, my reasoning was that it should (still) be as primitive as possible. As far as I understand, this is what widgets are/for.

With [tobibeer/join](http://tobibeer.github.io/tw5-plugins/#join), I see how a filter operator makes much more sense from a *practical* point of view - *especially* for the example applications I mentioned previously.

Given your input, I'm closing this issue. (Yes, of course I fully understand that implementing those last suffixes are *intentions*, not promises. But I do look forward to it ;-) )

**Comment by tobibeer** [comment]
@twMat 

> Given your input, I'm closing this issue. (Yes, of course I fully understand that implementing those last suffixes are intentions, not promises. But I do look forward to it ;-) )

Go take a look ;-)

**Comment by twMat** [comment]
Haha!
ATM, no possibility to try it out but, in deed, you seem to have implemented it already!!! Warm thanks @tobibeer !

**Comment by diego898** [comment]
Hello @Jermolene! Is it possible/probable that @tobibeer's [tobibeer/split](https://tobibeer.github.io/tw5-plugins/#split) will make it into core?

P.S. What about his [tobibeer/join](http://tobibeer.github.io/tw5-plugins/#join)?
