### ISSUE TITLE
[Bug?] WikiText @@ gives different result from html class

### ISSUE THREAD

**Issue by twMat** [Jermolene/TiddlyWiki5#2729]
Applying a class to bullet lists using WikiText `@@` does not produce the same result as using html tags.

Demo:

```
@@.class
*Parent
**Child
@@

<div class="class">

*Parent
**Child
</div>

<style>
.class ul { list-style: none; }
</style>
```

The `@@` variant disregards the class for the first list element.

Tested on Chrome and FF.

**Comment by pmario** [comment]
no bug. works as configured, but probably not as expected.

```
@@.class
*Parent
**Child
@@
```

produces a structure, where your style CSS is wrong

```
<ul class="test">
  <li>Parent
      <ul><li>Child</li></ul>
  </li>
</ul>
```
----

```
<div class="class">

*Parent
**Child
</div>
```

is something completely different: 

```
<div class="test">
  <ul>
    <li>Parent
       <ul><li>Child</li></ul>
    </li>
  </ul>
</div>
```

where the following style is ok

```
<p><style>
.test ul { list-style: none; }
</style></p>
```

**Comment by pmario** [comment]
You can see the raw html code that's produces with the TW pre-release preview function.
http://tiddlywiki.com/prerelease/

**Comment by pmario** [comment]
try: `.test li { list-style: none; }`

**Comment by twMat** [comment]
Ah! Thanks Mario.
I'm closing this and might post a new issue about the expected result intead.

**Comment by pmario** [comment]
did you see my last comment?

**Comment by twMat** [comment]
Yes, will try some stuff. Thanks Mario!
