### ISSUE TITLE
Disable CodeMirror when on Mobile

### ISSUE THREAD

**Issue by tgrosinger** [Jermolene/TiddlyWiki5#2730]
TiddlyWiki version: 5.1.13
CodeMirror version: 5.1.13

The codemirror plugin does not work very well on mobile. Errors pop up frequently and sometimes the written content is even lost. There should be a way to automatically disable codemirror only when on mobile.

This issue is a continuation of this discussion: https://groups.google.com/forum/#!topic/tiddlywiki/Usrl0OQyESY

As noted by @Jermolene, the `$:/config/EditorTypeMappings/text/vnd.tiddlywiki` tiddler is not wikified when being read for configuration, so changing the value using a mechanism like the `$reveal` widget is not an option.

**Comment by pmario** [comment]
I think, to make this work, we would need to modify the core plugin initialisation. IMO there isn't much, that the user can do atm. except manually disabling the plugin and save / reload. :/

**Comment by tgrosinger** [comment]
Yeah, that is what @Jermolene indicated as well (a startup module). I might be interested in looking into that, but would need pointers of where to start digging. I have worked in plugin-space a bit, but have not done much in core yet.

**Comment by buggyj** [comment]
maybe along the lines of 
```
/*\
title: $:/core/modules/macros/hackeditorstring.js
type: application/javascript
module-type: startup


\*/
(function(){

/*jslint node: true, browser: true */
/*global $tw: false */
"use strict";

// Export name and synchronous status
exports.name = "hackeditstring";
exports.after = ["load-modules"];
exports.synchronous = true;


exports.startup = function() {


if ($tw.browser)
if (/Android|webOS|iPhone|iPad|iPod|Opera Mini/i.test(navigator.userAgent || navigator.vendor || window.opera)) {
		$tw.wiki.addTiddler(new $tw.Tiddler({title: "$:/config/EditorTypeMappings/text/vnd.tiddlywiki", text: "text"}));
			}
else {
		$tw.wiki.addTiddler(new $tw.Tiddler({title: "$:/config/EditorTypeMappings/text/vnd.tiddlywiki", text: "codemirror"}));
}
}

})();
```

**Comment by tgrosinger** [comment]
This is great @buggyj. It is missing a "}" on the second to last line, but I tested it after changing that and it works perfectly. Thank you very much.

Would you like to submit a PR, or do you want me to?

**Comment by buggyj** [comment]
@tgrosinger - it's just a general idea to get you started, this piece of code does not match the cores' coding style (look at the use of braces and spaces - this probably a code style guide somewhere), I have no idea if it would capture all smart phones, and if this is applicable for tablets?? So I think there is some work to do yet.

I would expect this functionality to go into the codemirror plugin as you are suggesting.

**Comment by PaulHobbs** [comment]
I had to modify the script @buggyj posted to get it working. I replaced `$tw.wiki.addTiddler` with `$tw.wiki.setText` on the same already-existing tiddler:

`

(function(){

/*jslint node: true, browser: true */
/*global $tw: false */
"use strict";

// Export name and synchronous status
exports.name = "hackeditstring";
exports.after = ["load-modules"];
exports.synchronous = true;

exports.startup = function() {
    if ($tw.browser) {
        var w = "$:/config/EditorTypeMappings/text/vnd.tiddlywiki"
        if (/Android|webOS|iPhone|iPad|iPod|Opera Mini/i.test(navigator.userAgent || navigator.vendor || window.opera)) {
            $tw.wiki.setText(w, "text", null, "text");
        }
        else {
            $tw.wiki.setText(w, "text", null, "codemirror");
        }
    }
}

})()
`

**Comment by gabrielmontagne** [comment]
Thanks so much, @buggyj and @PaulHobbs. Your hack worked for me perfectly! Great relief!

**Comment by AnthonyMuscio** [comment]
I thought there was a way when code mirror was operating to use the standard editor instead, this recollection was from some time ago.
I am sure one could find how code mirror replaces the existing editing and may be as simple as introducing an alternative $:/tags/EditTemplateBodyFilter cascade item to invoke the standard editor instead, if in mobile mode only as you go to edit it. In this way the codemiror editor remains in place and running but is not used.
* Possibly the worst case scenario would be building your own cascade edit-text widget that included the editor toolbar component but not code mirror.
* Either way I think a switch to do this could make sense to put an option in, if not a default switch if the codemirror plugin is not "fit for purpose" on mobile.
  * Perhaps you need only turn off a few features to stop this happening.

There is another use case such as if you want to use a browser add on to edit text in an external browser, code mirrors line focused operation, interferes with this. Perhaps there is an argument that one could "mark a tiddler" as "do not use codemirror", or use in code mirror, so large "code" based tiddlers, html content etc... can be set to simple text editing so as to allow editing in an external editor.
* Better yet would be if code mirror carried the feature to support its own "do not use code mirror" facility, even a cascade that allows designers to choose by any means they wish, and this could work along side other editors such as a wysiwyg editor.
* Codemirror has being around a lot longer than the cascade feature, perhaps it needs to be brough up to date.
