### ISSUE TITLE
not Operator

### ISSUE THREAD

**Issue by tobibeer** [Jermolene/TiddlyWiki5#2731]
I'd like to suggest a new filter operator called **not** which is given a **list of titles** via the operand that are to be removed from the set of input titles.

Especially for dynamic choices, it does not suffice to use `-[[Some Title]]` as it can be unknown what and how many titles to eventually remove from the set of available titles.

```
<$vars these="foo bar baz">

{{{ foo bar baz mumble frotz gronk +[not<these>]] }}}

should output:

mumble frotz gronk
</$vars>
```

Alternatively, the filter operator may be called **but**, since that's a term already used, so perhaps easier recognizable.

**Comment by pmario** [comment]
Shoudn't it be: `{{{ foo bar baz mumble frotz gronk -[<these>] }}}`

**Comment by tobibeer** [comment]
@pmario: have you tried? Short answer: No.

**Comment by pmario** [comment]
yea, but isn't it a bug then? http://tiddlywiki.com/#Filter%20Expression

**Comment by tobibeer** [comment]
No, it's not a bug because, given the example...

`-[<these>]` is the same as
`-[[foo bar baz]]` which is not the same as
`-foo -bar -baz`

**Comment by pmario** [comment]
try

```
<$vars these="foo bar baz">

{{{ foo bar baz mumble frotz gronk +[remove<these>] }}}

should output:

mumble frotz gronk
</$vars>
```

**Comment by pmario** [comment]
its part of the listops stuff http://tiddlywiki.com/#remove%20Operator

**Comment by tobibeer** [comment]
Thx, @pmario ...that works.

Ok, so [the description](http://tiddlywiki.com/#remove%20Operator) of *remove* really isn't very good:

*remove a range of items in an array from the current list*

It should rather be:

*remove a list of titles specified in the operand from the input titles*
