### ISSUE TITLE
Add support for autosave with the download saver

### ISSUE THREAD

**Issue by Jermolene** [Jermolene/TiddlyWiki5#2741]
Background: The download saver is the module that handles saving in a strictly HTML5-compliant way using the `download` attribute of the `<a>` element. It is currently flagged as not supporting autosave, meaning that it only saves changes when the save button is explicitly clicked.

I've done some experiments to enable autosave for the download saver. The resulting user experience is quite fluid if the browser is set to download files without prompting for the location: each tiddler save triggers the browser to download another copy of the file (`index (7).html`, `index (8).html`, `index (9).html`, etc). It doesn't work quite so well if the browser is set to prompt for the location of each downloaded file.

The pitfall for users is that if one wants to reload the page then one needs to make sure to explicitly load the most recently saved file in order not to miss changes.

Overall, the transformation in usability for the download saver convince me that it's worth experimenting with.

Backwards compatibility and flexibility require a control panel switch to enable or disable the new behaviour.

I'll be committing an implementation soon, let me know if you have any thoughts or concerns @pmario @tobibeer @twMat @telmiger @danielo515?

(Note that the download saver does not get to see the filename that was eventually chosen for the newly downloaded file).

**Comment by pmario** [comment]
>The pitfall for users is that if one wants to reload the page then one needs to make sure to explicitly load the most recently saved file in order not to miss changes.

I think, that's a big problem. Users will blame TW, if they loose content, because they use/edit the wrong file.

**Comment by tobibeer** [comment]
There are browser plugins that do allow to overwrite an existing download file, While I'm not sure of the overall implication, with chances of conflicts generally being low, I think it may be worth a shot. However, if I do need  browser extension, possibly a browser extension that specifically handles that for TiddlyWIki sounds like the choice I would prefer. Also, I imagine those extensions use the last download location rather than the location of a file. So, one may have to initially select the right file to overwrite, which would mean one has to toggle the download behavior or have TiddlyWiki reside in the downloads folder.

So, a question would be: What's the intention for this move?

**Comment by Jermolene** [comment]
For clarity, what I am talking about is changing the array `capabilities: ["save", "download"]` to `capabilities: ["save", "autosave", "download"]` here:

https://github.com/Jermolene/TiddlyWiki5/blob/master/core/modules/savers/download.js#L59 

Try making the change, set up Chrome not to prompt for downloads and give it a try. Hopefully you'll see what I mean.

I'm making this proposal because we have consistently come across people who use the download saver on Chrome as their primary saver, surprising as it sounds. Backwards compatibility demands that we don't change the current default behaviour, so I'm proposing that the array we return above should depend on a configuration tiddler.

**Comment by danielo515** [comment]
At a first I saw this as an improvement, but after thinking about it sometime I think it's not at useful as it might look. It has the benefit that on every change you get an automatic "commit", which is indeed a good thing. The problem that @pmario points it's also important: you have to make sure that you open the latest TW, or you will be missing information. If the file is auto-named, this may not be a big problem for a single wiki, but once you mix several wikis and the download file gets the same name for all of them (`Download(x)`)you can be facing a severe problem that grows exponentially.

Other thing you have to think about is how this interferes with the user's way of working with the browser: I like that the browser asks me where to download a file, but with this feature on I may be forced to turn that prompt off, which is invasive for my workflow. 

Not sure what to think, depending on the user it could be an huge benefit or a nightmare. Of course you can turn-off autosave...

**Comment by tobibeer** [comment]
> I like that the browser asks me where to download a file, but with this feature on I may be forced to turn that prompt off, which is invasive for my workflow.

Definitely agree. I sure wouldn't want to change the default behavior I have set up for my browser. At least it would mean a conflict of interest with me losing one way or the other.

**Comment by ibnishak** [comment]
Combined with a browser plugin to automatically overwrite the files, this could potentially solve the "save issues", can't it?

**Comment by sukima** [comment]
If the autosave file naming is consistent then you could update the URL to reflect the new version.

Open `index.html` → Auto saves to `index (1).html` → Updates URL history with `pushState()`.

Per [the `pushState` docs](https://developer.mozilla.org/en-US/docs/Web/API/History_API#Example_of_pushState()_method):

>This will cause the URL bar to display [the updated URL], but won't cause the browser to load [the file] or even check that [the file] exists.

**Comment by telmiger** [comment]
Some thoughts and ideas on the intended standard behaviour (without other plugins): 
1) Better have 27 backups than none. Losing work is very annoying.
2) Messages/warnings. Concerning the reload issue: Could a warning be shown
- when switching the feature on?
- on (re)load, if the feature is on?
3) Alternatives. The main purpose of switching this on would be to have a backup if anything went wrong, right? Would it be feasible to export only the changed tiddlers (all/single?) instead of the whole wiki? If the backup is saved as .tid or .json there would not be a reload problem. So you save a full wiki first when you are done with working for the day.
4) Downsides of saving whole wikis: 
- Disk space is not a concern, if your biggest wiki ist 3.1 MB like mine. But as I hear, there are much fatter wikis in the wild. 
- No absolute security. There could be a problem you are not aware of, which would be present in X of your 27 copies. E.g. if you accidentally delete a tiddler’s text field and are not aware of it. (How could this happen? If you use it as state for a reveal widget maybe? I did not test that …)

**Comment by Jermolene** [comment]
I've updated the prerelease:

http://tiddlywiki.com/prerelease/index.html

<img width="964" alt="screenshot 2017-01-30 18 30 58" src="https://cloud.githubusercontent.com/assets/174761/22436065/6f70c26e-e71a-11e6-8fcb-bd9b9b843d52.png">

**Comment by Jermolene** [comment]
Do give it a try; TBD is documentation that we can link to from the text of the checkbox

**Comment by Jermolene** [comment]
@telmiger said:

> Some thoughts and ideas on the intended standard behaviour (without other plugins): 
> Better have 27 backups than none. Losing work is very annoying.
> 2) Messages/warnings. Concerning the reload issue: Could a warning be shown
> - when switching the feature on?

The feature has to be switched on explicitly in control panel, and there is therefore an opportunity to provide warnings there.

> - on (re)load, if the feature is on?

What would be the trigger for when we'd show the warning?

> 3) Alternatives. The main purpose of switching this on would be to have a backup if anything went wrong, right?

Yes. I think that it gets closer to the "ideal" mental flow of using tiddlywiki: the confidence that you've saved changes when you've finished editing each tiddler. Obviously, we've already got that flow with TiddlyFox but the motivation of merging this feature now is so that other people can easily experiment with incorporating it into their workflow.

> Would it be feasible to export only the changed tiddlers (all/single?) instead of the whole wiki? If the backup is saved as .tid or .json there would not be a reload problem. So you save a full wiki first when you are done with working for the day.

That's an interesting idea, and worth experimenting with.

4) Downsides of saving whole wikis: 
- Disk space is not a concern, if your biggest wiki ist 3.1 MB like mine. But as I hear, there are much fatter wikis in the wild. 

I agree that disk space shouldn't be our primary concern.

> - No absolute security. There could be a problem you are not aware of, which would be present in X of your 27 copies. E.g. if you accidentally delete a tiddler’s text field and are not aware of it. (How could this happen? If you use it as state for a reveal widget maybe? I did not test that …)

Good point, and should be incorporated in the docs (contributions welcome there, by the way!).

@sukima said:

> If the autosave file naming is consistent then you could update the URL to reflect the new version.

Yes, I think that that is worth experimenting. I'm also looking at local storage for communicating between browser tabs

**Comment by telmiger** [comment]
> What would be the trigger for when we'd show the warning?
We could offer the user to add a predefined tiddler at the top of his/her default tiddlers list to be reminded until they get used to the new flow.
