### ISSUE TITLE
Future maintenance and support for the ActionListops widget and associated filters

### ISSUE THREAD

**Issue by matabele** [Jermolene/TiddlyWiki5#2744]
@Jermolene @tobibeer 

Hi -- I have been struggling off and on with cancer for the past few years and no longer see that I will be able to maintain the ActionListops widget and extended filters code, nor provide support.

I believe that the cycle[] and keep[] filters should be pulled into the code from [here](http://listops.tiddlyspot.com/)

It might also be a good idea to pull the ActionMaketid widget and the associated filter into the core from [here,](http://maketid.tiddlyspot.com/) as I have had several requests for this functionality -- perhaps in the form of a plugin.

**Comment by matabele** [comment]
@Jermolene @tobibeer 

Hi -- I have been struggling off and on with cancer for the past few years and no longer see that I will be able to maintain the ActionListops widget and extended filters code, nor provide support.

I believe that the cycle[] and keep[] filters should be pulled into the code from [here](http://listops.tiddlyspot.com/)

It might also be a good idea to pull the ActionMaketid widget and the associated filter into the core from [here,](http://maketid.tiddlyspot.com/) as I have had several requests for this functionality -- perhaps in the form of a plugin.

Then there are a couple of other projects I was working on which might be worth someone picking up on:

http://checklist.tiddlyspot.com/

http://simple-tagger.tiddlyspot.com/

If anyone is interested, I will help where I can, but don't expect any technical input such as modifications to algorithms. 

There are two outstanding support requests:

https://github.com/Jermolene/TiddlyWiki5/issues/2312#issuecomment-250885661

https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/tiddlywiki/0m5CV3WXXu4/wtJwDwBzAwAJ

**Comment by Jermolene** [comment]
Hi @matabele please accept my best wishes, and warm thanks for your past contributions. You're currently listed as contributor #9 to TiddlyWiki, which is pretty good going!

<img width="490" alt="screenshot 2017-01-31 08 39 49" src="https://cloud.githubusercontent.com/assets/174761/22457715/e276d4bc-e790-11e6-89a5-27971ed3dc10.png">

If anybody is in a position to help @matabele and I by packaging up some PRs, please do shout here.

**Comment by matabele** [comment]
Hi @Jermolene 

Many thanks for the thumbs up. I should be able to answer questions relevant to a handover from time to time for a while -- but code changes or algorithm modification are out of the question.

**Comment by tobibeer** [comment]
Hi @matabele, very sorry to hear about your challenge(s). All the best wishes from Germany. I'll gladly review those plugins / PRs of yours and will contact you for aligning any wishes you have / developments you envisioned as to their maintenance / publication / possbible incorporation in the core.

**Comment by matabele** [comment]
Hi @tobibeer -- thanks for your kind words -- will endeavour to answer any questions you may have and have a couple of pointers about where I was heading.

1. The ActionMaketid plugin is complete, but lacks sufficient documentation (I threw it together rather rapidly in response to a support request.) The associated filter was a cut down version of one of your filters (as some features were redundant/duplicated) -- it should be fairly simple to beef up the documentation from your own and I believe that it might also be possible to simplify the filter code further. The plugin (as it stands) does everything I've ever required from it for the creation of sets of tiddlers.

2. I wrote the simple-tagger plugin for my own needs -- a simple utility to enter, delete, edit and copy tags between multiple tiddlers. I then became involved in adding emoticons to the tags. The formatting needs fixing for the current version of TW5 -- also looks much better on a Mac than on other PC's. 
Perhaps, the plugin should be broken into two -- a simple tagger suitable for everyone, and a simple tagger plus for those who wish to utilise emoticons in various ways. They are useful due to the easy encoding of fairly long and unique strings of alphanumerics -- this enables one to use an emoticon prefix with a simple repeated suffix such as "Intro" in numerous different tiddlers.

**Comment by expelledboy** [comment]
Hi @Jermolene @tobibeer, bumped into this while assisting my fiance on her TW5. I am Williams son, and just wanted to let you guys know that he passed away late last year. Hope his contributions have helped the project, he really loved working on TW!

**Comment by Jermolene** [comment]
Hi @expelledboy thank you for letting us know, and my heartfelt condolences to you and your family for your loss. I looked back at your father’s first post where he announced http://wills.tiddlyspot.com (there’s an archive.org [snapshot from a couple of months later](https://web.archive.org/web/20140531235937/http://wills.tiddlyspot.com/)). As then, I’m struck by the skill that he showed in making it look great and offering useful functionality that wasn’t available at the time, and I believe it was accomplished within a few days of his first discovering TidlyWiki. Looking back at your father’s postings to the discussion group you can see that he was very active and engaged with the community, and responsible for some popular enhancements to TiddlyWiki. It’s great to hear that you and your fiancé will perhaps benefit from his contributions in the future.

May I ask if there is a charity that your father supported to which those interested could make a donation in his memory?

**Comment by expelledboy** [comment]
She already has. It was pivotal to passing top of class in Neuroscience Honors. :)

He didn't believe in any charity. Being on the ground having lived in Zimbabwe and worked for many NGO's, and seeing the results in contrast to the size of the donations first hand I think coloured his perspective.

If I had to pick something though it would rather be the propagation of one of his ideas. Two of the simplest to communicate would be;

* Manufactures are taxed for the cost of recycling the products before consumer sales.
* NGO's should by law implement complete transparency with regard to fund movements.

When you next are having a discussion where people are open to new ideas on how to improve the world, remember my dad and share one of the above. Thanks!

**Comment by pmario** [comment]
@Jermolene .. IMO this one can be closed. The ActionListops stuff is part of the core and we do maintain it.

**Comment by Jermolene** [comment]
Thank you @pmario
