### ISSUE TITLE
Sticky titles overlap other content

### ISSUE THREAD

**Issue by twMat** [Jermolene/TiddlyWiki5#2747]
*Ctrlpanel > Appearence > Theme Tweaks > Sticky titles : yes*

![image](https://cloud.githubusercontent.com/assets/4534056/22461335/1c8f0e2c-e7a9-11e6-8b74-f2f3870d3108.png)

Problems both in FF and Chrome.

Is this the same as #1362 ? A quick test, per suggestion by @Jermolene there, to manipulate `.tc-tiddler-title` did not succeed, nor z-index for the *more* tool popup.

**Comment by pmario** [comment]
The title background is transparent with the latest release. ... There is still some overlapping, but every dropdown element can be seen and activated. ... IMO it can't be saved in a way that we know. 

The only thing left, that I see, is: A post to the FireFox mailing list, with a MTC on jsfiddle or so. ... Similar to the one used with the ["jumpy" toolbar behavior](https://github.com/Jermolene/TiddlyWiki5/issues/282). 

So what we would need is a MTC

On the other hand, it took me quite some time to construct a test-case like in the OP, since I don't have many tiddler bodies that are short enough.

**Comment by twMat** [comment]
Here's an idea that should work + could be used for other things:

Clicking the more button could **set a CSS attribute or add a class** for the current tiddlers "title div".

I.e `<div class="tc-tiddler-title">`  becomes `<div class="tc-tiddler-title" active>`

...and then in Stylesheet

`[active] {z-index:501}` (the z-index for `tc-tiddler-title` is 500) 


**We already have this mechanism** for when adding tags, i.e adding the tag *foo* causes this

<div class="tc-tiddler-frame ......  tc-tagged-foo">

It would be very useful to be able to add arbitrary classes at "tiddler-frame level" directly by button-clicking  rather than have to go //via// adding tags to trigger css.

**Comment by pmario** [comment]
the popup already has a z-index:1000 and the title:500 ... so this won't solve the problem.

**Comment by twMat** [comment]
@pmario 

It's not the popup, it is the specific `tc-tiddler-title` that needs >500 z-index. 

![image](https://cloud.githubusercontent.com/assets/4534056/26168053/18089e2a-3b39-11e7-8629-ca27eba0a75d.png)

**Comment by pmario** [comment]
related to: #1737

**Comment by twMat** [comment]
>related to: #1737

Aha! In deed the same issue. And it was reported before this one - but this one is better documented IMO, including what I believe to be a workable solution.
What to do about this double reporting?

@rubaboo

**Comment by rubaboo** [comment]
I'm glad see that your solution is essentially the same as I hinted to in my last comment in #1737. I agree this one is better documented. I'll close mine.

**Comment by tobibeer** [comment]
@twMat / @pmario was there any PR on this yet? None seems linked here.

**Comment by twMat** [comment]
This does not not fully solve it:

```
.tc-tiddler-frame:hover .tc-tiddler-title {
  z-index:501;
}
```

...but it does improve things *substantially* because you can now access all the buttons in the popup. IMO that makes it worthwhile to include in standard distro.

**Comment by Jermolene** [comment]
Fixed in 1c982fb

**Comment by twMat** [comment]
appreciated!

**Comment by ExoCode17** [comment]
Hi, I am having this problem too. I'll try with the 501 z-index, but why is this closed? I use TW on node and this fix is not included there.

**Comment by twMat** [comment]
@ExoCode17 - this is solved in https://tiddlywiki.com/prerelease/ - i.e 5.1.20 that will hopefully come soon.
