### ISSUE TITLE
Cannot create pull request

### ISSUE THREAD

**Issue by gernert** [Jermolene/TiddlyWiki5#2749]
## Problem:
Cannot create a pull request for code in the same way as for documentation.

## Description
I can create a pull request for documentation by going to tiddlywiki.com, open the appropriate tiddler in edit mode, and click - in the pink area - edit this tiddler on github. This brings me to the correct tiddler where I can edit the tiddler (and so on).
If I try to do the same for a code tiddler, e.g. $:/themes/tiddlywiki/vanilla/sticky (see #2748), I get to https://github.com/Jermolene/TiddlyWiki5/tree/master/editions/tw5.com/tiddlers and I am lost.

## Feature request
It would be nice if pull requests for code behave in the same way as for documentation.

**Comment by twMat** [comment]
Dito, as I mention in #2745

**Comment by gernert** [comment]
I did mention it a long time ago in #2525

**Comment by Jermolene** [comment]
Hi @gernert @twMat the workflow of making a pull request on a single file that we encourage for docs tweaks is not suitable for working with code. The trouble is that it makes it impossible for the submitter to test their submission, which is not acceptable. At the moment, making pull requests on the core code requires running Node.js to test things.

**Comment by Jermolene** [comment]
I should have mentioned that the technical issue that prevents the example you mentioned from working is that they are shadow tiddlers within a plugin; the link back to github.com is only fixed up for tiddlers within the tw5.com edition.

**Comment by gernert** [comment]
Hi @Jermolene.
Thanks for clarifying; it is more clear than you wrote in the past ( #2525 ):
> Hmm, I'm not sure what's going on there, you should have equal access to all the files of the repo.

**Comment by Jermolene** [comment]
Hi @gernert that was when I thought you meant that you literally were not authorised to make a PR against certain files (which would be very odd, but was what the linked OP said); the clarified statement of the problem is that you can't follow a link for shadow tiddlers on tw.com to the corresponding GitHub file.

**Comment by twMat** [comment]
>making pull requests on the core code requires running Node.js to test things.

I wish I had known this years ago. Just added [a PR](https://github.com/Jermolene/TiddlyWiki5/pull/2753) on the docs about this.

**Comment by tobibeer** [comment]
@gernert, I believe this is all clear then. Is it?

**Comment by gernert** [comment]
@tobibeer , yes it's clear now. I'll close this.
