### ISSUE TITLE
Portability

### ISSUE THREAD

**Issue by kookma** [Jermolene/TiddlyWiki5#2750]
If we put TiddlyDesktop on a thumb-drive , in Windows platform, it creates a folder under C:\Users\Some_User_Name\AppData\Local\TiddlyDesktop.
This causes to leave a track behind and on every PC you connect the thumb-drive and run the TiddlyDesktop. Sometimes different settings for different PCs make "nw.exe" stop displaying start page.

I suggest TiddlyDesktop supports portability.

Thank you for your great work.

**Comment by tobibeer** [comment]
Perhaps [this comment](https://github.com/nwjs/nw.js/issues/1197#issuecomment-225349606) is relevant?

**Comment by Jermolene** [comment]
Thank you @pmario @kookma - by the way this can be done with the `--user-data-dir /my/directory` command line switch for the nw.exe program.
