### ISSUE TITLE
no renaming for non existing tiddlers

### ISSUE THREAD

**Issue by tobibeer** [Jermolene/TiddlyWiki5#2752]
I just hit the create button for a new tiddler and I am seeing a warning and an option, both of which are inappropriate for tiddlers that never existed:

* `Target tiddler already exists`
* `Update New Tiddler to Creating Multiple Tiddlers At Once in the tags and list fields of other tiddlers`

Realised this because I accidentally built tb5 on prerelease. I think this should definitely be fixed before release.

![renamenonexisting_warning](https://cloud.githubusercontent.com/assets/97566/22604710/1e35bdce-ea4d-11e6-9a37-931e984838fe.jpg)

**Comment by Jermolene** [comment]
Hi @tobibeer do you get the same problem on http://tiddlywiki.com/prerelease/index.html?

**Comment by tobibeer** [comment]
ah, sry... I feel like I recently reported this one already w/o checking prerelease, again ...altough, I'm usually up to date merging the current master in

anyway, sorry for the noise
