### ISSUE TITLE
Is "library: yes" something like the "script src=" tag?

### ISSUE THREAD

**Issue by danielo515** [Jermolene/TiddlyWiki5#2756]
Hello,

There were a discussion sometime ago about tiddlers that needed to be added to the header of a tiddlywiki file. My use case was adding some javascript libraries that I needed them to run before the actual TW boot process.

I saw several times a section on the tiddlywiki template transcluding all the tiddlers with a field `library: yes`. I don't know why, but I ignored that section until today. The only thing that I found that uses it is the crypto library, which is in turn used by the boot kernel. So, my questions are: 

- Can I use this field set to yes for every portion of javascript that I want to run before tiddlywiki boot process? 
- Can I specify the order?
- If we have to compare this to an html feature, can it be the equivalent to `<script src='library'>` ?

Is this feature documented at any place? If the answer to my first question is yes this would have saved me a lot of template juggling. 

Regards

**Comment by Jermolene** [comment]
Hi @danielo515 the key is [this section](https://github.com/Jermolene/TiddlyWiki5/blob/master/core/templates/tiddlywiki5.html.tid#L38-L41) of the main HTML file template:

```
...
<!--~~ Library modules ~~-->
<div id="libraryModules" style="display:none;">
{{{ [is[system]type[application/javascript]library[yes]] ||$:/core/templates/javascript-tiddler}}}
</div>
...
```

>- Can I use this field set to yes for every portion of javascript that I want to run before tiddlywiki boot process? 

Yes.

>- Can I specify the order?

No, but if you encounter the need we can probably figure something out.

>- If we have to compare this to an html feature, can it be the equivalent to `<script src='library'>` ?

Yes. The script tag is generated automatically by the template used to render the library tiddlers. See https://github.com/Jermolene/TiddlyWiki5/blob/master/core/templates/javascript-tiddler.tid

> Is this feature documented at any place? If the answer to my first question is yes this would have saved me a lot of template juggling.

Possibly not.

**Comment by danielo515** [comment]
Dear @jermolene,

Thank you, that confirms all my guessings (I almost became an expert in tiddlywiki templating recently :smile:) 
Order is indeed important. Of course I can bundle everything together , but that totally defeats the purpose of plugabble external libraries. Isn't enough to use the usual fields list after and list before ?

Regards

**Comment by Jermolene** [comment]
Hi  @danielo515, there is no ordering to `library: yes` tiddlers, as you can see from the snippet I quoted above.

This is a really ancient part of TiddlyWiki, [about 5 years old](https://github.com/Jermolene/TiddlyWiki5/commit/5322d3cdfdda0f4ba0d8778e83f1ad3ea4396097#diff-9b0d8808e9e22106786d81e2fb93b736). To be honest, I can't remember why I used a field here instead of a tag. Using a tag seems more obvious, and would give you your ordering (we'd need to decide on a system of tag names; maybe `$:/tags/RawMarkup/BeforeBoot`). And maybe we need more such insertion points; we ended up with many in TiddlyWiki Classic.

**Comment by danielo515** [comment]
Hello Jeremy,

I have to admit that having a tag (specially with that name ) would make it more obvious and visible. I'm not very fan of using tags for system stuff , it feels like polluting user's space. But as you say at some point, it is better to have something stable and standard before trying to change it . I think it will be quite easy to add tag support while keeping retro compatibility. But , do we want to keep retro compatibility?

**Comment by tobibeer** [comment]
>  I'm not very fan of using tags for system stuff , it feels like polluting user's space.

Me neither. However, if we only "pollute" system tiddlers with "system tiddler tags", I think the "pollution" is wanted. What's not a recommendable practice is to tag tiddler "Foo" with "$:/tags/Bar", imho.

**Comment by danielo515** [comment]
I thing this has been already addressed with the addition of tags like `$:/tags/RawMarkupWikified/TopHead` and  `$:/tags/RawMarkupWikified/TopBody`.
@Jermolene you can close this issue

**Comment by Jermolene** [comment]
Thanks @danielo515
