### ISSUE TITLE
Proper media files handling.

### ISSUE THREAD

**Issue by sprnza** [Jermolene/TiddlyWiki5#2760]
Hi there!
Guys, I'm new to TW and Node.js And I'm failed to google these simple questions:
What is a proper way to handle media? I mean as soon as node.js version of TW does not consist of a one single file and pictures/audio is being uploaded as separate ~~files~~ tiddlers is it okay to use a big amount of pictures uploaded to TW? Or I should consider to make them "[external](http://tiddlywiki.com/#ExternalImages)". is this relevant to node.js app? The whole tiddlywiki.com is mostly about running the wiki as a separate file, right? As far as I get "Creating external images under Node.js" section is about downloading a copy of node.js version of a wiki? 
If I am wrong and still should using external images, what's the recommended way to host them on may apache server? I use apache auth, so my wiki is private, but in order to be able to add pictures to is I must share ones, I don't like this. So the question is what is the proper way to make pictures external for the private wiki behind the apache auth?
Another question is: `--savetiddlers` commands mentioned in the section are supposed to move pictures which are __already uploaded to the app__ to "images" folder, right? I've tried to alter my systemd.service file adding this option and what I've got is existed tiddlers were moved to a specified dir, but new ones were created as usual under `wiki/tiddlers` directory.
Sorry for trivial questions, if there is an explanation regarding this, please share a link.

Thanks for the great piece of software!

**Comment by pmario** [comment]
>..is it okay to use a big amount of pictures uploaded to TW?  Or I should consider to make them "external".

IMO external images are preferable ... but the TW server is a development server. So it's no fileserver, like nginx. .. There are some pull requests, to improve file handling but I'm not sure if they are merged yet.

**Comment by pmario** [comment]
>The whole tiddlywiki.com is mostly about running the wiki as a separate file, right? 

yes

**Comment by pmario** [comment]
>If I am wrong and still should using external images, what's the recommended way to host them on may apache server?

If you know, how to do this. It's possible and a straight forward possibility.

**Comment by pmario** [comment]
> I use apache auth, so my wiki is private, but in order to be able to add pictures to is I must share ones, I don't like this. So the question is what is the proper way to make pictures external for the private wiki behind the apache auth?

There's no "out of the box" solution for this problem.

**Comment by pmario** [comment]
>Another question is: --savetiddlers commands mentioned in the section are supposed to move pictures which are already uploaded to the app to "images" folder, right?

right.

**Comment by pmario** [comment]
> I've tried to alter my systemd.service file adding this option and what I've got is existed tiddlers were moved to a specified dir, but new ones were created as usual under wiki/tiddlers directory.

have a look at: http://tiddlywiki.com/#TiddlyWikiFolders especially:

>Configuration options include:
>
>    **default-tiddler-location** - a string path to the default location for the filesystem adaptor to save new tiddlers (resolved relative to the wiki folder)
>    **retain-original-tiddler-path** - If true, the server will generate a tiddler $:/config/OriginalTiddlerPaths containing the original file paths of each tiddler in the wiki

**Comment by pmario** [comment]
I'm not sure if I missed something. ... just ask :)

**Comment by sprnza** [comment]
Thanks @pmario you've covered everything I was missing.
