### ISSUE TITLE
"Content Type" of new Tiddlers not shown until reload

### ISSUE THREAD

**Issue by Awerick** [Jermolene/TiddlyWiki5#2765]
Hello,

I think, there is a bug when creating a new tiddler: The "content type" is not shown until TiddlyWiki is ~~restarted~~ reloaded.
(Interestingly this does not apply for new markdown tiddlers, using the markdown plugin.)

**TiddlyWiki:** Version `5.1.14-prerelease`
**Browser:** `Firefox`

**Steps to reproduce:**
 *  (Optional: Create a new TiddlyWiki.
     *  `tiddlywiki testwiki --init server`
     *  `tiddlywiki testwiki --server`
     *  Access the wiki via the browser)
 *  Create a new tiddler (e.g. `Content`)
 *  Actual behavior: The `type` field (at the bottom of the tiddler) is empty.
 *  Expected behavior: The `type` field should show `text/vnd.tiddlywiki`.
    (Even after saving the tiddler and then pressing edit the field is still empty.)
 *  Additional info: When inspecting the tiddler file with a text editor, the content type is visible in it.
 *  Additional info: After reloading TiddlyWiki (in the browser), the field shows the expected behavior and displays the content type. – However this behavior probably intended without reloading TiddlyWiki?

Best, Awerick

_**Edit:** Ups, I initially wrote that after_ restarting _TiddlyWiki, the content type is shown – but actually it is sufficient to_ reload/refresh _TiddlyWiki in the browser..._

**Comment by pmario** [comment]
With tiddlywiki, the default / fallback tiddler type is always `text/vnd.tiddlywiki`, So this is "kind of" a convenience function. ...

but you are right. If a type field  is set, it should be shown. 
If it isn't set, it shouldn't be shown. ... 
if not set, it uses the fallback mechanism.

Only if you want a different type, you'll need to define it.

**Comment by pmario** [comment]
typo: tiggler  -> tiddler

**Comment by Awerick** [comment]
> typo: tiggler -> tiddler

Oh yes ;D
(Creating issues when being tired is not always a good idea...)

**Comment by pmario** [comment]
@Awerick ... does this behavior cause problems for you, or is it just a "visual" inconvenience.

... As you found out, the type is set when a tiddler is saved _but_ in the TW internal store there is no type field until you reload the TW.

... The default type for tiddlers without a type field is assumed to be `text/vnd.tiddlywiki` 

@Jermolene ... should we adjust the "new tiddler", "new journal" buttons, or modify the `addTiddler()` core code, that it sets the type field in a proper way? .... The existing behavior is inconsistent, as this issue points out.

**Comment by Awerick** [comment]
No, it does not cause any problems and after knowing the default type I am not even affected anymore.
But during initial experimentation with different types (especially tiddlywiki- vs markdown-tiddlers) I was a bit confused, so I thought resolving this improves the user experience.

**Comment by tobibeer** [comment]
I don't quite think there is something here that needs resolving. Yes, a served TiddlyWiki may not show the explicit type until after reload... but that being the default, not sure if this is actually problematic, or simply a negligible inconsistency.

**Comment by Awerick** [comment]
I thought, this would be rather easy to fix but something only a new user might stumble upon…
But if this minor issue is tolerated/negligible, there is no need in keeping this issue open.
Thus I will close it in the next days (if there is nothing else to discuss).

**Comment by Jermolene** [comment]
It's a problem with the HTTP API; TiddlyWiki 5 is based on the older [TiddlyWeb API](https://tank.peermore.com/tanks/tiddlyweb/HTTP%20API) which was first developed for TiddlyWiki Classic. Thus, the default tiddler content type is the TiddlyWiki Classic `text/x-tiddlywiki`, and therefore TW5 must explicitly specify the newer `text/vnd.tiddlywiki` for all wikitext tiddlers, including those that don't otherwise have a content type, and are relying on the default handling.

I think fixing it would require us to move to a new version of the API that uses TW5 wikitext format as the default.

**Comment by Awerick** [comment]
Well, I also don't think this minor issue is worth the move to a new API version...
