### ISSUE TITLE
Add "enlist" operator

### ISSUE THREAD

**Issue by Jermolene** [Jermolene/TiddlyWiki5#2767]
As we've discussed a few times, while we can store the lists generated by filters in a variable, there's currently no way to access such a list from within a filter.

It is proposed to add a new "enlist" operator that interprets the operand as a stringified list (ie space separated items, with items quoted with double square brackets) which replaces the current selection.

For example:

```
[enlist[a b c]] --> returns a list with three items: "a", "b", "c"
[enlist[a b c]butfirst[]addprefix[-]] --> returns a list with two items: "-b", "-c"
```

Given the inability to include square brackets within filter operands, the "enlist" operator is more useful when used to bring in a list from a variable or transclusion:

```
<$vars myList="h1 h2 h3 h4 h5 h6">
<$macrocall $name="myMacro" heading={{{ [enlist<myList>] }}}/>
</$vars>
```

The proposed semantics is:

* `[enlist[]]` replaces the current selection
* `[!enlist[]]` removes any of the listed entries from the selection

```

exports.enlist = function(source,operator,options) {
	var list = $tw.utils.parseStringArray(operator.operand);
	if(operator.prefix === "!") {
		var results = [];
		source(function(tiddler,title) {
			if(list.indexOf(title) === -1) {
				results.push(title);
			}
		});
		return results;
	} else {
		return list;
	}
};
```

Is there any prior art here? I'm guessing that @tobibeer must have a plugin that does something like this?

**Comment by tobibeer** [comment]
Not sure when I would need this, but there's no artwork I know of atm. :-)
