### ISSUE TITLE
Tiddlymap on Node.js seems to cause problems when trying to export to static > is this a TW5-Problem or rather a Tiddlymap-Problem?

### ISSUE THREAD

**Issue by gesundelehre** [Jermolene/TiddlyWiki5#2769]
I was not sure, whether this problem is caused by some problem relating to TW5 or Node.js or rather by Tiddlymap, that's why i also reference this questions here to the TW5-repository here.

The Problemdescription is here: https://github.com/felixhayashi/TW5-TiddlyMap/issues/257

Thanks for your help, Greetings

**Comment by Jermolene** [comment]
Hi @gesundelehre I've replied over on the TiddlyMap issue.
