### ISSUE TITLE
Tiddler editor background (Color palette) not working as expected

### ISSUE THREAD

**Issue by gernert** [Jermolene/TiddlyWiki5#2772]
Triggered by a question in the [Google group](https://groups.google.com/d/msg/tiddlywiki/fEfTdazhG9k/9fDaYUPkCgAJ) about the background color of the tiddler in edit mode, I found Chinny Hoogler pointing to the Color palette where 'Tiddler editor background' did not behave as expected.

If you change 'Tiddler editor background (tiddler-editor-background)', it colors:
* title input area
* tag input area 
* field input area (name & value)
but **not** the text area

If you change 'Tiddler editor border (tiddler-editor-border)', it colors (as expected):
* title input area
* tag input area
* text area
* field input area (name & value)

'Tiddler editor border image (tiddler-editor-border-image)', 'Tiddler editor background for even fields (tiddler-editor-fields-even)', and 'Tiddler editor background for odd fields (tiddler-editor-fields-odd)' work as expected.

I thought may be the new editor toolbar was the problem but that is not true:
* Switching the editor toolbar on/off has no effect on the text area
* TW5.1.11 (before the editor toolbar) behaves the same for the text area

**Comment by Jermolene** [comment]
Thanks @gernert

**Comment by gernert** [comment]
That's real fast!
