### ISSUE TITLE
New plugins not working after a restart (pre-release version)

### ISSUE THREAD

**Issue by Awerick** [Jermolene/TiddlyWiki5#2783]
It seems, the _"Major refactoring of filesystemadaptor"_ ([3708f6c](https://github.com/Jermolene/TiddlyWiki5/commit/3708f6c8e4f4bf2ea1cb10b0)) affected the installation of new plugins:
New plugins (previously saved as `.json.tid`, now saved as `.json` and `.json.meta`) can still be installed and used – but after a restart they are not recognized anymore!

**Steps to reproduce:**
 *  (Create a new tiddlywiki)
 *  Install a plugin from the "Official TiddlyWiki Plugin Library" (via the "ControlPanel")
 *  Restart the server
 *  _Expected result_: Plugin should be working
 *  _Actual result_: Plugin is not working (not even shown as installed)

**Comment by Jermolene** [comment]
Thanks @Awerick.

The problem here is that the tiddler loading code treats JSON files specially, and doesn't look for the `.meta` file. The fix is to similarly treat JSON tiddlers specially on saving; commit coming up.
