### ISSUE TITLE
Cannot load Official Plugin Library from a site hosted on https

### ISSUE THREAD

**Issue by mklauber** [Jermolene/TiddlyWiki5#2788]
At present, the official plugin library url points to `http://tiddlywiki.com/library/v5.1.13/index.html`.  If the user is on a site loaded over https, access to the official plugin library is blocked by browser security.  

Attempting to workaround this by changing the plugin library url to `//tiddlywiki.com/library/v5.1.13/index.html` does not resolve the issue because `https://tiddlywiki.com` is hosted by github.com and gets github.com's SSL cert, which is not valid for tiddlywiki.com.

Using the direct github address (https://jermolene.github.io/library/v5.1.13/index.html) does not work at present because that repository is configured with a CNAME directive that redirects any attempts to access it at jermolene.github.io/* to tiddlywiki.com/*.

Proposed Resolutions:
* Remove the CNAME for the pages at jermolene.github.io to allow directly accessing it.
* Host a copy of the library in a new repo without a CNAME to avoid the CNAME related issues.
* Host the tiddlywiki library independently, and use a custom cert.

**Comment by Arlen22** [comment]
> Attempting to workaround this by changing the plugin library url to //tiddlywiki.com/library/v5.1.13/index.html does not resolve the issue because https://tiddlywiki.com is hosted by github.com and gets github.com's SSL cert, which is not valid for tiddlywiki.com.

I just checked on my own site, and this is the entire problem. It appears that the second option is the most doable one, as there is no easy way to do a custom cert, it seems. Someone could just fork it and maintain it that way, or @Jermolene could push to two git repos at once perhaps? I don't understand git much but it seems like that shouldn't be too hard. 

I'm pretty sure you can have a `username.github.io` and a project `username.github.io/project` both hosted, but whether they both have to be hosted on the custom domain, I don't really know how that works.

**Comment by Jermolene** [comment]
Fixed in #3005
