### ISSUE TITLE
Links in buttons don't work in FF

### ISSUE THREAD

**Issue by twMat** [Jermolene/TiddlyWiki5#2790]
```
<$button>
aaa [[bbb]] ccc
</$button>
```

In e.g Chrome the "bbb" is a working link. Not so in FF (even in spite of styling like a link!).

This also doesn't work with plain html markup.  But, reasoning that the buttonwidget is a "layer" on top of the html elements I'm hoping this problem could be circumvented in TW.

A concrete use case is my [TabLinks](http://tablinks2.tiddlyspot.com/#) plugin, which adds links inside *tabs* (where the tabs widget apparently is based on buttons).

In some way this feels related to #1880 that points out that CamelCase autolinking creates a link inside the link for e.g;

`<$link to="foo">Linking in WikiText</$link>`

Apparently there are reasons to keep that incidental behaviour (see thread).  For my above OP, links in buttons, the user has a very deliberate purpose, so the case is even more justified IMO.

**Comment by Jermolene** [comment]
Hi @twMat OK, so here you're asking if we can make it so that links within buttons work reliably across browsers.

Sadly, HTML defines quite strict rules about which elements can contain which other elements, and button elements are not allowed to contain "interactive content", which includes links:

https://www.w3.org/TR/html5/forms.html#the-button-element

So, the position we're in is that links within buttons work "unofficially" in some browsers, but not in all browsers. There is no way to "fix" the behaviour of browsers that disallow links within buttons without changing the conditions (eg using a fake button).

**Comment by inmysocks** [comment]
I actually ran into a similar problem recently. Would it be possible to extend the action-navigate widget to work with external links? Or to create an action-link widget that allows opening external links? I just realised that would help yesterday so I haven't had time to actually look at it yet.

**Comment by Jermolene** [comment]
> Would it be possible to extend the action-navigate widget to work with external links? Or to create an action-link widget that allows opening external links? I just realised that would help yesterday so I haven't had time to actually look at it yet.

I think @pmario did some work recently on a `wm-*` message to open an external link?

**Comment by pmario** [comment]
>I think @pmario did some work recently on a wm-* message to open an external link?

@Jermolene: Do you mean PR: first try - tm-open-external-window plus documentation. #2721
demo: http://2721.tiddlyspot.com/#WidgetMessage%3A%20tm-open-external-window

I'm not sure, if that's what the OP requested, because I wanted to open a new browser window or tab (depending on browser settings)

.... but it may be, what @inmysocks wants.

**Comment by twMat** [comment]
@Jermolene - thanks for reply

>There is no way to "fix" the behaviour of browsers that disallow links within buttons without changing the conditions (eg using a fake button).

Is there a particular reason why `<$button>` is based on `<button>`? I.e does the latter bring something crucial that is not achievable with fake buttons?

**Comment by pmario** [comment]
One reason may be, that screen readers don't know what to do with "fake-buttons", but they can handle built in buttons quite well.

**Comment by twMat** [comment]
Surely that must depend on how you fake it? A possible route might be to style a link to make it appear like a button, which I think would be un-problematic also for screen readers.  But I might be missing something.

**Comment by sukima** [comment]
I'm confused what would the intention be to add a clickable element inside a clickable element? What does it mean to click an HTML link and a button at the same time? In fact, [this SO answer](http://stackoverflow.com/a/17253457/227176) sums it up:

> Content model: Phrasing content, but there must be **no** interactive content descendant.
[HTML5 Spec](http://www.w3.org/TR/2011/WD-html5-20110525/the-button-element.html#the-button-element) (Emphasis mine)

`<a>` is an *interactive content*. It is not allowed by the spec and the fact that some browsers handle it is a mistake.

**Comment by twMat** [comment]
@sukima - It is not really to *activate* them both at the same time, at least not my use cases, but to have an area that behaves differently.

At an elementary level I *agree* with you and the HTML5 Spec. But we're talking about `<$button>` not `<button>` and, as noted, the former would probably not even have to be based on the latter **if that would make `<$button>` more useful for us**.

An familiar example that is easy to envision; Imagine a "tabs storyview" showing tiddlers like browser tabs. It would be very cool if we could use the tabs macro and have a small "x" to close (= remove) individual tabs.

**Comment by pmario** [comment]
>An familiar example that is easy to envision; Imagine a "tabs storyview" showing tiddlers like browser tabs. It would be very cool if we could use the tabs macro and have a small "x" to close (= remove) individual tabs.

IMO this works out of the box. We just would need a new tabs macro, that behaves that way.

**Comment by twMat** [comment]
>IMO this works out of the box. We just would need a new tabs macro, that behaves that way.

Ah, you're right, bad example. since `tabs` is a macro. Should have stuck with the button widget.

**Comment by Jermolene** [comment]
Hi @twMat a design goal for TW5 was to generate "correct" HTML5 where we use the semantically appropriate element; which we mostly achieve. The primary goal is to support users with screenreaders. [This article](http://html5doctor.com/lets-talk-about-semantics/) is a reasonable summary of the general issues.

**Comment by twMat** [comment]
@Jermolene - OK, so that disqualifies the OP.
I guess an alternative route might then be some other very similar but new widget... which seems very unlikely to be worked on.
Closing this issue.
Thanks for input.

**Comment by Jermolene** [comment]
The `<$button>` widget has a "tag" attribute that allows you to override which HTML element it generates. If you make it generate a div or a span then you'll avoid the button nesting problem.
