### ISSUE TITLE
Incorrect message when _canonical_uri image

### ISSUE THREAD

**Issue by twMat** [Jermolene/TiddlyWiki5#2796]
In single file TW, including an image-link via the _canonical_uri field and setting to type png shows the following as tiddler body in edit mode:

`This is an external tiddler stored outside of the main TiddlyWiki file. You can edit the tags and fields but cannot directly edit the content itself`

IMO this is not correct and I propose the following instead:

`This tiddler shows content stored outside of the TiddlyWiki file. You can edit the tags and fields but cannot directly edit the content itself`

**Comment by xcazin** [comment]
Hi Mat,

While we're at it, I propose that we also make a PR regarding the message displayed when the external content cannot be displayed. It currently reads:

> Loading external text from **https://commons.wikimedia.org/wiki/Category:SVG_animal_icons#/media/File:Lapin-bouh.svg**
>
> If this message doesn't disappear you may be using a browser that doesn't support external text 
> in this configuration. See http://tiddlywiki.com/#ExternalText

Usually, the issue is merely that the default Tiddlywiki type has not been adjusted. So I propose instead:

> Trying to load external text from **https://commons.wikimedia.org/wiki/Category:SVG_animal_icons#/media/File:Lapin-bouh.svg**
>
> If this message doesn't disappear, you may either need to adjust the tiddler type to your external content type, or you may be using a browser that doesn't support external text in this configuration. See http://tiddlywiki.com/#ExternalText

Xavier.

**Comment by twMat** [comment]
@xcazin Hi Xavier. Yeah, sounds reasonable.

As for making a PR; I am not quite sure how to go about this. It is not documentation (which I do know how to PR)  and there's also the multiple language matter. So, anyone qualified, feel free to make a PR.  :-)

**Comment by Jermolene** [comment]
Thank you @pmario
