### ISSUE TITLE
Content type image/svg has drawing tools but text area

### ISSUE THREAD

**Issue by twMat** [Jermolene/TiddlyWiki5#2804]
![image](https://cloud.githubusercontent.com/assets/4534056/23969384/94746ab0-09c6-11e7-919f-9a3f5d3343da.png)

**Comment by pmario** [comment]
There is no svg editor in the core. So it should be text only. IMO SVG editors are plugin territory, because of size.

**Comment by pmario** [comment]
@twMat -- Can be closed. It seems we did remove the drawing tools some time ago. 

![image](https://github.com/Jermolene/TiddlyWiki5/assets/374655/ae821ea0-c19e-476d-951a-b4c7a008ae07)
