### ISSUE TITLE
d&d: RSOD dragging highlighted text into dropzone

### ISSUE THREAD

**Issue by pmario** [Jermolene/TiddlyWiki5#2809]
to reproduce

 - open [tw-prerelease](http://tiddlywiki.com/prerelease/)
 - highlight mark some text.
 - drag and drop this text into a d&d dropzone
 -> RSOD

**Comment by Jermolene** [comment]
Thanks @pmario! Fixed in bea33efd63daaa705947e25443769336fbe9c63e
