### ISSUE TITLE
Properly save local filenames that contain spaces.

### ISSUE THREAD

**Issue by DelphiCoder** [Jermolene/TiddlyWiki5#2819]
This is an easy fix and I have done so by adding one simple line to `$:/core/modules/savers/download.js` and `$:/core/modules/savers/msdownload.js`

The problem is that if you have a local filename containing one or more spaces like `My File.html` and then you save it locally, it becomes `My%20File.html`, and after the next load and save `My%2520File.html`, then `My%252520File.html`.  

If you save and reload the file enough times, `My File.html` becomes `My%25252525252525252525252525252520File.html`

Both `download.js` and `msdownload.js` have the same section in their code:

```
if(p !== -1) {
	filename = document.location.pathname.substr(p+1);;
}
```

Simply adding an additional line of code to replace the %20 with a space character repairs this issue like so:

```
if(p !== -1) {
	filename = document.location.pathname.substr(p+1);
	filename = filename.replace(/%20/g, " ");
}
```

- I'm sure there are others that wish to use space characters within file names and hate having to constantly remove the %20 characters from them.

Thank you,

Douglas Counts

**Comment by Jermolene** [comment]
Hi @DelphiCoder I believe that this problem is due to implicit URL encoding when retrieving the document location. The solution here only fixes spaces; we should deal with all URL encoded characters. In any case, I'm afraid this is too late for 5.1.14.
