### ISSUE TITLE
Possible PR: prettier tabs

### ISSUE THREAD

**Issue by twMat** [Jermolene/TiddlyWiki5#2827]
[demo](http://clearertabs.tiddlyspot.com/)

A long time annoyance for me has been the tab styling. They are way too dominant, IMO. 

@Jermolene - I'd be happy to rework my draft into a PR but this would probably mean having to edit both the themes vanilla and snowwhite as well palette colour refs so I only want to do this if I know it'll be accepted (obviously, presuming the code is good enough).

Thanks!

**Comment by Jermolene** [comment]
Hi @twMat a good first step might be to share some bitmap mockups so we can see what you're aiming for?

**Comment by twMat** [comment]
Hm, is the demo not enough? 

Thanks for fast reply!

**Comment by Jermolene** [comment]
Well, either way, lets first agree on the desired visual appearance, and then worry about the implementation details 😄

**Comment by twMat** [comment]
Sure! Is there anything you don't like in the demo? Any opinion what would improve it? :-)

**Comment by Jermolene** [comment]
Ah, I missed the link to the demo, thank you @twMat !

**Comment by Jermolene** [comment]
They look good @twMat but I don't think they are suitable for the default theme(s), which are intended to be crisp and unambiguous. Furthermore, I'd be concerned about backwards compatibility with existing custom styles.

**Comment by twMat** [comment]
Ok, fair enough :-)
