### ISSUE TITLE
Last call for changes for 5.1.14 

### ISSUE THREAD

**Issue by Jermolene** [Jermolene/TiddlyWiki5#2829]
I plan to release 5.1.14 later this week. That means shaking down any missed bugs or incompatibilities, and avoiding any further major changes.

I've updated the release notes, and uploaded a new build to http://tiddlywiki.com/prerelease.

This would be a good time for developers like @danielo515, @buggyj, @felixhayashi, @pmario, @tobibeer, @twMat (and everyone I've forgotten to mention) to give the latest code a final run through with your various wikis, plugins and other tools.

One controversial feature that I have not had much feedback on is the switch to plain text to display system tiddlers that have more than one slash in their title #2814. It makes it much harder to accidentally trigger recursion errors, but I'm concerned that it may have unexpected side effects.

Thanks to everyone for your help.

**Comment by twMat** [comment]
>One controversial feature that I have not had much feedback on is the switch to plain text to display system tiddlers that have more than one slash in their title #2814. It makes it much harder to accidentally trigger recursion errors, but I'm concerned that it may have unexpected side effects.

Hopefully not too late, I just posted some comments in that thread (#2814). My proposed solution there is much more conventional and should omit any such potential "unexpected side effects", but that is not really my primary arguments for it.

**Comment by DelphiCoder** [comment]
It would be great if the problem with saving local files with space characters in the name could be fixed too.  Issue [2819](https://github.com/Jermolene/TiddlyWiki5/issues/2819). Only requires the addition of a single line to download.js to support HTML5 saves with space character included file names.  Same single line addition to msdownload.js to support older IE versions too.  No reason to escape character codes if the file is saved locally that I can imagine.

**Comment by gernert** [comment]
Updated Dutch translation can be found at http://tw5dutch.tiddlyspot.com/

**Comment by CodaCodr** [comment]
I'm a big user of right-hand-only copy/paste (Ctrl-Insert, Shift-Insert). The former works, the latter does not which is painful.

Tested 
  http://tiddlywiki.com/prerelease/ Win7, Firefox 52.0
  http://tiddlywiki.com/prerelease/ Win10, Firefox 52.0.1

**Comment by CodaCodr** [comment]
I'm seeing repaint/reflow where there was none (visible anyway) before. Noticeable mostly for items tagged $:/tags/PageTemplate. It's most noticeable when the item is revealed using CSS :hover - if I click a checkbox which causes a state change elsewhere, a repaint/reflow occurs on the PageTemplate item (host) making it disappear (and, if the mouse is in the correct hover position, reappear).

**Comment by Jermolene** [comment]
Thanks @DelphiCoder I'll comment on that issue but the TLDR is that I don't think the proposed fix is adequate.

@CodaCodr are both of those issues regressions from 5.1.13? Can you provide a test case for the second one?

**Comment by Jermolene** [comment]
Hi @gernert I've merged the update, many thanks

**Comment by CodaCodr** [comment]
@Jermolene 

I upgraded from 5.1.11 - it went along pretty sweet, fyi.

As for the testcase, first I'll post a couple of GIFs - a proper test case will take a while longer.

**Comment by Jermolene** [comment]
Hi @CodaCodr to be clearer, I'm particularly interested here in finding bugs introduced in 5.1.14. If it's something that became broken in an earlier version then there's no reason for it to hold up the release of 5.1.14.

**Comment by CodaCodr** [comment]
@Jermolene Understood.  Not sure how I can tell for sure.

![tw-5 1 11](https://cloud.githubusercontent.com/assets/436812/25152138/b4438550-244d-11e7-8cb9-d5f999a8f85c.gif)

![tw-5 1 14](https://cloud.githubusercontent.com/assets/436812/25152168/c76e3486-244d-11e7-8842-85e59b06a701.gif)

**Comment by Jermolene** [comment]
Hi @CodaCodr yikes! Perhaps a case for git bisect? I'd be very interested to understand the issue.

**Comment by CodaCodr** [comment]
Yeah, I thought you ought to see it and might be alarmed.  That's a very "graphic" and obvious one... there are others too but harder to display.  

It's a "big" system - should be an "edition" but I'm not there yet. Perhaps I'll carve up Alice in Wonderland and send it across to you to have a play. (Time, as ever, is the killer)

**Comment by Jermolene** [comment]
Hi @CodaCodr I won't have time to examine your code for a while; can you run a git bisect to track it down?

**Comment by CodaCodr** [comment]
@Jermolene I have no idea how to do that.

**Comment by Jermolene** [comment]
Try http://webchick.net/node/99

**Comment by CodaCodr** [comment]
@Jermolene and, key point, it's not "my code" in the sense that it's all *your* JS.  All I've done is use regular templates/macros etc.

**Comment by Jermolene** [comment]
Hi @CodaCodr sorry if I misunderstood. I just mean that I am on a race to get 5.1.14 out of the door and am concerned that if your "big" system is complicated I'm going to find it tough to track things down. Not a problem if you're unfamiliar with git bisect, but I need all the help I can get to get this done. When I said "Yikes" it wasn't that I thought the bug was serious but that your test case looked too complicated for me to even understand what you were pointing out. Sorry!

**Comment by CodaCodr** [comment]
@Jermolene Got it.  Better if I knock up a test case.

**Comment by pmario** [comment]
@Jermolene can be closed

**Comment by danielo515** [comment]
I was about to say exactly the same. This can be closed
