### ISSUE TITLE
What is special about TiddlyWiki5 + node.js?

### ISSUE THREAD

**Issue by bythckr** [Jermolene/TiddlyWiki5#2836]
I am a very basic user of tiddlywiki and my knowledge about node.js or js is very poor.

I believe that I know how tw works. I am confused as to why would I need node.js. What extra functionalities does it add? How is this different from tiddlywiki Desktop?

**Comment by twMat** [comment]
Hi @bythckr 

You question is a good one but much better asked on the [discussion forum](https://groups.google.com/forum/#!forum/tiddlywiki). Please close this thread and post there instead.

Here in github we try to keep issues to be "actionable" things that can be implemented in the code.

**Comment by bythckr** [comment]
Sorry about that @twMat, I was unaware of the forum. I [posted it](https://groups.google.com/forum/#!topic/tiddlywiki/-J7CGyF7uY8).
