### ISSUE TITLE
Contents of - core - themes cannot be seen

### ISSUE THREAD

**Issue by gernert** [Jermolene/TiddlyWiki5#2841]
Core plugins do - at least - have tabs 'readme' and 'contents'; 'contents' lists the separate tiddlers of the plugin.
Core themes do not have 'readme' and/or 'contents'. To inspect the styles of a theme you have to search for the 'base' part of the theme under the shadow tiddlers which is cumbersome.

My own themes do show the tabs 'readme' and 'contents' so the 'contents' mechanism is working there.

Has it something to do with the missing 'readme' tiddlers in the core themes?

**Comment by pmario** [comment]
Themes are plugins. see:https://github.com/Jermolene/TiddlyWiki5/tree/master/themes/tiddlywiki/snowwhite

So I think it's just an oversight, and should be added.

**Comment by Jermolene** [comment]
Thanks @gernert 

The problem is that the "No information provided" text is displayed if the plugin doesn't provide any information pages, and the themes lack a "readme". (The "contents" tab is special, and included automatically for all plugins).

Anyhow, a fix is upcoming.
