### ISSUE TITLE
Pill handle to drag filtered lists

### ISSUE THREAD

**Issue by twMat** [Jermolene/TiddlyWiki5#2843]
**Proposal**
I want something similar to tagpills for drag handles but for explicit lists or, ideally, *filters* like so 

`<<pill "label" "foo bar frotz">>`

The current *tag'n drag* solution is insufficient as it requires *modifying* the tiddlers.

**Background**
Any plugin author is likely to eventually want to **reuse**  existing functionalities for a new plugin. This can be anything from someone elses extra *filter operators* to full feature plugins  (e.g my Toggle macro) or various stylesheets.

It is not a good idea to copy such supporting plugins into the new plugin nor to modify them with tags. So currently the author has to serve all those components separately for the end user to drag'n drop. Not elegant. Plus, at least I feel compelled to explain that "this is a supporting plugin that you must also install because..." 

Instead, a single tagpill should serve as a draggable handle for whatever is in it.

**Comment by AnthonyMuscio** [comment]
I would like this very much especialy if the second parameter could be any filter.  

Arguably a clone of the existing tag macro would be a good start but it would be nice if label could be used on the tag macro as well.

**Comment by pmario** [comment]
I'll probably release something very similar with the "story handling". It should be able to handle lists and filtered lists at the same time. 

BUT drag and droping filters like: `[tag[title with spaces]]` causes some problems I need to solve. .. That's actually causing the delay.

**Comment by saqimtiaz** [comment]
@twMat Is this still relevant considering changes to the ButtonWidget since the PR was created? You can use the ButtonWidget with the dragFilter attribute. You have complete control over appearance as well as the drag payload.

`<$button dragFilter=<<myfilter>> > my label </$button>`

This should get you close to the tag pill appearance as well:

```
\define dragPill(label filter)
<$button tag="span" class="tc-tag-label" dragFilter="""$filter$""" style="
fill:#333333;color:#333333;cursor:pointer;"><$text text="""$label$"""/></$button>
\end
```

**Comment by twMat** [comment]
Thanks @saqimtiaz . I'm happy to see this is possible *but* it is missing the possibility to click it to get a peek of what it contains.

Further, something like this ought to be part of core or the standard distro. I'd think a good implementation could let us deprecate the *tag* macro because it'd be a mere subset and pretty limited at that. (Other than up in the tags list, it is of little practical use.)

**Comment by twMat** [comment]
>`<$button dragFilter=<<myfilter>> > my label </$button>`

@saqimtiaz 
Your solution *is* adequate, after all. And very dynamic. Thank you very much!
Mom says I may be slow but I'm at least pretty!

**Comment by twMat** [comment]
One addition though: It ought to be a core macro because the concept with a single "drag handle" for multiple tiddlers should be useful in many situations.
