### ISSUE TITLE
"New Journal" functions incorrectly if journal already exists

### ISSUE THREAD

**Issue by Jermolene** [Jermolene/TiddlyWiki5#2845]
As raised by Sean Boyle [over on the mailing list](https://groups.google.com/d/msgid/tiddlywiki/e0766fe7-f073-4794-94bb-115ae287a152%40googlegroups.com):

> In version &lt; 5.1.14, if a journal for a given day (name) exists when the New Journal button is clicked, it simply opened the existing tiddler.  The behaviour now seems to be to open a blank tiddler with the same name.  If this is saved, it overwrites the current version.  If it is exited w/o saving, the old tiddler appears with content intact.
> 
> Is anyone else experiencing this?
> Have I been taking advantage of a beacher all along? (bug which has become a feature)

**Comment by gernert** [comment]
"In version ≤ 5.1.14" must be "In version < 5.1.14"

**Comment by Jermolene** [comment]
Thanks @gernert I've updated the OP

**Comment by hoelzro** [comment]
ec0fa2f9322346ec405b90356de03c66ae30cc0d appears to be the problematic commit

**Comment by ArtursDen** [comment]
I noticed this aswell, was thinking it was a bug I caused, but then I downloaded a vanilla (empty) TWiki, tried it out and the bug persisted.

**Comment by yesasha** [comment]
I have this bug, exactly.

**Comment by twMat** [comment]
>"In version ≤ 5.1.14" must be "In version < 5.1.14"

IMO revert OP back to state "≤ 5.1.14" as it is still prevalent.

**Comment by gernert** [comment]
@twMat If you read the [OP](https://groups.google.com/d/msg/tiddlywiki/3KCr0a318zs/oVGFf8LbBAAJ) it did work as expected **before** 5.1.14, but the wrong 'code' &le; (≤ ) was used in the OP.

**Comment by twMat** [comment]
@gernert - aha! Thanks Ton. 
@ all - Please disregard my previous post.

**Comment by diego898** [comment]
This has been an issue that has bitten me in the past! Also, this is an issue with a custom new journal button that uses the date as a tiddler title. Where would a potential fix be?

**Comment by Jermolene** [comment]
This problem was introduced by #2821 back in April. Fix upcoming.

**Comment by diego898** [comment]
ok thanks!

**Comment by pmario** [comment]
@Jermolene ... IMO can be closed.

**Comment by Jermolene** [comment]
Thanks @pmario
