### ISSUE TITLE
Please fix Shift-Insert (paste on Windows)

### ISSUE THREAD

**Issue by CodaCodr** [Jermolene/TiddlyWiki5#2847]
The key combination **Shift-Insert** is an alternative (to Ctrl-V) paste command on Windows.  It no longer works in TW5.

It works in version 5.1.11 and is broken in 5.1.14 (tiddlywiki.com).

Sorry I cannot be more precise about *when* it was originally broken.

**Comment by Jermolene** [comment]
Hi @CodaCodr does switching off the editor toolbar make a difference? (Control Panel -> Settings -> Editor Toolbar -> off)

**Comment by CodaCodr** [comment]
Yes

**Comment by Jermolene** [comment]
And you don't have any custom keyboard shortcuts mapped to Shift-Insert?

One possibility is that Shift-Insert is being misread for a different key. What do you see when you type Shift-Insert into the blue text box in this illustration:

<img width="1288" alt="screenshot 2017-05-04 18 25 52" src="https://cloud.githubusercontent.com/assets/174761/25716503/29b1bd9c-30f7-11e7-89d2-498fb7d6fb59.png">

**Comment by CodaCodr** [comment]
![image](https://cloud.githubusercontent.com/assets/436812/25716731/b62f3eca-30c5-11e7-98f6-e8cc0687aeb2.png)

**Comment by CodaCodr** [comment]
Agreed. Fixed. And probably has been for quite some time -- I forgot all about this.
