### ISSUE TITLE
Importing a tiddler via JSON with a trailing whitespace in its title creates an uneditable tiddler

### ISSUE THREAD

**Issue by hoelzro** [Jermolene/TiddlyWiki5#2850]
Steps to reproduce:

  1) Load http://tiddlywiki.com
  2) Import the `.json` file below (note the trailing whitespace in the title field)
  3) Edit the new tiddler
  4) Note that a new tiddler is created with the trailing whitespace stripped; editing the trailing whitespace tiddler will replace that new tiddler

The trailing whitespace tiddler is still deletable, thankfully.

```json
[
    {
        "created": "20170508133011823",
        "title": "Testing 1 2 3 ",
        "type": "application/x-tiddler",
        "modified": "20170508133134537",
        "tags": "",
        "text": "hello"
    }
]
```

**Comment by Jermolene** [comment]
Hi @hoelzro great stuff! Interesting to see the unintended consequences of the whitespace trimming. It should be fixable, though, I'll investigate.

**Comment by hoelzro** [comment]
@Jermolene Have you had a chance to look at this? I took a stab at it in #2852 - please let me know if that PR needs more work!

**Comment by Jermolene** [comment]
Fixed in https://github.com/Jermolene/TiddlyWiki5/commit/847727146ef401242ef4e000d8411f6180e4a2fe
