### ISSUE TITLE
'Blurred' text in tag pills in the sidebar

### ISSUE THREAD

**Issue by gernert** [Jermolene/TiddlyWiki5#2851]
For some reason the Snow White theme adds a white drop shadow to the text in tag pills in the sidebar ('Tags' tab in sidebar) which makes the text less readable especially with a dark background of the tag pill (and thus with white text).

See e.g. at http://tiddlywiki.com/ the tag 'done'.

Note:
* The 'untagged' tag does not show a drop shadow
* Tags in tiddlers do not show a drop shadow

I prefer the Vanilla theme look for the tag pills in the sidebar.
![colored_tags](https://cloud.githubusercontent.com/assets/5826020/25823865/ab44dc88-343d-11e7-87cb-237988314c62.png)

**Comment by twMat** [comment]
I track it down to this in $:/themes/tiddlywiki/snowwhite/base

```
.tc-sidebar-header {
	text-shadow: 0 1px 0 <<colour sidebar-foreground-shadow>>;
}
```

AFAICT this is exclusively used in *sidebar > More > Tags*. I agree it should be removed from snowwhite.

**Comment by tobibeer** [comment]
@twMat: care to make a pull request against snowwhite / [base.tid](https://github.com/Jermolene/TiddlyWiki5/blob/cee7baa1831a8f236c46d8c438c2a4d9bda8a0e2/themes/tiddlywiki/snowwhite/base.tid#L6)

I suppose the shadows were meant for `tc-site-title` and `tc-site-subtitle` instead.

**Comment by Jermolene** [comment]
Hi @twMat @tobibeer in fact the text shadow effect is applied to all text in the sidebar, not just the tag pills.

Way back in the past, tag pills independently had a text shadow but that was removed at some point.

**Comment by pmario** [comment]
I think, this is a leftover from times, where users couldn't change text color easily. ... If you have a dark background and a dark text color, it sometimes happened, that the text was invisible. The "default" shadow setting avoided that problem. ... There is still something that you can (almost) read -> the shadow

Now in the OP the "done" text color is white ... with a white shadow, which causes a problem.

**Comment by tobibeer** [comment]
> Now in the OP the "done" text color is white ... with a white shadow, which causes a problem.

So, in other words, some contrast color should apply to the shadow instead of a general shadow.

Anyhow. I don't see the problem you describe to apply to tag buttons. So, the text of those definitely should not have shadows, imho.

**Comment by pmario** [comment]
@Jermolene -- Can be closed. We did fix this a long time ago.  Screenshot v5.3.1

![image](https://github.com/Jermolene/TiddlyWiki5/assets/374655/25e36cc0-ddd5-4706-af59-44e79a5f3084)

**Comment by Jermolene** [comment]
Thank you @pmario
