### ISSUE TITLE
Feature Request: Related Words/Tags

### ISSUE THREAD

**Issue by diego898** [Jermolene/TiddlyWiki5#2854]
I think a very useful feature for tiddlywiki, would the concept of a related word/tag.

When I search for "USA", I'd like the option to see posts tagged/or mention USA, posts tagged/mention America, posts tagged/mention US, etc.  

I am very new to TiddlyWiki, but this could perhaps be accomplished with a "Related Tag" system where I specify a new Tiddler called "Related Tags: USA" and in that tiddler, list all items I would like to be "related" to that tag. 

What do you guys think?

**Comment by pmario** [comment]
IO thats already there. If you open eg: http://tiddlywiki.com/#HelloThere : More: Info: References
you can see all the tiddlers, that use the link HelloThere. In your case you just need to use [[USA]], [[America]] or [[US]], to achieve, what you want. 

The "More: Info" tiddler toolbar button also contains "Tagging", "List" and "Listed" tabs.

see: http://tiddlywiki.com/#Reference%20Tiddlers:%5B%5BReference%20Tiddlers%5D%5D%20ListField%20%5B%5Blisted%20Operator%5D%5D%20Tagging

**Comment by twMat** [comment]
>When I search for [...]

@diego898 - I agree with you; The sole purpose of *searching* is to *find*, so of course searching should list everything that you are likely to want.

I created http://searchwords.tiddlyspot.com/ for this. It does not use a global list of associations but instead lets you add custom associations on a per tiddler basis.

**Comment by danielo515** [comment]
I have a small customization in one of my wikis , and it is very convenient. Maybe someday I find the time to ship it as a plugin

**Comment by twMat** [comment]
>I have a small customization in one of my wikis , and it is very convenient. Maybe someday I find the time to ship it as a plugin

@danielo515 ... that's probably one of the *least* useful posts you've ever posted ;-) ;-)

**Comment by danielo515** [comment]
@twMat sorry about that. It's a placeholder to remind me what I have to do and to which it is related to.

Let's see if you find this more useful:

Edit template:

```
title: $:/_EditTemplate/relateTiddlers
tags: $:/tags/EditTemplate

\define filter() [!is[current]$(tagfilter)$!list[!!related]limit[10]]
\define relatewith() $(current)$ [[$(with)$]]

<small>
<$edit-text tiddler="$:/temp/search/relate" default="" tag="input" placeholder="search for relate"/>

<$set name="current" value={{!!related}}>
<$fieldmangler>
<$list filter="[!list[!!related]!is[current]!is[system]search{$:/temp/search/relate}limit[10]]" variable="with">
<$button class="tc-btn-invisible tc-tiddlylink uc-btn-relate"><<with>>
<$action-sendmessage $message="tm-add-field" related=<<relatewith>>/>
</$button>
</$list>
<!-- Relate based on tags -->
<$set name="tagfilter" value=<<extractTagsAsFilter>> >
<$list filter=<<filter>> variable="with">
<$button><<with>>
<$action-sendmessage $message="tm-add-field" related=<<relatewith>>/>
</$button>
</$list>
</$set>
</$fieldmangler>
</$set>
</small>
```
View template

```html
title: $:/_ViewTemplate/relate
tags: $:/tags/ViewTemplate

<$list filter="[all[current]has[source]]">
,,''Source:'' {{!!source}},,
</$list>
<br>
<small>
<$list filter="[all[current]has[related]]">''See also:'' <$list filter="[list[!!related]]"> <$link>{{!!title}}</$link>,</$list></$list>
<$list filter="[all[current]listed[related]!list[!!related]]"> <$link>{{!!title}}</$link>,</$list>
</small>
```

Now anyone is able to turn it into a plugin.

> that's probably one of the least useful posts you've ever posted ;-) ;-)

You have to admit that your post is not of much use neither.

**Comment by danielo515** [comment]
What I  have posted shows relations in both directions, at the tiddler that points to the other one and at the one that is being pointed

**Comment by diego898** [comment]
@danielo515 - so I create two new tiddlers named `$:/_ViewTemplate/relate` and `$:/_ViewTemplate/relate` with that content?

**Comment by danielo515** [comment]
That's correct. The I terrace it's not pretty but works for me. You can use the search field to narrow the number of elements that appear. There are two sections, one based on your search term and another based on tags. I don't remember the logic behind it right now

**Comment by danielo515** [comment]
I don't know why are you seeing so many system tiddlers. IT does not happen to me

**Comment by danielo515** [comment]
Seems that I forgot to include one macro called extractTagsAsFilter

**Comment by diego898** [comment]
@danielo515 can you add it?

**Comment by danielo515** [comment]
Here is the macro.

It is part of one of my plugins (tagSearch)

```js
/*\
created: 20140110061443770
creator: Danielo Rodriguez
modified: 20140415014136920
modifier: Danielo
tags: macros
title: $:/plugins/danielo/tagSearch/macros/extractTagsAsFilter.js
type: application/javascript
module-type: macro
\*/
(function(){

/*jslint node: true, browser: true */
/*global $tw: false */
"use strict";

/*
Information about this macro
This is developed to .
*/

exports.name = "extractTagsAsFilter";

exports.params = [
	{ name: "tiddlerName" }
];

/*
Run the macro
*/
exports.run = function(tiddlerName) {
   var tiddler=$tw.wiki.getTiddler(tiddlerName || this.getVariable("currentTiddler") ) ;
    var result="";
    if(tiddler && tiddler.fields.tags)
    {
        var tags=tiddler.fields.tags;
        for(var i=0; i<tags.length; i++)
            result+="tag["+tags[i]+"]";
    }

return result;
}

})();
```

**Comment by diego898** [comment]
Im closing this, as I think @pmario 's unilink plugin and searching for "aliases" address a lot of this.
