### ISSUE TITLE
RSOD when selecting $:/core/templates/raw-static-tiddler

### ISSUE THREAD

**Issue by gernert** [Jermolene/TiddlyWiki5#2863]
Steps to reproduce (at tiddlywiki.com):

1. Search for the shadow tiddler $:/core/templates/raw-static-tiddler
2. Click the link for $:/core/templates/raw-static-tiddler => RSOD (Uncaught RangeError: Maximum call stack size exceeded)

The strange thing is this template contains nothing 'special':

```
<!--

This template is used for saving tiddlers as static HTML

--><$view field="text" format="plainwikified" />
```

**Comment by pmario** [comment]
.. it is special.. It calls `view text` which renders `view text`, that calls `view text` which renders `view text` to call `view text` ... :))

it's a recursion, which seems to be not detected by the core atm. So the program eats all your memory ;)

**Comment by gernert** [comment]
But $:/core/templates/plain-text-tiddler behaves 'normal' while it contains:

```
<$view field="text" format="text" />
```

The only difference the format.

**Comment by pmario** [comment]
yes. text is only rendered once. wikified will try to wikify, what it reads. That causes the problem.

**Comment by pmario** [comment]
but it still is a bug. ... The core already has a mechanism to detect recursion. ... but it seems this one managed to escape, somehow.

**Comment by gernert** [comment]
Tnx for clarification.

**Comment by tobibeer** [comment]
Don't even know where to look. Would be neat to see some pointers.

**Comment by Jermolene** [comment]
Hi @tobibeer one way would be to set a breakpoint in the view widget that is conditional on the tiddler title matching `$:/core/templates/raw-static-tiddler`...

**Comment by Jermolene** [comment]
Annoyingly, the recursion protection mechanism we use for transclusion cannot easily be applied to this case.

**Comment by pmario** [comment]
@Jermolene -- Can be closed. [$:/core/templates/raw-static-tiddler](https://tiddlywiki.com/#%24%3A%2Fcore%2Ftemplates%2Fraw-static-tiddler) has a `code-body` field now

**Comment by Jermolene** [comment]
Thank you @pmario
