### ISSUE TITLE
[TW5] Internal Javascript Error

### ISSUE THREAD

**Issue by am517** [Jermolene/TiddlyWiki5#2869]
This week I started getting various javascript errors anytime I edit or open anything. I'm using Ubuntu 17.04 in a VM, npm 7, /usr/bin/node is linked to /usr/bin/nodejs. I created a fresh VM witn a fresh install and had the same error. After running `tiddlywiki --version` the error went a way but it's not clear why.

```
Internal JavaScript Error

Well, this is embarrassing. It is recommended that you restart TiddlyWiki by refreshing your browser
```

```
Uncaught NotFoundError: Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.
```
and

```
Uncaught TypeError: Cannot read property 'removeChild' of null
```
Edit: I just had the same error on http://tiddlywiki.com/dev/ in Chrome. In Firefox I don't get the error. After disabling all the plugins there is no more error, so plugins seem to be the problem.

**Comment by Voleking** [comment]
I got Internal JavaScript Error when visiting [tiddlywiki.com](https://tiddlywiki.com) the first time on Safari, refresh make this disappear. That's a little annoyed, Hope fix.

```
macOS 10.13.3
Safari 11.0.3
```

**Comment by pmario** [comment]
which tiddlywiki version do you use?

IMO you should go with a node 8 LTS version. Which shouldn't be a problem, but I personally only work with stable node LTS versions. They cause much less problems .... for me :)

**Comment by sukima** [comment]
What plugins did you disable? Try each plugin one at a time till the error shows itself and you will know which plugin to report an issue to.

**Comment by sukima** [comment]
What is the stack trace? Does it offer any insight?

As reference I do **not** get any of that with Chrome (latest) or Firefox (latest) on Ubuntu 16 or MacOS High Sierra. It is likely a bad interaction with a browser addon/extension.

**Comment by pmario** [comment]
@Jermolene -- IMO can be closed. There is no way to reproduce this problem. Most components described in the OP are "end of live" already.

**Comment by Jermolene** [comment]
Thank you @pmario
