### ISSUE TITLE
Revert the commit about not sync story list

### ISSUE THREAD

**Issue by danielo515** [Jermolene/TiddlyWiki5#2872]
This is a reminder/discussion for e3544ff3c26256999992ba1ebae5b911c31153f2

I think it should be considered a breaking change, and should be not included in the next production release.

I would like to continue the discussion of that commit here, where more people will be able to participate.

Regards

**Comment by danielo515** [comment]
At this moment I'm not sure about being against the change at e3544ff .
There are few scenarios where sharing the same story list makes sense. Even if you are the same user on different devices you probably don't want the story list to be synced. Each editing session has it's own context, and it is not very likely that you want the same opened tiddlers, and in the same state when you move from one editing session to a new one.

The only problem that comes with this change is that it is literally impossible to store the story list. For example, in the case of NoteSelf I can easily configure a sync-filter to avoid the story list to be synced across devices and still saving it locally, but this is impossible if the story list is not synced at all.

As a conclusion, I'm still convinced that the way story list is handled should be something the sync adapter should take care of.

**Comment by saqimtiaz** [comment]
+1 for reverting this change. It totally breaks the old behaviour to restore the state and open tiddlers after a reload that some users have come to expect. To keep backwards compatibility I suggest we revert this change and allow users that don't want to sync their storylist to edit their sync filter. We could also make this more easily user configurable via a checkbox in settings.

**Comment by danielo515** [comment]
This issue is fixed thanks to cf9085b
