### ISSUE TITLE
http://tiddlywiki.com/ line 26038 > eval:152

### ISSUE THREAD

**Issue by thisname12345** [Jermolene/TiddlyWiki5#2876]
Create a new tiddler in tiddlywiki.com.
Turn preview on and paste

```
text

<!-- [[text|http://tiddlywiki.com/#DateFormat]] -->

<!-- $:/core/ui/ControlPanel/Info -->
```

Move to the first

<!--

and delete it.

Firefox reports unresposive script with this message 

Script: http://tiddlywiki.com/ line 26038 > eval:152

Chrome tab just stops responding. 

Alternatively paste

```
aaaaa --> 
<!--
```

Firefox browser console reports

"TypeError: aRequestOrigin is null"

view source in debugger leads to

"view-source:resource://jid1-f9uj2thwoam5gq-at-jetpack/lib/shared/policy.js"

```
function makeDetails(aContentType, aContentLocation, aRequestOrigin, aContext, aMimeTypeGuess) {
  return {
    type: getTypeMemod(aContentType),
    location: aContentLocation,
    origin: aRequestOrigin.spec,
    context: null, // TODO: support this in a safe way somehow..
    mimeTypeGuess: String(aMimeTypeGuess)
  };
}
```

with "origin: aRequestOrigin.spec" highlighted

**Comment by thisname12345** [comment]
(first attempt to report issue curtailed - here is the continuation)

Move to the first

<!--

and delete it.

Firefox reports unresposive script with this message 

Script: http://tiddlywiki.com/ line 26038 > eval:152

Chrome tab just stops responding. 

The following also causes the same response

```
aaaaa --> 
<!--
```

Firefox browser conole reports "TypeError: aRequestOrigin is null"

view source in debugger leads to "view-source:resource://jid1-f9uj2thwoam5gq-at-jetpack/lib/shared/policy.js"

with " origin: aRequestOrigin.spec," highlighted

```
function makeDetails(aContentType, aContentLocation, aRequestOrigin, aContext, aMimeTypeGuess) {
  return {
    type: getTypeMemod(aContentType),
    location: aContentLocation,
    origin: aRequestOrigin.spec,
    context: null, // TODO: support this in a safe way somehow..
    mimeTypeGuess: String(aMimeTypeGuess)
  };
}
```

**Comment by thisname12345** [comment]
(third try)

Move to the first

```
<!--
```

and delete it.

Firefox reports unresposive script with this message 

Script: http://tiddlywiki.com/ line 26038 > eval:152

Chrome tab just stops responding. 

The following also causes the same response

```
aaaaa --> 
<!--
```

Firefox browser conole reports "TypeError: aRequestOrigin is null"

view source in debugger leads to "view-source:resource://jid1-f9uj2thwoam5gq-at-jetpack/lib/shared/policy.js"

with " origin: aRequestOrigin.spec," highlighted

```
function makeDetails(aContentType, aContentLocation, aRequestOrigin, aContext, aMimeTypeGuess) {
  return {
    type: getTypeMemod(aContentType),
    location: aContentLocation,
    origin: aRequestOrigin.spec,
    context: null, // TODO: support this in a safe way somehow..
    mimeTypeGuess: String(aMimeTypeGuess)
  };
}
```

**Comment by pmario** [comment]
Hi. Thx for creating the issue. I did some more tests too 

eg: the following doesn't cause a problem. 

```
a -->
<!--
```

but this does:  

```
aa -->
<!--
```

So for me it seems to be a problem with a combination of `--` `---` strike-through or n-dash or m-dash and `<!--` start of comment.

**Comment by pmario** [comment]
I think, the strike-through parser is a little bit too greedy.

**Comment by pmario** [comment]
the following works. So the comment-block and/or comment-inline cause the problem
```
\rules except commentblock commentinline 

aa -->
<!--
```

**Comment by thisname12345** [comment]
wasn't able to find any trouble with

```
aa -->
<!--
```

unlike

```
aa -->
aa -->
<!--
```

**Comment by pmario** [comment]
the following works. So the  comment-inline cause the problem
```
\rules except commentinline 

aa -->
<!--
```

**Comment by thisname12345** [comment]
thats great
```
\rules except commentinline
```
fixes those two.

```
text

<!-- [[text|http://tiddlywiki.com/#DateFormat]] -->

<!-- $:/core/ui/ControlPanel/Info -->
```

needs deeper investigation... (i've not been able to get that to work with \rules except commentinline in many various ways)

**Comment by pmario** [comment]
Yea, it seems `commentblock` is involved too. They basically contain the same code. ...

**Comment by thisname12345** [comment]
ooh

```
<!-- keephidepreview for commentlinkmesswith -->
```

thisfor guidethrough takeaway
yes

byebye

**Comment by thisname12345** [comment]
ok i've no idea now and again

```
\rules except commentblock
```

does the trick
nice one

**Comment by thisname12345** [comment]
turns out i had preview off...

just put all your commented links in a multi-line one boys and girls

bye now

**Comment by tobibeer** [comment]
this is a nasty one, interestingly, no fix yet

**Comment by tobibeer** [comment]
Btw. preview or not doesn't matter.

If you enter this in the editor and either hit preview or save, it will bang, as well as if you open a tiddler with that content:

```
a

a-->

<!—
```

**Comment by tobibeer** [comment]
@Jermolene, could it be the problem lies in how the`parse` function in:

[$:/core/modules/parsers/wikiparser/rules/commentinline.js](https://github.com/Jermolene/TiddlyWiki5/blob/master/core/modules/parsers/wikiparser/rules/commentinline.js)

...does not implement any `eatTerminator` option as does **bold** for example.

[$:/core/modules/parsers/wikiparser/rules/emphasis/bold.js](https://github.com/Jermolene/TiddlyWiki5/blob/master/core/modules/parsers/wikiparser/rules/emphasis/bold.js)

?

**Comment by pmario** [comment]
@Jermolene ... I did stumble upon this issue. It seems there is **no issue anymore** ... I can non replicate it anymore.

**Comment by pmario** [comment]
@Jermolene -- IMO can be closed. The issue seems to be gone.

**Comment by Jermolene** [comment]
Thank you @pmario
