### ISSUE TITLE
BASE64 as a core filter

### ISSUE THREAD

**Issue by AndyDaum** [Jermolene/TiddlyWiki5#2878]
Hello,

Adding BASE64 encoding as a core filter would enable seamless generation of MS Word files from HTML (with the addition of MHT encoding to download binary file) using Tiddlywiki!

Approximated basic use case: http://resu-me.tiddlyspot.com/

Many, many thanks for considering this request.

Lots of love,

Andy.

**Comment by tobibeer** [comment]
Hi @AndyDaum, I quickly made a plugin for it, see [tobibeer/base64](https://tobibeer.github.io/tw5-base64).

You can also find [the sources vor v 0.5.0 here](https://github.com/tobibeer/tw5-base64/releases/tag/v0.5.0).

Should there be some more demand for it or a use case for the core itself, we can sure suggest a pull request for it as a core plugin.

**Comment by pmario** [comment]
@Jermolene -- Can be closed. We do have [base64 encoding and decoding](https://tiddlywiki.com/#encodebase64%20Operator:%5B%5Bencodebase64%20Operator%5D%5D%20%5B%5Bdecodebase64%20Operator%5D%5D%20%5B%5BFilter%20Operators%5D%5D) now

**Comment by Jermolene** [comment]
Thank you @pmario
