### ISSUE TITLE
Supporting macros in Markdown

### ISSUE THREAD

**Issue by dainkaplan** [Jermolene/TiddlyWiki5#2887]
I don't believe you can call out to macros in the markdown document; it just renders the macro call as plain text, e.g. <<mymacro "foo" "bar">> just appears as is, without calling out to "mymacro". (Maybe this is do to text escaping rather than not calling macros, I don't know.) Can running the content through all the macros processing be added?

**Comment by pmario** [comment]
markdown isn't tw-wikitext. ... And so far as I can see, there is no macro spec in the markdown spec. see: http://commonmark.org/ ..

**Comment by dainkaplan** [comment]
@pmario Yeah, I don't think there is... but the spec does allow embedding raw HTML (e.g. `<foo/>`), and considering that this markdown plugin exists within tiddlywiki it would make sense (at least to me) for it to support macro expansion (an important feature of TW)? 

Is there perhaps an easy workaround where the output of the markdown plugin is just piped through the macro processor before displaying?

**Comment by tobibeer** [comment]
TFM ;-)

**Comment by saqimtiaz** [comment]
As discussed in #4610 the new markdown plugin can be [configured](https://github.com/Jermolene/TiddlyWiki5/issues/4610#issuecomment-621709996) to allow syntax such as macros to work in Markdown tiddlers.

@Jermolene I suggest that we can close this issue.

**Comment by Jermolene** [comment]
Thanks @saqimtiaz
