### ISSUE TITLE
LinkWidget->handleClickEvent should send original event keypress data

### ISSUE THREAD

**Issue by saqimtiaz** [Jermolene/TiddlyWiki5#2889]
[LinkWidget.prototype.handleClickEvent](https://github.com/Jermolene/TiddlyWiki5/blob/8f1114960a20ba3d84dd1633ad1976db9461a41c/core/modules/widgets/link.js#L128) is currently implemented such that it does not pass along any of the original event keypress data (ctrlKey, metaKey, shiftKey, altKey) in the tm-navigate event that is dispatched.  

 ```
this.dispatchEvent({
		type: "tm-navigate",
		navigateTo: this.to,
		navigateFromTitle: this.getVariable("storyTiddler"),
		navigateFromNode: this,
		navigateFromClientRect: { top: bounds.top, left: bounds.left, width: bounds.width, right: bounds.right, bottom: bounds.bottom, height: bounds.height
		},
		navigateSuppressNavigation: event.metaKey || event.ctrlKey || (event.button === 1)
	});
```

For a plugin writer seeking to add on functionality or modify the existing behavior based on modifier keys used when clicking a tiddler link, including this keypress data is essential. 

The handler for this event ([Navigator.prototype.handleNavigationEvent](https://github.com/Jermolene/TiddlyWiki5/blob/eba1c3c160c63ac3dfc15f55df086971a832d657/core/modules/widgets/navigator.js#L174)) provides a hook 'th-navigating' that can be used to modify navigation behavior on clicking a link. However without the event keypress data, adding extra functionality based on say pressing Shift or Alt when clicking a link is not possible.

It should also be considered to provide the ctrlKey and metaKey data, in addition to Shift and Alt - in the tm-navigate event dispatched - in case it is desirable to override core suppressNavigation behavior and use those keys for a different purpose. Example:
 ```
this.dispatchEvent({
		type: "tm-navigate",
		navigateTo: this.to,
		navigateFromTitle: this.getVariable("storyTiddler"),
		navigateFromNode: this,
		navigateFromClientRect: { top: bounds.top, left: bounds.left, width: bounds.width, right: bounds.right, bottom: bounds.bottom, height: bounds.height
		},
		navigateSuppressNavigation: event.metaKey || event.ctrlKey || (event.button === 1),
		metaKey: event.metaKey,
		ctrlKey: event.ctrlKey,
		altKey: event.altKey,
		shiftKey: event.shiftKey
	});
```

**Comment by danielo515** [comment]
This is definetively a good idea, which opens interesting plugin options

**Comment by saqimtiaz** [comment]
If it helps to have a concrete example of a use case, I'm currently monkeypatching the core handleClickEvent in order to be able to open tiddlers in an alternative story by shift + clicking tiddler links.

Actually, the entire two story implementation requires no JavaScript at all, apart from this.

**Comment by Jermolene** [comment]
Hi @saqimtiaz yes that makes sense. I'd welcome a PR.

**Comment by saqimtiaz** [comment]
@Jermolene  here you go: https://github.com/Jermolene/TiddlyWiki5/pull/2900
and here is the CLA https://github.com/Jermolene/TiddlyWiki5/pull/2899

**Comment by saqimtiaz** [comment]
@Jermolene I think we have the retract this fix and tweak it. While I agree that the way we have passed on the original event data here is the better way to do so and what is pretty much standard for events, it is inconsistent with current core behaviour. The same kind of message "tm-navigate" when dispatched by the button widget simply attaches the original event:

```
ButtonWidget.prototype.navigateTo = function(event) {
	var bounds = this.getBoundingClientRect();
	this.dispatchEvent({
		type: "tm-navigate",
		navigateTo: this.to,
		navigateFromTitle: this.getVariable("storyTiddler"),
		navigateFromNode: this,
		navigateFromClientRect: { top: bounds.top, left: bounds.left, width: bounds.width, right: bounds.right, bottom: bounds.bottom, height: bounds.height
		},
		navigateSuppressNavigation: event.metaKey || event.ctrlKey || (event.button === 1),
		event: event
	});
};
```
The advantage here is that any other event properties from the original event will be available in the message. Shall I revise and make a new pull request following this pattern?

**Comment by tobibeer** [comment]
> The advantage here is that any other event properties from the original event will be available in the message. Shall I revise and make a new pull request following this pattern?

@Jermolene: I would also be in favor of that. What do you think?
