### ISSUE TITLE
Wording issues ...

### ISSUE THREAD

**Issue by TiddlyTweeter** [Jermolene/TiddlyWiki5#2891]
![capture](https://user-images.githubusercontent.com/28830541/27004762-7fc92b7c-4e0f-11e7-9ff7-34aad3caf124.PNG)

I suggest you change that wording to this:

This TiddlyWiki creates Google Analytics cookies to enable us to track usage. It does not track you individually. More ...

**Comment by TiddlyTweeter** [comment]
Sorry, wrong place :-(

**Comment by pmario** [comment]
>This TiddlyWiki creates Google Analytics cookies ...

Thats actually the wrong wording. ... The wiki uses a plugin from google, that creates the cookie. So imo the initial text is ok.
