### ISSUE TITLE
NavigatorWidget->handleEditTiddlerEvent should provide a hook

### ISSUE THREAD

**Issue by saqimtiaz** [Jermolene/TiddlyWiki5#2892]
[NavigatorWidget.prototype.handleEditTiddlerEvent](https://github.com/Jermolene/TiddlyWiki5/blob/master/core/modules/widgets/navigator.js#L211) should add a hook that allows for modifying the editing workflow. I would recommend a similar approach to the hook invoked in handleNavigateEvent

Example: warning a user when opening a tiddler for editing, that is already open for editing in another editing interface such as a second story.

**Comment by Jermolene** [comment]
Hi @saqimtiaz yes, that makes sense. Perhaps also in handleNavigateEvent?

**Comment by saqimtiaz** [comment]
@Jermolene I believe you mean [handleNewTiddlerEvent](https://github.com/Jermolene/TiddlyWiki5/blob/master/core/modules/widgets/navigator.js#L434) and I agree that we need a hook there too.

handleNavigateEvent already has [one.](https://github.com/Jermolene/TiddlyWiki5/blob/master/core/modules/widgets/navigator.js#L176)

**Comment by saqimtiaz** [comment]
@Jermolene Here is a pull that adds the hook to handleEditTiddlerEvent: https://github.com/Jermolene/TiddlyWiki5/pull/2901

For handleNewTiddlerEvent, I'd like for us to think a bit more carefully about what the use case might be and where in the flow the hook would be most useful. I will open a separate ticket for that and once we have a concensus, do a separate pull request for it.
