### ISSUE TITLE
Should Navigator->handleNewTiddlerEvent provide a hook?

### ISSUE THREAD

**Issue by saqimtiaz** [Jermolene/TiddlyWiki5#2902]
In discussion with @Jermolene , it has been suggested that handleNewTiddlerEvent should provide a hook (th-new-tiddler) similar to what we have in handleNavigateEvent and handleDeleteTiddlerEvent.

Where in the flow would this be most useful? What would be potential use case be for hooking into the creation of a new tiddler? To clarify, this handler creates a draft of a new tiddler. If we are not clear on potential use cases, it might be better to defer adding this hook until there is a need for it.

**Comment by tobibeer** [comment]
I imagine one usecase might be for a plugin to ensure that required fields are added?

**Comment by saqimtiaz** [comment]
This was implemented in #3206
