### ISSUE TITLE
Files loaded via tiddlywiki.files save to incorrect filename

### ISSUE THREAD

**Issue by saqimtiaz** [Jermolene/TiddlyWiki5#2906]
Plain text .txt files or .md files, loaded via a tiddlywiki.files declaration load in the TiddlyWiki just fine. However, editing them is problematic. They are saved to the wrong file name.

With a subdir in my tiddlers directory called "notes", containing a file "mynote.txt", editing results in a file "mynote 1.txt" and "mynote 1txt.meta" whereas I would expect the original "mynote.txt" to be updated and a .meta file created. This behavior leads to duplication of tiddler files and is rather confusing. If the intent was that files loaded in this manner should not be editable, then we should find a way to set them as read only.

Digging into the code in boot.js reveals that .txt or .md files that do not have .meta files and are loaded via a tiddlywiki.files declaration, are never added to $tw.boot.files [(as they don't have their filepath set).](https://github.com/Jermolene/TiddlyWiki5/blob/a4035d34247e2f27efc9cb6228432deea21d73a3/boot/boot.js#L1786)

If we modify line line [1594](https://github.com/Jermolene/TiddlyWiki5/blob/master/boot/boot.js#L1594) in boot.js from 

`tiddlers.push({tiddlers: fileTiddlers});`

to

`tiddlers.push({filepath: pathname, hasMetaFile: !!metadata && !isTiddlerFile, tiddlers: fileTiddlers});`

the files are added to $tw.boot.files and on editing are saved to the accurate and original filename, along with a .meta file for non .tid files.

I propose that this should be the default way of handling .txt and .md files that are loaded via tiddlywiki.files

**Comment by rubaboo** [comment]
@saqimtiaz Will this aply to other file types? I'm thinking various script file extensions, like .sh etc.
Can you submit a pull request for this?

**Comment by saqimtiaz** [comment]
The suggested change I've mentioned above would indeed make this behaviour apply to all file types. I haven't made a pull request as I feel some conversation is warranted here. I'm unsure as to whether this was an intentional behaviour designed to avoid some issues that I am not thinking of, or just an oversight.
 Any thoughts @Jermolene ?

**Comment by sukima** [comment]
@saqimtiaz But a **Pull Request** has *already* been created: #2996 ❗️

**Comment by sukima** [comment]
I think the conversation should move to #2996 so we can have code to refer to while discussing.

**Comment by kookma** [comment]
@saqimtiaz please update this issue with TW 5.1.23! I hope @Jermolene apply the patch.

**Comment by saqimtiaz** [comment]
@kookma attached is a patch for 5.1.22/23

Note that the directory listing in tiddlywiki.files needs a property `isEditableFile` to be set to enable this behaviour. 

This should address some of the concerns raised by Jeremy in #2996

Example:

```
{
  "directories": [
    {
      "path": ".",
      "filesRegExp": ".+\\.txt",
      "isTiddlerFile": false,
      "isEditableFile": true,
      "fields": {
        "title": {
          "source": "basename-uri-decoded"
        },
        "created": {
          "source": "created"
        },
        "modified": {
          "source": "modified"
        },
        "type": "text/plain",
        "tags": [
          "note",
          "externalnote"
        ]
      }
    }
  ]
}
```

[Patch](https://github.com/Jermolene/TiddlyWiki5/files/5339756/sq-boot-new.txt)
