### ISSUE TITLE
Proposal to make the "tree" macro (Explorer tab) global so anyone can use it

### ISSUE THREAD

**Issue by morosanuae** [Jermolene/TiddlyWiki5#2907]
Hello again,

I want to make a new proposal (request) relating my current work. I believe that we should make the "**tree**" macro from the new Explore tab a global macro that anyone can use. A user can add a custom panel with just a subset of the entire tree (e.g. $:/core/) or from his personal structure (e.g. $:/_morosanuae/).

**Modifications:**

- Put the internal macros (e.g. leaf-node, branch-node etc.) in a separate file to avoid making them global and referencing them with <$importvariables> widget in the main (global) macro tiddler. Now only the "tree" macro is global.
- The root element is now dynamic showing the current (user selected) prefix (tree root) for easier visual recomposing the original tiddler name. 

So @Jermolene what do you think about this? 

You can test it [here](http://morosanuae.tiddlyspot.com/#The%20new%20%22tree%22%20global%20macro)

Thanks!

**Comment by Jermolene** [comment]
Hi @morosanuae great idea, I'm in favour of making things as reusable as possible.

**Comment by tobibeer** [comment]
Very much in favor. However, I think the Explorer — owed to the naming conventions to make it work — should be a plugin, and not part of the empty edition. So, people who want to use such titles can enjoy working with the explorer ...but most probably don't want to use titles like `foo/bar/baz`.

**Comment by morosanuae** [comment]
@tobibeer This is practically a closed issue. The "tree" macro is now already a part of the core (empty edition). 
We don't really know how many users are in favor for the new Explorer and how many are against, that is just a guess. We don't have a voting platform (site). I posted this proposal and the one with the "Explorer" tab also on TiddlyWiki groups back then and very few responded, so... Anyway it's **impossible** to make everyone happy. For me, the only solution to this problem is to make TiddlyWiki entirely modular. To break things down even in the core, and to let the user the freedom to make his personal custom application. I saw this idea somewhere around here.

**Comment by Jermolene** [comment]
Hi @morosanuae please don't be discouraged! Your contributions have been of a consistently high standard and I'd hate to lose your skills!

The question of what should go into the core is always highly contentious. There's good reason for this: putting something into the core represents a long term commitment to supporting that feature, which can have a significant impact. The best approach to keep things moving is to develop radical new features as plugins, which allows some feedback from users before taking a definite decision.

**Comment by tobibeer** [comment]
@morosanuae: / @Jermolene: I hope my comment didn't come accross as criticism. I think the explorer is very useful for pro-users and your contributions were spot-on. So, that's that.

I didn't check that it was already in empty.html. But I don't think that installing a plugin is too great a barrier, for pro-users who use titles like "foo/bar". At least, I'd be happy to just click "install" w/o needing everything out of the box.

On the other hand, the sidebar is growing ever more crowded and we introduce more complex implementations directly to the core, as @Jermolene said. So, it's just something to consider.

I would definitely favor an architecture, where I can go into the ControlPanel and simply remove a bunch of now core features that I don't need or want for wiki xyz. And I think that investing some thought in a more modular core in terms of "removable" and "addable" modules / components is a worthwhile endeavour.

**Comment by tobibeer** [comment]
It's a bit like "unlearning". We always put so much emphasize on "learning new stuff" and "keeping up to date" w/o realizing how poor we have become in unlearning things that are of little to no use (for us) in this moment.

And I think TiddlyWiki should encourage and promote the capability to "unlearn" the things that are no longer relevant, both in terms of content as well as in terms of core modules.
