### ISSUE TITLE
Unticking 'Enable links to missing tiddlers' distorts dropdown links of filter search

### ISSUE THREAD

**Issue by gernert** [Jermolene/TiddlyWiki5#2915]
![enable_links_to_missing_tiddlers_unticked](https://user-images.githubusercontent.com/5826020/27326021-8b42026a-55aa-11e7-8aa5-784451d243cf.png)
![advanced_search_filters](https://user-images.githubusercontent.com/5826020/27326022-8b477b8c-55aa-11e7-9baf-3183dbc4c3a8.png)

To reproduce:

1. Open http://tiddlywiki.com/
2. Untick 'Enable links to missing tiddlers'
3. Go to Advanced Search, tab Filter
4. Click the dropdown icon: you get a list of filters, without newlines, but worse: the entries are no links anymore!

**Comment by pmario** [comment]
I think there is a similar issue somewhere here.

**Comment by gernert** [comment]
@pmario You are right: Disabling "Wiki Links > Enable links to missing tiddlers" Breaks Tags and Type: #2839. Can these be combined?

**Comment by pmario** [comment]
Now they are linked. So it should be OK. don't close it, since its the second problem we found so far.

**Comment by tobibeer** [comment]
Commented at #2839 regarding the cause. Most efficient fix still needs  evaluating.

**Comment by tobibeer** [comment]
Commented at #2839 regarding the cause. Most efficient fix still needs  evaluating.

**Comment by pmario** [comment]
@Jermolene -- Can be closed. There are no problems anymore. 

Same is true for **Disabling "Wiki Links > Enable links to missing tiddlers" Breaks Tags and Type: #2839**

**Comment by Jermolene** [comment]
Thank you @pmario
