### ISSUE TITLE
Error: Permission denied to access property "target"

### ISSUE THREAD

**Issue by CodaCodr** [Jermolene/TiddlyWiki5#2916]
STR...

1 http://tiddlywiki.com/
   HelloThere appears

2 Select the text `Have you ever had the feeling`

3 Drag the selected text
   The "Drop here" green target zone appears

4 Press `Esc` to cancel the drag-drop operation
  JS Error report appears

**Comment by Jermolene** [comment]
Hi @CodaCodr what browser and OS versions are you using?

**Comment by sukima** [comment]
I'm guessing this could be a browser addon issue. I just tried in FF (Mac OS) latest and could not reproduce.

**Comment by pmario** [comment]
no problem with ubuntu 17.04 and FF 54.0 on my system

**Comment by morosanuae** [comment]
It happened to me also several times. The error appears with every drag (text, links etc.) not just in the context mentioned by @CodaCodr. My combination is Windows 7 Pro x64 + Firefox 54.0 (x64).

**Comment by CodaCodr** [comment]
Firefox 54.0
Win 7

**Comment by CodaCodr** [comment]
Oh... and it's TiddlyWiki version: 5.1.14

Happens locally "all the time" - thought it was my overly large wiki but testing on tw.com proves not.

I have no addons - only TiddlyFox (TiddlyWiki for Firefox)

**Comment by CodaCodr** [comment]
![perm-denied](https://user-images.githubusercontent.com/436812/27436729-c609ae3a-5725-11e7-8957-43a23b3c4446.gif)

**Comment by CodaCodr** [comment]
Does NOT occur in Firefox Nightly (but the green drop zone does not clear).

Here's where the debugger stops with the error: 

```
DropZoneWidget.prototype.leaveDrag = function(event) {
	var pos = this.currentlyEntered.indexOf(event.target);  // <==  dbgr breaks here
	if(pos !== -1) {
		this.currentlyEntered.splice(pos,1);
	}
	// Remove highlighting if we're leaving externally
	if(this.currentlyEntered.length === 0) {
		$tw.utils.removeClass(this.domNodes[0],"tc-dragover");
	}
};

```

**Comment by CodaCodr** [comment]
Stacks from the console

```
Error: Permission denied to access property "target"  tiddlywiki.com:25727:2
	_boot/$tw.utils.error http://tiddlywiki.com/#:25727:2
	_boot/window.onerror http://tiddlywiki.com/#:25754:3
Error: Permission denied to access property "target"[Learn More]  tiddlywiki.com:67:6
	DropZoneWidget.prototype.leaveDrag $:/core/modules/widgets/dropzone.js:67:6
	DropZoneWidget.prototype.handleDragLeaveEvent $:/core/modules/widgets/dropzone.js:104:2
	handler $:/core/modules/utils/dom.js:197:6
```

**Comment by sukima** [comment]
Is this loaded into an iframe? A google search finds https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Property_access_denied as a likely culprit. Could there be an addon / extension mucking with the DOM? Ad blocker?

**Comment by CodaCodr** [comment]
No iframe. I have no addons (except Tiddlyfox)

**Comment by pmario** [comment]
I can not replicate the issue, if I do it like the animated gif. ... .but ... If I take a link from the right sidebar and d&d it, I do get the same issue.

**Comment by pmario** [comment]
@CodaCodr -- I think this one can be closed. It does not happen anymore. I used FF and Windows 11 -- No problem.
