### ISSUE TITLE
Error loading plugin library

### ISSUE THREAD

**Issue by sprnza** [Jermolene/TiddlyWiki5#2926]
Hi there!
I use TW5 behind apache proxy.
Here is an apache config
```
<VirtualHost *:80>
    ServerAdmin *****
    ServerName *****
    ServerAlias *****
    Redirect permanent / https://*****
</VirtualHost>

<VirtualHost *:443>
    ServerAdmin *****
    ServerName *****:443
    ServerAlias *****:443
    AllowEncodedSlashes On
    <Proxy *>
	Order Deny,Allow
	Allow from all
    </Proxy>
    ProxyRequests Off
    ProxyPreserveHost Off
    ProxyPass / http://127.0.0.1:7000/
    ProxyPassReverse / http://127.0.0.1:7000/
    ErrorLog /var/log/httpd/tid.info-error_log
    CustomLog /var/log/httpd/tid.info-access_log common
    SSLEngine on
    SSLCertificateFile    /etc/letsencrypt/live/******/cert.pem
    SSLCertificateKeyFile /etc/letsencrypt/live/******/privkey.pem
    SSLCACertificateFile /etc/letsencrypt/live/******/fullchain.pem
</VirtualHost>
```

When I try to open Plugin Library I get an error:
`Error loading plugin library: http://tiddlywiki.com/library/v5.1.14/index.html`
I've found somethere that it's necessary to delete $:/temp/ServerConnection/http:tiddlywiki.com/library/v5.1.14/index.html tiddler to have this issue fixed but it doesn't help.
I'm not very good at node.js thing so I even don't know where to look for the logs.
Please help.

**Comment by danielo515** [comment]
You can't mix origins with different levels of security. You are serving your wiki through https,while the plugin library is serverd over http

**Comment by sprnza** [comment]
Yep, thanks!
