### ISSUE TITLE
Tiddler titles or tags containing `$(x)$` do not work

### ISSUE THREAD

**Issue by Jermolene** [Jermolene/TiddlyWiki5#293]
Any string wrapped in `$(` and `)$` will be processed as a variable substitution, thoroughly confusing the UI.

**Comment by pmario** [comment]
we have a warning in place now. so may be closed.

**Comment by pmario** [comment]
>we have a warning in place now. so may be closed.

@Jermolene

**Comment by pmario** [comment]
@Jermolene ... bump :)
