### ISSUE TITLE
Subfilter option missing from image-picker

### ISSUE THREAD

**Issue by Marxsal** [Jermolene/TiddlyWiki5#2939]
The documentation for the image-picker says that it has a sub-filter option. The sub-filter option is missing, and instead there is only a filter option. Either the documentation or the code needs to be tweaked accordingly.

Thank you,
Mark

**Comment by Marxsal** [comment]
I've made a proposed fix #2940

**Comment by tobibeer** [comment]
@Marxsal, thanks and please close.
