### ISSUE TITLE
PR: Typo in doc on Tabs macro blocks example link

### ISSUE THREAD

**Issue by twMat** [Jermolene/TiddlyWiki5#2943]
Github will not accept this PR - I'm guessing it parses out the very error I attempt to PR on. Ironically it is even tricky to copy the matter here because it contains triple-single-quotes, so I'll have to just describe it:

At the very end of the [tabs Macro doc](http://tiddlywiki.com/#tabs%20Macro) the link to the examples are mistakenly "baked into" the preceding code block. It seems to be caused by an extra space character at the end of the code block triple quotes.

Just remove the space character and it works fine.

**Comment by tobibeer** [comment]
@twMat: Is this still an issue? At least, I can't see it.
