### ISSUE TITLE
Custom fields, when created, evaluate - causing loss of info

### ISSUE THREAD

**Issue by twMat** [Jermolene/TiddlyWiki5#2951]
Attempting to create a field with value like so:

`foo: hey $(bar)$ ` ...but clicking the field `add` button only results in.... `foo: hey`

(All while staying in edit mode.)

I was expecting the full string to remain. And I cannot find any mention of such limitations in the docs.

(It is possible to *modify* the value after it was created, to make it read `foo $(bar)$`, but this makes me uncertain if it is not really allowed or something.)

---

My use case is for the graphs "plugin framework" where graph templates fetch values from the graph instance tiddler. For example, I want to do this:

In a style block in the tiddler text:
`margin-left: {{x-axis!!margin-left-per-index}};` (i.e the `:` here is the css attribute:value separator)

...and in custom fields:
`margin-left-per-index: calc($(index)$ * 10px)`
`margin-left-per-share: calc($(share)$ * 100%)`

**Comment by pmario** [comment]
The tiddler text area technically is a field too. So what happens if you write: `foo: hey $(bar)$` ??

Variables have a context that is defined by the `<$set>, <$vars>` widgets or by imported into a tiddler with the http://tiddlywiki.com/#ImportVariablesWidget ... variables are only visible **inside** their context.

**Comment by twMat** [comment]
>what happens if you write: foo: hey $(bar)$ into the tiddler text area??

...in edit-mode it, of course, appears exactly as the string of characters that it is. 

I'm talking about never leaving edit mode. I fill in the two fields for field-name and field-value then click "add"; The field is created with the correct field-name but the field-value gets "contorted" so any `$(bar)$` simply becomes no characters. I.e that as-always-still-editable-value-field in tiddler edit mode.

I do *not* want, nor expect, the variable to be evaluated. I expect the literal string of characters to remain.

Or do I misunderstand your reply?

**Comment by twMat** [comment]
Also, creating the field  `foo: hey <<bar>>` does work as expected, even with no existing bar macro.

**Comment by pmario** [comment]
.. I did misunderstand your issue. ... Did run a test now... 
The variable actually is evaluated and then assigned to the tiddler field value. So it's lost. 

IMO that is a bug.

**Comment by twMat** [comment]
Thanks.

**Comment by twMat** [comment]
Could you or someone please tag it as a bug?
Appreciated.

**Comment by pmario** [comment]
As a workaround, you can crate a field name with empty value. 
add it
edit the value. ... It keeps the value

**Comment by twMat** [comment]
Thanks, yes I discovered this too. Just hope it is reliable to do.

**Comment by tobibeer** [comment]
@twMat: added the above PR to fix the behavior.

**Comment by twMat** [comment]
@tobibeer - excellent!!!
Closing.
