### ISSUE TITLE
Handlinig of environment variables is incorrect (according to documentation)

### ISSUE THREAD

**Issue by danielo515** [Jermolene/TiddlyWiki5#2954]
Good morning @Jermolene 
Documentation about environment variables says that tiddlywiki accepts a colon delimitid list of paths, you can see it here:

https://github.com/Jermolene/TiddlyWiki5/blob/master/editions/tw5.com/tiddlers/nodejs%2FEnvironment%20Variables%20on%20Node.js.tid#L7

However, the code that handles this uses `path.delimiter`, which is not consistent across OS. Here is the piece of code I am mentioning:

https://github.com/Jermolene/TiddlyWiki5/blob/f59809e9a4bbb8d29aa5fc3b8a3850cd7bfd08c3/boot/boot.js#L1721

And this is the value on different OS:

```sh
# Ubuntu
> p = require('path')
> p.delimiter
':'
```

```sh
# windows
> p = require('path')
> p.delimiter
';'
>
```

This is specially annoying because I was following the documentation and nothing was working as expected. The I had to navigate through the code to understand how paths are managed, and then check on my OS which was the correct delimiter.

I think it will be just easier to use `:` on the split, which will be 100% compliant with the documentation.

Regards

**Comment by Jermolene** [comment]
Hi @danielo515 

It's the documentation that is wrong here. We switched from splitting the environment variables with `":"` to `path.delimiter` in the fix for #1187 by @pmario.

In cases like this it's better to fix the documentation than to change the behaviour to match the documentation. It would be a breaking change for anyone who is relying on the current behaviour. Pull requests welcome.

**Comment by pmario** [comment]
yea. The docs need to be fixed. The delimiter depends on the OS and has to be in a way, that the OS understands.

**Comment by danielo515** [comment]
I don't see this as a feature but as a headache for all the cross-env developers. So I have to build different build files for windows and unix just because this. I don't see the advantages while we only need to split the path in different chunks as you do in the piece of code that I linked.

**Comment by Jermolene** [comment]
Hi @danielo515 discovering and catering for differences between *nix and Windows has been a frustrating experience, so I understand where you are coming from.

However, there's not a lot we can do; each platform has its own standards and we have little choice but to observe them. Surely we would be adding to user confusion if TW5 used a different format for path variables than everything else on Windows.

see: https://en.wikipedia.org/wiki/PATH_(variable)

**Comment by danielo515** [comment]
Hello again ,

Are we using that environment variable in any other place different from the linked chunk of code ? If we pass the variable directly to any system specific method, then it will make sense . However, if the only operation/usage is to split the string I don't see anything bad about using a consistent separator.
Regards

**Comment by Jermolene** [comment]
Hi @danielo515 the logic for the situation goes like this:

* Windows and *nix both have clear platform standards for how the PATH variable is delimited
* TiddlyWiki 5 is using a number of environment variables that are analogous to the PATH variable
* Therefore TiddlyWiki 5 adopts the same delimiter standard as the host platform

If TiddlyWiki 5 didn't observe the platform standards then somebody using Windows would be confused that the PATH variable works normally, but that TiddlyWiki 5 is inconsistent.

**Comment by pmario** [comment]
@danielo515 ... It's simply not possible to use the colon as a path separator in windows. eg: `c:\thispath:d:\thatpath` won't work .. There is a reason, why they use the semicolon.

**Comment by danielo515** [comment]
Hello @jermolene and @pmario,

I do understand your points, and they make sense and I can understand your position. However, I feel that you are missing my point: We have several environment variables that **looks like** PATH variables, so is your desire to mimic the behavior uf such variables as close as possible to the host OS. My point is that those env variables JUST look like PATH variables, but they are not because we are not allowing the SO to handle the path, we are splitting them and reading each path individually. Because this reason, I don't see the point about making them look like actual PATH variables, because they are not, they are just a list of values for tw.  Sure it is better to follow the standards as close as possible, but here the problems (incompatibility between OSs) are bigger than the benefits (just look familiar and standard).

Hope now my position is more clear. I have a windows laptop on my home, I work on a MAC OSx and all the build services uses linux.

Regards

**Comment by Jermolene** [comment]
Hi @danielo515 I think your argument is that these environment variables are unique to TiddlyWiki, and have no interdependency with the host platform, and so therefore we can choose whatever delimiter we want, and don't need to worry about compatibility with the platform.

The counter arguments are (a) that consistency makes life simpler for users, who would otherwise need to remember an exception to a general rule, and (b) that consistency permits interoperability with other features/tools of the platform (for example, any utility written to manipulate the PATH variable can be reused to manipulate one of TiddlyWiki's environment variables).

**Comment by danielo515** [comment]
Hello @jermolene,

Now that I see my point is clear and you don't agree with me I think is time to label this conversation as documentation and fix the documentation.

On a side note, I think that environment variables are a very obscure way of configuring the behavior of a program, specially with this kind of configurations that you will probably want to persist in some way. I think they will be better placed on a config file, being tiddlywiki.info the best place for it. I'll be hapi to give it a try if you agree with it 

Regards

**Comment by tobibeer** [comment]
@danielo515: it's not just how the variable is stored, it's also how it is represented and editable as a list... at east in windows.

While having long term implications, I think we should be more practical about these things in the short term, hence the PR above.
