### ISSUE TITLE
Folded tiddler indicator

### ISSUE THREAD

**Issue by steronydh** [Jermolene/TiddlyWiki5#2957]
Would it be possible to add a clear indicator showing that a tiddler has been folded? At present the only difference between a blank tiddler and a folded tiddler is the small grey date under the title. 

I just wasted a while trying to work out why a tiddler's text wasn't appearing no matter what text I put in it before I worked out that it was folded.

**Comment by pmario** [comment]
Go to: ControlPanel: Appearence: Toolbars: ViewToolbar:   ... and activate the "FoldBar" indicator. 

You'll get 2 buttons:

 - 1 at the left border of the tiddler to fold a tiddler
 - 2 if the tiddler is foleded, you'll get a big button at the bottom of the empty content. 

... If you want to have it more visible, you can play with the CSS settings. `tc-unfold-banner`

**Comment by steronydh** [comment]
Perfect, thanks for the info.
