### ISSUE TITLE
Proposal: Make the `enlist` operator more powerful

### ISSUE THREAD

**Issue by pmario** [Jermolene/TiddlyWiki5#2958]
Proposal: 
 - Make the `enlist` operator more powerful.

@Jermolene 
The `enlist` operator implementation is relatively simple at the moment. It understands

 - the tiddler `list` field
 - tiddler text containing `lists` 
   - space separated
   - newLine separated
 - lists in variables. 

But TW has more lists already built in: 

 - application/x-tiddler-dictionary
 - application/json   ... aka palette parameters 
 - application/x-tiddlers .... aka `.multids`-tiddlers

I'm especially interested in the the `.multids` setting, since it knows about **comments**. 

```
title: 

aa: text for aa
# some comment, that is ignored
bb: text for bb
```

**Comment by tobibeer** [comment]
Do you have any usecases in mind that this would help solve (that cannot be solved differently)?

Syntax suggestions and expected output examples would also be helpful.

**Comment by pmario** [comment]
Close this one. Forgot about the usecase :)
