### ISSUE TITLE
Multiple button popups - or autoclose previous when new opens 

### ISSUE THREAD

**Issue by twMat** [Jermolene/TiddlyWiki5#2959]
Ideally multiple popups should be allowed to be open simultaneously.
If this is not possible, then the current popup should take precedence over the previous popup, i.e the new should close the previous one.

It is particularly annoying that **search** does not work if e.g a tag dropdown is open.

**Comment by Jermolene** [comment]
> Ideally multiple popups should be allowed to be open simultaneously

There's a bunch of logic that is intended to specifically prevent multiple independent popups being open simultaneously (you can of course nest popups eg more -> export tiddler). The reasoning is to mirror the behaviour of the underlying native GUI; in all such interfaces since the original Mac it is only possible to have a single popup/dropdown open. Dropdowns are modal.

(Of course, it is possible to use the TW5 dropdown styles without the popup logic in order to create dropdowns that are not modal).

Perhaps the best solution for you would be a search gizmo that didn't use a popup?

**Comment by twMat** [comment]
Thanks @Jermolene but I probably expressed myself poorly (sorry!):
I'm only talking about popups that a open when a user explicitly clicks a button, i.e when it is clear that he *wants* to access the popup. Is your reply still relevant in this regard?

**Comment by Jermolene** [comment]
I'm not sure that there is much of a distinction. Displaying a popup cancels any previous popup, regardless of how it was triggered.

**Comment by twMat** [comment]
>Displaying a popup cancels any previous popup, regardless of how it was triggered.

Hm, *no* this does not seem to be the case. For me (Chrome/Win10) the search field (which triggers a popup, right?) does *not* cancel e.g an open tag dropdown. I would prefer it that it does.

Further, I just noted that multiple popups *can* be simultaneously open under some circumstances: 

First, if I have a tag dropdown open and enter and *leave* a string in the search field... and click outside of it.. this closes all popups. But if I now again click the tagpill to get that dropdown and now click on the already existing string in the search field, there is a *flash* of a popup!

...and if I switch browser tab, and then back again, then *both* popups do persistently show!

This can be repeated with other dropdown fields also, e.g in tiddler edit mode with tag + type dropdowns.

**Comment by diego898** [comment]
@twMat I just discovered this myself and agree with you - even if my tag dropdown is being displayed, when I search for something I'd like for the tag dropdown to close and see the results. 

I posted a semi-related (possible bug?) [on the group](https://groups.google.com/d/msg/TiddlyWiki/hGTCwhGbayo/OcX-ODF4AgAJ) about the tag dropdown persisting even if you're not interacting with it - you could even be typing in the body of the tiddler and the tag drop-down still shows up blocking it. 

Should I make a separate issue for that bug, if indeed it is one?

**Comment by tobibeer** [comment]
Why are drop downs modal? (Why) Do they need to be?

**Comment by twMat** [comment]
Just discovered that this can cause even more confusion, even if this case is rarer:

If you're in edit mode and click the "image" editor tool, you get the popup listing the images. Click directly on an image to add it. Now type something into the searchbox. - No search results show! I suspect that the image list popup is still active, even if it is not seen, which blocks the search popup.

**Comment by twMat** [comment]
Closing thanks to @BurningTreeC pull 4089
