### ISSUE TITLE
[Request] Extend enlist filter op to allow +enlist[]

### ISSUE THREAD

**Issue by twMat** [Jermolene/TiddlyWiki5#2962]
Example of what I wish for

`[[tid]get[tags]enlist[]]` ---> individually listed tags

The `enlist` filter op currently demands some argument and is a "pre" operator, whereas my suggestion is to allow it as a "post" operator. (I made up those terms. What is the correct lingo?)

Either that, or some other operator that "splits up" complex output as per the example.

**Comment by Jermolene** [comment]
Hi @twMat you probably realise this but you can already do what you want if you use an intermediate variable. For example:

```
<$vars mytagsfield={{{ [[tid]get[tags]] }}}>
<$vars mytagslist={{{ [enlist<mytagsfield>]] }}}>
...
</$vars>
</$vars>
```

To do it in a single operation we'd need a new filter operator that, as you suggest, would behave like 'enlist' except that it would operate on the current list, rather than on the operand.

**Comment by twMat** [comment]
@Jermolene , yes, in deed, to what you're saying. I just feel it would be a useful and intuitive enhancement. Actually, I've attempted to use enlist[] quite a few times only to time and again conclude "ah! nope". Point being: I think users expect this.

BTW since you presented that example: It seems one must enclose the inner filtered trancslusion with quotes, i.e `"{{{ ... }}}"` or only the first argument gets assigned. Should I start a separate issue for this or do I misunderstand sth?

Thank you.

**Comment by Jermolene** [comment]
>  Point being: I think users expect this.

Do you mean that users expect the enlist operator to work differently than it does, or that users would expect their to be an alternative operator that works on the list instead of the operand?

> BTW since you presented that example: It seems one must enclose the inner filtered trancslusion with quotes, i.e "{{{ ... }}}" or only the first argument gets assigned. Should I start a separate issue for this or do I misunderstand sth?

Indeed, my example was misleading; this is better:

```
<$vars mytagsvalue={{{ [[tid]get[tags]] }}}>
<$set name="mytagslist" filter="[enlist<mytagsvalue>]">
...
</$set >
</$vars>
```

**Comment by twMat** [comment]
>Do you mean that users expect the enlist operator to work differently than it does, or that users would expect their to be an alternative operator that works on the list instead of the operand?

The former, I would think. I certainly expected enlist to work as I described and I would think others do too, so why introduce another operator (which would *still* risk that users think enlist should work as suggested).

The (my) assumption/expectation is based on that most other operators can appear "mid filter" and use the up-until-then-results as input, and accept empty argument brackets.

Forgive a back-seat driving layman, but given how other operators behave, I'd guess that the filter run "up-until-then" is a temporary variable. Thus, it ought to be possible to use this as input for ´enlist[]´. This would be automatic and thus significantly simpler and less error prone than the examples you provided.

**Comment by tobibeer** [comment]
I don't quite get it. Enlist turns a title list into titles which is also what this does:

```
[[tid]get[tags]]
```

It already gives you a list of titles.

So this:

```
<$vars mytagsvalue={{{ [[enlist Operator]get[tags]] }}}>
<$set name="mytagslist" filter="[enlist<mytagsvalue>]">

; mytagsvalue
: <$text text=<<mytagsvalue>>/>

; mytagslist
: <$text text=<<mytagslist>>/>

</$set>
</$vars>
```

...practically gives the same output twice.

![image](https://user-images.githubusercontent.com/97566/33799142-c7e930aa-dd25-11e7-92c6-dc2c618f625a.png)

So, what's the point of it?

@twMat: anything here that is actionable?

**Comment by twMat** [comment]
@tobibeer 

The request is to allow the enlist filter op to be used like basically all other operators, i.e "mid filter". It is quirky to demand circumventional setwidgets here.

**Comment by tobibeer** [comment]
@twMat: Please be so kind and provide a practical example of what you want to achieve but can't.

**Comment by twMat** [comment]
Sorry, in my previous reply I should have emphasized that - other than possibility to use the operator mid-filter like any other operator - I want the output to be a list of **separate** titles.

I.e any string that is input to the operator is split up so to output separate units, where either space is a delimiter other than if surrounded by `[[ ]]`. 

Clearer?

**Comment by tobibeer** [comment]
Not really. :-) Can you give an actual example of input titles and expected output?

**Comment by twMat** [comment]
{{{ [[tid]get[tags]enlist[]addsuffix[XXX]] }}}` and the tags for "tid" are "[[aa aa]] bb [[cc cc]]".

I want the output: 

 [aa aaXXX]() [bbXXX]() [cc ccXXX]()

or possibly

 [aa aaXXX]() bbXXX [cc ccXXX]()

I do not want

 [aa aa bb cc ccXXX]()

...or...

[[aa aa]] bb [[cc cc]]XXX]    as one monolithic link (github prevents the brackets from being "blue" )

**Comment by Jermolene** [comment]
The thing that might be counter-intuitive is that `[[tid]get[tags]]` yields a *list* of the tags, not a quoted string of the tags, as you might expect.

So, with reference to the OP, you don't need the `enlist` operator. You can just do `[[tid]get[tags]]` to get a list of the tags.

**Comment by twMat** [comment]
@tobibeer and @Jermolene 

OK I'm closing this and will return when I eventually stumble over the problem again. Who knows, maybe I'm misunderstanding something.
