### ISSUE TITLE
All tid creation should induce predefined set of fields

### ISSUE THREAD

**Issue by twMat** [Jermolene/TiddlyWiki5#2969]
**Proposal**: For consistency/predictability, any tiddler creation should by default create a full (but minimal) set of tiddler fields.

**Illustrative demo**: [demo](http://fieldtest55.tiddlyspot.com/)

Setting tag on missing tid creates the tid, with that tag. But *title* and *tags* are the only fields created.

...and deleting the tag not only deletes the tag but also adds fields *modified* and *modifier*! IMO both tagging and untagging should create/update those other fields.  And, probably, also *created + creator* should be added.

**Actual use case problem**: As seen in demo, the missing fields prevent the created tiddler from showing up in *Recent* list. This is problematic when I now am developing [Batch Manipulator](batchmanipulator.tiddlyspot.com) to allow batch tagging also on non existing tids. I.e tids come into existence but don't appear in *Recent*.

**Comment by twMat** [comment]
(note: there was something wrong with the demo. This is now corrected.)

**Comment by pmario** [comment]
IMO this is a bug or an oversight.
