### ISSUE TITLE
Inconsistent behavior in set widget between value and filter attributes and issues caused by it.

### ISSUE THREAD

**Issue by reidgould** [Jermolene/TiddlyWiki5#2971]
Using the "value" attribute of the set widget to set a title sets the plain value.
Using the "filter" attribute of the set widget to set a single title sets an enlisted value, even if using get[title].

A workaround to avoid automatic enlisting is to URI encode at the end of the filter. 

[Import the tiddler in this gist](https://gist.github.com/reidgould/1bde138826a49bef5bf9c7bda567dfeb) for examples of the issue and workaround.

Being able to retrieve a value using filter is important to be able to build up much abstraction or complexity using macros and widgets. See ["blc-ui-Macros.tid" in this commit](https://github.com/reidgould/tiddlywiki-blc-plugin/blob/keep-perm-CgICDAwKDAkIDw4DBA0KBg/Source/editions/blc-plugin/plugins/blc/tiddlers/common/blc-ui-Macros.tid) of BLC Plugin for an example of how automatic enlisting (which occurs in [blc-ui-ListViewTemplate.tid](https://github.com/reidgould/tiddlywiki-blc-plugin/blob/keep-perm-CgICDAwKDAkIDw4DBA0KBg/Source/editions/blc-plugin/plugins/blc/tiddlers/ui/blc-ui-ListViewTemplate.tid) where it uses the next operator) prevented a critical operation in the "actionAddTwoWay" macro where it uses insertbefore, and the workaround saved it, albeit at computational cost of encoding and decoding the entire list that needed to be operated on.

I recognize this behavior is intentional and necessary for list operation, but perhaps it could use some refinement (especially because these are both available on the set widget which out of context one would think they should operate the same). As a newcomer it threw me for quite a loop and took me a few days to figure out.

Two possible proposals:

* Make operators that expect a plain value (like insertbefore) parse an enlisted value.
* A delist operator so that plain value can be stored into a variable.

**Comment by Jermolene** [comment]
Hi @reidgould 

When used with the "filter" attribute the set widget intentionally always returns a list, which means that items are quoted if they contain spaces. That is true regardless of whether the filter returns one or more items.

It sounds like you might need the new(-ish) triple-quoted attribute syntax: it evaluates as a filter and then returns just the first value, without any quoting. For example:

```
<$vars foo={{{ [tag[mytag]] }}}>
...
```

**Comment by reidgould** [comment]
That sounds like exactly what I need! Thank you, feel free to close this issue.

I recall seeing that precisely once in the tw5.com edition, but the description was short and I didn't understand its use at the time. Perhaps that part of the docs could be expanded.

**Comment by reidgould** [comment]
For anyone looking in the future, here is an [updated version of the gist above](https://gist.github.com/reidgould/3b1c9f3e44276bfa65d78c5a5950ebe4) using triple curly bracket syntax with the value attribute on the set widget.

**Comment by Jermolene** [comment]
Thanks @reidgould

**Comment by tobibeer** [comment]
@reidgould: with 5.1.14 the **select** attribute was introduced for the [SetWidget](https://tiddlywiki.com/#SetWidget) (instead o #2589) and its purpose seems to be what you asked for.
