### ISSUE TITLE
Documentation for "has" operator on tiddlywiki.com needs to be updated

### ISSUE THREAD

**Issue by rmunn** [Jermolene/TiddlyWiki5#2977]
As of 2017-09-15, the documentation for the `has` operator on tiddlywiki.com looks like this:

![has_operator_field](https://user-images.githubusercontent.com/90762/30464120-d4a7a480-99f9-11e7-8239-6c7077b217aa.png)

The documentation for the `field` suffix is backwards from what the code actually does. The docs say that the normal behavior of `field` is to return "those input tiddlers in which field `F` does *NOT* exist", and the `!` (negated) behavior of `field` is to return "those input tiddlers in which field `F` exists". (Which would be very confusing if that's how it actually worked).

However, the [source for the `has` operator](https://github.com/Jermolene/TiddlyWiki5/blob/24c325611bdf8793afeb8804d21bb03af1e88e75/core/modules/filters/has.js) shows that the `field` suffix actually works the way one would expect (and the opposite of what the documentation says): `has:field` will return tiddlers for which field `F` exists (whether or not its content is empty), and the `!` version of `has:field` will return tiddlers for which field `F` does *NOT* exist.

So the code is correct, but the documentation of the `field` suffix needs to swapped around.

**Comment by rmunn** [comment]
Actually, this was already fixed in https://github.com/Jermolene/TiddlyWiki5/commit/3edf3892e85e20415849cec1ef7cbf168b1c5316, four months ago. So the only problem remaining is that the tiddlywiki.com site has not been updated with that fix. Might as well leave this issue open until the site gets updated, then close the issue.

**Comment by tobibeer** [comment]
@rmunn: Tiddlywiki.com is updated. Please close.
