### ISSUE TITLE
Request: Allow comments in macros

### ISSUE THREAD

**Issue by twMat** [Jermolene/TiddlyWiki5#2979]
Ref to [this discussion](https://groups.google.com/forum/#!topic/tiddlywikidev/AMrfx7mMdFQ), where knowledgeable people come with input.

**Problem**
The more complex my wikitext code gets, the greater the need for comments in the code. It is very difficult to *locate* stuff or even to know what a macro, that I wrote myself, does - even within a single tiddler[1].

**Request**
Functionality to comment. The ideal would be comments *anywhere* in tiddlers, including inside macros and between macro defs. 

From an end user POV, I want to use one global syntax for this, i.e the same for e.g CSS and wikitext. As CSS would then dictate, this means `/* ... */ `. And perhaps `//` as a complimentary and optional addition for single line comments (note: conflict with `//italics//`)

**Side note**
[1] A fundamental problem that increases the need for comments is that you cannot easily split your code into multiple macro tiddlers *during* development because they re-render. You also loose overview. Instead you're forced to create complex monolithic tiddlers - with drastically increases need for comments. I outline a fundamentally different tiddler paradigm [here](https://groups.google.com/forum/#!topic/tiddlywikidev/Rnzj7yGrg_E) that deals with this.

**Comment by tobibeer** [comment]
You can most always use:

```
\define foo()
<!-- Some comment -->
\end
```

Everything else seems slightly on the non-backwards compatibility front.

The only thing I can think of is to provide an enhanced macro definition pragma, like

```
\define\ foo()
/*comment*/
\end
```

So, the second backslash indicates that you wish to treat `/* */` as comments within your macro. In other words, you would thus enable the parser rule for it ...which would have to be created.

@Jermolene: Not sure if we should support simple, single line comments. I suppose we should not. At least, I would not know what characters to use, perhaps `\\`.

**Comment by pmario** [comment]
```
\define foo()
<!-- Some comment -->
\end
```

As I wrote in the discussion Mat mentioned. https://groups.google.com/d/msg/tiddlywikidev/AMrfx7mMdFQ/ZjDrv1AUAwAJ  ... That's a performance problem for heavily commented macros. 

We did get the \whitespace trim option which allows us to make macros more readable. like so: 

```
\define foo()
\whitespace trim
<code>
  <code>
  </code>
</code>
\end
```

May be we may want a `\comment ##`  pragma, which removes lines that start with `##` while parsing.

**Comment by tobibeer** [comment]
Not sure about the `##`, but other than that 👍

**Comment by pmario** [comment]
>Not sure about the ##, but other than that 

I thought, it may be configurable like: 

`\comment // or ## or $$ or §$%&` ... so it can be uniqe, depending on the content.

**Comment by pmario** [comment]
@twMat -- Can be closed. We do have `<!-- comments -->` in macros and in the `\pragma` area now.
