### ISSUE TITLE
LaTeX plugin does not work in markdown tiddlers

### ISSUE THREAD

**Issue by crypdick** [Jermolene/TiddlyWiki5#2984]
The Katex and Markdown plugins don't work with one another. Most of my wiki ks in markdown and it is annoying to port individual docs into the Tiddly syntax to get equations to display.

Edit: [waylonflinn/markdown-it-katex](https://github.com/waylonflinn/markdown-it-katex) adds Katex support to Markdown, but I don't know if that's helpful.

**Comment by crypdick** [comment]
Here are some previous discussions on the mailing list: [one](https://groups.google.com/forum/#!searchin/tiddlywiki/latex$20markdown|sort:relevance/tiddlywiki/arAS5qvYkiA/5xHmbQI79ukJ) and [two](https://groups.google.com/forum/#!searchin/tiddlywiki/latex$20markdown|sort:relevance/tiddlywiki/PhFdqZ_eWLE/J2soYXjupmoJ).

**Comment by tobibeer** [comment]
Feels like plugin territory to me.

**Comment by syrte** [comment]
I've modified the official markdown plugin with `markdown-it.js`, here's the link to gist https://gist.github.com/syrte/8062e11d8fec6221820c5f998239af61 if you're interested.
Documentation self-contained.

**Comment by syrte** [comment]
`marked` is another choice. However `markdown-it` is in a more active maintenance and has a better flexibility through plugins.

**Comment by diego898** [comment]
Just want to bump this - Much of the "modern web" (blog posts, papers, etc) are written in some flavor of markdown with latex: `$$x^2$$` and then "compiled" to other versions using pandoc, for example.

I think it makes sesne for tiddlywiki to support this workflow.

**Comment by szhorvat** [comment]
Please add an _official_ MarkDown plugin which supports math (KaTeX).

It should support the common syntax where inline math is delimited with `$...$` and display math is delimited with

```
$$
...
$$
```

Using `$$` for inline math is cumbersome and does not make it easy to copy/paste to other systems (including LaTeX documents).

The plugin linked above does exactly this, but it is based on an old version of the MarkDown plugin (it replaces it), and it is no longer maintained. 

An _official_ MarkDown plugin with this capability would be very useful in that people could rely on it, and count on it working for as long as TiddlyWiki itself works. This kind of assurance is important to be able to choose TiddlyWiki with confidence. Third-part. plugins always fall out of maintenance eventually so someone who can't themselves write/maintain plugins cannot realistically rely on them.

**Comment by pdroalves** [comment]
Any update on `$..$` syntax? I really miss more compatibility to Latex.

**Comment by 5agado** [comment]
Also curious about any update on this issue. 

I definitely agree with @szhorvat, and I'm currently relying on the mentioned plugin by @syrte , but is no longer maintained, and has major issues for links to other Tiddlers.

**Comment by tejasvi** [comment]
Probably there were a few changes in meanwhile. I am able use latex in markdown tiddlers by adding `latex-parser` rule to `$:/config/markdown/renderWikiTextPragma` which now contains
```
\rules only html image macrocallinline syslink transcludeinline wikilink filteredtranscludeblock macrocallblock transcludeblock prettylink latex-parser
```

@pdroalves If you have minimal experience with javascript and regex you can modify `$:/plugins/tiddlywiki/katex/latex-parser.js` to support that syntax.

**Comment by somenxavier** [comment]
@tejasvi Perhaps you could make some Patch Request here with your code as you have high expertise

**Comment by tejasvi** [comment]
@somenxavier I would love to give TW back but I currently don't have time for a PR. I recently migrated to markdown format and needed more consistent latex delimiter across tools. From the attached file remove `.txt` extension to get the `.json` and then import it in your wiki. It supports both block mode (using `$$..$$`) and inline mode (`$..$`). It works only with markdown since TW macro syntax uses `$` thus requiring advanced regex.

[$__plugins_tiddlywiki_katex_latex-parser.js.json.txt](https://github.com/Jermolene/TiddlyWiki5/files/5930484/__plugins_tiddlywiki_katex_latex-parser.js.json.txt)

**Comment by somenxavier** [comment]
@tejasvi it does not work

**Comment by oflg** [comment]
@tejasvi thanks for your work, but the changed katex_latex-parser conflict with wikitext . I modify it's name to katex_markdown-parser which works with both wikitext and markdown. 

[katex_markdown-parser.zip](https://github.com/Jermolene/TiddlyWiki5/files/6607263/katex_markdown-parser.zip)

**Comment by rryan** [comment]
Since TiddlyWiki v5.1.22 switched to using [remarkable.js](https://github.com/jonschlinkert/remarkable), I forked the built-in markdown plugin and added support for KaTeX using [remarkable-katex](https://github.com/bradhowes/remarkable-katex). It uses the version of KaTeX provided by the tiddlywiki/katex plugin, so that is required by this plugin.

Hope it's useful!
https://github.com/rryan/tiddlywiki-markdown-katex

All it took was a pretty trivial change on top of including remarkable-katex.js:
https://github.com/rryan/tiddlywiki-markdown-katex/commit/14e72c522d13db52ad7fba2245f9a50be980469f

Happy to discuss how this could be integrated as an official plugin.

**Comment by rryan** [comment]
(hat tip to @bradhowes for the nice plugin)

**Comment by Jermolene** [comment]
Hi @rryan thanks for sharing. Those modifications looks like they would be useful for the core. Would you be able to make a PR?

**Comment by rryan** [comment]
thanks @Jermolene! I'd be happy to add this to the core plugin. 

Clarification: Do you mean I should modify the tiddlywiki/markdown plugin directly? That means it would depend on the katex plugin (which I don't think it does currently). I guess I could try to detect whether the katex plugin is installed and used remarkable-katex.js in that case. Is there a good way to check if another plugin is installed?

**Comment by Jermolene** [comment]
> Clarification: Do you mean I should modify the tiddlywiki/markdown plugin directly?

Yes, hopefully this would be a backwards compatible change?

> That means it would depend on the katex plugin (which I don't think it does currently). I guess I could try to detect whether the katex plugin is installed and used remarkable-katex.js in that case. Is there a good way to check if another plugin is installed?

You can test for the existence of a JS module without requiring it like this:

```
	if(!$tw.modules.titles["$:/plugins/tiddlywiki/async/async.js"]) {
```
