### ISSUE TITLE
Width of content Type in Editor too narrow

### ISSUE THREAD

**Issue by TiddlyTweeter** [Jermolene/TiddlyWiki5#2986]
The default width of the input field for content Type in the Editor is simply too narrow. It becomes more problematic if you make custom types with long names. Could it either have adaptive width to length of content or just a much wider default?

![capture](https://user-images.githubusercontent.com/28830541/30808966-6d45162e-a200-11e7-940b-27dcff7e4213.PNG)

**Comment by Marxsal** [comment]
While waiting for response, you can alter this using a stylesheet tiddler with contents:

input.tc-edit-typeeditor { width: 80% ; }

**Comment by saqimtiaz** [comment]
@BurningTreeC would you be up to taking a look at this?

**Comment by BurningTreeC** [comment]
@saqimtiaz - I can have a look
