### ISSUE TITLE
Request: Editor have a toggle between monospace & proportional fonts

### ISSUE THREAD

**Issue by TiddlyTweeter** [Jermolene/TiddlyWiki5#2987]
When you are doing CODING using MONOSPACED fonts is much better.

For normal texts PROPORTIONAL is better.

Any chance of a toggle between them, live, in the Editor?

**Comment by pmario** [comment]
The next version will have a setting .. see merged PR #2867

**Comment by TiddlyTweeter** [comment]
Thanks @pmario. I will close the thread.
