### ISSUE TITLE
Missing else in put saver?

### ISSUE THREAD

**Issue by donleyp** [Jermolene/TiddlyWiki5#2989]
See https://github.com/Jermolene/TiddlyWiki5/blob/7bdaabce78b86698dfed6e93fbabc624b79bf650/core/modules/savers/put.js#L73

**Comment by sukima** [comment]
I do think this is a bug!

**Comment by Arlen22** [comment]
I second, since this could possibly result in callback being called twice, breaking a cardinal rule of callbacks.

**Comment by tobibeer** [comment]
Made a PR to fix this: #3042 . Perhaps close, since the initial commit was also heavily commented.
