### ISSUE TITLE
Mixed Active Content problem when loading plugins

### ISSUE THREAD

**Issue by javabean** [Jermolene/TiddlyWiki5#2994]
Hi there,

Currently hosting a private instance of TiddlyWiki 5.1.14 on a WebDAV server.
I works quite well, except when I want to install plugins, where I get a "mixed active content" access denied: my server serves over https, but the TW plugin server only speaks http…

Could you please allow plugins to load over a secure (https) connection?

Thanks!

**Comment by tobibeer** [comment]
@javabean This is a duplicate of #2582, please close. (@Jermolene).

**Comment by javabean** [comment]
Thanks for taking care of this issue, I can now happily install plugins! :-)
