### ISSUE TITLE
Keyboard shortcuts for Dropdown lists navigation (question / proposal)

### ISSUE THREAD

**Issue by llamaqcom** [Jermolene/TiddlyWiki5#2998]
Dear @Jermolene : As I have noticed, currently it's impossible to use standard keyboard shortcuts (Esc - close list, ArrowUp, ArrowDown to move up and down the list) for dropdown lists generated by TiddlyWiki (such as Tag List when adding tags to a tiddler or in Search Box result). If I'm right only Enter works to adding tags. Is it technical limitation? Is it possible to implement these shortcuts, at least with a custom script? Can I widen Enter for tag script adding Escape for close? If yes, where is this script located?

**Comment by sancho-one** [comment]
@pmario Could you help me to figure it out how to summon new tiddler event "tm-new-tiddler" with javascript? I couldn't find out where it's hidden beneath $tw. :)

**Comment by pmario** [comment]
>@pmario Could you help me to figure it out how to summon new tiddler event "tm-new-tiddler" with javascript? I couldn't find out where it's hidden beneath $tw. :)

I'm not sure, what this has to do with the initial issue? Can you clarify?

**Comment by pmario** [comment]
> Is it technical limitation?

Kind of. .... It's an implementation limitation. ... The TW dropdown is just a new DOM element that is shown above the other UI elements. ... It's not a real select dropdown. .. That's why activating different keyboard navigation is relatively complex.

**Comment by pmario** [comment]
>Is it possible to implement these shortcuts, at least with a custom script? 

Not really.

**Comment by pmario** [comment]
> If I'm right only Enter works to adding tags.

Yes, because this is part of the text input function and not the dropdown.

**Comment by sancho-one** [comment]
@pmario I've realized very basic rawmarkup script which handles Global keyboard events and it integrates with TW5 perfectly:

```
<script type="text/javascript">
document.onkeyup=function(e){
  var e = e || window.event; // for IE to cover IEs window event-object
  if(e.altKey && e.which == 65) {
    alert('Keyboard shortcut working!');
    // @todo: invoke send-message message tm-new-tiddler here
    return false;
  }
}
</script>
```

Currently it's triggered on Alt+A. I'd like to handle it New Document event and Esc event for TW's pseodo-dropdown lists.

New Tiddler message is just easy to start with.

**Comment by tobibeer** [comment]
@sancho-one: This is a duple, pls add your requirements [t]here: #980 and close this one.

**Comment by tobibeer** [comment]
Also, this one tackling #980 is long overdue for a pull request: #1970 

As far as I remember it provides the groundworks for keyboard / event based enhancements.

**Comment by BurningTreeC** [comment]
@Jermolene - I believe this Issue can be closed as we now have keyboard-navigatable dropdowns

**Comment by Jermolene** [comment]
Thanks @BurningTreeC
