### ISSUE TITLE
Title of new journal tiddlers, display date time format interpretation

### ISSUE THREAD

**Issue by sancho-one** [Jermolene/TiddlyWiki5#2999]
At least as for title of new journal tiddlers, TiddlyWiki (or plugin?) can't interpret correctly HH for hours, it displays "HH" instead of hours in 24-hour format.

**Comment by pmario** [comment]
Use `hh` and `hh12` as shown here: http://tiddlywiki.com/#DateFormat

**Comment by sancho-one** [comment]
@pmario Yes, I've just found it by myself but thank you very much for your assistance!

**Comment by pmario** [comment]
cool ... can you please close the issue ... if it is solved?
