### ISSUE TITLE
Editing ViewTemplate by inserting a new-line blocks the .navigatTo handling of the core. 

### ISSUE THREAD

**Issue by pmario** [Jermolene/TiddlyWiki5#3002]
Editing ViewTemplate by inserting a new-line blocks the .navigatTo handling of the core. 

To recreate the Issue see: https://groups.google.com/d/msg/tiddlywiki/_nZI7Kt-UR0/0F5fLKrZBQAJ

Code that cause the problems: https://groups.google.com/d/msg/tiddlywiki/_nZI7Kt-UR0/0eFaEGmUAwAJ

Possible fix: https://groups.google.com/d/msg/tiddlywiki/_nZI7Kt-UR0/yYtglcfPAwAJ

**Comment by tobibeer** [comment]
@pmario: Sry, but your breadcrumbs didn't work for me at all. Could you make a PR and a demo instead?

**Comment by pmario** [comment]
To reproduce: 

I was playing with $:/core/ui/ViewTemplate in search of ways to change the tiddlers' look while I encountered something strange. It can be easily reproduced online on tiddlywiki.com site.

 1. Go to http://tiddlywiki.com/
 1. Edit the shadow tiddler $:/core/ui/ViewTemplate
 1. Find the opening `<div>` tag, immediately following the `<$tiddler>` widget declaration
    `...<$tiddler tiddler=<<currentTiddler>>><div class=<<frame-classes>>>...`

 1. Place the cursor between the `<$tiddler>` and the `<div>` and insert a newline
    `...<$tiddler tiddler=<<currentTiddler>>>`
    `<div class=<<frame-classes>>>...`

 1. Save and close, overwriting the shadow tiddler

Now click on any link in the page (both in the story or in the sidebar): it seems that tiddlers are opened, but the page doesn't scroll to the clicked tiddler. Il looks very strange to me that simply adding a newline could change the wiki behaviour. 

I first found something similar on a wiki I was working on, with a little different result. In that case I had a  working custom ViewTemplate with more changes and I inserted some newline to make the code more readable. When I saved the "beautified" ViewTemplate it happened that clicking on any link raised a Javascript error.

TypeError: this.getLastFrame(...).getBoundingClientRect is not a function

I rolled back my newline one by one, until I came to this and the error was fixed. So I decided to test it on the Tiddlywiki site to see if it was just because of my changes. As I said on the site the behaviour is also unexpected, even if a little bit different.

discussion: https://groups.google.com/d/msg/tiddlywiki/_nZI7Kt-UR0/0F5fLKrZBQAJ

**Comment by tobibeer** [comment]
Ha, I was mostly curious about the "Possible fix"... and didn't discover it yet. Was there a suggested solution then, already? (Except reverting those newlines?)

**Comment by Jermolene** [comment]
The problem here is that most of the storyviews depend upon each item in the story river being represented by a single DOM element that contains the body of the tiddler. Meanwhile, by design, the list widget doesn't produce any DOM elements itself. That means that it is a requirement for the template to enforce a wrapper element around each tiddler in the story river.

Adding the newline as above changes the way that the template is parsed such that the requirement for a single wrapper element for each story tiddler is broken — you can use the parse tree preview pane to observe what's going on.

**Comment by tobibeer** [comment]
Well, then why don't we add a wrapper and then you can have as many newlines within it as you want?

**Comment by Jermolene** [comment]
Why would we want to change anything? The situation is at the moment is that things break if you make a modification to a system template and you don't know what you're doing. That would seem to be the situation with pretty much every system template.

**Comment by pmario** [comment]
As I wrote, we should test it with the new `\whitespace trim` pragma. ... I didn't do that yet.

**Comment by tobibeer** [comment]
> Why would we want to change anything?

To make the templates more robust, I think, especially when users want to change them but face these kinds of unknowns / constraints.

**Comment by pmario** [comment]
This issue cannot be replicated anymore, since the template structure has changed significantly. I cannot find the code parts mentioned. So close it for now.
