### ISSUE TITLE
Enable SSL for tiddlywiki.com

### ISSUE THREAD

**Issue by Jermolene** [Jermolene/TiddlyWiki5#3005]
It is proposed to implement SSL for tiddlywiki.com over the weekend of 11th/12th November 2017.

The plan is to use [CloudFlare](https://cloudflare.com)'s free service level to give us basic SSL support. The performance of the site may also benefit from CloudFlare's content delivery network.

Everything should still work -- for example, old links to http://tiddlywiki.com/ will be automatically redirected to https://tiddlywiki.com/ -- but please let me know here if you have any concerns.

This change should fix a number of reported issues: #2709, #1437, #2788, #2582.

**Comment by pmario** [comment]
I think, it could be done, without any 3rd party service. github will support it. We just would need to restructure the tiddlywiki repo a little bit.

**Comment by Jermolene** [comment]
Hi @pmario as far as I know GitHub Pages doesn't support SSL with custom domains, have you found a reference that suggests that it does?

**Comment by pmario** [comment]
>Hi @pmario as far as I know GitHub Pages doesn't support SSL with custom domains, have you found a reference that suggests that it does?

I was pretty sure, that I did ... But having a closer look now. ... It seems to be limited to github.io .. sry.

But IMO [CF Free Plan : Security tab: overview](https://www.cloudflare.com/plans/#compare-features) says: 10$ for custom hostnames. ... If I see it right. ... You need to scroll down to: "Compare All Features": Security tab.

**Comment by Jermolene** [comment]
OK, I've now flipped the switch. Things seem to work, I'd appreciate any help tracking down anomalies:

https://tiddlywiki.com/
https://classic.tiddlywiki.com/

In particular, I think it's worth testing the plugin library.

**Comment by danielo515** [comment]
Hello @Jermolene 
Which kind of certificate are you using ? Seems to not be trusted by my browser

![image](https://user-images.githubusercontent.com/2270425/32689935-da2e6b02-c6ed-11e7-9c06-4222139b0e01.png)

**Comment by Jermolene** [comment]
Hi @danielo515 I'm using [CloudFlare](https://www.cloudflare.com/)'s free tier, which gives a shared certificate. It works OK for me in Chrome and Chrome Canary; perhaps there is something stuck in the cache?

**Comment by sukima** [comment]
CloudFlare uses Comodo as a root:

![screenshot](https://user-images.githubusercontent.com/70075/32691688-7d3af0dc-c6d9-11e7-9901-4dc04009ab6c.png)

@danielo515, Considering the recent [fraud problems with Comodo](https://arstechnica.com/information-technology/2011/03/how-the-comodo-certificate-fraud-calls-ca-trust-into-question/) is it possible that root certificate has been black listed by your system?

**Comment by Jermolene** [comment]
Hi @danielo515 are you still seeing that certificate problem?

**Comment by danielo515** [comment]
Hello,

On my workplace laptop the problem does not appear. Maybe is a problem with my home computer. I'll check it out again.

**Comment by Jermolene** [comment]
Excellent, thanks @danielo515
