### ISSUE TITLE
Firefox Add-on for TiddlyWiki doesn't work anymore with Firefox 57

### ISSUE THREAD

**Issue by modir** [Jermolene/TiddlyWiki5#3016]
I know that this github repo is about TiddlyWiki and not about the firefox add-on, but I didn't find anywhere an issue tracker for the Firefox add-on and it seems that the Firefox add-on was developed by the same person who manages this repo.

Back to the problem: The Firefox add-on is written in a old technology and therefore doesn't work anymore in Firefox 57. More information about it here: https://support.mozilla.org/en-US/kb/firefox-add-technology-modernizing?as=u&utm_source=inproduct

**Comment by pmario** [comment]
There are 2 new options now: 
see: https://groups.google.com/forum/#!topic/tiddlywiki/h0k7z62N79Y
and: https://groups.google.com/forum/#!topic/tiddlywiki/9984ShVVbbA

**Comment by modir** [comment]
@pmario Thanks for the two links. It's sad that we have the restrictions with the download folder now.

**Comment by pmario** [comment]
> It's sad that we have the restrictions with the download folder now.

Yes. But browser devs won't change that anymore. 

Mark S. has posted some info how we can create "Directory Links" (Junctions) on windows. So we can link folders from the Download dir to other directories. ... Kind of a workaround. .. We still have to open TW files from within the download dir. .. see: https://groups.google.com/d/msg/tiddlywiki/h0k7z62N79Y/mOnErEHqBwAJ

Browser vendors also implemented a mechanism, that allows addOns to [send data to external apps.](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Working_with_files). The last section of the linked document contains some info about this mechanism. 

The probelem here is, that stuff IMO is a 100 times more complex and error prone, than just installing a browser addOn. 

So for the time being, we'll have to live with the restrictions. ..

**Comment by pmario** [comment]
You can close the issue, if that's OK for you.

**Comment by tobibeer** [comment]
The whole thing seems quite bonkers, browser-vendor-wise, seeing as how you can (re-)define the download location to whatever you want.

**Comment by pmario** [comment]
Yes. ... but that doesn't matter. They think it's more secure that way and they won't change it anymore. ... 

I got this response [as a starting argument at bugzilla.](https://bugzilla.mozilla.org/show_bug.cgi?id=1420586#c1)

>Since WebExtensions by design have very limited ways to interact with the filesystem, I don't agree with the claim that "it should be easy".

**Comment by pmario** [comment]
@modir ... please close, since only the creator of an issue and Jeremy can close them.

**Comment by modir** [comment]
OK. I close it for now. I would open it again if someone posts a practical solution to the problem.

**Comment by pmario** [comment]
> It's sad that we have the restrictions with the download folder now.

There's absolutely no chance, that this restriction will be lifted. ... 

The devs closed comments at this bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1246236  which imo means. "Whatevery you have to say. ... wo don't want to know it"

**Comment by callahad** [comment]
If anyone's looking to resurrect TiddlyFox, one avenue would be to implement the filesystem writing as a separate program, and communicate with it using [Native Messaging](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Native_messaging). This would work on both Chrome and Firefox.

**Comment by pmario** [comment]
We do have 2 new AddOns. 

https://addons.mozilla.org/en-US/firefox/addon/file-backups/ and 
https://github.com/buggyj/savetiddlers/releases

**Comment by pmario** [comment]
I did investigate Native Messaging. ... But the whole concept is very complcated. We'd need to create several different install packages, plus browser addOns ... 

So imo TiddlyDesktop, TiddlyServer or the built in windows [WebDav option](https://www.youtube.com/playlist?list=PLuiC_HFhI4OwoVDb-B-VK0ydj-mBPNn-1) would be easier to use. ..
