### ISSUE TITLE
Does a plugin library beg for a library plugin?

### ISSUE THREAD

**Issue by tobibeer** [Jermolene/TiddlyWiki5#3026]
I am a bit confused about @danielo515's [request for a library plugin to contain a tiddler pointing to my plugin library](https://github.com/tobibeer/tw5-plugins/issues/2).

Would you agree that there's merit to that? Otherwise, if not, what would be the most sensible approach to "include" someone else's plugin libary into ones own build / distro?

**Comment by danielo515** [comment]
@tobibeer I seriously don't understand why you see my request so contrived.
Plugin libraries are plugins themselves, that's the way it works on tiddlywiki.

**Comment by tobibeer** [comment]
> Plugin libraries are plugins themselves, that's the way it works on tiddlywiki.

I don't see it as contrived, I just don't see the point.

In what sense can you not use / access my library without a plugin?

So far, my sole instruction was: Drag this tiddler with a reference to my library to your wiki.

So, why not just use an appropriate library tiddler to point to my library? You can add any details and descriptions to your liking, so long as the target knows where to look.

**Comment by pmario** [comment]
@Jermolene -- Can be closed. 

Tobias's plugin library config tiddler can be found at: http://tobibeer.github.io/tw5-plugins/#%24%3A%2Fpluginlibrary%2Ftobibeer%2Fofficial -- So the official library mechanism can be used to import plugins. 

**Important** The "url" field has to be set to **https://** instead of http://

**Comment by Jermolene** [comment]
Thank you @pmario
