### ISSUE TITLE
Trouble Removing Items From Filter Results

### ISSUE THREAD

**Issue by tobibeer** [Jermolene/TiddlyWiki5#3027]
> ## RESOLUTION
> 
> Below, only actual tiddlers are subtracted from the input, not matching titles. So, it has to be either of:
> 
> * `foo bar $:/baz +[!is[system]]`
> * `foo bar $:/baz +[!prefix[$:/]]`

----

I'm having trouble recapitulating why the following is not behaving as I expect it to in advanced search / filters:

* `foo bar $:/baz -[is[system]]`
* `foo bar $:/baz -[prefix[$:/]]`

![to_remove_or_not_to_remove](https://user-images.githubusercontent.com/97566/33456823-d95f75ee-d620-11e7-9e64-5df361389d41.jpg)

The same result is returned using:

```
foo bar $:/baz -[prefix[$:/]]
```

Am I wrong in expecting both to yield:

```
foo
bar
```

?!?

Otherwise, how can I remove items from the list w/o being forced to do it in one filter run?

**Comment by morosanuae** [comment]
@tobibeer I think this version works (tested): `foo bar $:/baz +[!is[system]]`, but I don't know why yet.

**Comment by pmario** [comment]
According to the docs, it should work. https://tiddlywiki.com/#Filter%20Expression

**Comment by pmario** [comment]
`foo bar $:/baz -[prefix[$:/]]` .... works if $:/baz is a physical tiddler.

**Comment by tobibeer** [comment]
> works if $:/baz is a physical tiddler

I would argue this is wrong. Filters don't know much about tiddlers, unless specifically designed for that, they mostly know about "titles". So, if there are elementary filters that require for there to be tiddlers, then there have to be equivalents that just allow to specify and operate on "titles". Possibly, we could introduce `--[prefix[$:/foo]]`. However, to me this smells more of BUG than something asking for yet another pattern.

**Comment by pmario** [comment]
>I would argue this is wrong

That's how it works at the moment. ... But I think it's a bug.

**Comment by tobibeer** [comment]
@Jermolene: Would you be inclined to accept a PR for fixing this as a **bug**?

**Comment by Jermolene** [comment]
@tobibeer I think these are all cases where titles of non-existent tiddlers are being ignored, even if the logic of the filter operation could be handled just with the title, without needing the full tiddler.

We should certainly explore fixing them, and take some care that there are not unexpected side effects.

**Comment by tobibeer** [comment]
@Jermolene: Gr8, I see if I can find a sensible fix ...and hopefully the side-effects are either not existing or easy to fix.

**Comment by tobibeer** [comment]
@Jermolene: After some more testing and debuging, the answer was rather simple. ;-)
