### ISSUE TITLE
BUG: Extra paces in names could lead to overwriting tiddlers! 

### ISSUE THREAD

**Issue by diego898** [Jermolene/TiddlyWiki5#3033]
Below are two tiddlers uploaded as txt files (github) to illustrate this bug:

**[test.txt](https://github.com/Jermolene/TiddlyWiki5/files/1523183/test.txt)**: This is the original tiddler with content: "original test text"

**[test2.txt](https://github.com/Jermolene/TiddlyWiki5/files/1523184/test2.txt)**: Contains 4 links. The first three are all italicized indicating the target tiddler does not exist. Clicking each of these three links opens up three distinct tiddlers, all showing as missing. 

**BUG1**: If you edit **any** of these **three** tiddlers and save, you **overwrite** the original test tiddler with **no warning!** 

**BUG2**: A related bug can be seen by manually creating a new tiddler with title "test" (no quotes), noting the collision warning. If you then add a space, the collision warning banner disappears. **Note**: clicking save on this manually created new tiddler does behave correctly - you get an overwrite warning. This is true if the space is before, after, or both. 

I also posted this [on the google groups](https://groups.google.com/d/msg/TiddlyWiki/Ts2jbqFEqw8/Swlr0FK2BAAJ)

**Comment by tobibeer** [comment]
Yet another reason why spaces and titles are not a happy couple. Trim them, is what I think.

**Comment by diego898** [comment]
I agree @tobibeer, I actually didn't realize that in certain places I had made a link like: `[[My_Title| Existing_Tiddler]]` and was seeing this strange behavior.

**Comment by tobibeer** [comment]
@diego898, I'm pretty sure this issue has been reported before though. Can you double check?

**Comment by Jermolene** [comment]
Thanks @diego898 I think this behaviour is just an unexpected consequence of the fact that the core trims whitespace from titles in the "pretty link" wikitext rule.

**Comment by diego898** [comment]
Thanks @tobibeer you're right. This is almost an exact replica of #1791, and is intimately related to #751 . 

I guess we should close this and move all conversation to #1791?
