### ISSUE TITLE
Feature Request: Suggesting improvements for BibTex plugin

### ISSUE THREAD

**Issue by diego898** [Jermolene/TiddlyWiki5#3039]
I am very interested in using the bibtex plugin in my TW. I use Mendely, and it automatically creates a bib file of my entire library. I made the following small edits to: 

1. made title of resulting tiddler be the parsed title
2. added an alias field, for my own uses
3. added a bibtex-citationkey field to store citationKey.

resulting in the following code change:

```
        // Convert each entry
	$tw.utils.each(data,function(entry) {
		var fields = {
			title: entry.entryTags.title,
			"alias": entry.citationKey,
			"bibtex-citationKey": entry.citationKey,
			"bibtex-entry-type": entry.entryType
		};
```

I then repackaged my plugin and refreshed. I tried uploading my library, but all tiddlers had their **titles** surrounded by `{}`. The actual bibitex file generated by Mendely has `title={{my title}}` for all entries, resulting in the titles all being surrounded by one set of `{}`. 

Even in the test file provided with the default plugin at:

https://github.com/Jermolene/TiddlyWiki5/blob/master/plugins/tiddlywiki/bibtex/samples/first-jabref-bibtex-db.bib

there are 12 entries with the double braces around the title. This seems like a common enough thing for TiddlyWiki to try and deal with. 

I'm not sure that ORCID/bibtexParseJs should be the one to deal with these special characters, since its job is just to parse the file. TiddlyWiki is the one that doesn't want tiddler names with `| [ ] { }`. 

Suggested Improvements:

- Automatically handle special characters in titles 
- Include built-in support for Zotero and Mendely
  - Within these cases, add option to tag posts with author names
  - Specifically for Mendely, it exports a `mendeley-tags` field in the bibtex-entry. We should be able to automatically add these tags to posts as well.

**Comment by diego898** [comment]
I am still learning about plugins and how to pass them parameters/settings, etc. But so far I've made the following changes:

* carefully removed all `{{` and `}}` from the `title` field of my `.bib` file.
  * not that much of a pain using regular expressions
* Made the following changes to `$:/plugins/tiddlywiki/excel-utils/deserializer.js`:

```
// Convert each entry
    $tw.utils.each(data,function(entry) {
        var fields = {
            title: entry.entryTags.title,
            "bibtex-citationKey": entry.citationKey,
            "bibtex-entry-type": entry.entryType
        };
        $tw.utils.each(entry.entryTags,function(value,name) {
            fields["bibtex-" + name] = value;
        });
        // add tags and custom fields
        fields["tags"] = "Paper PoI";
        fields["summary"] = "one sentence summary";
        fields["touched"] = $tw.macros.now.run("[UTC]YYYY0MM0DD");
        results.push(fields);
    });
```

I then repackaged the plugin with: 

```
$tw.utils.repackPlugin("$:/plugins/tiddlywiki/bibtex",["$:/plugins/tiddlywiki/bibtex/bibtexParse.js","$:/plugins/tiddlywiki/bibtex/license","$:/plugins/tiddlywiki/bibtex/readme","$:/plugins/tiddlywiki/excel-utils/deserializer.js"])
```

saved, and reloaded and was on my way. 

Moving forward my plan is to try and setup some kind of config tiddler where a user can enter:

* the string to prepend to each field coming from the bibtex file (ie, change `bibtex-`)
* a set of tags they want to add
* another other fields they would like to add to the incoming tiddlers. 

If I accomplish this, my plan is to fork this repo, make my edits, and open a pull request for these changes.

Any help/advice on how to accomplish this would be greatly appreciated!

**Comment by diego898** [comment]
Just wanted to bump this in case others have comments/suggestions!

**Comment by Jermolene** [comment]
Hi @diego898 my plan is to migrate to using the text-slicer plugin to import BibTeX documents. Text-slicer is evolving to be a generic engine for importing XML data.

In the meantime, you'll probably find experimenting with the existing BibTeX plugin code to be a lot easier, and I'd encourage you to go ahead. The real challenge is finding a useful set of behaviours that work for as many people as possible; the implementation is kind of a detail :)

**Comment by gse-cc-git** [comment]
Hi @Jermolene,
I tried to install the plugin and to drop a bib file in the TW without success.
Could you please give me advices or point to a link explaining the procedure.
Thanks.

**Comment by Jermolene** [comment]
> I tried to install the plugin and to drop a bib file in the TW without success.

Hi @gse-cc-git did you reload the TiddlyWiki after installing the plugin? Can you describe what happens when you drop the file? Do you see any message in your browser's JavaScript console?

**Comment by gse-cc-git** [comment]
I am using:

-  tw 5.1.17 fresh install
-  the tw file is accessed from a webdav server through Firefox Nightly 59.0a1 (2017-11-18) (64 bits) on Ubuntu
- I took (dragged & dropped for the install then reloaded the tw) the plugin from here: https://designwritestudio.updog.co/skunkworks/ 
- then I d&d the first-jabref-bibtex-db.bib file on the tw
- I get a tiddler named first-jabref-bibtex-db.bib
- saving gives that line in the browser's Javascript console:

```
saver-handler: Saving wiki with method autosave through saver put   $:/core/modules/utils/logger.js:33
```

Sorry I do most of these thing without having a clear understanding of the informatics theory behind...

**Comment by Jermolene** [comment]
Hi @gse-cc-git those instructions look correct, apart from the way that you installed the BibTeX plugin. Instead of dragging it from the designwritestudio site, you can install it directly from the TiddlyWiki plugin library (see https://tiddlywiki.com/#Installing%20a%20plugin%20from%20the%20plugin%20library).

Can you perhaps post the BibTeX file you are using?

**Comment by gse-cc-git** [comment]
@Jermolene, thanks for your feedback. 
I installed the plugin update using the method you described.
The BibTeX file I am using comes from the example files in this github repository: `first-jabref-bibtex-db.bib`

[I copied/pasted the content found there](https://github.com/Jermolene/TiddlyWiki5/blob/master/plugins/tiddlywiki/bibtex/samples/first-jabref-bibtex-db.bib)

**Comment by Jermolene** [comment]
Thanks @gse-cc-git

> the import went fine

Does the import panel look like this?

<img width="920" alt="screenshot 2018-05-14 14 46 27" src="https://user-images.githubusercontent.com/174761/40001361-f5f59f08-5785-11e8-8ebd-64e32376ed7f.png">

> the first-jabref-bibtex-db.bib tiddler created do not appears in the Recent tab listing tiddlers

The tiddlers created by the BibTeX importer won't necessarily have a "modified" field, and so won't necessarily show up in the "Recent" tab. You can find them on the "All" tab (under "More"), or via search or filters.

**Comment by gse-cc-git** [comment]
@Jermolene  sorry. I meant went fine like:
![selection_117](https://user-images.githubusercontent.com/12275706/40002499-400b2bde-5791-11e8-94ad-32b1196a1ae2.png)

Could it be somehow link to line endings ?

**Comment by Jermolene** [comment]
Hi @gse-cc-git that looks as though the BibTeX plugin isn't properly installed. Is it listed in the control panel "Plugins" tab?

**Comment by gse-cc-git** [comment]
Hi  @Jermolene, yes it seems to me:
![selection_119](https://user-images.githubusercontent.com/12275706/40002870-32e329a6-5792-11e8-910f-8f1e424b98ac.png)

**Comment by Jermolene** [comment]
Hi @gse-cc-git I'm not sure what's going on: the plugins looks like it is properly installed, but the results of the import show that the plugin isn't active. I just repeated the following steps successfully on my Mac:

1. Visit https://tiddlywiki.com/empty.html
2. Click on the cog icon in the sidebar to open control panel
3. Switch to the plugins tab
4. Click the button "Get more plugins"
5. Click the button "open plugin library"
6. Locate the BibTeX plugin; it should be the second entry
7. Click the "install" button for the BibTeX plugin; a yellow bar should appear at the top of the window
8. Click the red save button in the yellow bar; Chrome should download a new copy of the empty wiki with the BibTeX plugin installed
9. Open the newly downloaded file
10. Drag the `first-jabref-bibtex-db.bib` into the TW browser window

I think that that is pretty much what you're doing too?

**Comment by gse-cc-git** [comment]
Hi @Jermolene,
I followed the procedure and repeated it iwth
- Firefox 57
- Firefox 59.01a
- Chrome 64
- Firefox ESR

each time I get the import picture posted above...
I tested with my own bibtex file, and with a reduced version of the example bib file (2 refs only)... without more success.

I'll try opn a windows machine and let you know...
I must be dumb as hell and missing something.

Sorry to bother you with that.

**Comment by gse-cc-git** [comment]
@Jermolene . It works on Windows !
So it has something to do with my Ubuntu install...

**Comment by Jermolene** [comment]
Hi @gse-cc-git great, glad we've been able to track it down. Very weird that you're getting the same problem in all browsers, I've no idea what could be going on. @pmario is a Linux user and may have some ideas?

**Comment by pmario** [comment]
Using your [workflow](https://github.com/Jermolene/TiddlyWiki5/issues/3039#issuecomment-389091350) I can verfy, that ther is a problem with ubuntu 18.04. .... I'll have a closer look.

**Comment by gse-cc-git** [comment]
Hi @Jermolene, I'll try later on another distrib (Manjaro). Could be the Java install...

**Comment by pmario** [comment]
Definitely no Java problem. ..

**Comment by pmario** [comment]
It seems ubuntu knows the `.bib` extension and returns `text/x-bibtex` instead of `application/x-bibtex` ... that we know. .. I'll make a short test

**Comment by pmario** [comment]
found it

**Comment by pmario** [comment]
uups ... @diego898 ... we have hijacked your issue for "something completely different :)".  Sorry about that!

**Comment by kookma** [comment]
@diego898 
Look at the https://groups.google.com/d/msg/tiddlywiki/85LZZO0Wgnk/0F6NxoDECAAJ

It seems Jeremy also believes to keep the bibtex plugin. I have asuggestion

- bibtex tiddler show few biblio data in the text field through transclusion [no need to open the tiddler to see what it is]. For example title, author and year

I saw you started a PR and I hope you could finalize it, hopefully this can be reflected in TW 5.1.20

**Comment by diego898** [comment]
hey @kookma - I haven't yet started a PR for this as the plan is still to migrate to the text-slicer (eventually). I was able to make my own local changes as detailed above, however, to help me out during the wait. As far as having bibtex tiddler show the biblio data, I think you could accomplish that by having something tagged with the viewtemplate that is something like:

```
<$list filter="[all[current]tag[biblioEntry]]">

* {{!!bibtex-title}}
* {{!!bibtex-authors}}
...

</$list>
```

**Comment by kookma** [comment]
@diego898 
Thanks Diego!
I think this is a simple solution!

Regarding the `biblioEntry` tag, do you add this manually? I use Sciencedirect to search articles and export them as .bib file. I also use Mendely.

I created a tiddler like below to show some information of bibtex file.

```
<$list filter="[all[current]has[bibtex-title]]">

* ''DOI'': {{!!bibtex-doi}}
* ''Published'': {{!!bibtex-journal}}, {{!!bibtex-year}}
<div style="font-size:1.3em;font-weight:700;text-align:center;padding:10px;"> <$text text={{!!bibtex-title}}/></div>
<div style="font-weight:500;text-align:center;color:blue;"> <$text text={{!!bibtex-author}}/></div>

!! ''Abstract''
><$text text={{!!bibtex-abstract}}/>

''Keywords'': {{!!bibtex-keywords}}
</$list>
```

**Comment by diego898** [comment]
> Hi @diego898 my plan is to migrate to using the text-slicer plugin to import BibTeX documents. Text-slicer is evolving to be a generic engine for importing XML data.
> 
> In the meantime, you'll probably find experimenting with the existing BibTeX plugin code to be a lot easier, and I'd encourage you to go ahead. The real challenge is finding a useful set of behaviours that work for as many people as possible; the implementation is kind of a detail :)

Hey @Jermolene , just checking on the above with regards to the text-slicer plugin?

**Comment by diego898** [comment]
Hey @Jermolene - any update on this issue + text-slicer? Or is there a more appropriate issue?

**Comment by Jermolene** [comment]
Hi @diego898 no direct progress, I'm afraid. Glad to know you're still interested, this is still something I'd like to tackle.

**Comment by s3r3ndipit** [comment]
As I said [through cross-posting with Mohammad Refnotes plugin](https://groups.google.com/forum/#!msg/tiddlywiki/85LZZO0Wgnk/xCZa5CHSCAAJ), I'm also very interest, and glad to know you're enjoying the tackling of this. ;)

**Comment by pdroalves** [comment]
I'm having the same issue on a Ubuntu installation.

**Comment by pmario** [comment]
@diego898 ... You closed several unresolved issues / feature requests, within a few hours. 

What's the reason?

**Comment by rahulkashyap411** [comment]
> 

Hi @kookma, @diego898, 

I had a small question regarding a modification I want to make in the bibtex parser to show the link to the local file. 
I want to use one of the entrytags to be displayed in the main text as path to an external file. 

I tried changing `$:/plugins/tiddlywiki/bibtex/deserializer.js` where I added a line `fields["text"]="[ext[file|path_to_file]]";` towards the end. However, I couldn't fix the `path_to_file` using the field `bibtex-file` already parsed and present in the tiddler. 

Alternatively, I would prefer that tiddler created by bibtex importer already contains these lines which Mohammad suggested. Could we add a line here to get path to local file as well using `bibtex-file` field; some thing like `* [ext[file|{{!!bibtex-file}}]]` ?

```
<$list filter="[all[current]has[bibtex-title]]">

* ''DOI'': {{!!bibtex-doi}}
* ''Published'': {{!!bibtex-journal}}, {{!!bibtex-year}}
<div style="font-size:1.3em;font-weight:700;text-align:center;padding:10px;"> <$text text={{!!bibtex-title}}/></div>
<div style="font-weight:500;text-align:center;color:blue;"> <$text text={{!!bibtex-author}}/></div>

!! ''Abstract''
><$text text={{!!bibtex-abstract}}/>

''Keywords'': {{!!bibtex-keywords}}
</$list>
```

**Comment by kookma** [comment]
I can not comment on JS side, but the current bibtex parser correctly import the .bib file and text!
After importing a tiddler is created, you can have your own view template with proper code to create a visual link to the local file!

Just my two cents!
