### ISSUE TITLE
Katex plugin does not work with markdown plugin

### ISSUE THREAD

**Issue by somenxavier** [Jermolene/TiddlyWiki5#3045]
I do not know if this issue is yours or from markdown plugin. But I cannot use `$something$` in my markdown tiddlers because it does not display nothing.

**Comment by tobibeer** [comment]
I just read the exact same today. If you search for katex and markdown, thou shalt find an existing issue.

So please use search more, close this one and comment at #2984.

**Comment by somenxavier** [comment]
I did not find it, obviously, Sorry

**Comment by tobibeer** [comment]
@somenxavier: no worries. Happens to all of us. ;-)

**Comment by somenxavier** [comment]
So what's a solution.Will you upgrade the plugins for working together?

**Comment by diego898** [comment]
Hey, I just bumped #2984 to continue this discussion - should this issue be closed?

**Comment by somenxavier** [comment]
This is a duplicated to this bug
