### ISSUE TITLE
Proposal: replace macro call from $:/core/ui/TagTemplate with filter

### ISSUE THREAD

**Issue by angelodag** [Jermolene/TiddlyWiki5#3053]
In $:/core/ui/TagTemplate the list of the tiddlers tagged with a specific tag is created using the call:

`<$macrocall $name="list-tagged-draggable" tag=<<currentTiddler>>/>
`

On the other end, the tiddlers displayed in the resulting list (accessible clicking on the tag pill) are NOT draggable.
Same result may be achieves using a standard filter:

```
<$list filter="[all[current]tagging[]]">
<$link><$view field="title"/></$link>
</$list>

```
This approach also gives room for improvement i.e. customizing the filter to remove some results:

```
<$list filter="[all[current]tagging[]!tag[excludeLists]]">
 <$link><$view field="title"/></$link>
</$list>

```

**Comment by pmario** [comment]
```
{{xx||$:/core/ui/TagTemplate}}
```

I'm not sure what you tested. but for me, they are dragable. If you use the code above, and tag some tiddlers "xx" the resulting list is dragable. 

So I don't see the need to change `$:/core/ui/TagTemplate`

----------

`<$list filter="[all[current]tagging[]!tag[excludeLists]]">`

There was a reason, why we removed the `excludeLists` tag known from TWclassic. ... It cause way more problems than improvements.

**Comment by angelodag** [comment]
Hello Mario, 
thanks for the answer, I did check again and found that on Chrome/Chromium it works but it does not work on Internet Explorer (11), personally I use the HTA 'hack' and also in this case the dragging does not work.

Sorry I did not test with multiple browsers.

**Comment by pmario** [comment]
Did your proposal work with IE11? ... just to be sure.

**Comment by pmario** [comment]
Because, if it would work, it would be a strong reason to change it.
