### ISSUE TITLE
I can't save to TiddlySpot anymore!

### ISSUE THREAD

**Issue by morosanuae** [Jermolene/TiddlyWiki5#3061]
Hello,

Is there a new problem with the TiddlySpot server? I can't save my edits online anymore. I didn't make changes for a couple of weeks so I don't know when the problem appeared.

I tried many variants: the old and the new Firefox browser, Chrome, The old (v5.1.14) and new (v5.1.15) TiddlyWiki. Nothing seems to work. The save button remains red all the time.

Does anyone knows what's going on and can post a quick response/solution?

**Comment by morosanuae** [comment]
Suddenly it started working again. I didn't do absolutely anything. I leave this issue open for the moment, maybe someone knows what's happening.

**Comment by tobibeer** [comment]
You need to make sure to either upload from localhost (download first) or the same protocol. 

Since tiddlywiki.com is now on https you cannot upload directly to tiddlyspot anymore it seems

If you can confirm this, consider closing this issue (or help update the docs where needed)

**Comment by morosanuae** [comment]
Now it works but I don't know the cause of this issue. It seems that is happening from time to time and it's not related to the protocol or incorrect configuration. I've done this many times and it worked without issues. I'm very familiar with the configuration procedures and I didn't change anything for a long time. I heard from others that sometimes the process of saving takes a long time to complete (~1min). Maybe is a server problem after all.
