### ISSUE TITLE
Positional arguments in tiddlywiki command

### ISSUE THREAD

**Issue by cpjobling** [Jermolene/TiddlyWiki5#3084]
I'd like to specify my username when starting up the TW5 server but the arguments are positional so it's not easy if that's all I want to define.

From [ServerCommand.html](https://tiddlywiki.com/static/ServerCommand.html)
```
tiddlywiki --server <port> <roottiddler> <rendertype> <servetype> <username> <password> <host> <pathprefix>
```

I'd like:
```
tiddlywiki --server --username='Chris Jobling'
```
because I'll never remember the arguments that have to precede `<username>` in the positional command.

**Comment by inmysocks** [comment]
For a plugin I made a way to load settings from a json file instead of giving 8 command line arguments. I like that way much better but I am not sure how other people feel about it.

**Comment by pmario** [comment]
@Jermolene -- Can be closed. `--server` command is deprecated. [--listen has named parameters](https://tiddlywiki.com/#ListenCommand).

**Comment by Jermolene** [comment]
Thank you @pmario
