### ISSUE TITLE
no tag for 5.1.15

### ISSUE THREAD

**Issue by buggyj** [Jermolene/TiddlyWiki5#3085]

**Comment by sukima** [comment]
Looking at the git history I think the commit associated with 5.1.15 is https://github.com/Jermolene/TiddlyWiki5/commit/54b1e284fa323968b6d8e49ad5c2344627d8ce3b

**Comment by Jermolene** [comment]
Aargh that’s really annoying, and entirely my fault; I missed out a step of the release process.

Is it possible to retrospectively tag in a clean way?

**Comment by sukima** [comment]
@Jermolene YES:

```
$ git tag 5.1.15 54b1e284fa323968b6d8e49ad5c2344627d8ce3b
$ git push --tags
```

**Comment by Jermolene** [comment]
Thanks @sukima, I've performed those commands.

Annoyingly, I think there should have been a "v" before the version number:

```
$ git tag v5.1.15 54b1e284fa323968b6d8e49ad5c2344627d8ce3b
```

But, what I don't understand is why there's now **two** 5.1.15s listed, one with a "v" and one without:

https://github.com/Jermolene/TiddlyWiki5/tags


<img width="1045" alt="screenshot 2018-01-09 20 15 33" src="https://user-images.githubusercontent.com/174761/34741253-e8c1daae-f579-11e7-8999-7e0f9b018813.png">

**Comment by sukima** [comment]
@Jermolene try this to fix the troubles:

```console
$ git tag -D 5.1.15 # remove tag from local repo
$ git push origin :5.1.15 # remove tag from GitHub
$ git tag -D v5.1.15 # remove tag from local repo
$ git push origin :v5.1.15 # remove tag from GitHub
$ git tag v5.1.15 54b1e28
$ git push --tags
```

**Comment by Jermolene** [comment]
Thanks @sukima. Running the first command gives this error:

```
error: unknown switch `D'
```

`git --version` reports `git version 2.14.3 (Apple Git-98)`

**Comment by buggyj** [comment]
maybe that on windows - ie case insensitive

**Comment by sukima** [comment]
@Jermolene My fault it is lowercase `-d`.

**Comment by Jermolene** [comment]
Many thanks @sukima @buggyj; everything seems to have worked.
