### ISSUE TITLE
Update KaTeX version in the plugin

### ISSUE THREAD

**Issue by yzaretskiy** [Jermolene/TiddlyWiki5#3086]
The KaTeX version currently available through the corresponding plugin is lagging behind the current official KaTeX version. For instance, currently KaTeX can parse the `\underbrace{}` command, while the plugin cannot.

**Comment by Jermolene** [comment]
Thanks @yzaretskiy. I've updated to v0.9.0-alpha2 in a88e28c and uploaded a new prerelease you can try at https://tiddlywiki.com/prerelease/plugins/tiddlywiki/katex. Let me know if you run into any issues.

**Comment by yzaretskiy** [comment]
Thank you, @Jermolene! Seems to be working great! What is the best way to install it in my own TiddlyWiki?

**Comment by Jermolene** [comment]
Thanks @yzaretskiy you can drag and drop the plugin tiddler `$:/plugins/tiddlywiki/katex` from the link above to your own wiki.
