### ISSUE TITLE
Saving issue (dirty state mechanism)

### ISSUE THREAD

**Issue by morosanuae** [Jermolene/TiddlyWiki5#3090]
Hello,

One thing bothers me when working with TiddlyWiki. The save button becomes red (indication of dirty state) and remains that way in the following cases:
- When I open the editing state of a tiddler but I don't make any modifications (discard changes) --> **no need to save**.
- When I create a tiddler by mistake and delete it without modifications which causes it to be deleted --> **no need to save**.

This leads to unnecessary saves or reloading to get rid of the incorrect "dirty state" indicator.

Can this behavior be improved, so that the save button activates (dirty state) only when modifications are done or the tiddler is actually created?

Thanks.

**Comment by Jermolene** [comment]
Hi @morosanuae apologies for the late response

At the moment the dirty state is triggered whenever the tiddler store is modified; there is no attempt to deduce that two consecutive changes cancel one another out. We absolutely could enhance things to try to handle those situations, but I'd be very conscious that a fault with that logic might lead to a user edit erroneously failing to trigger the dirty state.
