### ISSUE TITLE
Allowing .dat site linking support in a Tiddler

### ISSUE THREAD

**Issue by PepperBrooks** [Jermolene/TiddlyWiki5#3103]
I am attempting to link an external .dat site (ie dat://...) in a tiddler but it doesn't seem to allow it. The link is being pushed back to the local file (ie file://C:/...) much like a bad external link which I assume it is being treated as.

**Comment by pmario** [comment]
It should work with `[ext[dat://04845ß324985ß32485]]` ... but it will only make sense, if you use the beaker browser. Major browsers don't understand the dat:// protocol

**Comment by PepperBrooks** [comment]
Perfect appreciate it, and totally understand on the Beaker deal. Thanks

**Comment by pmario** [comment]
Can you please close the issue?

**Comment by rmunn** [comment]
@Jermolene - This issue is over two and a half years old and the original poster is satisfied that it's resolved. Can be closed.
