### ISSUE TITLE
Recently viewed tiddlers list (history)?

### ISSUE THREAD

**Issue by morosanuae** [Jermolene/TiddlyWiki5#3110]
Hello,

is there a simple way to create a list of recently viewed (not modified!) tiddlers, similar to the browsers history? I know the current limitations of JSON handling in TW that "forbid" the access to "$:/HistoryList" tiddler. I'm interested in a simple solution (out-of-the-box) if there is one.

Thanks.

**Comment by pmario** [comment]
If you have a closer look at the [TW ControlPanel](https://tiddlywiki.com/#%24%3A%2Fcore%2Fui%2FControlPanel%2FSettings%2FNavigationAddressBar:%24%3A%2FControlPanel%20%24%3A%2Fcore%2Fui%2FControlPanel%2FSettings%2FNavigationAddressBar): NavigationAddressBar you can change the setting about URL handling, which allows you to use the browser back and forward buttons.

**Comment by morosanuae** [comment]
Hi @pmario and thanks for the answer. 
I know about that feature but is not exactly what I'm looking for. 
So I guess that a simple solution for this doesn't exist currently.
Thanks.

**Comment by Jermolene** [comment]
Hi @morosanuae it would certainly be useful if we could expose the history usefully. If we did, we might want to also extend the format with a timestamp, so that we can e.g. introduce a filter for tiddlers visited in the last 'n' hours.

Anyway, unless we have a concrete proposal perhaps this can be closed?

**Comment by morosanuae** [comment]
Hi @Jermolene that's exactly what I'm looking for, to be able to create a list of tiddlers visited in the last 'n' hours/days etc. This is would be a vital feature for me.
I'll close it for now and maybe I'll think about a concrete proposal.
