### ISSUE TITLE
Fonts & International Reach

### ISSUE THREAD

**Issue by TiddlyTweeter** [Jermolene/TiddlyWiki5#3111]
Discussing an on-line keyboard design here: https://groups.google.com/forum/?hl=en-GB&pli=1#!topic/tiddlywiki/C76L0ro8jS0 An issue that came up is font support. 

I was wondering if TW could (1) document better how to support non-european languages (2) maybe an access system to Google web fonts, that solve many of the issues.

Just thoughts
Josiah

**Comment by pmario** [comment]
> ... access system to Google web fonts, that solve many of the issues.

And ping google everytime I use TW with their font? ... Not my real intention!

I install my fonts locally, or I use what's already installed with the OS. .. IMO much less problems.

**Comment by pmario** [comment]
> ... access system to Google web fonts, that solve many of the issues.

And ping google everytime I use TW with their font? ... Not my real intention!

I install my fonts locally, or I use what's already installed with the OS. .. IMO much less problems.

Onscreen keyboards are part of the OS ... IMO no need to invent the "keyboard" again

**Comment by TiddlyTweeter** [comment]
Ciao @pmario 

Since the developer is switching direction towards a more modest editor addition I may close the issue.

You are right about the OS keyboard and I agree its mad to lumber TW with replicating that for the sake of it. BUT in my mind was something else: providing online keyboards to properly _support the many, many edge cases that OS don't support out-of-the-box_.

These have great utility for anthropologists & linguists.
