### ISSUE TITLE
Operators work inconsistently

### ISSUE THREAD

**Issue by Skeeve** [Jermolene/TiddlyWiki5#3117]
Please compare the descriptions of the parameter of the "sort" and "each" operator. They both state:

    F = the name of a field, defaulting to title

Nevertheless, the output of these tiddlers is different if you put it into a "New tiddler":

    <$list filter="[[New Tiddler]] [[test]] +[sort[]]">
    
    </$list>
    ----
    <$list filter="[[New Tiddler]] [[test]] +[each[]]">
    
    </$list>

"each" will silently drop "test" as it is not existing and thus has no real "title" field, while "sort" will happily sort "test". "sort" will even do it when you call it as "+[sort[title]]".

We should resolve inconsistencies like this.

My PR #3116 doesn't help much in this inconsistency, as it treats "each[]" and "each[title]" differently.

My Proposal is to either define that each non-existing tiddler has  a title field (like "search" does) or that they don't in which case we should treat any "operator[]" differently than "operator[title]".

**Comment by Skeeve** [comment]
Please note that if we do treat "sort[]" differently than "sort[title]" we get confusing results.

As "sort[]" would take the title while "sort[title]" would result in an empty string, we would get the nonexisting tiddlers at the beginning in a (possibly) random order.

I do not think that this is a good idea. So my vote is to state that each tiddler has a title field by definition.

**Comment by Skeeve** [comment]
solved with merging #3124

**Comment by TheDiveO** [comment]
Just got bitten by the old `each` behavior, then checked the repo code of the each filter and found 5.1.16 fixes this using the `value` suffix, which is great. Unfortunately, the `value` suffix isn't documented in the each operator documentation.
