### ISSUE TITLE
Feature request: vars widget should allow for filters

### ISSUE THREAD

**Issue by diego898** [Jermolene/TiddlyWiki5#3120]
I like making use of the vars widget, but I think it would be more useful if we could also assign filters directly. Currently we do: `<$vars myVariable="literalString">`, we could perhaps also add: `<$vars myVariable:filter="[filterString]">`. I know Evan's `formula-vars` widget lets use filters directly.

**Comment by Skeeve** [comment]
Why not, in order not to have to introduce suffixes for variable names:

<$var $filter:myVariable=…

BTW: Nice to see that my LetWidget Proposal (http://tiddlystuff.tiddlyspot.com) made it through as a VarWidget.

**Comment by Jermolene** [comment]
If you want to be able to assign the results of evaluating a filter to a variable you can use the 'set’ widget with the 'filter’ attribute.

If you want a more concise syntax for that operation then we would explore adding a wiki parser rule for it, and probably not extend the generic widget syntax in this way.

**Comment by Skeeve** [comment]
I think @Jermolene is right. After all it can become very long, when you have more than one filter.

**Comment by Jermolene** [comment]
Hi @diego898 can this be closed?

**Comment by diego898** [comment]
yes thank you for the discussion
