### ISSUE TITLE
"Title" IS an index - Can it be easier to create & enumerate?

### ISSUE THREAD

**Issue by TiddlyTweeter** [Jermolene/TiddlyWiki5#3130]
This emerged from a discussion on GG at [issue](https://groups.google.com/forum/?hl=en-GB&pli=1#!topic/tiddlywiki/_BaIcxNtqFw) called: "Auto-Enumeration. I have no idea how." It was best addressed at: [answer](https://groups.google.com/d/msg/tiddlywiki/_BaIcxNtqFw/CW-fAQqwCAAJ)

The discussion highlighted what we already know: 
1. that creating new tiddlers requires that Titles are unique. THAT seems unnecessarily strict. Surely there can be detection of the "title" of the import and some options on import? Like auto-create "title"?

2. if an imported JSON of Tiddlers lacks unique titles the import will fail.

3. if an imported JSON of Tiddlers has unique titles that are already in the TW there are conflicts that can lead to unannounced overwrites.

4. though tiddler Titles ARE the INDICES within TW the default numbering mechanism doesn't produce numbers that sort well. There is no option to PAD the names of imported Tiddlers so they form something that corresponds to a "normal index number" (if you need that). So, for instance, you get "Tiddler 4" and "Tiddler 4000", NOT "Tiddler 0004" and "Tiddler 4000" which would, I think work more intuitively when you using TW like a flexible data repository.

Maybe this been discussed before? Hard to see how it couldn't have been. But I couldn't find direct discussion or other issues on it. Apologies if its being handled already.

**Comment by Jermolene** [comment]
Hi @TiddlyTweeter I think there's several distrinct issues here. I'd prefer to close this and open new issues for each specific issue, if they are actionable.

* Extend the import mechanism to warn and provide options for handling clashing or missing titles (I'm also interested in this)
* Extend the JSON tiddler format to allow tiddlers without titles, automatically generating the required titles
* Make it easier to sort tiddler titles by a numeric suffix

**Comment by TiddlyTweeter** [comment]
Ciao @Jermolene. Fine with me. I agree with all your points. 

I'm not quite sure how to proceed. You want me to post those three again as issues? I'm not up to PRs yet. What's the easiest way forward? 

Once you reply I'll close the issue.

**Comment by Jermolene** [comment]
> I'm not quite sure how to proceed. You want me to post those three again as issues? I'm not up to PRs yet. What's the easiest way forward?
> 
> Once you reply I'll close the issue.
> 
These features are all fairly obvious so I'm not sure that it's necessary to create tickets for them. But it might be worth reviewing the existing tickets to see if there is already one covering improvements to the import process.

**Comment by pmario** [comment]
The [bundler-plugin](https://github.com/wikilabs/plugins/tree/master/wikilabs/bundler/tiddlers) contains some functions to modify the default import behaviour. Using `th-importing-tiddler` hook . .... BUT .... 

If the core import function disables an element it is physically removed from the internal structure. So checking / activating the element again will always fail. I think the code responsible is at: NavigatorWidget.prototype.handleImportTiddlersEvent ..

So we would need to change the core behaviour, since a plugin can't fix this atm

**Comment by TiddlyTweeter** [comment]
@Jermolene & @pmario 

Before I close this issue I wanted to comment on Jeremy's points ...

> Extend the import mechanism to warn and provide options for handling clashing or missing titles (I'm also interested in this)

I do really think that would be a helpful addition. 

@pmario's Bundler plugin has some useful settings that ease this issue. Its particularly useful on bulk import.

> Extend the JSON tiddler format to allow tiddlers without titles, automatically generating the required titles

For my practical purposes [Riz's plugin](https://ibnishak.github.io/Tesseract/pluginsandmacros/index.html#Action-JSONtid) does all that I need on naming Tiddlers from JSON's without titles--and also enumerating them.

> Make it easier to sort tiddler titles by a numeric suffix

Regarding that Riz also made a "[natural sort order](https://ibnishak.github.io/Tesseract/pluginsandmacros/index.html#Sortan%20-%20Sorting%20Alpha%20numerically)"  gizmo. I have not tested it.
