### ISSUE TITLE
international compatibility - wikiparser rules for system-tiddlers (syslink.js)

### ISSUE THREAD

**Issue by BurningTreeC** [Jermolene/TiddlyWiki5#3138]
Titles starting with $:/ get treated as system tiddlers

But character-sets like chinese, hindi, russian or arabic used for system-tiddlers, like $:/你好这是个考验 , don't create wikilinks

I've seen that there are character regexes defined in $:/core/modules/config.js

I'd like to propose include the most commonly-used character sets, where chinese is the by far most-spoken language worldwide, followed by **hindi**, english, spanish, **arabic**, **russian**, portuguese, **bengalese** ...

If I add the most common languages that use the latin characters (english, spanish, portuguese, german, french, italian ... ) I'm at ~1.5 billion people (very rough, only counting those mentioned)

Chinese alone ~1.3 billion people
Hindi alone ~0.5 billion people
Arabic alone ~0.29 billion people

If it doesn't break functionality, I think at least covering chinese characters would be justified

**Comment by Jermolene** [comment]
Hi @BurningTreeC

I'd be very happy to see the system tiddler regexps enhanced for compatibility with international characters. My only concern would be performance: the parser regexps can obviously have a big impact. Hopefully the regexp can blacklist the characters that can mark the end of a system tiddler, rather than having to whitelist all the characters that can appear in a system tiddler title.

**Comment by pmario** [comment]
>... rather than having to whitelist all the characters that can appear in a system tiddler title.

White-listing imo is impossible for eg: chinese, because it would be the whole character set.

**Comment by BurningTreeC** [comment]
Thank you, i see that it must be blacklisting so that it doesn't slow everything down

Blacklisting now needs another regex approach if I didn't understand it the wrong way

So instead of calling $tw.config.textPrimitives(...including anyletter...) we'd need to call it to just exclude the blacklisted one(s) ...
Please correct me if I'm wrong

**Comment by BurningTreeC** [comment]
> characters that can mark the end of a system tiddler

I have no clue what characters to use/include/look for

**Comment by Jermolene** [comment]
Hi @BurningTreeC the easy one is that whitespace would mark the end of a system tiddler (ie spaces, tabs, newlines etc.), but perhaps there are other characters that should too.

So we'd be looking at something like this (written on a phone, and therefore untested!):

```
/\$\:\/\S+/mg
```

Where `\S` in regexp-speak means “any character other than whitespace”".

**Comment by BurningTreeC** [comment]
Thanks @Jermolene ,
I was trying something like that, but not with \S
would that cover for example: 
$:/systemtiddler$:/systemtiddler
where there's no space between them?
or
$:/system/system tiddler/this is a system tiddler

I tried it in this handy tool: https://regexr.com/
Didn't have luck
