### ISSUE TITLE
How to add new fields to an individual tiddler

### ISSUE THREAD

**Issue by threed777** [Jermolene/TiddlyWiki5#3143]
I am a new Tiddlywiki user and really love this app. I would like to be able to add one or more new fields to individual tiddlers as I create them. I'm not looking to add a field to many or all tiddlers automatically. All I want to do is add a field and assign it a value when I create a new tiddler. It is probably very simple, but I have not been able to find it in any of the help files or online. Please pardon my ignorance. Thanks for any help you could provide for a rookie Tiddlywiki user. Thanks for the great app.

Tim

**Comment by morosanuae** [comment]
Hello Tim and welcome to the community,

Normally I would recommend you to familiarize yourself with the documentation in the first place, but by searching the current documentation just to give you a reference, I realize that even it is indeed a very simple thing to do, the documentation page that contain this info is not that easy to find, as you said. If you search for it by entering "field" or "edit" or "adding fields" you're not gone find anything relevant. The same thing with browsing through the doc chapters also. And believe me, I went trough all this myself in the process of learning the app.

Anyway the doc page that you're looking for is: ["Creating and editing tiddlers"](https://tiddlywiki.com/#Creating%20and%20editing%20tiddlers).
I'll give you a summary:
1. You need to put the tiddler into the "editing" mode by pressing the pencil icon on the tiddler upper toolbar (in the right side of the title)
2. You then scroll down to the bottom of the tiddler (if it is a long one) and you'll see a section for adding fields and their values.
3. You create a field by entering a name into the "field name" and a value into the "field value" then press "add".
That's it. You can modify the value anytime after the creation and you can also delete them.

Good luck!

**Comment by threed777** [comment]
Thank you very much for your help and quick response. That was exactly what I was looking for.
I don't know how I missed that - a rookie indeed!

Best regards,
Tim
