### ISSUE TITLE
Paragraph break should cause new list

### ISSUE THREAD

**Issue by twMat** [Jermolene/TiddlyWiki5#3158]
``` 
#one
#two

#one
```
currently this mashes together the two lists. That ought not be the behaviour, i.e the distance should be kept and the numbering should start anew. This would be consistent with common double (text-)line breaks.

**Comment by Jermolene** [comment]
Hi @twMat 

That behaviour is by design; and matches Markdown's behaviour. The intention is to allow people to make complex lists more readable by inserting blank lines that don't affect the output.

In any case, it's hard to see how we could change this without impacting backwards compatibility.

**Comment by twMat** [comment]
OK guess I'll have to close this then.

But, for the record, I don't agree with the design decision; it is inconsistent with the normal 'line-breaking'. behaviour. And readability is IMO clear enough also in edit-mode... I mean, it basically looks like the rendered result.

More crucially, I don't know how to split lists. My use case is that I quite often take notes in the form of lists and I need to be able to separate them.

**Comment by Plloi** [comment]
Genuinely curious, why are making numbered lists that don't have a header or descriptive text defining what the list is for?

**Comment by twMat** [comment]
@Plloi 
I assume you're referring to that "mid list separation". 

First just; In my request I used `#` rather than `*` just to make clear that the list should start anew after the empty line. In reality I typically don't use numbers in bullet lists.

To answer your question

I'm sure most of us make quick meeting notes or todo/shoppng lists. One note per line is the most convenient format. These are much to improvised/temporary to "deserve" the thought process involved in figuring out headings.  So the simplest visual distinction between two lists is a simple empty line. 

```
-coffe house, Sandra
-post office
--envelopes
--stamps

-milk
-butter
- ...
```
Clear enough for anyone what the things are, without any headings.

E.g quick meeting notes might deserve editing (headings, reorganization etc) *later on*, after the occasion.

I think the underlying problem is that TW is currently designed for *managing* notes, which it is brilliant for, but still not so great for *taking* notes, IMO. Standard TW tools are just too slow/fiddly.

**Comment by pmario** [comment]
>I think the underlying problem is that TW is currently designed for managing notes, which it is brilliant for, but still not so great for taking notes, IMO. Standard TW tools are just too slow/fiddly.

As I wrote in the group for a similar thread. ... If you want to be fast, just don't mess with the formatting at all. .. Use tiddler type: text/plain and you are good to go. ... 

That's simple and fast. Doing the refactoring later.

**Comment by twMat** [comment]
> If you want to be fast, just don't mess with the formatting

Thanks! For this particular issue that is actually a very good idea!
