### ISSUE TITLE
iframe questions

### ISSUE THREAD

**Issue by rubaboo** [Jermolene/TiddlyWiki5#3165]
Why is iframe height set to `600px` in `$:/themes/tiddlywiki/vanilla/base`, and why if I try to set it to auto in my stylesheet, it becomes 150px high?

**Comment by twMat** [comment]
May I suggest you ask this question on the [board](https://groups.google.com/forum/#!forum/tiddlywiki) instead? There are more people hanging around there and this github place is for *actionable* matters concerning the code. Kindly close this thread.

**Comment by rubaboo** [comment]
You are right, @twMat. I thought so myself, right after I hit the Submit.
