### ISSUE TITLE
Hide sidebar by default

### ISSUE THREAD

**Issue by samuelwiechmann** [Jermolene/TiddlyWiki5#3171]
Hey,

I wonder how I can set the right sidebar to be hidden by default.
It seems to works with @Jermolene 's https://tiddlywiki.com/talkytalky/ 
but I can't figure how to recreate that setting.

**Comment by Jermolene** [comment]
Hi @samuelwiechmann the trick is simple but only works with the Node.js configuration: include a tiddler called "$:/state/sidebar" and give it the value "no". You can see an example here:

https://github.com/Jermolene/TalkyTalky/blob/master/2015-06%20GDS/tiddlers/system/sidebar.tid

**Comment by gernert** [comment]
Hi @samuelwiechmann,

For the standalone version have a look at https://tobibeer.github.io/tb5/#Hiding%20The%20Sidebar%20On%20Startup

**Comment by samuelwiechmann** [comment]
As is suspected - too easy to ponder for too long :)
Thank you very much for your quick reply!

**Comment by twMat** [comment]
'nuther trick, for single file TW. No plugins or code:

1. open $:/core/ui/Buttons/save-wiki
2. hide sidebar
3. save

If you use "save storyview" but don't want that saving iddler opened, use its tiddler toolbar > more > open in new window.

**Comment by twMat** [comment]
@samuelwiechmann - It seem you got an answer to your question. Kindly close this thread.

**Comment by twMat** [comment]
@samuelwiechmann - It seem you got an answer to your question. Kindly close this thread.

**Comment by linonetwo** [comment]
Share my solution using startup script https://github.com/tiddly-gittly/itonnote-plugin/blob/master/src/Startup/closeSidebarOnMobile.ts
