### ISSUE TITLE
Confused about Auto-download modified tiddlers, savetrail plugin

### ISSUE THREAD

**Issue by Kaan88** [Jermolene/TiddlyWiki5#3179]
Am I expected to drag and drop an older json file on tiddlywiki to take advantage of this? There isn't a single documentation about this. 

Also 

> Configured correctly, the browser will download the files silently in the background, and they can be used as a backup in case of accidental data loss.

What does this mean in terms of node.js, what should I change? Currently it prompts browser download dialog and doesn't save it on server.

**Comment by Jermolene** [comment]
> Am I expected to drag and drop an older json file on tiddlywiki to take advantage of this? There isn't a single documentation about this.

Yes, to recover an old tiddler just drag and drop the JSON file into your wiki.

> What does this mean in terms of node.js, what should I change? Currently it prompts browser download dialog and doesn't save it on server.

The savetrail plugin works in the browser; it doesn't save files on the server. If you want to use it with the Node.js configuration of TW5 then you'd configure the browser the same as for the single file edition.

**Comment by Kaan88** [comment]
Thank you.

**Comment by Jermolene** [comment]
Thanks @Kaan88 😄
