### ISSUE TITLE
How to reuse current parsers?

### ISSUE THREAD

**Issue by caasi** [Jermolene/TiddlyWiki5#3183]
I have to read and create new tiddlers from another format. Is it possible to reuse parsers in this project?

I tried to import/require `tiddlywiki/core/modules/parsers/wikiparser/wikiparser` but the global variable `$tw` prevents me from using the `WikiParser`.

What should I do if I want to reuse parsers? Or should I give up and create my own plugin to achieve my goal inside the TiddlyWiki?

**Comment by twMat** [comment]
Warmly welcome @caasi  May I suggest you ask this question on the [dev board](https://groups.google.com/forum/#!forum/tiddlywikidev) instead? It's a great question but given how many "issues" we already have, we try to keep this github place for *actionable* matters concerning the code. If you agree, kindly close this thread.

**Comment by caasi** [comment]
@twMat @TiddlyTweeter Wow. Thank you.

I realized that I can import core modules and write my plugin in [ES2015][ES2015] if I stay in the TiddlyWiki system. I will check Flexitype Demos and dev board, and rethink my problem.

[ES2015]: https://tiddlywiki.com/dev/alltiddlers.html#Using%20ES2016%20for%20Writing%20Plugins
