### ISSUE TITLE
LinkWidget should have label attribute

### ISSUE THREAD

**Issue by twMat** [Jermolene/TiddlyWiki5#3195]
Instead of having to write the commonly recurring

`<$link to={{!!title}}><$view field="title"/></$link>`

the linkwidget should have a **label** attribute and with default as the current tiddlers title (just like for its `to` attribute). That way the above expression could be written as

`<$link to={{!!title}} label={{!!title}} />`

...or the super smooth...

`<$link/>`

If there is actual *content* between the link tags, then this takes *precedence* over the label attribute value.

P.S The `<$link/>` syntax resembles the `<$transclude/>` syntax which should positively reinforce understanding.

**Comment by Jermolene** [comment]
Hi @twMat generally, at the widget layer of the design, we favour consistency over expressiveness. In contrast, the next layer up -- the wikitext layer -- we favour expressiveness over all else. So, if you're trying to make a syntax that is designed to be concise it's better to look to a new or improved wikitext rule than to make a special case in the way that widgets are processed. (The "top" layer is user defined macros, which are primarily available to avoid repetitive typing).

**Comment by twMat** [comment]
Much appreciated. Just curious; not 'consistent' with what? HTML?

I'll propose a new wikitext rule as you mention (..by which I assume you mean a core-defined macro).

**Comment by Jermolene** [comment]
> Just curious; not 'consistent' with what? HTML?

Yes (the content of elements in HTML is provided via containment, and never via an attribute).

> I'll propose a new wikitext rule as you mention (..by which I assume you mean a core-defined macro).

I wasn't actually advising a wikitext rule or a macro in this case, just trying to convey the general layering principles. If you can get away with a macro, go for it, but I don't think it'd be the kind of thing for the core: it would probably be harder to document it than to teach people how to write their own such macros when they need them.

**Comment by twMat** [comment]
OK, but I see a real need for a simplification of this mouthful

><$link><$view field="title"/></$link>

It is (1) a very *common* use case and (2) there is a *big risk* that people carelessly use this instead:

><$link>{{!!title}}</$link>

...and unknowingly get unintentional "internal links" ([#1880](https://github.com/Jermolene/TiddlyWiki5/issues/1880)).

These are strong arguments for a core `<<link>>` macro. Specifically:

`<<link "target" "label">>`  where both arguments are *optional* and both default to title - but if there is a *caption* then this takes precedence as label default value.

Reasonable?

**Comment by Jermolene** [comment]
Hi @twMat as you note, part of the problem is that `<$view field="title"/>` (or `<$text text={{!!title}}/>`) is so much clunkier than `{{!!title}}`. I'd love to find a suitable, concise wikitext syntax for plain text wikification.

> `<<link "target" "label">>`  where both arguments are *optional* and both default to title - but if there is a *caption* then this takes precedence as label default value.

It sounds like a useful example/starter macro for people to use as a basis for their own custom macros. I don't think it's suitable for the core because it lacks universality: it's a trivial abbreviation for a common idiom, but one that is only commonly used within templates. Templates generally already contain a bunch of widget-y code, and so it's not clear that it's a net improvement to substitute an opaque macro for some of them.

**Comment by twMat** [comment]
> I'd love to find a suitable, concise wikitext syntax for plain text wikification.

OK, I just posted [this concept](https://groups.google.com/forum/#!topic/tiddlywikidev/JbGKsxOu998) on the boards. I believe it is also very universal. Would love to hear your thoughts on it.

Closing this thread.
