### ISSUE TITLE
Tiddlywiki no longer saves to local file

### ISSUE THREAD

**Issue by Skilly** [Jermolene/TiddlyWiki5#3200]
For some time now I have been using the TiddlyWiki single HTML file to store my personal wiki. I view and edit my wiki by navigating to my linux file on linux via my chrome browser e.g.: file:///home/bob/wiki.html

Upon trying to update my wiki this week, I am no longer able to save locally. Now when I click on the red "Save changes" icon (the image of a tick mark within a circle), a new tab is opened with the following url: blob:null/cdbd9397-ec15-4315-9b6d-ca5456cdfca7 (previously when I clicked the "Save changes" icon, i was prompted for a location to store the changed file and could elect to overwrite the existing one)

I'm not sure if this is a Tiddlywiki issue or a Chrome issue but I expect it will affect multiple TiddlyWiki users, so am logging this issue here. 

I'm wondering whether this is a size issue?

- wiki.html file is 2.4Mb
- ./images/ is 16Mb (referenced from wiki page)
- ./files/ is 37Mb (referenced from wiki page)

My current version of Chrome is _Version 65.0.3325.181 (Official Build) (64-bit)_ running on _Ubuntu Linux 16.04_

**Comment by pmario** [comment]
That's strange. ... Just tested the exact same win10 version ... which works.

**Comment by pmario** [comment]
Tested with ubuntu 17.10, Chrome 65.0.3325.181 ... works too. .... Did you install any chrome addOns that do mess with download managing?

**Comment by Skilly** [comment]
Hi @pmario, thanks for your feedback. No I haven't installed any chrome addOns recently. The only recent chrome related change that I'm aware of is an upgrade to 65.0.3325.181.

For info, I use git to keep track of my TiddlyWiki changes and typically do a new checkin whenever I've added a "chunk" of info to Tiddlywiki. I've reverted to earlier known working versions of my wiki (i.e. restored to an earlier version where "Save changes" did work) using git and even those versions now exhibit the problem

**Comment by sukima** [comment]
If you use Git to track changes you might be interested in running TiddlyWiki with Node as it will save each tiddler as a single file and is far more Git friendly.

**Comment by Skilly** [comment]
Hi @sukima,

I too am able to edit and save a default tiddlywiki page without any problem.

For instance, I have no problem editing and saving the empty wiki downloaded [from this](https://tiddlywiki.com/static/Saving%2520with%2520the%2520HTML5%2520fallback%2520saver.html) link.

Therefore I don't believe this is add-on related. The problem is specific to my one TiddlyWiki instance - it works fine on other Tiddlywiki instances.

**Comment by pmario** [comment]
>Therefore I don't believe this is add-on related. The problem is specific to my one TiddlyWiki instance - it works fine on other Tiddlywiki instances.

Then ... 

 - which TW plugins do you use?
 - Have a look at ControlPanel: Plugins

**Comment by sukima** [comment]
You could try opening up a new `empty.html` tiddlywiki then dragging your HTML onto it and importing. See if an upgrade changes anything.

**Comment by sukima** [comment]
Next steps:

1.  Download a fresh `empty.html`
2.  Verify the problem **does not** happen with the fresh `empty.html`
3.  Drag the broken html onto the running `empty.html`
4.  Screen shot or copy/paste the import list. Then import.
5.  Verify problem **does** exist.
6.  Begin deleting tiddlers one by one in the list of imports until the problem either resolves or you've deleted enough sensitive tiddler that you are comfortable uploading it and providing a link here for others to experiment with.

**Comment by Skilly** [comment]
@sukima I followed your earlier advice and upgraded my Tiddlywiki from version 5.1.13 to 5.1.15. I'm thrilled to report that much to my surprise, this worked and I can now save successfully to my local folder. (I can't think of a valid explanation to explain the behavior that I've experienced, however at this stage I'm relieved to have my fully functioning wiki back)
