### ISSUE TITLE
Ctrlpanel - style proposals (1)

### ISSUE THREAD

**Issue by twMat** [Jermolene/TiddlyWiki5#3201]
See

http://5.1.16proposals.tiddlyspot.com/

Toughts? Some of them are on issues I've brought up before.

**Comment by pmario** [comment]
IMO duplicate of: https://github.com/Jermolene/TiddlyWiki5/pull/1954 ... which also handles right sidebar: tools: palette and theme buttons.

**Comment by twMat** [comment]
Aha! Agree fully. Closing.
