### ISSUE TITLE
112 PRs. Some 4 years old.

### ISSUE THREAD

**Issue by twMat** [Jermolene/TiddlyWiki5#3202]
@Jeremy

It may seem that this should be a privately written email but it concerns exactly *everyone* in here.

I don't think it will be "fun" to read this but it is for constructive purposes and I do have a constructive suggestion.

Jeremy, you know I appreciate your efforts with TW - but it is frankly saddening to see so much well meaning effort from people that is just ignored by you. At least it appears so. Excellent and ready made PRs that *don't even get a comment* as to why they're not accepted. For *years and years*!

From 1000 TW users, I'd estimate that *one* is a contributor. Maybe even less. They are *rare*. But looking at the PR list, there are names that seem to abandon ship after a while. Real coders! I have no idea why super contributors like @tobibeer , @felixhayashi , @aelocson , @matabele have basically disappeared, not to mention @cdent or @simonbaird or other heavy weights whose names escape me. They might be away for totally other reasons but I know from experience that when it concerns *ones own* PRs - made from hours of effort - the feeling is not really 'sadness', it is more like being insulted.

...but "insulting" is definitely NOT a trait of the gentleman leading our beloved TW project!

There's a big disconnect here and it is this:

The problem is NOT that you don't merge PRs or that you don't give comments. The problem IS

- ...that you don't do those things AND
- don't allow anybody else to do it either AND 
- in spite of others clearly being both willing and competent to help out!

That IS frustrating.

I must assume the situation has, understandably, arisen from your need to be in control.

...so here is a new angle on this that might both let you be in control *and* let others help out;

Open up the *pre-release* edition for multiple curators with full merging rights. You would still have the final say for the actual release but/and any decision to reject a tried-out PR will be much more informed because things have been tried out. 

Such tried-out PRs are 'sent back' to be closed/rejected PRs but they are by then much more likely to have an explanation for the decision because the decision is more of a collective process even if you have the final say. Effectively, the pre-release will be more of a lab-version in an intentional sense than then current variant where we incidentally discover mistakes. Actually, I think it might even engage the community a bit more; "Try out these potential features and come with input. They might not make it." 

**Running through the PR list ought to be part of the workflow before every upgrade**, not least to give encouragement and affirmation to contributors. This version of a pre-release would probably make this possible.

(Besides, the current prerelase need some cleaning up of some oddities that seem to hang on but never make it to the official release. These pieces should probably also be put elsewhere.)

Of course, this proposal assumes there are competent individuals who really would be willing to participate as curators - yes guys, I'm talking to you, but rather than me mentioning any names it is probably better to let you step up and announce yourself.

Thoughts? Good/bad? ...or I mean; Better/worse than status quo? 112 PRs, some 4 years old say it's time for *some* kind of change.

...

I write this because I absolutely love TW. If I didn't care, I wouldn't have spent over two hours formulating this, including pondering whether posting it publicly is better for the project or not. I hope it is.

**Comment by Jermolene** [comment]
Hi @twMat indeed, the PR/issue backlog is embarrassing. #3114 outlines my proposed response: to transfer the TW5 repo to the TiddlyWiki organisation so that we can authorise other people to triage/process PRs/issues.

**Comment by twMat** [comment]
Aha! (posted during my Kenya trip!) That makes me really happy! 
Ok, continuing over there.
Closing.
