### ISSUE TITLE
[docs+code] Clean out TiddlySpace

### ISSUE THREAD

**Issue by twMat** [Jermolene/TiddlyWiki5#3218]
Recently someone noted that there was a reference on tw.com to the shut down TiddlySpace service. I can't find it as an issue here so posting this now. Actually, if you do a search on tw.com there are multiple tiddlers that should probably be taken care of but the most problematic one is the [TiddlySpace ](https://tiddlywiki.com/prerelease/#TiddlySpace) tiddler which says the service is active.

**Comment by Jermolene** [comment]
Thanks @twMat
