### ISSUE TITLE
export tiddler with map getting error can't read property 'contains' of undefined

### ISSUE THREAD

**Issue by dipenpatel235** [Jermolene/TiddlyWiki5#3221]
Hello..
i have created tiddly map but getting error same as below screenshot.

then i have try to check from your link with tiddlymap so in that also getting same error.
below is screenshot of that.

![screenshot 2018-04-24 12 01 27](https://user-images.githubusercontent.com/8135097/39169983-6fd333aa-47b7-11e8-80c0-c9f0c3205d13.png)

Thanks

**Comment by felixhayashi** [comment]
Hi @dipenpatel235 this is most likely not TiddlyWiki related. Please post such issues at the TiddlyMap repo: https://github.com/felixhayashi/TW5-TiddlyMap/issues.

Does this error occur just by visiting tiddlymap.org? In this case, I assume it is an issue with your browser or one of your plugins.

**Comment by dipenpatel235** [comment]
ok..
u can close this

Thanks

**Comment by Jermolene** [comment]
Thanks @dipenpatel235
