### ISSUE TITLE
sidebar retain causes sidebar not to show

### ISSUE THREAD

**Issue by BurningTreeC** [Jermolene/TiddlyWiki5#3223]
test: tiddlywiki.com and tiddlywiki.com/prerelease - click the hide-sidebar button and click it again -> sidebar doesn't show content

only happens if retain="yes"

**Comment by BurningTreeC** [comment]
only happens below a certain interval between the two clicks - I guess the animation duration?

**Comment by BurningTreeC** [comment]
confirmed: if the animation duration is 10ms then I can double click fast and the sidebar content shows - with 5000ms i can click, wait 3 seconds and click again - it doesn't show

**Comment by pmario** [comment]
>only happens if retain="yes"

 Which retain?

**Comment by BurningTreeC** [comment]
The retain in the $:/core/ui/PageTemplate/sidebar - there's only one reveal and one retain ;)

**Comment by BurningTreeC** [comment]
@pmario - If I set the animation duration to say 4000 and I close the sidebar and open it again within those 4 seconds then I can see what happens in slow-mo ... there gets a check executed at the wrong time returning a wrong value - the content appears and then disappears

all this isn't visible with 400ms

**Comment by pmario** [comment]
I can confirm the behavior ... with 400ms ... Just make a double click.

**Comment by pmario** [comment]
IMO it's an animation problem. ... The fade-out of the sidebar isn't finished yet. So somewhere is a state problem.

**Comment by pmario** [comment]
For me animate=yes or no makes the difference.

**Comment by pmario** [comment]
Yes. 5.1.15 has the same problem.

**Comment by Jermolene** [comment]
Thanks, in that case, I won't delay 5.1.16, but I appreciate anything you can do to chase this down.

**Comment by BurningTreeC** [comment]
@pmario - I'm not sure if it's retain or animate. It has something to do with the animation but I thought to have that wrong behaviour also with retain

@Jermolene - sorry for the late issue, found it today

I was looking at reveal.js - I don't get which state check it is but I was thinking that it must be put in a callback somewhere?

**Comment by sukima** [comment]
The reason `retain` makes a difference it because it drives the animation logic of the content (`this.updateState()` will animate, `this.refreshSelf()` does not, if I am reading the code right):

https://github.com/Jermolene/TiddlyWiki5/blob/75709d745f9d5fe846412550c788100f5a2323d3/core/modules/widgets/reveal.js#L181-L186

This suggests that there is a race condition in the `open` and `close` animations. However, after much `git grep` I was unable to finds where the `open` and `close` animations are defined!!!

**Comment by sukima** [comment]
I also wrapped this line in a `requestAnimationFrame` to see if that was a cause:

https://github.com/Jermolene/TiddlyWiki5/blob/75709d745f9d5fe846412550c788100f5a2323d3/core/modules/utils/dom/animator.js#L38

Unfortunately this did not change anything.

**Comment by BurningTreeC** [comment]
... and I believe I found a fix

**Comment by BurningTreeC** [comment]
... at that point in all cases the state should already be "sidebar closed" - the close animation has already been performed. if there the state is "sidebar open" it means that in the meantime there was another click

**Comment by BurningTreeC** [comment]
@Jermolene @sukima @pmario - what do you say?
