### ISSUE TITLE
Editor Bug

### ISSUE THREAD

**Issue by dsheil** [Jermolene/TiddlyWiki5#3225]
I am using the NodeJS version of tiddly version 5.1.15

The text editor has almost no room vertically, if I resize the the textarea it disappears behind the iframe.

Should be fixable by making the iframe resizable and then have the textarea expand to fill space.
Unfortunately all the style for the textarea is done via the style attribute and it looks like that's filled by javascript which means I can't just use my own CSS to fix the problem.

**Comment by pmario** [comment]
The edit-area does automatically adjust to your content. 

You may have codemirror plugin enabled. So at the beginning it is only 1 line. ..

**Comment by pmario** [comment]
@Jermolene IMO can be closed. 

OP user seems to be gone and did not give more feedback. For me it seems CodeMirror has been used, so there is only 1 line at the beginning.

**Comment by Jermolene** [comment]
Thank you @pmario
