### ISSUE TITLE
Macros don't accept foreign characters in param name

### ISSUE THREAD

**Issue by twMat** [Jermolene/TiddlyWiki5#3229]
```
\define foo(bär) $bär$

<<foo x>>
```
The output is `$bär$` instead of the expected `x`

It seems neither of the German/Swedish characters `å ä ö ü` are accepted and I find no info on this in the docs.

The characters *do* work in parameter fallbacks (i.e `\define foo(aa:"bär") $aa$` )

**Comment by Evolena** [comment]
https://tiddlywiki.com/#Macro%20Definition%20Syntax states that:

> A param-name is a sequence of letters (A–Z, a–z), digits (0–9), hyphens (-) and underscores (_).

**Comment by pmario** [comment]
macros are like "lego blocks". They should be as generic as possible. For me it would be easy to type ö,ä because I have a German keyboard configuration. But to create `å` I need to copy/paste it from your post, because I don't know how to create it. 

So imo we should not change this behavior.

**Comment by twMat** [comment]
@Evolena , thanks, you are right.

@pmario , thanks for input but if we really want it "as generic as possible" then it would of course accept anything that we type or paste there. The current restriction is after all arbitrary.

Looking at the docs, the "arbitrariness" is particularly obvious when noting that the *macro name* and the macros *parameter name* have **different** such character restrictions! That is far from evident for an end user.

**Comment by Jermolene** [comment]
> BTW, it would be convenient if there was a common term for the permitted character set (which of course, should ideally be only one) so that we can refer to it more easily. Does anybody know of any such term? I figure it should be frequent in coding

In some situations we might write things like "upper and lower case alphanumeric plus dash and underscore", but I think it's probably better for TiddlyWiki docs to be more explicit, because not everybody will be aware of the technical meaning of words like "lowercase" or "alphanumeric".

Can we close this ticket?
