### ISSUE TITLE
is-filter issue with 5.1.16

### ISSUE THREAD

**Issue by pmario** [Jermolene/TiddlyWiki5#3231]
IMO started with: https://github.com/Jermolene/TiddlyWiki5/pull/2982

I'll try to create a PR .... @Jermolene ... We will need a hot-fix for this one.

**Comment by mklauber** [comment]
Can you be more explicit about the issue?  Is it behavior, or performance?

**Comment by mklauber** [comment]
Started work on #3232

**Comment by mklauber** [comment]
Some work at https://github.com/Jermolene/TiddlyWiki5/pull/3240
