### ISSUE TITLE
Sync error issue after temporary tiddlers were created silently

### ISSUE THREAD

**Issue by yuzijie** [Jermolene/TiddlyWiki5#3235]
Hi everyone,

I found that if you create a temporary tiddler with _ActionSetFieldWidget_ or _ActionListopsWidget_, and open it immediately, the server does not recognize it as a temporary one, and try to find a local copy of that tiddler, and therefore generating an error message.

> Sync error while processing '$:/temp/XXX': XMLHttpRequest error code: 404

Try this button:

```
<$button>
<$action-listops $tiddler="$:/temp/TEST" $subfilter="ABC"/>
<$action-navigate $to="$:/temp/TEST"/>
Error Message Generator
</$button>
```

Thanks

**Comment by Jermolene** [comment]
Thanks @yuzijie, fix upcoming.
