### ISSUE TITLE
Editor height bleeds outside iframe

### ISSUE THREAD

**Issue by twMat** [Jermolene/TiddlyWiki5#3237]
![image](https://user-images.githubusercontent.com/4534056/39399159-3f7c6b12-4b19-11e8-93ba-88a02be27f40.png)

seems to come from 
![image](https://user-images.githubusercontent.com/4534056/39399176-93ad692a-4b19-11e8-98ce-c6837b5330e6.png)
(browser inspector image)

setting height to 100px instead of 114px aligns it so there is no bleeding height.

This has been around for quite some time... I believe it started when the editor toolbar was introduced. Ought this be corrected or is there reason for this?

Win10, Chrome and FF.

**Comment by BurningTreeC** [comment]
Hi @twMat , @Jermolene and all others interested

In #3302 I've referenced this issue and I think it could also be somehow related with #3225

This grey bar below the textarea shows up only if the toolbar is shown. Hide the toolbar in the Control-Panel and it's gone.

I think we should just not set +14px if the toolbar is shown and set +14px if it's hidden.

I've tested that on chrome and firefox - and it behaves like on tiddlywiki.com but without that overlapping area

**Comment by twMat** [comment]
Can't believe I've missed this before: If this attribute is set to 100% instead of 100px it adapts to the outer limits set by the iframe, as it should be. (I still don't understand why the iframe is set to specifically 114px but that's another matter and doesn't bother me.)

![image](https://user-images.githubusercontent.com/4534056/61654701-494b9f80-acbd-11e9-84fa-ec4410695704.png)

**Comment by twMat** [comment]
@Jermolene - regarding the post just above this one: I believe this is a low hanging fruit that would take a second to fix and makes for nice optics when 5.1.20 is released.

**Comment by twMat** [comment]
I think this is fixed.
