### ISSUE TITLE
Published v5.1.16 points to v5.1.15 plugin library

### ISSUE THREAD

**Issue by Jermolene** [Jermolene/TiddlyWiki5#3245]
I neglected to update the `$:/config/OfficialPluginLibrary` tiddler when releasing v5.1.16, meaning that it still points to the v5.1.15 plugin library.

I intend to make a quick release of v5.1.17 to fix this issue and the related #3239.

**Comment by pmario** [comment]
webdav PUT-fix and `is` filter should be included too

**Comment by Jermolene** [comment]
OK, I'll have a look.

**Comment by pmario** [comment]
is-filter: https://github.com/Jermolene/TiddlyWiki5/pull/3240
webdav: https://github.com/Jermolene/TiddlyWiki5/pull/3230 ... not yet ready!!

code to be tested with different settings. ... Works for me on windows10 with IIS
https://github.com/pmario/TiddlyWiki5/blob/fix-3231/core/modules/savers/put.js
