### ISSUE TITLE
Sync Error While Processing

### ISSUE THREAD

**Issue by dipenpatel235** [Jermolene/TiddlyWiki5#3247]
Hello,,
i have attached screenshot.
getting error after install twiki5 on own server.

please help me to fix this issue 

![capture](https://user-images.githubusercontent.com/8135097/39572134-ab8215ca-4eeb-11e8-9444-ab97d69a075c.PNG)

Thanks

**Comment by Jermolene** [comment]
Hi @dipenpatel235 do you get the same problem if you run up a new, empty wiki created with `tiddlywiki mynewwiki --init server`?

**Comment by dipenpatel235** [comment]
No..
This issue due to run it behind nginx proxy with below i.e url

https://www.myhostname.com/twiki

**Comment by Jermolene** [comment]
Hi @dipenpatel235 in that case, have you followed these instructions:

https://tiddlywiki.com/#Using%20a%20custom%20path%20prefix%20with%20the%20client-server%20edition

**Comment by dipenpatel235** [comment]
Ok..Thanks..
I will try it and updating u.

Thanks

**Comment by Jermolene** [comment]
Hi @dipenpatel235 did you also set up `$:/config/tiddlyweb/host`? It sounds like there's something broken in the nginx config, but I'm afraid I don't know nginx myself.

**Comment by dipenpatel235** [comment]
did you also set up $:/config/tiddlyweb/host? - No,

actually forget about nginx now..
first thing i want to make it runnig without nginx below url
http://www.myhostname.com:8080/twiki

if above url work without error then i will make it working from nginx.
i have expertise on nginx

did you also set up $:/config/tiddlyweb/host? - No, how to setup that ?

actually forget about nginx now..
first thing i want to make it runnig without nginx below url
http://www.myhostname.com:8080/twiki

if above url work without error then i will make it working from nginx.
i have expertise on nginx

**Comment by Jermolene** [comment]
> did you also set up $:/config/tiddlyweb/host? - No, how to setup that ?

See note 2 here:

https://tiddlywiki.com/#Using%20a%20custom%20path%20prefix%20with%20the%20client-server%20edition

Otherwise, the command you quoted above looks good, so I'm a bit puzzled.

**Comment by dipenpatel235** [comment]
see i have fill details according below screen shot
then i have fire below command in linux server. 
then i have try to open link http://www.myhostname.com:8080/twiki but now working...

![capture](https://user-images.githubusercontent.com/8135097/39624923-cb7a4852-4fb8-11e8-9c50-f8a26da23d18.PNG)

tiddlywiki mynewwiki --server 8080 $:/core/save/all text/plain text/html "" "" 0.0.0.0 '/twiki'

**Comment by dipenpatel235** [comment]
Hello..
finally i make it working without any popup error behind nginx proxy with sub path.
let me share mine setup configuration for loadbalancer / nginx proxy

1. set url in  Host configuration. in that  set url what u want to used.
for example is you want url https://www.mysite.com/twiki 
then paste that same url in hostconfiguration

2. started tiddlywiki server using below command. not need to add prefixpath
tiddlywiki mynewwiki --server 8080  

3.  nginx proxy pass block in nginx.conf file.

        location /twiki {
                proxy_pass http://127.0.0.1:8080/;
        }

Thanks

**Comment by Jermolene** [comment]
Hi @dipenpatel235 great! I'm delighted you've got things working.

**Comment by Bennett-Yang** [comment]
> Hello..
> finally i make it working without any popup error behind nginx proxy with sub path.
> let me share mine setup configuration for loadbalancer / nginx proxy
> 
> 1. set url in  Host configuration. in that  set url what u want to used.
>    for example is you want url https://www.mysite.com/twiki
>    then paste that same url in hostconfiguration
> 2. started tiddlywiki server using below command. not need to add prefixpath
>    tiddlywiki mynewwiki --server 8080
> 3. nginx proxy pass block in nginx.conf file.
>    ```
>    location /twiki {
>            proxy_pass http://127.0.0.1:8080/;
>    }
>    ```
> 
> Thanks

Could you help me with the same problem?
How can I set host configuration if I can not get tiddlywiki work on my server?

**Comment by Bennett-Yang** [comment]
I solved it. Just create a new tid file 'config-tiddlyweb-host.tid' with the content:
```
title: $:/config/tiddlyweb/host
text: https://www.mysite.com/twiki
```
Thanks a lot.
