### ISSUE TITLE
filter operator: listed

### ISSUE THREAD

**Issue by 00SS** [Jermolene/TiddlyWiki5#3248]
<$list filter=[$:/NewTiddler][listed[]]>

</$list>

Gives the error: Filter error: Unterminated regular expression in filter expression

It seems that any forward slash in the input creates this error.

**Comment by BurningTreeC** [comment]
Hi @00SS ,

your filter syntax is not correct, this one should work:

<$list filter="[[$:/NewTiddler]listed[]]">

**Comment by 00SS** [comment]
Thank you.

I apologize for the confusion.

From having an error in a complex macro, in trying to distill the crux of the problem, I posted nonsense here.

After some (many) more hours of confusion, I hope I have identified my own error, as following the below rule seems to lead to a fix.

The problem stemmed from a $list filter where if I am not mistaken, the following applies:

```
VALID : <variable>listed[] 
INVALID: [<variable>]listed[] 

INVALID: $(variable)$listed[]
VALID: [$(variable)$]listed[]

```

**Comment by BurningTreeC** [comment]
@00SS

yes you're right, it's confusing
discovering this is very important if one wants to create more complex macros,
but it's a long way until it gets discovered and memorized

... I think we should add very explicit docs with big letters at an important place
