### ISSUE TITLE
[hint update] Sticky titles do work in chrome

### ISSUE THREAD

**Issue by twMat** [Jermolene/TiddlyWiki5#3249]
The [hint on Sticky titles](https://tiddlywiki.com/#%24%3A%2Flanguage%2FThemeTweaks%2FOptions%2FStickyTitles%2FHint)

reads

>Causes tiddler titles to "stick" to the top of the browser window. Caution: Does not work at all with Chrome, and causes some layout issues in Firefox

But "sticky" does work in Chrome, at least in Win10. (The [bug](https://caniuse.com/#search=sticky) mentioned in CanIUse is not relevant for our application.)

I propose updating this hint because it is a really neat functionality.

**Comment by Jermolene** [comment]
Thanks @twMat it looks like browser support is pretty good now, so I'll remove the note.
