### ISSUE TITLE
links with accents don't work

### ISSUE THREAD

**Issue by somenxavier** [Jermolene/TiddlyWiki5#3250]
This
```
[[El camí més llarg sense tocar terra
|https://gizmodo.com/this-is-the-longest-straight-path-you-could-travel-on-w-1825725532?utm_source=gizmodo_twitter&utm_medium=socialflow&utm_campaign=socialflow_gizmodo_twitter]]
```

does not work:

![captura de pantalla_2018-05-03_16-39-14](https://user-images.githubusercontent.com/89915/39583511-8b7fcbb4-4ef0-11e8-962f-27e54eec7126.png)

**Comment by Jermolene** [comment]
Hi @somenxavier I think that the problem is that you've got an extraneous line break before the vertical bar.

<img width="989" alt="screenshot 2018-05-03 16 08 36" src="https://user-images.githubusercontent.com/174761/39585264-4149ee7a-4eec-11e8-90ab-b458d058a02e.png">

**Comment by somenxavier** [comment]
thanks
