### ISSUE TITLE
Add actions to the RangeWidget 

### ISSUE THREAD

**Issue by twMat** [Jermolene/TiddlyWiki5#3252]
The RangeWidget will be much more useful if it can be made to trigger stuff when it's "knob" is dropped.

A specific use case is when I'm currently dealing with core tiddlers for *metric values*, e.g font-size, story width etc. These tiddlers include **units**, e.g `14px`. The RangeWidget directly edits a field but it only ouputs a number... so it will need several complex steps just to append the "px" to that number and, worst of all, I believe it would require some manual action to do so ..."set the range slider AND then click the button" :-(

**Comment by Jermolene** [comment]
Another idea might be to add an optional new attribute "outputFilter" that would be interpreted as a filter that is provided with the value of the control and yields the value to be written to the tiddler. For example: `outputfilter="[addsuffix[px]]"`

**Comment by twMat** [comment]
>Also, might actions enable triggering different things depending on range value? I.e could an action use the value as input?

I'm guessing TW uses a specific approach to "handle actions" so [this example](https://stackoverflow.com/questions/15195449/html5-type-range-showing-label?noredirect=1) is probably of limited value, but who knows.

**Comment by Jermolene** [comment]
> aversion to non-html attributes

No, the issue we were discussing in #3195 was about how content is "assigned" to a widget: the core, like HTML, uses containment (ie the content of the widget is the collection of child widgets within it), whereas you were proposing that the content be provided in an attribute.

> which is why I made an effort to make this proposal more similar to other TW solutions (compare e.g with checkboxwidget actions)... and I felt 'actions' was a better and more general route.

There's nothing wrong with your proposal; it's a potentially useful extension, as confirmed by @pmario's suggestion for another use case. My proposal is merely a different approach to meeting your original use case.

> Also, might actions enable triggering different things depending on range value? I.e could an action use the value as input?

Yes, just as e.g. the Droppable widget passes variables to its actions.
