### ISSUE TITLE
Make permalink/view also Add to clipboard

### ISSUE THREAD

**Issue by twMat** [Jermolene/TiddlyWiki5#3255]
AFAICT there are only two reasons to click permalink/view; to bookmark or to get a copy of the link to be pasted somewhere. The latter is probably much more frequently used than the former. However, to get a copy of the link you must also take the extra steps to get it into memory.

I propose that clicking permalink/view also copies the url to memory.

**Comment by pmario** [comment]
>I propose that clicking permalink/view also copies the url to memory.

I would like to have a possibility, that permalink and permaview ONLY copy to the clipboard. ... I don't like it, that the URL is changed. .. It actually causes minimal problems for me.

**Comment by twMat** [comment]
>I would like to have a possibility, that permalink and permaview ONLY copy to the clipboard. ... I don't like it, that the URL is changed. .. It actually causes minimal problems for me.

You do state "minimal" but maybe others will chime in if you describe them. Personally I'd also be OK if it was only copied to clipboard because it would be simple to paste into address field for those rare occasions.

**Comment by BurningTreeC** [comment]
@twMat @pmario 

Hi, the part for the permalink button could look like this:

```
title: $:/core/ui/Buttons/permalink
tags: $:/tags/ViewToolbar
caption: {{$:/core/images/permalink-button}} {{$:/language/Buttons/Permalink/Caption}}
description: {{$:/language/Buttons/Permalink/Hint}}

\whitespace trim
\define uriEncodedPermaLink() $(url)$#$(encodedTitle)$
<$button message="tm-permalink" tooltip={{$:/language/Buttons/Permalink/Hint}} aria-label={{$:/language/Buttons/Permalink/Caption}} class=<<tv-config-toolbar-class>>>
<$vars url={{$:/info/url/full}} encodedTitle={{{ [<currentTiddler>encodeuricomponent[]] }}}>
<$action-sendmessage $message="tm-copy-to-clipboard" $param=<<uriEncodedPermaLink>>/>
</$vars>
<$list filter="[<tv-config-toolbar-icons>prefix[yes]]">
{{$:/core/images/permalink-button}}
</$list>
<$list filter="[<tv-config-toolbar-text>prefix[yes]]">
<span class="tc-btn-text">
<$text text=" "/>
<$text text={{$:/language/Buttons/Permalink/Caption}}/>
</span>
</$list>
</$button>
```
... and a setting in controlpanel could disable the tm-permalink message

for the permaview I don't know how to put the url together by just using wikitext... I was almost there with a filter but it was too complicated

**Comment by pmario** [comment]
IMO It needs to be : 

```
\define uriEncodedPermaLink() $(url)$#$(encodedTitle)$
\whitespace trim
...
```

**Comment by BurningTreeC** [comment]
> IMO It needs to be :

\define uriEncodedPermaLink() $(url)$#$(encodedTitle)$
\whitespace trim
...

oh, well - thanks @pmario - I never understood well enough where to put pragmas

**Comment by twMat** [comment]
Good working! Is this even PR ready? :-D

**Comment by pmario** [comment]
I wouldn't support the code as it is. ... I want to have a configuration, where I can decide IF content is copied to the clipboard. ... 

Copying content to the clipboard as a "side-effect" imo isn't proper behavior. So we need a new button or a new icon, that makes it clear, what's going on!

**Comment by AnthonyMuscio** [comment]
Could we simply add a new button that allows "copy permalink to clipboard button". The choice can be made in the ViewTemplate Toolbar or behind more...

I can provide an Icon once I learn how to export the svg images into InkScape.

**Comment by twMat** [comment]
@Jermolene - EXCELLENT!

**Comment by Jermolene** [comment]
Thanks @twMat - you can try it out at https://tiddlywiki.com/prerelease

**Comment by pmario** [comment]
>Thank you! I just tried it and like it! Great idea with the little "Copied!" popup.

IMO it should be "Copied to clipboard!" .. So users actually know, what's going on.

**Comment by Jermolene** [comment]
Hi @twMat @pmario 

> Unchecking both checkboxes makes the permalink button do nothing, but there is no feedback for this when clicking the permalink button. Maybe inactive buttons should be greyed out? Inactivating both checkboxes does mean that one doesn't want the feature so that could toggle a de-activate for the permalink button?

We could switch to a dropdown that offers "copy", "address", "copy+address" as its options. But I don't think the current behaviour is confusing really: if you turn everything off, then everything will be off, is pretty much all that's going on.

> As I've noted before; Checkbox labels in blue text look odd, even if they're links. In this case the linkiness is even odder because they are in italics since they're missing... unless you click one, which makes it normal but the other still in italics. IMO, all Ctrlpanel setting-labels should just be a normal looking black text. If a link is needed, these could be in the form of a little "link symbol" after the label.

Agreed, but this needs to be fixed across all the settings as a separate PR.

**Comment by Jermolene** [comment]
> IMO it should be "Copied to clipboard!" .. So users actually know, what's going on.

Good thinking, I've updated it in 7d0b255
