### ISSUE TITLE
Internal JavaScript Error

### ISSUE THREAD

**Issue by rubaboo** [Jermolene/TiddlyWiki5#3261]
Getting this with the current Github clone.

Internal JavaScript Error
Well, this is embarrassing. It is recommended that you restart TiddlyWiki by refreshing your browser
TypeError: xhr is undefined

**Comment by rubaboo** [comment]
Rolled back to d4b4c3c93 and it's good again.

**Comment by pmario** [comment]
@rubaboo ... How does your setup look like? server? apache, nginx, ??

**Comment by rubaboo** [comment]
@pmario Nodejs on linux.
```
~$ nodejs --version
v6.13.1
$ cat /etc/debian_version
9.0
```

**Comment by pmario** [comment]
Ah, OK. ... 

The PUT saver is for WebDav configuration. So I shouldn't affect a nodejs configuration. ... IMO retrieveETags should not be called if OPTIONS doesn't return `dav` @sukima
