### ISSUE TITLE
[Print Tiddler Button] print dialogue fires too early

### ISSUE THREAD

**Issue by BurningTreeC** [Jermolene/TiddlyWiki5#3268]
To replicate: print a tiddler with some heavier content that doesn't render instantly  (more images, something that takes a bit to load) when the new window opens. The print dialogue doesn't show the content then. Closing the dialogue causes the window to finish rendering and afterwards one can print the content

**Comment by sukima** [comment]
Not sure how to fix this but to reproduce this in development you can use this PHP script:

```php
<?php
sleep(5);
header("Cache-Control: no-store, no-cache, must-revalidate, max-age=0");
header("Cache-Control: post-check=0, pre-check=0", false);
header("Pragma: no-cache");
header("Content-Type: image/jpg");
echo readfile("editions/tw5.com/tiddlers/images/Blurry Lawn.jpg");
?>
```

1.  Place the above PHP script in the root TiddlyWiki5 folder. (`test.php`)
2.  Run the PHP dev server: `php -Slocalhost:8888`
3.  Run the tiddlywiki server in a seperate terminal: `./tiddlywiki.js editions/tw5.com --server`
4.  Open the browser to `http://localhost:8080`
5.  Create a new tiddler with the following in it: `<img src="http://localhost:8888/test.php">`
6.  Attempt to **print in new window**

**Comment by BurningTreeC** [comment]
Hm. How does this work in your test?

line 65 in windows.js

```js
                widgetNode.render(srcDocument.body,srcDocument.body.firstChild,function(){
                // Print the window if required
                if(print) {
                                srcWindow.print();
                }
                });
```

**Comment by BurningTreeC** [comment]
-.- I thought that worked but testing it now after restarting node I've seen that I was still using the setTimeout method :+1:

**Comment by Jermolene** [comment]
Thanks @BurningTreeC @sukima. I wondered if we could find a good example tiddler for testing? My current thinking is that we should push the feature back to v5.1.18 if we can't fix this overnight.

**Comment by sukima** [comment]
@Jermolene We can't really have a test tiddler because the bug only presents itself if the content of such tiddler is remote *and* the remote takes forever to resolve. Since most all of the tiddlers in the current repository are built-in we would not see this happen.

The reason I posted the test Node server above was to artificially introduce a large delay to the act of serving a remote image. It used an image in the repo but has nothing to do with the tiddlywiki server. Once a tiddler that references that slow image (by means of a `<img src="http://localhost:8888/">` in the tiddler body) is created the bug will present itself.

**Comment by BurningTreeC** [comment]
@sukima 
in my case the bug presents itself just by printing a tiddler with many different served images

this problem seems to be chrome-only (chromium, tiddlydesktop) - because of the print dialogue not reloading what's still trying to render below
firefox does it differently, the print dialogue shows in a new window - it prints the whole thing

**Comment by BurningTreeC** [comment]
what I'm experiencing is probably related to https://bugs.chromium.org/p/chromium/issues/detail?id=437230

on chrome/chromium javascript execution gets stopped when the print dialogue opens, that's why it prints only content that's already rendered at the moment the dialogue opens. The main wiki page on chrome/chromium also is unresponsive while the dialogue is open. That won't be fixable with waiting-til-tiddler-content-is-rendered

**Comment by Jermolene** [comment]
Hmm @BurningTreeC if it works on all other browsers, and the problem is just Chrome, then perhaps there's a case for retaining the feature? We'd just make a note in the release note about the issues with Chrome

**Comment by BurningTreeC** [comment]
yes @Jermolene , seems this is a WontFix from the chromium-side

only thing that would improve printing in those cases would be waiting until I-don't-know

Because I don't know it's ok as it is. I'll modify my windows.js with a setTimeout of around 1.5s because I'll have served images often and it's the only fix working for me atm (TiddlyDesktop has that kind of trouble, too)
