### ISSUE TITLE
No mention of TiddlySpot at all in docs (!?) [incl. PR]

### ISSUE THREAD

**Issue by twMat** [Jermolene/TiddlyWiki5#3269]
To my surprise, searching for `TiddlySpot` on tw.com yields nothing. I can swear there was previously something that at least mentioned the issues about uploading a TW5 for the first time, that it requires Chrome.

IMO it should also appear as one of the listed platforms in GettingStarted.

Here is a possible entry:

````
title: TiddlySpot
tags: Linux Mac Resources Saving Windows
text: [[TiddlySpot|http://tiddlyspot.com/]] is a public hosting service for ~TiddlyWikis, built and administered by Simon Baird and Daniel Baird. It is popular in the ~TiddlyWiki community as a free and easy way to host ~TiddlyWikis online. It offers several setups for the older TiddlyWikiClassic but it is also possible to upload a ~TiddlyWiki5 to TiddlySpot.

TiddlyWiki has an integrated saver to upload to ~TiddlySpot.
```

**Comment by morosanuae** [comment]
Hello,

IMO and based on my frustrating experience learning TW: "**SEARCHING** the docs **IS NOT THE BEST WAY** to find what you're looking for". I tried some time ago to draw attention on the docs problems and also tried to take care of them but I realize that solving them is not a main priority for this community.
Currently, it seems that only singular small patches/fixes can be applied to the docs. No major intentions yet.

**Comment by Jermolene** [comment]
> I can swear there was previously something that at least mentioned the issues about uploading a TW5 for the first time, that it requires Chrome.

@twMat you are not crazy, it turns out that somehow the tiddler about TiddlySpot got deleted in the big reorganisation I did back in November -- see 021b5e072b4a575ff52153fcb8fdac4109132a9c

I'll reinstate it.
