### ISSUE TITLE
Tiddler type field malfunctions if setting "links to missing tids" is disabled

### ISSUE THREAD

**Issue by twMat** [Jermolene/TiddlyWiki5#3274]
As noted [here](https://groups.google.com/forum/#!topic/tiddlywiki/m8O6LlhsS6k).
To reproduce:

Ctrlpanel > Settings .... uncheck "Enable links to missing tiddlers"

Then open a tid in edit mode and click on the type dropdown. The list is not correct.

**Comment by BurningTreeC** [comment]
Hi @twMat , I've proposed a possible fix here: #3275

**Comment by twMat** [comment]
wow, that was fast! Thank you. I'll wait til your PR is accepted before closing this issue.

**Comment by Jermolene** [comment]
Thanks @twMat @BurningTreeC I'm beginning to think that I should never have merged the "disable links to missing tiddlers" setting; it's poorly thought through, evidently insufficiently tested and disables critical wiki functionality.

One thing I don't quite understand is why people might actually use it; I'm wondering if it's perhaps being used to mask some other problem?

**Comment by pmario** [comment]
>One thing I don't quite understand is why people might actually use it; I'm wondering if it's perhaps being used to mask some other problem?

I can understand the desire. eg: If you create some documents for end-users, that are "pure" documentation "consumers". Users may have no idea, that TW is actually used to create the docs.  It may be confusing  for them, if they click a link and an "empty" tiddler opens. 

For me this falls into the same topic as "hiding tiddler toolbar buttons" ... or "read only mode"

**Comment by pmario** [comment]
I think the problem could be fixed with CSS only.

**Comment by BurningTreeC** [comment]
Hi ... I can imagine that it's useful in some cases to have it

@pmario - I don't know how to fix it with CSS, because of the linkcatcher widget catching the link, which isn't functional in the current state with "disable links to missing tiddlers"

**Comment by pmario** [comment]
You are right. ... I didn't think about the functionality, of the buttons ... Just the block formatting :) 
Function is completely removed, here. .... 

So we may need ot split the whole thing into 2 different functions, that can be used independently

**Comment by BurningTreeC** [comment]
... for the new-field-name drop-down the problem is the same
I'm ok with other ideas

**Comment by twMat** [comment]
AFAICT this is now solved.
Thanks everyone.
Closing.
