### ISSUE TITLE
listen for navigator-events in story.js

### ISSUE THREAD

**Issue by BurningTreeC** [Jermolene/TiddlyWiki5#3286]
we need to modify the [story startup module](https://github.com/Jermolene/TiddlyWiki5/blob/master/core/modules/startup/story.js)

currently only the [navigator widget](https://github.com/Jermolene/TiddlyWiki5/blob/master/core/modules/widgets/navigator.js) is able to listen for events like "tm-new-tiddler"

because of that the (work in progress) [keyboard startup module](https://github.com/Jermolene/TiddlyWiki5/pull/3283) for global shortcuts and the startup actions cannot use actions handled by the navigator widget

**Comment by pmario** [comment]
We can have more than 1 stories open at the same time and global keyboard shortcuts still should work. 

I think we should go with the workaround Jeremy proposed [here](https://github.com/Jermolene/TiddlyWiki5/pull/3283#issuecomment-389498551): 

>That's correct. The current workaround is to wrap the action widgets in an instance of the navigator widget, with the appropriate settings for the story and history list.

**Comment by Jermolene** [comment]
I think we should keep this open. It's not a dependency of the keyboard shortcut work, but this change would make that more useful, and the existing startup actions. The startup module story.js already knows about the default story river.
