### ISSUE TITLE
palette colors undefined result in CSS errors

### ISSUE THREAD

**Issue by rubaboo** [Jermolene/TiddlyWiki5#3290]
Did something change in dictionary tiddler handling, or was the browser always complaining about invalid CSS that results? I just noticed.

https://github.com/Jermolene/TiddlyWiki5/blob/33453039fcb92d8e0e14b4822e08d72e26384e25/core/palettes/Vanilla.tid#L13-L15

![image](https://user-images.githubusercontent.com/212368/40139658-78f7fa1a-5905-11e8-99f2-74237d94e365.png)

**Comment by pmario** [comment]
Browsers just ignore those variables. ... They have been always like this.

**Comment by pmario** [comment]
@Jermolene .. This one can be closed. Browser do ignore the missing parameters. 

There is some development going on with palettes ... https://talk.tiddlywiki.org/t/palette-manager-test-version/4434  but there still well be empty colours in the future.

**Comment by Jermolene** [comment]
Thanks @pmario @rubaboo
