### ISSUE TITLE
Put "class=tiddler" in tiddlers div

### ISSUE THREAD

**Issue by somenxavier** [Jermolene/TiddlyWiki5#3293]
I want to use nokogiri (ruby) for extracting and modifying the information in the tiddlers. For this, I propose a non-obtrusive change in tiddlers div: put "class=tiddler" in this. So
```
<div created="..." modifited="..." tags="..."  title="..."><pre>[content]</pre></div>
```

would become
```
<div class="tiddler" created="..." modifited="..." tags="..."  title="..."><pre>[content]</pre></div>
```

**Comment by pmario** [comment]
Could you be a bit more specific, what you want to do?

**Comment by pmario** [comment]
Hi, If you have a closer look at: https://github.com/Jermolene/TiddlyWiki5/blob/6b14969cf60bdcad16ac5978030bf1d929a712c6/core/templates/tiddlywiki5.html.tid#L38 you'll see that the storage area in a TW file is placed in line 38. 

Which is this template: https://github.com/Jermolene/TiddlyWiki5/blob/master/core/templates/store.area.template.html.tid

It contains a `<div id="storeArea">` .. so every "child div" IS a tiddler, which I think should be enough info for your code to reliably identify tiddler boundaries. 

The only child in a tiddler is the `<pre>` element, that contains html-encoded tiddler source code. 

If you have more questions, just ask.

**Comment by somenxavier** [comment]
Thanks @pmario
