### ISSUE TITLE
sortByList is incorrect when placement specifications are in inconvenient order

### ISSUE THREAD

**Issue by flibbles** [Jermolene/TiddlyWiki5#3296]
Simple example: three tiddlers, all tagged with `foo`

A {list-after: B}
B {list-after: C}
C

Results?

A, C, B

Tiddler A is not after B, because in sortByList, it was placed after B, then B was placed after C, which put it back after A. This problem can manifest in many little ways when using `list-after` and `list-before`, but this is the most rudimentary example.

I already have a fix, and I can make a PR at any time. I'm unfamiliar with the Tiddlywiki dev process. Am I allowed to go straight to making the PR? Or should I continue making an issue about it first?

**Comment by Jermolene** [comment]
Thanks @flibbles it would be very much appreciated if you can produce a PR for this.

There is already a single test for tag ordering. As part of the PR it would be very useful to expand the tests:

https://github.com/Jermolene/TiddlyWiki5/blob/master/editions/test/tiddlers/tests/test-tags.js

**Comment by flibbles** [comment]
Done! Let me know if there's any issues with the code. Formatting, style, tests...

**Comment by pmario** [comment]
As I wrote in PR #3301 I don't think there is an easy fix. eg: A (list-after B) and B (list-after A)

**Comment by flibbles** [comment]
As it turns out, it actually _is_ an easy fix. @Jermolene and @pmario, PR #3301 is ready to merge.

If not, please provide a reason why it shouldn't be. This issue and PR has been stagnating for nearly 6 months when it was ready to merge in the first week. It fixes a legitimate bug.

**Comment by flibbles** [comment]
Thank you all for merging the fix for this issue. This proves that there is a brighter future ahead for our children and our children's children.
