### ISSUE TITLE
<TAB> to cycle through title-tag-text-type-fields inputs

### ISSUE THREAD

**Issue by BurningTreeC** [Jermolene/TiddlyWiki5#3298]
Hi all, at the moment using `<TAB>` to jump ahead from the tiddler title focuses the tag-pill - next focuses the tag input - the next goes through all the toolbar buttons and maybe at one point focuses the text area. No way to jump to the type input fields or the fields input areas.

Could we add tabindices to the different engines and give them the correct values?

I'd say ...

1st tiddler
title: 1
tag input: 2
text field: 3
type input: 4
field name: 5
field value: 6

2nd tiddler
title: 7
tag input: 8
and so on

I've managed to do it by adding them within the engines but with change event listeners and I don't know how that's performance-wise

What I can say is that it's very comfortable

**Comment by Jermolene** [comment]
Hi @BurningTreeC I'd be very happy to see this fixed.

**Comment by BurningTreeC** [comment]
Ok @Jermolene - I made a PR #3302 
Fortunately I found a much easier way to accomplish this
