### ISSUE TITLE
<$list><$set><$set> nesting renders garbage closing tags

### ISSUE THREAD

**Issue by flibbles** [Jermolene/TiddlyWiki5#3306]
I'm noticing that this:
```
<$list filter="1 2 3 4 5">
<$set name="A" value="value">
<$set name="B" value="value">

</$set></$set></$list>
```
produces that:
```
</$list> </$list> </$list> </$list> </$list>
```
Am I doing something wrong?

In my project, I'm currently using a workaround of <$list><$list><$set> nesting.

**Comment by Jermolene** [comment]
Hi @flibbles good spot. I think it's a bug, but we'll need to investigate further. In the prerelease you can use the preview type dropdown to choose the parse tree view which makes it easier to see.

**Comment by Evolena** [comment]
It seems to be a inline/block issue. These codes don't add any list closing tag:

```
<$list filter="1 2 3 4 5">
<$set name="A" value="value">
<$set name="B" value="value">
</$set></$set></$list>
```

```
<$list filter="1 2 3 4 5">
<$set name="A" value="value">
<$set name="B" value="value">

</$set>
</$set></$list>
```

Or with something displayed inside:

```
<$list filter="1 2 3 4 5">
<$set name="A" value="value">
<$set name="B" value="value">
<<A>> (inline)
</$set></$set></$list>
```

```
<$list filter="1 2 3 4 5">

<$set name="A" value="value">
<$set name="B" value="value">
<<A>> (block)
</$set></$set></$list>
```

This one adds the extraneous `<\$list>`:

```
<$list filter="1 2 3 4 5">
<$set name="A" value="value">
<$set name="B" value="value">

<<A>>
</$set></$set></$list>
```

**Comment by flibbles** [comment]
This is causing me more problems, so I looked at it a bit more.
```
<div><span><span>

Text
</span></span></div>
```
This also catches the problem. This is definitely an issue with the parser.

Putting in the following test in `test-wikitext-parser.js` (Line 96) replicates the problem:

```javascript
                expect(parse("<div><span><span>\n\nSome text</span></span></div>")).toEqual(

                        [ { type : 'element', tag : 'p', children : [ { type : 'element', start : 0, attributes : {  }, tag : 'div', end : 5, isBlock : false, children : [ { type : 'element', start : 5, attributes : {  }, tag : 'span', end : 11, isBlock : false, children : [ { type : 'element', start : 11, attributes : {  }, tag : 'span', end : 17, isBlock : true, children : [ { type : 'element', tag : 'p', children : [ { type : 'text', text : 'some text' } ] } ] } ] } ] } ] } ]

                );
```

It looks like the parser is failing to pick up the second `</span>` tag, because it's acting like it's not there, and adding a _third_ `</span>` (I.E. `</span></span></span></div>`) closes things out and creates exactly the parseTree that should be produced with only two closing spans.

I might look into this more if I have the time, but I'm posting this in case anyone more familiar with that part of the code may know what's happening.

**Comment by twMat** [comment]
@flibbles , your PR brought me here.
I have noticed that `{{{ aaa }}} {{{ bbb }}}` (i.e two filtertrans on same line, with arbitrary content between them) also produces erroneous output. I'm thinking it might be related to the inline/block matter, so IF it is, then maybe your magic PR can deal with this case too. If it is NOT related, then never mind. *No need to reply to me or spend time on it*.

**Comment by flibbles** [comment]
It's only related in that it's also a inline/block issue. This is because the filtertransclude is getting parsed as a block, because it detected the `}}}` at the end of the line. So everything inbetween thus counts as content. If you put even a single space at the end of `{{{ aaa }}} {{{ bbb }}}`, it forces it to parse inline, and it's fine.

This is indeed a bug, but it's a separate issue.

**Comment by Jermolene** [comment]
Hi @flibbles @twMat thanks for bringing this to my attention again. I've also encountered the same problem as the OP in this form see #4864:

```
<div><p><p>

</p></p></div>
```

Which renders as:

```
</div>
```

As per your investigations, I concluded that the issue was that the inner `<p>` matches with the final `</p>`, causing things to fall out of sync, but I didn't get any further.

**Comment by flibbles** [comment]
No worries! It was a tricky one. Glad it's fixed now.
