### ISSUE TITLE
Feature Request: Allow fields to take up multiple lines

### ISSUE THREAD

**Issue by diego898** [Jermolene/TiddlyWiki5#3307]
There has been some discussion in the group about modifications allowing fields to be displayed with textareas, contain new lines, etc. 

I think a great workflow for this would be to just allow some special marker to contain a field spanning multiple lines. Something like `{= ... =}` (like evan's formula plugin):

```
title: A tiddler
created:
modified:
tags: tag1 [[tag 2]]
field1: a field text!
field2:{=a
field
on
multiple
lines
=}

This is the body of the tiddler
```

I think this will allow for **much** more flexibility in splitting a tiddler into relevant portions for example:

```
title: My Structured Tiddler
created:
modified:
tags: tag1 [[tag 2]]
intro:{=...paste long text here...=}
p1:{=.....=}
p2:{=.....=}
conclusion:{=.....=}

{{{!!intro}}}
{{{!!p1}}}
{{{!!p2}}}
{{{!!conclusion}}}
```

**Comment by sukima** [comment]
Why not `"` and `\"` Or ending `\`?

```
intro: foo \
bar \
baz
p1: ...
```

An alternative point of view is to say that tiddler front-matter is the wrong abstraction for multi-line data and instead the tiddler format should be in JSON or XML.

In any case I personally do't like the delimiter approach (`{=......=}`) is way to difficult to read. I think I would re-architect my fields before I ever attempted to use that style. In fact I'd like use a [JSON data tiddler](https://tiddlywiki.com/#DataTiddlers) before wanting multi-line tiddler fields.

**Comment by diego898** [comment]
@sukima  you make a great point. I only went with that delimiter as a suggestion and it was similar to another awesome plugin's delimiter. 

I agree XML/JSON would be better, but the `.tid` format is so clean, simple, easy to read, and easy to type. Plus - it already exists and is supported. So I think its natural to have some way to type multiline fields in a `.tid` format.

**Comment by pmario** [comment]
I think this is a duplicate of: https://github.com/Jermolene/TiddlyWiki5/issues/1947

**Comment by diego898** [comment]
Jeremy's description in https://github.com/Jermolene/TiddlyWiki5/issues/1947#issuecomment-261960097 makes perfect sense! Lets do it!

**Comment by pmario** [comment]
>Jeremy's description in #1947 (comment) makes perfect sense! Lets do it!

Yea, .. but you'll need to push it from time to time :)
