### ISSUE TITLE
Feature Request: Advanced Edit Mode

### ISSUE THREAD

**Issue by diego898** [Jermolene/TiddlyWiki5#3308]
I think it would be a great feature to be able to enter an "advanced edit mode" where we click a button and the entire tiddler we are working on turns into a large text field with the contents of the file in `.tid` format are visible. 

This way I can quickly change tags, field contents, etc. without having to click and re-click, etc. 

~~Note: This is intimately related to #3307~~
EDIT: This is related to: https://github.com/Jermolene/TiddlyWiki5/issues/1947

**Comment by sukima** [comment]
I use the node version with my tiddlers and can edit them with any editor I wish. It does exactly what you request. I usually reserve editing in the web page as a last resort or if I want all the fancy web editor features.

Though I guess a built in advanced mode might be nice. 🤔

**Comment by diego898** [comment]
@sukima I also use the node version and make/edit these files in my text editor. But sometimes I'm on a browser version and find it cumbersome to use the fancy web editor. 

Preview mode already has several advanced previewing modes, I think its natural for edit mode to have one too. As I mentioned in #3307, the `.tid` style is the most natural, cleanest and simple to type

**Comment by diego898** [comment]
Edited above, this is actually related to https://github.com/Jermolene/TiddlyWiki5/issues/1947

**Comment by AnthonyMuscio** [comment]
Diego, 

As per issue 3350

Interestingly your advanced edit mode is in some ways a more basic edit mode where you are looking at the raw tiddler. I think I could build that already, but you are aware you will loose all the lookup and validation features?, like when adding a field have you got the same spelling as last time, is the tag already there?. Can you give me more of the business case, and how you see it being a benefit,  are you mostly wanting to avoid edit mode?

Regards
Tony

**Comment by diego898** [comment]
Hey Tony,

Thanks for your comments. I agree this "advanced mode" is in many ways more "basic". As you might remember from the group, I frequently find it more convenient to create `.tid` files automatically in response to certain events (new files in a folder, for example) and open those `.tid` files in a text editor where I can quickly and easily make all required edits using just my keyboard. 

I thought it would be straightforward to incorporate this directly into the browser TW, allowing someone to quickly change things like created date, field names, contents etc. Coupled with an ability to define multi-line fields, I see this a great feature for quick medium/heavy editting of tiddlers.

**Comment by diego898** [comment]
Just refreshing this issue!

**Comment by diego898** [comment]
I came across rquicktid: 

http://rquicktid.tiddlyspot.com/

which is definitely en route to this feature! It pops up a simple window in where the first line is the title, the second line is the tags, and third and on is the body. This would be a great starting point!

**Comment by diego898** [comment]
Just a quick refresh on this one!

**Comment by diego898** [comment]
A related idea by @pmario was posted on the google groups here:

https://groups.google.com/d/msg/tiddlywiki/42_bWs-f2YY/MsxNmud9AAAJ

**Comment by diego898** [comment]
Hey @Jermolene - I'm trying to go through and clean/close my old/dead issues. This one is still very interesting to me, but if you don't think it's appropriate or not-in-line with the vision for core TW I can go ahead and close it.

**Comment by pmario** [comment]
I think, there is no problem to have open Feature Requests. ... A label would be good!

**Comment by diego898** [comment]
Hey @pmario - sorry, what do you mean by label?

**Comment by pmario** [comment]
@Jermolene can assign a label named: newfeature   which can be used as a filter. newfeatures imo are "long running" issues. They are closed if the feature exists, or it gets a "wontfix"

**Comment by diego898** [comment]
Ah I see what you mean - yes I think thats a good idea. I've seen the post-5.1.20 label currently in use.

**Comment by AnthonyMuscio** [comment]
Diego,
Time has passed and I do recall discovering a way to type into the text field of a tiddler the raw definition of a tiddler, exporting this and reimporting it would generate a new tiddler/overwrite the existing one with new values. Perhaps now I could find a way to do this without export/import. It would be possible to copy all existing fields into a tiddler text field using the raw tiddler format, where you edit it, and trigger its "re-import" for want of a better word. Note the edited fields would override the existing fields. If you would like to proceed along this path let me know and I will provide some background info on how to do it.

A little more work may allow this method to do a difference compare with preview.

Regards
Tony

**Comment by diego898** [comment]
Hey @AnthonyMuscio sure! Leave some notes here describing your approach!

**Comment by Jermolene** [comment]
This is indeed a really interesting idea, but in the first instance it can be explored via a plugin, and doesn't seem to require any upfront core modifications to make it feasible.

**Comment by diego898** [comment]
@saqimtiaz I was watching your google hangout video again where you talk about Notation, and thought that this could be a great fit for your notation workflow, in the bottom panel. What do you think?

**Comment by saqimtiaz** [comment]
> @saqimtiaz I was watching your google hangout video again where you talk about Notation, and thought that this could be a great fit for your notation workflow, in the bottom panel. What do you think?

I think the best way to go about this is first implementing this as standalone feature. Recommend you look into the template tiddler used by tiddlywiki to save tiddlers to .tid files on node. You should be able to re-use this within TW (no need for node even) to format the fields of a tiddler into a string in a .tid format and put that in an edit-text widget that writes to a temp tiddler.

This would allow editing the tiddler (as well as creating new ones)

The next step will be parsing the .tid format into json and saving it. You may need a tiny bit of JavaScript to get that done reliably and in the same manner as the core, though filters could do the trick as well. Once you get this far, if you have problems taking it further post on the google groups with your code, and either I or someone else will be able to help you out.

**Comment by diego898** [comment]
@saqimtiaz I can give it a try - can you point me to that template?

**Comment by diego898** [comment]
I'd like to give this issue a try, but would really appreciate a "mentor"!

**Comment by diego898** [comment]
for what its worth, this is almost solved by Mat's "Side Editor 2.0", the original author of rquicktid.

The only missing thing would be to be able to initialize the quick edit window with the .tid contents of a tiddler.

**Comment by saqimtiaz** [comment]
> @saqimtiaz I can give it a try - can you point me to that template?

https://github.com/Jermolene/TiddlyWiki5/blob/master/core/templates/tid-tiddler.tid

I do think the proper place to ask for further help in trying to implement this is the google group.
