### ISSUE TITLE
Ordered lists problem with table of contents

### ISSUE THREAD

**Issue by depht** [Jermolene/TiddlyWiki5#3310]
Apologies if this has been raised before. I did a cursory search but didn't find anything regarding this. 

When using the table of contents macro and using the tabbed version of it there's a little bit of an issue with ordered lists. 

The element .tc-table-of-contents is overriding the style of the ordered list in the actual content, as such the numbers are no longer there and the elements have font-weight: bold.

Now this can obviously be sorted out with a custom stylesheet, however this seems like it's unintended behaviour?

This is what it should look like:

![tw issue 1](https://user-images.githubusercontent.com/7636176/40509758-71d1311e-5f92-11e8-9430-49b111fe6e89.png)

This is what it looks like: 
![tw-issue2](https://user-images.githubusercontent.com/7636176/40509818-8f91199e-5f92-11e8-854c-91852ead157c.png)

Thanks.

**Comment by pmario** [comment]
Can you post your wikitext?

**Comment by depht** [comment]
The wikitext below is what should be creating an numbered list. 
`# A homomorphism need not be either one-one or onto. A homomorphism that is one-one and onto is an isomorphism. `

`# A homomorphism that is one-one but not onto fails to be an isomorphism. In this case, a closely related isomorphism can be found by restricting the the codomain. The first function of the three functions can have it's codomain restricted to $$(5\mathbb{Z}, +)$$ to yield an isomorphism.`

Which renders fine in the tiddler itself, however when using the tabbed toc macro: 
```
<div class="tc-table-of-contents">
<<toc-tabbed-internal-nav "Contents">>
</div>
```

That's when it just renders as bold text.

**Comment by depht** [comment]
After posting this, I noticed the div that contains the macro. I tried removing the div and now this works properly.

**Comment by pmario** [comment]
>After posting this, I noticed the div that contains the macro. I tried removing the div and now this works properly.

If it's fixed for you, you should close the issue. .. If not, we'll have to investigate further.

**Comment by Evolena** [comment]
As it was intriguing for me, I searched an explanation.

The non-tabbed toc macro don't have the tc-table-of-contents class, this is why it is added with an englobing div.

But the tabbed-toc macros do have this class for the tab only, and not for the content:

```
\define toc-tabbed-external-nav(tag,sort:"",selectedTiddler:"$:/temp/toc/selectedTiddler",unselectedText,missingText,template:"")
<$tiddler tiddler={{$selectedTiddler$}}>
  <div class="tc-tabbed-table-of-contents">
    <$linkcatcher to="$selectedTiddler$">
      <div class="tc-table-of-contents">
        <$macrocall $name="toc-selective-expandable" tag="""$tag$""" sort="""$sort$""" itemClassFilter=<<toc-tabbed-selected-item-filter selectedTiddler:"""$selectedTiddler$""">>/>
      </div>
    </$linkcatcher>
    <div class="tc-tabbed-table-of-contents-content">
      ...
    </div>
  </div>
</$tiddler>
\end
```

So addind a div with the class is useless for the navigation tab as it already have it, and useless and faulty for the content part, as it doesn't need it.

**Comment by depht** [comment]
Interesting. I made a separate tiddler for the tabbed contents and copied the wikitext from my normal one which has the example from tiddlywiki.com with the containing div, not realising this would break it like it did.

Thanks for the investigation :)
