### ISSUE TITLE
transclusion templates used at attributes don't work

### ISSUE THREAD

**Issue by flibbles** [Jermolene/TiddlyWiki5#3311]
`<$text text={{base||template}} />` renders nothing, but I'd expect it to render `{{base||template}}`, which renders fine on its own. It seems like any use of `||template` as an attribute argument for widgets or html elements all fail.

Is this a bug? Or a known limitation?

If a bug, then putting this unit test in **editions/test/tiddlers/test/test-widget.js** will isolate it:
```javascript
it("should parse and render attribute template transclusion", function() {
        var wiki = new $tw.Wiki();
        wiki.addTiddlers([
                {title: "template", text: "prefix_<$transclude />"},
                {title: "base", text: "value"}
        ]);
        var text = "Result: <$text text={{base||template}} />";
        var widgetNode = createWidgetNode(parseText(text,wiki),wiki);
        // Render the widget node to the DOM
        var wrapper = renderWidgetNode(widgetNode);
        expect(wrapper.innerHTML).toBe("<p>Result: prefix_value</p>");
});
```

To be clear: `<$text text={{base}} />` *does* render something.

**Comment by pmario** [comment]
hmmm, I think you are the first one who wanted to use a template for widget attributes. ..

**Comment by pmario** [comment]
`{{base||template}}` is a shortcut for 

```
<$tiddler tiddler="base">
<$transclude tiddler="template"/>
</$tiddler>
```

which could be created with a macro, as a workaround

**Comment by flibbles** [comment]
Hah! That's possible. Funny part is I was using templated transclusion as a workaround for some finicky macro issues. (and to keep from polluting my global macro namespace more than I have).

If you all think this one is worth fixing, I can look into it as soon as I have some time.

**Comment by Jermolene** [comment]
Hi @flibbles you've stumbled on a facet of a trivial but critical design flaw in TW5: usage of the double brace transclusion notation is inconsistent between body text and attributes. In the case of transclusions in body text, the default action is for the target of the transclusion to be wikified. But attributes get the raw text value of the target of the transclusion. It's frustrating that it is too late to change.

Are you happy to close this ticket for the moment?

**Comment by flibbles** [comment]
If nothing can be done, then I suppose there’s nothing else to do but to close the ticket. Thank you for the explanation.
