### ISSUE TITLE
Twitter Plugin -- "Widgets" deprecated by Twitter

### ISSUE THREAD

**Issue by TiddlyTweeter** [Jermolene/TiddlyWiki5#3314]
Twitter has recently ended ability to create "Widgets". New ones can no longer be made in accounts and after July 27th old ones won't be accessible either. 

(Most) Old widgets embedded in sites will continue to work, but all are deprecated.

More detail here on what will still work and what won't: https://twittercommunity.com/t/deprecating-widget-settings/102295

The excellent Twitter plugin for TW should be updated to mention that since it is a significant change. The widget support can continue but should be flagged "deprecated".

FWIW, I myself am wondering if some things the widgets could do well can be so easily replaced. As far as I know Twitter has not yet added all the methods needed to fill the gap.

**Comment by Jermolene** [comment]
Thanks @TiddlyTweeter I had missed the announcements...

It looks like the plugin can be adapted to work in the new way, I'll try to make some time to investigate.

**Comment by cpjobling** [comment]
Yes, I can confirm that the Twitter widget has stopped working in version 68 of Chrome. It still works in Safari, Firefox and Beaker (at least on my Mac), but perhaps it's just a matter of time.

**Comment by mandarvaze** [comment]
Does this work anymore ? I tried to add "Button to share", but it does not work. It renders as `Can't render tweet` - Same for all the examples in the Usage section of the plugin.

**Comment by Jermolene** [comment]
It works for me in the browsers I've tested, apart from the "List Timeline", "Widget Timeline" 
<img width="1104" alt="image" src="https://user-images.githubusercontent.com/174761/79776490-bca63e80-832d-11ea-9ef8-224c9b527786.png">

**Comment by mandarvaze** [comment]
@Jermolene Do I need to configure it before it works ?
I just installed the plugin (save and reload, as instructed) and went to the `usage` tab. 
I keep seeing `Can't render tweet`

I'm on TW version 5.1.22 (and macOS catalina)

I tried on Firefox, Brave and Google Chrome.  Same result.

To troubleshoot, I downloaded `empty.html` and just installed twitter plugin (save and reload, as instructed) and went to the `usage` tab.  Got `Can't render tweet` 😢

**Let me know if there are ways to troubleshoot this. I see no error on the Developer Tools-> Console (Google Chrome and Firefox)**

<img width="886" alt="Screen Shot 2020-04-20 at 10 33 10 PM" src="https://user-images.githubusercontent.com/46438/79779429-09067400-8358-11ea-8412-f991c797b3d7.png">

**Comment by Jermolene** [comment]
Hi @mandarvaze 

> Do I need to configure it before it works ?

No, it should just work. 

The error message "Can't render tweet" implies that Twitter's API library hasn't loaded and initialised correctly. Are you running an ad-blocker or other software that interferes with browsing?

Are you able to try on a different device?

Do other plugins work OK for you?

It may also be worth opening dev tools and typing `window.twttr` in the console, and reporting back what you see.

**Comment by mandarvaze** [comment]
> Are you running an ad-blocker

Yes, with Firefox I use Adblocker Ultimate. 
I think Brave automatically blocks Ads.
But Google Chrome does not have **any** extensions. (It is my backup browser when other browsers just don't work. So no extensions etc.)
I also tried on Safari (No extensions, but I am not sure if it blocks ads on its own)

> Do other plugins work OK for you?

Yes. I have "Powered By TiddlyWiki" and "Menu Bar" plugins. They work OK.

> It may also be worth opening dev tools and typing window.twttr in the console, and reporting back what you see.

Returns `undefined` for Firefox, Brave **and** Google Chrome.
I looked at the [code](https://github.com/Jermolene/TiddlyWiki5/blob/master/plugins/tiddlywiki/twitter/twitter-widget.js#L115), I think this is definitely why I'm seeing `Can't render tweet`

But I am not sure why `window.twttr` is undefined.

**Comment by Jermolene** [comment]
Hi @mandarvaze I should have mentioned this earlier, but the Twitter plugin requires an extra step in the installation process: after installing the plugin from the library and saving changes, it is necessary to open the file again and re-save it before the Twitter library will be loaded properly.

**Comment by mandarvaze** [comment]
@Jermolene Worked. Thanks.

**Comment by Jermolene** [comment]
Thanks @mandarvaze I've added a warning in 678e25f51 for v5.1.23

<img width="869" alt="image" src="https://user-images.githubusercontent.com/174761/79910290-5a753880-8416-11ea-8ae6-8aa3b0100336.png">
