### ISSUE TITLE
Please urlizy the # contents

### ISSUE THREAD

**Issue by somenxavier** [Jermolene/TiddlyWiki5#3316]
If you have a title like this:
`Les hores que els estatunidencs veuen la televisió`
you get
`wiki.html#Les hores que els estatunidencs veuen la televisió`
instead of
`wiki.html#Les%20hores%20que%20els%20estatunidencs%20veuen%20la%20televisi%C3%B3`

in the URL bar. I think it is a bug, isn't?

**Comment by Jermolene** [comment]
Hi @somenxavier I believe that the behaviour you're seeing is the browser helpfully trying to make the URL more readable by URL decoding it for display, without changing the underlying value. If you copy the URL from the address bar you should find that it is the expected value.

**Comment by pmario** [comment]
@somenxavier .. if you copy the link with spaces into a forum like here on github, you'll see it will be broken. 

eg: 

http://example.com/wiki.html#Les hores que els estatunidencs veuen la televisió

while the second one will work. 

http://example.com/wiki.html#Les%20hores%20que%20els%20estatunidencs%20veuen%20la%20televisi%C3%B3

**Comment by Jermolene** [comment]
@pmario  to see the problem that @somenxavier is referring to:

1. Create a new tiddler called "Les hores que els estatunidencs veuen la televisió"
2. Choose "permalink" in the tiddler toolbar
3. In Chrome, the address bar shows: "#Les%20hores%20que%20els%20estatunidencs%20veuen%20la%20televisió"
4. Copying from the address bar (with ctrl/cmd-L then ctrl/cmd-C) yields the expected, fully encoded value

**Comment by somenxavier** [comment]
> Hi @somenxavier I believe that the behaviour you're seeing is the browser helpfully trying to make the URL more readable by URL decoding it for display, without changing the underlying value. If you copy the URL from the address bar you should find that it is the expected value.

Yes, but the permalink "should" display `%` in firefox too when you press it, right?

**Comment by BurningTreeC** [comment]
> Yes, but the permalink "should" display % in firefox too when you press it, right?

I can confirm that on the latest stable firefox on Windows 10 the permalink of the tiddler "Les hores que els estatunidencs veuen la televisió" on tiddlywiki.com shows:

https://tiddlywiki.com/#Les hores que els estatunidencs veuen la televisió

**But in fact is:**

https://tiddlywiki.com/#Les%20hores%20que%20els%20estatunidencs%20veuen%20la%20televisi%C3%B3

The last link is the result of copy-pasting it

This must be a browser-"feature" of firefox. The link is correct, but it translates the encoded characters to readable characters for the user

**Comment by BurningTreeC** [comment]
To be more precise

> Yes, but the permalink "should" display % in firefox too when you press it, right?

No, it doesn't seem so on Firefox. When you click it, it remains visually "translated". But: The url **is** the correct one with the encoded %20 - try copying it using Ctrl-C and pasting it somewhere. The result is the real url

**Comment by pmario** [comment]
IMO we can't fix this issue, since it is browser specific. As BTC found out, FF tries to show human friendly URLs, but copy-paste uses a "working" not so friendly representation.
