### ISSUE TITLE
_canonical_uri doesn't work with local images (harddrive) and MS Edge

### ISSUE THREAD

**Issue by InoPlugs** [Jermolene/TiddlyWiki5#3325]
This issue was also reported here: https://groups.google.com/forum/#!topic/tiddlywiki/SDtyUVripc0

If Microsoft Edge is used (tested with latest Win10 april 2018 version) local images won't be diplayed if the "_canonical_uri " field contains a local path (i.e. ./resources/images/my_image.jpg). However Firefox or Chrome display the local images just fine. The filepath does not contain any special characters, etc.

**Comment by pmario** [comment]
@Jermolene IMO can be closed. -- I did test it with latest Edge Version 119.0.2151.97 (Official build) (64-bit) and it seems to work fine

**Comment by Jermolene** [comment]
Thank you @pmario
