### ISSUE TITLE
Journal tiddlers seem to pick the date the TiddlyWiki file was last loaded, not today's date

### ISSUE THREAD

**Issue by tfeb** [Jermolene/TiddlyWiki5#3326]
I'm using TiddlyWiki 5.1.17, single-file TiddlyWiki, Firefox 60.0.1, download saver, OS 10.12 (and a tiny daemon which watches the downloads directory & copies the saved tiddlywiki to where it should be).

Because of the above I don't save very often but rely in Firefox not to die.  The following sequence of events (which is common for me) will cause the date of a new journal entry to be behind by a day:

1. open (or reload) the TiddlyWiki file on day *n*;
2. make a journal entry on day $n$ (not sure if this is necessary & suspect it is not);
3. wait until day *n + 1*;
4. make a journal entry: it will be dated day *n*, not day *n + 1*, and in particular it will start editing any preexisting journal for that day rather than making a new one.

The workaround is easy: save the TiddlyWiki if needed and reload.  But it is mildly annoying doing this, *especially* as this seems to be a reversion: I am pretty sure (although I have not checked) that this *didn't* happen with 5.1.15 (it did happen with some earlier versions though).

It's possible this is because of Firefox changes of course.

**Comment by pmario** [comment]
>It's possible this is because of Firefox changes of course.

I don't think so. .. We did some changes to the journal button.

**Comment by pmario** [comment]
The easiest way to test is: 

use: `DDth MMM YYYY 0hh:0mm` in the new Journal title template in ControlPanel and wait for the minute to switch. ... So you don't have to wait for the day-change ;)

**Comment by pmario** [comment]
As a workaround copy the following code into: `$:/core/ui/Buttons/new-journal`
and report if it works for you. 

```
\define getTitle()
<$wikify name="journalTitle" text="""<$macrocall $name="now" format=<<journalTitleTemplate>>/>""">
<$reveal type="nomatch" state=<<journalTitle>> text="">
<$action-sendmessage $message="tm-new-tiddler" title=<<journalTitle>> tags=<<journalTags>> text={{{ [<journalTitle>get[]] }}}/>
</$reveal>
<$reveal type="match" state=<<journalTitle>> text="">
<$action-sendmessage $message="tm-new-tiddler" title=<<journalTitle>> tags=<<journalTags>> text=<<journalText>>/>
</$reveal>
</$wikify>
\end
\define journalButton()
<$button actions=<<getTitle>> tooltip={{$:/language/Buttons/NewJournal/Hint}} aria-label={{$:/language/Buttons/NewJournal/Caption}} class=<<tv-config-toolbar-class>>>
<$list filter="[<tv-config-toolbar-icons>prefix[yes]]">
{{$:/core/images/new-journal-button}}
</$list>
<$list filter="[<tv-config-toolbar-text>prefix[yes]]">
<span class="tc-btn-text"><$text text={{$:/language/Buttons/NewJournal/Caption}}/></span>
</$list>
</$button>
\end
<$vars journalTitleTemplate={{$:/config/NewJournal/Title}} journalTags={{$:/config/NewJournal/Tags}} journalText={{$:/config/NewJournal/Text}}>
<<journalButton>>
</$vars>
```

**Comment by pmario** [comment]
Don't close the issue. It's a bug.

**Comment by tfeb** [comment]
@pmario Thanks, I'm glad it's a real bug and not some artifact of my baroque setup.  I can't test the workaround right now but I will do so soonish.

**Comment by Jermolene** [comment]
Thanks @tfeb @pmario, I think this is fixed by the change above.
