### ISSUE TITLE
Allow headings within a transclusion to be rebased

### ISSUE THREAD

**Issue by Jermolene** [Jermolene/TiddlyWiki5#3330]
A common frustration when transcluding content that includes headings occurs when trying to transclude content that includes headings within other headings. For example, @ldorigo [mentions](https://github.com/Jermolene/TiddlyWiki5/pull/3322#issuecomment-395677498) that:

> However the transclusion doesn't look very good, because the titles in the Forums tiddler have the same level as the other ones (`<h1>`)... Not sure what the best solution is here.

One possible solution is to establish a variable `tv-base-heading-level` that is consulted by the [element widget](https://github.com/Jermolene/TiddlyWiki5/blob/master/core/modules/widgets/element.js) when it encounters a heading element, and used to adjust the rendered heading level.

One could use it like this. Here's the tiddler `Foo`:

```
! I'm a level 1 heading

!! I'm a level 2 heading

<$vars tv-base-heading-level=3>
<$transclude tiddler="Bar"/>
</$vars>
```

And here's the tiddler `Bar`:

```
! I'm written as a level 1 heading...

...but will display as a level 3 tiddler when transcluded into [[Foo]]
```

**Comment by ldorigo** [comment]
Hi Jeremy, that's indeed one of my main frustrations with TW and was on top of the list of issues I wanted to tackle once I got familiar enough with the code base.

I had thought of a slightly different syntax, something like:

```
!  I'm a level one heading 

!! And me, a level 2

!!! {{Bar}}
```

With `Bar` being the same as yours:

```
! I'm written as a level 1 heading...

...but will display as a level 3 tiddler when transcluded into [[Foo]]
```

It's probably more intuitive (especially for everyday users, no need to know about variables and widgets), but I don't know how much harder it would be implementation-wise.

**Comment by Jermolene** [comment]
Hi @ldorigo 

> I had thought of a slightly different syntax, something like:

The approach I proposed is at the widget layer; we could also add a parser rule that provides a shortcut syntax (just as the `{{}}` syntax provides a shortcut for the `<$transclude>` and `<$tiddler>` widgets.

I don't think we could use the syntax you proposed, though, because it wouldn't be backwards compatible for existing content that might easily use the same construction.

I wondered about `{!!{Bar}}` for transcluding "Bar" while setting `tv-base-heading-level` to 2. And maybe `{-!!{Bar}}` for transcluding "Bar" while setting `tv-base-heading-level` to -2.

It's tricky: we don't try to define syntactic primitives for everything in TW, because the wikitext syntax would get too large and complex. There's a tension with the other alternative of using a custom macro. In this case, I do wonder whether it's common enough to warrant a special syntax.

**Comment by pmario** [comment]
I think it would be nice to have a mechanism like this. It would be possible to create tiddlers with a h1 ... so they have a defined structure if they are read alone. ... If they are listed in a different context h1 will become what ever the context needs. ..

**Comment by twMat** [comment]
Isn't this kind of what the `em` and `rem` units are for? I believe these let you have text set to a specific font-size but it then varies depending on context.

**Comment by pmario** [comment]
>Isn't this kind of what the em and rem units are for? I believe these let you have text set to a specific font-size but it then varies depending on context.

No really. It's a possibility that headings dynamically change their "nature" eg: 

tiddler-1 contains: 

```
! Heading 1 in tiddler-1

some text

{{tiddler-2}}
```

tiddler-2 contains:

```
! Heading 1 in tiddler-2
```

The rendered result will look like this: 

---

# Heading 1 in tiddler-1

some text

# Heading 1 in tiddler-2

---

but it should look like this

# Heading 1 in tiddler-1

some text

## Heading 1 in tiddler-2
