### ISSUE TITLE
Unexpected variable expansion with set widget

### ISSUE THREAD

**Issue by Jermolene** [Jermolene/TiddlyWiki5#3333]
An interesting series of problems were reported on Twitter by Zemoxian:

https://twitter.com/zemoxian/status/1006530305547735040

To see what's going on, let's start with a familiar example of variable substitution within a macro:

```
\define foo()
bar $(baz)$
\end

<$set name="baz" value="hello!">
<$text text=<<foo>>/>
</$set>
```

As expected, it displays "bar hello": the string `$(baz)$` in the macro is replaced by the value of the variable `baz`, in this case "hello!".

Unexpectedly, this second example displays the same result:

```
<$set name="baz" value="hello!">
<$set name="foo" value="bar $(baz)$">
<$text text=<<foo>>/>
</$set>
</$set>
```

The unexpected part is that the variable substitution is taking place even though "foo" is a variable defined with the set widget, and doesn't use the normal macro definition syntax.

The implications of this problem are fairly severe: it means that any attempt to access a variable that contains valid variable substitution syntax will be corrupted. There are several places in the core where the text field of a tiddler is copied to a variable for manipulation. Any $(*)$ markup within the tiddler will be removed.

I propose to explore fixing it by restricting the variable substitution to macros that were defined via the \define pragma, and not to variables defined with the set widget. I don't see a way to do it without breaking backwards compatibility, so it will need some careful testing.

**Comment by Jermolene** [comment]
Hi @pmario you're right, the bug (and the change) affects all widgets that set the values of variables, not just the `<$set>` widget.

I think that the new behaviour is correct; the old behaviour was undocumented, and meant that it was not possible to avoid variable substitution when passing variables.

A workaround for your plugin might be to add a new attribute to the `<$set>` widget that selects whether or not text substitutions are performed.

**Comment by pmario** [comment]
Please have a closer look at my example. I'm using the wikify-widget, which by definition needs to wikify everything. 

My plugin uses a mechanism like this: 

rendering template: 

```
`<html tags> some text` $(var-name)$ `some more text <more html tags>`
```

IMO With the new change the wikify-widget is useless. Whatever I do it doesn's substitute the `var-name`

**Comment by pmario** [comment]
See the backtick!

**Comment by Jermolene** [comment]
The only place that was intended and documented to do text substitution is the `\define` pragma. The fact that text substitutions were occurring for all widgets that assigned values to variables (like the wikify widget) was a mistake.

> With the new change the wikify-widget is useless. Whatever I do it doesn's substitute the var-name

To emphasise, the wikify widget has never been documented as performing text substitution; text substitution is not part of wikification (if it was, text substitution would be performed in tiddler bodies). Surely it is still useful with its documented usage of wikifying text?
