### ISSUE TITLE
ButtonWidget: allow multiple "set" attributes

### ISSUE THREAD

**Issue by twMat** [Jermolene/TiddlyWiki5#3343]
The `set`/`setTo` syntax in the buttonwidget is a elegant. But setting additional values is cumbersome; the forced introduction of *action widgets* breaks the simple syntax, its not really intuitive, it makes the button code much more difficult to read and, at least for me, typically forces extra consultation of the docs to get the action widget syntax right. 

Considering how popular the ButtonWidget is and that its most common use probably is to set field values, I propose to enhance its syntax to allow for an *arbitrary number* of set/setTo pairs. The syntax would be to associate any `set` with the subsequent `setTo`.

Example

```
<$button 
  set=textref1 setTo=foo
  set=textref2 setTo=bar >
    ...
</$button>
```

A further simplification would be to use the idea of interpreting "unknown attributes" as arguments (as used in e.g VarsWidget and ActionSetFieldWidget) i.e;

```
<$button 
  textref1=foo
  textref2=bar >
    ...
</$button>
```
Even my mommy would understand this syntax.

Note that other types of button triggered actions would still use action widgets. This is IMO quite acceptable as it goes beyond the most common use case of setting a field.

**Comment by Jermolene** [comment]
Thanks @twMat 

>  I propose to enhance its syntax to allow for an arbitrary number of set/setTo pairs

That would mean changing the way that widget attributes are handled throughout the system: the attributes are stored as a hashmap, which doesn't permit multiple entries with the same name.

> A further simplification would be to use the idea of interpreting "unknown attributes" as arguments (as used in e.g VarsWidget and ActionSetFieldWidget) i.e;

All those widgets that handle "unknown" attributes differently distinguish them by the presence or absence of a dollar sign as the first character. It's too late to do that for the button widget, and so we couldn't do it consistently with the existing widgets.

**Comment by twMat** [comment]
@Jermolene 

...OK, that's a pity but I understand. Closing.

Thanks for fast reply.

**Comment by Jermolene** [comment]
And don't stop suggesting things! It's thought-provoking, and your current success rate is pretty good :smile:

**Comment by twMat** [comment]
Thank you, that is encouraging to hear. (In case you're somehow referring to my silence of late; I'm just busy building a TW system for my current work as a teacher, for pupil assessments. It's both amusing and distressing to find that I can build solutions in TW that are in many ways better than the major commercial systems in use by schools!)
