### ISSUE TITLE
search operator cannot handle brackets properly

### ISSUE THREAD

**Issue by twMat** [Jermolene/TiddlyWiki5#3361]
Surely this is a bug:

This returns *both* `yes` and `no`. I would expect it to only return `no`.

```
\define xor()
<$list filter="missingtid +[search[$(bar)$]]">yes</$list>
<$list filter="missingtid +[!search[$(bar)$]]">no</$list>
\end

<$vars bar='[[bar]]'><<xor>></$vars>
```
I'm guessing `search` can't handle (scrub?) brackets properly. If `bar` is a string without brackets, it works. The "missingtid" represents some - or no - tiddler that does not contain the searched for string.

**Comment by Jermolene** [comment]
Hi @twMat if you think of the macro text once the variable substitution has taken place you'll see the problem:

```
<$list filter="missingtid +[search[[[bar]]]]">yes</$list>
<$list filter="missingtid +[!search[[[bar]]]]">no</$list>
```

Once again, the problem is text substitution. If you instead use a variable reference everything works fine:

```
\define xor()
<$list filter="missingtid +[search<bar>]">yes</$list>
<$list filter="missingtid +[!search<bar>]">no</$list>
\end

<$vars bar='[[bar]]'><<xor>></$vars>
```

**Comment by twMat** [comment]
Given the special role of square bracket characters in TW and especially in filters, shouldn't the ListWidget "handle this", perhaps by scrubbing brackets from incoming arguments. Or maybe pure text subsitution means it can't?
