### ISSUE TITLE
Folding ought to include extra viewtemps

### ISSUE THREAD

**Issue by twMat** [Jermolene/TiddlyWiki5#3365]
[Not urgent but still justifies an issue]

Toolbar button "Fold" ought to make all tiddlers, regardless of extra viewtemps, appear like it does when folding a tid that has no extra viewtemps. I.e basically only the title bar should remain visible. While I can imagine someone wanting some exception for this, full folding should at least be the default behaviour.

**Use case**
I typically add conditional viewtemps e.g to insert descriptions in macro tids about their syntax etc (because otherwise macros appear totally blank and uniinformative). But I still want it minimized like any other tid when I fold it.

**Comment by Jermolene** [comment]
View template segments are responsible for implementing folding themselves. For example:

https://github.com/Jermolene/TiddlyWiki5/blob/master/core/ui/ViewTemplate/body.tid#L4
https://github.com/Jermolene/TiddlyWiki5/blob/master/core/ui/ViewTemplate/tags.tid#L4
https://github.com/Jermolene/TiddlyWiki5/blob/master/core/ui/ViewTemplate/subtitle.tid#L4

So, if you add a new view template segment and you want it to respect the folding state, you'll have to duplicate that reveal widget.

**Comment by twMat** [comment]
Aha, good to know. Thank you for explanation and examples.
