### ISSUE TITLE
Possible (small) Bug: New Journal Button overwrites `created` date everytime 

### ISSUE THREAD

**Issue by diego898** [Jermolene/TiddlyWiki5#3371]
Steps to reproduce:
* go to https://tiddlywiki.com 
* enable and press the new journal button
* place the following content in the tiddler: `I was created {{!!created}}`, as well as any additinoal content. Save, and make note of the reported time.
* Press new journal button again - Note that your already created tiddler contents are correctly retrieved. Save and close
* Note the **new** `created` time. 

This is not a big deal, but just wanted to report what might be an unintended behavior.

**Comment by Jermolene** [comment]
Thanks @diego898, fix coming up.
