### ISSUE TITLE
Bug: List widget not rendering in preview mode

### ISSUE THREAD

**Issue by diego898** [Jermolene/TiddlyWiki5#3372]
If you go to https://tiddlywiki.com/ and replace the contents of `Learning` with the following:

```
<$list filter="[all[current]tagging[]]">
</$list>
```
shows nothing in preview mode or view mode (reason why discussed in google groups - possible bug but not the main one Im reporting)

```
<$list filter="[all[current]tagging[]]">

</$list>
```
shows **nothing** in preview mode, but shows all titles correctly in view mode.

```
<$list filter="[all[current]tagging[]]">

<<currentTiddler>>

</$list>
```
shows **nothing** in preview mode, but shows all text titles correctly in view mode.

Tested on Chrome 67.0 (in incognition - no extensions running)

**Comment by pmario** [comment]
Try this: 

```
<$list filter="[all[current]tagging[]]">

</$list>
```

and tag a tiddler `Draft of 'Learning'` and it works as expected. ..  all[current]  returns `Draft of 'Learning'` and not Learning

**Comment by pmario** [comment]
IMO not a but

**Comment by diego898** [comment]
I see its the `[all[current]]` that is the problem. You can see this as well with `{{!!title}}` in preview mode.

This seems strange, as preview mode no longer corresponds to what you will actually see after saving. I typically use preview mode when I'm building these widgets

**Comment by pmario** [comment]
Edit mode opens a new new tiddler named "Draft of xxx". That's necessary to have the possibility to undo the changes. ... but you are right. There is a difference between preview and view-mode. 

But I still think, that's not a bug.

**Comment by diego898** [comment]
Agreed
