### ISSUE TITLE
Sync StoryList and HistoryList Different Story Views

### ISSUE THREAD

**Issue by kookma** [Jermolene/TiddlyWiki5#3374]
There is an issue in storylist / historylist when switching between different story views!
Assume you are in Classic view and the tiddler under focus is Tid-A then switch to Zoomin view and navigate to some other tiddlers no matter to navigate from in/outside story river and then switch back to classic view! You wont see the same tiddler under focus, instead you will get focused to the tiddler at top of story river in classic view.

This is annoying when you want to edit something returning from zoomin view!

One suggestion is to sync these two! or use the same storylist historylist behavior in two story view.

**Comment by AnthonyMuscio** [comment]
Kookma,

Perhaps there would be value in you cloning Classic view and Zoomin view then editing them to use the same history and story list (perhaps to new history and story lists) to achieve what you want? Perhaps renaming them Classic/Zoom and Zoom/Classic to indicate the toggle.

The reason I suggest this is I am not sure if some people have relied on its current behaviour to build other solutions.

As has often being promoted as one of tiddlywikis strengths is the degree to which the user interface can be customised. So go ahead customise. Feel free to ask for support in the TiddlyWiki Google Group.

Regards
Tony
