### ISSUE TITLE
Inconsistent $:/temp/ behaviour.

### ISSUE THREAD

**Issue by TiddlyTweeter** [Jermolene/TiddlyWiki5#3375]
I create a Tiddler called `$:/temp/mark-test` on Bob and on simple node ... Under node and Bob after closure and restart it is GONE.

I create a Tiddler called `$:/temp/mark-test` on single file TW and on single file under TiddlyDesktop. After closure and restart the Tiddler is STILL THERE.

**Comment by AnthonyMuscio** [comment]
Josiah, I think Bob has simply being set to not save temp tiddlers, where as the default behaviour in a full wiki is to save all tiddlers (that match a filter but should exclude temp see below) however when using $:/temp tiddlers you should assume they are not there when you return and I think the value of this naming standard is for the processes that use the $:/temp tiddler names, which may often even delete the value themself. The default appears to be in $:/config/SaverFilter which on tiddlywiki.com reads
`[all[]] -[[$:/HistoryList]] -[[$:/StoryList]] -[[$:/Import]] -[[$:/isEncrypted]] -[[$:/UploadName]] -[prefix[$:/state/]] -[prefix[$:/temp/]]`
I believe different servers/savers may or may not honour this filter at save time. It makes sense on bob not to write to the server things we know are transient.
TiddlyDesktop may also be ignoring the filter and saving everything, I am not sure.
I just saved the empty file, created a temp tiddler saved over it over itself and reloaded and the temp tiddler is still there - so even a normal save does not honour the filter.

**Comment by TiddlyTweeter** [comment]
@AnthonyMuscio Tx. After your comment I'm no longer sure this is an "issue" as such, since it seems, in some sense, to be by design. However I do think its useful to know what is happening and why--which, TBH, I'm still hazy about. 

An issue is that a novice "tweaker" like me could assume on Bob -- "hey it is great I can create loads of $:/temp without the hassle of having to explicitly delete them" -- but find out that won't auto-transport to a standalone TW I build from Bob that then gets clogged by them.

**Comment by pmario** [comment]
> .. $:/config/SaverFilter is for the "dirty state" (whatever that means :).

"dirty state" is responsible to eg: change the colour of the "save button", so users know they did change something that has to be saved. ... and ... It also activates the "save changes needed" warning when you want to close the tab with TW ...

**Comment by TiddlyTweeter** [comment]
>... TW-file and TW-server "save-behaviour" is a little bit "bumpy" ... IMO there is some room for improvement. 

@pmario, I do grasp there are likely necessary differences. My main issue is its NOT CLEAR to me what they are and how to adjust for them. 

In my use case I'd like to ensure that on "$:/temp" server and single file version save the same way. Its unclear how to do that.

**Comment by pmario** [comment]
>In my use case I'd like to ensure that on "$:/temp" server and single file version save the same way. Its unclear how to do that.

At the moment you'd need to modify [$:/core/save/all](https://tiddlywiki.com/#%24%3A%2Fcore%2Fsave%2Fall) to

```
\define saveTiddlerFilter()
[is[tiddler]] -[prefix[$:/state/popup/]] -[[$:/HistoryList]] -[[$:/boot/boot.css]] -[type[application/javascript]library[yes]] -[[$:/boot/boot.js]] -[[$:/boot/bootprefix.js]] -[prefix[$:/temp/]] +[sort[title]] $(publishFilter)$
\end
{{$:/core/templates/tiddlywiki5.html}}
```

See the additional `-[prefix[$:/temp/]]` 

@Jermolene 
The problem here is, that there is a variable named: `$(publishFilter)$`, which should users allow to add additional filters. .... But I know no way to use it!

**Comment by TiddlyTweeter** [comment]
Thanks @pmario for the simple, useful, reply.

I don't mind they (server & single) are different. I do mind I didn't know they were different. I think it matters. 

People much more experienced than me in [Query 101 -- $:/state, $:/temp, $:/config ....](https://groups.google.com/d/msg/tiddlywiki/t_3ANIqWP1Q/gVoCq5SkAQAJ) illustrate that its not just me who was unclear. Everyone in that thread was stumbling in not quite knowing.

**Comment by Jermolene** [comment]
We don't sync `$:/temp`, `$:/state` etc. in client-server configuration to avoid different users interfering with one another.

When it comes to saving in the standalone configuration, I think it may be a mistake that we save `$:/temp` tiddlers; I was under the impression that they were filtered out of saving.

**Comment by solarpowerinncr** [comment]
I search for the same problem back in 2020 and find this issue. I read the Doc [SavingMechanism](https://tiddlywiki.com/static/SavingMechanism.html) and fix this by defining a global variable. However I can't find out whether the Doc has been updated after this disscusion, so I left my solution here in case anyone else meets the same problem.

**Comment by rmunn** [comment]
Looks like this will be fixed by https://github.com/Jermolene/TiddlyWiki5/pull/4938 once it gets merged.

**Comment by saqimtiaz** [comment]
@Jermolene this is now resolved and can be fixed.

**Comment by pmario** [comment]
@TiddlyTweeter ... You can close this too!
