### ISSUE TITLE
Improvements to Comments Plugin for v5.1.18 Pre-release

### ISSUE THREAD

**Issue by AnthonyMuscio** [Jermolene/TiddlyWiki5#3378]
Jeremy, as author of the comments plugin perhaps this is for you.

I suppose the comments plugin has some value, but it seems to me, to fall short. I would like to suggest some possibly small improvements that could add great value. It would provide a sanctioned way to comment, propose changes and apply changes to any tiddlywiki regardless  of the read only state of a wiki.

1. Add an additional system filter "[has[comment-target]]" such as $:/core/Filters/comment and mention it in the readme so people can export their own comments at least, even from read only (or NoteSelf) wikis. Perhaps a dedicated export comments, page button.

2. Perhaps allow the import process to recognise comments being re-imported such that none are over written, perhaps simply with additional increments added. Perhaps this could be handled with a separate dedicated import comments Page Button.

3. Provision the ability to add buttons to the comment read panel, OR provide a few to allow each comment to be reviewed, accepted, rejected... 

4. Provide a method or convention by which comments can be made that relate to the whole wiki and not to a specific tiddler, and a way, in which to propose new tiddlers as comments as well, that on acceptance become the new tiddler.

5. Provide a way to fold comments away on each tiddler, with an indicator remaining showing the tiddler has comments.

This would allow users to comment on their own or others wikis/tiddlers, or even tiddlywiki.com's documentation tiddlers and save, then even email the resultant set of comments. Then anyone can import the comments and review each tiddler with comments and apply the comments, once done accepting or rejecting the comments they are hidden or deleted. Input from multiple reviewers simultaneously would also work. Comments may also be kept indefinitely.

This would provide a way for independent and read-only TiddlyWikis to be reviewed in detail and review comments collected, exported shared and applied by the wiki owner. For example I could quickly provide examples of using widgets and filters to support tiddlywiki.com documentation and a senior experienced and authorised person with write access can apply or reject my comments against each tiddler and the wiki as a whole.

A bonus would be if a comment can be added to accepted/rejected comments, exported and returned to the reviewer as feedback. Perhaps an email address field in comments could facilitate this along with a url to the source wiki.

Applications:

- TiddlyWiki documentation support
- Inviting/Commenting on others work (Via email), or provide a submit as a file to a server host.
- Ability to treat TiddlyWikis as re-viewable documents whether or not they are hosted on a server or multi-user platform
- Provide a personal workflow tool for reviewing and enhancing ones own wikis, developers and users alike.
- Provide first use notes the learner can use as guidance and delete once understood.
- Use to provide blog comments and moderation on top of tiddlywiki.

Can I help?

Regards
Tony

**Comment by Jermolene** [comment]
Hi @AnthonyMuscio those are excellent suggestions, thank you.

One further question I've been considering is whether to replicate/reuse the drafts mechanism for comments.

> 1. Add an additional system filter "[has[comment-target]]" such as $:/core/Filters/comment and mention it in the readme so people can export their own comments at least, even from read only (or NoteSelf) wikis. Perhaps a dedicated export comments, page button.

I think that's easy and I can do that straight away.

> 2. Perhaps allow the import process to recognise comments being re-imported such that none are over written, perhaps simply with additional increments added. Perhaps this could be handled with a separate dedicated import comments Page Button.

There is some extensibility to the import process that would allow us to do this, but I think I'd prefer to explore more generic solutions to the overwrite-on-import problem:

* An import-wide option to rename incoming tiddlers if they clash with existing tiddlers
* An import-wide option to add a prefix to the title of incoming tiddlers

> 3. Provision the ability to add buttons to the comment read panel, OR provide a few to allow each comment to be reviewed, accepted, rejected... 

Great idea, and fairly easy.

> 4. Provide a method or convention by which comments can be made that relate to the whole wiki and not to a specific tiddler, and a way, in which to propose new tiddlers as comments as well, that on acceptance become the new tiddler.

Aha, nice idea. Those comments might be displayed at the top of the story river by default.

> 5. Provide a way to fold comments away on each tiddler, with an indicator remaining showing the tiddler has comments.

Oooh, excellent idea.

I'm actively using the comments plugin with @xcazin on a private wiki on xememex.com and I'm finding it surprisingly useful, even in its current primitive form.

**Comment by AnthonyMuscio** [comment]
Jeremy,

I am glad you see value in this, and thanks for adding comments in the first place.

A little more info. At the moment when I install Mario's bundler plugin I get access to toggle "Enable Overwrite Check" and there is other features that are related to this "comments" solution, like the import bundle. Of course it is important that the comment is tied to the tiddler it commented on regardless of the import naming.

I understand the $:/import tiddler is generated on the fly and on a number of occasions have wanted to customise it but there is no easy mechanism I could find. However I could see value in allowing some "pre-import" customisations being possible. To support comments and other uses.

Best wishes
Tony

**Comment by AnthonyMuscio** [comment]
Jeremy,

If I may also add,

Any macro or tool created such as the comments should allow it to be invoked with custom label or no label.  This is the problem with the copy to clipboard macro as well. In many cases this text could be removed and the icon and or its tooltip relied on to explain the icon, saving screen space and reducing visual complexity. In other cases we may want to prompt a particular way eg "Feedback".

Regards
Tony

**Comment by Jermolene** [comment]
Hi @AnthonyMuscio thanks for the feedback. I've made some of the suggested changes (see the commit above) and posted a new built to https://tiddlywiki.com/prerelease for you to try out.

**Comment by AnthonyMuscio** [comment]
Thanks Jeremy,

Based on what you provided I created a 'single tiddler' extension to the comments plugin to allow accepted rejected comments (attached).

[Accept-RejectComments.tid.txt](https://github.com/Jermolene/TiddlyWiki5/files/2269245/Accept-RejectComments.tid.txt)

I also attached an example of a documentation update comment tiddler to import 

[Comment by 'Tony' on 'Date Fields'.tid.txt](https://github.com/Jermolene/TiddlyWiki5/files/2269391/Comment.by.Tony.on.Date.Fields.tid.txt)


I would now like to provide a checkbox to toggle +[!has[comment-status]] when the comments are listed on each tiddler, this will allow accepted and rejected comments to optionally be hidden as they are processed.

Would it be possible for you to move that filter into a config tiddler as well. Even if it is not in the readme or config tiddler, it would improve hack-ability?

I will pursue some other solutions in time that leverage the comments plugin.
- Out of the box it is a type of log entry system
- It could be used to list edit/development tasks to be done against each tiddler
- Allow links and tiddlers to be provided inside a comment
and the aforementioned
- Guidance information
- Replys to blog entries

Thanks
Tony

**Comment by Jermolene** [comment]
Hi @AnthonyMuscio I'm considering another change to the comments plugin -- as things stand, a tiddler can't be renamed without breaking links in the `comment-target` field of other tiddlers. So what I propose is to replace the `comment-target` field with a `role` field with the value `comment`, and to put the tiddler(s) to which the comment applies in the `list` field. In that way, comment links will be automatically relinked when a tiddler is renamed.

**Comment by AnthonyMuscio** [comment]
Jeremy,

Will they show as tags? Not that it is is too important.

In a related submission of mine [Actions on title change?](https://github.com/Jermolene/TiddlyWiki5/issues/3399) you could use the same hack I want exposed to do the renaming on tiddler rename.

It would be a good test case actually.

Not withstanding I support your suggestion.

Regards
Tony

**Comment by Jermolene** [comment]
Hi @AnthonyMuscio 

> Will they show as tags? Not that it is is too important.

No, the list field of a tag tiddler is used to order the tiddlers with that tag, but that's the only connection between the list and tags fields.

> In a related submission of mine Actions on title change? you could use the same hack I want exposed to do the renaming on tiddler rename.

Apologies, I haven't studied that thread, I'll leave a comment there.

**Comment by AnthonyMuscio** [comment]
This issue raised a few ideas, not all of which have been addressed. It would be worth checking against the changes made, and perhaps creating one or more new issues then close this.

**Comment by pmario** [comment]
>This issue raised a few ideas, not all of which have been addressed. It would be worth checking against the changes made, and perhaps creating one or more new issues then close this.

I think, that would be the right thing to do. It's not immediately obvious for others, that did not follow the thread closely. .. And its 4+ years old. .. So closing this one and eventually create new issues, with a single actionable request will make sense.

**Comment by Jermolene** [comment]
Thanks @AnthonyMuscio @pmario
