### ISSUE TITLE
Let HTML be free

### ISSUE THREAD

**Issue by AnthonyMuscio** [Jermolene/TiddlyWiki5#3380]
Folks,

Following on from my speculation in dealing with cases such as the [html details](https://github.com/Jermolene/TiddlyWiki5/issues/3353) I would like your views on the following.

If we could find a way to support the integration of HTML with TiddlyWiki for these "primitives" I believe this would be very popular, one way maybe to have some basic functions that "emulate" common html javascript functions OR extend the way WikiText containing HTML is parsed, so that the two work better together.

Eg a way to provision the html details with a toggle value.

The idea would be to leverage the rich html environment and reduce the need for solutions to be built into tiddlywiki when they already live in the HTML5 standards. If you spend time as I have looking at HTML at https://www.w3schools.com/ you will see that on many occasions that the html demands JavaScript which will not (directly) work in tiddlywiki but more often than not this java script seems really basic, allowing a value to be set or stored on click or some other primitive operation. Or the browser contains the value the html has produced from input to states but we have no way to reference it in the wikitext. 

In fact TiddlyWiki has already done as I propose with CSS allowing it to be a fully supported standard in tiddlywiki as well as permitting it to be used in response to tiddlywiki tags and other attributes.

I am not saying this is simple, but it potentially is, and I do not have the experience to implement it.

In some ways Evans formula plugin is doing this by allowing html attributes to be set using tiddlywiki variables and tiddler/fields.

What remains is I believe a need to connect HTML more closely to the tiddlywiki internals.

One slightly more complex example may be html forms and php https://www.w3schools.com/html/html_forms.asp 
```

 <form>
  First name:<br>
  <input type="text" name="firstname"><br>
  Last name:<br>
  <input type="text" name="lastname">
</form> 
```
If we could only access the values above we know are stored in the browser eg firstname lastname

But I think it worthy of investigation, because it would open the world of HTML5 and related frameworks to users while reducing the need for "equivalent" widgets like this threads Details widget. It will simplify what goes into tiddlywiki while at the same time enriching its capabilities. Further once a subset of tiddlywiki/html5 "methods" are available it would be easy to translate a wealth of code from html training and support sites, and users.
 
Please consider deeply, the return could be massive.

Regards
Tony

**Comment by twMat** [comment]
@AnthonyMuscio 
This is probably a very valuable discussion - *but* it is in the wrong forum. We aim to keep github issues be actionable. If you consider the amount of standing issues, I'm sure you can see why. May I propose closing this and reposting in the dev group?

**Comment by AnthonyMuscio** [comment]
Sure. The reason was it somewhat related to the details issue, but I can reference that from TW Dev
