### ISSUE TITLE
Allow currentTiddler as default parameter value

### ISSUE THREAD

**Issue by twMat** [Jermolene/TiddlyWiki5#3389]
When using a tiddler title as argument for a macro, it is *very common* that a desirable *fallback/default* is, specifically, the current tiddler title.

I.e is should be possible to have the `default` value here be the *current tiddler* value

`\define mymacro(tiddler:"default")` 

**...without trickery outside of the macro or in the macro body.**

The direct syntax `(tiddler:<<currentTiddler>>)` - to name one natural example - only works if the macro is used in the same tiddler as it is defined but the syntax should be as direct wherever used **because it is such a common use case** to want current tiddler as fallback value.

**Comment by pmario** [comment]
Every macro definition automatically has access to all variables, that are available in the context where it is used: `$(currentTiddler)$`

**Comment by twMat** [comment]
If you mean this:

` \define mymacro(tiddler:"$(currentTiddler)$") $tiddler$`

I tried that but I think the placeholder parentheses mess up the parameter list parentheses so it doesn't work, or am I doing it wrong? 

Of course it is possible to - inside the macro - test if `tiddler` is empty and then *set* it to... etc, but the idea was to avoid having to do this.

**Comment by pmario** [comment]
```
\define mymacro() "$(currentTiddler)$"
```

**Comment by twMat** [comment]
...but it should only be a fallback. If mymacro is called like so `<<mymacro Foo>>` then it really should be Foo.

**Comment by twMat** [comment]
I've updated the OP to clarify it more.

**Comment by pmario** [comment]
try

```
\define xx(tid:<<currentTiddler>>)<$tiddler tiddler=$tid$><<currentTiddler>></$tiddler>
```

... but I think you make it more complicated, than it needs to be.

**Comment by pmario** [comment]
```
\define xx(tid:<<currentTiddler>>) $tid$
```

That's exactly, what you wanted! ... The rest of the example, is just to show you that it's already part of the core. No changes needed.

**Comment by twMat** [comment]
I'm truly embarrassed. As you point out; it does work. I must have made some error when I tried it at first.
Thank you for your patience @pmario

**Comment by pmario** [comment]
The problem with the `currentTiddler` variable is, that it is "changed" quite a bit.

 ... eg: the `<$tiddler` widget changes it. ... `<$list` widget also changes it if no list-variable is set. ... 

Transcluding with `{{}}` also changes it, while `{{||template}}` doesn't ... So templates can use currentTiddler using the variable from the "calling" tiddler. ....

So may be you used macro definitions in combination with templates. ... Just a guess!
