### ISSUE TITLE
Possible bug when table between tags

### ISSUE THREAD

**Issue by twMat** [Jermolene/TiddlyWiki5#3392]
Please confirm that this is *not* a bug and I'll close:

```
<div>foo

| bar |

</div>
```

If the `foo` is there, then the wikitext table does not parse properly. As soon as `foo` is removed it works. Same goes for any other tag (real or made up).

**Comment by Evolena** [comment]
If you don't have 2 line breaks after the div, then its content is parsed inline, and thus the table markup - which are block content - are not recognized.

**Comment by twMat** [comment]
@Evolena - thank you. Is this an intentional TW feature? Any docs? or is it perhaps some feature of browsers or even behaviour of html?

**Comment by pmario** [comment]
That's how TW wkitext works. It's intentional. see: https://tiddlywiki.com/#Paragraphs%20in%20WikiText

**Comment by twMat** [comment]
>That's how TW wkitext works. It's intentional. see: https://tiddlywiki.com/#Paragraphs%20in%20WikiText

IMO there is nothing about this issue in that doc, but OK - intentional. Thanks for replying!

**Comment by Jermolene** [comment]
@twMat there are some more docs on inline vs. block mode in 
https://tiddlywiki.com/#HTML%20in%20WikiText, but I think we could do with a better explanation

**Comment by twMat** [comment]
@Jermolene , thank you. I made a little PR with the most important difference being the heading used to make it easier to find. I was considering providing a clarifying example directly in the text, similar to the one in this OP but was afraid it would not fit stylistically. What would you say about this? From an educational point it would definitely make sense.
