### ISSUE TITLE
[question] Enable preview window for edited tiddlers in default

### ISSUE THREAD

**Issue by newhinton** [Jermolene/TiddlyWiki5#3397]
The default behaviour is to see the result of the changes made to an tiddler is to click the preview button, or to save the tiddler and close it. Is there a way to open it in default?

I have found $:/state/showeditpreview which defaults to 'no'. If i edit this, i get the message about the shadowtiddler. If i edit it to 'yes', it will not create a copy, and keeps 'no'. If i create the tiddler manually, it will say yes, and is shown as edited, but the previewpane in the editor is not opened in default.
Is there any way to enable it?

**Comment by pmario** [comment]
If you open the preview pane in edit mode and save your TW it will store the state variable. So the next time if you open a tiddler, it will also open the preview pane. 

There is no default "show preview on open edit" option at the moment. We would need 2 settings:

 - show preview on open edit
 - hide preview on open edit

**Comment by pmario** [comment]
@Jermolene IMO this is a feature request.

**Comment by AnthonyMuscio** [comment]
newhinton,

The advantage with tiddlywiki is you can do what ever you want.

If you look into the toolbar button preview you will see the whole thing is driven by a state tiddler

```
<$reveal state="$:/state/showeditpreview" type="match" text="yes" tag="span">
{{$:/core/images/preview-open}}
<$action-setfield $tiddler="$:/state/showeditpreview" $value="no"/>
</$reveal>
<$reveal state="$:/state/showeditpreview" type="nomatch" text="yes" tag="span">
{{$:/core/images/preview-closed}}
<$action-setfield $tiddler="$:/state/showeditpreview" $value="yes"/>
</$reveal>
``
You could clone the existing edit button and edit it to manipulate the state tiddler using a second <<qualified >> state tiddler. If your state tiddler is set that will determine if the (cloned) edit button sets the preview state). Then set the standard edit tiddler button to hide behind the more and your new edit button to appear on the view toolbar.  

Done?

Although it will open preview on every tiddler in edit mode, is still achieves what you want.

Regards
Tony

**Comment by newhinton** [comment]
@pmario I did not realize that this was actually kept between edits! It's good to know :D
@AnthonyMuscio Thank's for the hint, but shouldn't that already be controlled by the value of the "$:/state/showeditpreview"-tiddler? I already overrode that one, but it had no effect

**Comment by AnthonyMuscio** [comment]
Newhinton,

Actually read my comments carefully, I am talking about you having an alternate to the edit button which enforces the behaviour you want (with its own state tiddler, perhaps one <<qualified preview>>) and you may create a toggle as well to toggle this open preview on edit using the <<qualified preview>> state tiddler)

Since the Preview button uses the $:/state/showeditpreview to work is should work if you custom edit button does <$action-setfield $tiddler="$:/state/showeditpreview" $value="yes"/>

I understand their is a little "design gymnastics" here, and I am only sharing an outline but not the details, to this solution/work around.

Best wishes, tony
Tony

**Comment by pmario** [comment]
@AnthonyMuscio ... It seems github "ate" some content between `<>` .. please check your post and use backticks for code :)

**Comment by newhinton** [comment]
@AnthonyMuscio At first, thank you for your help!
I have experimented with Buttons and tried to implement it like you advised me to, and i had success with adding a button which changes exactly like the "old" preview-button, while using a different state tiddler. However, i need to somehow toggle the preview to actually show the preview or trigger the preview-button, but i could not find anything in the docs. Could you give me a hint there how to do that, or if its documented, where to find that?

**Comment by AnthonyMuscio** [comment]
newHinton, I will have to do that tomorrow now (+12 hours), but if you can provide the content of your current toggle it will give me a head start, and I can debug that if necessary.

Regards
Tony

**Comment by newhinton** [comment]
it's not much, its really only the button which sets a state. Besides that, there is no code which does anything good

> 
> <$reveal state="$:/state/showEditPreviewInDefault" type="match" text="yes" tag="span">
> {{$:/core/images/preview-open}}
> <$action-setfield $tiddler="$:/state/showEditPreviewInDefault" $value="no"/>
> </$reveal>
> <$reveal state="$:/state/showEditPreviewInDefault" type="nomatch" text="yes" tag="span">
> {{$:/core/images/preview-closed}}
> <$action-setfield $tiddler="$:/state/showEditPreviewInDefault" $value="yes"/>
> </$reveal>

(Tagged with "$:/tags/EditorToolbar")
The missing part is now to make the editpreview to listen to this tiddler.
I have tried to set the value which defindes the state in the old button, but this does not work.

> <$reveal state="$:/state/showeditpreview" type="match" text="yes" tag="span">
> {{$:/core/images/preview-open}}
> <$set name="tv-tiddler-preview" $value="no"/>
> </$reveal>
> <$reveal state="$:/state/showeditpreview" type="nomatch" text="yes" tag="span">
> {{$:/core/images/preview-closed}}
> <$set name="tv-tiddler-preview" $value="yes"/>
> </$reveal>

I really appreciate your help!

**Comment by Jermolene** [comment]
Hi @newhinton it sounds like the problem is that you are running under Node.js, and you want to make the edit preview pane be switched on by default, so that you don't need to switch it back on each time you start.

The reason why just editing `$:/state/showeditpreview` doesn't work is because `$:/state/` tiddlers are not synced from the browser back to the server in client server configuration. This is done so that multiple users' state doesn't interact.

The workaround is to manually create a .tid file in your wiki folder and then restart the server:

```
title: $:/state/showeditpreview
text: yes
```

**Comment by newhinton** [comment]
@Jermolene You are right! that solved it!
I have tried this earlier, but i copied an existing tiddler, and the format differs ('yes' instead of 'text: yes') so that failed. But it works now, which is great! Thank you!

@AnthonyMuscio Thank you too, i have used the information you gave me to improve my wiki further!
