### ISSUE TITLE
Actions on title change?

### ISSUE THREAD

**Issue by AnthonyMuscio** [Jermolene/TiddlyWiki5#3399]
Folks,

There is a common issue with the renaming of titles, that a number of solutions exist to deal with a tiddler title being renamed. Some unique ids, using tags so the name change is reflected, even some methods to search and replace. I am looking at building a quite sophisticated solution and realised if we had a primitive that would generate a trigger on rename, it would be the hack we need.

The idea would be if we can capture a rename occurring and trigger an action tiddler, like $:/tags/StartupAction process does. I imagine we can leverage the Draft.of rename process to do this and the odd widget or message.

eg $:/tags/RenameAction but providing the new and old tiddler names.

People could then write code to update or maintain the wiki when such an event occurs.

Regards
Tony

**Comment by pmario** [comment]
>The idea would be if we can capture a rename occurring and trigger an action tiddler,

Have a closer look at the navigator.js widget. It contains a lot of `$tw.hooks.invokeHook()` actions. So there should be every hook, that you need for your project. IMO no hacks needed. 

boot.js contains: `$tw.hooks.addHook()`  function to add them. 

the `savetrail.js` plugin should be a good example, how to register you own hooks.

**Comment by pmario** [comment]
A much simpler example is: https://github.com/wikilabs/plugins/blob/master/wikilabs/bundler/tiddlers/bundles-import.js

**Comment by AnthonyMuscio** [comment]
Mario, Thanks - perhaps I will go there eventually. 

However I was looking to a non javascript solution, using  action widgets. Or a minor change to the core to open this up to users.

Regards
Tony

**Comment by pmario** [comment]
>However I was looking to a non javascript solution, using action widgets. Or a minor change to the core to open this up to users.

Oh .. I think it's hard to do all the necessary stuff with wiki-syntax. renaming tags is already part of the core. ... So I thought you'd want to add a similar mechanism for "tiddler renaming".  

I think it needs to be done at the js-level. 

--------------

I'm not 100% sure, what you'd like to do. May be you could specify it a bit closer.

**Comment by AnthonyMuscio** [comment]
Mario,

Yes, the solution may/will be in Java script, but I do not know how to do that, Sorry I got confused. 

I just realised the rename mechanism is already there because of the prompt to update  tags and list fields. eg;
_Update New Tiddler 54 to New Tiddler 55 in the tags and list fields of other tiddlers_ 

I am asking if we could have a tags/wikitext method, to react to a rename event. It looks like it may just be allowing users to add actions along side the above update in the tags and list fields of other tiddlers.

So if for example I built the "branch field" (mentioned elsewhere) I could activate a process to update all related fields.

Regards
Tony

**Comment by pmario** [comment]
>So if for example I built the "branch field" (mentioned elsewhere) I could activate a process to update all related fields.

Yea and there's the problem. ... We know for sure, that tags and list fields contain tiddler names. ... BUT for any other field we don't. So we would need a "marker" that a user-field also only contains tiddler names. Otherwise we may overwrite "plain text" that happens to look like a tiddler name. 

The same thing is true for the tiddler text field. It's extremely hard to know for sure, what to replace and what not ... 

The solution may be a "diff-list" that is shown to the user and the user decides.

**Comment by AnthonyMuscio** [comment]
Mario,

Thanks for considering this. To be clear with a tag that indicated "action tiddler" it would be up to the "designer" to work out how to tackle this. For example I could have a tiddler called $:/PSaT/branchhandling/renametiddler-action tagged to be actioned when any tiddler changes its name and make the previous and new title available. I would first check if the current tiddler has a branch field, then list all tiddlers with a field suffix "-branch" then search each all of the branch fields for the previous title and update it to the new title.

I actually have a method to do this but it needs a button and to revalidate all branch fields from the root. It would be more efficient to respond to any tiddler rename event (which are usually far and few between).

If noting else I could use this mechanism to set a "dirty branch" flag and give the user a button to "re-index the branch".

The reason I have raised this in Git-Hub is it needs to leverage something in the core, but as we have both realised there is already actions that respond to rename events to update tag fields. I just want access as a super-user to the same "event". If is possibly in the draft mechanisium and/or we can use draft.of and draft.title fields.

I note: $:/core/ui/EditTemplate/title contains $:/config/RelinkOnRename (a state tiddler) so it is somewhere around there. I could even make a test that the if renamed tiddler has a branch field then offer a button to regenerate the branch fields.

Regards
Tony

**Comment by AnthonyMuscio** [comment]
I have already found the way to respond with a button to the need to handle renamed tiddlers.

I edited $:/core/ui/EditTemplate/title to include 
`{{||test-on-rename}}`

test-on-rename contains
```
test-on-rename: "<<currentTiddler>>"<br>
<$list filter="[is[current]fields[]suffix[-branch]limit[1]]" variable=null>
Action required:<br>from: "<<fromTitle>><br>" To: "<<toTitle>>"<br>
    <$list filter="[is[current]fields[]suffix[-branch]]" variable=branch-field>
       <li><<branch-field>></li>
    </$list>
</$list>
```

And a test tiddler I rename has one or more -branch suffixed tiddlers.

In the case of updating the title in the tags and list fields of other tiddlers there is only a checkbox, and the updating the title in the tags and list fields takes place somewhere else in an action.

I simply want to be able to add my own actions on rename equivalent in design and processing requirement to the existing method.

Regards
Tony

**Comment by pmario** [comment]
It's ok, to try to fix things "automatically" for newbie users. ... But there is a major systematic problem. 

Eg: 
You have 3 tags: A, B, C ... that are _no_ tiddlers yet. 

- Now you create a tag-tiddler A
- You rename A to B ... with "auto-fix" ON 
- You find out, that this was a mistake, it should have been C
- You change B to C with "auto-fix" on

As a result all your tags are now C, because you accidentally also changed all your As to Bs to Cs. 

What you wanted should have been: A -> C, without touching the Bs. ... 

That's a systemic problem. IMO The only way to control this is a global "diff search and replace" mechanism, where the user has a "per item" control. ... Similar to the import list. 

Since diff-match-patch lib is now part of the core, this should be possible.

**Comment by AnthonyMuscio** [comment]
Mario,

I always stand to be corrected, but I do not understand. I am not able to write js code into tiddlywiki and if I were to build a plugin I think I would still need to overwrite a core function. What I seek is the ability to provide my own response to renamed tiddlers, triggered on rename.

Perhaps a global dif mechanisium would be helpful for the cases you mention however In the case I am working on you must have a tiddler to add a field to it (your case of _A, B, C ... that are no[t] tiddlers yet_ would just never happen), the fields are contained inside an existing tiddler, and may included tiddlers named elsewhere. Selected from existing tiddlers. All I want is the opportunity to write the code necessary to take a name change and action it, triggered by a name change. This would mean in a similar example to yours, all tiddler references to A would become B, and I could then rename B to C all tiddler references to a would become C, and all would be fine.

In fact in my current use case I do not want the fields treated as a tags or list field because  I do not want them reordered, capturing and maintaining the order is in fact why I am doing this.

As the designer/user it would be incumbent on me to ensure the integrity is maintained, but as it stands I can at best create a batch regeneration process, where as if I had the hook, I could respond every time a rename occurs, and only deal with the specific tiddler name changing.

One strength we have is tiddler names are unique, and when you rename them they are also unique, or you overwrite one that is unique. Thus using this information to effectively do a constrained search and replace is somewhat trivial.

In fact I could use the GenTags plugin to do this if I was interested in tag like structures. Or I could ask that the branch field get special treatment, but rather than do that I just want the hook.

If you are interested in my vision I will post a separate comment. Thanks for you patience.

Tony

**Comment by AnthonyMuscio** [comment]
@Jermolene Thanks, I expect I may be able to replace the edit button to achieve this (un-researched by me yet), however I have done this in the past for other reasons, so it makes sense. Perhaps for no other reason that to prohibit some tiddler renames unless done through my own rename process.

I still feel what I ask is a hook that can be used by non JS writers, which I am at present, and whilst I do write plugins they typically do not include JS.

If you are interested in my vision I will post a separate comment. Thanks for your patience.

Tony

**Comment by Jermolene** [comment]
> I still feel what I ask is a hook that can be used by non JS writers, which I am at present, and whilst I do write plugins they typically do not include JS.

As I say, it's not a bad idea, and interesting to explore. I should have added that implementing and testing this feature for the core would be relatively demanding. Hence my suggestion for exploring other routes to gain the functionality you need.

**Comment by AnthonyMuscio** [comment]
My Vision for tiddlywiki that demands a hook into the rename function.
(Optional reading)

If TiddlyWiki were a regular database we would possibly use unique, numerical and unreadable primary keys to store and reference our data. One of tiddlywikis strengths is every tiddler has a unique key, as they should as the unit or atom of tiddlywiki - the title is this unique key. Users and designers alike also have full and unabated access to create _readable_ primary keys.

Because these keys are readable they can also be the result of a typo, or an ill considered naming convention, bad spelling or grammar, or a change of mind. Thus they need to be able to be renamed. TiddlyWiki handles this well, and in the case of tags very well, allowing relationships within the tags to remain valid after a rename. 

In many databases you rarely if ever rename a key, perhaps never even "delete" them.

TiddlyWiki is very strong at allowing us to create any type of conceivable data structure from heirachical, random, relational, network to structures as yet un-imagined. except....

Except the key may be renamed on you and the various places the key is specified will then name a missing key. I can create buttons for new tiddlers that maintain and enforce a structure, I can do almost everything except detect when I need to maintain my "referential integrity" when a key changes. This actually rarely cause a problem for me because of my Information, Knowledge and Database experience but it is a limitation.

I want the ability to respond conditionally to a key change such that any one of these data structure models I may design in the future can be supported to maintain referential integrity.

Personally I have half a dozen revolutionary (I hope) data structures in my head for which TiddlyWiki gives me 99% of what I need to prototype, build and demonstrate them, _if I can maintain referential integrity_. Such structures stand to capture information and knowledge so far not addressed well in computing.

Regards
Tony

**Comment by AnthonyMuscio** [comment]
Post Script, Although it would be somewhat more complex than necessary my comment just now in https://github.com/Jermolene/TiddlyWiki5/issues/3385 is actually a work around, If I cant persuade you of this change.

**Comment by flibbles** [comment]
I hope [this new plugin ](https://flibbles.github.io/tw5-relink/)could be a solution to this problem. It actually pours through all the tiddlers' text and performs all renames, taking wikitext into consideration.

It doesn't support renaming macro arguments yet, but I _think_ that should be possible too. Transcludes, links, widgets, fields, and filter are all supported already.

**Comment by AnthonyMuscio** [comment]
@flibbles I totally agree, and your solution provides insight to how we need to provide a hackable or hookable improvement to the core so a plugin (If it must be) can add functionality as you have whilst avoiding overwriting core tiddlers.

**Comment by AnthonyMuscio** [comment]
Before I close this because @flibbles  plugin addresses the immediate need, I still would like to see a hackability method here so apart from any thing @flibbles cantap into the rename process without editing a cord tiddler. But I see a lot of value to use an open mechanism here for other solutions to maintain referential integrity when tiddler title change.

Can I have someone who can submit a change help me please?

**Comment by Jermolene** [comment]
> Can I have someone who can submit a change help me please?

I think your request is already covered by #3967, which is a current focus for me.

**Comment by AnthonyMuscio** [comment]
@Jermolene I will close it soon then if no one else comments, Especially while working on  #3967, if you can take into account the key issues in this thread.
- capture a rename occurring and trigger an user action tiddler
- Provide the ability to provide additional user actions to standard buttons (indirect)
- Provide the ability to trigger a user action on open tiddler (indirect) the only standard action that a button is not in the picture for.

This would result in a comprehensive hack-ability of actions based on standard triggers. Perhaps with the exception of dropping content.

**Comment by Jermolene** [comment]
Hi @AnthonyMuscio just to warn you, it may well be a multi-step journey to get to the point where everything you need is possible. These are deep changes which will require careful work to get right.

**Comment by AnthonyMuscio** [comment]
Jeremy,

I must defer to you and others for deep understanding for changes. However I already have identified methods to achieve these changes **via wikitext and small edits to core tiddlers**. I have not attempted to propose these changes because
- Perhaps I would overlook some standard naming practices etc... eg language
- I am not clear on submitting changes to the standard distribution (I know how to do tiddlywiki.com)
- If I was to submit changes could this stimulate a review of my changes careful work to get right? Or is this not the most productive approach. Would plugins that override the standard distribution be the best first demonstration?

Regards
Tony

**Comment by AnthonyMuscio** [comment]
The relink plugin goes a long way to achieving what this thread was about. It may still be valuable creating way to trigger an on rename event, just as relink is already doing and make this available to designers.

However I am closing this as mostly resolved and too old to retain open
