### ISSUE TITLE
core: change "is[current]" to "all[current]" everywhere

### ISSUE THREAD

**Issue by twMat** [Jermolene/TiddlyWiki5#3402]
[Ref](https://groups.google.com/d/msg/tiddlywiki/XuHiTCI4N60/dS58oZQJBAAJ)

If the argument in the above referenced link is true, i.e that

`all[current]` is more efficient than `is[current]`

then this should probably be implemented also in core. A quick search shows a few key tiddlers that contain `is[current]`

**Comment by Jermolene** [comment]
Thanks @twMat
