### ISSUE TITLE
Smartphone user experience: sidebar & it's show\hide button unreasonable position placement

### ISSUE THREAD

**Issue by HiRolla** [Jermolene/TiddlyWiki5#3405]
Hello! I like this project, Thank you, dear Contributors! Sorry for my English.. 
IMO: In mobile view, when we scroll down, it would be reasonable to 
A) make hide/show << | >> button not "sticky" to the top of the browser window, because we don't see sidebar anyway, but just lose the current scroll position. Also the << | >> button interferes the tiddler buttons without such usefulness;
B) or leave the button as it is and make sidebar to extend over all tiddlers on the top by z-order.

For me A seems to be easier to do. But B looks more convenient for me as a user.

**Comment by BurningTreeC** [comment]
Hi @HiRolla , on https://burningtreec.github.io/KeeBoord I've made the sidebar become a popup when the screen is narrow (below the sidebar breakpoint) ... The sidebar can be opened/closed with the top right button - it can also be closed by clicking/tapping above or below. Would something like that fit your idea?

BTC

**Comment by HiRolla** [comment]
Thank you, @BurningTreeC! Yes, popup is even better! How I can do this for my TiddlyWikis? Maybe this should become a part of empty TiddlyWiki by default?

**Comment by HiRolla** [comment]
Additionall , I would change the << >> button icon when the screen is narrow. Maybe even it should be a main favicon or some standard menu/navigation icon.

**Comment by BurningTreeC** [comment]
First you need a TiddlyWiki v5.1.17 or newer
The DynaView plugin is needed, and in its configuration tab, enable the saving of the Viewport Dimensions

Then you need 4 Tiddlers:

https://burningtreec.github.io/KeeBoord/#%24%3A%2Fcore%2Fui%2FPageTemplate%2Fsidebar
https://burningtreec.github.io/KeeBoord/#%24%3A%2Fcore%2Fui%2FPageTemplate%2Fsidebar-popup
https://burningtreec.github.io/KeeBoord/#%24%3A%2Fcore%2Fui%2FTopBar%2Fmenu
https://burningtreec.github.io/KeeBoord/#%24%3A%2F_styles%2Fsidebar-popup

you can change the << >> button in the $:/core/ui/TopBar/Menu tiddler, in the lower section

**Comment by HiRolla** [comment]
@BurningTreeC, I have set up DynaView and imported that 4 tiddlers, but got no sidebar at all and no popup.
[empty (1).zip](https://github.com/Jermolene/TiddlyWiki5/files/2306301/empty.1.zip)

**Comment by BurningTreeC** [comment]
oh right, sorry - I'm using the 5.1.18 prerelease version of tiddlywiki, where the sidebar got modularized and that's missing in your v5.1.17, that's why it doesn't show up...

you can either download an empty prerelease wiki from tiddlywiki.com/prerelease or change the part of the $:/core/ui/PageTemplate/sidebar and $:/core/ui/PageTemplate/sidebar-popup that looks like this:
```
<$list filter="[all[shadows+tiddlers]tag[$:/tags/SideBarSegment]!has[draft.of]]" variable="listItem">

<$reveal type="nomatch" state=<<config-title>> text="hide"  tag="div">

<$transclude tiddler=<<listItem>> mode="block"/>

</$reveal>

</$list>
```
to:
```
<h1 class="tc-site-title">

<$transclude tiddler="$:/SiteTitle" mode="inline"/>

</h1>

<div class="tc-site-subtitle">

<$transclude tiddler="$:/SiteSubtitle" mode="inline"/>

</div>

{{||$:/core/ui/PageTemplate/pagecontrols}}

<$transclude tiddler="$:/core/ui/SideBarLists" mode="inline"/>
```

**Comment by HiRolla** [comment]
@BurningTreeC 
Got it! 
THANK YOU
