### ISSUE TITLE
When option "Sticky titles" is on, then titles overlap the tiddler dropdown menu.

### ISSUE THREAD

**Issue by HiRolla** [Jermolene/TiddlyWiki5#3406]
When option "Sticky titles" is on, then titles overlap the tiddler dropdown menu. Here is screenshot. Maybe menu should be on top.

![image](https://user-images.githubusercontent.com/7746812/44359067-a00e8f00-a4d8-11e8-94d1-b26a93f17a98.png)

**Comment by twMat** [comment]
double post #2747 please close this one,

BTW, my hacky solution at bottom there actually works quite well.
