### ISSUE TITLE
indexes.js return sorted results by default

### ISSUE THREAD

**Issue by kookma** [Jermolene/TiddlyWiki5#3407]
the indexes operator when is used in a filter returns the result in alphabetical order while we can use sort[title] if required! Many times the indexes are required in the order they stored!

Please correct the index.js code in the core!

Thank you

**Comment by Jermolene** [comment]
Hi @kookma the fundamental problem is data tiddlers (whether in JSON or data dictionary format) are internally implemented as JavaScript objects, and JavaScript objects don't have a well defined ordering to their property names -- there's a few StackOverflow articles about it e.g. https://stackoverflow.com/questions/5525795/does-javascript-guarantee-object-property-order

In other words, those situations where the order of indexes is retained are actually bugs -- thanks to non-standard browser behaviour, they won't necessarily work the same way in all browsers.

**Comment by kookma** [comment]
Hello Jeremy!
Many thanks for clarification!
I will use other solution in my case.
