### ISSUE TITLE
Reduce unneeded refreshing of transclude widget

### ISSUE THREAD

**Issue by Jermolene** [Jermolene/TiddlyWiki5#341]
Several people have run into the issue with adding an edit widget to a tiddler that targets a field on that same tiddler. The problem is that any change to the edit widget automatically triggers a refresh of the transclusion, causing the edit widget to lose focus.

See discussion here:

https://groups.google.com/d/msg/tiddlywikidev/-nWqbNg-DwI/Kwmg_Tzi_pEJ

The fix is the transclude widget to retain the previous text of the field/index being rendered, and then do a further check in refresh() to avoid refreshing the transclusion if the text has not in fact changed from its previous value

**Comment by tobibeer** [comment]
@Jermolene, I'm all for keeping the number of widgets low and providing polymorphic capabilities that are well documented and easy to grasp. Besides, the reveal widget already has this polymorphic nature by virtue of being used for popups and sliders.

**Comment by IreneKnapp** [comment]
This is an old issue and I haven't exactly been active on TiddlyWiki in the past year and a half, so I should mention that I'm still around.  Life has been busy, but I'm glad to have been reminded about TW!

As far as the question @Jermolene posed, I think there are points to be made both for and against polymorphism, and I don't feel strongly invested in which we choose.  I suspect I'll develop an opinion as I get back into things, but at the moment I'm happy either way.

**Comment by Jermolene** [comment]
Welcome back @IreneKnapp! I'll be interested in your thoughts as you get back back into things.

**Comment by xeor** [comment]
Pretty sure this is still an issue? Or is this fixed somehow?

I'm trying a simple

```
\define journalLogButton()

<$edit-text tiddler="$:/state/new-journal-log-title" tag="input" default=""/>

<$button>
<$action-sendmessage
  $message="tm-new-tiddler"
  title=<<now "YYYY-0MM-0DD $(titleSuffix)$ ">>
  tags="Journal"
  journal-type="log"
  year=<<now "YYYY">>
  month=<<now "0MM">>
  day=<<now "0DD">>
/>
New log
</$button>

\end

<$set name="titleSuffix" value={{$:/state/new-journal-log-title}}>
<<journalLogButton>>
</$set>
```

but the text-box looses focus after each keypress.

Is this the same issue, or shall I create another issue?

**Comment by pmario** [comment]
This is still an issue, but there are some discussions going on, how it can be changed.

**Comment by xeor** [comment]
Thanks for the update.

I started using tw5 2 days ago. Is there any obvious way I could have done the above for bypassing the bug in this issue?
As I read it, the issue should not apply to my usecase since I am not editing the tiddly the controls are located on.

**Comment by pmario** [comment]
Hi, @xeor ...  I'll have a closer look, but you use the "temp tiddler"  in the tiddlerr,,  that contains the edit widget. ... So this tiddler will be updated. ... See your `<$set name=` construct. .. thats the problem.

**Comment by xeor** [comment]
Thanks @pmario. But no need anymore :)
Eric Shulman had the answer and an explanation, see https://groups.google.com/d/msg/tiddlywiki/2otSTpG1_a8/VuLKHFFYBgAJ

The solution was basicly to move edit-text out of the function so it was outside "set"

**Comment by pmario** [comment]
this works. 

```
\define getTitle()
$(title)$ $(titleSuffix)$
\end

\define send()
<$vars title=<<now "YYYY-0MM-0DD">> titleSuffix={{{[[$:/state/new-journal-log-title]get[text]]}}}> 
<$action-sendmessage
  $message="tm-new-tiddler"
  title=<<getTitle>>
  tags="Journal"
  journal-type="log"
  year=<<now "YYYY">>
  month=<<now "0MM">>
  day=<<now "0DD">>
/>
</$vars>
\end

\define journalLogButton()

<$edit-text tiddler="$:/state/new-journal-log-title" tag="input" default=""/>

<$button actions=<<send>> >New log</$button>
\end


<<journalLogButton>>

```

**Comment by pmario** [comment]
Yea, I was thinking that you want to call the stuff with a simple macro call without any wrapping set widget. The above solution does this.

I did update the above example, to make it simpler.

**Comment by saqimtiaz** [comment]
@Jermolene this can be closed as it is resolved in TW v5.2.0. Surprisingly I had not seen this issue before today.

**Comment by Jermolene** [comment]
Thanks @saqimtiaz – it's very satisfying closing issues that are nearly 8 years old!

**Comment by IreneKnapp** [comment]
Haha, wow! I'm pretty happy to see this closed too! Sorry I vanished, I got busy with life stuff.

**Comment by CodaCodr** [comment]
I'm so glad it's fixed - marvelous job.

But @Jermolene, I have a question:

If I understand what was going on correctly, the problem was never about "focus" even though that's what's been mentioned in a thousand threads here, there and everywhere. If I understand the TW internals correctly, a refresh causes a _new_ `<input>/<textarea>` to be constructed and added to the dom (the old one being replaced). So the old control ceased to exist after the refresh cycle completes -- correct? 

It's what in automation/testing parlance is referred to as a "stale element"; any references to it are "void".
