### ISSUE TITLE
TW 5.1.18 and language plugin

### ISSUE THREAD

**Issue by MikeCh74** [Jermolene/TiddlyWiki5#3410]
I found that after installing language plugin (e.g. Russian) the following error occurs

> _http_outgoing.js:463
>     throw err;
>     ^
> 
> TypeError [ERR_INVALID_CHAR]: Invalid character in header content ["WWW-Authenticate"]
>     at storeHeader (_http_outgoing.js:410:5)
>     at processHeader (_http_outgoing.js:405:3)
>     at ServerResponse._storeHeader (_http_outgoing.js:311:9)
>     at ServerResponse.writeHead (_http_server.js:270:8)
>     at BasicAuthenticator.authenticateRequest ($:/core/modules/server/authenticators/basic.js:84:12)
>     at Server.requestHandler ($:/core/modules/server/server.js:174:30)
>     at Server.emit (events.js:182:13)
>     at parserOnIncoming (_http_server.js:652:12)
>     at HTTPParser.parserOnHeadersComplete (_http_common.js:109:17)

This error occurs only if I start tiddlywiki server with username/password parameters

> tiddlywiki editions/tw5.com-server  --listen root-tiddler=$:/core/save/lazy-images username=xxx password=xxx

**Comment by Drakor** [comment]
*Quick fix:*
Name your wiki with only ASCII (as in no russian unicode) characters. I realize this is probably slightly nonsensical, but I imagine this might be fixed soon.

*Developer notes:*
https://github.com/Jermolene/TiddlyWiki5/blob/0f7ce7b67fb9a6b7c5cb944fc897eb23775ce3a8/core/modules/server/authenticators/basic.js#L85
HTTP-Headers don't really support other character encodings besides [ASCII](https://tools.ietf.org/html/rfc7230#section-3.2.4).
This might also relate to #1930.

**Comment by MikeCh74** [comment]
@Drakor Thank you!
