### ISSUE TITLE
Embarrasing CodeMirror keymap Vim plugin

### ISSUE THREAD

**Issue by braykov** [Jermolene/TiddlyWiki5#3413]
When I install the plugin (together with codemirror plugin), this shows in the river:

```
Internal JavaScript Error
Well, this is embarrassing. It is recommended that you restart TiddlyWiki by refreshing your browser
Error executing boot module $:/plugins/tiddlywiki/codemirror/keymap/vim.js: "Cannot find module named '../addon/search/searchcursor' required by module '$:/plugins/tiddlywiki/codemirror/keymap/vim.js', resolved to $:/plugins/tiddlywiki/codemirror/addon/search/searchcursor"

undefined
```

**Comment by BurningTreeC** [comment]
Hi @braykov 
A few months ago we split the CodeMirror plugin into the base Editor plugin and several "AddOn" plugins. Some of those AddOns have other AddOns as dependencies.

The Vim KeyMap needs the "closebrackets" and the "search and replace" AddOns installed

Simon

**Comment by sukima** [comment]
For what it is worth I found that CodeMirror's Vim key bindings to be atrocious. Even when they do work it is like learning a upside-down poor imitation of vi likely conceived by someone who has never actually used vi (or Vim) before.

I found it to be better to just copy/paste into an actual Vim (or gVim) instance. There are also many browser addons to help with this if you want the preview to work better.

**Comment by BurningTreeC** [comment]
@sukima - keybindings for the vim keymap are sort of hardcoded in vim.js. The most important part to make it more vim-like is to change the "cancel-edit-tiddler" tiddlywiki shortcut from "Escape" to something else, so that leaving insert mode works and one can do some basic vim commands in normal mode using ":" - like "%s/something/else/g", which works. but many other commands don't work

**Comment by braykov** [comment]
I disabled the plugin, then I wanted to uninstall it, but I couldn't find how. I expected to find an Uninstall button near the Disable button. Instead I deleted the tiddler itself. I am still not sure if this is enough.
However, I think dependencies should be installed automatically, otherwise what's the point? And how am I (as a user) supposed to guess what they are and that I need to install them manually?

**Comment by tejasvi** [comment]
@braykov Plugins are implemented as tiddlers. You need to delete the plugin tiddler for uninstallation. (Don't forget to make backups before)

**Comment by ght** [comment]
It seems this support question has been resolved and the issue can be closed.

Do dependencies still have to be manually installed? If so, that should be tracked in a new issue.

**Comment by Jermolene** [comment]
Thanks @ght – plugin dependencies are indeed now automatically installed.
