### ISSUE TITLE
Loading message!

### ISSUE THREAD

**Issue by AnthonyMuscio** [Jermolene/TiddlyWiki5#3417]
Folks,

As per the discussion https://groups.google.com/forum/?hl=en#!topic/tiddlywiki/QIZQX7Jy61s

I think something along these lines should be part of the core or a core plugin. Any tiddlywiki on a slow internet connection currently suggests to the user something is broken. This solution uses an animated gif during loading to reassure the user is not on a broken site.

I believe the reason it should be in the distribution is because we do not know when and where and how tiddlywiki will be used and when it is we do not want it receiving unnecessary criticism because people have a lack of patience with blank screens. 

I am almost tempted to build a custom animated gif like that in the example (Sourced by Bimlas) and ass some text like;

> This whole site is loading into your browser for high performance, Please wait a moment.

Thanks Eric and Bimlas.

I zipped my own json bundle attached
[splash-screen.bundle.zip](https://github.com/Jermolene/TiddlyWiki5/files/2342093/splash-screen.bundle.zip)

**Comment by felixhayashi** [comment]
Hi @AnthonyMuscio please see https://github.com/Jermolene/TiddlyWiki5/issues/2254

**Comment by pmario** [comment]
I like the background image. ... Which license does it have? ... Where do you get it from?

**Comment by pmario** [comment]
Playing a little bit with the possibilities I found this one: https://codepen.io/cassidoo/pen/KRdLvL ... from this page: https://cssauthor.com/loading-animation/

So my proposal is, that we prepare some "bundles" with tested loaders, so users can choose. There are some really cool animations. I'm sure some users will reload the page, just to see them again :)

-m

**Comment by pmario** [comment]
The problem with the text is, that it needs to be translatable.

**Comment by AnthonyMuscio** [comment]
Too true,

I suppose it is too early to test for language and source the appropriate text at that point?

Can we use a Internet translator for that I wonder.

Regards
Tony

**Comment by pmario** [comment]
> Can we use a Internet translator for that I wonder.

That's not the problem. TW can handle language switching. The problem is, that at the time this message is shown, the TW-core isn't started. So the translations are not available. ... 

So if we want to show a text, we need to tell users how to modify them. ... It can't be handled by the core.

So for "the core" I'd suggest to have no text at all. If users want text, they would need to read the docs. 

just my opinion. ... which is subject to change here :)

**Comment by AnthonyMuscio** [comment]
Yes, I understand the same.

Lets go with no text

What I was wondering was could we use some html that references a WebTranslation service where if the user has time they can select their flag from the the list and google or what ever "tries" to translate it to their selected language. If simple and common language is used the translations will be fairly good.

Regards
Tony

No Tiddlywiki here just a brute force translation. I expect this may need an API so that may proclude it.

**Comment by Jermolene** [comment]
As @tobibeer [noted](
https://github.com/Jermolene/TiddlyWiki5/issues/2254#issuecomment-176121766), I think the best approach is new system tiddler analogous to `$:/core/templates/static.content` that contains wikitext that is rendered as the loading screen. (We'd actually maybe also need a companion tiddler for the styles). Then the core would render that content into the HTML file, and the startup process would hide it once the core has booted up.

In terms of suitable splash screen animations for the core, I think CSS animations make the most sense these days.

**Comment by AnthonyMuscio** [comment]
I hope we can implement this in the next version. I will raise a new issue but is it possible to do the same for tiddlers? Perhaps we can toggle it on an off, so it only happens when necessary.
