### ISSUE TITLE
Cannot dag and drop list item to new last location

### ISSUE THREAD

**Issue by jho1965us** [Jermolene/TiddlyWiki5#3418]
E.g. open 3 new tiddlers

    New Tiddler 1
    New Tiddler 2
    New Tiddler 3

Go to sidebar > open
it will show

    New Tiddler 3
    New Tiddler 2
    New Tiddler 1

Try drag 'New Tiddler 2' to after 'New Tiddler 1' not possible!

**Comment by twMat** [comment]
You can accomplish the desired result by instead dragging the very bottom-most tiddler one step up.
Is that enough for you?

**Comment by saqimtiaz** [comment]
This has since been resolved and the issue can now be closed @jho1965us @Jermolene

**Comment by Jermolene** [comment]
Thanks @saqimtiaz
