### ISSUE TITLE
Minor but powerful improvement to the Range Operator

### ISSUE THREAD

**Issue by AnthonyMuscio** [Jermolene/TiddlyWiki5#3425]
Folks,

In the pre-release the range operator is available. This will prove very valuable. 

However it would be more value with a minor improvement and that is to provide a leading zero when required. Especially for the production of test data within TiddlyWiki

That is the range operator will currently return as follows

```
<$list filter="[range[1,12]]" variable=month>

</$list> 
```

1
2
3
4
5
6
7
8
9
10
11
12

If however you want to generate some test data, lets say tiddlers with YYYY0MM0DD dates you can't do it because there is no leading zero generated.

What I would like to propose is the ability to place leading zeros in the range operator that sets the incrementing number that it will zero fill.

Eg;
```
<$list filter="[range[01,12]]" variable=month>

</$list> 
```

01
02
03
04
05
06
07
08
09
10
11
12

Or
```
<$list filter="[range[0001,1000]]" variable=month>

</$list> 
```

What do you think?

Can you do it please

Regards
Tony

**Comment by Jermolene** [comment]
Hi @AnthonyMuscio I think this is a good idea. The range widget was contributed by @EvanBalster - Evan do you have any thoughts?

**Comment by EvanBalster** [comment]
Hey —

This is sensible enough.  `range` already respects the number of trailing digits.  It could also be nice if it supported comma decimal separators as mentioned in #1523, though that would require using `:` as the delimiter.

Commas/periods as a thousands separator would be neat too...  I wonder how much of that could be done without an explicit formatting string.  Perhaps that's a fun evening project for one of these days.

**Comment by AnthonyMuscio** [comment]
Evan,

It sound great that you are considering extending its features to handle numbers in a better way, I am all for that however I really are keen on being able to have simple zero prefixed numbers returned.

The key reason is it will be very easy to build custom lists for the rapid generation of tiddlers including with custom date fields (Zero filled essential). Personally I feel "test Data" is lacking in tiddlywiki and having good test data especially generated for purpose will be valuable to starters and pros alike.

I can see providing a plugin designed to generate and delete test data a great support to people learning and experimenting.

The Truth is this is possibly trivial with you formulas plugin but I am not sure its necessary for this use case.

Thanks
Tony

**Comment by AnthonyMuscio** [comment]
Folks,

I am closing this because we have a work around and otherwise we have far to much in our issues queue. The work around is to generate numbers using decimals and remove the "0." prefix as follows to generate numbers with leading zeros.

```
<$list filter="[range[.001,.01,.001]]" variable=number>
  <$list filter="[<number>removeprefix[0.]]">

  </$list>
</$list>
```
