### ISSUE TITLE
Markdown plugin has some strange behaviour

### ISSUE THREAD

**Issue by ghost** [Jermolene/TiddlyWiki5#3426]
Simply put `something: foo [intro]` and the very beginning of one markdown tiddly. It does not appear.

**Comment by Jermolene** [comment]
Hi @somenxavier it seems that the problem only appears when using the Maruku dialect (configured via $:/config/markdown/dialect; if you switch it back to `Gruber` then things work as expected). I think you're triggering some unexpected bit of Maruku's syntax (see https://github.com/bhollis/maruku/blob/master/docs/markdown_syntax.md).

**Comment by pmario** [comment]
@Jermolene ... IMO this issue can be closed. We use a completely different library now and the user is "ghosted" / deleted.

**Comment by Jermolene** [comment]
Thanks @pmario
