### ISSUE TITLE
TOC macro breaks with titles ending with a double quote character

### ISSUE THREAD

**Issue by somenxavier** [Jermolene/TiddlyWiki5#3427]
I have 
```
Table of Contents

<div class="tc-table-of-contents">
<<toc-selective-expandable 'menu' "sort[title]">>
</div>
```

If I tag (with `menu` tag) one tiddler with `"somenthing"` in title, I get something strange.

**Comment by Jermolene** [comment]
Hi @somenxavier the first parameter to the `<<tabs>>` macro should be a filter expression yielding the titles of the tiddlers comprising the individual tabs. If you want to include all tiddlers with the tag `menu` then you should use `<<tabs "[tag[menu]]" "sort[title]">>`.

**Comment by somenxavier** [comment]
But I want a `toc-selective`

**Comment by Jermolene** [comment]
Hi @somenxavier apologies for my confusion, goodness knows how I could have misread that. Anyhow, yes, the TOC macro cannot cope with tiddlers with double quotes at the end of their titles. Fix upcoming.

**Comment by somenxavier** [comment]
Thanks.
