### ISSUE TITLE
Editable selectwidget option

### ISSUE THREAD

**Issue by twMat** [Jermolene/TiddlyWiki5#3431]
Ref [this solution](http://jsfiddle.net/nwH8A/)

The above shows a html **select** element modified to allow typing in a custom option! Very elegant *and* that code looks like it should be a very quick matter(?)

I propose this for the TW SelectWidget. There could be an added attribute `editable` in the widget that, if present, toggled this behaviour.

Actual use cases include the [batch manipulator](http://batchmanipulator.tiddlyspot.com/#batchmanipulator) where one could then skip the separte editwidget above the selectwidget, and also as I'm fiddling with TWederation and now want users to be able to either select a pre-defined filter for import or manually type one.

**Comment by Jermolene** [comment]
Hi @twMat the solution is just CSS, it can be adapted to TW5 pretty directly. But I'd want to test it in a *lot* of browsers before adopting it too widely: I suspect that the assumptions it makes about the layout of the "select" control might not hold for all browsers.

**Comment by twMat** [comment]
Oh... I noted that line of js in the html but, yeah, it seems they've just moved the editor. Hm, that does seem fragile. 

I'll close this and see if it is workable. I do like the idea and if it is not good with pure css I'll propose it again.

**Comment by twMat** [comment]
Ah! Thank you!
