### ISSUE TITLE
evalSandboxed causes serious bottleneck

### ISSUE THREAD

**Issue by Arlen22** [Jermolene/TiddlyWiki5#3450]
NodeJS TiddlyWiki takes a significant amount of time to start, so much so that I was almost ready to switch to a single file wiki on my Android (where the problem is the worse), even though I majorly prefer data folder wikis.

Instead I dug into the code to find out where the problem was and a trace revealed that the biggest problem was in loading modules from tiddlers. I wondered why my browser did not have the same effect, and so I modified boot.js evalGlobal and evalSandboxed to use the Function factory, which has the same effect as vm.runInThisContext. 

Voila! My startup time was now 1.5 seconds instead of 30.

But this is obviously a change that could have implications, although the NodeJs docs say the vm module should not be used for security purposes. So I was wondering what your thoughts are.

At the very least we should be careful to override every global when using evalSandboxed, but even then there isn't much that we're worrying about since we still allow requiring external modules.

**Comment by Arlen22** [comment]
I don't think NodeJs loads modules in a new context. I think it loads them in the same context as the code calling require. So what if we would try creating one context and loading all NodeJS modules in that one context. It is possible that this would still speed things up a lot. Or just create one empty context on startup to run all code in and then do the function construction as evalGlobal does.

**Comment by Arlen22** [comment]
Ok, did some more tests. Passing undefined or an empty object to runInNewContext does not improve performance.

On the other hand, creating one empty context for all modules to use has the same effect as as using runInThisContext and so it is also a solution.

**Comment by Arlen22** [comment]
Using one context for all modules is still better than running them in the global context because it prevents modules from overriding global variables.

**Comment by Arlen22** [comment]
So here is how I modified it to use one context. 

```js

$tw.utils.evalMakeModule = function(code,context){
	var contextCopy = $tw.utils.extend(Object.create(null),context);
	// Get the context variables as a pair of arrays of names and values
	var contextNames = [], contextValues = [];
	$tw.utils.each(contextCopy,function(value,name) {
		contextNames.push(name);
		contextValues.push(value);
	});
	// Add the code prologue and epilogue
	code = "(function(" + contextNames.join(",") + ") {(function(){\n" + code + "\n;})();\nreturn exports;\n})\n";
	return { code, contextNames, contextValues }
}
/*
Run code globally with specified context variables in scope
*/
$tw.utils.evalGlobal = function (innercode, context, filename) {
	var { code, contextNames, contextValues } = $tw.utils.evalMakeModule(innercode, context);
	// Compile the code into a function
	var fn;
	if ($tw.browser) {
		fn = Function("return " + code + "\n\n//# sourceURL=" + filename)();
	} else {
		fn = vm.runInThisContext(code, filename);
	}
	// Call the function and return the exports
	return fn.apply(null, contextValues);
};

/*
Run code in a sandbox with only the specified context variables in scope
*/
var sandboxContext = $tw.browser ? undefined : vm.createContext();
$tw.utils.evalSandboxed = $tw.browser ? $tw.utils.evalGlobal : function (innercode, context, filename) {
	var { code, contextNames, contextValues } = $tw.utils.evalMakeModule(innercode, context);
	return vm.runInContext(code, sandboxContext, filename).apply(null, contextValues).exports;
};
```

**Comment by Arlen22** [comment]
Remember that this only affects the server. The browser uses eval anyway, which has no separation of concern at all. Actually, it would be better to use the Function factory because eval uses all the local variables in the code block it is called from too. At least that's my understanding.

**Comment by Arlen22** [comment]
Is there any reason we need to have a separate context for each module on the server or is it enough to have all modules inside one context. The more I think about this, the less reason I see for it given the major performance difference. I think I'm going to make it an option in TiddlyServer for now because I can't think of a major security implication of doing it this way. 

Please correct me if I'm wrong, but my understanding is that the only thing it affects is whether modules can override certain JavaScript globals like adding methods to Array.prototype for other functions to use, and stuff like that, and only on the server. 

The other option I thought of is to run each plugin in it's own context, but there again we are only doing this on the server, not in the browser. But there is no point in that since if a plugin actually wants to go that route it has a reason for it. 

I think it's good to have a new context, but I think we only need one.

**Comment by pmario** [comment]
@Arlen22 ... Is this one resolved with:  Change evalSandboxed to use only one context for all modules #4624 
Can we close it?

**Comment by Arlen22** [comment]
Yes, this is solved.
