### ISSUE TITLE
Node performance issue

### ISSUE THREAD

**Issue by crazyerghb** [Jermolene/TiddlyWiki5#3452]
hi guys, 
    I really love tw and I was worried about if I put so many tiddler in one page file. so I found another way after I tried to use tw on the Node.js.
   and I have about 450 tiddlers in one folder, and I tried to use Tiddlywiki --server port to start node web service, and then I drag my an original file to import all tiddlers into client-server mode folder.
   it is very strange that when I tried to open multiple tiddler, about 5~10 tiddler at the same time, and Brower will say,  NO Response, Please wait, then quit, I have to close the page then restart it.
   also, When I try to delete some tiddler, browser will also report this issue.
   I dont know exact reason, but I think it should NOT be happen, cause I expect it will put more that 1k files at the one folder.   another way I tried, use TW5.com from Github which distributed so many file in many folders, and I try to open multiple files at the same time, It wont happened again.

  I am not sure if I express my question clear enough, please give me some tips if you have time.

   Tks in advance.

Robert from China.

**Comment by pmario** [comment]
@Jermolene -- IMO can be closed. 

User has no GH activity since several years and issue has not been "bumped". IMO user is gone.

**Comment by Jermolene** [comment]
Thank you @pmario
