### ISSUE TITLE
tc-popup - a leftover?

### ISSUE THREAD

**Issue by twMat** [Jermolene/TiddlyWiki5#3456]
Is `tc-popup` an intentional css hook or is it a leftover? - in which case it should perhaps be removed. It is not defined anywhere, as far as I can tell.

**Comment by Jermolene** [comment]
Hi @twMat the `tc-popup` class is used internally by the popup mechanism to keep track of the extent of popups. It's not used for styling; instead there's JS code that adds, removes and checks for this class.

**Comment by twMat** [comment]
Ah, thank you.
