### ISSUE TITLE
String remove and replace and other string filters?

### ISSUE THREAD

**Issue by AnthonyMuscio** [Jermolene/TiddlyWiki5#3457]
Folks,

It seems to me a basic and easy to implement operation to provide a tool to remove or replace characters or strings from a field value or title. I can't seem to find it in the current version 

For example given the Journal tiddler title YYYY-0MM-0DD eg 2018-09-28 to replace "-" with "" giving 20180928 making it a valid date for date formats, or 2018-09-28 to replace "-" with "/" giving 2018/09/28

I could imagine  filter operator "[[title]] +[removestring[-]]" or "[get[fieldname]] +[replacestring[/,-]]"

I imagine the best place to use this would be inside the $set widget (possible $vars)
`<$set name=variablename filter="<variable> +[remove[-]]">`

Which to me opens up the use of filters in the set parameter for string manipulation, this makes me ask what other string manipulation gaps do we have that could be addressed by filters and also applied to titles.

For example I have just discovered we can use set this way already
```
<$set name=test filter="[[test string]] +[addprefix[66 ]]">
  <<test>>
</$set>

I presume the following would also work
{test string} +[addprefix[66 ]]
{!!test-string} +[addprefix[66 ]]
<test string> +[addprefix[66 ]]
[[test string]]  +[addprefix[66 ]] +[removesuffix[ing]] (tested OK)
```

**If people like this idea I can research for what the missing string operations are and we can provision the additional filter operators. We could also note for the existing operators they operate on titles by default and that the ones suffixed "string" apply within titles/text.**

As per the addprefix and removesuffix examples above you can see it is easy to make multiple operations on a single string, or multiple titles (as a set of strings)

I have often gone to the String Operators in Filter Operators only to be disappointed and forced to use work arounds.

Your thoughts please.

**Comment by Jermolene** [comment]
Hi @AnthonyMuscio 

> It seems to me a basic and easy to implement operation to provide a tool to remove or replace characters or strings from a field value or title

I've also been thinking about this recently, but with a slightly different syntax:

```
[[HelloThere]get[text]replace:e[é]]
```

The trouble is that neither syntax allows both the original and replacement text to be specified via transclusion.

>`<$set name=test filter="[[test string]] +[addprefix[66 ]]">`

Are you sure the set filter is appropriate here? In this form, it puts the entire result list in the output variable, using double square brackets to quote any results that contain spaces.

Perhaps you'd be better off using the filtered transcluded attribute syntax:

```
<$set name=text value={{{ [[test string]addprefix[66]] }}}>
```

> PS Perhaps we could partially address the issues raised in "Provide an index value in lists" a string operator +[addprefix[Number ]] where is replaced with the nth item generated in the list.

I think that that is just a restatement of the original request to provide a numerical index in the list filter. I think we've covered that one to death already.

**Comment by Jermolene** [comment]
Hi @jho1965us that is a first class suggestion, thank you! I think that could work, but need to think about it more...

**Comment by AnthonyMuscio** [comment]
Perhaps there is a technical argument for "[operator:suffix[operand1]:[operand2]]" but it best be documented well, because Filters are already so powerful that they take sometime to grasp. If humans need to "parse" such filters is their brain going to explode?

Perhaps the above will make it simpler, but are there existing methods that should be brought it this standard if adopted?

**Comment by AnthonyMuscio** [comment]
I do miss the Old Cobol inspect statement that would handle this and more. http://www.mainframestechhelp.com/tutorials/cobol/cobol-inspect-statement.htm

**Comment by Jermolene** [comment]
Over in #3502 I've addressed a slightly different need to extend the filter operator suffix syntax. It's a less ambitious change than adding support for multiple operands, but might still be handy.

**Comment by saqimtiaz** [comment]
@AnthonyMuscio @Jermolene this can be closed in light of the new `search-replace[]` operator in 5.1.23

**Comment by Jermolene** [comment]
Thanks @AnthonyMuscio @saqimtiaz
