### ISSUE TITLE
Bug in Macro definitions

### ISSUE THREAD

**Issue by AnthonyMuscio** [Jermolene/TiddlyWiki5#3459]
Folks,

I have just being "beating my head against a brick wall", only to discover a bug or inconvenient fact.

In the below code  no matter what I did within \define layer-diagram I could never get it to return a result. I tried everything simplifying it and testing it (OK) below the `<hr>`.
```

\define layer-diagram-row(tiddlername)
Row $tiddlername$
\end
\define layer-diagram-column(tiddlername)
\end
\define layer-diagram(tiddlername)
<$list filter="[tag<currentTiddler>]">

</$list>
\end

<<layer-diagram>>

<hr>

<$list filter="[tag<currentTiddler>]">

</$list>
```

Based on my experience of TiddlyWiki I tried the almost irrational thing and added a blank line in layer-diagram-column with no result, then the word "blah" and now layer-diagram suddenly works even although at this point I do not reference it at all.

Could we fix this time wasting "Bug" please?. I am not even sure how to document it to remember how to avoid it happening again. I imagine it needs something in the routines that parse the define "pragma".

Thanks
Tony

**Comment by Jermolene** [comment]
Hi Tony apologies, I rewrote this as ticket #3460 thinking you had posted this to Google Groups.
