### ISSUE TITLE
Bug: empty macro definitions don't parse as expected

### ISSUE THREAD

**Issue by Jermolene** [Jermolene/TiddlyWiki5#3460]
The `\end` of an empty macro definition is incorrectly parsed as its body.

For example:

```
\define max()
\end
Nothing
\end

Out: <<max>>
```

The correct output should be `Nothing \end Out:`, but the current output is `Out: \end Nothing`.

**Comment by AnthonyMuscio** [comment]
The problem in Bug in Macro definitions #3459 is most likely the same but while still "legally constituted".

```
\define one()
Show One
\define two()
\end
\define three()
Show three
\end
```

The above looks fine, but the fact that two is empty will cause unexpected results.

```
\define two()

\end
```

Will also Cause unexpected results

```
\define two()
a
\end
```

Will not cause problems

**Comment by pmario** [comment]
Procedures have the same problem. 

```
\procedure max()
\end
Nothing
\end

Out: <<max>>
```

**Comment by AnthonyMuscio** [comment]
Perhaps they could return the macro, function, procedure name + "empty" or something similar that will test true in a filter, be visible in dump variables or the console log?

Keep in mind no one depends on a different behaviour because currently it breaks code and causes indeterminant results.

**Comment by CodaCodr** [comment]
To be consistent with missing definitions, they should return blank.

![image](https://github.com/Jermolene/TiddlyWiki5/assets/436812/50332675-8fd4-4847-a931-94e557278b84)

**Comment by Jermolene** [comment]
I think this would be a fairly simple fix if anyone wants to pick it up; the logic for matching the body of the definition should allow for a blank body.
