### ISSUE TITLE
Using a variable in filter and list

### ISSUE THREAD

**Issue by pajtai** [Jermolene/TiddlyWiki5#3462]
I'm trying to show links and then contents for all tiddlers tagged, "2018-10-01"

This works:
```
TOC

{{{ [tag[2018-10-01]] }}}

Contents
<$list filter="[tag[2018-10-01]]">
    <$transclude mode="block"/>
</$list>
```

But this doesn't:
```
TOC 

<$set name=dateToday value=2018-10-01>
{{{ [tag[<dateToday>]] }}}

Contents
<$list filter="[tag[<dateToday>]]">
    <$transclude mode="block"/>
</$list>
<$set>
```

2 Questions:

1. How would I use a variable for the above?
2. I've looked in the docs, but they're very narrow in scope. Is there a high level overview of the templating language?

**Comment by twMat** [comment]
@pajtai - welcome to the github board for TW. We actually only post issues, i.e errors or suggestions here and regular "how do I...?" questions is for the [discussion forum](https://groups.google.com/forum/#!forum/tiddlywiki). 

That said, here's a reply that might work so you can please close this issue afterwards:

```
<$set name=dateToday value="2018-10-01">
{{{ [tag<dateToday>] }}}

Contents
<$list filter="[tag<dateToday>]">
    <$transclude mode="block"/>
</$list>
<$set>
```
