### ISSUE TITLE
indentUnit, tabSize and cursorBlinkRate should have field type="integer"

### ISSUE THREAD

**Issue by NikolayMakhonin** [Jermolene/TiddlyWiki5#3474]
Now these configs is a strings, and this leads to problems, for example with tabulation (TAB button)
(2 + "2" = 22)

$:/config/codemirror/indentUnit
$:/config/codemirror/cursorBlinkRate
$:/config/codemirror/tabSize

**Comment by BurningTreeC** [comment]
Thanks @NikolayMakhonin , I've created a PR for it
