### ISSUE TITLE
$:/StoryList.modified updated with any operation

### ISSUE THREAD

**Issue by yrashk** [Jermolene/TiddlyWiki5#3485]
Here's a dump of my log:

```
 syncer-server-filesystem: Dispatching 'save' task: $:/StoryList 
 filesystem: Saved file /home/yrashk/Projects/sit-fyi/wiki/tiddlers/$__StoryList.tid 
 syncer-server-filesystem: Dispatching 'save' task: Draft of 'SPORE/1' 
 filesystem: Saved file /home/yrashk/Projects/sit-fyi/wiki/tiddlers/Draft of 'SPORE_1'.tid 
 syncer-server-filesystem: Dispatching 'delete' task: Draft of 'SPORE/1' 
 filesystem: Deleted file /home/yrashk/Projects/sit-fyi/wiki/tiddlers/Draft of 'SPORE_1'.tid 
 syncer-server-filesystem: Dispatching 'save' task: $:/StoryList 
 filesystem: Saved file /home/yrashk/Projects/sit-fyi/wiki/tiddlers/$__StoryList.tid 
 syncer-server-filesystem: Dispatching 'save' task: SPORE/1 
 filesystem: Saved file /home/yrashk/Projects/sit-fyi/wiki/tiddlers/SPORE_1.tid 
```

Here I just tried to edit `SPORE/1`, discarded changes. Yet at every step step, `StoryList` is updated (for `modified`).

This causes a bit of an issue in my workflow where I put .tid files into a git repository and send merge requests with my changes. If I am not careful I might include `StoryList` in those patches and therefore eventually create conflicts between patches for no good reason (they would both update `StoryList`).

What is the rationale behind this? Any good way to disable this behavior?

**Comment by hoelzro** [comment]
I can't speak to the rationale, but you can edit `$:/config/SyncFilter` to make sure changes to `$:/StoryList` aren't synced to the Node daemon, assuming you want to make sure it's never written to disk.

**Comment by yrashk** [comment]
@hoelzro thanks, that alleviates my issue!
