### ISSUE TITLE
Automatic refresh of the date used by "new journal entry" button

### ISSUE THREAD

**Issue by tgirod** [Jermolene/TiddlyWiki5#3489]
When leaving a wiki open and coming back the next day, the "new journal entry" button does not work as expected. As the date is not refreshed unless the wiki is reloaded, clicking on the button will effectively open yesterday's journal entry.

Maybe clicking on the button should trigger an update of the date used by the button.

Disclaimer: I'm using tiddlywiki in a post-tiddlypocalypse setting, manually saving it in firefox. Maybe there is an automatic refresh when auto-save is working ? I don't know ...

**Comment by pmario** [comment]
Which TW version do you use?

**Comment by pmario** [comment]
The next upcoming version will work as expected. see: https://tiddlywiki.com/prerelease/

**Comment by pmario** [comment]
As I wrote. The next version will get it right! ... So IMO you can close this issue.
