### ISSUE TITLE
$tw.platform.isLinux wrong on latest firefox

### ISSUE THREAD

**Issue by BurningTreeC** [Jermolene/TiddlyWiki5#3494]
in startup.js the platforms are tested like so:

```
        $tw.platform.isMac = /Mac/.test(navigator.platform);
        $tw.platform.isWindows = /win/i.test(navigator.platform);
        $tw.platform.isLinux = /Linux/i.test(navigator.appVersion);
```

`navigator.appVersion` contains the "Linux" string on Chrome on my Linux Desktop, but not on latest Firefox

I'd appreciate if someone could verify this on another machine, because I have a nightly build and somehow my stable builds got replaced by it... 

anyway, if I use navigator.platform for the Linux test, the platform gets reported correctly. Also on Chrome navigator.platform contains "Linux" so it would be fine there, too

**Comment by Jermolene** [comment]
Hi @BurningTreeC ouch! It sounds like a good idea to go with the navigator.platform.

**Comment by Jermolene** [comment]
Hi @BurningTreeC great, perhaps @pmario can confirm your findings.

**Comment by pmario** [comment]
I can confirm, that there is a problem.  ubuntu 18.04  ff 62.0.3

**Comment by BurningTreeC** [comment]
@pmario @Jermolene is it safe to simply use `navigator.platform` or will there problems with older firefoxes?

**Comment by pmario** [comment]
seems to be ok: see: https://developer.mozilla.org/en-US/docs/Web/API/NavigatorID/platform

**Comment by Jermolene** [comment]
OK, please go ahead with a PR. Many thanks @BurningTreeC
