### ISSUE TITLE
about (defaults to "$:/core/save/all")



### ISSUE THREAD

**Issue by pumpkinpies** [Jermolene/TiddlyWiki5#3499]
when i use 

`tiddlywiki mywiki ——server 8080 $:/core/save/all ...` 

in windows, it report a error

**Comment by pumpkinpies** [comment]
i want know what is the "$:/core/save/all" , i just google it and found nothing.

**Comment by pumpkinpies** [comment]
What should i do when i try to assign a ip for a  wiki with the other parameters using the default properties.

**Comment by pmario** [comment]
Can you describe, what you want to achieve?

**Comment by pumpkinpies** [comment]
Sorry for my English , but i want to use tiddlywiki in a local network. So my class mate can access it

**Comment by pmario** [comment]
TW server works with so-called editions. There are several steps involved. 

Have a closer look at: https://tiddlywiki.com/#GettingStarted%20-%20Node.js

**Comment by pmario** [comment]
IMO you forgot the "init" step.

**Comment by pumpkinpies** [comment]
I truely followed the tutorials in this page.
And I can access the page though localhost:8080, but when I try to access the tiddlywiki from another pc,  use


npm -g install tiddlywiki

C:\Users\Nancy\AppData\Roaming\npm\tiddlywiki -> C:\Users\Nancy\AppData\Roaming\0/save/all text/plain text/html "" ...

+ ~~

The variable reference is invalid. The variable name character after '$' is invalid. Consider using ${} to separate names.

     + CategoryInfo : ParserError: (:) [], ParentContainsErrorRecordException

     + FullyQualifiedErrorId : InvalidVariableReference 0

and i just don't know how to handle it

**Comment by pumpkinpies** [comment]
I truely followed the tutorials in this page.
And I can access the page though localhost:8080, but when I try to access the tiddlywiki from another pc,  use


npm -g install tiddlywiki

C:\Users\Nancy\AppData\Roaming\npm\tiddlywiki -> C:\Users\Nancy\AppData\Roaming\npm\node_modules\tiddlywiki\tiddlywiki.js

+ tiddlywiki@5.1.17

added 1 package from 1 contributor in 102.382s


tiddlywiki wiki --init server

Copied edition 'server' to wiki


tiddlywiki wiki --server8080 $:/core/save/all text/plain text/html "" "" 10.13.211.146

Location Line: 1 character: 30

+ tiddlywiki wiki --server8080 $:/core/save/all text/plain text/html "" ...

+ ~~

The variable reference is invalid. The variable name character after '$' is invalid. Consider using ${} to separate names.

     + CategoryInfo : ParserError: (:) [], ParentContainsErrorRecordException

     + FullyQualifiedErrorId : InvalidVariableReference 0

and i just don't know how to handle it

**Comment by pumpkinpies** [comment]
I truely followed the tutorials in this page.
And I can access the page though localhost:8080, but when I try to access the tiddlywiki from another pc,  use


npm -g install tiddlywiki

C:\Users\Nancy\AppData\Roaming\npm\tiddlywiki -> C:\Users\Nancy\AppData\Roaming\npm\node_modules\tiddlywiki\tiddlywiki.js

+ tiddlywiki@5.1.17

added 1 package from 1 contributor in 102.382s


tiddlywiki wiki --init server

Copied edition 'server' to wiki


tiddlywiki wiki --server8080 $:/core/save/all text/plain text/html "" "" 10.13.211.146

Location Line: 1 character: 30

+ tiddlywiki wiki --server 8080 $:/core/save/all text/plain text/html "" ...

+ ~~

The variable reference is invalid. The variable name character after '$' is invalid. Consider using ${} to separate names.

     + CategoryInfo : ParserError: (:) [], ParentContainsErrorRecordException

     + FullyQualifiedErrorId : InvalidVariableReference 0

and i just don't know how to handle it

**Comment by pumpkinpies** [comment]
Anyway, it's very kind of you to pay attention to the issue.

**Comment by pumpkinpies** [comment]
`tiddlywiki wiki --server 8080 $:/core/save/all text/plain text/html "" "" 10.13.211.146` 

I use win10

**Comment by pumpkinpies** [comment]
Maybe it's not compatible with powershell ?

**Comment by pumpkinpies** [comment]
I just try it with CMD , and it works as excepted! Thank you very much!

**Comment by pmario** [comment]
yea with powershell there is a problem with empty double quotes: `""`.  I did know a workaround but I can't find it at the moment. stackoverflow may know something
