### ISSUE TITLE
external-js: auto-save doesn't work. PR on the way. 

### ISSUE THREAD

**Issue by pmario** [Jermolene/TiddlyWiki5#3500]
2 problems: 

 - If a file-TW is used with the tiddly-fox like auto-save mechanism an invalid html file is created. 
 - this [commit](https://github.com/Jermolene/TiddlyWiki5/commit/f2a38960fce1bb70f1090012334bee452d59f45f) breaks the default download savers. all of them. It only seems to work with `tw --server`

How to reproduce. 

 - create an empty.html file with tiddlywiki.js
 - install file-backups or savefiles browser addOn
 - open it from the Downloads folder
 - edit a tiddler with autosave enabled. 

PR is on the way!!

**Comment by Jermolene** [comment]
> this commit breaks the default download savers. all of them. It only seems to work with tw --server

It might just be a language thing, but surely that's not right? The commit just adds a template for people who want to experiment with external JS configurations of TW5. It doesn't break anything, does it?

I think you're trying to report that saving in the browser doesn't work as you expect when using the external JS template, is that it?

**Comment by pmario** [comment]
That's right. If you open the index.html with tiddlywiki.js in the same directory you get an error message "Cannot load tiddlywiki.js"

**Comment by pmario** [comment]
Also auto-save doesn't work, since the existing code saves an invalid 2Byte html instead of a 80KByte.

**Comment by pmario** [comment]
The PR fixes the problems with file TiddlyWikis. I didn't test it with a server configuration.

**Comment by pmario** [comment]
Clicking the Save-Button does work, since it gets the updated template as a param. With the PR auto-save also gets this new param. Check the PR.

**Comment by BurningTreeC** [comment]
@pmario are you trying to use the external-js template to build single-file wikies? As far as I understood, it's meant to be run on a node.js configuration

**Comment by pmario** [comment]
I want to have tiddlywiki.js in the same directory as index.html. .. Which works fine without any server. 

Why should it be limited to a node.js configuration, which I don't use in production. It should work well with WebDav, file-backups AddOn and the beaker browser, since browsers can use tiddlywiki.js from the local cache.

**Comment by pmario** [comment]
I want to use index.html as a single file store. ... yes.

**Comment by pmario** [comment]
Think about it. ... 

You can have a dozen small x.html files + 1 tiddlywiki.js file in 1 directory. ... 

If you update the tiddlywiki.js file with new functionality, you automagically update all of them. ... including all the problems, that will happen, if you don't know, what you are doing ;)

**Comment by pmario** [comment]
Writing those comments, I just found out, that `tiddlywiki.js` is a bad name, because it's extremely confusing. ... It could be confused with the existing `npm tiddlywiki` module. ... 

So I'd propose to rename the thing into eg: "external-xxxx.js" or something similar.

**Comment by BurningTreeC** [comment]
@pmario - your idea sounds great!

**Comment by Jermolene** [comment]
I implemented this experimental cut of support for externalising the core JS in response to the user requests for it over the years, and I wanted to show that it is in fact very straightforward to experiment with such things.

I'm happy for us to extend the support to make things work well for the single file configuration, but I do think we need to take care in how it is presented to end users. I don't think we should present it as a primary or mainstream way of using TW5 because it compromises the "singlefileness" of TW5. The difference between a file with zero dependencies and one with 1 dependency is exponential complexity. Just recently I was referring back to TWs from 2004-5, and they all work. Part of that is the simplicity of the configuration.

**Comment by BurningTreeC** [comment]
> I don't think we should present it as a primary or mainstream way of using TW5 because it compromises the "singlefileness" of TW5. The difference between a file with zero dependencies and one with 1 dependency is exponential complexity.

I think the same, but for experiments like with beaker browser, it could be a nice feature to have.
I'm just curious what @pmario is going to create with it :smile:

**Comment by pmario** [comment]
Jeremy, you are absolutely right. With TWclassic for some time we had the java-enabled saver, which was an additional file. ... This caused a lot of "handling" problems. 

The external-?core will be much more problematic, since content/core versioning is critical.

**Comment by pmario** [comment]
On the other hand. The dat file system is copy-on-write, which means it is automatically versioned.

**Comment by pmario** [comment]
Close this one. It has been fixed.
