### ISSUE TITLE
Crashes when using large images (notable when 2x clicking)

### ISSUE THREAD

**Issue by Ktar5** [Jermolene/TiddlyWiki5#3504]
I am using a D&D map with a size of 50mb. It renders perfectly, however, makes the application incredibly unstable.

Also, it would be VERY useful to have a feature in which I could zoom in on the image to better display what is going on :)

**Comment by Jermolene** [comment]
Hi @Ktar5 

> I am using a D&D map with a size of 50mb. It renders perfectly, however, makes the application incredibly unstable.

Sadly, the problems you're seeing are the browser being unable to cope with moving all that data around. Part of what's going on is that we're used to dealing with compressed images (eg jpg), but when a browser loads an image into memory it does so in uncompressed format, which consumes horrendous amounts of memory.

You might find that you get better performance by tiling the map into much smaller chunks, displaying each with a separate `<img>` tag. Best of all would likely be an SVG rendering of your map.

> Also, it would be VERY useful to have a feature in which I could zoom in on the image to better display what is going on :)

Splitting it into tiles might make that easier too.
