### ISSUE TITLE
Dropzone doesn't cancel correctly

### ISSUE THREAD

**Issue by BurningTreeC** [Jermolene/TiddlyWiki5#3509]
If we drag a tag-pill on a tiddler and release the drag on the story river, the dropzone on top of the page doesn't remove its highlighting

That happens because it somehow gets another `dragEnter` event and adds the `tc-dragover` class again

I tried adding another eventlistener for `dragend` and setting `this.dragEnd = true` within its handler. Then in `handleDragEnterEvent` I continue only if `this.dragEnd !== true` , else `this.dragEnd = false` ... which works for not adding the `tc-dragover` class again

You can see this problem on tiddlywiki.com by simply dragging a tag and releasing it above the story river

**Comment by BurningTreeC** [comment]
Update: I think we can ignore this. It's probably just an issue with my (beta-state) linux window-manager not correctly handling drag&drop

**Comment by pmario** [comment]
No it not your problem. ... With FF every list drag and drop sorting goes wrong. But there are is a long standing open issue somewhere already. So you can keep this one closed.
