### ISSUE TITLE
Saving on TiddlySpot lacks a description label.

### ISSUE THREAD

**Issue by Marxsal** [Jermolene/TiddlyWiki5#3510]
All the other save mechanisms under "Getting Started" have descriptions.

**Comment by twMat** [comment]
Maybe obvious for everyone but me, but where exactly do you mean that this label should be seen?

**Comment by Marxsal** [comment]
Look at "Getting Started". Every save mechanism has a description except for TiddlySpot.

**Comment by Jermolene** [comment]
Hi @Marxsal apologies this is fixed in the prerelease: https://tiddlywiki.com/prerelease

**Comment by Marxsal** [comment]
Thanks!
