### ISSUE TITLE
navigator when creating new tiddlers

### ISSUE THREAD

**Issue by BurningTreeC** [Jermolene/TiddlyWiki5#3513]
when we set `openLinksFromOutsideRiver` to `bottom` , I'd expect that new Tiddlers would also be inserted at the bottom of the story list

this would be a very easy fix for good benefit - what do you think?

**Comment by twMat** [comment]
makes sense.

**Comment by BurningTreeC** [comment]
thanks @twMat 
I'll close this since #3514/#3516 got merged ... Is Nov.06th TW-day? :grin:  :+1: :+1:
