### ISSUE TITLE
New wikitext syntax for filtered transcluded links

### ISSUE THREAD

**Issue by Jermolene** [Jermolene/TiddlyWiki5#354]
Currently we have `[[a]]` for links to an individual tiddlers and `{{a}}` for transcluding an individual tiddler. `{{{filter}}}` is used to transclude the list of tiddlers generated by a filter. By default, the template that is used causes each entry in the list to be rendered as a clickable link.

It is proposed for consistency to change things so that:
- `[[[filter]]]` transcludes the filter with a template generating a clickable link for each entry (ie, the same as the present implementation of `{{{filter}}}`)
- `{{{filter}}}` transcludes the filter with a template showing the entire text of the tiddler

We would still allow `{{{filter||template}}}` to transclude a filter through a specified template tiddler.

Questions:
- Would we also allow `[[[filter||template]]]`? Would it be a synonym for `{{{filter||template}}}`?
- Is it really sensible for the filtered transclusion syntax to support a tooltip? It's not currently supported by the list widget, and doesn't seem particularly useful (if you want a separate tooltip for each entry just include it in the template)

**Comment by pmario** [comment]
@Jermolene ... The OP was created prior to TW v5.1.0 while it would have been possible to change the syntax for `{{{ filter }}}` to show the tiddler text instead of title-links. 

IMO it's to late for that change and `[[[ filter ]]]` would be the same thing as `{{{ filter }}}` is now. .. So imo this issue should be closed.

**Comment by Jermolene** [comment]
Thanks @pmario
