### ISSUE TITLE
$tw.wiki.initParsers is not a function (FF38)

### ISSUE THREAD

**Issue by BurningTreeC** [Jermolene/TiddlyWiki5#3555]
in [the group](https://groups.google.com/d/msg/TiddlyWiki/htO5KckxEfw/6Ii6_KNdBgAJ) this error was reported on an old FireFox version (38.0.5) and I could reproduce it using that  version and opening the tiddlywiki prerelease

the window is stuck at the splash screen and yells `$tw.wiki.initParsers` is not a function

see the attached screens
![19-11-2018-155653_shoot](https://user-images.githubusercontent.com/9407182/48715072-74548f80-ec14-11e8-951c-3e057ca2b3e4.png)
![19-11-2018-155718_shoot](https://user-images.githubusercontent.com/9407182/48715075-74ed2600-ec14-11e8-8ccc-5238b5096cee.png)

**Comment by Jermolene** [comment]
Thanks @BurningTreeC I tried to run Firefox 38.0.5 on my Mac (from [here](http://archive.mozilla.org/pub/firefox/releases/38.0.5/)), but it doesn't work, I think because I'm now on High Sierra which doesn't run some old stuff.

Sooo, it would be great if you can help track this down...

First question is whether you see the same problem at https://tiddlywiki.com/prerelease/empty.html?

Also, are there any other messages scrolled up out of view in the console?

**Comment by BurningTreeC** [comment]
@Jermolene , it happens with the empty.html, too

I only get these 2 messages ... the first one:
![19-11-2018-210159_shoot](https://user-images.githubusercontent.com/9407182/48732047-dd50fd00-ec3e-11e8-9bbd-deb63b254ec9.png)

**Comment by Jermolene** [comment]
Hi @BurningTreeC well done, I think that might be right. Running JSHint over wiki.js gives this error:

```
core/modules/wiki.js: line 564, col 9, Function declarations should not be placed in blocks. Use a function expression or move the statement to the top of the outer function.
```

I've run into this before somewhere, and yes, I think the answer is to refactor that inner function declaration to the top of its host function. Great if you're up to having a go at it :)

**Comment by flibbles** [comment]
My apologies @Jermolene and @BurningTreeC. After all that fuss I made about getting #3301 to fix a bug, and I went and broke tiddlywiki on legacy browsers.

**Comment by Jermolene** [comment]
HI @flibbles there's nothing to apologise for. Progress always carries some risk, and everything here worked perfectly: the error was detected pretty swiftly, and fixed without fuss.
