### ISSUE TITLE
CodeMirror doesn't render properly in new windows

### ISSUE THREAD

**Issue by BurningTreeC** [Jermolene/TiddlyWiki5#3562]
codemirror doesn't render correctly when opening a story river in a new window for example

steps to reproduce:

- open tiddlywiki.com/prerelease
- search for the $:/core/ui/PageTemplate tiddler and open it
- open the PageTemplate in a new window
- create a new Tiddler
- see the wrong rendering of the cm editor, try inserting some text

I found an issue about this over at the CodeMirror repo. They state that it'd be necessary to replace all references to `document` and `window` with the corresponding new-window document and window

**Comment by Jermolene** [comment]
Thanks @BurningTreeC are there some simple steps to reproduce on https://tiddlywiki.com/prerelease? Is the problem code that references the global "window" object directly?

**Comment by BurningTreeC** [comment]
@Jermolene, I've updated the first comment

**Comment by Jermolene** [comment]
Ouch! That's a shame, I can imagine that could be pretty useful.

**Comment by BurningTreeC** [comment]
Yes it would... Maybe at a later point we get an idea for a workaround
