### ISSUE TITLE
Doc: Replacement for "TiddlyWiki in the Sky for TiddlyWeb" tiddler?

### ISSUE THREAD

**Issue by Marxsal** [Jermolene/TiddlyWiki5#3563]
The "TiddlyWiki in the Sky for TiddlyWeb" tiddler promises to demo TiddlyWeb with a site at tiddlyspace. Unfortunately, tiddlyspace is no more. Should the "demo" instructions be removed? Or is there a suitable replacement?

**Comment by Jermolene** [comment]
Thanks @Marxsal we should probably just delete that tiddler entirely; the existing "TiddlyWeb" tiddler already explains that TW5 can be used with a TiddlyWeb server.

**Comment by pmario** [comment]
@Jermolene ...  [The tiddler mentioned](https://tiddlywiki.com/#TiddlyWiki%20in%20the%20Sky%20for%20TiddlyWeb) in the OP still exists, but it **does not promise anything**.. I explains the therms and was rewritten in 2021

So IMO this issue can be closed.

**Comment by Jermolene** [comment]
Thanks @pmario
