### ISSUE TITLE
please undo #3490

### ISSUE THREAD

**Issue by BurningTreeC** [Jermolene/TiddlyWiki5#3581]
@Jermolene, apologies

#3490 is not ready, I thought it was

it cancels the more-tiddler-actions popup if the export-tiddler popup is shown, resulting that both popups disappear. needs work

**Comment by BurningTreeC** [comment]
Hi @Jermolene, would you undo it? My PR doesn't undo this one

**Comment by BurningTreeC** [comment]
@hoelzro, Hi, don't worry! Have you seen #3309 ? In the end that PR would also accomplish cancelling the popups your PR cancels

**Comment by hoelzro** [comment]
@BurningTreeC I haven't - I'll take a look tomorrow morning!
