### ISSUE TITLE
No space between tag pills in edit template

### ISSUE THREAD

**Issue by Jermolene** [Jermolene/TiddlyWiki5#3582]
One of the recent changes to tag rendering in the edit template has lost the space that should be separating each tag pill:

![c6c98d2a-4eb2-42d4-a211-d0f3473f9130](https://user-images.githubusercontent.com/174761/48980203-039eee80-f0be-11e8-9ca8-609c7b74cedd.jpeg)

**Comment by BurningTreeC** [comment]
I noticed that, too. I think we should just add a margin-right, maybe not for the last child

**Comment by pmario** [comment]
the pill has a class `tc-tag-label` ... if it would be `tc-tag-label tc-tag-list-item` it would get the right margin with 7px like in view-mode

**Comment by pmario** [comment]
In view mode the elements also contain a text element, which shouldn't be there. imo the text element is a bug.

**Comment by pmario** [comment]
if $:/core/ui/TagTemplate would have a `\whitespace trim` pragma, the text element would be gone

**Comment by pmario** [comment]
ino can be closed.

**Comment by Jermolene** [comment]
Thanks @pmario
