### ISSUE TITLE
update to katex 0.10.0

### ISSUE THREAD

**Issue by BurningTreeC** [Jermolene/TiddlyWiki5#3599]
Hi, in the group someone asked for a katex update to 0.10.0

There's a new extension for chemical syntax which would be very useful:

https://github.com/KaTeX/KaTeX/tree/master/contrib/mhchem

https://mhchem.github.io/MathJax-mhchem/

Do you think we can do this before 5.1.18?

**Comment by Jermolene** [comment]
Hi @BurningTreeC that looks really interesting. We could put it in 5.1.18, with the reasoning that given that it's a plugin there's no impact on the core, and you can presumably implement it in a manner that minimises any risks to the existing KaTeX functionality. Would you like to do the upgrade to v0.10.0 at the same time? (actually, it should be two separate PRs for clarity).

**Comment by BurningTreeC** [comment]
Hi @Jermolene , I'll try

**Comment by BurningTreeC** [comment]
@Jermolene, I've added the first PR for the version update #3600 ... would you mind having a look if this introduces rendering issues that have been solved in the past?

**Comment by BurningTreeC** [comment]
I'll add the chemistry stuff later on, when this is clear
