### ISSUE TITLE
Table of Contents toc-caption macro awkward behaviour

### ISSUE THREAD

**Issue by 00SS** [Jermolene/TiddlyWiki5#3624]
When using the Table of Content macros:

The top (first) macro in the Shadow file: [$:/core/macros/toc](https://tiddlywiki.com/#%24%3A%2Fcore%2Fmacros%2Ftoc) is -

```
\define toc-caption()
<$set name="tv-wikilinks" value="no">
  <$transclude field="caption">
    <$view field="title"/>
  </$transclude>
</$set>
\end
```

This means that if a Table of Contents macro lists a  **tiddler** that has a **caption** field, but the field is **empty**, the a table of contents listings shows an **blank** space for the title.

Would something like the below address this issue?

```
\define toc-caption()
<$set name="tv-wikilinks" value="no">
<$list filter="[all[shadows+tiddlers]has[caption]]" 
      emptyMessage="""<$transclude field="title"><$view field="title"/></$transclude>""">
  <$transclude field="caption">
    <$view field="title"/>
  </$transclude>
  </$list>
</$set> 
\end
```

**Comment by pmario** [comment]
I think you are right. ... but an empty caption creates problems with all other lists too! ... It should not be empty!

**Comment by pmario** [comment]
If it is empty, it should be removed!

**Comment by Jermolene** [comment]
Hi @00SS the reason that the toc-caption macro is separated out is so that it can be overridden for customisation purposes. So you can use your definition of toc-caption with a local definition, or a `<$importvariables>` widget, and then invoke the core TOC macro which will then use your definition of toc-caption. We don't want to make the core toc-caption macro too complicated because it is typically rendered many times.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by 00SS** [comment]
An empty title in a list can be quite confusing & disconcerting. Worse might be **not noticing** that such items are **not appearing** at all. Perhaps this can be adjusted in other lists that use captions as well?

So as not to increase overhead, could it be done this way with similar widgets as presently used?:

```
\define toc-caption()
<$set name="tv-wikilinks" value="no">
<$view field="caption"><$transclude field="title"/></$view>
</$set>
\end
```

**Comment by Jermolene** [comment]
Hi @00SS in that sample you've transposed the view and transclude widgets so that the caption field is being rendered as raw text, and the title field is wikified. That isn't the convention; the caption field is generally wikified (and so can include formatting etc.) while the title is rendered as plain text.

**Comment by pmario** [comment]
>An empty title in a list can be quite confusing & disconcerting. Worse might be **not noticing** that such items are **not appearing** at all. Perhaps this can be adjusted in other lists that use captions as well?

I think your concerns are valid here. ... The actual implementation makes it very hard for users to fix the problem, since you can't reach / and fix the tiddler, that causes the problem. 

@00SS ... As a workaround you should use the following code, since it should have better performance

```
\define toc-captionx()
<$set name="tv-wikilinks" value="no">
  <$list filter="[all[current]has[caption]]" 
      emptyMessage="""<$transclude field="title"><$view field="title"/></$transclude>""">
  <$transclude field="caption">
    <$view field="title"/>
  </$transclude>
  </$list>
</$set> 
\end
```

**Comment by pmario** [comment]
fixed a typo in the above code

**Comment by pmario** [comment]
@Jermolene ... I think this is a bug. .... 

And I did find several other problems eg: `toc-item` - `toc-item-selected` class detection doesn't work. ... and I think it never has.

**Comment by Jermolene** [comment]
Hi @pmario what is the bug exactly? That the view widget renders a blank field if it is present, rather than treating it as a missing field?

**Comment by pmario** [comment]
From my point of view, it's a "usability-bug". It's very hard for users to fix the problem, because "nothing" is rendered. 

So it's not possible to click something, that would open the tiddler, that contains the empty caption. 

On the other hand, this may be an intended usecase too! So fixing it may cause a problem for other users, which "misuse" the existing behaviour.

**Comment by Jermolene** [comment]
Thanks @pmario that makes sense.

**Comment by 00SS** [comment]
I appreciate the suggestion of having  my own **toc-caption** macro with a local definition. Would the below be the correct way to do it?
```
\define toc-caption()
<$set name="tv-wikilinks" value="no">
   <$list filter="[all[current]has[caption]]" 
      emptyMessage="""<$view field="title"/>""">
      <$transclude field="caption"/>
  </$list>
</$set> 
\end
```

A note somewhere may be useful - warning that an empty **caption** field will result in the ToC macros giving the behaviour mentioned in the original comment.

I feel that since the ToC is one of the early set of macros (probably the first) that a new user would try out, it is important that they anticipate this kind of situation. Missing tiddlers titles/captions in a list that one expects them to be there - not noticing some are missing - noticing some are missing and not knowing which ones - not knowing what the fix might be - not a nice predicament. Early confusion can lead to disappointment.

I personally have some hundreds of tiddlers that have an empty caption field, as the templates that created them automatically put in that field, along with many other empty fields. These are often filled in later when the information becomes available, or just left empty.

After 2 years of extensively using TW, it was only this week that I spotted this side effect, and that was because I randomly tested the **toc** macro to see what it did, and since it gave a simple numbered list, I saw missing titles. I took me a while to figure out the reason.

**Comment by 00SS** [comment]
A few weeks ago, there was a TiddlyWiki Google Groups post by bimlas (2018-11-03): [Why is there no table of content in the empty wiki?](https://groups.google.com/forum/?hl=en&#!topic/tiddlywiki/y7THOx9VJtQ)

This led to my post on TiddlyWikiDocs Google Groups (2018-11-16): [Beginners help for Table of Contents](https://groups.google.com/forum/?hl=en&#!topic/tiddlywikidocs/008FhZq2KEc)

It refers to the [TW I have been slowly adding to for Beginner's Documentation](https://00ss.github.io/help/Adding-a-table-of-contents-to-the-sidebar.html).

Unfortunately it hasn't attracted interest, though I feel at some point the work there may be useful for a part of TW5's help documentation for newer users.

I have added a note under how a **caption** field is used in a ToC as follows:

#### Note: A tiddler listed within a Table of Contents should NOT have a blank (empty) `caption` field as this will result in either a blank entry being displayed, or the entry not appearing at all.

**Comment by BurningTreeC** [comment]
Hi @00SS , @Jermolene , @pmario 

Another way to do it, I don't know about performance
```
\define toc-caption()
<$set name="tv-wikilinks" value="no">
  <$transclude field={{{ [get[caption]] -[get[caption]] +[[caption]] }}}>
    <$view field="title"/>
  </$transclude>
</$set>
\end
```

**Comment by BurningTreeC** [comment]
... No, just forget about my example ;)

**Comment by 00SS** [comment]
@Jermolene , @pmario , @BurningTreeC

On tiddlywiki.com there is a simple conditional tiddler used for documentation: [$:/editions/tw5.com/if-macro.js](https://github.com/Jermolene/TiddlyWiki5/blob/master/editions/tw5.com/tiddlers/system/if-macro.js)

If this macro is included in empty.html then it appears this works, without calling a <$list ...>:

```
\define toc-title() <$view field="title"/>
\define toc-caption()
<$set name="tv-wikilinks" value="no">
<$wikify name="cap" text={{!!caption}} output="html">  
<$macrocall $name=".if" cond={{!!caption}} then=<<cap>> else=<<toc-title>>/>
</$wikify>
</$set>
\end

```

**Comment by kookma** [comment]
@00SS 
Yes, this is a good suggestion, also why not to have this .if macro for conditional operatiion.
Right now it is done using the Reveal widget, but it is tedious comparing to this simple logic

**Comment by Jermolene** [comment]
I'd forgotten about the `.if` macro. I'd hope that now we can use the conditional filter syntax to get the same effect more elegantly.

**Comment by kookma** [comment]
@Jermolene 
 Is it the ~ Else operator or do you mean the reveal widget?

**Comment by 00SS** [comment]
For more ideas, I opened a discussion on 2019-02-06 to the tiddlywikidev Google Groups: 
[$view widget new attribute : format="wikified" ](https://groups.google.com/forum/?hl=en#!topic/tiddlywikidev/x9Oqcs3RSsM)

**Comment by 00SS** [comment]
Since the core `toc-caption` macro has to be rendered many times thus and needs to be _uncomplicated_ , this should hopefully not be any slower than the present one.
```
\define title() <$view field="title"/>
\define toc-caption()
   <$set name="tv-wikilinks" value="no">
   <$set name="display" tiddler=<<currentTiddler>> field="caption" emptyValue=<<title>>>
      <<display>>
   </$set>
   </$set> 
\end
```

**Comment by Jermolene** [comment]
Hi @00SS is the intent to display the title if the caption field is blank? Going back to your original post, why would that happen? It seems like it would be quite unusual for it to happen by accident. For what it's worth, it's not been reported or discussed before to my recollection.

**Comment by 00SS** [comment]
@Jermolene - yes, the intent is to display the title if the caption is blank.

The `caption` field is a "Standard Field" as defined in the [TiddlerFields](https://tiddlywiki.com/#TiddlerFields).

I believe it is counter intuitive to designate a field as a "Standard Field" and then expect a user to know it cannot be left blank, or force them to not leave them blank without a very valid reason. There is no breakage if many of the other Standard Fields are left blank, namely: `creator` `list` `tags` `text`. Even `type` can be left blank and has a default value. In essence, only the `title` field HAS to not be blank - and this behaviour is forced upon the user in order to save a tiddler.

What I feel is that the default value for a blank `caption` field should be the tiddler's `title` wherever core functions (macros basically) use the caption field. This is what one would both want and expect. Is it correct to withhold this expected and wanted behaviour because someone might want to display a blank line instead of a title in a Table of Contents or a `list-links` type macro? A backward compatiblity issue will arise if an empty caption field was being purposely used to suppress a title being shown in a Table of Contents (list-links etc. macro) - displaying a blank line instead. Other than that, I cannot envision it breaking anything else.

Say someone creates and fills in a caption field, then later decides he doesn't want that caption and deletes its contents, but not the field. At some later point, maybe months later, he notices that a `<<list-links>>` macro looks odd, some tiddlers are not listed, or a `<<list-links-draggable>>` macro has an empty position on a list, or that a Table of Contents listing seems to be missing entries. It is extremely difficult to spot, and very confusing to fix. 

As for my own experience for example, I used TiddlyWiki for almost 2 years before noticing there were tiddlers not being listed! And that too because I was playing with the `toc` macro for tiddlywiki.com documentation purposes. And I am a heavy user. It took me quite a bit of advanced listing to find out what was wrong.

Since the caption field can be used so effectively as an alternate title, and it is an integral part of some core macros, one can envision templates for creating tiddlers including this field when making new tiddlers.

My templates include those that create a caption field for tiddlers that hold information on: **authors** (442 tiddlers)  **publications** (114 mostly books) etc. More than half have an empty `caption` field. It is much easier to have a list of important fields ready in a tiddler for filling in, than remembering which are missing and adding the field when the information becomes available.

As for the final part of your question, I feel it is only a matter of time when the issue will be reported by others as more people use TW. (I of course have reported it multiple times as soon as I noticed it happening - once in the ToC, some weeks later in the list-links-draggable). I believe it is probably newer users who would have the issue and  perhaps have not even noticed the problem or come across it yet.

I think a decision can be made as to what is the preferred behaviour, and whether having that behaviour will create unwanted backward compatible problems.

Apologies for making you read so much for what could be considered a small issue in the big picture.
Of course I have "fixed" my macros, so it is not an issue for me anymore. I just feel it doesn't become TW to leave exposed this kind of breaking possibility on as significant an issue as the display of a Tiddler's title in important structural navigation components. Even more so when it now has a proper fix.

**Comment by Jermolene** [comment]
Hi @00SS that makes sense.

I'm wondering though if the best fix isn't to change the behaviour of the transclude widget so that it will treat a blank string the same as a missing string. The rationale is that your logic actually applies to any situation where we are relying on the transclude widget cascade mechanism. I'll look into it.
