### ISSUE TITLE
How to access qualified states from outside?

### ISSUE THREAD

**Issue by BurningTreeC** [Jermolene/TiddlyWiki5#3637]
This is  a question I've been thinking about for a while

I made an `action-popup` widget for my `raw-state` navigator plugin [here](https://burningtreec.github.io/TW5-navigator/) that should trigger popup states on/off

Somehow it should be able to access qualified states of known tiddlers

So I changed the qualify macro and widget to push its created states to a global array as `stateTile: tiddlerTitle` objects

Two filters `getqualifytiddler` and `getqualifiedstates` allow me to get the tiddler title corresponding to a qualified state or to get all qualified states corresponding to a tiddler title

Opening a tiddler in the story river that is present as an ui element in the sidebar for example causes some problems but the states can be filtered or I can prefer one state (for example the story-river state) over the other one

I believe such a mechanism would be very useful to have in the core and I'd like to discuss it here. Do you have any thoughts about it?

all the best, Simon

**Comment by BurningTreeC** [comment]
There's a plugin [here](https://github.com/BurningTreeC/TW5-qualifiedstates) that does what I've described above

**Comment by Jermolene** [comment]
Hi @BurningTreeC this is interesting! But of course the implementation is fraught with difficulties such as the fact that macros are not allowed to have side effects. What mechanism could be used to invalidate cached mappings? In a dynamic environment like this there's no guarantee that a mapping will persist for any length of time.

I think perhaps this is part of the wider conversation at #3591: popups and state tiddlers and qualified IDs are all intimately tied up together.

**Comment by BurningTreeC** [comment]
@Jermolene , the qualify macro itself doesn't necessarily need to be changed, it could be moved to the `getStateQualifier` function (?)

Yes this is related to the popups discussion, that's true. Now that I think more about it, it's also a reveal-widget thing ... so the reveal widget could update and validate mappings

I think it's not only a popup discussion

**Comment by BurningTreeC** [comment]
@pmario the qualify macro is used all over the place. Is replacing it an alternative for TW and its backwards compatibility?

**Comment by pmario** [comment]
>.. the qualify macro is used all over the place. Is replacing it an alternative for TW and its backwards compatibility?

I don't think so. .. but it could be replaced, with a compatible "drop-in" replacement, that creates predictable state tiddlers. 

I did link to my experiments, that you can see, what's needed. ... It shouldn't be the solution. ... It's just my way of changing things to see, what can be done.

**Comment by BurningTreeC** [comment]
Yes I've seen your experiments and I understand their approach. How do they react to reusing the same element a second time, in the same tiddler, in a second window, in the sidebar and the story river at the same time? We can't assume that users will keep the UI the way it is

**Comment by BurningTreeC** [comment]
The qualify widget could be a drop in replacement. It doesn't solve what you describe as the root of the problem but it would solve the limitation of the qualify macro not being allowed to have sideeffects

**Comment by Jermolene** [comment]
Hi @BurningTreeC widgets are only expected to have side effects within event handlers.

**Comment by BurningTreeC** [comment]
@Jermolene would it then be necessary to dispatch a qualify event and add a qualify listener somewhere?

**Comment by pmario** [comment]
>Yes I've seen your experiments and I understand their approach. How do they react to reusing the same element a second time

It's important to create unique names, by careful engineering. ... That's why the existing qualify macro is so convenient. ... Users don't need to take care ... It just works.

**Comment by pmario** [comment]
I see the usecase for your implementations. ... but I think, we need to go deeper. 

The code, that is responsible to return a unique name is: Widget.prototype.getStateQualifier
and the mechanism is described here: https://tiddlywiki.com/#transclusion%20Variable

The implementation is responsible for the `--` in some states, depending on the level of transclusion.

**Comment by pmario** [comment]
It should be possible, to create a new eg: `.getStateQualifierHR` for HumanReadable, which returns "better" state names.

**Comment by pmario** [comment]
A **new requirement** should be, that those state names also survive tiddler renaming. .. Which isn't the case atm.

**Comment by BurningTreeC** [comment]
Thanks @pmario , I know about the transclusion variable and I had looked into `getStateQualifier` in widget.js , I was trying to change something there, but felt like it was too much for what I wanted...

Now it seems that rethinking that function wouldn't be the worst thing

**Comment by Jermolene** [comment]
A useful precursor to making these kind of changes is to make sure that the existing documentation is up to date and usable. Hopefully it's obvious that almost any significant change is going to require a parallel, opt-in implementation alongside the existing mechanism, so we really need to have solid documentation for both.

The docs we have at present about the state mechanism are in StateMechanism, but they need to be broken down into smaller chunks so that we can elaborate on them -- everything is very terse at the moment: "...we append together tokens representating each of the stack of transclusions that led to the current rendering location. Then that string of symbols is hashed to a simple numeric value."

**Comment by AnthonyMuscio** [comment]
I would like to add my own "General" solution for qualifying tiddlers is to transform the created date into a unique ID, test to ensure it is unique, increment (milli-seconds) by one if not, inc again, then once set hide the ability to change that field. Of course system tiddlers could be given these ahead of time. Then the Unique ID can be used within a qualifier macro <<uniqueID $:/temp/named>> to generate 
$:/temp/named/IDNNNNNNNNNN

If the above was moved into a widget it would be great, especially if we had an action (on new tiddler) available as well.

Thus once locked onto a tiddler, it will remain the same regardless if the title or even created date changes. If the tiddler is transferred to another wiki it is unlikely to clash, but a test would ensure you can regenerate its uniqueness in the new wiki, perhaps with a qualifyer.

Yes this operated as a GUID which solves a lot of problems for which we have had independent calls for, for ages.  The only difference is it can be added retrospectively as needed, yet is cumulative.

Then we can add a few tools like Marios uni-links to create tiddlers with, also list, reference and transclude via the UniqueID mechanism. Or even use an edit toolbar to select a tiddler by name, but paste the UniqueID reference.

Benefits: There are many but I would the ability to rename tiddlers to system tiddlers to hide them but be able to continue referencing them via the UniqueID.

I already use my own solution to build "subtiddlers" for any given tiddler, but hide them below a System tiddler/UniqueID naming standard, and I can rename the primary tiddler without impact, the subtiddlers remain connected. These could be state tiddlers.

Regards
Tony

**Comment by BurningTreeC** [comment]
@Jermolene 

> A useful precursor to making these kind of changes is to make sure that the existing documentation is up to date and usable. Hopefully it's obvious that almost any significant change is going to require a parallel, opt-in implementation alongside the existing mechanism, so we really need to have solid documentation for both.

Yes I'm also thinking about that

> The docs we have at present about the state mechanism are in StateMechanism, but they need to be broken down into smaller chunks so that we can elaborate on them -- everything is very terse at the moment: "...we append together tokens representating each of the stack of transclusions that led to the current rendering location. Then that string of symbols is hashed to a simple numeric value."

I'll give this a try with a doc-PR

**Comment by BurningTreeC** [comment]
@AnthonyMuscio how does your solution work for states in the sidebar?

**Comment by BurningTreeC** [comment]
I tried an idea I got and it worked, I think it isn't that bad. It provides a way to break out of `getStateQualifier` if we set a specific value for `transclusion`:

```
Widget.prototype.getStateQualifier = function(name) {
	this.qualifiers = this.qualifiers || Object.create(null);
	name = name || "transclusion";
	if(this.qualifiers[name]) {
		return this.qualifiers[name];
	} else {
		var output = [],
			node = this;
		while(node && node.parentWidget) {
			if($tw.utils.hop(node.parentWidget.variables,name)) {
				if(node.getVariable(name) === "{|||||STOP}") {
					break;
				} else {
					output.push(node.getVariable(name));
				}
			}
			node = node.parentWidget;
		}
		var value = $tw.utils.hashString(output.join(""));
		this.qualifiers[name] = value;
		return value;
	}
};
```

What do you think?

in a tiddler I emulate the "road" down to the point where the qualified state is:

```
<$set name="transclusion" value="{|||||STOP}">
<$set name="transclusion" value="{|$:/core/ui/PageTemplate|||}">
<$set name="transclusion" value="{|$:/core/ui/PageTemplate/sidebar|||}">
<<qualify>>
</$set>
</$set>
</$set>
```

and voilá , I know the qualified state if I know the "road" and the state prefix, which is all doable

**Comment by BurningTreeC** [comment]
... In global keyboard shortcuts we don't need to break out of `getStateQualifier` because they are not within the `PageTemplate`, which means that accessing qualified states through "emulation" already works in keyboard shortcuts tagged `$:/tags/KeyboardShortcut`. Try this to cycle through the sidebar tabs in a global keyboard shortcut:

```
\define get-transclusion()
{|$(listItem)$|||}
\end
<$set name="transclusion" value="""{|$:/core/ui/PageTemplate|||}""">
<$set name="transclusion" value="""{|$:/core/ui/PageTemplate/sidebar|||}""">
<$list filter="[all[shadows+tiddlers]tag[$:/tags/SideBarSegment]suffix[tabs]]" variable="listItem">
<$set name="transclusion" value=<<get-transclusion>>>
<$set name="state" value=<<qualify "$:/state/tab/sidebar">>>
<$set name="currentTab" value={{{ [<state>get[text]] ~[{$:/config/DefaultSidebarTab}] }}}>
<$action-setfield $tiddler=<<state>> text={{{ [all[shadows+tiddlers]tag[$:/tags/SideBar]after<currentTab>] ~[{$:/config/DefaultSidebarTab}]  }}}/>
</$set>
</$set>
</$set>
</$list>
</$set>
</$set>
```

**Comment by BurningTreeC** [comment]
We don't need to modify anything if we add a widget that does nothing else than `this.parentWidget = $tw.rootWidget` ... I call it `rootpipe`, it's working well for me
