### ISSUE TITLE
Simple Improvment request "subfilter" operator alias "filter"

### ISSUE THREAD

**Issue by AnthonyMuscio** [Jermolene/TiddlyWiki5#3644]
Folks,

I have started using the NEW subfilter operator and find it helps simplify filter code massively, basically because you can create named filters in macros such as active-task and apply it in a filter as [subfilter<active-task>] this allows filters to be read very simply and logically, and updating the active-task macro need only be done once, and it will be available in all filters that use it, allowing designs to be extended.

**To me there are cases where we will use subfilter where there is no filter to be sub of.**

It may be clear that then I would be likely to start a filter with a subfilter operator. This is not altogether the best wording so I would like to suggest another alias for the same subfilter operator. Ideally filter[] but another may be acceptable such as "titles[]" "input-titles[]" "list-titles[]" perhaps even filter-list[] or list-filter[]

However I feel **filters** is the best option as sometimes they will return a list that is not actual tiddler titles.

Thus rather than write
`"[subfilter<active-task>subfilter<in-context>]"`

We could write
```
"[filter<active-task>subfilter<in-context>]"
"[filter<active-task>subfilter<in-context>has[item-planned]]"
```

or
```
"[titles<active-task>subfilter<in-context>]"
"[input-titles<active-task>subfilter<in-context>]"
"[list-titles<active-task>subfilter<in-context>]"
"[list-filter<active-task>subfilter<in-context>]"
"[filter-list<active-task>subfilter<in-context>]"
```

In the long run I expect a set of subfilter macros may be bundled as a starting point for many solutions. For example a set of subfilters for a todo list 
new-task
active-task
inactive-task
completed-task
cancelled-task
archived-task

These can be then used to test if the current tiddler belongs to one of these, or list all tiddlers meeting that criteria. **Anything that can reduce the complexity of filters is always welcome.**

**Comment by AnthonyMuscio** [comment]
Edits applied above to format as code blocks.

On further thought, would it be too much to allow users to define one or more aliases for the sub-filter operator a bit like how we can use field-name[value] as a text? I am not sure how to handle "disambiguation" (if that is the word)

**Comment by pmario** [comment]
>... **Anything that can reduce the complexity of filters is always welcome.**

That's right and it also allows users to create a DSL "domain specific language" as you did with your "-task" examples. ... BUT what if my DSL is not your DSL? ... 

So as a beginning I'd like to have new subfilter-DSLs as plugins. Your examples may be part of a future "task-management" edition, because it would fit there.

**Comment by Jermolene** [comment]
Hi @AnthonyMuscio the logic of the operator being called "subfilter" is because it is itself used as a component of a filter, and so the filter that it references is a sub-filter. The logic is analagous to a "subroutine" in programming.  I don't really see the case for renaming it to "filter", I'm afraid.

**Comment by AnthonyMuscio** [comment]
Mario,

I acknowledge there may be alternate DSLs as you put it but surely it makes sense if I supply one with a macro, plugin or edition so as to make it more readable and extendable to those using it?

You could say it is a bundle of subfilters to extend the ease of use and customisation.

For example I could publish one that supports geneological trees, or that supports a custom field.

Regards

**Comment by AnthonyMuscio** [comment]
Jeremy,

I leave it to you, but if you could find an alias that was better than starting a filter definition with a subfilter it would read better.

I am always looking for ways to code and explain in a simpler manner for new users. This comes from contributing a lot to the google groups. Where possible we should do our best to reduce tge complexity. Perhaps this is not it but I hope you can understand why I asked.

Tony

**Comment by pmario** [comment]
>For example I could publish one that supports geneological trees, or that supports a custom field.

That's right. What I wanted to say is: We need to start with bundles and plugins. Then see, what is generic enough to be part of empty.hml

**Comment by Jermolene** [comment]
Hi @AnthonyMuscio I don't see the problem with starting a filter definition with a subfilter; structurally, it is a subfilter to the filter one is reading. `<$list filter="[filter<blah>]"/>` looks weirder to my eyes because of the repetition of the word "filter".

**Comment by diego898** [comment]
@AnthonyMuscio - would you be willing to post your example use of subfilter? thanks!

**Comment by AnthonyMuscio** [comment]
Diego,

An example would be pre-defined subfilters
\define is-task() [tiddler-type[task]
\define new-task() [tiddler-type[task]!has[item-started]!has[item-completed]!has[item-cancelled]]
\define active-task() "[tiddler-type[task]has[item-started]!has[item-completed]!has[item-cancelled]]
\define completed-task() [tiddler-type[task]has[item-completed]]
\define in-context() [domain{!!domain}project{!!project}client{!!client}]
\define new-task-in-context() <<new-task>> +[domain{!!domain}project{!!project}client{!!client}]

In this case each tiddler will have a field time stamped as needed eg item-started item-completed or item-cancelled

Then in a List filter you could use
<$list filter="[is[current]subfilter<new-task>]">
Show if current task is a new task
</$list>

<$list filter="[subfilter<new-task>]">
List all new tasks not started, closed or completed
</$list>

<$list filter="[subfilter<active-task>subfilter<in-context>]">
List all new tasks not started, closed or completed in the same "context" as the current tiddler.
</$list>

and all that follows from this.

Basically it is a way to set-up your own custom filters and use them as needed from that point forward, it helps define the meaning of different fields in tiddlers and with careful design one could use this as a package to define fields/tiddlers and list them in a way that the detailed logic can be forgotten and the subfilters become more readable, and simpler to extend than if you were using the RAW wiki filters. you can always return to the full definition if required. 

Personally, in defining these subfilters it is easy to code for all expected filter permutations for the set of fields you intend to mange and their related logic, ie if item-cancelled has a value it does not matter if it never started eg item-started empty.

Notice how in-context will only show items with the current tiddlers matching domain project and client fields.

Regards
Tony

Post Script
The Above concept has being tested but the above code not tested, especially the last one new-task-in-context.

**Comment by AnthonyMuscio** [comment]
Edited previous to fix code highlighting.

**Comment by AnthonyMuscio** [comment]
Closed issue as Jeremys argument that filter="[filter<filtername>]" is worse that what I was complaining about filter="[subfilter<filtername>]" and I am struggling to come up with another better name, for an alias so it reads nicer.

I feel there may be an opportunity to provide a neater way of starting a run with another form of  subfilter and adding value, the subject of a future request perhaps.

I will re-open if I have a brainstorm.
