### ISSUE TITLE
Fix: Display of backlinks when renaming a tiddler - Hide when none

### ISSUE THREAD

**Issue by AnthonyMuscio** [Jermolene/TiddlyWiki5#3648]
Show backlinks on rename (#3534) 

**During rename**
_The following references to this tiddler will not be automatically updated:
No tiddlers link to this one_

Please fix this so the "The following references to this tiddler will not be automatically updated:" is not shown unless there are references. at present you must click to see, "No tiddlers link to this one" and it is a wast of valuable screen space for no reason.

It would be useful if we could use a system tag so this function could be extended by users but this is not part of this request.

**Comment by Jermolene** [comment]
Thanks @AnthonyMuscio that's a good idea, but I'm not going to tackle it for v5.1.19 because it's not a bug, and I'm trying to keep this release as low risk as possible.

**Comment by AnthonyMuscio** [comment]
Thanks Diego, To me it may not be a bug but it was in need of better design.

**Comment by diego898** [comment]
I believe #3654 successfully closes this. @AnthonyMuscio what do you think?

**Comment by AnthonyMuscio** [comment]
Agreed Diego, a quick test on tiddlywiki.com 5.1.21 suggests this is fixed - thanks
