### ISSUE TITLE
Rapid refreshing in browser crashes the server

### ISSUE THREAD

**Issue by david-pp** [Jermolene/TiddlyWiki5#365]
run TW5 by node.js. if you open the browser, and hold the F5(Refresh) button, the cpu is overload.. and memory leaks.. finally, server is crashed ...

maybe, some cache or limit the refresh rate will solve it ..

**Comment by pmario** [comment]
I did a test: 

```
D:\git\tiddly\tiddlywiki\TiddlyWiki5 [master +1 ~0 -0 !]> node .\tiddlywiki.js .\editions\tw5.com-server --verbose --server
```

which shows:

```
Boot log:
  Startup task: load-modules
  Startup task: info after: load-modules before: startup
  Startup task: startup after: load-modules
  Startup task: story after: startup
  Startup task: commands platforms: node after: story
Executing command: server
Serving on 127.0.0.1:8080
(press ctrl-C to exit)
```

In the browser I use: `http://localhost:8080/#:` to load the page
The server log shows:

```
syncer-server: Dispatching 'save' task: $:/StoryList
FileSystem: Saved file D:\git\tiddly\tiddlywiki\TiddlyWiki5\editions\tw5.com\tiddlers\$__StoryList.tid
syncer-server: Dispatching 'load' task: bf Operator
syncer-server: Dispatching 'load' task: butfirst Operator
syncer-server: Dispatching 'load' task: Caruso - Ave Maria
syncer-server: Dispatching 'save' task: $:/StoryList
FileSystem: Saved file D:\git\tiddly\tiddlywiki\TiddlyWiki5\editions\tw5.com\tiddlers\$__StoryList.tid
```

So one more thing is strange. 

 - Where does the "Caruso sync" task come from
 - Hitting F5 continuously still crashes the server

**Comment by Jermolene** [comment]
Hi @pmario sorry for the delayed response...

The reason for those "load" tasks is that all of the three tiddlers `bf Operator`, `butfirst Operator` and `Caruso - Ave Maria` are tiddlers in tw5.com that do not have a text field, thus triggering the lazy loading process.

**Comment by pmario** [comment]
@david-pp  .. can you still reproduce the problem? .. I can't FF latest with ubuntu 17.04, nodejs v 6.10.3

**Comment by pmario** [comment]
@Jermolene ... With the latest version of tiddlywiki server I can't reproduce a crash. ... It shows a network connection alert, but after enough time the connection is re-established. .. IMO this should be closed

**Comment by Jermolene** [comment]
Thanks @pmario
