### ISSUE TITLE
more-tiddler-actions popup doesn't animate

### ISSUE THREAD

**Issue by BurningTreeC** [Jermolene/TiddlyWiki5#3652]
Hi all, is the more-tiddler-actions popup supposed to animate?

I ask because its `reveal` widget has `animate="yes"` but it only animates if I also add `retain="yes"`

**Comment by Jermolene** [comment]
Hi @BurningTreeC apologies my memory is a bit faded but I think that it did indeed once animate but that I removed it for performance reasons. Definitely worth experimenting with.

**Comment by BurningTreeC** [comment]
I also think it's better without animation
