### ISSUE TITLE
$:/tags/SideBarSegment not working in 5.1.18?

### ISSUE THREAD

**Issue by AnthonyMuscio** [Jermolene/TiddlyWiki5#3656]
In 5.1.18

I assumed if you tag a tiddler with $:/tags/SideBarSegment it will be listed in the sidebar.

It is not working, or have I missed something

See Overhaul of sidebar making modular. #2758

**Comment by Jermolene** [comment]
Hi @AnthonyMuscio can you show what you tried?

**Comment by AnthonyMuscio** [comment]
Sorry, Just discovered a number of my Wikis, of course the ones I tested this on, all have $:/core/ui/PageTemplate/sidebar overwritten. I have being using a self developed equivalent for some time and it is on most of my wikis.

I will do it on TidllyWiki.com before I raise an issue again.

Tony
