### ISSUE TITLE
Feature Request: Add Tobias's Split and Join to the Core

### ISSUE THREAD

**Issue by diego898** [Jermolene/TiddlyWiki5#3658]
I think Tobias' [split](https://tobibeer.github.io/tw5-plugins/#split) and [join](https://tobibeer.github.io/tw5-plugins/#join) should be part of the core. How can we make that happen? I dont think its appropriate for me to push it?

**Comment by pmario** [comment]
Hi Diego, ... The problem with those plugins is, that they introduce a new syntax, that is not consistent with the existing one. The plugins are from 2015. Many of Tobias's ideas have been implemented in a consistent way, with different names. 

With 5.1.18 the `search` operator introduces a new way to add multiple flags to operators. So the requested plugins would be needed to be rewritten.

**Comment by diego898** [comment]
Hey Mario - should we then use this issue to track adding new split and join operators (that are based on Tobias')? Or should we close this and make a new feature request?

**Comment by pmario** [comment]
imo we can use this one,

**Comment by diego898** [comment]
Hey @pmario - which one did you mean?
