### ISSUE TITLE
Styles by data-tags are not applied in preview pane

### ISSUE THREAD

**Issue by rubaboo** [Jermolene/TiddlyWiki5#3661]
Please add `data-tags` to the appropriate shadow (`$:/core/ui/EditTemplate/body/preview/output` maybe?) so that the preview is formatted correctly when "styles by data-tags" are used.

**Comment by pmario** [comment]
Yea. That's an oversight.

**Comment by pmario** [comment]
IMO It needs to be [$:/core/ui/EditTemplate/body/default](https://tiddlywiki.com/#%24%3A%2Fcore%2Fui%2FEditTemplate%2Fbody%2Fdefault)

and line

```
<div class="tc-tiddler-preview-preview">
```

would need to be changed to

```
<div class="tc-tiddler-preview-preview" data-tiddler-title={{!!draft.title}} data-tags={{!!tags}}>
```

I think data-tiddler-title should be there too. May be someone will want to style the new tiddler by title too. `{{!!draft.title}}` has to be used. More testing would be needed.

**Comment by Jermolene** [comment]
Thanks @rubaboo @pmario – would you be able to prepare a PR?

**Comment by pmario** [comment]
@rubaboo @Jermolene ... IMO this one can be closed .. a PR has been merged.

**Comment by Jermolene** [comment]
Thanks @pmario
