### ISSUE TITLE
Simplify default font family

### ISSUE THREAD

**Issue by rubaboo** [Jermolene/TiddlyWiki5#3662]
I think those "x"-es used to look bigger before, like on the right maybe?

![image](https://user-images.githubusercontent.com/212368/50388475-9ab29280-06cc-11e9-9525-8f5717dd0cc0.png)

This issue manifests in Firefox, not so much in Chrome because of Chrome's "user agent stylesheet".

I am guessing the relevant pieces of CSS would be
`$:/themes/tiddlywiki/vanilla/reset`
```
button, input, optgroup, select, textarea {
    color: inherit;
    font: inherit;
        line-height: inherit;
    margin: 0;
}
```
and `$:/themes/tiddlywiki/vanilla/base`
```
button.tc-tag-label, span.tc-tag-label {
    font-size: 0.9em;
    font-weight: 400;
    …
}
```

I can take care of this whichever way I want in my own stylesheet, but not sure how to fix it for the project, with minimal impact. Leaving it to pro's to figure out.

**Comment by rubaboo** [comment]
Assuming this needs fixing, that is. If the new appearance is by design, please close the issue.

**Comment by 00SS** [comment]
I preferred that little more space between the "x" and the link (the previous version's style). Makes it easier and thus faster when I close many tiddlers in a long story river one-by-one, which I often have to do.

**Comment by pmario** [comment]
Which OS and browser versions do you use? ... It looks different for me.

**Comment by rubaboo** [comment]
Firefox 63 on Linux. Looks more normal in Chrome.

**Comment by pmario** [comment]
I'm using FF64 and ubuntu 18.04. The x-es are a bit smaller, but position is ok for me. Nowhere near your screenshots. That's funny.

**Comment by pmario** [comment]
TW version?

**Comment by rubaboo** [comment]
https://github.com/Jermolene/TiddlyWiki5/commit/04ba91ce2f69e59a66ffda47646e3b8cca05cdfe

**Comment by rubaboo** [comment]
Thanks for the hints, maybe I'll try playing with font-config one day. For now I tweaked font-size for `.tc-remove-tag-button`. It's a bit more hacky for `.tc-btn-mini`in the sidebar - I have to skip "close all" button as it's already a good size.

**Comment by BurningTreeC** [comment]
@rubaboo , you can try the following to see if it has something to do with the fonts:

open the ControlPanel and go to Appearance - Theme Tweaks

under Settings - Font Family try removing ",Helvetica ,Arial"

then see if that affects the "x"-es

**Comment by rubaboo** [comment]
Would it not make sense to simplify the defaults to only these, and leave the rest to the user?

|                  |            |
|------------------|------------|
| Font family      | sans-serif |
| Code font family | monospace  |

**Comment by BurningTreeC** [comment]
@rubaboo , yes I was thinking the same. Reordering the font-names already has an impact. The system will pick the first found font, so if you move Helvetica and Arial after sans-serif, it should already be better

You're right about reopening this issue - I propose to rename it to something that reflects the font-name ordering issues, what do you think?

**Comment by BurningTreeC** [comment]
also the SegoeUI caused some problems on my part

**Comment by rubaboo** [comment]
Sure, can you suggest a better title? I don't see it as just a matter of reordering. Putting "sans-serif" in front of other fonts doesn't really make sense, does it? I don't have -apple-system, BlinkMacSystemFont, or "Segoe UI" on my system, so by removing Helvetica and Arial I effectively made "sans-serif" take effect. Having it as the default font family seems more platform-agnostic.

**Comment by BurningTreeC** [comment]
There's a pretty popular modern normalize.css [here](https://github.com/sindresorhus/modern-normalize) which appears to be worth having a look at

The font-family for example is defined like this:

```
body {
	font-family:
		-apple-system,
		BlinkMacSystemFont,
		'Segoe UI',
		Roboto,
		Helvetica,
		Arial,
		sans-serif,
		'Apple Color Emoji',
		'Segoe UI Emoji',
		'Segoe UI Symbol';
}
```

... preferring Roboto over Helvetica and Arial is reasonable

**Comment by rubaboo** [comment]
That article specifically says they removed Roboto as it caused issues in some distros. It seems GitHub devs prefer Mac, and Linux users are relegated to tinkering with their font-config.

**Comment by pmario** [comment]
@rubaboo ... Is this still a problem? .. If not please close it. @Jermolene ?

**Comment by Jermolene** [comment]
@pmario we haven't made any changes to the default font family since then, so I think it might still be relevant:

https://github.com/Jermolene/TiddlyWiki5/commits/master/themes/tiddlywiki/vanilla/settings.multids

**Comment by pmario** [comment]
>I am guessing the relevant pieces of CSS would be
>$:/themes/tiddlywiki/vanilla/reset
>
>```
>button, input, optgroup, select, textarea {
>    color: inherit;
>    font: inherit;
>        line-height: inherit;
>    margin: 0;
>}
>```

The reset looks like this now:

**Comment by pmario** [comment]
@Jermolene .. I think it's safe to close the issue, since the conditions of the OP have changed.

**Comment by pmario** [comment]
As mentioned at: https://github.com/Jermolene/TiddlyWiki5/issues/3662#issuecomment-449725552 I could replicated the problem with old FF and older OS. .. But now since we use the new reset the tag close-buttons look just fine and the same size as for FF on windows

**Comment by Jermolene** [comment]
OK thanks @pmario

**Comment by rubaboo** [comment]
Hi @pmario, Please go ahead and deal with my remaining 19 open issues as you see fit. Or don't. I have unfortunately lost all interest in contributing to this project. I think it would be a disservice to the community for me to blindly go and close those issues. I'd rather have someone do it meaningfully. Thanks for all the fish!

**Comment by Jermolene** [comment]
Hi @rubaboo I'm sorry to hear that, and very sorry if you have had a bad experience with the project – you have been a valuable contributor to the project over quite a few years. Is there anything that we could have done differently? Do feel free to email me privately via jeremy (at) jermolene (dot) com.
