### ISSUE TITLE
DOCS: replace <<list-links ...>> with <<toc-tabbed-internal-nav ...>>

### ISSUE THREAD

**Issue by 00SS** [Jermolene/TiddlyWiki5#3664]
I have been wondering if using a Tabbed Internal Table of Contents (**toc-tabbed-internal-nav**) may be an effective way to present certain groups of tiddlers.

For an example, please look at at [THIS Help Internal ToC](https://00ss.github.io/help/Adding-a-table-of-contents-to-the-sidebar.html). This is what I am proposing. 

Is this a good idea? If so, I may work a little on making the changes for further discussion.

The below tiddlers have all used a simple **list-links** macro for a **tag** related list. I propose  this presentation is changed to a Tabbed Internal Table of Contents.

The modifications needed to make these changes appears to be quite minor and easy - but the presentation style gives large benefits for quick review and navigation.

_List of tiddlers  (apart from the ones marked --X--) to look at modifying the display:_
- About 
- Commands
- Concepts
- Core Macros
- Core Variables
- Custom Styles FAQ
- Customise TiddlyWiki
- Definitions 
-   --X-- Editions
-   --X--  Editor toolbar
- Features
-   --X--  Filter Syntax
- Hidden Settings
- How to apply custom styles
-   --X--  Languages
- Learning
- Macro Syntax
- Mechanisms
- Messages
- OfficialPlugins
- Platforms 
- Plugin Editions
- PluginMechanism
- Plugins
- --X-- ReadMe -->tag--> TiddlyWiki on Node.js
- Videos 
- Webserver -->tag--> WebServer Parameters & WebServer Guides
- WebServer API
- WebServer Guides
- WebServer Parameters
- Widgets -->tag--> Widgets
- Widgets in WikiText -->tag--> Widgets
- WikiText
- Working with TiddlyWiki

**Comment by 00SS** [comment]
If you save this text file (  [Tiddlers using List Links.txt](https://github.com/Jermolene/TiddlyWiki5/files/2720328/Tiddlers.using.List.Links.txt) ) - rename it to *.tid and import (drag & drop) it into http://tiddlywiki.com/

It shows the number of **list-links** links for each tiddler that is a possible candidate for changing to a **toc-tabbed-internal-nav** ToC .



Below are the tiddlers that contain a list-links of **over 20 links:**

- Widgets 	46
- Messages 	43
- Concepts	37
- Learning 	33
- Definitions	32
- Core Macros	29
- Features	24
- Commands	23
- Core Variables	22
- WikiText	22
- WebServer Parameters	21
- Working with TiddlyWiki	20

**Comment by ibnishak** [comment]
Please consider that it looks rather confusing on mobile screens

**Comment by 00SS** [comment]
I must admit I do not use _smart phones_ and thus never considered this.

To get an idea of how others solve the issue, I am looking at https://www.w3schools.com/html/default.asp on my laptop, and on an Android mobile. The two presentation styles are completely different.

The normal style is very much like TW's **toc-tabbed-internal-nav** Table of Contents.

The mobile version changes the left side menu into a clickable dropdown (upper left of the screen). I wonder if anyone has already implemented this in a TW table of contents.

Each page on both a laptop and a mobile also has a [< Previous] [Next >] button, both at the top and the bottom of the page being displayed.

At tiddlywiki.com - the present Table of Contents when fully expanded is over 1,700 lines long. This is much more like an **index**. It is really difficult to use efficiently.

A better way of navigating through the information would be very useful.

Any ideas?

**Comment by 00SS** [comment]
Another thought for the following tiddlers:

Tiddler name | Links
-------------- | ----
Widgets | 46
Messages | 43
Definitions | 32
Commands | 23
Core Macros | 29
Core Variables | 22
WikiText | 22
WebServer Parameters | 21
OfficialPlugins | 13
Hidden Setting | 7
Platforms | 4

What if these were remade in the same style as: **Filter Operators**
`<$count filter="[tag[Filter Operators]]"/>` = 90

This **Filter Operators** table layout style with a short summary and a link to the detailed tiddler is really useful. I refer to it very often because it is so informative. It also displays well in both wide and narrow screen devices.

**Comment by Jermolene** [comment]
Hi @00SS I wonder if another solution might not be to explore adding a variant of `<<list-links>>` macro that is better suited to displaying larger numbers of items. It could include an input box for filtering the list, and options to reduce the font size and use multiple columns where the screen is wide enough.

Looking through your wiki I see many good suggestions. I wonder if we should establish a new ticket for keeping track of all the work you are doing, just to make sure that I pay attention to the areas that will make the most difference for you.

**Comment by 00SS** [comment]
Thanks for the suggestions @Jermolene - I've been mulling over this for almost 2 weeks now.

I can't come to any conclusions so I thought to try one possibility.

An effective solution might be the way [Filter Operators](https://tiddlywiki.com/#Filter%20Operators) is laid out in tables. That entails each item having fields 
1. `description`  
1. `caption` (many already have this)
1. Other relevant information field(s) - in this example: `location`

I tried this with the tiddler: [Hidden Settings](https://00ss.github.io/help/Adding-a-table-of-contents-to-the-sidebar.html#Hidden%20Settings)

Attached a json for record: [Hidden Settings.zip](https://github.com/Jermolene/TiddlyWiki5/files/2871567/Hidden.Settings.zip)

**Comment by 00SS** [comment]
Anyone has perhaps 30 seconds to look at the new layout for: [Hidden Settings](https://00ss.github.io/help/Adding-a-table-of-contents-to-the-sidebar.html#Hidden%20Settings) ?

Would be useful to know if this was a better layout that the original [tiddlywiki.com list-links style](https://tiddlywiki.com/#Hidden%20Settings).

If it is, then effort could be made to do the same for other similarly presented tiddlers using **list-links**.

Thanks

**Comment by 00SS** [comment]
Perhaps if not 30 seconds, then 20 seconds? 
:disappointed:
