### ISSUE TITLE
Table of Contents macro toc-tabbed internal-nav & external-nav awkward behaviour

### ISSUE THREAD

**Issue by 00SS** [Jermolene/TiddlyWiki5#3675]
In the Table of Contents macros:

- <<toc-tabbed-internal-nav ... >>
- <<toc-tabbed-external-nav ...>>

If a tiddler has a **caption** field with _value_, then this _value_ shows up in the link index on the left.
This is the expected behaviour.

However when the link is clicked, and the tiddler opens in the right pane, the same **caption** _value_ also shows up as the **title** in the right pane!

This is not an expected behaviour. The tiddler in the pane should show the tiddler's **title**

Or am I mistaken?

**Comment by 00SS** [comment]
Fortunately a question was asked in Google Groups precisely to correct this anomaly : [TOC question](https://groups.google.com/forum/?hl=en#!topic/tiddlywiki/sZNfQBxMs3c) ( David Gifford 2019-02-07 )

In answering it, I believe I found this fix:

Open the shadow tiddler: [$:/core/macros/toc](https://github.com/Jermolene/TiddlyWiki5/blob/master/core/wiki/macros/toc.tid)

Find the line (169) starting with : \define toc-tabbed-external-nav(

_Note: Yes, I believe that is the correct line for modifying the **toc-tabbed-internal-nav** as this macro calls that one._

Find this line (180) : `<h1><<toc-caption>></h1>`

Change it to this : `<h1><$view field="title"/></h1>`

If it is agreed this is the expected proper behaviour, I will submit a Pull Request.

**Comment by Jermolene** [comment]
Hi @00SS the current behaviour of preferring the caption field over the title for the heading inside the tabbed TOCs is intentional. If you want different behaviour then you can pass a custom template to the macro. The default template is:

```
          <h1><<toc-caption>></h1>
          <$transclude mode="block">$missingText$</$transclude>
```

**Comment by 00SS** [comment]
Thanks @Jermolene 

Using the parameter `template=`  when invoking the macro, and adding the below in the template tiddler - is the right way to get the desired result and resolves the issue perfectly.

```
<h1><$text text=<<currentTiddler>>/></h1>
<$transclude mode="block">$missingText$</$transclude>
```
