### ISSUE TITLE
Tiddlers are not being saved or updated (no warnings are shown)

### ISSUE THREAD

**Issue by neil-rubens** [Jermolene/TiddlyWiki5#368]
Tiddlers are not being saved or updated (without any messages or warnings).  
# Details

TW5 ver: 5.0.6-beta
TW mode: w/ node.js server (localhost)
OS: OSX Mavericks
Browser: Safari

I had been using TW in the same Safari window for several days.  I use git to commit my changes; and have noticed that the files were no longer changed.  I confirmed this behavior by trying to update & create tiddlers; but the changes were not persisted to disk; even though changes were shown in the browser; in addition there were no messages at all on the terminal window (e.g. "Saved file ...", or "Deleted file ..."); to make sure I checked the .tid files by there were no changes.  p.s.  I did put computer to sleep several times (am not sure if that had a side-effect).

I then opened a new Safari window; I then was able to create/update tidlers that did persist to disk.  Although none of the changes that were made in the original browser window were shown.

This is probably a major issue since no error messages or warnings are shown; even though none of the changes are being saved.  Unfortunately I am not sure how to reproduce this behavior.  Please let me know if there are any log files that I can submit to help with diagnosing this issue.

**Comment by Jermolene** [comment]
Thanks @pmario
