### ISSUE TITLE
extra spaces inserted: Using conditional view widget to show caption or title

### ISSUE THREAD

**Issue by kookma** [Jermolene/TiddlyWiki5#3681]
I have a macro as below to show the title or caption of a tiddler based on the availability of caption field

```
\define mac(tid)
[<$view tiddler=$tid$ field="caption">
<$view tiddler=$tid$ field="title"/>
</$view>]
\endEnter
```

Then I have several tiddlers like t-2016, t-2017, t-2018, t-2019. The two tiddler t-2017 and t-2018 also have c-2017 and c-2018 as caption.

Using the above macro as below gives the below results

`Note <<mac t-2017>> and <<mac t-2018>> and <<mac t-2019>> and  <<mac t-2016>> give different result.`

Result:

`Note [c-2017] and [c-2018] and [ t-2019 ] and [ t-2016 ] give different result.`

As you can see extra spaces are inserted when title is shown! What is the problem.

I expect to have the same behavior in both cases.

[Forum discussion](https://groups.google.com/d/msg/tiddlywiki/dzZWAa5Hmlo/SPxl3PM9EQAJ)

**Comment by Jermolene** [comment]
Hi @kookma in this situation, yes: the line breaks are passed through to the browser and it's the browser HTML parsing logic that treats line breaks as white space.

So, the following HTML renders as `This is whitespace`:

```
<div>
This is
whitespace
</div>
```

**Comment by kookma** [comment]
@Jermolene 
Thank you. So this is normal and not a bug!
