### ISSUE TITLE
TiddlyDesktop language strings should go into TW core

### ISSUE THREAD

**Issue by BurningTreeC** [Jermolene/TiddlyWiki5#3691]
Working on "aTW" (Android application for TiddlyWiki) I figured that language strings used in the TiddlyDesktop "landing page" should be in the tiddlywiki core, so that they can be translated and we can reuse the language system for it

Can we do that?

all the best, BTC

**Comment by AnthonyMuscio** [comment]
BTC Have you a GitHub project for this app?

Could you please consider my suggestion [Alternative File Extension for TiddlyWiki Files #3719](https://github.com/Jermolene/TiddlyWiki5/issues/3719)
