### ISSUE TITLE
Filtered attributes cannot contain newlines

### ISSUE THREAD

**Issue by Jermolene** [Jermolene/TiddlyWiki5#3692]
Although filters accept newlines as whitespace, the filtered attribute parser does not accept newlines. Thus this example does not work unless the newline is removed:

```
<$text text={{{ [[this has
spaces]] }}}/>
```

**Comment by kookma** [comment]
@Jermolene 
I expect we can have flexibility when we develop a TW code (script). So as Joe asked in this [post](https://groups.google.com/d/msg/tiddlywiki/R6QFOPP5Hhs/io97FqW9CAAJ) it would be great to be able to write a readable code to be able to debug or understand by others.

**Comment by AnthonyMuscio** [comment]
I support doing what we can to allow well formatted code for readability and self documentation especially since code sharing is so common in the community. This may also assist in the generation of dynamic filters.

**Comment by kookma** [comment]
@Jermolene - this issue is rather old, please see your discussion with the late Joe Armstrong here: https://groups.google.com/g/tiddlywiki/c/R6QFOPP5Hhs/m/-zXDbl-VGAAJ
 
you said there
>  I think we can fix this without impairing backwards compatibility, and I've created a ticket here:

My concern is about better readability and am highly in favor of 

```
<$set name="username" 
           value={{$:/status/UserName}} 
           emptyValue="(anonymous)">
  <$set name="target" 
             filter="[<currentTiddler>]">
    <$action-createtiddler 
        $basetitle={{{ [[Comment by ']] 
                                +[addsuffix<username>] 
                                +[addsuffix[' on ' ]] 
                                +[addsuffix<currentTiddler>] 
                                +[addsuffix[']] }}} 
        role="comment"
        list=<<target>> 
        text="" 
        edit-mode="yes"/>
    </$set>
</$set>
```

instead of 

```
<$set name="username" value={{$:/status/UserName}} emptyValue="(anonymous)">
<$set name="target" filter="[<currentTiddler>]">
<$action-createtiddler 
    $basetitle={{{ [[Comment by ']] +[addsuffix<username>] +[addsuffix[' on ' ]] +[addsuffix<currentTiddler>] +[addsuffix[']] }}} 
      role="comment" list=<<target>> text="" edit-mode="yes"/>
</$set>
</$set>
```

**Comment by Jermolene** [comment]
Thanks for the reminder @kookma. I'll post a PR shortly.
