### ISSUE TITLE
aTW - TiddlyWiki communication

### ISSUE THREAD

**Issue by BurningTreeC** [Jermolene/TiddlyWiki5#3699]
Hi @Jermolene and everyone interested in a tiddlywiki application for Android

I'm thinking about if it's possible to load a plugin within a tiddlywiki on startup if it's not installed

The reason is that while working on *aTW* I need a bit of communication between the app and the open wikies.
I'd like to have a wiki respond to some requests, like the site title, subtitle, background color and possibly more useful requests in the future

Wikies can also be opened directly from a file browser ...
that's why it would be great if it'd be possible to test at startup if a plugin is installed and if not, install it. aTW can evaluate javascript code within the loaded html, which means there's access to `$tw` and we can "inject" javascript to be executed

I hope I made it clear enough what the intent is,
would be great if there was a solution

all the best,
Simon

**Comment by Jermolene** [comment]
Hi @BurningTreeC Quine has the same requirement, perhaps @cjhunt can advise on the details. I'm pretty sure that Quine just injects some JS that responds to messages from the app and delves into `$tw` to interact with TiddlyWiki, and thus there's no extra tiddlers/plugins that are visible to the user.

**Comment by BurningTreeC** [comment]
Thanks for the response @Jermolene ,

at the moment I'm doing it by invoking an action-string when the page is loaded, using a list widget to test if a plugin is missing and installing it by calling tm-load-plugin-from-library in that case

I'll have a look at how @cjhunt does all his things, thanks for the hint, again :smile:
