### ISSUE TITLE
comments plugin - incorrect palette support

### ISSUE THREAD

**Issue by j-xella** [Jermolene/TiddlyWiki5#3701]
It looks like the comments plugin does not use background colour from palette.

This is probably done to make comments stand out. However it produces issues with dark palettes, for example "contrast dark" or "spartan night" from https://github.com/jdjdjdjdjdjd/TW5-JD-Palettes . Those palettes use light font on dark background. However, since the background of comments always remains light, the comments become unreadable when using such palettes.

The quickest solution would probably be to use fixed font colour as well in comments. However, then comments would look very much out of place with dark palettes. I wonder if a better approach could be used, for example:

- reworking the design of comments so that it is independent of colours
- dynamic background of comments, calculated as an offset from the standard background
- new palette parameter for comment backgrounds ?

**Comment by pmario** [comment]
@j-xella, @jdjdjdjdjdjd -- IMO this issue belongs to JDs repository. We cannot change it from the TW repo
 
@Jermolene ... IMO should be closed, since we cannot fix it

**Comment by Jermolene** [comment]
Hi @j-xella as you point out, the comment plugin currently uses hardcoded colours which is problematic when switching palettes. I'll push a fix shortly.

**Comment by Jermolene** [comment]
Apologies I'd only just noticed the age of this issue. Fix coming up anyway.

**Comment by Jermolene** [comment]
Fixed in 1be8f0a9336952d4745d2bd4f2327e353580a272
