### ISSUE TITLE
Improve command line logging

### ISSUE THREAD

**Issue by Jermolene** [Jermolene/TiddlyWiki5#3703]
It is proposed to make the following improvements to the way that TW5 logs messages to the command line:

* Include a datestamp at the start of each log line
* Include a the process ID within logs from the server component
* Merge the server component messages `Serving on http://127.0.0.1:8080` and `(press ctrl-C to exit)` into a single line

```
2019-01-17T15:08:27.299Z [server:1323-451961067283] Serving on http://127.0.0.1:8080 (press ctrl-C to exit) 
2019-01-17T15:08:28.323Z [syncer-server-filesystem] Dispatching 'save' task: $:/StoryList 
2019-01-17T15:08:28.369Z [filesystem] Saved file /TiddlyWiki5/editions/tw5.com/tiddlers/$__StoryList.tid 
```

The motivation for some of these changes is to make easier to debug when TW5 is running within a proxy web server (e.g. Apache or Internet Information Services).

I'm open to suggestion for other improvements.

**Comment by Jermolene** [comment]
Hi @the-kenny that's an interesting idea. We could provide a new console object in the `$tw.modules.execute()` method ([see here](https://github.com/Jermolene/TiddlyWiki5/blob/master/boot/boot.js#L646)), but the thing we'd lose compared to the current approach is the colour coding we apply on a per-logger basis.

**Comment by the-kenny** [comment]
@Jermolene I'm not too familiar with the code - aren't we able to inject a different `console` object into each module (via the `sandbox` object) to auto-prefix every log statement?

**Comment by AnthonyMuscio** [comment]
Could we provide the ability to send items to the log from an entry in the Wiki (non javascript) as I think bob allows? Even provide a verbose mode?
