### ISSUE TITLE
Different action-listops behaviors for draggable vs. droppable widgets

### ISSUE THREAD

**Issue by theSherwood** [Jermolene/TiddlyWiki5#3706]
Hi Everyone,

Draggable and droppable widgets perform the following action-listops differently:

`\define startactions()
<$action-listops $tiddler="List 1" $subfilter="-[<actionTiddler>]"/>
\end

<$list filter="[list[List 1]]">
<$draggable tiddler=<<currentTiddler>> startactions=<<startactions>>>
<$text text=<<currentTiddler>>/>
</$draggable>
</$list>`

In a list like the following:
`TiddlerOne [[TiddlerTwo]] [[Tiddler Three]]`
The draggable widget will remove the first two items from the list on drag, but not the third item. The droppable widget manages with any of the three title formats.  Seems like the action ought to be agnostic as to which widget invokes it.

Best wishes,
Adam

**Comment by admls** [comment]
I think I may have spotted where the issue may be arising.

This is how the actions are invoked by the droppable widget:
`this.invokeActionString(this.droppableActions,this,event,{actionTiddler: title, modifier: modifierKey})`
In contrast, the draggable widget calls $:/core/modules/utils/dom/dragndrop.js which invokes startActions like this:
`options.widget.invokeActionString(startActions,options.widget,event,{actionTiddler: titleString});`
The titleString variable is:
`var titleString = $tw.utils.stringifyList(titles);`
So the droppable widget is passing one title and the draggable widget is passing a list of titles. 

In the course of making that list, $tw.utils.stringifyList (in $:/boot/boot.js), does this:
`if(entry.indexOf(" ") !== -1) {
	result.push("[[" + entry + "]]");
} else {
	result.push(entry);
}`
So if there is whitespace, as in the case of [[Tiddler Three]], it gets an extra set of brackets in the draggable widget versus the droppable widget. 

Any ideas on this?

**Comment by Jermolene** [comment]
Hi @admls there are some inconsistencies here, and the documentation isn't as clear as it could be.

The situation is that the droppable widget invokes its action string once for each title that is dropped. That's why the "actionTiddler" variable can contain a single title, and doesn't need quoting. Meanwhile, the draggable widget invokes its action string(s) just once for all the title that are dragged, which is why it has to pass the titles as a quoted list.

Ideally, we'd have used a different variable name in each case but fixing that in a backwards compatible manner would add complexity. I'll make some documentation tweaks in the meantime to make things clearer.

**Comment by pmario** [comment]
@admls ... your code example in the OP is not readable, since github eats some chars. ... So please use a code block like this: 

```
    ```
    your code goes here
    ```
```

**Comment by admls** [comment]
Hi @Jermolene. I found an easy workaround for it. Just wikifying the <<actionTiddler>> and passing that to $action-listops does the trick. But it took me a while to figure out that was necessary.

Hi @pmario. Thanks for pointing that out. I'm pretty new to github. Still trying to figure things out over here!

```
\define startactions()
<$action-listops $tiddler="List 1" $subfilter="-[actionTiddler]"/>
\end

<$list filter="[list[List 1]]">
<$draggable tiddler=<> startactions=<<startactions>>>
<$text text=<<currentTiddler>>/>
</$draggable>
</$list>
```

**Comment by saqimtiaz** [comment]
A better solution than wikify is to `enlist[]` or the new `enlist-input[]` operator, both of which are designed precisely for working with title lists.

The documentation has been updated to clarify this exact issue since, and this can be closed @theSherwood @Jermolene
