### ISSUE TITLE
Documentation Macros improvement: Documentation Macros.tid

### ISSUE THREAD

**Issue by 00SS** [Jermolene/TiddlyWiki5#3711]
I would like to propose a restructure of the **Documentation Macros** tiddler and the addition of a few new macros. Two corresponding tiddlers will  also have to be modified.

- $:/editions/tw5.com/doc-macros
- $:/editions/tw5.com/doc-styles

The reason for the restructure is that it was difficult to add new examples, and the possibility that some macros are not listed increases. It also makes usage clear.

The reason for the new macro additions are for the beginner style Introduction set of tiddlers I am working on.

A preview of these 3 files can be seen here - placed in a v5.1.19 download from tiddlywiki.com: https://00ss.github.io/documentation/tiddlywiki.html

Main changes:

1. Total restructure of Display so as to show actual proper example usage - this is done using macros & lists.
2. Addition of 5 `.placeholder-...` macros
3. Addition of `.button-only` macro
4. All missing buttons added using `$list`
5. Display Macros added to the bottom - help needed for descriptions of these (TO DO)
6. Small fixes in formatting in the definitions of newer macros added recently - changed from WikiText to html

Comments would be welcome before I submit a Pull Request

**Comment by 00SS** [comment]
It would be helpful to know if the way changes have been made would be in line with future documentation developments.

If not, then I should look for another way this can be done.

**Comment by Jermolene** [comment]
Hi @00SS apologies for the delayed response. These look good, please do go ahead and submit a PR.

(By the way I really appreciate your careful approach to these changes).
