### ISSUE TITLE
ViewWidget doesn´t accept missing tid argument

### ISSUE THREAD

**Issue by twMat** [Jermolene/TiddlyWiki5#3714]
Docs on ViewWidget reads

|Attribute | Description|
|tiddler | The title of the tiddler (defaults to the current tiddler)|

I would therefore expect `<$view/>` and `<$view></$view>`, i.e no arguments at all, to show the title of the current tiddler. Instead they show as unparsed tag strings.

**Comment by Jermolene** [comment]
Hi @twMat if you put `<$view></$view>` in a tiddler then the view widget will default to showing the text field of the current tiddler, which is that text `<$view></$view>`.

**Comment by twMat** [comment]
Doh! Embarrassment...

**Comment by 00SS** [comment]
@twMat try this!
`<$view></$view> ha`
