### ISSUE TITLE
`@@` formatter should create a wrapper element

### ISSUE THREAD

**Issue by Jermolene** [Jermolene/TiddlyWiki5#372]
The block mode `@@` parser ($:/core/modules/parsers/wikiparser/rules/styleblock.js) currently tries to apply the specified classes and styles to each of the contained blocks in turn. This leads to inconsistent behaviour when the contained blocks ignore attributes and classes.

The proposed solution is to create a wrapper DIV element to take the classes and attributes.

**Comment by ght** [comment]
Looking back >6 years later, is this still desirable? If so, I'll give it a try over the next days, but I suspect that it might break backwards compat, since stylesheets that work with the current way `@@` works might break with a wrapper element.

**Comment by Jermolene** [comment]
Hi @ght I think it is no longer worth considering this change. As it's turned out the underlying issue is rarely reported, so I think it may not be hitting people in practice.
