### ISSUE TITLE
DOC elaboration needed: Using Stylesheets.tid

### ISSUE THREAD

**Issue by 00SS** [Jermolene/TiddlyWiki5#3726]
**Ref**: tiddler : [Using Stylesheets.tid](https://github.com/Jermolene/TiddlyWiki5/blob/tiddlywiki-com/editions/tw5.com/tiddlers/howtos/Using%20Stylesheets.tid)

**Discussion**: on Google Group TiddlyWikiDocs 2019-01-23: [Using Stylesheets](https://groups.google.com/forum/?hl=en#!topic/tiddlywikidocs/zJlNjjlyMys)

**Action**: Someone please take it upon themselves to do this simple write up!

Tiddler on Style Sheets should include information on the following:

Control Panel > Info > Advanced  > Stylesheets
Shows the order of StyleSheets, and using the tag pill therein you can drag and drop the order to reorder them. 

CSS by definition is Cascading if you can't see what the cascade order is, you can easily be tricked

Unless we were to provide details of all the class names already applied to all TiddlyWikis elements we should provide information that allows people to identify those elements such as via _inspect_. And suggest how these can be over ridden. We do not need to teach css only say how TiddlyWiki deals with it, and a few high level pointers.

Also correct typo : **w3scools** : to : w3schools

**Comment by 00SS** [comment]
The stylesheets in Control Panel > Info > Advanced > Stylesheets can be reordered by drag & drop.

What is the priority of the Cascading order. Does the top or bottom stylesheet in the list get highest priority?

**Comment by 00SS** [comment]
Changes include using a `<<.tag $:/tags/Stylesheet>>` which breaks the <<.tag>> macro so waiting till it is fixed in an update to $:/editions/tw5.com/doc-macros. This will be done when I put in a Pull Request based on #3711

**Comment by pmario** [comment]
>What is the priority of the Cascading order. Does the top or bottom stylesheet in the list get highest priority?

yes

**Comment by pmario** [comment]
`<<tag $:/tags/Stylesheet>>`

Don't use the docs macro. Use the TW core! Which works as expected!!
