### ISSUE TITLE
Cosmetic Bug Tag and Tiddler Managers captions missing

### ISSUE THREAD

**Issue by AnthonyMuscio** [Jermolene/TiddlyWiki5#3727]
The following tiddlers opened from the Tools tab have captions with a tiddler transcluded which do not seem to exist. I would have through the Captions would be Tiddler Manager and Tag Manager Respectively.

$:/Manager
$:/TagManager

Regards
Tony

**Comment by Jermolene** [comment]
Thanks @AnthonyMuscio I can see the extraneous caption field on the `$:/TagManager` tiddler, but I don't see it on `$:/Manager`. Fix upcoming.
