### ISSUE TITLE
haschanged  operator: Missing example

### ISSUE THREAD

**Issue by kookma** [Jermolene/TiddlyWiki5#3736]
Look at 
https://tiddlywiki.com/#haschanged%20Operator

The Example link does not work.

**Comment by 00SS** [comment]
Ref: [Google Groups Discussion](https://groups.google.com/forum/?hl=en#!topic/tiddlywiki/GqB0apuMhiE)

The explanation on tiddlywiki.com of the **haschanged** operator is:

> **purpose**    filter the input by tiddler modification status
> 
> A tiddler is deemed to have been modified if it has been written back to the wiki since the start of the current TiddlyWiki session. If you edit a tiddler and immediately store it again without making any changes, that is enough to mark it as modified.
> 

If you manually save your TiddlyWiki, I believe this may be a reset to the state of a new TiddlyWiki session? If that is correct, perhaps we can mention it in the [haschanged](https://github.com/Jermolene/TiddlyWiki5/blob/tiddlywiki-com/editions/tw5.com/tiddlers/filters/haschanged.tid) documentation tiddler.

**Comment by kookma** [comment]
Should I close this?
