### ISSUE TITLE
Feature Request: Triple-click to edit

### ISSUE THREAD

**Issue by diego898** [Jermolene/TiddlyWiki5#3743]
Danielo Rodriguez has a nice plugin enabling double-click-to-edit a tiddler:

https://danielorodriguez.com/TW5-2click2edit/

I edited that plugin so its triple-click-to-edit. This is frequently very useful for me, in longer tiddlers for example. I think its worth incorporating this a core feature, with a toggle to enable/disable in settings.

**Comment by pmario** [comment]
The problem with those "click 2 edit" function is, that 2 clicks and 3 clicks are valid text-selection functions in browsers. So 2 clicks selects a wrod. 3 clicks selects a paragraph. ... 

For "visitors" it would be very strange behaviour if the editor opens, but they just wanted to select some text. .. That's the reason, why this function was removed from TW5

**Comment by pmario** [comment]
So it would be a 4 click to edit, which would be something unique. ..

**Comment by pmario** [comment]
or CTRL-double-click

**Comment by Jermolene** [comment]
Hi @diego898 the other issue with double-click-to-edit is that it doesn't work on mobile devices. I don't think it qualifies as universal enough to warrant inclusion in the core.
