### ISSUE TITLE
State tiddlers for open tabs should not persist after refresh

### ISSUE THREAD

**Issue by giffmex** [Jermolene/TiddlyWiki5#375]
Hi all

I open the TiddlerInfo tabs quite a bit in one particular TW. But tiddlers like 

$:/state/tab-{-724328382} 

are accumulating every time I open a TiddlerInfo tab, and when I refresh the browser or close and reopen the file, they are still there. Is there a way to kill them upon refreshing or closing?

**Comment by pmario** [comment]
I think everyone got used to the existing behavior. So this issue may be closed or tagged "wontfix"

**Comment by giffmex** [comment]
Thanks Mario, I also bookmarked your Remove States tool.

**Comment by nilslindemann** [comment]
Thanks, @pmario. I came here to see if I could safely delete the 2500 state tiddlers (1700 of them `S:/state/TOC/...`) that my wiki had silently generated. Lesson learned, having each tiddler automatically generate a TOC at its end is not without its problems. But interesting that the wiki still loads without delay with so many tiddlers. Anyway, I created your clean-up tiddler right away. For those who are reading along, you can also do this manually with @kookma´s [TW-Commander](https://github.com/kookma/TW-Commander).
