### ISSUE TITLE
Feature Request: Add Edit-CompText to Core (title dropdown while typing)

### ISSUE THREAD

**Issue by diego898** [Jermolene/TiddlyWiki5#3764]
Snowgoon has this wonderful plugin:

https://snowgoon88.github.io/TW5-extendedit/

that I think should be an official part of the core. What do others think?

**Comment by twMat** [comment]
Generalizing the concept a bit; Yes, to be able to trigger *custom popups* via *custom strings* would be so useful that it deserves place in standard distro. Both newbies and experts should benefit from having custom triggers like `[[`, `<$`, etc show pickable options like

* tiddler titles
* widgets/macros - much needed (e.g `<$` triggers picklist of available widget with parameters) 
* transclusion popups - to show arbitrary tiddler (... e.g string `wikipedia:foo` shows a tid with an iframed wikipedia for entry "foo". Or `scrap` transcluding transcludes your clippings tid)

**Comment by diego898** [comment]
Hey @twMat, just to make sure I understand, you mean something like this?

https://snowgoon88.github.io/TW5-extendedit/#%24%3A%2Fplugins%2Fsnowgoon88%2Fedit-comptext%2Fusage

If I understand you correctly then I 100% agree!

**Comment by twMat** [comment]
I don't believe the popups are *customizable* in that plugin but I may be wrong. Combining *custom triggers* AND *custom popups* would be super powerful because it gives you immediate access to "anything" as you author. (I'm reminded of [Scribblenauts](https://www.youtube.com/watch?v=utOOckuag-U) - a game where you solve problems by conjuring up any object by merely typing it... e.g type "jetpack" and you get a jetpack).

**Comment by diego898** [comment]
I think you're right @twMat. Do you think its worth A. trying to get this plugin into the core as a first step? or B. close this issue, open a new one to specifically flesh out your great idea?

**Comment by twMat** [comment]
>Do you think its worth A. trying to get this plugin into the core as a first step? or B. close this issue, open a new one to specifically flesh out your great idea?

Yes a new issue makes more sense, giving Snowgoons thing only as a reference/example. The wider concept really could give power and control *during* note taking that we don't have today. I'll outline some stuff if you create a new issue.

**Comment by diego898** [comment]
This feature is closed in favor of #3784
