### ISSUE TITLE
Thanks for TiddlyWiki

### ISSUE THREAD

**Issue by tobiasd** [Jermolene/TiddlyWiki5#3766]
When I was outlining my blog posting for this years [I love Free Software](https://fsfe.org/campaigns/ilovefs/index.html) day I realised that I once again was using a TiddlyWiki to do so and how much I enjoy working with it.

Thanks a lot everybody for all the work and love you are putting into this project <3

**Comment by Jermolene** [comment]
Thanks @tobiasd much appreciated! I hadn't heard of "I love free software day" but it's a cool idea.

**Comment by saqimtiaz** [comment]
Lovely sentiment.

@Jermolene perhaps we could close this issue now?
