### ISSUE TITLE
BUG: Odd behaviour from <a href=> 

### ISSUE THREAD

**Issue by 00SS** [Jermolene/TiddlyWiki5#3777]
It looks like a double slash in the `<a>  //  </a>` tag (the display name part) breaks the link.

Make a tiddler with the 
field: `url`
value:`https://www.google.com/ncr`

Put this code in the tiddler:
```
1. <a href={{!!url}}>Link</a> -- Normal: <a href="https://www.google.com/ncr">Link</a>

2. <a href={{!!url}}>https://www.google.com/</a> -- Normal: <a href="https://www.google.com/ncr">https://www.google.com/</a>

3. <a href={{!!url}}>https:/www.google.com/</a> -- Normal: <a href="https://www.google.com/ncr">https:/www.google.com/</a>

4. <a href={{!!url}}>https//www.google.com/</a>

5. Normal: <a href="https://www.google.com/ncr">https//www.google.com/</a>
```

Run the cursor over each link and note the result.

Note: Issue noticed while tweaking the link in #3773

**Comment by Jermolene** [comment]
Hi @00SS I'm on a touch device at the moment, and so can't hover over links, can you clarify which example doesn't function as expected?

**Comment by 00SS** [comment]
It's a little difficult to explain but I'll try.

Also my examples 4. & 5. were wrongly copied*s. The correct ones to try are:

```
4. <a href={{!!url}}>https//www.google.com/</a>

5. Normal: <a href="https://www.google.com/ncr">https//www.google.com/</a>
```
The test has been done on `https://tiddywiki.com/`

1. They both display & link as expected to links to :  `https://www.google.com/ncr`
2. They both display as expected BUT link to: `https://www.google.com/`
3. They both display as expected BUT link to: `https://tiddlywiki.com/www.google.com/`
4. This LINKS properly but displays: `httpswww.google.com/</a> `
and it doesn't stop linking to anything that comes after it.

**Comment by Jermolene** [comment]
Hi @00SS I'm not sure I'm following precisely, but I think the problem might be with constructions like `https//www.google.com`: it is not recognised as a URL and so instead the double slash is interpreted as the wikitext shortcut for italics.

**Comment by 00SS** [comment]
Yes, that is what appears to be happening on No. 4 & 5.
The link looks like this (without the missing space): [https]() _www.google.com/</a>_

Examples 2 & 3 link to the wrong URL without become italic.

**Comment by 00SS** [comment]
I updated the previous comment but you may not see it by email notification so:

Yes, that is what appears to be happening on No. 4 & 5.
The link looks like this (without the missing spaces): [https]() _www.google.com/ [< /a>]()_

**Comment by Jermolene** [comment]
Hi @00SS is there a problem here beyond the observations that invalid URLs won't get recognised as URLs, and that the double slash shorticut is used to delimit italic text?

**Comment by 00SS** [comment]
The URLs are all valid. All the URLs are `https://www.google.com/ncr`

It is the text that displays that is breaking 
 - either what is seen
 - or breaking the underlying valid URL. 

Example 3. does not even have a double `//` and it is not giving the right URL.

It seems that in the display text some letter following `http:` or `https:` also causes problems, example: `<a href="https://www.google.com/ncr">http::X</a>` gives the underlying URL of `https://tiddlywiki.com/http::X`

There are too many different ways it is not working to explain them all.

**I tested all the examples in a normal HTML file and they work as expected.**

**Comment by 00SS** [comment]
I tested it in a v5.1.14 TiddlyWiki and it is the same. So it is not a new issue. I guess it was not noticed before as it is unusual to make a link name starting with `http://` which is what I was trying.

**Comment by 00SS** [comment]
And as another note to have while examining the issue - the following link also breaks into two separate links - the first part becomes CamelCase and the second links to the wrong place:
`<a href="https://www.google.com/ncr">HelloThere http://x</a>`

**Comment by Jermolene** [comment]
Hi @00SS 

> `<a href="https://www.google.com/ncr">HelloThere http://x</a>`

This example is fairly simple: "HelloThere" is camelcase and so is turned into a link to HelloThere, while "http://x" is a valid URL and so is turned into a link.

**Comment by 00SS** [comment]
I guess then `CamelCase` & `http://` being turned into a link may better be left alone. I will try and make some documentation for how to handle these fringe cases based on the [Google Groups solution](https://groups.google.com/forum/?hl=en#!topic/tiddlywiki/xkwdp5Ochqw).

However links like this one below should not be breaking. 
`<a href="https://www.google.com/ncr">http::/x</a>`
If put in a tiddler on: https://tiddlywiki.com/prerelease/
It links to: 
`https://tiddlywiki.com/prerelease/http::/x` instead of `https://www.google.com/ncr`

**Comment by 00SS** [comment]
`<a href="https://www.google.com/ncr">http::/x</a>`  gives the wrong link.
Tested in preprelease 5.1.20

**Comment by 00SS** [comment]
I thought the odd **http** string might be being interpreted as a **syslink**, but it does not look like that. I think their is some logical mix up in the **extlink** creator. Maybe this will help explain it better:

```
\define tester()
\rules except syslink 
http:/x

$:/_tw5.com-styles
\end

\define tester2()
\rules except extlink 
http:/x

$:/_tw5.com-styles
\end

Before \rules 

http:/x

$:/_tw5.com-styles
<hr>
After \rules except syslink 

<<tester>>
<hr>
After \rules except extlink 

<<tester2>>
```
