### ISSUE TITLE
Special field handling

### ISSUE THREAD

**Issue by AnthonyMuscio** [Jermolene/TiddlyWiki5#3779]
Folks,

The Transclusions
```
{{!!modified}}
{{!!created}}
```

Return formatted dates, taking into account UTC and the time zone. This is not standard transclusion behaviour.

Can we please document the method used so designers could do the same for other fields, especially date fields. How to defeat this and return the real value would also be helpful.

This could be simply a matter of documentation or perhaps we need to open this up with a hack ability improvement.

Any tips here, so I can craft a better request would be helpful, thanks Tony

**Comment by AnthonyMuscio** [comment]
[Relevant Discussion ](https://groups.google.com/forum/#!topic/tiddlywiki/fbszxrvatvA)

**Comment by Jermolene** [comment]
Hi @AnthonyMuscio I'm on mobile and so can't easily find the past discussions on this.

The boot kernel establishes some special behaviour for a handful of fields: modified, created, list, tags and color. For the first four, we customise how the field is converted between the serialised external format and the internal (JS) format. For the colour field we customise how the edit widget renders the field so that it is displayed as a colour picker.

This behaviour was carried over from TWC but long ago we realised that it was causing more harm than good. It's too late to change now.

**Comment by AnthonyMuscio** [comment]
Ok, I get your point, Knowing how it is currently done is not of much value.

However It sounds like it may be causing a barrier to better field handling.

Then may a Propose a path, for users to achieve something similar?
_I apologise in advance for the length of this reply, deal with it in your own time. It is based on lots of prior design and analysis._

I have done a lot of work on the concept of a **field definition tiddler.**  I am proposing a methodology with peer review and necessarily a plugin to start, however I may need some help and I certainly would need your conditional approval, as we need to set a few standards. All of which are backward compatible because this is an add-on to current functionality only.

Such a **field definition tiddler** can specify the following for each custom field;

- How to display the value in the field
-- eg date format, text, wikified
- How to edit the value
- - eg Date stamp, date picker, direct edit
- - Colour picker
- - Number
- - Text area or line
- - image picker
- - ability to reorder titles within the field (Like list)
- - ability to add and remove titles from a single field (Like list)
- Details if field is displayed in a list/table
- - Column heading
- - Cell in table format View
- - Cell in table format Edit
- - Column Footer
- - Sort order toggle or single order
- - Possibly provide filter options
- A method to create and reorder a column list (ie "field definition tiddlers" and above column fields) for use in tables
- - The Row list is defined by filters as it stands, columns could also use lists or filters on field definition tiddlers, or just all fields tagging the column list tiddler.

We should also design this to operate appropriately so we can edit the fields in what appears to be the current tiddler even although it is not, much of this can also be presented in the Edit View Field, edit lines, including a link to the field definition tiddler. eg $:/fields/fieldname. This is possible, it is just its too complex for even the best to do, its not easy. When by comparison creating a Field in a word Document or spreadsheet is relatively easy.

Users will be give some help creating a Field definition tiddler and some usable tiddler fieldnames and default values however they will need to reference the field definition tiddler and fields within it to build solutions that reference such fields in their tiddlers, lists and forms.

At most some habitability options, in the core would help achieve this, but will not be necessary, only desirable.

yours Sincerely
Tony

**Comment by pmario** [comment]
Just some notes: 

I'd like to have a DatePicker. The problem is browser support: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/date#Browser_compatibility

**Comment by pmario** [comment]
@AnthonyMuscio 

 - the modules, that are responsible for special field handling are here: 
https://github.com/Jermolene/TiddlyWiki5/blob/810033bd71abfad14c7d92f340ce26c33eab4ce8/boot/boot.js#L983
    - Problem: hardcoded here! Would need to be more modular.
    - elements needed seem to be: `name`, `parse()`, `stringify()` and optional parameters, depending on type.
 - field handling is initialized as `$tw.Tiddler.fieldModules very early in the startup process.: https://github.com/Jermolene/TiddlyWiki5/blob/810033bd71abfad14c7d92f340ce26c33eab4ce8/core/modules/startup/load-modules.js#L27
 - .... may be more

**Comment by AnthonyMuscio** [comment]
Thanks for the details Mario,

I think I will abandon trying to use the existing mechanism in favour of a new one, unless it could be opened to user hackability.

> I'd like to have a DatePicker. The problem is browser support: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/date#Browser_compatibility

I am using the datepicker plugin from https://github.com/kixam/TW5-datepicker

I have not tested it on various browsers except FF and Chrome. It is easy to incorporate it in my field definition tiddlers. And select while in the View template.

Regards
Tony

**Comment by pmario** [comment]
>I am using the datepicker plugin from https://github.com/kixam/TW5-datepicker

Way too much overhead for me!

**Comment by pmario** [comment]
As Jeremy pointed out, 

>This behaviour was carried over from TWC but long ago we realised that it was causing more harm than good. It's too late to change now.

"Internal", "hardcoded" magic always causes problems, because the elements affected are limited. 
Users need generic ways to solve some problems, with their own custom fields. ...

So I think your approach with some configuration tiddlers is the right one.

**Comment by 00SS** [comment]
This comment is probably useless, but I will make it anyway.

Just like we can change some normal behaviour by setting a `core variable` to `yes` or `no`, such as:
```
<$set name="tv-wikilinks" value="no">
HelloThere,
[[HelloThere]],
<$link to="HelloThere">is //this// a link?</$link>
</$set>
```
What if there was a `tv-utc-date` variable, so that:
```
<$set name="tv-utc-date" value="no">
{{!!modified}}
{{!!created}}
</$set>
```
Would give Tony's required result?

**Comment by pmario** [comment]
>This comment is probably useless, but I will make it anyway. ...

No "on-topic" comments are useless. ... How should we know, what you think? thx!

**Comment by AnthonyMuscio** [comment]
> 
> 
> > I am using the datepicker plugin from https://github.com/kixam/TW5-datepicker
> 
> Way too much overhead for me!

A Widget equivalent of

`<input type="date" name="bday" max="1979-12-31">`

Good enough for me? to set fieldname, text reference or variable.

**Comment by AnthonyMuscio** [comment]
Closing and will open a more targeted issue
