### ISSUE TITLE
Additional String operator or split on <cr><lf> or <lf> and Quine

### ISSUE THREAD

**Issue by AnthonyMuscio** [Jermolene/TiddlyWiki5#3782]
The New split operator allows us to split values based on a string

`[<currentTiddler>split[.]]`

Could there possible be a way to use a "/n" in the split to split lines?

eg 
`[{tiddlername!!text}split[/n]]`

That would return each line found in a text field """first line here"""

This would allow us to insert, remove, append, pre-pend and delete lines in a text field as well as processing each line. Although in most cases this would be to a temp tiddler or variable first.

This would open up an additional Quine type feature. Writing code that writes code.

Regards
Tony

**Comment by Jermolene** [comment]
Hi @AnthonyMuscio good idea. The way to approach this might be a variant of the split operator that accepts a regular expression as its operand: `[split:regexp[\r?\n]]`

**Comment by AnthonyMuscio** [comment]
Ok, Perhaps, but to be honest regex scares me, I know it shouldent, Are you saying the equivalent of `[split:regexp[\r?\n]] ` or we have to use `[split:regexp[\r?\n]]`?

Thanks in advance
Tony

**Comment by Jermolene** [comment]
@AnthonyMuscio I was suggesting that as a possible syntax.

**Comment by AnthonyMuscio** [comment]
Perhaps that is fair enough in this case, because if I am doing something as sophisticated as parsing lines I can use a regex, There will be value of indicating that this his how to parse lines in the split[] documentation so people need not learn regex to do this.

**Comment by saqimtiaz** [comment]
@Jermolene @AnthonyMuscio this was resolved with the introduction of the `splitregexp` operator in 5.1.20 and the issue can be closed.

**Comment by Jermolene** [comment]
Thanks @saqimtiaz
