### ISSUE TITLE
Useful enhancement with Maths Operators?

### ISSUE THREAD

**Issue by AnthonyMuscio** [Jermolene/TiddlyWiki5#3788]
Folks,

I just discovered the useful select="n" parameter on the setWidget when Using filters. This is a "zero-based index" into the items listed due to a filter. 

To my joy I realised I can use "count" to get the number of items in a given filter, and a listWidget and range filter to iterate the number, 

Then within that use set, the original filter and the select="n" parameter to recover the nth item title, and have N available as well.

This will be useful for paging lists such as 20 at a time, I have a item or index number generated for lists, I can include this "index" in the display, which is something asked for previously and thus opens a number of other possibilities.

**The Problem is that count is not a zero-based index, it is a one based index. Now we could just create a new variable and once the maths operators are available subtract 1, however this is another variable for a simple decrement to match a different index.**

Or is this already valid in $set `select={{{ [<item>subtract[1]] }}}` ?

**If this works**

- lets document this as the method to provide maths operators to a parameter.
- Perhaps also adding count[offset] where offset is a number like -1

**If this does not work, or to open it up further**

However this all made me think,  I was wondering if with the introduction of the Maths operators if parameters such as the $Set select parameter could not only accept actual numbers but a "maths filter" thus the set could look like this;

```
  <$list filter="[subfilter<rangesubfilter>]" variable=item>
    <$set name="myVariable" filter="[prefix[2019]]" select="[<item>subtract[1]]"> >
       <<item>> <$text text=<<myVariable>>/><br>
    </$set>
  </$list>

```

What if we allow the following?

Such that `select="[<item>subtract[1]]"` is valid and redresses the zero based index.

Theoretically any number field containing a non numeric value could be treated as a maths filter.

**Its an idea that is possibly opened up with the introduction of maths operators to allow parameters to be the result of a filter.**

Alternatively and of limited scope could we revisit get a non zerobased index for $set and other widgets? or a count[-1] operator when -1 is an offset.

Regards
Tony

**Comment by AnthonyMuscio** [comment]
Bump, I would hope this is addressed for the release of 5.1.20 and the maths operators

**Comment by pmario** [comment]
@AnthonyMuscio -- I think this one should be closed. The set-widget mainly has been superseded by the let-widget and specialised filter operands. 

So IMO everything what's requested here is much better doable using the latest filter operators. I'm pretty sure, we do not want to make the outdated set-widget even more bloated.

**Comment by AnthonyMuscio** [comment]
I will close this right away as mentioned the new functions and backtick forms of attribute values permit this. I will not document here, but may give examples in talk.tiddywiki when it arrises.
