### ISSUE TITLE
View Widget enhancement - value input?

### ISSUE THREAD

**Issue by AnthonyMuscio** [Jermolene/TiddlyWiki5#3789]
Would it be possible to provide the value of a variable and more to the view widget ?

I am not sure why this limitation exists.

Such that we can format the contents of a variable to any one of the available formats from dates to encoding. It would also provide a shorthand to the tiddler/field parameters.

Eg add a value= parameter 
```
value=<<variable>>
value={{text!!reference}}
value="$param$"
value="$(param}$"
```

Regards
Tony

**Comment by pmario** [comment]
@AnthonyMuscio please check you text. I think there are some words missing!. use backticks for TW code!

**Comment by 00SS** [comment]
I don't think anything is missing.
I believe what Tony means is the following **and similar**:

```
<$set name=X value=Y>
<$view value=<<X>> >Something else in case variable X is empty</$view>
</$set>
```
Interesting proposal! 
Imagine if [$view widget new attribute : format="wikified"](https://groups.google.com/forum/?hl=en#!topic/tiddlywikidev/x9Oqcs3RSsM) is also considered for implementation along with this!

**Comment by AnthonyMuscio** [comment]
Examples
<$set name=mydate value="201909031200">
<$set name=mydate2 filter="[!is[system]get[created]!sort[created]limit[1]]"> Not valid but gives the idea
<$wikify name=link1 text="https://{{!!urlfield}}/index.html"
<$view value=<<mydate>> format="relativedate"/>
<$view value=<<mydate>> format="date" template="DDD"/>
<$view value=<<mydate2>> format="relativedate"/>
<$view value=<<mydate2>> format="date" template="DDD"/>
<$view value=<<link1>> format="urlencoded"/>
etc
value={{text!!reference}} format="text"
value="$param$" format="urlencoded"
value="$(param}$" format="urlencoded"
</$set></$set>

Regards
Tony

**Comment by 00SS** [comment]
In essence, what I believe is being proposed, and what I would find useful as well, is:

The view widget displays the contents of a tiddler field **or a variable** in a specified format.

**Comment by AnthonyMuscio** [comment]
Exactly

Especialy variables

It would permit date formatting and more that can then be saved to a field.

Perhaps in future we could enhance format settings such that we could display a number as $99,000.00 such that 9 is blank if no digit or 0 if no didgit or display a string with the value substituted. 

This would complement the new maths operators.

Tony

**Comment by Jermolene** [comment]
Thanks @AnthonyMuscio @00SS that's very helpful.

Extending the view widget in the way that you suggest would actually make it an entirely different widget; the actions of displaying text versus assigning to a variable are fundamentally different.

Instead, I think the best approach is to migrate (more of) the view widget's formats into being standalone filters. For example, we could expose date formatting as `[<currentTiddler>get[modified]format:date[YYYY/MM/DD]]`.

**Comment by AnthonyMuscio** [comment]
Jeremy,

The key practical use for the view widget is to transform the format of something, and the view widget is used to set variables, or present info in a "final format". The key failure here is without being able to feed the view widget a variable, we often need a trigger, state tiddler to save a value to a field/tiddler before we can feed it into the view widget.  

An example may be constructing a URI from its parts in a macro definition (Consisting of various fields and values) and wanting to url encode it

Whilst I would welcome the format operator it does not address the need in the OT. 

I leave it to you to determine where to put this, but it is currently a "serious" gap from my view, or am I missing something?

Perhaps a <$format-variable widget? that is almost identical to the $view widget replacing tiddler and field with input=<<variableormacroname>>

Regards
Tony

**Comment by 00SS** [comment]
@Jermolene 
> 
> Extending the view widget in the way that you suggest would actually make it an entirely different widget; the actions of displaying text versus assigning to a variable are fundamentally different.

I believe you may have misread what I wrote. 
> The view widget displays the contents of a tiddler field or a **variable** in a specified format.

The idea is that the $view widget can ALSO **display** a variable, not set a variable.

**Comment by AnthonyMuscio** [comment]
Jeremy,

I am only asking that the $view widget be able to display a variable in the existing formats. Additional formats in the future perhaps.

Your belief that I miss read you stems from the fact I did not spell out that the view widget can be used in a macro or wikify widget to set a variable, not that the actual $view widget needs to handle it.

In the prior examples "value=" was only used to illustrate a parameter by which to pass the variable into the view widget, because the current method is using tiddler and field which is not relevant for passing a variable.

I hope we are now on the same page. I need to reflect on why my posts seem to be miss understood.

Tony

**Comment by Jermolene** [comment]
Hi @AnthonyMuscio you'll have spotted that (e.g.) `<$view variable="myvariable" format="htmlencoded"/>` is equivalent to `<$text text={{{ [<myvariable>htmlencode[]] }}}/>`, so for the formats of the view widget that have an equivalent filter operator, there is already a way to achieve the effect you're after.

I now judge the `<$view>` to have been a mistake; it isn't very flexible, and doesn't allow the formatting operations to be combined. I've already started the process of making the useful formats available as filter operators.

**Comment by AnthonyMuscio** [comment]
Jeremy, 

The initial reason to request this was to format dates from variable values. As a result I think if the $view widgets role in this is to diminish, your suggestion of 
`[<currentTiddler>get[modified]format:date[YYYY/MM/DD]].`
Increases in importance.

It may also be relevant to look at [S S's date Macro](https://groups.google.com/forum/?hl=en#!topic/tiddlywiki/_bbDpiiReic)  which illustrates other date format requirements that people try and use work arounds' for.

Regards
Tony

**Comment by saqimtiaz** [comment]
@AnthonyMuscio @Jermolene suggest this can be closed in light of the new format[] operator in `5.1.23` pre-release.

**Comment by Jermolene** [comment]
Thanks @saqimtiaz @AnthonyMuscio
