### ISSUE TITLE
5.1.18 regression ?

### ISSUE THREAD

**Issue by Jc-L** [Jermolene/TiddlyWiki5#3791]
The following code works as expected in 5.1.17 but broke in 5.1.18.
It uses the `$(variable)` syntax to expand a variable passed to a macro function. Expected behaviour is that when user click on A,B,C, etc. this is added to a field `jc.authors`. Multiple selections are allowed.

Since 5.1.18, the `$(match)` *text* is added to `jc.authors` field instead of the return value of the macro call.

 Tiddler content:
```
     <$list variable=match filter="A B C D E">
        <$set name=bracketedmatch value= <<addbrackets $(match)$>> > 
          <div class="tc-menu-list-item">
            <$button class="tc-btn-invisible tc-tiddlylink tc-tiddlylink-resolves">
              <$action-listops $field="jc.authors" $subfilter=<<bracketedmatch>>/>
              <<match>>
            </$button> 
          </div>
        </$set>
      </$list>
```

Macro content:
```
/*\
title: $:/plugins/jc/various/macros/addbrackets.js
type: application/javascript
module-type: macro

<<addbrackets "foo bar">>
returns
[[foo bar]]

\*/
(function(){

/*jslint node: true, browser: true */
/*global $tw: false */
"use strict";

exports.name = "addbrackets";
exports.params = [
    { name: "variable" }
];

exports.run = function(variable) {
    var variable = variable || "",
    output = '[['+variable+']]'
    return output;
};

})();
```

**Comment by 00SS** [comment]
`<$set name=bracketedmatch value= <<addbrackets $(match)$>> >`
I believe it was an inadvertent long-time bug in the $set widget that was fixed and unfortunately breaks backwards compatibility. See issue #3333 
Also read this [Google Groups post](https://groups.google.com/forum/#!msg/tiddlywiki/gmddqRgRFaI/Vz2B1KXlDwAJ).
Hope that helps.

**Comment by Jc-L** [comment]
Thanks @00SS, so there is indeed a breaking regression.

For this specific case, I replaced the js macro with a tiddler-defined macro, so that I get rid of the variable argument by relying on "tiddler global variable" instead. Doesn't feel exactly right to me, but it works.

```
\define bracketedmatch()
[[$(match)$]]
\end
```
I close this issue.
