### ISSUE TITLE
--listen path-prefix option creates Sync error messages.

### ISSUE THREAD

**Issue by tvanriper** [Jermolene/TiddlyWiki5#3795]
Environment:

* Ubuntu 16.04 Server
* node v11.10.0
* tiddlywiki 5.1.19
* Chrome 72.0.3626.109 64-bit

Steps to reproduce:

1. on server, execute: tiddlywiki wiki --init server
2. on server, execute: tiddlywiki wiki --listen path-prefix=/tiddlywiki host=0.0.0.0 port=8081
3. On browser, browse to http://(server dns):8081/tiddlywiki/

Expected result:

The default TiddlyWiki displays without errors.

Actual result:

Yellow 'syncer-browser-tiddlyweb' boxes appear reading 'Sync error while processing '$:/StoryList': XMLHttpRequest error code: 404

Notes:

Chrome's developer console indicates it tried to reach :8081/recipes/undefined/tiddlers/%24%3A%2FStoryList, among other similiarly unprefixed URLs.

Examining $:/plugins/tiddlywiki/tiddlyweb/tiddlywebadapter.js, everywhere one sees 'this.host +' you do not see a variable to indicate the path-prefix set on the command line, so perhaps that went missing?

**Comment by babastienne** [comment]
Still replicable in March 2020.

**Comment by Jermolene** [comment]
Hi @tvanriper the steps above set up the server components to use the prefix, but you also need to set up the browser components by creating a tiddler called $:/config/tiddlyweb/host containing `$protocol$//$host$/tiddlywiki/`. There are docs here:

https://tiddlywiki.com/#Using%20a%20custom%20path%20prefix%20with%20the%20client-server%20edition

**Comment by Jermolene** [comment]
I've made a small docs update to try to clarify things:

https://github.com/Jermolene/TiddlyWiki5/commit/cab9fd11dc89e0a322385009bd60cc1dbf5d42c2

**Comment by babastienne** [comment]
I tested your solution and it works perfectly. Thanks a lot for your help ! :+1:

**Comment by Jermolene** [comment]
Great, thanks @babastienne
