### ISSUE TITLE
"Not" prefix (!) not working with new is(variable) filter operator

### ISSUE THREAD

**Issue by malgam** [Jermolene/TiddlyWiki5#3804]
In this thread, Jeremy advised that he had implemented a new "variable" category for the "is" operator.  This provides a method for testing the existence of a macro or variable.  However, the "!" prefix does not seem to be working for this category.  For example, I expect the following filter transclusion:

`{{{ [[myMacro]] +[!is[variable]addsuffix[ is not defined]] }}}`

to produce "myMacro is not defined" if myMacro is non-existent and no output if has been defined.  When I test this in 5.1.20 prerelease, I get no output irrespective of whether the macro or variable exists.

The same construct works as I would expect when using "!is[tiddler]" to test for non-existence of a tiddler.

**Comment by malgam** [comment]
Sorry, "this thread" should have been a link to [this thread](https://groups.google.com/forum/#!topic/tiddlywiki/4rEuAWc4EpM).

**Comment by pmario** [comment]
I can confirm the problem. This seems to be a bug in the code. Need more investigation.

**Comment by Jermolene** [comment]
Thanks @malgam @pmario fix coming up.

**Comment by pmario** [comment]
hihi, Just wanted to create a PR - pulled the latest source - and saw the fix :) ... That was fast. thx!
