### ISSUE TITLE
drag-and-drop: making it more "direct"

### ISSUE THREAD

**Issue by BurningTreeC** [Jermolene/TiddlyWiki5#3807]
Hi @all,

I've experimented with the list-tagged-draggable macro and found a way to make it drag-n-drop directly, more the way one expects it to work, not showing the green placeholder above each item, but making it a bit more intelligent by detecting if the item should be inserted above or below the "current tiddler" ...
the visual feedback can be added to the dragover-item directly ...

what I'd like to ask is if there's a reason that those draggable core macros are currently built this way or if it's welcome to make them feel more like drag and drop "how we know it"

**Comment by BurningTreeC** [comment]
edit: top comment updated

**Comment by BurningTreeC** [comment]
the following is the logic that detects if the actionTiddler is dragged from 1) a position after the currentTiddler or 2) before the currentTiddler. it then inserts the actionTiddler before the currentTiddler in case of 1) and before the tiddler after the currentTiddler in case of 2)

this is the modified list-tagged-draggable-actions macro
```
<!-- Save the current ordering of the tiddlers with this tag -->
<$set name="order" filter="[<__tag__>tagging[]]">
<!-- Save the title of the tiddler after the currentTiddler for the case dragging is done from top to bottom / left to right -->
<$set name="nextTiddler" value={{{ [<__tag__>tagging[]] +[after<currentTiddler>] }}}>
<!-- detect the drag direction. split the current list, get all items after the actionTiddler -->
<$set name="afterActionTiddlerList" filter="[enlist<order>allafter<actionTiddler>]">
<!-- count the items after the actionTiddler, remove the currentTiddler and count again. save both values, then compare -->
<$vars afterActionTiddlerListCount={{{ [enlist<afterActionTiddlerList>] +[count[]] }}}  afterActionTiddlerListCountReduced= {{{ [enlist<afterActionTiddlerList>] -[<currentTiddler>] +[count[]] }}}>
<!-- if the count of the list-items after the actionTiddler is the same as the count of the list-items after the actionTiddler minus the currentTiddler, we're dragging from bottom to top (right to left) and insert the actionTiddler before the currentTiddler. otherwise from top to bottom (left to right) and insert the actionTiddler before the tiddler after the currentTiddler. Save the result in a insertAction variable that contains either "before" or "after" -->
<$set name="insertAction" value={{{ [<afterActionTiddlerListCount>addsuffix<afterActionTiddlerListCountReduced>removesuffix<afterActionTiddlerListCount>addsuffix[before]removeprefix<afterActionTiddlerListCount>] ~[[after]] }}}>
<!-- Remove any list-after or list-before fields from the tiddlers with this tag -->
<$list filter="[<__tag__>tagging[]]">
<$action-deletefield $field="list-before"/>
<$action-deletefield $field="list-after"/>
</$list>
<!-- Save the new order to the Tag Tiddler -->
<!-- insert actionTiddler before currentTiddler or nextTiddler, depending on insertAction variable -->
<$list filter="[<insertAction>removeprefix[before]]" variable="ignore" emptyMessage="""
<$action-listops $tiddler=<<__tag__>> $field="list" $filter="+[enlist<order>] +[insertbefore:nextTiddler<actionTiddler>]"/>
""">
<$action-listops $tiddler=<<__tag__>> $field="list" $filter="+[enlist<order>] +[insertbefore:currentTiddler<actionTiddler>]"/>
</$list>
<!-- Make sure the newly added item has the right tag -->
<!-- Removing this line makes dragging tags within the dropdown work as intended -->
<!--<$action-listops $tiddler=<<actionTiddler>> $tags=<<__tag__>>/>-->
<!-- Using the following 5 lines as replacement makes dragging titles from outside into the dropdown apply the tag -->
<$list filter="[<actionTiddler>!contains:tags<__tag__>]">
<$fieldmangler tiddler=<<actionTiddler>>>
<$action-sendmessage $message="tm-add-tag" $param=<<__tag__>>/>
</$fieldmangler>
</$list>
</$set>
</$vars>
</$set>
</$set>
```

**Comment by pmario** [comment]
I think the draggable stuff are Jeremy's first shots that worked well enough. I think, there is always room for improvement.

**Comment by pmario** [comment]
The comments are nice, but they will cost parsing time.

**Comment by pmario** [comment]
IMO a PR would be nice

**Comment by BurningTreeC** [comment]
> The comments are nice, but they will cost parsing time.

Hi @pmario, thanks for taking a look. the comments here are just to explain the mechanism, would be removed later

> IMO a PR would be nice

ok I can give it a shot

**Comment by BurningTreeC** [comment]
using this PR we could remove all "superfluous" droppables below draggable lists (open tab, tag dropdown, list-tagged-draggable, list-links-draggable ...) and we could style the item with the dragover class

I'm using this in tiddlydesktop's wikilist right now, where it works really well

**Comment by BurningTreeC** [comment]
I made a PR #3808 that adds this to the list-tagged-draggable and list-links-draggable macros. it removes the green placeholders. styles for the dragover links are missing

I like something like

```
item.tc-dragover {
transition:0.4s ease;
transform:scale(1.1);
}
```

**Comment by BurningTreeC** [comment]
now there's also the PR #3806 that fixes the placeholders in the open tab for FireFox (they often don't get removed ... whitespace issue as it appears)

...

the PR's should probably merged somehow, the open tab would also benefit from "direct" drag-n-drop, and tiddlydesktop's wikilist could, too

**Comment by Jermolene** [comment]
Hi @BurningTreeC you're talking about the green dotted placeholder rectangles that appear to mark the place where an item will be dropped? They are intended to provide positive feedback of what will happen when an item is dropped.

Can you explain or show the effect of the change so that I can see it without merging the PR? I've perhaps mentioned before that it's very useful to include a PNG or GIF for visual changes.

**Comment by BurningTreeC** [comment]
Hi @Jermolene, I'll make a gif and add it within some minutes here ...

yes I'm talking about those green placeholders and more precisely about the insertbefore behavior of the action-listops used currently, which feels right when dragging from bottom to top, but feels wrong when dragging from top to bottom.

so this would detect if we're dragging from bottom to top and insert the dragged item before the currentTiddler, like always

when dragging from top to bottom it inserts the dragged item before the tiddler after the currentTiddler

the placeholders are visually very useful and I'm thinking about a way to keep them and still giving the correct visual feedback

**Comment by Jermolene** [comment]
> so this would detect if we're dragging from bottom to top and insert the dragged item before the currentTiddler, like always. when dragging from top to bottom it inserts the dragged item before the tiddler after the currentTiddler

OK that's pretty cunning.

> the placeholders are visually very useful and I'm thinking about a way to keep them and still giving the correct visual feedback

Great stuff, let me know.

**Comment by BurningTreeC** [comment]
![peek 2019-03-01 18-38](https://user-images.githubusercontent.com/9407182/53655801-9026f300-3c51-11e9-9278-a57db640ec83.gif)

**Comment by Jermolene** [comment]
Hi @BurningTreeC I think there's a problem with highlighting an element as we hover over it: the highlight is applied to an item and yet it's not the item that is going to change as a result of the drop, the item is just going to be moved out of the way. So think there's misplaced visual feedback that isn't as clear as the current placeholder.

**Comment by BurningTreeC** [comment]
a way to keep the visual feedback could be the following:

all items can get an additional class that ends with their index in the list (for example)

when starting to drag a tiddler, we can set a state tiddler to the title of the actionTiddler and its list field to the list of the items

a stylesheet tiddler takes the items before the actionTiddler and adds something like a placeholder before them when they have the tc-dragover ... 

and to the items after the actionTiddler it adds the placeholder below

**Comment by BurningTreeC** [comment]
the placeholders could be a margin-top / margin-bottom ... or we simply add the currently used placeholder above and below and display the right one according to the above mentioned method

**Comment by BurningTreeC** [comment]
now realizing that we're not working with <$draggable> widgets most of the time here,

an idea to solve it in css:

```

list-item.tc-dragover .tc-droppable-placeholer.tc-droppable-placeholer-above {
display: block;
}

list-item.tc-dragover .tc-droppable-placeholer.tc-droppable-placeholer-below {
display: none;
}

list-item.tc-dragging ~ list-item.tc-dragover .tc-droppable-placeholer.tc-droppable-placeholer-above {
display: none;
}
list-item.tc-dragging ~ list-item.tc-dragover .tc-droppable-placeholer.tc-droppable-placeholer-below {
display: block;
}

```

**Comment by BurningTreeC** [comment]
Sorry, the last css-only idea wouldn't work.

We would need to add dragstartactions to draggable links, too and then we can show placeholders conditionally, I'm successful over here trying it. it uses a mix of the css-only idea and the index of the dragged item in a state-tiddler

**Comment by BurningTreeC** [comment]
![peek 2019-03-01 22-28](https://user-images.githubusercontent.com/9407182/53667508-7b5a5780-3c71-11e9-9214-13877418ee99.gif)

this would be possible if we add dragstartactions to draggable links, too

**Comment by Jermolene** [comment]
Hi @BurningTreeC I think that has the same issue that highlighting is applied to list entries that will not be modified by the drop.

**Comment by BurningTreeC** [comment]
![peek 2019-03-01 22-37](https://user-images.githubusercontent.com/9407182/53667934-c45edb80-3c72-11e9-81d2-0424b9067a36.gif)

**Comment by BurningTreeC** [comment]
> I think that has the same issue that highlighting is applied to list entries that will not be modified by the drop.

Hi @Jermolene , the blue highlighting is just for fun, that's not included. also those transitions / animations, these styles are in a separate stylesheet, it's not related to this

**Comment by BurningTreeC** [comment]
This is a clean version without additional styling (just the placeholder dimensions, height 7em and a top/bottom margin)

![peek 2019-03-01 22-48](https://user-images.githubusercontent.com/9407182/53668440-32f06900-3c74-11e9-9ab5-b91451ddd0da.gif)

**Comment by Jermolene** [comment]
Thanks @BurningTreeC could you kindly summarise again exactly how the behaviour has changed from the users perspective?

**Comment by BurningTreeC** [comment]
> Thanks @BurningTreeC could you kindly summarise again exactly how the behaviour has changed from the users perspective?

... that made me laugh, because there's no visible difference if looking at such a draggable list when the placeholders are visible

the difference is there, when the placeholders aren't, if a user creates a list-tagged-draggable for example and removes the placeholder styling (or doesn't add, are they always styled?) for "direct" drag and drop. then it's confusing that the dragged tiddler is always inserted before the drop-target tiddler. I'd expect it's inserted after it when dragging from the top and before it when dragging from the bottom

that's actually the only difference but in my eyes it was worth the try

**Comment by Jermolene** [comment]
Hi @BurningTreeC ah, OK. Perhaps it would be better for people to use a different macro if they didn't want the placeholder behaviour?

> it's confusing that the dragged tiddler is always inserted before the drop-target tiddler. I'd expect it's inserted after it when dragging from the top and before it when dragging from the bottom

I do also wonder if everybody would have the same expectation. The trouble with the logic here is that you've removed the mechanism that provides visual feedback for where an item will be dropped, and then are having to try to compensate by adjusting behaviour that is rather arguable...

Stepping back, I'd love to have more "canned" drag and drop functionality, so if there's a strong scenario which needs different behaviour I'd be happy to see it in the core.

**Comment by BurningTreeC** [comment]
@Jermolene , I got no real ideas at the moment but will reach back to this if at some point
