### ISSUE TITLE
\whitespace trim thoughts

### ISSUE THREAD

**Issue by BurningTreeC** [Jermolene/TiddlyWiki5#3812]
I found that in some places in the ui the `\whitespace` pragma can help solving issues

I'm thinking about other places, like the toc macros, where there's no `\whitespace trim` (yet?)

How much does a consistent use of `\whitespace trim` impact performance?

I did an experiment where the whole ui from the top PageTemplate to the tiddler bodies and to the sidebar tabs is whitespace trimmed. Somehow it feels more stable, at some points faster, but at others slower, but these are only subjective "observations".
The performance instrumentation tells me the contrary, refresh cycles take more time.

Is it possible that trimming whitespace makes the wiki `easier to eat` for the browser, but if used heavily, hits on tiddlywiki-internal performance?

**Comment by Jermolene** [comment]
Hi @BurningTreeC 

> I found that in some places in the ui the `\whitespace` pragma can help solving issues

> I'm thinking about other places, like the toc macros, where there's no `\whitespace trim` (yet?)

I'd be all in favour of that.

> How much does a consistent use of `\whitespace trim` impact performance?

I don't think very much at all. Literally all it does is trim whitespace from text widgets generated by the parser (see the code [here](https://github.com/Jermolene/TiddlyWiki5/blob/master/core/modules/parsers/wikiparser/wikiparser.js#L357)).

> I did an experiment where the whole ui from the top PageTemplate to the tiddler bodies and to the sidebar tabs is whitespace trimmed. Somehow it feels more stable, at some points faster, but at others slower, but these are only subjective "observations".

It's annoying that it's so hard to check the effects of global changes like that (see #3790!).

> The performance instrumentation tells me the contrary, refresh cycles take more time.

The performance tools need improvement!

> Is it possible that trimming whitespace makes the wiki `easier to eat` for the browser, but if used heavily, hits on tiddlywiki-internal performance?

No I'm pretty sure not.

**Comment by BurningTreeC** [comment]
thanks for answering @Jermolene !

is the `easier to eat for the browser` part true?

**Comment by BurningTreeC** [comment]
I found that when trimming whitespace this works best:

```
\whitespace trim
\define ui-part()
\whitespace trim
ui stuff, no line-breaks
transcluding with mode="block" where needed
adding <p></p> where needed
\end
<<ui-part>>
```

this really seems to work best when trying to consistently remove all unwanted whitespace

**Comment by Jermolene** [comment]
> is the easier to eat for the browser part true?

I don't think so. The output of the text widget ends up as a DOM text node, and the browser will be normalising the whitespace, but that would happen regardless of whether or not we trimmed it.

> this really seems to work best when trying to consistently remove all unwanted whitespace

I think I've noticed you use this pattern. Why do we need the ui-part macro?

**Comment by BurningTreeC** [comment]
> I think I've noticed you use this pattern. Why do we need the ui-part macro?

I believe I've noticed a difference how it gets trimmed at the very bottom

I'll try to reproduce it so I can tell you if it's just imagination or not

**Comment by pmario** [comment]
>adding <p></p> where needed

IMO there should be no paragraphs in the UI at all! From my point of view they are bugs.... in the UI

**Comment by pmario** [comment]
We should use margins instead of paragraphs to define porpper UI spacing.

**Comment by BurningTreeC** [comment]
@pmario ,

*indirect* paragraphs are used at many places for defining the UI

with indirect I mean those generated when adding an empty line between one and the next ui part

an example is the advanced search. the text `Search for system tiddlers` is surrounded by `<p></p>`, the search input below, too (in the inspector)

there are many examples like this

**Comment by pmario** [comment]
>with indirect I mean those generated when adding an empty line between one and the next ui part
>
>an example is the advanced search. the text Search for system tiddlers is surrounded by <p></p>, the search input below, too (in the inspector)
>
>there are many examples like this

Yea, and I'd say that's a wide area for improvements. .. IMO It would also make the default CSS cleaner and improve "mod-ability". 

I know the `whitespace trim` is relatively new and we didn't have the possibilities as the existing base UI was developed. ... We have to live with our past ;)
