### ISSUE TITLE
current prerelease adds <p> above story river

### ISSUE THREAD

**Issue by BurningTreeC** [Jermolene/TiddlyWiki5#3813]
you can notice more space above the story in the current prerelease

there's an additional paragraph added above, I don't know where it comes from

trimming whitespace in the topmost ui tiddlers just moves that `<p>` , the gap remains

probably something splashscreen or dynaview related?

**Comment by Jermolene** [comment]
You'll laugh at the fix for this...

**Comment by Jermolene** [comment]
Thanks by the way!
