### ISSUE TITLE
Add useful `npm run` tasks, tidy & simplify .sh and .cmd scripts (was: consider using Makefile or Grunt)

### ISSUE THREAD

**Issue by simonbaird** [Jermolene/TiddlyWiki5#383]
I don't like the clutter of having all those .sh files and .cmd files in the root directory, so I was initially going to suggest moving them all into a sub-directory.

But it occurred to me that it might be nicer to put them into a Makefile (with a bunch of .PHONY targets, one per .sh file).

Eg instead of `./qbld.sh` you might do `make qbld` or whatever.

It adds a dependency on make. I don't know how problematic that would be for windows developers, but I assume it's not too hard to get GNU make.

It might be possible to have a single Makefile that work in windows and non-windows.

If the dependency on make is not desirable, perhaps Grunt.js would work. I don't know a lot about Grunt, but it seems to be popular for node projects.

**Comment by ght** [comment]
This can probably be closed, since the build process has evolved since this discussion.
