### ISSUE TITLE
 If you have PHP problems, check your Adblocker

### ISSUE THREAD

**Issue by Kevin-Winehouse** [Jermolene/TiddlyWiki5#3831]
First of all, I have no issue. Cause last night it cost me three hours to think about it.
And I just want to record it , in case you struggle with it.
Any kind of browser u use, please make sure your server website is not blocked by Adblock or add-ons like that!!!
It truly block the PHP error, leaving the message of TW is saving fading away.

**Comment by pmario** [comment]
Hi, ... May be you can edit your title, to something similar of: **If you have PHP problems, check your Adblocker** ... Or something similar. 

Since this isn't an open issue, you may close it too. ... google search will still find it, if someone searches for "php problems" and "tiddlywiki"

**Comment by Kevin-Winehouse** [comment]
@pmario Thank you for your advice!
