### ISSUE TITLE
Titlebar "More actions" popup appears under title for next tiddler

### ISSUE THREAD

**Issue by adamse** [Jermolene/TiddlyWiki5#3855]
As seen in this screenshot:

![Screenshot 2019-03-12 at 14 47 21](https://user-images.githubusercontent.com/75746/54209652-0ccd9300-44d6-11e9-9c47-579001ec7404.png)

**Comment by BurningTreeC** [comment]
Hi @adamse , @Jermolene addressed this problem recently with a PR. It should be fixed on the current prerelease. Would you mind testing on https://tiddlywiki.com/prerelease if there this problem still exists?

**Comment by adamse** [comment]
Thank you! Yes, it seems to be fixed in the pre-release version.

Furthermore it only seems to happen when using "Sticky titles" in the default theme.
