### ISSUE TITLE
Add support for widget subclasses

### ISSUE THREAD

**Issue by Jermolene** [Jermolene/TiddlyWiki5#3865]
Following some discussion in #3863, it is proposed to add a generic mechanism to enable plugins to subclass widgets so that their behaviour can be customised.

Two forms of subclassing should be supported:

* Adding methods and properties to the prototype of an existing widget class
* Making a new widget class by extending an existing one with additional methods and properties

An example of widget subclass module:

```
/*\
title: $:/my-customised-text-widget.js
type: application/javascript
module-type: widget-subclass

Widget base class

\*/
(function(){

/*jslint node: true, browser: true */
/*global $tw: false */
"use strict";

exports.baseClass = "text"; // Extend the <$text> widget

exports.type = "extend"; // Alternatively type = "subclass", name = "<new-name>"

exports.prototype = {};

exports.prototype.render = function(_baseClass,parent,nextSibling) {
	// Call the base class render function
	_baseClass.prototype.render.call(this,parent,nextSibling);
	// Add our custom attribute
	this.domNodes[0].setAttribute("data-text","my custom attribute");
};

})();
```

**Comment by BurningTreeC** [comment]
Hi @Jermolene, I was reading about js inheritance right now and this looks comprehensible

**Comment by Jermolene** [comment]
Hi @BurningTreeC great, let me know how you get on

**Comment by BurningTreeC** [comment]
@Jermolene 

>let me know how you get on

I'll need to digest the first shock of the seemingly endless new possibilities, then I let you know!

**Comment by BurningTreeC** [comment]
Good start to the week @all ,

@Jermolene , first I'd use this to refresh codemirror's options when its config tiddlers change, #3824

then I can use this to realize "selectable-inputs" (http://selectable-inputs.tiddlyspot.com) in a much easier way

that's what I'm about to do with this but there are many possibilities

**Comment by BurningTreeC** [comment]
@Jermolene, I can also address #2449 with the same mechanism used for the above mentioned selectable-inputs. #2449 is about the editor loosing focus when the preview gets activated by alt-P.

Also closing other popups when an input gets focus is something I'd like to address with a widget-subclass
