### ISSUE TITLE
Math, how are negative numbers expressed?

### ISSUE THREAD

**Issue by twMat** [Jermolene/TiddlyWiki5#3866]
**Request**: Clarify the math op [docs](https://tiddlywiki.com/prerelease/#Mathematics%20Operators) tiddler to clarify how *negative numbers* are expressed.

The confusion: The `-` prefix is reserved for filter *removals* and surrounding with different kinds of brackets don't seem to work either. Possibly same confusion; The [docs](https://tiddlywiki.com/prerelease/#Mathematics%20Operators) explicitly states `-Infinity` but  e.g `{{{ 5 -Infinity +[sum[]] }}}` = 5

Side note: Yes, we need much more docs on Math Ops but I would rather see the Math Ops functionality without extensive docs than delay 5.1.20 to first complete the docs. People can ask on the boards which will also serve as input on how to formulate the docs. Still, I think the above matter about negative numbers is so fundamenal that it is needed as soon as possible.

**Comment by Jermolene** [comment]
Hi @twMat you need to use quotes around negative numbers. For example: `{{{  5 [[-Infinity]] +[sum[]] }}}`.

**Comment by twMat** [comment]
>Hi @twMat you need to use quotes around negative numbers. For example: {{{ 5 [[-Infinity]] +[sum[]] }}}.

Thank you.

**Comment by twMat** [comment]
Hm, in attempting to edit the doc [Mathematics Operators](https://tiddlywiki.com/prerelease/#Mathematics%20Operators) on github, I click the "edit this tiddler on github" but github gives a 404 page as if the link doesn't exist.

**Comment by Jermolene** [comment]
The link in the pink ribbon takes you to the tiddlywiki-com branch; the maths operators are in the master branch.
