### ISSUE TITLE
precision operator: can return exponential notation

### ISSUE THREAD

**Issue by BurningTreeC** [Jermolene/TiddlyWiki5#3868]
The following example returns `1.2e+3`
```
{{{ [[1234.5]precision[2]] }}}
```

even if the other math operators can handle that, users may not expect such a result

**Comment by BurningTreeC** [comment]
`parseFloat(1.2e+3)` would return 1200

**Comment by Jermolene** [comment]
Hi @BurningTreeC I think this might be a docs issue: the behaviour you've observed is that of the underlying [toPrecision() method](
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/toPrecision).

**Comment by BurningTreeC** [comment]
@Jermolene ,

>I think this might be a docs issue: the behaviour you've observed is that of the underlying toPrecision() method

yeah, I've seen that this is the behavior of `toPrecision()` but is it intended that the filter output then contains a number in exponential notation?

I see it can be "parsed" to decimals through `+[add[0]]` or such ...

Do you prefer just documenting that behavior?

**Comment by Jermolene** [comment]
Hi @BurningTreeC the purpose of the precision operator is to convert numbers into strings according to scientific notation conventions. As you note, exponential notation works when we're converting the other way from strings back into numbers.

**Comment by BurningTreeC** [comment]
I've added a tip to the precision op, thanks @Jermolene
