### ISSUE TITLE
Bug with stateTitle attribute of reveal widget

### ISSUE THREAD

**Issue by Jermolene** [Jermolene/TiddlyWiki5#3874]
Note the difference in output between these two variants of the reveal widget used with a non-existent tiddler:

```
<$reveal stateTitle="nonexistent" type="match" text="" default="">
NONE 1
</$reveal>

<$reveal state="nonexistent" type="match" text="" default="">
NONE 2
</$reveal>
```

Results:

```
NONE 2
```

**Comment by BurningTreeC** [comment]
@Jermolene, this was my mistake. I'll take more care in the future when taking hand on a working core functionality

**Comment by Jermolene** [comment]
Hi @BurningTreeC no worries! If I had a pound for every bug I've introduced into TiddlyWiki I'd be a rich man...

**Comment by BurningTreeC** [comment]
:grin: wouldn't be bad to earn something that way
