### ISSUE TITLE
Fields with non-lowercase names

### ISSUE THREAD

**Issue by 00SS** [Jermolene/TiddlyWiki5#3887]
[TiddlerFields](https://tiddlywiki.com/#TiddlerFields)
> TiddlerFields are name:value pairs that make up a tiddler. Field names must be lowercase letters, digits or the characters - (dash), _ (underscore) and . (period).

```
<$radio field="Tiddler" value="a"> Tiddler a</$radio> 
<$radio field="Tiddler" value="b"> Tiddler b</$radio> <br>
<$radio field="tiddler" value="c"> tiddler c</$radio> 
<$radio field="tiddler" value="d"> tiddler d</$radio> 

Field Tiddler: {{!!Tiddler}}

Field tiddler: {{!!tiddler}}
```

Result after selecting **Tiddler a** & **tiddler c** :

```
Field Tiddler: a
Field tiddler: c 
```

**Comment by pmario** [comment]
Follow this:

 - download empty.html
 - insert your code
 - test
 - save
 - reload ... you'll see "Tiddler" field is gone. 

That's why "fields **must** be lower-case"!

**Comment by pmario** [comment]
If you create a field named: "Test"
save 
it will be "test" after reload.

**Comment by 00SS** [comment]
Ha! Interesting!
Thanks @pmario 

After clicking on the **_Tiddler a_** and **_tiddler c_** radio buttons, saving and reloading has an interesting effect. It is the **Tiddler** field that is retained and renamed with its value **a** - and the  **tiddler** field is I guess overwritten, and its **c** value is lost.
