### ISSUE TITLE
Nested $set widgets - ODD behaviour

### ISSUE THREAD

**Issue by 00SS** [Jermolene/TiddlyWiki5#3893]
What is causing the wikitext `!! Header` to break in this scenario?

```
!! A Header
<$set name="var1" value="1">
<$set name="var2"  value="2">

Var2: <<var2>>
</$set>

Var1: <<var1>>
<p />

!! This Header Doesn't Work!
<h2> But an H2 Header does work</h2>
</$set>

!! A Third Header
```

**Comment by pmario** [comment]
try

```
!! A Header

<$set name="var1" value="1">

<$set name="var2"  value="2">

Var2: <<var2>>
</$set>

Var1: <<var1>>

!! This Header Doesn't Work!

<h2> But an H2 Header does work</h2>
</$set>

!! A Third Header
```

2 linebreaks between the first 2 set activates block-mode

**Comment by 00SS** [comment]
Wow! Very interesting. Never realized line spacing multiple `$set` widgets could affect inline and block modes! This threw me off for a while yesterday when completing the tiddler: Set Widget Tester for attribute precedence

**Comment by 00SS** [comment]
Thanks @pmario 

> Wow! Very interesting. Never realized line spacing multiple `$set` widgets could affect inline and block modes! This threw me off for a while yesterday when completing the tiddler: [Set Widget Tester for attribute precedence](https://groups.google.com/forum/#!msg/tiddlywiki/lvLfDiqNxEE/wnEaHsvhCAAJ)

**Comment by 00SS** [comment]
Now I am confused again.

Why is this code with this EXACT line spacing breaking down?

```
<$set name="x" filter="[[1 2 3]]">
<$set name="x" filter="[[4 5 6]]">

</$set></$set>
<$set name="x" filter="[<x>]">
<<x>>
</$set>
```

**Comment by 00SS** [comment]
It becomes even more apparent this way:

```
<$set name="x" filter="[[1 2 3]]">
<$set name="x" filter="[[4 5 6]]">

<<x>>
</$set></$set>
<$set name="x" filter="[<x>]">
<<x>>
</$set>
```

**Comment by Jermolene** [comment]
Hi @00SS I'm pretty sure you've found a bug -- the giveaway is that the final `<<x>>` shows the value of the first `<$set>` widget, meaning that that widget hasn't been properly terminated by the parser. I'll investigate when I'm back on my dev machine.
