### ISSUE TITLE
Google Chrome v73 breaks auto display of search results

### ISSUE THREAD

**Issue by tinyheero** [Jermolene/TiddlyWiki5#3906]
The latest version of the Google Chrome browser (v73.0.3683.103) seems to break
TiddlyWiki's auto display of search results. I had been using Google Chrome (v72.0.3626.121) up until recently.

For instance, I've attached a simply wiki that has two tiddlers (test and test2) (https://drive.google.com/open?id=1z_vFnkovnsZp9cc1ZQV1PV9k2pXlFjwf). Typing test into the search bar auto displays the results as expected using Google Chrome (v72.0.3626.121). 

![tiddywiki_on_chrome_72](https://user-images.githubusercontent.com/3268173/55937206-478b2e00-5c30-11e9-89b8-76036bfa735b.png)

But using the latest version Google Chrome browser (v73.0.3683.103) now, typing test into the search bar does not always auto display the results. 

<img width="1262" alt="tiddywiki_on_chrome_73" src="https://user-images.githubusercontent.com/3268173/55937208-4b1eb500-5c30-11e9-9bfe-dae990b03063.png">

The behaviour is a bit unpredictable as it works sometimes, but then simply stops auto displaying results. You can reset it by clicking on the down arrow to the right of the search bar.

I am using TiddlyWiki 5.1.19.

**Comment by AnthonyMuscio** [comment]
I have observed this as well

**Comment by sukima** [comment]
Seems we are  not the only ones:

* https://www.sencha.com/forum/showthread.php?471593-Focus-not-working-fine-on-latest-chrome-version-73
* https://bugs.chromium.org/p/chromium/issues/detail?id=941910
* https://bugs.chromium.org/p/chromium/issues/detail?id=947062

**Comment by pmario** [comment]
@tinyheero, @AnthonyMuscio, @sukima  -- Is this still a thing?

**Comment by AnthonyMuscio** [comment]
All I can say is its not happening now in the latest empty.html

I think if there are circumstances in which it is observed again we can raise a new issue with reproducible examples.

**Comment by pmario** [comment]
@Jermolene -- I could not reproduce it too. So IMO this one can be closed and reopened if someone can replicate it again.

**Comment by Jermolene** [comment]
Thanks @pmario
