### ISSUE TITLE
Prefix line

### ISSUE THREAD

**Issue by RunningUtes** [Jermolene/TiddlyWiki5#3912]
A tm-edit-text-operation is supposed to preform an operation on selected text but it doesn't seem to do as the documentation lists.

https://tiddlywiki.com/#WidgetMessage%3A%20tm-edit-text-operation

If selected text is bolded, the '' is added as a prefix and as a suffix. If the same text is already bolded and the operation is run again, the '' is removed. See the rules in $:/core/ui/EditorToolbar/list-bullet.

This doesn't seem to happen for the prefix-lines operation.

For example, select several lines of text and press the unordered list button. A * will be added as a prefix according to the rules in $:/core/ui/EditorToolbar/list-bullet. If the same text is selected and the unordered list button is pressed again, the * is not removed. In fact, nothing happens. The documentation states that the prefix should be removed from the selected lines.

Is this a bug in the code of the current TW?

The problem seems to be in $:/core/modules/editor/operations/text/prefix-lines.js

**Comment by AnthonyMuscio** [comment]
Perhaps with prefix items such as * # and : we should allow add level and subtract level

I know I would like to select multiple rows and simply add another level deep, then a tools to reverse this one level at a time. Perhaps once fixed the existing button can simply reset it to one level or none.

+
*  +
** +
*** +
** -
* -
-


Regards
Tony

**Comment by sukima** [comment]
# Confirmed

This is a bug. [`prefix-lines.js` L:36](https://github.com/Jermolene/TiddlyWiki5/blob/df416814b13fadd541ca30dffe3f77d24e63f8b0/core/modules/editor/operations/text/prefix-lines.js#L36) has a type error.

```js
		if(count !== event.paramObject.count) {
```

in this case `count` is a number while `event.paramObject.count` is a string and the `!==` comparison is type sensitive.

**Comment by pmario** [comment]
@sukima ... Nice catch!
