### ISSUE TITLE
Trouble with z-index of titlebars in sticky mode

### ISSUE THREAD

**Issue by ExoCode17** [Jermolene/TiddlyWiki5#3915]
I see it has already been reported, but changing the z-index to 501 doesn't fix it for me. As soon as I hover the titlebar, it overlaps the popup menu. I am using TW under node.

![2019-04-15 10_01_43-Webcomic Name — Subtitle or tagline](https://user-images.githubusercontent.com/13753044/56116271-b389d100-5f65-11e9-8d1c-31793d9811b6.png)
![2019-04-15 10_01_49-Webcomic Name — Subtitle or tagline](https://user-images.githubusercontent.com/13753044/56116274-b389d100-5f65-11e9-931d-13478f99cedc.png)

**Comment by ExoCode17** [comment]
It's on your website too.

![2019-04-15 10_04_15-TiddlyWiki — a non-linear personal web notebook](https://user-images.githubusercontent.com/13753044/56116341-dddb8e80-5f65-11e9-9d1e-19c2f4415b88.png)

**Comment by twMat** [comment]
This is solved in https://tiddlywiki.com/prerelease/ - i.e the next version that will hopefully come soon.
@ExoCode17 , please close this issue.

**Comment by ExoCode17** [comment]
Oh, I see. Can you please direct me to the change that makes it possible? I can't find it.

**Comment by twMat** [comment]
Do a simple text search for "sticky" in the prerelease notes for 5.1.20, i.e this tiddler:
https://tiddlywiki.com/prerelease/#Release%205.1.20

**Comment by ExoCode17** [comment]
Oh, awesome, thanks!

**Comment by Jermolene** [comment]
Thanks @ExoCode17 -- I guess this is a reminder that it's about time v5.1.20 was released...

**Comment by ExoCode17** [comment]
Can't wait! The new calc functions are exactly what I needed to move my business stuff on a tiddlywiki! @Jermolene when the update is released, how can I make sure that the modifications I made to the system are overwritten with the new wiki? I actually imported the four tiddlers referenced in the issue, and it's fixed for me now. But being tiddlywiki so interconnected I am sure there is other stuff related to these tiddlers too.

**Comment by Jermolene** [comment]
Hi @ExoCode17 

>  I actually imported the four tiddlers referenced in the issue, and it's fixed for me now

In general, that's not a good idea, for exactly the reasons you note: TiddlyWiki's components are so interconnected that you risk subtle malfunctions due to mismatched versions. It's better to switch fully, and use the prerelease version.

**Comment by ExoCode17** [comment]
Shoot D: How can I revert?? I don't want to switch to the prerelease as I read that I then must update the code manually.

**Comment by Jermolene** [comment]
Hi @ExoCode17 

> How can I revert??

Open the "More" tab in the sidebar, then the "System" tab. Locate, open and delete the following tiddlers:

* $:/core/ui/Buttons/more-tiddler-actions
* $:/core/macros/CSS
* $:/themes/tiddlywiki/vanilla/base
* $:/themes/tiddlywiki/vanilla/sticky

Background: when a core "shadow" tiddler is modified, the original tiddler is overridden, and can be restored by deleting the modified tiddler.

**Comment by ExoCode17** [comment]
OOOOHH, good to know!! Thank you very much!

**Comment by Jermolene** [comment]
Thanks @ExoCode17
