### ISSUE TITLE
list-tagged-draggable with title field

### ISSUE THREAD

**Issue by mikob** [Jermolene/TiddlyWiki5#3916]
I'm trying to make a generic TODO list template, it should filter by tags that are the title of list (eg. "Home TODO").
The code below doesn't work, I suppose there's something wrong with tag:"{{!!title}}" but couldn't get it to work.

```
<<list-tagged-draggable tag:"{{!!title}}" subFilter:"!has[draft.of]!tag[done]" itemTemplate:"TODOItemTemplate" emptyMessage:"You don't have any active {{!!title}} tasks.">>
```

**Comment by 00SS** [comment]
[Macro Calls in WikiText](https://tiddlywiki.com/#Macro%20Calls%20in%20WikiText)

> The syntax is actually a shorthand for a [$macrocall](https://tiddlywiki.com/#MacroCallWidget) widget. The widget itself offers greater flexibility, including the ability to **transclude** parameter values or generate them via additional macros.

`<$macrocall $name="list-tagged-draggable" tag={{!!title}} . . . />`

You may find that asking these kinds of question get faster/better answers on the [tiddlywiki Google Group](https://groups.google.com/forum/!forum/tiddlywiki)

**Comment by twMat** [comment]
>You may find that asking these kinds of question get faster/better answers on the tiddlywiki Google Group

In deed. You're more than welcome to ask questions @mikob but the TW google group is the way to go for "personal" user type issues. *Many* more helpers there. Github is for TW system issues.
Please close this thread if you agree your question has been dealt with :-)

**Comment by mikob** [comment]
Thanks for your help, sorry I will use the Google Group for questions like this next time.
