### ISSUE TITLE
[tw.com] PR: "Demo" tiddler

### ISSUE THREAD

**Issue by twMat** [Jermolene/TiddlyWiki5#3918]
IMO tiddlywiki.com is missing a "live demo" to clarify what TW is. We must not forget that TW is radically different from most webpages that people have ever seen and visitors to tw.com probably don't really grasp that they're staring at the very tool itself nor that it is immediately useable.

For this reason I've created the tiddler

http://livetest.tiddlyspot.com/#Live%20test

intended to be presented as a thumbnail in HelloThere on tiddlywiki.com. The current setup with "HelloThere" immediately followed by "GettingStarted" (containing the download button + saver options) is a bit demanding in that we expect them to download before they really know what it is. I feel a normal user would want to *try it out* before downloading anything. One may argue that the whole tw.com site is for "trying out" but the visitor might not understand this. He may not even understand that tw5.com *is* a tiddlywiki - this is far from self evident for a first timer. An explicit "try out" also engages them in a positive way, just like having a taste sample in the food store does.

The tiddler, named "Live test", is intentionally written in a more conversational tone than other doc tiddlers. A native English speaker is more than welcome to correct anything that doesn't flow linguistically.

Pedagogically, I want visitors to get *straight* into the tasks. No "philosophy", it is not really a learning moment. I also make an effort to avoid introducing too much lingo and I keep wikitext and intimidating code to a minimum because they enter edit mode.

Finally, it links to the GettingStarted/download tiddler, making for a softer "bridge" to encourage download.

I am not 100% happy with the "compact" appearence of the text so maybe some of the special tw.com styling could be applied. Not sure exactly how/where... as noted, the user must not be intimidated when in edit mode.

Thoughts? I'm asking everyone but particularly @Jermolene of course. I fully understand that the front page is a sensitive spot but I believe this concept is a softening bridge for a newcomer to actually give  TW a proper chance. If you like the text, please consider this a PR.

**Comment by AnthonyMuscio** [comment]
twMat,

- I think this is a good idea. For people looking to understand we should give them what they are likely to be looking for, even if once they understand tiddlywiki it is not so relevant. 
- It would be reasonable to note that TiddlyWiki.com allows the same live test but includes documentation. see **About this live test**
- It would also be wise to explain these variances in "about this live test" in the live test wiki see **About this live test**
- Once 5.1.20 is released with the local storage plugin I think it makes sense to activate local storage on the live test and provide a download this live test and your changes button. The caveats of local storage should also be documented. 

eg;
About this live test
This live test has being provided to help visitors jump right in to TiddlyWiki and to get an idea of how it works. This is a simplified version of tiddlywiki. You can do the same at the tiddlywiki.com website however it also contains tiddlywiki documentation and more. It is also a simple process to download your own "empty" tiddlywiki and use that locally on your computer (or a mobile solution?)

Regards
Tony

**Comment by sukima** [comment]
# Today I Learned

> **pedagogical** | ˌpedəˈɡäjək(ə)l | _adjective_
> relating to teaching: _innovative pedagogical methods._

**Comment by AnthonyMuscio** [comment]
Also I wonder if we could allow a language selection and provide multiple languages of the same tiddler.

**Comment by sukima** [comment]
@twMat I just looked at the demo. First off 👍 well done. The prose reads well and I think I would really feel engaged with it if it were my first time. Unfortunately that is no substitute for real evidence provided by new users.

Second, since this is a single tiddler I think it would work well as part of the TiddlyWiki.com site itself! You said it earlier that tw.com is a TiddlyWiki already dispite that not being abundently clear to new people.

My suggestion then would be to have a very prominent thumbnail in the [HelloThere](https://tiddlywiki.com/#HelloThere) tiddler that the [Live Test](http://livetest.tiddlyspot.com/#Live%20test) tiddler instead of a separate link. In this way live experimentation is still front and center but doesn't confuse people thinking they need to go to the live site to accomplish something. In fact this could be part of the [A Gentle Guide to TiddlyWiki](https://tiddlywiki.com/#A%20Gentle%20Guide%20to%20TiddlyWiki)

**Comment by 00SS** [comment]
I agree that this is really good!
For the Beginners series I am working on, I have partially written something similar. It's the 5th link in the table of Contents - **Make a tiddler right now, right here**

https://00ss.github.io/help/Adding-a-table-of-contents-to-the-sidebar.html#Beginners

**Comment by twMat** [comment]
>My suggestion then would be to have a very prominent thumbnail in the HelloThere tiddler [sic]

Ah, you're right @sukima ! Thumbnail in HelloThere would make sense, instead of as default tid. Perhaps snappily titled "Demo". I'm revising the OP.

That said, my proposal is also a reaction to the placement and design of GettingStarted which I do insist is too direct at that point in time (plus that whole tid is indimidating).

**Comment by AnthonyMuscio** [comment]
I believe the way tiddlywiki.com introduces new users to tiddlywiki has being discussed at length in the past. However this has not yet resulted in much change. Hello explains what it is, even promotes it a little then getting started is what you do if you are persuaded. I believe a little more persuasion is needed through tangible examples. Much has being said about introducing various editions that have practical uses here. 

Your suggestion goes part way but I think more is needed. In addition to hands on editing, An example may be some feature rich tiddlers that demonstrate what can be done with standard tiddlywiki. Some people have the imagination to extrapolate what can be done with tiddlywiki but many will not.

**Comment by 00SS** [comment]
If you are using a thumbnail on HelloThere, please do consider what was discussed in PR #3046 

My view is that this tiddler on the front page is not for regular users. It is for new visitors.

I feel there really should NOT be so many thumbnails in that tiddler. It's very confusing, hard to read, and there are too many choices. I suggest max 4 thumbnails, two on top, two below.

The following should be considered for dropping in a main front page tiddler: 
- What's new in 5.1.19
- Developers
- Helping TiddlyWiki
- TiddlyMap Plugin
- TiddlyWiki Classic

**Comment by twMat** [comment]
@00SS , exactly how to include a potential Demo thumbnail in HelloThere is beyond this OP. However, note that in #3925 Front page redesign proposal, Jermolene says he thinks it's time for a redesign of HelloThere so do please come with ideas there. I'm currently dabbling with some stuff for it.

**Comment by Jermolene** [comment]
Good stuff @twMat. I think that we might call this a "tutorial", and I agree that a properly sequenced practical tutorial would be useful for lots of users.

I wondered idly if the currently rather unused "help" panel in the prerelease might be a useful way to display the tutorial while it is being worked on?

**Comment by twMat** [comment]
> "tutorial"

Hm, the "target" for a demo is people who have not yet decided if TW is worth downloading to begin with. Everyone is at this stage at one point in time, of course, and most offers to download stuff are simply rejected. So a demo would more serve to create a "feeling" of TW rather than to actually teach them stuff. 

But I agree a tutorial is useful once someone has actually downloaded and wants to start working and I do think the help panel would be a great place for a tutorial. I'm not sure what you mean with "while it is being worked on"?

**Comment by 00SS** [comment]
I do not believe this PR was meant to be part of a "tutorial."

My understanding is that it is meant only for - brand new users - first time visitors to the website to try out the program - thus helping them to decide if they want to download and use it.

That is why it was also [one of the first tiddlers I made](https://github.com/Jermolene/TiddlyWiki5/issues/3918#issuecomment-483910089) when designing the Beginners series.

**Comment by Jermolene** [comment]
Hi @00SS @twMat I don't think it works as part of the initial evaluation process because it's too long and fiddly. If we just want to show what's possible then a video or animation would be better.

**Comment by twMat** [comment]
>a video or animation would be better

You're right, those are an even better ideas! It is even easier (lazier) for the visitor and it would give us more control on what to steer focus to. I'm closing this PR.
