### ISSUE TITLE
How to or Documentation broken for Filtered Attribute Values

### ISSUE THREAD

**Issue by AnthonyMuscio** [Jermolene/TiddlyWiki5#3920]
Folks,

As documented here https://tiddlywiki.com/#HTML%20in%20WikiText at the bottom the example is given for Filtered Attribute Values
`<$text text={{{ [<currentTiddler>]addPrefix[$:/myprefix/]] }}}>`
The above does not work even in tiddlywiki.com returning 
"Filter error: Syntax error in filter expression"

I have built a number of shortcuts using the Filtered Attribute Values and the triple curly braces. I would like to return some of the result as plain text rather than apparent links to non existent tiddlers and would hope this example worked, however if does not. 

Please advise how to do this and help me then correct the documentation.

Regards
Tony

**Comment by AnthonyMuscio** [comment]
Also I see the syntax error, an additional "]" has being removed

Corrected here
`{{{ [<currentTiddler>addPrefix[$:/myprefix/]] }}}`

However 
`<$text text={{{ [<currentTiddler>addPrefix[$:/myprefix/]] }}}>`
returns nothing

**Comment by AnthonyMuscio** [comment]
Done https://github.com/Jermolene/TiddlyWiki5/pull/3921

**Comment by 00SS** [comment]
Thanks for catching this and fixing it with a PR!
