### ISSUE TITLE
tiddlers not deleted (after page load) when using 'root-tiddler=$:/core/save/lazy-all'

### ISSUE THREAD

**Issue by mdemoss** [Jermolene/TiddlyWiki5#3928]
tiddlywiki 5.1.19
nodejs v8.16.0

I can create and delete tiddlers in a single session, but if I create a tiddler and then refresh the page or close the page and open it again later it is not possible to delete.

Looking at the browser's network log, I can see the DELETE request is made if I try to delete a tiddler immediately after creating it, but no request is made if there has been a page load in between creation and attempted deletion.

**Comment by mdemoss** [comment]
Looking in TiddlyWebAdaptor.prototype.deleteTiddler, I see that it's looking for a "bag" and not finding one when I refresh and re-open.

```js
	// If we don't have a bag it means that the tiddler hasn't been seen by the server, so we don't need to delete it
	var bag = options.tiddlerInfo.adaptorInfo.bag;
	if(!bag) {
		return callback(null);
	}
```

**Comment by maxco2** [comment]
This bug is reproducible. Same as me.

**Comment by dev4light** [comment]
+1 any news about this?

**Comment by Jermolene** [comment]
Thanks @mdemoss @maxco2 @dev4light and apologies for the delay. I've been working on a major overhaul of the syncer and I believe that this bug is now fixed. I'd be very grateful if you could try out the branch at https://github.com/Jermolene/TiddlyWiki5/pull/4373

**Comment by mdemoss** [comment]
works fine in `5.1.23`
