### ISSUE TITLE
Editor preview pane default should be: ON

### ISSUE THREAD

**Issue by 00SS** [Jermolene/TiddlyWiki5#3930]
### Present Settings
The tiddler editor does not show its preview pane by default

### Proposal
I propose that the editor preview pane is shown by default 

### Affected tiddlers

The tiddler: `$:/state/showeditpreview` starts with a default value of `no` in :
- [empty.html](https://tiddlywiki.com/empty.html)
- [tiddlywii.com](https://tiddlywiki.com/) 
- [prerelase](https://tiddlywiki.com/prerelease/)

Its value to be changed to `yes` in all 3 editions

### Reasons
- I believe new users would not be aware that the editor has a preview pane, and there is no easy way for them to find this out and to enable it.
- Most every modern editor uses WYSIWYG or similar & new users would expect to see such an editor when they first start using it
- I cannot think of any reason to introduce the editor without its preview pane set on

**Comment by pmario** [comment]
Every toolbar button has a tooltip. IMO we can expect, that new users at least hover every button once. I personally press every button, to see what happens, if I'm new to an editor.

**Comment by 00SS** [comment]
Good point!

Perhaps a Beginner's help tiddler should be made on using the Editor, advising all new users to hover over each of the 24 buttons and read the tooltips. When they reach the 23rd button, they can just enable the preview!

New users often want to just get on with it before exploring too deeply. My proposal is intended to facilitate this known behaviour.

If we can find some downsides to enabling the preview pane, then it may be easier to decide which is a better option for unseasoned new users.

**Comment by twMat** [comment]
I don't agree with the OP but, that said, I think the preview pane toggle should not be positioned where it currently is. IMO it should sit inside the editor text area in the extreme upper right corner. IMO the tools should be - and are probably *expected* to be - "about" the formatting of the text, not the editor itself.
