### ISSUE TITLE
Modify splash page

### ISSUE THREAD

**Issue by twMat** [Jermolene/TiddlyWiki5#3935]
![image](https://user-images.githubusercontent.com/4534056/57013628-b98ddc00-6c0c-11e9-90d7-e093e852cdbc.png)

- What's that house doing there? Suggest: remove
- Motovun Jack, OK but the small rectangle looks really amateurish.  Suggest: exchange for the [stylized svg](https://tiddlywiki.com/#Motovun%20Jack.svg) in a "we're proud" size or possibly the favicon in a "subtle branding" size. Either way, perhaps in colour for softer impression.

**Comment by Jermolene** [comment]
This splash screen originated as a demo of how to make one. It shows three key features that are not hugely obvious:

* CSS animation
* An embedded SVG
* An embedded image

Another consideration is that anything in the splash screen will end up being duplicated in the HTML file (once for the splash screen itself, and once for the tiddler that contains the image).

So, we could use a different SVG perhaps but I'd be inclined to keep the small bitmap of Jack precisely because it's small and so we're not paying too much for carrying it twice. Perhaps also we could improve the CSS...

**Comment by twMat** [comment]
One idea, if possible, is a demo in a separate subpage, linked to from the docs on splash pages? Might it be possible to demo it using a splash page for a static tiddler page even?

Otherwise I guess this is encouragement for me to think more about #3925 (Front page redesign proposal) :-)

**Comment by Jermolene** [comment]
> One idea, if possible, is a demo in a separate subpage, linked to from the docs on splash pages?

It's quite nice making the one example serve both needs because it reduces the number of moving parts we have to maintain going forwards.

> Might it be possible to demo it using a splash page for a static tiddler page even?

Hopefully the static renderings don't need a splash screen because they load instantly without requiring JS processing.

**Comment by sukima** [comment]
The current setup works well for me with a fancy SVG: https://tritarget.org/#%24%3A%2FSplashScreen

**Comment by twMat** [comment]
OK, so the conclusion is that the splash page looks as intended.
Fair enough. Closing.

**Comment by Jermolene** [comment]
> OK, so the conclusion is that the splash page looks as intended. Fair enough. Closing.

Gosh no! I think your points were well made, and I'd love to improve the splash screen while still making it a showcase of the different types of image inclusion. Maybe just choosing a different icon from https://tiddlywiki.com/#ImageGallery%20Example would be enough?

**Comment by twMat** [comment]
Ah, OK. Reopening. 

>Maybe just choosing a different icon from ...

IMO it should be something that "makes sense". A logo is probably the best then, so from the existing svg's, I'd say it is the [Jack svg](https://tiddlywiki.com/#Motovun%20Jack.svg). If it specifically has to be an *icon* then I guess the hexagonal Jack is the one... even if the hexagonal shape is very arbitrary in the context.

Perhaps multiple icons that together illustrate TWs features (the edit pen, the wikilink, the transclusion...)?

As for the photo, might it be possible to just fade its edges? It really looks thrown in currently. 

The photo would also look much better if it was bigger to actually make a statement, but maybe that is costly? If size is not a problem then maybe it could even make for a nice background?

**Comment by sukima** [comment]
`<RandomThought>` What about the babel fish from the flyer/poster? I think that would look interesting in a splash page. `</RandomThought>`

**Comment by Jermolene** [comment]
OK I've tried switching to the Jack-in-a-hexagon icon, and swapping in the "New Release Banner", which I think works quite well to draw attention to the release

![image](https://user-images.githubusercontent.com/174761/57573779-70683400-7425-11e9-8c40-9b123d893322.png)

**Comment by Jermolene** [comment]
By the way, because the splash screen is technically part of the docs (it's in the tw5.com edition rather than the core), the changes should be live on https://tiddlywiki.com shortly.

**Comment by twMat** [comment]
This makes much more sense. Everything actually means something. Good with the boxshadow also. 
Harmony achieved, thank you.
Closing.

**Comment by Jermolene** [comment]
Thanks @twMat and apologies for the delay

**Comment by bimlas** [comment]
Not really related to the topic, but if we make the design better, we could use shadows (on the bottom of an element) and highlights (on the top) in more places. They make it clear that the tag is a pressable button, for example:

![image](https://user-images.githubusercontent.com/7034200/57696418-0207b980-7651-11e9-8097-8cef69a37d93.png)

(https://bimlas.gitlab.io/#TiddlyWiki, https://gitlab.com/bimlas/bimlas.gitlab.io/blob/43cc01af0aeeeaa144ff35ed32060561639ec0a2/tiddlers/$__bimlas_theme_Bimlas_base.tid#L67-70)

**Comment by twMat** [comment]
Looks nice! And I particularly agree with your note that:

>Not really related to the topic

;-) ;-) ;-)
