### ISSUE TITLE
Differentiate style classes for search- and tabs segments

### ISSUE THREAD

**Issue by twMat** [Jermolene/TiddlyWiki5#3936]
I'm investigating styling possibilites and noted that both sidebar segments
- $:/core/ui/SideBarSegments/search 
- $:/core/ui/SideBarSegments/tabs

are styled with `tc-sidebar-lists` . I figure they should have differently titled style classes as one might want to, for example, position the search elsewhere by means of styling...?

**Comment by Jermolene** [comment]
Hi @twMat the idea is that `tc-sidebar-lists` captures the things that are in common with all the sidebar lists; if we need to style specific lists differently then we may need to add further, more specific classes to those elements.

**Comment by twMat** [comment]
>Hi @twMat the idea is that tc-sidebar-lists captures the things that are in common with all the sidebar lists; 

Hm, what does the search field have in common with the sidebar lists that e.g the page tools don't? Basically I'm wondering why is there a div surrounding specifically the search things, styled with `tc-sidebar-lists`?

>if we need to style specific lists differently then we may need to add further, more specific classes to those elements.

So no confusion; I'm not talking about styling "specific lists" (as in the individual tabs) but about the individual sidebar *segments*.

**Comment by Jermolene** [comment]
Hi @twMat 

> Hm, what does the search field have in common with the sidebar lists that e.g the page tools don't? Basically I'm wondering why is there a div surrounding specifically the search things, styled with `tc-sidebar-lists`?

The `tc-sidebar-lists` class is around the whole search widget, including the dropdown that contains the actual list. The class should probably have been assigned to a wrapper around the list, and not include the rest of the search gubbins.

In any case, backwards compatibility pretty much constrains us to deal with situations like this by adding new classes, rather than modifying how the existing ones are applied.

**Comment by twMat** [comment]
>In any case, backwards compatibility pretty much constrains us to deal with situations like this by adding new classes, rather than modifying how the existing ones are applied.

OK. There are already internal divs with `tc-search` (for the search stuff) and `tc-tab-set` (for the tab lists) so I guess a hacker can access those and just ignore or overwrite any surrounding div styles then.
Thanks regardless.
Closing
