### ISSUE TITLE
adaptorInfo and tiddlerInfo is only for TiddlyWeb?

### ISSUE THREAD

**Issue by linonetwo** [Jermolene/TiddlyWiki5#3938]
https://github.com/Jermolene/TiddlyWiki5/blob/07198b9cda12da82fc66dcf0589d6a9caab1cdf6/core/modules/syncer.js#L494-L508

How can I use these fields?

**Comment by Jermolene** [comment]
Hi @linonetwo `tiddlerInfo` is the state information stored by the syncer for each tiddler. It includes the `adaptorInfo` property which contains whatever the adaptor needs to store as state for each tiddler.
