### ISSUE TITLE
Changed favicon?

### ISSUE THREAD

**Issue by twMat** [Jermolene/TiddlyWiki5#3940]
Both empty from tw.com and from prerelase have this favicon

![image](https://user-images.githubusercontent.com/4534056/57181171-a4c17a80-6e90-11e9-8957-0d8d00e14aaa.png)

Mistake?

**Comment by Jermolene** [comment]
Hi @twMat are you using Chrome? I think that's the default favicon that Chrome uses. Both tiddlywiki.com and tiddlywiki.com/prerelease show the correct icon for me, but I have noticed that Chrome has recently been apt to "forget" favicons. Might be worth checking in another browser, and in a fresh Chrome profile.

<img width="1448" alt="Screenshot 2019-05-04 at 17 26 03" src="https://user-images.githubusercontent.com/174761/57181943-b8211580-6e91-11e9-8f35-4cadf5ae7f20.png">

**Comment by twMat** [comment]
Chrome - you're right! However... also firefox behaves strangely; no favicon at all for empty, but the usual one for e.g tw.com. Not sure what to make of it. 
Anyway, closing.
