### ISSUE TITLE
Improve performance instrumentation for filter evaluation

### ISSUE THREAD

**Issue by Jermolene** [Jermolene/TiddlyWiki5#3941]
It is proposed to extend the performance instrumentation mechanism so that the execution time of individual filter strings can be reported.

For example, one might learn that evaluating `[[$:/core/ui/PageMacros]] [all[shadows+tiddlers]tag[$:/tags/Macro]!has[draft.of]]` had taken 12.32ms since startup. By comparing the execution times of the different filters used in a wiki one can determine which ones may have performance issues.

**Comment by Jermolene** [comment]
Adding a screenshot
![image](https://user-images.githubusercontent.com/174761/57539824-3888c000-7343-11e9-8f14-dff691ca136e.png)

**Comment by pmario** [comment]
@Jermolene ... It would be nice to have a `$tw.perf.clearLog()` function. This would allow us to user the preview pane to activate measurements ... And probably have less noise. ... 

So the goal is to reduce the noise, if possible.
