### ISSUE TITLE
best method to pre configure Advanced Settings>Server URL ?

### ISSUE THREAD

**Issue by dubiouscript** [Jermolene/TiddlyWiki5#3946]
hi 
..having found some pointers in this comment

https://github.com/Jermolene/TiddlyWiki5/issues/1387#issuecomment-71161740
> @excogitation step by step:
> I changed line 4261 in empty.html from "http://$(userName)$.tiddlyspot.com/backup/" to the link to my store.php

and located "http://$(userName)$.tiddlyspot.com/backup/" on line 6653

and "http://\&quot; + username + \&quot;.tiddlyspot.com/store.cgi\" on line 5521

I have a "server" ;]  ( https://github.com/TooTallNate/bashttpd )
and am looking for any other methods to pre configure the 'Server URL'

this appears to work 
`curl https://tiddlywiki.com/empty.html |tee empty.html | sed -e 's#http://$(userName)$
.tiddlyspot.com/backup/#localhost:54321#g' >empty-mod.html`

however i see tiddlywiki / empty.html is makeing a request using 'OPTIONS' method
can this be used *somehow* to setup local defaults ??

... i also considered looking into 'Scripts for building tiddlywiki'
 https://tiddlywiki.com/dev/#Scripts%20for%20building%20tiddlywiki.com
to better understand how the pieces fit together

are there any other sources of enlightenment i have missed  ?

**Comment by pmario** [comment]
Hi, TiddlyWiki has it's own development server. You can use it if you want. 

The build-scripts you mention are outdated. ... 

I assume you installed `node.js + npm` and you did `npm install -g tiddlywiki`. So

```
tiddlywiki --version 
5.1.9
```

The following commands will create a dev-server setting: 

```
cd \temp
tiddlywiki ./test-server --init server

cat << EOF > test-server/tiddlers/_UploadName.tid
title: $:/UploadName

test-file
EOF

tiddlywiki test-server --listen
```

[localhost:8080/#$:/UploadName](http://localhost:8080/#%24%3A%2FUploadName) should show the file which was created.

**Comment by pmario** [comment]
also see: https://tiddlywiki.com/#Commands:Commands%20%5B%5Btiddlywiki.info%20Files%5D%5D

**Comment by pmario** [comment]
and: https://tiddlywiki.com/#ListenCommand:ListenCommand%20WebServer

**Comment by dubiouscript** [comment]
> Hi, TiddlyWiki has it's own development server. You can use it if you want.
> 
> The build-scripts you mention are outdated. ...


 
> I assume you installed `node.js + npm` and you did `npm install -g tiddlywiki`. 
tbh i was hoping to mash something together in that quirky shell svr just for fun... 

i guess i need to dig through th source , & previously didnt explore enough to find it was  internally viewable :sunglasses: 
https://tiddlywiki.com/#%24%3A%2Fcore%2Fmodules%2Fsaver-handler.js

 i was kind of avoiding  installing via npm *just because*
then i looked at the  TiddlyWiki5/blob/master/package.json
 ```
  "dependencies": {},
  "devDependencies": {},
"bundleDependencies": [],
```
and was presently surprised by an apparent lack of external module deps xD
so will try messing about abit with the node(.js) server

**Comment by pmario** [comment]
There are 2 "version" of save handlers. 

saver-handlers as found in https://github.com/Jermolene/TiddlyWiki5/tree/master/core/modules/savers ... Every saver is responsible to implement a file-based save. That means, it saves 1 tiddlywiki.html file. 

plugin sync adaptors as found in https://github.com/Jermolene/TiddlyWiki5/tree/master/plugins/tiddlywiki/tiddlyweb ... These adaptors allow you to save 1 tiddler as xx.tid file to a tiddlers subdirectory. 

The OPTIONS request probably comes from the put.js saver. ... It requests info from a WebDav server, to get the possibilities that are available. 

About dependencies. TW is selfcontained. Other libraries are included with plugins, if needed. eg: [jszip plugin](https://github.com/Jermolene/TiddlyWiki5/tree/master/plugins/tiddlywiki/jszip/files) So we can precisely control compatibility. ... With the disadvantage, that we also have to maintain the plugins ourself.

**Comment by Jermolene** [comment]
Hi @dubiouscript I'm not sure if I understand correctly, but it sounds like you want to configure the URL used by the upload saver. If so, you can use a startup action tiddler to assign a value to the tiddler `$:/UploadURL`.

**Comment by dubiouscript** [comment]
hi Jermolene

>I'm not sure if I understand correctly, but it sounds like you want to configure the URL used by the upload saver. 

yes exactly that

but i was hoping it was possible to automagically set this via sending a header 

in the case of  bashttpd server
using this 'add_response_header' function  https://github.com/TooTallNate/bashttpd/blob/79582483264acad15b49e4b911f17f7bda753f43/bashttpd#L130

eg : https://github.com/TooTallNate/bashttpd/blob/master/bashttpd.conf#L77

```
add_response_header "Server-URL" "blarg.localhost:54321/"
```

and like is done hear in tiddly wiki with  etag header.. 
https://github.com/Jermolene/TiddlyWiki5/blob/2f8053265e96e0ae57b8d7b6c841af15aebd3f6d/core/modules/savers/put.js#L33

..set the tiddly wiki 'UploadURL' variable ,  from  the "Server-URL"  header  

it appeared a reasonable sort of thing to expect an 'OPTIONS' request to do 

>   A server generating a successful response to OPTIONS SHOULD send any
   header fields that might indicate optional features implemented by
   the server and applicable to the target resource (e.g., Allow),
   including potential extensions not defined by this specification.

https://tools.ietf.org/html/rfc7231#section-4.3.7

---
>If so, you can use a startup action tiddler to assign a value to the tiddler $:/UploadURL.

thanks! 
i guess this went over my head when @pmario mentioned it before 
```
cat << EOF > test-server/tiddlers/_UploadName.tid
title: $:/UploadName

test-file
EOF
```
another example of setting Server URL via  "$:/UploadName"
https://github.com/Jermolene/TiddlyWiki5/blob/929b0c98330ad25aa4a32cd201274a6e89cd8902/editions/es-ES/tiddlers/%24__UploadURL.tid

just for reff 
https://github.com/Jermolene/TiddlyWiki5/blob/2f8053265e96e0ae57b8d7b6c841af15aebd3f6d/core/modules/savers/upload.js#L31

**Comment by Jermolene** [comment]
Hi @dubiouscript OK so it sounds like your best approach might be to fork the existing upload server, incorporating the OPTIONS request code from the putsaver. Let us know how you get on

**Comment by dubiouscript** [comment]
> Let us know how you get on

... currently  trawling the git history xD
```
<$button id=01 set="$:/UploadURL" field="fieldname" setTo="valuefoo"> foo </$button>

<$button id=00 set="$:/UploadURL" field="fieldname" setTo="value"> bar  </$button>
```
..apparently https://github.com/Jermolene/TiddlyWiki5/pull/268#issue-10640864 .. $:/UploadURL can be created / updated via button, all though im not shore its working exactly as expected described.. 

ftr
after a bit of messing about over the week end  
i now have a more or less working tiddly wiki script/configuration for TooTallNate/bashttpd server ,.. responding to head option requests and saveing post data *yay*  which i guess is posted with the upload saver ...

while the upload.js method appears to work 
 https://github.com/Jermolene/TiddlyWiki5/blob/2f8053265e96e0ae57b8d7b6c841af15aebd3f6d/core/modules/savers/upload.js#L60
ftr "0 - " means  saved ;]

upload.js method repeatedly pushes alot of data 
and ... apparently an api exists https://tiddlywiki.com/#WebServer%20API 
with which it appears possible to send/request the minimum required!

**Comment by dubiouscript** [comment]
https://tiddlywiki.com/dev/#Extended%20Persistence
