### ISSUE TITLE
Latex (Katex) \neq with offset forward slash 

### ISSUE THREAD

**Issue by aneuhold** [Jermolene/TiddlyWiki5#3963]
## Summary
When using \neq the forward slash is offset. This happens in the Katex Demo page as well, as shown in the images below:

![Katex Demo offset](https://i.imgur.com/Tlv5nk1.png)

![Katex Demo offset](https://i.imgur.com/oZjuOc5.png)

This does not occur on the Katex website. 

## Steps to reproduce

Use `$$\neq$$` in a tiddler body in a tiddlywiki that has the Katex plugin. Then save it to see the rendered result.

## Expected behavior

For the not equals symbol to be rendered correctly.

## Context

Windows 10, Chrome Version 74.0.3729.169 (Official Build) (64-bit)

**Comment by twMat** [comment]
I know nothing about this, but aren't you just putting the slash on the wrong side of the equal sign?

**Comment by twMat** [comment]
Confirmed.

**Comment by pmario** [comment]
There seems to be a ktex problem: https://github.com/KaTeX/KaTeX/issues/1842
This is probably the fix: https://github.com/KaTeX/KaTeX/pull/1852
This seems to be the version with the fix: https://github.com/KaTeX/KaTeX/releases/tag/v0.10.1

I can't see, which version we use in the KTeX plugin. .... So may be we need an update.

**Comment by pmario** [comment]
It seems [we use 0.10.0](https://github.com/Jermolene/TiddlyWiki5/commits/master/plugins/tiddlywiki/katex) ... so we need an update. Latest is: 0.10.2 <---- see 2
