### ISSUE TITLE
Jasmine Testframework

### ISSUE THREAD

**Issue by Sinister267** [Jermolene/TiddlyWiki5#3970]
Hello Jeremy,

I am currently working on a University Project where i use TW5 (its awesome  btw) and my Prof. is asking for us to implement Testing. Unfortunately I was unable to use the Plugin you created. Could you help me how i can enable it and how i could run the test.

Thank you a lot in advance

Artur

**Comment by flibbles** [comment]
I realize I'm replying two months after you posted this, but I can help if you still need any.

## Basics

Install the Jasmine plugin into your tiddlywiki project. Then you create test modules. A Jasmine test module needs to be set up in two ways:

* It needs the tag `$:/tags/test-spec`
* It's type should be: `application/javascript`

Your file will look something like:

![Screen Shot 2019-08-23 at 11 11 26 AM](https://user-images.githubusercontent.com/205465/63603046-c4db8d80-c596-11e9-85d9-fa038e137c9e.png)

To run these tests, it depends how are you running TW5. As a standalone file? Or as a Node.JS project? It's more natural as a Node.JS project, but either works.

### Standalone file

You need to install the Jasmine plugin into your project. If you have test tiddlers like I described above, they'll run automatically whenever you open your tiddler. The results will be at the bottom of the page.

### NodeJS project

Install the plugin into your `tiddlywiki.info` file. Something like:
```
        "plugins": [
                "tiddlywiki/jasmine"
        ],
```
Whenever you run a `tiddlywiki` command on the command line, the tests will run. It doesn't matter what command you use. I use `tiddlywiki --version`.

Hope this helps! Hope this isn't too late.

**Comment by flibbles** [comment]
Ah, I just saw your original post said you were having trouble enabling it. Do you mean installing the plugin?

If so, for NodeJS, just do what I wrote above, but it's not as easy for standalone files, because a drag-n-drop version isn't available anywhere I can find, but here it is:

[$__plugins_tiddlywiki_jasmine.tid.zip](https://github.com/Jermolene/TiddlyWiki5/files/3535206/__plugins_tiddlywiki_jasmine.tid.zip)

You've got to unzip it first, and then drag the resulting file onto your project's browser window.

I really don't know why this isn't available through tiddlywiki.com. Probably because it's so cumbersome to use through the browser. I'm trying to fix that.

**Comment by Jermolene** [comment]
Hi @flibbles @Sinister267 a few plugins are currently purposely [https://github.com/Jermolene/TiddlyWiki5/blob/master/editions/pluginlibrary/tiddlywiki.info#L13](omitted) from the plugin library on the basis that they aren't generally useful for users of the single file configuration:

```
$:/plugins/tiddlywiki/upgrade
$:/plugins/tiddlywiki/translators
$:/plugins/tiddlywiki/pluginlibrary
$:/plugins/tiddlywiki/jasmine
```

We could consider enabling the jasmine plugin.

**Comment by flibbles** [comment]
Yeah, I figured it was something like that. I admit that if @Sinister267 is using a single-file configuration, they're in for a bad time.

The discussion on whether to do something about it should probably take place  #4194.

_This issue can probably be closed_, seeing as how we're both super late in helping this guy. His university project is almost certainly over.

**Comment by Jermolene** [comment]
Thanks @flibbles

**Comment by linonetwo** [comment]
I'm following this, this is my setup

```ts
      if (test) {
        $tw.boot.extraPlugins = [
          ...($tw.boot.extraPlugins ?? []),
          'tiddlywiki/jasmine',
        ];
      }
      const serve = async () => {
        const port = await getPort({ port: 8080 });
        $tw.boot.argv = [wiki, '--listen', `port=${port}`];
        if (test) {
          $tw.boot.argv = [wiki, '--verbose', '--version'];
        }
        $tw.boot.boot();
      };
```

and in wiki

```wiki\tiddlers\tests\activity-log-tools\filters.js.meta
title: tests/activity-log-tools/test-filters.js
type: application/javascript
tags: $:/tags/test-spec
```

```wiki\tiddlers\tests\activity-log-tools\filters.js
describe('Filter tests', function() {
  // Test filter parsing
  it('should parse new-style rich operator suffixes', function() {
    expect($tw.wiki.parseFilter('[search:: four, , five,, six [operand]]')).toEqual(
      [{ prefix: '', operators: [{ operator: 'search', suffix: ': four, , five,, six ', suffixes: [[], ['four', 'five', 'six']], operands: [{ text: 'operand' }] }] }],
    );
  });
});
```

why the console output is only

```sh
> @0.0.2 test C:\Users\linonetwo\Documents\repo-c\tw-gamification
> tiddlywiki-plugin-dev dev --test

syncer-server-filesystem: Dispatching 'save' task: $:/StoryList
Compiling...
████████████████████████████████████████ 100% | tw-gamification

Boot log:
  Startup task: load-modules
  Startup task: info after: load-modules before: startup
  Startup task: plugins after: load-modules before: startup
  Startup task: startup after: load-modules
  Startup task: story after: startup
  Startup task: commands platforms: node after: story
Executing command: version 
5.3.3
syncer-server-filesystem: Dispatching 'save' task: $:/StoryList
```

**Comment by linonetwo** [comment]
tiddlywiki-plugin-dev@0.1.0 provides `tiddlywiki-plugin-dev test` that run the test, no setup needed.
