### ISSUE TITLE
Request: <$link/> as synonym for current verbose syntax

### ISSUE THREAD

**Issue by twMat** [Jermolene/TiddlyWiki5#3974]
**Description/request**
As brained up by @Jermolene in #3972 , the empty link widget, i.e `<$link/>` could be modified to work as a synonym for `<$link to=<<currentTiddler>>><$view field="title"/></$link>`.

**Comment by twMat** [comment]
Addition: 
Might this syntax `<$link to=... />` use the *title* field of `...` as label, if there is such a field? This would mean the viewwidget and closing link tag can be omitted in the verbose version.

**Comment by Jermolene** [comment]
Hi @twMat I don't quite understand your second comment. The proposal is that the `<$link>` widget should use `<$text text=<<currentTiddler>>/>` as it's content if it has no content specified. That particular syntax is just another way of outputting the title.

**Comment by twMat** [comment]
In deed very poorly described. I've updated the post.

**Comment by Jermolene** [comment]
Hi @twMat 

> If there is a to argument, then the default name for the link could be the title of whatever the to argument is (or points to)

Sorry, I phrased it poorly, but that is what the proposed modification does: if there is no content within the link widget then it would default to displaying the title of the target of the link.

**Comment by twMat** [comment]
Wow - fast! Thank you!

**Comment by pmario** [comment]
hmmm, I know that I was aware of the change, ... but it broke my uni-link plugin. .. So we definitely need to be more careful, if we change core defaults.

**Comment by Jermolene** [comment]
> hmmm, I know that I was aware of the change, ... but it broke my uni-link plugin. .. So we definitely need to be more careful, if we change core defaults.

Proving once again that maintaining backwards compatibility is hard. Can you briefly explain how the change impacted the plugin?

**Comment by pmario** [comment]
I did fix it already (uni-link plugin). ... and it's partially my fault. I did use parse-tree code that was a little bit hacky, to avoid the need to modify "core" js elements. 

Now I need to modify core "link backlink" generation but the "parser" output is much cleaner now. ... I knew, that it could be a problem...

**Comment by Jermolene** [comment]
Thanks @pmario
