### ISSUE TITLE
request: function for replace

### ISSUE THREAD

**Issue by twMat** [Jermolene/TiddlyWiki5#3977]
I wish for a good way to _replace_ segments of strings in longer texts.

Currently one has to reside to opening the *html file in an editor* - or one is forced to create very elaborate filter constructs that recursively iterates through the text to split, remove, append, etc etc. To name an example of the latter, I did that in [TriEdit](http://triedit.tiddlyspot.com/) a long time ago but never published it because I felt it was too fragile and also relied on other peoples filter ops.

The most obvious use case is of course; "I want to replace *foo* with *bar* in a set of tiddlers."

Apparently js has a [replace()](https://www.w3schools.com/jsref/jsref_replace.asp) method so maybe it is not overly complicated to tiddlify it.

**Comment by Jermolene** [comment]
Hi @twMat there are two existing issues about search and replace:

* #3803 proposing a `searchreplace` filter operator
* #3288 proposing a way of implementing the UI for search and replace

Does your request fit within one of those proposals?

**Comment by twMat** [comment]
Thank you, I had missed those.
