### ISSUE TITLE
Providing documentation changes for 5.1.20 tiddlywiki.com? eg mathematics

### ISSUE THREAD

**Issue by AnthonyMuscio** [Jermolene/TiddlyWiki5#3979]
What is the best way for me to submitt feedbackl for documentation changes for 5.1.20 tiddlywiki.com? eg mathematics prior to its release?

For example
file:///C:/Data/TW5/EmptyFiles/5.1.20Pre-release2019-06-14.html#Mathematics%20Operators

Examples are not using "=" before each number thus will be de-duped if the same value is used more than once. This is fragile, and miss-leading.

**Comment by rmunn** [comment]
You inspired me to check. The individual example tiddlers were using `=` properly, so only the "Mathematics Operators" tiddler needed to be changed. So I submitted a fix.

**Comment by twMat** [comment]
>What is the best way for me to submitt feedbackl for documentation changes for 5.1.20 tiddlywiki.com?

For doc errors, wouldn't it just be a PR? I click on the tiddler in the prerelease and the pink ribbon to open in github, etc.

**Comment by Jermolene** [comment]
Thanks @AnthonyMuscio @rmunn @twMat I'm closing this now that @rmunn's has contributed #3982
