### ISSUE TITLE
CodeMirror: investigating wrong selection values

### ISSUE THREAD

**Issue by BurningTreeC** [Jermolene/TiddlyWiki5#3986]
The codemirror editor sometimes reports negative values for the current selection when there's no text and/or the cursor is at the beginning of the editor (first index)

This makes repeated clicks on toolbar buttons behave the wrong way sometimes (jumps)

**Comment by Jermolene** [comment]
Thanks @BurningTreeC

**Comment by BurningTreeC** [comment]
The selections are correct, what causes selection-losses is the rendering timeout of 400ms in $:/config/Drafts/TypingTimeout ... 

to reproduce: try hitting the `{{}}` toolbar button repeatedly with aprox. 400ms intervals on tiddlywiki.com/prerelease with the cursor within a codemirror instance. it will sometimes loose the cursor position and add `{{}}` where it should remove it instead

**Comment by BurningTreeC** [comment]
A very low timeout works better for codemirror
