### ISSUE TITLE
How to proceed with "selectable" input fields

### ISSUE THREAD

**Issue by BurningTreeC** [Jermolene/TiddlyWiki5#3987]
At http://selectable-inputs.tiddlyspot.com/ there's a demo that uses macros to generate input fields that can be provided with a filter which can be sorted by the user input within the input field. The filter matches can be selected (I prefer the up/down arrow keys, but they can be changed) and another key can be used to perform an action on the selection. There's another key to clear the input field.

I think this would be a great feature for the tiddlywiki core, but @Jermolene once mentioned another mechanism that could provide a similar functionality (through restoring selections on every browser refresh IIRC)

I'm just posting this as an issue so that we don't forget about the possible feature

**Comment by Jermolene** [comment]
Thanks @BurningTreeC perhaps we should try to pick up the selection retention work when v5.1.20 is out.

**Comment by BurningTreeC** [comment]
>Thanks @BurningTreeC perhaps we should try to pick up the selection retention work when v5.1.20 is out.

makes sense, thanks @Jermolene
