### ISSUE TITLE
[doc] In the GettingStarted "Savers" listing, remove the OS buttons

### ISSUE THREAD

**Issue by twMat** [Jermolene/TiddlyWiki5#3989]
The word "Platform" seems to refer to both **browsers** and **OS's** here:
![image](https://user-images.githubusercontent.com/4534056/59560801-cb3e0e00-9017-11e9-846f-b5cea8ddbb03.png)

But clicking "Windows" filters out that first thumbnail which doesn't seem correct.

I don't understand why OS's are listed there to begin with. Both browsers and OS's are categorized as "Platforms" in the list but they are treated differently. Alternatively, they would make sense if there was a *multi-select* option to get savers that exclusively match both e.g "windows AND chrome".

**Proposal**: Either of:

- Remove the OS buttons
- Introduce multi-select
- Re-tag the individual saver docs with OS's so that clicking e.g windows also shows the "Download saver"

**Comment by dubiouscript** [comment]
>     * Re-tag the individual saver docs with OS's so that clicking e.g windows also shows the "Download saver"

i thunk some thing similar
...imho  the "filtered" separation between savers should something like

savers : desktop-app / browser / server 
&..
servers : locally-hosted / `someone-elses-computer` (aka "cloud")

**Comment by Jermolene** [comment]
Hi @twMat @dubiouscript 

> The word "Platform" seems to refer to both browsers and OS's here

Yes, it's definitely confusing, and I'm not sure that it was successful to have both OSs and browsers listed there (the idea was to provide multiple recognisable triggers to help users understand which options might apply to them). But it's more fundamental than that: the platform tags don't really apply at all to online services, but there are other tags that might be helpful ("free", "DIY", etc).

To your three suggestions I'd add a fourth:

* Redesign "Getting Started" to be more like a wizard, guiding the user through a series of questions to narrow down the listed options

**Comment by twMat** [comment]
OK, so a more radical redesign of GettingStarted is what makes most sense then. So I'd say this is covered in #3925 - so closing this here. Thanks for input.
