### ISSUE TITLE
Inline {{{...}}} output needs comma+space separator

### ISSUE THREAD

**Issue by twMat** [Jermolene/TiddlyWiki5#3990]
`{{{ [tag[HelloThere]] }}}` gives a nice bare bones list, breaking new line for each item
`Foo {{{ [tag[HelloThere]] }}}` gives an inline list but each item iscrammedlikethis which makes it **unusable** for direct textual displays.

**Proposal**
Insert a comma+space after each item. 

Note: It is way too demanding to create a *template* to `{{{ do this || template }}}` and even a provided template activated in this manner requires you to "hm, wasn't there some template for this? What was it named, how find" etc.

I don't know if this inline format would mess up e.g `<$set .... ={{{...}}}>`, i.e where the evaluation is not used for direct textual display. In that case I should note that it is actually simple to insert comma+spaces using only CSS!

If the proposal is NOT a problem, then the proposal ends here. If it IS a problem, then maybe some kind of flag could indicate how the output should be displayed. For example `{{{ [tag[HelloThere]]csv }}}`. I'm unsure if csv is only a comma or comma+space but you get the point. (`csp`?)

**Comment by twMat** [comment]
Addendum: Here's an example of how to create this purely with CSS

```
<div class="csv">
Foo {{{ [tag[HelloThere]] }}}
</div>

<style>
.csv span:after {content:", "}
.csv span:last-of-type:after  {content:""}
</style>
```

**Comment by Jermolene** [comment]
Hi @twMat 

This is another manifestation of the weird, confusing logic that TiddlyWiki uses to distinguish "block" vs. "inline" modes. All markup engines suffer from the same basic problem: that when parsing we need to distinguish between block mode markup (like headings) and inline markup (like bold text), and keep track of which is allowed in any particular context.

The rule you're bumping into here is that triple braces are parsed as a block mode structure if it starts at the start of a block, and is terminated by two blank lines. In block mode, it generates DIVs and in inline mode it generates SPANs.

As it's turned out, everybody is hopelessly confused by the rules, and many of the system templates use various tricks to opt out of it entirely, by forcing inline mode for an entire template.

So, this ticket is the tip of a much bigger iceberg. I'd like to improve things but it's complicated because we don't have a better solution to the overall problem, and we have the usual backwards compatibility constraints.

**Comment by twMat** [comment]
>... we don't have a better solution to the overall problem, and we have the usual backwards compatibility constraints.

Thanks for informative reply. 

So, should I close this issue - i.e will this be dealt with automatically when the bigger issue one day is dealt with? 

But, meanwhile, how can someone solve this problem without having to manually wrap the transclusion in a class each time - i.e how can one target the output spans? There is no unique output structure. **Could perhaps the `{{{...}}}` mechanism have a built in class that hackers can hook on to?** That should be backwards compatible AFAICT. I'm guessing `{{{...}}}` is built on the TranscludeWidget but there is no `class` parameter there (interestingly there's no *template* parameter either...?).

**Comment by pmario** [comment]
I think using a template or the `<$list ` widget itself AND a user specific CSS, is the only way that make sense here. ... As you found out. Even if you use a template, you'll have to have some special CSS styling, to block the "last-of-type" colon. ... So if we need a inline list, we should add `<<list-links-inline>>` macro to the core. Similar to `list-links` macro. There may be a `xx-draggable` for inline lists too.

**Comment by Jermolene** [comment]
Hi @twMat @pmario 

> So, should I close this issue - i.e will this be dealt with automatically when the bigger issue one day is dealt with?

Yes; we can probably only really deal with it in TWX.

> But, meanwhile, how can someone solve this problem without having to manually wrap the transclusion in a class each time - i.e how can one target the output spans? There is no unique output structure. Could perhaps the {{{...}}} mechanism have a built in class that hackers can hook on to? That should be backwards compatible AFAICT.

The trouble here is that the triple braces construction generates a list widget, but list widgets intentionally don't create any DOM elements, and so there's nowhere to apply a class.

**Comment by twMat** [comment]
Thanks for replies.

pmario wrote
>So if we need a inline list, we should add `<<list-links-inline>>` macro to the core.

Nice idea. It would make inline lists usable, which they currently are not.
...
Jermolene wrote
>The trouble here is that the triple braces construction generates a list widget, but list widgets intentionally don't create any DOM elements, and so there's nowhere to apply a class.

But isn't it TW that wraps the items in *spans* (or where do the spans come from)? As it does so, could it not sneak a class into that span, too?

**Comment by Jermolene** [comment]
> But isn't it TW that wraps the items in spans (or where do the spans come from)? As it does so, could it not sneak a class into that span, too?

Those span/divs are in the default item template that is used when no template is specified in the triple brace construction. They wrap the items, not the overall list.
