### ISSUE TITLE
[tw.com] Create dummy doc tid 

### ISSUE THREAD

**Issue by twMat** [Jermolene/TiddlyWiki5#3997]
It is simple enough to make PR for *changes* to doc tids but not so for PR'ing *new* doc tids. As a humble *modificateur o'docs* I don't get how to PR new tids so I'm requesting a *dummy doc tid*, or even a few, where proposed text can be PR'ed.

A frequent use case is our ambition to keep *examples* split out from the main text, which is not consistently "implemented".

The dummy could even be prefixed `$:/` to hide it (...unless that puts it in the tricky-to-PR category)

**Comment by Jermolene** [comment]
Hi @twMat the secret is happily pretty simple.

1. Find the folder that should contain your new tiddler

<img width="1005" alt="image" src="https://user-images.githubusercontent.com/174761/59674047-5951fa00-91ba-11e9-8e8a-2f46c717ec0b.png">

2. Click the "Create new file" button

<img width="1049" alt="image" src="https://user-images.githubusercontent.com/174761/59674084-74bd0500-91ba-11e9-8861-967bfcde84ee.png">

3. Choose a filename for the new tiddler in the text box at the top (here it's `MyNewTidd.tid`). It won't work properly without the correct file extension (usually `.tid` for docs)

4. Scroll down and create the PR for the new file.

**Comment by twMat** [comment]
Aha, thanks! Will try when moment arises.

**Comment by Jermolene** [comment]
Hi @twMat feel free to try creating a dummy tiddler, with an instruction to me to delete it afterwards. At some point it would be great to update https://tiddlywiki.com/#Improving%20TiddlyWiki%20Documentation
