### ISSUE TITLE
sentencecase behavior is unexpected

### ISSUE THREAD

**Issue by rmunn** [Jermolene/TiddlyWiki5#4003]
The new `sentencecase` operator doesn't produce the results I would expect. Consider the title list "abc [[ten reasons to switch to TiddlyWiki]] Example", containing three titles.

### What I'd expect

I'd expect `sentencecase` to produce a title list consisting of "Abc [[Ten reasons to switch to TiddlyWiki]] Example", where only the *first* word in each title is converted to uppercase and, crucially, the rest of the letters are left alone.

### Current behavior

What `sentencecase` currently produces is "Abc [[Ten Reasons To Switch To Tiddlywiki]] Example". Each word of the multi-word title has been capitalized, and the name TiddlyWiki has become Tiddlywiki. This is more like what I'd expect from an operator called `titlecase`.

### Notes

Why do I say that it's crucial for the rest of the letters to be left alone? Because converting them all to lowercase before capitalizing each one risks converting "TiddlyWiki" to "Tiddlywiki", which may not be the desired result. If `titlecase` (as I'd suggest renaming the `sentencecase` operator to) is made to not touch the rest of the letters, then this has two benefits:

* Scenarios where the user doesn't want "TiddlyWiki" to get a lowercase "W" become possible.
* Scenarios where the user **does** want "TiddlyWiki" to get a lowercase "W" are still possible, by chaining multiple filters together like `lowercase[]titlecase[]`.

So I'd suggest renaming the current implementation of `sentencecase` to `titlecase` (AND editing it to remove the `.toLowerCase()` call in there — the user can do that if they want it, but it won't always be desirable), and creating a new `sentencecase` operator that touches only the first letter of each title, rather than the first letter of each word.

The `titlecase` and `sentencecase` documentation would also need a sentence or two to mention that they *don't* change the case of any other letters, and they should be combined with a `lowercase` filter if the desired result is to change "aBcDeF" into "Abcdef".

**Comment by AnthonyMuscio** [comment]
Perhaps what is currently called sentencecase should be called capitalise? and the first word capitalisation only called sentencecase.

Following from this
I wonder if there is a way to use capitalisation to generate an abbreviation?

eg United Nations High Commissioner for Refugees UNHCR or U.N.H.C.R. Note the for is not capitalised so It may not always be appropriate

**Comment by Jermolene** [comment]
Hi @rmunn thanks that sounds sensible, and apologies for the late response. I'll respond over at #4006
