### ISSUE TITLE
Is Product operator "brittle" or buggy?

### ISSUE THREAD

**Issue by AnthonyMuscio** [Jermolene/TiddlyWiki5#4014]
In some tests demonstrating the use of the "=" sign I had the following results for sum and product, where the **variable and field name contained the value "3"**. This means they do not work the same way. I have not yet tested it for other mathematics operators that operate on all input values at once.

Result of filter="`3 =[<a-number>] =[{!!fieldname}] +[sum[]]`"
9

Result of filter="`=3 =[<a-number>] =[{!!fieldname}] +[product[]]`"
0 INCORRECT if it worked the same as sum[]

Result of filter="`=3 =3 =3 +[product[]]`"
27 CORRECT but only if using litterals.

Regards
Tony

**Comment by Jermolene** [comment]
Hi @AnthonyMuscio it would be helpful if you could provide enough information to easilt replicate the problem. If there's more than fits in a single tiddler, perhaps include a JSON file that can be dropped on https://tiddlywiki.com/prerelease/empty.html to replicate the problem

**Comment by AnthonyMuscio** [comment]
Jeremy, 
I went to copy my test which led me to conclude this error and discovered I had a `</$set>`  too high in the tiddler. The result is in the product filter the variable was empty and treated as 0. Of course multiple anything by 0 is 0. 

I some ways I would have hoped a missing value would not be converted to 0. The Question is do we fix this or document it?

Paste the following into a new tiddler on the pre-release to see
```
\define filter-result(filter) 
<h3>Result of filter="<$text text="$filter$"/>"</h3>
<$list filter="$filter$" emptyMessage="No result from filter $filter$"></$list>
\end
<$set name="a-number" value="3">
:Note variable "b-number not defined"

<h2>Testing the Product Operator</h2>

<<filter-result """=3 =[<a-number>] =[{!!fieldname}] +[product[]]""">>
 
<<filter-result """=3 =3 =3 +[product[]]""">>
 
<<filter-result """3 =[<a-number>] =[{!!fieldname}] +[sum[]] 3 =[<a-number>] =[{!!fieldname}] +[product[]]""">>

<<filter-result """=3 =[<b-number>] =[{!!fieldname}] +[product[]]""">>

</$set>

```

Regards

**Comment by pmario** [comment]
Since the OP seems to be resolved. 

I think the important thing here is: 

>I some ways I would have hoped a missing value would not be converted to 0. The Question is do we fix this or document it?

@AnthonyMuscio could you adjust the title of the issue?

**Comment by AnthonyMuscio** [comment]
Title changed from
Is Product operator "brittle" or buggy?
to 
The Product operator will do as expected anything multiplied by 0 is zero, and 0 is the default if you have a missing value in maths

and closed, I will see if a suitable doco change can be done
