### ISSUE TITLE
Filters: Interpret "[]" and "[<missing>]" as empty/nothing

### ISSUE THREAD

**Issue by twMat** [Jermolene/TiddlyWiki5#4018]
This doesn't make sense

`<$list filter="[]">foo</$list>` gives `foo` 
`<$list filter="[] [] [] []">foo</$list>` also gives (only one) `foo`  and even...
`<$list filter="[] 1 2 3 4 5">foo</$list>` also gives (only one) `foo` 
 but...
`<$list filter="[]"></$list>` gives error

...so is `[]` a faulty filter or not?

I'm guessing the filter is interpreted as starting with the first encapsulating bracket `[` **but then views the rest as *content* to that initial bracket, i.e also that immediate `]` is treated as an argument... and the initial bracket then never gets a resolving end bracket.**

Further

`<$list filter="[{missing}]">should not show</$list>`
Problem: There is no `missing` tiddler, still the widget shows the text. IMO it shouldn't.

..and/but...

`<$list filter="[{missing}]"></$list>` ...doesn't give an error message like with `<$list filter="[]"></$list>` ...which makes me think the missing transclusion is evaluated into *something* (what?) which makes the `]` be interpreted as the resolving bracket, but `[thesomething]` is treated as an *empty* filter.

**Proposal**: Make both the special case with the exact string `[]` and anything `[<non-existing>]` be interpreted as empty/nothing in filters.

**Comment by Jermolene** [comment]
Hi @twMat if you try `[]` in the "filters" tab of advanced search you'll see that it actually triggers an error: "Filter error: missing [ in filter expression". The error is "delivered" as a single filter result.

To your other question, `[{missing tiddler}]` is interpreted the same as `[[]]`, ie it returns an empty string.

**Comment by twMat** [comment]
>Hi @twMat if you try `[]` in the "filters" tab of advanced search you'll see that it actually triggers an error: "Filter error: missing [ in filter expression". The error is "delivered" as a single filter result.

...so why does `<$list filter="[]">foo</$list>` give `foo` ?

Are you saying the error message itself is the actual single item filter output? So that the "foo" here is really *because* of that?

>To your other question, `[{missing tiddler}]` is interpreted the same as `[[]]`, ie it returns an empty string.

OK... so is there any reason to not treat an empty string as empty/nothing? The current behaviour causes false positives e.g when supposedly evaluating a state tiddler but in reality the tiddler is missing.

**Comment by Jermolene** [comment]
> ...so why does `<$list filter="[]">foo</$list>` give `foo` ?

Because the filter returns a single result for the error message, and so you get a single instance of `foo`.

> Are you saying the error message itself is the actual single item filter output? So that the "foo" here is really because of that?

Yes, that's right.

> OK... so is there any reason to not treat an empty string as empty/nothing? The current behaviour causes false positives e.g when supposedly evaluating a state tiddler but in reality the tiddler is missing.

Are you suggesting that empty strings be ignored in filters? That would break a bunch of stuff. e.g. the search and replace via split and join needs to be able to work with empty strings.

**Comment by pmario** [comment]
I think you use the wrong tools: `[{missing tiddler}]` use `[{missing}has[title]]` should do what you want.

**Comment by twMat** [comment]
>Are you suggesting that empty strings be ignored in filters? That would break a bunch of stuff. e.g. the search and replace via split and join needs to be able to work with empty strings.

You rascal, stay off my baby ;-) ;-) 
OK... I guess this was just transferred to TWX status where the proposal is empty strings should be ignored... IF that is the most sensible use of them.

@pmario - thanks for the tip! Perhaps even clearer: `{missing}!is[missing]`.
