### ISSUE TITLE
Shortcut for global search

### ISSUE THREAD

**Issue by BurningTreeC** [Jermolene/TiddlyWiki5#4020]
Could we add a keyboard shortcut that makes the cursor jump to the sidebar search?

**Comment by Jermolene** [comment]
Hi @BurningTreeC that would be great, if you're offering?

**Comment by BurningTreeC** [comment]
Yes, I would like to. I think it could be a hack that makes that sidebarsegment render again...

**Comment by BurningTreeC** [comment]
Alt-f for find or similar as the shortcut?

**Comment by pmario** [comment]
I'd like `Ctrl-Shift-F` ... or configurable.

**Comment by BurningTreeC** [comment]
I think it should be configurable but with a preset... Ctrl-shift-f works fine for me

**Comment by BurningTreeC** [comment]
I could make the search sidebarsegment render again by adding a tag and deleting the Tiddler directly afterwards which would be a hack, or we add a simple mechanism that includes a 'refreshTiddler' parameter which makes an input field refresh whenever that Tiddler changes. What do you think?
