### ISSUE TITLE
th-renaming-tiddler - double use - with different return values

### ISSUE THREAD

**Issue by pmario** [Jermolene/TiddlyWiki5#4023]
Hi, 

The following line expects a "tiddler object" as a return value: https://github.com/Jermolene/TiddlyWiki5/blob/274dffe75053b165b4498c42fc70f1fa9488cedf/core/modules/wiki-bulkops.js#L26

The following line expects an "event" as a return value.: https://github.com/Jermolene/TiddlyWiki5/blob/274dffe75053b165b4498c42fc70f1fa9488cedf/core/modules/widgets/navigator.js#L601

IMO **That's a big problem**. ... 

The `tm-rename-tiddler` message isn't documented, so the only affected plugin should be the "multi-user" plugin. ... **PR that introduced the "event" hooks**: https://github.com/Jermolene/TiddlyWiki5/pull/3206

**Comment by pmario** [comment]
My proposal is to rename the "event-hooks"

**Comment by pmario** [comment]
Can you see the problem. 

![th-renaming-tiddler](https://user-images.githubusercontent.com/374655/60330677-434ef100-9993-11e9-86c3-9c18b08bd212.gif)

The same hook is invoked 2 times with different expectations.

**Comment by Jermolene** [comment]
Hi @pmario well spotted!

The original `tm-renaming-tiddler` hook was implemented in 2397f0aa6f7af305807b61ccb1d435c2e6a789ab, and the newer one in #3206. I note that #3206 lacks documentation while there is complete docs in 2397f0aa6f7af305807b61ccb1d435c2e6a789ab (see https://tiddlywiki.com/dev); if documentation had been produced it maybe would have been more likely to have been spotted.

I'd rather fix #3206 to match the existing documentation.

**Comment by pmario** [comment]
>I'd rather fix #3206 to match the existing documentation.

But @inmysocks did create the PR for a special purpose, which expects an event and returns an event. ... So imo it may need a new and different hook-name.

**Comment by pmario** [comment]
We'll see, what Jed says.

**Comment by Jermolene** [comment]
Hi @pmario when we have two things that clash like this the one that "wins" is the one that has docs and/or is first. #3206 should have been done in a backwards compatible manner, and we'll just have to fix that now.

**Comment by inmysocks** [comment]
I am pretty certain that I removed the dependency on the hook from the plugin so there isn't a reason to keep the behaviour, if not I will just update the plugin. I can make a pull request to fix the behaviour in two or three days if no one else gets it first.

**Comment by pmario** [comment]
Close this one, as it seems a fix has been merged.
