### ISSUE TITLE
RSOD "a.localeCompare is not a function"

### ISSUE THREAD

**Issue by twMat** [Jermolene/TiddlyWiki5#4026]
RSOD "Uncaught TypeError: a.localeCompare is not a function"

`{{{ [tag[HelloThere]sortan[created]] }}}`

it's the `sortan[created]` causing it

(What would be an appropriate headline for this issue?)

**Comment by twMat** [comment]
Still causes RSOE. Hopefully an isolated circumstance.

**Comment by saqimtiaz** [comment]
This was a bug with the sortan operator used with the created/modified fields that has since been fixed for 5.1.23 pre-release, and can be tested at https://tiddlywiki.com/prerelease/#%24%3A%2FAdvancedSearch

@twMat could you please confirm and close the issue?

**Comment by twMat** [comment]
Confimed. Mucho thanko.
