### ISSUE TITLE
small rendering problem with codemirror

### ISSUE THREAD

**Issue by BurningTreeC** [Jermolene/TiddlyWiki5#4029]
The default 400ms for the `TypingTimeout` causes problems in the `cm instance` when clicking toolbar buttons with intervals approx equal to that timeout interval. Is it possible to turn that interval off when CodeMirror is used or automatically use a small interval for `cm instances`?

This is the problem described in #3986

**Comment by pmario** [comment]
There is a [Hidden Setting](https://tiddlywiki.com/#Hidden%20Settings:%5B%5BHidden%20Settings%5D%5D%20%5B%5BHidden%20Setting%3A%20Typing%20Refresh%20Delay%5D%5D) for the Typing Delay.

**Comment by pmario** [comment]
The problem is the preview mode. ... The shorter the delay, the shorter is the preview update cycle, which may cause problems for users, which use the "eagle search system" for typing.

**Comment by BurningTreeC** [comment]
I understand @pmario, should I still leave the issue open?

**Comment by pmario** [comment]
I could reproduce your issues, ... But I needed about 10 tries. So it's "hard" to reproduce and I think it's much harder to fix. ... So as long we don't get too many more issue reports, we should just remember the issue if it comes up in the GG
