### ISSUE TITLE
small screens (phones): memo-app theming/styling?

### ISSUE THREAD

**Issue by BurningTreeC** [Jermolene/TiddlyWiki5#4034]
On my phone I frequently use my pre-installed memo app and I wonder if tiddlywiki should provide a theme similar to that styling?

**Comment by BurningTreeC** [comment]
I think on small screens tiddlers need only one edit-button (the more-tiddler-actions button). The sidebar could be shown as a popup (button at the bottom). The most basic buttons should also be shown at the bottom. The padding between tiddlers should be very low

**Comment by twMat** [comment]
This proposal is much to vague to be actionable. Please close and open in one of the google groups for refinement and come back with more specific issue. (Even if it is hopeless, because of a systemic fault, we should at least *try* to not add to our impressive pile of issues.)
