### ISSUE TITLE
How to see external tiddler modification without restarting node server?

### ISSUE THREAD

**Issue by vlad-timofeev** [Jermolene/TiddlyWiki5#4039]
I'd like to be able to modify tiddlers directly from the file system using vim and see the result in the browser.

After installing this vim plugin https://tiddlywiki.com/#Editing%20Tiddlers%20with%20Vim I can confirm that `modified` field gets auto-updated, but the changes are not detected by the web application - page refresh doesn't help, only restarting the node server makes the changes be reflected in the browser.

Is there any way to detect the changes in browser without having to restart the server (reloading the page is fine to me)? Is it a bad idea in general to modify tiddlers externally like I'm trying?

**Comment by inmysocks** [comment]
I made the Bob plugin to solve this problem.

https://github.com/OokTech/TW5-Bob

I also made a executable version

https://github.com/OokTech/TW5-BobEXE

**Comment by vlad-timofeev** [comment]
@inmysocks, thank you
Can you also give a brief explanation why external modifications don't work out-of-box?

**Comment by Jermolene** [comment]
Hi @vlad-timofeev one of the reasons that it wasn't present at the beginning is that in the early days of TW5 the Node.js file watching APIs were unreliable. It's something that I'd like to add to the core but there are many pitfalls. As I think @inmysocks has discovered, to do it reliably one needs a daemon that can quit and restart the main process.

**Comment by vlad-timofeev** [comment]
Hi @Jermolene , thank you for the info
