### ISSUE TITLE
Reveal widget popup positioning problems

### ISSUE THREAD

**Issue by Jermolene** [Jermolene/TiddlyWiki5#4041]
#3486 identified the problem that dropdown menus sometimes overlap the left edge of the screen, making it impossible to scroll them into full visibility (see below).

A fix was attempted in #3491 by having the reveal widget clamp popup coordinates to ensure that they are positive.

However, there are many cases where this fix is not appropriate. In particular, if the popup is positioned within a container with its own coordinate system then a left coordinate of zero may no longer correspond to the left edge of the screen.

It is proposed to add a new attribute `positionAllowNegative` to the reveal widget that when set to “yes” would omit the clamping of popup coordinates to be non-negative.

**Comment by twMat** [comment]
I'm hoping this annoyance is part of the same problem

<img width="408" alt="Capture2" src="https://user-images.githubusercontent.com/4534056/60444321-44934e80-9c1d-11e9-8ef0-74877250ae81.png">

**Comment by Jermolene** [comment]
Hi @twMat no, that's different. See the picture in #3486. In the case you've illustrated I don't think you'd want to reposition the popup so much as scroll the viewport to bring the dropdown into view.

**Comment by twMat** [comment]
>scroll the viewport to bring the dropdown into view.

Yeah, you're right.
