### ISSUE TITLE
Feature request - Transclude Filter Operator?

### ISSUE THREAD

**Issue by AnthonyMuscio** [Jermolene/TiddlyWiki5#4042]
Folks,

If we had a filter operator transclude[] such that titles listed in a filter could be automatically transcluded in the output it could simplify coding and understanding of this basic function for new users. Ideally the parameter could name a template to use for the transclusion.

After all titles and there transclusions are a key feature of Tiddlywiki, and titles the key result of a filter so perhaps providing a transclude filter will be very useful.

Regards
Tony

**Comment by AnthonyMuscio** [comment]
PS if there was also a method to transclude fields other than text would also be helpful.

I also wonder what could be achieved with;

`{{{ [[tiddlername]transclude[template]] }}}`

**Comment by pmario** [comment]
`{{{ [[tiddlername]transclude[template]] }}}` ... try `{{tiddlername||template}}` That's existing wikitext. see:https://tiddlywiki.com/#Transclusion%20in%20WikiText

**Comment by pmario** [comment]
`{{{ [tag[mechanism]] ||TemplateTitle}}}` filtered version

**Comment by AnthonyMuscio** [comment]
Mario,

Please tell me if I am wring.
In this case `{{{ [tag[mechanism]] ||TemplateTitle}}}` it is only valid because of the `{{{ triple braces }}}` format is what is setting the template.

Is there a way for me to get the equivalent of;
```
<$list filter="[tag[mechanism]] +[transclude[TemplateTitle}]]">

</$list>

```
Regards
Tony

**Comment by pmario** [comment]
Sure, the list-widget has a [template](https://tiddlywiki.com/#ListWidget) and editTemplate parameter. 

```
<$list filter="[tag[mechanism]]" template=TemplateTitle />
```

**Comment by AnthonyMuscio** [comment]
Mario,

I think you have demonstrated that there are ways to achieve the same thing already although I still wonder if it would be good inside the filter rather than outside. 

The fact is the formatting via templates is a visual output and possibly better used as you have suggested.

I will let this issue sit for a while if anyone wants to contribute then close it if not. Thanks for your insight.

Regards
Tony

**Comment by twMat** [comment]
>If we had a filter operator transclude[] such that titles listed in a filter could be automatically transcluded in the output 

How does it differ from `get[]` ? (Excepting the template aspect.)

**Comment by Jermolene** [comment]
> If we had a filter operator transclude[] such that titles listed in a filter could be automatically transcluded in the output it could simplify coding and understanding of this basic function for new users. Ideally the parameter could name a template to use for the transclusion.

Can you show give examples of things that can't be done with the current transclude widget but that could be accomplished with a transclude filter operator?

**Comment by AnthonyMuscio** [comment]
Jeremy,

Thanks for asking. Mat and Mario's replies have shown me there are a number of ways to achieve the same thing, however if it were not a complex thing to do, even in a plugin, It could improve the readability of some code and solutions including making the possibilities more obvious. Yes these things may be achievable in other ways but they are more complex.

- Permit "one liner" solutions see below
- Placing the ability to transclude within filters puts the function right next to where we generate the titles we may wish to transclude.
- If transclude is in a filter, it can easily be altered rather than needing to structure this inside wikitext - it opens it to more flexibility. 

For example in this example the template lies within the filter
`{{{ [tags[]transclude[$:/core/ui/TagTemplate]] }}}`
`{{{ [tags[]transclude<templatename>] }}}`

Rather than here where the template lies within the wikitext, and wikitext needs to be edited to change templates
`{{{ [tags[]] ||$:/core/ui/TagTemplate}}}`

This could be used in Advanced Search > filter to actually display the content of the tiddlers searched for
`eg [tag[$:/tags/Macro]transclude<plaintexttemplate>]]`

`{{{ [prefix[Chapter]sort[]transclude[]] }}}` 
to display all chapter tiddlers in the current tiddler
or
`{{{ [prefix[Chapter]sort[]transclude[chapteredittemplate]] }}}` 

Further it would be easy to programaticaly change the template

`{{{ [prefix[Chapter]sort[]transclude<modetemplate>] }}}` 
eg: Multiple mode templates for view, edit, list, preview

- The current equivalent of the above tends to require at least three lines and a few parameters and even more if you want the filter to be changed programaticaly. There are lot more places to make a mistake and it is a higher cognitive load to learn.
- This would encorage the use of templates to format output rather than the code existing in places such as between the open and close of a list widget. Yes it has the template parameter but this is once removed from the result of the filter.
- A range of subfilters could be defined that also contains the display format within it because the transclude  and template is available to filters.

`{{{ [subtiddler<chapters-plus>] }}}`

Details below
```
\define chapterplustemplate()
<$link to=<<currentTiddler>> > {{{ [all[current]get[caption]] ~[all[current]get[title]] }}} </$link><br>
<$transclude /><br>
{{||$:/core/ui/Buttons/edit}} {{||$:/core/ui/Buttons/export-tiddler}} {{||$:/core/ui/Buttons/open-window}}
\end

\define chapters-plus() [prefix[Chapter]sort[]transclude<chapterplustemplate>]

{{{ [subtiddler<chapters-plus>] }}}
or
<<tabs "[subtiddler<chapters-plus>]" "[prefix[Chapter]sort[]first[]]" "$:/state/tab2" "tc-vertical">>
```

Regards
Tony

**Comment by twMat** [comment]
I think @AnthonyMuscio has a case. It does make sense and it illustrates something I've been thinking about; there should be filter operators for all widgets when possible. It is (1) much simpler to use and (2) it contributes to making filters a more complete language within TW. 

Specifically regarding the TranscludeWidget it is also worth noting it *has no template* attribute.

**Comment by Jermolene** [comment]
Hi @AnthonyMuscio @twMat I do not think transclusion belongs in filters. Transclusion is highly optimised within TiddlyWiki because it is so central to how it works: the need to support transclusion was one of the primary drivers of the design of the rendering system of TiddlyWiki.

Meanwhile, filters are lightweight expressions that have to be executed at high frequency. Shoehorning transclusion in there would break all the optimisations, and make for very poorly performing filters.

Further, I don't think the examples really work. For example:

```
{{{ [tags[]transclude[$:/core/ui/TagTemplate]] }}}
```

The problem here is that we have already defined what the triple braces without a template does: it transcludes each result from the filter through a default template that shows the title as a link. For your example to work, the triple brace syntax would have to instead interpret the results of the filter as the content of tiddlers.

**Comment by AnthonyMuscio** [comment]
I accept the argument against this proposal and mario pointed out effective alternatives in this case.

Mats point may remain valid, but perhaps not in this case
> here should be filter operators for all widgets when possible.

twMat do contact me if you want to know the result of my research.
