### ISSUE TITLE
proposal: sharedtags filter

### ISSUE THREAD

**Issue by BurningTreeC** [Jermolene/TiddlyWiki5#4043]
I had the idea of a filter that returns all tiddlers that share a tag with the input title if used empty like `sharedtags[]` or that share a given tag when used like `sharedtags[tag]`

**Comment by BurningTreeC** [comment]
given the importance of tags in tiddlywiki and that there are only 4 tag filter operators, this would be a great addition I think. what do you think?

**Comment by twMat** [comment]
Could you give some use cases?

**Comment by BurningTreeC** [comment]
Use case: list all tiddlers that share a tag with the currently viewed tiddler

**Comment by twMat** [comment]
Share any of the tags or all of the tags?

**Comment by BurningTreeC** [comment]
@twMat 

any of the tags

**Comment by BurningTreeC** [comment]
... or a specific tag with `sharedtags[tag]`

**Comment by twMat** [comment]
Does `tags[]tagging[]` perhaps achieve this?

**Comment by BurningTreeC** [comment]
@twMat ... yeees :smile: my bad, closing this!
