### ISSUE TITLE
stamp button: wrap selection if prefix and/or suffix fields are given

### ISSUE THREAD

**Issue by BurningTreeC** [Jermolene/TiddlyWiki5#4046]
The idea is to add a condition that looks if a stamp has a prefix or a suffix field and in that case it wraps the selection, adding the defined prefix and suffix and ignoring the text input

**Comment by BurningTreeC** [comment]
a better condition would be, that one or both of the tiddlers named like the original stamp but with a `/prefix` and /or `suffix` suffix are present. In that case it uses those tiddlers - advantage: new lines are preserved

**Comment by twMat** [comment]
>a better condition would be, that one or both of the tiddlers named like the original stamp but with a /prefix and /or suffix suffix are present. In that case it uses those tiddlers - advantage: new lines are preserved

You mean *additonal tiddlers* for that stamp with the *titles* suffixed with `/prefix` or `/suffix` ?

**Comment by BurningTreeC** [comment]
>You mean additonal tiddlers for that stamp with the titles suffixed with /prefix or /suffix ?

Yes that's what I mean. Because if fields are used, we cannot insert new lines, the fields don't accept new line characters

**Comment by BurningTreeC** [comment]
closing, as it's in the core now :)
