### ISSUE TITLE
every navigation should update "viewed-tiddler"

### ISSUE THREAD

**Issue by BurningTreeC** [Jermolene/TiddlyWiki5#4061]
I'd like to discuss how we want to update a state tiddler with the "currently viewed", respectively the last navigated tiddler

the new escapecss filter allows secure highlighting of that tiddler using its title

the keyboard shorcuts allow navigation in the story river and actions for that tiddler

this would improve usability a lot and the change wouldn't hurt a lot

**Comment by BurningTreeC** [comment]
... see https://burningtreec.github.io/TW5-navigator/ for an example how to navigate, description in the sidebar

alt-down and alt-up for navigation, alt-e for editing etc.

**Comment by pmario** [comment]
BTC have a look at: https://github.com/Jermolene/TiddlyWiki5/pull/3975 and support it. It does exactly what you need. and it fixes the existing TOC

**Comment by BurningTreeC** [comment]
@pmario , +1 for it! I can close this and #3590 in favor of your PR
