### ISSUE TITLE
tabbing into inputs should close other popups

### ISSUE THREAD

**Issue by BurningTreeC** [Jermolene/TiddlyWiki5#4076]
if we tab into an input - like from the tags input to the editor - when the input gets focus it should close all other popups (before it eventually opens its own popup)

**Comment by twMat** [comment]
dupe of #2959 ? ...in deed annoying. Ioften dont see any search results because there's apparently some popup open.

**Comment by pmario** [comment]
@twMat #2959 can be closed if PR: cancel open popups when input gets focus #4078 is merged

**Comment by twMat** [comment]
@pmario , yes if merged I'll close it, thanks.

**Comment by BurningTreeC** [comment]
@twMat @pmario - #4089 is merged which is basically #4078 , please test on the current prerelease, I believe we can close the issue

**Comment by twMat** [comment]
Thank you for this @BurningTreeC . I've closed #2959
