### ISSUE TITLE
Captions should visually replace title everywhere

### ISSUE THREAD

**Issue by twMat** [Jermolene/TiddlyWiki5#4081]
I'm unsure why captions don't simply replace the display of a title. This is particularly annoying in plugins for user facing tiddlers (that are not embedded in e.g ctrlpanel) and they have typical shadow tiddler names like `$:/plugin/Foo/gobbledegook` or even longer.

**Comment by inmysocks** [comment]
I disagree quite strongly that the caption should always replace the title. It would make working with a wiki significantly harder for me. Having some flag, either per-tiddler or global, would be a much better solution than forcing it to always be the caption.

The way I have started using to get around the problem you desccribe is to have the plugin create tiddlers with more human readable titles that transclude the shadow tiddlers.

The new.version of the wiki listing in Bob is like this, when you check the box to include it a tiddler is created with the appropriate tag and transclusion and when you unchecked the box the tiddler is removed.

**Comment by morosanuae** [comment]
@twMat I also disagree. It will be confusing for many. And for system tiddlers the title holds a lot of info about the role of each tiddler. I think the caption is more appropriate for standard tiddlers.

**Comment by pmario** [comment]
caption is a short title
subtitle is a longer title. ... It needs to be the users choice. see: my uni-link plugin. ... Which only works that way for prettylinks eg: `[[tiddler-title]]` ... aliases have a choice like this: `[[alias|?c]]``[[alias|?s]]``[[alias|?field-name]]` for caption, subtitle and any other field name.

**Comment by pmario** [comment]
above response has been edited.

**Comment by twMat** [comment]
How about a `forced-caption` field?

As is abundantly clearly in your replies, it is currently way too complicated to get an alternative title.

**Comment by pmario** [comment]
If users what to have a different tiddler title, they should use a different theme. IMO there is no need for more specially treated fields. 

see: https://wikilabs.github.io/editions/slant-01/#01-slant-01-theme

**Comment by AnthonyMuscio** [comment]
Mat

What about a plugin/macro for people who want your feature, it provides a toggle on any tiddler that has a caption field and when on it changes the format

### Tiddlertitle
subtitle

to 
### caption
Tiddlertitle in small font link and even with a copy to clipboard.
subtitle

Regards
Tony

**Comment by twMat** [comment]
Well, a main thing is that I don't want to present my plugins as "$:/plugins/TWaddle/foobellibar". Why should an end user face such monsters?

"Welcome to your new iPhone. Which media player do you want  `//&/setup$4.4/$` or `//&/setup$8.1/$` ?" Steve Jobs would have *thrown* out someone.

But OK, I guess there are more important things... closing.

**Comment by AnthonyMuscio** [comment]
Then include in your plugin a tiddler called FooBelliBar containing
`{{$:/plugins/TWaddle/foobellibar}}` now FooBelliBar is a searchable tiddler title.

Regards
Tony

**Comment by pmario** [comment]
>Then include in your plugin a tiddler called FooBelliBar containing

hmm. IMO plugins should not "pollute" the default tiddler namespace. ... eg: a plugin author decides to name a tiddler "License" ... That would be a real problem. 

-----------------

Editions can overwrite GettingStarted. ...

**Comment by AnthonyMuscio** [comment]
Mario,

I understand you are trying to maintain "standards" but rather than just say it should not be done, can you provide a solution to the requirement behind it?

How would what I suggested "pollute" the default tiddler namespace?, yes it uses the namespace but "pollute"". This is a single tiddler that provides access to an installed plugin or macro. It does use the general namespace but what are tiddler names for but to be able to access a tiddler of that name?

Presumably it is named FooBelliBar, which is unlikely to clash.

Of course a generic tiddler name like licence is foolish. Lets say we had a plugin called $:/PSaT/myplugin creating such a tiddler as "PSaT Myplugin" is close to impossible to cause a problem.

But if you want to be extremely conservative you could add to the plugins readme or configuration tab the ability to create this tiddler (if it does not already exist).

I have attempted to find a generic solution in the past and not received any support. Perhaps we could have another namespace like $://PSaT/pluginname/tiddlername such that it is still a system tiddler but the standard TiddlyWiki search resolves tiddlername (or there part there of) in effect automatically generating an alias of tiddlername in the standard namespace.

Alternatively perhaps a system tag $:/tags/unhide-system such that  a system tiddler so tagged eg $:/PSaT/pluginname/tiddlername will appear in searches for tiddlername (ideally also in lists). Or perhaps the caption is presented in the standard name space.

Without such features we instead have to "pollute" the sidebar, or the control panel etc... to make our plugin visible without users having to look for it.

Regards
Tony

**Comment by pmario** [comment]
>Presumably it is named FooBelliBar, which is unlikely to clash.

... until someone else also uses this name, because s/he doesn't know about the name clash.

As so many things in TW, plugin namespaces are just a convention, that turned out to be useful. eg: Every plugin can have tiddlers named: `readme`, `license` and other titles the are very common.

**Comment by pmario** [comment]
>Of course a generic tiddler name like licence is foolish. Lets say we had a plugin called $:/PSaT/myplugin creating such a tiddler as "PSaT Myplugin" is close to impossible to cause a problem.

There is a reason why we did use system tiddlers for the plugin namespace. ... System tiddlers are hidden for newbie uses. 

Let's say I'm an author of a TW based "sudoku" edition. ... I like what your plugin does and I want to include it. ... 

My edition gets a GettingStarted page and nothing else. So the right sidebar: Recent tab only contains GettingStarted and "PSaT Myplugin"

What do you think, what a newbie user does? ... They click "PSaT Myplugin". ... and they are linked to content, that has absolutely nothing to do with the purpose of the edition. 

The result is. **I do have a problem**. ... The only way to fix this is: remove the plugin. ... 

It's OK to add some branding to a plugin. But imo it has to be done at places, where it belongs to. -> The $:/ControlPanel

**Comment by pmario** [comment]
>Without such features we instead have to "pollute" the sidebar, or the control panel etc... to make our plugin visible without users having to look for it.

IMO the $:/ControlPanel is the right place to do this. 

You are right. The **$:/ControlPanel: Settings** tab needs some love. ... IMO that should be  a different issue.

**Comment by pmario** [comment]
>Alternatively perhaps a system tag $:/tags/unhide-system 

In the past (TW classic) using "special" tags to hide content has failed. ... The other way around has a high chance to fail too.

**Comment by pmario** [comment]
>I have attempted to find a generic solution in the past and not received any support. Perhaps we could have another namespace like $://PSaT/pluginname/tiddlername such that it is still a system tiddler but the standard TiddlyWiki search resolves tiddlername (or there part there of) in effect automatically generating an alias of tiddlername in the standard namespace.

I'll support making ALIASes a first class citizen.

**Comment by twMat** [comment]
>I'll support making ALIASes a first class citizen.

I like... but what exactly do you mean? Can I write [[foo]] and have a link to my plugin? Or is it only visually exchanging the title of my plugin tho show foo? Does it say foo in sidebar and other places?

**Comment by pmario** [comment]
I did create a new issue: #4125

**Comment by pmario** [comment]
>....Does it say foo in sidebar and other places?

It can not say "foo" in the sidebar. What if there are 2 foo's

**Comment by pmario** [comment]
>I like... but what exactly do you mean? Can I write [[foo]] and have a link to my plugin?

IMO a starting point could be, that the "alieases" field is included into the default search. ... The formatting of the link needs to be defined ... in the future.

**Comment by pmario** [comment]
>IMO a starting point could be, that the "alieases" field is included into the default search. ... The formatting of the link needs to be defined ... in the future.

After posting this, I did regret it ;) ... It shouldn't be the aliases field. ... It may be new **"keywords"** field

**Comment by twMat** [comment]
>It may be new "keywords" field

And what is *that* supposed to do then? ;-)  The name sounds like [something I made](http://searchwords.tiddlyspot.com/) to make tiddlers findable but you probably have something else in mind.

**Comment by Jermolene** [comment]
Just to add that the intention was that end users wouldn't need to directly interact with plugin tiddlers, accessing them entirely through the control panel. I believe that the best approach to @twMat's is to improve the control panel (there's a discussion somewhere else about adding a "name" field to plugins which is also relevant).

**Comment by twMat** [comment]
>I believe that the best approach to @twMat's is to improve the control panel

But, as it is, 99% of all TW plugins are not accessible via the ctrlpanel/pluginlibrary.
