### ISSUE TITLE
Order of stylesheet tiddlers in 5.1.20pre

### ISSUE THREAD

**Issue by kookma** [Jermolene/TiddlyWiki5#4082]
One expect to have the theme stylesheet tiddlers at the very begining or list of tiddlers tagged with $:/tags/Stylesheet.

This way one can override theme stylesheets and have customized css for his/her wiki!

Strangely in TW5.1.20pre, it seems theme cssa are not at top of the list and they override other plugin or user defined CSSs.

Even if you look at the 
https://tiddlywiki.com/prerelease/#%24%3A%2Fcore%2Fui%2FControlPanel%2FStylesheets

You see snowwhite and vanilla base tiddlers are at position 5 and 6.

**Comment by kookma** [comment]
@Jermolene 
 Please have a look. I downloaded the latest version! The bug still is there!

**Comment by Jermolene** [comment]
Hi @kookma I can confirm the problem. The difference can be seen in Control Panel -> Info -> Advanced -> Stylesheets. Here is the list from v5.1.19:

<img width="452" alt="image" src="https://user-images.githubusercontent.com/174761/61185975-8b3e6b00-a657-11e9-8cdb-077ff302ba81.png">

And here's the list from v5.1.20-prerelease:

<img width="444" alt="image" src="https://user-images.githubusercontent.com/174761/61185981-9c877780-a657-11e9-8271-26841450c84d.png">

I'll investigate a fix.

**Comment by pmario** [comment]
@Jermolene  5.1.19 also has a problem. vanilla/base should be the first one

**Comment by Jermolene** [comment]
> @Jermolene 5.1.19 also has a problem. vanilla/base should be the first one

Hi @pmario do you mean that v5.1.19 broke the ordering used by previous versions? Or that we've always had the wrong order for those stylesheets?

The ordering of stylesheets isn't special, it's controlled by the tag. Making some special arrangement to change the default ordering wouldn't be backwards compatible.

**Comment by pmario** [comment]
>The ordering of stylesheets isn't special, it's controlled by the tag. Making some special arrangement to change the default ordering wouldn't be backwards compatible.

It's actually save to move snowwhite as no. 2. .. I did check every element in snwowhite and it only contains definitions, that are not existent in vanilla/base. ... That's the reason, why nobody complained yet. 

So for the future, it should be safe to have SW as the second stylesheet. .... So for the future it would be possible to overwrite vanilla/base in SW!!!

**Comment by Jermolene** [comment]
I think it's too late to change the default stylesheet ordering. It's always possible to use higher specificity to override vanilla/base settings.

**Comment by kookma** [comment]
> difference can be seen in Co

Thanks Jeremy! While I manually move theme to top of the list but absolutely it needs a fix

**Comment by pmario** [comment]
I did check every definition in snowwhite and vanilla. There are no conflicts, if we change the default order.

**Comment by Jermolene** [comment]
Hi @pmario @kookma I'm sorry this is confusing. I think you're raising a separate issue from the one in the OP aren't you? I think that the issue you're talking about isn't a v5.1.20 regression? I'm only interested in fixing regressions; IF WE KEEP ON MAKING WORK FOR OURSELVES WE WILL NEVER RELEASE v5.1.20!!!

**Comment by Jermolene** [comment]
Anyhow, please can we just keep this discussion to the v5.1.20 regression -- things are bad enough without making them worse.

In particular, it turns out that the fake shadow tiddlers used by the test suite are breaking the tests, so I'm having to work on fixing them first. This is looking like a major piece of work, so please as I say, don't make things more complicated by introducing issues other than the one covered by this ticket.

**Comment by Jermolene** [comment]
To be clear, the OP is a problem with the indexing stuff. The issue you're raising appears to be absolutely nothing to do with the indexing stuff.

**Comment by kookma** [comment]
Hi @Jermolene 
Yes, you are right! For now I only like to solve the issues with css ordering!
I checked the prerelease of June 20th, 2019, the issue is still there!

-Mohammad

**Comment by Jermolene** [comment]
Hi @kookma please let me know if the new prerelease fixes the problems for you (the build will be finished in about 8 minutes).

**Comment by pmario** [comment]
@Jermolene ... Wouldn't it have been easier to add a list field to the $:/tags/Stylesheet tiddler, that contains the right order. 

Who does this change, change the filter performance improvements?

**Comment by Jermolene** [comment]
> Wouldn't it have been easier to add a list field to the $:/tags/Stylesheet tiddler, that contains the right order.

That wouldn't have been backwards compatible. This is a regression, and so needed fixing directly.

> How does this change, change the filter performance improvements?

It just means that we have to separately track indices for each of the four combinations of tiddler source. It was overlooked in the original implementation.

**Comment by kookma** [comment]
@Jermolene 
Seems it works fine! By the way I will make more experiment and inform you if the issue has been not solved!

Thank you
