### ISSUE TITLE
Make `-` distributive

### ISSUE THREAD

**Issue by twMat** [Jermolene/TiddlyWiki5#4085]
This works

`{{{ [tag[good]] -[tag[bad]] }}}`

but this does not work

`<$set name=bad filter="[tag[bad]]"> {{{ [tag[good]] -[<bad>] }}} </$set>`

i.e the `-` doesn't distribute onto a calculated list.

**Proposal**: Make `-` distributive

I stumble on this quite a lot and I believe the proposal to be the expected behaviour.

**Comment by pmario** [comment]
I think you doing it wrong: bad is a list of title names and not a subfilter. 

try `<$set name=bad filter="[tag[bad]]"> {{{ [tag[good]] -[enlist<bad>] }}} </$set>` ... Because that's what you have configured!

**Comment by pmario** [comment]
second possibility `<$set name=bad value="[tag[bad]]"> {{{ [tag[good]] -[subfilter<bad>] }}} </$set>`

**Comment by Jermolene** [comment]
Hi @twMat actually it's best to use "enlist" here; as discussed elsewhere "subfilter" won't work as expected if the list contains titles beginning with +, - or ~. Anyhow try:

```
<$set name=bad filter="[tag[bad]]"> {{{ [tag[good]] -[enlist<bad>] }}} </$set>
```

**Comment by twMat** [comment]
Thank you! 
Closing (somewhat red in my face).

**Comment by Jermolene** [comment]
@twMat don't be shy to raise tickets like this, it's still helpful in understanding how stuff gets used.

**Comment by twMat** [comment]
Thanks, that's kind of you to say. It was just a bit silly because I use `ènlist` frequently but I've hit this issue several times and always get the feeling that "oh, this ol' issue again - why didn't I ticket this already!?" but this time I did post before I realized the usual "ah, enlist!". (or I shoud say; before @pmario made me realize it)
Thanks guys.

**Comment by pmario** [comment]
If you would have posted it 3 month from now, I woudn't have had an answer that quick. .. but messing around with the toc-macros and using "set filter" quite a bit, made me aware of the "issue in thinking" :)
