### ISSUE TITLE
hidden="true" ----> hidden

### ISSUE THREAD

**Issue by twMat** [Jermolene/TiddlyWiki5#4092]
There is a lot of `hidden="true"`. Would it make sense to change this into merely `hidden` which I believe has the exact same result, for space optimization?

![image](https://user-images.githubusercontent.com/4534056/61087823-02e17f80-a437-11e9-8a18-95a158abbadc.png)

**Comment by pmario** [comment]
There is only 1 generic type of functions in the core, that set DOM attributes. All of them have a `name` and a `value`. 

There are a several DOM elements like "hidden", which have an effect, only being present. The value is ignored by the browser. ... We would need to modify a lot of different functions, to deal with special cases, which would make the code more complex. 

Looking at the reveal.js code the best we can achieve is: `hidden=""` without messing with really deep core code ... I don't see real savings here.

**Comment by pmario** [comment]
IMO `hidden=""` is more confusing then `hidden="true"` even if `hidden="false"` is still hidden.

**Comment by twMat** [comment]
>There are a several DOM elements like "hidden", which have an effect, only being present. The value is ignored by the browser.

(I thought the that since `<div hidden>foo</div>` does hide it meant that the browser does not ignore it?)

Anyway, I didn't expect any particular savings but didn't know so it was worth mentioning. Thanks for replying.
