### ISSUE TITLE
escape to clear input fields in edittemplate

### ISSUE THREAD

**Issue by BurningTreeC** [Jermolene/TiddlyWiki5#4097]
Hi there,

I'd like to discuss if we can add the keyboard shortcut `escape` to the tags, type and fields inputs of the EditTemplate and the search input in the sidebar to clear the corresponding input field

In the edittemplates it should do two things, first clear the input if it's not empty and cancel editing the tiddler if it's empty

**Comment by pmario** [comment]
I think, that's not the purpose of the "ESC" button. It is used to "undo" an action, that you started but now you don't want to continue, without changing anything. 

We have 2 keys that delete content. "Backspace" and "Delete"
A workflow the overwrites marked content: Ctrl-A  select all text ... Start typing will overwrite it. 

`Ctrl-A, Backspace` will delete the input box. 
`Ctrl-A Del` will do the same thing

So I can see a shortcut like `Ctrl-Backspace` which removes the last word. Is **browser default** in edit-text. 

`CTRL-Del` does nothing at the moment. ... So this could be a candidate.

**Comment by BurningTreeC** [comment]
@pmario - I got confused that chrome-like browsers do delete the input content when pressing `escape` and firefox does not

**Comment by pmario** [comment]
>I got confused that chrome-like browsers do delete the input content when pressing 'escape'  and firefox does not

Deleting content with ESC. I'd consider this a fatal bug.

**Comment by BurningTreeC** [comment]
ok then, closing
