### ISSUE TITLE
Remove warning for illegal tiddler titles

### ISSUE THREAD

**Issue by Jermolene** [Jermolene/TiddlyWiki5#4107]
It is proposed to get rid of the warning message about illegal characters in tiddler titles because:

1. The message dated from a time when key core features didn't work properly when some of those characters were used in tiddler titles (e.g. the TOC). Now that those features are fixed the only problems are with custom wikitext, and we shouldn't be trying to teach how to write wikitext in a warning message in the edit template
2. Users either don't read or misunderstand the message

See the discussion here for background: https://github.com/Jermolene/TiddlyWiki5/issues/4084#issuecomment-511138477

<img width="650" alt="image" src="https://user-images.githubusercontent.com/174761/61185869-03a42c80-a656-11e9-9997-00f2f8e653a1.png">

**Comment by saqimtiaz** [comment]
In light of the recent conversation at #4850, this can be closed.

**Comment by saqimtiaz** [comment]
@Jermolene do we still need this in light of the recent discussion at #4850?

**Comment by Jermolene** [comment]
Thanks @saqimtiaz there was indeed resounding support for keeping the warning
