### ISSUE TITLE
Attempting save with faulty field name should interrupt the save

### ISSUE THREAD

**Issue by twMat** [Jermolene/TiddlyWiki5#4114]
If attempting to save a tid containing a faulty field name, e.g "foo,bar", you get a popup warning - but then the tiddler is actually saved, and the field attempt is just erased.

**Proposal**: Clicking OK on the warning should interrupt the save, leaving the tiddler in edit mode and untouched, i.e with the faulty field still in place for correction.

**Comment by pmario** [comment]
@twMat -- I think this one can be closed, since there should be no "faulty" field names anymore. [v5.2.0](https://tiddlywiki.com/#Release%205.2.0) introduced "unrestricted" field names

**Comment by twMat** [comment]
@pmario - thanx amigo.
