### ISSUE TITLE
regression with "bad" titles

### ISSUE THREAD

**Issue by BurningTreeC** [Jermolene/TiddlyWiki5#4116]
In 5.1.19 I can create and edit a Tiddler like `!!!This {[] /// "" Is !!! a bad Title ′′¹^12¹³¼½¬{ , right ?? !!!!` without problems...

In 5.1.20 such a Tiddler causes the page to become unresponsive when trying to edit it

**Comment by BurningTreeC** [comment]
Edit: inreactive = unresponsive

**Comment by twMat** [comment]
Confirmed. Chrome Win10

**Comment by morosanuae** [comment]
@Jermolene isn't this also a regression that needs to be fixed for the v5.1.20?

**Comment by pmario** [comment]
@Jermolene ... the new tag-indexing ?? just a guess.

**Comment by Jermolene** [comment]
This is actually a problem with the contribution banner, specifically this line:

https://github.com/Jermolene/TiddlyWiki5/blob/master/editions/tw5.com/tiddlers/system/ContributionBanner.tid#L14
