### ISSUE TITLE
Revamp of adding and searching for tags in TW5

### ISSUE THREAD

**Issue by giffmex** [Jermolene/TiddlyWiki5#412]
I have closed three issues I created about tags and am opening this one to combine them, and add a couple of tweaks. I really think this is an important change that will make TiddlyWiki much more efficient for users. There are three parts to this proposed revamp.

ONE: The tags editor in edittemplate should narrow searches strictly by the name of the tag only, and not include other tags found in tiddlers where the tag being entered is mentioned somewhere. When I type specific characters in the tag editor, it is because I want to _that_ tag, not some related tag, and the options given in the dropdown should continue to narrow as I type each additional character. The current dropdown does not do that. Let me give an example. Say I create a tag 'World'. Then I create tiddlers 'Asia' 'Britain' and 'Cambodia'. Then I tag other tiddlers Asia, Britain and Cambodia. Since the tiddlers 'Asia', 'Britain' and 'Cambodia' are tagged 'World' but are now also tags, this means that whenever I want to add the 'World' tag to a new tiddler, the option 'World' is now fourth on the list. As I add more that come alphabetically before 'World', it will continue to be pushed further and further down the list, forcing me to scroll down to it, usually off the screen. But filtered lists like this should zero in on the target as one continues to type.

TWO: Tag pill CSS should be removed from the dropdown list in the tags editor, so that the tag names appear as simple links. This is for three reasons:
a. Removing the tag pill around the tag name will reduce the line height for each tag name by about half, meaning that twice as many tag names will be visible in the same amount of vertical monitor space.
b. The list will be more instantly readable.
c. I have a TW5 with numerous tags, and the tag adding is taking longer and longer. I suspect it is because the dropdown list needs to wrap the pill CSS around every single tag name of an ever expanding list of tags.

Don't think I have no love for the tag pills. I actually like them. They add an enjoyable visual element to TW5. But I think they are most appropriate for displaying the tags of the present tiddler, both in viewtemplate and edittemplate, and are not really appropriate for dropdown lists of tags.

THREE: Finally, I think a tab in $:/AdvancedSearch, that searches for tags in the way described above (filtering by tag names only, displayed as regular links to dropdown menus rather than tag pill button CSS being applied) would be an invaluable addition to $:/AdvancedSearch. Going to the More tab (when it's not hidden by search results), then going to the tags tab, then scrolling to the tag, then choosing from a dropdown, is a laborious way of finding tiddlers with a certain tag. Much easier to open advanced search and do a filtered search for the tag.

**Comment by giffmex** [comment]
I think I use the List-search plugin for the things I wanted from this issue. And no one has done anything about it since 2014. So I am closing it.

**Comment by pmario** [comment]
If you create a tiddler `myTagDropdownStyles `and tag it `$:/tags/Stylesheet` with this content 

```
.tc-block-dropdown a { display: block; padding: 1px 14px; }
```

It removes the padding around the A element. So the whole thing is much more compact. The firsr `1px` value is responsible. 

I didn't test it, if there are side effects with other lists. ... So some more testing will need to be done.

**Comment by giffmex** [comment]
Thanks Mario!
