### ISSUE TITLE
@5.1.20 - Image as bg works in .19 but not .20

### ISSUE THREAD

**Issue by twMat** [Jermolene/TiddlyWiki5#4124]
The example to set a local image as background 

[works in 5.1.19](https://tiddlywiki.com/#datauri%20Macro%20(Examples)) 

but [not in 5.1.20](https://tiddlywiki.com/prerelease/#datauri%20Macro%20(Examples))

**Comment by BurningTreeC** [comment]
Hi @twMat ... both examples work for me on a recent FireFox

**Comment by morosanuae** [comment]
@twMat both work for me too (latest Firefox).

**Comment by twMat** [comment]
Hupp??? Now it works for me too? I have no idea... :-/ .... well, good it works :-)
