### ISSUE TITLE
LinkWidget - add label param

### ISSUE THREAD

**Issue by twMat** [Jermolene/TiddlyWiki5#4126]
With the introduction of the short (and wonderful) LinkWidget syntax, where `<$link/>` gives a link to current tiddler, comes need for a *label* parameter. Currently one has to resort to the old verbose link syntax to get this.

A typical use case would probably be `<$link label={{!!caption}}/>`

**Comment by pmario** [comment]
https://tiddlywiki.com/prerelease/#LinkWidget You may use the existing "tooltip" parmeter.

**Comment by pmario** [comment]
I see. It can be done with a macro similar to my [uni-link](https://wikilabs.github.io/editions/uni-link/#%24%3A%2Fplugins%2Fwikilabs%2Funi-link%2Funi-link-macro) macro. ... Which can also be used with a macro call if you want. ...

**Comment by twMat** [comment]
Is a common label parameter not appropriate? It seems like a very reasonable thing. It is the equivalent to prettylinking like so `[[foo|bar]]`

**Comment by pmario** [comment]
Ah ok. ... I think that should be done. It may make my code simpler too. ... maybe

**Comment by pmario** [comment]
It he "label" parameter is used but empty, it needs to have a `label-default` setting. if label-default is missing the tiddler title needs to be used.

**Comment by Jermolene** [comment]
Hi @twMat we do have precedents for widgets providing default content if they are empty -- for example, the list widget treats `<$list filter=x/>` or `<$list filter=x></$list>` as if they were written `<$list filter=x><div><$link to=<<currentTiddler>><$text text=<<currentTiddler>>/></div></$list>`.

So, we could indeed make `<$link>` behave in the same way. Indeed it would work even if the `to` attribute were specified, so `<$link to="foo"/>` would also be transformed into `<$link to="foo"><$text text="foo"/></$link>`.

**Comment by AnthonyMuscio** [comment]
Yes please Jeremy!

> So, we could indeed make <$link> behave in the same way. Indeed it would work even if the to attribute were specified, so <$link to="foo"/> would also be transformed into <$link to="foo"><$text text="foo"/></$link>.
I am always doing this to stop camel case interfering with link titles. eg "Mr McDuffy" This is painfully necessary when you do not know if users will use camel-case for legitimate reasons in a title or field.

In TWC (via a plugin) there was a way to override the label displayed independently of the way is was displayed. An example someone may want to do for examples in psudocode

```
<$lable "Related Tiddlers">
<<tag "$:/longandunfriendlysystemtiddler">>
</$lable>
```
Would display a tagpill for $:/longandunfriendlysystemtiddler as "Related Tiddlers"

I have no idea of the technical feasibility but I expect there may be a way in html/the parsing engine.

An alternative may be to have an overriding "template"

Regards
Tony

**Comment by pmario** [comment]
I think the OP is more like prettylink handling.

`[[Displayed Link Title|Tiddler Title]]`

is

`<$link to="Tiddler Title" label="Displayed Link Title"/>`

**Comment by pmario** [comment]
```
<$label "Related Tiddlers">
<<tag "$:/longandunfriendlysystemtiddler">>
</$label>
```

IMO not needed, it's already there. 

@AnthonyMuscio  ... The [$:/core/macros/tag](https://tiddlywiki.com/#%24%3A%2Fcore%2Fmacros%2Ftag) uses  [$:/core/ui/TagTemplate](https://tiddlywiki.com/#%24%3A%2Fcore%2Fui%2FTagTemplate) which uses [$:/core/ui/ListItemTemplate](https://tiddlywiki.com/#%24%3A%2Fcore%2Fui%2FListItemTemplate)

So if you change the last one, all your problems with custom labels a probably gone. .. There may be some side effects, which should be merged back into the core, once they are fixed.

**Comment by Jermolene** [comment]
> I think the OP is more like prettylink handling.

> `[[Displayed Link Title|Tiddler Title]]`

> is

> `<$link to="Tiddler Title" label="Displayed Link Title"/>`

I don't think that the latter is better than `<$link to="Tiddler Title">Displayed Link Title</$link>`.

Bear in mind that widgets are not the place to pursue brevity: they are for consistency, flexibility and compatibility with HTML. We can arrange sensible defaults to make them easier to use, but we should avoid introducing inconsistencies and special cases. The right place to pursue brevity is at the wikitext or macro layer.

For example, `[[]]]` and `[[|blah]]` in wikitext both currently generate a blank link (invisible visually, but still present in the DOM), which is not at all useful. We could propose some alternative behaviour for those constructions. For example, `[[]]` could make a link to the current tiddler, labelled with the title.  I'm not 100% that it's worth the complexity, but it's the best way to pursue brevity.

**Comment by AnthonyMuscio** [comment]
Mat,

could you posibly spell out you requirement and use cases a little further?

Other than brevity or consistency accross widgets I think there are existing nethods. There is also an opportunity to achive improved handling by way of the tiddlers mario pointed out. Perhaps even eventualy a change to the standard distribution. It would help if your requirement and use cases had some more details.

Thanks tony

**Comment by twMat** [comment]
I must embarrassedly confess that I disregarded `<$link>label</$link>` when I proposed this. IMO this is sufficient instead of `<$link to=label/>`. I'm closing this issue.

Some other potentially interesting ideas have come up so feel free to pursue these in new threads.
