### ISSUE TITLE
Add new "then" and "else" operators for replacing values

### ISSUE THREAD

**Issue by Jermolene** [Jermolene/TiddlyWiki5#4147]
During discussions in #3763 and more recently #4142 I proposed the introduction of a new operator that replaces any input titles with a constant. I called it `as` in the original proposal, but now prefer `then`.

It's useful because in filters we often use an empty list to represent boolean "false" and a list with at least one entry to represent "true". When used with the list widget we generally don't care about the actual value of the entry in the list. However, when using the result of a filter in other ways it can be useful to use a fixed value to represent "true".

A simple use case is to add a class `tc-tiddler-is-missing` to a DIV if the current tiddler is missing:

```
<div class={{{ [<currentTiddler>is[missing]then[tc-tiddler-is-missing]] }}}>
...
</div>
```

The logic unfolds as:

1. `[<currentTiddler>` returns the current tiddler
2. if it is missing, `is[missing]` returns the current tiddler, otherwise it returns an empty list (ie nothing)
3. if `then[tc-tiddler-is-missing]]` receives a tiddler title then it is replaced with the string `tc-tiddler-is-missing`. Otherwise, the result is an empty list

UPDATE

An `else` operator would also be useful: if the input is an empty list then it is replaced with a constant; if the input is a non-empty list then it would just be passed through. So, for example, to apply a default when retrieving a field:

```
[<currentTiddler>get[text]else[The tiddler or field was missing]]
```

**Comment by pmario** [comment]
Does it allow `then<var>, then{var}` ... That would be really powerfull.

**Comment by pmario** [comment]
edited the last reply

**Comment by Jermolene** [comment]
Hi @pmario 

> Does it allow `then<var>, then{text-reference}` ... That would be really powerfull.

Yes, that works; the operand is the replacement value and it can be computed in the usual ways.

**Comment by Jermolene** [comment]
I think it also makes sense to add a companion "else" operator, I'll update the OP.

**Comment by pmario** [comment]
remark: Our filter syntax is a complete DSL on its own :)

**Comment by Jermolene** [comment]
And as @joearms pointed out, all done with monads :)
