### ISSUE TITLE
FF: Reordering inside a tag shows many dropzones

### ISSUE THREAD

**Issue by twMat** [Jermolene/TiddlyWiki5#4151]
I note a difference between Chrome and FF when doing the following, and IMO the FF behaviour is not as it should be. 

Using FF, go to tw.com, open any tiddler tagged HelloThere.
Click the HelloThere tag, grab the lowermost title and drag it upwards.
This creates multiple green-dashed dropzones when there probably only should be one, like in Chrome.
Also, dragging downwards again removes the dropzones... unless you move downwards fast in which case only some disappear.

**Comment by BurningTreeC** [comment]
Hi @twMat , that should be fixed on the current Prerelease

**Comment by twMat** [comment]
Ah, you're right! Thanx!
