### ISSUE TITLE
Size of svg icon in TW, a documentation macro

### ISSUE THREAD

**Issue by kookma** [Jermolene/TiddlyWiki5#4153]
The svg icons appear in TW documentation tiddlers are very big and does not look consistent with font size and seems a little annoying!

See for example see: (https://tiddlywiki.com/prerelease/#Using%20Stamp)

One simple solution is a documentation macro to solve this

CSS:

```
.kk-doc svg{
width: 1.2em;
height: 1.2em;
vertical-align: middle;}

```
Macro
```
\define doc-svg(tiddler:"", color:"")
<span class="kk-doc" style="fill:$color$;"><$transclude tiddler=<<__tiddler__>> /></span>
\end
``` 

A working version is available here https://github.com/kookma/TW-Trashbin
See the index.html

**Comment by Jermolene** [comment]
Hi @kookma I concur that the present arrangement looks klunky. As you note, a good solution would require a bit of CSS and an update to the markup used to incorporate the images in the text.

**Comment by kookma** [comment]
Hi @Jermolene 
 I hope you find free time to do this minor adjustments! 
TW really deserves great an nice looking documentation tiddlers.

**Comment by Jermolene** [comment]
Hi @kookma it does indeed look a lot better. Here's an example before/after shot:

<img width="503" alt="image" src="https://user-images.githubusercontent.com/174761/66718242-8b2a4480-edd9-11e9-881b-2a306194609c.png">
<img width="441" alt="image" src="https://user-images.githubusercontent.com/174761/66718240-81084600-edd9-11e9-9be5-309eea3477b1.png">
