### ISSUE TITLE
Delete folded state when delete/rename tid

### ISSUE THREAD

**Issue by twMat** [Jermolene/TiddlyWiki5#4166]
Not a biggie but still. To reproduce:

1. Fold a tiddler.
2. Delete it via view mode menu - OR - open and change its title and save.
3. Create a new tiddler with the original title.
--> the new tiddler is in the folded state which is confusing.

I guess the state tiddler should be deleted from the above actions.

Otherwise I think it would be sufficient with a clearer indicator that a tiddler is folded, which has come up elsewhere anyway. If this route is taken, I have a particular css proposal for this - basically a gradient beneath the title bar, which could also be used under sticky titles.

**Comment by Jermolene** [comment]
>  a clearer indicator that a tiddler is folded

I think that might be the best way to approach this. (The other alternative, of deleting related state tiddlers when deleting a tiddler, seems clunky and error prone).

We do already have an optional indicator/button for folded tiddlers -- it's the bottom option under the "tools" tab of the tiddler info panel:

<img width="737" alt="image" src="https://user-images.githubusercontent.com/174761/62627959-4dfd8e00-b922-11e9-8225-72f2811d5269.png">
<img width="731" alt="image" src="https://user-images.githubusercontent.com/174761/62628052-7be2d280-b922-11e9-9eb5-5a31d7aa7d3e.png">

So, one option would be to stop making that indicator optional, and always display it when a tiddler is folded. But I don't think we should display the "fold" option in the left margin of the tiddler by default, so we might still need to make that optional.

We could easily add a CSS class for folded tiddlers, but it's not clear how they could be styled that would suggest to users that they were folded.

**Comment by pmario** [comment]
Yea, we should "force" the "unfold" button, if a tiddler is folded.

**Comment by twMat** [comment]
>So, one option would be to stop making that indicator optional, and always display it when a tiddler is folded. But I don't think we should display the "fold" option in the left margin of the tiddler by default, so we might still need to make that optional.

+1 for all statements above.

>We could easily add a CSS class for folded tiddlers, but it's not clear how they could be styled that would suggest to users that they were folded.

What do you mean? Why not like in the iamges? If that is not enough or is confusing, then one could add css like `:hover:after {content:"Tiddler is folded"}`

**Comment by Jermolene** [comment]
> What do you mean?

I mean that it would be easy to add a CSS class that made it possible to style folded tiddlers differently from unfolded ones.

> Why not like in the iamges?

The images show an optional feature we already have called "fold bars". We could make it so that the "unfold" bar is shown even if the fold bars are not enabled.

> If that is not enough or is confusing, then one could add css like :hover:after {content:"Tiddler is folded"}

I don't think a textual message like that will help users who don't know what "folded" means, nor where to go to switch it off again. Any meaningful indicator that the tiddler is folded should be actionable, so that it can be unfolded again.

**Comment by twMat** [comment]
Anyway, I think your previous idea would solve everything without any css:

>stop making that indicator optional, and always display it when a tiddler is folded

I.e (as i interpret this) force move the "unfold tiddler" button so it is visible in the tiddler toolbar as soon as at tiddler is folded. I imagine this is super simple **programmatically** also (just set the `$:/config/ViewToolbarButtons/Visibility/` state tiddler when clicking fold but somehow also retain the previous state to reset when unfold).

P.S
The spellcheck suggest "programmatically" to be: "pro grammatically", "pro-grammatically" or "programmatic ally". Assuming we keep it grammatical, you can do this as a pro but if you want me to do it I would, in deed, need an ally. Browser AI is getting scary!!!

**Comment by Jermolene** [comment]
> I.e (as i interpret this) force move the "unfold tiddler" button so it is visible in the tiddler toolbar as soon as at tiddler is folded

Not quite. In the tiddler info "tools" tab you'll see that there are two entirely separate buttons concerned with folding/unfolding. One is the usual fold/unfold buttons that appear in the tiddler toolbar. The other is a special arrangement of custom buttons that appear in the tiddler itself (as per my illustrations above).

The proposal I made is that if a tiddler has been folded through either button then always display the custom unfold button. (ie the unfold button illustrated above, not the one in the toolbar).

**Comment by twMat** [comment]
Ah, sorry, yes you did mention it concerned that thing via the info button.

Sure, force adding the big special horizontal button would do the trick. 

(Side note: IMO the whole idea with those large fold/unfold areas is not so elegant and basically repeats what what the standard fold/unfold button already does. Instead the fold/unfold button should be split into two: fold and unfold, and the user can decide which one/s he wants permanently visible - but the *unfold* is only visible *if* the tiddler is folded and if the *fold* button is only visible if unfolded.)

**Comment by pmario** [comment]
@twMat -- IMO can be closed.

The "forced" unfold button, which is independent of the visibility setting was introduced some time ago.
