### ISSUE TITLE
Tag Usability

### ISSUE THREAD

**Issue by jmholla** [Jermolene/TiddlyWiki5#4171]
When you are entering tags in a new post and you tab into the post contents field, the dropdown stays up. It should go away as you can't read what you're typing anymore.

**Comment by twMat** [comment]
Are you saying this for the latest release from today - 5.1.20? I don't get this problem.

**Comment by jmholla** [comment]
My entire hard drive corrupted not too long after I posted this, and I never got a chance to look into this. May as well close this as I won't have it or TiddlyWiki back up anytime soon.
