### ISSUE TITLE
authentication gzip

### ISSUE THREAD

**Issue by dev4light** [Jermolene/TiddlyWiki5#4176]
When basic authentication is enabled, for some reason gzip compression doesn't apply anymore.

Would using header authentication fix this?
Is there any tutorial on how to use header authentication with TiddlyWiki?

**Comment by Jermolene** [comment]
Thanks @dev4light 

> When basic authentication is enabled, for some reason gzip compression doesn't apply anymore.

Basic authentication should not affect gzip compression. Conceivably your browser isn't passing the accept header for GZIP compression; if you're familiar with HTTP you may find it useful to use the "debug-level" parameter to the listen command to see the headers actually been received by TW.

We currently only apply gzip compression to the `/index.html` route; other responses from the server are not compressed.

> Would using header authentication fix this?

No, I don't think so. Header authentication is useful when there's an upstream server handling authentication, and it can add a header to pass the username on to TiddlyWiki.

> Is there any tutorial on how to use header authentication with TiddlyWiki?

We do not have any such tutorials at the moment. The TW5 end is just a matter of telling it in which header to look for the username. All the complexity is in setting up the authentication server, which of course depends whether one is using IIS, Apache, nginx etc.

**Comment by dev4light** [comment]
Thanks @Jermolene!
You're right, I just re-enabled basic auth and it gzips correctly even with the password. Have no idea why I had the issue and dissapeared when I didn't pass username/password to --listen.

Would it then be possible to use something like passport.js with TiddlyWiki's header authentication?

**Comment by Jermolene** [comment]
Great, thanks @dev4light.

> Would it then be possible to use something like passport.js with TiddlyWiki's header authentication?

That would be an interesting project, and should in principle be straightforward....

**Comment by dev4light** [comment]
Btw, I discovered the issue with no gzip. It only happens on TiddlyWiki 5.1.19. 
On 5.1.20, something fixes it. But I'm using <tagfilter> plugin and it has a bug with 5.1.20, clicking the filter button makes the tag suggestions popup to immediately hide itself(after 100ms or so).

**Comment by dev4light** [comment]
I'll close this issue and open another on-topic one for 5.1.20 bug with tagfilter.

**Comment by dev4light** [comment]
Opened #4177

**Comment by brizzbane** [comment]
> Thanks @dev4light
> 
> > When basic authentication is enabled, for some reason gzip compression doesn't apply anymore.
> 
> Basic authentication should not affect gzip compression. Conceivably your browser isn't passing the accept header for GZIP compression; if you're familiar with HTTP you may find it useful to use the "debug-level" parameter to the listen command to see the headers actually been received by TW.
> 
> We currently only apply gzip compression to the `/index.html` route; other responses from the server are not compressed.
> 
> > Would using header authentication fix this?
> 
> No, I don't think so. Header authentication is useful when there's an upstream server handling authentication, and it can add a header to pass the username on to TiddlyWiki.
> 
> > Is there any tutorial on how to use header authentication with TiddlyWiki?
> 
> We do not have any such tutorials at the moment. The TW5 end is just a matter of telling it in which header to look for the username. All the complexity is in setting up the authentication server, which of course depends whether one is using IIS, Apache, nginx etc.

How do you tell TW5 what header to look for? ....I've been looking all over and can't find anything about it. 

--authenticated-user-header

does not seem to be it...

Appreciate the help.

**Comment by Jermolene** [comment]
Hi @brizzbane the docs are here:

https://tiddlywiki.com/#WebServer%20Header%20Authentication:%5B%5BWebServer%20Parameters%5D%5D%20%5B%5BWebServer%20Header%20Authentication%5D%5D%20%5B%5BWebServer%20Parameter%3A%20authenticated-user-header%5D%5D

It would be used something like this:

```
--listen authenticated-user-header=my-header-name
```

**Comment by brizzbane** [comment]
> Hi @brizzbane the docs are here:
> 
> https://tiddlywiki.com/#WebServer%20Header%20Authentication:%5B%5BWebServer%20Parameters%5D%5D%20%5B%5BWebServer%20Header%20Authentication%5D%5D%20%5B%5BWebServer%20Parameter%3A%20authenticated-user-header%5D%5D
> 
> It would be used something like this:
> 
> ```
> --listen authenticated-user-header=my-header-name
> ```

I did come across that....but really struggling to figure out how to make nginx work with it.  If you have the time, and are familiar with nginx, can you tell me what would be wrong with this?  (I don't see any "X-User" header passed in Chrome developer console--but I don't know if I should be anyways?)


```
    server {
        listen 80 default_server; 
        location / {
  #auth_basic "Restricted";
  #auth_basic_user_file /var/www/.htpasswd;
  sendfile off;
  proxy_pass         http://127.0.0.1:8080;
  proxy_set_header        X-User             'brizz';
}
}
```

TiddlyWiki run as follows:

`node ./tiddlywiki.js TradeWiki --listen authenticated-user-header=X-User`

and visit site, by going to:

`http://127.0.0.1
`

Right now I'm just trying to make sure the header gets passed.  So that is why I comment out #auth stuff, and just manually set X-User.

I'm guessing my issue is with nginx?.  I've tried placing headers before/after proxy_pass ...and other methods of setting header that I have come across, but I have yet to see anything 'work' (and that to me would mean that when I click on settings--the 'Username' for edits would be 'brizz').
