### ISSUE TITLE
EditTextWidget focus causes popups to close

### ISSUE THREAD

**Issue by dev4light** [Jermolene/TiddlyWiki5#4177]
If $edit-text widget has focus=true and is placed inside of a popup(i.e. the tag-filter macro - http://tagfilter.tiddlyspot.com/#Start), when popup opens the focus event causes the popup to automatically close within few milliseconds.

Reproducibility: 
- starting with TiddlyWiki 5.1.20
- 5.1.19 doesn't have the bug

Cause:
- in 5.1.20, this commit causes the issue: https://github.com/Jermolene/TiddlyWiki5/commit/8aa6427d6728ddfb7365bd51a1c136dc7f54395b#diff-2788afb61c207f85b558b296f643ce5e

**Comment by BurningTreeC** [comment]
@dev4light , yes that's the commit that breaks the popup. The popup would need the class `tc-popup-keep` so that it doesn't get cancelled when the input field gets focus

**Comment by saqimtiaz** [comment]
@Jermolene @dev4light this issue can be closed.

**Comment by Jermolene** [comment]
Thanks @saqimtiaz
