### ISSUE TITLE
TypeError: $tw.utils.saveTiddlerToFile is not a function

### ISSUE THREAD

**Issue by paulojeronimo** [Jermolene/TiddlyWiki5#4187]
Hi! After upgrading [my wiki](https://github.com/paulojeronimo/wiki) TiddlyWiki Node.js from 5.1.19 to version 5.1.20 I'm receiving this error when I try to build it:

```
$ tiddlywiki wiki --build index
 syncer-server-filesystem: Dispatching 'save' task: $:/StoryList
$:/plugins/tiddlywiki/filesystem/filesystemadaptor.js:74
		$tw.utils.saveTiddlerToFile(tiddler,fileInfo,callback);
		          ^

TypeError: $tw.utils.saveTiddlerToFile is not a function
    at $:/plugins/tiddlywiki/filesystem/filesystemadaptor.js:74:13
    at FileSystemAdaptor.getTiddlerFileInfo ($:/plugins/tiddlywiki/filesystem/filesystemadaptor.js:61:2)
    at FileSystemAdaptor.saveTiddler ($:/plugins/tiddlywiki/filesystem/filesystemadaptor.js:70:7)
    at Syncer.dispatchTask ($:/core/modules/syncer.js:494:21)
    at Syncer.processTaskQueue ($:/core/modules/syncer.js:437:9)
    at Timeout._onTimeout ($:/core/modules/syncer.js:416:26)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
```

Any tip to solve this? Thanks!

**Comment by Jermolene** [comment]
Hi @paulojeronimo the error shows that the filesystem adaptor plugin has been unable to invoke a new core function that was added in v5.1.20. That suggests that one or more shadow tiddlers has been overridden with the text of an earlier version. This can happen if, for example, one attempts to edit a shadow tiddler.

If you're building a standalone HTML file wiki then you don't actually need the filesystem adaptor plugin, so you can edit the `tiddlywiki.info` file of your wiki to remove references to it. Perhaps you can show the current content of the file?

If you manage to get it building again, you can investigate the overridden shadow tiddlers by opening the advanced search tiddler, choosing the "Filter" tab and then typing the following filter:

```
[[$:/core]plugintiddlers[]is[tiddler]type[application/javascript]] 
```

You'll see a list of any JS modules from the core that have been overwritten. If you see any tiddlers listed, open them and then delete them to restore the underlying shadow tiddler.

**Comment by paulojeronimo** [comment]
Thanks @Jermolene ! The [removal of "tiddlywiki/filesystem" from tiddlywiki.info](https://github.com/paulojeronimo/wiki/commit/a7acc8b1a46d9f33afebd9f31fb3858edae0452b#diff-d678b04755d06d401b1b9da59f5eb495) worked for me! Thanks for your support and for creating this fantastic tool!
