### ISSUE TITLE
RSOE action-deletefield missing tid

### ISSUE THREAD

**Issue by twMat** [Jermolene/TiddlyWiki5#4188]
[Minimalish Test Case](http://rsoe4187.tiddlyspot.com/#DataTiddler%2FViewTemplate:Demo%20DataTiddler%2FViewTemplate%20GettingStarted)

Clicking the delete icon Demo is supposed to delete the displayed field but gives

Uncaught TypeError: Cannot read property 'fields' of undefined

I'm guessing it is caused from `<$action-deletefield $field={{!!title}}/>` is missing `tiddler` argument and therefore assumes a title that, because of the context, doesn't exist.

**Comment by pmario** [comment]
xasdf tiddler doesn't exist. it uses currentTiddler. the missing parameter imo is no problem

**Comment by twMat** [comment]
Yes, exactly, the assumed tiddler doesn't exist causing the widget to be in a "contextless environment" and with no default title to fall back on.

(So no misunderstanding: I'm not asking for help, I'm just alerting about a situation causing RSOE)

**Comment by pmario** [comment]
ah ok. .. that's a bug

**Comment by Jermolene** [comment]
Thanks @twMat
