### ISSUE TITLE
Sidebar not expandable/collapseable

### ISSUE THREAD

**Issue by ascherer** [Jermolene/TiddlyWiki5#4193]
After upgrading a TiddlyWiki from 5.1.14 to 5.1.20, I can no longer expand/collapse the "sidebar" via the button(s) on the top-right of the page. Instead of a single `«` resp. `»` button, it appears that _both_ buttons are superimposed and block each other; see screenshots from Opera 63.0.3368.43 and Konqueror 5.0.97, both on Kubuntu 18.04 LTS (also with Tor Browser 8.5.4; without additional screenshot). The same problem occurs with AndTidWiki 1.0.0, where the sidebar is expanded and cannot be collapsed at this time.

![Screenshot_20190823_123300](https://user-images.githubusercontent.com/51143/63587163-7a144280-c5a3-11e9-8b1d-a9cd2ac5baf6.png)
![Screenshot_20190823_123336](https://user-images.githubusercontent.com/51143/63587165-7aacd900-c5a3-11e9-944c-ae55faab9186.png)

**Comment by Jermolene** [comment]
Hi @ascherer one possibility is that your wiki contains a customisation to a shadow tiddler that doesn't work in the new version.

Try opening the advanced search "filter" tab and select the canned search "Overridden shadow tiddlers" from the dropdown:

<img width="993" alt="image" src="https://user-images.githubusercontent.com/174761/63596553-6ec91300-c5b3-11e9-93f6-0535ba78c103.png">

Please copy and paste the results.

Also, please try the filter `[all[shadows+tiddlers]tag[$:/tags/TopRightBar]]` and post the results.

**Comment by ascherer** [comment]
[Typed on PC from Mobile screen:]

# `[is[shadow]]`
3 hIts
```
$:/DefaultTiddlers ==> [list[$:/StoryList]]
$:/language ==> $:/languages/de-DE
$:/temp/advancedsearch ==> [is[shadow]]
```

# `[all[shadows+tiddlers]tag[$:/tags/TopRightBar]]`
1 hit
```
$:/core/ui/TopBar/menu
```

**Comment by ascherer** [comment]
For whatever reason, this particular file is broken on my PC. Even after installing Firefox, I can't use the TW at all, because the double-crossed button won't open the side bar.

Curiously enough, AndTidWiki resumed to work with this file in version 5.1.20.

**Comment by Jermolene** [comment]
Hi @ascherer so this problem is only occurring on Firefox? Does the sidebar work normally in Chrome?

**Comment by ascherer** [comment]
No, on Opera, Tor, Konqueror, _and_ Firefox – all on Kubuntu Linux. It _does_ work on Android, now.

Another TW file with version 5.1.17 works with Opera, even _after_ the upgrade to version 5.1.20.

I suspect that the problem is related to one of the following:

1. Upgrade from 5.1.14 to 5.1.20.
2. Continuous work in the TW file with AndTidWiki on Android, but upgrade on Linux, and transferal between the two systems.

**Comment by ascherer** [comment]
Case closed. The bug was on my side. Saving the upgraded TW file the wrong way in Opera was the cause of the matter.

After a second upgrade on Android and re-transfer to Linux all is fine.

**Comment by Jermolene** [comment]
Thanks @ascherer
