### ISSUE TITLE
Why does Jasmine run eagerly?

### ISSUE THREAD

**Issue by flibbles** [Jermolene/TiddlyWiki5#4194]
I'm trying to finalize the demo site for my own plugin, and I have to keep Jasmine separated as its own site because of how eagerly it runs tests.

### Problem

If you have a tiddlywiki Node.JS project with Jasmine added as a plugin, and you use the command line to render tiddlers, run a server, check the version, _or even look at the help menu_, all tests run.

If you have a tiddlywiki website with Jasmine as a plugin, you can't open the page without all the tests running. If your tests take a while, it means your browser will take a while to load the page, which isn't savory.

### Solution?

Why not instead make Jasmine less eager? If on command line, there could be a `tiddlywiki --test` command. If in the browser, why not have a widget that renders as a button, that runs the tests when clicked? This way, the tiddlywiki page loads just fine, and any delays from testing occur after hitting the button (which could now show progress output, maybe as dots) instead of just stalling.

I realize this introduces one extra click into running browser tests, but I really think it would be preferable.

If people agree, I could probably make the outlines of this myself.

**Comment by Jermolene** [comment]
Hi @flibbles good question. The current behaviour is probably because I use a script that opens the test.html in my default browser, and I find it quite handy that I can see the results immediately. We could perhaps make it configurable. Now that we have startup actions we could make the tests be triggered by a message defined in a startup module, and then the `test` edition could include a startup action for auto-running the tests for backwards compatibiltiy.

**Comment by flibbles** [comment]
Sure, @Jermolene, that sounds like it could work, but before I start poking, is this something worth doing? Between this and your response in #3970, I get the impression that, before me, you were the only person who used Jasmine. If that's the case, it should work the way _you_ want it to work.

**Comment by Jermolene** [comment]
> Sure, @Jermolene, that sounds like it could work, but before I start poking, is this something worth doing? Between this and your response in #3970, I get the impression that, before me, you were the only person who used Jasmine. If that's the case, it should work the way you want it to work.

I've no objection to a PR that makes the behaviour configurable while retaining the current behaviour for the "test" edition.

**Comment by flibbles** [comment]
I'd just like to confirm that this would still be desirable. This eager running has always been a thorn to me.

1. I can't debug with Chrome, because the test framework runs too soon, and the debug js doesn't load in time.
2. I can't run a server from Node.js if jasmine is installed, because jasmine hard quits TiddlyWiki once it's done.
3. I can't do *anything* from Node.js without running every single test.
4. I've had trouble with the jasmine startup task running before my own plugins' startup tasks. It's **very** tricky to configure a startup task to run after jasmine, and not have it crash when jasmine isn't there in the production build.

I'll dispose of the "startup" task and make a command and a widget. The "test.html" file will have its Startup Tiddler contain a $test or $jasmine widget which will effectively run the tests when the file is open. This will all have two consequences:

1. The testing dots and results will likely show up in the tiddler containing the widget rather than at the bottom of the window.
2. People who use jasmine and upgrade may get confused as to why their tests aren't running anymore. Maybe I can make a message if "--test" isn't found in the tiddlywiki.info file.

If this is all okay with you @Jermolene, then I'll get started.

**Comment by Jermolene** [comment]
Hi @flibbles that's sounds good.

Perhaps rather than a `<$jasmine>` widget, we should use a `tm-run-tests` message to trigger execution of the tests, with parameters defined to allow a single test to be selected for running.

We don't have to maintain total backwards compatibility for the test suite because it's not user facing, but we do need to draw attention to any changes.

**Comment by pmario** [comment]
>Perhaps rather than a <$jasmine> widget, we should use a tm-run-tests message to trigger execution of the tests, with parameters defined to allow a single test to be selected for running.

I would love to have a mechanism for the CLI too, where it's possible to only run a "subsets" of tests. At the moment we need to run all of them, or temporarily rewrite the project.

**Comment by pmario** [comment]
@flibbles ... IMO this issue can be closed?

**Comment by flibbles** [comment]
Yes. My bad. This should have closed alongside #6944.
