### ISSUE TITLE
Global Shortcuts not working 

### ISSUE THREAD

**Issue by NoxMortem** [Jermolene/TiddlyWiki5#4198]
No global shortcuts seem to work for me. I really would love to have shift+space for [Simple Search](https://tid.li/tw5/plugins.html#%24%3A%2Fplugins%2Ftelmiger%2Fsimple-search:%5B%5BGet%20More%20Plugins%5D%5D%20%24%3A%2Fplugins%2Ftelmiger%2Fsimple-search%20ToDoNow%20%5B%5BToDoNow%20Installation%5D%5D%20%24%3A%2Fplugins%2Ftelmiger%2FPluginSize%2Flists).

However, the text area focused ones (ctrl+b for bold) seem to work.

I am running tiddlywiki 5.1.14 via nodejs v12.9.0 on windows 10 (x64) and [tiddlyserver](https://github.com/Arlen22/TiddlyServer) using the [Navigator Theme](https://tid.li/tw5/plugins.html#%24%3A%2Fthemes%2Ftelmiger%2Fnavigator:%24%3A%2Fthemes%2Ftelmiger%2Fnavigator). The shortcut works on the tid.li page but not on my node.js page (firefox, chrome, edge).

Attached is my tiddlyserver tiddlywiki folder.
[testrunde.zip](https://github.com/Jermolene/TiddlyWiki5/files/3537960/testrunde.zip)

**Comment by BurningTreeC** [comment]
Hi @NoxMortem , the global keyboard shortcuts work from v5.1.18 on, so you'll need to update your tiddlywiki version in order to use them

**Comment by NoxMortem** [comment]
@BurningTreeC Thank you. On point!
