### ISSUE TITLE
tiddlywiki.com - performance instrumentation is switched ON by default

### ISSUE THREAD

**Issue by pmario** [Jermolene/TiddlyWiki5#4201]
@Jermolene ... Is it intentional that: https://tiddlywiki.com/#%24%3A%2Fconfig%2FPerformance%2FInstrumentation defaults to yes?

**Comment by morosanuae** [comment]
@pmario I don't think so. In the previous version (v5.1.19) the performance instrumentation is not activated by default.  Good catch anyway. I have disabled it right away in my private wiki. I don't know how much resources it eats.
Thanks

**Comment by AnthonyMuscio** [comment]
I just looked at my first producton wiki upgraded from 5.1.19 and the performance instrumentation is also on. Do you think this is worthy of publication on the google forums?

**Comment by Jermolene** [comment]
Hi @pmario @morosanuae @AnthonyMuscio thanks! That was an oversight. Fix upcoming.
