### ISSUE TITLE
How to render double quotes inside codeblock widget?

### ISSUE THREAD

**Issue by dk1013** [Jermolene/TiddlyWiki5#4214]
Apologies if this feature is already available.
I Googled a lot and still cannot find a satisfying solution.
Suppose I want to render below code using codeblockwidget:
`print("Hello world")`
I tried this:
`<$codeblock code="print("Hello world")" language=python />`
Obviously this won't work due to ambiguity of the double quotes there.
Is there a way to escape double quote? Or is there a different delimiter for the code text?
Thanks!

**Comment by AnthonyMuscio** [comment]
As documented [here](https://tiddlywiki.com/#Macro%20Calls%20in%20WikiText) just choose a different delimiter

```
<$codeblock code="""print("Hello world")""" language=python />
or
<$codeblock code='print("Hello world")' language=python />
```

**Comment by pmario** [comment]
This may be interesting too: https://tiddlywiki.com/#Code%20Blocks%20in%20WikiText

**Comment by dk1013** [comment]
> 
> 
> As documented [here](https://tiddlywiki.com/#Macro%20Calls%20in%20WikiText) just choose a different delimiter
> 
> ```
> <$codeblock code="""print("Hello world")""" language=python />
> or
> <$codeblock code='print("Hello world")' language=python />
> ```

This is perfect, thank you!
