### ISSUE TITLE
Reference tiddler in which the code exists

### ISSUE THREAD

**Issue by AnthonyMuscio** [Jermolene/TiddlyWiki5#4216]
I could write a macro, config tiddler and more that relies on the value in one of that tiddlers fields.

`{{!!fieldname}} `however this is no longer valid if this tiddler is transcluded and another currentTiddler value exists. To ensure this we need to hard code the tiddler name so its text reference is complete.

`{{tiddlername!!fieldname}}`

If the tiddler is cloned or renamed we need to know that the literal tiddlername needs renaming in the text of the tiddler. It is not easy to automate this or ensure it takes place.

I want to ask those with more knowledge of tiddlywiki if there is a way for us to reference the current tiddler in which the code is defined and introduce a keyword that is automatically replaced with the tiddler title in which it is contained for example

`{{here!!fieldname}} or {{here}} or [[Edit|here]]`

Where "here" is always replaced with the tiddlername in which the code resides?

A simple NO is fine, but if there is a possibility it would be very helpful to insert debug and edit wikitext that allows you see where in a multi-level transclusion something in the result is found/defined.

I do however believe there would be other opportunities opened up with such a facility because we can represent in wikitext not only current tiddler values, or those as a result of a multilevel transclusion, but access tiddlers and field values in intermediate levels of transclusion. Kind of breadcrumbs insight into a multi-level transcluision, an example would be a books with paragraphs, sections, chapters in a big multi-level transclusion and a simple way to provide access to information in at any depth.

Thanks
Tony

**Comment by pmario** [comment]
Hi Tony, That's the reason, why templates exist. ... Not everything can be done with global macros. 

I did create some step by step videos, some time ago, that contain global macros and templates. 

[Video #9](https://www.youtube.com/watch?v=LVGDDakD7-8&list=PLuiC_HFhI4OzcqS8wBPSgT3nEK8WAXswk&index=10) shows the usage of a template, and how it works together with global macros. ... 

The key info is a transclusion call like this: `{{||transcludeTemplate}}` 

Jumping into the middle of the "game" can be very confusing. .. So if you don't understand what's going on, you should start from the beginning. 

That's the intro [thread in the GG](https://groups.google.com/forum/#!msg/tiddlywiki/_VQw8yIKWn8/G8TO8h6MCAAJ) which also contains all the attachments and links you'll probably need.

**Comment by Jermolene** [comment]
Hi @AnthonyMuscio

> I want to ask those with more knowledge of tiddlywiki if there is a way for us to reference the current tiddler in which the code is defined and introduce a keyword that is automatically replaced with the tiddler title in which it is contained for example

There's a subtle reason why this isn't something that could be easily added to TiddlyWiki. The parser (and therefore renderer) work on fragments of text that don't necessarily exist as a discrete tiddler. Consider the example of text that is within the text attribute of the wikify widget: that text might be constructed from a complex filter expression, and so there's no applicable concept of an originating tiddler.

A possible workaround might be for the transclude widget to set a variable with the title of the transcluded tiddler. That way, tiddlers could access the last transcluded tiddler, which would usually be themselves.

**Comment by AnthonyMuscio** [comment]
@Jermolene 

> A possible workaround might be for the transclude widget to set a variable with the title of the transcluded tiddler. That way, tiddlers could access the last transcluded tiddler, which would usually be themselves.

Are you suggesting a Bit like currentTab is used under the tabs macro? eg currentTransclusion and we could place in the transcluded tiddler (or wrapped for conditional display).
`<$link to=<<currentTransclusion>> tooltip="open transcluded tiddler"><$text text=<<currentTransclusion>>/></$link>`

Regards
Tony

**Comment by AnthonyMuscio** [comment]
@pmario 

Sorry I don't follow your point here. If I we to use templates are you saying that is the place to surface a link to the transcluded tiddler?. Like going through a template for transclusions that adds this functionality?

Your link to video 9 opens video 10 and I am not sure what to look for. Never the less thanks for your support.

Regards
Tony

**Comment by AnthonyMuscio** [comment]
I have created a two level transclusion in which each transcluded tiddler begins
`\define currentTransclusion() StaticTiddlername`

Renamed json file attached with three tiddlers demonstrating.
[currentTransclusion.bundle.txt](https://github.com/Jermolene/TiddlyWiki5/files/3561930/currentTransclusion.bundle.txt)

This is an acceptable work around to the OT however it requires forthought to insert this in every tiddler that may require it. Not so helpful if it is nested transclusions of user content.

However I think this can be further generalised

**Comment by pmario** [comment]
>Your link to video 9 opens video 10 and I am not sure what to look for. Never the less thanks for your support.

Sorry about that. It's just the link text that's wrong.

**Comment by AnthonyMuscio** [comment]
May I ask is there a standard template for transclusions given it defaults to text?

**Comment by AnthonyMuscio** [comment]
@Jermolene  
> There's a subtle reason why this isn't something that could be easily added to TiddlyWiki. The parser (and therefore renderer) work on fragments of text that don't necessarily exist as a discrete tiddler. 

I understand this, and if there is no value for fragments then `<<currentTransclusion>>` would be empty.

Would this method also work for direct transclusion?

eg `{{tiddlername}}`

**Comment by AnthonyMuscio** [comment]
Bump - little work around?

**Comment by AnthonyMuscio** [comment]
Ok, I found a way to do this using the transclusion variable some time ago but in the planned release of 5.3.0 we have the new `<<thisTiddler>>` variable which is exactly what I wanted.

* To me it is a lesson in how it does not matter how useful an idea, it can take years before others see the value.
* It means a super user like me can find gaps in tiddlywiki with ease, but to get that gap addressed can take years.

**Comment by Jermolene** [comment]
Thanks @AnthonyMuscio. It's true that sometimes it needs more than one voice before a request gets prioritised.

I am reminded by my first response that I was initially seeing this request as a parser extension which then raised a number of difficult questions. The implementation we've ended up with is much simpler, and in practical terms equivalent but it wasn't obvious initially.
