### ISSUE TITLE
ViewTemplate $:/core/ui/ViewTemplate/subtitle hackability

### ISSUE THREAD

**Issue by AnthonyMuscio** [Jermolene/TiddlyWiki5#4217]
Currently existing elements in $:/core/ui/ViewTemplate/subtitle can be hidden with CSS [here](https://tiddlywiki.com/#How%20to%20hide%20the%20author's%20and%20other%20fields%20with%20CSS) however there is no current method to "hack" and add information to $:/core/ui/ViewTemplate/subtitle.

I would like to suggest we provide a tag that will transclude tiddlers so tagged, into the subtitle in addition to the standard because this is a useful location for designers to add code.

$:/tags/TiddlerSubTitle

It would be wise to recommend defining a CSS class for it as well and using "float: right;" is helpful.

I believe the code to add is
`<$list filter="[all[shadows+tiddlers]tag[$:/tags/TiddlerSubTitle]!has[draft.of]]" variable="listItem"><$transclude tiddler=<<listItem>>/></$list>`

Here is an example content of a tiddler I would so tag
`<div style="float: right;">&nbsp;<<tsn>></div>`

Regards
Tony

**Comment by twMat** [comment]
>because this is a useful location for designers to add code.

It is?

>defining a CSS class for it as well and using "float: right;" is helpful.

Especially if you're floating it, you could simply add a new viewtemplate that is positioned above or below the subtitleviewtemplate, and get the same visual result.

If you're proposing new content that actually *belongs* in the subtitle then this is not clear in your post.

**Comment by AnthonyMuscio** [comment]
Mat,

You may be correct about the float (or would it drop a line)? But please consider a more general solution here.

The subtitle is diminished in size and comes with every tiddler (unless turned off) thus it is a suitable location to publish additional information or features on each tiddler. I have done this on a few occasions but must overwrite $:/core/ui/ViewTemplate/subtitle and could hit another macro or plugin rewriting of the same tiddler.

I am only asking that a tag be used to populate the subtitle so we can design additions to the subtitle without clashes.

Users/designers may wish to display creator and other details in the subtitle.

**Comment by AnthonyMuscio** [comment]
Change $:/core/ui/ViewTemplate/subtitle
to include
`<$list filter="[all[shadows+tiddlers]tag[$:/tags/TiddlerSubTitle]!has[draft.of]]" variable="listItem"><$transclude tiddler=<<listItem>>/></$list>`

Perhaps moving the following into a tiddler tagged $:/tags/TiddlerSubTitle
```
<$link to={{!!modifier}}>
<$view field="modifier"/>
</$link> <$view field="modified" format="date" template={{$:/language/Tiddler/DateFormat}}/>  
```

Modifiers (tiddlers created from above) can be found by searching for "[has[modifier]]" but perhaps it could be enhanced to include a field created-from=`<<currentTiddler>>` or similar.

**Comment by AnthonyMuscio** [comment]
Could someone please propose this as a pull request. I am not so sure how to do this, only for tiddlywiki.com

Regards
Tony

**Comment by AnthonyMuscio** [comment]
In tw 5.2.3 thanks
