### ISSUE TITLE
field name issue

### ISSUE THREAD

**Issue by kookma** [Jermolene/TiddlyWiki5#4218]
1. in tiddlywiki.com create a new tiddler
1. add a new field with title `__test`
1. now try to add a new field and look at the list appears in the drop down menu
1. you cannot see `__test` but you see the underlined test 

Suggestion: 

1. remove wikification on displaying the fields drop down list
2. add some rules for naming the fields

**Comment by Jermolene** [comment]
Fixed in 4ef9ccbab967c127e510100da2790c92fa54039d

**Comment by kookma** [comment]
Thanks BTC.
