### ISSUE TITLE
how to change the Tab Index in edit inputs?

### ISSUE THREAD

**Issue by 2anyone** [Jermolene/TiddlyWiki5#4229]
did search on TiddlyWiki, found: https://tiddlywiki.com/#Hidden%20Setting%3A%20Tab%20Index%20for%20Edit-Inputs

but I don't know how to ` assigned a tabindex value` in my TiddlyWiki, 

did checked the Hidden Settings description, https://tiddlywiki.com/#Hidden%20Settings, 

after I tried to drag of configuration tiddler to mine, it just copy the "Tab Index for Edit-Inputs" tiddler without anything I can do "assigned", also the link ($:/config/EditTabIndex) in it is lead to a missing tiddler...

how can I  achieve to change the Tab Index in tiddlywiki 5.1.20? thanks.

**Comment by BurningTreeC** [comment]
Hello @2anyone , simply create the tiddler $:/config/EditTabIndex and put a value (like 1) in its text field, then save the tiddler

**Comment by 2anyone** [comment]
thanks for your quick reply, 👍 

why doesn't the official intro be simple like you did? :)
