### ISSUE TITLE
External Attachments plugin on Windows: Script Error

### ISSUE THREAD

**Issue by BurningTreeC** [Jermolene/TiddlyWiki5#4237]
Windows 10, Tiddlydesktop

The External Attachments plugin throws a Script Error (see the screenshots) when trying to import a file
![script_error](https://user-images.githubusercontent.com/9407182/64238155-263c1e80-cefe-11e9-9fb1-7959b9779742.PNG)
![script_error2](https://user-images.githubusercontent.com/9407182/64238166-2c31ff80-cefe-11e9-9c03-721011fe0fe5.PNG)

**Comment by BurningTreeC** [comment]
On Windows, the filepath doesn't start with a `/` ... it starts with `C:/` or another disk prefix (`A:/` in my case) ... that makes it throw this error. Further, it encodes the filepath with uri encoding but doesn't decode it in the final filepath string

**Comment by pmario** [comment]
>On Windows, the filepath doesn't start with a `/` ... it starts with `C:/`

That's not always true. ... If you use the `file://` prefix a windows path also starts with: `/` because you need `file:///C:/xxx`

Download tiddlywiki.com save it locally and have a look at: `$:/info/url/pathname`

**Comment by pmario** [comment]
This isn't a problem on unix systems since absolute paths always start with eg: `/home/xxxx`

**Comment by Jermolene** [comment]
There's another ticket about this over at https://github.com/Jermolene/TiddlyDesktop/issues/142. I'd like to fix it for v5.1.21, and am downloading Windows VMs now.

**Comment by Jermolene** [comment]
I've just committed a fix, I'd be very grateful if you could test it if you get a chance. You can use the existing version of TiddlyDesktop, the fix is entirely inside the plugin.

**Comment by BurningTreeC** [comment]
Hi @Jermolene, thanks a lot, I will test

**Comment by BurningTreeC** [comment]
@Jermolene it's working fine in my tests 😄

**Comment by Jermolene** [comment]
Great, thanks @BurningTreeC!

**Comment by bimlas** [comment]
Related: #3761 

Maybe the PR fixed it, I can't test right now (I'm on Android).
