### ISSUE TITLE
Undocumented 'tm-rename-tiddler'

### ISSUE THREAD

**Issue by gernert** [Jermolene/TiddlyWiki5#4246]
Triggered by the discussion in the [Google groups](https://groups.google.com/d/msg/tiddlywiki/NC79XPu9j-8/QscZaAswAwAJ) I checked the list of messages: it does NOT contain tm-rename-tiddler.

**Comment by kookma** [comment]
I see there is a discussion on the GitHub about this, but it has not documented!

Hope this time Jeremy take proper action.

By the way, I think there are many features or capabilities NOT documented at all! Developers all the time are working on new features fixing issues!
But what has been developed, never enough documented!

Isn't it the time to give the same value if not more to documentation part?

**Comment by kookma** [comment]
Thanks Jeremy!
