### ISSUE TITLE
Field operator no longer works as described

### ISSUE THREAD

**Issue by flibbles** [Jermolene/TiddlyWiki5#4247]
I'm on cutting edge v5.1.20, and I'm noticing that the field operator has different behavior.

Documentation says when it's passed no operand, it should accept all tiddlers that either don't have that field, or have that field as blank. This is how it worked in v5.1.19 too.

Now it only returns tiddlers that have the field as blank.

**Comment by Jermolene** [comment]
Hi @flibbles ouch! Backwards compatibility is hard. A possible fix upcoming, let me know if it works for you.

**Comment by flibbles** [comment]
Seems fixed!

**Comment by Jermolene** [comment]
Thanks @flibbles
