### ISSUE TITLE
Wiki file is corrupted on gitlab repo.

### ISSUE THREAD

**Issue by T1mL3arn** [Jermolene/TiddlyWiki5#4251]
I configured gitlab saver to save my wiki. But in the repo the content of wiki file does not look like a html. It looks like single line of random characters like this `0YXNrLCJzeW5jaHJvbm91cyIpIH`. Though the size of file looks correct (~ 3mb).

Is there a problem with gitlab saver? Or I did something wrong? How can I decode it back?

TiddlyWiki version is 5.1.20

**Comment by Jermolene** [comment]
Hi @T1mL3arn I'm sorry you've run into problems. It looks like perhaps the file has been base64 encoded; you may be able to decode it with an online base64 decoder such as [this one](https://www.base64encode.org).

@bimlas can you duplicate the problem?

**Comment by bimlas** [comment]
Yes, the issue is real! #4243 would like to solve the problem, but it does not seems to work for me. @T1mL3arn can you please try it out?

**Comment by bimlas** [comment]
The decoded file works for me.

**Comment by T1mL3arn** [comment]
Decoding worked for me. Thanks!

**Comment by bimlas** [comment]
@T1mL3arn , I mean can you please try out the pull reuest (#4243)?

**Comment by T1mL3arn** [comment]
Is there "night build" with this pr? I cant get through building dev version right now.

**Comment by Jermolene** [comment]
Hi @T1mL3arn I've merged the fix #4255 which is currently in the process of being built. In 10 minutes you should be able to try it out at https://tiddlywiki.com/prerelease

**Comment by T1mL3arn** [comment]
Pre-release v 5.1.22 saves to gitlab properly. Thanks for fixing!

**Comment by Jermolene** [comment]
Hi @T1mL3arn #4255 was merged into v5.1.21 which was released yesterday. It seems that there is still an outstanding problem, see #4243
