### ISSUE TITLE
RevealWidget - add "missing" as type

### ISSUE THREAD

**Issue by twMat** [Jermolene/TiddlyWiki5#4253]
**Use case**: I have a toggle button to set status for if a tiddler should be published or not. I want this button to reflect and easily toggle between the three states; *"yes"*, *"no"* or the default value *"no-status-set"*. For this I'm using the RevealWidget. 

**Proposal** - enable this:

`<$reveal type="missing" state="$:/state/SampleReveal1">`

**Comment by pmario** [comment]
Reveal widget has a "default" parameter, that is used if the state tiddler is missing. see: https://tiddlywiki.com/#RevealWidget

**Comment by Jermolene** [comment]
Hi @twMat the distinctive thing about the reveal widget is that it generates a div/span, and the primary purpose of doing so is to enable content changes to be animated. For a tri-state button I think you'd be better of using a sequence of list widgets to control the display of the three states.

**Comment by twMat** [comment]
Thank you both.

The current `default` parameter is a fallback whereas my proposal is an explicit case used as a condition so there is pretty big a difference IMO. The syntax (for the whole expression) is also more difficult to figure out when using the fallback than my proposal.

But OK, I'll do as Jermolene proposes and use listwidgets, however;

>the reveal widget [...] generates a div/span, and the primary purpose of doing so is to enable content changes to be animated.

1. That it generates a div/span is only *indirectly* communicated in the docs (in some of the attribute descriptions mentioning HTML)
2. ...and that the widgets *primary purpose* is for animation is definitely not reflected in the docs.
3. About using the ListWidget instead; my impression is that the RevealWidget binary nature is less taxing on the system than a list iteration, no? The button I'm constructing is a viewtemplate to appear in every tiddler..

**Comment by Jermolene** [comment]
Hi @twMat I don't think there's a significant difference in performance. The docs could definitely be improved.

**Comment by twMat** [comment]
I'm letting go of my OP (and thereby closing issue) but taking the opportunity to ask about:

>primary purpose .... content changes to be animated

With the intention of improving the docs I'm hoping to add an example of animation but I'm confused about how to go about. My first attempt is to use the `animate=yes` attribute. This seems to have no effect, even when setting global animation time to 4000. 

Thinking "OK, maybe *animation* refers to using the *class* attribute with some style transition"... but this also doesn't make sense, at least not in the "accordion/slider" case, because when the state tiddler changes, the widget content is immediately switched. 

What do I misunderstand? What animation are we talking about? Set it how?

**Comment by Jermolene** [comment]
Hi @twMat the docs are misleading; for animations to work one also needs to set "retain" to "yes". Here's one of the existing doc examples with animation added:

```
<$button set="$:/state/SampleReveal1" setTo="show">Show me</$button>
<$button set="$:/state/SampleReveal1" setTo="hide">Hide me</$button>

<$reveal type="match" state="$:/state/SampleReveal1" text="show" animate="yes" retain="yes">

! This is the revealed content
And this is some text

</$reveal>
```

I've posted an [update to the docs](https://github.com/Jermolene/TiddlyWiki5/commit/b5e4cc0cc886b02340e643a2cddaeb8182dd9f0e).

**Comment by twMat** [comment]
Thank you Jeremy.
