### ISSUE TITLE
Allow message handlers to be written as action strings

### ISSUE THREAD

**Issue by Jermolene** [Jermolene/TiddlyWiki5#4265]
Issue #3967 outlines the goal of making the behaviour of TiddlyWiki's black box logic more hackable by implementing it in wiki text. This proposal is a step in that direction by providing a general purpose mechanism for handling wikitext messages via action strings.

The background is that much of TiddlyWiki's interactive behaviour is implemented as message handlers. Messages are sent from child nodes in the widget tree up through their ancestors until they find a node that will handle the message. Message handlers can be implemented in JS within widgets or as global handlers that are always available.

The proposal is to change the way that messages are dispatched such that if a macro with the same name as the message exists then the macro is invoked as an action string, with parameters mapped to the message parameters.

For example, here is a custom handler for the `tm-navigate` message. The `tm-navigate` is usually handled by the navigator widget. It can also be handled by the linkcatcher widget, which assigns the target of the link to a given tiddler field/index, which is what this example shows:

```
\define tm-navigate(navigateTo)
<$action-setfield $tiddler="MyTiddler" $field="text" $value=<<__navigateTo__>>/>
\end

Clicking [[This Link]] will set the tiddler MyTiddler to `This Link`...
```

A more complex example: the dropzone widget sends the `tm-import-tiddlers` message with a string containing the JSON of the tiddlers that have been dropped (it is usually handled by the navigator widget which does the importing and updates the story river). This example imagines a new action widget that imports the tiddlers while adding a prefix:

```
\define tm-import-tiddlers(param)
<$action-importtiddlers tiddlers=<<param>> addTitlePrefix="$:/imported/"/>
\end

<$dropzone>
<div>
Drop here to import tiddlers directly, without bringing up the $:/Import tiddler
</div>
</$dropzone>
```

It's worth noting that the effect of this change is to partially unite variables/macros and messages, making them interchangeable in some circumstances. This reflects a recent realisation on my part that messages are redundant in the TW5 design; everything they do could have been accomplished with macro invocations.

**Comment by pmario** [comment]
>... This reflects a recent realisation on my part that messages are redundant in the TW5 design; everything they do could have been accomplished with macro invocations.

I think that's right. ... The only problem I did face was: changing `$:/HistoryList` using 2 different action-setfield actions, caused 2 tw-refresh events. 

So I think, we need to be careful there.

**Comment by Jermolene** [comment]
> The only problem I did face was: changing $:/HistoryList using 2 different action-setfield actions, caused 2 tw-refresh events.

That would only happen if the two action-setfield actions were asynchronous with respect to one another. If they happen consecutively in the same set of actions then they won't cause two refreshes, the two updates will be coalesced into a single refresh.

**Comment by AnthonyMuscio** [comment]
In #4272 I point out the fact that we are using the button only as a trigger. a custom action tiddler is responsible for ts actions to be timely and ordered and single refresh.

**Comment by AnthonyMuscio** [comment]
Ahh on my third reading of this I now Understand your suggestion. 

This would allow designers to intervene in how the message works rather than the original trigger. Given there are less different messages than there are invocations of such messages a wiki wide hack is easier in some respects. 

Some questions that may indicate what people will ask (and I am asking)!

- Will it still be possible to access the currentTiddler ?
- Will it still be possible to access the the calling tiddler - eg this message originated in this button tiddler?
- Can we wrap some or all of the actions in the message definition with conditionals like list and reveal?
- Does this mean people can make their own custom messages? in addition to adding to or redirecting the existing messages?
- What are the implications of people building their own messages?

**Comment by Jermolene** [comment]
Hi @AnthonyMuscio 

Somewhat hypothetical answers since this doesn't exist yet:

> - Will it still be possible to access the currentTiddler ?

Yes

> - Will it be possible to access the the calling tiddler - eg this message originated in this button tiddler?

Messages are sent by widgets, not tiddlers. There's no mapping available back to the tiddler containing the widget -- primarily because there may not be a containing tiddler; the widget could have been synthesised with a wikify widget.

> - Can we wrap some or all of the actions in the message definition with conditionals like list and reveal?

Yes

> - Does this mean people can make their own custom messages? in addition to adding to or redirecting the existing messages?

A speculative part of this proposal is that message handlers would be action strings, so yes, naturally people could make their own.

> - What are the implications of people building their own messages?

The same as building action strings as macros.

**Comment by saqimtiaz** [comment]
@Jermolene another quick thought today was whether there might be scope for a `<$messagecatcher>` widget akin to the new `<$eventcatcher/>` widget. 

The original proposal in this issue would suggest most probably not, but just leaving the thought here as an alternative possibility for customizing message handling.

**Comment by Jermolene** [comment]
Thanks @saqimtiaz I'd forgotten about this ticket; I still quite like the idea. I think it's a cleaner approach than having a `<$messagecatcher>` widget because of the way it unifies messages and variables, and thus marginally simplifies the set of entities that users must learn about.

**Comment by saqimtiaz** [comment]
@Jermolene I also think the original idea is more approachable for non-technical users, who are much more likely to think in terms of macros than events.

I wanted to document the `<$messagecatcher>` idea though in case it might prove useful at some point. In some ways issues are like a knowledge and idea bank as well.

**Comment by Jermolene** [comment]
Hi @saqimtiaz I've run into a situation where it seems like `<$messagecatcher>` would be useful, but it's kind of a hack: trapping extraneous `tm-scroll` events generated by the `<$list>` widget when used with storyviews. I'm thinking about polishing it up for the core, but wondered if you had usecases in mind for it as well?

**Comment by saqimtiaz** [comment]
@Jermolene There was some usecase I had in mind when I posted this but it doesn't come to mind at the moment, and I'm a bit buried under other work at the moment. 

If I had to guess I would think it was either with multiple stories or Floats in mind (a plugin of mine that implements floating, moveable containers for tiddlers in addition to the usual stories).

Suggest you go ahead and polish it up to the core. I'll make sure to revisit my notes during the pre-release period so that if there are any ideas worth incorporating we can do so before this goes to a public release.

**Comment by Jermolene** [comment]
Thanks @saqimtiaz I'll go ahead.

**Comment by Jermolene** [comment]
> Thanks @saqimtiaz I'll go ahead.

See 9eda02868

**Comment by Jermolene** [comment]
I'm closing this because the `<$messagecatcher>` widget adequately addresses the OP without introducing any backwards compatibility issues.

**Comment by saqimtiaz** [comment]
> See [9eda028](https://github.com/Jermolene/TiddlyWiki5/commit/9eda02868f21e9dd1733ffe26352bd7ac96285b4)

@Jermolene Looks good at first glance. Only thing that comes to mind is whether we would want to extend the widget to capture multiple messages as we did for `<$eventcatcher>`, but that may be premature optimization at this point.

I'll look up my own notes on this when I get the chance and then take another more in depth look.

You can go go ahead and close this issue, and I'll open a discussion for `<$messagecatcher>` when I have something more to convey.

**Comment by saqimtiaz** [comment]
> I'm closing this because the `<$messagecatcher>` widget adequately addresses the OP without introducing any backwards compatibility issues.

@Jermolene I believe you forgot to actually close this issue.

**Comment by Jermolene** [comment]
Thanks @saqimtiaz
