### ISSUE TITLE
FontAwesome plugin characters in Tiddler links

### ISSUE THREAD

**Issue by think-info** [Jermolene/TiddlyWiki5#4280]
I'm trying to use a TiddlyWiki with the FontAwesome plugin.

The specific use-case I have is that I've got a bunch of tabs `<<tabs "tab1 tab2 tab 3">>` which I want to be easily editable from the parent Tiddler without having to edit the parent, dig to find the tab's name, then search for it manually. To achieve this, I wanted to insert an edit icon from FontAwesome `<i class="fas fa-pen-square"></i>` in a link.

The problem: once it's inside a link's square brackets, it's treated as raw text to be html-encoded, and doesn't get parsed into the desired FontAwesome character.

Is there some way around this, so I can use an icon to make my tabs directly editable.

If there's some code to go a step further so the link is to self, so I can copy-paste a block in without having to customise it for each tab's name, that would be a bonus.

**Comment by morosanuae** [comment]
Hello @think-info, I made a little demo: [link to demo](http://fa5-free-svg.tiddlyspot.com/#tabs%20demo). Is this what you trying to accomplish?

**Comment by think-info** [comment]
Thanks @morosanuae 

In one sense, that's even better than what I was hoping for - editing firectly from the tab is brilliant.

However, it loses a feature I was using before, which was that tabs by default displayed the target Tiddler's caption field. How do I get that to display?

Additionally - and this might be asking too much - my tabsets had a little collapsing cheat, with the first tab being to a Tiddler with a whitespace caption (and no content), so it had a baby tab that hid all without wasting space on a tab label. Is there some way to style the first tab differently, without the edit button?

**Comment by think-info** [comment]
After a bit of playing, I partially solved the first issue there, swapping the `<<currentTab>>` in the template for `<$transclude tiddler=<<currentTab>> field="caption">`.

Interestingly, if I put that element first, so the edit buttons are on the right of the tab, the edit button then doesn't display…

**Comment by morosanuae** [comment]
@think-info 

> After a bit of playing, I partially solved the first issue there, swapping the <<currentTab>> in the template for <$transclude tiddler=<<currentTab>> field="caption">.

There is a potential problem with this approach. If the caption field is empty or missing, nothing will be displayed in the tab title. So I recommend you to replace your code with this:
`<$transclude tiddler=<<currentTab>> field="caption"><<currentTab>></$transclude >`
This way the title of the tiddler will be used as a fallback if the caption field is empty or missing as you can see in my v2 demo: [link to demo v2](http://fa5-free-svg.tiddlyspot.com/#tabs%20demo%202)

> Interestingly, if I put that element first, so the edit buttons are on the right of the tab, the edit button then doesn't display…

In my v2 demo this is working as expected: the edit buttons appear on the right side of the tabs. Maybe you got something wrong. Please, double check your code to be sure!

> Additionally - and this might be asking too much - my tabsets had a little collapsing cheat, with the first tab being to a Tiddler with a whitespace caption (and no content), so it had a baby tab that hid all without wasting space on a tab label. Is there some way to style the first tab differently, without the edit button?

I need to understand this first. I'll come back later with a response.

**Comment by morosanuae** [comment]
@think-info 

> Additionally - and this might be asking too much - my tabsets had a little collapsing cheat, with the first tab being to a Tiddler with a whitespace caption (and no content), so it had a baby tab that hid all without wasting space on a tab label. Is there some way to style the first tab differently, without the edit button?

I'm sorry, I'm unable to figure out exactly what you trying to accomplish. Can you post a demo or share the code?

**Comment by think-info** [comment]
@morosanuae 

> Please, double check your code to be sure!

Yep. I was missing a closing slash in that `<$transclude>`. Duh!

> I need to understand this first.

Create **blankTab**, leave it empty and give it an empty caption.

Create **tabs demo 3** with content `<<tabs "blankTab SampleTabOne SampleTabTwo SampleTabThree" >>`

There will be a baby tab at the front of the set, which effectively closes whatever the current tab is without taking up significant space. That's the effect I'm hoping can be replicated wih the edit buttons. Can the template have a conditional statement: `if (<<currentTab>> == [[blankTab]]) {no-button-option} else {button-option} `

Additional question: is there an open-edit _below_, as a link to the tiddler would? `<$button message="tm-edit-tiddler" param=<<currentTab>> >` opens the tab's tiddler at the top of the list, which is a long way from where I'm working.

**Comment by morosanuae** [comment]
@think-info

> There will be a baby tab at the front of the set, which effectively closes whatever the current tab is without taking up significant space. That's the effect I'm hoping can be replicated wih the edit buttons. Can the template have a conditional statement: if (<<currentTab>> == [[blankTab]]) {no-button-option} else {button-option}

So you want a button which closes the current tab instead of the editing button?

> Additional question: is there an open-edit below, as a link to the tiddler would? <$button message="tm-edit-tiddler" param=<<currentTab>> > opens the tab's tiddler at the top of the list, which is a long way from where I'm working.

This is the current default behavior I'm afraid and I couldn't find a way to change it. I couldn't find something helpful in the docs also. Maybe you should post this in the forums.

**Comment by think-info** [comment]
@morosanuae 

> So you want a button which closes the current tab instead of the editing button?

Effectively, yes. A shadow tab that closes whichever one is open.  Not on the other tabs, and not replacing the edit button on any of the tabs with real content.

**Comment by think-info** [comment]
@morosanuae 

> This is the current default behavior I'm afraid and I couldn't find a way to change it.

I might have half-solved it, but I don't know enough of the syntax and can't find documentation…

I can get it to open the tab's tiddler below the current location:

`<$transclude tiddler=<<currentTab>> field="caption" />
<$button>
 <$action-navigate $to=<<currentTab>> />
<i class="fas fa-pen-square"></i>
</$button>`

My attempts to insert an `<$action-sendmessage … />` after the `<$action-navigate … />` don't work as I was hoping; it won't properly target the right one to open. Maybe that's just a syntax issue.

**Comment by think-info** [comment]
@morosanuae 

Update

`<$transclude tiddler=<<currentTab>> field="caption" />
<$button>
 <$action-navigate $to=<<currentTab>> />
 <$action-sendmessage $message="tm-edit-tiddler" $param=<<currentTab>> />
<i class="fas fa-pen-square"></i>
</$button>`

It works! Navigates to it below the current location, then opens it to edit.

**Comment by morosanuae** [comment]
@think-info Well done, I'm glad that you have found a solution! But I guess the problem with closing (hiding) the tab remains no?

**Comment by think-info** [comment]
@morosanuae 

The tab-closing is still outstanding. I've discovered the existence of a [Conditional Operator](https://tiddlywiki.com/static/Conditional%2520Operators.html), but it requires v 5.1.20… I've come up with some code based on that template that I think _might_ work (basically conditional template forwarding), but I can't test it yet.

Which raises an alternate question to get there: how do I upgrade from 5.1.19?

The one other thing that will make this look neater: how do i change the button styling to eliminate all that padding? (So the tabs are back to a more normal size.)

**Comment by morosanuae** [comment]
@think-info 

> The one other thing that will make this look neater: how do i change the button styling to eliminate all that padding? (So the tabs are back to a more normal size.)

With the help of CSS of course. You should overwrite some default TiddlyWiki classes. Please, see my v2 demo again: [link to demo v2](http://fa5-free-svg.tiddlyspot.com/#tabs%20demo%202)

> The tab-closing is still outstanding. I've discovered the existence of a Conditional Operator, but it requires v 5.1.20… I've come up with some code based on that template that I think might work (basically conditional template forwarding), but I can't test it yet.

The conditional functionality exists in the previous versions also by using "list" widget with some other older operators.

**Comment by morosanuae** [comment]
> Which raises an alternate question to get there: how do I upgrade from 5.1.19?

Upgrading can be very easy and straightforward or challenging depending on what type of content do you want to export. In the simplest case you drag your personal wiki over a special online upgrading app and then download the upgraded version that retains your personal tiddlers. The docs for upgrading is here: [https://tiddlywiki.com/#Upgrading](https://tiddlywiki.com/#Upgrading)

**Comment by think-info** [comment]
@morosanuae 

> With the help of CSS of course. 

Thanks. A bit cumbersome that I have to transclude that CSS into each instance and wrap the whole thing in another div, but it could have been worse.

> Upgrading

Was easy. It's all just text, text and text. Tons of it, but nothign dangerous.

> Conditional functionality

My initail thoughts on the template forwarding failed miserably :-( I've tested template forwarding by transclusion; it works. But the conditional logic from the examples doesn't get parsed as a conditional statement, instead just presenting as text.

**Comment by morosanuae** [comment]
@think-info 
> Thanks. A bit cumbersome that I have to transclude that CSS into each instance and wrap the whole thing in another div, but it could have been worse.

You don't need to wrap the whole thing in a div as I did. I forgot that you could add CSS classes to the tabs macro directly as an argument to the "class: parameter. See my demo v2 again.

**Comment by morosanuae** [comment]
@think-info

**Comment by think-info** [comment]
@morosanuae 

> you have the possibility to define classes in an external tiddler 

Thank you!

It's the little details there - and clearer explanation - that make all the difference. My previous attempts to do anything with stylesheet-level things in TW failed because I couldn't make sense of the documentation (like so much, it describes what is without the context of how to use).

Btw, I've solved the conditional template via a question in the forum, so I now have both my hider tab and the edit buttons on tabs; it makes life so much easier.

I'm now thinking I should create a modification of the tabs macro to do all of this cleanly, without the need to reference Blank every time. Or to be bothered with the CSS reference… But layers of obfuscation in the code.

**Comment by morosanuae** [comment]
@think-info 

If you manage to fulfill all your needs, please close this issue. To be honest with you, this kind of thread don't belong here because GitHub is mainly for bug reporting and maybe suggestions/feature requests but not basic/advanced use cases. I hope you understand. Also, I think, you'll receive greater help in the forums because the participation of the community users is greater there.
