### ISSUE TITLE
Dropdowns should not be dismissed when clicking in a contained text editor

### ISSUE THREAD

**Issue by Jermolene** [Jermolene/TiddlyWiki5#4282]
To reproduce, paste the following into a new tiddler on https://tiddlywiki.com:

```
<$button popup="$:/SamplePopupState">Pop me up!</$button>

<$reveal type="popup" state="$:/SamplePopupState" class="tc-popup-keep">

<div class="tc-drop-down">

{{||$:/core/ui/EditTemplate/body/editor}}

<$edit tiddler="this"/>

</div>

</$reveal>
```

After saving it, click the button to display the dropdown, and scroll down to the two text boxes. Clicking on the lower text box (a plain `<textarea>`) does not dismiss the popup, but clicking on the upper one (a full iframe editor) does erroneously dismiss the popup:

<img width="444" alt="image" src="https://user-images.githubusercontent.com/174761/66112774-6658f480-e5c3-11e9-82d0-dae449632db3.png">

@BurningTreeC I think you did some work in this area?

**Comment by BurningTreeC** [comment]
Hi @Jermolene , I cannot reproduce this. Testing your code on the current prerelease. Both editors don't cancel the popup

**Comment by BurningTreeC** [comment]
Ah, now I see. Codemirror works fine, the standard editor doesn't

**Comment by Jermolene** [comment]
Oh good! I was worried for a moment!

**Comment by BurningTreeC** [comment]
I'm worried about how to fix this

**Comment by Jermolene** [comment]
OK so it's because we cancel popups when the editor gets focus. Perhaps the editor widget can check whether it's within a popup before cancelling popups? It would be reasonable to scan ancestors in the DOM looking for the CSS classes.

**Comment by BurningTreeC** [comment]
> OK so it's because we cancel popups when the editor gets focus. Perhaps the editor widget can check whether it's within a popup before cancelling popups? It would be reasonable to scan ancestors in the DOM looking for the CSS classes.

I thought I'd have already done so in popup.js

**Comment by BurningTreeC** [comment]
@Jermolene , I'd be inclined to undo the latest changes that cancel popups when focusing textareas and give it a new try at some point. I think I haven't covered all possible cases there

**Comment by Jermolene** [comment]
Thanks @BurningTreeC can you remind me of the commit/PR in question?

**Comment by BurningTreeC** [comment]
@Jermolene, this should be fixed now

**Comment by Jermolene** [comment]
Thanks @BurningTreeC
