### ISSUE TITLE
toc-selective-expandable macro still shows arrow despite excluding tiddlers

### ISSUE THREAD

**Issue by KendrickLamarck** [Jermolene/TiddlyWiki5#4284]
The `toc-selective-expandable` macro still shows arrows to expand when using filter expressions to exclude tiddlers, even though there is nothing to expand.

## Steps to reproduce

1. Create a tiddler, named `TableOfContents` with content

```
<div class="tc-table-of-contents">
<<toc-selective-expandable "TableOfContents" "!tag[no-toc]">>
</div>
```

2. Create a tiddler named `foo` tagged `TableOfContents` and a Tiddler named `bar` with tags `foo` and `no-toc`.

## Expected behavior

The tiddler `TableOfContents` shows only the title `foo` without an arrow.

## Actual behavior

The title `foo` is shown with an arrow to expand next to it. Clicking it does nothing, as if using `toc-expandable`.

**Comment by Jermolene** [comment]
Thanks @KendrickLamarck, fix coming up.

**Comment by Jermolene** [comment]
Please try the fix at https://tiddlywiki.com/prerelease (the system will need about 10 minutes to build the new commits).
