### ISSUE TITLE
Deletes are not saved when lazy loading is active

### ISSUE THREAD

**Issue by arnowelzel** [Jermolene/TiddlyWiki5#4291]
### Summary

Lazy loading prevents syncing of deleted tiddlers back to the server.

### Steps to reproduce

1. Run TiddlyWiki in Node.js with `tiddlywiki --listen root-tiddler=$:/core/save/lazy-all`

2. Create a tiddler and save it and wait for the autosave to be executed.

3. Reload the wiki to check, that the tiddler is also saved on the server

4. Delete the tiddler again and wait  for the autosave to be executed

5. Reload the wiki to check, that the tiddler is still deleted

### Expected result

The deleted tiddler is also delete on the server.

### Actual result

The tiddler only gets deleted in the browser but not on the server. When you refresh the wiki in the browser the already deleted tiddler returns.

When I try it with `tiddlywiki --listen root-tiddler=$:/core/save/lazy-images` I can delete text tiddlers permanently again but then image tiddlers will still not get deleted on the server, only in the browser.

Is this a known limitation of lazy loading or is this a bug?

### Context

Server: TiddlyWiki 5.1.21, Ubuntu 16.04 LTS, Node.js 8.16.1
Client: Firefox 69.0.2

**Comment by Jermolene** [comment]
Thanks for the report @arnowelzel. I've pushed a fix, please let me know if it works for you.

**Comment by arnowelzel** [comment]
How to I integrate this fix to my installation? Any hint, how to build a new version?

**Comment by arnowelzel** [comment]
Ok, I just applied the change to `/usr/lib/node_modules/tiddlywiki/core/modules/server/routes/get-tiddler.js`. Seems to work now - thank you!
