### ISSUE TITLE
Embedded PDF files cannot be opened

### ISSUE THREAD

**Issue by marypo** [Jermolene/TiddlyWiki5#4299]
Hi, 
I work with several tiddlywikis on iPad and iMac. **This regards iPad:** When I embed a PDF file in a tiddler only the first page is shown (like an image) and I can't open the file. I tried in Firefox, Safari and Quine, both on iOS 12 and iPadOS 13 and with both syntaxes {{}} and [[]]. Works fine with Firefox on desktop though. Since other PDF files from any webpage work fine on iPad I think it must be some issue with Tiddlywiki itself. Is there anything I can do about it?

**Comment by Jermolene** [comment]
Hi @marypo browsers handle PDFs in wildly different ways. As you've noted, Safari on the iPadOS or iOS treats PDFs as images if they are embedded, and only presents the full viewer if the PDFs are opened as separate files. (Note also that iPadOS/iOS doesn't really support browsers other than Safari, they are all obliged to use the same underlying WebKit framework to view the files).

**Comment by AnthonyMuscio** [comment]
Installing a third party PDF reader with the addon for the browser should resolve this, if apple does not provide the solution (odd). I like FoxIt reader, and FireFox but I have not attempted this on a MAC or IOS device lately.

**Comment by Jermolene** [comment]
@AnthonyMuscio this question is about iPadOS, where Apple do not allow the installation of third party plugins that present content within the browser.

**Comment by AnthonyMuscio** [comment]
Jeremy I understand but I have got past limitations in the past imposed by iOS by using a third party app and its features or plugins especially when it comes to standard files like pdfs. I have not used one lately for some time but the is a common workaround. For example the Firefox app had its own pdf viewer.

If iOS does permit alternate browsers now I am surprised but then apple does try and use its proprietary solutions to lock out competitors and lock users into their own each system.

If this is the case I would like confirmation because I will be supporting my parents new iPads soon.

**Comment by Jermolene** [comment]
Hi @AnthonyMuscio 

> Jeremy I understand but I have got past limitations in the past imposed by iOS by using a third party app and its features or plugins especially when it comes to standard files like pdfs. I have not used one lately for some time but the is a common workaround. For example the Firefox app had its own pdf viewer.

There are standalone PDF viewers on the iOS app store, but none of them alter the way that WebKit displays embedded PDFs.

>If iOS does permit alternate browsers now I am surprised but then apple does try and use its proprietary solutions to lock out competitors and lock users into their own echosystem.

Apple say that the reason that they block other browsers is that only WebKit is efficient enough in terms of power consumption. It's certainly true that Chrome and Firefox drain laptop batteries.

> If this is the case I would like confirmation because I will be supporting my parents new iPads soon.

I use one of the newish iPad Pros regularly, and can highly recommend it.

**Comment by pmario** [comment]
>.. It's certainly true that Chrome and Firefox drain laptop batteries.

hmm, ... maybe, if laptop is an Apple. ... With my Dell XPS dev edition running Unix I'm happy to work 8+hs browser active 100% of the time ... no video streaming. 

The biggest impact for me has the screen brightness setting, which can cause a variation up to 3hs.

**Comment by sukima** [comment]
I'm curious. Is it possible to have TW open a new tab with the data URI maybe via a link? That way on iPadOS the user clicks the link and it is no longer *embedded*?

**Comment by MagicJF** [comment]
Is there anything new since 2019?

I have tiddlers that transclude pdf's and on my iPhone only the first page is shown (no matter which browser I do use).

**Comment by Jermolene** [comment]
Hi @MagicJF I don't think anything has changed here. PDF handling is still inconsistent across browsers.

I will close this as it is not actionable.

**Comment by MagicJF** [comment]
Someone does know why/how come Telegram for IOs can skip webkit restrictions?

If I do access this link _(https://mws-tw.tailabb6c.ts.net/bags/pdf/tiddlers/sample#page3)_ from the the browser I get directed to page nº1, while if I acces the same link through telegram I get directed to page nª3

![telegramlink](https://github.com/user-attachments/assets/7791844f-c031-4695-906a-2728d91172d0)

**Comment by Jermolene** [comment]
Hi @MagicJF on my iPad, accessing the link https://mws-tw.tailabb6c.ts.net/bags/pdf/tiddlers/sample#page3 opens it in Safari showing page 3 as expected. It looks like this might be a problem with the Firefox iOS browser?

**Comment by MagicJF** [comment]
Hi!
Seems like Firefox for iOS behaves differently on iPad and on iPhone.

While the link opened on iPad takes me to page 3, same link on iPhone takes me to page 1.
🤷‍♂️
