### ISSUE TITLE
Tag dropdown is broken

### ISSUE THREAD

**Issue by Jermolene** [Jermolene/TiddlyWiki5#4309]
The tag autocomplete dropdown on https://tiddlywiki.com/prerelease is broken:

1. Create a new tiddler
2. Type an "E" in the new tag box
3. Click on one of the entries in the dropdown

Expected result: the tag is added

Actual result: as though the "save" button was clicked to finish editing the tiddler

cc @BurningTreeC -- I think this was introduced in d01b781283115f32eac345f92e483741918a65a7

**Comment by BurningTreeC** [comment]
Hi @Jermolene , this is my fault, it's in a different PR

**Comment by Jermolene** [comment]
Thanks @BurningTreeC

**Comment by BurningTreeC** [comment]
@Jermolene , this issue is resolved

**Comment by Jermolene** [comment]
Thanks @BurningTreeC
