### ISSUE TITLE
Normalize.css v8.0.1 displays tables differently

### ISSUE THREAD

**Issue by Jermolene** [Jermolene/TiddlyWiki5#4327]
The update to v8.0.1 of normalize.css in #4208 breaks the display of tables.

Before:

![image](https://user-images.githubusercontent.com/174761/66957198-a73e1800-f05d-11e9-8c87-b419df78f013.png)

After:

![image](https://user-images.githubusercontent.com/174761/66957245-c177f600-f05d-11e9-8011-9ba83cf74de4.png)

@pmario I guess we should fix this in $:/themes/tiddlywiki/vanilla/base (we already have a section to undo certain normalize.css things).

**Comment by pmario** [comment]
@Jermolene Which browser? which OS? ... I use Win10, FF latest .. and there is no difference. 

Will test IE and Edge and Edge beta, too. Can't test Chrome (not installed)

**Comment by pmario** [comment]
- MS Edge: Microsoft Edge 44.18362.387.0   ... is OK
 - MS Edge beta with Chromium base: Version 78.0.276.17 (Official build) beta (64-bit) ... OK
 - IE 11, V 11.418.18362.0 .. looks OK

**Comment by pmario** [comment]
did you use a different browser zoom level?

**Comment by Jermolene** [comment]
Apologies @pmario, it looks like the illustration above on every browser I have: Chrome, Safari and Firefox on macOS, and iPadOS

Here's Chrome running on Windows in a VM:

<img width="691" alt="image" src="https://user-images.githubusercontent.com/174761/67011000-aac9b180-f0e6-11e9-850a-01c9e0d41dce.png">

I'm surprised you're not seeing the same thing in, say, Firefox because it's highly unusual to have layout differences between the same browser on different OSs. Can you post a screenshot from Firefox?

**Comment by Jermolene** [comment]
(All using default browser zoom level btw)

**Comment by gernert** [comment]
@Jermolene 

Normalize.css v3.0.0 contains:

```
table {
  border-collapse: collapse;
  border-spacing: 0;
}
```
Normalize.css v8.0.1 doesn't.
If I apply the code above to the prerelease, tables look normal (Linux Mint, Firefox).
