### ISSUE TITLE
Proposal: add Print-River to core

### ISSUE THREAD

**Issue by BurningTreeC** [Jermolene/TiddlyWiki5#4352]
Hi, I'd like to add some PR's for a Print-River like shown in http://printriver.tiddlyspot.com/

If you're ok with that, I'd like to make small steps towards it by making a few single PR's

What do you think about this?

**Comment by BurningTreeC** [comment]
another demo: http://print-tiddler.tiddlyspot.com

**Comment by pmario** [comment]
I think it can be a core-plugin, or does it need to be implemented in a low level?

**Comment by BurningTreeC** [comment]
It can be a core plug-in

**Comment by BurningTreeC** [comment]
... but it needs many language tiddlers

**Comment by pmario** [comment]
>... but it needs many language tiddlers

ok. That would be a reason to include it. ... but implementing it as a plugin is better for diversity. 

So we could include the needed text elements, which then can be used by several plugins.

**Comment by kookma** [comment]
@BurningTreeC 
Why as a plugin? 
TW needs to have a user friendly UI for printing! right now it is too difficult to customize print!
Also changing tiddlers using user styles makes getting strange result in print!
I think we need in setting or print preview like print river to have adjust margins, ... like that.

Please also see my recent post here:
https://groups.google.com/d/msg/tiddlywiki/EHmnIW13uoE/GnJWGJ15AQAJ

**Comment by AnthonyMuscio** [comment]
Can I suggest if this is to goes into core it should have the added advantage  of allowing further adjustment of the UI to map it to the print output. Ie WISYWIG basically we could introduce one or more print like themes that can be used for display and/or at print preview. Why develop features and not give them also to the UI ?

Some tiddlywikis could thus be published as if they were "White papers" or interactive documents in a selected print like theme, with a print button.

Until such tiddlywiki I too feel it should remain a plugin even if that plugin is considered so useful it is provided in the empty (however not everyone wants a print facility and instead would like a minimal edition).

Once again this reinforces my suggestion that we should publish a minimal empty.html and a standard.html with key functional plugins installed. Thus plugin or themes for print would be in standard not empty.

**Comment by kookma** [comment]
> Hi, I'd like to add some PR's for a Print-River like shown in http://printriver.tiddlyspot.com/
Hi @BurningTreeC 
While this is great plugin and I noticed in Tiddlywiki 5.1.21 the yellow top menu bar is not working as expected. Drag and drop, saving  and reloading tiddlywiki.com/prerelease adds the printer icon on every tiddler view toolbar, but when you click on printer icon the PrinRiver new window does no show the tools icon and one cannot customize printing.

**Comment by kookma** [comment]
@BurningTreeC 

These are discussion on forum 
- https://groups.google.com/d/msg/tiddlywiki/EHmnIW13uoE/GnJWGJ15AQAJ
- https://groups.google.com/d/msg/tiddlywiki/KrG-yAs2stQ/hAlpyjE2AwAJ

@Jermolene 
The current print capability of TW core is limited. For example at least it is required to have flexibility to choose if title/tags/subtitle can be printed. Like print the whole storyriver, one can select a tag,...
If think even if PrintRiver is considered as plugin, it worth to polish it and publish as an official plugin

**Comment by kookma** [comment]
@Jermolene 

Please also see the issue reported here: print page and top menubar

**Comment by TiddlyTweeter** [comment]
I'd add, having used & still using @BurningTreeC's original work on this that enhances TW in a basic way that extends a commonly needed function to print elegantly. I don't care if its done through core or plugin so long as it works. Yes, there were minor issues on its working. I'm sure some of those are resolved already. I'd be happy to comment on an updated version afresh.

**Comment by BurningTreeC** [comment]
I'll close this issue and try creating a plugin

**Comment by kookma** [comment]
@BurningTreeC 
It is very demanding to be able to produce nice looking PDF from Tiddlywiki Tiddlers. Print-River does the job! please have a look at the issues reported above and in the forum! Bye the way, this is an essential feature and is highly recommended to be part of the core in future.

I would like to have @Jermolene opinion on this proposal.
