### ISSUE TITLE
Using "<<now DDD>>" in startup actions creates a RSOD "TypeError: $tw.language is undefined"

### ISSUE THREAD

**Issue by pmario** [Jermolene/TiddlyWiki5#4370]
see: https://github.com/Jermolene/TiddlyWiki5/commit/2c2d03f7a76f81b68a9bce2e84f7fb05e1197a9b

to reproduce: test-startup   tagged: $:/tags/StartupAction

code 

```
\import [[$:/core/ui/PageMacros]] [all[shadows+tiddlers]tag[$:/tags/Macro]!has[draft.of]]

<$set name=test value=<<now DDD>>>
<$reveal type="match" default=<<test>> text="Sunday">
<$action-setfield $tiddler="hugo" $value="it's Sunday"/>
</$reveal>
</$set>
```

**Comment by pmario** [comment]
Seems to be a chicken / egg problem.

**Comment by saqimtiaz** [comment]
@pmario for some situations at least, using the new [post-render startup actions](https://github.com/Jermolene/TiddlyWiki5/commit/5cc1600072f5aa50c8ff5f5d2e748d81a7067420) is an option.

**Comment by pmario** [comment]
Tested it with post-render and it works now!
