### ISSUE TITLE
Open in new window - bug or limitation

### ISSUE THREAD

**Issue by AnthonyMuscio** [Jermolene/TiddlyWiki5#4372]
A reoccurring observation in the Open in New Window Button often used to act as a remote control TOC or to prepare to print an individual tiddler is that **not all buttons and content is reproduced as it is within the same tiddler in the standard story**. eg Printing from "open in new window" | Layout good | icons not visible.

I raise this issue here because I believe someone with detailed knowledge of tiddlywiki can possibly solve this easily. Please help resolve this gap.

I speculate that this is because "open in new window" is not including references to variables and stylesheets that are normally included when displaying tiddlers in the main body of tiddlywiki. Perhaps the gap is to do with page variables and stylesheets that are normally already active when displaying standard tiddler but not when they are in a new window. 

- The solution would be to identify the gaps and use import variables and transclude appropriate stylesheets and tiddlers in the tiddler to appear in the window. I imagine an import variables or include stylesheets would fix this.

In relation to [gg discussion](https://groups.google.com/forum/?hl=en#!topic/tiddlywiki/N7xwaOh84mk)

Thanks Tony

**Comment by AnthonyMuscio** [comment]
Postscript: Perhaps this is or should be a template used for open in new window. I can foresee a need to use alternate templates.

**Comment by Jermolene** [comment]
Hi @AnthonyMuscio we have indeed had a succession of problems along the lines of functionality not working in a new window, but working OK in the main window. If you've found something specific that doesn't work when opened in a new window, please can you post a minimum test case? Either a series of steps to be performed on tiddlywiki.com, or a custom demo wiki. Many thanks.

**Comment by AnthonyMuscio** [comment]
I will when I come across it again.

**Comment by AnthonyMuscio** [comment]
Here is the first example @Jermolene 

`{{||$:/core/ui/Buttons/home}}
`

Works in a tiddler in the story river, open it in new window and it fails.

Tony

**Comment by Jermolene** [comment]
Thanks @AnthonyMuscio, fix upcoming. Please open a new issue if you encounter any further problems with opening things in new windows.
