### ISSUE TITLE
New tiddler : unable to enter  text in the text area 

### ISSUE THREAD

**Issue by vfarcy** [Jermolene/TiddlyWiki5#4377]
I can create tiddlers and type to give them names, assign tags, and create fields with values, but when I try to type body text in the text area then nothing appears.

Clicking edit buttons e.g. for bold does enter text in to this area, but typing does not.

**Comment by AnthonyMuscio** [comment]
Can you make this occur on Tiddleywiki.com and provide us with the information so we can reproduce it?

If you think the text is there, such that you can highlight and copy it perhaps the text color or something is wrong, Looks for tiddlers tagged stylesheet that may have being modified.

This is possibly better suited to the [tiddlywiki forum](https://groups.google.com/forum/?hl=en#!forum/tiddlywiki)

**Comment by Jermolene** [comment]
Hi @vfarcy did you follow @AnthonyMuscio's suggestion? It would be helpful to post a link to the discussion here for anyone coming across this in the future.

**Comment by pmario** [comment]
@Jermolene ... No response for more than 3 weeks. IMO should be closed.

**Comment by pmario** [comment]
@Jermolene -- IMO should be closed. -- User did not respond to any instructions for several years.

**Comment by Jermolene** [comment]
Thank you @pmario
