### ISSUE TITLE
Optimise the core SVG icons

### ISSUE THREAD

**Issue by Jermolene** [Jermolene/TiddlyWiki5#4379]
The TiddlyWiki core SVG icons were created using an app called [Sketch for the Mac](https://www.sketch.com), and then hand tweaked to convert them from images to SVG fragments without any effort at optimisation. However, experimentation with https://squoosh.app/ suggests that many of the icons could be reduced by 50% or more.

[SVGO](https://github.com/svg/svgo) is the tool used by Squoosh to optimise SVGs. A quick script to use it to optimise all the SVGs in the ./core/images folder yields a total saving of 107,664 bytes from the resulting index.html.

**Comment by BurningTreeC** [comment]
Hi @Jermolene, the `file` and `line-width` icons each had a superfluous path (it was the first path) which is now hard-coded. The superfluous path is visible on IE, I can't provide Screenshots atm but wanted to let you know

**Comment by Jermolene** [comment]
Thanks @BurningTreeC I think you're referring to #4368 and #4369. How did you prepare those PRs? Is it easy to re-make them based on the recent updates?

**Comment by Jermolene** [comment]
Fixed in 015306dfc9099f4d5d9415b64266d328a154b119
