### ISSUE TITLE
How do I do nested transclusion within a codeblock?

### ISSUE THREAD

**Issue by braykov** [Jermolene/TiddlyWiki5#4380]
I have problems figuring out how to (properly) achieve the following:
I have a tiddler called "test". There are 3 fields in it:
- field a = `abc`
- field b = `def`
But 
- field c = `{{!!a}}-concat-{{!!b}}` 

When I just test with transclude, field c as `{{test!!c}}` in another tiddler I see the rendered concatenated value: `abc-concat-def`. But if I try to put it in a codeblock widget I get this its definition: `{{!!a}}-concat-{{!!b}}`.

Now what I eventually want is to display the value of test!!c within a codeblock with a copy-to-clipboard button.

**Comment by Jermolene** [comment]
Hi @braykov may I suggest that you ask this question on the TiddlyWiki forum? GitHub issues aren't really for general help, they are to help us keep track of outstanding bugs and investigations.

**Comment by braykov** [comment]
Done. Sorry about this.
