### ISSUE TITLE
Sort filter: Add support for stripping "stop words" from start of strings

### ISSUE THREAD

**Issue by Jermolene** [Jermolene/TiddlyWiki5#4394]
The sort operator largely exposes the underlying JavaScript `sort()` method, which is not language aware.

This means that strings like "The House" are sorted under "T", rather than "H", which would be conventional for alphabetical indexes (see the image below for an example).

It is proposed to extend the sort filter to support automatically removing "stop words" from the start of each string. The list of stopwords would be language specific, with English stopwords being shipped in the core, and others available via plugins.

<img src="https://user-images.githubusercontent.com/174761/71242128-26bdc100-2305-11ea-873f-de9cba29bc62.jpeg" width="300"/>

**Comment by pmario** [comment]
I need 2 or more sets of stop-words to be active at the same time. 
So imo it's not like the language switcher, which replaces tiddlers.

It's just the sort order, that is changed. The returned list-title is the full title. right?

just brainstorming.

**Comment by Jermolene** [comment]
> I need 2 or more sets of stop-words to be active at the same time.
> So imo it's not like the language switcher, which replaces tiddlers.

My rough thinking was that the sort operator would use tiddlers tagged $:/tags/Sort/StopWords each containing a list of words in their list field. Languages plugins would include a tiddler like $:/language/Sort/StopWords with that tag, and thus the default stop words would be switched as one switched language, but it would be easy enough to modify the list.

> It's just the sort order, that is changed. The returned list-title is the full title. right?

That's right, it means using a sort function that removes any prefixes before doing an ordinary string comparison.

**Comment by AnthonyMuscio** [comment]
Could this be implemented through a wsort operator (Word sort) or tsort (title sort) operator, just as we have nsort so people have to explicitly ask for this StopWords sort. Tiddler Titles may be titles of books, movies and other real world items but given the generic nature of tiddlers and their use in many different applications including as data or status or tag etc... I would think it unwise and possibly not backward compatible unless implemented under its own sourt operator.

**Comment by Jermolene** [comment]
Hi @AnthonyMuscio indeed this would be either an entirely new operator, or a new option on the existing "sort" operator.

**Comment by twMat** [comment]
I think this could be easily solved if filter ops like removeprefix have a *flag* to also allow lazy matching, i.e passing of titles that don't have the prefix.

Current behvariour:

`foo bar baz +[removeprefix[b]] ----> ar az`

Proposed, using flag

`foo bar baz +[removeprefix:lazy[b]] ----> foo ar az`

Sorting would could be done after or wherever.

**Comment by Marxsal** [comment]
Maybe the operator could take as a parameter the name of tiddler that contains the list of stop items? So you could sort items in one list by one language, another by another language, all in the same TW file?

**Comment by saqimtiaz** [comment]
@Jermolene copying here your [post on GG just now](https://groups.google.com/g/tiddlywiki/c/k1wCx3QtCc4):

One of my personal TiddlyWiki’s contains song lyrics and chords, with the default tiddler displaying a list of the songs sorted by title. It’s been annoying for a long time that the titles starting “The …” are sorted under “T”, and not the first letter of the following word.

The new sortsub operator in v5.1.23 has provided a simple means to resolve things:

```
\define sort-filter() [<currentTiddler>removeprefix[the ]] ~[<currentTiddler>removeprefix[The ]] ~[<currentTiddler>]

<$list filter="[tag[song]sortsub<sort-filter>]" template="$:/_SongItemTemplate"/>
```

The subfilter relies on the fact that the removeprefix operator doesn’t return anything if the input string doesn’t start with the specified prefix. Thus we can step through the prefixes we want to remove, finishing up with the original title.

A more complete version should perhaps strip the prefix “A ”  as well.

It would be nicer if we have a case-insensitive version of removeprefix.

**Comment by Jermolene** [comment]
Thanks @saqimtiaz that hack is probably sufficient for the moment so I'll close this for now.

**Comment by saqimtiaz** [comment]
@Jermolene I haven't tested this but I think you could also do this for more flexibility:

`[<currentTiddler>search-replace:i:regexp[^The |A ],[]]`

**Comment by Jermolene** [comment]
Good thinking @saqimtiaz perhaps we should add this as a new example for those two operators?

**Comment by saqimtiaz** [comment]
@Jermolene exactly my thoughts, just made a note to prepare PRs for docs when I wrote the above.

**Comment by saqimtiaz** [comment]
Here is yet another approach without `sortsub`, which I quite like for how it displays the list:

`<$list filter="[tag[song]search-replace:i:regexp[(^The |A )(.*)],[$2, $1]sort[]]" template="$:/:_SongItemTemplate>`

`The Richest Man in Babylon` becomes:
`Richest Man in Babylon, The`

**Comment by saqimtiaz** [comment]
PS: it will need some finessing to get the link pointing to the correct tiddler though.

**Comment by Jermolene** [comment]
Excellent, presumably we'll need separate filters for sorting and for display, but this is promising stuff.

**Comment by saqimtiaz** [comment]
Working on docs. Posting the full solution here in case someone comes across this later:

```
\define sort-filter()
[<currentTiddler>search-replace:i:regexp[^The |A ],[]]
\end

<ul>
<$list filter="[tag[song]sortsub<sort-filter>]">
<li><$link><$text text={{{[<currentTiddler>search-replace:i:regexp[(^The |A )(.*)],[$2, $1]]}}}/></$link></li>
</$list>
</ul>
```

**Output:**
![image](https://user-images.githubusercontent.com/68092/99510282-2996bb00-2987-11eb-8ee4-99597a8e2ed6.png)
