### ISSUE TITLE
title operator behaves inconsistently. Makes certain procedures impossible.

### ISSUE THREAD

**Issue by flibbles** [Jermolene/TiddlyWiki5#4400]
Title works like this: `[title[Cats]]` or even `[[Cats]]` will push Cats into the input stream, even if it doesn't exist as a tiddler.

However, `[!title[Cats]]` does not filter out Cats from the input stream, leaving only everything else like you'd expect. Instead, it filters out _all non-existing tiddlers_, and also Cats, if Cats existed. _search:title_ is the same way.

_field:title_ has the opposite problem. If an incoming item doesn't exist as a tiddler, then it ignores it completely and just passes it through.

Between all these operators, it is practically impossible to filter `B` out of `A B C` without doing something stupid like `+[!prefix[B]]`, which is error-prone. It's also literally impossible to filter out the empty string that results from `[join[]]` on an empty list, at least as far as I can tell.

Can we fix `[title[Cats]]` to only filter out `Cats`, and not also act like `[!is[missing]]`? I can make the PR with included tests in about an hour.

**Comment by flibbles** [comment]
Oh. `[!is[blank]]`. But still, `title` does not behave at it's documented.

**Comment by AnthonyMuscio** [comment]
Flibbles,

Without going into the validity of using the title as you do the way I would remove cats from the list is following with "run -[[Cats]]", but now you can also say "run!match[Cats]]" or if you defined the following
`\define nonfelines[] Cats`
you could have a filter with 
`"run!subfilter<nonfelines>]"`

I think the key to this different handling is in https://tiddlywiki.com/#title%20Operator
where it says "title is a constructor (except in the form !title), but field:title is a modifier."

normally field:fieldname[fieldvalue] can test if a given field contains fieldvalue and title is a field.

```
<$list filter="dogs cats frogs -[[cats]]">

</$list>
```

`dogs cats frogs -[title[cats]]` works

I think the best way to approach this is not try and use the title operator as a sophisticated operator, but use the field and other filters which are all oriented to dealing with titles anyway.

Regards
Tony

**Comment by pmario** [comment]
>Can we fix [title[Cats]] to only filter out Cats, and not also act like [!is[missing]]? I can make the PR with included tests in about an hour.

hmmm  I think this will be a backwards compatibility problem

**Comment by Jermolene** [comment]
Hi @flibbles it sounds like we need to improve the docs for the `title` filter, and extend it (or a new filter) in a backwards compatible way to give us the desired improved behaviour. Have you tried `field:title[Foo]`? it's subtly different than `title[Foo]`.

**Comment by flibbles** [comment]
I have. It's got the opposite problem. `[[NonExistent]!field:title[NonExistent]]` returns NonExistent, even though you'd think it would be filtered.

**Comment by Jermolene** [comment]
Does the 'match' operator help things?

**Comment by flibbles** [comment]
It does. `[!match[]]` basically does exactly what you'd expect `[!title[]]` to do. I guess I'll close this issue. I don't think title and field:title are behaving consistently, but I guess for backward compatibility reasons, it's probably best just not to bother and encourage _match_ instead.
