### ISSUE TITLE
Core should use new "match" operator instead of "prefix" operator for matching

### ISSUE THREAD

**Issue by kookma** [Jermolene/TiddlyWiki5#4407]
There are statement like this in the tiddlywiki

`<$list filter="[<tv-config-toolbar-icons>prefix[yes]]">`

The semantic way is 

`<$list filter="[<tv-config-toolbar-icons>match[yes]]">`

Hope these codes be improved!

**Comment by Jermolene** [comment]
Thanks @kookma fix upcoming, let me know if I've missed any.

**Comment by kookma** [comment]
Thanks @Jermolene 
I will check the new update and will inform if any!
