### ISSUE TITLE
$:/tags/RawMarkup is not taken in account if plugin is disabled

### ISSUE THREAD

**Issue by danielo515** [Jermolene/TiddlyWiki5#4415]
Hello.
This is partly a report and partly a question, because it may be intentional. Or maybe it is not intentional but you think it is desirable.
The thing is, if a plugin that contains any tag that injects stuff into the HTML file  (tags like `$:/tags/RawMarkup` or `$:/tags/RawMarkupWikified/TopBody`) is disabled then those tiddlers are not injected on the resulting html file.
This is normal you may think, but if the user decided to include the plugin (for example, it is on the save filter) then the plugin will need this mechanisms to be executed when the file is downloaded in order to work in the resulting html file.

Let me know what  do you think about this.

**Comment by Jermolene** [comment]
Hi @danielo515 interesting! The basic principle here is that a disabled plugin should act as if it were just an ordinary tiddler, and not have any of the special behaviour of plugins (including making the shadows available). On that basis, it would clearly be wrong for a disabled plugin to contribute any markup tiddlers during a save.

I think this is really the same problem as we have with the installation of such plugins in the first place: a save and reload is needed to activate the markup tiddlers.

**Comment by danielo515** [comment]
Yes, after thinking about it a while I see the problem. One of the great things I love about TW is how it uses it's own semantics for almost everything, and in this case the everything expects disabled plugins to not be "expanded" hence not contributing to the space of "existing" tiddlers.
It is basically what you said but I wanted to put it on my own words, sorry about that.

This has been a major pain point for NoteSelf since the very first day, because I always wanted to mimic the ability of tiddlywiki.com to download a working copy of itself.
The problem is that I don't want the plugin to be active on the main site (because it is very intrusive) so I have to flag is as inactive. But I want the user to be able to download an offline working version built from the main site itself, so I need the head tiddlers of the plugin to be injected while downloading (and a lot of other ceremonies that are quite hard to remember).
This is, now that I see it with perspective and a lot of more experience,  probably a stupid requirement that I imposed to myself. It will probably better to just build an offline version during CI, not include the plugin at all on the main site, and just handle it as a normal file download.

Thanks for your prompt response!

**Comment by danielo515** [comment]
By the way, will it be possible to render a tiddler from a disabled plugin using the subTiddler property/filter or however is called?

**Comment by Jermolene** [comment]
> It will probably better to just build an offline version during CI, not include the plugin at all on the main site, and just handle it as a normal file download.

Indeed, I think that makes sense.

> By the way, will it be possible to render a tiddler from a disabled plugin using the subTiddler property/filter or however is called?

Yes I think that should work.

**Comment by danielo515** [comment]
Will `tm-download-file` support downloading an external file in any way? 
Probably a stupid idea and it is better to just use a link with a dowload property.
