### ISSUE TITLE
Add actions to link widget?

### ISSUE THREAD

**Issue by AnthonyMuscio** [Jermolene/TiddlyWiki5#4430]
Folks,

The link widget is a trigger or sorts. Would it be possible for it to be extended to include an actions= parameter so that custom actions could be assigned to links that are actioned when the link is clicked?

Thanks
Tony

**Comment by Jermolene** [comment]
Hi @AnthonyMuscio the link widget doesn't support actions because the expectation was that the link-catcher widget would be used to apply actions to a whole set of links in one go. Would the linkcatcher widget work for you?

**Comment by AnthonyMuscio** [comment]
Got, It, it looks right, I will close and return look for help if I can't get it working thanks
