### ISSUE TITLE
more math operators

### ISSUE THREAD

**Issue by kookma** [Jermolene/TiddlyWiki5#4431]
Is there any reason TW does not have the below operators?

1. power like "1 2 3 +[power[2]]
2. sqrt or other fractional power like "1 2 3 +[sqrt[]]" or "1 2 3 +[power[0.5]]"
3. some useful statistical functions like
  - mean
  - std
  - median

**Comment by Jermolene** [comment]
Hi @kookma I think those are all good candidates for inclusion.

**Comment by kookma** [comment]
Hi @Jermolene 
Thank you for your prompt reply and your support for inclusion into TW.

Following the discussion at forum https://groups.google.com/d/msg/tiddlywiki/jNATAnqE_KI/Q4Jb9D5XFQAJ

I think the power and log are important basic mathematical operators need to be added.

I have given a use case there!

The statistical functions like mean, median, variance, and standard deviation can be the next priority.


```
"1 2 3 +[std[]]"
"1 2 3 +[var[]]"
"1 2 3 +[mean[]]"
" 1 2 3 +"[median[]]"
```

**Comment by diego898** [comment]
I'd just like to point out Evan's Formula plugin:

https://evanbalster.com/tiddlywiki/formulas.html

At one point Jeremy said he's not immediately against including it (or major pieces) in the core. Just adding this here for completeness, and to avoid duplication of efforts.

**Comment by kookma** [comment]
Diego
 Many thanks for the reference. If Jeremy add only power and log operator, I can use wikitext and do many of the above operations.

I think this is fastest.
