### ISSUE TITLE
Doc Bug for Button Widget

### ISSUE THREAD

**Issue by Marxsal** [Jermolene/TiddlyWiki5#4435]
The docs say:

```
setField | A field name to which the new value will be assigned, if the attribute stateTitle is present. Defaults to the text field
-- | --
setIndex | An index to which the new value will be assigned, if the attribute stateTitle is present

```

But there is no "stateTitle" attribute defined. But there is "setTitle" attribute. Perhaps a cut/paste error from the Reveal widget?

**Comment by Jermolene** [comment]
Thanks @Marxsal fixed here: b454e809f35679ff3547ea5c45f2bf44c7bf0661
