### ISSUE TITLE
Request: ViewWidget format to show links

### ISSUE THREAD

**Issue by twMat** [Jermolene/TiddlyWiki5#4438]
On the forum there was a question how to make `<$view field=foo/>` show linkified links (instead of brackets and non-linkified CamelCase). Indeed - how!?

**Proposal**
For the ViewWidget `format` attribute, introduce some argument that turns intended links into actual links. (What is this called actually? "wikify/wikified" seems to refer to the opposite ref e.g the wikify widget)

**Comment by Jermolene** [comment]
The answer is to use the `<$transclude field=foo/>` widget instead (which is much more performant than the view widget).

**Comment by twMat** [comment]
OK, I'll make a PR to the doc for the ViewWidget to inform about this.
