### ISSUE TITLE
diagram/discription of tiddlywiki architecture?

### ISSUE THREAD

**Issue by dubiouscript** [Jermolene/TiddlyWiki5#4439]
EDIT!

https://tiddlywiki.com/dev/  - contains "Microkernel Architecture" + other relevant info/diagrams :tada: 
++
wrt : gitlab saver 
from https://web.archive.org/web/20200205195506/http://docs.gitlab.com/ee/user/project/pages/
an over view diagram of the pages deploy pipeline 
https://web.archive.org/web/20200109110852/https://docs.gitlab.com/ee/user/project/pages/img/new_project_for_pages_v12_5.png

interestingly relevant 'conceptual overview on static versus dynamic sites.' 
https://web.archive.org/web/20200209110015/https://about.gitlab.com/blog/2016/06/03/ssg-overview-gitlab-pages-part-1-dynamic-x-static/
ven: ( tiddlywiki ( "A conceptual overview on static versus dynamic sites." ) gitlab-pages )
 
---

looking around tw
i found/discovered the "Discover TiddlyWiki"  tiddler/page/fragment 
https://tiddlywiki.com/#Discover%20TiddlyWiki

        a tool, 
        a toolbox, 
        a community, 
        and a philosophy. 

im told that 
> You've never seen anything like TiddlyWiki 

 indeed! 

but what im still wandering is what is tiddlywikis architecture?
ftr:( what i have in mind as i write 
is this 
https://web.archive.org/web/20200209110138/https://i.imgur.com/qZPdReo.png
an incredibly concise over view
of a fairly alternative OS/distro
that in some ways has alot *wrt  alt architecture* in common with tidlywiki)

:thinking: 
if it is 
 - tiddlers all the way down!
how are they constructed / contained ?
and why they are  constructed / contained  that way ?

---

... 
some perhaps more practical 
simply answerable questions ..

- exactly how dose tiddly wiki replicate/recreate a copy of its self ?

- what is the  minimum knowledge of tidlywiki : "syntax / env / functions" 
  needed to understand this process
...

- what i am atempting is to insert plain-text / "raw html"
 before the 
> <.!--~~ Raw markup for the top of the body section ~~--.>

line 

---
i have managed to find 
$:/core/templates/tiddlywiki5.html

where it appears i could just add some raw-html , and be done!

how ever i would like to try to grock the curent process / how the bits actually fit together / what functions do what ect  

iv read a bit about  "raw markup" tags
https://github.com/Jermolene/TiddlyWiki5/issues/4415

https://github.com/Jermolene/TiddlyWiki5/issues?utf8=%E2%9C%93&q=is%3Aissue+rawmarkup

https://tiddlywiki.com/#SystemTag%3A%20%24%3A%2Ftags%2FRawMarkup

 that appear in this section 
of $:/core/templates/tiddlywiki5.html
> < !--~~ Raw markup for the top of the body section ~~-- >
>`{{{ [enlist<saveTiddlerAndShadowsFilter>tag[$:/tags/RawMarkupWikified/TopBody]] ||$:/core/templates/raw-static-tiddler}}}`

what is the function of the above line =S 

??  list  | ?? filter tag[ name] |  template 

what X operator's dose?

---

is there/could there be 
 some kind of reverse tiddlywiki operator look up  ?
a sort of quick reference
 for the forgetful and or those uninitiated in the tiddlywiki way
edit: found =  "Wikitext Markup Reference" @ https://tid.li/tw5/plugins.html 
https://tid.li/tw5/plugins.html#Wikitext%20Markup%20Reference
&+ https://tiddlywiki.com/editions/full/#%24%3A%2Fplugins%2Ftiddlywiki%2Fhelp

---    
..
 
https://tiddlywiki.com/#tag%20Operator
 
~i did try tagging  a new tiddler but it was not found / did not appear
& tbh idk *exactly* what im doing =]~

^.^

...a "weird" cache issue 
https://github.com/Jermolene/TiddlyWiki5/issues/4239#issuecomment-582366122
was causing me a grate amount of confusion/frustration `(-:UX;-)`

 --

> ~~ It's only wafer thin ~~

**Comment by twMat** [comment]
@dubiouscript - here on github we try to keep issues concise and actionable. May I advise that you copy your post and repost it in the discussion forum, possibly in the [dev forum](https://groups.google.com/forum/#!forum/tiddlywikidev) AND close this thread here (because it will, 100% sure, remain unsolved here). It is a good general idea and, I'm sure you agree, would require quite a bit of discussion before anything can be done. Hopefully you'll engage some of the system-knowledgeable guys (of which I'm not one).

**Comment by dubiouscript** [comment]
hi @twMat =]
wrt 
>discussion forum, possibly in the dev forum 

i opened the link and my system/browser slowdown and froze!! =[ =S
... the web is a crazy place in 2020 

> Hopefully you'll engage some of the system-knowledgeable guys (of which I'm not one).

imho 
if you were to look at a "tiddlywiki architecture diagram" you would automagically 
gain a knowledgeable over view of the system  and  therefore be a member of the set of the "system-knowledgeable" 

:robot:

**Comment by dubiouscript** [comment]
@TiddlyWiki5
>:question:> what is tiddlywikis architecture?

>IT's very sophisticated and a bit tricky
https://gitter.im/TiddlyWiki/developers-and-geeks?at=5b71360f67eb9f60fed2afa6

@pmario  ( imho this quote should be tiddlyifyed in the dev wiki )

:+1:

> IMPORTANT have a very close look at the backticks in the code !!!

... why ?

..& do the "backticks in the code" have a static .html reference url ?

 /.tid

**Comment by dubiouscript** [comment]
>:question:> what is tiddlywikis architecture?

https://gitter.im/TiddlyWiki/developers-and-geeks?at=5b71360f67eb9f60fed2afa6

> IT's very sophisticated and a bit tricky

:+1:
:laughing: 

> IMPORTANT have a very close look at the backticks in the code !!!

@pmario 

... why ? 
.. what *exactly* do the "backticks in the code " do ??
.. is there a static HTML page/url describing this IMPORTANT "backticks in the code " functionality ??

**Comment by dubiouscript** [comment]
> it made me realize the appeal of this single page application (pour moi)
> was (previously) being able to scroll over all the html source form start to finish


https://pastebin.com/bs97y6qa - TiddlyWiki 1.0 (1400 lines )

https://github.com/Jermolene/TiddlyWiki5/blob/master/core/modules/wiki.js - TiddlyWiki5 wiki.js module  (1400 lines )

**Comment by dubiouscript** [comment]
still digging  =]

https://github.com/Jermolene/TiddlyWiki5/issues/4456#issuecomment-586373885

> When the story river itself is deleted and recreated we lose the scroll position.
> 
> This is a fundamental problem with the current design: we lose a lot of state from the DOM when widgets are deleted and recreated as part of the refresh cycle (selection status, focus, scroll positions, the state of summary/detail widgets etc).
> 
> The lack of state preservation is a major flaw that I’d like to see fixed. We have some proposals for partial solutions that work for some state in some situations, but we really need a rethink that makes state preservation just work across the board. One possibility is adopting a more conventional virtual DOM strategy for updating the DOM.

**Comment by kookma** [comment]
@dubiouscript 
You started very interesting topic. As Mat said it is good to share this in Forum and lets discuss in details.

**Comment by dubiouscript** [comment]
@kookma 
google groups is a mailing list 
and IMHO 
not very good mailing list ( they hoard the plain text )

:grimacing: 

other `actual` forums exist  
better mailing lists servers exist ( with actual text archives , i can grep :exploding_head:  ) 

so hear we are in the MS owned *null space*  @  git hub 

¯\_(ツ)_/¯

**Comment by dubiouscript** [comment]
++

https://github.com/linonetwo/solid-tiddlywiki-syncadaptor

https://raw.githubusercontent.com/linonetwo/solid-tiddlywiki-syncadaptor/master/docs/diagrams/getSkinnyTiddlers.png

sync adapter saver diagram 

=]
