### ISSUE TITLE
Request: Memory variable filter ops

### ISSUE THREAD

**Issue by twMat** [Jermolene/TiddlyWiki5#4452]
**Problem**
In a filter run, the "context" can easily be lost - for example here: `[tag[foo]get[text]]` - the tiddler titles are lost. To get around this one typically has to *nest* lists and save the outer filter results in some variable that can be retrieved in the inner.

Another problem is described [here](https://groups.google.com/d/msg/tiddlywiki/XJ0D5f9QZao/n4a1ZAEUBQAJ), where nested listwidgets cause duplicates - so you're forced to externalize the nesting into a macro and do a wikify on it. This is complex and not obvious.

**Proposal**
Enable storing of *intermediate* filter results for later use, via "memory filter ops", e.g `memoryin[var1]` where ´var1´ is a user constructed variable name. This can then be recalled in the succeeding part of the filter expression with `memoryout[var1]` - or maybe even within the scope of the widget with `<<var1>>` (do note that the content is probably a list).

This should omit the need for nesting lists unless it is desired.

**Implementation**
I'm guessing that already now each filter step result is temporarily stored in some variable as input for the next filter step... so `memoryin` would just copy this temporary value.

**Ideas for operator names** 
memoryin/memoryout, memin/memout, m-in/m-out, store/recall, mem/mrc, push/pop
(I prefer the ones based on the same word, e.g memin/memout for a more obvious pairing.)

**Comment by AnthonyMuscio** [comment]
Mat,

Very close to your proposal.

Perhaps allowing the result to be pushed into a named variable with a set operator?

[tag[foo]set[varname]get[text]set[body-text]]

Such that within the widget list or template you can use <<varname>> and <<body-text>>,

However if a subsequent filter removes the item from the list you will never see all these variables.

[tag[foo]set[varname]get[text]set[body-text]] -[[hidden[yes]]

I have no idea how to implement it but it may be a simpler way forward. Ie it not so much as pushes and pops but just passes the newly set variable through if the title gets thru.

Regards
Tony

**Comment by pmario** [comment]
If you do have a variable you call it with eg: `[enlist<variableName>]` So imo there is no need for a pop. You have to use enlist anyway, since you don't know, if it is an array.

**Comment by pmario** [comment]
>  [tag[foo]set[varname]get[text]set[body-text]]

I think, that this one is a mix, which isn't needed. ... `varname` will be `<<currentTiddler>>` and <<body-text>> will be {{!!text}} in the template. So the above can be solved already.

**Comment by pmario** [comment]
> ..for example here: [tag[foo]get[text]] - the tiddler titles are lost.

But you don't need them. eg: `<$list filter="[tag[foo]]"><<currentTiddler>> - {{!!text}}</$list>` gives you everything that you need. 

So I think, you need to give a real example, that can't be easily solved in a common way.

**Comment by saqimtiaz** [comment]
> In a filter run, the "context" can easily be lost - for example here: `[tag[foo]get[text]]` - the tiddler titles are lost. To get around this one typically has to _nest_ lists and save the outer filter results in some variable that can be retrieved in the inner.

Since this PR was created there have been several filter run prefixes introduced that help avoid this issue: `:filter`, `:map` and `:reduce`.

Furthermore it is important to note that filter operators cannot set variable values for the widgets using them. That simply isn't how filters are implemented, and with good reason since they need to be usable in different contexts.

I think this issue should be closed. If there are use cases for **filter operations** that cannot be accomplished with existing operators, please give specific examples.

**Comment by twMat** [comment]
Thanks for input everyone.
Closing.
