### ISSUE TITLE
bug/feature? gitlab-saver (working)  :  "access token" field was cleared / reset

### ISSUE THREAD

**Issue by dubiouscript** [Jermolene/TiddlyWiki5#4455]
while testing the gitlab saver ( its working well ! ftr https://github.com/Jermolene/TiddlyWiki5/pull/4243) 

the  "access token" field 
was reset/cleared 

is this  intentional  or error ?
is it a feature or a bug ?

... :memo:  documentation or :bug:  investigation :thinking: 

js console shows nothing unusual 
>saver-handler: Saving wiki with method save through saver gitlab $:/core/modules/util/logger.js:33:10
>saver-handler: Saving wiki with method save through saver download $:/core/modules/util/logger.js:33:10

i made no modification to  "access token" field 
it `auto-magically` happened some how 

not expecting this 
i cancelled the 
- 'download saver' dialog ( thinking is was from some other tab  )

.. several times!
 before realizing something had changed  wrt to saving methods =S
and therefore no saveing was actually happening

**Comment by pmario** [comment]
Did you use a "private tab" in the browser to access gilab?

**Comment by dubiouscript** [comment]
> Did you use a "private tab" in the browser to access gilab?
indeed!

why would that make difference?

**Comment by pmario** [comment]
The access token is written to the browser local storage. I think closing the tab removed the token, because of private-mode

**Comment by dubiouscript** [comment]
i did not close the tab  !

++ also afaik there is no way to clear the 'private' history/cookies/storage ect 
with out  browser restart

**Comment by Jermolene** [comment]
> afaik i did not close the tab ! ( it is still open/ has been for a while! )

Most browsers nowadays pretty aggressively unload open tabs that haven't been viewed for a while. Generally, reloading the page will restore things to their previous state, but not in the case of incognito tabs.

**Comment by dubiouscript** [comment]
ok 
i will close  this as it appears to be 
less tiddly-wiki related 
and 
more browser / timeing specific
