### ISSUE TITLE
 Saving to a Git service 

### ISSUE THREAD

**Issue by JOduMonT** [Jermolene/TiddlyWiki5#4467]
While I try to:  **Saving to a Git service**
![image](https://user-images.githubusercontent.com/5204724/75221629-e2ebaa00-57d4-11ea-8fb0-c0a412e6c2f5.png)

I receive an: **XMLHttpRequest error code: 401**
I created my git Repo and a Personal access tokens which I gave:
![image](https://user-images.githubusercontent.com/5204724/75221514-986a2d80-57d4-11ea-82b0-a3dc77767bfe.png)

I tried with an emtpy Repo and with a Repo which contain README.md without success

**Comment by pmario** [comment]
did you try a case sensitive username?

**Comment by JOduMonT** [comment]
@pmario 

> did you try a case sensitive username?

Nice try for a moment I truly believe you but nope it is not the solution :(

![image](https://user-images.githubusercontent.com/5204724/75251845-febf7200-580d-11ea-80ff-a10aabc557cc.png)
