### ISSUE TITLE
GitLab saver not working

### ISSUE THREAD

**Issue by gabriel-seoworks** [Jermolene/TiddlyWiki5#4469]
## Summary
I can't seem to make the GitLab saver work. I have GitHub saver working correctly in the same TiddlyWiki.

I've given ever permission that exists to the personal access token. And I've made sure that both the branch and file I want to commit to already exist.

## Context
- Operating system: MacOS Catalina
- Browser: Firefox v72
- TiddlyWiki url: `file:///[my-tiddlywiki]`
- Saver authentication: `Username` + `Personal access token`
   - Personal access token scope: `api`, `read_user`, `read_repository`, `write_repository`, `read_registry`
   - Personal access token expiry: `never`
- Target repository: `[my-organisation]/[my-repository]`
- Target branch for saving: `[custom-branch]` (not `master`)
- Path to target file: `/`
- Filename of target file: `[my-tiddlywiki]`
- Server API URL: `https://gitlab.com/api/v4`

## Steps to Reproduce
- Make a change to my TiddlyWiki
- Click `Save`

## Result
Browser says:
`XMLHttpRequest error code: 400`

Console says:
`Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://gitlab.example.com/api/v4//projects/[my-project-name]/repository/tree/. (Reason: CORS request did not succeed).`

## Thoughts
The CORS things seems to be a red herring as the GitHub saver is working correctly.(?)

Is it possible that a rogue second `/` has crept into the API call somehow (after `v4`) and is breaking the call? Seems weird as I don't even have a final `/` on the relevant setting in the saver:

$:/ControlPanel > Saving > GitLab Saver > Server API URL:
`https://gitlab.com/api/v4`

**Comment by pmario** [comment]
Does the save work, if you load the wiki from GitLab pages? .. So you can be sure your settings are correct. 

The saver isn't intended to save from a file-URI to an http-URI since latest browsers generally disallow such a behaviour.

**Comment by gabriel-seoworks** [comment]
I see, I didn't understand the purpose of how it is intended to be used.

My use case requires the repository to be private (it was going to be published elsewhere by another process), so it doesn't really fit into this model. Thanks for explaining 👍

It might be worth updating the docs to make this a bit clearer - https://tiddlywiki.com/static/Saving%2520to%2520a%2520Git%2520service.html

**Comment by pmario** [comment]
Doesn't GitLab allow private pages?

**Comment by pmario** [comment]
see: https://docs.gitlab.com/ee/user/project/pages/pages_access_control.html .. I didn't test and didn't read the docs, just found the link

**Comment by gabriel-seoworks** [comment]
I didn't realise that was a thing - thanks for suggestion. I was able to deploy my Tiddlywiki from a private repository to a publically accessible `gitlab.io` address, with those extra options changed.

I ended up tweaking the file structure of the branch with the Tiddlywiki in it. It is now `/public/index.html`, but otherwise no other changes were made. The relevant fields in the saver were updated to reflect this.

But unfortunately I still can't save back to the repository - still get 400 error. There's nothing in the console this time.

(As before, I'm using a personal access token with all privileges enabled.)

**Comment by pmario** [comment]
You should probably use GoogleGroup and ask if someone can help. I don't use Gitlab saver at the moment.

**Comment by pmario** [comment]
just in case ;) https://groups.google.com/forum/#!forum/tiddlywiki

**Comment by dubiouscript** [comment]
wrt : git lab saver : 'Target repository' 

its probably worth noting that ( in case its not obvious )
that git lab saver uses the api https://docs.gitlab.com/ee/api/README.html

and that the 'Target repository'  path value can be the target project ( id / iid ; i only used iid see bellow quote & link  )

see https://docs.gitlab.com/ee/api/README.html#id-vs-iid

> Note: The iid is displayed in the web UI.

i did not have much luck using the project path as 'Target repository'  value

presumably because it requires escaping 
i think i have encountered this (necesity to escape project paths) when using the gitlab api via other means 
https://gist.github.com/dubiouscript/5553dce89497ffd9805dd0de16503e8d
