### ISSUE TITLE
any method exist? to set  default tiddler icon for all tiddlers @ $:/core/ui/ViewTemplate/title

### ISSUE THREAD

**Issue by dubiouscript** [Jermolene/TiddlyWiki5#4474]
adding 
field icon with 
value $:/core/ui/Buttons/fold 
works only for individual tiddlers 

but it appears no way to create default 'icon' field value for the 'view template' exists

default appears to be set in $:/core/ui/ViewTemplate/title

at line

```
 <$transclude tiddler={{!!icon}}/>
```

 is it  possible to expose a setting/option that will over ride the icon if  icon field is empty / not set 

if so how!? can it be done 

thanks

**Comment by Jermolene** [comment]
Hi @dubiouscript that makes sense, I've committed a fix here:

https://github.com/Jermolene/TiddlyWiki5/commit/6091b013864af3d9918df69894f4aa05d1b8ffeb

**Comment by dubiouscript** [comment]
ftr 

`<$transclude tiddler={{!!icon}}>
<$transclude tiddler={{$:/core/ui/ViewTemplate/title!!icon}}/>
</$transclude>`

appears more or less of a criptic / hidden 
eg : seting the icon feild from $:/core/ui/ViewTemplate/title template
changes each tiddlers icon 

this appears more 'in tune' with the idea of templateing , imho
