### ISSUE TITLE
advanced search permalink  : include the (encoded) search string

### ISSUE THREAD

**Issue by dubiouscript** [Jermolene/TiddlyWiki5#4475]
advanced search permalink 
> #%24%3A%2FAdvancedSearch

should include the (encoded) current search  in the url hash section 

EG

> #%24%3A%2FAdvancedSearch?search=find+this+string

$:/core/ui/AdvancedSearch/System

imho this would be useful as it would allow  linking to previous searches

any hint as to how this might be achieved?

**Comment by Jermolene** [comment]
One can link to searches like this: https://tiddlywiki.com/#:[search[jeremy]]

**Comment by dubiouscript** [comment]
interesting !  

> One can link to searches like this: [https://tiddlywiki.com/#:[search[jeremy]]](https://tiddlywiki.com/#:%5Bsearch%5Bjeremy%5D%5D)

it appears this would be more or less the equivalent of 

> #%24%3A%2FAdvancedSearch?tab=filter&search=jeremy

except that this 'filter search' link https://tiddlywiki.com/#:[search[jeremy]]

only displays/loads the resulting tiddlers 

instead of displaying/loading/selecting the advanced search box / tab  and populating the textinput

**Comment by Jermolene** [comment]
Hi @dubiouscript indeed. The share plugin allows one to create links that embed tiddlers to be injected into the wiki. For example:

https://tiddlywiki.com/prerelease/share.html##%5B%7B%22created%22%3A%2220200309213612557%22%2C%22title%22%3A%22%24%3A%2Ftemp%2Fsearch%22%2C%22text%22%3A%22jeremy%22%2C%22modified%22%3A%2220200309213613093%22%7D%5D

**Comment by dubiouscript** [comment]
interesting!

 without creating 'links that embed tiddlers to be injected into the wiki.'
( sounds a bit brasseye;) .. :cake:  anyone one :smile_cat: 

... which i guess would appear to be a disadvantage of enabling this sort of permalink??

> #%24%3A%2FAdvancedSearch?search=find+this+string

could *some other* form of "search history" be created from the `search box input` ?

eg : saving a list of the last N  searches

**Comment by Jermolene** [comment]
Injecting arbitrary page content via the URL is a major vector for "cross site scripting" security flaws, so we don't do it by default.

**Comment by dubiouscript** [comment]
>Injecting arbitrary page content via the URL is a major vector for "cross site scripting" security flaws, so we don't do it by default.

i guess this generally makes sense 
...
if the saver is 
- hosting the content 
- requires a token to save & logs history , 

 it would appear to be a bit less of a concern ,.. imho
all though thinking about this case more , it might be relatively simple to script

still  some kind of `~/.tw_search_history` would be nice to have , addition :thinking:
