### ISSUE TITLE
Menu Plugin: Sidebar chevron not visible on narrow screens

### ISSUE THREAD

**Issue by BurningTreeC** [Jermolene/TiddlyWiki5#4477]
The sidebar - chevron disappears when the screen gets narrow

**Comment by Jermolene** [comment]
That was intentional, but perhaps it does make more sense to keep it visible when narrow.

**Comment by BurningTreeC** [comment]
>perhaps it does make more sense to keep it visible when narrow.

I would say so

**Comment by Jermolene** [comment]
It turns out not to be so easy with the current code because when the menubar is narrow the items are display: block to make them stack vertically. The code is already fairly hairy but I'll investigate further.

**Comment by twMat** [comment]
Many services that have the equivalent of a sidebar use a popout from the side for narrow screens. I find this superior to something that affects the scroll, especially since our sidebar tabs are so tall.

**Comment by Jermolene** [comment]
Hi @twMat I think that's a separate issue, isn't it? This is one is about the visibility of items in the menu bar.

**Comment by twMat** [comment]
You're right. My bad.

**Comment by Jermolene** [comment]
My intention had been for the toprightbar buttons (including the sidebar chevron) to move into the hamburger menu when the screen is narrow, now fixed.
