### ISSUE TITLE
Request: Filter op to extract regexp from string

### ISSUE THREAD

**Issue by twMat** [Jermolene/TiddlyWiki5#4479]
**Problem**: Extract segments from strings.

**Solution approach/proposal**:
These are the most general string extraction manipulations I can think of, for which it would be useful to have direct filter ops:

1. extract the string up until before the first occurrence of regexp R
2. extract the first occurrence of regexp R
3. extract the string from after the first occurrence of regexp R

I.e view the string as consisting of "pre+R+post" parts. Yes, you can probably get the same results by combining already existing filter ops but, besides that this is frankly [very difficult](https://groups.google.com/d/msg/tiddlywiki/x19fLoGNews/-XpnPhZcAwAJ) and complex, my point is these three cover such fundamental use cases in string manipulation that they ought to be primitives. (Maybe it can even be considered to be a *single* fundamental use case, i.e "do something with a segment of a text while also keeping track of its context".) Of course, the *post* part can be further investigated for additional occurrences.

For syntactical reasons, I suggest a **single operator** for this that uses flags to specify *pre* and *post*, e.g: "extract:pre" or "regextract:pre". Noflag/default is "extract regexp R".

In the related post, #2963 , there is discussion if that proposal should be a *widget* instead. I would argue this is more suitable as filter ops because:
* after the extraction, it is reasonable to expect further (filter) manipulations to be needed for the output
* since the beginning of that discussion (2017) the TW "filter language" has been further enriched and filter ops is the *main modus operandi for finer manipulations* in TW. To quote the [docs](https://tiddlywiki.com/prerelease/#Widgets): "Widgets are analogous to elements in an HTML document." which IMO does not rhyme with the manipulations we're discussing.
* ...in particular, a palette has shaped with dedicated *String Operators* where ops for the basic use case outlined above would fit right in.

**Comment by TiddlyTweeter** [comment]
Ciao Mat. Extraction of sub-strings in REGEX (not all string situations) are economical via "(capture)" groups. Its the easiest way. In software that utilises the output of regex captures then you can do anything with them. The key point is saving the JS captures. Technically re-parsing "$&" would make less sense than just returning $1, $2 etc directly from captures in the case of regex. My point ... JS regex already via capturing groups can return what you are asking about.

**Comment by twMat** [comment]
Are you saying that with one regex, js can capture all three parts in a string in the way I refer to in the OP? I guess the more specific you can be the more useful for anyone who intends to actually implement this. Unless you think it is trivial for a js coder, or problematic for you, could you give an example of how using "(capture)" groups and $1,$2,$3 would split this paragraph into the pre-R-post I talk about? Thank you.

**Comment by TiddlyTweeter** [comment]
Regex you can't specify like code as its very context dependent. 

"First part R After part" could be captured via "^(.+? )(R)( .+)" to 3 groups. There is a cheat in it is using the spaces to isolate "R". You could do it like this too: "^(.+?) (R) (.+)" which discards the spaces before and after R. Depending on "R's" context you alter the pattern to suit.

In other words regex issue is less ability to return group match (easy) as honing match so its precise enough for the context.

**Comment by Jermolene** [comment]
Hi @twMat the reason I've proposed a widget is because filter operators can only return a list of results, and we need to return more information than that. See https://github.com/Jermolene/TiddlyWiki5/pull/3502#issuecomment-434262591

**Comment by twMat** [comment]
Closing in favor of [#3502](https://github.com/Jermolene/TiddlyWiki5/pull/3502#issuecomment-434269701).
