### ISSUE TITLE
Extend Modal to allow custom class for customization

### ISSUE THREAD

**Issue by saqimtiaz** [Jermolene/TiddlyWiki5#4485]
Being able to add a custom class to the modal wrapper allows for customization via css.
As an example, it opens the door for resizable modals using only CSS.

This could be accomplished by either providing the custom class in the parameters to the tm-modal message, or via a field in the tiddler to be transcluded in the modal.

**Comment by Jermolene** [comment]
Hi @saqimtiaz that's a good idea. I think perhaps it would be more in keeping with the current implementation for the class to be a field on the modal tiddler.
