### ISSUE TITLE
Request: Update CodeMirror and Highlight.js plugins in 5.1.22p

### ISSUE THREAD

**Issue by kookma** [Jermolene/TiddlyWiki5#4487]
**CodeMirror**
There are some requests for updating the CodeMirror in 5.1.22p. Seems there are some issues reporting here: https://groups.google.com/d/msg/tiddlywiki/4NGCvCJObhc/i_CsytpCAwAJ

**Highlight.js**
There was a bug in highlighting numbers in some language like fortran (e.g 12.23_wp) which addressed in new Highlight.js update. It would be nice to update the Highlight.js in 5.1.22p

**Comment by BurningTreeC** [comment]
Thanks @kookma...

@pmario, what would you say, shall we update?

**Comment by pmario** [comment]
We didn't get feedback from George "bluespire" ... So may be I scared him a bit too much ;)

There have been several changes to the javascript mode for eg: new elements like "arrow functions" and some such. If I did read the release notes right. 

Our last cm version is from April 2018 so I think it would be worth an update. 

----------

I did want to play with CM-V6-next and create a new TW5 syntax-mode + hints, but the new "parser" is a real parser optimized for highlighting now. see: [Lezer-parser](https://lezer.codemirror.net/)

The time needed to deig deeper is much higher, than I anticipated. 

---------------

So adding to CM-5 is worth a new thought.

 - There is also a new option, that would be nice: https://codemirror.net/addon/edit/trailingspace.js ... which would add nicely to an option I did implement as an [experimental parser addOn for Tony](https://groups.google.com/forum/#!topic/tiddlywiki/BJe7X-0jhSc). 

 - edit/continuelist.js ... needs some modifications, but could be nice add for TW too.
 - runmode/runmode.js and
 - runmode/colorize.js ... would make it possible to make highlight.js obsolete, if CM is used. 
 - merge/merge.js ... 
 - mode/overlay.js
 - mode/multiplex.js

All of that stuff would be nice addOns, if we really want to invest some more time into CM-V5.

**Comment by BurningTreeC** [comment]
@pmario I was thinking that it's worth waiting for cm6 and just keep our cm5 plugins up to date. If you'd like to add some plugins, I'm totally fine with that

**Comment by pmario** [comment]
With TWclassic I did use TW exclusively as a development environment, so an up to date CM editor was critical for me. 

With TW5 I'm using brackets.io editor (which uses CM5 :) because it has "inline code viewing and editing" and a really great git-plugin. 

So CM in TW isn't essential for me anymore. ... That's the main reason, why I didn't bother to create a "runmode" plugin, because highlight.js is just good enough.

**Comment by kookma** [comment]
@BurningTreeC 
is it possible to have the latest stable version of Highlight.js?

**Comment by pmario** [comment]
## Proposal

Let's move CodeMirro Plugin out of the `plugins/tiddlywiki/ path to `plugins/codemirror5`. There is a CM 6 on the way. So this would make it simple to keep them separated 

AND more important

We could simplify the UI again. TWprerelease is super errorprone if you want to install CM elements. 

The install UI is different to the ControlPanel plugin UI. So it's even confusing for me, and I should know, what to do. 

I hope, I can find some time at the weekend. cu. 

@Jermolene what do you think about the move to a separated directory?

**Comment by Jermolene** [comment]
>@Jermolene what do you think about the move to a separated directory?

Interesting idea! It is not quite how the naming scheme was intended to work, of course.

But I'd prefer to fix the problems that you've identified with the UI.

**Comment by kookma** [comment]
@BurningTreeC 
Is there any chance to update Highlight.js?

**Comment by pmario** [comment]
@BurningTreeC ... Simon, I'm on the way to test the split _and_ will update the existing libs on the way. 
So don't make any new PRs for the existing stuff, otherwise, we will have an inconsistency. 

I'll upload a new branch soon, so you can test.

**Comment by pmario** [comment]
@BurningTreeC @Jermolene I did create a PR, that contains the existing CM version. see: https://github.com/Jermolene/TiddlyWiki5/pull/4508

**Comment by pmario** [comment]
It also includes a working local server setting for easy testing and complete dependency resolution.

IMO The modal dialog has room for UI improvements. At the moment it is the same as we are used to.

**Comment by BurningTreeC** [comment]
@pmario - have you had time to look into the runmode/colorize addons for codemirror and if we can use them for code highlighting instead of highlight.js?
