### ISSUE TITLE
Prerelease ControlPanel Info Basics - Filter links are broken - problem for existing plugins

### ISSUE THREAD

**Issue by pmario** [Jermolene/TiddlyWiki5#4504]
This is a real problem for many plugins, that will also use the "old" state tiddler. 

To reproduce expected

 - At 5.1.21 open https://tiddlywiki.com/#%24%3A%2Fcore%2Fui%2FControlPanel%2FBasics
 - Click the last element: "Number of overridden shadow tiddlers"
 - The AdvancedSearch panel will be opend _and_ Filter tab will be selected. 
 - OK

To reproduce ISSUE

 - Open https://tiddlywiki.com/prerelease/#%24%3A%2Fcore%2Fui%2FControlPanel%2FBasics
 - Click the last element: "Number of overridden shadow tiddlers"
 - AdvancedSearch will be opened BUT no Filter tab will be selected. 

In 5.1.21 the state tiddler is: $:/state/tab--1498284803
In 5.1.22-pre it is: $:/state/tab-1822219760

**Comment by Jermolene** [comment]
Many thanks @pmario can you determine which commit introduced the problem?

**Comment by pmario** [comment]
I did have a fast look, but I couldn't find anything. ... It needs to be an additional transclusion somewhere. ... right?

**Comment by pmario** [comment]
5.1.22 output array is

```
output: (6) […]
​​0: "{$:/AdvancedSearch|$:/AdvancedSearch|||}"
​​1: "{$:/AdvancedSearch|$:/core/ui/ViewTemplate/body|||}"
​​2: "{$:/AdvancedSearch|$:/core/ui/ViewTemplate|||}"
​​3: "{|$:/core/ui/PageTemplate/story|||}"
​​4: "{|$:/core/ui/PageTemplate|||}"
​​5: "{|$:/core/ui/PageTemplate|||}"
```

5.1.21 output array for hasString calc is:

```
output: (5) […]
​​0: "{$:/AdvancedSearch|$:/AdvancedSearch|||}"
​​1: "{$:/AdvancedSearch|$:/core/ui/ViewTemplate/body|||}"
​​2: "{$:/AdvancedSearch|$:/core/ui/ViewTemplate|||}"
​​3: "{|$:/core/ui/PageTemplate/story|||}"
​​4: "{|$:/core/ui/PageTemplate|||}"
```

So there seems to be something wrong with the PageTemplate. There is 1 more transclusion, which imo shouldn't be there.

**Comment by flibbles** [comment]
PR #4518 fixes this issue and adds a test to make sure this travesty never happens again.

**Comment by Jermolene** [comment]
Thanks @flibbles @pmario much appreciated
