### ISSUE TITLE
Tiddlywiki 5.1.22p: Fields do not accept space and stick words with together

### ISSUE THREAD

**Issue by kookma** [Jermolene/TiddlyWiki5#4505]
- go to https://tiddlywiki.com/prerelease/
- create a new tiddler
- add a **list** field
-try to input in new list field these words `one two three`
-Tiddlywiki sticks them and remove spaces between them

This issue seems exist for some other fields
- create a new tiddler call it "Test"
- add a new tag `new` to Test tiddler
- create another tiddler call it Test2
-in the text field of Test2 enter below wikitext `<$edit-text tiddler=Test field=tags tag=input />`
-save Tiddler Test02
-Try to add a new tag like `new2` in the inputbox
-Tiddlywiki sticks them and remove spaces between them

This issue is not seen in previous release.

**Comment by pmario** [comment]
@BurningTreeC .. There's probably a problem with the new text handlers. 
I could confirm the problem with the second example. 

The first issue description worked for me.

**Comment by BurningTreeC** [comment]
@pmario... Yes I can confirm that there are some problems

**Comment by pmario** [comment]
Ahhh. The first example is

 - Add an **empty list** field
 - Then insert some text with spaces. 
 - If typing is fast enough it works. 
 - Slow typing removes the space

**Comment by BurningTreeC** [comment]
@pmarion @Jermolene This is probably related to https://github.com/Jermolene/TiddlyWiki5/commit/a65ec87c53fceee69dac87d1051b46ebb7aaaf75

**Comment by Jermolene** [comment]
Thanks @kookma @pmario @BurningTreeC, this is an interesting one!

Every time one types into the `list` field the underlying tiddler is updated by the edit-text widget. Note that the tiddler stores the contents of the list field as an array, and not as a string. The refresh that the update causes is throttled, meaning it is deferred until a second or so after typing stops. Then, when the refresh comes, the text in the edit-text widget is refreshed from the new tiddler value. To do that, we convert the array representation of the field to a text representation.

So now you can see the problem: the contents of the list field is round tripped to an array and back, which has the effect of removing trailing whitespace, and stripping unneeded double square brackets. Try typing `[[one]]` into a list field.

As @BurningTreeC points out, undoing the changes in a65ec87c53fceee69dac87d1051b46ebb7aaaf75 reverts to the v5.1.21 behaviour. However, I think that has an impact on #4458 doesn't it?

**Comment by BurningTreeC** [comment]
> However, I think that has an impact on #4458 doesn't it?

@Jermolene - Yes reverting it has an impact on #4458 ... but better than it is atm. Maybe there's a better fix, idk?

**Comment by Jermolene** [comment]
OK I reverted things in a6f6db40d
