### ISSUE TITLE
Menu plugin: search dropdown is hidden

### ISSUE THREAD

**Issue by BurningTreeC** [Jermolene/TiddlyWiki5#4509]
the search dropdown (now that there's a scrollable widget) is hidden below the story-river and only accessible through scrolling on the menu bar

**Comment by BurningTreeC** [comment]
it's probably better to add the `scrollable` widget to `$:/plugins/tiddlywiki/menubar/items/sidebar`

**Comment by kookma** [comment]
@BurningTreeC 
Considering the new proposal on [page layout](https://github.com/Jermolene/TiddlyWiki5/issues/4473), I may recommend to put force on an overhaul of both page layout and Tiddlywiki CSS

It should be possible to add UI element simply without this kind of issue, if the new page layout can be used.

**Comment by Jermolene** [comment]
Snap!
