### ISSUE TITLE
Possible bug: enlist and join on no field or empty fields

### ISSUE THREAD

**Issue by kookma** [Jermolene/TiddlyWiki5#4514]
Ref: https://groups.google.com/d/msg/tiddlywiki/zwPTejz1nms/SRYNArwvBgAJ

- In https://tiddlywiki.com/prerelease/
- Create a new tiddler
- Put the below wikitext inside its text field

```
<a href={{!!url}} target="_blank">
<$list filter="[enlist{!!keywords}join[, ]]" variable=item><$text text=<<item>> /></$list>
</a>
```

- Save.
Why Internal JavaScript Error is appeared?

If you add url and keywords field but keep them empty, the red popup error window appears again!

Mark confirmed this also breaks Tiddlywiki 5.1.21

**Comment by saqimtiaz** [comment]
@kookma can you verify if this is still an issue on the current pre-release?

**Comment by pmario** [comment]
I did a test. For me it worked. FF win 10

**Comment by saqimtiaz** [comment]
@pmario It worked for me as well and I recall there being fixes for either enlist or join recently. So if @kookma can verify that it is fixed, we can close this issue.

**Comment by saqimtiaz** [comment]
I believe this was fixed in #4396 and can be closed.

**Comment by saqimtiaz** [comment]
@Jermolene resolved and can be closed

**Comment by kookma** [comment]
@saqimtiaz the issue has gone in TW  5.1.23. Thank you
