### ISSUE TITLE
Range widget does not save value in IE10

### ISSUE THREAD

**Issue by saqimtiaz** [Jermolene/TiddlyWiki5#4519]
The range widget does not save its value on user mouse input in IE 10 on Windows 10.

To reproduce the bug:

- Open https://tiddlywiki.com/#RangeWidget
- Move the range widget sliders in the demos.
- The new value is not displayed as the tiddler the value is to be saved to, is not created.

This is probably because IE 10 & 11 do not fire the `input` event on range sliders on mousemove, but rather the `change` event.
See "Known Issues" at https://caniuse.com/#feat=input-range

**Comment by Jermolene** [comment]
Thanks @saqimtiaz do you have a fix?

**Comment by saqimtiaz** [comment]
> Thanks @saqimtiaz do you have a fix?

I can attempt a fix in the next few days,  I currently do not have a Windows test/debug environment and will need to set one up

**Comment by Jermolene** [comment]
Thanks. I don't pay much attention to IE10 but it's good to fix what we can for IE11

**Comment by saqimtiaz** [comment]
@Jermolene I believe this is the simplest solution and doesn't require resorting to browser sniffing:
https://github.com/Jermolene/TiddlyWiki5/pull/4534
