### ISSUE TITLE
ActionPopupWidget doc demo doesn't work

### ISSUE THREAD

**Issue by twMat** [Jermolene/TiddlyWiki5#4527]
https://tiddlywiki.com/prerelease/#ActionPopupWidget

Maybe I misunderstand it or the example/demo doesn't work, i.e clicking the button to: `[...]trigger the "more" button in the sidebar "Tools" tab`. 

Could someone confirm?

**Comment by Jermolene** [comment]
Thanks @twMat that's fixed 010483f705d6248aa01e08792ac6f67472365a32

**Comment by twMat** [comment]
Thank you.

While at it, it is not clear in the doc what `(x,y,w,h)` means. I'm guessing it is for "the popups upper left corner, relative to buttons upper left corner, and measures given in pixels" ...but the, in the demo, what is `w,h`=`0,0`?  ...Should I post new issue about this?

**Comment by Jermolene** [comment]
The coordinates are the coordinates of the "handle" element that triggered the popup. They are set by the button widget when it triggers a popup, and then used as the basis for positioning the popup.
