### ISSUE TITLE
new syncer: Page toolbar whitespace problem.

### ISSUE THREAD

**Issue by pmario** [Jermolene/TiddlyWiki5#4530]
The new save-icon introduces whitespace, where it shouldn't be.  

`\whitespace trim` as the first line in the `$:/plugins/tiddlywiki/tiddlyweb` - `$:/core/ui/Buttons/save-wiki` will fix the problem

![syncer-whitespace-problem](https://user-images.githubusercontent.com/374655/78031660-23a28a00-7364-11ea-93d6-eb6391a42f74.gif)

**Comment by Jermolene** [comment]
Thanks @pmario
