### ISSUE TITLE
Links in lists improperly formatted causing unwanted whitespace nodes

### ISSUE THREAD

**Issue by KalciferKandari** [Jermolene/TiddlyWiki5#4532]
In UI list generators the `<$link>` HTML is improperly formatted. For example, in $:/core/ui/ListItemTemplate:
```
<div class="tc-menu-list-item">
<$link to={{!!title}}>
<$view field="title"/>
</$link>
</div>
```

This is causing browsers to collapse the newlines into whitespace nodes that cannot be removed with CSS. Browsers do this for inline elements, that includes `<a>` and `<li>` tags, and maybe more.

This particularly becomes a problem when adding `::before` or `::after` content to the generated links, as shown in the screenshot.

![Annotation 2020-04-01 192426](https://user-images.githubusercontent.com/11889543/78172725-748ead00-744e-11ea-9e36-6fc7915fea61.png)

In the link in the sidebar to the right, the spaces before and after "Custom CSS" should not be there.

This is how the code above should be formatted, just need to remove the newlines:
```
<div class="tc-menu-list-item">
<$link to={{!!title}}><$view field="title"/></$link>
</div>
```

![Annotation 2020-04-01 193719](https://user-images.githubusercontent.com/11889543/78173852-3f835a00-7450-11ea-84ae-e19ac90667e6.png)

Here are some of the files I have found that have improper formatting, there may be more:

- $:/core/ui/ListItemTemplate
- $:/core/macros/timeline
- $:/core/ui/PluginListItemTemplate
- $:/core/ui/PluginInfo/Default/contents

**Comment by twMat** [comment]
>This is how the code above should be formatted, just need to remove the newlines:
>[...]

...it's prolly even enough with:

```
<div class="tc-menu-list-item">
<$link/>
</div>
```

**Comment by pmario** [comment]
Just to make the list more visible: 

Found some additional files that needed to be edited, still may be more:

 - $:/core/ui/ListItemTemplate
 - $:/core/macros/timeline
 - $:/core/ui/PluginListItemTemplate
 - $:/core/ui/PluginInfo/Default/contents

**Comment by Jermolene** [comment]
Thanks @KalciferKandari @twMat @pmario I concur that this is worth fixing. Could one of you make a PR?

**Comment by KalciferKandari** [comment]
I'm not familiar with the code, so I don't think I could find all the instances, or with Git to actually make a pull request.

**Comment by KalciferKandari** [comment]
I'm curious if would be possible to create a small script that would find all the nuisance newlines for all inline HTML tags by using grep.

I don't know what TiddlyWiki code generates inline tags though, other than `<$link>`.

**Comment by KalciferKandari** [comment]
I'm trying to work through this, but I've just realised it might be more difficult than I thought.

If a block element is `display: inline;` in CSS then it causes the same issue. Problem is that you don't know which block elements the user is going to want to display inline.

**This leads me to think that all HTML should be compressed into a single line.** Well obviously that is not going to be readable, so what if it was done automatically by TiddlyWiki in the background? That would be problematic, because the question would be, which tiddlers to compress? Well there could be a tag or type to mark a tiddler for compression, and if parts of a tiddler can't be compressed, such as macro definitions, then the HTML can be transcluded from another compressed tiddler.

Implementing this is way beyond me.

**Comment by pmario** [comment]
I'll create a PR soon

**Comment by pmario** [comment]
@KalciferKandari .. I did a version with fixed the problem for most elements except the TOC table-of-contents. .. Where your CSS doesn't make much sense. ...

The CSS used is too unspecific. So it needs to be eg: 

```
.tc-more-sidebar a::before,
.tc-timeline a::before,
.tc-sidebar-tab-open a::before {
  content: "[b]";
}
```

**Comment by pmario** [comment]
I did test every link in TW with: 

```
a::before { content: "[b]"; }

a::after { content: "[a]"; }
```

And there are only 8 tiddlers which are used to create links + CSS. .... So most of the time TW already uses the list-templates to produce links. 

PR follows

**Comment by KalciferKandari** [comment]
I do appreciate the solution for links. It would be nice to see the generic solution I mentioned that works for all elements, though I can see how difficult that would be. For example, I wanted to add `::before` and `::after` to the tiddler title `h2.tc-title` and realised the problem was there as well.

**Comment by pmario** [comment]
`h2.tc-title` For me this doesn't produce whitespace in the DOM.

**Comment by KalciferKandari** [comment]
![Annotation 2020-04-12 083213](https://user-images.githubusercontent.com/11889543/79063201-253f4c80-7c98-11ea-8e35-ee477f66bcbe.png)

You sure?

**Comment by pmario** [comment]
OK. You are right. I didn't test it with the CSS. I'll try to fix it.

**Comment by pmario** [comment]
I did modify the PR accordingly. Also tested icon + title.
