### ISSUE TITLE
Issue with $reveal widget: extra space created by reveal widget

### ISSUE THREAD

**Issue by kookma** [Jermolene/TiddlyWiki5#4533]
I use the below code to create a button on page controls.

```
\whitespace trim

\define show-fields-button()
<$reveal type="nomatch" state=<<fldshowstateTid>> text="show" tag="span">
<$button set=<<fldshowstateTid>> setTo="show" 
	         tooltip={{$:/language/Buttons/Utility/Hint}} 
					 aria-label={{$:/language/Buttons/Utility/Caption}} 
					 class=<<tv-config-toolbar-class>> >
    <<disp-on-pagecontrols>>
    <$action-setfield $tiddler=<<viewtemplateTid>> tags="$:/tags/ViewTemplate"/>
  </$button>
</$reveal>
\end

<<show-fields-button>>
```

Strangely $reveal adds an extra space before the button.

![extra-space](https://user-images.githubusercontent.com/830394/78339152-44a7ec80-75a9-11ea-8f04-3ce10dcf6c26.png)

When I use 

`<$reveal type="nomatch" state=<<fldshowstateTid>> text="show" tag="span"><$button set=<<fldshowstateTid>> setTo="show" `

The extra space disappears. 

To see the code look at: https://kookma.github.io/TW-Utility/#%24%3A%2Fplugins%2Fkookma%2Futility%2Fpagecontrol%2Fview-fields-button

**Comment by pmario** [comment]
You need to place the `\whitespace trim` inside the `\define show-fields-button()` construction. 
So if you have more macro definitions you need it per definition.

**Comment by kookma** [comment]
@pmario 
Many thanks. That is correct and the issue has gone!
