### ISSUE TITLE
[BUG] Draft tiddler not deleted, when I delete it from another instance of wiki

### ISSUE THREAD

**Issue by linonetwo** [Jermolene/TiddlyWiki5#4548]
**Describe the bug**
I'm running multiple instances of nodejs wiki, and in one instance I create a tiddler, finish editing and autosave.

In another instance still shows there is a draft tiddler.

**To Reproduce**
Similar to https://github.com/Jermolene/TiddlyWiki5/issues/4547

1. Open two nodejs localhost:xxx wiki
2. create a new tiddler in one instance A
3. finish editing via save or delete
4. See another instance B still have draft tiddler
5. after a while, if you delete that new tiddler in A, you will find A sync that draft tiddler back, as if it is not deleted

**Expected behavior**
When tiddler saved or deleted in instance A, nodejs server updates the skinny tiddler list properly, so when instance B sync the skinny tiddler list, it deletes the local draft tiddler.

**Screenshots**

Draft tiddler on the left still presists after I delete it on the right:
<img width="1241" alt="Screen Shot 2020-04-10 at 12 34 31 AM" src="https://user-images.githubusercontent.com/3746270/78918584-36833000-7ac3-11ea-9fbf-311d7bdd9193.png">

I've look at the `http://127.0.0.1:xxx/recipes/default/tiddlers.json`, and there is no entry with `Draft` in title.

**Desktop (please complete the following information):**
 - OS: MacOS 10.15.4 (19E287)
 - Browser: Firefox 74.0.1 (64-bit)
 - Version: TW 5.2.1

**Additional context**
I found this bug when I'm using webcatalog to make a desktop app and a menubar dropdown quick search app:

<img width="1438" alt="Screen Shot 2020-04-09 at 11 48 41 PM" src="https://user-images.githubusercontent.com/3746270/78914192-a7731980-7abc-11ea-9318-ba08adf3246a.png">

I use main app to do long edit, and dropdown app to search or paste note.

After a while...

<img width="1233" alt="Screen Shot 2020-04-10 at 1 56 56 PM" src="https://user-images.githubusercontent.com/3746270/78966736-33278d00-7b33-11ea-8335-83852591dee8.png">

Which file in syncadaptor should I look into to fix this?

I'm currently using folowing injected JS in WebCatalog as a workaround:

```js
const RELOAD_INTERVAL = 1000 * 60;
const CHECK_ACTIVITY_INTERVAL = 1000 * 3;

let time = new Date().getTime();

const refreshTime = () => {
  time = new Date().getTime();
};
document.addEventListener('keyup', refreshTime);
document.addEventListener('mousemove', refreshTime);
document.addEventListener('mouseup', refreshTime);

function refresh() {
    const serverNotStarted = !document || document.querySelector('.tc-site-title') === null;
    const notActivatedForLong = new Date().getTime() - time >= RELOAD_INTERVAL;
  if (serverNotStarted || notActivatedForLong) {
    window.location.reload(true);
  } else {
    setTimeout(refresh, CHECK_ACTIVITY_INTERVAL);
  }
}

setTimeout(refresh, CHECK_ACTIVITY_INTERVAL);
```

**Comment by linonetwo** [comment]
Closing, as it might be caused by error in my nodejs script.

**Comment by linonetwo** [comment]
Might related to https://github.com/Jermolene/TiddlyWiki5/issues/3008

**Comment by linonetwo** [comment]
Not a problem with 5.2.2 new Syncer.

It takes some time to sync (30s ?), but after, everything is in sync.

**Comment by kookma** [comment]
@linonetwo 
5.2.2 --> 5.1.22
