### ISSUE TITLE
[BUG] External Attachments plugin - relative paths

### ISSUE THREAD

**Issue by BurningTreeC** [Jermolene/TiddlyWiki5#4549]
The **relative** paths generated by the External Attachments plugin are off by one level of depth (don't know how to say it)

Example:

../path/to/image.png **should be** ./path/to/image.png

OS: Linux
Browser: TiddlyDesktop

**Comment by BurningTreeC** [comment]
This is still an issue

**Comment by Jermolene** [comment]
Thanks @BurningTreeC, let me know if the upcoming fix works for you.

**Comment by BurningTreeC** [comment]
@Jermolene, thanks a lot, this now works fine!

**Comment by Jermolene** [comment]
Thanks @BurningTreeC sorry it's been so long...
