### ISSUE TITLE
[BUG] CodeMirror e.toggleComment is not a function

### ISSUE THREAD

**Issue by linonetwo** [Jermolene/TiddlyWiki5#4550]
**Describe the bug**
I've installed the codemirror editor, and try to edit a css file.

When I press command+/ to toggle comment, this error pops up.

**To Reproduce**
1. Install codemirror plugin and sublime keymap, and enable that keymap
1. Create a code tiddler with css
2. press command+/

**Expected behavior**
No error, and comment is toggled

**Screenshots**
<img width="877" alt="Screen Shot 2020-04-11 at 12 04 40 PM" src="https://user-images.githubusercontent.com/3746270/79034993-a04b2900-7bec-11ea-974c-8a56d603fc3d.png">

**Desktop (please complete the following information):**
 - OS: MacOS 10.15.4 (19E287)
 - Browser: Firefox 74.0.1 (64-bit)
 - Version: TW 5.1.21

**Comment by linonetwo** [comment]
I know the source is in https://github.com/Jermolene/TiddlyWiki5/blob/master/plugins/tiddlywiki/codemirror-keymap-sublime-text/files/keymap/sublime.js

But it is minimized so difficult to fix.

How can I found the source and debug? And I'd like to make a VSCode keymap, I also need a reference to modify from.

**Comment by BurningTreeC** [comment]
Thanks for the bug-report @linonetwo 

This is probably related to https://github.com/codemirror/CodeMirror/issues/5917

@pmario, what do you think, should we include comments.js somewhere?

**Comment by pmario** [comment]
>@pmario, what do you think, should we include comments.js somewhere?

I think it should be included, if it is needed.

**Comment by pmario** [comment]
It seems we "just" missed it ;)

**Comment by BurningTreeC** [comment]
We'll need to find the plugin which requires comment.js - the sublime keymap doesn't do so

**Comment by pmario** [comment]
may be they also missed to define the dependency.

**Comment by pmario** [comment]
comment.js is part of the addOns section: https://codemirror.net/doc/manual.html#addons
