### ISSUE TITLE
Add filter operators for comparing numbers, integers, strings, dates and versions

### ISSUE THREAD

**Issue by Jermolene** [Jermolene/TiddlyWiki5#4554]
TiddlyWiki 5 lacks filter operators for comparing values. There is some discussion in #2253, #2968 and #3760, #3781 and #4128.

It is proposed to add a new "compare" operator. It uses two suffixes. The first is for selecting the data type from:

* "number" - invalid numbers are interpreted as zero
* "integer" - invalid integers are interpreted as zero
* "string"
* "date" - invalid dates are interpreted as 1st January 1970
* "version" - invalid versions are interpreted as "v0.0.0"

The second suffix selects the operation type from

* "eq" - equal to
* "ne" - not equal ot
* "gteq" - greater than or equal to
* "gt" - greater than
* "lteq" - less than or equal to
* "lt" - less than

The operator compares each item in the selection against the value of the operand, retaining only those items that pass the specified condition.

For example:

```
[[2]compare:number:eq[3]] returns ""
[[2]compare:number:lt[3]] returns "2"
[[2]compare:number:eq[2]] returns "2"
[[20200101]compare:date:gt[201912311852]] returns "20200101"
[[202001011852]compare:integer:gt[20191231]] returns ""
[[v5.1.23-prerelease]compare:version:gt[v5.1.22]] returns "v5.1.23-prerelease"

[[1]compare:number:gt[2]then[yes]else[no]]
```

Note several of these operators are synonyms for existing operators, and are provided in the interests of consistency. For example, `compare:strings:eq[x]` is a synonym for `match[x]`.

**Comment by kookma** [comment]
@Jermolene 
This is really amazing and will improve and facilitate scripting in Tiddlywiki.

**Comment by Jermolene** [comment]
Thanks @kookma!
