### ISSUE TITLE
[BUG] externalimages build process destroy jpg file

### ISSUE THREAD

**Issue by linonetwo** [Jermolene/TiddlyWiki5#4556]
**Describe the bug**
I tried running following custom "externalimages" build process on local machine:

```
        "externalimages": [
            "--setfield",
            "[is[image]]",
            "_canonical_uri",
            "$:/core/templates/canonical-uri-external-image",
            "text/plain",
            "--setfield",
            "[is[image]]",
            "text",
            "",
            "text/plain",
            "--rendertiddler",
            "$:/plugins/tiddlywiki/tiddlyweb/save/offline",
            "index.html",
            "text/plain"
        ],
```

And it makes xx.jpg 's content changed to `�w^~)�`

**To Reproduce**
1. Clone https://github.com/linonetwo/Meme-of-LinOnetwo/tree/beeff69eb1ba9c93e0fac24d4c0d0384a82ab88c
2. `npm i`
3. `npm run build`
4. See error in `./MemeOfLinonetwo/tiddlers/webcatalog-tiddlywiki-menu-app.jpg`

**Expected behavior**
The build process should not change the file inside `tiddlers`, it should be a pure function without side effect.

**Screenshots**

<img width="964" alt="Screen Shot 2020-04-13 at 11 52 03 AM" src="https://user-images.githubusercontent.com/3746270/79090725-34e49100-7d7d-11ea-948d-5349c61c13f6.png">

**Desktop (please complete the following information):**
 - OS: MacOS 10.15.4 (19E287)
 - Browser: Firefox 74.0.1 (64-bit)
 - Version: TW 5.2.1

**Additional context**
I use image uploaded to Github as src for img, so I just let generated HTML have `_canonical_uri`.

**Comment by KendrickLamarck** [comment]
Possible duplicate of #4484

**Comment by linonetwo** [comment]
Sorry for duplicate...
