### ISSUE TITLE
[IDEA] Allow serving via external http server

### ISSUE THREAD

**Issue by linonetwo** [Jermolene/TiddlyWiki5#4561]
**Is your feature request related to a problem? Please describe.**
When using `root-tiddler=$:/core/save/lazy-all` to start the wiki, it's very slow because there are too many requests.

If I can use HTTP2, the speed can be faster.

And I'd like to serve `./public` folder for my service worker, so I'd like to set up my own HTTP server instead of a built-in file server that serves the file with a `/file` prefix.

**Describe the solution you'd like**
~~I read the code, but still can't find where does TiddlyWiki use `http` package...So I don't know.~~

---

update:

I forget to disable `.gitignore` when search...Now I can find the file I should look at.

<img width="282" alt="Screen Shot 2020-04-15 at 8 44 23 AM" src="https://user-images.githubusercontent.com/3746270/79287160-75ffb100-7ef5-11ea-9ae0-582f45cbffc7.png">

I will read the code...

**Comment by Jermolene** [comment]
Hi @linonetwo the server functionality is in https://github.com/Jermolene/TiddlyWiki5/tree/master/core/modules/server and its subdirectories, with the require("http") [here](https://github.com/Jermolene/TiddlyWiki5/blob/master/core/modules/server/server.js#L77).

**Comment by saqimtiaz** [comment]
@Jermolene @linonetwo this can be closed.

**Comment by Jermolene** [comment]
Thanks @saqimtiaz
