### ISSUE TITLE
[BUG] Create a wiki using Node.js in a nested directory

### ISSUE THREAD

**Issue by kookma** [Jermolene/TiddlyWiki5#4563]
tiddlywiki.js cannot handle creating wiki in nested directory on Windows (not tested other OS). To reproduce 

```
$ node ./TiddlyWiki5/tiddlywiki.js ./test/wiki --init empty
Error: Error creating directory './test/wiki'
```

None of _test_ and _wiki_ directories are existed!

See also:  https://github.com/inmysocks/PluginDevelopment/issues/2#issuecomment-613636398

**Comment by Jermolene** [comment]
Hi @kookma I tried the same thing and it seems to work for me, are you still having problems? Could it be a filing system error of some kind?

**Comment by kookma** [comment]
Thanks @Jermolene 

I am on Windows 10
- [x] Powershell both core and windows
- [x] Command com (cmd.exe)
- [ ]  Gnu bash (4.4 msys2 x64)

I will check on a Linux system to see if the issue is not from TW side

**Comment by kookma** [comment]
Tested on Lubuntu Gnu bash 5.0.16 works!
Seems the issue is from Gnu bash 4.4 installed on Windows 10
