### ISSUE TITLE
[BUG] Get more plugins window can not be opened

### ISSUE THREAD

**Issue by jeffrey4l** [Jermolene/TiddlyWiki5#4570]
**Describe the bug**

After upgrade to `5.1.22`, the **Get more plugins** window can not be opened/loaded.

I can not find clear error message in devtools and command line logs.

**To Reproduce**

1. Go to **ControlPanel**
2. Click on **Plugins**
3. Click on **Get more plugins**

**Expected behavior**

Can open the plugins list page

**Screenshots**

![138](https://user-images.githubusercontent.com/354768/79521618-2ef7f400-808c-11ea-8077-dd381a335595.jpg)

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser: Chrome
 - Version: 5.1.22

Start by 

```
/usr/bin/tiddlywiki --listen port=8181 "root-tiddler=$:/core/save/lazy-images"
````

Tiddlywiki.info

```json
{
    "plugins": [
        "tiddlywiki/blog",
        "tiddlywiki/codemirror",
        "tiddlywiki/codemirror-autocomplete",
        "tiddlywiki/codemirror-closebrackets",
        "tiddlywiki/codemirror-closetag",
        "tiddlywiki/codemirror-fullscreen-editing",
        "tiddlywiki/codemirror-keymap-vim",
        "tiddlywiki/codemirror-mode-css",
        "tiddlywiki/codemirror-search-replace",
        "tiddlywiki/d3",
        "tiddlywiki/filesystem",
        "tiddlywiki/highlight",
        "tiddlywiki/internals",
        "tiddlywiki/jszip",
        "tiddlywiki/katex",
        "tiddlywiki/markdown",
        "tiddlywiki/menubar",
        "tiddlywiki/pluginlibrary",
        "tiddlywiki/railroad",
        "tiddlywiki/tiddlyweb"
    ],
    "themes": [
        "tiddlywiki/vanilla",
        "tiddlywiki/snowwhite"
    ],
    "build": {
        "renderfull": [
            "--rendertiddler", "$:/core/save/all", "index_full.html", "text/plain"
        ],
        "render": [
            "--rendertiddler", "$:/core/save/lazy-images", "index_without_img.html", "text/plain"
        ],
        "index": [
            "--rendertiddler",
            "$:/core/save/all",
            "index.html",
            "text/plain"
        ],
        "empty": [
            "--rendertiddler",
            "$:/core/save/all",
            "empty.html",
            "text/plain",
            "--rendertiddler",
            "$:/core/save/all",
            "empty.hta",
            "text/plain"
        ],
        "externalimages": [
            "--savetiddlers",
            "[is[image]]",
            "images",
            "--setfield",
            "[is[image]]",
            "_canonical_uri",
            "$:/core/templates/canonical-uri-external-image",
            "text/plain",
            "--setfield",
            "[is[image]]",
            "text",
            "",
            "text/plain",
            "--rendertiddler",
            "$:/core/save/all",
            "externalimages.html",
            "text/plain"
        ],
        "static": [
            "--rendertiddler",
            "$:/core/templates/static.template.html",
            "static.html",
            "text/plain",
            "--rendertiddler",
            "$:/core/templates/alltiddlers.template.html",
            "alltiddlers.html",
            "text/plain",
            "--rendertiddlers",
            "[!is[system]]",
            "$:/core/templates/static.tiddler.html",
            "static",
            "text/plain",
            "--rendertiddler",
            "$:/core/templates/static.template.css",
            "static/static.css",
            "text/plain"
        ]
    },
    "config": {
        "retain-original-tiddler-path": true
    }
}
```

**Comment by linonetwo** [comment]
I had the same problem before, I have installed Kookma plugin library and main plugin library.

But after the upgrade, only the Kookma plugin library remains.

So I have to recreate the main plugin library by hand. You can do that too.


Just add a tiddler with title `$:/config/OfficalPluginLibrary` and tag `$:/tags/PluginLibrary` and a caption `Offical Plugin Library` and a url `https://tiddlywiki.com/library/v5.1.22/index.html ` and text `The official TiddlyWiki plugin library at tiddlywiki.com. Plugins, themes and language packs are maintained by the core team.`.

Then the problem will be solved.

**Comment by linonetwo** [comment]
But it is still weird that upgrading npm package tiddlywiki will remove the OfficalPluginLibrary

**Comment by jeffrey4l** [comment]
Your solution works, thanks a lot.

**Comment by cba85** [comment]
Your solution works for me too, @linonetwo! Thanks!

I've fixed the bug by copying the `/tiddlers/$__config_OfficalPluginLibrary.tid` file of the official Tiddlywiki repository in my local Tiddlywiki project.

$__config_OfficalPluginLibrary.tid:
```
title: $:/config/OfficialPluginLibrary
tags: $:/tags/PluginLibrary
url: https://tiddlywiki.com/library/v5.1.22/index.html
caption: {{$:/language/OfficialPluginLibrary}}

{{$:/language/OfficialPluginLibrary/Hint}}
```

**Comment by KendrickLamarck** [comment]
This seems to be intentional, but communicated poorly. The present **$:/config/OfficalPluginLibrary tiddler** says

>(This core tiddler is overridden by the tiddlyweb plugin to prevent users from installing official plugins via control panel. Instead they should be installed by editing tiddlywiki.info in the root of the wiki folder)

which I'm fine with, but upon clicking **Get more plugins** one should be presented with this message instead of a blank window.

**Comment by linonetwo** [comment]
@KendrickLamarck  Oh, I didn't know that!

But I think clicking button to upgrade and install plugin is more confortable for me, compare to manually download things, extract zip and put into the folder and edit config file...

**Comment by KendrickLamarck** [comment]
@linonetwo Are you talking about plugins from the official **tiddlywiki/** plugin library? Because in that case, no downloading or unzipping is required. Simply edit the config file, start the server and the plugins will be there.

**Comment by Jermolene** [comment]
Thanks everyone, and sorry for the confusion. As @KendrickLamarck [says](https://github.com/Jermolene/TiddlyWiki5/issues/4570#issuecomment-615200955), this is intentional. When using the client-server configuration plugins from the official plugin library should be installed in tiddlywiki.info. Using the browser-based plugin installer means that the plugin is installed as a regular tiddler, and won't be upgraded when the TW installation is upgraded.

I'll have a look at making a warning message visible.

**Comment by linonetwo** [comment]
Today another user get confused by this, he struggles with installing codemirror from the official library for 1.5 hours.

Normal users don't know about what JSON is, and editing fields in the `.info` file is a pain for them. Also editing this JSON file ask them to know about the plugin's id.

I hope we can re-enable this feature, so people using other editions can enjoy CPL style (or obsidian style) "click to enable plugin". (I have re-enable this feature in TidGi's default edition, so TidGi user usually won't have this problem. And I feel easier introducing TidGi instead of introducing TiddlyWiki itself to normal non-technical new users, this is one of the reasons.)

**Comment by linonetwo** [comment]
That wouldn't be an urgent task, as I can import all core plugins  into CPL, so TidGi users (who knows tiddlywiki stuff, but don't know nodejs and json) can use it.

And I'm starting multiple wiki in TidGi using worker thread, so multi wiki in a single thread wouldn't be much use for it. But if it can reduce CPU and memory usage, I will adapt it
