### ISSUE TITLE
[BUG] is[image] doesn't work with type image/jpg

### ISSUE THREAD

**Issue by BurningTreeC** [Jermolene/TiddlyWiki5#4571]
**Describe the bug**
the filter `is[image]` works with tiddler types `image/jpeg` but doesn't work with `image/jpg`

**Expected behavior**
`image/jpg` is recognized as an image tiddler by the `is[image]` filter

**Comment by pmario** [comment]
`image/jpg` is _not_ a mime type see: https://www.iana.org/assignments/media-types/media-types.xhtml#image .. So I'd say no.

**Comment by BurningTreeC** [comment]
but it works for tiddlers with type `image/jpg` ... they're shown as image tiddlers. Only the `is[image]` filter ignores them

**Comment by pmario** [comment]
>but it works for tiddlers with type image/jpg 

Yea, that's a problem ... technically speaking: "It shouldn't"

**Comment by BurningTreeC** [comment]
... While for `image/jpeg` everything works perfectly fine

**Comment by BurningTreeC** [comment]
@pmario should I close this issue?

**Comment by pmario** [comment]
No. I have changed my mind. We do `	$tw.utils.registerFileType("image/jpeg","base64",[".jpg",".jpeg"],{flags:["image"]});`  .. So we should also recognize it.
