### ISSUE TITLE
[BUG] Uncaught TypeError: self.widget.cancelPopups is not a function

### ISSUE THREAD

**Issue by Dialga** [Jermolene/TiddlyWiki5#4574]
**Describe the bug**
Uncaught TypeError: self.widget.cancelPopups is not a function when creating a new tiddler in the latest 5.1.22 release.

**To Reproduce**
1. I upgraded my tiddlerwiki to the latest release
2. Press + to create new tiddler
3. Fill in title
4. Click body
5. Error popups as above.

**Expected behavior**
No TypeError popup

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser Chromium
 - Version 81

**Smartphone (please complete the following information):**

**Additional context**
I was not expecting this error, and as such it has rendered my personal tiddlywiki unusable.

**Comment by BurningTreeC** [comment]
Hi @Dialga, thanks for the Bug report. Which plugins are you using?

**Comment by Dialga** [comment]
Hi @BurningTreeC, I've narrowed down the problem and disabling the CodeMirror Editor plugin makes the issue disappear. That brings to question why #4310 was merged?

**Comment by BurningTreeC** [comment]
@Dialga , have you tried reinstalling codemirror?

**Comment by Dialga** [comment]
Yes, reinstalling fixes the issue. Thanks.
