### ISSUE TITLE
404

### ISSUE THREAD

**Issue by 221V** [Jermolene/TiddlyWiki5#4577]
at page
https://tiddlywiki.com/static/Generating%2520Static%2520Sites%2520with%2520TiddlyWiki.html

link "at static.html."
sends to 404 page
https://tiddlywiki.com/static/static.html

link
https://tiddlywiki.com/static/alltiddlers.html
404 too

------------

so guides are 404, no exists or non-understable...
i do not know, how get statis css and js :cry: 
https://github.com/Jermolene/TiddlyWiki5/issues/4443#issuecomment-615954948

**Comment by twMat** [comment]
Confirming.
