### ISSUE TITLE
[BUG] Journal tag pill dropdown list includes the system tiddler "$:/config/NewJournal/Tags"

### ISSUE THREAD

**Issue by abesamma** [Jermolene/TiddlyWiki5#4591]
**Bug description**
Clicking the Journal tag pill produces a dropdown list that wrongly includes a single system tiddler as the first tiddler titled: "$:/config/NewJournal/Tags" in TW5 v5.1.22 This behaviour seems to be restricted to only that action. Using list generating macros correctly excludes the system tiddler. Changing that system tiddler to remove the behavior breaks the creation of new Journal tiddlers.

**To Reproduce**
1. Create a non-system tiddler tagged Journal
2. Click on Journal tag pill
3. First entry shows ""$:/config/NewJournal/Tags""

**Expected behavior**
"$:/config/NewJournal/Tags" should not appear in the dropdown list.

**Screenshots**
![EWNXSr0X0AAxAtX](https://user-images.githubusercontent.com/8182498/79986843-56e4be80-84b5-11ea-9969-904a070bafdf.png)

**Comment by pmario** [comment]
That's new. ... It's a bug.

**Comment by pmario** [comment]
`$:/config/NewTiddler/Tags` has the same problem, if the system tiddler / configuration is created.

We should use the text field instead of the tags. .. The tiddler name is already right.

**Comment by abesamma** [comment]
> 
> 
> `$:/config/NewTiddler/Tags` has the same problem, if the system tiddler / configuration is created.
> 
> We should use the text field instead of the tags. .. The tiddler name is already right.

I agree. That was my initial thought too.

**Comment by Jermolene** [comment]
Just to be clear, the only part of this that is new is that setting default tags in control panel will cause a system config tiddler to be created with those tags.  We've always listed system tiddlers within tag dropdowns.

@BurningTreeC is it practical to use a different field on the templates? I can see it might make things more awkward to handle.

**Comment by BurningTreeC** [comment]
@Jermolene,  @abesamma, I know about this flaw but using a different field than the tags field would indeed make things more difficult to handle. I'll have a look

**Comment by pmario** [comment]
@Jermolene ... It's OK to show system tiddlers in the tag dropdown. ... But imo the config tiddler shouldn't be there. 

@BurningTreeC ... I think we should try to use the text field, even if we can't use the "tag - UI" to add them. ... Or we need to improve the UI, so it will be able to use tag-like behaviour with any field.

**Comment by abesamma** [comment]
@Jermolene at the risk of sounding naive, could you explain why it would be awkward to use the text field of the config tiddler instead of the tag field? Looking at the `new-journal.tid`, it feels like a no brainer. What else could break because of this?

**Comment by pmario** [comment]
@abesamma ... The tagging UI can't be used atm if we use a different field.

**Comment by abesamma** [comment]
> @abesamma ... The tagging UI can't be used atm if we use a different field. 

I think I understand now.

**Comment by BurningTreeC** [comment]
#4600 fixes this issue
