### ISSUE TITLE
[IDEA] alltiddlers.html use html title anchors for navigation

### ISSUE THREAD

**Issue by dubiouscript** [Jermolene/TiddlyWiki5#4595]
**Is your feature request related to a problem? Please describe.**

https://www.w3.org/TR/html4/struct/links.html

as described in https://github.com/Jermolene/TiddlyWiki5/issues/4594 , alltiddlers.html navigation is broken 

in summery

- url hash links , do nothing 

- no internal linking of tiddler sections contained in  alltiddlers.html  

---

as the title i think it could be possible to use plain html title / anchor link to navigate 

like (eg) https://en.wikipedia.org/wiki/Trie#Applications  wikipedia do!

... ( trying to catch some rays =] hence brevity .. = )
l8r

**Comment by twMat** [comment]
You're double posting. Or, frankly, 0.5+0.5 posting. Please edit your two posts into one. As you can tell we already have a problem with too many posts and while bug reports are valuable they need to be phrased so that people are actually willing to read them.

**Comment by Jermolene** [comment]
Hi @dubiouscript the links in alltiddlers.html do work for me, apart from the links to system tiddlers discussed in #4594.

**Comment by dubiouscript** [comment]
ah ! 
so the links do work and it appears that system tiddler are the exception and not the rule 

noted
