### ISSUE TITLE
[Question/Bug] TW refreshes every 20-50s

### ISSUE THREAD

**Issue by jordifradera** [Jermolene/TiddlyWiki5#4605]
I'm not sure this is a bug or an intended behavior of TW, but it makes it difficult to work in a multi-user environment. The problem is the following:

- TW is hosted in a server inside an intranet
- TW safe content to the server (no gitHub or gitLab or giTea or...)
- All users browse as (anon)
- Every 20-50s the interface refreshes on its own showing a layout
- The layout is the one corresponding to a user loged-in as writer
- When another user logs-in as writer the interfaces does not refresh, it only happens in Read-Only

I use TW as a collaborative tool, so all users with write permission add content to projects. The rest of users browse TW for info on that projects. Hence, it is annoying for (anon) users to go to a layout other than theirs every now and then.

I've been trying to find a parameter in tools than can change this behavior with no luck.

The following is the list of plugins in case there is any incompatibility:

TiddlyWiki5 core 5.1.22
 encryptTiddler 2.1
 datepicker 0.5.2
 moment 2.24.0
 bibtex 5.1.21
 comments 5.1.21
 d3 5.1.21
 Filesystem 5.1.22
 Highlight 5.1.22
 katex 5.1.21
 TiddlyWeb 5.1.22

All users browse with Chrome.

Thanks in advance.

**Comment by saqimtiaz** [comment]
@Jermolene this is resolved with the fix for system tiddler sync.

**Comment by saqimtiaz** [comment]
@Jermolene bump. Is resolved and can be closed.

**Comment by Jermolene** [comment]
Thanks @saqimtiaz
