### ISSUE TITLE
[BUG] evalSandboxed causes server to take 4x more memory

### ISSUE THREAD

**Issue by Arlen22** [Jermolene/TiddlyWiki5#4618]
**Describe the bug**

The use of evalSandboxed in TiddlyWiki causes it to take 85 MB of memory, whereas changing it to evalGlobal uses only 20 MB. Are there any particular reasons for using evalSandboxed vs evalGlobal? 

**To Reproduce**

1. Run `node --inspect-brk tiddlywiki.js editions/server --listen`
2. In Google Chrome, navigate to `chrome://inspect` and open the devtools for the node instance. 
3. Take a heap snapshot or simply note the amount of consumed memory on the memory tab.
4. Press run in source code (because `--inspect-brk` starts with it paused)
5. Note the amount of memory now. It should be 80 MB or so. 

**Desktop (please complete the following information):**
 - OS: MacOS
 - NodeJS 12.14.1
 - Version: master

**Comment by Arlen22** [comment]
Here's another idea. This sandboxes all modules together in one context, but still keeps them separate from the main context. 

```diff
diff --git a/boot/boot.js b/boot/boot.js
--- a/boot/boot.js
+++ b/boot/boot.js
@@ -501,7 +501,7 @@ $tw.utils.getTypeEncoding = function(ext) {
 /*
 Run code globally with specified context variables in scope
 */
-$tw.utils.evalGlobal = function(code,context,filename) {
+$tw.utils.evalGlobal = function(code,context,filename,sandbox) {
 	var contextCopy = $tw.utils.extend(Object.create(null),context);
 	// Get the context variables as a pair of arrays of names and values
 	var contextNames = [], contextValues = [];
@@ -516,19 +516,21 @@ $tw.utils.evalGlobal = function(code,context,filename) {
 	if($tw.browser) {
 		fn = window["eval"](code + "\n\n//# sourceURL=" + filename);
 	} else {
-		fn = vm.runInThisContext(code,filename);
+		if(sandbox){
+			fn = require('vm').runInContext(code, sandbox, filename)
+		} else {
+			fn = vm.runInThisContext(code,filename);
+		}
 	}
 	// Call the function and return the exports
 	return fn.apply(null,contextValues);
 };
-
+var sandbox = vm.createContext(); 
 /*
 Run code in a sandbox with only the specified context variables in scope
 */
 $tw.utils.evalSandboxed = $tw.browser ? $tw.utils.evalGlobal : function(code,context,filename) {
-	var sandbox = $tw.utils.extend(Object.create(null),context);
-	vm.runInNewContext(code,sandbox,filename);
-	return sandbox.exports;
+	return $tw.utils.evalGlobal(code, context, filename, sandbox);
 };
 
 /*
```

**Comment by Arlen22** [comment]
This only affects the server side. If evalSanboxed is called in the browser it uses evalGlobal. 

I have not checked the browser side but your comment about closures intrigues me. However, I would open a separate issue for that if I found anything.

**Comment by Jermolene** [comment]
Hi @Arlen22 as I recall it, using evalSandboxed was just me trying to minimise side effects from executing modules. I don't see an immediate objection to the idea of changing it as long as we test it very carefully, so please go ahead and draft a PR if you'd like.

**Comment by Arlen22** [comment]
I'm working on the PR, and it turns out that the only offender was a polyfill, which has me really puzzled... Oh, right, it's only sandboxed on the server, and only needed on the browser, so that worked fine. But I'm not sure why it's still being run on the server. 

Ok, figured that out as well. The polyfill was being called immediately on module execution instead of waiting for the startup sequence. So that will be in the PR as well.

**Comment by Arlen22** [comment]
> I'm working on the PR, and it turns out that the only offender was a polyfill, which has me really puzzled... Oh, right, it's only sandboxed on the server, and only needed on the browser, so that worked fine. But I'm not sure why it's still being run on the server. 
> 
> Ok, figured that out as well. The polyfill was being called immediately on module execution instead of waiting for the startup sequence. So that will be in the PR as well. 

For the record, the polyfill mentioned was moved to a different part of tiddlywiki so the problem and the file were no longer an issue.
