### ISSUE TITLE
[IDEA] "Template" field to specify default template for tiddlers.

### ISSUE THREAD

**Issue by flibbles** [Jermolene/TiddlyWiki5#4626]
I'm building an XML toolkit plugin for TiddlyWiki, and I've run into a problem I've hit before. I'd like to be able to render those XML tiddlers in the story river, but only through a template, because seeing the raw XML is not useful.

If we had a core "template" field, like "list" or "tags", it could specify a template which TiddlyWiki would use to render the tiddler by default. I've looked through the code, and it seems the best way to do this would be to change the way the transcludeinline and transcludeblock rules work. So that they either take `{{||THIS_template}}`, or they use the template field when a tiddler is called `{{like_This}}`. It's about three lines of extra code, which I'd be happy to do (and test).

The core tiddler **wikified-tiddler.tid** would need to be changed from, `<$transclude />` to `{{}}`, and some of the render commands might want to take the "template" field into consideration. However, `<$transclude>` and `wiki.renderTiddler` wouldn't touched by this change.

Any thoughts? This could be used on data tiddlers to render them more meaningfully, rather than as their raw data. Instead of having to render them through `<<tabs>>` or something, which doesn't always work for me.

**Comment by flibbles** [comment]
However, I can understand if this will be too back-compat breaking. I am looking into a solution with my XML files by including processing instructions like:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<?tiddlywiki template="MyTemplate"?>
```

And it's actually quite promising. It works in the story river, and it's legal XML.

**Comment by pmario** [comment]
hmmm, It would be nice to have a mechanism that would allow different `View-` and `EditTemplates` to be used based on "something"

**Comment by pmario** [comment]
There are some long standing issues, that discuss this topic. 
see: More flexible view/edit templates (was `$:/tags/PlainText`) #1189 

I think, the main problem was "nested transclusions". We didn't come to a conclusion. ... But IMO it would be worth a new discussion.

**Comment by pmario** [comment]
I'm still a fan of a differentiation between "render-type" and "content-type"

**Comment by joshuafontany** [comment]
I'm looking at how to switch out the tiddler body, instead of adding UI segments, via Tags. Good overview, thank everyone.

**Comment by twMat** [comment]
[Related discussion](https://groups.google.com/forum/#!topic/tiddlywikidev/a4bhQ_gIMvw).

**Comment by flibbles** [comment]
Gonna close this. I got my working solution with my [tw5-xml plugin](https://flibbles.github.io/tw5-xml/), and it's pretty nifty. I won't be pursuing this, and I don't think anyone else is either.

**Comment by pmario** [comment]
Hmm, I'm not sure, if I see the relation between a "per tiddler template" and your XML plugin.

**Comment by flibbles** [comment]
I wanted a way to render XML tiddlers through a template by default. Having a field attached to tiddlers called "template" would have solved my problem, and also anyone who's ever wanted to show something other than the raw data for dictionary tiddlers.

But I can read the winds. This feature isn't happening. I managed to solve this problem with my XML case with the processing instruction:
```xml
<?tiddlywiki template={{!!template}}?>
```
or something of the like. Which actually works pretty well, I think. It's what processing instructions are for, and my way is more flexible... for XML.

Dictionary and JSON tiddlers are still stuck looking like unhelpful garbage, but it is what it is. It'll only make my XML plugin more popular.
