### ISSUE TITLE
[BUG] tiddler with _canonical_uri not showing in 5.1.22

### ISSUE THREAD

**Issue by linonetwo** [Jermolene/TiddlyWiki5#4642]
**Describe the bug**

This tiddler is not existed:

https://onetwo.ren/wiki#TiddlyWikiIconBlack.png

while I have this in the source code:

```
<div
title=TiddlyWikiIconBlack.png
type=image/png
created=20200414094148855
modified=20200414094152119
tags=素材
tmap.id=250e11d3-7205-4603-b0a9-b4cbcac2fc65
_canonical_uri=https://raw.githubusercontent.com/linonetwo/wiki/master/MemeOfLinonetwo/tiddlers/TiddlyWikiIconBlack.png></div>
```

**To Reproduce**

// I will try to handle this issue by my self.

1. Go to https://onetwo.ren/wiki#TiddlyWikiIconBlack.png
2. It is not exist
3. Right-click to view the source, search for `TiddlyWikiIconBlack.png
`
4. It exists in the source, with correct `_canonical_uri`

**Expected behavior**
It shows as `external-image` build target expects.

**Desktop (please complete the following information):**
 - OS: MacOS 10.15.4
 - Browser Firefox 76.0
 - Version 5.1.22

**Additional context**
I'm using this build target:

```
        "externalimages": [
            "--setfield",
            "[is[binary]] [type[application/msword]]",
            "_canonical_uri",
            "$:/core/templates/canonical-uri-external-image",
            "text/plain",
            "--setfield",
            "[is[binary]] [type[application/msword]]",
            "text",
            "",
            "text/plain",
            "--rendertiddler",
            "$:/core/save/all",
            "index.html",
            "text/plain"
        ],
```

And my `$:/core/templates/canonical-uri-external-image` is:

```

https://raw.githubusercontent.com/linonetwo/wiki/master/MemeOfLinonetwo/tiddlers/<$view field="title" format="doubleurlencoded"/>
```

**Comment by linonetwo** [comment]
This will load (because it contains a `<pre></pre>` tag:

```html
<div title=SRAM选择电路.png type=image/png created=20200608122338963 modified=20200608122343904 tmap.id=3ab32c1b-a6fd-4d5e-84df-e315916455c6 creator=林一二 modifier=林一二 _canonical_uri=https://raw.githubusercontent.com/linonetwo/wiki/master/Meme-of-LinOnetwo/tiddlers/SRAM%E9%80%89%E6%8B%A9%E7%94%B5%E8%B7%AF.png><pre></pre></div>
```

These won't (contains a single `a` or `<div>a</div>` or  `<div><pre></pre></div>` is not enough for it to load:

```html
<div title=SRAM选择电路.png type=image/png created=20200608122338963 modified=20200608122343904 tmap.id=3ab32c1b-a6fd-4d5e-84df-e315916455c6 creator=林一二 modifier=林一二 _canonical_uri=https://raw.githubusercontent.com/linonetwo/wiki/master/Meme-of-LinOnetwo/tiddlers/SRAM%E9%80%89%E6%8B%A9%E7%94%B5%E8%B7%AF.png>a</div>
```

```html
<div title=SRAM选择电路.png type=image/png created=20200608122338963 modified=20200608122343904 tmap.id=3ab32c1b-a6fd-4d5e-84df-e315916455c6 creator=林一二 modifier=林一二 _canonical_uri=https://raw.githubusercontent.com/linonetwo/wiki/master/Meme-of-LinOnetwo/tiddlers/SRAM%E9%80%89%E6%8B%A9%E7%94%B5%E8%B7%AF.png><div>a</div></div>
```

```html
<div title=SRAM选择电路.png type=image/png created=20200608122338963 modified=20200608122343904 tmap.id=3ab32c1b-a6fd-4d5e-84df-e315916455c6 creator=林一二 modifier=林一二 _canonical_uri=https://raw.githubusercontent.com/linonetwo/wiki/master/Meme-of-LinOnetwo/tiddlers/SRAM%E9%80%89%E6%8B%A9%E7%94%B5%E8%B7%AF.png><div><pre></pre></div></div>
```

**Comment by linonetwo** [comment]
Now here is a workaround:

```json
"externalimages": [
      "--setfield",
      "[is[binary]] [type[application/msword]]",
      "_canonical_uri",
      "$:/core/templates/canonical-uri-external-image",
      "text/plain",
      "--setfield",
      "[is[binary]] [type[application/msword]]",
      "text",
      "$:/core/templates/canonical-uri-external-image",
      "text/plain",
      "--rendertiddler",
      "$:/core/save/all",
      "index.html",
      "text/plain"
    ],
```

This build target keeps tiddler from being empty, so it won't be omitted by tiddlywiki@5.1.22

**Comment by linonetwo** [comment]
My fault...

I have

```tid
created: 20200412025117549
creator: LinOnetwo
title: $:/core/templates/canonical-uri-external-image
type: text/vnd.tiddlywiki

<!--

This template is used to assign the ''_canonical_uri'' field to external images.

Change the `./images/` part to a different base URI. The URI can be relative or absolute.

-->
https://raw.githubusercontent.com/{{$:/GitHub/Repo}}/master/{{$:/config/linonetwo/github-external-image/tiddler-folder-name}}/<$view field="title" format="urlencoded"/>
```

But its 

```
title: $:/config/linonetwo/github-external-image/tiddler-folder-name

tiddlers
```

was `Meme-of-LinOnetwo/tiddlers` before, and I forget to chage this.

**Comment by linonetwo** [comment]
I can see _canonical_uri is ignored, instead tw try to load it with ./{{!!title}}

![Screen Shot 2020-10-24 at 8 02 21 PM](https://user-images.githubusercontent.com/3746270/97081280-ef5e2600-1633-11eb-9a8d-3c34639f371d.png)

**Comment by Jermolene** [comment]
Hi @linonetwo the implication of the screenshot of the code is that the tiddler "Expanding Look Ahead Adder Equations.png" doesn't exist, because "tiddler" is showing as "undefined".

**Comment by linonetwo** [comment]
![Screen Shot 2020-10-24 at 8 33 23 PM](https://user-images.githubusercontent.com/3746270/97081906-2c2c1c00-1638-11eb-94ff-6cf9381d5112.png)


But the tiddler is actually in the source.

Where can I look at?

**Comment by Jermolene** [comment]
> But the tiddler is actually in the source

The issue is whether the tiddler is in the runtime store. Try executing `$tw.wiki.getTiddler(""Expanding Look Ahead Adder Equations.png")` in the JS console to check for the existence of the tiddler.

**Comment by linonetwo** [comment]
![Screen Shot 2020-10-24 at 11 51 58 PM](https://user-images.githubusercontent.com/3746270/97086088-ea10d380-1653-11eb-9c53-1058b6d2553f.png)

It is somehow undefined.

I should read the part that load tiddlers from these DIV from html file...

**Comment by Jermolene** [comment]
Hi @linonetwo I suspect that the tiddler is being read from the HTML file OK at startup, but that later on it is being deleted by the synchronisation process.

**Comment by linonetwo** [comment]
Hi Jeremy, I figure out the cause is http://perfectionkills.com/experimenting-with-html-minifier/#remove_empty_elements
Which I was using to reduce HTML size.

TW can parse this as tiddler (with `<pre>`):

```html
<div title="Expanding Look Ahead Adder Equations.png"type=image/png created=20200609151038966 modified=20200609151038966 tmap.id=d8d36b46-9dad-40ce-aa11-75ea7db2df9d _canonical_uri=https://raw.githubusercontent.com/linonetwo/wiki/master/tiddlers/Expanding%20Look%20Ahead%20Adder%20Equations.png>
<pre></pre>
</div>
```

but not this (without `<pre>`):

```html
<div title="Expanding Look Ahead Adder Equations.png"type=image/png created=20200609151038966 modified=20200609151038966 tmap.id=d8d36b46-9dad-40ce-aa11-75ea7db2df9d _canonical_uri=https://raw.githubusercontent.com/linonetwo/wiki/master/tiddlers/Expanding%20Look%20Ahead%20Adder%20Equations.png>
</div>
```

**Comment by linonetwo** [comment]
If you can guide me which file to look at for 

1. being read from the HTML file OK at startup
2. later on it is being deleted by the synchronisation process

I can look into the source and get a better understand of the true cause.
