### ISSUE TITLE
[BUG] node.js not registering publishFilter modifications for $:/core/save-all

### ISSUE THREAD

**Issue by lc-guy** [Jermolene/TiddlyWiki5#4664]
**Describe the bug**
Using the node edition of tiddlywiki, I noticed that creating a global macro named publishFilter, putting a filter in it, and restarting doesn't actually pick up the filter at all.
Even directly modifying $:/core/save-all as a tiddler in my wiki doesn't pick up the edit. I assume the node executable just uses the tiddler from the global tiddlywiki install without looking if there's one with higher priority, nor does it pick up global macros.
I'm trying to stop tiddlywiki from saving $:/StoryList/ to disk, as is the default SaverFilter behaviour (but not built-in to node's filters, for some reason).

**Comment by saqimtiaz** [comment]
The publishFilter is only for the single file version. On node, use the syncFilter instead. Example here:
https://tiddlywiki.com/#%24%3A%2Fconfig%2FSyncFilter

**Comment by lc-guy** [comment]
Ohh, thanks for the info. Works correctly now.
This should probably be put forward somewhere -- couldn't find anything after what I consider some meticulous googling.

**Comment by saqimtiaz** [comment]
@Jermolene this is resolved and can be closed.

**Comment by Jermolene** [comment]
Thanks @saqimtiaz
