### ISSUE TITLE
[IDEA] Creating themes for Tiddlywiki

### ISSUE THREAD

**Issue by ph1-xyz** [Jermolene/TiddlyWiki5#4669]
I'd like to create themes for Tiddly Wiki.

I'd like to understand how to create styles that integrates well with the TW code. I searched for a central stylesheet, but I didn't find it. Is there one? Should I seek another way of styling components, for example inserting classes/style in components?

Which could be the best way to develop frontends for TW?

**Comment by twMat** [comment]
Hi @ph1-xyz and welcome.

Your question is best posed in the [community forum](https://groups.google.com/forum/#!forum/tiddlywiki). Here, in github, we are now limiting matters to be directly actionable issues such as bugs or feature requests. You question is more a "how do I?" type of question. May I recommend that you **close** this thread and repost your question in the discussion group?

**Comment by ph1-xyz** [comment]
Sure!!

Thanks!
