### ISSUE TITLE
[BUG]  Adding a tag from the dropdown in the manager does not work.

### ISSUE THREAD

**Issue by KalciferKandari** [Jermolene/TiddlyWiki5#4673]
**Describe the bug**

Adding a tag in the manager does not work. Neither typing one or selecting one from the dropdown.

Tested with a fresh TiddlyWiki, same issue.

**To Reproduce**

1. Go to $:/Manager.
1. Click on a listed tiddler.
1. Tags section -> Add a tag.

**Expected behavior**

A new tag should be added.

**Desktop:**
 - OS: Windows 10
 - Browser: Firefox, Chrome
 - Version: 5.1.22

**Comment by saqimtiaz** [comment]
@BurningTreeC  could you take a look? This is a bug that crept in with this change:
https://github.com/Jermolene/TiddlyWiki5/commit/74172b35ceae84f254e20d6d7ec4dff2cca692b1#diff-386ecaa300541982a5b1436bba4cef28

The parameter to tag-picker was removed but the Manager still relies on it:
https://github.com/Jermolene/TiddlyWiki5/blob/master/core/ui/Manager/ItemSidebarTags.tid#L31

This will also impact the pull request for keyboard driven inputs. It is also worth checking how that pull request works in the Manager.

**Comment by BurningTreeC** [comment]
@saqimtiaz hi, I've seen this thanks! I'm having a look right now
