### ISSUE TITLE
[BUG] Line breaks rendered incorrectly for Markdown tiddlers

### ISSUE THREAD

**Issue by ifethereal** [Jermolene/TiddlyWiki5#4679]
Currently being addressed by #4684.

---

**Describe the bug**
Line breaks are rendered incorrectly for Markdown tiddlers if `breaks` is `false`. That is, `<br>` appears when `<br>` is meant to be absent; `<br>` is absent when `<br>` is meant to be present.

**To Reproduce**
1. Go to [the _MarkdownExample_ tiddler on the Markdown demo](https://tiddlywiki.com/plugins/tiddlywiki/markdown/#%24%3A%2Fconfig%2Fmarkdown%2Fbreaks:%24%3A%2Fconfig%2Fmarkdown%2Fbreaks%20MarkdownExample).
2. Note that the `breaks` setting is `false` for the Markdown plugin.
3. Observe the multiple `<br>` present in the _MarkdownExample_ tiddler by inspecting the source code of the page (although it can be noticed by eye too).
4. Add two spaces at the end of any line inside a regular plain-text paragraph of the _MarkdownExample_ tiddler which is not followed by a blank line.
5. Observe the disappearance of a `<br>`.

I have observed the same behaviour for Markdown tiddlers on my own TiddlyWiki (running on a Node.js server).

**Expected behavior**
Based on what I understand of the `breaks` setting for Remarkable, since `breaks` is `false`, there should have been no `<br>` within any one paragraph in the _MarkdownExample_ tiddler, and adding the two spaces should have introduced a `<br>`.

**Screenshots**
Using the preview pane to get everything on one screen. (There are two spaces after `This page offers a brief overview of what it's like to use Markdown.`.)

![Screenshot](https://i.imgur.com/JVxq7M3.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Google Chrome 83.0.4103.61, Mozilla Firefox 76.0.1
 - Version: TiddlyWiki 5.1.22

**Additional context**
N/A

**Comment by pmario** [comment]
I can confirm the issue. We will have a closer look.

**Comment by flibbles** [comment]
Weird how we found this issue separately in the same week.

**Comment by flibbles** [comment]
I probably should have just said I have PR fix standing by.

**Comment by saqimtiaz** [comment]
This was resolved in #4684  and be closed @flibbles @Jermolene

**Comment by Jermolene** [comment]
Thanks @saqimtiaz @flibbles
