### ISSUE TITLE
[BUG] - Entity widget not working in Preview dropdown

### ISSUE THREAD

**Issue by BurningTreeC** [Jermolene/TiddlyWiki5#4693]
**Describe the bug**
The ✓entity isn't rendered in the preview dropdown

**To Reproduce**
1. Go to 'https://tiddlywiki.com'
2. Edit the first tiddler
3. Change the preview type
4. See that there's no ✓

**Desktop:**
 - OS: Linux
 - Browser: Chrome and Firefox

**Comment by pmario** [comment]
Did try it windows. ... Works there.

**Comment by BurningTreeC** [comment]
> Did try it with ubuntu. Works. ... Your step 3 says Change preview type. ... to what?

Hi @pmario, it doesn't matter to what, the problem stays the same (for me)

**Comment by pmario** [comment]
which OS do you use?

**Comment by BurningTreeC** [comment]
@pmario Linux, Manjaro(Gnome)

**Comment by Jermolene** [comment]
Hi @pmario I think @BurningTreeC means that the preview type dropdown doesn't show a tick against the currently selected preview type. I can confirm the same problem on Safari.

**Comment by BurningTreeC** [comment]
> Hi @pmario I think @BurningTreeC means that the preview type dropdown doesn't show a tick against the currently selected preview type. I can confirm the same problem on Safari.

exactly, thanks @Jermolene ...

there's a workaround to show the tick:

1. open the preview popup
2. click into the sidebar search input
3. see how the tick appears

**Comment by pmario** [comment]
If you use a node server with a broken connection, the icon is shown if the Network Error counter is updated. ... So you need to wait max 1 minute.

So there seems to be a refresh problem.
