### ISSUE TITLE
[IDEA] - adding some classesto replace whitespace with spans

### ISSUE THREAD

**Issue by BurningTreeC** [Jermolene/TiddlyWiki5#4694]
There are many places where `&nbsp;` or just ` ` are used for styling of the UI and I'd propose replacing those with `spans` with classes like `tc-span-margin-05`, `tc-span-margin-025`, `tc-span-margin-05-left` for example

**Comment by pmario** [comment]
+1 in principle. 

But if there are `&nbsp;`, there should be html elements that follow. .. If so, there shouldn't be extra spans, if we can use existing elements.

**Comment by BurningTreeC** [comment]
> But if there are &nbsp;, there should be html elements that follow. .. If so, there shouldn't be extra spans, if we can use existing elements.

Yes I'm thinking the same

**Comment by Jermolene** [comment]
Apologies for the delay, I agree this would be a worthwhile improvement.

**Comment by BurningTreeC** [comment]
@Jermolene - so I'll try to come up with a PR in time

**Comment by BurningTreeC** [comment]
@Jermolene, what names would you prefer for the classes? I was thinking about classes that add a margin-right, a margin-left, and both a margin-right and margin-left of 0.5em (which should replace &nbsp;) ... we could call the classes like "tc-margin-05em, tc-margin-05-em-right, tc-margin-05em-left and so on ...?

**Comment by pmario** [comment]
>we could call the classes like "tc-margin-05em, tc-margin-05-em-right, tc-margin-05em-left and so on ...?

IMO you shouldn't use the "05em" part in the name. If we want to change it to 0.4em or rem, the name would be invalidated. 

tc-small-margin-xxxxx, tc-tiny-margin-xxxx  would be 2 possibilities I can think of atm. or even 

tc-push-left and tc-push-right may be more generic. You could use both margin and padding to push "content" out of the way.

**Comment by saqimtiaz** [comment]
Maybe tc-small-gap rather than push?

**Comment by pmario** [comment]
>Maybe tc-small-gap rather than push?

hmmm, gap doesn't have a direction, which should be part of the class so tc-gap-left, tc-gap-right?

**Comment by BurningTreeC** [comment]
Perhaps tc-small-gap for margin-left+margin-right, tc-small-gap-left and tc-small-gap-right?

**Comment by saqimtiaz** [comment]
I am wondering about order, tc-gap-left-small?

**Comment by BurningTreeC** [comment]
I like tc-gap-small, tc-gap-left-small etc.
