### ISSUE TITLE
[BUG] Markdown table no center and right-alignment

### ISSUE THREAD

**Issue by shorca** [Jermolene/TiddlyWiki5#4698]
**Describe the bug**
The markdown plugin does not render tables correctly when there are centered or right-aligned columns. Columns always align to the left.

**To Reproduce**
1. Go to https://tiddlywiki.com/plugins/tiddlywiki/markdown/
2. Click on 'MarkdownExample'
3. Add table with center or right alignment such as 

```
| Tables   |      Are      |  Cool |
|----------|:-------------:|------:|
| col 1 is | left-aligned | $1600 |
| col 2 is | centered in the middle |   $12 |
| col 3 is | right-aligned |    $1 |
```
4. See the table rendered. Here is a screenshot:

![Screenshot from 2020-06-04 05-50-22](https://user-images.githubusercontent.com/64256736/83759017-c9ee6280-a627-11ea-9679-edc3702c5017.png)

**Expected behavior**
| Tables   |      Are      |  Cool |
|----------|:-------------:|------:|
| col 1 is | left-aligned | $1600 |
| col 2 is | centered in the middle |   $12 |
| col 3 is | right-aligned |    $1 |

**Desktop**
 - OS: Ubuntu 18.10
 - Browser [brave]

**Comment by pmario** [comment]
I can confirm, that there seems to be a problem with remarkable.js V2.0.0 which is used by TW as a dependency. 

remarkable text page, doesn't have the problem. It uses an older version V1.6.0 ... we would need to test it with an older version.
