### ISSUE TITLE
[IDEA] - add ability to for compare operator to refer to fields other than title

### ISSUE THREAD

**Issue by hoelzro** [Jermolene/TiddlyWiki5#4699]
**Is your feature request related to a problem? Please describe.**

I was talking with a friend today about accomplishing something with TiddlyWiki - namely, he wanted to close all tiddlers in the story list that hadn't been modified in a certain period of time.  I figured this would be simple using `compare`, but it looks like `compare` can only compare the titles of its input elements.

**Describe the solution you'd like**

I'd like to see if there's a solution to this already - if not, I was thinking maybe a field operand could be added to `compare`.

**Describe alternatives you've considered**

**Additional context**

**Comment by saqimtiaz** [comment]
As of 5.1.22 you can compare dates:

**Comment by hoelzro** [comment]
Awesome, thanks @saqimtiaz!  I think `days` will help my friend out - as far as compare goes, the date would need to be the input to the filter, right? You can't currently do anything like `[tag[Review]compare:number:gteq:review_count[5]]`?

**Comment by KendrickLamarck** [comment]
Just another idea: You can do `[tag[Review]get[review_count]compare:number:gteq[5]]`, use a filter like that one in a `<$list>` widget and access the titles via `{{!!title}}` inside the widget.

**Comment by hoelzro** [comment]
@KendrickLamarck Interesting - how would that work? If I `get[review_count]`, wouldn't the "title" getting passed through `compare:number` be the value of the `review_count` field, and thus that, rather than the title, be used for `currentTiddler` to resolve `{{!!title}}`?

**Comment by KendrickLamarck** [comment]
@hoelzro Ah, what I wrote was slightly wrong. But what you can do is

```
<$list filter="[tag[Review]]">

{{{ [{!!title}get[review_count]compare:number:gteq[5]then{!!title}] }}}

</$list>
```

and that should print the titles that you want in your example.

**Comment by hoelzro** [comment]
@KendrickLamarck Cool, thanks!

**Comment by saqimtiaz** [comment]
As of 5.1.23 you can use the `:filter` run prefix to do the following:

`{{{ [tag[Review]] :filter[get[review_count]compare:number:geteq[5]] }}}`

@hoelzro @Jermolene I suggest that we can close this issue.

**Comment by Jermolene** [comment]
Thanks @saqimtiaz
