### ISSUE TITLE
[IDEA] Notification if duplicated attachment

### ISSUE THREAD

**Issue by xeor** [Jermolene/TiddlyWiki5#4703]
**Is your feature request related to a problem? Please describe.**
If I drag an attachment to tw5 with the same name as an existing. It gets overwritten.

**Describe the solution you'd like**
A notification if the file exists, or maybe it can append a unique number.

**Describe alternatives you've considered**
Trying to keep track, or checking if the file exists before I upload it.

**Additional context**
This might lead to data gone missing

**Comment by pmario** [comment]
What do you mean by attachment? 

I did test it with a json file with 2 tiddlers. ... You are right, there is no info.

As a workaround, you could use my [bundler plugin](https://wikilabs.github.io/editions/bundler/#%24%3A%2Fplugins%2Fwikilabs%2Fbundler), which contains an import handler, that gives you some info about existing tiddlers.

**Comment by pmario** [comment]
This is the intro thread at GG: https://groups.google.com/forum/#!msg/tiddlywiki/_Uqbg08Pjow/J-coR68cCAAJ

**Comment by xeor** [comment]
Thanks for the tip @pmario . I mean drag&dropping a file. And your plugin seams to give a warning :)
But I'm not sure what the rest of your plugin does tho? I read about it, but I'm not sure I understand what it does (except solving my little problem tho).

**Comment by pmario** [comment]
You basically only need the "modified" import mechanism. The bundler stuff shouldn't have any side effects, if you don't use it.

**Comment by saqimtiaz** [comment]
This is resolved in 5.1.23 with rename support in the import UI as well as a warning about tiddlers that already exist.

@xeor @Jermolene this can be closed.

**Comment by Jermolene** [comment]
Thanks @saqimtiaz
