### ISSUE TITLE
[BUG] RSOE wikify widget

### ISSUE THREAD

**Issue by twMat** [Jermolene/TiddlyWiki5#4745]
Type this and save the tiddler or merely preview:

><$wikify name=y text={{!!text}}></$wikify>

This causes RSOE "Uncaught RangeError: Maximum call stack size exceeded" (presumably self recursion)

Note that the `y` is not called.

**Comment by saqimtiaz** [comment]
I would say that is to be expected. It is similar to what will happen if you transclude a tiddler inside itself.
You are creating a loop, wikifying the tiddler text over and over.

Do you want a more user friendly error message?

**Comment by twMat** [comment]
While I agree it is to be expected (for those who understand the reason), my impression is that we wish to eliminate all identified cases that cause RSOE. And, specifically, I believe we have mechanisms to prevent self recursion, so I was thinking it is "just a matter simply applying that mechanism" (...easy peasy, right!? ;-) ;-)

**Comment by pmario** [comment]
>This causes RSOE "Uncaught RangeError: Maximum call stack size exceeded" (presumably self recursion)

At tiddlywiki.com using FF 78, I do get "Internal Error: too much recursion!" ... 

So which browser do you use?

**Comment by twMat** [comment]
>So which browser do you use?

Sorry, using Win10 and Chrome. Same error message for Edge, i.e "Uncaught RangeError: Maximum call stack size exceeded"

**Comment by pmario** [comment]
@twMat -- I did test this one with v5.3.1 with FF and Edge and could not see the problem anymore.
