### ISSUE TITLE
[BUG] Markdown doesn't process WikiLinks

### ISSUE THREAD

**Issue by avks** [Jermolene/TiddlyWiki5#4747]
**Describe the bug**
Markdown plugin doesn't parse WikiLinks even if `renderWikiText` is enabled.

**To Reproduce**
1. Install official markdown plugin
1. Go to `$:/config/markdown/renderWikiText`
2. Set the value to `true`
3. Create a new tiddler (with content type set to `text/x-markdown`) with `[[Title of Existing Tiddler]]`
4. Markdown doesn't create a link to the existing tiddler

**Expected behavior**
Markdown should create link to `Title of Existing Tiddler`

**Desktop:**
 - OS: Mac OSX 10.14
 - Browser: Firefox 78
 - Tiddlywiki Version 5.1.22

**Additional context**
I do have to the option to create a link in markdown using `[Title of tiddler](link to tiddler)` but that's lengthy process. I would rather prefer `[[Title of tiddler]]`

Also, thank you to @Jermolene and the community for this great tool. I have been using it for couple of days and I spend about 26 hours a day tweaking things. The possibilities are endless. Here's a heartfelt thanks to the community for this gift!

**Comment by avks** [comment]
Okay, I have fixed the issue with this:
1. Create a new tiddler: `$:/config/markdown/renderWikiTextPragma`
2. Add the following:
   ```
   \rules only html image macrocallinline syslink transcludeinline wikilink filteredtranscludeblock macrocallblock transcludeblock prettylink
   ```
(Thanks to Dave Gifford’s [Stroll](https://giffmex.org/stroll/stroll.html)

However couple suggestions:
1. Since I am adding a shadow tiddler to the official markdown plugin, it would future upgrades break.
2. The `renderWikiText` option should enable linking with `[[ ]]`.

Keeping it open for visibility for core devs.

**Comment by saqimtiaz** [comment]
@avks Welcome to the community. 

This may be a duplicate of issue #4610 

The consensus reached was to provide a UI to toggle which TW parser rules would be enabled in Markdown tiddlers.

**Comment by avks** [comment]
Aha, should have searched before creating the issue. Thanks!
