### ISSUE TITLE
[BUG] Palette switcher preview doesn't work with indirect colours

### ISSUE THREAD

**Issue by Jermolene** [Jermolene/TiddlyWiki5#4755]
The preview swatches in the palette switcher in control panel do not correctly show colours that are defined indirectly via the `<<colour>>` macro

1. Go to https://tiddlywiki.com/
2. Click on the cog icon to open the control panel, and choose the "Appearance" and then "Palette" tabs
3. Scroll down to the "Show Editor" button and click it
4. Locate the entry for "General Background"/"background" (which should currently be set to `#ffffff`)
5. Change it to `<<colour alert-background>>`
6. Note that the background colour of tiddlers changes to yellow, and 
7. The error is that the preview swatch should show the background colour as the second box, but it doesn't show the correct yellow colour

<img width="475" alt="image" src="https://user-images.githubusercontent.com/174761/87409752-51cb7300-c5bd-11ea-8a56-70e797a9c3ce.png">

This behaviour is observed on all platforms.

**Comment by Jermolene** [comment]
@BurningTreeC I wondered if you'd be able to kindly look at this?

**Comment by Jermolene** [comment]
I should have added a link to a Google Group discussion where this issue is raised:

https://groups.google.com/d/msgid/tiddlywiki/52e787ec-eb8a-429c-8c83-c895a016fed1o%40googlegroups.com

**Comment by BurningTreeC** [comment]
@Jermolene yes I can have a look when I have time

**Comment by Jermolene** [comment]
Thanks @BurningTreeC
