### ISSUE TITLE
[BUG] Prerelease styling bug in custom field area

### ISSUE THREAD

**Issue by twMat** [Jermolene/TiddlyWiki5#4759]
If current 5.1.23-pre is set to *Fixed story/Fluid sidebar*, you get this:

![image](https://user-images.githubusercontent.com/4534056/87704806-361ec300-c79d-11ea-96fc-98f44f98d2bb.png)

I note the field for "field name" is wider than in 5.1.22. A quick investigation shows `width:100%` in .22 and `width:auto` in .23 but there seem to be other modifications as well.

Might it be a consequence of one of @BurningTreeC 's styling mods?

**Comment by pmario** [comment]
fix is merged. IMO can be closed.

**Comment by twMat** [comment]
Thanks @BurningTreeC and @pmario
