### ISSUE TITLE
[IDEA] Easier keyboard shortcut to accept offered tag shortcut

### ISSUE THREAD

**Issue by hyphz** [Jermolene/TiddlyWiki5#4762]
**Is your feature request related to a problem? Please describe.**
When typing in a tag, TiddlyWiki offers existing tags that match what has been typed so far. However, there is no easy way to use the keyboard to accept a suggestion. Even when only one tag is shown, hitting Return does not accept the suggestion; instead it creates a new tag with the partially typed name, which is a potential trap for creating incorrect tags. Pressing the down arrow does not move the cursor into the suggestion box to allow a suggestion to be accepted, as it does in most systems. The only way to accept a suggestion is to click on the suggestion, which requires moving a hand from the keyboard to the mouse.

**Describe the solution you'd like**
Pressing the down arrow while tag suggestions are showing should highlight the active tag suggestion and allow it to be accepted by pressing return.

**Comment by twMat** [comment]
This is in the https://tiddlywiki.com/prerelease and most likely coming in the next update. 
Please close this issue.
