### ISSUE TITLE
[BUG] - Upgrade to 5.1.22 causes severe issue

### ISSUE THREAD

**Issue by diva-D** [Jermolene/TiddlyWiki5#4764]
**Describe the bug**

After upgrading to 5.1.22 using https://tiddlywiki.com/upgrade.html, the tiddler body field is somehow now connected to the field key/property fields - in that changing the text in one changes the text in the other.

**To Reproduce**
1. Upgrade tiddler from 5.1.21 to 5.1.22
2. Create new tiddler or open existing one
3. Tiddler body is now connected to field key/value boxes (even for existing)

**Expected behavior**

The body is separate from the fields.

**Screenshots**

![CleanShot 2020-07-22 at 10 49 22](https://user-images.githubusercontent.com/28694272/88115130-97192180-cc09-11ea-99ea-4a0f74a44043.gif)

**Desktop (please complete the following information):**
 - OS: Mac 10.13.6
 - Browser: Chrome using TiddlyDrive
 - Version: 5.1.22

**Comment by twMat** [comment]
Any plugins or other things installed? Or are you saying this happens for a completely empty 5.1.21 --> 5.1.22 ?

**Comment by diva-D** [comment]
Here are the plugins I have

![image](https://user-images.githubusercontent.com/28694272/88116581-f9275600-cc0c-11ea-94f3-477fdaf8580a.png)

It is not empty. It is upgrading my current TW file which has ~800 tiddlers.

**Comment by twMat** [comment]
So, chances are pretty high that it is not the TW core causing this. After all, several other people have upgraded from .21 to .22. 
This is how to get help:

1. Close this thread. You can always reopen it later IF you, after all, conclude that it *is* the core causing problems.
2. Open a thread in the [forum](https://groups.google.com/forum/#!forum/tiddlywiki) where there are a lot of friendly people. I have already written up some text that I'm ready to post for you there :-)

Here on github we are more strict on what should be discussed. With 800+ issues this might not seem to be the case... but that is exactly why we need to be more strict.
