### ISSUE TITLE
[BUG] Renaming tiddler with lazy-loading enabled can delete other tiddlers' bodies

### ISSUE THREAD

**Issue by flibbles** [Jermolene/TiddlyWiki5#4767]
When you rename a tiddler (say, from A to B), then any tiddler that references A in its `tags` or `lists` field which is still skinny (it hasn't been loaded yet) will have its `text` field deleted. This is because the relinker will update the `tags` or `lists` field, but when it goes to save the tiddler, it doesn't have the text (because the server never gave it to the browser), so the browser ends up telling the server that the new text is an empty string.

This is **especially problematic** if you have my *Relink* plugin installed, [since relinking is far more likely to occur](https://github.com/flibbles/tw5-relink/issues/20).

**Fix**

There are two ways to fix this as far as I can see:

1. **The easy way:** Program the browser to load any skinny tiddlers whose fields it must update before sending it back to the server to update. Easy, but I don't think a good solution.

2. **The hard-but-better-longterm-solution way:** Create a new SyncAdapter task, RenameTiddler. The renaming occurs on the server, and then maybe the server sends the browser a list of updated tiddlers. This seems like more work, but it's definitely **my** preferred solution, since it's the only way my *Relink* plugin could handle lazy-server renaming. *Relink* can change the bodies of tiddlers, but unless it eagerly loads *every* tiddler, it can't do its job on the browser. The server has to do it. I realize *Relink* isn't core Tiddlywiki's problem, but if we ever want to adopt better relinking in core, this is necessary.

Does anybody have any idea how feasible solution 2 is? I'm not that familiar with the syncAdapter.

-Flibbles

**Comment by flibbles** [comment]
So... any thoughts? Because this is a pretty bad bug for anyone using lazy loading.

**Comment by Jermolene** [comment]
Hi @flibbles apologies for the late response.  As you say, moving rename operations to the server would be the logical solution. One could imagine something along the lines of the remote command processing in #3461 for this. Having said that, I find that lazy loading introduces a lot more problems than it solves, and I would seriously consider dropping it entirely. I don't think that there is much practical benefit in most situations.

**Comment by flibbles** [comment]
Understood. I'll have my plugin warn against use of lazy-loading. I suppose this bug should be closed as "Won't fix" then?

**Comment by Jermolene** [comment]
Hi @flibbles while there's no easy solution there are definitely a few things we could do:

* Pick up the external tasks work that I referenced above
* Canvas opinion about dropping support for lazy loading

**Comment by joshuafontany** [comment]
This has come up in the Google Groups here: https://groups.google.com/g/tiddlywiki/c/dT-3CS_KA_Y

> 
kswk...@gmail.com
unread,
Apr 19, 2022, 4:52:13 PM (7 days ago) 
to TiddlyWiki
A bunch of files with the same tag appear overwritten. They won't load when I select them and the contents (except meta data) is empty in the node files. 

All the files affected have the same tiddler tag. I set the tiddler to be a system tiddler so it would autoload in the side bar.

Markdown files that are now empty have a meta file that says _is_skinny at the top.
All the tiddler files that have been over written say _is_skinny: at the top for example example:
_is_skinny:
created: 20220331194245560
creator: khalfani
modified: 20220419190910674
modifier: khalfani
tags: $:/Bookmark
title: Notes
type: text/vnd.tiddlywiki


Is it supposed to work like this or should I try to recover these using my backup?

Also Is there another way to make a sidebar tiddler autoload without making it a system tiddler?
>

**Comment by flibbles** [comment]
This issue has [come up again with TiddlyMap](https://github.com/felixhayashi/TW5-TiddlyMap/issues/431). A user had his entire TiddlyWiki deleted after he installed TiddlyMap because it added a `tmap.id` field to every tiddler.

**Comment by linonetwo** [comment]
@flibbles Is there a PR for this? I want my wiki to be lazy to fix the tid10k issue...

**Comment by flibbles** [comment]
A PR was already merged, and this can be closed, but I might still recommend against lazy loading. It's still problematic in many ways.

**Comment by linonetwo** [comment]
You mean we can't do fulltext search? That can be done by searching using server API. I don't know if there are other problem exists, I'm gonna have a try after I add API based searching to command palette plugin.

**Comment by linonetwo** [comment]
Oh, you mean relink can't work on server side in https://github.com/Jermolene/TiddlyWiki5/pull/7014 , why, I'm curious about this, I'm going to read your code.

**Comment by flibbles** [comment]
Relink doesn't work with lazy loading because Relink is executed on client side, so it would either need to ignore the bodies of unloaded tiddlers (which defeats the purpose of Relink), or it would need to eagerly load all tiddlers (which defeats the purpose of lazy loading.) There really isn't a mechanism to support server-side relinking, and it doesn't seem like anyone on the core team is interested in implementing or supporting that.

That's the general problem with lazy loading. It seems like everyone just wants to forget about it. Core developers don't work on it, and plugin developers never take it into considerations when making their plugins. So lazy loading is bound to be problematic in many easy-to-find cases.

**Comment by linonetwo** [comment]
Well, as tw mostly branded as single file HTML wiki, this is reasonable. Most of old users are using HTML wiki, so it's up to our nodejs wiki users to push this.

 I'm thinking on this, as far as I know, plugins is working on server side, we just need to trigger the execution. Maybe we can add a server route to execute the "relink" on server side, and let [https://github.com/twcloud/tiddlyweb-sse](https://github.com/twcloud/tiddlyweb-sse) push the change back to the client side.

I'm also planning to add a async search server route for command palette plugin, to execute filter expression on server side (by concat the keyword to a template filter expression, so we don't need to send expression via HTTP request, which is dangerous) and return the search result.

This kind of usages may requires an API token mechanism, to ensure only trusted client can send these requests.

Just some humble thinking.
