### ISSUE TITLE
[BUG] Backlinks don't show up for lazy loading

### ISSUE THREAD

**Issue by avks** [Jermolene/TiddlyWiki5#4768]
**Describe the bug**
Backlinks don't show up if the tiddlers are not loaded yet. Once loaded, backlinks are working just as fine.

**To Reproduce**
@crazko has a very useful plugin named `krystal`. I took out the backlinks feature by adding a new tiddler called [`references`](https://github.com/crazko/krystal/blob/master/plugins/rmnvsl/krystal/references.tid) with the following content:
```
<$list filter="[!is[system]all[current]backlinks[]sort[title]] -[is[current]] +[limit[1]]" variable=none>
<ul class="krystal-references">
<li class="krystal-references__title"><strong><$transclude tiddler="$:/plugins/avks/bidili/referenceshere" field="text" mode="inline" /></strong></li>
<$list filter="[!is[system]all[current]backlinks[]sort[title]] -[is[current]]">
<li class="krystal-references__reference">
<$link>
<b><$view field="title" /></b>
<div class="krystal-references__content"><$transclude field="text" mode="inline" /></div>
</$link>
</li>
</$list>
</ul>
</$list>
```
Essentially, this tiddler uses `[!is[system]all[current]backlinks[]sort[title]] -[is[current]]` to show backlinks to the current tiddler.

The above works perfectly for the nodejs version if the server is started with `$/config/save/all`. **But** if the server is started with `$/config/save/lazy-all`, the backlinks are not shown until _all_ the tiddlers are loaded into the DOM.

**Expected behavior**
Backlinks to a certain tiddler should be shown at all times: whether they tiddlers are lazy-loaded or not.

**Desktop**
 - OS: All
 - Browser: Chrome, Safari, Firefox
 - Version: latest

**Comment by pmario** [comment]
Backlinks are calculated from the tiddler text field. Lazy loaded tiddlers _don't_ load the text field. ... So the wiki core isn't able to calculate backlinks without the needed information!

If you need backlinks you can't use lazy-loading or vice versa. ... You decide!

**Comment by avks** [comment]
@pmario thanks for the straight and simple response. Closing it.
