### ISSUE TITLE
[BUG] $:/Import tiddler should not be saved in single file

### ISSUE THREAD

**Issue by saqimtiaz** [Jermolene/TiddlyWiki5#4772]
In single file tiddlywiki's the $:/Import tiddler is saved, whereas on node.js it is not.

Saving this tiddler in single file wikis can lead to accidentally saving data in wikis and increasing the file size, as it is not clear to users that closing this tiddler without clicking cancel, leaves that data from the incompleted import in the wiki. At the very least, closing the $:/Import tiddler with pending data should provide feedback that the data will be saved.

Background: I received a bug report from a colleague I had setup a TW for, that their file size had ballooned to 100+MB and could not be easily shared via email. Investigation showed that at some point they had accidentally dragged a PDF into the wiki, and then closed the $:/Import tiddler and saved and continued using the wiki for several weeks.

**Comment by pmario** [comment]
There should be an easy fix.
