### ISSUE TITLE
[BUG] plugintiddlers filter doesn't update value for $:/Import

### ISSUE THREAD

**Issue by saqimtiaz** [Jermolene/TiddlyWiki5#4773]
If `$:/Import` already exists when a single file wiki is loaded, calls to `plugintiddlers[]` will always return the same result as exists on startup, even if the tiddler is changed. This manifests in the user being unable to add more tiddlers to the import tiddler. Only deleting `$:/Import`, saving and reloading resolves the problem.

**To Reproduce**
1. In a single file wiki version 5.1.22, drag and drop a tiddler from tiddlywiki.com to trigger the import interface.
2. Without importing or cancelling the import process, save the wiki and reload.
3. Any attempt to import more tiddlers will not be reflected in `$:/Import` in the story, even though editing the tiddler shows the expected JSON data is present.
4. Even deleting the `$:/Import` tiddler and trying to import will show the same tiddler for import as when the wiki was loaded.

When `$:/Import` exists at startup, it has a `pluginInfo` defined in wiki.pluginInfo. Therefore the filter `plugintiddlers[]` always [returns the pluginInfo value from startup, instead of calling getTiddlerDataCached](https://github.com/Jermolene/TiddlyWiki5/blob/master/core/modules/filters/plugintiddlers.js#L21)

Not saving `$:/Import` is one way to resolve this. See also #4772 

Tested in TiddlyDesktop on Windows 10.

**Comment by pmario** [comment]
Strange things can happen ...

**Comment by saqimtiaz** [comment]
Resolved in #4907
