### ISSUE TITLE
[Dev Process] Travis has stopped reporting build statuses to this repo

### ISSUE THREAD

**Issue by ento** [Jermolene/TiddlyWiki5#4789]
<details><summary>Travis used to report build statuses until July 16 or 17, 2020</summary>

![screenshot of recent commits](https://user-images.githubusercontent.com/21108/89148283-d9920680-d505-11ea-9628-e603c97af9b8.png)

</details>

What I expect: build status reported as green ✔️ or red ❌  marks next to each commit I push to an open PR, and a dedicated check status line at the bottom of PRs (where GitHub reports "This branch has no conflicts with the base branch" and the like). Without these, it's not really discoverable that CI checks are available.

### Turn it off and on again

[One person on Travis's support community reported that it worked](https://travis-ci.community/t/github-ci-notifiactions-from-travis-stopped-working/9238/4).

>  I just switched my repo off and on again in the Travis settings and started a rebuild, and it showed up in GitHub again, so it is worth a try.

https://travis-ci.org/account/repositories lets you turn a repo off and on.

Some recent builds to retry: [push to master](https://travis-ci.org/github/Jermolene/TiddlyWiki5/builds/714182778), [pull request update](https://github.com/Jermolene/TiddlyWiki5/pull/4716).

### Migrate from Legacy GitHub Services to GitHub Apps

[Travis acknowledged](https://travis-ci.community/t/github-status-not-posted-on-commits-on-repositories-using-legacy-service-integration/7798) that there may be issues with status updates for repos that are using Legacy GitHub Services integration.

From further reading, it appears to be that repo builds hosted on **travis-ci.org** are considered legacy, and those that have been migrated to **travis-ci.com** use the newer GitHub Apps integration:

> On May 2nd, 2018 Travis CI announced that open source projects will be joining private projects on travis-ci.com!
> [..]
> We are implementing these changes with GitHub Apps
> https://docs.travis-ci.com/user/migrate/open-source-on-travis-ci-com/

TiddlyWiki5's builds are hosted at travis-ci.org, so I think it uses the legacy integration.

The URL above explains how the migration steps look like on the travis-ci.org side, and [this article](https://docs.travis-ci.com/user/migrate/open-source-repository-migration) explains how to do it on the travis-ci.com side. I followed the latter for my own repos and it seemed to work.

Hosting of public repos on travis-ci.com is still considered to be in beta, so depending on TidddlyWiki5's policy, this might not yet be a desirable change.

**Comment by Jermolene** [comment]
Hi @ento I very much favour moving to GitHub Actions, it's got a very active community and has good integration with GitHub. I've done some experiments in a throwaway repo but not got very far. I'd welcome a PR to switch our existing build process over to GitHub Actions.
