### ISSUE TITLE
[BUG] EditTemplate: "tc-type-selector-wrapper" not containing "tc-edit" and "&nbsp;&nbsp;"

### ISSUE THREAD

**Issue by jdjdjdjdjdjd** [Jermolene/TiddlyWiki5#4794]
Hi! I noticed in the prerelease site, the tiddler **$:/core/ui/EditTemplate/type** does not include 

`<em class="tc-edit"><<lingo Type/Prompt>></em>&nbsp;&nbsp;` 

inside of

`<div class="tc-type-selector-wrapper">`

I think this is a bug because the rest of the EditTemplate segments are completely inside their wrappers and thus can be targetted in styling (5.1.22 doesn't have this bug)

**Desktop (please complete the following information):**
 - Windows 10
 - Chrome
 - 23 Prerelease

**Comment by BurningTreeC** [comment]
@jdjdjdjdjdjd - I added this wrapper so that the type dropdown could be aligned with the type input field. IMO no bug

**Comment by jdjdjdjdjdjd** [comment]
Hi, @BurningTreeC , what I see in the prerelease is that currently `<em class="tc-edit"><<lingo Type/Prompt>></em>&nbsp;&nbsp;` is _not inside_ of `<div class="tc-type-selector-wrapper">`

**v23 Prerelease:**
![image](https://user-images.githubusercontent.com/37834546/89745250-92031000-daed-11ea-875c-6a6de2789d97.png)

Shouldn't it also be inside it? 

In the current stable release, v22
![image](https://user-images.githubusercontent.com/37834546/89745340-1d7ca100-daee-11ea-9ea2-daffb24424e6.png)

Each edit template segment is wrapped, which made it easy to target each segment for styling...

**Comment by BurningTreeC** [comment]
@jdjdjdjdjdjd - I'm preparing a fix
