### ISSUE TITLE
[BUG] Wrong file extension in German translation

### ISSUE THREAD

**Issue by fkohrt** [Jermolene/TiddlyWiki5#4803]
**Describe the bug**
The German translation has a wrong file extension: [`languages/de-DE/Help/savewikifolder.tig`](https://github.com/Jermolene/TiddlyWiki5/blob/6721d70/languages/de-DE/Help/savewikifolder.tig)

**Comment by pmario** [comment]
Nice catch! I did create a PR https://github.com/Jermolene/TiddlyWiki5/pull/4804

**Comment by pmario** [comment]
Anything else you found out?

**Comment by fkohrt** [comment]
Not yet, found it by chance because of [this tiddler](https://tiddlywiki.com/languages/de-DE/index.html#%2Fhome%2Ftravis%2Fbuild%2FJermolene%2FTiddlyWiki5%2Fnode_modules%2Ftiddlywiki%2Flanguages%2Fde-DE%2FHelp%2Fsavewikifolder.tig).

**Comment by pmario** [comment]
OK. .. This seems to be a build artefact. ... Let's hope it will be gone with the next build.
