### ISSUE TITLE
[BUG] Make sure travis build artefact is gone with TW 5.1.23 in german version

### ISSUE THREAD

**Issue by pmario** [Jermolene/TiddlyWiki5#4805]
This tiddler shouldn't be part of the published version.

[/home/travis/build/Jermolene/TiddlyWiki5/node_modules/tiddlywiki/languages/de-DE/Help/savewikifolder.tig](https://tiddlywiki.com/languages/de-DE/index.html#%2Fhome%2Ftravis%2Fbuild%2FJermolene%2FTiddlyWiki5%2Fnode_modules%2Ftiddlywiki%2Flanguages%2Fde-DE%2FHelp%2Fsavewikifolder.tig)

Make sure it's gone with 5.1.23

**Comment by pmario** [comment]
related to:  #4803

**Comment by Jermolene** [comment]
Hi @pmario I don't think there's a problem; the .the erroneous file was only ever distributed via GitHub/npm, and publishing the new version will overwrite it. The .tig file doesn't appear in the output repo https://github.com/Jermolene/jermolene.github.io

**Comment by pmario** [comment]
Cool. So I'll close the issue. I just wanted to have a reminder.
