### ISSUE TITLE
[BUG] Using the external JavaScript template always brings up save and reload warning

### ISSUE THREAD

**Issue by fkohrt** [Jermolene/TiddlyWiki5#4808]
**Describe the bug**
Starting a Node.js wiki with `"root-tiddler=$:/core/save/all-external-js"` always leads to the warning "Please save and reload to allow changes to JavaScript plugins to take effect" after a few seconds. Reloading the page doesn't help.

**To Reproduce**
1. `tiddlywiki wiki/ --init server`
2. `tiddlywiki wiki/ --listen "root-tiddler=$:/core/save/all-external-js"`
3. Open page and see warning

**Expected behavior**
No warning

**Screenshots**
![warning](https://user-images.githubusercontent.com/12914806/90082651-a2470500-dd10-11ea-811d-cb30b6af336b.png)

**Desktop (please complete the following information):**
 - OS: Fedora 31
 - Browser: Firefox
 - Version: 78

**Additional context**
<details>
<summary>Syncer logs</summary>

```
User Agent: Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:78.0) Gecko/20100101 Firefox/78.0
Online Status: true

Log:
2020 8 13 02:53:38.520: Getting status
2020 8 13 02:53:38.922: Status: {"username":"","anonymous":true,"read_only":false,"space":{"recipe":"default"},"tiddlywiki_version":"5.1.22"}
2020 8 13 02:53:38.923: Retrieving skinny tiddler list
2020 8 13 02:53:38.936: Dispatching 'save' task: $:/StoryList
2020 8 13 02:53:38.997: Deleting tiddler missing from server: $:/config/SaveWikiButton/Template
2020 8 13 02:53:38.998: Checking dirty status
2020 8 13 02:53:38.999: Checking dirty status
2020 8 13 02:53:39.000: Dispatching 'load' task: $:/boot/boot.js
2020 8 13 02:53:39.003: Checking dirty status
2020 8 13 02:53:39.029: Checking dirty status
2020 8 13 02:53:39.030: Dispatching 'load' task: $:/boot/bootprefix.js
2020 8 13 02:53:39.038: Checking dirty status
2020 8 13 02:53:39.059: Checking dirty status
2020 8 13 02:53:39.060: Dispatching 'load' task: $:/library/sjcl.js
2020 8 13 02:53:39.064: Checking dirty status
2020 8 13 02:53:39.083: Checking dirty status
2020 8 13 02:53:39.084: Dispatching 'load' task: $:/core
2020 8 13 02:53:39.088: Checking dirty status
2020 8 13 02:53:39.142: Checking dirty status
2020 8 13 02:53:39.143: Dispatching 'load' task: $:/HistoryList
2020 8 13 02:53:39.150: Checking dirty status
2020 8 13 02:53:39.181: Checking dirty status
2020 8 13 02:53:39.182: Checking dirty status
```
</details>

**Comment by phlummox** [comment]
Huh, I was just about to report the same thing.

In case it's of use, [here's][heroku] a running instance on Heroku, exhibiting the behaviour, built from the Dockerfile in [this][docker-repo] GitHub repo.

[heroku]: https://tw5-bug-4808.herokuapp.com/
[docker-repo]: https://github.com/phlummox-bugs/TiddlyWiki5-issues-4808

**Comment by Jermolene** [comment]
Hi @fkohrt @phlummox thanks for the very clear and complete bug report. I'll post a fix shortly.

**Comment by phlummox** [comment]
Thank you very much! I've tried out the new "server-external-js" edition. and so far, all appears to be running swimmingly. Cheers :)
