### ISSUE TITLE
[BUG] Minor typos, mostly in documentation

### ISSUE THREAD

**Issue by fkohrt** [Jermolene/TiddlyWiki5#4815]
**Describe the bug**
- [Simple ways to write protect tiddlers](https://github.com/Jermolene/TiddlyWiki5/blob/tiddlywiki-com/editions/tw5.com/tiddlers/howtos%2FSimple%20ways%20to%20write%20protect%20tiddlers.tid): `but to edit them your will have to find` → `but to edit them you will have to find`
- [[all[tiddlers]search:text:literal[ and and ]]](https://tiddlywiki.com/#:[all[tiddlers]search:text:literal[%20and%20and%20]]): duplicate `and`
- [BuildCommand](https://github.com/Jermolene/TiddlyWiki5/blob/tiddlywiki-com/editions/tw5.com/tiddlers/commands%2FBuildCommand.tid): `See TiddlyWikiFolders for details of defining build targets.` → `See [[tiddlywiki.info Files]] for details of defining build targets.`
- [list-thumbnails Macro](https://github.com/Jermolene/TiddlyWiki5/blob/tiddlywiki-com/editions/tw5.com/tiddlers/macros%2Flist-thumbnails%20Macro.tid): shouldn't the caption say `list-thumbnails`? Because the caption `thumbnails` is already "taken" by [thumbnail Macro](https://github.com/Jermolene/TiddlyWiki5/blob/tiddlywiki-com/editions/tw5.com/tiddlers/macros%2Fthumbnail%20Macro.tid)
- [SystemTags](https://github.com/Jermolene/TiddlyWiki5/blob/tiddlywiki-com/editions/tw5.com/tiddlers/concepts%2FSystemTags.tid): `$:/tags/Macro` is listed twice, the second time it should be `$:/tags/Macro/View`
- [$:/plugins/tiddlywiki/freelinks/readme](https://github.com/Jermolene/TiddlyWiki5/blob/master/plugins/tiddlywiki/freelinks/readme.tid): `customising the shadow tiddler $:/plugins/tiddlywiki/freelinks/macros/view. This tiddler` → `customising the shadow tiddler [[$:/plugins/tiddlywiki/freelinks/macros/view]]. This tiddler`

**Comment by Jermolene** [comment]
Thanks @fkohrt. In the case of the last one, the double square brackets shouldn't be needed, or am I missing something?

**Comment by fkohrt** [comment]
The trailing period is part of the link when I view `$:/plugins/tiddlywiki/freelinks/readme` and is being displayed as non-existent, which confused me while reading the documentation.

**Comment by fkohrt** [comment]
And you might have missed another duplicate `and` [here](https://github.com/Jermolene/TiddlyWiki5/blob/acd2cbf56a64f72c0b7422b2a35b0e1c79e54bcd/editions/tw5.com/tiddlers/howtos/Simple%20ways%20to%20write%20protect%20tiddlers.tid#L29)

**Comment by Jermolene** [comment]
Thanks @fkohrt

**Comment by fkohrt** [comment]
- [WebServer Parameter: tiddler-render-type](https://github.com/Jermolene/TiddlyWiki5/blob/tiddlywiki-com/editions/tw5.com/tiddlers/webserver%2FWebServer%20Parameter_%20tiddler-render-type.tid): ``Alternatively, `text/html` can be used`` → ``Alternatively, `text/plain` can be used``
