### ISSUE TITLE
[IDEA] Add Mac Command key support for DroppableWidget

### ISSUE THREAD

**Issue by kebifurai** [Jermolene/TiddlyWiki5#4820]
**Is your feature request related to a problem? Please describe.**
The only modifier Variable that can be used on mac is "shift", as pressing "ctrl+left click" will automatically simulate a right click, making drag an drop impossible.
This problem can't be fixed with third party software.

**Describe the solution you'd like**
Make the command key a modifier Variable.

**Comment by saqimtiaz** [comment]
There is now support for the alt key on all platforms as well so there are more options: https://github.com/Jermolene/TiddlyWiki5/blob/de69ab0d0e8d7fe355c0c0d463cf5fa194576b2c/core/modules/keyboard.js#L287

I don't think add the command key is a realistic option as it is not cross platform.

In light of this, I think this can be closed @kebifurai @Jermolene

**Comment by Jermolene** [comment]
We do support the "cmd" key for keyboard shortcuts so it would make sense to support it as an event modifier key too, if possible.

**Comment by BurningTreeC** [comment]
@Jermolene - that would then be the "meta" key, right? I can create a PR for that soon

**Comment by Jermolene** [comment]
Hi @BurningTreeC yes, it looks like keyboard.js maps cmd, alt and win to meta.

**Comment by BurningTreeC** [comment]
>yes, it looks like keyboard.js maps cmd, alt and win to meta.

Isn't that problematic?

**Comment by Jermolene** [comment]
I think it's just how browsers work: they have a field called "meta" which they use for the command key.

**Comment by BurningTreeC** [comment]
Ah ok. PR is on the way
