### ISSUE TITLE
[BUG] Mobile Scrolling is broken

### ISSUE THREAD

**Issue by ohare93** [Jermolene/TiddlyWiki5#4824]
**Describe the bug**
Scrolling down on a tiddler which is quite long while in edit mode does not scroll down. It stops ever 5mm or so, unless one grabs outside the edit text box) which takes up most of the space on either side of the screen. It should scroll down

**To Reproduce**
1. Have a tiddler with a long text. The text of this issue here in Github is long enough.
1. Enable editmode
1. Try to scroll to the bottom. It will stop again and a again. Though scrolling up seems to be fine.

**Expected behavior**
The window scrolls the amount you want it to.

**Desktop (please complete the following information):**
 - OS: Android
 - Browser: DuckDuckGo
 - Version: Latest

**Smartphone (please complete the following information):**
 - Device: OnePlus 6T
 - OS: Android
 - Browser: DuckDuckGo
 - Version: Latest

**Additional context**
I did this on a brand new blank tiddler. Made a tiddler by copy pasting the same sentence with a bullet point 40 or so times on my laptop (I am running the server version of TiddlyWiki) then opened it on my mobile.

**Comment by Jermolene** [comment]
Hi @ohare93 I can't duplicate this on Mobile Safari on iOS, so I'm wondering if this is an Android or browser specific problem. Do you have any other browsers installed that you can try?

**Comment by ohare93** [comment]
I just tried on Chrome for Android and have the exact same problem. Looks like an OS specific issue.

**Comment by saqimtiaz** [comment]
I cannot reproduce this on Chrome for Android.
Chrome: 86.0.4240.185
Android 10 on a Huawei p20 pro
