### ISSUE TITLE
[BUG] JavaScript error with Codemirror markdown highlight plugin

### ISSUE THREAD

**Issue by pagdot** [Jermolene/TiddlyWiki5#4825]
**Describe the bug**
The markdown highlight plugin for codemirror shows an error and highlighting inside the editor doesn't work

**To Reproduce**
Static copy of broken Tiddlywiki: https://gist.github.com/pagdot/ce766e48b9da4c97fa4ec85a61a47309

**Expected behavior**
No error, 

**Screenshots**
![error](https://user-images.githubusercontent.com/2229858/90434886-70e28680-e0ce-11ea-99ed-5a931214d5fc.png)

**node.js:**
 - Browser Chromium, Firefox
 - Tiddlywiki Version 5.1.22

**Additional context**

tiddlywiki.info of of broken Tiddlywiki: https://gist.github.com/pagdot/ce766e48b9da4c97fa4ec85a61a47309

**Comment by adithya-badidey** [comment]
Seems like a similar issue to #4821

**Comment by linonetwo** [comment]
Did you install that xml syntax plugin?

**Comment by pagdot** [comment]
Yeah, that fixed it. Maybe it is possible to provide a better error message in the future

**Comment by linonetwo** [comment]
I agree, you can close this issue and open another issue about this.

Maybe auto install related plugin is another option.
