### ISSUE TITLE
[BUG] Keyboard-driven-inputs clashes with customized search results.

### ISSUE THREAD

**Issue by saqimtiaz** [Jermolene/TiddlyWiki5#4826]
I am creating an issue for this as I am not sure if notifications work for [already merged PRs](https://github.com/Jermolene/TiddlyWiki5/pull/4725).

@BurningTreeC @Jermolene

I've discovered a significant issue with the way we have implemented `keyboard-driven-inputs` in #4725 

It requires both the keyboard driven input macro that creates the search input, and the code handling displaying the search results to use the same filter to return search results.

However, the search results can be customised:
https://tiddlywiki.com/#Customising%20search%20results

With an alternative $:/tags/SearchResults tiddler like the one provided in the example at the link above, the keyboard navigation is completely broken since the keyboard driven input and the search results display code no longer use the same filter.

I haven't had the opportunity to give this much thought, but the answer might lie in storing the search filter to be used in a common location that can be accessed by both the macro and the search results code.

**Comment by saqimtiaz** [comment]
Having found the [documentation](https://github.com/Jermolene/TiddlyWiki5/blob/929b0c98330ad25aa4a32cd201274a6e89cd8902/editions/tw5.com/tiddlers/customising/Customising%20search%20results.tid) for tiddlers tagged `$:/tags/SearchResults`, I am wondering if the above concerns are less of an issue if the intention is only to present alternative visualizations of the same search results

**Comment by BurningTreeC** [comment]
Hello @saqimtiaz , I've created a PR that addresses this issue (#4875)
