### ISSUE TITLE
[BUG] BibTeX import does not import names properly

### ISSUE THREAD

**Issue by dbobak** [Jermolene/TiddlyWiki5#4847]
**Describe the bug**
When importing BibTeX file with two-segment name in curly braces (which is correct format), the braces are not removed.

**To Reproduce**
1. Unpack and drag attached files to TiddlyWiki. The raw contents of the .bib file is also below.
2. Open importet tiddler
3. Check contents of the bibtex-author field. It is: 
`Adler, Daniel S. and {Belfer-Cohen}, Anna and {Bar-Yosef}, Ofer`
but it shold be
`Adler, Daniel S. and Belfer-Cohen, Anna and Bar-Yosef, Ofer`

**Expected behavior**

The parser should remove curly braces from the names.

**Screenshots**

![obraz](https://user-images.githubusercontent.com/6285546/92771284-08b85500-f39b-11ea-8623-e99f4a3586a3.png)

```
@incollection{AdlerEtAl2006Rock,
  title = {Between A Rock And A Hard Place: Neanderthal-Modern Human Interactions In The Southern Caucasus},
  booktitle = {When Neanderthals and Modern Humans Met},
  author = {Adler, Daniel S. and {Belfer-Cohen}, Anna and {Bar-Yosef}, Ofer},
  editor = {Conard, Nicholas J.},
  year = {2006},
  pages = {165--187},
  publisher = {Kerns Verlag},
  address = {Tübingen},
  abstract = {The southern Caucasus is a prime sellillg ill which fO model Neanderthal· modem human interactions. The region occupies an intermediate position between Europe and Asia thac is bounded to the west. north, and east by the Black Sea, tlte Caucasus Mountains, and the Caspian Sea, respectively. As such it represents a geographic cui de sac where individuals and Cllltures in contact have limited room to maneuver as they compete/or space and resources. In sllch sellings, where movements and opportunities are largely circumscribed by the surrounding landscape. it is lincommon /01' significall/ spatial or temporal overlap to occur among pop"lations compelillg to occupy the same niche, especially if one populatioll possesses or develops a major technological, biological, demographic, or social advantage. This chapter considers recellt archaeological dara ji-Olll Or/vale Klde, a late Middle-early Upper Palaeolithic rockshelter in western Georgia, which indicate that the Neanderthal occupation a/the region came to an abrupt end approximately 36 ka (uncal BP). The Upper Palaeolithic populations who replaced them can be distingUished by their flew technologies 0/ bOlle and stone but nol by their hunting behaviors, which are indistinguishable/rom those oj the Neanderthals. Ii is argued IIiat deveLopments in the social rather than the technological realm 0/ Upper Palaeolithic societies allowed these populations 10 rapidly replace Neanderthals in the Caucasus, wilh lillie if allY significanl temporal overlap or interaction.},
  isbn = {3-935751-03-6},
  series = {Tübingen Publications in Prehistory}
}

```

**Comment by Jermolene** [comment]
Thanks @dbobak. We use an third party library to do the BibTeX parsing: https://github.com/mikolalysenko/bibtex-parser

It hasn't been updated for 7 years (!). I did find a later fork at https://github.com/ORCID/bibtexParseJs but it does not appear to address the problem here. It looks like it's still worth upgrading so I'll go ahead and do that.

**Comment by dbobak** [comment]
@Jermolene, thank you! In the meantime, I've found workaround in Zotero (that's the soft I'm exporting from). With extension BetterBibTex one can customize the output code, also - remove the curly braces.

**Comment by Jermolene** [comment]
Great, thanks @dbobak
