### ISSUE TITLE
[BUG] dynannotate RSOD in 5.1.23 prerelease 

### ISSUE THREAD

**Issue by CodaCodr** [Jermolene/TiddlyWiki5#4858]
**Describe the bug**

**To Reproduce**
1. Use Firefox.
2. Bring up the dynannotate example "Multiple search result snippets"
3. Enter a value in the search prompt e.g. intricate 
4. dynannotate displays the results of the search
4. Hit Ctrl-F (find) type: intricate
5. See error

**Screenshots**

![image](https://user-images.githubusercontent.com/436812/93392718-e3ae6100-f836-11ea-99b8-edea3507cc59.png)

![image](https://user-images.githubusercontent.com/436812/93392631-c11c4800-f836-11ea-91ed-dc043431fd6a.png)

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser Firefox
 - Version 79

**Comment by Jermolene** [comment]
Hi @CodaCodr thanks, glad you're still finding Dynannotate interesting! I couldn't duplicate this on Firefox v81 on macOS; I wondered if you might have an extension interfering with things?

**Comment by CodaCodr** [comment]
That was the tiddlywiki pre-release site, Jeremy. :/

**Comment by saqimtiaz** [comment]
@CodaCodr I cannot replicate this either on Firefox 83 on Windows 10. Could you confirm if the error still occurs?

I think Jeremy was wondering if you might have browser addons that are interfering.

**Comment by CodaCodr** [comment]
Sorry sorry sorry. 

Yes, I did figure out eventually what Jem was refrring to. It was Tampermonkey tampering with things it shouldn't. 

I can confirm dynannotate is working extremely well

Closing.
