### ISSUE TITLE
[BUG] Missing attributes for external links created in Markdown tiddlers

### ISSUE THREAD

**Issue by gera2ld** [Jermolene/TiddlyWiki5#4861]
**Describe the bug**
External links created in Markdown tiddlers do not have some attributes as in normal tiddlers.
As a result, the links are not properly styled when appearance is changed.

**To Reproduce**
1. Go to <https://tiddlywiki.com/plugins/tiddlywiki/markdown/#HelloThere>
1. *Optionally inspect an external link, say `Remarkable`, we can find `<a href="https://github.com/jonschlinkert/remarkable" class="tc-tiddlylink-external" target="_blank" rel="noopener noreferrer">Remarkable</a>`.*
1. Click on `MarkdownExample` to open a Markdown tiddler.
1. *Optionally inspect an external link there, say `syntax page`, we can find `<a href="https://daringfireball.net/projects/markdown/syntax" target="_blank">syntax page</a>`.*
1. Now change appearance, open `$:/ControlPanel`, `Appearance` > `Palette`, pick `Gruvbox Dark`.
1. Look back to the links in the Markdown tiddler, they are hardly seen.

**Expected behavior**
Links created in Markdown tiddlers should have the same attributes as in normal tiddlers. The `class` attribute is essential since it affects appearances.

**Screenshots**
<img width="574" alt="Screen Shot 2020-09-22 at 12 31 37" src="https://user-images.githubusercontent.com/3139113/93844413-a5e68800-fccf-11ea-9802-fcc680404640.png">

**Desktop (please complete the following information):**
 - OS: macOS Catalina 10.15.6
 - Browser: Chrome
 - Version: 85.0.4183.102

**Comment by Jermolene** [comment]
Thanks @gera2ld
