### ISSUE TITLE
[Question] How does one remove shadow tiddlers?

### ISSUE THREAD

**Issue by vihu** [Jermolene/TiddlyWiki5#4871]
![image](https://user-images.githubusercontent.com/3199183/94772819-52c7a180-036f-11eb-997b-2a0b108f2a2f.png)

Pretty sure this is a basic question, I tried looking for some info but couldn't quite find it. Can someone please tell me how to remove the `$:/config?NewJournal/Tags` from displaying under my `Journal` section above?

**Comment by pmario** [comment]
This is an issue, that will be fixed with 5.1.23.
