### ISSUE TITLE
[BUG] Tiddler content not saved (but title is) with FF 81.0&81.0.1

### ISSUE THREAD

**Issue by journey-of-code** [Jermolene/TiddlyWiki5#4874]
**Describe the bug**
When saving a tiddler, the title is saved but not the content.

**To Reproduce**
1. Download an empty TiddlyWiki (v 5.1.22)
2. Open the TiddlyWiki
3. Create new Tiddler
4. Enter anything into title and content of the Tiddler
5. Press `Ctrl+Enter` or save the Tiddler manually
6. The **Tiddler appears with just it's title and the content is gone**

**Expected behavior**
The Tiddler is saved with title and content.

**Screenshots**
During editing:
![grafik](https://user-images.githubusercontent.com/1939047/94897910-df1db580-0490-11eb-9b6c-4d31887121a8.png)
After saving:
![grafik](https://user-images.githubusercontent.com/1939047/94897929-e80e8700-0490-11eb-81db-620c407281d6.png)

**Desktop (please complete the following information):**
 - OS: Windows_NT x64 10.0.18362
 - Browser: Firefox 81.0.1 (also tested with 81.0)
 - Version: TiddlyWiki 5.1.22

**Additional context**
During the tests a new tiddler showed `recursive transclusion...` in red in the content of a newly saved Tiddler. I think this was with Firefox 81.0. Afterwards it was the only Tiddler where something was in the content. Instead of the test text it contained `{{}}`. It was not repeatable. Didn't see any issues with Firefox versions before 81. Everything works with Chrome (which makes me sad as I want to have a choice).

**Comment by pmario** [comment]
If you use NoScript AddOn that's the problem. There will be a new version soon. See: https://github.com/hackademix/noscript/issues/156#issuecomment-702436427

**Comment by journey-of-code** [comment]
Thank you @pmario for the investigation. I indeed have NoScript in my Firefox. That explains why it's working in Chrome. I will disable my extensions next time before submitting a bug report. Closing as this is not caused by TiddyWiki.
