### ISSUE TITLE
can't visit tiddlywiki from remote browser

### ISSUE THREAD

**Issue by turtlekey** [Jermolene/TiddlyWiki5#4881]
**Describe the bug**
I have totally followed [the guide](https://tiddlywiki.com/#Installing%20TiddlyWiki%20on%20Node.js) to host tiddlywiki on my server, it's ok to visit it by `curl 127.0.0.1:8080` from localhost, but it fails when visiting it from remote browser by `http://***.**.**.**:8080`, what is the problem? What should I do? Or maybe there is a `configure file` for tiddlywiki? By the way, I have opened the port both on my server provider side and server side by `firewall-cmd`.

**To Reproduce**
completely following [the guide](https://tiddlywiki.com/#Installing%20TiddlyWiki%20on%20Node.js)

**Desktop (please complete the following information):**
 - OS: [windows]
 - Browser [chrome]
 - Version [85.0.4183.121]

**Comment by saqimtiaz** [comment]
What is the command you are using to start the tiddlywiki server?

**Comment by Jermolene** [comment]
To add that it sounds like the command used to start the wiki is listening on the host address 127.0.0.1, which only accepts connections from the same computer. To serve other computers on the same network you'll need to listen on the host address 0.0.0.0

https://tiddlywiki.com/#WebServer%20Parameter%3A%20host

**Comment by turtlekey** [comment]
Thanks for both of you, problem has been resovled by the command `tiddlywiki [wiki-dir] --listen host=0.0.0.0`

**Comment by saqimtiaz** [comment]
@turtlekey you are welcome. Could you please close this issue? Thank you.
