### ISSUE TITLE
[BUG] Spaces omitted in rendered markdown beneath links

### ISSUE THREAD

**Issue by fkohrt** [Jermolene/TiddlyWiki5#4891]
**Describe the bug**

When writing emphasized text beneath links in a markdown tiddler, the spaces between these parts are omitted.

**To Reproduce**

1. Go to the [markdown demo](https://tiddlywiki.com/plugins/tiddlywiki/markdown/)
2. Create a new markdown tiddler
3. Enter `__bold text__ [example.org](https://example.org/) _italic text_` as content
4. Save and see

**Expected behavior**

Spaces after __`bold text`__ and before _`italic text`_.

**Screenshots**

![markdown bug](https://user-images.githubusercontent.com/12914806/95846627-f50e5e80-0d4b-11eb-9480-f0bf549c4b4c.png)

**Desktop (please complete the following information):**
 - OS: Fedora 31
 - Browser: Firefox 81

**Additional context**

As can be verified in the [Remarkable demo](https://jonschlinkert.github.io/remarkable/demo/), this is a problem of TiddlyWiki's [markdown](https://github.com/Jermolene/TiddlyWiki5/tree/master/plugins/tiddlywiki/markdown) plugin.

**Comment by Jermolene** [comment]
Thanks @fkohrt I can duplicate the problem with v5.1.22 but not with the current v5.1.23-prerelease. I think @flibbles fixed this issue in #4684

**Comment by fkohrt** [comment]
Thanks and sorry for the unnecessary noise! I can confirm that this is fixed with #4684.
