### ISSUE TITLE
[BUG] Codemirror doesn't honor indentation of previous line

### ISSUE THREAD

**Issue by fkohrt** [Jermolene/TiddlyWiki5#4892]
**Describe the bug**

When hitting <kbd>Enter</kbd> on a line that is indented with two spaces, Codemirror indents the next line with a tab character.

This is particularly annoying when indenting markdown lists with spaces, because a mix of spaces and tab characters leads to undesired results.

**To Reproduce**

1. Go to TiddlyWiki's [Codemirror edition](https://tiddlywiki.com/plugins/tiddlywiki/codemirror/)
2. Create a new tiddler
3. Enter `  line 1` (two spaces followed by "line 1")
4. Hit <kbd>Enter</kbd>
5. Notice that the next line contains a tab character (instead of two spaces)

**Expected behavior**

I expect Codemirror to follow the indentation convention of the previous line.

**Desktop (please complete the following information):**
 - OS: Fedora 31
 - Browser: Firefox 81

**Additional context**

#3810 might be related. I filed this as a bug because writing lists in Markdown is currently hindered by Codemirror.

**Comment by Jermolene** [comment]
Hi @fkohrt ouch! Does the same problem occur with the Codemirror demos on their site? Or is it something about the bindings we're using in TW5?

**Comment by BurningTreeC** [comment]
@Jermolene @fkohrt - We have a config tiddler for this setting: $:/config/codemirror/indentWithTabs ... if set to false this problem shouldn't occur

**Comment by fkohrt** [comment]
The Codemirror demos always use spaces, even if the previous line was indented with tabs. So I guess there's no automatic detection but setting `$:/config/codemirror/indentWithTabs` to `false` works just fine!

**Comment by BurningTreeC** [comment]
@fkhort - the coming 5.1.23 release will have a controlpanel setting for the indentWithTabs config

**Comment by fkohrt** [comment]
It might be worthy of note that a custom tiddler `$:/config/codemirror/indentWithTabs` (one that isn't created by the UI) needs to have the field `type` set to `bool`.
