### ISSUE TITLE
[IDEA] Reduce initial dom node and initial html size to speed up page loading when deployed

### ISSUE THREAD

**Issue by linonetwo** [Jermolene/TiddlyWiki5#4893]
**Is your feature request related to a problem? Please describe.**

Google SEO console said my tw based blog have too many dom node, and is huge to load.

**Describe the solution you'd like**

Extract tiddlers into JS or other static file, so there won't be so much dom node in the HTML at the first load.

Extract all tiddler except front page tiddlers into a JSON file, and batch load it after page loaded, just like lazy load skinny tiddlers.

**Describe alternatives you've considered**
Thinking...Maybe put all tiddler data in the bottom of the HTML, inside a Script tag, and add "defer" to it, to allow lazy building of the dom node?

**Additional context**

**Comment by Jermolene** [comment]
Hi @linonetwo I've run into that warning as well. I suspect it is triggered more by the number of DOM nodes that are dynamically created than those that make up the tiddler store. It might be worth experimenting to see if Google gives the same warning for a site that consists of a TW file with the JS ripped out.

**Comment by linonetwo** [comment]
I've configed external javascript, so tiddlywiki5.js will be load separately:

And the dom size is still huge https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fonetwo.ren%2Fwiki%2F


![Screen Shot 2020-10-26 at 2 39 39 AM](https://user-images.githubusercontent.com/3746270/97115889-81e5ee80-1734-11eb-9f06-e5a41cd7b0b7.png)

**Comment by Jermolene** [comment]
Hi @linonetwo the question is whether the Google SEO tools measures the 2,150 DOM elements before or after TiddlyWiki's JavaScript executes to generate the user interface. I suspect that they measure the number of DOM elements after the "DOM content loaded" event, which would imply that the count includes the DOM elements that are created dynamically as part of the UI. That would suggest that there's no point in optimising the storage of the tiddler DIVs, but rather to pay attention to the templates used to render the UI.

But to be honest, 2,150 is not a lot of DOM elements, and I would suggest ignoring that metric. Far more significant is the nearly 6 seconds spent on script evaluation....

**Comment by linonetwo** [comment]
Seems this will be fixed by:  

https://github.com/Jermolene/TiddlyWiki5/pull/5708 Add support for JSON-formatted tiddler store, and make it the default
