### ISSUE TITLE
[BUG] Install on IIS causes 404 errors via AJAX

### ISSUE THREAD

**Issue by OblivionSY** [Jermolene/TiddlyWiki5#4898]
**Describe the bug**

Installing TiddlyWiki on Microsoft Internet Information Server <= based on this entry docs

followed these instructions, set file permissions to everyone, 
![image](https://user-images.githubusercontent.com/3511993/96584185-c6593080-12d5-11eb-944b-621c50de67d9.png)

Resolved the copy paste issue with MyApp, but  showing:

![image](https://user-images.githubusercontent.com/3511993/96584278-e983e000-12d5-11eb-8e40-714d496a3689.png)

more detail on one:

![image](https://user-images.githubusercontent.com/3511993/96584491-35cf2000-12d6-11eb-8b12-ba54df32d146.png)

with the undefined being in the url

![image](https://user-images.githubusercontent.com/3511993/96584537-48e1f000-12d6-11eb-8d86-0a53a68c38df.png)

Something out dated with the docs?

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome & Edge tested

**Comment by pmario** [comment]
Hi, You didn't provide any links to the docs in your post?!

**Comment by OblivionSY** [comment]
There wasn't a link in the browser, new to this platform. I found the permalink:
https://tiddlywiki.com/#Installing%20TiddlyWiki%20on%20Microsoft%20Internet%20Information%20Server

**Comment by pmario** [comment]
Hi, I did install the stuff and it works for me now. BUT ... I needed to adjust more things. 

```
PUT | http://localhost/MyApp/recipes/default/tiddlers/%24%3A%2FStoryList
```

I'm sure you need to have `default` as the recipe name. So There seems to be something wrong with your wiki setup. .. Are you sure, you defined the `tiddlywiki.info` and `config-tiddlyweb-host.tid` in the right directory?

My dir structure looks like this: 

```
x:\wikis\
  +- wiki
       +- tiddlers
           config-tiddlyweb-host.tid
       tiddlywiki.info
  +- node_modules
       +- tiddlywiki
package.json
web.config
```

I didn't install the `sax` node dependency. .. IMO it's not needed. 

I did have a problem with PUT and a 405 error, which meant PUT is not allowed. .. I needed to disable WebDav module, because it caused a side effect. 

my web.config looks like this: 

```
<?xml version="1.0" encoding="UTF-8"?>
<configuration>
    <system.webServer>
        <httpPlatform stdoutLogEnabled="true" stdoutLogFile=".\node.log" startupTimeLimit="20" processPath="C:\Program Files\nodejs\node.exe" arguments=".\node_modules\tiddlywiki\tiddlywiki.js ./wiki --listen port=PORT path-prefix=/MyApp">
            <environmentVariables>
                <environmentVariable name="PORT" value="%HTTP_PLATFORM_PORT%" />
                <environmentVariable name="NODE_ENV" value="Production" />
            </environmentVariables>            
        </httpPlatform>
        <handlers>
            <remove name="WebDAV" />
            <add name="httpplatformhandler" path="*" verb="*" modules="httpPlatformHandler" resourceType="Unspecified" requireAccess="Script" />
        </handlers>
    </system.webServer>
</configuration>
```

**Comment by pmario** [comment]
If you expose your wiki to the web, you should definitely go with HTTPS:// ...

**Comment by OblivionSY** [comment]
Hello 
Thanks for the response. I will certainly add https once I have it working.

This is my dir structure:
![image](https://user-images.githubusercontent.com/3511993/96695177-44264600-1381-11eb-8121-77781950a4dc.png)

I have the tiddlewiki.info file in the wiki folder
I have the config-tiddlyweb-host.tid file in the tiddlers folder

There is also a $__StoryList.tid file created which contains 
list: GettingStartedtitle: $:/StoryList (possible line ending issue as notepad does not show the carriage return, did try adding it no effect )

The contents of my host.tid file
```
title: $:/config/tiddlyweb/host
text: $protocol$//$host$/  
```  
I edited this ^ to remove the MyApp element as all the requests had /MyApp in them.

I have also set up the site as a dedicated IIS site, rather than a subdirectory.

There are no logs generated in the logs folder.

My web config with the added webDav removal is:

```
<?xml version="1.0" encoding="UTF-8"?>
<configuration>
    <system.webServer>
        <handlers>
		<remove name="WebDAV" />
            <add 
                name="httpplatformhandler"
                path="*"
                verb="*"
                modules="httpPlatformHandler"
                resourceType="Unspecified"
                requireAccess="Script" />
        </handlers>
        <httpPlatform 
           stdoutLogEnabled="true"
           stdoutLogFile=".\logs\node.log"
           startupTimeLimit="20"
           processPath="C:\Program Files\nodejs\node.exe"
           arguments=".\node_modules\tiddlywiki\tiddlywiki.js ./wiki --listen port=PORT path-prefix=/">
            <environmentVariables>
                <environmentVariable name="PORT" value="%HTTP_PLATFORM_PORT%" />
                <environmentVariable name="NODE_ENV" value="Production" />
            </environmentVariables>            
        </httpPlatform>
    </system.webServer>
</configuration>
```

In fact, I have solved the issue, but it probably should be fixed or documented in the app/docs. The path-prefix is documented to be
`path-prefix=/MyApp`

but I was not using a subfolder so I set it to / whereas it just needs to be path-prefix="> (ie nothing)

**Comment by pmario** [comment]
>In fact, I have solved the issue, but it probably should be fixed or documented in the app/docs. The path-prefix is documented to be

does this mean, it works for you now?

**Comment by OblivionSY** [comment]
Yes, it was the path-prefix that was causing the error. When set to / it went haywire 

I think it would be worth having a note in the docs that if you don't want a subDirectory (MyApp) then the path-prefix should be empty, (or maybe just removed if empty is the same as omitted?)

Now to add ssl and authentication...

**Comment by Jermolene** [comment]
Thanks @OblivionSY @pmario I've updated the docs here:

https://github.com/Jermolene/TiddlyWiki5/commit/9eec6ff915a5ad4b961be68867b68a1afad5196c

**Comment by pmario** [comment]
@OblivionSY ... You should close the issue, if you are OK with the solution.

**Comment by pmario** [comment]
... and thx for pointing me to the "httpplatformhandler", which allows me to autostart a node based wiki and use it with `wiki.lan` instead of a `localhost:<port>`

**Comment by OblivionSY** [comment]
Looks good to me
