### ISSUE TITLE
[BUG] Syncing plugin tiddlers on Node daemon results in RSOD

### ISSUE THREAD

**Issue by hoelzro** [Jermolene/TiddlyWiki5#4900]
**Describe the bug**
If you have two clients open to the same wiki and drag a plugin tiddler onto one to install it, the other client gets a RSOD with the following message:

```
SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data
```

**To Reproduce**
As of d25461282, steps to reproduce the behavior:

1. Create a fresh wiki with the server edition: `./tiddlywiki.js /tmp/test-wiki --init server`
2. Run the server: `./tiddlywiki.js /tmp/test-wiki --listen port=10001`
3. Open the server in two separate windows or tabs
4. Click and drag a plugin from another wiki into one of the windows/tabs
5. Confirm the import
6. Wait for the sync to catch up - an RSOD dialog is displayed

**Expected behavior**
No RSOD dialog should be displayed

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Browser: Firefox
 - Version: 81

**Additional context**
This seems to be happening because the plugin tiddler is lazily loaded into the second window/tab via `getSkinnyTiddlers`, and then `readPluginInfo` (called via the `change` event listener in `core/modules/startup/plugins.js`) tries parsing the `text` field of the skinny tiddler as JSON, which is `null` at the time.

**Comment by Jermolene** [comment]
Thanks @hoelzro I've committed a fix, let me know if it works for you.

**Comment by hoelzro** [comment]
@Jermolene That solved the issue, thanks!
