### ISSUE TITLE
[BUG] data:image/png;base64, before image url from the _canonical_uri

### ISSUE THREAD

**Issue by linonetwo** [Jermolene/TiddlyWiki5#4901]
**Describe the bug**

I'm using external image,  the tiddler looks like this:

<img width="1120" alt="截屏2020-10-23 上午10 51 52" src="https://user-images.githubusercontent.com/3746270/96950825-c3508100-151d-11eb-848e-6d02c239bcf1.png">

And using `[img[ ]]` syntax will result in 

<img width="107" alt="截屏2020-10-23 上午10 53 14" src="https://user-images.githubusercontent.com/3746270/96950913-f561e300-151d-11eb-857c-7288dffc1cf7.png">

An example is at https://onetwo.ren/wiki/#%E4%B8%8D%E5%90%8C%E5%B1%82%E6%AC%A1%E4%B8%8A%E7%9A%84%E9%A2%84%E6%B5%8B

I tried add an transclusion:

```
[img[Expanding Look Ahead Adder Equations.png]]

{{Expanding Look Ahead Adder Equations.png}}
```

And I found `[img[ ]]` syntax will add a `data:image/png;base64,` before the image url:

<img width="935" alt="截屏2020-10-23 上午10 51 13" src="https://user-images.githubusercontent.com/3746270/96950787-acaa2a00-151d-11eb-9ef9-af1ac1e573f8.png">

Which make the image url invalid.

**To Reproduce**
1. Go to https://onetwo.ren/wiki/#%E4%B8%8D%E5%90%8C%E5%B1%82%E6%AC%A1%E4%B8%8A%E7%9A%84%E9%A2%84%E6%B5%8B
2. Click on Edit
3. try add `{{Expanding Look Ahead Adder Equations.png}}`
4. see difference in resulted dom node with `[img[Expanding Look Ahead Adder Equations.png]]`

**Expected behavior**

If there is the `_canonical_uri`, don't add `data:image/png;base64,`

**Desktop (please complete the following information):**
TiddlyGit
Version v0.3.3.

Electron Version: 10.1.3

Node Version: 12.16.3

Chromium Version: 85.0.4183.121

TiddlyWiki Version: 5.1.23-prerelease.20201011-fix-file-info

**Additional context**

I'm using https://github.com/linonetwo/tiddlywiki-plugins/tree/master/plugins/linonetwo/github-external-image
To lazy load images in gh-pages deployed tw wiki.

---

I can see `options._canonical_uri` maybe undefiend here, but why?

https://github.com/Jermolene/TiddlyWiki5/blob/09112ed455e7c4be2e50e88c00f370d726d71f64/core/modules/parsers/imageparser.js#L21-L27

I don't know how I can debug this?

**Comment by Jermolene** [comment]
Hi @linonetwo I'm unable to duplicate this problem with the current prerelease:

1. Visit https://tiddlywiki.com/prerelease/
2. Verify that the tiddler `Blurry Lawn.jpg` is an image with a _canonical_uri field
3. Create a new tiddler and enter `[img[Blurry Lawn.jpg]]`
4. Verify that the image displays correctly

Perhaps some of the customisations in the wiki are affecting things?

**Comment by linonetwo** [comment]
I know why, actually I tried to fix https://github.com/Jermolene/TiddlyWiki5/issues/4642#issuecomment-640735480 and fill the text with uri, so it gets to this branch:

https://github.com/Jermolene/TiddlyWiki5/blob/4cdbe6540b4d037bb694605a1454502ee0112d46/core/modules/widgets/image.js#L63-L77

**Comment by linonetwo** [comment]
I will try to dig deeper. This is also a good chance to learn your code.
