### ISSUE TITLE
Uncaught TypeError: Cannot read property 'username' of null [BUG]

### ISSUE THREAD

**Issue by evanhackett** [Jermolene/TiddlyWiki5#4904]
When opening up tiddlywiki in the browser for the first time (newly installed server with no notes created), I am greeted with an error message:

```
Internal JavaScript Error
Well, this is embarrassing. It is recommended that you restart TiddlyWiki by refreshing your browser
Uncaught TypeError: Cannot read property 'username' of null
```

Here is a screenshot:

<img width="1048" alt="Screen Shot 2020-10-23 at 4 28 22 PM" src="https://user-images.githubusercontent.com/10438484/97061739-c9118b00-154c-11eb-93ca-b382a317397c.png">

All I did was install the node server on my VPS, run the init command to create the wiki directory, and then I ran:

```
tiddlywiki mynewwiki --listen
```

No errors are reported in the node console.

In the browser console there are additional errors:

```
Uncaught TypeError: Cannot read property 'username' of null
    at Object.callback ($:/plugins/tiddlywiki/tiddlyweb/tiddlywebadaptor.js:98)
    at XMLHttpRequest.request.onreadystatechange ($:/core/modules/utils/dom/http.js:53)

OPTIONS http://XXX/ 404 (Not Found)
HEAD http://XXX/ 404 (Not Found)

Uncaught TypeError: Cannot read property 'indexOf' of null
    at TiddlyWebAdaptor.parseEtag ($:/plugins/tiddlywiki/tiddlyweb/tiddlywebadaptor.js:330)
    at Object.callback ($:/plugins/tiddlywiki/tiddlyweb/tiddlywebadaptor.js:201)
    at XMLHttpRequest.request.onreadystatechange ($:/core/modules/utils/dom/http.js:53)
```

I replaced my servers IP address with "XXX" in the above error message.

Desktop:
 - OS: MacOS Catalina
 - Browser: Chrome and Brave
 - Version TiddlyWiki version 5.1.22

**Additional context**

Note that I am running the node server from a VPS, not on my local machine. I am using Caddy (similar to nginx) as a proxy server. Currently not using TLS, so it is just HTTP, not HTTPS for now.

I run tiddlywiki 5.1.22 locally with no problems, so I have a feeling I might have done something wrong in the setup on my VPS. Still, I can't figure out what I would have done wrong, so figured it is possible that this is a bug.

Thanks

**Comment by Jermolene** [comment]
Hi @evanhackett the error messages imply that the TiddlyWiki client code running in the browser is seeing corrupted responses from the server. So it looks as though the VPS might indeed be messing things up. In particular, it looks like the "Etag" header is being dropped, and that the `GET <host>/status` that happens during startup is not returning a valid JSON response.

**Comment by evanhackett** [comment]
Thanks Jeremy. I got things working by using NGINX instead of Caddy. Something about the reverse proxy was messing things up. All good now 👍
