### ISSUE TITLE
Support for translating remaining core text

### ISSUE THREAD

**Issue by Jermolene** [Jermolene/TiddlyWiki5#491]
There are still some language-specific text strings embedded in the core that are not translateable:
- JavaScript files:
  - $:/core/modules/widgets/navigator.js - confirmation messages for deleting and overwriting tiddlers
- Plugins:
  - $:/plugins/tiddlyweb/
  - $:/editions/clientserver/download-offline-button
  - $:/snippets/encryptionstatus
  - $:/plugins/tiddlywiki/tiddlyweb/ServerControlPanel
- Themes
  - ThemeTweaks
  - Palettes
- $:/TagManager - table headings

**Comment by pmario** [comment]
@Jermolene ... is this still an issue?

**Comment by Jermolene** [comment]
Hi @pmario plugins and themes are still not translated, but I think we can close this ticket because most of the info here is about the things we've already fixed
