### ISSUE TITLE
[BUG] Editor link dropdown is broken in pre-release.

### ISSUE THREAD

**Issue by saqimtiaz** [Jermolene/TiddlyWiki5#4910]
"https://tiddlywiki.com/prerelease/ -> New tiddler -> Create wikitext link (in toolbar) -> search for "HelloThere", it doesn't give me search results in either Chrome or Firefox." via [GG](https://groups.google.com/forum/?oldui=1#!topic/tiddlywiki/HU7n7NPl9wM)

Presumably this is due to #4875, as I did test the toolbar link dropdown after we introduced the keyboard-driven-macro, including extending it to be usable via a keyboard only workflow.

@BurningTreeC  I suspect configTiddler needs to be defined in [$:/core/ui/EditorToolbar/link-dropdown](https://github.com/Jermolene/TiddlyWiki5/blob/master/core/ui/EditorToolbar/link-dropdown.tid) before transcluding $:/core/ui/SearchResults:
https://github.com/Jermolene/TiddlyWiki5/pull/4875/files#diff-b4f2091e7fe5d0fa2d16dc46b6b88ea843a2702f573923959f2fedc6fbf6e7e0R11

Note that there is also an opportunity here to extend the link dropdown to be usable with an entirely keyboard based workflow.
I did prototype this a while back and the user experience is very good:
https://saqimtiaz.github.io/sq-tw/floats.html#%24%3A%2Fcore%2Fui%2FEditorToolbar%2Flink-dropdown:%5B%5BDraft%20of%20%27link-autocomplete%27%5D%5D%20%24%3A%2Fcore%2Fui%2FEditorToolbar%2Flink-dropdown

**Comment by BurningTreeC** [comment]
thanks @saqimtiaz , I'm investigating

**Comment by BurningTreeC** [comment]
@saqimtiaz @Jermolene - I've created PR #4913 which fixes this problem
