### ISSUE TITLE
[BUG] Save offline snapshot on pre-release is broken

### ISSUE THREAD

**Issue by saqimtiaz** [Jermolene/TiddlyWiki5#4924]
**Describe the bug**
Using the latest pre-release on node.js, the "save offline snapshot" feature results in a tiddlywiki.html file that does not load in the browser.

**To Reproduce**
1. with the latest pre-release code from github run `node tiddlywiki.js editions/server/ --listen`
2. In the browser, click on the syncer dropdown and choose "save snapshot for offline use".
3. Open the saved HTML file in the browser.
4. The TiddlyWiki does not load, giving a blank white screen and no error messages in the developer console.
5. Inspecting the HTML file in a text editor, it looks like a TW file at first glance.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: latest Chrome and Firefox

Can anyone else confirm that they are having the same issue? 

Stepping backwards at intervals through the git history has so far failed to identify a specific point or commit that causes the problem. I would like to determine whether this is an issue others are experiencing as well or somehow specific to my environment.

**Comment by Jermolene** [comment]
Ouch, thanks @saqimtiaz.

**Comment by saqimtiaz** [comment]
@Jermolene I've reproduced this issue on OSX.

It seems like boot.js is missing from the file generated.

I've stepped back through git history, checking out specific versions at intervals to test (with `git checkout commit-hash`).

At [this version](https://github.com/Jermolene/TiddlyWiki5/commit/422eb43e50bf659099c9e018d5fa3b2803379725) from Sept 1st it has the same problem. 
File size for offline snapshot: 2458kb

Then at [this version](https://github.com/Jermolene/TiddlyWiki5/commit/87dc67d0cd55454ff65a90ffa8839b4caef6e3b5) from Sept 8th it works. 
File size for offline snapshot: 2531kb

At the following [version](https://github.com/Jermolene/TiddlyWiki5/commit/af82a95a299dfb216577006af0ca96dda0e991b0) from Sept 14th we have the same problem. 
File size for offline snapshot: 2458kb.

I don't see anything in the space of those commits that would be an issue. So it seems the issue is elsewhere and surfacing sporadically.

**Comment by saqimtiaz** [comment]
From the source of the non-functional snapshot file:


```
<!--~~ Boot kernel prologue ~~-->
--
  | <div id="bootKernelPrefix" style="display:none;">
  | <script data-tiddler-revision="1" data-tiddler-bag="default" type="text/javascript"></script>
  | </div>
  | <!--~~ Boot kernel ~~-->
  | <div id="bootKernel" style="display:none;">
  | <script data-tiddler-revision="1" data-tiddler-bag="default" type="text/javascript"></script>
  | </div>
  | <!--~~ Raw markup for the bottom of the body section ~~-->

```

**Comment by Jermolene** [comment]
Thanks @saqimtiaz I'm away from my desk at the moment, and so this may not be useful, but I have lingering suspicions about the changes in a0d9559bf844648bc39815dd389cc331fd63c6f7d0f29bc38d4a5a2b6e395916...

**Comment by saqimtiaz** [comment]
@Jermolene > a0d9559bf844648bc39815dd389cc331fd63c6f7d0f29bc38d4a5a2b6e395916

I wasn't able to correlate that to a commit. No rush, but if you get the opportunity to point me at the right commit, I can take another look after lunch. 

Seems boot.js and bootprefix.js are missing in the node wiki running in the browser, and therefore don't make it to the snapshot.

For the node wiki in the browser, the dev console shows:
```
 syncer-browser-tiddlyweb: Deleting tiddler missing from server: $:/library/sjcl.js 
$:/core/modules/utils/logger.js:52  syncer-browser-tiddlyweb: Deleting tiddler missing from server: $:/boot/bootprefix.js 
$:/core/modules/utils/logger.js:52  syncer-browser-tiddlyweb: Deleting tiddler missing from server: $:/boot/boot.js 
```

**Comment by Jermolene** [comment]
Thanks @saqimtiaz that makes more sense: it's the recent changes to syncing system tiddlers that's the problem. We've excluded the boot files from the tiddlers returned by the server, so they are being deleted in the browser at startup, but it's not a problem in the browser because those tiddlers have already been executed.

**Comment by saqimtiaz** [comment]
@Jermolene yes it makes sense now. I'll give this a rest until you get the chance to look at this at your own convenience. The syncing of system tiddlers needs some rethinking so we don't need to keep making case by case exceptions.

**Comment by saqimtiaz** [comment]
This is probably the same issue as #4829.
Apologies, that ticket skipped my mind when I posted this morning.

**Comment by joshuafontany** [comment]
No prob, as long as we confirm the same root cause we can close all linked bugs. Thanks for researching this, work has gotten super busy recently.

Mahalo (thanks),
Joshua F

**Comment by saqimtiaz** [comment]
Probably not the most elegant solution but adding the following to $:/config/SyncFilter seems to resolve the issue:
`-[[$:/library/sjcl.js]] -[prefix[$:/boot/]]`

@joshuafontany could you confirm whether this helps in your case?
Could you also check the developer console right after the node wiki loads to see if there are any messages about tiddler deletion like:
`$:/core/modules/utils/logger.js:52  syncer-browser-tiddlyweb: Deleting tiddler missing from server: $:/boot/bootprefix.js `

**Comment by joshuafontany** [comment]
I can confirm that I saw the `$:/core/modules/utils/logger.js:52 syncer-browser-tiddlyweb: Deleting tiddler missing from server: $:/boot/bootprefix.js`, and that using the specified  $:/config/SyncFilter _seems_ to let me "Save a Snapshot" that then loads correctly.

I'm also reading through core tiddlers for the fix-fileInfo PR and thinking about the $:/StoryList issue... They all seem related.

**Comment by saqimtiaz** [comment]
You're absolutely right @joshuafontany both issues have the same root.

The underlying problem here is that the syncer will delete from the client any Tiddler that matches it's syncFilter, and does not exist on the server.

There is no mechanism in place to say: sync this this tiddler to the server, but not from the server. Which is what we need for a simplistic solution to the story list problem for now.
