### ISSUE TITLE
[BUG] Story river gets lost if anchor `#StoryList` is appended to URL

### ISSUE THREAD

**Issue by FlashSystems** [Jermolene/TiddlyWiki5#4972]
**Describe the bug**
If you add the anchor `#StoryList` to a TiddlyWiki URL and refresh the page the whole story river will be deleted. This happens on Node.js and on a local TiddlyWiki file.

**To Reproduce**
1. Open a saved TiddlyWiki file or navigate to a TiddlyWiki Node.js instance.
2. Add `#StoryList` to the URL and press enter. An empty Tiddler named "StoryList" will appear at the start of the story river. Closing this tiddler or leaving it open does not make a difference.
3. Now refresh the page.
4. The whole story river is gone.

I somehow managed to get the `#StoryRiver` in my URL by accident (maybe some unintentional Drag&Drop). I didn't think about it and closed the undesired tiddler. After refreshing the page many hours later, by changing back to the TiddlyWiki tab, my story river was gone. 😢

**Expected behavior**
The story river should not get lost by this series of actions.

**Desktop**
 - OS: Windows 10 and Linux
 - Browser: Firefox (Win, Linux) and Edge Chromium (Win)

**Smartphone**
not tested

**Additional context**
Tested with TiddlyWiki 5.1.22

**Comment by pmario** [comment]
With TW5.1.23 the $:/StoryList tiddler will not be synced or saved anymore. .. We will need a new mechanism to store and reload an existing story river. 

So if you used `[list[$:/StoryList]]` in your `$:/DefaultTiddlers` .. This setting will _not_ work anymore with 5.1.23

**Comment by FlashSystems** [comment]
I've red bug #4868 and understand the problem. Removing the synchronization of the story river will break my workflow. (But this is my personal problem ☹️)
But one quest remains for me: Is saving the story river also disabled for a local TiddlyWiki and the download saver? I think the diskussion in #4868 is not relevant for this use case because there is always a single user when using a local file.  If saving the StoryList is disabled for all all use cases, this bug is truly irrelevant and I'll close it.

**Comment by pmario** [comment]
You shouldn't close it. It is relevant for those, who also need the possibility to store and set a saved state at startup. ... Including me!

**Comment by saqimtiaz** [comment]
@FlashSystems the discussion in #4868 is only for the node.js version, the story list should still be saved properly in single file.

**Comment by saqimtiaz** [comment]
@pmario @FlashSystems with the recent changes to the syncing of system tiddlers, saving the $:/StoryList and restoring it again works once more.

I have not been able to recreate the problem from the original post in the current pre-release.

**Comment by Jermolene** [comment]
Thanks @saqimtiaz
