### ISSUE TITLE
[BUG] - Chrome sets ugly outline on inputs

### ISSUE THREAD

**Issue by BurningTreeC** [Jermolene/TiddlyWiki5#4984]
**Describe the bug**
Google Chrome sets an (opinionated) ugly outline on inputs

**To Reproduce**
1. Go to 'https://tiddlywiki.com/prerelease' using Chrome Web-browser
2. Click on 'the sidebar search input field'
4. See the ugly outline

**Expected behavior**
The border of the input field changes its color, not an ugly inset-style outline

**Desktop (please complete the following information):**
 - OS: [Linux]
 - Browser [Chrome]
 - Version [86.0.4240.183]

**Possible solution**
- set `outline:none` on inputs
- set `input[type="search"]:focus { border-color: <<colour primary>>; }`

**Comment by Jermolene** [comment]
Hi @BurningTreeC I appreciate the problem (I use Chrome Canary as primary development browser). I had a look and it seems that the problem might actually lie somewhere else: commenting out the background color setting [here](https://github.com/Jermolene/TiddlyWiki5/blob/master/themes/tiddlywiki/vanilla/base.tid#L193) makes things look more as expected:

```

textarea,
input[type=text],
input[type=search],
input[type=""],
input:not([type]) {
	color: <<colour foreground>>;
	background: <<colour background>>;
}
```

Before:

<img width="801" alt="image" src="https://user-images.githubusercontent.com/174761/98387968-034d5300-204a-11eb-97b6-b31f50af77d9.png">

After:

<img width="778" alt="image" src="https://user-images.githubusercontent.com/174761/98388014-1102d880-204a-11eb-8172-dad925ee7d78.png">

**Comment by Jermolene** [comment]
Apologies @BurningTreeC I clicked the button too early. I meant to add that we clearly can't remove that background colour without breaking existing palettes/themes that rely on changing the background colour of inputs. But perhaps it helps to shed some light on why things are being messed up.

**Comment by BurningTreeC** [comment]
Thanks @Jermolene - it makes things a bit better, but it still leaves an ugly inset-outline in the sidebar search input:

![Peek 2020-11-06 17-12](https://user-images.githubusercontent.com/9407182/98388682-5aa3f100-2053-11eb-9b5a-ea2ffabc9958.gif)

**Comment by Jermolene** [comment]
> Thanks @Jermolene - it makes things a bit better, but it still leaves an ugly inset-outline in the sidebar search input:

I think that's caused by [this](https://github.com/Jermolene/TiddlyWiki5/blob/master/themes/tiddlywiki/vanilla/reset.tid#L295):

```
[type="search"] {
  -webkit-appearance: textfield; /* 1 */
  outline-offset: -2px; /* 2 */
}
```

We already unset a number of settings from the CSS reset, so we could just add this to the list.

**Comment by BurningTreeC** [comment]
@Jermolene - ah! that makes sense! shouldn't we remove it?

**Comment by BurningTreeC** [comment]
Thanks @Jermolene , my issue is resolved in the current prerelease
