### ISSUE TITLE
[IDEA] - Update font-families to use system-font and modern fallbacks

### ISSUE THREAD

**Issue by BurningTreeC** [Jermolene/TiddlyWiki5#4988]
**Is your feature request related to a problem? Please describe.**
We should update the currently used font-families in `$:/themes/tiddlywiki/vanilla/settings/fontfamily` like [here](https://github.com/sindresorhus/modern-normalize/blob/692ad6ae5d34df53f2588cfe54cc804e5263d5ac/modern-normalize.css#L54) ... I've configured my Firefox so that webpages cannot use their fonts, but on Chrome there's no such setting and fonts look ugly.

**Describe the solution you'd like**
`system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol"` as new default font-families

**Comment by BurningTreeC** [comment]
A screenshot to demonstrate the ugly fonts using Chrome on a Linux Desktop:

![Bildschirmfoto vom 2020-11-07 08-35-20](https://user-images.githubusercontent.com/9407182/98435577-64216d80-20d4-11eb-9e2d-9db7ab7b20c9.png)

**Comment by Jermolene** [comment]
Hi @BurningTreeC good idea. I think we might as well switch to https://github.com/sindresorhus/modern-normalize in any event, the old normalize.css hasn't been updated in many years. I've tried it and it seems to work so I'll commit it shortly.

**Comment by BurningTreeC** [comment]
Thanks @Jermolene :)

**Comment by ValdikSS** [comment]
Using "system-ui" made _my_ fonts (Firefox, Fedora Linux 33) look ugly. Fedora's fontconfig defaults "system-ui" to Cantarell, which is too lean.
As I'm using KDE, there doesn't seem any way to adjust "system-ui" font for Firefox — it seem to support this function only with Gnome desktop. I had to change fontconfig configuration manually.

Is it possible to exclude "system-ui" from the font line?

**Comment by ValdikSS** [comment]
StackExchange [changed the fonts](https://meta.stackexchange.com/questions/364048/we-are-switching-to-system-fonts-on-may-10-2021) a month ago, and they ditched out "system-ui" for now. Here are the quotes:

>The reason you see discrepancy between Firefox and Chrome is because Firefox [doesn't support](https://developer.mozilla.org/en-US/docs/Web/CSS/font-family#browser_compatibility) system-ui keyword at all. It simply ignores it.
>
>Also, the poor result in non-English Windows is the exactly reason why GitHub, Twitter, etc. have tried and then immediately reverted their change of font stack of including system-ui.

https://bugzilla.mozilla.org/show_bug.cgi?id=1226042
Opened 6 years ago
>add support for the new 'system-ui' generic font family

Comment 21, 9 days ago
>Is there any reason to delay this feature? The only reason I cannot use system-ui is because of Firefox, and for seemingly no reason Firefox doesn't support this feature whereas all other browers support it.

**Comment by pmario** [comment]
Go to [ControlPanel](https://tiddlywiki.com/#%24%3A%2FControlPanel) **: Appearance : Theme Tweaks** .. .There you can remove or add fonts as you like.  It's the 4th parameter.

**Comment by ValdikSS** [comment]
@pmario, I know, I did that already after looking at not great fonts after TiddlyWiki update. I'm writing here to inform about kind of regression due to incomplete support of "system-ui" on all platforms. This may be not the best commit worth reverting.

**Comment by pmario** [comment]
@Jermolene 

So your suggestion is: **remove -system-ui** from https://github.com/Jermolene/TiddlyWiki5/commit/93e7380188dae8c86819bff3bfe12c3700a58fcd -- right?

**Comment by ValdikSS** [comment]
Yes.
