### ISSUE TITLE
[BUG] Pressing Enter in Advanced Search Filter Tab Creates Missing Tiddler

### ISSUE THREAD

**Issue by kookma** [Jermolene/TiddlyWiki5#4998]
**Describe the bug**
The new $:/AdvancedSearch tweaks creates a missing tiddler

**To Reproduce**
1. Go to https://tiddlywiki.com/prerelease/
2. Open $:/AdvancedSearch
3. Open the Filter Tab
3. Enter the [tag[book]tag[AI]] in search input
4. Press Enter key
4. See Tiddlywiki creates a missing tiddler _[tag[book]tag[AI]]_ and navigate to it

_It seems this is the case for all search boxes in $:/AdvancedSearch_

**Screenshots**
![image](https://user-images.githubusercontent.com/830394/98459734-cb155400-21b2-11eb-8d88-b8e7bbf5ed89.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome 86
 - Version TW 5.1.23 prerelease

**Comment by BurningTreeC** [comment]
Hi @kookma, I would say that this is by Design. Pressing <kbd>enter</kbd> in such an input field should navigate to whatever is stored in the input field. I think we should let more users test this and see if they find this behavior convenient or buggy

**Comment by Jermolene** [comment]
Hi @kookma @BurningTreeC funnily enough, I've recently talked to users who were confused that a new tiddler was apparently created when they pressed "enter" with text in the search input. Part of the problem is perhaps that the new keyboard handling makes it more likely that "enter" is pressed accidentally.

So, I'd actually favour hiding this behaviour behind a setting, so that by default pressing "enter" in a search field is ignored unless there is a highlighted search result.

**Comment by BurningTreeC** [comment]
Hi @Jermolene, that is doable. I'll create a PR for that

**Comment by Jermolene** [comment]
Thanks @BurningTreeC

**Comment by BurningTreeC** [comment]
I just don't want to be the one that creates PR #5000 :grin:

**Comment by BurningTreeC** [comment]
@Jermolene , how should that hidden-setting-tiddler be called?

**Comment by Jermolene** [comment]
Thanks @BurningTreeC

**Comment by Jermolene** [comment]
> @Jermolene , how should that hidden-setting-tiddler be called?

Maybe $:/config/Search/NavigateOnEnter/enable set to "yes" or "no"?

**Comment by BurningTreeC** [comment]
@Jermolene , just to be clear: it's enough if it doesn't navigate on enter if the tiddler is missing, right? In each other cases the tiddler should not be missing (if selected from the dropdown / list) ... and the same for the actions on <kbd>ctrl-Enter</kbd>

**Comment by Jermolene** [comment]
That sounds correct @BurningTreeC

**Comment by kookma** [comment]
> Hi @kookma, I would say that this is by Design. Pressing enter in such an input field should navigate to whatever is stored in the input field. I think we should let more users test this and see if they find this behavior convenient or buggy

Hi @BurningTreeC, Well that is correct, but creating a new tiddler like [tag[book]tag[AI]] is not correct!
