### ISSUE TITLE
[BUG] Modal Windows and Keyboard Shortcuts:

### ISSUE THREAD

**Issue by kookma** [Jermolene/TiddlyWiki5#5006]
**Describe the bug**
Referring to https://github.com/Jermolene/TiddlyWiki5/pull/5003 when using keyboard shortcuts one can create a modal window repeatedly (one over the other) by pressing the shortcut key again and again. 

**Expected behavior**
When a certain modal window is opened by shortcut keys, pressing the same shortcut keys over the opened modal window should not open another copy of that model window e.g. prevent duplicated/redundant modal window!

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome 86
 - Version TW 5.1.23pre

**Comment by saqimtiaz** [comment]
@kookma the way to avoid this problem is something we have discussed here:
https://github.com/Jermolene/TiddlyWiki5/issues/4512

Note that its a feature that you can open the same modal twice, as you might want to pass it different variables. I actually do this in one of my applications.

**Comment by pmario** [comment]
I personally think, the core UI shouldn't use modals. They are destructing and against the tiddler based mechanism. It's easier and more convenient to open a tiddler. .. done.

**Comment by kookma** [comment]
@saqimtiaz I forgot your solution here https://github.com/Jermolene/TiddlyWiki5/issues/4512
What do you think if the default behavior of a modal+shortcut is to open one modal window?

@BurningTreeC  What do you think for https://github.com/Jermolene/TiddlyWiki5/pull/5003?

**Comment by BurningTreeC** [comment]
@kookma , I think opening more of the same modal is just fine, it doesn't bother me personally

**Comment by saqimtiaz** [comment]
@kookma I think let's allow the layout switching to have a stable implementation before we consider addressing this.

Do you feel like we can close this issue though? If so, please do close it.

**Comment by kookma** [comment]
Thank you all!

**Comment by Jermolene** [comment]
> I personally think, the core UI shouldn't use modals. They are destructing and against the tiddler based mechanism. It's easier and more convenient to open a tiddler. .. done. 

@pmario I would generally agree, but modals do have some properties that are hard to replicate in any other way. The fact that they are not part of the page template (and hence outside the main "page container" DOM element) turns out to be quite useful in cases such as this.
