### ISSUE TITLE
Moving some styles from the menubar plugin to vanilla/base

### ISSUE THREAD

**Issue by BurningTreeC** [Jermolene/TiddlyWiki5#5018]
https://github.com/Jermolene/TiddlyWiki5/blob/59c6f4447e25ef73c0678ee3cf8413cf1357bcd2/plugins/tiddlywiki/menubar/styles.tid#L220

We should add these lines of CSS to vanilla/base

**Comment by Jermolene** [comment]
That makes sense, thanks @BurningTreeC

**Comment by BurningTreeC** [comment]
Ok I'll create the PR
