### ISSUE TITLE
have to also mention removing  -[prefix[$:/StoryList]] from $:/config/SyncFilter

### ISSUE THREAD

**Issue by rubaboo** [Jermolene/TiddlyWiki5#5022]
https://github.com/Jermolene/TiddlyWiki5/blob/929b0c98330ad25aa4a32cd201274a6e89cd8902/editions/tw5.com/tiddlers/howtos/Preserving%20open%20tiddlers%20at%20startup.tid#L9

**Comment by saqimtiaz** [comment]
@rubaboo the syncFilter for 5.1.23 has been modified so this change will no longer be necessary. Could you please close this issue?
