### ISSUE TITLE
[BUG] Sidebar search popup is in inconsistent state after clicking elsewhere on the page

### ISSUE THREAD

**Issue by Jermolene** [Jermolene/TiddlyWiki5#5025]
The popup mechanism gets into an inconsistent state after the sidebar search input loses focus

1. Go to https://tiddlywiki.com/
2. Open the JavaScript console 
3. Enter `$tw.popup.popups.length`
4. The result will be zero, indicating that no popups are currently displayed
5. Click on the main page background
6. Enter `$tw.popup.popups.length` in the JS console
7. The result will be 1, even though no popups are displayed

@BurningTreeC please could you have a look at this?

**Comment by BurningTreeC** [comment]
Yes I can have a look @Jermolene

**Comment by BurningTreeC** [comment]
@Jermolene I cannot reproduce this on FireFox (Linux). I have a popup when loading the page which is the search-dropdown-popup and no popups after clicking on the main page background

**Comment by Jermolene** [comment]
Thanks @BurningTreeC. I was using Chrome Canary, so perhaps it's just a quirk there. I'll investigate other browsers.

**Comment by BurningTreeC** [comment]
@Jermolene , I tried this on FireFox, TiddlyDesktop, Chrome and Chrome Canary and cannot reproduce the problem.

**Comment by pmario** [comment]
@Jermolene .. I could not reproduce the behaviour using FF and Edge on Windows. Is this still an issue for you?

**Comment by Jermolene** [comment]
Thank you @pmario
