### ISSUE TITLE
[BUG] Type application/x-tiddler forced while importing .tid files from Windows Explorer

### ISSUE THREAD

**Issue by mauloop** [Jermolene/TiddlyWiki5#5028]
**Describe the bug**

I imported some .tid files, which did not  have the type field set, in my wiki, by dragging the files from the Windows explorer into the TW5 browser view.

After the import has completed the type was set to "application/x-tiddler". 

**To Reproduce**

- Create a simple tiddler like this (or use any tiddler from any wiki, it does not make difference)

```
title: Example of standard tiddler

Any text
```

1. Export the tiddler as `.tid` file
2. Navigate to https://tiddlywiki.com/
3. Import the tiddler in Tiddlywiki site dragging the .tid file icon into the browser
4. Look at the imported tiddler type field: it is now set to "`application/x-tiddler`"

**Expected behavior**
"Type" field still not set. I expect the same behaviour as if I would drag the tiddler link from a wiki to another one.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: verified with Chrome 84.0.4147.135 and Firefox  82.0.3 
 - Tiddliwiki

TW version: verified with: 
- TW 5.1.21 + TiddlyServer 2.1.5 + Node.js 12.13.0
- TW 5.1.19 (single file)
- TW 5.1.22 on the official TW website

**Comment by saqimtiaz** [comment]
It seems this is an intentional configuration, so may be hard to change now in light of backwards compatibility:
https://github.com/Jermolene/TiddlyWiki5/blob/ecb3c86e7bff8205043f397848355d5cefe7f470/boot/boot.js#L2261

It is intended to extend the import UI post 5.1.23 to allow choosing the deserializer to be used so that may be one way to address this.

**Comment by Jermolene** [comment]
Thanks @mauloop I can't replicate this on Chrome on the Mac; .tid files import as expected. Is this specific to Window Explorer?

**Comment by mauloop** [comment]
Hi, Jermolene.

I think it is not a Windows specific behaviour. I can replicate it on Archlinux + XFCE 4.14 + Thunar File Manager 1.8.15 + Firefox 78.0.1 + TW 5.1.22 (Tiddliwiki web site)

**Comment by mauloop** [comment]
I forgot to tell that this is not a critical issue for me. I didn't noticed it as soon as it happened, and everything worked fine, despite the type of imported tiddlers. I use TW5 at work to save bookmarks and notes about ongoing tasks. I converted some collegues to TW5 and we use to exchange notes by email attaching the exported tid files. None of the notes has been corrupted or lost due to this behaviour.

I posted [this on the forum](https://groups.google.com/g/tiddlywiki/c/8OZoLeZ6rxM) prior to open this issue and then realized that opening the issues could could help the team that actively contributes to TW5 development. But I don't expect that you waste your time for what looks like a very low priority issue.

In the past i made some experiments with Tiddlyweb, and I remember that in that case "application/x-tiddler" type broke something, but it was two or three years ago, now I don't remember exactly what was the matter.

Honestly I cannot tell what is the use for "application/x-tiddler" type. If someone can explain (here or on the forum) I am interested to learn.

Thanks, )+(au

**Comment by saqimtiaz** [comment]
@mauloop I cannot replicate this on Chrome or Firefox and Windows 10 either. The tiddler type is set to `text/vnd.tiddlywiki` after import.

Could you perhaps share the contents of a `.tid` file that is triggering this behaviour?

**Comment by mauloop** [comment]
@saqimtiaz You can find an example tiddler and some screenshot in the attached zip file: [tw5-issue-5028.zip](https://github.com/Jermolene/TiddlyWiki5/files/5540573/tw5-issue-5028.zip)

I created the tiddler in the TW5 web site with Chrome (01-tiddler-created.png).
Then I imported the tiddler into the same wiki (after having it reloaded, in order to wipe any changes) three times, with Chrome, then Firefox and finally Edge. In Chrome I tested the import dragging the .tid file icon from the Windows Explorer as well by the import tool in the TW5tools sidebar. The result was the same.

As from my previous reply, the same happened on Linux in a completely different environment.

**Comment by Jermolene** [comment]
Thanks @mauloop, and apologies. I was testing with .tid files that included `type` field, while your example does not. It turns out that any tiddler without a `type` field will have its type set to `application/x-tiddler` on import. It appears that this bug has been present since 2013 (!); I'll investigate further.

**Comment by saqimtiaz** [comment]
@Jermolene I can confirm that my test was also with a .tid file with the type field set.

**Comment by Jermolene** [comment]
I think this is fixed. I've checked that it doesn't impact importing other file types, but would appreciate a second set of eyes.

**Comment by saqimtiaz** [comment]
@Jermolene I've had a careful look through the code and it looks good to me. None of the downstream code in the import process relies on the `type` attribute in `tiddlerFields`.

**Comment by Jermolene** [comment]
Thanks @saqimtiaz

**Comment by mauloop** [comment]
Thanks to both. I appreciated very much your readiness, even id if the issue was not critical.

Let me make a little comment. Since no type defined is intended by the wiki as "text/vnd.tiddlywiki" and there is nothing that set a default type for newly created tiddlers, it leads to have a lot of tiddlers with undefined type without the users beeing aware of this. At tiddlywiki.com 173 of 1263 regular tiddlers fall in this case. 

As I said it is not critical. The fact that it works this way since 2013 without no one knowing demonstrates it. Any way could be the case of having a default type forced or at least some kind of warning.

I remember at least one use case (Tiddlyweb) where having unwanted "application/x-tiddler" tiddlers was a problem and made me spend lot of hours troubleshooting.

Thanks again for your work with Tiddlywiki. Best regards,
)+(au

**Comment by Jermolene** [comment]
Hi @mauloop indeed, I think it is important to maintain support with tiddlers without a type field for brevity.
