### ISSUE TITLE
[BUG] The $:/AdvancedSearch tiddler and horizontal overflow

### ISSUE THREAD

**Issue by kookma** [Jermolene/TiddlyWiki5#5030]
**Describe the bug**
When search tiddlers with very long title, the result text crosses the $:/AdvancedSearch boundaries and overflows in x direction.

**To Reproduce**
1. Go to 'https://tiddlywiki.com/prerelease
2. From $:/ControlPanel, Appearance, Theme Tweaks, change Sidebar layout to Fixed Story, Fluid Sidebar
3. Open $:/AdvancedSearch and goto Filter tab
4. Search for `[all[shadows+tiddlers]get[title]minlength[80]]`
5. See how the results cross the right boundery and overflows outside $:/AdvancedSearch tiddler.

**Expected behavior**
Wrap the result text or use the overflow-x!

**Screenshots**
![image](https://user-images.githubusercontent.com/830394/99086014-31004200-25de-11eb-9928-e6a11f04be8d.png)

**Desktop (please complete the following information):**
 - OS:  Windows 10
 - Browser : Chrome 86
 - Version 5.1.23pre

**Comment by Jermolene** [comment]
Thanks @kookma. There is a `white-space: nowrap;` on the class used to display lists. It is intended for use in the sidebar, I'll post a fix narrowing its scope.
