### ISSUE TITLE
[IDEA] Request for configurable setting for autofill tag pill in TW 5.1.23

### ISSUE THREAD

**Issue by kookma** [Jermolene/TiddlyWiki5#5038]
**Describe the bug**
A feature has recently added to TW 5.1.23 lets you to focus tag input after adding a tag and repeat the partial word you used in previous input. While in some cases this may be useful but in other cases it is annoying and needs more clicking/pressing keys to cancel or remove the partial word you entered in tag input. See https://github.com/Jermolene/TiddlyWiki5/pull/5032

**To Reproduce**
1. Go to https://tiddlywiki.com/prerelease/
2. Add new tiddler
3. In the tag input type Hel
4. Select HelloThere by mouse or keyboard (no difference)
5. See the Hel in next tag input under focus
6. You have finished by Hel is there
6.1. If you click save, the Hel is added as new tag
6.2 If you not you have to
      a. click Esc, then click save or ctrl+Enter  (mouse+keyboard), OR
      b. click clear tag input button and then save (by mouse or keyboard)
So you have one extra clicking/pressing key!

This auto fill of next tag input is not useful always so, I am in favor of removing it or adding proper setting lets user choose proper behavior.

There is also a bug I reported in

**Screenshots**
![image](https://user-images.githubusercontent.com/830394/99177822-4ed6bf80-2722-11eb-90c4-753c2916533d.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome 86
 - Version TW 5.1.23

**Comment by BurningTreeC** [comment]
@kookma thanks for your report. I think I'll revert this behavior to how it was before
