### ISSUE TITLE
[BUG]  Autofill tag pill in TW 5.1.23 keeps partial word input if the tiddler is deleted

### ISSUE THREAD

**Issue by kookma** [Jermolene/TiddlyWiki5#5039]
**Describe the bug**
The autofill tag input keeps the partial word already used when you create a new tiddler, if you deleted the previous tiddler you used partial word in tag input. See https://github.com/Jermolene/TiddlyWiki5/pull/5032

**To Reproduce**
1. Go to https://tiddlywiki.com/prerelease/
2. Create a new tiddler
3. In tag input type Hell
4. Add the HelloThere from tag drop down
5. Delete the tiddler
6. Add new tiddler
7. In new tiddler you see Hell already in tag input

**Expected behavior**
In new tiddler created the tag input shall be empty

**Screenshots**
![077_%pn](https://user-images.githubusercontent.com/830394/99177923-62cef100-2723-11eb-8c9a-426652faf6cd.gif)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome 86
 - Version TW 5.1.23

**Comment by BurningTreeC** [comment]
@kookma thanks for your report. I think I'll change this behavior to how it was before

**Comment by BurningTreeC** [comment]
@kookma - I misunderstood the OP. I'll investigate how to fix this issue. Thanks for reporting!

**Comment by BurningTreeC** [comment]
@kookma - this issue is the same for the fieldname input and the fieldvalue input. This behavior was also in 5.1.22 ... 

The fix would be a bit more complicated. I'd like to hear others if it's worth the effort

**Comment by kookma** [comment]
@BurningTreeC  Yes, it seems this is the same behavior for Fields. Okay lets see what other users say!

**Comment by Jermolene** [comment]
Hi @BurningTreeC I do think the more expected behaviour would be to clear the typed input when clicking an entry in the dropdown.

**Comment by BurningTreeC** [comment]
> I do think the more expected behaviour would be to clear the typed input when clicking an entry in the dropdown.

That's fixed with #5041 ... but the OP is more about state tiddlers not being deleted after cancelling/deleting a tiddler

**Comment by kookma** [comment]
@Jermolene Can I close this issue or it should be open for other fields?

**Comment by BurningTreeC** [comment]
@kookma I think you can leave this issue open

**Comment by BurningTreeC** [comment]
Hi @kookma, I believe I've fixed this issue in the following Demo:

[delete_state_tiddlers.zip](https://github.com/Jermolene/TiddlyWiki5/files/5542914/delete_state_tiddlers.zip)

If you have some time, you may want to test this :+1:

**Comment by kookma** [comment]
@BurningTreeC, Thank you!

I tested the demo.
 It works fine! After each tag was added the input for the next tag is clear!

**Comment by BurningTreeC** [comment]
@kookma, it should also work for the fieldname and fieldvalue inputs!

**Comment by kookma** [comment]
@BurningTreeC  Sorry, I forgot it!

Well I tested the Demo again! It nicely do clear the field input and works as expected.

**Side notes**: 
When adding a new field (field name) using the mouse click the drop down will be closed, but when you add a field name by selecting from the drop down by pressing `Enter` key the drop down remains open! It is like nothing was happened, but after clicking the field value or remove focus from field name input you see the field was added.

**Comment by BurningTreeC** [comment]
>When adding a new field (field name) using the mouse click the drop down will be closed, but when you add a field name by selecting from the drop down by pressing Enter key the drop down remains open! It is like nothing was happened, but after clicking the field value or remove focus from field name input you see the field was added.

@kookma - I think I don't understand what you mean. The fields that are added should always be clearly visible

**Comment by kookma** [comment]
> @kookma - I think I don't understand what you mean. The fields that are added should always be clearly visible

Yes, the fields that are added are clearly visible! So, I confirm the issue has gone!
My point was: it is good to close the drop down on `Enter`.

**Comment by Jermolene** [comment]
Hi @kookma can this be closed?

**Comment by kookma** [comment]
Thank you Jeremy!
