### ISSUE TITLE
[IDEA] Esc key to close the tag drop down

### ISSUE THREAD

**Issue by kookma** [Jermolene/TiddlyWiki5#5040]
**Is your feature request related to a problem? Please describe.**
In TW 5.1.23, clicking in tag input brings the tag drop down and you can enter a partial word to search in tag dropdown. The Esc key clear the tag input, pressing Esc key again tries to close the tiddler while tag drop down is still open.

It would be convenient to use Esc key when tag input under focus to close the tag drop down menu!

So

1. If tag input has something, Esc key clear the tag input
2. If tag input is empty, Esc key close the tag input and text field get focused 

**Note**
This may need further investigation, as in the current configuration except the tag input everywhere in a tiddler (in any field) when you press the Esc key, it closes the tiddler and ignore the changes. Only tag input is an exception.

**Comment by saqimtiaz** [comment]
Is there really much utility in closing the tag dropdown though? If you're finished with tagging, `Tab` takes you to the text area and closes the dropdown.

**Comment by BurningTreeC** [comment]
I'm with @saqimtiaz' opinion

**Comment by kookma** [comment]
@BurningTreeC @saqimtiaz 
Well, it is not critical action and one can click somewhere else or press tab key to move focus to other element and closes the tag drop down! But as the Esc is working to clear the tag input, unintentionally you may press Esc to close the drop down and then you loose the changes as the second Esc closes the tiddler. 

I think this may be an improvement in workflow but it does not hurt me if you keep the current configuration!
