### ISSUE TITLE
[IDEA] use "share" and "share all" instead of "permalink" and "permaview"

### ISSUE THREAD

**Issue by pmario** [Jermolene/TiddlyWiki5#5053]
Hi, I just found: https://giffmex.org/gifts/documenting.tw.html which uses a nice "share" button, which basically does the same thing as our "permalink" button. 

![idea-new-share-button](https://user-images.githubusercontent.com/374655/99253036-4f4d8400-2810-11eb-8be1-ce42aa74b93d.gif)

**The Proposal** is: 

We should implement this one into the core, because it is used by many apps and users may be more familiar with it as the "hash" icons we use. 

So "permalink" and "permaview" should be deprecated and replaced by "share" and "share all" (permaview) 

What do you think? ... Especially @giffmex

**Comment by giffmex** [comment]
Great idea! I think the "share" language is more familiar for most people, as is the icon. Glad to have been an inspiration!

**Comment by Jermolene** [comment]
Hi @pmario @giffmex making a radical change to an existing icon has implications for existing documentation and forum posts. Permalink and permaview have been part of TW5 for many years and so we can expect that there would be many references to that functionality making reference to the existing icons.

In any case, this is the Android "share" icon; it isn't used on Apple operating systems, and so will not be familiar to all users.

**Comment by giffmex** [comment]
I had a feeling Jeremy would say that...and he's right about backward incompatibility. 

One option might be just to create the share button as a redundant functionality, then just leave permalink there in the background, and never talk about it again. 

As for the icon, perhaps both the Apple and Android share icons could be added, and instructions on tiddlywiki.com for changing the icon. I agree wth the (nice) article below that the Apple 'share' icon looks more like an 'upload' button. I think both are pretty common enough to communicate the idea.

 https://www.fastcompany.com/3031872/why-isnt-there-a-standard-share-button

**Comment by Jermolene** [comment]
Hi @giffmex indeed, thinking of a "share" icon as a new feature is easier. There might also be scope to use the new browser native share dialogue which has good support on mobile devices:

https://caniuse.com/web-share

**Comment by pmario** [comment]
OK. Having different buttons for the same thing will really cause a lot of confusion. ... So we may wait until the W3.org comes up with an official "spec" in some years ;)

**Comment by giffmex** [comment]
Hi Mario
I think you gave up too soon. No confusion if you quietly hide the permalink in a dark recess of the control panel to be forever forgotten, and play up the share button. But hey, at least I have it as an option in my 'Documeting TW' file for those that want it.

**Comment by pmario** [comment]
I wasn't aware, that the iStuff does use different icons. Having 3 of them instead of 2 IMO is problematic. ... 

My tocP plugin provides 2 different icons for the exact same functionality, because I thought users can use the one they like more. ... But it causes support requests that I don't want to deal with. ... 

The new plugin will keep 2 buttons, for compatibility reasons. BUT new users will only see 1 button.
