### ISSUE TITLE
[IDEA] - Styles for narrow screens

### ISSUE THREAD

**Issue by BurningTreeC** [Jermolene/TiddlyWiki5#5077]
**Is your feature request related to a problem? Please describe.**
On narrow screens like smartphones some UI elements could get better positioning / less padding etc.

**Describe the solution you'd like**
- the right topbar should be more to the right
- the bottom tiddler margin should be smaller
- the tiddler-info-padding (left/right) should be smaller
- ... more? (ideas?)

**Comment by kookma** [comment]
Great idea!

I think one the best theme which consider most  of these is Notebook from https://nicolas.petton.fr/tw/project-manager.html
(Nicolas Petton). It is very handy on smart phone!
