### ISSUE TITLE
[IDEA] Combo Search for TW 5.1.23

### ISSUE THREAD

**Issue by kookma** [Jermolene/TiddlyWiki5#5082]
**Is your feature request related to a problem? Please describe.**
The search box in the right sidebar (called standard searchbox) is the most used method for searching in Tiddlywiki or it will be used as first option when a user try to find something. It searches in title text and tag fields, but how if you want to find tiddlers tag with foo and bar, you need to switch to $:/AdvancedSearch.

**Describe the solution you'd like**
While $:/AdvancedSearch is very useful and yet very powerful, but for such case above it sufficient to let simple filter search in Standard search box like `[tag[foo]tag[bar]]` or `[search:*[simon]]`.

My Commander plugin uses a combo search box.

## What is combo search?
By combo search it means one searchbox can be used to perform both standard and filter search

Tiddler Commander searchbox performs combo search so

- if the first character in the searchbox entered is a `[`, commander will start a filter search
  - example: `[prefix[tid]]`
  - example: `[regexp[kerman]]`
- if any character other than `[` entered as the first character a standard search will be triggred
  - example: `demo`
  - example: `concepts`
The standard search performs a search in title, text, and tags.

**Note**: To perform a standard search for a keyword start with `[` enter a space as the first character in the search box."

Please have a look a https://kookma.github.io/TW-Commander/#Combo%20Search
This is a working combo search box:
https://kookma.github.io/TW-Commander/#%24%3A%2FCommander

To give a try 

1. enter the word `demo` in the search box
2. enter the filter `[tag[demo]]` in the search box

compare the result

**Comment by Jermolene** [comment]
Hi @kookma I would not be in favour of this approach for the core. I think there are a significant fraction of users who are unaware of filters; they are intended to be an advanced feature that is only required by users who are trying to do relatively sophisticated customisation. So, my concern would be that this specialised behaviour would be confusing for those users if encountered by accident.

An alternative approach would be to add a "filter search" tab to the sidebar search results.

**Comment by kookma** [comment]
Hi @Jermolene I understand your concerns.

I just like to explain and clarify the idea: using combo search makes no changes for users who has gotten used to use sidebar search box as a standard search box! so for newbies or those who use Tiddlywiki as a simple note taking  nothing will change. but if somebody like to use it as a filter search he/she just need to start with `[`. 

There are plugins around changes the behavior of search box by adding more tabs to UI, but combo search box keeps standard search as it is now while it can be used for something simple  like `[tag[foo]tag[bar]]`.

**Comment by saqimtiaz** [comment]
@kookma consider that the following is a valid filter but does not start with a bracket:

`HelloThere Community`

**Comment by Jermolene** [comment]
> I just like to explain and clarify the idea: using combo search makes no changes for users who has gotten used to use sidebar search box as a standard search box! so for newbies or those who use Tiddlywiki as a simple note taking  nothing will change. but if somebody like to use it as a filter search he/she just need to start with `[`. 

That's what I meant: under this proposal, if a user who is not interested in filters types `[` into the search box (perhaps because they want to search for a link they have made) they won't get the results they expect, and they are unlikely to guess why.

Hidden features like this are great for more advanced users that have opted into using them, but they are likely to be a pitfall for the less experienced.

> There are plugins around changes the behavior of search box by adding more tabs to UI, but combo search box keeps standard search as it is now while it can be used for something simple  like `[tag[foo]tag[bar]]`.

The core supports tabs in the search results; plugins just need to add a second tiddler with the tag $:/tags/SearchResults in order to activate them.

**Comment by kookma** [comment]
@Jermolene 
Thank you for clarification! I got your point.
