### ISSUE TITLE
[Question] Is there a different process to the WikiText between widget attribut and content?

### ISSUE THREAD

**Issue by zhangaz1** [Jermolene/TiddlyWiki5#5094]
example test use three tiddler, json below, save and import to preview.

[tiddlers.json.txt](https://github.com/Jermolene/TiddlyWiki5/files/5580997/tiddlers.json.txt)

**Comment by saqimtiaz** [comment]
@zhangaz1 I've had a look and I am afraid I don't understand your question. Could you please try explaining it in a different manner perhaps?

**Comment by zhangaz1** [comment]
I mean that the $button tooltip and content use the same WikiText but we got different result (button text and it's tooltip when mouse hover)

**Comment by saqimtiaz** [comment]
@zhangaz1 when you assign a value to an attribute it is used in its raw form.
However if you use the same value in the text field of a tiddler, it is wikified (evaluated) before being used.

If you have a development background then think of if this way.

```
function hello() {
  console.log("hello");
}
```

when you write 
`<$widget myattribute=<<hello>> >`
it is the same as `var myattribute = hello;`

However when you write in the text field of a tiddler:
`<<hello>>`
It is the same as: `hello();`

**Comment by zhangaz1** [comment]
@saqimtiaz
* attribute value wikitext invoke once immediately
* text value wikitext invoke delay to render and invoke until the value is not wikitext
is it right?

**Comment by saqimtiaz** [comment]
@zhangaz1 
- attribute value wikitext like tag={{!!foo}} is only fetched and assigned. It it only *get value*
- the same wikitext in the text of a tiddler is fetched and rendered/wikified. It is *get value* and then *render/wikify value*

**Comment by saqimtiaz** [comment]
@zhangaz1 please read the explanations in this thread as they address the exact same problem:
https://groups.google.com/g/tiddlywiki/c/YCdcBV88h_g

If you now understand the difference please close this issue. Thank you.

**Comment by zhangaz1** [comment]
@saqimtiaz thank you, I recently read the source code of tiddlywiki5 and I understand a bit
