### ISSUE TITLE
[BUG] Import $:/Core to a Tiddlywiki does not show correct TW version

### ISSUE THREAD

**Issue by kookma** [Jermolene/TiddlyWiki5#5095]
**Describe the bug**

**To Reproduce**
1. Go to 'https://tiddlywiki.com/prerelease'
2. Open $:/ControlPanel and then Plugins
3. Drag and drop $:/Core from https://tiddlywiki.com/prerelease to any open Tiddlywiki like https://tiddlywiki.com/
4. Import, save and reload
5. You see the new core has overwritten the old one
6. New create a tiddler with content `<<version>>` and save. It shows the old version e.g 5.1.22
7. Open $:/ControlPanel info tab, it is 5.1.22

**Expected behavior**
I expect new core works instead of old one

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome 86
 - Version TW 5.1.22 and 5.1.23pre

**Comment by saqimtiaz** [comment]
@kookma I'm unable to look at this right away but as a general rule I would always recommend importing from the old version into the new one. This allows the upgrader modules in the new version to make any compatibility changes that might be needed

**Comment by Jermolene** [comment]
Hi @kookma just to explain what's going on: the version number of a TiddlyWiki file is taken from the line `<meta name="tiddlywiki-version" content="5.1.23-prerelease">` at the top of the HTML file, and not from the core plugin. If you check the control panel "Plugins" tab at step 7 in the OP you'll see that the plugin is indeed the newer version.

**Comment by kookma** [comment]
Thank you @Jermolene!
