### ISSUE TITLE
[BUG] Some characters in tiddler titles in pre-release are obscured.

### ISSUE THREAD

**Issue by saqimtiaz** [Jermolene/TiddlyWiki5#5104]
**The bottom of some characters in tiddler titles is obscured.**

![image](https://user-images.githubusercontent.com/68092/100004698-286eef00-2dc8-11eb-9e33-45010dee7264.png)

Note the bottom of the character `g` in Plugins.
From: https://tiddlywiki.com/prerelease/#Plugins

![image](https://user-images.githubusercontent.com/68092/100004909-78e64c80-2dc8-11eb-9cb3-55a8ad629f03.png)
Or the `j` and `y` characters at https://tiddlywiki.com/prerelease/#TiddlyWiki%20on%20Node.js

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome. Firefox has the same issue with the j character but only intermittently.

**Comment by saqimtiaz** [comment]
@BurningTreeC do you know if we have made any CSS changes in this area?

**Comment by BurningTreeC** [comment]
@saqimtiaz not that I know ... this is new to me

**Comment by saqimtiaz** [comment]
Everything is fine on tiddlywiki.com

**Comment by BurningTreeC** [comment]
@saqimtiaz I'll investigate - but I can't remember having changed anything in this direction. Maybe it's the new normalize.css we're using

**Comment by saqimtiaz** [comment]
@BurningTreeC thanks! It occurred to me that for the layout switcher I only focused on the modal and just copied your switcher code verbatim without testing it. Going to give it a quick test now to confirm it switches layouts as expected.

**Comment by BurningTreeC** [comment]
>It occurred to me that for the layout switcher I only focused on the modal and just copied your switcher code verbatim without testing it. Going to give it a quick test now to confirm it switches layouts as expected.

fingers crossed that it works @saqimtiaz

**Comment by saqimtiaz** [comment]
Switching layouts doesn't work! But I think the problem is not with the switcher but the underlying code. Sigh.

Will investigate after dinner. Sorry for going offtopic here.

**Comment by BurningTreeC** [comment]
@saqimtiaz - to this issue here: it may have something to do with the new font settings. They prefer the system-ui font now

**Comment by saqimtiaz** [comment]
@BurningTreeC manually changing the font family to the same as 5.1.22 didn't seem to help. Can you confirm that?

**Comment by BurningTreeC** [comment]
@saqimtiaz - I don't seem to have this issue

Linux, Google Chrome

![Bildschirmfoto_2020-11-23_20-51-02](https://user-images.githubusercontent.com/9407182/100008443-c6b18380-2dcd-11eb-8a91-fe7914b63e9c.png)

**Comment by saqimtiaz** [comment]
@BurningTreeC I think you may be right about the font. It seems like overriding it to the same value as 5.1.22 via the ControlPanel does not work:

![image](https://user-images.githubusercontent.com/68092/100008479-cf09be80-2dcd-11eb-8012-a08ceaef5f25.png)

**Comment by BurningTreeC** [comment]
@saqimtiaz I believe this is because vanilla/reset sets those fonts on the body and it shouldn't do so

**Comment by BurningTreeC** [comment]
@saqimtiaz @Jermolene - so we should delete the block from vanilla/reset that defines those font-family styles on the body

**Comment by saqimtiaz** [comment]
@BurningTreeC It seems the reset is not the actual problem. The culprit seems to be the changes made in this commit by @pmario :
https://github.com/Jermolene/TiddlyWiki5/commit/4877891980f077c6c31e99cc6a9eb45b5d1230e1

**Comment by saqimtiaz** [comment]
The problem is intermittent in Firefox but a constant in Chrome. Reverting to the version of the ViewTemplate from before that commit resolves it. But I don't understand the reasoning behind that change well enough.

@pmario could you please take a look?

**Comment by saqimtiaz** [comment]
> @saqimtiaz I believe this is because vanilla/reset sets those fonts on the body and it shouldn't do so

@BurningTreeC that might be a separate issue.

**Comment by BurningTreeC** [comment]
@saqimtiaz - great that you found the root of this problem. But there's still a problem with the fonts which we found here I think: deleting the fonts from ControlPanel->Appearance doesn't change anything on the current prerelease, because they are overridden by the ones in the vanilla/reset Stylesheet

**Comment by BurningTreeC** [comment]
>that might be a separate issue.

You've been faster :grin:

**Comment by saqimtiaz** [comment]
@BurningTreeC suggest creating a separate issue for that.

**Comment by pmario** [comment]
@saqimtiaz   I thought I fixed the problem. see my comments at: https://github.com/Jermolene/TiddlyWiki5/pull/4859 

I did change the line-height from 1.2em to 1.3em. ... That fixed the problem for me in FF

**Comment by saqimtiaz** [comment]
@pmario it is still an issue on Chrome. Could you please take a look?

**Comment by pmario** [comment]
yes

**Comment by saqimtiaz** [comment]
Thank you @pmario
