### ISSUE TITLE
[IDEA] Dark Palettes and Few Elements in Tiddlywiki does not follow Palette

### ISSUE THREAD

**Issue by kookma** [Jermolene/TiddlyWiki5#5112]
**Is your feature request related to a problem? Please describe.**
There are many beautiful dark palettes in Tiddlywiki 5.1.23 like Gruvbox, Cupertino, Nord, Spartan night,... but there are elements in Tiddlywiki and official plugins do not follow the palettes.

See below screenshots

**Panels in GettingStarted**
![092_chrome](https://user-images.githubusercontent.com/830394/100052966-4ffba100-2e34-11eb-903f-7fe66c13f879.png)

**Editor when CodeMirror
![091_chrome](https://user-images.githubusercontent.com/830394/100052990-5db12680-2e34-11eb-9c27-69d68fd6c61b.png)
![090_chrome](https://user-images.githubusercontent.com/830394/100053006-61dd4400-2e34-11eb-8b7c-db28ffbb53d1.png)

**Describe the solution you'd like**
These elements shall follow dark palette colors, Also official plugins shall follow dark/light palettes

**Comment by kookma** [comment]
For CodeMirror plugin I know one can install a dark palette but it is better to have customized and consistent colors for official plugins.

**Comment by BurningTreeC** [comment]
@kookma it's true that for the codemirror and highlight plugins we could provide the colors with the palette. I'll investigate a bit to see if it's worth the effort
