### ISSUE TITLE
[BUG] GitHub saver often fails with a 409 Conflict

### ISSUE THREAD

**Issue by spinningarrow** [Jermolene/TiddlyWiki5#5119]
**Describe the bug**
I've set up the GitHub saver with auto-saving set to disabled. Saving succeeds sometimes, but quite often I get the "409 conflict" error message.

I'm using Safari on macOS Catalina.

**To Reproduce**
1. Setup the GitHub saver
2. Create a new tiddler
3. Save it
4. Create another one
5. Save it

**Expected behavior**
Saving is always successful

**Screenshots**
Here's the log in the network tab of the browser:

![image](https://user-images.githubusercontent.com/1797328/100232755-10fb4780-2f29-11eb-9935-3946519a3e9b.png)

From here it looks like the failures always happen after the `contents` response is served from disk. Looking into that `contents` response, it comes back with a Cache-Control header of `private, max-age=60, s-maxage=60` so my guess is that when a save is done within 60s, `contents` is loaded from disk (and therefore has the same SHA) which then causes the subsequent PUT request to fail.

**Desktop (please complete the following information):**
 - OS: macOS Catalina (latest update)
 - Browser: Safari (latest update for Catalina)

**Comment by pmario** [comment]
How long did you wait between your step 3. save and 5. save ... After a save the github server needs some time to process a background task, that publishes your wiki. .. For me it can take up to 2 minutes until a new write succeeds. 

Depending on the server load I'm sure it can take even more time.

**Comment by spinningarrow** [comment]
@pmario I waited about half a minute, maybe 45 seconds? But I didn't understand what you mean by "publishes your wiki" - publishes it where?

**Comment by saqimtiaz** [comment]
Are you using Github pages to serve your wiki @spinningarrow 

When you save to Github, after saving to the repository there is a build step that publishes your wiki to Github pages. Github pages is what allows you to load your wiki via *.github.io 

This step can take anywhere from 30s to several minutes.

**Comment by spinningarrow** [comment]
@saqimtiaz nope, I'm not using github pages for the repo, just using the repo to store the TW.

As I understand it, whether GH pages/something similar is being used or not shouldn't matter: once you load the TW in the browser, it uses the github API to talk to the repo directly and fetch the index.html. It does not fetch the published version even when there is one (unless you reload the TW browser tab).
