### ISSUE TITLE
[BUG] Remove TiddlySpot tab from Control Panel?

### ISSUE THREAD

**Issue by saqimtiaz** [Jermolene/TiddlyWiki5#5120]
With TiddlySpot in a read-only state and unlikely to return without major changes if at all, should we remove the saver tab for it from the Control Panel?

**Comment by saqimtiaz** [comment]
Alternatively we could add a status message there explaining the current state of affairs.

**Comment by Jermolene** [comment]
Perhaps lets add a warning banner for as long as there's a chance it's going to be fixed?

**Comment by kookma** [comment]
I thought to some an advanced settings! For example in Google Chrome users see Settings which fit many users requirements but there is a button show advance settings which reveals some tabs and controls.

One solution here may be using an advanced setting checkbox when checked reveals other settings (show hidden tabs, ...)

**Comment by Jermolene** [comment]
> I thought to some an advanced settings! For example in Google Chrome users see Settings which fit many users requirements but there is a button show advance settings which reveals some tabs and controls.
> 
> 
> 
> One solution here may be using an advanced setting checkbox when checked reveals other settings (show hidden tabs, ...)

Hi @kookma I think this might have been intended for a different ticket?

We do already have an "Advanced" tab in control panel that hides some functionality that's not useful for most people.

**Comment by kookma** [comment]
> Hi @kookma I think this might have been intended for a different ticket?

Sure, I will add a new ticket!

>We do already have an "Advanced" tab in control panel that hides some functionality that's not useful for most people.
I forgot about that.

**Comment by saqimtiaz** [comment]
@BurningTreeC would you have the time for this? I'm still a bit under the weather so it is easier for me to co-ordinate and review than make actual PRs.

 Basically we want to add a message via the lingo mechanism at the top of the TiddlySpot saver.

Something along the lines of: "TiddlySpot service may currently be available as read only. Please see http://tiddlyspot.com/ for details"

**Comment by BurningTreeC** [comment]
Ok @saqimtiaz , I'll have a look

**Comment by saqimtiaz** [comment]
Thank you @BurningTreeC
