### ISSUE TITLE
[IDEA] Overhaul of Tiddlywiki Settings

### ISSUE THREAD

**Issue by kookma** [Jermolene/TiddlyWiki5#5124]
**Is your feature request related to a problem? Please describe.**
Right now all the settings can be accessed by opening the $:/ControlPanle. Are all of these required for normal users?  Of course there is an Advanced Tab which used by superusers.

**Describe the solution you'd like**
A propose a setting page like Chrome

![image](https://user-images.githubusercontent.com/830394/100337247-63ea0300-2fec-11eb-9f19-719cce8d9af4.png)

It has three features:

1. A searchbox to find a setting (or hidden one)
2. A Tree like menu in the left with icons to simply recognize categories. Click on each category open the setting for that category in the right panel.
3. A hidden Advanced section on click expand advanced setting categories

I think replicating the Chrome Setting page in Tiddlywiki is simple. TW has all required tools to create such elements.

If we want to keep the current design, I am insisted to have item 1 and 2 above.

**Comment by saqimtiaz** [comment]
Also see #4957

**Comment by kookma** [comment]
@saqimtiaz should I close this issue and move comments to #4957

**Comment by saqimtiaz** [comment]
@kookma if you don't mind, it will be easier to have everything in one place :)

**Comment by kookma** [comment]
Sure!
