### ISSUE TITLE
[IDEA] filter operator to pad a string to given length

### ISSUE THREAD

**Issue by saqimtiaz** [Jermolene/TiddlyWiki5#5137]
I've needed this a few times and mostly recently for something that might be a candidate for the core. 

I am not sure what the best name for the operator would be suggest something of the form `[[...input...]pad[length],[optional-character-to-pad-with]]`

`[[12]pad[5]]` => `00012`

`[[12]pad[4],[-]]` => `--12`

**Comment by Jermolene** [comment]
Great idea. Zero padding numbers to a given length might be another usecase, but perhaps that's better dealt with by a format:number operator?

**Comment by saqimtiaz** [comment]
@Jermolene yes `format:number` is one option. Also most filters assume strings as input/ouput so treating a number like a string and zero padding it would work for most use cases too.

What operator name would you suggest? `pad`?

I wrote the following a while ago for personal use. I can try to clean it up for a PR in the next day or two:

```
exports.pad = function(source,operator,options) {
	var results = [],
		padlength = operator.operand ? parseInt(operator.operand) : 0,
		fill = operator.operands[1] || "0";
		
	source(function(tiddler,title) {
		if(title && title.length) {
			var len = Math.max(title.length,padlength);
			var pos = operator.suffix && (operator.suffix == "suffix") ? "suffix" : "prefix";
			while (len > title.length) {
				if(pos == "prefix") {
					title = fill + title;
				} else {
					title = title + fill;
				}
			}
			results.push(title);
		}
	});
	return results;
}

})();
```

**Comment by Jermolene** [comment]
Thanks @saqimtiaz. `pad` is reasonable. I think your implementation might return a string longer than the specified length if the pad string is more than one character?

**Comment by saqimtiaz** [comment]
@Jermolene yes that is correct and I'll tweak that before submitting a PR. This is something that was quickly whipped up for personal use where I knew the pad string would never be a single character.

**Comment by Jermolene** [comment]
Thanks @saqimtiaz otherwise I think this is just what we need.

**Comment by saqimtiaz** [comment]
@Jermolene thinking about it this morning, ensuring the correct length is a bit tricky when the string to pad with can be of variable length:

1. we can ensure that the final string is never longer than the specified length, but it could end up shorter. `[[12]pad[7],[abc]]` can be `abc12` (5 characters) or `abcabc12` (8 characters)
2. or we can pad with a part of the padding string only to get the length exact: `[[12]pad[7],[abc]]` => `bcabc12` . This does not seem intuitive and could potentially be very confusing.
3. or we specify that the **fill string can only be a single character**. If the user provides a longer string, all but the first character are ignored.
`[[12]pad[7],[a]]` => `aaaaa12`
`[[12]pad[7],[ab]]` => `aaaaa12`

Personally I favour option `3.`
Thoughts?

**Comment by Jermolene** [comment]
Hi @saqimtiaz interestingly, JavaScript's "padStart/padEnd" methods actually seem to do the second option:

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/padStart

There might be something to be said for sticking with existing JS semantics.

**Comment by rmunn** [comment]
:+1: for sticking with existing JS semantics (i.e. option 2 among the ones that @saqimtiaz listed). And we should document the behavior of multi-character padding with text in the documentation tiddler *and* with examples. The ones at https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/padStart#Examples and https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/padEnd#Examples are probably good (converted to TiddlyWiki syntax, of course).

Also :+1: for getting this in before the 5.1.23 release, as it is a nice counterpoint to the new functionality of the `trim` operator. (Which, now that I think about it, really should be tagged as a "String operator" now that it has new functionality. I'll do a quick PR for that.)

**Comment by saqimtiaz** [comment]
@Jermolene @rmunn the PR for the operator is up: #5146
