### ISSUE TITLE
[IDEA] - External attachments plugin should work with dropzone widget

### ISSUE THREAD

**Issue by BurningTreeC** [Jermolene/TiddlyWiki5#5142]
**Is your feature request related to a problem? Please describe.**
When I have the external attachments plugin installed (TiddlyDesktop) and I drop a file into my wiki, the external attachments plugin should catch in and import the file like it does using the import button

**Comment by Jermolene** [comment]
Hi @BurningTreeC the external attachments plugin currently just uses the `th-importing-file` hook to transform tiddlers as they are imported. Are you asking for the import process to be automated so that no manual intervention is required?

**Comment by Jermolene** [comment]
One thing that might be useful would be to be able to drag a directory into the wiki in order to create _canonical_uri tiddlers for every file in one step.

**Comment by BurningTreeC** [comment]
>the external attachments plugin currently just uses the th-importing-file hook to transform tiddlers as they are imported. Are you asking for the import process to be automated so that no manual intervention is required?

Hi @Jermolene , no I'm asking for the dropzone widget to invoke the th-importing-file hook and therefor making the external-attachments-plugin do the import ... if that's possible somehow

**Comment by BurningTreeC** [comment]
>One thing that might be useful would be to be able to drag a directory into the wiki in order to create _canonical_uri tiddlers for every file in one step.

That would be very useful @Jermolene

**Comment by Jermolene** [comment]
> Hi @Jermolene , no I'm asking for the dropzone widget to invoke the th-importing-file hook and therefor making the external-attachments-plugin do the import ... if that's possible somehow

The dropzone widget just fires the same `tm-import-tiddlers` event as the file browse widget, and the navigator widget handles it by firing off the import process.

I think I'm still missing something though, what is the objective here?

**Comment by BurningTreeC** [comment]
I'll explain it step by step: If I import a file into TiddlyDesktop with the external-attachments-plugin installed and I use the "Import" Button, then the `th-importing-file' hook gets invoked and the external-attachments-plugin imports the file using the `_canonical_uri' field, it leaves the file externally. But if I drag a file into the same wiki, a file `Untitled` gets created with the text-content: `file:///path_to_file.extension` ... And I'd like it to behave the same way as if I'd import the file via the Import Button. Is that possible somehow?

**Comment by Jermolene** [comment]
Hi @BurningTreeC I've not encountered that behaviour, it seems like a bug. Does the distinction between dragging and using the import button only happen in TiddlyDesktop?

**Comment by BurningTreeC** [comment]
>I've not encountered that behaviour, it seems like a bug. Does the distinction between dragging and using the import button only happen in TiddlyDesktop?

@Jermolene - If I try the same file on FireFox, the file gets imported using the Import Button. But if dragging the file into the wiki, the tiddler "Untitled" gets imported with the text-content same as above (`file:///path_to_file.extension`)

OS: Linux

**Comment by BurningTreeC** [comment]
@Jermolene - Sorry for the confusion, I've just found out that this is a desktop-specific bug. It works fine when I switch to my Standard Linux-Desktop. It just doesn't work using the sway window-manager, seems that they have a drag-and-drop bug

**Comment by Jermolene** [comment]
> @Jermolene - Sorry for the confusion, I've just found out that this is a desktop-specific bug. It works fine when I switch to my Standard Linux-Desktop. It just doesn't work using the sway window-manager, seems that they have a drag-and-drop bug

Phew! That's a relief. Happy to try to look at workarounds we could incorporate if the problem isn't going away.

**Comment by BurningTreeC** [comment]
Thanks @Jermolene! I'll report the bug at the swaywm repo
