### ISSUE TITLE
[BUG] Disable CamelCase don't work without reload

### ISSUE THREAD

**Issue by silvyn** [Jermolene/TiddlyWiki5#5160]
Hello,

**Describe the bug**

On prerelease 5.1.23, disable automatic CamelCase don't work for me.

**To Reproduce**

Go to ControPanel
Uncheck Enable automatic CamelCase linking
And voilà, CamelCase are still alive.

**Expected behavior**
Of course, disable CamelCase link ;)

**Comment by saqimtiaz** [comment]
It looks like disabling automatic CamelCase works but requires a save and reload. Could you confirm that @silvyn ?

**Comment by saqimtiaz** [comment]
In fact, I get the same behaviour at https://tiddlywiki.com/ so in version 5.1.22

**Comment by silvyn** [comment]
Hi @saqimtiaz yes it's true. Save and reload work.

Arf, so if it's on 5.1.22 it's not 5.1.23 ;) (but I'm wrong of thinking it was not necessary before ?)

**Comment by saqimtiaz** [comment]
@silvyn honestly I don't remember what the behaviour for this has been like in the past. So I am not sure if it is a regression or the expected behaviour.

**Comment by Jermolene** [comment]
It's not a regression, I'm afraid. Global disabling of parser rules is accomplished at the JavaScript module level, and hence requires a restart.

**Comment by saqimtiaz** [comment]
@Jermolene that makes sense and I rather think it is good news that it is not a regression.

@silvyn could you please close this issue?

**Comment by silvyn** [comment]
Thanks, I've just read the worning indeed. Sorry !
