### ISSUE TITLE
[BUG] Tiddler opening position in story is incorrect in 5.1.23 pre-release

### ISSUE THREAD

**Issue by saqimtiaz** [Jermolene/TiddlyWiki5#5162]
As reported [here](https://groups.google.com/g/tiddlywiki/c/i_rzRBDZvn4), the setting for where in the story the tiddler is opened, is not respected.

I believe this bug was introduced in #4200 

`Navigator.prototype.addToStory` calls `Story.prototype.addToStory` with [4 arguments](https://github.com/Jermolene/TiddlyWiki5/blob/master/core/modules/widgets/navigator.js#L131) whereas it [accepts only 3](https://github.com/Jermolene/TiddlyWiki5/blob/master/core/modules/story.js#L37). 

Presumably the 4th argument needs to be merged into the 3rd as an options object. However it **does not seem like the 3rd argument as it is now is used at all**? 

I haven't had the time to fully read through and understand the logic of this PR, but it seems like it is not quite consistent and needs careful review.

@Jermolene @BurningTreeC @pmario

**Comment by BurningTreeC** [comment]
@saqimtiaz this is indeed a bug introduced by my PR. I'll add a fix shortly
