### ISSUE TITLE
[BUG] - x-listops.js throws Syntax Error on Internet Explorer

### ISSUE THREAD

**Issue by BurningTreeC** [Jermolene/TiddlyWiki5#5170]
**Describe the bug**
Using IE 11 on startup there's a RSOD saying "Syntax Error in x-listops.js"
I can't track the problem down since the Konsole doesn't show anything, but maybe @saqimtiaz has an idea what could be the problem?

**Comment by saqimtiaz** [comment]
@BurningTreeC could you please confirm that #5171 resolves it for you?

**Comment by BurningTreeC** [comment]
I'll give it a try @saqimtiaz

**Comment by BurningTreeC** [comment]
Yes @saqimtiaz , #5171 resolves the issue on IE

**Comment by Jermolene** [comment]
Thank you @saqimtiaz @BurningTreeC
