### ISSUE TITLE
[IDEA] Extend Range operator to allow hex incrementals

### ISSUE THREAD

**Issue by AnthonyMuscio** [Jermolene/TiddlyWiki5#5177]
**Is your feature request related to a problem? Please describe.**
Unicode and html entities and other systems make use of hex values. There is however then need to readily convert between hex and decimal with a macro but incrementing hex number is unwieldly.

**Describe the solution you'd like**
I would be nice if the range operator or a new rangehex operator could increment hex numbers one or more hex digits at a time.

**Describe alternatives you've considered**
As in the problem definition. 

**Additional context**
In many cases we need not convert hex to decimal at all but if we want to generate a list we have to do two way conversions for every increment and can simply could the values from data.

I ask because perhaps there are Javascript functions that will allow this with little change on the current range operator.

I would not be surprised if Javascript or HTML/CSS already have this feature.

Regards
Tony

**Comment by Jermolene** [comment]
Hi @AnthonyMuscio there are a couple of other ways we could handle this that wouldn't be restricted to the range widget:

* Introduce an operator that converts hexadecimal numbers to decimal. For example `[[FFFF]parse:int[16]multiply[3]]`
* Extend the parsing of numeric constants to accept hexadecimal notation prefixed with `0x` (for consistency with JavaScript). For example `[[0xFFFF]multiply[3]]`

**Comment by saqimtiaz** [comment]
At some point I wrote some simple filters for decimal<->hex conversions. Perhaps these might be helpful in the interim:

```
/*\
title: $:/plugins/sq-filters/hex.js
type: application/javascript
module-type: filteroperator
\*/
(function(){

exports.tohex = function(source,operator,options) {
	var results = [];
	source(function(tiddler,title) {
		if(title.length) {
			var value = parseInt(title).toString(16);;
			results.push(value);
		}
	});
	return results;
};

exports.fromhex = function(source,operator,options) {
	var results = [];
	source(function(tiddler,title) {
		if(title.length) {
			var value = parseInt(title,16).toString();;
			results.push(value);
		}
	});
	return results;
};

})();
```

**Comment by AnthonyMuscio** [comment]
Update, The power Operator now facilitates conversion from/to other number bases. 

As a result we can use the range operator in decimal and convert it to another base for each item.

With hex a common base used on computers the Original idea would be helpful, but it is no longer too difficult to achieve with a workaround.

Tony
