### ISSUE TITLE
[BUG] Shortcuts for switching tabs in advanced search clash with macOS text editing shortcuts

### ISSUE THREAD

**Issue by Jermolene** [Jermolene/TiddlyWiki5#5178]
**Describe the bug**
The default `input-tab-left` <kbd>alt-Left</kbd> and `input-tab-right` <kbd>alt-Right</kbd> clashes with core macOS text editing shortcuts that are available in every browser:

> Option-Left Arrow: Move the insertion point to the beginning of the previous word.
> Option-Right Arrow: Move the insertion point to the end of the next word.

See https://support.apple.com/en-gb/HT201236#text

**To Reproduce**

1. Go to https://tiddlywiki.com/prerelease
2. Click on the magnifying glass next to the search box to open advanced search
3. Start typing in the search box, then type <kbd>alt-Left</kbd>
4. The advanced search tab will switch instead of the cursor returning to the start of the line 

**Expected behavior**

We need to choose a different shortcut, at least for macOS. <kbd>ctrl-Left</kbd> and <kbd>ctrl-Right</kbd> appear to be unused.

**Comment by BurningTreeC** [comment]
@Jermolene I think it's appropriate to change it for Mac
