### ISSUE TITLE
[BUG] Autosave does not work correctly in 5.1.23pre

### ISSUE THREAD

**Issue by kookma** [Jermolene/TiddlyWiki5#5182]
**Describe the bug**
Autosave seems does not work in all occasions

**To Reproduce**
1. Go to https://tiddlywiki.com/prerelease/#Empty%20Edition
2. Download the latest empty.html of today  Dec 2nd
3. Open the new empty.html and from control panel / saving select **Save changes automatically**
4. Create a tiddler and save it
5. Refresh browser, you see new tiddler is there [TW works fine]
6. Drag and drop a plugin /json to empty.html for this test I used Katex plugin https://tiddlywiki.com/prerelease/plugins/tiddlywiki/katex/#%24%3A%2Fplugins%2Ftiddlywiki%2Fkatex
7. TW shows the user the wiki has been saved after dropping plugin into it
8. TW asks to refresh and do it
9. Open the Control panel / Plugins
10. Katex is not there!

**Expected behavior**
Autosave shall keep imported JSON/Plugin

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Edge chromium 87
 - Version TW 5.1.23pre

**Comment by pmario** [comment]
Do you use a "saver addOn"? I can not reproduce the problem, becaucs Edge doesn't save at all. The default saver creates empty (1,2,3..) files.

**Comment by kookma** [comment]
Hi @pmario  Yes, I use Timimi.
To make sure if the issue is with Edge, I repeated this test on FF and Chrome and they work fine. All of them uses Timimi saver addon.
I also realized when I deleted a plugin (I tested with KaTex) the autosave does not work and I have to save manually.

So do you think this is related to save addOn?
