### ISSUE TITLE
[BUG] RSOD with any call to $tw.utils.getEditionInfo in the browser

### ISSUE THREAD

**Issue by joshuafontany** [Jermolene/TiddlyWiki5#5187]
**Describe the bug**
Red-screen error "Uncaught TypeError: $tw.utils.getEditionInfo is not a function" whenever `[editions[]]` or `[editiondescriptions[]` is called (from the $:/AdvancedSearch Fitler tab, for example).

**To Reproduce**
1. Go to the $:/AdvancedSearch Filter tab.
2. Enter exactly "[editions[]]"

Results: RSOD Error above

It's weird because 
```
title: $:/core/modules/utils/edition-info.js
type: application/javascript
module-type: utils-node
```
definitely exists on disk, but `$tw.utils.getEditionInfo` does not exist in `$tw.utils` in the browser....

This occurs live on tiddlywiki.com and tiddlywiki.com/prerelease.

**Comment by joshuafontany** [comment]
I just fond the documentation stating that these filter functions are not available in the web browser. In which case should be treated as unknown filters, i.e. [field:editions[]]/[field:editiondescriptions[]]?

**Comment by Jermolene** [comment]
Hi @joshuafontany I guess the more consistent thing might be for those operators to return empty lists?

**Comment by Jermolene** [comment]
> Hi @joshuafontany I guess the more consistent thing might be for those operators to return empty lists?

I meant to add "in the browser":


> I guess the more consistent thing might be for those operators to return empty lists in the browser?

**Comment by joshuafontany** [comment]
@Jermolene Agreed & and easy fix. https://github.com/Jermolene/TiddlyWiki5/pull/5222
