### ISSUE TITLE
[IDEA] Suffix for stringify and jsonstringify to not escape Unicode characters

### ISSUE THREAD

**Issue by rmunn** [Jermolene/TiddlyWiki5#5189]
**Is your feature request related to a problem? Please describe.**
The `stringify` and `jsonstringify` filter operators escape Unicode characters in addition to escaping characters like `"` and `\` and newlines. While this is useful for portability (it ensures that the resulting string contains only ASCII characters and is therefore safe to read in any context), it may be overkill for some use cases. I'd like to see a suffix added to these operators that allows them to pass Unicode codepoints U+0080 and higher unchanged. There are many times when I know the tool chain I'm using is handling Unicode correctly all the way through, and I don't need þ turned into `\u00fe` because I know it will come out as þ on the other side of my tool chain. This would be especially relevant for people working in languages that don't use the Latin alphabet, where nearly every letter of their tiddlers would be above U+0080, so escaping those would turn three bytes of UTF-8 into six bytes, or two bytes of UTF-16 into twelve bytes.

I suggest adding the suffix `rawunicode` for the `stringify` and `jsonstringify` filter operators to enable skipping codepoints U+0080 and up. The suffix `raw` would also work, but since we use that as the opposite of `dedupe` it might cause confusion, or it might cause people to think that characters U+001F and below would also be skipped (no; U+001F and below would still be encoded). So `rawunicode` would best communicate what the suffix does, I think.

**Describe the solution you'd like**
Implementation would be very simple: add a Boolean parameter to the `stringify` and `jsonStringify` functions in utils.js, named something like 'rawUnicode', which will default to undefined (and therefore be considered false if not passed) for compatibility with existing calls to those functions. If it is true, then the final `.replace()` call that replaces characters from U+0080 and up is just not called.

**Describe alternatives you've considered**
Leaving it as-is is not necessarily a bad option, because I might be a rarity in wanting this. But since the implementation is simple and it will be simple to explain, I think it's worth considering.

**Comment by Jermolene** [comment]
Hi @rmunn that's a good idea, do go ahead and prepare a PR if you can.

**Comment by rmunn** [comment]
I can probably get a PR done for this within the next 24 hours.

**Comment by rmunn** [comment]
While creating the PR, I discovered that the escaping in jsonstringify is wrong! Actually, the escaping for stringify and jsonstringify is backwards. The [JSON spec](https://www.json.org/json-en.html) only allows `\u` escapes (with exactly four hex digits) where as the [Javascript spec](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String#Escape_notation) allows `\x` escapes with two hex digits for codepoints 00-ff, or `\u` escapes with four hex digits for codepoints 100 and above (using surrogate pairs for astral-plane characters). Which means the jsonstringify operator has been producing invalid escapes for characters U+00FF and below, while stringify has been producing escapes that are longer than they need to be. My PR will also switch the code around between stringify and jsonstringify, and mention that fact in the tiddler documentation for both operators.

**Comment by rmunn** [comment]
PR: #5191

I fixed the documentation for `\x` while I was at it (the stringify operator uses `\x`, the jsonstringify operator doesn't). If the release is much delayed, I can submit a PR against tiddlywiki-com making that swap in the documentation, but that would create a merge conflict later on when master is merged into tiddlywiki-com to update the documentation. Since the issue would almost never come up in practice (you really have to *work* at it to create a string with a character that `stringify` would escape with a `\x` sequence), I think it's safe to just let the documentation be updated when 5.1.23 is released, since that will be pretty soon anyway.
