### ISSUE TITLE
[IDEA] reduce operator: initial value from second operand.

### ISSUE THREAD

**Issue by saqimtiaz** [Jermolene/TiddlyWiki5#5190]
Use an optional second operand for the initial value for reduce, so that variables and references can be used to assign it.

@Jermolene if we want to support this we should make the change before 5.1.23 goes live.

**Comment by rmunn** [comment]
I like it. The suffix was used because the reduce operator went in (IIRC) before we added the possibility of having two operands, and a second operand is much more flexible.

**Comment by saqimtiaz** [comment]
@rmunn @Jermolene a PR is up: #5193 

If we want to make this change the sooner the better before 5.1.23 goes live.

**Comment by Jermolene** [comment]
Great idea, thanks @saqimtiaz
