### ISSUE TITLE
Introduce shortcut syntax for transclusion passing parameters via variables

### ISSUE THREAD

**Issue by Jermolene** [Jermolene/TiddlyWiki5#5199]
There has been some recent [discussion](https://github.com/Jermolene/TiddlyWiki5/issues/5188#issuecomment-737896712) (and the subsequent PR #5195) about the poor parsing performance of macro calls compared to transclusions. In particular, the result of parsing each tiddler is cached and reused next time if the tiddler hasn't changed (the same technique can't be used for macro calls because they are not global but local to the widget tree).

So, we should promote the judicious use of this technique. However currently, it is inconvenient to pass parameters to transclusions as a separate `<$set>` or `<$vars>` widget needs to be used.

It is proposed to introduce a shortcut wikitext syntax for passing parameters via variables when transcluding a tiddler. For example:

```
{{tiddler||template} myvar=<<value>> }
```

Would be equivalent to:

```
<$vars myvar=<<value>>>
{{tiddler||template}}
</$vars>
```

(We may want to allow `:` to be used as a synonym for `=` for consistency with the existing macro call syntax).

We may also want to support positional parameters that do not need to be named when they are called:

```
{{tiddler||template} <<value>> }
```

In such a case, the target tiddler would have to define a `parameters` field containing an ordered list of the parameter names it requires, and then the provided value would be assigned to the correct variable before the transclusion.

**Comment by saqimtiaz** [comment]
@Jermolene Overall I am very much for this proposal.

I am somewhat unsure about the _positional parameters_ and the _parameters field_ in the target tiddler. It would be introducing an entirely new concept and cognitive overhead for users. Unless it offers some advantage that I am not thinking of at the moment I would prefer that _named parameters_ be used. This way the same template tiddler could be transcluded with the new syntax, or the old fashioned way using a vars. Also it would be one less new concept for users to learn.

**Comment by saqimtiaz** [comment]
Perhaps we also need to document the performance advantage of transclusions over macros at https://tiddlywiki.com/#Performance

**Comment by pmario** [comment]
>I am somewhat unsure about the positional parameters and the parameters field in the target tiddler. 

+1

I think we should stick with named params only.

**Comment by AnthonyMuscio** [comment]
What we need at a **minimum is at least one, possible parameter** in the short form and widget transclude, allowing other custom parameter's and dealing with arbitrary names and positioning of parameter's may be desirable (as discussed in this thread) but I believe 90% of the increased functionality becomes available, with only one parameter being available. It could be used as a switch.

The transclusion variable used inside a transcluded template returns a little more information. It can be used to get the name of the transcluded/transcluding tiddler, but you have to parse the output of the transclusion variable. Setting a variable for this "code tiddler" would be helpful.

In effect the currentTiddler value is currently the only parameter "passed" with a transclusion, even just a single additional parameter would allow a template to respond. Currently I have a workaround, in a number of templates, that I invoke with `{{paramname||templatename}}` where the currentTiddler variable can be used as a parameter, and if I need access to the currentTiddler, I get it from the Story Tiddler variable.

Since transclusions can access variables and other values, all we need is a simple way to pass a value when wanting to add a switch mechaisium inside a transclusion. For example
`{{tiddlername||templatename:switch}} `eg `<<switch>>` may be equal to **view or edit** and can be used to change the way the template responds. and the switch variable set to that value. Passing a filter as a parameter would also be helpful.

This may allow transclusions to be used more often and more efficiently than macros.

It may be easy may be to to update the transclude widget such that it's parameter's varname=value are converted to variables before transclusion. This long form could be used when there is more complex parameter requirements but a simple pre-named variable made available in the short form eg `<<switch>> or <<param>>`

Regards
Tony

**Comment by Jermolene** [comment]
Hi @AnthonyMuscio I'm not clear if you're agreeing with the proposal in the OP, suggesting additional features or making an entirely different proposal. Comments like "This may allow transclusions to be used more often and more efficiently than macros" are confusing because (a) it's not clear what "this" refers to and (b) it's the motivation given in the OP for this proposal. Are you agreeing or making a different point?

**Comment by pmario** [comment]
@Jermolene ... did you create any code already?

**Comment by Jermolene** [comment]
> @Jermolene ... did you create any code already?

No I haven't looked at this further yet.

**Comment by pmario** [comment]
I think that would be a nice and understandable syntax.

```
{{tiddler||template} myvar=<<value>> }
```

We may also consider this

```
{{{"filter syntax here"} myvar=<<value>> }}
```

to have "feature" parity the [transclude widget](https://tiddlywiki.com/#TranscludeWidget) needs the same mechanism for additional variables, which leads us to the same problem we discussed at: #5026 and #5052

I did implement it for my `wl-radio-widget` like this: https://github.com/wikilabs/plugins/blob/master/wikilabs/custom-markup/tiddlers/widgets/wl-radio-widget.js ... 

Which is 1 of the versions we discussed ... It turns out to be very usable and easy to read and understand. see: https://wikilabs.github.io/editions/custom-markup/#test-wl-radio

**Comment by AnthonyMuscio** [comment]
> Hi @AnthonyMuscio I'm not clear if you're agreeing with the proposal in the OP, suggesting additional features or making an entirely different proposal. Comments like "This may allow transclusions to be used more often and more efficiently than macros" are confusing because (a) it's not clear what "this" refers to and (b) it's the motivation given in the OP for this proposal. Are you agreeing or making a different point?

First this reply is direct to you first line "poor parsing performance of macro calls compared to transclusions", clearly this supports and restates your proposal, and yes I share more information without judgement that may guide the final solution.

As my first reply to the post "This" Refers to the OT, and the minimum possibility of a switch parameter. My reply supports the idea and puts forward the argument even if a single additional parameter were available and illustrate it.

I also illustrate a way I use the currentTiddler variable as a parameter.

I also suggest it may be good to provide handling so varname=value are converted to variables.

Regards
Tony

**Comment by motisal** [comment]
This is a useful enough idea that I'd look for a way of making it apply to more than only transclusions. This would also be useful for arbitrary widget and macro invocations. A suitable prefix notation, likely with a new token representing the operation, could be part of the general expression syntax.

**Comment by Jermolene** [comment]
Hi @motisal that sounds interesting. I had seen this proposal as bringing transclusions up to par with macros and widgets in terms of parameters/attributes; how would you see it applying there?

**Comment by motisal** [comment]
It would be a quite flexible mechanism, but only within code. The most obvious things to me are patterns from functional programming, such as argument binding, currying, and closures. This would include being able to set context on an invocation accessed through an indirection such as a variable reference; this would be tantamount to adding context to root of a widget tree. It's also a step toward having contexts be a data type, so that they themselves could support indirect reference.

Insofar as syntax goes, widgets invoke arguments by name with "=" and macros invoke with ":". I'd suggest that harmonizing these for consistency, and whatever is chosen be used for the present issue. The context of html attributes dominates here, so adding "=" for macro invocations and deprecating ":" seems the best choice.

**Comment by motisal** [comment]
> the result of parsing each tiddler is cached and reused next time if the tiddler hasn't changed (the same technique can't be used for macro calls because they are not global but local to the widget tree)

There doesn't seem to be an open issue on this subject, so please pardon a digression. I'll be brief. Parsing of macros could be cached coherently with the tiddler cache. Macros are defined globally inside tiddlers but need to be evaluated locally. Javascript's `prototype` facility could support a copy-on-write approach for local evaluation, creating new objects only insofar as needed for local evaluation. A first version of this could make a copy of the whole parse tree, and even this would perform better than redoing the parsing itself.

**Comment by Jermolene** [comment]
Hi @motisal 

> It would be a quite flexible mechanism, but only within code. The most obvious things to me are patterns from functional programming, such as argument binding, currying, and closures.

Yes, the TW5 rendering process can be viewed in functional terms, and it's interesting to recognise FP concepts within it.

> This would include being able to set context on an invocation accessed through an indirection such as a variable reference; this would be tantamount to adding context to root of a widget tree. It's also a step toward having contexts be a data type, so that they themselves could support indirect reference.

What do you mean by "context"? For me I'd use it to mean the set of variable values prevailing for a widget in the render tree.

> Insofar as syntax goes, widgets invoke arguments by name with "=" and macros invoke with ":". I'd suggest that harmonizing these for consistency, and whatever is chosen be used for the present issue. The context of html attributes dominates here, so adding "=" for macro invocations and deprecating ":" seems the best choice.

TiddlyWiki wikitext breaks down into layers, and the idea is that beginners can learn these layers progressively, without having to understand successive layers:

* Simple formatting wikitext, links etc
* Macro invocations (which are intentionally simple: parameters are pure text, and there's no "containment" syntax like for widgets/elements)
* Widgets, the underlying primitive layer

So macro invocations are intentionally different, and simpler, than widget tags.

People regularly get confused by the fact that `<<mymacro {{thing}}>>` passes the argument as plain text, but I believe that it would actually make things enormously more complex if we resolved arguments at two different layers.

> > the result of parsing each tiddler is cached and reused next time if the tiddler hasn't changed (the same technique can't be used for macro calls because they are not global but local to the widget tree)


> There doesn't seem to be an open issue on this subject, so please pardon a digression. I'll be brief. Parsing of macros could be cached coherently with the tiddler cache. Macros are defined globally inside tiddlers but need to be evaluated locally. Javascript's `prototype` facility could support a copy-on-write approach for local evaluation, creating new objects only insofar as needed for local evaluation. A first version of this could make a copy of the whole parse tree, and even this would perform better than redoing the parsing itself.

We already cache the parse tree that results from [parsing tiddlers](https://github.com/Jermolene/TiddlyWiki5/blob/427eb6d08511009f6ee09145f8f2268d90328f35/core/modules/wiki.js#L912-L923) and from [parsing macros](https://github.com/Jermolene/TiddlyWiki5/blob/427eb6d08511009f6ee09145f8f2268d90328f35/core/modules/widgets/macrocall.js#L58-L69).

**Comment by Jermolene** [comment]
I'm just about to push an experimental partial implementation of the OP that just extends the transclude widget to use attributes starting with `$` as variables for the scope of the transclusion. I'm not 100% happy with it but would appreciate feedback.

**Comment by pmario** [comment]
It seems you only did change the `<$transclude` widget code. So there is no `{{xx}$var1=test}` parser for the wikitext. right?

**Comment by Jermolene** [comment]
> It seems you only did change the `<$transclude` widget code. So there is no `{{xx}$var1=test}` parser for the wikitext. right?

That's correct, it's a partial implementation in the sense that the OP proposes a wikitext syntax, but this is instead an extension to the transclude widget.

**Comment by pmario** [comment]
I think there is a problem with "variable name clashes" eg: 

```
<$set name="$var_1" value="user $var">
<$vars var_1="user defined variable">
<$transclude tiddler=test $var_1="transcluded" >

`<<var_1>>` is: ''<<var_1>>'',

`<<$var_1>>` is: ''<<$var_1>>'' ... As a naive user I'd expect the $var_1 to be ''transcluded''
</$transclude>
</$vars>
</$set>
```

Which will have a completely unexpected behaviour. ... Copy/Paste this example into the new prerelease and have a closer look. 

I think `$var_1` inside the transclusion is completely unexpected and `var_1` too

I think we do have the same discussion as with my supposed "radio" and "range" widget implementation.

**Comment by pmario** [comment]
I think, the issue shouldn't be closed.

**Comment by motisal** [comment]
> What do you mean by "context"? For me I'd use it to mean the set of variable values prevailing for a widget in the render tree.

Values in variables are the only thing at present where context matters. It's not the only kind of context that could be implemented. Another could be namespace resolution, which would allow, for example, a comparison function to be replaced in a sort or merge operation. Modifying context is also useful in testing by removing elements of context to ensure an absence of unwanted dependencies; this is good for refactoring, as well.

> So macro invocations are intentionally different, and simpler, than widget tags.

My point was really quite narrow about harmonization. Named arguments use "=" in widgets and ":" in macros. This one-character syntax difference should be harmonized.

**Comment by Jermolene** [comment]
> I think, the issue shouldn't be closed.

I didn't mean to close it, it was autoclosed when I made the commit.

> Which will have a completely unexpected behaviour

I think you've hit the problem that troubles me: it is confusing that `$var_1="transcluded"` in your example actually sets the variable `var_1`, not a variable called `$var_1`. That's why it's overwriting your existing variable.

**Comment by Jermolene** [comment]
> Values in variables are the only thing at present where context matters. It's not the only kind of context that could be implemented. Another could be namespace resolution, which would allow, for example, a comparison function to be replaced in a sort or merge operation. Modifying context is also useful in testing by removing elements of context to ensure an absence of unwanted dependencies; this is good for refactoring, as well.

I'm intrigued what you mean by "namespace resolution". The way we handle pluggable comparison functions is via the `sortsub` operator which takes a secondary filter to define the comparison.

> My point was really quite narrow about harmonization. Named arguments use "=" in widgets and ":" in macros. This one-character syntax difference should be harmonized.

I was trying to articulate why they are not harmonized. If macro invocation used "=" then it would lead people to expect that macro invocation works the same as attribute assignment, when it does not.

**Comment by pmario** [comment]
>I think you've hit the problem that troubles me: it is confusing that $var_1="transcluded" in your example actually sets the variable var_1, not a variable called $var_1. That's why it's overwriting your existing variable.

Exactly. I know why you wanted feedback. ... I did have the same problem with my [wl-radio widget](https://wikilabs.github.io/editions/custom-markup/#test-wl-radio) ... which I did implement [like this](https://github.com/wikilabs/plugins/blob/master/wikilabs/custom-markup/tiddlers/widgets/wl-radio-widget.js).

I'm using `usr-varX` as the definition and inside I use `<<__varX__>>` ... 

IMO we already did introduce `<<__var__>>` as something special for macros. ........ 

If we can translate this into `{{xxxxx} varX}` and inside `<<__varX>>` it would be consistent

**Comment by pmario** [comment]
>If we can translate this into {{xxxxx} varX} and inside <<__varX>> it would be consistent

uuups .. It wouldn't

```
<$transclude varX=test/>
```

has the same problem as I have with the wl-radio widget

**Comment by pmario** [comment]
here is the PR where we had the same discussion: https://github.com/Jermolene/TiddlyWiki5/pull/5026

**Comment by pmario** [comment]
Only a comment: I'd really like to solve this problem! ... @saqimtiaz ... are you listening?

IMO it would open up a lot of new possibilities for existing widgets, which I would like to use in my plugins ;)

**Comment by pmario** [comment]
ping: @flibbles @BurningTreeC

**Comment by motisal** [comment]
> I was trying to articulate why they are not harmonized. If macro invocation used "=" then it would lead people to expect that macro invocation works the same as attribute assignment, when it does not.

The difference in calling syntax is perfectly adequate to get that point across. I spent way too many hours over the weekend tracking down what was essentially a typo on this matter. I view the difference as needless cognitive overhead.

If the arguments are passed in fundamentally different manners, then the appropriate harmonization would be both ":" and "=" for both widgets and macros, designating which argument passing regime was in effect. I can't tell that there's any difference there, though.

> namespace resolution

Dynamic resolution of a namespace alias symbols. There's no namespace facility in TW at present, but it could sure use one. It could make packing plugins completely automatic. And it will be needed to eliminate name conflicts in plugins as their number grows.

**Comment by pmario** [comment]
>My point was really quite narrow about harmonization. Named arguments use "=" in widgets and ":" in macros. This one-character syntax difference should be harmonized.

That was a decision, which was discussed very early. I think in **alpha** ... I think, it could be done in a backwards compatible way, if keep `:` and implement `=` as a second option

**Comment by flibbles** [comment]
Maybe it's because I've been having this creeping feeling that Tiddlywiki is suffering from feature-bloat, but is this feature really that high in demand?

Would it be used so often that...
```
<$vars [[however you want them]]>{{myTiddler}}</$vars>
```
...is too verbose for people?

If some users find themselves using a pattern a lot, are the macros so inefficient that...
```
\define tMyTiddler([[vars however you want them]])
<$vars varA=<<__varA__>> varB=<<__varB__>>>{{myTiddler}}</$vars>
\end
```
...causes that much of a slowdown?

**Comment by pmario** [comment]
>Dynamic resolution of a namespace alias symbols. There's no namespace facility in TW at present, but it could sure use one. It could make packing plugins completely automatic. And it will be needed to eliminate name conflicts in plugins as their number grows.

We already use namespaces for plugins. ... But It's a convention only

**Comment by Jermolene** [comment]
> IMO we already did introduce `<<__var__>>` as something special for macros. ........

I'm not sure, in that case we are creating a variable name from a parameter name, but here we're encoding a variable name as an attribute name.

> If we can translate this into `{{xxxxx} varX}` and inside `<<__varX>>` it would be consistent

We don't have the problem at the wikitext syntax level, so at that level we can use the variable name directly.

Possible solutions:

* Introduce a new, differently named clone of the transclude widget that uses `$` for the existing attributes, leaving non-`$` attributes free to be variables.
* Use a different prefix character to mark the attributes that are to be interpreted as variables

> Would it be used so often that...
> 
> ```
> <$vars [[however you want them]]>{{myTiddler}}</$vars>
> ```
> 
> ...is too verbose for people?

That is indeed the question. It's because I've been typing that sequence a lot recently that I wanted to start exploring this.

**Comment by Jermolene** [comment]
> The difference in calling syntax is perfectly adequate to get that point across. I spent way too many hours over the weekend tracking down what was essentially a typo on this matter. I view the difference as needless cognitive overhead.
> 
> If the arguments are passed in fundamentally different manners, then the appropriate harmonization would be both ":" and "=" for both widgets and macros, designating which argument passing regime was in effect. I can't tell that there's any difference there, though.

OK, we're disagreeing over one thing: that using a different syntax in the macro call invocation makes sense because the underlying semantics are different.

>
> > namespace resolution
> 
> Dynamic resolution of a namespace alias symbols. There's no namespace facility in TW at present, but it could sure use one. It could make packing plugins completely automatic. And it will be needed to eliminate name conflicts in plugins as their number grows.

Words like "namespace" and "alias" are a bit ambiguous here. Can you give an example?

**Comment by motisal** [comment]
> We already use namespaces for plugins. ... But It's a convention only

You seem to be acknowledge what I'll say explicitly: rely on a convention won't scale well.

**Comment by Jermolene** [comment]
> > We already use namespaces for plugins. ... But It's a convention only
> 
> You seem to be acknowledging what I'll say explicitly: relying on a convention won't scale well.

I don't think I understand the proposal you're making here, but it's intriguing.

**Comment by motisal** [comment]
> Words like "namespace" and "alias" are a bit ambiguous here. Can you give an example?

I'm drawing this from how C++ has used these terms for a long time. Namespaces are used to disambiguate symbols: `ns_alpha::foo` and `ns_bravo::foo` distinguish between otherwise-conflicting symbols where `ns_alpha` and `ns_bravo` are both in scope. An alias declaration looks like `namespace A = a_really_long_name`; `A::foo` and `a_really_long_name::foo` resolve to the same entity.

I'm not recommending the C++ syntax as necessary (although it's become somewhat conventional) but rather the concept.

Applying this to plugins (and spitballing what would be required), tiddlers could be tagged with namespaces so that definitions (right now, that means macros) would resolve through the declared namespace and not in the global one. One method of exporting a plugin could have a single argument: the namespace symbol. In addition, namespace declarations make possible an export declaration, allowing all other symbols to be local with an explicit or default `private` declaration. The exported symbols become the only visible API of the plugin. The namespace of the plugin can be aliased into the global namespace or left as-is to require its fully-qualified name.

C++ has been around a long time and used for very large projects with lots of independent developer groups participating. These kind of mechanisms have become completely standard. At this point, if you have a naming problems with C++, it's your fault (at least almost always). Packages with namespace leakage just don't get adoption.

**Comment by motisal** [comment]
> OK, we're disagreeing over one thing: that using a different syntax in the macro call invocation makes sense because the underlying semantics are different.

There are two kinds of semantics at play here, though, not just one. The first is the semantics of argument passing. The second is the semantics of subroutine (be it widget or macro) behavior. I see no difference in semantics in argument passing, yet there's a difference in syntax. The difference in both definition and invocation are already sufficient to make clear that difference in semantics.

**Comment by Jermolene** [comment]
> C++ has been around a long time and used for very large projects with lots of independent developer groups participating. These kind of mechanisms have become completely standard. At this point, if you have a naming problems with C++, it's your fault (at least almost always). Packages with namespace leakage just don't get adoption.

Apologies @motisal, to be clear I wasn't criticising anything you'd said, I was asking for clarity because terms like "namespace" and "alias" all get used loosely within the project to mean slightly different things. So, while I understand roughly what you might mean in general, I want to understand what you mean in the context of this project.

> > Words like "namespace" and "alias" are a bit ambiguous here. Can you give an example?
> 
> I'm drawing this from how C++ has used these terms for a long time. Namespaces are used to disambiguate symbols: `ns_alpha::foo` and `ns_bravo::foo` distinguish between otherwise-conflicting symbols where `ns_alpha` and `ns_bravo` are both in scope. An alias declaration looks like `namespace A = a_really_long_name`; `A::foo` and `a_really_long_name::foo` resolve to the same entity.

TiddlyWiki has two independent namespaces: tiddler titles, and variable names.

For tiddler titles, as @pmario says, we use title prefixes as a namespacing mechanism. Likewise, we use namespacing conventions for variables, like `tv-` for configuration variables.

We do also allow direct access to the tiddlers within tiddler using the "subtiddler" attribute of the view widget, which gives a sort of explicit namespace access.

> I'm not recommending the C++ syntax as necessary (although it's become somewhat conventional) but rather the concept.
> 
> Applying this to plugins (and spitballing what would be required), tiddlers could be tagged with namespaces so that definitions (right now, that means macros) would resolve through the declared namespace and not in the global one. 

Macro definitions are created in the widget tree in response to rendering parsed wikitext; by the time they are rendered there's no direct connection to the tiddler or plugin in which they were defined.

>One method of exporting a plugin could have a single argument: the namespace symbol. In addition, namespace declarations make possible an export declaration, allowing all other symbols to be local with an explicit or default `private` declaration. The exported symbols become the only visible API of the plugin. The namespace of the plugin can be aliased into the global namespace or left as-is to require its fully-qualified name.

I don't think that approach would work with TiddlyWiki, or at least it would be a very different design than what we've got at the moment.

Plugins can expose functionality as wikitext tiddlers, or as JS modules, or as CSS stylesheets, all of which involve slightly different techniques to let plugins coexist nicely.

> > OK, we're disagreeing over one thing: that using a different syntax in the macro call invocation makes sense because the underlying semantics are different.
> 
> There are two kinds of semantics at play here, though, not just one. The first is the semantics of argument passing. The second is the semantics of subroutine (be it widget or macro) behavior. I see no difference in semantics in argument passing, yet there's a difference in syntax. The difference in both definition and invocation are already sufficient to make clear that difference in semantics.

Sorry, I should have bought up the word "semantics" so loosely, it's never particularly helpful.

**Comment by Jermolene** [comment]
> I'm just about to push an experimental partial implementation of the OP that just extends the transclude widget to use attributes starting with `$` as variables for the scope of the transclusion. I'm not 100% happy with it but would appreciate feedback.

I've now reverted this change: https://github.com/Jermolene/TiddlyWiki5/commit/28521d82f3df5cc7dd7a3aaecb95dd8cece9c500

**Comment by pmario** [comment]
@Jermolene ... I think this one can be closed since we do have parametrised transclusions now. (I did only read the OP and not the whole thread)

**Comment by Jermolene** [comment]
Thanks @pmario this PR was from before I had discovered the syntax used by Wikipedia for passing parameters to transclusions, which is what we've ended up with in #6666.
