### ISSUE TITLE
[BUG] makeTiddlerIterator in v5.1.23 is using $tw.wiki

### ISSUE THREAD

**Issue by flibbles** [Jermolene/TiddlyWiki5#5201]
**Describe the bug**
Most everything uses `options.wiki` or `this.wiki` with a wiki object it was passed, but makeTiddlerIterator is using $tw.wiki to lookup tiddlers for filter operations. This won't actually cause problems in production, but it did cause some of my unit tests for my filter plugin to fail. I can't create temporary $tw.Wiki objects and test filters against them anymore.

I'll leave it up to you guys whether this is something y'all want to correct. I don't immediately see a passed wiki object available to these `filterrunprefixs`.

**Comment by saqimtiaz** [comment]
I pondered over this briefly when I did the refactoring but didn't forsee any issues with this implementation.

If we do want to avoid the reference to `$tw.wiki`, we would need to call the filter run prefixes with a second argument `self` which is the wiki object.

**Comment by flibbles** [comment]
Actually it's easier than that. We just need to use widgets.filter in `filterrunprefixes/and.js`. The annoying part is that all the unit tests aren't passing a widget. That's easily remedied by passing `{wiki: $tw.wiki, getVariable: function(){}}` to all the filterTiddlers calls in the testing framework (or maybe pass something more appropriate... like a widget). I can make a PR for this later tonight.

**Comment by saqimtiaz** [comment]
@flibbles yes that works too. My issue there was precisely that widget is currently an optional argument.

A PR would be most welcome. Note that the just added reduce.js has the same issue.

**Comment by flibbles** [comment]
PR in #5202.

**Comment by jeremyredhead** [comment]
Since PR #5202 has been merged this issue can be closed, right?

**Comment by flibbles** [comment]
It can. Closed!
