### ISSUE TITLE
[BUG] $log widget producing empty output in Firefox

### ISSUE THREAD

**Issue by rmunn** [Jermolene/TiddlyWiki5#5219]
**Describe the bug**
The `$log` widget appears to be producing blank output in the Firefox console: the values of the logged variables aren't showing up.

**To Reproduce**
I created a tiddler named `Something`, and two related tiddlers called `Something/one` and `Something/two` containing the text `One` and `Two` respectively. (In my real project these would be subcategories of data that I want to show up in the main tiddler). Each of the "one" and "two" tiddlers had a `list` field containing tiddler titles, to simulate my use case.

The content of the `Something` tiddler looked like this:

```plaintext
Something goes here

<$vars foo={{{ [<currentTiddler>addsuffix[/one]get[list]then[ListTemplate]else[nonexistent]] }}}>
<<foo>>
<$log foo currentTiddler/>
<$tiddler tiddler={{{ [<currentTiddler>addsuffix[/one]] }}} >
<$transclude tiddler=<<foo>>/>
</$tiddler>
</$vars>
```

The `<<foo>>` line printed out `ListTemplate` as I expected, and the transclusion looked the way it should (I was doing the equivalent of `{{Something/one ||ListTemplate}}`). But the `<$log foo currentTiddler/>` line just underneath the `<<foo>>` line produced a table that showed rows for `foo` and `currentTiddler`, but the rows were empty. See screenshot below.

A simpler repro would be to just create a tiddler named `ABC` with the following contents:

```
<$log currentTiddler/>
<<currentTiddler>>
```

When I do this, I can see that the `currentTiddler` variable does indeed contain ABC as it should, but the console log is showing an empty value for currentTiddler.

**Expected behavior**
The console log contains actual values.

**Screenshots**
![image](https://user-images.githubusercontent.com/90762/101288086-2c1e5f00-3827-11eb-8b3a-15651123b924.png)

**Desktop (please complete the following information):**
 - OS: Linux (Ubuntu 18.04)
 - Browser: Firefox
 - Version: 81.0

**Additional context**
I don't have time right now to test this under Chrome or other browsers. Once I find the time, I'll report back with those findings.

**Comment by saqimtiaz** [comment]
Your syntax is incorrect.
Use named attributes:
<$log myVar=<<myVar>> otherVar=<<otherVar>>/>

Or check docs at the pre-release site for $$all attribute.

**Comment by saqimtiaz** [comment]
`<$log myVar=<<myVar>> other={{!!status}} $$filter="foo currentTiddler"/>`

**Comment by rmunn** [comment]
Ah, I see. I misunderstood the line "When the widget is rendered, the names and values of all attributes are logged to the JavaScript console" to mean that you could specify the variables by name and their values would be looked up, but you actually have to specify the values in the `$log` element.

However, I fixed my syntax and the problem still persists. Same symptoms: empty values in the console log, both with the `<$log $$filter="foo currentTiddler" />` syntax and with the `<$log foo=<<foo>> currentTidldler=<<currentTidldler>>/>` syntax. So I'll leave this issue open, as it seems there really is a bug and it wasn't just my wrong syntax causing it.

**Comment by saqimtiaz** [comment]
@rmunn I can confirm the problem exists on Firefox. It seems to be caused by the `console.table` call in` utils.logTable`.

**Comment by saqimtiaz** [comment]
So the the second argument to $tw.utils.logTable is the problem. This is only supported for arrays and not objects, however is ignored on Chrome:
https://github.com/Jermolene/TiddlyWiki5/blob/483fd941f57a81bfb86ff7f92a62ff2186cd8ff3/core/modules/widgets/action-log.js#L81

**Comment by rmunn** [comment]
I can confirm that PR #5223 fixes this issue.

**Comment by rmunn** [comment]
And if I use the incorrect syntax, `<$log currentTiddler/>`, then it logs it with a value of `true`, which is what you'd expect once you read the HTML5 spec (and the TW code) and realize that "empty" attributes are treated like booleans with the implied value "true". So `<$log currentTiddler/>` is really being treated as `<$log currentTiddler="true"/>`, and that's what's being logged.
