### ISSUE TITLE
[BUG] Saving in Beaker Browser 1.0 is not working?

### ISSUE THREAD

**Issue by tgirod** [Jermolene/TiddlyWiki5#5227]
**Describe the bug**
I've just installed beaker browser 1.0, created a new drive with a tiddlywiki (v5.1.22) as index.html. When I edit my wiki from beaker and click save changes, I get a "save file" window to save on disk rather than inside the drive.

**To Reproduce**
1. install beaker
2. create a new hyperdrive
3. add an empty tiddlywiki file
4. rename it to index.html
5. open it
6. edit it
7. save it
8. see the save window opening

**Expected behavior**

Saving should update the wiki inside the drive.

**Comment by BurningTreeC** [comment]
Hi @tgirod - the beaker browser save mechanism has changed with version 1.0 and therefor you need tiddlywiki version 5.1.23 to be able to save changes with it. Version 5.1.23 will be released soon

**Comment by tgirod** [comment]
that's great to know, thanks a lot !
