### ISSUE TITLE
[BUG] Get more plugins does not load

### ISSUE THREAD

**Issue by Mixie-12** [Jermolene/TiddlyWiki5#5235]
**Describe the bug**
Using chrome, trying to get more plugins.
Looks like tiddlywiki cant open the plugin library

**To Reproduce**
Open your TiddlyWiki in a browser
Open the control panel , click on the Plugins tab and then the  Get more plugins button
Click  open plugin library to open the official plugin library

**Expected behavior**
Display a library

**Screenshots**
![image](https://user-images.githubusercontent.com/43768459/101409176-cfca4680-38dd-11eb-9be5-9b976cd136cf.png)

**Desktop (please complete the following information):**
Windows, chome 87.0.4280.88 (Official Build) (64-bit)

**Comment by clutterstack** [comment]
I have this issue as well. I searched for issues with plugin libraries, because I've rebuilt my wiki with 5.1.23 and didn't know if it's "just me."  On https://tiddlywiki.com/prerelease/ it looks as though the official library has plugins, but when you click the plugins tab, it goes back to just the two top tabs offering the online or local libraries.

I'm on Mac Catalina 10.15.7, Firefox.

**Comment by saqimtiaz** [comment]
@clutterstack @Mixie-12 Can you both please confirm if you have this problem at:
- https://tiddlywiki.com/prerelease/ 
- https://tiddlywiki.com/

Or is this happening when running locally on node?

The plugin library is working just fine for me at both of the above URLs in Chrome and Firefox on Windows 10.

**Comment by kookma** [comment]
I can confirm using latest 5.1.23 the third party plugin libraries do not work!

Tested: Windows 10, Chrome 87, TW 5.1.23prerelease

**Comment by clutterstack** [comment]
@saqimtiaz It works fine on tiddlywiki.com, but not on tiddlywiki.com/prerelease for me, if I use Firefox (83.0, up to date).

But --  both sites work fine in Safari!

OS: Mac Catalina 10.15.7

**Comment by clutterstack** [comment]
OK, argh, I spoke too soon. I was able to see the plugins under the "plugins" tab in Safari, but if I click another tab it goes blank. 

In any case, looking at the [google group](https://groups.google.com/g/tiddlywiki/c/dZmp1gQivJI/m/s2l6NeAOAgAJ), is this just a matter of finalising the library address on release, and not truly a bug?

**Comment by kookma** [comment]
Another test:

1. go to https://tiddlywiki.com/prerelease/#Empty%20Edition
2. download empty.html
3. go to $:/ControlPanel , Plugins tab, and click on Get more plugins
3.1 NO plugin is displayed (empty window)
4 import https://tiddlywiki.com/prerelease/#%24%3A%2Fconfig%2FOfficialPluginLibrary
5. save and relaod
6. got to $:/ControlPanel , Plugins tab, and click on Get more plugins
7. all official plugin is seen
8. try to add a plugin
9. tab is closed like it resets everything
![116_%pn](https://user-images.githubusercontent.com/830394/101584951-ff6b7280-39f3-11eb-9908-999ee5afab16.gif)



**Tested on**
Windows 10, Chrome 87, Edge 87, FF 82

**Comment by kookma** [comment]
strangely in opera no plugins are shown. the plugin library is empty

**Comment by Jermolene** [comment]
Thanks everyone I've tracked it down to a problem in #4985, I'll commit a fix shortly.

**Comment by kookma** [comment]
@Jermolene - I can confirm the issue has gone.
