### ISSUE TITLE
[BUG] Gruvbox theme button background color + svg image

### ISSUE THREAD

**Issue by kookma** [Jermolene/TiddlyWiki5#5245]
**Describe the bug**

**To Reproduce**
1. Go to https://tiddlywiki.com/prerelease/
2. create a new  tiddler
3. put this wikitext as body and save : `<$button>{{$:/core/images/close-button}} Close</$button>`
4. See issue: very little contrast

**Expected behavior**
svg image should be seen clearly

**Screenshots**
![image](https://user-images.githubusercontent.com/830394/101684981-764c4e00-3a7c-11eb-97eb-0131fb7c8f4f.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome 87
 - Version TW 5.1.23pre

**Comment by kookma** [comment]
@BurningTreeC  - I will make a PR

**Comment by BurningTreeC** [comment]
The problem here is, that there's only the fill-rule on `body.tc-body` which applies here, and that is the `foreground-color` ... on a white / gray button the svg icon becomes invisible.

A solution would be to set

```
html button {
fill:<<colour button-foreground>>;
}
```

and define that properly for all palettes

**Comment by Jermolene** [comment]
> The problem here is, that there's only the fill-rule on `body.tc-body` which applies here, and that is the `foreground-color` ... on a white / gray button the svg icon becomes invisible.
> 
> A solution would be to set
> 
> ```
> html button {
> fill:<<colour button-foreground>>;
> }
> ```
> 
> and define that properly for all palettes

We already have `html button {color: <<colour button-foreground>>;}`, I think the lack of a declaration for the `fill` property was an oversight.

**Comment by kookma** [comment]
@BurningTreeC  - Thank you

**Comment by kookma** [comment]
@BurningTreeC  - Thank you for your solution hear. I have tested the three dark palettes

-Cupertino dark
-Gruvbox drak
- Nord

All of the have issue on buttons with `tc-btn-invisible` class

See my example test on https://tiddlywiki.com/prerelease/ below

```
<$button>{{$:/core/images/close-button}}</$button>
<$button class="tc-btn-invisible">{{$:/core/images/close-button}}</$button>
{{$:/core/images/close-button}}
```

**Screenshot**
![image](https://user-images.githubusercontent.com/830394/102255538-771f2d00-3f1f-11eb-803c-dbac4255ebdf.png)

I think the solution in https://github.com/Jermolene/TiddlyWiki5/pull/5250 caused the issue. If you remove `fill: <<colour button-foreground>>;` the button has very low contrast for svg enclosed in button and if you use `fill: <<colour button-foreground>>;` then the button with `tc-btn-invisible` has very low contrast for enclosed svg.

**Comment by BurningTreeC** [comment]
@kookma I'll prepare a fix this evening

**Comment by kookma** [comment]
@BurningTreeC , I tried to fix myself but no luck. Sorry for not being helpful anymore!
