### ISSUE TITLE
code block rendering broken in 5.0.8 and .9-pre

### ISSUE THREAD

**Issue by pmario** [Jermolene/TiddlyWiki5#525]
to reproduce:
copy the following code blcok into a tiddler
the first 3 blocks render well
the last 2 don't ... same problem with FF and Chrome

    <pre>adf sadföl </pre>

    <pre>
    adf sadföl 
    if (a == a) { asdf }
    </pre>

    ```
    multi
    line
    content
    ```

    paragraph 

    <pre>
    // long long long long long long long long long long long long long long long long long    long long long long line 

    var a, i;

    for (i=0; i < 10; i++) {
      a = 10;
    }
    </pre>

    ```
    // long long long long long long long long long long long long long long long long long long long long long line 

    var a, i;

    for (i=0; i < 10; i++) {
      a = 10;
    }
    ```

**Comment by foobilly** [comment]
@Jermolene

Does this also explain why the double-dash when wrapped in code tags gets converted to an emdash (as I believe it's called)?

<code>wget --version</code>

**Comment by Jermolene** [comment]
@foobilly yes, that's right. You'll need to use backticks to quote such pathnames.

You can also create plain text tiddlers which aren't wikified at all.

**Comment by tobibeer** [comment]
Is the op actually an issue and if yes, is the expected behavior for the contents of a pre to always be rendered as plain text?

**Comment by Jermolene** [comment]
It's not a bug. For it to work otherwise, the `<pre>` element would have to have special behaviour for parsing it's content differently. It would rather break the layering; the parser doesn't distinguish between different HTML tags.

> Would that be a problem for stylesheets wrapping things in <pre> for readability?

Stylesheet processing just takes the plain text output, ignoring the `<pre>` tags.

**Comment by tobibeer** [comment]
Ok, so is there anything to be done about the OP and if yes, what?

**Comment by Jermolene** [comment]
I don't think there's any fix for this. It's another gotcha, not a fixable bug.

**Comment by pmario** [comment]
IMO wontfix. So I'll close it.
