### ISSUE TITLE
 [Plugins Tab] Sort plugins by name in Plugins Tab

### ISSUE THREAD

**Issue by kookma** [Jermolene/TiddlyWiki5#5259]
Reference to https://github.com/Jermolene/TiddlyWiki5/discussions/5256#discussioncomment-194699

>I agree. The rationale for sorting by title was to keep plugins from a particular publisher together in the listings, which may not be an issue in practice.
> I couldn't discover how to convert this post into an issue, but I'll see what happens if I make a commit marked as fixing this post.

_Originally posted by @Jermolene in https://github.com/Jermolene/TiddlyWiki5/discussions/5256#discussioncomment-194699_

**Comment by Jermolene** [comment]
Fixed in 93309b0b7d376f61e4ae3a9fc7b2021db7eeb44c
