### ISSUE TITLE
[IDEA] Dropzone widget - honor deserializer for plain text pasted or dragged and dropped

### ISSUE THREAD

**Issue by kookma** [Jermolene/TiddlyWiki5#5261]
**Is your feature request related to a problem? Please describe.**
Bibtex importer plugin  honors the imported .bib file and not text. 

> [Springer in Google Forum](https://groups.google.com/g/tiddlywiki/c/Bn4ffIpe4B4/m/RhMrWSaGBQAJ): My workflow includes, for example, coming a cross a citation in google scholar, which I can display in bibtex format like so: 

```
@book{crary2016inside, 
    title={Inside ethics}, 
    author={Crary, Alice}, 
    year={2016}, 
   publisher={Harvard University Press} 
}
```
>I was hoping that dragging that text into Tiddlywiki would auto-populate the fields. Instead, I get an ordinary tiddler with a text field that looks exactly like the above block.

**Describe the solution you'd like**
Based on discussion on Google forum:  it seems if Bibtex importer honors pasted text it is possible to have special dropzone to import bibtex entry from sites like Google Scholar

Proposed by [Saq](https://groups.google.com/g/tiddlywiki/c/Bn4ffIpe4B4/m/8pVUFVubBQAJ)

```
<$dropzone deserializer="application/x-bibtex">

paste/drag bibtex here


</$dropzone>
```

**Comment by saqimtiaz** [comment]
@kookma thank you.

In general terms: the `deserializer` attribute of the `dropzone` widget is only honoured for files that are imported and not for text.

I propose that we try to [deserialize the text](https://github.com/Jermolene/TiddlyWiki5/blob/0911d99813f9123961116a08c136b157a72393bd/boot/boot.js#L1483) using the specified deserializer as well, falling back to treating it as plain text if necessary.

**Comment by saqimtiaz** [comment]
@kookma perhaps rename this issue to:

`Dropzone widget - honour deserializer for plain text pasted or dragged and dropped`

**Comment by kookma** [comment]
@saqimtiaz - done!

**Comment by saqimtiaz** [comment]
@kookma I think this can be closed now.

**Comment by kookma** [comment]
Thank @saqimtiaz. I will follow and would happy to help to add example to documentation!
