### ISSUE TITLE
[BUG] v5.1.23 FileSystemAdaptor no longer respects existing tiddler file names

### ISSUE THREAD

**Issue by flibbles** [Jermolene/TiddlyWiki5#5270]
I use NodeJS. On my server, I have several files which aren't named exactly as `$:/config/FileSystemPaths` would make them. In 5.1.22 and below, Tiddlywiki would respect the already existing name, but in v5.1.23, if I make any edits to the files, it will delete the old file and remake it how FileSystemPaths would make it.

If this isn't a bug, just let me know and I'll deal with it. I can see why this change would be made, but I'd like to know whether it is or not before I have to commit a bajillion file renames to my server's git history.

**Comment by joshuafontany** [comment]
Hi @flibbles - yes with 5.1.23 we are attempting to make sure the file-structure on disk always matches the current $:\config\FileSystemPath settings whenever a tiddler is saved to disk.

The workaround currently provided is that all tiddlers loaded via `tiddlywiki.files`  configs have thier boot-filepath saved & this is preferred over the tiddler-title if the "isEditableFile" flag is True in the `tiddlywiki.files` config. Thus, you have to make sure those files do not match any of the $:/config/FileSystemPath.

These files do not need to be in the "tiddlers/" directory of the wiki, but the`tiddlywiki.files`  config should be in a subdirectory of "tiddlers/". At this time, you have to define a config for each subdirectory in your `tiddlywiki.files`  config, as it does not autostart subdirectories.

Once defined as "externally loaded, editable" files, the new filesystem code will prefer the original path saved in the $:/config/OriginalTiddlerPaths tiddler.

Hope this helps,
Joshua F

**Comment by joshuafontany** [comment]
@flibbles Wait, I'm overlooking the simple option again.

Try this first, simply open your wiki's `tiddlywiki.info` file and add `"retain-original-tiddler-path" : true` to the root object, AND make sure the affected tiddlers to not match any $:/config/FileSystemPath filters.

**Comment by flibbles** [comment]
Ah. I didn't realize this was a direction Tiddlywiki was going. Seeing as how _all_ of my tiddlers are processed by FileSystemPath, I think the appropriate solution for me is to just let Tiddlywiki match files up the way it wants to. ...even if this means a plethora of `file_X` and `file_X.meta` files.

Thank you for clarifying this for me.

**Comment by joshuafontany** [comment]
@flibbles Ah, I thought that the `"retain-original-tiddler-path" : true` setting might work out for you, but the filesystem utils will not always write a *.meta file for non-standard tiddlers. Are you importing non-standard /non-text files (non *.tid/*.json)? Curious if you could share more of your setup.

**Comment by flibbles** [comment]
I have numerous dictionary files which the FileSystemPath will initially write down as `X` and `X.meta`, but I often compress them into `X.tid` with a type field. Or I may lightly altar a directory path  containing strange characters before I commit it to git.

For the `.meta` files, I should come to live with it. For the strange directory paths, I should probably just make my FileSystemPath filter make the changes I have been occasionally been making by hand over the last few years.

It's not so much a case of importing, as I'm more anal retentive about making my git history look super clean and tidy.

**Comment by joshuafontany** [comment]
Ah! You can force those files back to *.tid if you can match them with a filter in the (new for v5.1.23) `$:/config/FileSystemExtensions` tiddler, which takes a similar set of filters to `$:/config/FileSystemPaths`, but should always output an file-extention (complete with "."). ".tid" and ".json" have special handling to force those filetypes (where ".json" takes over if the tiddler has "bad-fields"):

https://tiddlywiki.com/prerelease/#Customising%20Tiddler%20File%20Naming
```
[!is[system]type[text/javascript]tag[.tid]then[.tid]]
[!is[system]prefix[tid/]then[.tid]]
```

**Comment by flibbles** [comment]
All sorts of interesting changes. I think between fiddling with my FileSystemPath file and this FileSystemExtensions one, I should be able to put everything back in its proper place.

Thank you. Much appreciated.

**Comment by kookma** [comment]
@joshuafontany - thank you for all your efforts.
I see the sync adapter and related stuffs to saving tiddlers and folders in TW 5.1.23 has improved in many ways.  The description in tw5.com is short and concise. It would be great to demonstrate these features through examples. So, I would highly recommend to have a page, blog or even use the Show and Tell in discussion board to introduce these new features to user community.
