### ISSUE TITLE
[BUG] Solar Flare Palette and CodeMirror editor: Incorrect background color for selected text

### ISSUE THREAD

**Issue by kookma** [Jermolene/TiddlyWiki5#5272]
**Describe the bug**
The background color of selected text in Codemirror editor with Solar Flare palette is incorrect or missed.

**To Reproduce**
1. Go to https://tiddlywiki.com/prerelease/
2. Set palette to Solar Flare
3. Create a tiddler
4. Put some text
5. Select the text ...
6. No background color is shown !

**Expected behavior**
Correct for background color of selected text

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome 87
 - Version TW 5.1.23pre

**Comment by BurningTreeC** [comment]
Hi @kookma - coincidentally the solar flare palette uses the same color for the tiddler-editor-background like the color used for the selection. I hadn't noticed that before. I'll have a look if there's a quick fix
