### ISSUE TITLE
[BUG] Railroad diagram for Filter Expression tiddler is out-of-date

### ISSUE THREAD

**Issue by rmunn** [Jermolene/TiddlyWiki5#5277]
**Describe the bug**
The railroad diagram shown in the Filter Expression tiddler currently shows the prefixes `+`, `~`, `-`, and `=`, but does not show any named prefixes. This doesn't have to block the 5.1.23 release as the documentation could be updated post release, but it's probably a good idea to update the railroad diagram before the release.

**Expected behavior**
I suggest adding a single entry marked "named prefix" with a colon in front to the diagram, rather than adding all the valid named prefixes in as separate possible choices. Otherwise the sheer number of valid named prefixes will make the list unwieldy, and the fact that named prefixes are extensible by plugins will make it likely that the diagram would miss a valid prefix anyway.

**Comment by pmario** [comment]
good catch!

**Comment by Jermolene** [comment]
Thanks @rmunn
