### ISSUE TITLE
can we move the TW2 edition into a tw2-testing branch - please!

### ISSUE THREAD

**Issue by pmario** [Jermolene/TiddlyWiki5#528]
If you do a "global search" for something in the TW5 source, most of the time you also get an equal number of hits in the TW2 source tree. ... eg: `template, tiddler, gettiddler, get... `

The TW2 edition is old / frozen, since imo it is only needed to test the TW5 build mechanism. ... 

I think we could remove the tw2 edition from the dev branch, if we create a `tw2-testing` branch. So if there is a problem with the TW2 build process, we just need to checkout the tw2-testing ... do a git merge master and we are good to go.

**Comment by tobibeer** [comment]
Instead of a branch, the tw2 repo should leverage use a basic TW5 install to build. Not?

**Comment by sukima** [comment]
If it is repo cruft then the resources for tw2 should be in an different repo.

**Comment by Jermolene** [comment]
Apologies, this was actually fixed a while ago, I think it's in 5.1.10.

But anyhow, the code was there as test data for the TW2 build process.
