### ISSUE TITLE
[IDEA] Create a production branch that always contains the latest release

### ISSUE THREAD

**Issue by inmysocks** [Jermolene/TiddlyWiki5#5299]
**Is your feature request related to a problem? Please describe.**

I have been working on automatic setup scripts for Bob and the secure server I am building and having a production branch that always pulls the latest release version will simplify the process.
Also it means updating tiddlywiki on node can just be `git pull` instead of having to pull and checkout the tag for the newest branch.

**Describe the solution you'd like**

Create a production branch and merge master into it whenever a new release is created.

**Describe alternatives you've considered**

I have used a script that finds the newest tag created and checking out that tag. It works but isn't as simple and could be broken if a non-release tag is created.

Also `npm install` has almost the same result.

**Additional context**

I think something like this has been discussed before. I don't remember the reasons it wasn't implemented

Using `npm install` isn't quite the same because that makes its more difficult to place new plugins (or themes, etc.) in the tiddlywiki plugins folder and use them without having to set environment variables.

**Comment by Jermolene** [comment]
Hi @inmysocks the branch `tiddlywiki-com` is always the latest release plus subsequent docs updates in the `editions/tw5.com` directory. Would that work for your purposes?

**Comment by inmysocks** [comment]
Yes, I missed that. That will work perfectly.
