### ISSUE TITLE
[IDEA] Lookup Operator extended to permit fieldnames

### ISSUE THREAD

**Issue by AnthonyMuscio** [Jermolene/TiddlyWiki5#5307]
**Is your feature request related to a problem? Please describe.**
Recent fix in Pre-release, perhaps appropriate time to add an additional feature.

**Describe the solution you'd like**
Allow the lookup operator to be given a fieldname so the value that is returned can be retrieved from fields other than text.

Another feature may be to allow the lookup to be forced to a shadows text or field values if one exists.

**Describe alternatives you've considered**
The can be achieved by other means but would extend the natural function of the lookup operator and provide simpler code

**Additional context**
- perhaps the new multi-parameter operator format could be used to name the field.
- Being able to alter the fieldname via a variable would help for advanced coding.
- I have a series of tools and ideas I plan to publish that would make use of this, the simpler the fundamental function the better.

**Comment by Jermolene** [comment]
Hi @AnthonyMuscio it makes sense to extend the `lookup` operator to be able to specify the target field that is used.

> Another feature may be to allow the lookup to be forced to a shadows text or field values if one exists

Can you expand on what you mean?

> perhaps the new multi-parameter operator format could be used to name the field.

I think you're referring the new capability for filter operators to have multiple operands.

**Comment by joshuafontany** [comment]
That is a really good idea. So good, I got it coded up today!

https://github.com/Jermolene/TiddlyWiki5/pull/5315

**Comment by AnthonyMuscio** [comment]
Joshua

Thank I look forward to seeing it.

Jeremy
If we use lookup and we may specify text or a field value I was wondering if we could use it to retrieve the original value in a shadow tiddler as well. This would be a way to retrieve the default value without all the shadow tiddler handling. In this case the lookup prefix may be $:/config/ fieldname and a shadow switch.

This would allow a single tiddler to contain many fields with different values. Changing one value will creat a tiddler, access to the shadow value for a given field allows the default to be retrieved from the shadow.

This feature would be useful for accessing plugin config tiddlers and large data plugins.

I am also developing an idea called ghost tiddlers which would make use of this.
