### ISSUE TITLE
[BUG] WidgetSubclassingMechanism fails for widgets that set event-handlers

### ISSUE THREAD

**Issue by rimi** [Jermolene/TiddlyWiki5#5308]
**Describe the bug**
When subclassing a widget which registers `eventHandlers` (e.g. `navigator, scrollable`) using the WidgetSubclassingMechanism (as described in https://tiddlywiki.com/dev/#WidgetSubclassingMechanism), one gets the error "this.eventListeners is undefined" because the underlying widget-constructor (which initializes the field) is called too late in the flow. 

**To Reproduce**
Create a widget-subclass (module-type: widget-subclass) implementation target to e.g. navigator like this:

```
(function(){
    /*jslint node: true, browser: true */
    /*global $tw: false */
    "use strict";
    exports.baseClass = "navigator";
    exports.name = "limited-stack-navigator";
    exports.constructor = function(parseTreeNode,options) {
        this.initialise(parseTreeNode,options);
    };
    exports.prototype = {};
    exports.prototype.handleNavigateEvent = function(event) {
        console.log("HANDLE");
        return false;
    };
})();
```
and restart the wiki. Exception-details appear in console.

**Expected behavior**
Navigator should be overwritten and navigate-event shouldn't be handled anymore. Instead a console.log stating "HANDLE" should appear.

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser Firefox
 - Version 84

**Comment by BurningTreeC** [comment]
I can confirm this bug. Subclassing the navigator widget seems not possible right now

**Comment by BurningTreeC** [comment]
@Jermolene - is there something we can do about this?

**Comment by Jermolene** [comment]
> @Jermolene - is there something we can do about this?

I did look at this briefly when @rimi first reported it (see https://groups.google.com/g/tiddlywikidev/c/YgKbeeklDnE/m/7EbIMevbAgAJ). The problem is simply that widgets shouldn't really do anything in their constructor other than calling `initialise(parseTreeNode,options);` because the constructor doesn't get called for subclasses. I think a sufficient fix should be to move those bits of code to the `render()` method.

**Comment by BurningTreeC** [comment]
@Jermolene @rimi - which are the affected widgets? I can create a PR for this

**Comment by saqimtiaz** [comment]
@BurningTreeC checking specifically for event listeners added in the constrcutor, grep says:

- linkcatcher
- fieldmangler
- navigator
- scrollable

There may be other widgets that have other logic in the constructor that should ideally also be moved.

**Comment by BurningTreeC** [comment]
Thanks @saqimtiaz ,

the widgets that add event-listeners in the constructor are indeed the ones you're listing

widgets that do other logic in the constructor are:

- edit-bitmap
- list
- vars
