### ISSUE TITLE
<h1> and <h2> are visually indistinguishable in the prerelease

### ISSUE THREAD

**Issue by Jermolene** [Jermolene/TiddlyWiki5#5311]
The font size of `<h1>` and `<h2>` are identical in the latest prerelease.

v5.1.23-prerelease:

![image](https://user-images.githubusercontent.com/174761/103030296-6e4bde00-4553-11eb-971b-6ba89d2f517a.png)

v5.1.22:

![image](https://user-images.githubusercontent.com/174761/103030323-799f0980-4553-11eb-968c-cb65fd79b4fa.png)

**Comment by kookma** [comment]
I can confirm this!

**Comment by twMat** [comment]
It seems the h1 styles are overwritten 

![image](https://user-images.githubusercontent.com/4534056/103043780-681f2700-457e-11eb-9ae5-aea1c18b1424.png)

**Comment by saqimtiaz** [comment]
I suspect the previous version of normalize.css specified a font-size for h1 but the new one does not. We may need to review the changes in the newer normalize.css to see what other elements are affected.

**Comment by Jermolene** [comment]
OK it turns out that the browser default behaviour is to make `<h1>`s slightly smaller if they are within an `<article>`, `<aside>`, `<nav>` or  `<section>` with the style rules quoted above by @twMat:

https://stackoverflow.com/a/26291186

And as @saqimtiaz points out, our old version of normalize.css did apply explicit sizes to headings.
