### ISSUE TITLE
[BUG] Trouble upgrading node.js TW5 to 5.1.23

### ISSUE THREAD

**Issue by adithya-badidey** [Jermolene/TiddlyWiki5#5322]
**Describe the bug**
I used `npm update -g tiddlywiki` to update TW5 to 5.1.23. `tiddlywiki --version` correctly outputs `5.1.23`. Then, if I run `tiddlywiki mywiki --listen`, I get this error
```
 syncer-server-filesystem: Dispatching 'save' task: $:/StoryList 
Serving on http://127.0.0.1:8080
(press ctrl-C to exit)
$:/plugins/tiddlywiki/filesystem/filesystemadaptor.js:103
			$tw.utils.cleanupTiddlerFiles(options, function(err){
			          ^

TypeError: $tw.utils.cleanupTiddlerFiles is not a function
    at $:/plugins/tiddlywiki/filesystem/filesystemadaptor.js:103:14
    at FSReqCallback.oncomplete (node:fs:179:23)
```

**Expected behavior**
Before the update, this command used to work as expected, i.e. the TW Server would start listening for connections on localhost:8080

**Desktop (please complete the following information):**
 - OS: MacOS Big Sur (11.1)
 - Node version 15.2.0

**Comment by saqimtiaz** [comment]
@adithya-badidey please check that `$:/plugins/tiddlywiki/filesystem/filesystemadaptor.js` does not exist in your `tiddlers` directory, that is as a tiddler.

Also try creating a new wiki and confirm if that starts properly.

**Comment by adithya-badidey** [comment]
Hi @saqimtiaz,
* `$:/plugins/tiddlywiki/filesystem/filesystemadaptor.js` and `$:/core/modules/utils/filesystem.js` do not exist in my tiddlers directory.
* A new wiki starts properly without issue.

**Comment by saqimtiaz** [comment]
@adithya-badidey it could also be in a subfolder like: 
`\tiddlers\$_\core\modules\utils`

**Comment by adithya-badidey** [comment]
There are no subfolders inside my tiddlers directory at all.

**Comment by saqimtiaz** [comment]
@joshuafontany any ideas? It almost sounds like a current version of the `filesystemadaptor` in use with an older version of `utils/filesystem`.

**Comment by adithya-badidey** [comment]
Also, if this helps: 
Everytime I run `tiddlywiki mywiki --listen`, new file like `$__StoryList_1.tid` is created with the number after `$__Storylist_` incremented. Now I am upto `$__StoryList_15.tid`.

Contents of `$__StoryList_1.tid` (and the rest) is just:
```
list: Homepage
title: $:/StoryList
```

**Comment by adithya-badidey** [comment]
@saqimtiaz I found the `$:/core/modules/utils/filesystem.js` tiddler inside a `$__core.json` file in the tiddlers directory. I deleted the `$__core.json` file (the `$__core.json.meta` said the version is 5.1.22 so I'm assuming it didnt get upgraded somehow.)

Things are working as expected now.

I can close this if nothing more is to be done for this.

**Comment by saqimtiaz** [comment]
@adithya-badidey right! So the entire $:/core plugin was somehow a tiddler. I wonder, did you convert this wiki from single file to node at some point? Otherwise at some point the $:/core plugin tiddler in your wiki got edited.

Anyway, this can be closed as that was the issue. You were still using the old core version because of the presence of that tiddler.

**Comment by adithya-badidey** [comment]
@saqimtiaz Thanks for the help! Closed. 

Can this problem be documented somewhere so others can find it easily?

**Comment by saqimtiaz** [comment]
@adithya-badidey under normal circumstances this should never happen.  Any attempt to edit $:/core should fail to save.

That is why I was curious if this wiki was converted from a single file version at some point.

**Comment by adithya-badidey** [comment]
Yes! It was converted from a single file. I forgot to mention that in the previous message. Thanks for the followup.

**Comment by saqimtiaz** [comment]
@adithya-badidey if you happen to remember how you performed that conversion, it will help identify why this happened and how it can be prevented in the future. Thank you.

**Comment by adithya-badidey** [comment]
@saqimtiaz The conversion was performed in v5.1.22. I think it was just `tiddlywiki mynewwiki --init server` followed by `tiddlywiki --load 'tiddly.html`. Not 100% sure.

**Comment by Jermolene** [comment]
> @saqimtiaz The conversion was performed in v5.1.22. I think it was just `tiddlywiki mynewwiki --init server` followed by `tiddlywiki --load 'tiddly.html`. Not 100% sure.

The correct procedure is to use the `--savewikifolder` command:

https://tiddlywiki.com/#SaveWikiFolderCommand
