### ISSUE TITLE
[BUG] etag is null

### ISSUE THREAD

**Issue by ericlathrop** [Jermolene/TiddlyWiki5#5328]
**Describe the bug**

Big red popup with this error message:

```
Internal JavaScript Error
Well, this is embarrassing. It is recommended that you restart TiddlyWiki by refreshing your browser
TypeError: etag is null
```

Also, changes to wiki do not save.

**To Reproduce**

1. Use firefox
2. Install [ClearURLs](https://addons.mozilla.org/en-US/firefox/addon/clearurls/?utm_source=addons.mozilla.org&utm_medium=referral&utm_content=search#&gid=1&pid=1) add-on, which filters `etag` headers for privacy reasons.
3. Open wiki with tiddlywebadaptor plugin
4. See error message

**Expected behavior**

The error popup should not show up, and changes should save.

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Browser Firefox
 - Version

**Additional context**

The exception happens at: https://github.com/Jermolene/TiddlyWiki5/blob/ac8f52130353dd5476599b979a8eea6abd8b3648/plugins/tiddlywiki/tiddlyweb/tiddlywebadaptor.js#L329 because the `etag` header is stripped.

Further, if someone were to add `if (!etag) { return null; }` to the top of `parseEtag`, then the code at https://github.com/Jermolene/TiddlyWiki5/blob/ac8f52130353dd5476599b979a8eea6abd8b3648/plugins/tiddlywiki/tiddlyweb/tiddlywebadaptor.js#L203-L204 would break because it's expecting an object instead of `null`.

**Comment by ericlathrop** [comment]
My workaround for now is to disable the `etag` filtering behavior of ClearURLs.

**Comment by pmario** [comment]
Hi Eric, I think your workaround is the way to go. 

It seems you are controlling the serverside. So if you don't use the etag to track user information, no one else does. 

The tiddlywebadaptor uses the etag to control data integrity. So it's not simple to remove it. ... How will you repalce it?

**Comment by ericlathrop** [comment]
I think that in case the etag is missing, the software should just handle it and not crash.

**Comment by Jermolene** [comment]
Thanks @ericlathrop 

> I think that in case the etag is missing, the software should just handle it and not crash.

Indeed! A "red screen of embarrassment" like this is a bug that needs fixing. I've applied a fix in e96a54c7531a2d9e07745e27d2015d8d7d09588f, let me know how it goes.

**Comment by tim-hub** [comment]
uh, I think I get this error again. 5.1.22 and 5.1.23


![image](https://user-images.githubusercontent.com/2884320/118337353-224e0580-b503-11eb-9f6c-1aacd66c69bc.png)

**Comment by tim-hub** [comment]
![image](https://user-images.githubusercontent.com/2884320/118338190-021f4600-b505-11eb-8c73-b40bf3834c69.png)
do  you have any ideas about it? @Jermolene 

thanks
