### ISSUE TITLE
server-external-js edition unable to save snapshot

### ISSUE THREAD

**Issue by fluxsmith** [Jermolene/TiddlyWiki5#5343]
The local html file produced when $:/plugins/tiddlywiki/tiddlyweb/syncer-actions/save-snapshot is run is corrupt.  Initially I had missed the documented instructions for populating $:/config/SaveWikiButton/Template with $:/core/save/all-external-js.  Without this it the file produced is unexpectedly small.  After adding the forgoing the file produced is the expected size, but shows no data when opened in a browser.

**Comment by saqimtiaz** [comment]
@fluxsmith which version of TiddlyWiki are you running?

**Comment by fluxsmith** [comment]
5.1.23

**Comment by Jermolene** [comment]
Thanks @fluxsmith do you have the external JS file in the right place for the saved HTML file to access it? Do you see any errors in the browser JabaScript console?
