### ISSUE TITLE
[BUG] Bullet/number list disapearing in HTML view after applying some customizations

### ISSUE THREAD

**Issue by offray** [Jermolene/TiddlyWiki5#5345]
**Describe the bug**
After applying some theme customizations now the Tiddlers that contain item/number list are shown with a space in front of each itemized list preserving list hierarchies but no actual number or bullet point is shown. 

**To Reproduce**
1. Go to https://mutabit.com/repos.fossil/offray-blog/uv/bliki/index.html#TiddlyWiki
2. Click on Tiddler pencil icon to see the source code. 
3. Source code is fine for nested bullet list, but no items/numbers characters are shown, only nested white space.

**Expected behavior**
Item/number character should be shown in HTML views.

**Screenshots**
![Not bullets/numbers only indented space](https://imgur.com/Gz06TNa.png)

![Source code and preview](https://imgur.com/s8MlkbD.png)

**Desktop (please complete the following information):**
 - OS: Gnu/Linux, Manjaro
 - Browser: All
 - Versions: TiddlyWIki 5.1.22,  TiddlyDesktop: 0.0.14

**Comment by saqimtiaz** [comment]
@offray this is **not** a bug. The problem is your CSS which sets `overflow:hidden` on the `ul` and `li` elements while using the default `list-style-position` value of `outside`.

Remove the `overflow:hidden` or use `list-style-position: inside;`

Please close this issue.

**Comment by offray** [comment]
Thanks @saqimtiaz .  The issue is presented when installing the [Mono theme support for](http://j.d.mono.tiddlyspot.com/#Hello%2C%20world) for the Griffmex dual story river plugin (linked there). I have been editing the `$:/themes/jd/Mono/Stylesheet/StoriesPluginCompatibility` trying to follow your advice but still bullet points are not shown.

I really enjoy the vibrant plugins ecosystem developed by TiddlyWiki now (coming back after almost 10 years without using it). But I think that most newcomers, like myself, are going to think that this behavior is not expected and because we are unable to detect which is the cause quickly, probably we are going to come to the TW main repository as a first place to look for support or orientation. So some questions to guide me in this new (for me) interaction with the community: 

* Where I should put the report? In the theme developers repository?  
* Is expected that plugins change some expected behavior like native markup rendering to the point where is not following TiddlyWiki's documentation normal? If this is not a bug, under which category should I file it?

**Comment by offray** [comment]
OK, I have found the proper file and it was `$:/themes/jd/Mono/Stylesheet` and now bullet list are working fine, but now long text is overflowing outside the Tiddler... ahh the joys of CSS. I think that I'm in the right path.

**Comment by offray** [comment]
I'm going with Drift[Drift](https://akhater.github.io/drift/)  for now as it has support for backlinks and renaming while addressing specifically the [issue with bullet list items in Mono Theme](https://akhater.github.io/drift/#FAQ). I lose the dual story river view of Stroll, but have the Mono theme with most of the properties I liked from Stroll.

Ummm... still thinking in the on-boarding experience as a new comer (again) to TiddlyWiki. Response times are pretty good, but I get the feeling that I was doing something wrong while trying my first interaction with the community, as Google Groups are not a good choice for many and GH discussions are only for developers and Issues are not a good place to ask questions and have a more conversational informal first contact with the broader TW community.... Well I imagine that I will contact the community in the Tiddleverse.
