### ISSUE TITLE
[BUG] Excessive server polling, $:/config/SyncPollingInterval not effective

### ISSUE THREAD

**Issue by fluxsmith** [Jermolene/TiddlyWiki5#5349]
A single browser open to my wiki is pulling approximately 7K from the server every minute, even with no user activity.  Based on limited documentation I found googling I created a tiddler named:
$:/config/SyncPollingInterval
containing text:
600000
(One more zero than default, expecting 10 minutes)
I restarted the node.js TiddlyWiki server, and it is still pulling 7K every minute.  Since I pay Amazon for traffic transferred, this is a concern.
The uri which is being pulled from the server every minute is:
/recipes/default/tiddlers.json?filter=[all[tiddlers]] -[[$:/isEncrypted]] -[prefix[$:/temp/]] -[prefix[$:/status/]] -[[$:/boot/boot.js]] -[[$:/boot/bootprefix.js]] -[[$:/library/sjcl.js]] -[[$:/core]]
I do not need multi-user updates, I would prefer a one-way sync putting changes to the server, and only pulling on initial load and explicit refresh.  Absent that, I would like to at least be in control of the polling interval.

**Comment by Arlen22** [comment]
That should be the correct tiddler and it should happen as you are expecting. Can you confirm that the text of that tiddler is included in the page upon load, as opposed to lazy loading? This could be one reason why it is doing that. Also, can you verify you are using v5.1.23?

**Comment by fluxsmith** [comment]
Good evening, thank you for responding.  Happy New Year!  I am using 5.1.23 installed just this week. In my page source I find:
```
<div created="20201231232919345" creator="jhl" modified="20210101010152384" modifier="jhl" tags="" title="$:/config/SyncPollingInterval" type="text/plain" revision="0" bag="default">
<pre>600000</pre>
</div>
```
I do not have a $:core/save/lazy tiddler.
In my access log I get this in exactly one minute intervals:
```
50.233.44.222 - - [01/Jan/2021:05:01:40 +0000] "GET /recipes/default/tiddlers.json?filter=%5Ball%5Btiddlers%5D%5D%20-%5B%5B%24%3A%2FisEncrypted%5D%5D%20-%5Bprefix%5B%24%3A%2Ftemp%2F%5D%5D%20-%5Bprefix%5B%24%3A%2Fstatus%2F%5D%5D%20-%5B%5B%24%3A%2Fboot%2Fboot.js%5D%5D%20-%5B%5B%24%3A%2Fboot%2Fbootprefix.js%5D%5D%20-%5B%5B%24%3A%2Flibrary%2Fsjcl.js%5D%5D%20-%5B%5B%24%3A%2Fcore%5D%5D HTTP/1.1" 200 7471 "https://wiki.fluxsmith.com/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.102 Safari/537.36 Edge/18.18363"
```

**Comment by fluxsmith** [comment]
I have to apologize for wasting your time.  Whatever is at 50.233.44.222 (it's at my workplace) is doing that poll despite my wiki no longer being open there.  I've blocked that IP address in iptables and have my wiki open from my home without any unexpected traffic.

**Comment by pmario** [comment]
see: https://www.whois.com/whois/50.233.44.222 .. may be you did share your URL address and anyone has the page still open in the browser
