### ISSUE TITLE
[Question] Sort by coalesced fields

### ISSUE THREAD

**Issue by fluxsmith** [Jermolene/TiddlyWiki5#5351]
Actually my first question would be where best to submit usage questions?  My apologies if here is inappropriate.

I'm working on my wiki's table of contents.  Some tiddlers have a title appropriate for the TOC and some I create a caption field to change the TOC.  Now my issue is the sort, conceptually (bad syntax) I want:
`sort[coalesce([caption], [title])]`
I haven't been able to find the syntax that would achieve this.

**Comment by pmario** [comment]
Hi, The best way for questions like this would be the google group: https://groups.google.com/g/tiddlywiki
anyway. 

At the moment, there is no way to achieve this with a sort criteria you mention. ... BUT 

You can use the "tag-dropdown" button, that is part of every tiddler that is tagged with the "parent" name. 
This dropdown supports drag&drop sorting. ... It will create a list field in the tag-tiddler, which defines the sort order. 

The list field will always overwrite the `sort[]` filter setting. So you can remove it. 

--------

The tag-macro can be used too: https://tiddlywiki.com/#tag%20Macro:%5B%5Btag%20Macro%5D%5D%20%5B%5Btag%20Macro%20(Examples)%5D%5D

-------------

A second possibility is: https://tiddlywiki.com/#list-links-draggable%20Macro:%5B%5Blist-links-draggable%20Macro%5D%5D%20%5B%5Blist-links-draggable%20Macro%20(Examples)%5D%5D

TW automatically uses the "tags" list-field to sort elements if there are some. So you can do the following as a workaround. 

```
<<list-links-draggable tiddler:"myTag">>
```

So if you have several tiddlers that are tagged: `myTag`, the list can be sorted using drag and drop now. 

BUT

Whenever you add an element it will be added at the end of the list. So you need to sort them again. 

IMO that's not optimal but it works.

**Comment by fluxsmith** [comment]
Thank you for responding, I'll try the google group for usage questions, something I'd read elsewhere had led me to believe it was 'retired'.
Your answer really helped me 'sort' out my TOC for now, but some kind of coalesce ability would sure be a nice enhancement that may have many useful applications, and would sure help here!

**Comment by fluxsmith** [comment]
I just reallized for my current need concatenation would also work.  Is there a fuctional equivelent of the invalid?:
`sort[concat([caption], [title])]`

**Comment by pmario** [comment]
no possibility atm

**Comment by fluxsmith** [comment]
Thank you.

**Comment by Jermolene** [comment]
> I just reallized for my current need concatenation would also work. Is there a fuctional equivelent of the invalid?:
> `sort[concat([caption], [title])]`

Hi @fluxsmith the new [subsort operator](https://tiddlywiki.com/#sortsub%20Operator) should be able to do what you want with a subsort filter like `[get[caption]else[]addsuffix{!!title}]`.
