### ISSUE TITLE
[BUG] Crash on Node.js with ActionSetField when type field is given a value upon new tiddler creation

### ISSUE THREAD

**Issue by xcazin** [Jermolene/TiddlyWiki5#5366]
When the ActionSetField widget is used on a missing tiddler, it usually creates it, then sets the provided fields to their requested values. In Node.js mode, it instead crashes when given an explicit value for the type field.

1. Start a Node.js instance of TiddlyWiki 5.1.23 in a terminal, like `node ~/src/TiddlyWiki5/tiddlywiki.js ~/wikis/100000000000000/ --verbose --listen port=10000 host=0.0.0.0 tls-key=../tls/key.pem tls-cert=../tls/server.crt`
2. Create a tiddler with the following content: `<$button><$action-setfield $tiddler="A probably missing tiddler" type="text/plain"/>Crash test</$button>`
4. Click on the button, and experience the crash in the terminal:
``` 
...
syncer-server-filesystem: Dispatching 'save' task: A probably missing tiddler 
internal/fs/utils.js:781
  throw new ERR_INVALID_ARG_TYPE(
  ^

TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received undefined
    at Object.writeFile (fs.js:1436:5)
    at Object.exports.saveTiddlerToFile ($:/core/modules/utils/filesystem.js:414:6)
    at $:/plugins/tiddlywiki/filesystem/filesystemadaptor.js:85:13
    at FileSystemAdaptor.getTiddlerFileInfo ($:/plugins/tiddlywiki/filesystem/filesystemadaptor.js:72:2)
    at FileSystemAdaptor.saveTiddler ($:/plugins/tiddlywiki/filesystem/filesystemadaptor.js:81:7)
    at SaveTiddlerTask.run ($:/core/modules/syncer.js:597:27)
    at Syncer.processTaskQueue ($:/core/modules/syncer.js:503:9)
    at Function.<anonymous> ($:/core/modules/syncer.js:90:9)
    at $tw.Wiki.exports.dispatchEvent ($:/core/modules/wiki.js:133:13)
    at $:/core/modules/wiki.js:166:10 {
  code: 'ERR_INVALID_ARG_TYPE'
}
...
```
FWIW, this has been tested with Node.js version v14.14.0 and v15.5.0

**Comment by Jermolene** [comment]
Thanks @xcazin is the use of HTTPS necessary for the problem to occur? I did find a slightly different bug, though: when I tried it with the usual HTTP configuration I found that a file called "A probably missing tiddler.txt" contains the string "undefined", and "A probably missing tiddler.txt.meta" contains the title, type, created and modified fields.

@joshuafontany would you be able to look at this?

**Comment by xcazin** [comment]
Hi @Jermolene indeed, when using HTTP instead of HTTPS, it crashes as well, but the tiddler is created and looks normal in the browser, although I can't find it anymore among the tiddlers server side. When the node instance is restarted, the sync causes the one in the browser to disappear.

**Comment by joshuafontany** [comment]
@Jermolene @xcazin I will take a look! I am currently debugging a callback-scope bug in the same callback chain that may be related, thanks for the bug report!

**Comment by joshuafontany** [comment]
Aaah, I see right where we are assuming each tiddler has a text field, but didn't trap for that being undefined if the tidder was created "programmatically"...

This also a removed an unknown variable from my debugging test. :) Fixes will be incoming. Thanks!

**Comment by joshuafontany** [comment]
Fixed with https://github.com/Jermolene/TiddlyWiki5/pull/5415
