### ISSUE TITLE
[BUG] It seems we are wasting time and memory

### ISSUE THREAD

**Issue by pmario** [Jermolene/TiddlyWiki5#5368]
Hi Jeremy,

Every tw JS module uses a structure like this: 

```
/*\
header info
\*/
(function(){

// code comes herer

})();
```

I did a little bit of debugging and I found this: 

![tw-internal-function-structure](https://user-images.githubusercontent.com/374655/103580078-d1d1f600-4ed9-11eb-96b0-43ce4cf99f3a.gif)

So we do have 1 closure to much. I think we are wasting time and memory here. 

@Jermolene @flibbles

**Comment by flibbles** [comment]
Oh yeah. They're completely useless. Even the first `(function() {` is worthless too. Technically, it prevents people from typing `return something` at some point in the module and thus preventing `exports` from being returned, but if you look at the boot code, we don't actually use that return value anyway.

Don't know about you guys, but I haven't bothered wrapping my modules in `(function(){` ever in Relink.

**Comment by flibbles** [comment]
Also, while we're on the topic of weird javascript conventions, what's the point of `/*global $tw: false */`?

As far as I can tell, it doesn't do anything. And like, what would it even do? Make $tw not defined in case the user wants to define their _own_ $tw variable? I mean, they can already. They'd just need to use `var`. The jslint stuff I kinda get, even though I don't know of any lint files _anywhere_.

**Comment by pmario** [comment]
`/*global $tw: false */` that's eslint instructions.

**Comment by pmario** [comment]
So we should probably remove both of them?

**Comment by Jermolene** [comment]
As I recall it, the anonymous function around JavaScript modules is to provide a context for "use strict". The inner anonymous function wrapped around each module by the `$tw.utils.evalGlobal()` was added later and does indeed appear to be unneeded. Generally, I think we were attempting to define a module format that would be resilient against later changes to the module implementation.

**Comment by pmario** [comment]
>The inner anonymous function wrapped around each module by the $tw.utils.evalGlobal() was added later and does indeed appear to be unneeded. 

I would keep this one, since it is a "protection" against problems that could come up with inexperienced 3rd party plugin authors. 

Monkey patching is still possible, so I think we should remove from all js-files. .. 

**The disadvantage** -- It will invalidate all existing PRs that change a core js file

**Comment by pmario** [comment]
>As I recall it, the anonymous function around JavaScript modules is to provide a context for "use strict". 

Is the "outer" `function(module,exports, ... ` not enough?

**Comment by Jermolene** [comment]
> Is the "outer" `function(module,exports, ... ` not enough?

Yes, but that sets up a dependency between our JS module format and the implementation we use to execute them, which I think makes things more brittle. The goal is for our JS module format to work in as many situations as possible, and for our module execution implementation to handle as many existing modules as possible.

**Comment by pmario** [comment]
Ahhh. .. OK now I do understand it. ... So if TW source code is "copy pasted" it should just work with other common "js-handlers".

If we copy/paste "some 3rd party code" it should "just work" ... Is that right? If yes we can close the issue

**Comment by Jermolene** [comment]
> Ahhh. .. OK now I do understand it. ... So if TW source code is "copy pasted" it should just work with other common "js-handlers".
> 
> If we copy/paste "some 3rd party code" it should "just work" ... Is that right? If yes we can close the issue

That was indeed the rationale, but it's still entirely possible that we could do better.

**Comment by pmario** [comment]
>Don't know about you guys, but I haven't bothered wrapping my modules in (function(){ ever in Relink.

I think, I'll remove mine too from my plugins. They cause problems with the indentation settings of VisualCode anyway. .. 

Closing this issue.

**Comment by nilslindemann** [comment]
_Jermolene said_

> As I recall it, the anonymous function around JavaScript modules is to provide a context for "use strict". 

Yes, [quote from MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Strict_mode#strict_mode_for_scripts):

> This syntax _(without [IIFE](https://developer.mozilla.org/en-US/docs/Glossary/IIFE))_ has a trap _(...)_: it isn't possible to blindly concatenate conflicting scripts. You can (...) take the approach of wrapping the entire contents of a script in a function and having that outer function use strict mode. This eliminates the concatenation problem _(...)_.

_pmario said_

> I would keep this one _(The IIFE added by [`$tw.utils.evalGlobal()`](https://github.com/Jermolene/TiddlyWiki5/blob/9caba544eb04f56ed772340a2d8767974b2617c9/boot/boot.js#L551))_, since it is a "protection" against problems that could come up with inexperienced 3rd party plugin authors.

That also makes sense.

Both IIEF's have their use case.

---

For the records, we could leave the inner IIFE (and the `"use strict";` statement) away ...

* [when inside classes](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Strict_mode#strict_mode_for_classes)
* [when using ES 2015 import syntax](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Strict_mode#strict_mode_for_modules)

... because then strict mode is enabled by default.

However, this affects Node.js:

* [Class syntax is supported since Node.js v4.3.2](https://stackoverflow.com/a/42073968/1658543) (so this is no big problem)
* [ES 2015 import/export syntax is supported since v13.2.0](https://stackoverflow.com/a/37132668/1658543)
* [Official Windows 7 support ended with v13.6.0](https://stackoverflow.com/a/64615875/1658543)

So, for example, my current setup (Win 7, Node v12.18.2) would not break when using class syntax, but it would when using ES 2015 import/export syntax.

Not speaking of older browsers.
