### ISSUE TITLE
[BUG] 5.1.23 says added support for SVG favicons, is it broken or how do we do it?

### ISSUE THREAD

**Issue by AnthonyMuscio** [Jermolene/TiddlyWiki5#5373]
**Describe the bug**
I have renamed an svg icon to $:/favicon.ico and it does not seem to work as I expected the change _added support for SVG favicons,_

**To Reproduce**
Do as in description above

**Expected behavior**
That the SVG would become the favicon and appear in the browser tab

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome (default Icon shows) FireFox (No icon shows)
 - Version latest

**Smartphone (please complete the following information):**
Not tested

**Additional context**
Perhaps it has a subtlety that needs to be documented. Including against the release note.

Regards
Tones

**Comment by joshuafontany** [comment]
Does that tiddler have `type: image/svg+xml` set? Or is it just a snippet of html/svg code w/ no type?

**Comment by twMat** [comment]
@AnthonyMuscio 
When I test it on tiddlywiki.com, i.e renaming one of the existing svg's there, it works fine. Win10, Chrome
Did you try it there?

**Comment by AnthonyMuscio** [comment]
twMat,

Testing on TiddlyWiki.com, Yes I did but only when I used the SVG images such as the international flags.

The largest number of SVG's in empty.html are of course the button images we use. So I assumed we could easily use one of these as the favicon. A quick and easy way to give TiddlyWiki an icon to tell the difference in the browser tabs.

I have however found this;
- Clone an existing icon svg tiddler and rename to $:/favicon.ico
- After the opening "svg tag" insert `xmlns="http://www.w3.org/2000/svg" `
- Set the tiddlers type to `image/svg+xml`
- It now works as a Favicon.

So Clearly the favicon method insists on this variation of the button image tiddlers to work.

- A quick test suggest if the above changes are applied to a standard icon image if renamed $:/favicon.ico they will work

So Going forward; Which is the best choice?

1. Document this extra step to use tiddler image icons as a favicon including [here](https://tiddlywiki.com/#Setting%20a%20favicon)
2. Change the favicon method somehow to display tiddler icons without modification 
3. Change all the image icons so they work if they are renamed to favicon

I also observed that the package of fontawesome svg icon tiddlers need the same treatment to operate as favicons.

Regards
Tones

**Comment by twMat** [comment]
@AnthonyMuscio - the steps you outline indicate that you are *not* using svg images somehow. I mean, your first bullet says to "clone an svg" but then your other bullets instructs to do things that, if it *is* an svg, then these actions are already part of the svg. E.g "set type" etc. So did you clone an svg or not? It seems not.

If you have an svg or tiddler that you think ought to work but doesn't, maybe you can attach or link to it here for testing purposes?

**Comment by AnthonyMuscio** [comment]
ywMat,

The distinction is on tiddlywiki.com clone any tiddler with the prefix $:/core/images and rename it to $:/favicon.ico it will not work as a favicon.

Now edit the new favicon and

-  insert xmlns="http://www.w3.org/2000/svg"
- Set the tiddlers type to image/svg+xml

And it will work as a favicon.

I have other svg's from various sources, some work without this change others do not.

Regards
Tony

**Comment by AnthonyMuscio** [comment]
So I have answered the OT, but ask what if anything we should do about it.

**Comment by Jermolene** [comment]
Hi @AnthonyMuscio this is actually an old favourite: there are two different ways that SVG is used:

* SVG images are free standing image files that behave somewhat like iframes: they are there own world, and can't inherit CSS properties etc from their surrounds
* SVG elements are fragments of SVG images that can be inserted directly into an HTML document. SVG elements are part of HTML and so they can inherit CSS properties etc from their surroundings

As you've discovered, SVG images have an XML name space declaration because they have to be valid XML files. SVG fragments don't have that declaration because they are actually XML embedded in HTML, a slightly different thing.

All of this is documented at https://tiddlywiki.com/#Using%20SVG but evidently the documentation isn't getting things across successfully because variations of this question crop up every few weeks. PRs for docs improvements gratefully received as usual.

**Comment by Jermolene** [comment]
I should add that the distinction isn't unique to TiddlyWiki, you'll find plenty of general web development articles about all of this too.

**Comment by NicolasPetton** [comment]
Should this issue be closed?

**Comment by Jermolene** [comment]
Thanks @NicolasPetton

**Comment by AnthonyMuscio** [comment]
I have being away as many may be at this time of year, especially in southern hemisphere summer. Jeremy's explanation solved it for me, I plan to submit an update to the documentation.
