### ISSUE TITLE
[BUG] $tw.utils.pushTop is inconsistent

### ISSUE THREAD

**Issue by flibbles** [Jermolene/TiddlyWiki5#5374]
I'm tooling around with my LinkedLists when I noticed a problem with $tw.utils.pushTop.
Check this browser console output:
```javascript
var array = ['item', 'item'];
$tw.utils.pushTop(array, ['X', 'item']);
// output: ['X', 'item']
// or rather ALL instances of 'item' were removed before the new one was added. now...

var array = ['item', 'item, 'item']
$tw.utils.pushTop(array, ['X','item]);
// output: ['item', 'item', 'X', 'item']
// only ONE instance of 'item' was removed before the new one was added.
```
This is because utils.pushTop is trying to do this optimization where if the given array is smaller than the input array, it'll iterate through the given array and look for corresponding values in the input array, which is the opposite of what it usually does. Take a look at it:
https://github.com/Jermolene/TiddlyWiki5/blob/e280f89ca5dc78ba384a3a1108c88bd1ff31f25c/boot/boot.js#L76-L109

My question is: What is LinkedList supposed to do? LinkedList (and soon-to-be-premiered memory-efficient LinkedList) does not have this inconsistency. It seems to me that pushTop was always intended to work on lists without duplicates. Thus removing duplicates would be preferred, except in nearly all cases (this array is larger than the input), pushTop has only ever removed a single instance. So it may be better to consistently only remove a single instance.

I _could_ make my LinkedList do both behaviors depending on whether the input is larger than the current size. I _could_. I'll throw up in my mouth a little when I write that weird-ass exception case, but I _could_.

**Comment by pmario** [comment]
I think your example arrays are wrong. In reality you don't start with `var array = ['item', 'item'];` because the `pushTop()` would already have removed the first item. 

So the test needs to be more like this:
 
```
var array = ['item'];
$tw.utils.pushTop(array, ['item']);
$tw.utils.pushTop(array, ['X']);
$tw.utils.pushTop(array, ['item']);
```

**Comment by flibbles** [comment]
That's assuming you've been using pushTop all along. The following filters would demonstrate that difference: `item =item [enlist[A item]]` and `item =item =item [enlist[A item]]` on a 23-prerelease build.

**Comment by flibbles** [comment]
Actually, even:
```
var array = [];
$tw.utils.pushTop(array, ['item', 'item']);
$tw.utils.pushTop(array, ['X', 'item']);
```
...would catch it, and it's strictly using pushTop.
```

**Comment by pmario** [comment]
See the comment. That's the way it was designed, as you said in the OP
```
/*
Push entries onto an array, removing them first if they already exist in the array
	array: array to modify (assumed to be free of duplicates)
	value: a single value to push or an array of values to push
*/
$tw.utils.pushTop = function(array,value) {
```

**Comment by flibbles** [comment]
Ah, I do see. So is this to assume the proper correction would be for LinkedList to remove all instances of an incoming item before pushing into the array? Because if so, that actually simplifies the code somewhat.

**Comment by pmario** [comment]
So there may be an oversight since the last changes to the pushTop() code was :https://github.com/Jermolene/TiddlyWiki5/commit/689e172e790973d148de94a083898cba6a68dc87

**Comment by pmario** [comment]
>Ah, I do see. So is this to assume the proper correction would be for LinkedList to remove all instances of an incoming item before pushing into the array? Because if so, that actually simplifies the code somewhat.

I don't think so. I think you found a consistency issue!

**Comment by pmario** [comment]
The issue was introduced with the possibility of https://tiddlywiki.com/#Dominant%20Append

**Comment by flibbles** [comment]
> So there may be an oversight since the last changes to the pushTop() code was :[689e172](https://github.com/Jermolene/TiddlyWiki5/commit/689e172e790973d148de94a083898cba6a68dc87)

Dunno if the oversight was introduced then. The "optimization" exists in both the old and new code.

I agree it is hard to trigger this issue without the dominant append prefix. I'd only ever done it before using filters I'd written myself. I suppose a decision just has to be made. Currently this problem doesn't show up because my LinkedList is installed, but if we'd like to address the silly behavior I was forced to replicate where only a single 'item' is removed if item is pushTopped, I wouldn't say no...

**Comment by flibbles** [comment]
Not to be a dickhole, because I know you already get it, but in futzing with #5376, I realized [lookup[]] is using push and not pushtop, so you can get this:
![Screen Shot 2021-01-07 at 1 10 28 PM](https://user-images.githubusercontent.com/205465/103928459-dbca4380-50e9-11eb-915c-f1722365cba4.png)
Which is practically a textbook use-case for [lookup[]]

**Comment by Jermolene** [comment]
Thanks @flibbles @pmario, I think that's correct: $tw.utils.pushTop() doesn't worry about any existing duplicates in the array.

**Comment by pmario** [comment]
>Thanks @flibbles @pmario, I think that's correct: $tw.utils.pushTop() doesn't worry about any existing duplicates in the array.

The problem is: It does know about "dedupe", but for only 1 of them, if the "surce" array contains duplicates already. See the OP

**Comment by Jermolene** [comment]
> > Thanks @flibbles @pmario, I think that's correct: $tw.utils.pushTop() doesn't worry about any existing duplicates in the array.
> 
> The problem is: It does know about "dedupe", but for only 1 of them, if the "surce" array contains duplicates already. See the OP

I think we're saying the same thing.
