### ISSUE TITLE
[BUG] html comments and preview pane: crash and memory problem

### ISSUE THREAD

**Issue by Alzacon** [Jermolene/TiddlyWiki5#5396]
**Describe the bug**
Many times rewriting html comments break something in tiddler preview pane. Its ocurrs to me when I comment and uncomment parts of the tiddler to check my changes. Then TW crashes and the process that runs TW begins to scale its memory consumption.

I tried cleaning up my code, but it keeps happening. The following example is the minimum I have found.

**To Reproduce**
1. Start a tiddler with preview pane actived and the following **4** lines :
```

-->
<!--
-->
```

2. If I try type, in the first line which is empty, the begin of comment tag `<!--` the crash happens

**Additional context**
I have only checked in the single file version in FF, Chrome and TiddlyDesktop

**Comment by Jermolene** [comment]
Thanks @Alzacon for the very clear report, it's good to have a simple test case to work on. I'll investigate.

**Comment by Jermolene** [comment]
It turns out that the bug can be triggered with the following snippet in the browser dev console:

```js
$tw.wiki.parseText(null,"abc\n-->\n<!--\n-->")
```

Fix upcoming.
