### ISSUE TITLE
evernote plugin has parsing/formatting errors

### ISSUE THREAD

**Issue by myfta** [Jermolene/TiddlyWiki5#5398]
When I import an enex file from Evernote (actually just a single note) I get a couple of errors.

**ITEM 1**
The Tiddler created includes the following at the top of the Tiddler, it is actally the header from the enex file:

```
<?xml version="1.0" encoding="UTF-8"?> <!DOCTYPE en-export SYSTEM "http://xml.evernote.com/pub/evernote-export2.dtd"> <![CDATA[<?xml version="1.0" encoding="UTF-8" ?> <!DOCTYPE en-note SYSTEM "http://xml.evernote.com/pub/enml2.dtd">
```

**ITEM 2**
My Evernote contains a table. When that is imported I get an extra row at the top of the table with the following tags appearing:

```
  </col></col></col>
```

These are part of the formatting in the enex file. The able does import but has thee extra tags above the top row.

**Comment by Jermolene** [comment]
Thanks @myfta. Would you be able to share a copy of the note?

**Comment by myfta** [comment]
Jeremy, here is a sample enex and a copy of the tid it creates.

It includes this at the top:
<?xml version="1.0" encoding="UTF-8"?> <!DOCTYPE en-export SYSTEM "http://xml.evernote.com/pub/evernote-export2.dtd"> <![CDATA[<?xml version="1.0" encoding="UTF-8"?> <!DOCTYPE en-note SYSTEM "http://xml.evernote.com/pub/enml2.dtd">

and this at the end of the note:
]]>20210113T102926Z20210113T103112ZGraham Warddesktop.win</source>evernote.win32

Thanks,
Graham
[enex.zip](https://github.com/Jermolene/TiddlyWiki5/files/5808073/enex.zip)

**Comment by rmunn** [comment]
@myfta - It looks like some of the XML tags you included in your issue report may have been swallowed by GitHub because they looked like HTML tags. If you're going to quote XML in a GitHub issue comment, you need to surround it with backticks first. E.g., if you write this:

```
Here is some <random> tag.
```

Then it comes out looking like this:

Here is some <random> tag.

But if you write this:

```
Here is some `<random>` tag.
```

Then it comes out looking like this:

Here is some `<random>` tag.

So surround your `<xml>` tags with backtick characters and it will be visible. The Preview tab at the top of the comment box is very useful for making sure that your tags didn't get swallowed, and that what you wrote is going to come out looking like you wanted it to look.

**Comment by myfta** [comment]
Thank you, I guessed it was something like that and had tried the \ , but of course, it did not quite fix it.

Thanks.

**Comment by Jermolene** [comment]
> Jeremy, here is a sample enex and a copy of the tid it creates.

https://tiddlywiki.com/ has the Evernote plugin loaded so I dragged the `.enex` file into it and got different results.

The tiddler looks OK:

<img width="629" alt="image" src="https://user-images.githubusercontent.com/174761/104723997-faeb5580-5727-11eb-839a-5765b00daedc.png">

The content looks like this with a type of 'text/html' (yours has the type `application/enex+xml`):

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE en-note SYSTEM "http://xml.evernote.com/pub/enml2.dtd">

<en-note><div><div><br/></div><table style="border-collapse: collapse; min-width: 100%;"><colgroup><col style="width: 130px;"/><col style="width: 130px;"/><col style="width: 130px;"/></colgroup><tbody><tr><td style="width: 130px; padding: 8px; border: 1px solid;"><div>Head 1</div></td><td style="width: 130px; padding: 8px; border: 1px solid;"><div>Head 2</div></td><td style="width: 130px; padding: 8px; border: 1px solid;"><div>Head 3</div></td></tr><tr><td style="width: 130px; padding: 8px; border: 1px solid;"><div>r1c1</div></td><td style="width: 130px; padding: 8px; border: 1px solid;"><div>r1c2</div></td><td style="width: 130px; padding: 8px; border: 1px solid;"><div>r1c3</div></td></tr><tr><td style="width: 130px; padding: 8px; border: 1px solid;"><div>r2c1</div></td><td style="width: 130px; padding: 8px; border: 1px solid;"><div>r2c2</div></td><td style="width: 130px; padding: 8px; border: 1px solid;"><div>r2c3</div></td></tr><tr><td style="width: 130px; padding: 8px; border: 1px solid;"><div>r3c1</div></td><td style="width: 130px; padding: 8px; border: 1px solid;"><div>r3c2</div></td><td style="width: 130px; padding: 8px; border: 1px solid;"><div>r3c3</div></td></tr></tbody></table><div><br/></div></div><div><br/></div></en-note>
```

I wonder if you could try your file on https://tiddlywiki.com to see what results you get, and then we can investigate from there.

**Comment by myfta** [comment]
That's interesting. If I import directly into [https://tiddlywiki.com/](https://tiddlywiki.com/) I get the same result as you. When it imports it also creates a second tiddler "Evernote Import Report".

Now if I download empty.html from the 5.1.23 homepage, and import into that I get the error. So it feels like there is something missing from empty.html?

![image](https://user-images.githubusercontent.com/47277622/104742300-2a0ec080-5742-11eb-85d4-abd287c90eb2.png)

**Comment by saqimtiaz** [comment]
That would be the Evernote migration tools plugin. Install via Control Panel -> Get more plugins.

**Comment by myfta** [comment]
Thank you. I had missed that the additional plugins needed installing. Is that the case with all of them?

**Comment by saqimtiaz** [comment]
If it isn't in the list of installed plugins, it needs to be installed:

![image](https://user-images.githubusercontent.com/68092/104751368-97781c80-5755-11eb-88fa-1e313b39435f.png)
