### ISSUE TITLE
[IDEA] LinkedList.toArray() might be more efficient by pre-allocating array size

### ISSUE THREAD

**Issue by rmunn** [Jermolene/TiddlyWiki5#5437]
**Is your feature request related to a problem? Please describe.**
I was reading through the new LinkedList implementation in https://github.com/Jermolene/TiddlyWiki5/pull/5380 and noticed that in the `.toArray()` method of LinkedList, it creates an empty array with `var output = []` and then repeatedly calls `output.push()`. However, since the length of the LinkedList is known at that point, it might be faster to pre-allocate the output array by creating it with the `Array(length)` constructor: `var output = new Array(this.length)`. The Array(length) constructor is [supported in all browsers](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/Array). Its performance will vary from browser to browser depending on the browser's implementation of Javascript, but in general it should be more efficient to pre-allocate the array if the array is large. For example, in V8 (the most widely-used Javascript engine), when you create an empty array with `[]` it's created with a capacity of 4, and every time a `push()` happens on a full array, a new array is allocated with new capacity = (old capacity * 2) + 16. So when you push the fifth item, a new array is created of size 24 and four items are copied into it. When you push the twenty-fifth item, a new array is created of size 64 and 24 items are copied into it. So the larger the output array is, the more time will be saved by pre-allocating. (And space saved, too: if you have 32 items in the linked list, it will end up creating and throwing away arrays of size 4 and 24, and then creating an array of size 64 to store those 32 items).

**However**, there's a caveat. Depending on what happens to the array *after* LinkedList.toArray() has been called, it may not be more efficient to pre-allocate. Specifically, if the array is going to have more items pushed into it later, then pre-allocating will guarantee that the array will be at capacity, and therefore the next push() will end up having to copy all the array's items. I have not yet read through the TW filter code to see when the arrays returned from LinkedList.toArray() will end up having more items pushed into them later or not. If it turns that the result of `toArray()` is usually used unchanged, then pre-allocating the output array should save both time and memory.

**Describe the solution you'd like**
After a code review of the TW filter functions, change `var output = []` in LinkedList.toArray() to be `var output = new Array(this.length)` instead, **if and only if** the TW filter functions rarely do a push() on the result of LinkedList.toArray().

Also, a performance test should be run to measure the impact of this change: **never** assume that something that "should" give better performance actually **will** give better performance until you've actually measured it. Ideally this performance test should happen in multiple browsers that use different Javascript engines; Chrome (V8 engine), Firefox (Spidermonkey engine), and Safari (JavaScriptCore engine). MS Edge used to use its own engine, but with their latest release they've switched to using the V8 engine so the performance on Edge should be the same as on Chrome. I don't have experience running JS performance tests on multiple browsers, so I'm not really able to implement my suggestion.

**Describe alternatives you've considered**
The alternative would be to leave the code as-is. If it turns out that for whatever reason, pre-allocating the output array in LinkedList.toArray() produces poorer performance, then it leaving the code as-is is the best option.

**Comment by rmunn** [comment]
Tagging @flibbles for comment on this.

**Comment by flibbles** [comment]
I'd be absolutely up for making a change like this if it improves performance, especially since it'd be self contained to a single method. I happen to know that the arrays returned by toArray are usually only iterated once and then discarded.

The reason I didn't bother with such an improvement is because it's my (vague) understanding that while `new Array(length)` is supported by nearly all browsers, many of them don't do any actual memory pre-allocation. They just set the length value.

I may absolutely be wrong about this. And I agree that speed tests will decide all. Frankly, I can't imagine using `new Array(length)` would be any _slower_.

**Comment by rmunn** [comment]
So far I've only looked at the source code for V8. If I've understood it correctly (it's rather complex as they have a lot of special-case code, such as handling arrays of small integers super-efficiently via special code paths), then it *does* preallocate arrays when the Array(length) constructor is used. So even if all other browsers did not do any pre-allocation, a performance win for V8 that is neutral on all other browsers would be a win, especially since the code change is small and very easy to understand,

**Comment by pmario** [comment]
There are other browser engines too. So we should only change something if it's a win for _all_ of them.

**Comment by rmunn** [comment]
> There are other browser engines too. So we should only change something if it's a win for _all_ of them.

If you meant "If it's a win *or neutral* for all of them", then I would agree. (With the caveat that I'd be willing to accept a minor performance loss on little-used browsers if it meant a performance gain on major browsers). But if you meant "if it's neutral (no measurable gain or loss) on some browsers then we shouldn't do it" then I can't agree with that. If it's a simple change (as this one is), and it produces gains on some browsers and losses on none, then it's obvious that it should be done.

**Comment by pmario** [comment]
I meant, I'd like to see the numbers first. If we are not able to measure the "status quo", we can't see any improvements.

**Comment by flibbles** [comment]
Got bored tonight, wrote this method and tested its speed using Tiddlywiki's built in performance class
```javascript
$tw.utils.linkedCount = function(depth) {
    var list = new $tw.utils.LinkedList();
    for (var i = 0; i < depth; i++) {
        var a = list.toArray();
        list.push(a.length.toString());
    }
    return list.toArray();
}
```
Here are the two implementations of toArray:
```javascript
LinkedList.prototype.toArray = function() {
    var output = []; 
    this.each(function(value) { output.push(value); });
    return output;
};
```
and
```javascript
LinkedList.prototype.toArray = function() {
    var output = new Array(this.length),
        index = 0;
    this.each(function(value) { output[index++] = value; });
    return output;
};
```
Depth at 10,000; Ran it 3-4 times per setup. All measurements in milliseconds.
```
Node.JS v15.5.1
	push
		2244, 1260, 1532, 1310
	preallocate
		1017, 1070, 996

Chrome v87
	push
		1228, 1361, 1050, 1387
	preallocate
		1048, 1220, 992

Safari v12
	push
		7412, 8222, 4090, 8074
	preallocate
		6826, 8180, 8091, 3620

Firefox v84
	push
		2157, 1987, 1947
	preallocate
		1819, 1785, 1796
```

The only thing I can definitively say about this is that Safari is super slow. Otherwise, the preallocation seems to help Node.JS out a little. Slightly for Chrome too. Firefox and Safari seems like a wash. I don't have a windows, so I couldn't test IE or edge.

I'd be up for the change. I'm not sure it'll make a sizeable difference with TW performance, but these things add up.

**Comment by rmunn** [comment]
Thanks for the perf numbers; https://jsperf.com/ has been giving me 502 Bad Gateway errors for the past several days so I haven't been able to use it, and I'm not yet familiar with TW's built-in perf measurements. (Speaking of which, why do your results sometimes have only three numbers listed for preallocate when push has four?) I wonder what's going on with Safari in that third test where push was significantly faster all of a sudden (dropping down to 4090 when the other tests had 8222 and 8074), and in the fourth test where this time it's preallocate that dropped to 3620. I feel like the Safari numbers are too inconsistent to be trustworthy and a lot more re-runs are needed on Safari. The others look like 5-10% improvements across the board, including Firefox (I don't quite see why you think Firefox is a wash as its percentage improvements look similar to Chrome/Node.js to me), so that's nice.

**Comment by Jermolene** [comment]
Thanks @rmunn @flibbles @pmario preallocating the array to the correct length seems like a fairly platform agnostic way of giving an opportunity for optimisation, so i'd support this change.

**Comment by flibbles** [comment]
This can be closed now.

**Comment by rmunn** [comment]
Closing as this has been implemented.
