### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by peteasa** [Jermolene/TiddlyWiki5#5441]
**Describe the bug**
WebDav save support with apache2 fails on PUT.  

WebDav PUT is working with cadaver so file system has correct permissions:
cadaver http://localhost/tw5
dav:/tw5/> put freddy.txt
Uploading freddy.txt to `/tw5/freddy.txt':
Progress: [=============================>] 100.0% of 6 bytes succeeded.

Using tiddlywiki v5.1.23 save you get an error popup "Error when saving File changed on server"

PUT | http://localhost/tw5/megawikitest.html
-- | --
Status412
Precondition Failed
VersionHTTP/1.1
Transferred535 B (308 B size)
Referrer Policy no-referrer-when-downgrade

**To Reproduce**
1. Load from WebDav apache2 server
2. Attampt to Save the tiddlywiki
3. you see the error.

**Expected behavior**
Saving works ok with nginx.. you load from the WebDav nginx server.. and saving works ok

**Desktop (please complete the following information):**
 - Ubuntu 18.04.5
 - Browser chrome and firefox
 - Version Firefox 84.0.2 (64-bit)
Server version: Apache/2.4.29 (Ubuntu)
Server built:   2020-08-12T21:33:25

DavLockDB ${APACHE_LOCK_DIR}

<Directory /home1/webdav/tw5>
    Options Indexes FollowSymLinks MultiViews
    AllowOverride None
    Order allow,deny
    Allow from all
    Satisfy Any
</Directory>

Alias /tw5 /home1/webdav/tw5
<Location "/tw5">
    DAV On
</Location>

**Comment by pmario** [comment]
There's probably a problem with ETAG handling. 

see: https://groups.google.com/g/tiddlywiki/c/a3Ihi9W2hlk/m/jVgJi_7ZAQAJ  

and all convesations at: https://groups.google.com/g/tiddlywiki/c/kBfqChfLnRk if the first one doesn't help

**Comment by pmario** [comment]
As we did test the default webdav saver I did use a docker image https://github.com/pmario/docker-webdav-apache wihch did work. So the settings used there may help you

**Comment by peteasa** [comment]
ok thanks

**Comment by pmario** [comment]
@peteasa ... Did it work out for you???. Otherwise there would be no reason to close the issue.

**Comment by peteasa** [comment]
I have a solution with nginx.  
The problem is highly likely to be a configuration issue or apache2 issue.
As you have tested it in a docker container with apache2 and it works then it is highly likely to be a configuration problem.  It may take me some time to get my old machine with apache2 fixed so rather than leave this possibly none-issue open for a long time I took the decision to close it.
