### ISSUE TITLE
[IDEA] Pls let us rename `$tw.utils.count(tiddler)` to eg: `$tw.utils.cntObjectKeys(xxxx)`

### ISSUE THREAD

**Issue by pmario** [Jermolene/TiddlyWiki5#5466]
I would like to rename the `$tw.utils.count(tiddler)` function  to something like `$tw.utils.cntObjectKeys(xxxx)` or `$tw.utils.countObjKeys()`

It's defined at:

https://github.com/Jermolene/TiddlyWiki5/blob/12f18474755c94362eef7191eafb532bafb743b1/core/modules/utils/utils.js#L187-L192

The function call `$tw.utils.count(tiddler)` is absolutely misleading, to what the function actually does.

I can create a PR that fixes the TW-core, which uses the call 10 times. 

We can keep the $tw.utils.count(tiddler) signature for compatibility reasons, but add a "deprecated" warning for plugin authors. 

So the PR will be backwards compatible, but from now on we can use a function that tells us, what it does. eg `$tw.utils.countObjKeys`  ... <- I personally prefer this one

**Comment by pmario** [comment]
@Jermolene what do you think?

**Comment by Jermolene** [comment]
Thanks @pmario. I agree that the name of the `$tw.utils.count()` method is not self-explanatory. `countObjectKeys()` is definitely better, at the expense of being longer.

But I'm not sure that it's worth retrospectively fixing such things. Whether a name is self-explanatory is somewhat subjective, so I'm not sure where we'd end.

**Comment by pmario** [comment]
With my bundler plugin I'm adding custom "upgraders", import-hooks and the import handling as a whole. .. I was searching for the mechanism, that tells me how to calculate the rule, if a tiddler is selected or not. 

I'm not exactly sure how often I did "ran over" [this line](https://github.com/Jermolene/TiddlyWiki5/blob/9f9ce6595b08032a602981f82940ca113cff8211/core/modules/widgets/navigator.js#L530), because I did completely misinterpreting its function. 

Even reading the comment I did go on searching for the text "selection" in the project to find the place "how" it is calculated, because I couldn't understand the algorithm that calculates the stat. 

Even single stepping the code didn't help, since I didn't "step into" the function ... I used "step over all the time". 

I just want to say: I wasted a lot of time, that's why I did create the PR

**Comment by Jermolene** [comment]
Indeed, @pmario I can readily imagine how the confusion arose. But really the problem here could be said to be that you had assumed that you understood what the method did without referring to its source. Those kinds of perfectly understandable assumptions are difficult to anticipate.

**Comment by pmario** [comment]
:) ok I'll close this issue in favour of 1 line of comments in: "Add th-before-importing hook mechanism #5464"
