### ISSUE TITLE
Use semantically meaningful content-type for JSON tiddlers

### ISSUE THREAD

**Issue by Jermolene** [Jermolene/TiddlyWiki5#551]
All JSON tiddlers currently get the content type `application/json`. It has been suggested that external tooling might be simpler if an application specific content type were used.

For example, plugin tiddlers could have the type `application/vnd.tiddlywiki-plugin+json`.

JSON tiddlers that might be candidates include:
- Plugins
- Navigation History
- Cecily Map

See the original discussion here:

https://groups.google.com/d/topic/tiddlywikidev/jjha5iXYFo4/discussion

One concern is that this approach might become impractical if every `application/blah+json` content type had to be pre-registered in the boot kernel. That implies that we should be able identify JSON tiddlers by the `+json` portion of the content type, rather than by looking at the entire content type.

**Comment by pmario** [comment]
@Jermolene -- I think we can close this one. 

IMO it does not make sense to invent our own mime-types, if there are well defined ones. 

We do not have the man-power to maintain any documentation about our custom types, that others could use to implement TW-specific stuff. Using the existing types and their documentation make much more sense.

**Comment by Jermolene** [comment]
Thanks @pmario
