### ISSUE TITLE
[BUG] Not responsive default theme now (but then yes)

### ISSUE THREAD

**Issue by somenxavier** [Jermolene/TiddlyWiki5#5517]
I have the browser width and height dimensions in 912 x 917
Then when I load tiddlywiki empty.html the sidebar menu was on the right, but now it is on the top (I attach the screen capture).

How can I do for put on the right again?
Why tiddlywiki is now not responsive?

Can you please, trick the theme to be 100% responsive theme?
[mozilla.pdf](https://github.com/Jermolene/TiddlyWiki5/files/6056532/mozilla.pdf)

**Comment by Jermolene** [comment]
Hi @somenxavier the design is already intended to be responsive; that is why the sidebar moves above the story river when the screen becomes too narrow to accommodate it to the side.

You can adjust the window size that triggers the layout change in control panel -> appearance -> theme tweaks:

![FD57E583-DA16-483B-BEBE-38B3C89D5370](https://user-images.githubusercontent.com/174761/109414534-39249780-79ab-11eb-9237-da661ff9892e.jpeg)

**Comment by somenxavier** [comment]
Thanks a lot, @Jermolene . I will try myself to adjust the parameter.
But why not is not responsive and in the begginning yes? A mystery ;-)

**Comment by Jermolene** [comment]
> Thanks a lot, @Jermolene . I will try myself to adjust the parameter.
> But why not is not responsive and in the begginning yes? A mystery ;-)

I'm not sure what you mean. The design is responsive: the layout changes as the window width changes. It sounds like you think that the breakpoint should be at a different position, but 960px is a standard breakpoint size to use for fairly good reasons.

**Comment by somenxavier** [comment]
Yes. It's true. Thanks for the trick.
Previously, I change `960px` with equivalent `em` width.
