### ISSUE TITLE
[BUG] Settings tab and third party plugins

### ISSUE THREAD

**Issue by kookma** [Jermolene/TiddlyWiki5#5520]
**Describe the bug**
Several of kookma plugins use a Settings tab appears in $:/ControlPanel / Settings. It is desired to see these setting pages side by side of Tiddlywiki settings.

Unfortunately it seems this does not happen until you first install the CodeMirror plugin. CodeMirror overwrite the core tiddler [$:/core/ui/ControlPanel/Settings](https://tiddlywiki.com/#%24%3A%2Fcore%2Fui%2FControlPanel%2FSettings). If you install third party plugins with Settings page after you have installed CodeMirror then you see the Setting Pages!

**To Reproduce**
1. Go to https://tiddlywiki.com/
2. Install a third part plugin with Settings page e.g [TW-Vote](https://kookma.github.io/TW-Vote/#%24%3A%2Fplugins%2Fkookma%2Fvote)
3. Open $:/ControlPanel and then setings
4. You do not see Vote settings page  (see image 1)
5. Now install CodeMirror and you see the Settings tab (see image 2)

**Expected behavior**
The official TW shall support adding Settings tab from third party plugin. It seems $:/core/ui/ControlPanel/Settings needs to be revised and also prevent CodeMirror plugin overwriting shadow tiddler.

**Screenshots**

## Fig 1.  What you get if use empty.html with no codemirror plugin
![258_chrome](https://user-images.githubusercontent.com/830394/109608105-96048700-7b3e-11eb-8611-024dd5a629b7.png)

## Fig 2. Expected behaviour
![image](https://user-images.githubusercontent.com/830394/109608520-3fe41380-7b3f-11eb-8fd4-f16bb532529b.png)

**TiddlyWiki Configuration (please complete the following information):**
 - Version [e.g. v5.1.24]
 - Saving mechanism [e.g. Node.js, TiddlyDesktop, TiddlyHost etc]
 - Plugins installed [e.g. Freelinks, TiddlyMap]
 
**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome 89
 - Version TW 5.1.23 and 5.1.24p

**Comment by kookma** [comment]
Hi @Jermolene - what do you think?
Should I make PR!

**Comment by kookma** [comment]
Hi @pmario 
What do you think about the above idea? I think you are the author and maintainer behind CodeMirror plugin!

**Comment by Jermolene** [comment]
Hi @kookma thanks for your patience. I didn't look closely enough at the original PR containing that modification to the control panel, and would not have merged it if I had realised what it was doing. I'd be happy to see it fixed.

However, we may want to consider using tags instead of tabs. The reason is that even just with TiddlyWiki's core settings we've got an overwhelming list of settings, and it would be good to provide ways to more easily navigate the list.

Another enhancement I'd be interested in adding at the same time is a search box at the top of the listing for searching for settings. This would actually be quite tricky because the translation mechanism means that the $:/tags/ControlPanel/Settings tiddlers don't necessarily contain searchable text.

**Comment by kookma** [comment]
Hi @Jermolene 
Many thanks for your reply!


> However, we may want to consider using tags instead of tabs.

Quite true!
 When you have many plugins installed which have settings/controls, this will make the settings tab quite lengthy and big tiddler! What CodeMirror uses is a new tag `$:/tags/ControlPanel/SettingsTab` and it also overwrites the core tiddler tab: `$:/core/ui/ControlPanel/Settings`!

My proposal was to use the CodeMirror solution! This is backward compatible as all old plugins/wikis still have access to `$:/core/ui/ControlPanel/Settings/TiddlyWiki` to add their settings to the bottom of that tiddler, and new plugins can use the `$:/tags/ControlPanel/SettingsTab` to add their own settings/configurations!

As I understood you prefer the old method adding a new section at the bottom of Settings tab for each new plugin uses settings configuration (e.g. using the `$:/tags/ControlPanel/Settings`)?

> Another enhancement I'd be interested in adding at the same time is a search box at the top of the listing for searching for settings.

I think @saqimtiaz has developed some ui here and that would be very useful to simply find the desired setting!

**Comment by pmario** [comment]
For some of my plugins, that have a lot of settings I add a new tab at the top level of the ControlPanel as seen in the screenshot below. I think users deserve easy access. 

![grafik](https://user-images.githubusercontent.com/374655/150694404-4157ad3d-cf28-4528-ad78-3af681da6314.png)

My "Link to Tabs" plugin adds some settings to the core Settings tab, where it is hard to find and imo only adds to the mess there. From my point of view the Settings tab is long overdue to a redesign. 

I'll probably give all my plugins with settings their own tab. I don't care if there are 20 or more tabs at the top level, if they are easy to access and if it's clear where they come from. ... It would be possible to add a link to every new tab, which tells the user which plugin installs this new ConfigPanel tab. 

As shown below, the default settings tab is a mess and IMO shouldn't be used by plugins at all.

![grafik](https://user-images.githubusercontent.com/374655/150694673-07a370e0-0a6b-4717-affe-3d25146ef84f.png)

**Comment by Jermolene** [comment]
Hi @kookma @pmario apologies for the confusion. Let me try to explain my counter proposal in different language.

I'm suggesting that we add an optional "keywords" field to tiddlers tagged `$:/tags/ControlPanel/SettingsTab`. At the top of the settings tab we'd display a pick list of the keywords as mini-pseudo tag pills. Clicking one of them would filter the list to just show settings with that keyword.

The advantage of the approach is that we can classify settings according to their area or usage, instead of requiring users to remember the plugin from which a setting originated. It also allows us to classify settings under multiple keywords. It obviously wouldn't stop the CodeMirror plugin having it's own settings tab if that is appropriate, but it absolutely should not overwrite core tiddlers to do so.

**Comment by kookma** [comment]
Great! I would e happy if I can help! 
So, plugins can have their own tab if needed and the UI allows to search/filter in the whole settings!
I like it!

**Comment by pmario** [comment]
>I'm suggesting that we add an optional "keywords" field to tiddlers tagged $:/tags/ControlPanel/SettingsTab. At the top of the settings tab we'd display a pick list of the keywords as mini-pseudo tag pills. Clicking one of them would filter the list to just show settings with that keyword.

IMO that doesn't solve the mess in the settings tab. Search is only useful, if I know, what I need to search for. Most of the time I know the plugin, that I want to customize. So having a "per plugin" tab somewhere does make sense for me.

If we want to search for plugin settings, we should probably search in pluigns. ... So if plugins do have a "settings" tab, it could be automatically shown as a tab somewhere. 

At the moment users need to open the plugin-list and have a look if there is a "config", "readme" or "settings" tab. If we would provide automatic integration in the ControlPanel IMO most plugin-authors would probably use it. ... I would. ... 

But I would still create a new top-level tab in the ControlPanel, if the settings are just added at the end of the default "Settings" tab. 

![grafik](https://user-images.githubusercontent.com/374655/150806286-45581073-8ec3-4535-b441-6a9d783a80bb.png)

**Comment by CodaCodr** [comment]
> > I'm suggesting that we add an optional "keywords" field to tiddlers tagged $:/tags/ControlPanel/SettingsTab. At the top of the settings tab we'd display a pick list of the keywords as mini-pseudo tag pills. Clicking one of them would filter the list to just show settings with that keyword.
> 
> IMO that doesn't solve the mess in the settings tab. Search is only useful, if I know, what I need to search for. Most of the time I know the plugin, that I want to customize. So having a "per plugin" tab somewhere does make sense for me.

Totally agree with @pmario.

That said, a top-level search along the lines of what @Jermolene is proposing sounds useful too. It should find _any_ setting mentioning the search term, native TW settings AND plugin settings.

**Comment by pmario** [comment]
I could imagine a settings tab similar to the talk.tiddlywiki admin page: 

![grafik](https://user-images.githubusercontent.com/374655/150814124-a2ead88e-0dfa-4056-a6bd-5c27bfdf2ac2.png)

If search is active it looks like this: 

![grafik](https://user-images.githubusercontent.com/374655/150814612-361b367d-1ca5-4937-b8b9-29942b53b45f.png)

IMO this would be a very usable UI. ... BUT it still didn't prevent me from having a manual look at all tabs without a filter to see what I needed to change some time ago. ...

**Comment by Jermolene** [comment]
I'll reply properly a bit later when I have more time, but your feedback is only about my search proposal; what do you think about keywords vs tabs, or is my proposal too unclear to understand?

The point is that entries can be filed under multiple keywords, which would be unusual with tabs.

**Comment by pmario** [comment]
>..what do you think about keywords vs tabs, or is my proposal too unclear to understand?

For me the $:/ControlPanel is the Settings area. I do like the tabs. They already contain the main keywords. For me it would be OK if a tab would be highlighted if the search term is found within it. 

If every parameter can have several keywords, that would be OK, but I think it would already be very helpful, if we would find/searhc the parameter **caption** and **description** fields.

I think we have to have some sort of **grouping**. The search function should create a **connection between the setting _and_ the location** where the setting can be found. eg: 

![grafik](https://user-images.githubusercontent.com/374655/150834929-ac4080e7-c7ac-40a1-beec-0a432452a5af.png)

or

![grafik](https://user-images.githubusercontent.com/374655/150835600-96df2393-985c-4c82-8207-ba2709b1dd48.png)

**Comment by Jermolene** [comment]
Thanks @pmario – your comments do not seem to be about my proposal for keywords instead of tabs. Was that part of my proposal clear?

**Comment by pmario** [comment]
>your comments do not seem to be about my proposal for keywords instead of tabs. Was that part of my proposal clear?

As I wrote I think there are already many keywords in the "caption" and "description" fields of the different elements. I think, if we would be able to find them it would already be a big win. 

------

A multi-language approach that I would like looks like this:

eg: I do have a German Windows, but I can still search for "device manager" and it will show the right program in German. Something similar would be valuable here too. 

If we do ad a keyword field, it should be possible to find keywords in all languages that are installed and show the result in the language that is active atm. ... 

The big advantage about this approach is, that every user can still use comments about english "setting keywords" made at eg. takl.tiddlywiki and still find settings in their native language.

**Comment by Jermolene** [comment]
Hi @pmario this is the specific part that I was hoping to get feedback on (emphasis added):

> I'm suggesting that we add an optional "keywords" field to tiddlers tagged `$:/tags/ControlPanel/SettingsTab`. **At the top of the settings tab we'd display a pick list of the keywords as mini-pseudo tag pills. Clicking one of them would filter the list to just show settings with that keyword.**

**Comment by pmario** [comment]
The Settings-tab has 16 parameters. I don't see a reason to search it. Typing the right "search term" will probably need more time than scroll down to find what to change. 

I think the settings tab at the moment contains parameters, that didn't fit to any other tab, that's why they landed there. May be "miscellaneous" would be the right term for it, since the whole ControlPanel tiddler contains "settings"

**Comment by Jermolene** [comment]
> The Settings-tab has 16 parameters. I don't see a reason to search it. Typing the right "search term" will probably need more time than scroll down to find what to change. 
> 
> 
> 
> I think the settings tab at the moment contains parameters, that didn't fit to any other tab, that's why they landed there. May be "miscellaneous" would be the right term for it, since the whole ControlPanel tiddler contains "settings"

Your comments seem to relate to search, but I'm trying to get your feedback on the keyword proposal, which is separate to the proposed search feature.

**Comment by pmario** [comment]
> Your comments seem to relate to search, but I'm trying to get your feedback on the keyword proposal, which is separate to the proposed search feature.

See: https://github.com/Jermolene/TiddlyWiki5/issues/5520#issuecomment-1020400001

**Comment by CodaCodr** [comment]
> Clicking one of them would filter the list to just show settings with that keyword.

Sorry, @Jermolene, I think now I understand.

So, if the proposed keywords arrive OOTB (and assuming I can't add my own) then all we'll have, in essence, is another way to organise settings. Checking on/off a set of keywords reduces the displayed settings accordingly. Correct?

I think I'd prefer it if, alongside the OOTB keywords, I could add my own. For example, you (i.e. the production "team") might think of a given setting as "foo-like" and add the keyword **foo**, whereas I might think of it more as "bar-ish" and want to check off **bar**. If I can't add my **bar** keyword then all the proposal amounts to is an alternate layout chosen by someone else (again, if I understand correctly).

Semi-aside. I see nothing wrong with repeating (duplicating) a setting in multiple tab areas, _if it makes sense_. I do that already in my own wikis. I mention this because it strikes me that visiting the control panel on all but (perhaps) the very first time, I have (a user has) a specific setting in mind that I wish to find. As things stand right now, I have to "borrow some else's hat" to hunt down their idea of where that setting might be stored. 

Search and/or keywords _should_ alleviate that and  shorten the time to finding that setting.

**Comment by kookma** [comment]
A gentle reminder
@Jermolene, @pmario

Based on the above discussion, I hope a decision can be made here. 

* The first request is having a central Settings tab, plugin developer can use it to add their plugins settings tiddler as subtab
* The next objective is, @Jermolene nice idea of having searchable settings (I know @saqimtiaz has done some efforts before)
* The next objective is to have a better in access settings with fewer click and may be a re-arrangement (for example one expect to find Toolbar button style under appearance ...)

**Comment by Jermolene** [comment]
> The first request is having a central Settings tab, plugin developer can use it to add their plugins settings tiddler as subtab

I would like to fix the behaviour of the CodeMirror plugin. The way that it moves existing entries around in the control panel is not acceptable (it was one of those PRs that I merged without deep enough evaluation; it's the sort of experience that has led me to be so cautious about PRs).

Perhaps we should fix that first and then worry about further enhancements. The trouble is that my proposal to use keywords is not compatible with the proposal to use tabs, so there's not an easy way forwards at the moment.

**Comment by kookma** [comment]
> I would like to fix the behaviour of the CodeMirror plugin.

I think @pmario is the maintainer behind Code Mirror! So, he may have a look!

**Comment by kookma** [comment]
> Perhaps we should fix that first and then worry about further enhancements. The trouble is that my proposal to use keywords is not compatible with the proposal to use tabs, so there's not an easy way forwards at the moment.

So, it seems there will be no improvement in the short term! I am using More sidebar for kookma plugins settings! It is not intuitive, but works and user has got used to. I continue using this approach and will wait for core improvement in future!
