### ISSUE TITLE
[IDEA] Make tags targettable and stylable

### ISSUE THREAD

**Issue by twMat** [Jermolene/TiddlyWiki5#5543]
**Is your feature request related to a problem? Please describe.**
Tags play a central role, also visually, but they're barely stylable. I want to style a tag (i.e all `Foo` tags, not a single instance of a `Foo` tag) with CSS but there is *no way to target it*.

One use case it to prevent selected tags from appearing when printing tiddlers, but there are many other use cases.

**Describe the solution you'd like**
Analogous to the `data-tiddler-title` attribute, I would like for a `data-tags-title` attribute like so:

`<span class="tc-tag-list-item" data-tags-title="Foo">`

**Describe alternatives you've considered**
Non-sense like setting a special background on the tag to make it targettable. This also means having to create a tiddler for the tag.

**Comment by Jermolene** [comment]
Thanks @twMat that's a good idea. Let me know how it goes

**Comment by twMat** [comment]
Hahaaa!!! I took your "encouraging dismissal" as an indication that this, contrary to my presumption, was actually something solvable without JS - and *voila!*

PR: https://data-tag-title.tiddlyhost.com/

(I really hope it is OK to PR like this. You've said so in the past.)

Thanks @Jermolene

**Comment by Jermolene** [comment]
Apologies @twMat I should have been clearer: I've already committed a fix to the prerelease. I meant let me know how you get on with using the new data- attribute.

**Comment by twMat** [comment]
Ha! OK, thank you! Turned out to be a good lesson anyway.  :-)
