### ISSUE TITLE
[BUG] SelectWidget placeholder attribute missing

### ISSUE THREAD

**Issue by twMat** [Jermolene/TiddlyWiki5#5544]
**Describe the bug**
I find no way to show a *placeholder* in the SelectWidget. The underlying html tag can do this using `disabled selected` parameters in the `option` tag. Compare the following by pasting them into a tiddler and observing the behaviour:

```
<select>
<option disabled selected>Select your option</option>
<option>A Tale of Two Cities</option>
<option>A New Kind of Science</option>
<option>The Dice Man</option>
</select>

<$select>
<option disabled selected>Select your option</option>
<option>A Tale of Two Cities</option>
<option>A New Kind of Science</option>
<option>The Dice Man</option>
</$select>
```

You'll note in both setups that the `disabled` parameter does work (shows as gray) but in the SelectWidget it does not show as *selected*. (The SelectWidget `default` parameter also does not *show up* as a placeholder value but, regardless, a deafult is not the same as a placeholder.)

It is very useful with a placeholder to give example values or instructions, especially in a tight layout when there is no room for an instruction next to the widget.

**Desktop (please complete the following information):**
 - Chrome
 - Win10

**Comment by twMat** [comment]
Add: Maybe - I'm not sure, please help me out - maybe it works with a `default` value after all because unless a value is selected, there is *no* value set anywhere. A deafult value does show before anything is selected, functioning as a placeholder.
Is this sufficient or does it risk messing something up? Are there cases where the default value can actually be transmitted as a value without it being actively selected (...which is normally the *point* with a default value). What, actually, *is* the point with a default value in the SelectWidget?

**Comment by pmario** [comment]
with tw widgets, the default value is used, if the config tiddler doesn't exist. As soon as the tiddler exists, this value is obsolete.

**Comment by twMat** [comment]
@pmario - can I read up on config tiddlers anywhere? I was not aware there is another tiddler involved with the SelectWidget selection.

Still, you say "the default value is used, if the config tiddler doesn't exist" - but if the user didn't actually select an option in the selectwidget to *set* a tiddler with some value... then how is the default value accessed by whatever uses the (supposedly) set value? I.e 

```
<$select default="true">
<option>false</option>
</$select>
```

How is that `true` value accessed? This isn't really my OP question but a general question about what the default value actually is/does in this widget.

**Comment by Jermolene** [comment]
Hi @twMat the select widget doesn't use the "selected" attribute of the "option" tag to determine the currently selected value. Instead it is bound to the value of a tiddler field or index, and TiddlyWiki manages things dynamically when either one changes.

So, the way to do the OP with the select widget is like this:

```
<$select tiddler="$:/temp/thing" default="Select your option">
<option disabled>Select your option</option>
<option>A Tale of Two Cities</option>
<option>A New Kind of Science</option>
<option>The Dice Man</option>
</$select>
```

**Comment by pmario** [comment]
@Jermolene imo your example should land in the docs

**Comment by pmario** [comment]
@twMat ... can you create a PR?

**Comment by twMat** [comment]
@Jermolene , thank you! @pmario , will do!
