### ISSUE TITLE
filters.js not ES5 compliant

### ISSUE THREAD

**Issue by cdruan** [Jermolene/TiddlyWiki5#5545]
Tiddlywiki 5.1.23 boot process aborts with Internal JavaScript Error on ipad3 (iOS 9.3.5):

>Internal JavaScript Error
>
> Syntax error in boot module $:/core/modules/filters.js ...

eslint points out `core/modules/filters.js` has violated the [no-inner-declarations](https://eslint.org/docs/rules/no-inner-declarations) rule. 

So I tried the following modification, and can confirm TW then loaded successfully.

```diff
--- ../tiddlywiki/core/modules/filters.js       
+++ ../tiddlywiki-mod/core/modules/filters.js   
@@ -63,7 +63,7 @@
                        operator.operator = "title";
                }
                operator.operands = [];
-               function parseOperand(bracketType) {
+               var parseOperand = function (bracketType) {
                        var operand = {};
                        switch (bracketType) {
                                case "{": // Curly brackets
```

**Comment by Jermolene** [comment]
Thank you @cdruan. We do try to stick to ES5 but stuff does slip through. I'll commit the fix shortly, but do feel free to sign the CLA and submit PRs in future (see contributing.md in the root).

I'm intrigued that you're able to run TW5 on iOS 9.3.5, may I ask how you've got it set up?

**Comment by cdruan** [comment]
Hi @Jermolene 

> I'm intrigued that you're able to run TW5 on iOS 9.3.5, may I ask how
> you've got it set up?

I haven't had any major issues viewing tiddlywiki pages on iOS 9
Safari.  I use Windows IIS WebDav server to host single-file
TiddlyWikis with client certificate authentication so I can edit
without username/password; others w/o certificates have read-only
access. Certificate authentification works on ipad, too. On my linux
desktop, I have tiddlywiki on node.js. for experiments and private
notes.
