### ISSUE TITLE
css-escape-polyfill.js doesn't quite work on old iOS

### ISSUE THREAD

**Issue by cdruan** [Jermolene/TiddlyWiki5#5546]
After changing `filters.js` to make TW 5.1.23 ES5 compliant, I received the following error on every link I clicked upon a successful page load on ipad3 (iOS 9.3.5):

> Internal JavaScript Error
>
> TypeError: CSS.escape is not a function. (In 'CSS.escape(title)', 'CSS.escape' is undefined)

I looked into `core/modules/startup/css-escape-polyfill.js`. Added `CSS.escape()` seems to disappear in the global context on iOS 9, causing `escapecss` filter to fail when calling `CSS.escape(title)`. But everything seems to work as expected if I just change how `escape` is added to `root.CSS`:

```diff
@@ -109,6 +110,6 @@
                root.CSS = {};
        }
 
-       root.CSS.escape = cssEscape;
+       Object.getPrototypeOf(root.CSS).escape = cssEscape;
```

Hope this is legit. I have tested this mod on IE and ipad 3. The modification ran without problems on either platforms. IE does not have `CSS` at all; iOS 9 has `CSS.support()` defined in `CSS`'s prototype.

One more question:

```js
// currently in css-escape-polyfill.js
exports.startup = factory(root);                // polyfill code gets executed on the server side, too

// do you mean to do this?
exports.startup = function() {factory(root);};  // delayed execution and polyfill not run on the server
```

Apologies for "bugging" the team with old-old browser issues. I am thankful for TW team's effort in backward compatibility :)

**Comment by Jermolene** [comment]
Thanks @cdruan 

> Hope this is legit. I have tested this mod on IE and ipad 3. The modification ran without problems on either platforms. IE does not have `CSS` at all; iOS 9 has `CSS.support()` defined in `CSS`'s prototype.

Great, that looks fine to me. I'll commit the fix shortly.

> 
> One more question:
> 
> ```js
> // currently in css-escape-polyfill.js
> exports.startup = factory(root);                // polyfill code gets executed on the server side, too
> 
> // do you mean to do this?
> exports.startup = function() {factory(root);};  // delayed execution and polyfill not run on the server
> ```

That's great, thanks for spotting that. I'll post the fix shortly.

> Apologies for "bugging" the team with old-old browser issues. I am thankful for TW team's effort in backward compatibility :)

Not at all, many thanks! We get deep backwards compatibility just by virtue of having started in 2011/12, but it still takes vigilance to maintain it.

**Comment by Jermolene** [comment]
Hi @cdruan I just realised that we have in fact approached this wrongly.

The problem is that we need the "escapecss" operator to work under Node.js as well as the browser. So we do in fact need to polyfill it under Node.js as well as in the browser. Part of fixing this should be to add a test for the "escapecss" operator.

Would you be interested in working on the fix with me?

**Comment by cdruan** [comment]
Hi @Jermolene 

I'm quite new to Tiddlywiki code base, but I'd be happy to contribute if you believe the task won't be over my head.

> Part of fixing this should be to add a test for the "escapecss" operator.

Do you mean adding something like `filter-escapecss-fitler.js` inside `editions/test/tiddlers/tests/`? Can I assume `cssEscape()` is correctly defined and just ensure "escapecss" filter operator can be triggered successfully under both node.js and the browser?

I was under the assumption that you can add more than one values to `exports.platforms` variable to determine when `exports.startup` should be triggered. If that is correct, could you please look at the code below?  I don't think the logic has the intended effect.

```js
// boot.js

$tw.boot.doesTaskMatchPlatform = function(taskModule) {
	var platforms = taskModule.platforms;
	if(platforms) {
		for(var t=0; t<platforms.length; t++) {
			if((platforms[t] === "browser" && !$tw.browser) || (platforms[t] === "node" && !$tw.node)) {
				return false;
			}
		}
	}
	return true;
};
```

If `taskModule.platforms` variable contains BOTH "browser" and "node", `false` is returned when running in either node or browser environment.

**Comment by pmario** [comment]
@Jermolene ... Is this issue closed or still open?

**Comment by Jermolene** [comment]
> I'm quite new to Tiddlywiki code base, but I'd be happy to contribute if you believe the task won't be over my head.

Hopefully not, it should be fairly simple.
 
> > Part of fixing this should be to add a test for the "escapecss" operator.
> 
> Do you mean adding something like `filter-escapecss-fitler.js` inside `editions/test/tiddlers/tests/`?

I think we can just drop some tests into the existing file https://github.com/Jermolene/TiddlyWiki5/blob/master/editions/test/tiddlers/tests/test-filters.js

> Can I assume `cssEscape()` is correctly defined and just ensure "escapecss" filter operator can be triggered successfully under both node.js and the browser?

I'm now thinking that it is needless complexity to polyfill the funciton as `CSS.escape()`, we might as well make a new `$:/core/modules/utils/escapecss.js` module that adds a new `$tw.utils.escapeCSS()` method, and then for us to invoke that function within the `escapecss` operator.

> I was under the assumption that you can add more than one values to `exports.platforms` variable to trigger `exports.startup` on any of the platforms listed. If that is correct, could you please look at the code below? I don't think the logic has the intended effect.

Good catch. In practice, startup modules that want to run on all platforms simply omit the `exports.platforms` property. But I think we could fix that without affecting backwards compatibility.
