### ISSUE TITLE
[BUG] Two Uncaught ReferenceErrors: global is not defined at _bootprefix & require is not defined at _boot

### ISSUE THREAD

**Issue by MikeAlMartinez** [Jermolene/TiddlyWiki5#5549]
**Describe the bug**
Tiddlywiki on latest version of chrome seems to be broken.

**To Reproduce**
1. Go to https://tiddlywiki.com/ (or your personal tiddlywiki) in the latest version of chrome
2. Open devtools inspector - view error

**Expected behavior**
It should display the target tiddlywiki as expected

**TiddlyWiki Configuration (please complete the following information):**
 - Version: Have check tiddlywiki versions from 5.1.20->5.1.24
 
**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome Version 89.0.4389.90 (Official Build) (x86_64)

**Comment by danfoley** [comment]
i have the same issue.

**Comment by MikeAlMartinez** [comment]
I've resorted to using firefox for my wiki for the time being.

**Comment by Jermolene** [comment]
Hi @MidnightLightning @danfoley it would be helpful to have more details/screenshot of the error you're encountering.

Also, might you be using any browser extensions that might be interfering with TiddlyWiki?

**Comment by MikeAlMartinez** [comment]
I disabled my password extension and it started working again. I then reenabled it and it still works... which seems strange, but perhaps it needed to be reloaded? I will keep an eye out to see if it happens again. But looks like extensions may have been to blame.

**Comment by Jermolene** [comment]
Thanks @MikeAlMartinez that's great. It's a surprisingly common problem.
