### ISSUE TITLE
[BUG] Unable to export double quoted tiddlers

### ISSUE THREAD

**Issue by Dialga** [Jermolene/TiddlyWiki5#5561]
**Describe the bug**
Currently it is not possible to export tiddlers with double quotes surrounding the tiddler title.

**To Reproduce**
1. Go to empty.html
2. Create a new tiddler named "Tiddler"
3. Click the drop drop to export

**Expected behavior**
Double quoted tiddlers to be exportable.

**Screenshots**
![Screenshot_20210323_185608](https://user-images.githubusercontent.com/5157928/112100712-6d861f00-8c0a-11eb-91af-b627290cc586.png)

**Comment by Dialga** [comment]
Same case with tiddler named `\"Tiddler\"`.

**Comment by Jermolene** [comment]
Thanks @Dialga that should be fixed in 226df2ad7d2978d3d7400d94767a0503e495cf98. The fix will be live on the prerelease shortly.
