### ISSUE TITLE
[BUG] TW on Node.JS does not keep the changes after bibtex importer error

### ISSUE THREAD

**Issue by kookma** [Jermolene/TiddlyWiki5#5581]
**Describe the bug**
I use Tiddlywiki on Node.JS with official Bibtex importer plugin. After importing a bib file I got error from Bibtext importer plugin (see below screenshot).  I clicked import by mistake despite the error by Bibtex importer) After that I note the messages in terminal window running TW on node.JS (see last screenshot below and it was repeating). All changes I did to wiki after this import were not saved while TW did not warn me or there was no any indication of maloperations.

**To Reproduce**
1. create an empty wiki with `tiddlywiki mywiki --init server`
2. add bibtex plugin by editing the  `tiddlywiki.info` file and adding `"tiddlywiki/bibtex"`
3. run the server and import a badly format bib file like attached one
4. note to terminal window
5. add some new tiddler
6. stop server
7. restart server
8. see the issue none of tiddlers of step 5 were saved

**Expected behavior**
TW shall continue saving the changes after the import operation.

**Screenshots**
![img_47_explorer](https://user-images.githubusercontent.com/830394/113484572-4b1fbb80-94be-11eb-8324-68410bb24393.png)

**After import**
![img_49_chrome](https://user-images.githubusercontent.com/830394/113484585-57a41400-94be-11eb-8d60-825039f6fbed.png)

Terminal window running Tiddlywiki on Node.JS

![img_48_ConEmu64](https://user-images.githubusercontent.com/830394/113484612-799d9680-94be-11eb-9969-e48e24928206.png)

**TiddlyWiki Configuration (please complete the following information):**
 - Version v5.1.24pre
 - Saving mechanism  Node.js
 - Plugins installed Bibtex importer
 
**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome 89

**Comment by saqimtiaz** [comment]
@kookma can you attached the bibtex file that triggered this error? That will likely prove helpful for debugging.

**Comment by kookma** [comment]
Hi Saq,
Attached is the bibtex file.
[mybibtext-library.zip](https://github.com/Jermolene/TiddlyWiki5/files/6253237/mybibtext-library.zip)

**Comment by Jermolene** [comment]
Thanks @kookma @saqimtiaz I believe the problem is just that the Bibtex parser was dumping the entire text of the imported file in case of an error with the Bibtext library. Fix upcoming.

**Comment by kookma** [comment]
Many thanks Jeremy!
I confirm that the error has gone! and TW works fine now!
