### ISSUE TITLE
[BUG] Filters in permalinks don't work

### ISSUE THREAD

**Issue by twMat** [Jermolene/TiddlyWiki5#5588]
**Describe the bug**
Either it is a syntax typo in the docs or complex permalink filtering doesn't work properly.

**To Reproduce**
1. Go to [https://tiddlywiki.com/prerelease/#PermaLinks](https://tiddlywiki.com/prerelease/#PermaLinks) - or just click the link in step 2
2. Click on the example link that reads [https://tiddlywiki.com/#:[tags[task]]](https://tiddlywiki.com/#:[tags[task]])
3. Lots of irrelevant tiddlers, not tagged `task`, appear

I note that the resulting urls are 
chrome: `https://tiddlywiki.com/#:%5Btags%5Btask%5D%5D`
firefox : `https://tiddlywiki.com/#:[tags[task]]`
...but neither gives correct results.

Win10, Chrome + FF

**Comment by Jermolene** [comment]
Thanks @twMat I think it's a typo: "tags[" should be "tag[". I'll post a fix shortly
