### ISSUE TITLE
Macros are broken in static renderings of tw5.com

### ISSUE THREAD

**Issue by Jermolene** [Jermolene/TiddlyWiki5#559]
The templates used to create static renderings do not include PageMacros. This means that macros like the wikitext examples are broken. (See http://tiddlywiki.com/static/Lists%2520in%2520WikiText.html for an example).

The fix is to make the macros inside PageMacros be global macros.

**Comment by tobibeer** [comment]
Is this fixed?

**Comment by Jermolene** [comment]
Yes, thanks @tobibeer it is fixed.
