### ISSUE TITLE
[BUG] Bibtex importer plugin does not take care of field names in uppercase

### ISSUE THREAD

**Issue by kookma** [Jermolene/TiddlyWiki5#5591]
**Describe the bug**
Bibtex importer  processes imported .bib data and all entry tags are assigned to fields with the prefix `bibtex-`. The problem is it does not take care of tag in upper case, so from a bibtex entry tag like ISBN it creates `bibtex-ISBN`.

**To Reproduce**
1. Open a wiki with bibtex importer installed
2. download the attached zip file, unzip it
3. Drag and drop the .bib file from step 2 above
4. Import the bibtex entries and open one of the tiddler
5. look at the fields and see `bibtex-ISBN`

**Expected behavior**
It should convert all entry tags to lowercase and then add the prefix `bibtex-`

**Screenshots**

![image](https://user-images.githubusercontent.com/830394/113873825-68100380-97ca-11eb-8d6e-f63d8128a59f.png)

**TiddlyWiki Configuration (please complete the following information):**
 - Version 5.1.24
 - Saving mechanism   Node.js
 - Plugins installed bibtex importer
 
**Desktop (please complete the following information):**

[CRE Books - EndNote.zip](https://github.com/Jermolene/TiddlyWiki5/files/6271860/CRE.Books.-.EndNote.zip)

**Comment by Jermolene** [comment]
Thanks @kookma I've pushed a fix, let me know if it fixes things for you.

**Comment by kookma** [comment]
Thank you @Jermolene. Now it work fine!
