### ISSUE TITLE
[BUG] RSOE from undefined variable in subfilter

### ISSUE THREAD

**Issue by twMat** [Jermolene/TiddlyWiki5#5592]
**Describe the bug**
RSOE with `Uncaught TypeError: Cannot read property 'getVariable' of undefined`

**To Reproduce**
```
<$vars sub="[match<undefined>]">
<$list filter="[[arbitrary]filter<sub>]">

</$list>
</$vars>
```

**Comment by pmario** [comment]
Very interesting catch.  It seems the list widget doesn't pass on the `widget` object-pointer. so widget.getVariable() isn't defined. 

There should have been problems much earlier.

**Comment by saqimtiaz** [comment]
Same underlying issue as #5471

**Comment by twMat** [comment]
>Same underlying issue as #5471

OK, closing this unless someone objects. Thanks guys.

**Comment by saqimtiaz** [comment]
@twMat please leave this open, while the cause is the same they will both need patching.
