### ISSUE TITLE
[BUG] in add-tm-field and add-tm-tag widget messages

### ISSUE THREAD

**Issue by kookma** [Jermolene/TiddlyWiki5#5593]
**Describe the bug**
Following the discussion on https://groups.google.com/d/msgid/tiddlywiki/93fc7e18-3336-40b3-988e-26a0887c3052n%40googlegroups.com?utm_medium=email&utm_source=footer I file this issue here.
fieldmangler widget not only apply the operation on target tiddler but also on the currentTiddler.

**To Reproduce**
1. Go to  https://tiddlywiki.com/prerelease/#FieldMangler%20Widget%20(Examples)
2. Click on edit button to open the FieldMangler Widget (Examples) in edit mode
3. Open the preview pan
4. Run the last example i.e click on `Add tag example to the Hello World tiddler` button
5. TW not only adds the new tag to HelloWorld tiddler but also to the `FieldMangler Widget (Examples)` e.g. the tiddler in preview mode!
6. The same issue is seen with `tm-add-field`

**Expected behavior**
the operation shall only be applied to the tiddler mentioned in fieldmangler widget!

**TiddlyWiki Configuration (please complete the following information):**
 - Version 5.1.24
 - Saving mechanism Timimi

 
**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome/Edge/FF

**Comment by Jermolene** [comment]
Thanks @kookma, fix is coming up.

**Comment by kookma** [comment]
Tested on https://tiddlywiki.com/prerelease/
The issue has fixed! Thank you very much!

**Comment by Jermolene** [comment]
Great, thanks @kookma
