### ISSUE TITLE
[bug] I cannot save more than one tag

### ISSUE THREAD

**Issue by ghost** [Jermolene/TiddlyWiki5#5595]
I cannot have this tiddler with more than one tag (see video)
![output](https://user-images.githubusercontent.com/89915/114194114-73d90280-994f-11eb-9058-2f51077e982b.gif)

**Comment by somenxavier** [comment]
This is related to [this](https://github.com/Jermolene/TiddlyWiki5/issues/5576):
when I remove "!!!" in the title, then I can add more than one tag
![Captura de pantalla_2021-04-09_16-26-11](https://user-images.githubusercontent.com/89915/114194977-5193b480-9950-11eb-8454-f9c16abb2cd5.png)

**Comment by Jermolene** [comment]
Thanks @somenxavier. Are you able to reproduce the problem on tiddlywiki.com/empty?

**Comment by pmario** [comment]
@Jermolene .. I can replicate it with title: `test!!`  ... As soon as there are 2 exclamation marks in the title it starts to create the same behaviour

 - crate a tiddler: test!!
 - save
 - open
 - try to add 2 tags
 -

**Comment by somenxavier** [comment]
Thanks @pmario

**Comment by saqimtiaz** [comment]
This is resolved in the prerelease and can be closed @Jermolene 

Note that the account associated with the ticket no longer exists so you are the only one that can close this.

**Comment by Jermolene** [comment]
Thanks @saqimtiaz
