### ISSUE TITLE
Massive search slowdown due to large images

### ISSUE THREAD

**Issue by choralbari** [Jermolene/TiddlyWiki5#5606]
I imported some images to my TiddlyWiki and things got unbearably slow. Especially search. The largest such image was  about 2.1 MB when saved as a PNG.

I noticed that base64-encoded image text appeared in the context widget when I stopped JS in the debugger. The fix appears to be easy:

I replaced this test in `contextWidget.prototype.render`

```JavaScript
if(this.term && this.term.length > 3)
```

with

```JavaScript
if(this.term && this.term.length > 3 && !this.wiki.isBinaryTiddler(this.tiddler))
```

and search is fast again.

**Comment by saqimtiaz** [comment]
@choralbari that makes sense. Would you feel comfortable making a PR for this change?

**Comment by pmario** [comment]
Which version of TW did you use?

I can't find `contextWidget.prototype.render` in the core repository

**Comment by pmario** [comment]
https://squoosh.app/ may help you to make your images smaller in size, if possible. ... 

You should try to load images external, since base64 actually doubles the space needed for your images. Especially since images can't be compressed serverside, they have to go fullsize over the wire. 

see: https://tiddlywiki.com/#ExternalImages

**Comment by Jermolene** [comment]
Hi @choralbari it sounds like you're using @danielo515's Context Plugin (http://contextplugin.tiddlyspot.com/), which has its own repo here: https://github.com/danielo515/TW5-contextPlugin

**Comment by pmario** [comment]
@Jermolene .. you did a similar thing, with the diff-match-patch library... But I can't remember the name

**Comment by Jermolene** [comment]
Hi @pmario do you mean the Dynannotate plugin?

**Comment by pmario** [comment]
If you used it for the: The [e-book-search-thing](it: https://tw5.immateriel.fr/wiki/7switch/book/aHR0cHM6Ly9jYXRhbG9ndWUuaW1tYXRlcmllbC5mci9yZXNvdXJjZXMvYTYvMTIvMDcyMDhkOTdhZjdmYWZkMjkyNzRhN2MwNDU1YS5lcHVi)

**Comment by choralbari** [comment]
Hi @Jermolene! You are right! I did not realize that I had that plugin installed. I will report the issue there.

**Comment by saqimtiaz** [comment]
@choralbari could you please close this issue? Thank you.
