### ISSUE TITLE
[BUG] Dropzone dragover state can incorrectly persist

### ISSUE THREAD

**Issue by saqimtiaz** [Jermolene/TiddlyWiki5#5616]
When a file is being dragged over a `<$dropzone>`, the DOM node created by the dropzone is given the class of `tc-dragover`. However, this class is not always correctly removed when the dragged file leaves the dropzone.

This particular issue surfaces on Firefox on both Windows 10 and Ubuntu 20.04 but not in Chrome (or at least not frequently enough that I can reproduce it). I've investigated the cause and while I do not have a clean solution for this yet, I will summarize my findings at the end of this issue.

The following video demonstrates the issue with a `<$dropzone>` with a custom class, with CSS to have a red border when it has the class `tc-dragover`.  Note how the red border around the dropzone persists even after the mouse is no longer over the dropzone's DOM Node, and even after the file has been dropped and an import triggered.

https://user-images.githubusercontent.com/68092/115244765-8b20a880-a124-11eb-9d54-b9310cad8c13.mp4

The file used for the video demonstration can be found here: https://saqimtiaz.github.io/sq-tw/temp/dropzone-bug.html

**While it takes some rather persistent erratic mouse movement here to trigger the bug, at times it can happen even the first time the file is dragged over a dropzone.**

All of the following contribute to the `dragleave` event firing less consistently and this problem cropping up more frequently:

- greater speed of drag movement
- no margin or padding between the nested DOM elements that we drag over
- entering and leaving the dropzone from different directions.
- the presence of an iframe or input element immediately inside the dropzone with no margin or padding.

`<$dropzone>` maintains an array of all DOM elements entered in the `dragenter` event, and then removes elements from this list in the `dragleave` event. The `dragleave` and `dragenter` events are fired for the DOM node created by the dropzone as well as all descendant DOM nodes. The logic is sound. 

The problem is that the browser implementation is such that the `dragleave` and `dragenter` events are not fired consistently on all descendant elements of the dropzone. So dragging across a dropzone with a child DIV inside it, you may get two `dragenter` events but only one `dragleave` event, in which case the `tc-dragover` class is never removed for the `<$dropzone>` widget. Alternatively you may get the same number of `dragenter` events as `dragleave`, but on different DOM nodes.

**Comment by pmario** [comment]
I thin we did have a similar problem with the **list-links-draggable** macro. ... So we may have a closer look there. ... Just a guess!

**Comment by saqimtiaz** [comment]
@pmario the <$droppable> widget and list-links-draggable macro also have the same problem, which makes sense since the code base is very similar.

**Comment by saqimtiaz** [comment]
There another way in which the same visual issue of a persisting dragover state surfaces:

- Create a new tiddler and type some content in it, do not save.
- Drag over a file to import it as normal.
- Press `Esc` to cancel the import. You will also get prompted to discard the changes to the tiddler. If you choose to cancel and not discard the changes, the dragover state will persist.

This is also risky because the user expects to just be cancelling the drag and if they do not read carefully, they can loose the changes they had made to the tiddler they were editing.

**Comment by Jermolene** [comment]
> The same visual issue of a persisting dragover state surfaces in Chrome as well in the following situation:
> 
> * Create a new tiddler and type some content in it, do not save.
> * Drag over a file to import it as normal.
> * Press `Esc` to cancel the import. You will also get prompted to discard the changes to the tiddler. If you choose to cancel and not discard the changes, the dragover state will persist.
> 
> This also **risks data loss** because the user expects to just be cancelling the drag and if they do not read carefully, they can loose the changes they had made to the tiddler they were editing.

Wow that's pretty scary. And tricky to fix, because I  that even the way that the <kbd>Esc</kbd> key cancels the drag is  platform/browser specific.

**Comment by saqimtiaz** [comment]
@Jermolene tricky indeed. It needs proper thought to hopefully find a cleaner solution, but one option could be a global drag state and when drag is active, we capture all `keydown` events or disable keyboard widgets. 

We have `$tw.dragInProgress` but that is currently not used for files being dragged. However such an approach would make it even more so important that we correctly exit the drag state.

**Comment by Jermolene** [comment]
> @Jermolene tricky indeed. It needs proper thought to hopefully find a cleaner solution, but one option could be a global drag state and when drag is active, we capture all `keydown` events or disable keyboard widgets.
> 
> We have `$tw.dragInProgress` but that is currently not used for files being dragged. However such an approach would make it even more so important that we correctly exit the drag state.

The trouble with trapping keydown events is that we would be embedding some rather browser specific behaviour into the core (in that one can just about imagine operating systems with long lived drag-and-drop like gestures that shouldn't be interrupted by the keyboard). It kind of seems like a browser behaviour bug to pass on the escape key despite having already acted upon it.

**Comment by saqimtiaz** [comment]
@Jermolene I'll find some time to look into this further and see what we can do to mitigate the problem. As drag and drop becomes more commonplace these issues will surface more frequently. I ran into these in the course of my PR for adding support for dragging and dropping images into the editor, and they aren't at all specific to that feature but crop up more frequently with that workflow.

I am wondering if it would be worth re-phrasing the message we show with the `tc-dragover` class to not mention the <kbd>Esc</kbd> button to cancel drag and drop, as a form of mitigation for the risk of data loss.

**Comment by saqimtiaz** [comment]
> It kind of seems like a browser behaviour bug to pass on the escape key despite having already acted upon it.

Agreed, and not surprising either considering this is the only mention that the [HTML5 Drag and Drop](https://www.w3.org/html/wg/spec/dnd.html) spec has of it:

> If the current drag operation is none (no drag operation), or, if the user ended the drag-and-drop operation by canceling it (e.g. by hitting the Escape key), or if the current target element is null, then the drag operation failed.  If the current target element is a DOM element, the user agent must fire a dragleave event at it; otherwise, if it is not null, it must use platform-specific conventions for drag cancellation.

**Comment by thammawat-s** [comment]
@saqimtiaz  I'm not sure about programming part but I can't reproduce the error.   I try to drag with lots of mouse movement over and outside dropzone, and red box doesn't persist.  I'm testing on Firefox v 88.0 64-bit on win 10.

**Comment by saqimtiaz** [comment]
@thammawat-s you can get lucky at times since what I posted is a minimal test case which doesn't include many of the above described factors which make this behaviour more commonplace.

Sadly I've reproduced this on 3 different machines in Firefox (2 on Windows and the third on Ubuntu).

I've tried various ways to address this bug with no clean solution in sight. At this point I am tempted to mitigate the problem by adding a click handler to the dropzone that clears its state, since a click event cannot occur during a drag.

**Comment by saqimtiaz** [comment]
Fixed in #5688.

Note that the same issue exists in the droppable widget and will be addressed separately.
