### ISSUE TITLE
[BUG] decodeuri op doesn't work for other spec chars than %20 (space)

### ISSUE THREAD

**Issue by twMat** [Jermolene/TiddlyWiki5#5619]
**Describe the bug**
The `decodeuri[]` op doesn't seem to give correct output for string with other special characters than `%20` (space). (OK, possibly there are more special characters that do work but at least the following don't)

**To Reproduce**
On tw.com type in the following (the link is a permalink to the core plugin)
`{{{ [[Title%20with%20Space]] [[https://tiddlywiki.com/#%24%3A%2Fcore]] +[decodeuri[]] }}}`

...which gives output
`Title with Space`
`https://tiddlywiki.com/#%24%3A%2Fcore`

I was expecting the output that I get when testing on e.g https://www.url-encode-decode.com/ ,i.e:
`Title with Space`
`https://tiddlywiki.com/#$:/core`

**Comment by Jermolene** [comment]
I think in this instance you need `[decodeuricomponent[]]`

**Comment by twMat** [comment]
Aha! Thanks! :-)
