### ISSUE TITLE
[BUG] The new disabled attribute of TW 5.1.23 for button widget does not work with tc-btn-invisible class 

### ISSUE THREAD

**Issue by kookma** [Jermolene/TiddlyWiki5#5625]
**Describe the bug**
The new disabled attribute of TW 5.1.23 for button widget does not work with `tc-btn-invisible` class 

**To Reproduce**
1. Go to https://tiddlywiki.com
2. Create a new tiddler with below contents

```
Enabled <$button disabled=no>{{$:/core/images/options-button}}</$button> 

Disabled no class <$button disabled=yes>{{$:/core/images/options-button}}</$button>

Disabled with `tc-btn-invisible` class  <$button class="tc-btn-invisible" disabled=yes>
{{$:/core/images/options-button}}
</$button>
```

3. Look at the buttons, the one without `tc-btn-invisible` has correct cursor type (normal) and is greyed out but the one with `tc-btn-invisible` has cursor as pointer and and is NOT greyed out!

**Expected behavior**
The appearance shall follow the disabled button!

**TiddlyWiki Configuration (please complete the following information):**
 - Version 5.1.24p
 - Saving mechanism Node.js

 
**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browse Chrome 
 - Version 89

**Comment by pmario** [comment]
IMO this wouldn't be a problem anymore, if https://github.com/Jermolene/TiddlyWiki5/pull/5294/files would have been merged.

**Comment by pmario** [comment]
That's what you expect. right?

![disabled-button-01](https://user-images.githubusercontent.com/374655/115959477-a87eb980-a50c-11eb-9c8e-b907ccfdaed3.gif)

**Comment by kookma** [comment]
Hi @pmario - thank you!
The last image shows what I expect!

**Comment by pmario** [comment]
I did update the PR. So it should be mergeable ... I think.

**Comment by saqimtiaz** [comment]
Can this be closed?

**Comment by pmario** [comment]
@kookma ... https://tiddlywiki.com/prerelease/ has been updated and your example can be tested there.

**Comment by kookma** [comment]
Testing on https://tiddlywiki.com/prerelease/ 

```
<$button disabled=yes class="tc-btn-invisible">Hi</$button>

<$button disabled=no class="tc-btn-invisible">Hi</$button>
```

I cannot see any difference! Is there anything wrong with my test? Note to the class="tc-btn-invisible" and the cursor shape on hover. The disabled button should not display a pointer shape for cursor on mouse hover!

**Comment by pmario** [comment]
IMO this is something new. ... And from my point of view useless. 

If the disabled button, is greyed out and the button is invisible, the user dosn't have any indication, that there is a button at all. So text without an icon or a button doesn't make too much sense. ... 

You can provide some new CSS and create a PR that covers this edge case. I don't!

**Comment by Jermolene** [comment]
> If the disabled button, is greyed out and the button is invisible, the user dosn't have any indication, that there is a button at all. So text without an icon or a button doesn't make too much sense. ... 

I don't think it's an edge case. tc-btn-invisible doesn't make the button invisible, just the border and background. I think what @kookma is asking is for disabled buttons with the tc-btn-invisible class to render in grey instead of black.

**Comment by saqimtiaz** [comment]
I think it is important to follow browser defaults here to match user expectations. Both Chrome and Firefox do not use a pointer cursor for disabled buttons, whereas we currently do as can be seen with this example:

```
<$button disabled=yes class="tc-btn-invisible">{{$:/core/images/options-button}}</$button>

<$button disabled=no class="tc-btn-invisible">{{$:/core/images/options-button}}</$button>
```

Furthermore we should change the color of the text in disabled buttons as well.

**Comment by pmario** [comment]
A naive fix would look like this, but will create a problem if `.tc-btn-invisible` is _not_ used: 

![grafik](https://user-images.githubusercontent.com/374655/116075992-f245dc00-a693-11eb-844b-33948af5446e.png)

So we will need the same mechanism for buttons, that we use for tags. 

copy / paste code to be tested at: https://tiddlywiki.com/prerelease

```
<style>
button:disabled  {
	cursor: default;
	color: <<colour muted-foreground>>;
}
</style>

<$button disabled=yes class="tc-btn-invisible">{{$:/core/images/options-button}} some text</$button>

<$button disabled=no class="tc-btn-invisible">{{$:/core/images/options-button}} some text</$button>

<$button disabled=yes class="">{{$:/core/images/options-button}} some text</$button>

```

**Comment by pmario** [comment]
For tag "contrast colour" handling we use the `contrastcolour` js-macro. .. The problem is, that the button-widget doesn't know anything about colours. It only knows about classes.

**Comment by Jermolene** [comment]
Could we do something like this:

```
 button:disabled.tc-btn-invisible  {
 	cursor: default; 
 	color: <<colour muted-foreground>>;
}
```

**Comment by pmario** [comment]
I think it may work in different contexts. .. I would be OK with it

![grafik](https://user-images.githubusercontent.com/374655/116088965-ab131780-a6a2-11eb-8437-bab057746d26.png)

**Comment by kookma** [comment]
Thank you all! I support what Saq stated above and I say the same! Browser default for disabled button is `cursor:default` and grayed out color! and this is not related to the user class! So the solution by Jeremy sounds good!

```
button:disabled.tc-btn-invisible  {
 	cursor: default; 
 	color: <<colour muted-foreground>>;
}

```

**Comment by saqimtiaz** [comment]
@kookma do you think you can find the time to create a PR for this so that it isn't forgotten?

**Comment by kookma** [comment]
Hi @saqimtiaz 
Sure I prepare the PR!

**Comment by kookma** [comment]
@saqimtiaz 
I have created a PR and correct the base.tid in Vanilla! See #5692
