### ISSUE TITLE
[BUG] GUTHUB saverr can't make it work

### ISSUE THREAD

**Issue by DBJDBJ** [Jermolene/TiddlyWiki5#5637]
That URL is a folder of the organization's site. A bit convoluted but why not ... that should work.  
Repo is https://github.com/DBJDBJ/dbjdbj.github.io

Thus I dutifully do this setup:

![image](https://user-images.githubusercontent.com/145155/115999970-8e1d0c80-a5ee-11eb-8d6d-7298489be6bc.png)

and after approx 30 sec I get

![image](https://user-images.githubusercontent.com/145155/116000008-bd337e00-a5ee-11eb-9a58-ddf6627e527a.png)

Yes I tried with a token and I tried with a password. 

F12 reveals problems

![image](https://user-images.githubusercontent.com/145155/116000221-97f33f80-a5ef-11eb-9962-3f505e183ae9.png)

If I switch of automatic save I can se that correct HTTP is attempted

![image](https://user-images.githubusercontent.com/145155/116000381-3f707200-a5f0-11eb-8be2-ee39839cacf1.png)

but both URLS have this `content` part ? 

https://api.github.com/repos/dbjdbj.github.io/contents/tw/index.html

If I change the repo to the probably correct `dbjdbj/dbjdbj.github.io` the outcome is the same

![image](https://user-images.githubusercontent.com/145155/116000734-af332c80-a5f1-11eb-8c44-ea395fea2aa1.png)

and so on ...

Please advise ...

**Comment by saqimtiaz** [comment]
Try removing the branch as you see it from the GitHub saving UI and typing it back in. There is a bug in TW5.1.23 where the default value isn't correctly read.

**Comment by Arlen22** [comment]
@saqimtiaz is that bug taken care of yet?

**Comment by saqimtiaz** [comment]
@Arlen22 the fix is in the pre-release and will be in TW 5.1.24 when that becomes available.

**Comment by DBJDBJ** [comment]
Does that make TW unusable at the moment, for us GitHub savers?

**Comment by saqimtiaz** [comment]
@DBJDBJ no, as I said, in the Github Saver tab in the Control Panel please remove the value you see for branch (master in your screenshot) and type it in again manually.

**Comment by Arlen22** [comment]
The problem is simply that the default value is set in two places, and only one of them was changed in the last release. However when you manually type the value into the box, even if it matches the default value it will still be saved, and from then on it will be used instead of either default.

**Comment by DBJDBJ** [comment]
that worketh
