### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by lixiepeng** [Jermolene/TiddlyWiki5#5649]
How can I trust html to allow js exec when I create html format doc?

**Comment by pmario** [comment]
In the same way, you trust every other web page, that you open.
Every browser basically is a virtual machine, that can execute javascript. So as long as you use a real browser and not an html webview, that you coded on your own, you should be covered.

**Comment by twMat** [comment]
@lixiepeng - how is this a [BUG]? And even if it was, your headline is very un-informative.
Please close this Issue thread and please post general coding questions in the Discussions section here on gh.
Thanx. :-)

**Comment by saqimtiaz** [comment]
> How can I trust html to allow js exec when I create html format doc?

Are you by any chance talking about exporting static HTML files with JavaScript in them?

**Comment by lixiepeng** [comment]
maybe create a custom plugin is a better choice, the default html format doc is just a html webview.
