### ISSUE TITLE
Provide shadows for all system configuration tags

### ISSUE THREAD

**Issue by giffmex** [Jermolene/TiddlyWiki5#565]
This feature would allow the use of a list field to order elements in the top menus in the same way other page elements can be ordered.

**Comment by pmario** [comment]
I had a look at all shadow tiddlers with the prefix `$:/tags` ... 
Every single one of the, which uses the list field has a physical representation. 

For the 2 "new" ones requested in the OP IMO it's not necessary, since the core doesn't use them. If someone needs some custom sorting they have to create the tiddlers anyway. 

@Jermolene I think this issue can be closed 

The exsting tags are: I will create a new PR to update http://tiddlywiki.com/#SystemTags soon. 

```
$:/tags/Alert
$:/tags/AboveStory
$:/tags/AdvancedSearch
$:/tags/AdvancedSearch/FilterButton
$:/tags/ControlPanel
$:/tags/ControlPanel/Advanced
$:/tags/ControlPanel/Appearance
$:/tags/ControlPanel/Info
$:/tags/ControlPanel/Settings
$:/tags/ControlPanel/Saving
$:/tags/ControlPanel/Toolbars
$:/tags/EditorToolbar
$:/tags/EditPreview
$:/tags/EditPreview
$:/tags/EditTemplate
$:/tags/Exporter
$:/tags/Filter
$:/tags/Filter
$:/tags/HelpPanel
$:/tags/HelpPanel/Videos
$:/tags/Image
$:/tags/Macro
$:/tags/Manager/ItemMain
$:/tags/Manager/ItemSidebar
$:/tags/MakeQR
$:/tags/MoreSideBar
$:/tags/MoreSideBar/Plugins
$:/tags/MoreSideBar
$:/tags/Palette
$:/tags/PageTemplate
$:/tags/PageControls
$:/tags/PluginLibrary
$:/tags/RawMarkup
$:/tags/RawMarkupWikified
$:/tags/RawStaticContent
$:/tags/RemoteAssetInfo
$:/tags/SearchResults
$:/tags/ServerConnection
$:/tags/SideBar
$:/tags/Stylesheet
$:/tags/TagDropdown
$:/tags/TiddlerInfo
$:/tags/TiddlerInfo/Advanced
$:/tags/ToolbarButtonStyle
$:/tags/TopLeftBar
$:/tags/TopRightBar
$:/tags/TranslationGroup
$:/tags/TextEditor/Snippet
$:/tags/TwitterUsage
$:/tags/ViewTemplate
$:/tags/ViewToolbar
$:/tags/ViewToolbarButton/QRcode

$:/tags/test-spec
```

**Comment by pmario** [comment]
uups ... I forgot to mention @giffmex :)

**Comment by gernert** [comment]
Hi @pmario,

Just a few days ago I made PR #2862 to extend the list of system tags. Upen quick inspection your list of system tags is longer than mine, but I miss $:/tags/BelowStory (a few 'doubles' in your list: $:/tags/Filter, $:/tags/MoreSideBar).
Do you want me to close #2862?

**Comment by pmario** [comment]
@giffmex ... All elements that use tags to be listed, are drag&drop sortable now. see: $:/tags/PageControls  
@Jermolene ... imo can be closed

**Comment by Jermolene** [comment]
Thanks @pmario
