### ISSUE TITLE
[BUG] ServerEvents causes exception on IE

### ISSUE THREAD

**Issue by saqimtiaz** [Jermolene/TiddlyWiki5#5663]
Starting the node server for the server edition and loading a wiki in IE 11 triggers a red error message screen. Console shows that "EventSource is undefined" originating from https://github.com/Jermolene/TiddlyWiki5/blob/master/plugins/tiddlywiki/tiddlyweb/sse-client.js#L43

Perhaps we need to start seriously considering a strategy to phase out IE support (#5192) or find a way for ServerEvents to fail gracefully on IE.

**Comment by saqimtiaz** [comment]
While testing other things in IE I've had a weird instance of data loss that I think may be due to this issue. While editing a tiddler, I've had the contents of the editor suddenly replaced with an older version of the tiddler that was open for editing in another browser.

**Comment by Jermolene** [comment]
Thanks @saqimtiaz.

> Starting the node server for the server edition and loading a wiki in IE 11 triggers a red error message screen. Console shows that "EventSource is undefined" originating from https://github.com/Jermolene/TiddlyWiki5/blob/master/plugins/tiddlywiki/tiddlyweb/sse-client.js#L43

Fix coming up.

> Perhaps we need to start seriously considering a strategy to phase out IE support (#5192) or find a way for ServerEvents to fail gracefully on IE.

The system needs in any case to be resilient to server sent events not being available due to transport issues.

I'm keen to retain IE11 support for as long as we can (not least because IE11 is still quite common in the UKs National Health Service).

**Comment by saqimtiaz** [comment]
Thank you @Jermolene 

> (not least because IE11 is still quite common in the UKs National Health Service).

A very valid reason to keep supporting IE11 and definitely one I can get behind.
