### ISSUE TITLE
[BUG?] Extraneous click event listener in DropZone widget?

### ISSUE THREAD

**Issue by saqimtiaz** [Jermolene/TiddlyWiki5#5675]
The `<$dropzone>` widget adds a [click event listener](https://github.com/Jermolene/TiddlyWiki5/blob/master/core/modules/widgets/dropzone.js#L52) to its DOM node but doesn't do anything in the handler. Does it serve a purpose?

I wanted to use the click event to clear the state of the <$dropzone> widget, i.e. remove the `tc-dragover` class and set `currentlyEntered = []` as mitigation towards the incorrect persistence of the dragover class (as in explained in #5616).

**Comment by Jermolene** [comment]
Hi @saqimtiaz I think that is a mistake, and can be removed.
