### ISSUE TITLE
currentTiddler variable and inconsistency in subfilter operators

### ISSUE THREAD

**Issue by saqimtiaz** [Jermolene/TiddlyWiki5#5683]
Currently we do not have consistency in what the value of `currentTiddler` is set to for filters operators that implement subfilters which are invoked once for each input title:

- `filter[]` : unchanged value for `currentTiddler`
- `reduce[]` : the value of `currentTiddler` is set to the respective title each time, allowing use of syntax like `{!!text}` within the subfilter
- `sortsub[]` : the value of `currentTiddler` is set to the respective title each time, allowing use of syntax like `{!!text}` within the subfilter

Similarly the `:reduce` and `:sort` filter run prefixes set the value of `currentTiddler` to the respective title but `:filter` does not.

This inconsistency between `filter[]` and the other two subfilter operators is confusing. Can we reasonably still change this behaviour for `filter[]` to make it consistent with the other two operators? Note that until now using variables in the operand to the `filter[]` operator has not been possible due to the bug recently resolved in #5640 for TW 5.1.24. This should help with backwards compatibility concerns.

Alternatively we could use a filter operator suffix to control what to set the value of currentTiddler to.

Furthermore, having a way to reference the value of `currentTiddler` from the main filter run can still be useful. This could be made available in the subfilter under a different variable name. I haven't given much thought to names but something indicating that this is the value of `currentTiddler` outside the subfilter. A (not ideal) example is `outerCurrentTiddler`.

**Comment by Jermolene** [comment]
> Currently we do not have consistency in what the value of `currentTiddler` is set to for filters operators that implement subfilters which are invoked once for each input title:

It would be great to address this.

> This inconsistency between `filter[]` and the other two subfilter operators is confusing. Can we reasonably still change this behaviour for `filter[]` to make it consistent with the other two operators? Note that until now using variables in the operand to the `filter[]` operator has not been possible due to the bug recently resolved in #5640 for TW 5.1.24. This should help with backwards compatibility concerns.

Cunning, yes, I think you're right that does make it reasonable to change things.

> Furthermore, having a way to reference the value of `currentTiddler` from the main filter run can still be useful. This could be made available in the subfilter under a different variable name. I haven't given much thought to names but something indicating that this is the value of `currentTiddler` outside the subfilter. A (not ideal) example is `outerCurrentTiddler`.

That's not bad, I'm struggling to think of anything better...
