### ISSUE TITLE
Eventcatcher: make it easier to trap events and do nothing

### ISSUE THREAD

**Issue by saqimtiaz** [Jermolene/TiddlyWiki5#5684]
Currently if there are no actions defined for an event, the `<$eventcatcher>` widget [does not trap the event and allows it to propagate](https://github.com/Jermolene/TiddlyWiki5/blob/master/core/modules/widgets/eventcatcher.js#L87). This was presumably to guard against missing actions attributes.

However, if you just want to stop propagation for some events (and do not want to invoke actions) you have to use a dummy non blank action string. For example:

```
\define dummyActions() NULL

<$eventcatcher events="dragenter dragleave dragover" actions-dragenter=<<dummyActions>> actions-dragleave=<<dummyActions>> actions-dragover=<<dummyActions>> selector=".tc-editor-toolbar">
```

instead of something simpler like:

`<$eventcatcher events="dragenter dragleave dragover" selector=".tc-editor-toolbar">`

- Is it too late to change the current behaviour for when the actions are blank or not defined? 
  - If so can we try to make the above use case more elegant? 
- Perhaps an extra attribute that can be used to always trap events even if actions are not defined? `alwaysCatch="yes"` ?

An alternative approach - which might be useful in its own right - would be to fall back to an `actions` attribute (if present) if an event does not have a specific actions attribute defined for it. One would still need to define dummy non blank actions for the above use case, but the widget could be invoked more concisely:

```
\define dummyActions() NULL

<$eventcatcher events="dragenter dragleave dragover" actions=<<dummyActions>> selector=".tc-editor-toolbar">
```

**Comment by pmario** [comment]
> - Is it too late to change the current behaviour for when the actions are blank or not defined? 

Why? .. I'm pretty sure, nobody except you uses it atm. ...

**Comment by saqimtiaz** [comment]
> Why? .. I'm pretty sure, nobody except you uses it atm. ...

@pmario I had the same thought but I checked and @BurningTreeC's Muuri plugin uses it and there could be others using it apart from me and @Jermolene.

**Comment by pmario** [comment]
I would fix it. @BurningTreeC what do you think?

**Comment by CodaCodr** [comment]
I use it - a bit ;)

**Comment by pmario** [comment]
> - Perhaps an extra attribute that can be used to always trap events even if actions are not defined? alwaysCatch="yes" ?

What about `stopBubbling = always` other possibilities may be `never, onaction`

`never` ... will always bubble the event, even if an action has been executed. 
`onaction` ... DEFAULT ... executing an action will stop bubbling. 

This will give us all possibilities, that users may need.

**Comment by saqimtiaz** [comment]
> What about `stopBubbling = always` other possibilities may be `never, onaction`

@pmario I like this suggestion and it would also accommodate one of @CodaCodr's [previous requests](https://github.com/Jermolene/TiddlyWiki5/discussions/5450). `stopPropagation` might be a more intuitive name.

One caveat to keep in mind is that a single `<$eventcatcher>` can handle multiple events each with their own actions. The stopBubbling attribute would apply to all events handled by the same widget. I think this is fine as long as it is properly documented.

Thoughts @Jermolene ?
