### ISSUE TITLE
[BUG] The sortan returns the RSOD when is used with tags field

### ISSUE THREAD

**Issue by kookma** [Jermolene/TiddlyWiki5#5701]
**Describe the bug**
The `sortan` returns the RSOD when is used with tags field

**To Reproduce**

1. Open http://tiddlywiki.com/prerelease
2. Create a tiddler with below contents and save

```
<$list filter="[tag[About]sortan[tags]]"/>
```

3. The Red window of Death has appeared!

4. See the error

![img_172_chrome](https://user-images.githubusercontent.com/830394/118703125-fc8a6e80-b82a-11eb-9b38-71bb4b61c276.png)

**Expected behavior**
See https://groups.google.com/g/tiddlywiki/c/Oc_wjhv_9Og/m/PFGm_LdtAQAJ

**Screenshots**

**TiddlyWiki Configuration (please complete the following information):**
 - 5.1.24pre
 
**Desktop (please complete the following information):**
 - OS:  Windows 10
 - Browser Chrome 90

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Jermolene** [comment]
Thanks @kookma fix upcoming
