### ISSUE TITLE
Make date format configurable

### ISSUE THREAD

**Issue by Jermolene** [Jermolene/TiddlyWiki5#571]
It would be useful if the user could customise the date format used in tiddler subtitles without having to modify the `$:/core/ui/ViewTemplate/subtitle` shadow tiddler.

**Comment by pmario** [comment]
v5.1.0 was: https://tiddlywiki.com/archive/full/TiddlyWiki-5.1.0.html#:$:/core/ui/ViewTemplate/subtitle  hardcoded
v5.3.0-pre is: https://tiddlywiki.com/prerelease/#%24%3A%2Fcore%2Fui%2FViewTemplate%2Fsubtitle flexible.

@Jermolene ... Feature was implemented. .. IMO issue can be closed

**Comment by Jermolene** [comment]
Hi @pmario I think the relevant shadow tiddler is actually this one:

https://tiddlywiki.com/prerelease/#%24%3A%2Fcore%2Fui%2FViewTemplate%2Fsubtitle%2Fmodified
