### ISSUE TITLE
[BUG] tm-download-file doesn't like <variable>s in exportFilter

### ISSUE THREAD

**Issue by xcazin** [Jermolene/TiddlyWiki5#5716]
When given an _exportFilter_ parameter containing variables, for instance `[list<tv-story-list>]`, _action-message_ crashes on the tm-download-file message, while it accepts the variable-free equivalent, for instance `[[$:/StoryList]get[list]enlist-input[]]`.

**Steps to reproduce the behavior**:
1. Copy `[list<tv-story-list>]` in your clipboard
2. Paste it into the edit-text input area of the AdvancedSearch Filter tab in the public TW site : https://tiddlywiki.com
3. Choose any exporter via the _Export tiddlers_ button 

**Expected behavior**
The `[list<tv-story-list>]` filter should trigger the same result than its functional equivalent `[[$:/StoryList]get[list]enlist-input[]]`, that is a dialog box to save a file for the chosen exporter. Any filter containing a `<variable>` notation triggers the same bug. Note that the other _soft_ notation `{}` doesn't trigger the bug. 

Also note that Firefox and Chrome don't display the same error (see below). 

**Screenshots**
See screenshots of what the above sequences trigger:
<img width="494" alt="Capture d’écran 2021-05-22 à 13 49 18" src="https://user-images.githubusercontent.com/1314688/119226729-f1755e00-bb0a-11eb-99b6-efb27b100dc8.png">
Chrome 90.0.4430.212 on MacOS 10.14.6 :
<img width="703" alt="Capture d’écran 2021-05-22 à 15 07 53" src="https://user-images.githubusercontent.com/1314688/119227707-8aa67380-bb0f-11eb-960c-a7d1178dc37b.png">
Firefox 88.0.1 on MacOS 10.14.6 :
<img width="497" alt="Capture d’écran 2021-05-22 à 13 50 14" src="https://user-images.githubusercontent.com/1314688/119226737-fd612000-bb0a-11eb-8376-d5dfd4ac467d.png">

**TiddlyWiki Configuration:**
 - Tested on versions v5.1.23 and 5.1.24-prerelease

**Comment by Jermolene** [comment]
Thanks @xcazin. A "red screen of embarrassment" that can be provoked entirely with wikitext is always a bug, but in this case fixing the bug won't help a further problem: the `tv-story-list` variable is set by the navigator widget and so is local to a particular subtree of the widget tree, but the export operation is effectively global and so can't access that value.

A fix for the RSOE is coming up.
