### ISSUE TITLE
TW 5.2.0 release imminent - last call for bug fixes and outstanding PRs

### ISSUE THREAD

**Issue by saqimtiaz** [Jermolene/TiddlyWiki5#5717]
**The next release of TiddlyWiki, likely to be version 5.2.0, will be released in the next 2-3 weeks.**

This is a last call for any bug fixes, as well as for finalizing any existing PRs that are already under discussion and close to being resolved. Changes that have not already been raised, or that need further discussion or testing, will likely be tabled until after the release.

_Please note that TiddlyWiki 5.2.0 will bring a change in the format and structure of the tiddler `storeArea` in the single file version as discussed in #5708._ 

Tools and services that parse the TiddlyWiki HTML file directly may be impacted. If you can think of any besides TiddlyHost and TiddlyClip that might be affected, please let us know.

Edit:
- release notes (last updated May 6th, 2021): https://tiddlywiki.com/prerelease/#TiddlyWiki%20Pre-release
- Git change history for this release: https://github.com/Jermolene/TiddlyWiki5/compare/v5.1.23...master

**Comment by saqimtiaz** [comment]
ping @pmario @joshuafontany @rmunn @simonbaird @buggyj @BurningTreeC

**Comment by Jermolene** [comment]
Adding @danielo515

**Comment by danielo515** [comment]
Any changes to the widget hierarchy or to the way sync mechanisms work?

**Comment by saqimtiaz** [comment]
@danielo515 widget hierarchy and sync mechanism remains unchanged. There is an optional server sent events capability introduced and used with the tiddlyweb syncer if enabled, see #5279

**Comment by kookma** [comment]
Is there any plan to drop some very old features back to 2004? For example does TW 5.2.x will support IE6 and before?
Except the big change in tiddler store area, is there any check list to see what will be changed?

**Comment by saqimtiaz** [comment]
> Is there any plan to drop some very old features back to 2004? For example does TW 5.2.x will support IE6 and before?

@kookma Not at this time.



> Except the big change in tiddler store area, is there any check list to see what will be changed?

There are links to the release notes and git history in the original post.

**Comment by kookma** [comment]
Hi Saq,
 
 Thank you! I see the release not!

Minor comment:
I am not in details! But some refactoring and look at the list of previous PR/Issues would be great!

**Comment by rmunn** [comment]
Thanks for the warning: I'll try to speed up my work on #5613 so it can get in before the release.

**Comment by danielo515** [comment]
> @danielo515 widget hierarchy and sync mechanism remains unchanged. There is an optional server sent events capability introduced and used with the tiddlyweb syncer if enabled, see #5279

I saw that already, thanks

**Comment by simonbaird** [comment]
I don't have any requests for inclusion, but I have a suggestion on how to track it.

Each issue that is considered a 5.2.0 blocker could be given a particular label, such as "5.2.0-blocker", then you'll know you're ready to release when the list of open issues in that label is empty.

**Comment by twMat** [comment]
@rmunn 
>Thanks for the warning: I'll try to speed up my work on #5613 so it can get in before the release.

Any chance of this making it?

**Comment by Arlen22** [comment]
I just found a couple problems with the Server Sent Events that I'm working on at the moment. 

- The server is incomplete and does not conform to the Socket Sent Events spec completely. I am finishing up a fix for this today. 
- The sse-enabled paramater does not actually seem to enable the events. I'm investigating this today and may need to change the format and docs slightly.

**Comment by Jermolene** [comment]
> I just found a couple problems with the Server Sent Events that I'm working on at the moment.
> 
> * The server is incomplete and does not conform to the Socket Sent Events spec completely. I am finishing up a fix for this today.
> * The sse-enabled paramater does not actually seem to enable the events. I'm investigating this today and may need to change the format and docs slightly.

Thanks @Arlen22, much appreciated

**Comment by pmario** [comment]
>The sse-enabled paramater does not actually seem to enable the events. I'm investigating this today and may need to change the format and docs slightly.

The `sse-enabled` parameter did work for me. So could you be more specific?

**Comment by Arlen22** [comment]
> > The sse-enabled paramater does not actually seem to enable the events. I'm investigating this today and may need to change the format and docs slightly.
> 
> The `sse-enabled` parameter did work for me. So could you be more specific?

My bad there. I had the wrong format.

**Comment by saqimtiaz** [comment]
The following still need resolution before the next release:
- revert Server Sent Events commits
- new JSON store area #5708 
- fix an issue with the ListWidget where the new `<counter-variable-name>-last `variable is not always accurately updated when items are removed from the end of the list. (Details in the discussion at #5867).

@Jermolene can you think of anything else?

**Comment by pmario** [comment]
IMO there are 2 files left in the Server Sent Events PR from Arlen, that need to be part of the core. @Arlen22 ... Can you create a new PR for what's left to be in the core?

**Comment by Jermolene** [comment]
Thanks @saqimtiaz @pmario.

I think we're now in good shape to merge #5708, and make an announcement to the mailing list asking for help with testing, and reissue the final call here on GitHub. Your help is much appreciated with the SSE stuff and #5867.

**Comment by saqimtiaz** [comment]
This week is hectic for me, but I'll try to find time to worm on the ListWidget issues towards the end of it. My focus will be to fix the current bug with the `-last` variable as I think that can be done relatively easily without a significant further performance hit.

**Comment by Arlen22** [comment]
> IMO there are 2 files left in the Server Sent Events PR from Arlen, that need to be part of the core. @Arlen22 ... Can you create a new PR for what's left to be in the core?

I'll remove the files that don't belong so that PR can be merged in.

**Comment by Jermolene** [comment]
> This week is hectic for me, but I'll try to find time to worm on the ListWidget issues towards the end of it. My focus will be to fix the current bug with the `-last` variable as I think that can be done relatively easily without a significant further performance hit.

Thanks @saqimtiaz, much appreciated.

> I'll remove the files that don't belong so that PR can be merged in.

Thanks @Arlen22 @pmario.

What about the original SSE PR #5279? I'd really like to minimise the SSE footprint in the core until thing settle down.

**Comment by Jermolene** [comment]
Just to point out that #5708 has now been merged, so this is a great time to test that everything we've got still works.

**Comment by pmario** [comment]
>What about the original SSE PR #5279? I'd really like to minimise the SSE footprint in the core until thing settle down.

I think it should be reverted. 

There are changes in 2 files in the @Arlen22 's PR https://github.com/Jermolene/TiddlyWiki5/pull/5853/files

 - plugins/tiddlywiki/tiddlyweb/tiddlywebadaptor.js 
 - core/modules/syncer.js

Those changes need to go to the core, since they are needed to disable the 1 minute client-side polling in the tiddlywebadaptor and activate the plugin, if server status is requested in syncer.js

**Comment by Arlen22** [comment]
I believe https://github.com/Jermolene/TiddlyWiki5/pull/5853 reverts everything from https://github.com/Jermolene/TiddlyWiki5/pull/5279. 

The code for SSE is now at https://github.com/twcloud/tiddlyweb-sse

**Comment by Arlen22** [comment]
#5882 should be ready to merge. This includes isPollingDisabled and the status hook.

**Comment by Jermolene** [comment]
It's now 128 days since @saqimtiaz opened this ticket. Development on v5.2.0 has continued as we've worked through a number of issues and opportunities. I think we're now getting to close the final release, so I'm closing this ticket and creating a new one.

**Comment by Sunzijie** [comment]
- Any changes to the widget hierarchy or to the way sync mechanisms work?

**Comment by pmario** [comment]
>Any changes to the widget hierarchy or to the way sync mechanisms work?

@Sunzijie .. Can you be a bit more specific. The pre-release notes are here: https://tiddlywiki.com/prerelease/#TiddlyWiki%20Pre-release  ...  The "badges" link to the PR at GitHub. So you can exactly see what was going on. .. If the code is not yours, the description has to do ;)

**Comment by Jermolene** [comment]
Hi @Sunzijie 

> * Any changes to the widget hierarchy 

I'm not sure what you mean. There are a couple of new widgets.

The hierarchy of widgets that makes up the page has some minor changes, but the overall structure is unchanged.

> or to the way sync mechanisms work?

There are some minor tweaks, but there shouldn't be anything that breaks compatibility with existing sync adaptors. You can see changes to the syncer here:

https://github.com/Jermolene/TiddlyWiki5/commits/master/core/modules/syncer.js
