### ISSUE TITLE
[IDEA] - keyboard widget should support data-attributes

### ISSUE THREAD

**Issue by BurningTreeC** [Jermolene/TiddlyWiki5#5741]
**Is your feature request related to a problem? Please describe.**
In my PR #5695 I'm surrounding the `div` of the `tc-tiddler-frames` with 4 keyboard widgets, where the first one needs to create a `div` in order for the storyview-animations to work correctly. Now I also found, that my `muuri storyview plugin` (https://github.com/BurningTreeC/tiddlywiki-muuri) needs that first div to be of class `tc-tiddler-frame`.

**Describe the solution you'd like**
The optimal solution would be to set the classes (`tc-tiddler-frame` etc.) on that first div created by the keyboard widget and all data-attributes (and attributes like tabindex), too.

**Comment by saqimtiaz** [comment]
Makes sense. Also see #5265

**Comment by BurningTreeC** [comment]
Thanks @saqimtiaz , I've updated the OP

**Comment by Jermolene** [comment]
Indeed, I think this is a dupe of #5265. The discussion there is a bit intertwined but there are really two proposals:

1. Proposal for supporting more declarative widget definitions
2. Proposal to add consistent support for DOM features (classes, data- attributes) for all widgets that generate DOM nodes (ie keyboard, button etc.)

**Comment by BurningTreeC** [comment]
Thanks @Jermolene, then I'll close this one here and revive #5265

**Comment by pmario** [comment]
With my "custom-markup" plugin, I do use an **older custom** version of the keyboard widget. ... I'll need to modify the code and use the new core-version.

**Comment by pmario** [comment]
I think, we will need to modify this function: https://github.com/Jermolene/TiddlyWiki5/blob/3a740b23bb80c12c802df4e352af67bd87248ea1/core/modules/keyboard.js#L219 to give use the "resolved key-code and the abstract shortcut info back". ... So we do have enough info, to pass it on to the action-widget as an additional variable.

**Comment by saqimtiaz** [comment]
@pmario I prototyped this when we first discussed it. I will prepare a PR when I get the chance.
