### ISSUE TITLE
[BUG] Non-action widgets are not refreshed before invocation

### ISSUE THREAD

**Issue by Jermolene** [Jermolene/TiddlyWiki5#5744]
**Describe the bug**
Action widgets are refreshed just before they are invoked, but this is not done for non-action widgets.

The refreshing is done to ensure that the computed values of attributes are up-to-date with the latest changes to the tiddler store. Because this doesn't happen for non-action widgets, their attributes will not necessarily contain the correct data.

**To Reproduce**
1. Go to https://tiddlywiki.com
2. Create a new tiddler
3. Paste the code below
4. Click "done" to finish editing the tiddler
5. Click the button labelled "Test me"

```
<$button>
<$action-createtiddler $savetitle="$:/temp/title" $basetitle="My New Tiddler"/>
<$vars title={{$:/temp/title}}>
<$action-log/>
<$action-navigate $to=<<title>>/>
</$vars>
Test me
</$button>
```

**Expected behavior**
The tiddler "My New Tiddler" should open. However, what actually happens is that no tiddler is opened. Using the browser JS console, one can see from the variable log that the variable "title" doesn't contain the correct value.

**Comment by Jermolene** [comment]
Once https://tiddlywiki.com/prerelease has finished building you can verify that the example given above now works.

**Comment by saqimtiaz** [comment]
Excellent, thank you @Jermolene

**Comment by saqimtiaz** [comment]
@Jermolene unfortunately this seems to have consequences we didn't foresee.

As reported by @BurningTreeC:
> on the current prerelease page, if we open the preview pane of a tiddler then it's not possible to close it anymore.

I haven't had the chance to investigate properly but I am guessing it has something to do with the refresh of the reveal widgets:

https://github.com/Jermolene/TiddlyWiki5/blob/2e695801b186cdadb888e6249375f19548bc058a/core/ui/EditorToolbar/preview.tid#L11-L18

**Comment by Jermolene** [comment]
No worries, thank you @saqimtiaz I've reverted the merge for the moment: 4f9dd50382b98239b8f611fb513e67146ab3d03a

**Comment by saqimtiaz** [comment]
@Jermolene I believe you have reverted the wrong commit. This bug seems to be introduced by the changes to `widget.invokeActions` and not the changes to the `transclude` widget.

**Comment by saqimtiaz** [comment]
This commit seems to be the culprit for this bug: https://github.com/Jermolene/TiddlyWiki5/commit/582b156d5f2b9b8b92f9289aa1288e1edb637450

**Comment by Jermolene** [comment]
> @Jermolene I believe you have reverted the wrong commit. This bug seems to be introduced by the changes to `widget.invokeActions` and not the changes to the `transclude` widget.

Whoooops! I'll try to disentangle it shortly...

**Comment by saqimtiaz** [comment]
@Jermolene you should be able to revert the revert.

`git revert 4f9dd50`

**Comment by Jermolene** [comment]
Thanks @saqimtiaz I *think* I've re-reverted the erroneous commit, and reverted the culprit.

**Comment by saqimtiaz** [comment]
@Jermolene thank you, that looks correct. 

It is a shame this change for action widget invocation didn't work out.

**Comment by Jermolene** [comment]
> I haven't had the chance to investigate properly but I am guessing it has something to do with the refresh of the reveal widgets:

That's correct. When invoking the actions to hide the preview pane, the first reveal widget is enabled, and so the setfield action is run to turn off the preview pane. However, immediately afterwards, it considers the second reveal widget, and refreshes it, and thus gets the newly set value of the config tiddler.

So, that means that there's at least one place in the core that relies on the old behaviour. Very frustrating; I'm finding the new semantics make writing complex action strings significantly simpler and more transparent.

One thing we could explore to get around things is to start support pragmas within action strings. Then we could allow them to opt into the improved semantics:

```
\define myactions()
\evaluate strict
...actions...
\end

<$button actions=<<myactions>>>
Push
</$button>
```

**Comment by pmario** [comment]
>So, that means that there's at least one place in the core that relies on the old behaviour. Very frustrating; I'm finding the new semantics make writing complex action strings significantly simpler and more transparent.

Since 5.2.0 will have some incompatibilities anyway, We may be able to "fix the one place in the core".
