### ISSUE TITLE
[IDEA] create a list of tiddlers/subtiddlers from a tiddler "template"

### ISSUE THREAD

**Issue by aalberici** [Jermolene/TiddlyWiki5#5753]
hello all,

**Is your feature request related to a problem? Please describe.**
i would like to be able to copy a tiddler and all the tiddlers related to it, using one specific tag, in a sort of templating system

**Describe the solution you'd like**
Having a new choice near the "clone" tiddler option in the tiddler view
![image](https://user-images.githubusercontent.com/2809249/120801365-5c7a5800-c541-11eb-9d80-f8d631bae8cd.png)

A macro / an action as long we don't change TW core, is fine

**Additional context**
just as an example 
![image](https://user-images.githubusercontent.com/2809249/120809146-1675c200-c54a-11eb-9c66-28d7c1b1444b.png)

**Comment by saqimtiaz** [comment]
@aalberici Welcome to the project. As a general rule we use Github for issues related to changes in the core. Other questions about usage and customization are usually better posted in the [Google Group](https://groups.google.com/g/tiddlywiki), where there are a lot more active users and you will likely get a lot more feedback.

There are several ways to go about this and it depends as well on how you want the cloned tiddlers presented. Do you want them created in the background or open for editing in the story?

As a starting point you can clone the tiddler `$:/core/ui/Buttons/clone` and customize it to clone more than one tiddler.

Here is some pseudo-code:
```
<$list filter="[tag[mytag]]">
<$action-sendmessage message="tm-new-tiddler" param=<<currentTiddler>>/>
</$list>
```
