### ISSUE TITLE
tm-focus-selector doesn't work in new windows

### ISSUE THREAD

**Issue by BurningTreeC** [Jermolene/TiddlyWiki5#5760]
**Describe the bug**
When I open the `$:/core/ui/PageTemplate` tiddler in a new window and try to focus the `sidebar-search` via `ctrl-shift-F`, `document.querySelector` finds the `sidebar-search` in the root tiddlywiki window, not the one in the newly opened window

**Expected behavior**
`ctrl-shift-F` in the new window focuses the sidebar-search of the new window

**TiddlyWiki Configuration (please complete the following information):**
 - latest prerelease

**Comment by Jermolene** [comment]
Thanks @BurningTreeC can you see a fix for this?

**Comment by BurningTreeC** [comment]
> Thanks @BurningTreeC can you see a fix for this?

No @Jermolene, I tried fixing this but wasn't successful

**Comment by saqimtiaz** [comment]
I haven't looked at the code for this recently but I think there are two issues here.

1. The listener for `tm-focus-selector` needs to get the reference to document from the event.

`var doc = event.event ? event.event.target.ownerDocument : document`
Note that here event refers to the widget message where as `event.event` is the original DOM event.

2. Actions invoked by keyboard shortcuts are invoked by the `root` widget. In `keyboard.js` when we invoke the actions triggered by keyboard shortcuts, if we do not already do so we need to pass the original event as the third argument to `invokeActionString`.

**Comment by Jermolene** [comment]
Thanks @saqimtiaz that sounds right.
