### ISSUE TITLE
[BUG] - White border below framed editor - what has changed?

### ISSUE THREAD

**Issue by BurningTreeC** [Jermolene/TiddlyWiki5#5768]
**Describe the bug**
In the current prerelease below the textarea of the framed text-editors, there's a white border of 14px of height
This doesn't show in the current 5.1.23 version. What has changed in this regard from 5.1.23 to 5.1.24?

**To Reproduce**
1. Go to https://tiddlywiki.com/prerelease
2. Choose a dark palette
3. Open a tiddler for editing
4. See the white border below the framed editor
5. Compare with 5.1.23

**Expected behavior**
The white area should have the color of the tiddler-frame background-color

**Comment by saqimtiaz** [comment]
On that note, why do we have this arbitrary 14px added to the iframe height?

https://github.com/Jermolene/TiddlyWiki5/blob/c18b7527a761bd7da6c603444dd029cfcca55cdc/core/modules/editor/engines/framed.js#L165

 It is a nuisance when trying to use the framed editor within other content, one always has to resort to complicated CSS to compensate for it.

**Comment by BurningTreeC** [comment]
> On that note, why do we have this arbitrary 14px added to the iframe height?
> 
> https://github.com/Jermolene/TiddlyWiki5/blob/c18b7527a761bd7da6c603444dd029cfcca55cdc/core/modules/editor/engines/framed.js#L165
> 
> It is a nuisance when trying to use the framed editor within other content, one always has to resort to complicated CSS to compensate for it.

@saqimtiaz , @Jermolene once mentioned that this was needed for something but I don't remember for what

**Comment by saqimtiaz** [comment]
This comment indicates its for the border, though that still doesn't seem logical considering the CSS:

https://github.com/Jermolene/TiddlyWiki5/blob/c18b7527a761bd7da6c603444dd029cfcca55cdc/core/modules/editor/engines/framed.js#L158-L159

**Comment by BurningTreeC** [comment]
Now I know who's the culprit. It's my PR #5720 ... I'll see if there's a workaround

**Comment by twMat** [comment]
@BurningTreeC wrote
>4. See the white border below the framed editor

I don't see anything:
![image](https://user-images.githubusercontent.com/4534056/121077137-89e03380-c7d7-11eb-8bbc-d7c33c05cc8b.png)

Brave/Chrome/FF

**Comment by BurningTreeC** [comment]
That's the codemirror editor @twMat

**Comment by twMat** [comment]
>That's the codemirror editor @twMat

OK. I just followed your instructions. Codemirror is installed in https://tiddlywiki.com/prerelease

**Comment by twMat** [comment]
Regarding the added 14px maybe it has something to do with #3237
