### ISSUE TITLE
[BUG] <<createdTiddler-title>> cannot be assigned to a variable within <$action-createtiddler />

### ISSUE THREAD

**Issue by xcazin** [Jermolene/TiddlyWiki5#5791]
**Describe the bug**
The value of the `createdTiddler-title` variable that has been made available since the new version of `<$action-createtiddler />` is not assignable to variables within the widget.

**To Reproduce**
1. Edit the first example of the latest `<$action-createtiddler/>` documentation : https://tiddlywiki.com/prerelease/#ActionCreateTiddlerWidget%20Example
2. Insert a variable assignment around the `<$action-navigate .../>` statement so that the text reads like the following:
```
Caption for new button: <$edit-text tiddler="$:/state/new-button-caption" tag="input" default=""/>

<$button>
<$action-createtiddler $basetitle="Homemade Button" tags="$:/tags/PageControls" text={{$:/state/new-button-caption}}>
<$vars foo=<<createTiddler-title>> >
<$action-navigate $to=<<foo>>/>
</$vars>
</$action-createtiddler>
Create a new non-functional page control button and open the tiddler
</$button>
```
3. Save content then click the button 
4. See how the newly created button is **not** navigated to anymore (instead, the `<<currentTiddler>>` is navigated to).

**Expected behavior**
The value of `<<createTiddler-title>>` should be made available to further variable assignment inside `<$action-createtiddler />`. I tried with `<$set />` and `<$macrocall />` parameter assignment as well: in every case, the variable that is set with `<<createTiddler-title>>` is void.

**TiddlyWiki Configuration:**
 - Latest v5.1.24 at  https://tiddlywiki.com/prerelease
 
**Desktop (please complete the following information):**
 - OS: MacOS
 - Browsers: Chrome 91 and Firefox 88

**Comment by saqimtiaz** [comment]
This is likely due to the PR that had to be reverted which refreshed widgets before action invocation.

@Jermolene since this ability for action-createtiddler is new and thus not constrained by backwards compatibility, we could refresh children here by calling `this.refreshChildren()` before the `return` statement.

https://github.com/Jermolene/TiddlyWiki5/blob/4f33d2f35cd2c34ca5edfcf062f23bd1ca7ef177/core/modules/widgets/action-createtiddler.js#L105-L107

**Comment by Jermolene** [comment]
Hi @xcazin @saqimtiaz the problem here is that without 582b156d5f2b9b8b92f9289aa1288e1edb637450 the `<$vars>` widget is not refreshed before it is invoked. You'll notice that the same problem does not occur if you insert `<$action-log message=<<createTiddler-title>>/>` before the vars widget because action widgets *are* always refreshed before invocation.

**Comment by saqimtiaz** [comment]
@Jermolene calling `this.refreshChildren()` at the end of `CreateTiddlerWidget.prototype.invokeAction` after we set the new variables, should at least ensure that all widgets within the `action-createtiddler` widget pick up the new variables being set by `action-createtiddler` such as `createTiddler-title`.

**Comment by Jermolene** [comment]
> @Jermolene calling `this.refreshChildren()` at the end of `CreateTiddlerWidget.prototype.invokeAction` after we set the new variables, should at least ensure that all widgets within the `action-createtiddler` widget pick up the new variables being set by `action-createtiddler` such as `createTiddler-title`.

Yes good idea, I'll commit that momentarily so I don't forget.

I've been experimenting with using a configuration variable to control action refreshing:

```js

Widget.prototype.invokeActions = function(triggeringWidget,event) {
	var handled = false;
	// For each child widget
	for(var t=0; t<this.children.length; t++) {
		var child = this.children[t],
			childIsActionWidget = !!child.invokeAction,
			actionRefreshPolicy = child.getVariable("tv-action-refresh-policy");
		// Refresh the child if required
		if(childIsActionWidget || actionRefreshPolicy === "always") {
			child.refreshSelf();
		}
		// Invoke the child if it is an action widget
		if(childIsActionWidget) {
			if(child.invokeAction(triggeringWidget,event)) {
				handled = true;
			}
		}
		// Propagate through through the child if it permits it
		if(child.allowActionPropagation() && child.invokeActions(triggeringWidget,event)) {
			handled = true;
		}
	}
	return handled;
};
```

I've tested it by putting `\define tv-action-refresh-policy() always` at the top of a tiddler containing actions defined as macros.

If we take this approach, I think we'd need to add a shortcut pragma like `\refresh always`, or possibly something shorter still if we can come up with it.

**Comment by saqimtiaz** [comment]
> I've tested it by putting `\define tv-action-refresh-policy() always` at the top of a tiddler containing actions defined as macros.
> 
> If we take this approach, I think we'd need to add a shortcut pragma like `\refresh always`, or possibly something shorter still if we can come up with it.

@Jermolene That looks like a good approach. A pragma would definitely be useful, not only for the brevity but so that it could be used within macros that define action strings.

**Comment by xcazin** [comment]
Thanks @saqimtiaz @Jermolene

**Comment by saqimtiaz** [comment]
> If we take this approach, I think we'd need to add a shortcut pragma like `\refresh always`, or possibly something shorter still if we can come up with it.

@Jermolene what if we treated just `\refresh` as being equivalent to `\refresh always` for brevity?

I assume we would just want the pragma to return a set widget akin to the `macrodef` pragma.

**Comment by Jermolene** [comment]
> > If we take this approach, I think we'd need to add a shortcut pragma like `\refresh always`, or possibly something shorter still if we can come up with it.
> 
> 
> 
> @Jermolene what if we treated just `\refresh` as being equivalent to `\refresh always` for brevity?
> 
> 
> 
> I assume we would just want the pragma to return a set widget akin to the `macrodef` pragma.

`/refresh` might be confusing because this isn't quite the usual usage of the word in a TiddlyWiki context.

I have wondered about taking advantage of the fact that we parse action strings in one place to support a really simple shortcut like `+` (ie something that would be printable in ordinary wikitext). But we also want users to use the new mode as a natural default (we can't make it a global default, but we can try to make it easy and natural to type). Or perhaps we could use parenthesis to wrap action widgets that should be fully refreshed:

```
\define myactions()
(<$action-blah foo=bar/>
<$action-blahblah bar=foo/>)
\end
```

I've also wondered about introducing a new optional attribute for specifying action strings which would automatically get the magic variable. For example: `<$button $actions=<<mynewactions>>/>` or `<$button onclick=<<mynewactions>>/>`.

**Comment by saqimtiaz** [comment]
Optimally we would want to add a new syntax in one place that would allow it to be used everywhere we use actions.

This is really off the top of my head and may also foster some confusion, but we could also support a new syntax for defining macros for actions:

```
\actions myactions()
<$action-.....>
\end
```

**Comment by pmario** [comment]
`<$button $actions=<<mynewactions>>/>` ... This change is so subtle, that I needed to read it 10+ times to get it. 
`<$button onclick=<<mynewactions>>/>` ... IMO the button widget is already overloaded ... 

So if we could go the "pragma route", I think it will make things easier

```
\define myActions()
\refresh actions
<$action-.....>
\end
```

IMO `\refresh actions` would give us the possibility to use the `\refresh` pragma for other things if we may need them in the future.

**Comment by Jermolene** [comment]
Hi @pmario the point about the proposals from @saqimtiaz and myself is that they allow us to eventually deprecate the current way of writing action strings. With the pragma route, we're stuck with people having to remember the strange requirement forever, even though we're already at the point where the only reason for the old functionality is backwards compatibility.

**Comment by Jermolene** [comment]
I've pushed the update to refresh all widgets in action strings if `tv-action-refresh-policy` is set to `always`, along with docs.

I've left the issue of introducing a shortcut for the moment.
