### ISSUE TITLE
[IDEA] :map filter run prefix

### ISSUE THREAD

**Issue by saqimtiaz** [Jermolene/TiddlyWiki5#5801]
**Proposal:** Introduce a new `:map` filter run prefix, which is invoked in turn for each input title with the output of the run replacing the input title. This will allow transforming each individual title with access to that title via the `currentTiddler` variable.

For example:

`[<...input titles...>] :map[get[caption]else{!!title}]`

Currently if one wants to do the same without changing the order of the input titles, the only option is a rather complicated usage of reduce:

`[<...input titles...>] :reduce[get[caption]else{!!title}format:titlelist[]addprefix[ ]addprefix<accumulator>] +[enlist-input[]]`

Other alternatives I have considered included a `map[]` operator, a suffix for the `get[]` operator which allows it to pass through unchanged titles that don't have the specified field, as well as a multi-operand form of `get[]` which returns the first field found in the tiddler: `get[field1],[field2],[field3]`. 

However I think the `:map` filter run prefix idea is more versatile.

**Comment by kookma** [comment]
Hi @saqimtiaz 
Is it possible to have operation like this

map all input tiddler if they include `xxx` phrase to the same title but `xxx` replaced with `yyy`

**Comment by saqimtiaz** [comment]
> map all input tiddler if they include `xxx` phrase to the same title but `xxx` replaced with `yyy`

I believe you can already do that with `search-replace[]`

**Comment by twMat** [comment]
Thinking about the OP I'm concluding that it hasn't been proposed earlier only because it is tricky to formulate ideas and understand what it is one needs, not because it is not important. I think the suggestion would immediately be *very* useful. Thanks for posting it Saq!

**Comment by Jermolene** [comment]
Good thinking @saqimtiaz that would be useful.

**Comment by saqimtiaz** [comment]
@Jermolene @twMat I will prepare a PR soon. The code is in place but I need to add documentation and tests.
