### ISSUE TITLE
[IDEA] Access to current date and time in filters.

### ISSUE THREAD

**Issue by saqimtiaz** [Jermolene/TiddlyWiki5#5830]
Currently there is no direct way to reference the current date and time in filters.
`<now>` returns the current date and time in `0hh:0mm, DDth MMM YYYY` format which makes it difficult to use with other operators.

The `format:date[]` operator supports formatting an input UTC date string (as used in the `created` and `modified` fields, i.e. `[UTC]YYYY0MM0DD0hh0mm0ssXXX`) according to a given template. If there was a macro or operator that provided the current date and time as a UTC date string, in combination with `format:date[]` this should be sufficient for most use cases.

Open to alternative ways to cater to the same use cases.

This came up for myself today when I needed to make sure an action was not fired more than once in a given period of time. There has also been a recent question on Discord by @sukima which involved checking if the current month was December or the 12th month. With access to the current date and time in `[UTC]YYYY0MM0DD0hh0mm0ssXXX` format this could be as simple as 
`[<now-timestamp>format:date[0MM]match[12]]`

Possible dupe of #5785 but I am not entirely sure what is being asked for there.

**Comment by Jermolene** [comment]
Good idea. Perhaps just `[<timestamp>]` might be OK?

**Comment by saqimtiaz** [comment]
@Jermolene Hah! `<timestamp>` is the working title I went with when I wrote a macro earlier today to use a stopgap until there was core support.

```
/*\
title: $:/core/modules/macros/timestamp.js
type: application/javascript
module-type: macro

Macro to return the current date and time as a [UTC]YYYY0MM0DD0hh0mm0ssXXX string.

\*/
(function(){

/*jslint node: true, browser: true */
/*global $tw: false */
"use strict";

/*
Information about this macro
*/

exports.name = "timestamp";
exports.params = [];

/*
Run the macro
*/
exports.run = function() {
	return $tw.utils.formatDateString(new Date(),"[UTC]YYYY0MM0DD0hh0mm0ssXXX");
};

})();

```

I will prepare a PR when I get the chance.

**Comment by Jermolene** [comment]
Hmmm just thinking aloud but one issue is that this looks a lot like the existing `<<now>>` macro but with a different default when there are no parameters so that it can be used more easily in filters.

Two alternative approaches:

* Fix things so that "[<variable>]" filter operands can take parameters, making it possible to use the existing `[<now>]` macro. But of course we would need to be able to do `[<now [UTC]YYYY0MM0DD0hh0mm0ssXXX>]` which isn't directly possible. Perhaps we could introduce a new shortcut for the date format language like `[<now !!!!>]` as a shortcut for the TW date format string...
* Make a new `[now[]]` operator which by default returns the timestamp in TW format, and is otherwise analogous to the `<<now>>` macro

**Comment by saqimtiaz** [comment]
Yes it is verbatim the same thing apart from the default. However, I couldn't think of a way to avoid the duplication and have that work in filters.

> * Make a new `[now[]]` operator which by default returns the timestamp in TW format, and is otherwise analogous to the `<<now>>` macro

I think this sounds like a sensible way to meet the use case without introducing complexity. 

Support for filter operands to take parameters is something we probably want to take a very considered approach to, and as you mentioned the square brackets would still be problematic in some use cases.

**Comment by Jermolene** [comment]
Great thanks @saqimtiaz

**Comment by saqimtiaz** [comment]
@Jermolene a couple of thoughts to run by you before I create a PR. 

One caveat with using an operator instead of a macro/variable is that this use case is no longer possible:

Get the tiddlers created today:
`[sameday<timestamp>]`

Also I was under the impression that every time a filter is run for a given input, it should always return the same result... or am I mistaken?

**Comment by Jermolene** [comment]
> One caveat with using an operator instead of a macro/variable is that this use case is no longer possible:
> 
> 
> 
> Get the tiddlers created today:
> 
> `[sameday<timestamp>]`

Ouch. Would that operation be safe from a timezone perspective anyhow?

> Also I was under the impression that every time a filter is run for a given input, it should always return the same result... or am I mistaken?

We've already got that problem given that one can write `[<now>]` as a filter. (It's JS macros that we normally talk about needing to be deterministic if they are used in the refresh process).

**Comment by saqimtiaz** [comment]
> > One caveat with using an operator instead of a macro/variable is that this use case is no longer possible:
> > Get the tiddlers created today:
> > `[sameday<timestamp>]`
> 
> Ouch. Would that operation be safe from a timezone perspective anyhow?

Hmm, not quite. It looks like `sameday[]` treats the operand as being UTC which is also what `<timestamp>` would output, so that part is OK. However depending on the user's timezone and when they use the filter, they may not get only the tiddlers created today. 

It would be good to be able to accommodate this use case in a single filter expression as I suspect its a rather common one, i.e. get tiddlers modified today. This is the best I can think of at the moment with a `now[]` operator.

```
<$vars today={{{ [now[]format:date[YYYY0MM0DD]] }}}>
[all[tiddlers]] :filter[get[created]format:date[YYYY0MM0DD]match<today>]
</$vars>
```

**Comment by Jermolene** [comment]
> Hmm, not quite. It looks like `sameday[]` treats the operand as being UTC which is also what `<timestamp>` would output, so that part is OK. However depending on the user's timezone and when they use the filter, they may not get only the tiddlers created today. 

Yes, the `sameday[]` operator is pretty broken, and I'm not sure that there's an obvious way to add support for using the local timezone. (The best I can think of is to add a second suffix, but the result would be a little awkward: `sameday:modified:local[blah]`)
 
> It would be good to be able to accommodate this use case in a single filter expression as I suspect its a rather common one, i.e. get tiddlers modified today. This is the best I can think of at the moment with a `now[]` operator.
> 
> 
> 
> ```
> 
> <$vars today={{{ [now[]format:date[YYYY0MM0DD]] }}}>
> 
> [all[tiddlers]] :filter[get[created]format:date[YYYY0MM0DD]match<today>]
> 
> </$vars>
> 
> ```

Again, it would be handy if we just support macro parameters in filters:

```
[all[tiddlers]] :filter[get[created]format:date[YYYY0MM0DD]match<now YYYY0MM0DD>]
```

Things would be a bit more convenient if we made a synonym for `[UTC]` that didn't use square brackets.

**Comment by Jermolene** [comment]
> Hmm, not quite. It looks like `sameday[]` treats the operand as being UTC which is also what `<timestamp>` would output, so that part is OK. However depending on the user's timezone and when they use the filter, they may not get only the tiddlers created today. 

Yes, the `sameday[]` operator is pretty broken, and I'm not sure that there's an obvious way to add support for using the local timezone. (The best I can think of is to add a second suffix, but the result would be a little awkward: `sameday:modified:local[blah]`)
 
> It would be good to be able to accommodate this use case in a single filter expression as I suspect its a rather common one, i.e. get tiddlers modified today. This is the best I can think of at the moment with a `now[]` operator.
> 
> 
> 
> ```
> 
> <$vars today={{{ [now[]format:date[YYYY0MM0DD]] }}}>
> 
> [all[tiddlers]] :filter[get[created]format:date[YYYY0MM0DD]match<today>]
> 
> </$vars>
> 
> ```

Again, it would be handy if we just support macro parameters in filters:

```
[all[tiddlers]] :filter[get[created]format:date[YYYY0MM0DD]match<now YYYY0MM0DD>]
```

Things would perhaps be a bit more convenient if we made a synonym for `[UTC]` that didn't use square brackets.

**Comment by saqimtiaz** [comment]
> Again, it would be handy if we just support macro parameters in filters

I've come around to the same conclusion. Every other solution I can think of involves synonyms for `now` with a parameter.

**Comment by saqimtiaz** [comment]
With the changes from #5836 in place, all of the following will be possible:

- Tiddlers created today:
  -  `[all[tiddlers]] :filter[get[created]format:date[YYYY0MM0DD]match<now YYYY0MM0DD>]`
- Check if the current month is December:
  - `[<now 0MM>match[12]]`
- current timestamp as UTC:
  - `[<now [UTC]YYYY0MM0DD0hh0mm0ssXXX>] `
  
I think that covers all the use cases I mentioned in this issue.
