### ISSUE TITLE
There is a breaking change in the current master

### ISSUE THREAD

**Issue by pmario** [Jermolene/TiddlyWiki5#5834]
Import the json into tiddlywiki.com and then into prerelease It has a different output. 

[breaking-change-5-23-5-24.zip](https://github.com/Jermolene/TiddlyWiki5/files/6726464/breaking-change-5-23-5-24.zip)

New Tiddler contains: 

```
<$tiddler tiddler=x>
<$transclude field=caption>

<$transclude field=title />

</$transclude>
</$tiddler>
```

x contains

```
title: x
caption: 

aa
```

**Comment by Jermolene** [comment]
Thanks @pmario please can you give some more details, it's not clear what "different output" means?

**Comment by pmario** [comment]
Since tiddler "x" contains an empty field: "caption"   there should be no text in New Tiddler. But in the prerelease there is the title "x"

**Comment by Jermolene** [comment]
I'm sorry @pmario are you trying to say that the tiddlers are imported differently? What exactly is the breaking change?

**Comment by saqimtiaz** [comment]
With a blank caption field, the below shows the title on the pre-release but does not on 5.1.23

```
<$transclude field=caption>

<$transclude field=title />

</$transclude>
```
The obvious culprit would be my PR #5736 though I did add extensive tests. I can investigate if that is the cause.

**Comment by saqimtiaz** [comment]
I have confirmed that this issue is introduced by #5736.

I will prepare a fix in a new PR later today. I am going to give it another once over to make sure we haven't missed anything else in the test coverage.

**Comment by Jermolene** [comment]
Great thanks @saqimtiaz @pmario
