### ISSUE TITLE
[IDEA] Drag and drop image path instead of including the image into the wiki

### ISSUE THREAD

**Issue by Telumire** [Jermolene/TiddlyWiki5#5854]
Currently the prerelease allow to drag&drop image into a tiddler, which is great. What I'm suggesting is to give the option to insert the image as an external image.

According to https://developer.mozilla.org/en-US/docs/Web/API/File, browsers do not give access to the file path. However, we can get the file name just fine : https://jsbin.com/vuyifovido/edit?html,js,output

Electron app [can access the file path](https://stackoverflow.com/a/64616487) though, so maybe TiddlyDesktop can too.

So in order for this feature to work, the user would be prompted to set the name of the folder containing the image (defaulting to img).

The file tree would be like that :

```
/root/tiddlywiki.html
/root/img/filename.png
```

When an image is drag&drop into a tiddler, tiddlywiki show a prompt to choose between importing the image or linking it into the wiki. The choice can be saved for later use. If linking is chosen, the user is prompted to specify the folder path (defaulting to img/), this setting is saved. 

The following code is then inserted into the wiki : `[img[img/filename.png]]`. 

This way, new users are less likely to accidentally bloat their tiddlywiki file (the prompt should allude to this, something like "Warning : importing image into the wiki can slow it down. Linking is recommended."), and it allows to quickly add new images to the wiki.

**Comment by twMat** [comment]
Is this perhaps the same request as #5309 ?

**Comment by Telumire** [comment]
> Is this perhaps the same request as #5309 ?
@twMat my bad, looks like I didn't search well enough ! I'l close this issue then, thanks :)
