### ISSUE TITLE
[BUG] Filters that use regexp break when a pipe character is used in certain contexts

### ISSUE THREAD

**Issue by joshuafontany** [Jermolene/TiddlyWiki5#5893]
**Describe the bug**

**To Reproduce**
While editing a tiddler "Test/Tiddler\1" in draft mode, open another new tiddler in draft mode.
Enter the below into the brand new tiddler's test field, and click preview:
```
{{{ [is[draft]search-replace:g:regexp[/|\\],[!]addprefix[drafts/]] }}}

<br/>

<$list filter="[is[draft]search-replace:g:regexp[/|\\],[!]addprefix[drafts/]]">

</$list>
```
Result:
```
Filter error: Missing closing bracket in filter expression

drafts/Draft of 'New Tiddler'
drafts/Draft of 'New!Tiddler!1'
```
**Expected behavior**
```
drafts/Draft of 'New Tiddler'
drafts/Draft of 'New!Tiddler!1'

drafts/Draft of 'New Tiddler'
drafts/Draft of 'New!Tiddler!1'
```

**TiddlyWiki Configuration (please complete the following information):**
 - Version v5.1.23 AND Prerelease.
 
**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version 91.0.4472.124

**Additional context**
This also seems to be failing in the `$:/config/FileSystemPaths ` filters used by the `filesystemadaptor`, but I was able to reproduce the bug 100% in the editor.

**Comment by saqimtiaz** [comment]
Sounds potentially like a dupe of #4462. In the triple brace filter transclusion syntax, the pipe character is a separator for the template and tooltip.

It is important not to think of the triple braces as a general purpose filter execution syntax. When used freely in wikitext, i.e. not as a widget attribute, it is a transclusion using the list item template.

**Comment by Jermolene** [comment]
I think this is indeed the same issue as #4462. The unexpected parsing of vertical bars within filtered transclusions is a weird gotcha, but it does give us a bit of freedom to extend the syntax in a backwards compatible way.

**Comment by joshuafontany** [comment]
@Jermolene @saqimtiaz Thanks guys, that definitely gives me more context. I first noticed this behavior with my new Bob2.0 server tests (single wiki at first), when the filesystem adaptor failed to write drafts to the correct directory.  I will have to test around that bug with a vanilla TW server.

**Comment by joshuafontany** [comment]
I have not been able to duplicate this with the filesystem adaptor, so I will close this in lieu of #4462.
