### ISSUE TITLE
Sluggishness in 5.0.10 in Firefox on Windows

### ISSUE THREAD

**Issue by giffmex** [Jermolene/TiddlyWiki5#590]
In a TW5 file I sent Jeremy by email, I have 1948 tiddlers, 321 tags, and 54 system tiddlers. The tiddlers are not large: mostly image links to web images, and list filters. The file itself is not large either, less than 2.5 MB. But in Firefox on Windows 8 everything is taken 1-3 seconds or more: new tiddler, edit tiddler, save tiddler, open from hyperlink, open and close tiddlerinfo, etc. One would expect normal times on these actions for a file of this size and with tiddlers of normal size. This file functioned normally in 5.0.8, and I didn't try it in 5.0.9. The switch to 5.0.10 was when I immediately noticed the change.

**Comment by pmario** [comment]
@Jermolene ... I think this can be closed. TW and browser perfomance improved quite a bit. and 5.0.10 was beta.

**Comment by Jermolene** [comment]
Thanks @pmario
