### ISSUE TITLE
[BUG] macrocall of tabs macro does not accept filter output if it contains spaces

### ISSUE THREAD

**Issue by swhcz** [Jermolene/TiddlyWiki5#5902]
**Describe the bug**
While trying to set the `default` parameter when calling the tabs macro, all works fine until it encounters a tiddler with a space in its title.

**To Reproduce**
- I have a tiddler, in my example it's called `[[The Big Buttons]]`.
- There's five tiddlers, `[[Trello]]` `[[Journals]]` `[[Google Translate]]` `[[Blackness]]` and `[[Colemak]]`, all tagged with `[[The Big Buttons]]`
- I want to create a tabbed view of everything that is tagged with `[[The Big Buttons]]`, default tab is whatever the first tab in order is
- I was trying to use the following code to achieve this, with `<<first>>` being determined by the surrounding set:

```
<$set name="first" filter="[title[The Big Buttons]tagging[]first[3]last[]]">
<$macrocall $name="tabs" tabsList="[title[The Big Buttons]tagging[]]" default=<<first>> state=null class="tc-vertical"/>
</$set>
```

**Expected behavior**
All works fine if the filter in $set finds a tiddler with no spaces. But, if the tiddler contains a space, the call wound not work.
I could, however, workaround this problem with a macro definition (which uses the `<<tags...>>` syntax, which understands the `[[Google Translate]]` as a parameter.

**Screenshots**
![cap000233](https://user-images.githubusercontent.com/25341031/126375735-60e5ce43-5743-46c3-928a-7f2872618cba.png)

**TiddlyWiki Configuration (please complete the following information):**
 - Version 5.1.22, but have also tested with 5.1.23 quickly, same problem
 - Saving mechanism: using Lighttpd to serve the file, WebDav probably
 - Plugins installed: Menu Bar, Markdown Parser

**Desktop (please complete the following information):**
 - OS: Win 10
 - Browser: Firefox and Chrome, both most up to date

**Additional context**
Don't mind the `<$set..`-Filter too much, I've experimented with several dozens of filters, the one shown in my example is just a quick example I could come up with in less than 2min.

Not sure if my way of solving the problem of setting first tab as default is the best approach, please advise if you would suggest something different.
Also, if `<$macrocall ../>` works as expected, please close this issue, I am not even 100% sure if this is actually a bug, maybe I'm misusing something here, or maybe did not understand things fully. Happy to learn, though!

**Comment by pmario** [comment]
The problem here is, that the tabs macro doesn't need a filter input as the "default" parameter, it needs a tiddler title. `[[Google Translate]]` is a filter syntax and not a tiddler title. 

So try: `<$set name="first" value={{{ [title[The Big Buttons]tagging[]first[3]last[]]}}} >` this instead of your variable definition

**Comment by swhcz** [comment]
Indeed, that works. I was biting my teeth off trying to get just the title, as a bare string, out of my filter, but `{{{ ... }}}` it is...

Maybe I got mislead by [the docs](https://tiddlywiki.com/#Widgets%20in%20WikiText), saying `attr=<<myMacro>>` is allowed, not bearing in mind the output of the macro is the actual problem.

**Comment by swhcz** [comment]
Thought a bit about this; 2 suggestions:

- would it make sense to mention the `{{{ ... }}}` on tiddliwiki.com, in "Macro Call Syntax Examples", too? It seems a powerful function to me (bridging from filters to "normal text" kindof), and I remember I could have used it a few times before...
- the `default` of `<<tabs ... >>` does not make much sense, as a state tiddler gets created anyways anyhow, and would override the default as soon as the wiki is saved; I helped myself with creating a StartupAction removing said state tiddler, but I'm not sure if that's how it's supposed to be.

I'd suggest to close this issue, though, it's quite clear that TW works exactly as it should.

**Comment by pmario** [comment]
>the default of <<tabs ... >> does not make much sense, as a state tiddler gets created anyways anyhow, and would override the default as soon as the wiki is saved; I helped myself with creating a StartupAction removing said state tiddler, but I'm not sure if that's how it's supposed to be.

That's exactly as it is supposed to work. The default setting is there to be used if, and only if the state tiddler is missing. If the state tiddler is missing it would show _no_ tab text area. ... And that's what the default should prevent. ... 

I just had a look at the docs and it should be mentioned there. ... So I'll create a pull-request, to be more specific in the docs.

**Comment by pmario** [comment]
>Maybe I got mislead by the docs, saying attr=<<myMacro>> is allowed, not bearing in mind the output of the macro is the actual problem.

It's the output of the <$set widget "filter" parameter. ... It creates the output of an evaluated filter, where tiddler titles with spaces are covered in brackets. ... That's an extremely useful behaviour, since it was the only possibility in V5.1.23. In V5.2.0 we get the [format-titlelist](https://tiddlywiki.com/prerelease/#format%20Operator) parameter, which will allow us to create titles, that are covered by braces. 

The <$set widget "name" parameter doesn't do this, because it expects a string and not a filtered list. ... 

>Thanks a lot!!!

You are welcome!

**Comment by pmario** [comment]
If you are OK with the "solution" you should close the issue.

**Comment by pmario** [comment]
see: tabs-macro improve "default" parameter docs (#5904)

**Comment by swhcz** [comment]
> 
> 
> If you are OK with the "solution" you should close the issue.

I am. Thanks a lot for your time and effort!!
