### ISSUE TITLE
[BUG] Spaces in field names result in a not working file

### ISSUE THREAD

**Issue by saqimtiaz** [Jermolene/TiddlyWiki5#5905]
At https://tiddlywiki.com/prerelease/empty.html

Create a new tiddler called "test" with a field name "my field" with a value of "hello".
Save and open the resultant file.

You get a blank white screen, no errors in the console. This is the same bug reported by Elise Springer in the [Google Group](https://groups.google.com/g/tiddlywiki/c/kF-OGmkyFfo/m/dWhWmMz_AgAJ).

I believe this check for field names is the cause:

https://github.com/Jermolene/TiddlyWiki5/blob/d455072f13dd00955ae82d62d2d6e44581bdba9e/boot/boot.js#L1604-L1608

**Comment by Jermolene** [comment]
Thanks @saqimtiaz, I managed to miss the `\s` somehow. Fix upcoming.
