### ISSUE TITLE
[UPDATE NEEDED] The KaTex library needs an update. We use 0.12.0 atm latest is: 0.13.13

### ISSUE THREAD

**Issue by pmario** [Jermolene/TiddlyWiki5#5907]
[UPDATE NEEDED] The KaTex library needs an update. We use 0.12.0 atm latest is: 0.13.13

See: https://groups.google.com/g/tiddlywiki/c/zqx0fW-_dJQ

**Comment by atronoush** [comment]
Yes, please update! KaTeX 0.13.3 has fixed many issues and adds tones of new features!

**Comment by Jermolene** [comment]
Thanks @pmario @atronoush I'll add this to my list for v5.2.0

**Comment by kookma** [comment]
@Jermolene - This is a gentle reminder. Some new features like align in KaTex 0.13.18 are very useful!

**Comment by Jermolene** [comment]
Hi @pmario @kookma thanks for the nudge. The plugin is now updated to v0.13.18, do let me know if there are any problems:

https://tiddlywiki.com/prerelease/plugins/tiddlywiki/katex/
