### ISSUE TITLE
Allow drag and drop to be disabled

### ISSUE THREAD

**Issue by Jermolene** [Jermolene/TiddlyWiki5#591]
For some applications we'd like to avoid end users accidentally dragging links and images.

**Comment by pmario** [comment]
@Jermolene -- We do have a hidden setting: Disable Drag and Drop. It works but the setting is not respected everywhere in the core UI at tiddlywiki.com

IMO this issue can be closed, but a new one should be created: eg: Disable Drag and Drop should be respected by the whole core UI

**Comment by Jermolene** [comment]
Thanks @pmario
