### ISSUE TITLE
[IDEA] Painful gotcha in action-setfield macro

### ISSUE THREAD

**Issue by CodaCodr** [Jermolene/TiddlyWiki5#5916]
The following, when rendered, will overwrite the text field of the currentTiddler because the variable `cur-itme-ref` does not exist. 

```
\define core-view-link(link, title:"", vw, prefix)
<$set name=cur-item-ref value={{{ [[$:/temp/bk-tw/]addsuffix<__vw__>addsuffix[-cur-item]] }}}>
<$log $$message=viewlinks/>
<$button class="tc-btn-invisible tc-tiddlylink bk-core-view-link bk-core-view-link-$prefix$" to="""$vw$"""
 ><$action-setfield $tiddler=<<cur-itme-ref>> $field=text $value=<<get-core-view-link-prefixed "$prefix$" "$link$">> 
/>$title$</$button>
</$set>
\end
```

**Describe the solution you'd like**

Would it be possible to somehow red-flag uses of non-existent vars in this and similar scenarios?

**Comment by clutterstack** [comment]
I do this to myself every once in a while. Most recently yesterday. I got carried away working on a macro in preview mode and wiped it out using its own button! So I was thinking about this.

Did you mean a warning in the debug log, or an actual interruption of macro execution? The former (which might already exist for all I know) might be nice (while not preventing us from overwriting our macros while writing them), but I think the latter would break a lot of macros. 

For example, if you actually wanted the action-setfield widget to apply to the current tiddler, unless cur-item-ref returned a tiddler title, then an interruption or visible flag would be undesirable.

In the short term I would just put a filter in the button action to prevent writing anything if cur-item-ref isn't a tiddler.

**Comment by Jermolene** [comment]
Hi @CodaCodr @clutterstack ouch, that's painful.

However, it's hard to see what can be done about it without breaking backwards compatibility. One option might be to introduce a new, alternate widget with different semantics that is available alongside `<$action-setfield>`.

**Comment by CodaCodr** [comment]
Thanks guys. I wrote this "wish" through tear-stained eyes and didn't expect - just hoped - we could somehow prevent actionable code addressing a missing var.

The actual pain here was that every "failsafe" I had in place also failed me:

1. I have a caching mechanism which I'd turned off for a limited class of tiddlers - this being one of them.
2. I had good intentions of targeting another field, `!!cur-item` but for dev-visibility I was targeting the text field while working on the core button code. Never again!
3. Extension to 2, I never target the text field unless that is a requirement of the intended functionality. :facepalm:

There's a word counter in that same UI. Last I looked it showed ~1500. My backup TW was a few days old and didn't contain that tiddler.

Closing.

**Comment by clutterstack** [comment]
@CodaCodr I'm sorry, I feel your pain. 

I wonder whether some kind of undo might be a useful avenue to explore. If someone had time!

**Comment by CodaCodr** [comment]
@clutterstack 

I did of course try Ctrl-Z but since the "edit" didn't happen in the textarea, no joy.

@Jermolene 

Aside...

The power of currentTiddler is of course extremely useful. Even it being used by default is powerful, but in this instance extremely dangerous. This, or something similar, would mitigate the worst case(s)

```
//pseudocode
target = node.getAttribute("$tiddler");
if(target !== "") { // or undefined
  if(! resolve(target)) {
    // issue - don't use currentTiddler
```
I don't know the code base so I can't progress that much further. But, in essence, if the attr is expressed, but is NOT resolved to something, don't blindly target currentTiddler. 

If attr is NOT present, then sure, use currentTiddler.

Hope that makes sense...

**Comment by pmario** [comment]
Hi folks,
I can feel your pain. 

>The power of currentTiddler is of course extremely useful. Even it being used by default is powerful, but in this instance extremely dangerous. This, or something similar, would mitigate the worst case(s)

I do have the same problem myself from time to time. It's extra painful, if you mess around with a working macro, but want to optimize the code and include a typo. ... The working code is gone with the click of a button :/

Most of the times I'm lucky if I have committed the change to git. .. But sometimes I'm not ......

**Comment by pmario** [comment]
@CodaCodr .. I think you should reopen the issue. Even if it can't be fixed with the core <$action-setfield> macro, there may be a possibility to improve the situation. 

I'm thinking about a "subclassed widget" with a different name, that will output an error message, if  `$tiddler=<<cur-itme-ref>>`  would be undefined. .. 

There may be a new parameter. eg: `forceCurrentTiddler=yes`, which if set to yes, it will use the currentTiddler as a fallback. .. So we could have the same behaviour as now, but with a safety net. 

... Just brainstorming

**Comment by CodaCodr** [comment]
@pmario 

> It's extra painful, if you mess around with a working macro

Which is what I was doing giving me unjustified over-confidence in my approach. The var was new, the code updated quickly to conform to changes elsewhere. Click. Bang. Tears. 🙄 

> I think you should reopen the issue.

done.

**Comment by Jermolene** [comment]
I think @CodaCodr's suggestion might work: to only fall back to using `currentTiddler` for the target if the `$tiddler` attribute is entirely missing, and not if it is blank. It wouldn't be fully backwards compatible, but I think the logic that a user would be unlikely to intentionally write `$tiddler=""` is fair.

**Comment by pmario** [comment]
>I think @CodaCodr's suggestion might work: to only fall back to using currentTiddler for the target if the $tiddler attribute is entirely missing, and not if it is blank. It wouldn't be fully backwards compatible, but I think the logic that a user would be unlikely to intentionally write $tiddler="" is fair.

It's only problematic, if the `field` is `text` too. So if both of them use the fallback, we could definitely lock the function, with an "Are you sure, you want to overwrite "current tiddler" "text" field. ... 

This dialogue may be annoying for some "valid" use cases, but it won't completely break existing code. ... And it will generate feedback, if our assumptions are wrong.

I think it's legit to write to a field different than `text` in every case.
