### ISSUE TITLE
Disable drag and drop import within same window

### ISSUE THREAD

**Issue by Jermolene** [Jermolene/TiddlyWiki5#592]
It is currently too easy to inadvertently drag a link or image within the same wiki, accidentally creating a new tiddler.

We should detect and suppress  attempts to import from the same window.

**Comment by tobibeer** [comment]
> I'm using this feature very often because it's easier to rearrange texts that way than to use ^X ^V.

Is that really easier? I truly don't think it is.

Asked differently: Is #592 truly an issue? And if yes: What **precisely** is the issue (in terms of an actionable spec)? 

@buggyj: I sure hope to see your taglist dropadapter actually extending the core $list widget rather than being a "standalone" thing. Any chance of seeing that happening?

**Comment by Skeeve** [comment]
Yes, it is, when you're used to it. Especailly when it comes to rearranging whole paragraphs.

Additionally you do not need the clipboard for this at all, meaning: You can keep something in the clipboard while rearranging text.

Is it an issue: For me for sure.

**Comment by Jermolene** [comment]
> Asked differently: Is #592 truly an issue? And if yes: What precisely is the issue (in terms of an actionable spec)?

@tobibeer go to tiddlywiki.com, and drag the "TiddlyWiki" title link at the top of the sidebar a little to the left and let go. You'll find that an import tiddler is created. I think that that is wrong; you'd never want to import a tiddler from the same window. I've updated the title to make it clearer.

**Comment by tobibeer** [comment]
Ok, without having looked at the code, does the current drag-start handling give the content some kind of "origin" attribute that can be validated? If not, would that make sense... and to then check for existing tiddlers by the same name?

Also not having looked at the code in detail, I believe droping stuff on TextInputs is handled differently from droping on the page itself, so that would / should remain unaffected. So, we're talking about the global dropzone widget instance. Correct?

**Comment by Jermolene** [comment]
There's no easy way to check the origin of the drag. As far as I can tell, one would have to use global variables.

> Also not having looked at the code in detail

Dragging is here:

https://github.com/Jermolene/TiddlyWiki5/blob/master/core/modules/widgets/link.js

Dropping is here:

https://github.com/Jermolene/TiddlyWiki5/blob/master/core/modules/widgets/dropzone.js

**Comment by felixhayashi** [comment]
Ehm, I depend on the in-page drag n drop for my plugin (see discussion #1067)

**Comment by Jermolene** [comment]
> Ehm, I depend on the in-page drag n drop for my plugin (see discussion #1067).

Hence the clarification that it is drag and drop **importing** within a page that needs to be suppressed, not drag and drop in general.

> Still I agree that the global dragndrop import should be made more "secure". Also I would favour an option to turn tiddlywikis import mechanism off since I use tiddlywiki as actual websites which are read only and the user should not note that he/she can dragndrop or modify the page.

Yes that makes sense, please make a separate pull request.

**Comment by felixhayashi** [comment]
> Hence the clarification that it is drag and drop importing within a page that needs to be suppressed, not drag and drop in general.

Sorry, I overlooked that.

> Yes that makes sense, please make a separate pull request.

Done #1482

**Comment by buggyj** [comment]
>buggyj: I sure hope to see your taglist dropadapter actually extending the core $list widget rather than being a "standalone" thing. Any chance of seeing that happening?
@tobibeer 
I am not sure that adding drag and drop to the list  widget is a good idea, it is already a very complicated thing, and I fear it would become a bit of a 'monster'. 
Also for drag and drop there needs to be something to add drop handlers to, in the taglist widget I add divs and  render elements inside the divs which is at odds with the design of the list widget.

Maybe we could have a separate 'arrangelist' widget (without the story functionality)?

**Comment by felixhayashi** [comment]
Hi @Jermolene.

> Hence the clarification that it is drag and drop importing within a page that needs to be suppressed, not drag and drop in general.

Seems like this feature is broken for my plugin. Is there no way I can enable the dropzone widget to accept internal links? Please see https://github.com/Jermolene/TiddlyWiki5/issues/1599

**Comment by danielo515** [comment]
Hello @Jermolene ,

Could you please specify if you are talking about whole tiddler import, which means that you can still importing chunks of text, or any kind of importing within the same file?

**Comment by Jermolene** [comment]
Hi @danielo515 dragging chunks of text in the same window still works as in 5.1.7. The only change in 5.1.8 is that dragging a tiddler within the same window is ignored.

**Comment by danielo515** [comment]
Ok @Jermolene , thank you for clarifying this.
