### ISSUE TITLE
Tag colors not always shown correctly in Tag manager

### ISSUE THREAD

**Issue by gernert** [Jermolene/TiddlyWiki5#596]
As of Firefox v29 we are blessed with the color picker (as it was already with Chrome). Very handy for selecting new colors.
But not all colors are shown correctly.

All tags with default yellow-brown color (#d5ad34) are shown as black (color bar under heading 'Colour'), but there are other colors shown as black while for sure they are not black.

To see it, select the Tag manager at http://tiddlywiki.com/
The following - non default colored - tags are shown black (color bar under heading 'Colour'):
- features
- introduction

Tested with Windows 7 64-bit, Firefox v29 and Chrome v34

**Comment by twMat** [comment]
Plead to reopen this issue.

I'm not sure this was ever fully fixed - I have over the years thought there was a problem with my computer and forgot about it. But now with a new laptop (and new OS) the problems still persist. Win10, FF & Chrome

![tagmanager](https://cloud.githubusercontent.com/assets/4534056/12638634/182eec80-c59f-11e5-82af-34429265adf0.PNG)
