### ISSUE TITLE
There is a new version of: Stanford Javascript Crypto Library (SJCL)

### ISSUE THREAD

**Issue by pmario** [Jermolene/TiddlyWiki5#5962]
We use 1.0.7 - Latest is: https://github.com/bitwiseshiftleft/sjcl/releases

**Comment by Jermolene** [comment]
Thanks @pmario, would you be interested in creating a PR?

**Comment by pmario** [comment]
I did download the tagged source, but It seems they didn't update the build. So we may wait until they do a real release. I'll close the issue.
