### ISSUE TITLE
[BUG] Tiddlywiki.com has a tiddler with garbled fields

### ISSUE THREAD

**Issue by joshuafontany** [Jermolene/TiddlyWiki5#5980]
**Describe the bug**
Go to Tiddlywiki.com, search for the "/home/runner/work/TiddlyWiki5/TiddlyWiki5/editions/tw5.com/tiddlers/concepts/ShadowTiddlers.tid" tiddler.

Look at the Info -> Fields.

<html>
<body>

<$action-setfield |  
-- | --
$field | "text"
$tiddler | $=
$value | "$:/core/ui/SideBar/More"/>"
sidebar--595412856&quot; |  
state |  
tab |  
title | /home/runner/work/TiddlyWiki5/TiddlyWiki5/editions/tw5.com/tiddlers/concepts/ShadowTiddlers.tid

</body>
</html>

**Comment by pmario** [comment]
ouch. That was my fault. It seems I did use tiddlywiki to change the text and then copy / pasted over the title and tag fields. :/ I'll create a PR immediately

**Comment by pmario** [comment]
Commit added to:  #5974

**Comment by pmario** [comment]
Sorry I've completely missed the reference to your PR
