### ISSUE TITLE
moduleproperty[] and extended modules[] operators in core

### ISSUE THREAD

**Issue by saqimtiaz** [Jermolene/TiddlyWiki5#6009]
I suggest that we include the `moduleproperty[]` and `modules[]` operators from the publishing framework in the core for 5.2.0:

* https://github.com/Jermolene/TiddlyWiki5/blob/bbdf9bae89a732d472e7569faded463e16839e56/core/modules/filters/moduleproperty.js
* https://github.com/Jermolene/TiddlyWiki5/blob/bbdf9bae89a732d472e7569faded463e16839e56/core/modules/filters/modules.js

Note that in the latter operator we may want to have another look to ensure that it is backwards compatible when there are no operands provided.

I am wrapping up my current round of work on the FileUploads plugin and while I don't have the opportunity to prepare a PR, I wanted to post this item from my notes lest it be forgotten.

In the FileUploads plugin I had to introduce an `uploaders[]` operator to get the module names of modules of the type uploader, this could have been avoided. Similarly, at the moment the Settings tiddler for the plugin transcludes the Settings tiddler of the selected uploader module, but this is based on naming convention and is brittle. It wont work if someone were to write an uploader module with a different plugin tiddler namespace. The two operators under discussion from the publishing framework would address both these use cases.

**Comment by Jermolene** [comment]
Thanks @saqimtiaz I'll add this to my list.
