### ISSUE TITLE
[BUG] Error when pasting text using HTA in v5.2

### ISSUE THREAD

**Issue by welford** [Jermolene/TiddlyWiki5#6014]
**Describe the bug**
Error when pasting text into editor using tw 5.2 HTA

**To Reproduce**
1. (On Windows) download tw 5.2, rename file extension to .hta
2. open hta file
3. create a new tiddler or edit an existing one
4. paste text
5. Error Appears

**Expected behavior**
No Error on pasting text

**Screenshots**

**TiddlyWiki Configuration (please complete the following information):**
 - Version [e.g. v5.2]
 - Saving mechanism: HTA
 - Plugins installed: None
 
**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser HTA
 - Version N/A

**Additional context**
I know continuing full hta support may be difficult, but this, to me at least, seems like an easy fix: 

in https://github.com/Jermolene/TiddlyWiki5/blob/82ec63e71118f9ee788972371f713579bae67530/core/modules/editor/factory.js

EditTextWidget.prototype.handlePasteEvent = function(event) {
  if(event.clipboardData.files.length) {

changing this to 

EditTextWidget.prototype.handlePasteEvent = function(event) {
  if(event.clipboardData && event.clipboardData.files && event.clipboardData.files.length) {

worked for me locally.

**Comment by Jermolene** [comment]
Thanks @welford fix upcoming

> I know continuing full hta support may be difficult, but this, to me at least, seems like an easy fix

I'd like to continue with MSIE & HTA support for as long as we possible can, so fixes are much appreciated.

**Comment by welford** [comment]
Thanks!
