### ISSUE TITLE
[IDEA] option to hide drag image

### ISSUE THREAD

**Issue by ericshulman** [Jermolene/TiddlyWiki5#6027]
Sometimes I use <$draggable> to move content that includes rendered images.

In `$:/core/modules/utils/dom/dragndrop.js`, the event handler for `dragstart` uses `dragImageType` with a default value of `dom` to set the drag image to the element being dragged.  

However, when dragging any large block of content and in particular a large image, this can be very distracting as it presents a "ghost" of the entire image, which makes it difficult to see precisely where you are dropping the element, since you need to look at the cursor position, rather than the overall visualized drag element.

In order to avoid this, I propose adding an option for `dragImageType==="blank"`, which suppresses the drag image, so that only the dragging cursor remains as the indicator of a drag-in-progress.

To do this, some minor code changes are needed:
1) **In `$:/core/modules/widgets/draggable.js`, add processing to get the `dragImageType` param value:**
    * in `DraggableWidget.prototype.execute()`, add `this.dragImageType = this.getAttribute("dragimagetype");` to get the parameter value from the widget
    * in `DraggableWidget.prototype.render()`, add `dragImageType: self.dragImageType,` as a parameter in the call to `$tw.utils.makeDraggable()` to pass the value on for further handling
2) **In `$:/core/modules/utils/dom/dragndrop.js`, add handling for `dragImageType==="blank"`**
    * in `makeDraggable()`, in the eventListener for "dragstart", add three lines here (indicated by /* ELS */):
       ```
		if(dataTransfer.setDragImage) {
			if(dragImageType === "pill") {
				dataTransfer.setDragImage(dragImage.firstChild,-16,-16);
			} else if (dragImageType === "blank") {			/* ELS */
				dragImage.removeChild(dragImage.firstChild);	/* ELS */
				dataTransfer.setDragImage(dragImage,0,0);	/* ELS */
			} else {
				var r = domNode.getBoundingClientRect();
				dataTransfer.setDragImage(domNode,event.clientX-r.left,event.clientY-r.top);
			}
		}
With the above changes, it will then be possible to write:
`<$draggable tiddler=... dragimagetype="blank" startactions=...  endactions=... >`

**Comment by Jermolene** [comment]
Thanks @ericshulman good idea, let me know if it works for you.
