### ISSUE TITLE
Performance regression reported from v5.1.23

### ISSUE THREAD

**Issue by Jermolene** [Jermolene/TiddlyWiki5#6042]
From https://talk.tiddlywiki.org/t/tw-5-2-0-prerelease-significantly-slower-than-tw-5-1-23-instrumentation-data-included/776:

---

I’ve tested the 5.2.0-prerelease over the past few days both on mobile and on desktop.

I’ve noticed significantly degraded performance on mobile and did some performance instrumentation tests on my desktop. Results below.

I’ve primarily tested the basic TW operations such as navigating links (opening, closing tiddlers), selecting checkboxes, radio buttons, clicking buttons etc.

The overall performance is significantly slower in 5.2.0 compared to the same wiki running on 5.1.23. It appears that mainRenderer and mainRefresh see the biggest slowdowns.

Here’s some data from the two identical wikis running side by side, the figures on the left correspond to the 5.1.23 version and the ones on the right are from the 5.2.0-prerelease. In each “test run” I had all tiddlers closed beforehand and then performed identical navigation:

mainRenderer values

Opening tiddlers (variable levels of complexity)
151 ms vs 276ms
149 ms vs 230ms
242 ms vs 302ms
105 ms vs 196ms
398 ms vs 503ms

Opening Control Panel
90ms vs 190ms

Opening Advanced Search
83ms vs 195ms

Clicking on a checkbox that sets a value in a data tiddler
67ms vs 160ms

Pressing a button that sets a value in a data tiddler
175mm vs 278ms

Entering a password in an encrypted wiki, upon pressing enter:
mainRender (v5.1.23): 226.00m vs mainRender (v.5.2.0-prerelease): 350.00ms
mainRefresh (v5.1.23): 74.00ms vs mainRefresh (v.5.2.0-prerelease): 192.00ms

I’ve performed these tests on my desktop with an 8-Core Ryzen CPU clocked at 3.60 GHz and 32GB RAM. The performance on my midrange Motorola is at least 5 times slower. While desktop performance slowdowns on this system are negligible, mobile performance introduces major usability issues.

The values above are obviously system dependent and wiki dependent but the point I’m trying to make is that in relative terms, 5.2.0-prerelease is significantly slower than 5.1.23. I’ve made these tests on the same system, the same identical wiki, with the only difference being the TiddlyWiki version.

I’d like to hear your thoughts about this and also if there’s anything you could suggest. Could anyone perhaps perform similar tests on their end?

One point to note is that the wiki I used was password protected, which means that the new json parsing probably does not affect it yet (unless I misunderstood). However, the core render modules are still slower to render the wiki and it would be interesting to learn why it should be the case.

**Comment by Jermolene** [comment]
I've now setup a very basic performance testing framework. It consists of:

* A test wiki (a snapshot of `editions/tw5.com`)
* A script to build the wiki with a specific Git commit of TiddlyWiki
* A script to open a wiki under [Puppeteer](https://pptr.dev/) and extract the performance timings

The repository is here:

https://github.com/Jermolene/tiddlywiki-performance-test-rig

At the moment, after running the tests several times I'm not seeing any performance regression between v5.1.23 and master:

```
./build-tiddlywiki-at-version.sh v5.1.23 ./tmp/v5.1.23 && ./build-tiddlywiki-at-version.sh master ./tmp/master
node ./index.js ./tmp/v5.1.23/index.html && node ./index.js ./tmp/master/index.html 
```

Output:

```
file:///xxx/git/Jermolene/tiddlywiki-performance-test-rig/tmp/v5.1.23/index.html
2021 9 17 16:43:12.200: Execute $tw.perf.log(); to see filter execution timings
2021 9 17 16:43:24.666: mainRender: 12301.70ms
2021 9 17 16:43:25.340: styleRefresh: 2.70ms
2021 9 17 16:43:26.465: mainRefresh: 1125.20ms

file:///xxx/git/Jermolene/tiddlywiki-performance-test-rig/tmp/master/index.html
2021 9 17 16:43:33.039: Execute $tw.perf.log(); to see filter execution timings
2021 9 17 16:43:45.018: mainRender: 11793.60ms
2021 9 17 16:43:45.680: styleRefresh: 2.60ms
2021 9 17 16:43:46.811: mainRefresh: 1130.20ms
```

The inconsistency may be because the test rig isn't measuring the correct thing. It would be helpful to dig into your wiki – would you be prepared to share it privately?

**Comment by sobjornstad** [comment]
If you aren't able to get a copy of Hubert's wiki or you want another test case, you could try [my public Zettelkasten](https://zettelkasten.sorenbjornstad.com)...should be able to just hit the download button and then run it through the upgrader. I don't have time to try turning on the instrumentation and looking for numbers at the moment, but it does feel just a wee bit slower after doing an upgrade. The machine I'm on is so fast that it's hard to tell the difference sometimes.

**Comment by Jermolene** [comment]
Thanks @sobjornstad. For your wiki, I'm seeing slightly slower timings on the prerelease than v5.1.23. To emphasise that this might be a limitation of the test rig; all it does at the moment is take the timings that are enabled by `$:/config/Performance/Instrumentation`.

```
file:///xxx/git/Jermolene/tiddlywiki-performance-test-rig/tmp/v5.1.23/index.html
2021 9 18 15:16:14.434: Execute $tw.perf.log(); to see filter execution timings
2021 9 18 15:16:15.297: mainRender: 399.20ms
2021 9 18 15:16:15.402: styleRefresh: 15.70ms
2021 9 18 15:16:15.435: mainRefresh: 32.70ms

file:///xxx/git/Jermolene/tiddlywiki-performance-test-rig/tmp/master/index.html
2021 9 18 15:16:16.498: Execute $tw.perf.log(); to see filter execution timings
2021 9 18 15:16:17.366: mainRender: 408.10ms
2021 9 18 15:16:17.481: styleRefresh: 16.40ms
2021 9 18 15:16:17.518: mainRefresh: 36.80ms
```

Changing `$:/DefaultTiddlers` to `[all[tiddlers]sort[]limit[300]]` is interesting: the prerelease is 10% faster. It seems like the more tiddlers that are displayed, the faster the prerelease is compared to v5.1.23:

```

file:///xxx/git/Jermolene/tiddlywiki-performance-test-rig/tmp/v5.1.23/index.html
2021 9 18 15:21:18.462: Execute $tw.perf.log(); to see filter execution timings
2021 9 18 15:21:25.504: mainRender: 6551.40ms
2021 9 18 15:21:27.229: styleRefresh: 13.70ms
2021 9 18 15:21:28.014: mainRefresh: 784.60ms
2021 9 18 15:21:28.746: styleRefresh: 5.70ms
2021 9 18 15:21:29.188: mainRefresh: 441.50ms
2021 9 18 15:21:29.214: styleRefresh: 5.80ms
2021 9 18 15:21:29.615: mainRefresh: 400.60ms
2021 9 18 15:21:35.516: styleRefresh: 6.50ms
2021 9 18 15:21:35.914: mainRefresh: 397.30ms

file:///xxx/git/Jermolene/tiddlywiki-performance-test-rig/tmp/master/index.html
2021 9 18 15:21:36.943: Execute $tw.perf.log(); to see filter execution timings
2021 9 18 15:21:43.339: mainRender: 5920.60ms
2021 9 18 15:21:44.860: styleRefresh: 13.50ms
2021 9 18 15:21:45.647: mainRefresh: 786.50ms
2021 9 18 15:21:46.350: styleRefresh: 7.30ms
2021 9 18 15:21:46.810: mainRefresh: 459.20ms
2021 9 18 15:21:52.019: styleRefresh: 6.10ms
2021 9 18 15:21:52.452: mainRefresh: 433.10ms
2021 9 18 15:21:52.476: styleRefresh: 6.30ms
2021 9 18 15:21:52.904: mainRefresh: 427.30ms
```

**Comment by hubertgk** [comment]
Thanks for looking into this further @Jermolene and apologies for responding late.

Unfortunetely, I cannot share my main wiki but could replicate my initial findings with a test pair of empty wikis, one running 5.1.23 and the other one being the empty 5.2.0-prerelease:

[TiddlyWiki test pair.zip](https://github.com/Jermolene/TiddlyWiki5/files/7190162/TiddlyWiki.test.pair.zip)

In each wiki, I've created 5000 dummy tiddlers that only contain some lorem ipsum plaintext (no wikitext, widgets or custom macros).

Overall, each wiki has 5003 ordinary tiddlers and is just over 17 megabytes in size. They should be identical in terms of user content.

By running performance instrumentation manually like before with my own wiki, I've found the results to be consistent with my initial fidings (5.1.23 is on the left, 5.2.0-prerelease on the right):

**Saving a new tiddler**

 - 1357ms vs 1661ms

**Clicking on the Recent tab**

 - 951ms vs 1233ms
 - 975ms vs 1290ms
 - 913ms vs 1253ms

**Opening Control Panel**

 - 371ms vs 528ms

**Opening a tiddler by clicking its title as a search result (sidebar)**

 - 266ms vs 535ms

**Clicking to edit a tiddler called "Startpage"**

 - 141ms vs 174ms
 - 139ms vs 179ms
 - 145ms vs 176ms

**Opening default tiddlers (clicking the home button)**

 - 10ms vs 14ms

**Creating a tiddler** (clicking the + button on the sidebar) so that it goes into edit mode

 - 138ms vs 161ms

**Deleting an open tiddler in draft mode**

 - 12ms vs 18ms

**Comment by Jermolene** [comment]
Thanks @hubertgk

I used the `--savewikifolder` command to unpack your example wiki into a wikifolder for use with the test rig. As before, I got similar timings with the single entry in `$:/DefaultTiddlers`. When I changed it to `[all[tiddlers]sort[]limit[1000]]`, I see an improvement in the initial render: 2.313s for master vs. 2.698s for v5.1.23.

I assume the inconsistency is because your tests are all interactive, whereas the test rig is just measuring the initial rendering. I'll look at extending the test rig, but in the meantime it might be helpful if you could report the startup render times your seeing with the updated `$:/DefaultTiddlers`.

**Comment by saqimtiaz** [comment]
Clicking on the Recent tab
369
371
317

Opening Control Panel
47
47
52

Opening a tiddler by clicking its title as a search result (sidebar)
47
41

Clicking to edit a tiddler called "Startpage"
106
82
80

Opening default tiddlers (clicking the home button)
15
16

Creating a tiddler (clicking the + button on the sidebar) so that it goes into edit mode
65

**Comment by saqimtiaz** [comment]
@hubertgk I tried some of your tests using your test wikis and I don't see a significant performance difference. Also worth nothing that having the zoomin story view active can confound testing as the number of open tiddlers can vary without one realizing it.

**Clicking on the Recent tab**
369ms vs 424ms
371ms vs 331ms
317ms vs 315ms

**Opening Control Panel**
47ms vs 50ms
47ms vs 46ms
52ms vs 47ms

**Opening a tiddler by clicking its title as a search result (sidebar)**
47ms vs 41ms
41ms vs 46ms

**Clicking to edit a tiddler called "Startpage"**
106ms vs 99ms
82ms vs 88ms
80ms vs 75ms

**Opening default tiddlers (clicking the home button)**
15 vs 18
16 vs 18

**Creating a tiddler (clicking the + button on the sidebar) so that it goes into edit mode**
65 vs 63

**Comment by hubertgk** [comment]
With `[all[tiddlers]sort[]limit[1000]]` in `$:/DefaultTiddlers` I get the folllowing:

### 5.1.23

Startup:

```
<empty string> performance: mainRender: 2530.00ms <empty string> $:/core/modules/utils/logger.js:52:26
<empty string> performance: styleRefresh: 5.00ms <empty string> $:/core/modules/utils/logger.js:52:26
<empty string> performance: mainRefresh: 496.00ms <empty string> $:/core/modules/utils/logger.js:52:26
```

Clicking the Home button (opening default tiddlers):

```
<empty string> performance: styleRefresh: 9.00ms <empty string> $:/core/modules/utils/logger.js:52:26
<empty string> performance: mainRefresh: 1921.00ms <empty string> $:/core/modules/utils/logger.js:52:26
```

Clicking the plus button (new tiddler):

```
<empty string> performance: styleRefresh: 7.00ms <empty string> $:/core/modules/utils/logger.js:52:26
<empty string> performance: mainRefresh: 2130.00ms <empty string> $:/core/modules/utils/logger.js:52:26
```


### 5.2.0-prerelease

Startup:

```
<empty string> performance: mainRender: 2574.00ms <empty string> $:/core/modules/utils/logger.js:52:26
<empty string> performance: styleRefresh: 10.00ms <empty string> $:/core/modules/utils/logger.js:52:26
<empty string> performance: mainRefresh: 1885.00ms <empty string> $:/core/modules/utils/logger.js:52:26
```

Clicking the Home button (opening default tiddlers):
```

<empty string> performance: styleRefresh: 10.00ms <empty string> $:/core/modules/utils/logger.js:52:26
<empty string> performance: mainRefresh: 1873.00ms <empty string> $:/core/modules/utils/logger.js:52:26
```

Clicking the plus button (new tiddler):

```
<empty string> performance: styleRefresh: 7.00ms <empty string> $:/core/modules/utils/logger.js:52:26
<empty string> performance: mainRefresh: 2076.00ms <empty string> $:/core/modules/utils/logger.js:52:26
```

Is it then recommended to open as many tiddlers as possible at startup to improve overal performance (at the cost of the longer startup time)?

**Comment by Jermolene** [comment]
> Is it then recommended to open as many tiddlers as possible at startup to improve overal performance (at the cost of the longer startup time)?

No, not at all. I'm just opening lots of tiddlers to make the startup time longer, and hence easier to measure.

**Comment by hubertgk** [comment]
Thanks @saqimtiaz 

> having the zoomin story view active can confound testing as the number of open tiddlers can vary without one realizing it

Fair point, however I'm aware of this. In my tests, I performed the exact same clicks on both test wikis so that the same tiddlers remain open, the same tabs are selected etc.

Again, not really an issue on desktop but the lag is becoming a UX problem on mobile (it's there that I've first noticed it).

I'm not quite sure why we're getting inconsistent readings.

**Comment by pmario** [comment]
I think it may be also important to check the browser vendors. It seems Hubert uses FF which I also use. I can confirm that there are differences: 

Switch between Open and Recent tab

5.1.23 vs 5.2.0
450ms vs 620ms 
(variaion from 440ms to 490ms) vs (variation from 540ms to 650ms)

**Comment by Jermolene** [comment]
Thanks @pmario. Puppeteer supports Firefox now so I'll have a look at adding it to the rig.

**Comment by pmario** [comment]
Reload page with Recent tab selected: 

v5.1.23

![grafik](https://user-images.githubusercontent.com/374655/133896113-e242893b-54c5-4361-a771-a5ca5409d366.png)


v5.2.0

![grafik](https://user-images.githubusercontent.com/374655/133896105-fdbadb9d-30cf-4499-ad2a-a9c4bf28743d.png)

**Comment by saqimtiaz** [comment]
@pmario if you get the chance, could you compare before and after this commit:
https://github.com/Jermolene/TiddlyWiki5/commit/dbd3f835bf8399ed1a3da7cc322ec9b6ab783d53

I can't reproduce the problem so can't test myself but I have a hunch...

**Comment by saqimtiaz** [comment]
@pmario @hubertgk here is a patched 5.2.0 file for testing: https://saqimtiaz.github.io/sq-tw/temp/5.2.0-prerelease-patched.html

Can you please confirm if the performance issue persists here, especially with filter execution?

**Comment by pmario** [comment]
@saqimtiaz 
5.2.0-prerelease-master - That's the version with the new sort code

![grafik](https://user-images.githubusercontent.com/374655/133898245-20f6cf2a-6628-48ae-9da3-22d53fa616f7.png)


5.2.0-prerelease - old sort code prior to #dbd3f83

![grafik](https://user-images.githubusercontent.com/374655/133898272-df87ca8c-8852-49f3-a16c-e86e581ec699.png)

**Comment by saqimtiaz** [comment]
@pmario thank you. So that change to the sorting is definitely the major contributor to the slowdown in filter evaluation. 

The question remains whether that resolves all performance issues or whether there might be other changes that are also contributing.

**Comment by hoelzro** [comment]
I don't know how feasible this would be, but would it make sense to track global/per-tiddler cache hit/miss ratios, or somehow reflect how long potentially cached operations are taking during each step? I imagine that might influence timings from startup vs timings from after the wiki has had a chance to warm up a bit!

**Comment by hoelzro** [comment]
I was looking at https://github.com/Jermolene/TiddlyWiki5/blob/1ddc3ab037bab8cefa0b0173367335ea31d665a5/core/modules/startup/render.js#L80-L104 and I think I found a bug - if only throttled tiddlers have changed, the actual refresh will happen in another execution of the event loop, but the function provided to `$tw.perf.report` will have returned after setting up that deferred refresh and `$tw.perf.report` will report a shorter time, right? I doubt this influences much in practice (especially regarding timings for initial loads and switching sidebar tabs), but I just thought I'd mention it.

**Comment by pmario** [comment]
>and I think I found a bug - if only throttled tiddlers have changed, the actual refresh will happen in another execution of the event loop, but the function provided to $tw.perf.report will have returned after setting up that deferred refresh and $tw.perf.report will report a shorter time, right? 

Right. But I think that isn't a big problem. The `mainRefresh` time has its own line in the log, every time it is measured.. So it isn't used to calculate an average value, where it would have a negative impact.

**Comment by pmario** [comment]
>I don't know how feasible this would be, but would it make sense to track global/per-tiddler cache hit/miss ratios, or somehow reflect how long potentially cached operations are taking during each step? 

I think, this would be interesting. ... Especially since the global cache is destroyed whenever _any_ tiddler is changed. And this basically happens with every user interaction.

**Comment by Jermolene** [comment]
Thanks @saqimtiaz @pmario @hoelzro 

I've updated the [test rig](https://github.com/Jermolene/tiddlywiki-performance-test-rig) to properly measure sorting by introducing the following test tiddler:

```
<$list filter="[range[0:50]]" variable="count">
<$list filter="[all[tiddlers]sort[modified]sort[title]sort[modifier]]">
<$text text=<<currentTiddler>>/>
</$list>
</$list>
```

Using the data from Soren's wiki, I get the following timings:

* v5.1.23 – **3314.00ms**
* master – **5373.30ms**
* master with dbd3f835bf8399ed1a3da7cc322ec9b6ab783d53 reverted – **1844.70ms**

So, it would appear that dbd3f835bf8399ed1a3da7cc322ec9b6ab783d53 is masking what would otherwise be a doubling in performance on this test. I will now use the test rig to investigate alternative fixes to https://github.com/Jermolene/TiddlyWiki5/issues/5701

> and I think I found a bug

Thanks @hoelzro I think you're correct, would you mind opening a separate issue?

**Comment by Jermolene** [comment]
I've just pushed a simple fix that brings the master execution time into line with v5.1.23 – the test rig gives roughly the same timings for each now.

> master with dbd3f83 reverted – 1844.70ms

I can't duplicate that result now, I think that I was testing the wrong wiki in that instance.

**Comment by pmario** [comment]
@Jermolene .. This function is used very often in the core. .. So if we can make it faster, it would be an improvement. right?

I saw `inNaN` checks at https://github.com/Jermolene/TiddlyWiki5/blob/fb4d77ef46e23c23f4e46c13f4a529aa29a27dcd/core/modules/wiki.js#L393 and again at: https://github.com/Jermolene/TiddlyWiki5/blob/fb4d77ef46e23c23f4e46c13f4a529aa29a27dcd/core/modules/wiki.js#L372


So I think they are redundant. ... Just a thought

**Comment by Jermolene** [comment]
That's right, I'm investigating some simple optimisations now

**Comment by pmario** [comment]
I think titles.sort() .. could start like this: 

Init from x and y moved up from the middle of the code to the init area. 
a and b initialized with empty string. 

```
	titles.sort(function(a,b) {
		var x = Number(a),
			y = Number(b),
			a = b = "";
```

The else path isn't needed, since a and b are initialized already. 
tiddlerA.getFieldString() does always return a string, so the `|| ""` is redundant

```
		if(sortField !== "title") {
			var tiddlerA = self.getTiddler(a),
				tiddlerB = self.getTiddler(b);
			if(tiddlerA) {
				a = tiddlerA.getFieldString(sortField);
			}
			if(tiddlerB) {
				b = tiddlerB.getFieldString(sortField);
			}
		}
/*snip*/
```

**Comment by Jermolene** [comment]
I'm preparing a PR with some simple optimisations and unrolling of the sort function. The timings for Soren's wiki are promising:

* v5.1.23 mainRender: **5412.20ms**
* 575c2335975cc6cc960d2061ba8fdfa726ed8618 mainRender: **11221.60ms**
* with the pending PR mainRender: **3862.00ms**

(575c2335975cc6cc960d2061ba8fdfa726ed8618 is the last commit before reverting the problematic commit dbd3f835bf8399ed1a3da7cc322ec9b6ab783d53)

**Comment by Jermolene** [comment]
The PR for optimising tiddler sorting is #6053.

**Comment by hoelzro** [comment]
@Jermolene Done: #6054
