### ISSUE TITLE
[BUG] when using root-tiddler=$:/core/save/lazy-all, linked images may not load.

### ISSUE THREAD

**Issue by mdemoss** [Jermolene/TiddlyWiki5#6060]
**Describe the bug**
embedded images may not load, or load late when using root-tiddler=$:/core/save/lazy-all

**To Reproduce**
1. refresh the page in the browser, none of the tiddlers involved should be open
2. navigate to a text tiddler, via the recent tab, that contains an embedded image, i.e. `[img[Development of Selected.png]]`
3. observe the image does not load
4. open the image tiddler via the recent tab
5. scroll to the text tiddler and observe that the embedded image has loaded

At step 4, alternately opening the text tiddler for editing and saving it will also cause the embedded image to load.
At step 4, alternately opening an unrelated text tiddler will also cause the image to load.

**Expected behavior**
When using lazy loading, embedded images load at the same time as the text tiddlers that embed them.

**TiddlyWiki Configuration (please complete the following information):**
 - Version 5.1.23
 - Saving mechanism node.js with root-tiddler=$:/core/save/lazy-all and a path-prefix
 - Plugins installed TimeTodo, Highlight
 
**Desktop (please complete the following information):**
 - OS: windows 10
 - Browser repro in brave, firefox, chrome
 - Version current for each 

**Additional context**
I don't observe any network request for the image in the browser's dev tools until step 4.

**Comment by linonetwo** [comment]
On my side, I can't even start the wiki when using `$:/core/save/lazy-all`

Uncaught TypeError: Cannot read properties of undefined (reading 'name')
    at index.js:4663
    at index.js:4652
    at Object.$tw.utils.each (index.js:3923)
    at Object.$tw.modules.forEachModuleOfType (index.js:4651)
    at Object.$tw.modules.getModulesByTypeAsHashmap (index.js:4662)
    at Object.exports.startup ($:/core/modules/startup/load-modules.js:36)
    at Object.$tw.boot.executeNextStartupTask (index.js:6261)
    at Object.$tw.boot.execStartup (index.js:6208)
    at Object.$tw.boot.startup (index.js:6218)
    at index.js:6384
VM141 925.chunk.js:1 

<img width="771" alt="截屏2021-11-11 下午1 57 43" src="https://user-images.githubusercontent.com/3746270/141245649-cc41b08f-7f39-4692-a831-9866528fcf7a.png">

**Comment by gabrielmontagne** [comment]
Here having the same problem.  TW won't start with the lazy loading configuration set.

**Comment by linonetwo** [comment]
Today I think I can implement a "lazy-non-system-tiddlers", so only those tiddlers without macro def, don't have system tags, without "$:/" prefix will be lazied.

What do you think?

**Comment by Jermolene** [comment]
> Today I think I can implement a "lazy-non-system-tiddlers", so only those tiddlers without macro def, don't have system tags, without "$:/" prefix will be lazied.
> 
> What do you think?

Hi @linonetwo that sounds like an interesting approach.

Some attention here would be very helpful. Lazy loading is evidently popular with users and yet our current implementation is brittle and has in some cases had dangerous side effects.

**Comment by mdemoss** [comment]
I updated to 5.3.1. The issue appears to be resolved with linked images and transclusions. TW not starting in some configurations may be a separate issue.
