### ISSUE TITLE
[IDEA] slugify and some odd characters mishandling

### ISSUE THREAD

**Issue by psiloi** [Jermolene/TiddlyWiki5#6066]
Today, slugify just erase some characters that would instead better be translated into meaningfull characters. Here are those that I spot so far:

German:
ß --> ss
ẞ --> SS

old English:
ð --> d
Ð --> D
þ --> th
Þ --> TH

Any language:
… --> ... (this is the three dots char that would be translated as a sequence three dots)

As for …, it could be argued that it's just a punctuation like ? or ! and so be treated alike just like it is currently. But many people ignore the … character and use ... and slugify currently keeps these 3 dots, so it would not be very logical to keep the current situation.

**Comment by Jermolene** [comment]
Thanks @psiloi fix coming up.
