### ISSUE TITLE
[IDEA] Indicate which tiddler is being rendered earlier in verbose output

### ISSUE THREAD

**Issue by sobjornstad** [Jermolene/TiddlyWiki5#6067]
Preface: if someone can let me know whether this makes sense to them and what approach would be best, I'm happy to write this up and send in a PR.

**Is your feature request related to a problem? Please describe.**

When running `tiddlywiki --verbose --render`, the name of each tiddler being rendered is logged to the console only *after* most errors would occur, such as parsing exceptions. This makes it difficult to see which tiddler is causing the renderer to blow up.

**Describe the solution you'd like**

In [render.js](https://github.com/Jermolene/TiddlyWiki5/blob/master/core/modules/commands/render.js), either:

* Move lines 54-56 (logging out the name of the tiddler) to the very top of their containing block (right after `.each`), so that the tiddler that it's attempting to render appears before parsing.
* If that is deemed confusing (e.g., because the render isn't technically starting yet), add a second `console.log` at the very top of the block indicating which tiddler we're about to try to parse and render.

**Describe alternatives you've considered**

I cannot think of any other ways to obtain this information, other than by going into my wiki, digging around, and finding the next tiddler alphabetically, which is silly, as well as useless when attempting to provide an error message in a program that calls the TiddlyWiki CLI (the scenario that led me here).

**Comment by Jermolene** [comment]
Thanks @sobjornstad that makes sense, I agree we should move the logging to the top of the block.
