### ISSUE TITLE
favicon doesn't load when restarting firefox

### ISSUE THREAD

**Issue by tgirod** [Jermolene/TiddlyWiki5#607]
Not sure if the problem is caused by TW5 or firefox. Opening TW5 automatically when firefox starts won't load the favicon. Steps to reproduce:
- from firefox preferences, choose "show my windows and tabs from last time"
- open your tiddlywiki file
- close firefox
- start firefox. your tiddlywiki tab should load, without the favicon.

**Comment by pmario** [comment]
@tgirod .. bump .. still a problem?
