### ISSUE TITLE
Looking for a way to make permalinks for tiddlers with non-English names shorter and more readable

### ISSUE THREAD

**Issue by MelomanCool** [Jermolene/TiddlyWiki5#6071]
Most of my tiddlers are in Russian, and TiddlyWiki handles that just fine. But when I try to send a link to a tiddler to somebody, it becomes pretty inconvenient, because the link is long and unreadable.

For example:
1. Create a tiddler named **"Тестовая заметка"**
2. The permalink is: https://example.com/#%D0%A2%D0%B5%D1%81%D1%82%D0%BE%D0%B2%D0%B0%D1%8F%20%D0%B7%D0%B0%D0%BC%D0%B5%D1%82%D0%BA%D0%B0

In contrast, if tiddler's name is in English:
1. Create a tiddler named **"Testovaya zametka"**
2. The permalink is: https://example.com/#Testovaya%20zametka

It would be much more convenient if the permalink used transliteration or a slug of the title, so the link would look like in the second example. Is there an option or a plugin to make it possible?

TiddlyWiki version is 5.1.23

P.S. Thank you for such a great wiki! The hierarchical tagging is just amazing, especially with a couple of plugins for search and backreferences.

**Comment by pmario** [comment]
There is a function in the core: https://github.com/Jermolene/TiddlyWiki5/blob/master/core/modules/utils/transliterate.js which may be used to change the characters prior to translating them to some gogledegoop.

There are some Cyrillic characters in the code. Can you see, if there is enough information to translate your tiddler titles. If yes it should be easy to adjust the links

**Comment by MelomanCool** [comment]
Yes, I can see the whole Russian alphabet at the end of the dictionary.

**Comment by pmario** [comment]
There is a tiddler.slug field, which can be used to create filenames atm. ... This info could also be used to create permalinks. BUT we would also need to create a function in the core, that would allow us to use the slug as a permalink indicator. ... This function doesn't exist at the moment. 

@Jermolene What do you think about a mechanism that can use a slug as a permalink ... My idea at the moment is, that there must be a slug field.

**Comment by joshuafontany** [comment]
For the time being, I would suggest the story filter notation in the URL option: https://tiddlywiki.com/#PermaLinks
"It is also possible to specify a story filter without specifying a target tiddler for navigation:

https://tiddlywiki.com/#:[tag[task]]

About URL encoding
There are technical restrictions on the legal characters in an URL fragment. To allow all tiddler titles to be addressed, illegal characters are subject to a process called "URL encoding" whereby problematic characters are replaced by their numeric code. For example, the space character is replaced with %20.

Both the target tiddler title and the story filter should be URL encoded (but not the separating colon). TiddlyWiki generates properly encoded URLs which can look quite ugly. However, in practice browsers will usually perfectly happily process arbitrary characters in URL fragments. Thus when creating permalinks manually you can choose to ignore URL encoding."

So you can have a literal link of `https://tiddlywiki.com/#:[title[Тестовая заметка]]` and that's what the user would see, even thought the browser is converting it to `https://tiddlywiki.com/#:[title[%D0%A2%D0%B5%D1%81%D1%82%D0%BE%D0%B2%D0%B0%D1%8F%20%D0%B7%D0%B0%D0%BC%D0%B5%D1%82%D0%BA%D0%B0]]` behind the scenes (for example, I copy/pasted that string out of the browser url bar after testing the legible version).

**Comment by MelomanCool** [comment]
> It is also possible to specify a story filter without specifying a target tiddler for navigation:
https://tiddlywiki.com/#:[tag[task]]

Thank you for pointing this out! I was able to make an alternative permalink button:

Name: `$:/core/ui/Buttons/permalink-slug`
Tag: `$:/tags/ViewToolbar`

```
\define whole-string-regexp() (.*)
\define replacement() https://example.com/#:[slug[$1]]

\whitespace trim
<$button tooltip={{$:/language/Buttons/Permalink/Hint}} aria-label={{$:/language/Buttons/Permalink/Caption}} class=<<tv-config-toolbar-class>>>
<$action-setfield $tiddler=<<currentTiddler>> $field="slug" $value={{{[<currentTiddler>slugify[]]}}}/>
<$action-sendmessage $message="tm-copy-to-clipboard" $param={{{[<currentTiddler>slugify[]search-replace::regexp<names>,<whole-string-regexp>]}}}/>
<$list filter="[<tv-config-toolbar-icons>match[yes]]">
{{$:/core/images/permalink-button}}
</$list>
<$list filter="[<tv-config-toolbar-text>match[yes]]">
<span class="tc-btn-text">
<$text text=" "/>
<$text text={{$:/language/Buttons/Permalink/Caption}}/>
</span>
</$list>
</$button>
```

Basically it assigns the slug to current tiddler and then copies the link.

**Comment by pmario** [comment]
>It is also possible to specify a story filter without specifying a target tiddler for navigation:
https://tiddlywiki.com/#:[tag[task]]

You are right. I did forget about this possibility.
