### ISSUE TITLE
TiddlyWiki v5.2.0 release - last call for bug fixes and outstanding PRs

### ISSUE THREAD

**Issue by Jermolene** [Jermolene/TiddlyWiki5#6073]
Thanks to considerable hard work on the part of many people, TiddlyWiki v5.2.0 is (again) nearing readiness for release. This is a final call (continuing from #5717) for any bug fixes or other PRs for inclusion.

In order to get this done, we need strict criteria for any further changes. It is proposed that:

* Fixes for bugs introduced in v5.2.0 will be accepted
* Fixes for bugs existing in v5.1.23 will only be accepted if the bug is serious and liable to affect many users
* PRs for improvements will only be accepted if there is an overwhelming case for not deferring until the next release

Please also take this opportunity to test the new release with your existing wikis. The core team does not do any systematic tests with third party plugins, so we really rely on the community for feedback.

**Comment by saqimtiaz** [comment]
Can be merged:

- JSONTiddler a little more extensible to allow plugins like Uglify to work #6057
- #6013

Recommend reviewing:
- #6026 - It has been updated since last review

Lastly just a reminder that we do need to update the TiddlyWikiLinks code to work with 5.2.0: https://github.com/TiddlyWikiLinks/TiddlyWikiLinks/issues/22

**Comment by Jermolene** [comment]
Many thanks @saqimtiaz. I've merged #6057, and reviewed #6026 but don't think it's ready to merge. I also pushed a fix for TiddlyWikiLinks and the new JSON store area.

**Comment by pmario** [comment]
I think the following PRs should be considered: 

 -  make-open-bar-more-customizable #5948 
 - partially-fix-1554-timeline-macro

**Comment by Jermolene** [comment]
Thanks @pmario I've made a comment on each.

**Comment by EvidentlyCube** [comment]
@pmario has mentioned that #6080 (Polish translation) could potentially be included in the release, so I am posting it here.
