### ISSUE TITLE
[IDEA] Improving the performance of $tw.utils.each

### ISSUE THREAD

**Issue by Gk0Wk** [Jermolene/TiddlyWiki5#6098]
> Note that this issue is also a topic in [talk.tiddlywiki.org](https://talk.tiddlywiki.org/t/idea-improving-the-performance-of-tw-utils-each/1100).

I noticed that the `$tw.utils.each` function (a very important core function used in most filters) in `$:/boot/boot.js` first determines the type of the object to be traversed, and uses a `for` loop to traverse it if it is an array, or a `for` + `Object.keys` loop to traverse it if it is an object. I recently conducted performance tests on various ways of traversing arrays and objects on several major browsers and came to some conclusions.

- For array traversal, using the sequential [Duff's Device algorithm](https://en.wikipedia.org/wiki/Duff%27s_device) can improve performance somewhat.
- For object traversal, the `for` + `Object.keys` approach is very efficient in most cases, but `for...in...` should be preferred in Safari (by detecting Safari browser first using `/version.*safari/i.test(navigator.userAgent)`).

The following is used to prove my conclusion.

---

## Benchmark test part

My test environment:

- Apple MacBook Pro 2017 (15-inch)
- macOS Big Sur (v11.6 (20G165)), Darwin Kernel Version 20.6.0
- CPU: 3.1 GHz Quad-Core Intel Core i7-7920HQ
- Memory: LPDDR3 2133 MHz 8G x 2

I have tested it in four browsers:

- Chrome 94.0.4606.81 (Official Build) (x86_64)
- FireFox 93.0 (x86_64)
- Safari 15.0 (16612.1.29.41.4, 16612)
- Edge 94.0.992.37 (Official build) (x86_64) (**Note that Edge also uses Chrome kernel**)

Test Method:

I encapsulate the various traversal methods into a function `each(obj, callback)`, which takes an argument `obj` to be traversed (possibly an array or object) and traverses the elements of it and calls the function `callback` one by one. For the array traversal test and the object traversal test, the following `callback` functions are used, respectively.

```javascript
// For Array
let arr_ = [];
each(EXAMPLE_ARRAY, (x) => {
  arr_.push(x);
});

// For Object
let obj_ = {};
each(EXAMPLE_OBJECT, (key, value) => {
  obj_[key] = value + 1;
});
```

The sizes of `EXAMPLE_ARRAY` and `EXAMPLE_OBJECT` are both 10000000. I timed each traversal method and counted the average of five timings as the test result.

---

### Array

<details>
<summary>Benchmark script for array</summary>

Thanks to [nullqube](https://stackoverflow.com/a/49105977);

```javascript
!(function () {
  const TEST_TIMES = 5;
  const ARRAY_SIZE = 10000000;
  const EXAMPLE_ARRAY = new Array(ARRAY_SIZE).fill(255);
  function time(name, each) {
    var totalDuration = 0;
    console.log(`[${name}]`);
    for (var i = 0; i < TEST_TIMES; i++) {
      let arr_ = [];
      const start = new Date();
      each(EXAMPLE_ARRAY, (x) => {
        arr_.push(x);
      });
      const end = new Date();
      var duration = end - start;
      console.log(`    * ${duration}ms`);
      totalDuration += duration;
      arr_ = undefined;
    }
    console.log(`    average: ${totalDuration / 5}ms`);
  }

  time("for i<len", (arr, func) => {
    var i, len;
    for (i = 0, len = arr.length; i < len; i++) {
      func(arr[i]);
    }
  });

  time("for i<arr.length", (arr, func) => {
    var i;
    for (i = 0; i < arr.length; i++) {
      func(arr[i]);
    }
  });

  time("while i<len", (arr, func) => {
    var i = 0,
      len = arr.length;
    while (i < len) {
      func(arr[i++]);
    }
  });

  time("forEach", (arr, func) => {
    arr.forEach(func);
  });

  time("for var..of..", (arr, func) => {
    for (var x of arr) {
      func(x);
    }
  });

  time("for let..of..", (arr, func) => {
    for (let x of arr) {
      func(x);
    }
  });

  time("for const..of..", (arr, func) => {
    for (const x of arr) {
      func(x);
    }
  });

  time("for var..in..", (arr, func) => {
    for (var i in arr) {
      func(arr[i]);
    }
  });

  time("for let..in..", (arr, func) => {
    for (let i in arr) {
      func(arr[i]);
    }
  });

  time("for const..in..", (arr, func) => {
    for (const i in arr) {
      func(arr[i]);
    }
  });

  time("Duff's device", (arr, func) => {
    var len = arr.length;
    var n = len % 8;
    var i;
    if (n > 0) {
      do {
        func(arr[len - n]);
      } while (--n); // n must be greater than 0 here
    }
    n = (len * 0.125) ^ 0;
    if (n > 0) {
      do {
        i = --n << 3;
        func(arr[i]);
        func(arr[i + 1]);
        func(arr[i + 2]);
        func(arr[i + 3]);
        func(arr[i + 4]);
        func(arr[i + 5]);
        func(arr[i + 6]);
        func(arr[i + 7]);
      } while (n); // n must be greater than 0 here also
    }
  });

  time("Duff's device (Ordered)", (arr, func) => {
    var len = arr.length;
    var block = (len * 0.125) ^ 0;
    var i, n;
    if (block > 0) {
      n = 0;
      do {
        i = n++ << 3;
        func(arr[i]);
        func(arr[i + 1]);
        func(arr[i + 2]);
        func(arr[i + 3]);
        func(arr[i + 4]);
        func(arr[i + 5]);
        func(arr[i + 6]);
        func(arr[i + 7]);
      } while (n < block); // n must be greater than 0 here also
    }
    n = len % 8;
    if (n > 0) {
      do {
        func(arr[len - n]);
      } while (--n); // n must be greater than 0 here
    }
  });
})();
```

**Please note: I didn't do a deep verification of my [Duff's Device algorithm](https://en.wikipedia.org/wiki/Duff%27s_device) implementation, I just tested it with some general arrays and verified it is correct. So there is no guarantee that this way of implementing the algorithm is completely correct. If someone finds a problem with it, please just point it out!**

</details>

Result (details are [here](https://gist.github.com/Gk0Wk/8bdc1ba104dee6e5d5881c0d63aeea96)):

|                         | Chrome   | FireFox   | Safari   | Edge     |
| ----------------------- | -------- | --------- | -------- | -------- |
| for i<len               | 269.8ms  | 211.4ms   | 295.4ms  | 252.8ms  |
| for i<arr.length        | 201.4ms  | 204ms     | 222.4ms  | 240.2ms  |
| while i<len             | 258ms    | 201.2ms   | 363ms    | 184.2ms  |
| forEach                 | 332.8ms  | 235.6ms   | 260.2ms  | 272.2ms  |
| for var..of..           | 310.6ms  | 254ms     | 360ms    | 249.6ms  |
| for let..of..           | 272ms    | 241.8ms   | 339.2ms  | 236.6ms  |
| for const..of..         | 289.2ms  | 261.8ms   | 342.2ms  | 271.6ms  |
| for var..in..           | 3680.2ms | 15953.6ms | 6477.2ms | 3151ms   |
| for let..in..           | 2862.8ms | 15977.8ms | 6657.6ms | 3001.6ms |
| for const..in..         | 3087.2ms | 15790ms   | 8089ms   | 2947.2ms |
| Duff's device           | 162.2ms  | 184.4ms   | 248.2ms  | 133.4ms  |
| Duff's device (Ordered) | 176ms    | 184.6ms   | 241ms    | 175.8ms  |

As a result, [Duff's Device algorithm](https://en.wikipedia.org/wiki/Duff%27s_device) is even faster than `for` loop. Considering that it is more suitable for optimizing complex traversal operations, I think it should be used as the traversal method for arrays.

---

### Object

<details>
<summary>Benchmark script for object</summary>

Thanks to [pod4g/tool](https://github.com/pod4g/tool/wiki/%E5%90%84%E7%A7%8D%E9%81%8D%E5%8E%86%E7%9A%84%E6%80%A7%E8%83%BD).

```javascript
!(function () {
  const TEST_TIMES = 5;
  const OBJECT_SIZE = 10000000;
  const EXAMPLE_OBJECT = {};
  for (var i = 0, j = OBJECT_SIZE; i < j; i++) EXAMPLE_OBJECT[i] = i;
  function duffOrdered(arr, func) {
    var len = arr.length;
    var block = (len * 0.125) ^ 0;
    var i, n;
    if (block > 0) {
      n = 0;
      do {
        i = n++ << 3;
        func(arr[i]);
        func(arr[i + 1]);
        func(arr[i + 2]);
        func(arr[i + 3]);
        func(arr[i + 4]);
        func(arr[i + 5]);
        func(arr[i + 6]);
        func(arr[i + 7]);
      } while (n < block); // n must be greater than 0 here also
    }
    n = len % 8;
    if (n > 0) {
      do {
        func(arr[len - n]);
      } while (--n); // n must be greater than 0 here
    }
  }
  function time(name, each) {
    var totalDuration = 0;
    console.log(`[${name}]`);
    for (var i = 0; i < TEST_TIMES; i++) {
      let obj_ = {};
      const start = new Date();
      each(EXAMPLE_OBJECT, (key, value) => {
        obj_[key] = value + 1;
      });
      const end = new Date();
      var duration = end - start;
      console.log(`    * ${duration}ms`);
      totalDuration += duration;
      obj_ = undefined;
    }
    console.log(`    average: ${totalDuration / 5}ms`);
  }

  time("for..in..", (obj, func) => {
    for (var key in obj) {
      func(key, obj[key]);
    }
  });

  time("duff+Object.getOwnPropertyNames", (obj, func) => {
    duffOrdered(Object.getOwnPropertyNames(obj), (key) => {
      func(key, obj[key]);
    });
  });

  time("duff+Reflect.ownKeys", (obj, func) => {
    duffOrdered(Reflect.ownKeys(obj), (key) => {
      func(key, obj[key]);
    });
  });

  time("duff+Object.entries", (obj, func) => {
    duffOrdered(Object.entries(obj), (entry) => {
      func(entry[0], entry[1]);
    });
  });

  time("duff+Object.keys", (obj, func) => {
    duffOrdered(Object.keys(obj), (key) => {
      func(key, obj[key]);
    });
  });
  time("for+Object.keys", (obj, func) => {
    var keys = Object.keys(obj);
    var i, length;
    for (i = 0, length = keys.length; i < length; i++) {
      func(keys[i], obj[keys[i]]);
    }
  });
})();
```

</details>

Result (details are [here](https://gist.github.com/Gk0Wk/8bdc1ba104dee6e5d5881c0d63aeea96)):

|                                 | Chrome    | FireFox  | Safari   | Edge     |
| ------------------------------- | --------- | -------- | -------- | -------- |
| for..in..                       | 3256.2ms  | 16665ms  | 6635.6ms | 3199.2ms |
| duff+Object.getOwnPropertyNames | 7922.6ms  | 1483ms   | 8904.8ms | 9849.4ms |
| duff+Reflect.ownKeys            | 8602.4ms  | 1410ms   | 7912.8ms | 8044.2ms |
| duff+Object.entries             | 11984.8ms | 5405.8ms | 8453.8ms | 11502ms  |
| duff+Object.keys                | 3120.4ms  | 1458.8ms | 7920.6ms | 3004.6ms |
| for+Object.keys                 | 3178.8ms  | 1329.2ms | 8613.2ms | 3020ms   |

Surprisingly, the [Duff's Device algorithm](https://en.wikipedia.org/wiki/Duff%27s_device) is not the fastest way to iterate over objects, so a for loop should be used. But we noticed a detail that `for` + `Object.keys` is less efficient on Safari browser, so `for... should be used. .in... ` loop for traversal.

---

Then, I have implemented the new `each` function and I have placed the code below.

<details>
<summary>New each function</summary>

```javascript
var isSafari = $tw.browser && navigator && /version.*safari/i.test(navigator.userAgent);
$tw.utils.each = function(object, callback) {
    var next, f, n, length;
    if (object) {
        if (Object.prototype.toString.call(object) == "[object Array]") {
            length = object.length;
            var blocks = (length * 0.125) ^ 0;
            if (blocks > 0) {
                n = 0;
                do {
                    f = n++ << 3;
                    next = callback(object[f], f, object) === false ||
                        callback(object[f + 1], f, object) === false ||
                        callback(object[f + 2], f, object) === false ||
                        callback(object[f + 3], f, object) === false ||
                        callback(object[f + 4], f, object) === false ||
                        callback(object[f + 5], f, object) === false ||
                        callback(object[f + 6], f, object) === false ||
                        callback(object[f + 7], f, object) === false;
                    if (next) {
                        return;
                    }
                } while (n < blocks); // n must be greater than 0 here also
            }
            f = length % 8;
            if (f > 0) {
                do {
                    next = callback(object[length - f], length - f, object);
                } while (--f && next !== false); // n must be greater than 0 here
            }
        } else {
            if (isSafari) {
                for (var key in object) {
                    next = callback(object[key], key, object);
                    if (next === false) {
                        break;
                    }
                }
            } else {
                var keys = Object.keys(object);
                for (f = 0, length = keys.length; f < length; f++) {
                    var key = keys[f];
                    next = callback(object[key], key, object);
                    if (next === false) {
                        break;
                    }
                }
            }
        }
    }
};
```

</details>

In addition, I wrote a method to test the performance of both old and new `each` functions. I only have my macOS environment, so I need some assistance with testing. Anyone can run the following code in their browser console and we can work together to see if this algorithm really improves performance.

<details>
<summary>Benchmark script for old/new each function</summary>

```javascript
!(function() {
    // Initalize
    const TEST_TIMES = 50;
    const ARRAY_SIZE = 10000000;
    const OBJECT_SIZE = 10000000;
    const EXAMPLE_ARRAY = new Array(ARRAY_SIZE).fill(255);
    const EXAMPLE_OBJECT = {};
    for (var i = 0, j = OBJECT_SIZE; i < j; i++) EXAMPLE_OBJECT[i] = i;

    // Two each functions
    const isSafari = navigator && /version.*safari/i.test(navigator.userAgent);
    const each1 = function(object, callback) {
        var next, f, length;
        if (object) {
            if (Object.prototype.toString.call(object) == "[object Array]") {
                for (f = 0, length = object.length; f < length; f++) {
                    next = callback(object[f], f, object);
                    if (next === false) {
                        break;
                    }
                }
            } else {
                var keys = Object.keys(object);
                for (f = 0, length = keys.length; f < length; f++) {
                    var key = keys[f];
                    next = callback(object[key], key, object);
                    if (next === false) {
                        break;
                    }
                }
            }
        }
    };
    const each2 = function(object, callback) {
        var next, f, n, length;
        if (object) {
            if (Object.prototype.toString.call(object) == "[object Array]") {
                length = object.length;
                var blocks = (length * 0.125) ^ 0;
                if (blocks > 0) {
                    n = 0;
                    do {
                        f = n++ << 3;
                        next = callback(object[f], f, object) === false ||
                            callback(object[f + 1], f, object) === false ||
                            callback(object[f + 2], f, object) === false ||
                            callback(object[f + 3], f, object) === false ||
                            callback(object[f + 4], f, object) === false ||
                            callback(object[f + 5], f, object) === false ||
                            callback(object[f + 6], f, object) === false ||
                            callback(object[f + 7], f, object) === false;
                        if (next) {
                            return;
                        }
                    } while (n < blocks); // n must be greater than 0 here also
                }
                f = length % 8;
                if (f > 0) {
                    do {
                        next = callback(object[length - f], length - f, object);
                    } while (--f && next !== false); // n must be greater than 0 here
                }
            } else {
                if (isSafari) {
                    for (var key in object) {
                        next = callback(object[key], key, object);
                        if (next === false) {
                            break;
                        }
                    }
                } else {
                    var keys = Object.keys(object);
                    for (f = 0, length = keys.length; f < length; f++) {
                        var key = keys[f];
                        next = callback(object[key], key, object);
                        if (next === false) {
                            break;
                        }
                    }
                }
            }
        }
    };

    // Tests
    function timeArray(name, each) {
        var totalDuration = 0;
        console.log(`[${name} on Array]`);
        for (var i = 0; i < TEST_TIMES; i++) {
            let arr_ = [];
            const start = new Date();
            each(EXAMPLE_ARRAY, (x) => {
                arr_.push(x + 1);
            });
            const end = new Date();
            var duration = end - start;
            console.log(`    * ${duration}ms`);
            totalDuration += duration;
            arr_ = undefined;
        }
        console.log(`    average: ${totalDuration / TEST_TIMES}ms`);
    }

    function timeObject(name, each) {
        var totalDuration = 0;
        console.log(`[${name} on Object]`);
        for (var i = 0; i < TEST_TIMES; i++) {
            let obj_ = {};
            const start = new Date();
            each(EXAMPLE_OBJECT, (value, key) => {
                obj_[key] = value + 1;
            });
            const end = new Date();
            var duration = end - start;
            console.log(`    * ${duration}ms`);
            totalDuration += duration;
            obj_ = undefined;
        }
        console.log(`    average: ${totalDuration / TEST_TIMES}ms`);
    }

    timeArray('Original each', each1);
    timeArray('New each', each2);
    timeObject('Original each', each1);
    timeObject('New each', each2);
})();
```

</details>

**Comment by saqimtiaz** [comment]
**Windows 10**
**Chrome 94 (64 bit)**

Array:
Original each:  average: 142.16ms
New each: average: 128.42ms

Object
Original each: average: 2250.08ms
New each: average: 2142.82ms

**Firefox 93 (64 bit)**
Array:
Original each: average: 197.52ms
New each: average: 194.14ms

Object:
Original each: average: 843.68ms
New each: 863.76ms

**Edge**
Array: 
Original each: average: 129.08ms
New each: average: 127.24ms

Object:
Original each: average: 2123.08ms
New each: average: 2130.12ms

---
**Ubuntu**
**Chrome**

Array:
Original each:  average: 151.51ms
New each: average: 138.92ms

Object
Original each: average: 2357.08ms
New each: average: 2169.89ms

**Firefox 93**
Array:
Original each: average: 196.45ms
New each: average: 193.67ms

Object:
Original each: average: 837.38ms
New each: 837.56ms

**Comment by pmario** [comment]
@Gk0Wk ... Artificial benchmarks are nice, but how did it perform in TiddlyWiki with many tiddlers?

So imo it would be needed to have before and after values of the performance measured in TW.

**Comment by Gk0Wk** [comment]
@saqimtiaz Thanks for the test! From the experimental results, I think the optimization may not be very obvious.

@pmario I think the best way to test it in TW is to do some tests with `$tw.utils.filterTiddlers` using a complex filter expression. But I couldn't find a tiddler size that could satisfy the testing accuracy (I think it should take several million tiddlers). So maybe this improvement does not bring much benefit. So after testing and thinking about it, I don't think such an improvement is worth it.

@flibbles Thanks, the `each` function is mainly used in filters. As for the `forEach` traversal method you mentioned, it is faster in tests, but generally not the fastest. Also, if you add a statement like `object.find(function(obj,f) { return callback(obj,f) === false; });`, performance does suffer.

**Comment by Jermolene** [comment]
Thanks @Gk0Wk @flibbles @pmario @saqimtiaz much appreciated. We've had some great results from previous optimisation efforts, and so it's always good to see experimentation in this area.

I wanted to point out the performance test rig I put together for tracking down the v5.2.0 performance regressions:

https://github.com/Jermolene/tiddlywiki-performance-test-rig

It's very primitive at the moment, but there's great benefit in improving it so that we can consistently compare results. I'd also like to explore including some basic performance regression tests in our main test suite.

A general observation about performance optimisations is that we should avoid getting too tied to the performance peculiarities of particular browser engines at particular times. Although we make regular new releases of the TiddlyWiki core, it is inevitable that some largish proportion of the deployments may never be subsequently upgraded. Thus, each release of TiddlyWiki is destined to be a sliver of future legacy.

Broadly that means that the most compelling optimisations are those that make an improvement in all browsers, not just in one particular engine.
