### ISSUE TITLE
[BUG] filter operator tiddlers in TW docs are not displaying all the table rows

### ISSUE THREAD

**Issue by btheado** [Jermolene/TiddlyWiki5#6100]
**Describe the bug**

The `$:/editions/tw5.com/operator-template` template used to display the tabular documentation for filter operators is not properly displaying all the rows.

**To Reproduce**

For one example, visit https://tiddlywiki.com/#prepend%20Operator and notice the tiddler is displaying only input, suffix, and output rows.

**Expected behavior**

Previous versions of tiddlywiki used to also display purpose, parameter list, and !output rows.

**Additional context**

Using `git bisect`, it looks like the issue was introduced with commit ca95f1069fae5223022ad3756366aeab79c9d48f (fix for #5396).

Looking at the contents of `$:/editions/tw5.com/operator-template`, I think the above commit just exposed use of improper html comments? That tiddler has lines like `<!-->` in between each row of display. I don't think that is proper syntax? It doesn't go well with the current parser at least.

Those comment lines should be fixed or removed so the tiddlywiki.com documentation will display correctly again.

**Comment by saqimtiaz** [comment]
Good catch. I recall writing docs for one of the new filter operators and feeling like there was something off with the display but not being able to put my finger on what had changed.

**Comment by pmario** [comment]
I found it. The problem is https://tiddlywiki.com/#%24%3A%2Feditions%2Ftw5.com%2Foperator-macros
It contains `<!-->` which is an invalid html comment. If changed to `<!-- -->` everything works again.

BUT There is still a problem. This should not have happened.
