### ISSUE TITLE
codemirror plugin issue: TypeError from certain characters in vim insert mode 

### ISSUE THREAD

**Issue by scytale** [Jermolene/TiddlyWiki5#611]
To replicate:
1. download a fresh 5.0.10-beta from http://tiddlywiki.com
2. add $:/plugins/tiddlywiki/codemirror and example config in HelloThere tiddler from http://tiddlywiki.com/codemirrordemo.html [1]
3. save and reload page to take effect
4. Create new tiddler, set focus to text, type i to go into vim insert mode
5. user enters any of the following characters: -_+=
   and raises
   TypeError: keyName.indexOf is not a function

[1] $:/config/CodeMirror used in example

<pre>{
  "require": [
      "$:/plugins/tiddlywiki/codemirror/addon/dialog.js",
      "$:/plugins/tiddlywiki/codemirror/addon/searchcursor.js",
      "$:/plugins/tiddlywiki/codemirror/keymap/vim.js",
      "$:/plugins/tiddlywiki/codemirror/keymap/emacs.js"
  ],
  "configuration": {
      "keyMap": "vim",
      "showCursorWhenSelecting": true
  }
}
</pre>

**Comment by pmario** [comment]
@scytale ... I think this one can be closed. We did completely rework the codemirror plugins in 5.1.16 .. If new problems come up, a new issue should be created.

**Comment by Jermolene** [comment]
Thanks @pmario
