### ISSUE TITLE
[IDEA] zero based nth[] operator

### ISSUE THREAD

**Issue by saqimtiaz** [Jermolene/TiddlyWiki5#6122]
While the `nth[]` operator starts at 1, the `:reduce` (and soon `:map`) prefixes are zero based as is the `reduce[]` filter operator. This means you cannot use the `index` variable inside the reduce filter with the `nth[]` operator.

Suggestions:
* Either we introduce a new operator akin to `nth[]` that is zero based,
* or we extend `nth[]` to have an affordance to switch it to being zero based, keeping the existing behaviour as default

**Comment by pmario** [comment]
What about: `nth:0[]` I think this would make it clear enough.

**Comment by pmario** [comment]
>I don't disagree. However the point remains that nth:0[] will mislead users into believing that different offset values are supported.

You are right. I do prefer your suggestion `nth:zero[]`
