### ISSUE TITLE
[BUG] Search-Replace with $ in Search String

### ISSUE THREAD

**Issue by kookma** [Jermolene/TiddlyWiki5#6129]
**Describe the bug**
The search-replace eats `$`

**To Reproduce**
1. Go to https://tiddlywiki.com/
2. Create a tiddler with content below

```
<$vars for="equation $$x$$ end." with="relation $$x$$  finish." source="This is equation $$x$$ end.">
{{{ [<source>search-replace<for>,<with>] }}}
</$vars>
```

See the result 

```
This is relation $x$ finish.
```

The `search-replace` operator eats one of `$`

NOTE: I also tested with `regexp-mode` with no success!

**Expected behavior**
Should keep both `$$`!

**TiddlyWiki Configuration (please complete the following information):**
 - Version 5.2.0
 - Saving mechanism -
 - Plugins installed -
 
**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome 90

**Comment by saqimtiaz** [comment]
Are you sure you tried regexp mode?

```
<$vars for="equation $$x$$ end." with="relation $$x$$  finish." source="This is equation $$x$$ end.">
{{{ [<source>search-replace::regexp<for>,<with>] }}}
</$vars>

```

**Comment by saqimtiaz** [comment]
I think the underlying issue is probably the escaping of special characters for regular expressions and a possible misunderstanding on my part as to what `$tw.utils.escapeRegExp` does. I will investigate when I get the opportunity but it might take a while.

**Comment by kookma** [comment]
Thank you Saq for clarification!

**Comment by CodaCodr** [comment]
Ah... I see. Anomaly there is the difference in results. Strange.

**Comment by saqimtiaz** [comment]
@kookma this has now been fixed in the pre-release. Please do test.

**Comment by kookma** [comment]
Much appreciated! Thank you @saqimtiaz
