### ISSUE TITLE
[BUG] EditTextWidget - unexpected placeholder behaviour in missing tids

### ISSUE THREAD

**Issue by twMat** [Jermolene/TiddlyWiki5#6152]
No biggie but still confusing:

The EditTextWidget behaves in unexpected ways when there's a placeholder for a missing tiddler. 
For a missing tiddler, both of these:

`<$edit-text tiddler=missing placeholder="foo"/>` 
`<$edit-text tiddler=missing placeholder="foo" field=text/>`

disregard the placeholder. Instead the message `Type the text for the tiddler 'missing'` is shown. 

1. I was expecting the placeholder to show.
2. The shown message is not a placeholder but some kind of default value. This means it doesn't go away as soon as I type, like a placeholder would, but I must instead manually erase the message.

Further, specifying any(?) `field` value other than `text` *does* make the placeholder show, e.g:
 
`<$edit-text tiddler=missing placeholder="foo" field=bar/>`

(Actually, even a valueless `field` parameter makes the placeholder show.)

**Proposal**
A placeholder should always take precedence when it is defined and there is no user defined `default` value. This behaviour should be the same for existing and missing tiddlers.

**Comment by pmario** [comment]
I think the "missing tiddler text" was there till be beginning of TW. 
The placeholder was probably added later. ... So I think that's an oversight. 

On a first thougth: **I do support your proposal.**

**Comment by AnthonyMuscio** [comment]
I support this proposal, in fact its bugged me for a while, my workaround is to use temp-tiddlers and fields therein to avoid. 

The advantage would be one can create tiddlers from an edit action in an edit-text widget without someone even knowing it was a separate tiddler. The tiddlername can be determined programaticaly then use the edit-text widgets inputActions to do more with the new tiddler eg add fields and tags.

A whole new way of creating tiddlers without the need (apparently) to create the tiddler.

**Comment by twMat** [comment]
bump

**Comment by Jermolene** [comment]
Hi @twMat I agree.

The default text `Type the text for the tiddler '" + this.editTitle + "'` no longer appears in the TiddlyWiki user interface and so I think we can safely drop the feature.

**Comment by pmario** [comment]
I think that's the problem mentined and it still exists

![image](https://user-images.githubusercontent.com/374655/187074232-da24be0b-df64-4711-818d-d74eb3452928.png)

**Comment by twMat** [comment]
> @Jermolene closed this as completed [...]

Thanks for fixing this! Just to make sure; will the fix ensure that the placeholder value shows?

**Comment by Jermolene** [comment]
> > @Jermolene closed this as completed [...]
> 
> Thanks for fixing this! Just to make sure; will the fix ensure that the placeholder value shows?

It does in my tests but do try it out for yourself on the prerelease.

**Comment by twMat** [comment]
>It does in my tests but do try it out for yourself on the prerelease.

OH, sorry, I didn't realize it was available in the prerelease that quickly... or maybe "merged" per definition means it is part of the prerelease?
Anyway, it works great now, thank you!
