### ISSUE TITLE
[IDEA] Wikify the content of $:/favicon.ico if tiddler.fields.type is set to text/vnd.tiddlywiki

### ISSUE THREAD

**Issue by Telumire** [Jermolene/TiddlyWiki5#6159]
**Is your feature request related to a problem? Please describe.**
Filters cant be used inside $:/favicon.ico because $tw.utils.makeDataUri apply datauri encoding regardless of tiddler.fields.type 

**Describe the solution you'd like**
If tiddler.fields.type is set to text/vnd.tiddlywiki, use the wikified content instead. This would allow to set dynamic favicons, e.g a favicon with a different color if darkmode is enabled, a favicon that show the date (google calendar), etc.

Another option would be to use a system tag such as $:/tags/RawMarkupWikified/TopHead to enable this behavior.

**Describe alternatives you've considered**

1. Set another favicon link in a tiddler and add the tag $:/tags/AboveStory. [This works](https://Telumire.github.io/TiddlyTweaks/index.html#:%5B%5BSVG%20favicon%5D%5D) but can mess up the layout since it add an element to the story river. Might not be standard html either since this is not in the head [1].

2. Use a startup action to set the content of $:/favicon.ico. The issue then is that the icon can only be updated by reloading the wiki or manually with a macro.

EDIT : 

[1] it seems like this only works on firefox, chrome only load favicon defined in the head. 
It is possible to set the favicon link in the head, by using the tag `$:/tags/RawMarkupWikified` and backticks : 

```
`<link rel="icon" type="image/svg+xml" href='`<$text text={{{[subfilter{SVG favicon!!uri}]}}}/>`'/>` 
```

but we loose the ability to do live update. It would also make more sense to be able to use $:/favicon.ico for this.

**Comment by Jermolene** [comment]
Thanks @Telumire that's an interesting idea, both in the specifics (dynamically setting a favicon) and the general (using wikitext to process binary data like images using base64 notation). I should be able to make a preliminary investigation later today.

**Comment by pmario** [comment]
>This would allow to set dynamic favicons, e.g a favicon with a different color if darkmode is enabled, a favicon that show the date (google calendar), etc.

There are 2 types of dark mode. The browser dark-theme mode, which is known by TW and the TW themed dark-mode, which is NOT known to the browser, so switching the icon in the later mode won't work out of the box, even if the wikitext logic is in place.

**Comment by Telumire** [comment]
@pmario Sorry, I'm not sure I understand .. the color theme used by TW cant change the color used for the browser tabs : as you said, the browser do not know if TW is using a dark theme or not. Therefore we only need to switch the icon used (be it svg or jpg/png) according to the browser mode. How would that be an issue ?

**Comment by pmario** [comment]
>How would that be an issue ?

I didn't say it's an issue, it just needs to be considered.

**Comment by Jermolene** [comment]
On reflection, I don't think it's worth implementing this feature at this point, primarily because it wouldn't let one do anything that couldn't be done by using `<$action-setfield>` to assign the result of a `<$wikify>` widget to the text field of `$:/favicon`.

**Comment by Telumire** [comment]
Indeed @Jermolene, since it's not possible to have "live" wikitext in the head, there is no advantage for this atm. Thanks to you and @pmario for sharing your thoughts on this ! I'm closing this issue.

**Comment by Telumire** [comment]
> The browser dark-theme mode, which is known by TW and the TW themed dark-mode, which is NOT known to the browser

@pmario it turns out that it is in fact possible to inform the browser of the color palette used ! 
With <meta name="theme-color" content="#4285f4"> - https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta/name/theme-color

Thus with $:/tags/RawMarkupWikified its possible to let the browser know what theme color to use.
