### ISSUE TITLE
[IDEA] github pages and tiddler update

### ISSUE THREAD

**Issue by TimotheeMathieu** [Jermolene/TiddlyWiki5#6163]
**Is your feature request related to a problem? Please describe.**
I use tiddlywiki saved on github with https://tiddlywiki.com/#Saving%20to%20a%20Git%20service and it is a bit frustrating because every time I change something, the whole wiki is saved in github and this takes time. Hence the process is quite slow and it is likely that I will have merge issues. 

**Describe the solution you'd like**
It would be great if we could save the files not only as a static html file,  but as static html file for config + tiddlers all separated. In this way, we may only upload the new tiddlers and not the whole wiki at every saves.

**Describe alternatives you've considered**
I think I could use this instead : https://github.com/kookma/Tiddlywiki-Travis-CI but it would not be very fast I guess because the static html would still be re-generated at each update. However, I guess this would solve possible merging problems so I will maybe migrate to Travis-CI if it is too difficult to do it using  separate html files.

**Comment by pmario** [comment]
Go to the ControlPanel: Saving : General : Do not save changes automatically

**Be aware, that you have to save manually now, once you are finished with editing !**

![grafik](https://user-images.githubusercontent.com/374655/139708694-4e97b9d3-0e87-4250-8678-02346d1bacad.png)

**Comment by pmario** [comment]
If you forget to save ... You may use the Browser Storage plugin. 

So edited tiddlers will be saved in browser local storage. Everytime you save manually your local storage should be written to GitHub. ... 

BUT on my configuration I sometimes have to save twice until all tiddlers from the local storage are really written. ...

Will need to investigate. 

![grafik](https://user-images.githubusercontent.com/374655/139709519-9be8cb7c-fff9-4a76-8fd1-08c45c6d9873.png)

**Comment by TimotheeMathieu** [comment]
Thanks for your answers.
I agree that this is a partial answer but this would still take some time and be quite inefficient because every time the whole wiki is re-uploaded. And if someone else edit the wiki at the same time, the wiki would be overwritten and there would be merge issues so it does not really solve the problem.

One other idea I had was to use github workflow. I can easily use github workflow to build the wiki using nodejs and when I do that I have one file for one tidler and I can use github to merge but the only problem is that I can't use tiddlywiki "save" tool I would have to change in local, commit and push the new tiddlers and then the index.html would automatically build. It would be easier to have a system where the new tiddler is automatically commited and pushed in the repo and then the job would redo the index.html.

**Comment by pmario** [comment]
>I agree that this is a partial answer but this would still take some time and be quite inefficient because every time the whole wiki is re-uploaded. And if someone else edit the wiki at the same time, the wiki would be overwritten and there would be merge issues so it does not really solve the problem.

The GitHub saver is _not_ intended to be used as a multiuser environment.

**Comment by pmario** [comment]
>I agree that this is a partial answer but this would still take some time and be quite inefficient because every time the whole wiki is re-uploaded. And if someone else edit the wiki at the same time, the wiki would be overwritten and there would be merge issues so it does not really solve the problem.

That's a possibility, but completely out of the range of a simple "saver module". 

You will need to implement a "syncer" for this usecase. **That's a completely different thing**. 

There is a library: https://github.com/octokit/octokit.js with which you can access github in a way you described. ... BUT this would be a completely new project on its own.

**Comment by TimotheeMathieu** [comment]
Ok, I thought that because the syncer does a commit of the whole index.html it could also do commit of individual tiddlers (which would have solved my problem I guess), but I do not understand tiddlywiki and Nodejs well enough to implement this hence this issue.

**Comment by saqimtiaz** [comment]
I have considered the approach of saving individual tiddlers to Github and using GH Actions to build the wiki but ultimately deemed it not worth the trouble.

The issue is that Github actions and pages can lag behind commits by several minutes and sometimes pages simply do not update for some commits. So saving individual tiddlers via the API and loading the wiki via HTTP over Github pages is a recipe for race conditions and overwriting newer content with older.
