### ISSUE TITLE
[BUG] EditTextWidget size=1 is not size=1

### ISSUE THREAD

**Issue by twMat** [Jermolene/TiddlyWiki5#6165]
EditTextWidget doc reads:

|size |The size of the input field (in characters)|

...but in practice the width of another 4-5 characters is added. So any width less than that doesn't work, for example:

`<$edit-text tag=input size=1/>`

shows an input field that is at least 5 characters wide.

Any applied `class` also seems to be overrun by this.

The incorrect minimal width setting is a problem because it takes up too much real estate. I sometimes make "editable tables" where each cell is intended to only hold a single or very few characters but because of this issue the table becomes too wide.

**Comment by saqimtiaz** [comment]
The size attribute of $edittext sets the size attribute of the generated input element, how that is rendered is dependent on the browser, see https://www.w3schools.com/tags/att_input_size.asp

A documentation update to clarify this further would be welcome if you feel it is needed. Controlling the width more precisely would need to be done via applying a custom class and your own CSS that sets the width, perhaps in em.

**Comment by twMat** [comment]
>dependent on the browser

Oh, that was surprising to hear. Thanks. And, to my (second) surprise it does work with CSS... I did test it before I posted but must have done... whatever, thank you :-)

I'll edit the docs.

[closing]
