### ISSUE TITLE
There is an refresh problem with the "codeblock" widget

### ISSUE THREAD

**Issue by pmario** [Jermolene/TiddlyWiki5#6171]
There is an update problem with the "prefixed code tiddlers" 

To reproduce:

 - open [this view at tiddlywiki-com](https://tiddlywiki.com/#%24%3A%2Ftemp%2Fadvancedsearch:%24%3A%2Ftemp%2Fadvancedsearch%20%24%3A%2FAdvancedSearch) and type in any search tab. `$:/temp/advancedsearch  ` is updated.
 - open the same configuration in the PR wiki -> The "code area" isn't updated.

_Originally posted by @pmario in https://github.com/Jermolene/TiddlyWiki5/issues/6168#issuecomment-961534434_

**Comment by pmario** [comment]
> Saq at: https://github.com/Jermolene/TiddlyWiki5/pull/6168#issuecomment-961659280
>
>The $codeblock widget doesn't refresh itself, the refresh method just returns false. That should be viewed as a separate issue.

**Comment by Jermolene** [comment]
Thanks @saqimtiaz @pmario

**Comment by pmario** [comment]
Thanks! ... That was fast.
