### ISSUE TITLE
[IDEA] New Eye-striketrough icon

### ISSUE THREAD

**Issue by pmario** [Jermolene/TiddlyWiki5#6182]
@Jermolene ... I do need a new icon for one of my plugins as a visual indication for "invisible" or "not visible". 

If I create a PR, would you consider to merge it? .. For my usecase the "preview-closed" image doesn't work too well.

![grafik](https://user-images.githubusercontent.com/374655/140797180-168be1af-1061-4c5c-9d7e-9ffe41f22a1f.png)

**Comment by pmario** [comment]
OK. That's sensible, so I'll include it in the plugin. I would also be interested in an icon that can visualize "hidden" and "visible" state in a distinctive way. 

For my usecase, using the core images looks as follows. For me personally, that looks strange and the visual difference between disabled and enabled buttons isn't clear enough. .. See marker 1, which can be toggled.

![grafik](https://user-images.githubusercontent.com/374655/141125909-f0b9e680-e5a7-4526-a9db-aece68a54cc7.png)

Using the eye looks as follows. IMO the "is a toggle button" visibility is better, but I need to make the "strike through bar" a bit wider, so it's more dominant. 

![visible-non-visible-fields-01](https://user-images.githubusercontent.com/374655/141125954-8a88378e-73d1-4ac4-b9a2-c10f66310b7f.gif)

**Comment by Jermolene** [comment]
I have to agree that the core closed eye icon is not particularly effective. I'd have no objection to changing both icons.
