### ISSUE TITLE
[BUG] Drag and Drop a Tiddler with Space in Title to Tag-pill Causes Filter Error

### ISSUE THREAD

**Issue by kookma** [Jermolene/TiddlyWiki5#6190]
**Describe the bug**

**To Reproduce**
1. Go to ['...'](https://tiddlywiki.com/)
2. Create new tiddler
3. add few tags
4. from sidebar drag and drop a tiddler with space in title to tag-pill
5. add more tags from drop down menu
6. See the filter error

**Expected behavior**
Prevent drag and drop to tag pill or do not add `[[..]]``

**Screenshots**
![img_658_%pn](https://user-images.githubusercontent.com/830394/141331720-4039568e-7590-4fa4-baf9-62048a97f8e9.gif)

**TiddlyWiki Configuration (please complete the following information):**
 - Version [e.g. v5.2.0]
 - Windows 10
 - Chrome 90

**Comment by pmario** [comment]
Good catch. The funny thing is, that the "Filter error: .. " really gets written to the tiddler object

![grafik](https://user-images.githubusercontent.com/374655/141335861-c1713d33-85f6-4bf5-a0ca-16909a1b6c64.png)

**Comment by pmario** [comment]
@kookma I think this one can be closed. Did test it with FF and Edge on Windows and the error seems to be gone

**Comment by Jermolene** [comment]
Thank you @pmario
