### ISSUE TITLE
[BUG] Icon in Tag Pill has Wrong Color after Merging 6168

### ISSUE THREAD

**Issue by kookma** [Jermolene/TiddlyWiki5#6221]
**Describe the bug**
After https://github.com/Jermolene/TiddlyWiki5/pull/6168, it seems the color of icons in tag pill is wrong (dark background shall have light icon color and light background shall have dark icon color)

**To Reproduce**
1. Go to  https://tiddlywiki.com/prerelease/#Reference
2.Edit the  'Reference' tiddler
3. Change to color to something light e.g `#F45757
4. Save
5. Noe open a tiddler tagged with Reference like https://tiddlywiki.com/prerelease/#Concepts
6. Note to tag and icon!
7. Icon cannot be seen

Repeat this in https://tiddlywiki.com/ and also add icon to Reference and see the difference

**Expected behavior**
Show correct color of icons in tag pill

**Screenshots**

**Tiddlywiki 5.2.1p**
Issue
![image](https://user-images.githubusercontent.com/830394/141933475-69411ecd-85dc-43c7-aa2a-45f84686faa0.png)

**Tiddlywiki 5.2.0**  
Works fine
![image](https://user-images.githubusercontent.com/830394/141933286-46346aa8-7459-46ce-8ee6-3950d62c02bc.png)

**Comment by kookma** [comment]
Further info:
This issue can be seen when tiddler is in edit mode!

**Comment by kookma** [comment]
Hi @Jermolene - Is there a chance to have a look and give some hints on this issue?

**Comment by Jermolene** [comment]
Thanks @kookma I've just pushed a fix, it's building now and will be available at https://tiddlywiki.com/prerelease shortly - see https://github.com/Jermolene/TiddlyWiki5/actions/runs/1480650700

**Comment by kookma** [comment]
Hi @Jermolene !

* Tested on https://tiddlywiki.com/prerelease/
* Tried with dark and light colors for tag tiddlers
* Tiddlywiki shows color correctly in tag pill and also when the `tag` macro is called like `<<tag mytag>>`

The issue has gone and TW works great!

Thank you

**Comment by Jermolene** [comment]
Great, thanks @kookma
