### ISSUE TITLE
[BUG] Hovering on checkbox should show cursor: pointer;

### ISSUE THREAD

**Issue by twMat** [Jermolene/TiddlyWiki5#6228]
No biggie:

Hovering over a [checkboxwidget](https://tiddlywiki.com/prerelease/#CheckboxWidget) or its label shows no feedback on the mouse cursor. This is annoying because it appears as if you can't click on the label (which you can) but that you instead *must* click only in the small checkbox.

**Proposal** Use `cursor: pointer;` on hover.

**Comment by pmario** [comment]
The example: `<$checkbox tag="done"> Is it done?</$checkbox>` doesn't have a class defined. .. 

So `<$checkbox tag="done" class="tc-cursor-pointer"> Is it done?</$checkbox>` may do the trick .. 

BUT ... We don't have a class definition `tc-cursor-pointer` at the moment. ...

So the question is if we define [a lot of](https://developer.mozilla.org/en-US/docs/Web/CSS/cursor) cursor `tc-..` elements or we define a default class eg: `tc-checkbox-label` hardcoded in the checkbox-widget code and define `.tc-checkbox-label: {cursor: pointer;}` once

@Jermolene @saqimtiaz what do you think

**Comment by twMat** [comment]
@pmario , you didn't ask for my opinion but from an end users PoV, I say it should be a hard coded default because it is the expected behaviour and we shouldn´t force users to have to dig up esoteric class names and stuff. Besides, the Ctrlpanel and sidebar Tools have many checkboxes so if we want this pointer I guess it'd save a few bytes if hard coded...

(There, I have said my opinion so it is now ensured that the others will say the opposite. Well, at least I tried... ;-)

**Comment by Jermolene** [comment]
Thanks @twMat – the present behaviour is the default way that browsers display checkboxes. Changing to a custom cursor on hover would result in behaviour inconsistent across other websites that the user might visit. It's also worth noting that it only solves the issue for desktop users with a mouse.

**Comment by twMat** [comment]
OK, I'm closing this even if a pointer cursor on checkbox labels *obviously* would benefit the user, regardless of default browser behaviour. I'm happy we don't reason in the same way for, say, the native TW font. It is not like TW is unopinionated - and why should it be? It is totally different from any other webpage they've seen.

But again, no biggie. Thanks for input everyone.

**Comment by Jermolene** [comment]
Hi @twMat the way I look at it is that the checkbox is a standard UI component that is common across websites. The consistency is more important than being the best. There's not much value if I design a better checkbox but it's unfamiliar to every user who encounters it.
