### ISSUE TITLE
[BUG] Macro rendering problem with $tw.wiki.renderText();

### ISSUE THREAD

**Issue by Vaneixus** [Jermolene/TiddlyWiki5#6230]
Problem:
It would appear that macros rendered using $tw.wiki.renderText() in the browser console would break if they're defined under WikiText.

Specifications:
- Windows 10 1094
- Edge(Chromium) - version 95
- Tiddlywiki 5.2.0

Examples:
`$tw.wiki.renderText("text/vnd.tiddlywiki","text/vnd.tiddlywiki",'<<makedatauri text:"Text to be converted" type:"text/vnd.tiddlywiki">>');` returns `'data:text/vnd.tiddlywiki,Text%20to%20be%20converted'` and `$tw.wiki.renderText("text/vnd.tiddlywiki","text/vnd.tiddlywiki",'<<version>>');` returns `'5.2.0'`

but `$tw.wiki.renderText("text/vnd.tiddlywiki","text/vnd.tiddlywiki",'<<color primary>>');` and `$tw.wiki.renderText("text/vnd.tiddlywiki","text/vnd.tiddlywiki",'<<tree>>');` both return `''`(an empty string). Also, running `console.log($tw.wiki.renderText("text/vnd.tiddlywiki","text/vnd.tiddlywiki",'<<color primary>>'));` in a custom parser only gave an empty line in the console log. Expected result for the third example would have been a color from the current palette while the fourth one would have been a tree resembling the one in the explorer tab. 

Explanation:
The only difference between the first two, and the other three would be that the first two are written in Javascript while the others are implemented in WikiText. To the best of my knowledge, there's no available documentation as to why that is. A possible but a time consuming solution would be to implement the WikiText core macros in Javascript instead, that is if the cause of the problem is not found.

Edit: It also works with somthing like `console.log($tw.wiki.renderText("text/vnd.tiddlywiki","text/vnd.tiddlywiki",'{{tiddler-title-here}}'));` which returns `'tiddler-text-here'`

**Comment by Jermolene** [comment]
Hi @Vaneixus the first parameter to `$tw.wiki.renderText()` is the content type for the output; the supported settings are `text/html` (the default) and `text/plain`, which returns the text content of the output HTML.

The other issue is that the `<<color>>` and `<<tree>>` macros are global macros that despite the name have to be explicitly imported. For example:

```js
$tw.wiki.renderText("text/vnd.tiddlywiki","text/vnd.tiddlywiki",'\\import [[$:/core/ui/PageMacros]] [all[shadows+tiddlers]tag[$:/tags/Macro]!has[draft.of]]\n<<color primary>>');
```

**Comment by Jermolene** [comment]
> ```js
> $tw.wiki.renderText("text/vnd.tiddlywiki","text/vnd.tiddlywiki",'\\import [[$:/core/ui/PageMacros]] [all[shadows+tiddlers]tag[$:/tags/Macro]!has[draft.of]]\n<<color primary>>');
> ```

Apologies, I forgot to correct the output type; that should be

```js
$tw.wiki.renderText("text/plain","text/vnd.tiddlywiki",'\\import [[$:/core/ui/PageMacros]] [all[shadows+tiddlers]tag[$:/tags/Macro]!has[draft.of]]\n<<color primary>>');
```

**Comment by Vaneixus** [comment]
Oh my, I am truly sorry for not answering back, I thought I already did. but, yes that did work, and helped me understand the function further. I guess it wasn't a bug after all, but a mistake on my part. Thanks! I will be closing this "issue" now since it seems that it wasn't in the first place.
