### ISSUE TITLE
Proposal: Add 4 new filters

### ISSUE THREAD

**Issue by Skeeve** [Jermolene/TiddlyWiki5#624]
Based on this thread https://groups.google.com/forum/#!topic/tiddlywiki/jGnRWgMNeNM I suggest to add 4 new filters:
1. later and laterday (laterday is the "afterday" shown in the thread)
2. earlier and earlierday

With "later" it would be possible to solve the OP's problem of giving an enduser of a customized TiddlyWiki a clean "recent" history.

"later" would look like this:

```
/*\
    title: $:/core/modules/filters/later.js
    type: application/javascript
    module-type: filteroperator

    Filter operator that selects tiddlers with a modified date field after the the provided timestamp value.

\*/
(function(){

/*jslint node: true, browser: true */
/*global $tw: false */
"use strict";

/*
Export our filter function
*/
exports.later = function(source,operator,options) {
    var results = [],
        fieldName = operator.suffix || "modified",
        targetDate = (new Date($tw.utils.parseDate(operator.operand))).setHours(0,0,0,0);
    // Function to convert a date/time to a date integer
    var isLater = function(dateField) {
            return (new Date(dateField)) > targetDate;
            // laterday: return (new Date(dateField)).setHours(0,0,0,0) > targetDate;
            // earlier: return (new Date(dateField)) < targetDate;
            // earlierday: return (new Date(dateField)).setHours(0,0,0,0) < targetDate;

        };
    source(function(tiddler,title) {
        if(tiddler && tiddler.fields[fieldName]) {
            if(isLater(tiddler.fields[fieldName])) {
                results.push(title);
            }
        }
    });
    return results;
};

})(); 
```

**Comment by pmario** [comment]
imo solved with the `days` operator and `limit` http://tiddlywiki.com/#Filter%20Operators:%5B%5BFilter%20Operators%5D%5D%20%5B%5Bdays%20Operator%5D%5D

so imo can be closed @Skeeve

**Comment by Skeeve** [comment]
It's too long ago and I'm too disconnected from TW5 at the moment, so I 
cannot decide.

Feel free to test whether it solves the initial request and close if you 
think it's fitting.

**Comment by pmario** [comment]
Only you (as the creator of the issue) and Jeremy (repo owner) can close issues. .. I'm pretty sure, that the `days` operator can solve the issue raised in the google group.

**Comment by Skeeve** [comment]
Okay. So Jeremy is free to close it.

**Comment by tobibeer** [comment]
@Jermolene: this not being a pull request, if you feel like adopting the filter then that's gr8, otherwise we can close this issue. It will stay reference anyway. Alternatively, I could release them as a plugin, if that's fine with you @Skeeve.

**Comment by Skeeve** [comment]
Let me repeat what I wrote:

> It's too long ago and I'm too disconnected from TW5 at the moment, so I
cannot decide.
> 
> Feel free to test whether it solves the initial request and close if you
think it's fitting.
