### ISSUE TITLE
issue with sidebar on safari also on FF16

### ISSUE THREAD

**Issue by Skeeve** [Jermolene/TiddlyWiki5#625]
Hi @Jermolene 

You might remember that I yet can't use a newer FF than 16 on my old OS X.

You showed in Hangout #47 an issue with Safari and the sidebar where the "All" "Recent" "Tags" etc. selectors under the "More" tab are shown on top and not to the left. This issue also exists on FF16.

**Comment by pmario** [comment]
it has a label "wontfix", so imo can be closed. Also FF has version 50 now
