### ISSUE TITLE
[BUG] importing by drag-and-drop of tiddler title is broken in latest update to Chrome and Edge

### ISSUE THREAD

**Issue by ericshulman** [Jermolene/TiddlyWiki5#6254]
As reported here: https://talk.tiddlywiki.org/t/drag-and-drop-does-not-work-in-chrome-96-0/1605

1. open https://tiddlywiki.com/ in your browser
2. create a tiddler named "TestTiddler" with text content "this is a test tiddler"
3. open https://tiddlywiki.com/empty in another browser tab
3. drag TestTiddler from https://tiddlywiki.com/ and drop into the empty.html
5. The $:/Import shows "download.url", not "TestTiddler"
6. On import "download.url" tiddler is created with a text field containing:
`[InternetShortcut] URL=data:text/vnd.tiddler,%7B%22created%22%3A%2220211120075141902%22%2C%22text%22%3A%22this%20is%20a%20test%20tiddler%22%2C%22tags%22%3A%22%22%2C%22title%22%3A%22TestTiddler%22%2C%22modified%22%3A%2220211120075157966%22%7D`

**TiddlyWiki Configuration (please complete the following information):**
 - v5.2.0
 
**Desktop (please complete the following information):**
 - Windows10
 - Chrome 96.0.4664.45 (Official Build) (64-bit) or Edge 96.0.1054.29 (Official build) (64-bit)

**Comment by Jermolene** [comment]
Thanks @ericshulman. I haven't been able to replicate this on macOS with Chrome 96, so I'd appreciate any help here.

**Comment by saqimtiaz** [comment]
A very quick look shows that the drop event received in Chrome 96 now has an entry in `dataTransfer.files` which has previously not been the case, and in our handling of the drop events this takes precedence over dataTransfer.items.

![image](https://user-images.githubusercontent.com/68092/142722002-8fb18dfe-8ee9-4ec5-80df-cad23ff41beb.png)

**Comment by ericshulman** [comment]
Although there may be a better way to fix this problem, the following code change seems to work...

In `$:/core/modules/wiki.js`, I added code to `exports.readFiles` to specifically ignore "download.url":
(additions and changes marked with `// ELS`)
```
exports.readFiles = function(files,options) {
	var callback;
	if(typeof options === "function") {
		callback = options;
		options = {};
	} else {
		callback = options.callback;
	}
	var result = [],
		outstanding = files.length,
		ignored = 0, // ELS
		readFileCallback = function(tiddlerFieldsArray) {
			result.push.apply(result,tiddlerFieldsArray);
			if(--outstanding - ignored === 0) { // ELS
				callback(result);
			}
		};
	for(var f=0; f<files.length; f++) {
		if(files[f].name=="download.url") { // ELS
			ignored++; // ELS
		} else { // ELS
			this.readFile(files[f],$tw.utils.extend({},options,{callback: readFileCallback}));
		} // ELS
	}
	return files.length - ignored; // ELS
};
```

**Comment by saqimtiaz** [comment]
My thinking is along the lines of:

If we have a member in `dataTransfer.items` with `type` that is `text/vnd.tiddler`, then do not call `readFiles()`. That is `text/vnd.tiddler` always wins over `Files`, which I think makes sense.

https://github.com/Jermolene/TiddlyWiki5/blob/dde1e4bc0f75e037b71578dc533360111afa2820/core/modules/widgets/dropzone.js#L201-L208

**Comment by Jermolene** [comment]
Thanks @ericshulman @saqimtiaz I think @saqimtiaz's proposal makes sense, but it does look like an annoyingly tricky bit of refactoring. Might you have time to make a PR?

I'm thinking that this fix may well justify a v5.2.1 release as soon as possible.

**Comment by saqimtiaz** [comment]
I can prepare a PR on Monday, when I'll also have time to do some cross browser testing of the change.

**Comment by kookma** [comment]
> A quick search has not turned up any relevant Chrome documentation or change history.

May be these docs help:

- https://www.ghacks.net/2020/06/06/drag-drop-functionality-changes-soon-in-chromium-based-browsers/
- https://9to5google.com/2020/06/04/google-chrome-drop-and-drop-taking-over-tab/

**Comment by kookma** [comment]
@saqimtiaz please also see https://www.chromestatus.com/features#milestone%3D96

**Comment by saqimtiaz** [comment]
This issue is actually manifesting as a problem in two different areas: drag and drop to import, and drag and drop into the editor.

I would appreciate some testing on this file in different browsers, in particular Firefox on Windows, and Chrome and Safari on OSX to ensure there are no knock-on side effects to the fix: https://saqimtiaz.github.io/sq-tw/temp/empty-chrome-dnd.html

Things to test:
* drag and drop tiddlers from another wiki to import
* drag and drop a tiddler link into the editor
* drag and drop text into the editor
* drag and drop images into the editor

**Comment by kookma** [comment]
> I would appreciate some testing on this file in different browsers, in particular Firefox on Windows, and Chrome and Safari on OSX to ensure there are no knock-on side effects to the fix: https://saqimtiaz.github.io/sq-tw/temp/empty-chrome-dnd.html

* Test on Windows 10 / Chrome 96
* Test on Windows 10 / Edge 96

- [x] drag and drop tiddlers from another wiki to import
- [x]  drag and drop a tiddler link into the editor (both simple and title with space)
- [x] drag and drop text into the editor (within wiki, from outside wiki)
- [x] drag and drop images into the editor

All works fine now!

**Comment by pmario** [comment]
I did test it with FF 94, Ubuntu 20.04 All those test worked
>
> -    drag and drop tiddlers from another wiki to import
> -    drag and drop a tiddler link into the editor
> -    drag and drop text into the editor
> -    drag and drop images into the editor
 

I could test it with Win10 FF latest on Monday when I'm back at home. So someone else may jump in here

**Comment by curio77** [comment]
I have the same issue on Chrome 96 (Linux). For me, DND also no longer works for reordering items in the favorites list.

**Comment by saqimtiaz** [comment]
> I have the same issue on Chrome 96 (Linux). For me, DND also no longer works for reordering items in the favorites list.

@curio77 can you please be more specific as to recreate the problem you are experiencing, TiddlyWiki by default has no concept of a favourites list.

**Comment by curio77** [comment]
Oh, sorry, turns out this is a plugin (`ajh/favorites`) I must have added so long ago I completely forgot about it not being core functionality. Will check with the plugin's repo, thanks for pointing this out!

**Comment by kookma** [comment]
@curio77 
For me the Favorites from kookma library (https://kookma.github.io/TW-Favorites/) works fine! I use the Core drag and drop feature! So reordering items in favorites list or between folders work fine!

**Comment by ericshulman** [comment]
someone should check this fix with the mobile drag-n-drop shim plugin

**Comment by saqimtiaz** [comment]
> Edit: From what I understand of the snippets making up the plugin, it utilizes `<$droppable>` and doesn't seem to implement anything JS by itself, so I _suspect_ the underlying issue is the same as for the problems discussed here and might get fixed along with them.

@curio77 note that at present there are no reports and no evidence to suggest that the $droppable widget is impacted by this issue. If you can demonstrate that there is, please report back with steps to recreate the issue.

**Comment by curio77** [comment]
> > Edit: From what I understand of the snippets making up the plugin, it utilizes `<$droppable>` and doesn't seem to implement anything JS by itself, so I _suspect_ the underlying issue is the same as for the problems discussed here and might get fixed along with them.
> 
> @curio77 note that at present there are no reports and no evidence to suggest that the $droppable widget is impacted by this issue. If you can demonstrate that there is, please report back with steps to recreate the issue.

Trying to do this just now based on an empty wiki with the plugin added, DND in the list *did* work as per usual, and what's even more interesting is that it now also works again in my „production“ wikis. So this seems to be some unrelated intermittent issue.  I've had intermittent issues with DND of Chrome tabs on my Linux KDE desktop in the past, maybe this is a desktop environment vs. Chrome rather than a TiddlyWiki vs Chrome issue.

Sorry about the confusion in this issue that mine now appears to be unrelated to. 😔

**Comment by kookma** [comment]
> * drag and drop a tiddler link into the editor (both simple and title with space)

@saqimtiaz 
In Tw5.2.1p (https://tiddlywiki.com/prerelease/) this test does not work anymore!
Would you please have a look!

**Comment by saqimtiaz** [comment]
@kookma good catch! The problem is specific to codemirror. I'll investigate and patch it later today.

**Comment by saqimtiaz** [comment]
@kookma see #6273

**Comment by pmario** [comment]
I did test with:
- FF 94.0.2, Windows 10
- Version 96.0.1054.34 (Official build) (64-bit), Windows 10

Everything works as expected, except with CM .. as we know from #6273

> - drag and drop tiddlers from another wiki to import
> - drag and drop a tiddler link into the editor
> - drag and drop text into the editor
> - drag and drop images into the editor

**Comment by positivesigner** [comment]
I tested https://saqimtiaz.github.io/sq-tw/temp/empty-chrome-dnd.html on Windows 10 under Google Chrome Version 96.0.4664.45 (Official Build) (64-bit). I was able to drag tiddlers into DND and the filename shows correctly and the contents are imported correctly.
