### ISSUE TITLE
Planning v5.2.1 Release

### ISSUE THREAD

**Issue by Jermolene** [Jermolene/TiddlyWiki5#6259]
We've encountered a bug with drag-and-drop that was introduced by the latest Chrome on Windows. It's a serious issue that potentially affects a large number of users so we intend to make the v5.2.1 release as soon as possible.

We'll collect the tickets that we intend to fix and other tasks here:

* [x] #6273
* [x] #6164
* [x] Documentation for #6168 
* [x] Update release note
* [x] New release banner image competition

Please reply here with any suggestions for tickets/bugs that should be considered. The primary criteria will be urgent changes that are low risk and simple to test/verify.

Another way to say it is that we are now trying to get v5.2.1 released as quickly as possible. Therefore we're trying to figure out the minimum amount of extra work to get the release done. So there's a very high bar at this point.

**Comment by saqimtiaz** [comment]
#6164 is a bug fix that has tests and should be considered.

**Comment by twMat** [comment]
>The primary criteria will be changes that are low risk and simple to test/verify.

Maybe #6152 qualifies for that?

**Comment by saqimtiaz** [comment]
> > The primary criteria will be changes that are low risk and simple to test/verify.
> 
> Maybe #6152 qualifies for that?

I think another unspoken requirement is that there be someone willing and available to make a PR in the next few days. Personally I have a lot on my plate and would not be able to make time to work on anything additional unless it was a critical bug.

**Comment by Jermolene** [comment]
Thanks @saqimtiaz @twMat I've updated the OP to try to clarify things.

**Comment by pmario** [comment]
@Jermolene ... You should start the "banner competition" otherwise it may delay the release ...

**Comment by simonbaird** [comment]
> @Jermolene ... You should start the "banner competition" otherwise it may delay the release ...

Perhaps we don't need a banner for a bug fix release like this.

**Comment by Jermolene** [comment]
> Perhaps we don't need a banner for a bug fix release like this.

Indeed, it's tight. There's a temporary holding banner there now for v5.2.1 so we certainly have a fallback if things don't work out.

**Comment by Jermolene** [comment]
v5.2.1 is now released
