### ISSUE TITLE
PRs for consideration for post-v5.2.1 release

### ISSUE THREAD

**Issue by Jermolene** [Jermolene/TiddlyWiki5#6266]
We are now aiming for a rapid release of v5.2.1 (as discussed in #6259). This ticket is to collect PRs/tickets that should be considered for the following release.

* #5742 
* #5899 
* #6293
* #6327
* #5419 
* #6388
* #6377
* #6421
* #6401
* #6383 
* #6427

A special section for @flibbles's trim saga (currently being discussed in #6270):

* #6265
* #6257
* #6269
* #6270
* #6272
* #6275
* #6276

Please let me know other that should be considered and I'll include them here.

UPDATE 21st February 2022: Most of these PRs have now been merged. I've moved the trim saga tickets to a new tracking ticket #6474.

**Comment by Jermolene** [comment]
Thanks @flibbles

**Comment by flibbles** [comment]
I'd also like to suggest this one, which I found after my own project started running incredibly slowly during certain operations.

- https://github.com/Jermolene/TiddlyWiki5/pull/6327

**Comment by Jermolene** [comment]
Thanks @flibbles
