### ISSUE TITLE
Issue with Filter:eachday documentation

### ISSUE THREAD

**Issue by Skeeve** [Jermolene/TiddlyWiki5#627]
Check tiddlywiki.com/#FilterOperator%3A eachday

It says: "For example, the following wiki text creates a list of the number of tiddlers that were modified on each day:" What follows is a list of tiddlers, not the code for the list.

**Comment by pmario** [comment]
outdated. text is different now. so seems to be fixed. @Skeeve pls close

**Comment by Skeeve** [comment]
I'll trust @pmario here
