### ISSUE TITLE
[BUG] Urgent: Dragging and dropping tiddler titles or links into CodeMirror does not work as expected.

### ISSUE THREAD

**Issue by saqimtiaz** [Jermolene/TiddlyWiki5#6273]
As a result of the same underlying changes in Chrome 96 that caused #6254, dragging tiddler links or external links into the CodeMirror editor does not insert the tiddler title or link URL as before. Instead we get text of the form:
```
[InternetShortcut]
URL=https://github.com/saqimtiaz/sq-tw
```

The way the CodeMirror plugin has always handled drop events is to let CodeMirror library handle it, which by default has always worked for us. Now however it is the underlying CodeMirror library handling itself that is not equipped to deal with this change.

Thoughts on how to proceed @Jermolene @pmario ?

Potential options:
- One option is for the CodeMirror plugin to take over the drop handling entirely, i.e. intercept the drop event, parse the text to insert and insert it at the correct position. However this may be significant work with a lot of edge cases to consider.
- We could also try catching the drop event and sending another drop event with a different dataTransfer payload, but that too will require some investigation as to how feasible it is.
- A cursory look does not show any options in the CodeMirror API to customize the drop handling but this might be worth looking into further.

This issue would need to be resolved before we ship TW v5.2.1

**Comment by Jermolene** [comment]
Thanks @saqimtiaz, not great news! Is there any reason to believe that this problem is affecting other apps that use CodeMirror 5?

**Comment by saqimtiaz** [comment]
@Jermolene the same behaviour is seen in the inline demo at the CodeMirror official site when dragging in any link:
https://codemirror.net/

So it feels like a fair assumption that any and all apps using CodeMirror would be impacted.

**Comment by Jermolene** [comment]
That's encouraging thank you @saqimtiaz – if you've time, perhaps it's worth opening a ticket at CodeMirror's GitHub? Otherwise I should be able to do so tomorrow.

**Comment by saqimtiaz** [comment]
@Jermolene I don't believe I will have the opportunity before tomorrow evening at the earliest. If you are able to do open a ticket in the morning that would be helpful. 

CodeMirror may decide that they are OK with observing browser defaults. I am also not sure how much support or updates there are for CodeMirror 5 presently.

**Comment by saqimtiaz** [comment]
For reference this is the code in CM that is seeing the File entry in the dataTransfer object and reading it as text, instead of the text/plain item:

https://github.com/codemirror/CodeMirror/blob/bd1b7d2976d768ae4e3b8cf209ec59ad73c0305a/src/edit/drop_events.js#L28-L44

**Comment by kookma** [comment]
> CodeMirror may decide that they are OK with observing browser defaults. I am also not sure how much support or updates there are for CodeMirror 5 presently.

I think @pmario already started some work with CodeMirror 6! @saqimtiaz don't you think it is time to move to CodeMirror 6?
I believe do not put much efforts for CodeMirror 5.

**Comment by Jermolene** [comment]
Hi @saqimtiaz 

> I don't believe I will have the opportunity before tomorrow evening at the earliest. If you are able to do open a ticket in the morning that would be helpful.

Tsk as it turns out I don't have a working Windows VM at the moment, nor quite enough free disk space to install one, but I'n fixing that in the background.

I'm still surprised that the Chrome 96 drag and drop changes haven't caused more of a fuss for other projects. If the impact were extensive we might hope that Chrome would fix things.

**Comment by pmario** [comment]
>I think @pmario already started some work with CodeMirror 6! and perhaps @Gk0Wk!
@saqimtiaz don't you think it is time to move to CodeMirror 6? I believe do not put much efforts for CodeMirror 5.

I didn't do any work with CM6 yet and as far as I can see @Gk0Wk uses CM5 ... 

CM6 follows a completely new concept. I'm interested in the new concept but I don't have a priority or incentive to get it going. ...  

I did a deep-dive into CM5 some years ago to get it going with TiddlySpace and TiddlyWikiClassic, since TiddlyWiki and the codemirror editor where the only tools I did use to create TWc plugins. So code highlighting in edit mode was essential for me.

My preferred editor at that time was: brackets.io, which uses CM5 as its base editor component. ... I don't use the brackets editor anymore ... I'm using VSCode atm. ... 

So for me CM5 at the moment is in "maintenance mode" only.

**Comment by pmario** [comment]
I did some tests with Edge on Windows and can confirm, that there is the same problem. .. I have to have a closer look at the code linked by Saq. 

But I have to say, that I don't know the drag&drop code in the TW core very well, so my progress probably won't be the fastest.

**Comment by saqimtiaz** [comment]
If we want to patch this bug ourselves, I think we need to look into duplicating the [drop event handling in CM](https://github.com/codemirror/CodeMirror/blob/bd1b7d2976d768ae4e3b8cf209ec59ad73c0305a/src/edit/drop_events.js#L19-L88) in the engine.js for the CM plugin. The tricky bit is going to be figuring out access to private CM methods that are used.

**Comment by pmario** [comment]
I did just reproduce the problem at codemirror.net main page. If I drop a tw-link from FF to the editor I do get the expected result. 

If I drop a link with Edget I do get "problems" ... So I thin it's valid to raise an issue there. ... A bit more testing is needed, because I want to reproduce the problem with eg: wikipedia links instead of TW links which they don't care about.

**Comment by saqimtiaz** [comment]
@pmario as I mentioned earlier, you can drag a link from the codemirror.net page itself into their demo to re-create the problem.

**Comment by pmario** [comment]
I did create a PR at CM https://github.com/codemirror/CodeMirror/issues/6831

**Comment by saqimtiaz** [comment]
@pmario thank you. I am hoping to have some time tomorrow to investigate if we can implement a reliable workaround that takes the place of the default drop event handler in CM.

**Comment by saqimtiaz** [comment]
I managed to write a replacement for most of the CM drop handling but have hit a stumbling block towards the end. In order to correctly detect where the text should be inserted, I need to use the methods in this file https://github.com/codemirror/CodeMirror/blob/bd1b7d2976d768ae4e3b8cf209ec59ad73c0305a/src/model/selection_updates.js

I am not sure however if that is possible from the engine.js that is a part of the CodeMirror plugin. Any ideas?

**Comment by saqimtiaz** [comment]
I have a patch that I would appreciate some testing for: https://saqimtiaz.github.io/sq-tw/temp/cm-drop-patch.html

While the new handling should only apply when Chrome is doing its new thing with drop events, it is best to be safe and do some cross browser and OS testing.

Things to test in CodeMirror - best to do this in a tiddler with some existing text:
- dragging and dropping tiddler links
- dragging and dropping external links
- dragging and dropping text
- whether the links or text are inserted at the correct place in the text
- dragging and dropping an image and importing it.

**Comment by pmario** [comment]
I did test with FF and Edge latest Windows 10 ... Almost all tests are OK, except

 - importing an image throws: 401 in FF with an Alert dialogue
 - importing an image throws: 405 in Edge silent

Edge log says: `Failed to load resource: the server responded with a status of 405 ()`
FF log: `XHR GET  https://api.github.com/repos/saqimtiaz/sq-tw/contents/temp/?ref=master ... [HTTP/2 401 Unauthorized 142ms]`

The problem is, both of them don't stop if I say: Stop at exceptions in the debugger. So I don't see where it comes from.

--------

If I import an image in FF the normal way with the $:/Import dialogue I still get the 401 ... Edge doesn't do anything in the dev-console.

**Comment by pmario** [comment]
I found it: ... I did remove the Username from the GitHub saving settings in the ControlPanel. So the GitHub saver doesn't try to save ... 

Everything seems to work now. ... Except we may respond with a better message if the GitHub saver can't save.

**Comment by saqimtiaz** [comment]
Thank you @pmario, I have disabled autosave on that wiki so hopefully others can avoid the same errors when testing.

**Comment by kookma** [comment]
Tested with

**Chrome 96 / Edge 96
Windows 10**


- [x] dragging and dropping tiddler links  
- [ ] dragging and dropping external links
- [x] dragging and dropping text
- [x] whether the links or text are inserted at the correct place in the text
- [x] dragging and dropping an image and importing it.




## A new behavior

* dragging and dropping external links into CodeMirror does work 
* dragging and dropping external links into Tiddlywiki creates a shortcuts as below **I love this**

Example
 drag and drop [Sample Link](https://github.com/Jermolene/TiddlyWiki5/pull/6278) into https://saqimtiaz.github.io/sq-tw/temp/cm-drop-patch.html

creates:

* a new tiddler with
  * title `Sample Link.url`
  * type: `text/plain`
  * text 
  

```
[InternetShortcut]
URL=https://github.com/Jermolene/TiddlyWiki5/pull/6278
```

**Comment by pmario** [comment]
>dragging and dropping external links into Tiddlywiki creates a shortcuts as below I love this

That's different to the old behavour and creates a mess with FF. The content of the tiddler is garbage like: 

```
[InternetShortcut]
URL=https://github.com/Jermolene/TiddlyWiki5/pull/6278
IDList=
HotKey=0
IconFile=...\Users\......\shortcutCache\....==.ico
IconIndex=0
```

as I posted in the issue at the codemirror repo.

**Comment by saqimtiaz** [comment]
@kookma @pmario If I understand correctly, this also happens in 5.2.0 and 5.2.1 pre-release, and is about dragging and dropping to import and not into codemirror? If so, please create a separate issue for it to help us track these problems better.

**Comment by kookma** [comment]
@saqimtiaz 
I tested this new behavior with Tiddlywiki 5.1.18 - 5.2.0 (all version). I tested in Chrome/Edge 96 on Win10.
In all cases I get a nice tiddler!

Example
I drag and drop the below link from https://www.w3schools.com/ page

```
<a target="_top" href="howto_js_collapse_sidepanel.asp">Collapsed Sidepanel</a>
```

I got a tiddler with `Collapsed Sidepanel.url` where its type is `text/plain` and the body contains

```
[InternetShortcut]
URL=https://www.w3schools.com/howto/howto_js_collapse_sidepanel.asp
```

**Comment by kookma** [comment]
@saqimtiaz 
If I use FF 94.0 and your wiki https://saqimtiaz.github.io/sq-tw/temp/cm-drop-patch.html
drag and drop a link like `https://github.com/Jermolene/TiddlyWiki5/issues/6273` from GitHub to https://saqimtiaz.github.io/sq-tw/temp/cm-drop-patch.html creates a new Tiddler with `Untitled` title!
The text body is `https://github.com/Jermolene/TiddlyWiki5/issues/6273` and type of tiddler is not set!

**Comment by saqimtiaz** [comment]
@kookma this issue is ONLY for the CodeMirror related issues. Please create a new issue if there are other problems, or a discussion if there are things that are not issues but need discussion. Otherwise these posts are just confusing and potentially does more harm than good.
