### ISSUE TITLE
List Tiddler with Tag Widget does not work as in Documentation

### ISSUE THREAD

**Issue by pat-githubber** [Jermolene/TiddlyWiki5#6288]
Hello, 

I downloaded a fresh TiddlyWiki and created test tiddlers to run the filter copied from the [documentation](https://tiddlywiki.com/#ListWidget):

```
<$list filter="[tag[<<MyTag>>]sort[title]]">
<<currentTiddler>>
{{||$:/core/ui/ViewTemplate/tags}}
</$list>
```

However, the output showing "test2" and "test3" does not include a link to the respective tiddler even though they are linked in the documentation (bottom image). What am I doing wrong? 

**My TiddlyWiki:**
![image](https://user-images.githubusercontent.com/87087327/143770167-e6ea33a9-7b25-435c-8ebb-10482d382bbc.png)

**Documentation: [ListWidget](https://tiddlywiki.com/#ListWidget):**
![image](https://user-images.githubusercontent.com/87087327/143770141-f66f8245-53e4-4c30-9575-4eebc948d990.png)

Best,
Patrick

**Comment by pmario** [comment]
Try the following code: (I didn't test it) See docs about [Special Parameters](https://tiddlywiki.com/#Introduction%20to%20filter%20notation)  `<MyTag>` needs to be a variable if you want to use it that way. .. In your example _no_ variable is defined so I defined one. ... But I'm not sure if that is what you want. 

```
<$vars MyTag="xxx">
<$list filter="[tag[<MyTag>]sort[title]]">
<<currentTiddler>>
{{||$:/core/ui/ViewTemplate/tags}}
</$list>
</$vars>
```

If you would describe what you want in plain text it would be easier for us to know what you want. With "non functional" code we need to guess. ...

**Comment by pat-githubber** [comment]
I am sorry, I am a real nooby.

I would like to apply the list widget as it is stated in the [documentation](https://tiddlywiki.com/#ListWidget) under the heading _Examples_ under _custom item output_. This is the code from there:

```
<$list filter="[tag[ListWidget]sort[title]]">
<<currentTiddler>>
{{||$:/core/ui/ViewTemplate/tags}}
</$list>
```

When I apply this code, replacing "ListWidget" with my tag-name, I receive the exact same output as in the documentation except that the title of the filtered tiddlers are not linked.

I would like that the listed tiddler is linked as "GroupedLists" is linked (from the documentation example):
![image](https://user-images.githubusercontent.com/87087327/143771720-3f5c3114-8eb6-4ded-ab70-78691fbb2369.png)

I am sorry for the misunderstanding.

**Comment by pmario** [comment]
ahh OK. ... Sorry I didn't read the text in the images .. my bad

TW applies "autolinking" for CamelCase tiddler names. .. If you want a link you can use the [link-widget](https://tiddlywiki.com/#LinkWidget)

```
<$list filter="[tag[ListWidget]sort[title]]">
<$link to=<<currentTiddler>> />
{{||$:/core/ui/ViewTemplate/tags}}
</$list>
```

Or a shorter version, since the link-widget links to `<<currentTiddler>>` by default. 

```
<$list filter="[tag[ListWidget]sort[title]]">
<$link />
{{||$:/core/ui/ViewTemplate/tags}}
</$list>
```

**Comment by pat-githubber** [comment]
Wow, so easy - I am learning! That's it, thank you!
Have a great Sunday :)
