### ISSUE TITLE
[Proposal] Add a new flag to the "search operator" that returns something if "any" token matches

### ISSUE THREAD

**Issue by pmario** [Jermolene/TiddlyWiki5#6289]
It's proposed to add a new flag to the search operator, that allows us to show _more_ results instead of _less_ as it is atm.

Eg: If I search for `[search:tags[one two]]` at the moment, the default behaviour needs to match both tokens to return an element

The proposal is to have a new flag eg: "any" that will return a result if at least **one** token matches. 

It would look like this: `[search:tags:any[one two]]` .......... I'm not sure if `any` is the best flag name .. It may be confused with search in "any field" if used without a field flag ... 

It will be possible to combine it with `anchored` and `casesensitive`

The implementation is simple. It's just the name of the flag and the docs that need to be done. I've done the code and tests already :)

What do you think?

**Comment by pmario** [comment]
`[search:tags:either[one two]]` may be a possibility too

**Comment by CodaCodr** [comment]
Well, the default is clearly `all` to support bc. That leads to `some` for "at least one", I think.

```
[search:tags:all[one two]] === [search:tags[one two]]

[search:tags:some[one two]]  match for one or two, or one-and-two. 
```

**Comment by Jermolene** [comment]
Thanks @pmario @CodaCodr it's a reasonable suggestion. I wonder if we there are values that might be useful beyond "all" and "some"?

**Comment by pmario** [comment]
I think `some` is a good choice. ... So `some` is the shortcut for "some words" ... 

The [search operator](https://tiddlywiki.com/#search%20Operator) has: `literal`, `whitespace`, `regexp` and `words`. Where `words === all` atm.

**Comment by CodaCodr** [comment]
brainstorming (not my babies ;) )

Since `some` equates to  "any of", we could round it out with "N of"

```
search:tags:1[one two] === 1 of
search:tags:3[one two three four] === 3 of
```
I think it should be read as "_any N of_" and **not**  "only N of".

**Comment by pmario** [comment]
>I think it should be read as "any N of" and not "only N of".

I don't see the usecase atm. 

IMO that's the existing behaviour if you remove 1 of the terms manually. eg: "one two three four" and you don't want "three" .. just remove it. ... You get 3 out of N ;)

**Comment by CodaCodr** [comment]
@pmario  Not sure. The list of comparators may be computed.

**Comment by CodaCodr** [comment]
Again brainstorming and I'm really not sure I even like this...

```
search:tags:from:<n><my-list>  start the search the nth list item
search:tags:from:<-n><my-list>  start the search the length-nth list item
```

**Comment by CodaCodr** [comment]
> Again brainstorming and I'm really not sure I even like this...
> 
> ```
> search:tags:from:<n><my-list>  start the search at the nth list item
> search:tags:from:<-n><my-list>  start the search at the length-nth list item
> ```

YAGNI :)

**Comment by saqimtiaz** [comment]
@pmario I'm rather distracted at the moment so this isn't very well thought through, I am mostly thinking out loud:

- A common user need in a filter is to check whether the input titles contains one or all of specific titles. Pseudocode:

` [...titles...] +[input-contains:any/all[a],[b],[c]]`

This use case may already be possible with the use of filter runs, and if so we should document it. It would be helpful for users to have an intuitively named operator that caters for this use case, rather than try to use the improvements in `search[]`. Furthermore, it would be ideal that the suffixes for such an operator matched the proposed extension to the `search[] `operator for consistency. (Whether we add such an operator is a later consideration).

I think the suffixes `any` and `some` are appropriate in both instances.

**Comment by CodaCodr** [comment]
> It would be helpful for users to have an intuitively named operator that caters for this use case, rather than try to use the improvements in `search[]`

THIS. +100

**Comment by pmario** [comment]
>... I am mostly thinking out loud:

No problem. ... also just brainstorming. ... 

I was thinking about a code change in the core to make some "search" utility functions usable as an API instead of encapsulating them in the `wiki.search()` function. eg: `.getSearchRegexp()` and `searchText()`

This would make the "search flags" like: `literal, whitespace, regexp, words, some, casesensitive, anchored` ...  usable for other existing or future filter functions _and_ for plugin authors. Those new functions would also define the "keywords" used and therefore they should be consistent. ...
