### ISSUE TITLE
[BUG] The except Named Filter Prefix Does Not Work as Expected

### ISSUE THREAD

**Issue by kookma** [Jermolene/TiddlyWiki5#6298]
See the below two codes! They produces different results:

### Shadows tiddlers
* In the first example `:except[search:title[icon]] ` is used
* In the second example `!search:title[icon]] `

**Issue**: They should produce the same results but `except` seems does not work.

<img src="https://user-images.githubusercontent.com/830394/144383111-b2dd30ff-38e9-4098-b7ac-40c75f56547e.png" width="560px"/>

### Ordinary tiddlers
It seems this issue is happen for shadow tiddlers.

See the below example
<img src="https://user-images.githubusercontent.com/830394/144384689-1c3b0eed-f6c1-4c73-87a4-7531b3868819.png " width="560px"/>
 
**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome / Edge 96
 - Version TW 5.2.1p

### Codes
To give a try, create a new tiddler in https://tiddlywiki.com/prerelease and put the below text inside

```
<$list filter="[all[shadows]] :except[search:title[icon]] :and[limit[5]]">

</$list>

---

<$list filter="[all[shadows]!search:title[icon]] :and[limit[5]]">

</$list>
```

and

```
<$list filter="[tag[About]] :except[search:title[History]] :and[limit[5]]">

</$list>

---

<$list filter="[tag[About]!search:title[History]] :and[limit[5]]">

</$list>
```

**Comment by Jermolene** [comment]
Hi @kookma it would be much appreciated if you could also include the text of those test cases; it's awkward to retype them from the screenshots.

**Comment by kookma** [comment]
Hi @Jermolene 
> it's awkward to retype them from the screenshots.

I updated the original post with code

**Comment by kookma** [comment]
Hi @saqimtiaz 
> The following three filter expressions should be equivalent:

As `:except` is the next step in the above example, one expects this filter run shall receive its input from previous run step! But it seems it is a separate filter run and only the result is subtracted from the first run!
