### ISSUE TITLE
[BUG] "ListWidget Counter variable" fail to render/export with "--render" command

### ISSUE THREAD

**Issue by msameen99** [Jermolene/TiddlyWiki5#6300]
**Describe the bug**
The Tiddlers that contains the new "ListWidget Counter" variable is working great inside the TW5 (node), but If I try to export it using 
`--render text/plain $:/core/templates/static.tiddler.html` command , the counter is disappeared from the HTML file , and any filters that use it also fail to produce the correct result.

**To Reproduce**
1. Using TW5 Node, create a new tiddlers as the following:
title: `Test Export - with List Counter`
list: `A1 B2 C3 D4 E5 F6`
text: `<$list filter="[list[]]" variable="lst" counter="cntr"><br>(<<cntr>>) <$text text=<<lst>>></$list>`
3. inside TW5 the Tiddler will show the correct result
4. Now try to render/export it using the command `tiddlywiki yourTW5 --render """[[Test Export - with List Counter]]""" """[addsuffix[.html]]""" text/plain $:/core/templates/static.tiddler.html`
5. Check the "test-export-with-list-counter.html" file, the "Counter Values" is EMPTY

**Expected behavior**
A Tiddler that use the New "ListWidget Counter" should look the same inside TW5 and in the Static HTML file produced with `--render` command

**Screenshots**
ListWidget Counter inside TW5:
![image](https://user-images.githubusercontent.com/16881960/144541166-8313503d-6b1a-4bfc-bddd-13c69fb984ab.png)

ListWidget Counter inside HTML rendered file:
![image](https://user-images.githubusercontent.com/16881960/144540188-33357a36-7507-4c9d-a4e1-c12eff61dc74.png)

**TiddlyWiki Configuration (please complete the following information):**
 - Version: v5.2.0
 - Saving mechanism: Node.js
 
**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Browser: chrome

**Comment by pmario** [comment]
There is a typo in the code. `<$text text=<<x>>\>` should look like this. See: `\>` at the end... but I'm not sure if that causes the problem can't test atm.

Which `node --version` do you use?

**Comment by msameen99** [comment]
1- I'm using node version v17.1.0 on Arch Linux

2- I repeated the steps above after correcting the typo, and the issue is still there, please see below screenshot

**Tiddler in TW5**
![image](https://user-images.githubusercontent.com/16881960/144590582-f3c87113-663b-446b-8577-59a8d8d24faf.png)

**Tiddler in HTML**
![image](https://user-images.githubusercontent.com/16881960/144590657-16a955d7-babe-487e-8e7c-252a0ae19415.png)

**Comment by msameen99** [comment]
Ok, It was my mistake, turn out that I was using 2 different TiddlyWiki versions:
- Version 5.2.0 in a docker container (Alpine v3.13 - Node.js=15.14.0) to display the Tiddler
- Version 5.1.23 in local Machine (Arch - Node.js=17.1.0) to render the Tiddlers

After upgrading the 5.1.23 to 5.2.0 , everything is working as expected

Closing the Issue
