### ISSUE TITLE
[BUG] [is[variable]] operator doesn't work for "fake" variables

### ISSUE THREAD

**Issue by Jermolene** [Jermolene/TiddlyWiki5#6303]
**Describe the bug**
Variables are stored in a property "variables" of widget objects that contains a hashmap of variable values, using prototypal inheritance to include the variables of the parent widget.

Some filter run prefix modules make variable values available to subfilters by providing a fake widget object that implements a `getVariable` method to retrieve variable values. For example:

https://github.com/Jermolene/TiddlyWiki5/blob/f88e3939e1d40f7c60d4dcf8c96a6c56d06bc3ec/core/modules/filterrunprefixes/cascade.js#L28-L41

The problem arises that the `[is[variable]]` operator tests for the existence of variables by reaching into the `variables` property, and thus cannot see any variables introduced via the fake widget technique.

**To Reproduce**
1. Go to https://tiddlywiki.com/
2. Open advanced search and switch to the "Filter" tab
3. Enter the filter expression `test :filter[[..currentTiddler]is[variable]]`
4. Note that the filter returns 0 results

**Expected behavior**
The filter should return the value `test`

**Possible Fixes**
The cleanest fix might be for `[is[variable]]` to test for the existence of the variable by calling `getVariable()` on the widget, and testing for the result `undefined`.

**Comment by pmario** [comment]
>Enter the filter expression test :filter[[..currentTiddler]is[variable]]

The documentation says that `..currentTiddler` is available in the operator. So why should I need a test like this?

`test :filter[[..currentTiddler]]` works as expected. .. So what I'm missing?

**Comment by Jermolene** [comment]
Hi @pmario it's a contrived example intended to show the bug, not to be an example of a practical usage.

**Comment by hoelzro** [comment]
@Jermolene I'm interested in trying to fix this - so far I've added a test to the test edition.  Regarding the fix itself - is there a valid reason `getVariable()` might return `undefined` for an actual variable?  My cursory understanding of the code didn't come up with anything, so I figured I'd check!

**Comment by Jermolene** [comment]
Hi @hoelzro there is a fix for this within #6666 

https://github.com/Jermolene/TiddlyWiki5/pull/6666/files#diff-8f945a9eb279630fb72963db71b825130162f24c67365478c6e5c011bc3b00f3

It would make sense to cherry pick the fix and merge it now.

**Comment by hoelzro** [comment]
Ah, ok! Would you like me to submit my tests as a PR?

**Comment by Jermolene** [comment]
Thanks @hoelzro 

> Ah, ok! Would you like me to submit my tests as a PR?

That would be great, perhaps also cherrypick the fix out of #6666.

**Comment by hoelzro** [comment]
@Jermolene Ok, done!

**Comment by Jermolene** [comment]
Thanks @hoelzro
