### ISSUE TITLE
Server edition forgets name for signing edits

### ISSUE THREAD

**Issue by nilslindemann** [Jermolene/TiddlyWiki5#6304]
Tested with the latest Firefox and Iridium (which is a relatively up-to-date Chrome) on Windows 7, Node.js v15.8.0. TiddlyWiki is the current codebase (tested with master in my fork).

Do the following (or your OS equivalent):

```batch
cd editions
node ..\tiddlywiki.js myNewWiki --init server
cd myNewWiki
node ..\..\tiddlywiki.js --listen
```

Open http://127.0.0.1:8080

Open [control panel](http://127.0.0.1:8080/#%24%3A%2FControlPanel), enter something in "Username for signing edits"

Reload page

Go back to control panel: What you entered is gone. Same result if you directly edit $:/status/UserName, save, reload.

The bug is older than October 24. (date of last commit in my oldest branch, the bug is there also)

**Comment by nilslindemann** [comment]
Hmm, `$/status/`, shouldnt this be `$/state/` ?!

**Comment by Jermolene** [comment]
When running in client-server configuration the tiddler $:/status/UserName is set automatically according to the user accessing the wiki. By default, there is no username defined, and so it gets reset. The anonymous username can be overridden by including `anon-username=myname` as an additional parameter for the `listen` command.

Nonetheless the user experience is confusing at the moment. Perhaps we could have the syncer notice that $:/status/UserName has changed and dynamically set the username accordingly.

> Hmm, $/status/, shouldnt this be $/state/ ?!

`$:/state/` is for user interface state, `$:/status/` is for status; the name actually better reflects the client-server behaviour than the standalone behaviour.

**Comment by nilslindemann** [comment]
Thanks, @Jermolene, didn't know that. So it is not really a bug.

I am inexperienced in the syncing part of the code (I guess syncer.js does this), so I can not be a big help in this.

**Comment by nilslindemann** [comment]
Closing this (though your idea to detect these changes would be nice to have)

**Comment by nilslindemann** [comment]
> Perhaps we could have the syncer notice that $:/status/UserName has changed and dynamically set the username accordingly.

Would I be right that this would be done [here](https://github.com/Jermolene/TiddlyWiki5/blob/f88e3939e1d40f7c60d4dcf8c96a6c56d06bc3ec/core/modules/syncer.js#L278)? (Not doing it, just curious)

**Comment by Jermolene** [comment]
> Would I be right that this would be done [here](https://github.com/Jermolene/TiddlyWiki5/blob/f88e3939e1d40f7c60d4dcf8c96a6c56d06bc3ec/core/modules/syncer.js#L278)? (Not doing it, just curious)

The current implementation depends on the fact that $:/status/UserName is not synced from the client to the server, so one would probably want to start by fixing that, and then have a change handler on the server to pick up the change and set the username in the server module.

It's a big change; at the moment server parameters don't change once the server has started up, so the semantics would be significantly more complex.

**Comment by nilslindemann** [comment]
Yeah, ok, it's not important enough for that.

**Comment by nilslindemann** [comment]
I mean, most users probably use it via browser and will never run into it, and on the server side it's just a command line parameter, so whatever.
