### ISSUE TITLE
[BUG]$tw.utils.decodeURIComponentSafe is not a function

### ISSUE THREAD

**Issue by ddavout** [Jermolene/TiddlyWiki5#6311]
**Describe the bug**
I obtain this popup
Well, this is embarrassing. It is recommended that you restart TiddlyWiki by refreshing your browser
TypeError: $tw.utils.decodeURIComponentSafe is not a function

**To Reproduce**
when I import a local copy of README.md
https://github.com/fuhrmanator/GIFT-grammar-PEG.js/blob/master/README.md

**Expected behavior**
opening of the document

**
I refresh the browser as advised, then the 
 Please wait while Mon wiki perso is loading ... 
 It hangs ...
I removed the README.tid and the README.meta; and made a full refresh the wiki loaded and I removed the README from the sidebar

but if to the import again and this time only close the popup, I can remove straight away the README.me.
Everything is back to normal, only for the Recent list and I press on README.me the popup reappears)

**TiddlyWiki Configuration (please complete the following information):**
 - Version [ v5.1.23]
 - Saving mechanism [Node.js]

 
**Desktop (please complete the following information):**
 - OS: Ubuntu]
 - Browser [Mozilla Firefox 90.0] same behaviour with Chromium Version 90.0.4430.212

**Additional context
tiddlyserver -v undefined

**Comment by pmario** [comment]
I did try to import it to tiddlywiki.com and with a local copy of v5.1.23 ...  everything works as expected.

Are you sure, you don't use plugins that mess up with the import system.

**Comment by ddavout** [comment]
Sorry, for the time yoy lost : I did not follow the peace of advice
> Note that including a plugin as an ordinary tiddler It is not recommended ...
> if TiddlyWiki has been installed with npm because npm is liable to overwrite the installation when performing an update

I installed my plugins . by dragging and dropping from one my standalone Tiddly, creating conflicts.
Maybe I carelessly followed https://tiddlywiki.com/#Installing%20a%20plugin%20from%20the%20plugin%20library
even if the point
> Create a backup of your current TiddlyWiki HTML file (just in case)
should have alerted me.
Fortunately, I manage to recover my wiki

Sent with [ProtonMail](https://protonmail.com/) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
