### ISSUE TITLE
[IDEA] Splitting core from store area

### ISSUE THREAD

**Issue by ibnishak** [Jermolene/TiddlyWiki5#6313]
To the effect of
```
<script class="tiddlywiki-tiddler-store" type="application/json" id="tw-core-store">
```
for core
and 
```
<script class="tiddlywiki-tiddler-store" type="application/json" id="tw-ordinary-store">
```
for user created/modified tiddlers.

Since loading of tiddlers is already based on class `tiddlywiki-tiddler-store`, there won't be any issue there.

Rationale: It would make it more easy for external applications to interact with TW5, say for example, backup of user data. Currently you need to read the entire JSON into memory and loop through the array to figure out what is worth saving. If we move core out of the way, it will become much easier. Even better, one would not have to check the JSON at all, just extract the ordinary store id using any generic web-scraper available. 

Further splitting can be considered for plugin tiddlers. The basic idea is to isolate user generated data.

**Comment by pmario** [comment]
>... say for ex, backup of user data

"ex" ??

**Comment by saqimtiaz** [comment]
> "ex" ??

example

**Comment by ibnishak** [comment]
> > ... say for ex, backup of user data
> 
> "ex" ??

Updated the comment for clarity

**Comment by Jermolene** [comment]
Thanks @ibnishak. My concern would be that by using multiple blocks of tiddlers we make the system more complex, ultimately making interoperability harder. In the meantime, we use [Postel's law](https://en.wikipedia.org/wiki/Robustness_principle), by being strict in what we generate and liberal in what we accept, and I think that that gives enough space for experimentation.
