### ISSUE TITLE
[BUG] $:/plugins/tiddlywiki/internals/.../raw -> InternalError too much recursion

### ISSUE THREAD

**Issue by CodaCodr** [Jermolene/TiddlyWiki5#6324]
**Describe the bug**
Browsing through plugins at tiddlywiki.com (5.2.1), clicked on https://tiddlywiki.com/#%24%3A%2Fplugins%2Ftiddlywiki%2Finternals and received the error.

**To Reproduce**
1. Go to tiddlywiki.com
2. Click on sidebar More/Plugins and choose Internals from the list
3. In the plugin tiddler, open the contents tab and start clicking on the links

Once ..."raw" has been clicked, you'll be stuck with red screens until you close the plugin tiddler. But even then you might be left with "dead" tiddler nodes left behind (see screenshot).

**Screenshots**
![image](https://user-images.githubusercontent.com/436812/145276174-a953ebb8-0760-488a-bbc3-99c04d4158b2.png)

**TiddlyWiki Configuration:**
 - TW Version 5.2.1
 - OS: Win10
 - Firefox

**Comment by Jermolene** [comment]
Thanks @CodaCodr fixed in 54cfda76ee353190f1cf0210b9071894fb1a5690

**Comment by Jermolene** [comment]
It should be live on the prerelease site in 5 mins

**Comment by CodaCodr** [comment]
Fix confirmed at https://tiddlywiki.com/prerelease/#%24%3A%2Fplugins%2Ftiddlywiki%2Finternals%2FEditTemplate%2Fbody%2Fpreview%2Fraw
