### ISSUE TITLE
Add support for image loading animations

### ISSUE THREAD

**Issue by Jermolene** [Jermolene/TiddlyWiki5#6346]
It is proposed to update the image widget so that an class `tc-image-loaded` class is added to the `<img>` tag when the image has successfully loaded. With some simple CSS this will make it possible to animate the display of images as they load.

**Comment by Jermolene** [comment]
(Proposed in this thread: https://groups.google.com/g/tiddlywiki/c/CO6dHDcOGJE/m/vxy4-_95BwAJ)

**Comment by Jermolene** [comment]
Fixed in 66ae1d6930796a9eb062fdb64a755adab8f39294

**Comment by protrolium** [comment]
works perfectly. thank you @Jermolene
