### ISSUE TITLE
The `--listen` command should issue warnings for unrecognised parameter names

### ISSUE THREAD

**Issue by Jermolene** [Jermolene/TiddlyWiki5#6375]
The `--listen` command takes named parameters like this:

```
tiddlywiki mywikifolder --listen credentials=myusers.csv "readers=(authenticated)" writers=mary
```

Users sometimes get the names of the parameters wrong (eg in #6374 `readers` was confused for `reader`.

It is proposed to issue a warning message for any unrecognised parameter names.

**Comment by Jermolene** [comment]
I don't think this is possible without a substantial redesign. The fundamental problem is that individual routes can and do read parameters via `state.server.get()`, which means that the server module itself doesn't know all of the valid parameter names.

I guess we could look for specific misspellings like `reader` vs. `readers`, but it seems hard to imagine that we'd be able to anticipate all of the mistakes.

**Comment by jaguart** [comment]
One thing I noted is that I can specify **password** without **username** and that leads to a wiki 404.

So you could validate that if **username** or **password** is specified, the other should also be present - that will pick up accidental combos of *user*, *passwd* etc.

Optionally, you could also require that  **readers** and **writers** are specified.

IMHO just tightening this up a little makes a big impact on security - I thought my wiki was password protected - when it was really open to the world. You could also consider some internal Wiki config that I could set using the Wiki itself - e.g. ``RequireAuthentication => yes`` - that could check and warn if the server was not running with auth enabled.

Good security is about having multiple layers of protection - the more you have, the less likely that all the holes will align and leave you hanging :o

**Comment by jaguart** [comment]
Oh - and another small idea, you could make **reader** an alias for **readers** and **writer** an alias for **writers** - that pluralisation makes sense, but I clearly just skipped over the last char.

Along the same lines, you could simply make **user** an alias for **username** e.g. ``$username //= $user if $user;`` - while the visual difference in the docs is greater, I am guessing that this will be a fairly common mistake. For an extra gold star ``warn 'oops' if $username and $user;``

My main thought though, is that having an internal wiki config like ``RequireAuth => yes`` that simply displays a constant banner warning if the server is not running with auth, or the UserName is not set, would be the biggest win for security. Of course you might choose something more flexible like ``SecurityCheck => AuthenticatedReader, AuthenticatedWriter, NoAnon`` which might be a more future-proof alert.
