### ISSUE TITLE
[IDEA] WidgetMessage: tm-edit-text-operation wrap-lines

### ISSUE THREAD

**Issue by jaguart** [Jermolene/TiddlyWiki5#6376]
**Is your feature request related to a problem? Please describe.**
Yes - the WidgetMessage: **tm-edit-text-operation** --  **wrap-lines** expects *both* **prefix** and **suffix** params. <br>
If either is not present, a Javascript Exception is thrown.

**Describe the solution you'd like**
* If the **prefix** is not specified (i.e. undefined, rather than empty-string), *don't* attempt to add the prefix.
* If the **suffix** is not specified (i.e. undefined, rather than empty-string), *don't* attempt to add the suffix.

This change would accomplish two things:
1. It would eliminate an exception
2. It would enable use of this message to simply add one line - either *before* or *after* the current selection.

Why? I would like to be able to add an EditToolbar item that inserts a new line of text (being a signature) after the current line, *without* inserting a blank line before the current line, and even when the cursor is in the middle of a line.

**Describe alternatives you've considered**
*None*

**Additional context**
I'd be happy to help do this if you point me in the right direction. My coding is fine - I'm just not familiar with the process of contributing here.

**Comment by Jermolene** [comment]
Thanks @jaguart, good spot. Broadly, any JS exception that can be triggered from wikitext is classed as a serious bug.
