### ISSUE TITLE
[BUG] Join Operator and the Empty Variable

### ISSUE THREAD

**Issue by kookma** [Jermolene/TiddlyWiki5#6386]
One expects join operator ignores empty value!

### To reproduces
1. download [Test Join.zip](https://github.com/Jermolene/TiddlyWiki5/files/7807040/Test.Join.zip)
2.  drag and drop into https://tiddlywiki.com/

### Description

The join operator shall ignore empty variable, but it does not!
The first example produces wrong result while the second works!

```
<$vars literal={{!!literal}} casesensitive={{!!casesensitive}} >
<$text text={{{ [<casesensitive>!is[blank]] [<literal>!is[blank]] +[join[,]] }}} />
</$vars>


<$vars literal={{!!literal}} casesensitive={{!!casesensitive}} >
<$text text={{{ [<casesensitive>] [<literal>] +[join[,]] }}} />
</$vars>
```

### System info

* Win10
* Chrome 96
* Tiddlywiki 5.2.1

**Comment by saqimtiaz** [comment]
This is expected behaviour, not a bug. An empty string is always considered a valid title in the output of a filter expression.

**Comment by kookma** [comment]
Thank you @saqimtiaz
