### ISSUE TITLE
[BUG] Test failure in editions/test/tiddlers/tests/test-utils.js

### ISSUE THREAD

**Issue by ualich** [Jermolene/TiddlyWiki5#6387]
There is a failing unit test that emerges when running the script `bin/test.sh`. The issue appeared in `v5.1.23` and has persisted since.

The output of the command `./bin/test.sh` is

```bash
Boot log:
  Startup task: load-modules
  Startup task: info after: load-modules before: startup
  Startup task: plugins after: load-modules
  Startup task: startup after: load-modules
  Startup task: story after: startup
  Startup task: commands platforms: node after: story
Executing command: version 
5.2.2-prerelease
Executing command: rendertiddler $:/core/save/all test.html text/plain
Randomized with seed 67164
Started
..................................................................................F...................................................................................................................................................................................

Failures:
1) Utility tests should handle parsing a date
  Message:
    Expected 'Thu, 28 Apr -073 20:49:30 GMT' to equal 'Thu, 28 Apr -0073 20:49:30 GMT'.
  Stack:
    Error: Expected 'Thu, 28 Apr -073 20:49:30 GMT' to equal 'Thu, 28 Apr -0073 20:49:30 GMT'.
        at <Jasmine>
        at UserContext.<anonymous> (test-utils.js:35:36)
        at <Jasmine>

262 specs, 1 failure
Finished in 1.581 seconds
Randomized with seed 67164 (jasmine --random=true --seed=67164)
```

NOTE: Issues related to this test failure were not observed.

**Additional context**
* node.js v10.19.0
* OS: Ubuntu 20.04 (Linux kernel 5.11.0-43-generic)
* could not reproduce on Android device

**Comment by Jermolene** [comment]
Thanks @ualich that's very strange – the tests [are running OK on GitHub actions](https://github.com/Jermolene/TiddlyWiki5/actions), and on my machine. I wonder if it's an issue with the node.js version – I'm on 14.x. The root cause must be a difference in the output of `Date().toUTCString()`, which seems like something that shouldn't happen!

**Comment by ualich** [comment]
Thank you, upgrading node.js solved the issue!
There was indeed a difference in the output of `Date().toUTCString()` between the versions.

**Comment by Jermolene** [comment]
Great thanks @ualich
