### ISSUE TITLE
[BUG] $:/tags/RawMarkupWikified/TopHead is ignored

### ISSUE THREAD

**Issue by sarna** [Jermolene/TiddlyWiki5#6395]
**Describe the bug**
This filter in `$:/core/templates/tiddlywiki5.html` seems to be broken: `{{{ [<saveTiddlerAndShadowsFilter>tag[$:/tags/RawMarkupWikified/TopHead]] ||$:/core/templates/raw-static-tiddler}}}`. If I paste it to another tiddler (along with the macros and stuff) it doesn't show any tiddlers.

**To Reproduce**
1. Open a new tiddler
2. Paste this in it:
    ```
    \define saveTiddlerFilter()
    [is[system]] -[prefix[$:/state/popup/]] -[[$:/boot/boot.css]] -[type[application/javascript]library[yes]] -[[$:/boot/boot.js]] -[[$:/boot/bootprefix.js]] +[sort[title]]
    \end

    <!-- above pasted from $:/core/save/all -->

    <$set name="saveTiddlerAndShadowsFilter" filter="[subfilter<saveTiddlerFilter>] [subfilter<saveTiddlerFilter>plugintiddlers[]]">


    Full filter:

    {{{ [<saveTiddlerAndShadowsFilter>tag[$:/tags/RawMarkupWikified/TopHead]] }}}

    Without the tag:

    {{{ [<saveTiddlerAndShadowsFilter>] }}}

    ```
   Feel free to change the tag, it doesn't matter what it is. It won't work.

**Expected behavior**
I'd expect this filter to correctly return tiddlers tagged with `$:/tags/RawMarkupWikified/TopHead` (and by that I'd expect the mechanism of putting stuff in <head> to work).

**TiddlyWiki Configuration (please complete the following information):**
 - Version 5.2.1
 - Saving mechanism Node.js
 - Plugins installed 
 
**Desktop (please complete the following information):**
 - OS: Linux (GNOME)
 - Browser Firefox
 - Version 95.0.2

**Comment by pmario** [comment]
You need to save and reload. ... Did you try that?

**Comment by sarna** [comment]
> You need to save and reload. ... Did you try that?

Yup, I restarted the Node service, multiple times - no dice. Tried disabling cache in Firefox, same thing.

Does it work correctly for you?

**Comment by Jermolene** [comment]
Thank you @sarna for the very clear report. I can confirm bug, and will push a fix shortly.

**Comment by sarna** [comment]
That was fast :) Thanks a ton!

**Comment by Jermolene** [comment]
> That was fast :) Thanks a ton!

Happily this is one of the class of bugs that was hard to find but trivial to fix, so I should thank you for doing most of the work!
