### ISSUE TITLE
[IDEA] extend tm-scroll message, $scrollable and pagescroller to optionally scroll without animation

### ISSUE THREAD

**Issue by saqimtiaz** [Jermolene/TiddlyWiki5#6406]
The widget message `tm-scroll` currently triggers a scroll that is animated using the duration as configured in `$:/config/AnimationDuration`. This makes it impossible to trigger a scroll with no animation without completely disabling animations in the wiki.

It is suggested to extend the widget message `tm-scroll` with an optional `animation-duration` parameter, which if present takes precedence over `$:/config/AnimationDuration` in the scroll handling in `$scrollable` and `PageScroller`.

Edit: alternatively we could have an `animate=yes/no` paramter for `tm-scroll`

**Comment by Jermolene** [comment]
Hi @saqimtiaz good thinking.

**Comment by saqimtiaz** [comment]
@Jermolene thoughts on whether we want to be able to control the animation duration via a parameter for `tm-scroll`, or just have a parameter that toggles the animation on and off?

**Comment by Jermolene** [comment]
> @Jermolene thoughts on whether we want to be able to control the animation duration via a parameter for `tm-scroll`, or just have a parameter that toggles the animation on and off? 

Supporting a duration parameter seems the most flexible. We've already established the convention that an animation duration of zero suppresses the animation entirely.

**Comment by saqimtiaz** [comment]
@Jermolene that makes sense and is my preference as well.

I would like some input on some code in `$scrollable` that doesn't quite make sense to me. 

`ScrollableWidget.prototype.scrollSelectorIntoView()` accepts a `callback` argument. However:
* I cannot see that it is ever called with this argument.
* It calls `scrollIntoView()` with `callback` as a second argument, however that method only accepts a single argument.
Can this `callback` argument be safely removed? It appears to not be used anywhere.

https://github.com/Jermolene/TiddlyWiki5/blob/d8238560821e6e3c0217eadcb7fe9d74981b4e32/core/modules/widgets/scrollable.js#L117-L123

https://github.com/Jermolene/TiddlyWiki5/blob/d8238560821e6e3c0217eadcb7fe9d74981b4e32/core/modules/widgets/scrollable.js#L52-L55

**Comment by Jermolene** [comment]
I think those peculiarities are connected with the fact that we have two implementations of the scrolling code (one in the global scroller, and one in the scrollable widget), and at some point in the past I made some moves to refactor things into a single implementation.
