### ISSUE TITLE
[IDEA] caseinsensitive behavior for prefix/suffix operators

### ISSUE THREAD

**Issue by saqimtiaz** [Jermolene/TiddlyWiki5#6407]
It would be helpful to have optional case-insensitive support in the `prefix[]`, `suffix[]` operators (and perhaps `removeprefix[]` and `removesuffix[]`).

One option would be to introduce a suffix for these operators, for example:

`prefix:ci[]`

**Comment by Jermolene** [comment]
Good idea. I think that the existing operators that have case sensitivity/insensitivity flags are "match" and "search", and that they spell things out in full to `casesensitive` and `caseinsensitive`.

**Comment by kookma** [comment]
@saqimtiaz having casein sensitive/insensitive support for prefix/suffix is absolutely useful!
