### ISSUE TITLE
[IDEA] post-render hook for storyviews

### ISSUE THREAD

**Issue by saqimtiaz** [Jermolene/TiddlyWiki5#6408]
Storyviews are a versatile way to add animation and behaviour to a `$list` widget. However currently there is no post-render hook for a storyview, which I am finding that I need in my use case to control the initial display state.

Could we extend the $list widget to call a `storyview.postRender()` method if it exists for the given storyview, at the end of `ListWidget.prototype.render()`?

**Comment by CodaCodr** [comment]
@saqimtiaz Interesting. How do you imagine the wikitext to look?

**Comment by saqimtiaz** [comment]
> @saqimtiaz Interesting. How do you imagine the wikitext to look?

The discussion is about a JavaScript hook for authors of storyviews to avail themselves of. Storyview methods are not directly exposed to wikitext, at least not until after we refactor $navigator to be wikitext based.

**Comment by Jermolene** [comment]
Hi @saqimtiaz 

> Could we extend the $list widget to call a `storyview.postRender()` method if it exists for the given storyview, at the end of `ListWidget.prototype.render()`?

Good idea, I don't see a problem with that.
