### ISSUE TITLE
[BUG] Fold bar position absolute cover the $:/tags/ViewTemplate element

### ISSUE THREAD

**Issue by linonetwo** [Jermolene/TiddlyWiki5#6411]
**Describe the bug**

I add an element use $:/tags/ViewTemplate , but the fold bar just overlay it, because the fold bar have `position: absolute`

**To Reproduce**
1. Drag a plugin that uses $:/tags/ViewTemplate, for example https://onetwo.ren/wiki/#%24%3A%2Fplugins%2Flinonetwo%2Finverse-link-and-folder , into https://tiddlywiki.com/
2. Enable fold-bar in ControlPanel - Appearance - Toolbars - View Toolbar 
3. Fold a tiddler
4. See the fold-bar overlay plugin's content

**Expected behavior**

Tiddler with $:/tags/ViewTemplate should be fold together? Or at least not overlay with the fold bar.

https://github.com/Jermolene/TiddlyWiki5/blob/853a899c77766e47eade1dfa5822640ef9915637/themes/tiddlywiki/vanilla/base.tid#L635

Maybe change this to position unset?

**Screenshots**

![截屏2022-01-20 下午10 00 11](https://user-images.githubusercontent.com/3746270/150353066-859e63eb-889e-4d93-9725-4866a9404ef8.png)

![截屏2022-01-20 下午10 00 07](https://user-images.githubusercontent.com/3746270/150353081-a12f6ed1-4413-425d-96e3-38f09a5f891f.png)

**TiddlyWiki Configuration (please complete the following information):**
 - Version 5.2.1
 - Saving mechanism official website
 - Plugins installed https://onetwo.ren/wiki/#%24%3A%2Fplugins%2Flinonetwo%2Finverse-link-and-folder

**Additional context**

I tried to search for a tag that will make tiddler added to the body that will be fold together, but not found.

I have to use 

```
<$reveal
	state=<<folded-state>>
	type="nomatch"
	text="hide"
	animate="yes"
>

</$reveal>
```

To hide content when folded.

**Comment by pmario** [comment]
The problem is in: https://onetwo.ren/wiki/#%24%3A%2Fplugins%2Flinonetwo%2Finverse-link-and-folder%2Finfobar

You can cover your content into a div eg:

```
<div class="add-top-margin">
your content
</div>
```

Add a rule to: https://onetwo.ren/wiki/#%24%3A%2Fplugins%2Flinonetwo%2Finverse-link-and-folder%2Flist-link.css

```
.add-top-margin{
  margin-top: 2em;
}
```

IMO that should do the trick.

**Comment by pmario** [comment]
If you want to hide the footer too, you can create some more logic in your footer, then the top margin won't be needed.

**Comment by linonetwo** [comment]
Okay, but maybe this margin should be automatically provided? In the core css.

**Comment by pmario** [comment]
> Or just make fold bar not absolute.

There's probably a reason why it is position absolute. .. I don't have the time to dig into that. ... 

There may be a possibility to completely redesign the ViewTemplate. So every element uses the new "cascade" mechanism. .. But nobody did research those possibilities yet.

**Comment by linonetwo** [comment]
> So every element uses the new "cascade" mechanism. .. But nobody did research those possibilities yet.

Hi Mario, I was quite interested in this, but I found that cascade is different to the viewTemplate mechanism, because "cascade" will replace the whole view template, so two template in cascade won't show at the same time. While ViewTemplate tag just add a new part to the existing view, many parts can show at the same time...

**Comment by Jermolene** [comment]
Hi @linonetwo just to confirm that the behaviour described in the OP is by design. The expectation is that custom view template segments will respect that a tiddler is folded, hiding the content with a reveal widget as you describe.

**Comment by linonetwo** [comment]
Thanks for the confirmation!

I will use the reveal widget for this. And adding padding-top if I want things keep shown when folding.
