### ISSUE TITLE
[BUG] Editor Button "Monospaced" Throws JS Error

### ISSUE THREAD

**Issue by telmiger** [Jermolene/TiddlyWiki5#6419]
**Click the "Monospaced" button in the Editor**
Result: The red overlay for internal JavaScript Errors states
> TypeError: can't access property "prefix", operation.paramObject is undefined

**To Reproduce**
1. Load the 5.2.2 prerelease 
2. Create a new tiddler or edit an existing tiddler
3. Select text or just click into the edit area of the text field
4. Click the button to format monospaced text.
5. See error

**Expected behavior**
The button should surround existing text or the cursor with tripple backticks.

**Screenshots**

**TiddlyWiki Configuration**
 - Version 5.2.2 prerelease
 
**Seen on Desktop and Mobile**
 - Mac OS FireFox Developer Edition
 - Chrome on Android

**Comment by saqimtiaz** [comment]
Confirmed the error, originates from this commit: https://github.com/Jermolene/TiddlyWiki5/commit/88812092fd8fa7da18e6da77f9c410338469cc4e

**Comment by Jermolene** [comment]
Thanks @saqimtiaz – I can't prepare a fix until later today, but will do so then if nobody else has got there first.

**Comment by twMat** [comment]
I get the presumably same error for "quote"

<img width="95" alt="image" src="https://user-images.githubusercontent.com/4534056/150833855-ac013613-0ad6-4525-90e6-e1e51e3853fc.png">

**Comment by saqimtiaz** [comment]
@Jermolene do you want to revert https://github.com/Jermolene/TiddlyWiki5/commit/88812092fd8fa7da18e6da77f9c410338469cc4e or just push a fix in another commit?

**Comment by Jermolene** [comment]
> @Jermolene do you want to revert [8881209](https://github.com/Jermolene/TiddlyWiki5/commit/88812092fd8fa7da18e6da77f9c410338469cc4e) or just push a fix in another commit?

I think in a case like this we can just push a fix in another commit.
