### ISSUE TITLE
[BUG] ImportVariables does not reliably import $set widgets.

### ISSUE THREAD

**Issue by saqimtiaz** [Jermolene/TiddlyWiki5#6424]
`$importvariables` does not import variables defined by `$set` widgets in the following three examples of tiddlers to import from, only the macro in Example 2 and 3 are successfully imported: (Windows 10, Chrome 97, TW 5.2.1)

Example 1:
```
<$set name="a" value="alpha"></$set>
```

Example 2:
```
\define b() beta

<$set name="a" value="alpha"></$set>
```

Example 3:
```
\define b() beta

<$set name="a" value="alpha"><$set name="c" value="charlie"></$set></$set>
```

A quick peek at the code suggests the problem is that we parse the tiddler in block mode and not inline, the loop finds a `p` element and aborts variable collection:
https://github.com/Jermolene/TiddlyWiki5/blob/6452eb56a9c498cae4ebdb14278fae011a2d8485/core/modules/widgets/importvariables.js#L47-L50

After changing line 49 to the following, all three test cases from above are successful:

`var parser = widgetPointer.wiki.parseTiddler(title,{parseAsInline:true});`

**Comment by CodaCodr** [comment]
@saqimtiaz but wouldn't that completely change the scope of `a`?

```
<$set name=a ... >scope of a</$set>
```

Or am I missing where you're going with this?

**Comment by saqimtiaz** [comment]
@CodaCodr all three examples above are consistent with how the importing variables mechanism is supposed to work.

**Comment by CodaCodr** [comment]
That's quite astonishing, and not clear from the documentation for $set or $importvariables. Once $set is closed, `</$set>`, only its content has access to its name/value attrs. Nothing about $importvariables led me to think that $set is placed thus:

```
<$importvariables ...> <!-- $set, $set ... -->

stuff

<!-- /$set, /$set --> </$importvariables>
```

**Comment by saqimtiaz** [comment]
@CodaCodr I agree that the documentation is lacking and without documentation the behaviour can come across as unintuitive. However, this isn't the place for that discussion, recommend posting at [Talk](https://talk.tiddlywiki.org/t/documentation-tiddlers-on-tiddlywiki-com-in-need-of-work-please-contribute-to-the-list/1246/20) or creating a Github discussion.

**Comment by CodaCodr** [comment]
Taken at face value I agree, of course I do. And I appreciate you're asking of @Jermolene that a problem/bug be fixed. But in so doing, you raised something that, to me, ran counter to my understanding of how something (in this case, $set, or any scoped blocked) was supposed to work.

To me, that discussion (or the initial question at least) certainly belongs here.

But I'll back off and defer, now.

**Comment by Jermolene** [comment]
Hi @CodaCodr the importvariables widget processes each tiddler by extracting the first `<$set>` widget, plus any nested further `<$set>` widgets (the `\define` pragma is a shortcut for the `<$set>` widget). The process stops if it encounters any widgets other than `<$set>`. Then, the entire stack of `<$set>` widgets is copied into the body of the `<$importvariables>` widget, and the children of the the latter widget moved up to be within the deepest `<$set>` widget.

**Comment by CodaCodr** [comment]
> ... and the children of the the latter widget moved up to be within the deepest `<$set>` widget.

yep, much like my textual pictogram above. Got it. Thanks.
