### ISSUE TITLE
[IDEA] Show Templates and Big Transcluded Stylesheets as Code in tw5.com

### ISSUE THREAD

**Issue by kookma** [Jermolene/TiddlyWiki5#6444]
Now Tiddlywiki can customize tiddlers in view mode readily by Cascades. My suggestion is to display templates in core and tw5.com as code instead of rendering the text field. These tiddlers normally render in story river and display some ugly, lengthy stuffs.

Example

* https://tiddlywiki.com/prerelease/#%24%3A%2Feditions%2Ftw5.com%2Fdownload-empty
* $:/_tw5.com/CustomStoryTiddlerTemplateDemo/Styles
* $:/themes/tiddlywiki/vanilla/base

... complete the list

**Comment by Jermolene** [comment]
Thanks @kookma I've fixed up the tiddlers you've mentioned in the above commit. In those cases I think it makes more sense to use `code-body: yes` than a new cascade step.
