### ISSUE TITLE
[BUG] The Subtiddlers of Some Themes are Shown as Missing While They are There

### ISSUE THREAD

**Issue by kookma** [Jermolene/TiddlyWiki5#6448]
**Describe the bug**
Sone themes when are displayed, in Content tab, you see shadow tiddlers as missing

**To Reproduce**
1. Go to https://tiddlywiki.com/#%24%3A%2Fthemes%2Ftiddlywiki%2Ftight-heavier
2. Open the Content Tab
3. Look at $:/themes/tiddlywiki/tight-heavier/base
4. It is shown as missing tiddler

**Additional context**
1. I was experimenting with Gatha to create themes plugin
2. I saw for plugin-type: theme I have this issue
3. When I changed plugin-type to plugin, the issue disappears
4. I tested with manual plugin making, the issue is there

**Expected behavior**
Themes tiddlers (shadows) shall not be displayed as missing tiddler

**Screenshots**
![image](https://user-images.githubusercontent.com/830394/152678954-5fd1085d-d34e-432a-b84e-4bf75c255f27.png)

**TiddlyWiki Configuration (please complete the following information):**
 - Version [5.2.1
 
**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome 98

**Comment by kookma** [comment]
Further information:

1. I edited https://tiddlywiki.com/#%24%3A%2Fthemes%2Ftiddlywiki%2Ftight-heavier
2. I change plugin-type from theme to plugin
3. The issue is disappeared
![image](https://user-images.githubusercontent.com/830394/152679120-d57e2be7-9cb7-40bd-b12b-736fd6c97d22.png)

**Comment by Jermolene** [comment]
Hi @kookma themes (and languages) don't behave exactly like plain plugins. Only the theme or language plugins that are named in `$:/theme` or `$:/language` are unpacked to become shadow tiddlers; any other themes or languages remain as tiddlers but their shadow tiddlers are hidden.

**Comment by kookma** [comment]
Thank you for clarification!
