### ISSUE TITLE
Plugins tab should provide more management capabilities 

### ISSUE THREAD

**Issue by danielo515** [Jermolene/TiddlyWiki5#645]
Under the control panel you have a nice plugins tab where you can see the installed plugins. But that is all that you can do. I think a button to **delete or uninstall** a plugin will be easy to implement and useful in plugin management. 
It should provide also the option to just disable a plugin, but this requires more time and effort to make it possible.

**Comment by twMat** [comment]
IMO most of this thread is now outdated. While it would still make sense with a direct *delete* button next to each item in the plugin list, I say whoever feels the enough urge should post a new fresh issue or OP for it.
@danielo515 - close?

**Comment by Jermolene** [comment]
I think the most important part of the OP was implemented: to be able to disable plugins directly from within the control panel.
