### ISSUE TITLE
[IDEA] Make hooks support asynchronous functions

### ISSUE THREAD

**Issue by FSpark** [Jermolene/TiddlyWiki5#6454]
Hello,

When the handler function is an asynchronous function, for example if you want to execute an asynchronous function for uploading a large file to the server, the judgement condition here will fail because it cannot return a `true` immediately,  the return value is a `promise`.

https://github.com/Jermolene/TiddlyWiki5/blob/master/core/modules/wiki.js#L1448
```js
	// Give the hook a chance to process the drag
	if($tw.hooks.invokeHook("th-importing-file",{
		file: file,
		type: type,
		isBinary: isBinary,
		callback: callback
	}) !== true) {
		//default process
		this.readFileContent(file,type,isBinary,options.deserializer,callback);
	}
```

There are maybe also many more cases like this, so I'd like to ask if there is a way to improve it?

**Comment by Jermolene** [comment]
Hi @FSpark. Hooks are executed synchronously; it is not possible to substitute an asynchronous function for a synchronous function.

@saqimtiaz has done some work on image upload that will eventually be integrated into the core. The approach we've taken is to have a background daemon that watches out for the creation of images that are candidates for upload, and then does the uploading in the background, updating the tiddler in question with a `_canonical_uri` field aftwards.

**Comment by saqimtiaz** [comment]
@FSpark the work that Jeremy mentions in this area is available via the FileUploads plugin. This plugin is extensible and uses Uploader modules that add support for different backends to upload to. So if your actual use case is to upload large tiddlers as files to a server, you can write an Uploader module for the FileUploads plugin to accomplish your goal. Currently there are uploader modules available for Fission, Github, WebDAV, There is also a highly experimental node.js uploader module available for TiddlyWiki on node.js 

The intent is to introduce to the core a more generic version of this mechanism that can also accommodate other uses cases than just uploads.

**FileUploads plugin.**
Source code: https://github.com/saqimtiaz/tw5-file-uploads
More uploader modules: https://github.com/saqimtiaz/tw5-file-uploads-PUT
Plugin: https://saqimtiaz.github.io/tw5-file-uploads/
Discussion: https://talk.tiddlywiki.org/c/plugins/file-uploads/8

**Comment by FSpark** [comment]
@Jermolene @saqimtiaz  Thank you for your prompt and informative replies! I will give it a try!
