### ISSUE TITLE
[IDEA] extend tm-open-window with "top" and "left" parameters

### ISSUE THREAD

**Issue by saqimtiaz** [Jermolene/TiddlyWiki5#6455]
It would be useful to extend the `tm-open-window` widget message with optional parameters to provide the position of the newly opened window.

The underlying JavaScript method `window.open()` accepts an [optional top and left position](https://developer.mozilla.org/en-US/docs/Web/API/Window/open#position_and_size_features).

**Comment by Jermolene** [comment]
Thanks @saqimtiaz that makes sense; I can't quite think why we didn't include top/left from the start.
