### ISSUE TITLE
[BUG] drag and drop texts and strange behavior of list-links-draggable and list-tagged-draggable macros

### ISSUE THREAD

**Issue by kookma** [Jermolene/TiddlyWiki5#6456]
**Describe the bug**
On drag and drop texts to list-links-draggable and list-tagged-draggable a tiddler is created with the dragged text as ugly title

**To Reproduce**
1. Go to https://tiddlywiki.com
2. Open list-links-draggable Macro (Examples) tiddler
3. Click try it
3. Select a text and drag and drop on the droppable area
4. See strange tiddler created
5. repeat this on list-tagged-draggable Macro (Examples)

**Expected behavior**
Macros shall accept only dropped tiddlers not texts

**Comment by saqimtiaz** [comment]
@kookma Consider that there is a valid use case for dragging links to non-existent tiddlers to a `list-links draggable` macro, and there is no real means to determine whether the dropped text came from a link or not. Note that the tiddler is not created in your example, only a link to a missing tiddler.

I think for your use case with the Gatha plugin, you should consider using the droppable widget directly. Then you can accept only valid tiddler links, have a placeholder text etc. There is a good example in the core in the Open tab of the sidebar: https://github.com/Jermolene/TiddlyWiki5/blob/master/core/ui/SideBar/Open.tid

**Comment by saqimtiaz** [comment]
@kookma I do not think this is an actual bug and recommend that you consider closing the issue.
