### ISSUE TITLE
[BUG] MenuBar plugin: class specified in tiddler field not applied

### ISSUE THREAD

**Issue by saqimtiaz** [Jermolene/TiddlyWiki5#6457]
As reported by Emily on Discord, adding a field "class" to a menu item tiddler that specifies a dropdown does not add that class to the reveal widget created. As such it is not possible to create a sticky dropdown.

To recreate:
- on TiddlyWiki.com edit `$:/plugins/tiddlywiki/menubar/items/contents` and add a field "class" with value "tc-popup-keep"
- Click "Contents" in the top menubar and click on a link. The popup is not sticky.

The culprit seems to be assignment of the class via a filtered transclusion:
https://github.com/Jermolene/TiddlyWiki5/blob/5022516c614432f25dca2baf0c165a9256899a98/plugins/tiddlywiki/menubar/menu.tid#L58

Changing it to `class={{{ [<currentTiddler>get[class]] }}}` resolves the issue.

**Comment by Jermolene** [comment]
Thanks @saqimtiaz – ouch, that was cruft from an earlier version that used a separate tiddler for the dropdown.
