### ISSUE TITLE
[BUG] Link created by macro not recognized as a backlink on the target tiddler

### ISSUE THREAD

**Issue by khinsen** [Jermolene/TiddlyWiki5#6459]
**Describe the bug**

Internal links embedded in CSS styling are not recognized as backlinks on the target tiddler.

**To Reproduce**

1. Open a freshly downloaded `empty.html`.
2. Add an empty tiddler with title "B".
3. Add a tiddler with title "A" and contents:
```
\define macro(text)

$text$

\end

<<macro "[[B]]">>
```
4. Check the backlinks on tiddler "B": none are reported. The link is correctly displayed in "A" and works fine.

**Expected behavior**

I expect to see "A" in the list of backlinks to "B".

**Screenshots**

![tw-bug-report](https://user-images.githubusercontent.com/94934/153823693-e45238cd-ef73-480e-b6bb-9add602a218b.png)

**TiddlyWiki Configuration (please complete the following information):**
 - Version: v5.2.1
 - Saving mechanism: none / irrelevant
 - Plugins installed: none
 
**Desktop (please complete the following information):**
 - OS: Linux (Ubuntu 20.04)
 - Browser: Firefox
 - Version: 96.0

**Comment by khinsen** [comment]
Thanks @saqimtiaz for this pointer! That makes backlinks pretty much useless for me, given that I need to structure my tiddlers via macros and/or transclusions.

**Comment by pmario** [comment]
@khinsen I did create a plugin named: [uni-link](https://wikilabs.github.io/editions/uni-link/), which provides a way to define tiddler aliases and detects backlinks to them. 

It implements a new backlink tracking function, that finds an internally used macro named: `<<uni-link "target-title">>` which will create a hard-link. 

So if you need to do back-linking with macros you can use `<<uni-link "title">>` or `<<aka "alias">>` those macro are "trackable" by the backlink system.

**Comment by pmario** [comment]
uuups. ... I did a test using the `<<uni-link..>>` macro in an other macro doesn't work either. Sorry. .. Need to have a closer look, if it's possible to "track" it

**Comment by pmario** [comment]
The [relink plugin](https://flibbles.github.io/tw5-relink/) is able to handle that case. 

Create a tiddler eg: myMacro  with the content

```
\relink macro text:title 
\define macro(text)

[[$text$]]

\end
```

You can call it in any tiddler with `<<macro "title">>` and the tiddler info area will show the reference in the "Relink references" area.

The `relink` pragma is documented in the docs. ... The relinks plugin is a plugin that should be installed in every wiki anyway. It will help you a lot if you need to rename your tiddlers.

**Comment by khinsen** [comment]
Thanks @pmario ! Relink looks good, I'll check if it solves all my issues.
