### ISSUE TITLE
Tracking PRs for adding "whitespace trim" to core templates

### ISSUE THREAD

**Issue by Jermolene** [Jermolene/TiddlyWiki5#6474]
The following PRs comprise @flibbles's work to add "whitespace trim" to core templates:

* #6265
* #6257
* #6269
* #6270
* #6272
* #6275
* #6276 

There is currently a discussion over at #6270 that awaits resolution.

**Comment by pmario** [comment]
@Jermolene .. I think this one can be closed for the moment, since all of them have been merged now.

**Comment by flibbles** [comment]
Well actually, I've been meaning to ask this.

But I was only 1/3rd done. I originally thought I'd put forward that first batch, people would look it over and make sure nothing was objectionable. They'd merge it, and I'd move on to the next batch.

I didn't expect the process to take so long though. I can move on and start work on the next batch. It should be easier. I did the worst tiddlers first. Or I can just drop the matter.

**Comment by Jermolene** [comment]
Thank you @flibbles I think it's taken a long time because the rushed release of v5.2.1 came just as you working on them, and then I missed the chance to get them into v5.2.2, and again we ended up having to rush the release.

I'd be keen for you to continue if you are able. Ideally, we'll merge them as you do them.

**Comment by flibbles** [comment]
Here's another one: https://github.com/Jermolene/TiddlyWiki5/pull/6587

This is the only one. Do you want them one at a time, or in batches of 6-7 like last time?

**Comment by Jermolene** [comment]
Hi @flibbles

>  Do you want them one at a time, or in batches of 6-7 like last time?

Whatever is easiest for you; if the latter then it would be worth making another issue to track them like this.

**Comment by flibbles** [comment]
And another: https://github.com/Jermolene/TiddlyWiki5/pull/6600

Probably won't be more than 3 or 4 more actually. I'm closer to the end than I thought.

**Comment by flibbles** [comment]
And another:  Trim Saga: Advanced Search and actions #6604 

I think is this is actually the 2nd to the last.
