### ISSUE TITLE
[BUG] classList.add cause error when  isTiddlyWikiFakeDom

### ISSUE THREAD

**Issue by linonetwo** [Jermolene/TiddlyWiki5#6475]
**Describe the bug**

Uncaught TypeError: Cannot read properties of undefined (reading 'add')

```js
render(parent, nextSibling) {
      this.parentDomNode = parent;
      this.computeAttributes();
      const importButton = this.document.createElement('button');
      importButton.classList.add('tc-btn-invisible'); // < here
```

**To Reproduce**
1. Drag https://onetwo.ren/wiki/#%24%3A%2Fplugins%2Flinonetwo%2Fzx-script to tiddlywiki.com
2. Use "export as HTML" on any tiddler
3. my plugin uses recommended API `element.classList.add`, but it does not exist on an element with `isTiddlyWikiFakeDom`

**Expected behavior**

Hope `tiddlyWikiFakeDom` can have `classList` property.

I will find out where to add this `classList` property, but I need maintainer's confirm about if I should add this.

**TiddlyWiki Configuration (please complete the following information):**
 - Version 5.2.2 prerelease
 - Saving mechanism Node.js
 - Plugins installed https://onetwo.ren/wiki/#%24%3A%2Fplugins%2Flinonetwo%2Fzx-script
 
**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Chromium
 - Version Chromium Version: 98.0.4758.82

**Additional context**

I think `isTiddlyWikiFakeDom` will be used when some plugin runs on the nodejs side? Why exporting HTML will show this error on the browser console?

**Comment by saqimtiaz** [comment]
I recommend using  `$tw.utils.addClass` instead:
https://github.com/Jermolene/TiddlyWiki5/blob/4cf3df0f86aedbee950bb8a7ec7f7e7f7d5895db/core/modules/utils/dom/dom.js#L39-L45

The core does not have support for `element.classList`, presumably to maintain support for IE11.

**Comment by linonetwo** [comment]
Okay, I will have a try.

Maybe I need to add this to [https://github.com/tiddly-gittly/TW5-Typed](https://github.com/tiddly-gittly/TW5-Typed) so later new developers can know this.

**Comment by linonetwo** [comment]
Oh, I fall on this again... Maybe I should disable this method on dom's type.
