### ISSUE TITLE
[IDEA] Ability to propagate caught tm-navigate messages

### ISSUE THREAD

**Issue by yaisog** [Jermolene/TiddlyWiki5#6493]
When a `tm-navigate` message is caught by the `$linkcatcher` or `$messagecatcher` widget, there is no way to propagate that exact message up the widget tree after having performed any actions. This would be necessary to e.g. have tiddlers open at the correct position in the story, according to the user preferences `$:/config/Navigation/openLinkFromInsideRiver` and `$:/config/Navigation/openLinkFromOutsideRiver`.
- The `$action-navigate` can only pass `$to` and `$scroll` parameters, but all event properties available from `$messagecatcher`.
- `$action-sendmessage` cannot be used to send `tm-navigate` messages.
- The `stopPropagation` attribute of the `$eventcatcher` widget is not available for the other catchers.

Please enable one of these three ways to propagate the original `tm-navigate` message.
See also [https://talk.tiddlywiki.org/t/executing-actions-on-navigation-clicks/2530](https://talk.tiddlywiki.org/t/executing-actions-on-navigation-clicks/2530).
Yaisog

**Comment by saqimtiaz** [comment]
I think adding support for a `stopPropagation` attribute to `$messagecatcher` makes sense and would be consistent with `$eventcatcher`.

**Comment by Jermolene** [comment]
Hi @yaisog I've also run into the need to intercept navigation messages and have been laying the groundwork via some recent enhancements: in v5.2.1 we added support for the `list-event` and `list-event-paramObject` variables to the message catcher widget, and we added the `$names` and `$values` attributes to the `<$action-sendmessage>` widget. Together, those changes make it possible to intercept messages and pass along the provided parameters without knowing their names in advance.

There's more to do, but I'm not sure that adding a "stopPropagation" attribute to the message catcher is directly helpful.

The fundamental issue is that the `tm-navigate` message relies on some additional properties that are set directly on the event object, and are thus not accessible to wikitext: 

```
navigateTo navigateFromTitle navigateFromNode navigateFromClientRect navigateFromClientTop navigateFromClientLeft navigateFromClientWidth navigateFromClientRight navigateFromClientBottom navigateFromClientHeight navigateSuppressNavigation
```

So, I think the next thing we need to do may be to extend the `<$action-sendmessage>` widget to be able to set properties directly on the event object.

**Comment by BurningTreeC** [comment]
Hi all,

a quick hack in the `navigator` widget enabled the functionality for me:

```
/*
Handle a tm-navigate event
*/
NavigatorWidget.prototype.handleNavigateEvent = function(event) {
	if(!event.navigateTo && !event.navigateFromTitle && event.event && event.event.navigateTo && event.event.navigateFromTitle) {
		event = event.event;
	}
	event = $tw.hooks.invokeHook("th-navigating",event);
	if(event.navigateTo) {
		this.addToStory(event.navigateTo,event.navigateFromTitle);
		if(!event.navigateSuppressNavigation) {
			this.addToHistory(event.navigateTo,event.navigateFromClientRect);
		}
	}
	return false;
};
```

**Comment by BurningTreeC** [comment]
pardon, the code is the following:

```
/*
Handle a tm-navigate event
*/
NavigatorWidget.prototype.handleNavigateEvent = function(event) {
	if(!event.navigateTo && event.event && event.event.navigateTo && event.event.navigateFromTitle) {
		event = event.event;
	}
	event = $tw.hooks.invokeHook("th-navigating",event);
	if(event.navigateTo) {
		this.addToStory(event.navigateTo,event.navigateFromTitle);
		if(!event.navigateSuppressNavigation) {
			this.addToHistory(event.navigateTo,event.navigateFromClientRect);
		}
	}
	return false;
};
```

**Comment by saqimtiaz** [comment]
On further reflection I find myself in agreement with Jeremy. There isn't much value to be gained by adding a stop propagation attribute to the $messagecatcher widget. 

A typical use case will be only allowing a message to propagate if certain conditions in the event variables are met, for example a modifier key was used. This cannot be accommodated by a stop propagation attribute and instead requires that in wikitext the condition can be checked and the message re-sent if needed.

**Comment by yaisog** [comment]
Cleaning up...
