### ISSUE TITLE
[BUG] CSS is not applied in `<style>` blocks because of CamelCase autolink

### ISSUE THREAD

**Issue by twMat** [Jermolene/TiddlyWiki5#6514]
**Describe the bug**
I don't know if it is a *bug* or just an *issue* but it is annoying and inconsistent that styleblocks `<style>...</style>` don't work as intended for dynamic (wikibased) css. 

**To Reproduce**
1. Go to 'tiddlywiki.com' and close all tiddlers except HelloThere
2. Click + to create a new tiddler...
3. ...with the following content:<br><div>`<style>`<br>`div { border: 1px dotted red; }`<br>`
[data-tiddler-title="HelloThere"] {  border: 10px solid blue; }`<br>`</style>`</div>
4. ...and Save tid

**Result**: Only the red borders are applied.

**Expected**: Also the blue border should be applied, just as it successfully is if a `$:/tags/Stylesheet` is used in place of the `<style>` tags.

**Comment by saqimtiaz** [comment]
Is there a typo in your post? I don't see any part of the posted CSS that is dynamic.

The CSS that you did post above wont work because it is wikified and probably HelloThere becomes a link.
Try ~HelloThere or use a pragma like `\rules only transcludeinline macrodef macrocallinline html`

**Comment by twMat** [comment]
OH! - it is the default camelcase linkification spooking here also!? Thank you! (This relieves and explains the irregular behaviour for this over the years. In my own wikis I have autolinking disabled but from time to time test out stuff on tw.com)

But I find it surprising that `[data-tiddler-title="~HelloThere"]` works considering that `~HelloThere` is *not* the attribute value in `<div data-tiddler-title="HelloThere" ... >`

**Comment by saqimtiaz** [comment]
> But I find it surprising that `[data-tiddler-title="~HelloThere"]` works considering that `~HelloThere` is _not_ the attribute value in `<div data-tiddler-title="HelloThere" ... >`

Again, the CSS in a style tag in an open tiddler is wikified, so consider what is the resultant CSS after wikification.

`~HelloThere` becomes `HelloThere`

**Comment by saqimtiaz** [comment]
I use the term wikified here to meaning that the wikitext is processed. It is the same difference between using a macro in a tiddler body where its contents and any wikitext within is processed, as opposed to directly using in a widget attribute where the contents of the macro are used without any processing.

The same wikitext processing turns HelloThere into a link, and turns ~HelloThere into HelloThere.

**Comment by twMat** [comment]
Hm. I read your post and get what you're saying (thank you) *but* then how is the following explained. I can't tell if it is directly about the issue we're discussing or only related:

```
tags: $:/tags/Stylesheet
type: (default)
text: [data-tiddler-title="HelloThere"] { border: 10px solid blue; }
```
The above works, but this does not:

```
tags: (no tag)
type: (default)
text:
<style>
[data-tiddler-title="HelloThere"] { border: 10px solid blue; }
</style>
```
Maybe the mere fact that the `$:/tags/Stylesheet` is added makes the text wholly be literally interpreted and the CSS kicks in *before* it is wikified? (...if I use the term wikified correctly).

<hr>

...and what should be done to make the following work? I.e it successfully applies the style to both tiddler "Foo", "Foo Bar" but not to "FooBar" but it is not possible to apply `~`:

```
<style>
<$list filter="[prefix[Foo]]">
[data-tiddler-title='{{!!title}}'] { border: 10px solid blue; }
</$list>
</style>
```

**Comment by saqimtiaz** [comment]
> Maybe the mere fact that the `$:/tags/Stylesheet` is added,

The mechanism by which CSS is extracted from tiddlers tagged `$:/tags/Stylesheet` is completely different, which is also why the tiddler does not need to be open for the CSS to apply. 

Wikitext in the body of an open tiddler is processed, that is the key thing to understand.

**Comment by twMat** [comment]
Your help is much appreciated Saq and I learned valuable things. I'm posting a re-phrasal of the OP: #6516
