### ISSUE TITLE
[BUG] Take two: CSS is not applied in <style> blocks because of CamelCase autolink

### ISSUE THREAD

**Issue by twMat** [Jermolene/TiddlyWiki5#6516]
#6514 is basically the same question *but* I fuddled up things so it went off on tangents. To start clean I'm rephrasing the OP here. (Fellow @saqimtiaz patiently replied to several of my confusions - thank you! - and I'd be more than happy if Saq replied to this also but I don't want any individual to feel "pressured" only because they were kind enough to reply in the first place.)

[The problem is illustrated in this demo](https://styleblockissue.tiddlyhost.com/) - i.e in a styleblock the styling is not applied to CamelCase tiddlers and it is *not possible* to apply a prefixing `~` because the title is achieved from a filter.

What can be done, or is this a bug?

Thank you!

**Comment by saqimtiaz** [comment]
From my personal perspective, it is a limitation of using `<style>` tags in tiddlers that should be documented. I would personally go as far as saying that using style tags should be discouraged, but I understand that is very opinionated.

**Comment by saqimtiaz** [comment]
If you are determined to use style tags in tiddlers, you will find code below that will work. This approximates how stylesheet tiddlers work. Note however that I do not recommend this and all the usual caveats about using the wikify widget apply:
```
\define mystyles()
<$list filter="[prefix[Foo]]">
[data-tiddler-title='{{!!title}}'] { border: 10px solid blue; }
</$list>
\end

<$wikify text=<<mystyles>> output="text" name="styles">
<style>
<$text text=<<styles>>/>
</style>
</$wikify>

```

**Comment by twMat** [comment]
Thank you - appreciated!

>using style tags should be discouraged

I'd say it is (also outside of TW) but I have found several situations where it, to me, seems to be the only reasonable solution. One general case is if the listwidget construct above, i.e with the "data-attribute styling", is part of a bigger code context. 

> it is a limitation of using <style> tags in tiddlers that should be documented

[OT] I've understood html tags are really reconstructed in wikitext. So couldn't `<style>` be made to deal with this issue instead of accepting the limitation? Or a `<$style>` widget that allows to more freely create styleblocks? CSS is, after all, a central player in TW and the closeness with a styleblock is often superior to using separate stylesheets.

**Comment by saqimtiaz** [comment]
> [OT] I've understood html tags are really reconstructed in wikitext. So couldn't `<style>` be made to deal with this issue instead of accepting the limitation? Or a `<$style>` widget that allows to more freely create styleblocks? CSS is, after all, a central player in TW and the closeness with a styleblock is often superior to using separate stylesheets.

This is where the part about "the usual caveats about using the wikify widget" come in. Due to the nature of the task that wikifying does, it unavoidably leads to suboptimal performance. It does not from my perspective make sense to facilitate code patterns that have such consequences, we should instead direct users to alternative and better ways to achieve the same thing.

> I'd say it is (also outside of TW) but I have found several situations where it, to me, seems to be the only reasonable solution. One general case is if the listwidget construct above, i.e with the "data-attribute styling", is part of a bigger code context.

I use data-attribute styling extensively in my Streams and Notation plugins and have never had this issue. Can you pointout an actual real use case where you have run into this?

**Comment by pmario** [comment]
It's a bit tricky, but the code needs to look like this: 

```
<style>
<$list filter="[prefix[Foo]]">
<$set name=xTitle value={{{[all[current]addprefix["]addsuffix["]]}}}>
[data-tiddler-title=<$text text=<<xTitle>>/>] { border: 10px solid blue; }
</$set>
</$list>
</style>
```

**Comment by twMat** [comment]
Thank you both for your input!

```
...
<$set name=xTitle value={{{[all[current]addprefix["]addsuffix["]]}}}>
[data-tiddler-title=<$text text=<<xTitle>>/>] { border: 10px solid blue; }
...
```

So does this avoid the with expensive wikifywidget that @saqimtiaz refers to then? Is this a better solution, in that regard?

**Comment by pmario** [comment]
See the image. It works perfectly fine. 

![grafik](https://user-images.githubusercontent.com/374655/157275883-a3e49982-ba3c-4e04-b99b-8348c9a9f749.png)

**Comment by pmario** [comment]
>So does this avoid the with expensive wikifywidget (i.e wikification) that @saqimtiaz refers to then? Is this a better solution, in that regard?

Yes. There is no wikify widget. It needed a bit of "trickery" in the filter `<$set name=xTitle value={{{[all[current]addprefix["]addsuffix["]]}}}>` to be able to deal with tiddler titles with spaces. So the addprefix, -suffix deals with spaces in tiddler titles.

**Comment by pmario** [comment]
>@pmario just to clarify, the problem described in the OP only happens with using style tags. Hence my comment that use of style tags should be discouraged.

@saqimtiaz You are right. Mat's code works fine in a Stylesheet tiddler and it should be used that way. ... The TW stylesheet rendering mechanism takes care that `FooBar` is rendered as text only. 

@twMat TW themes use the following rules: `\rules only`

```
\rules only filteredtranscludeinline transcludeinline macrodef macrocallinline macrocallblock
```

So they don't have problems with titles like `FooBar` being rendered as TW-links. ... That's one more reason, why stylesheet tiddlers should always be used.

**Comment by CodaCodr** [comment]
> That's one more reason, why stylesheet tiddlers should always be used.

And another:

![image](https://user-images.githubusercontent.com/436812/157295466-f0ea24a1-83f6-499b-95b4-641c3a3062d5.png)

The blank line in the second `<style>` element blows it away completely.

**Comment by pmario** [comment]
@twMat ... Is this still an issue. If no pls close

**Comment by twMat** [comment]
Right, thanks. And thank you everyone for your input!
