### ISSUE TITLE
[BUG] nested list ast is difficult to use

### ISSUE THREAD

**Issue by linonetwo** [Jermolene/TiddlyWiki5#6527]
**Describe the bug**

Currently, in the screenshot is the ast of this wikitext

```
# AAA
## BBB
### CCC
```

<img width="343" alt="截屏2022-03-13 上午12 03 54" src="https://user-images.githubusercontent.com/3746270/158025389-672f3b20-4789-4d31-9f9f-63166fce92af.png">

The level2 `ol` is at the same level of the `AAA` text, making it difficult to use in WYSIWYG editor.

**To Reproduce**
1. Use webdevtool to inspect the dom
2. or `$tw.wiki.parseText('text/vnd.tiddlywiki', input).tree` will produce a similar json output

**Expected behavior**

I hope its dom structure can be like this, this is the result of `contentEditable` or slatejs:

<img width="404" alt="截屏2022-03-13 上午12 07 25" src="https://user-images.githubusercontent.com/3746270/158025502-ad9c7357-0a1a-4a29-bb96-38c802bf8d9f.png">

let level2 `ol` be with level1 `li`.

**TiddlyWiki Configuration (please complete the following information):**
 - Version 5.2.2-prerelease-2022-01-28
 - Saving mechanism Node.js

**Additional context**

I may do a ast transformation before I use it, but it will waste a lot of CPU to do so. Maybe I can modify the core parser, and I think there is no other plugin using this ast as mine does. 

---

I think the reason is

https://github.com/Jermolene/TiddlyWiki5/blob/3f0fb7163534290c490583016441f9fd004fab47/core/modules/parsers/wikiparser/rules/list.js#L100-L104

I'd like to ask is this mandatory? Can I change it?

Simply change it to `var prevListItem = listStack[t-1];` seems to do the trick.

<img width="317" alt="截屏2022-03-13 上午1 37 28" src="https://user-images.githubusercontent.com/3746270/158028581-dcaa0719-8dba-4136-866f-2aa2890c0c5b.png">

And the visual rendering is totally the same.

**Comment by CodaCodr** [comment]
I think TiddlyWiki is generating correct HTML. See under "Nesting lists" here:

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/ol

**Comment by pmario** [comment]
> I'd like to ask is this mandatory? Can I change it?

Have a closer look at the DOM structure that slatejs produces and the structure you propose. They are different. slatejs uses valid HTML code. The change you suggest would be invalid. ...

**Comment by linonetwo** [comment]
@pmario 

> DOM structure that slatejs produces and the structure you propose. They are different

I think they are the same

This is slatejs's dom

\<img width="404" alt="截屏2022-03-13 上午12 07 25" src="https://user-images.githubusercontent.com/3746270/158025502-ad9c7357-0a1a-4a29-bb96-38c802bf8d9f.png">

This is the dom after I modify the parser

\<img width="317" alt="截屏2022-03-13 上午1 37 28" src="https://user-images.githubusercontent.com/3746270/158028581-dcaa0719-8dba-4136-866f-2aa2890c0c5b.png">

**Comment by linonetwo** [comment]
@CodaCodr Thanks, I see, maybe I need to change how slatejs produce dom, this maybe a bit hard...

**Comment by linonetwo** [comment]
[https://www.npmjs.com/package/@prezly/slate-lists](https://www.npmjs.com/package/@prezly/slate-lists) generate the correct structure, but its algorithm is very complex, I will try to figure it out...
