### ISSUE TITLE
[IDEA] Separate global keyboard shortcuts from editor shortcuts

### ISSUE THREAD

**Issue by yaisog** [Jermolene/TiddlyWiki5#6529]
Since the shortcut mechanism "swallows" keystrokes, any key combination that could ever be typed into an editor cannot be used for global shortcuts, as the characters never make it into the text input. I'm thinking of using e.g.  `j`/`k` to jump between tiddlers or, similarly, single unmodified (no ctrl, alt, win) letters for quick access to sidebar tabs. If such shortcuts were defined, these letters could not be typed into an editor window any more.
Initially, I thought that removing any `stopPropagation`-like code could help, see
[https://talk.tiddlywiki.org/t/is-there-a-way-to-make-global-keyboard-shortcuts-propagate-to-the-editor/2516](url)
However, something like j/k would then still jump to the next tiddler, away from the one currently being edited. This is likely unwanted in all cases.
It would be great if the shortcut mechanism could be extended to separate global shortcuts that _don't_ fire when a (text) input is focused from editor shortcuts that _only_ fire when an input is focused. If this were to be configured via tags, it would be easy to make shortcuts work both globally and in-editor by assigning more than one tag.
Have a nice day
Yaisog

**Comment by Jermolene** [comment]
Hi @yaisog as you've discovered, the global shortcuts mechanism assumes that non-printable characters would be used as keyboard shortcuts. It would be worth exploring adding a flag so that selected keyboard shortcuts can be configured to be ignored when inside a text input.

**Comment by yaisog** [comment]
Cleaning up...
