### ISSUE TITLE
[BUG] Automatic tiddler creation for PascalCase words

### ISSUE THREAD

**Issue by nicolnt** [Jermolene/TiddlyWiki5#6532]
**Describe the bug**
TiddlyWiki automatically creates links to new tiddler that I don't need. It generally happens when I write chemical formulae in their empirical form, where there is PascalCase in the name

**To Reproduce**
1. Create or edit a tiddler
2. Write PascalCase text like "TestTest"
4. See link to a non-existing tiddler called "TestTest"

**Expected behavior**
Have no automatic tiddler link, because it creates false missing tiddlers

**Screenshots**
![image](https://user-images.githubusercontent.com/12377588/158578208-a46fcf9e-cbef-4d47-b2c8-49ded2f355d2.png)

**TiddlyWiki Configuration (please complete the following information):**
 - Version [v5.2.0]
 - Saving mechanism [Browser or TiddlyDesktop]
 - Plugins installed [TiddlyMap, KaTeX]
 
**Desktop (please complete the following information):**
 - OS: [Debian 11]
 - Browser [Firefox]

**Comment by saqimtiaz** [comment]
You can turn off the creation of links for CamelCase words locally or globally:
https://tiddlywiki.com/#CamelCase:CamelCase%20%5B%5BHow%20to%20turn%20off%20camel%20case%20linking%5D%5D

**Comment by nicolnt** [comment]
> You can turn off the creation of links for CamelCase words locally or globally: https://tiddlywiki.com/#CamelCase:CamelCase%20%5B%5BHow%20to%20turn%20off%20camel%20case%20linking%5D%5D

OK thanks!! Maybe the documentation should call it PascalCase to better find this setting
