### ISSUE TITLE
[IDEA] Dynannotate plugin: When a word is annotated (no prefix or suffix), all this words in tiddler are clickable

### ISSUE THREAD

**Issue by oflg** [Jermolene/TiddlyWiki5#6538]
**Is your feature request related to a problem? Please describe.**
Whichever of these words is annotated, only the first word in the tiddler is currently clickable.

**Describe the solution you'd like**
When a word is annotated (no prefix or suffix), all this words in tiddler are clickable.

**Additional context**
This is useful for annotating rudimentary words when reading tiddler.

**Comment by Jermolene** [comment]
Hi @oflg apologies, I missed this ticket. The request seems reasonable, though, is it something you no longer need?

**Comment by oflg** [comment]
Hi @Jermolene. It's okay.
I closed it because I saw that this issue had not been processed for a long time. I still need this feature to annotate words.
