### ISSUE TITLE
merging tiddlers

### ISSUE THREAD

**Issue by tgirod** [Jermolene/TiddlyWiki5#654]
Here is an idea for a merge procedure: rather than overwriting tiddlers with the same name during the import, we detect possible editing conflicts and let the user manage them manually.

We have a local and a remote file. Other users may be able to update the remote file, so editing conflicts may occur.

Each tiddler has a `hash` field, containing a hash of its content. This field is updated whenever the tiddler is saved. When a new tiddler is imported from remote, its hash is copied in a new field called `imported`. Next time it is imported, we can compare the values of `hash` and `imported` fields to detect 4 possible situations:
1. no local changes, no remote changes -> do nothing
2. no local changes, remote changes -> overwrite with the remote version
3. local changes, no remote changes -> discard the remote version
4. local changes, remote changes -> store the remote tiddler in a subtiddler `/merge`

To go further, the manual merge would benefit from a nice UI - something based on [jsdiflib](https://github.com/cemerick/jsdifflib) for example.

I would like to work on this, but my understanding of TW's architecture is a bit shallow ... I would love to get some pointers to start working on it. For example, where should I start digging in order to add the hash computation I'm describing ?

**Comment by pmario** [comment]
imo should be marked "feature request"

**Comment by tobibeer** [comment]
Also, it appers that @tgirod is speaking of those hashes as if they were datetime-stamps. Are they? Otherwise, how would you know wether the local or the "remote" hash was the one that changed?

Not sure if anything changed about this in the meantime, but I guess that's what is needed to be able to "compare, merge or discard"... actually on a field level, rather than a tiddler level:

> The obstacle to doing any of this at the moment is that TW5 doesn't currently have a way of expressing the desired user interface. We need a way to store the content from a pending import, and to reference it to build a UI that eg shows a selectable list of tiddlers with a snippet of their content.

**Comment by Jermolene** [comment]
I think this can be closed; there doesn't seem to be much iinterest in the merge feature in the core, and there's nothing to stop plugins experimenting with features like this.

**Comment by pmario** [comment]
The bundler plugin contains an extension, that gives more control with importing existing content. see: https://wikilabs.github.io/editions/bundler/
