### ISSUE TITLE
[IDEA] insertafter operator for symmetry with insertbefore

### ISSUE THREAD

**Issue by rmunn** [Jermolene/TiddlyWiki5#6551]
**Is your feature request related to a problem? Please describe.**
Most listops operators have a symmetrical counterpart: append and prepend, putafter and putbefore, and so on. But while there's an insertbefore operator, there's no insertafter operator.

**Describe the solution you'd like**
Create an insertafter operator whose behavior would mirror that of insertbefore: given a title in the list, it would insert its operand immediately after that title.

When insertbefore can't find the target title it's searching for, it inserts its operand at the end of the list. To mirror that behavior, insertafter would, if the target title is not found at all, insert its operand at the beginning of the list. This seems a bit counterintuitive, but the behavor of insertbefore is well-established (it was added in 5.1.14) so there's no changing it now.

**Describe alternatives you've considered**
The insertafter operator could insert its operand at the end of the list if its target is not found, which would feel more intuitive. But then that's the same behavor as the insertbefore operator, whereas the rest of insertafter is a mirror of insertbefore. It's impossible to change the insertbefore behavior at this point without breaking backwards compatibility, so I think having insertafter mirror insertbefore in all respects is the better alternative.

**Comment by pmario** [comment]
>...so I think having insertafter mirror insertbefore in all respects is the better alternative.

I don't think so. If it doesn't find the tiddler to put it "after" it should use the "end of the list". 

TW has the same behaviour for elements, that are not in the `list` field of a tag. If they are tagged, but not listed, they automatically are "sorted" to the end of the list. 

I think this default behaviour was used for "insertbefore" too. ... Which is counter intuitive. .. But as you wrote, we can't change that anymore. ..

If we add a new possibility, we can define the new behaviour to make sense. 

Some time ago I did create [a lot of tests](https://github.com/Jermolene/TiddlyWiki5/blob/master/editions/test/tiddlers/tests/test-filters.js#L708), to "document" the listops "status quo" ... 

So if we implement the new "insertafter" operator, we should write the tests first, to see, what makes sense. -- And then we can implement the functions until all tests become green.

**Comment by rmunn** [comment]
It certainly is more intuitive in isolation to have `insertafter` put something at the end if it doesn't find the element. It's just that then the symmetry with `insertbefore` is broken, which is slightly less intuitive if you're comparing the two operators.

Perhaps another approach could be to add a suffix to `insertbefore`, where if the suffix is present then it uses the sensible approach (insert at start) rather than the weird approach (insert at end). Hmmm, on second thought I don't like that one either. Ah well, sometimes you just have to live with the consequences of decisions made years ago.

> Some time ago I did create [a lot of tests](https://github.com/Jermolene/TiddlyWiki5/blob/master/editions/test/tiddlers/tests/test-filters.js#L708), to "document" the listops "status quo" ...
> 
> So if we implement the new "insertafter" operator, we should write the tests first, to see, what makes sense. -- And then we can implement the functions until all tests become green.

Very much agreed. Writing the tests first allows you to specify the behavior in a very well-defined way.

**Comment by pmario** [comment]
>Ah well, sometimes you just have to live with the consequences of decisions made years ago.

Yes. That's true ;)

**Comment by rmunn** [comment]
I was thinking the suffix couldn't be re-used. But if it can, then that's the perfect solution.

**Comment by Jermolene** [comment]
> I was thinking the suffix couldn't be re-used. But if it can, then that's the perfect solution.

I think it would be OK. The suffix need only be interpreted as a variable if there is a single operand present, otherwise it would be safe to use it for flags.

Other operators that support suffix-based flags treat the suffix as a comma delimited list of flags, and I guess at some point we might want to add case sensitivity flags.

**Comment by rmunn** [comment]
I've started working on this now that the indeterminate-checkboxes PR (#6593) is ready to merge. And I find I'm having a bit of trouble writing the documentation for the `start` and `end` suffixes for the `insertbefore` operator. Here's what I've produced so far; would someone like to recommend better phrasing?

```patch
diff --git a/editions/tw5.com/tiddlers/filters/insertbefore Operator.tid b/editions/tw5.com/tiddlers/filters/insertbefore Operator.tid
index c5cefe828..a60dc9140 100644
--- a/editions/tw5.com/tiddlers/filters/insertbefore Operator.tid       
+++ b/editions/tw5.com/tiddlers/filters/insertbefore Operator.tid       
@@ -5,7 +5,7 @@ op-input: a [[selection of titles|Title Selection]]
 op-output: the input tiddler list with the new entry inserted
 op-parameter: <<.from-version "5.2.2">> the <<.op insertbefore>> operator accepts 1 or 2 parameters, see below for details
 op-purpose: insert an item <<.place T>> into a list immediately before an item <<.place B>>
-op-suffix: (optional) the name of a variable containing the title of the tiddler before which this one should be inserted
+op-suffix: <<.from-version "5.2.3">> (optional) the name of a variable containing the title of the tiddler before which this one should be inserted
 tags: [[Filter Operators]] [[Order Operators]] [[Listops Operators]]
 title: insertbefore Operator
 type: text/vnd.tiddlywiki
@@ -14,15 +14,23 @@ type: text/vnd.tiddlywiki
 
 The <<.op insertbefore>> operator requires at least one parameter which specifies the title to insert into the input list. A second parameter can be used to specify the title before which the new title should be inserted.
 
+<<.from-version "5.2.3">>
+
+Using the suffix to specify <<.place B>>, the title before which the new title should be inserted, is deprecated. Instead, the two-parameter form is recommended. If the two-parameter form is used,
 the suffixes ''start'' and ''end'' can be used to specify where the item should be inserted if <<.place B>> is not found.
+
 `` `
-insertbefore:<before-title-variable>[<title>],[<before-title>]
+insertbefore:<before-title-variable>[<title>]
+insertbefore:<missing-location>[<title>],[<before-title>]
 `` `
 
 * ''title'' : a title <<.place T>> to insert in the input list.
 * ''before-title'' : (optional). Insert <<.place T>> before this title <<.place B>> in the input list.
 * ''before-title-variable'' : (optional). The name of a variable specifying <<.place B>> instead of the `before-title` parameter.
+* ''missing-location'' : (optional). Either `start` or `end`: where to insert <<.place T>> if <<.place B>> is not found in the list.
+
+If the item <<.place B>> isn't present in the input list then the new item is inserted at the end of the list. <<.from-version "5.2.3">> The suffixes ''start'' and ''end'' can be spedified to control where the new item is inserted when <<.place B>> is not found. The suffix ''end'' is the default, inserting the new item at the end of the list. The suffix ''start'' will cause the new item to be inserted at the start of the list when <<.place B>> is not found.
 
-If the item <<.place B>> isn't present in the input list then the new item is inserted at the end of the list.
+TODO: Work on this phrasing.
 
 <<.tip "Either [[parameter|Filter Parameter]] can be a string, a text reference or a variable">>
 ```

**Comment by rmunn** [comment]
Hmm, diff format doesn't work very well since it ends up putting paragraphs onto one long line that has to be scrolled. Here's the text I have written so far, without diff format (so you'll only see the text in its post-change state and not see the original):

<hr>

<<.from-version "5.2.2">>

The <<.op insertbefore>> operator requires at least one parameter which specifies the title to insert into the input list. A second parameter can be used to specify the title before which the new title should be inserted.

<<.from-version "5.2.3">>

Using the suffix to specify <<.place B>>, the title before which the new title should be inserted, is deprecated. Instead, the two-parameter form is recommended. If the two-parameter form is used, the suffixes ''start'' and ''end'' can be used to specify where the item should be inserted if <<.place B>> is not found.

```
insertbefore:<before-title-variable>[<title>]
insertbefore:<missing-location>[<title>],[<before-title>]
```

* ''title'' : a title <<.place T>> to insert in the input list.
* ''before-title'' : (optional). Insert <<.place T>> before this title <<.place B>> in the input list.
* ''before-title-variable'' : (optional). The name of a variable specifying <<.place B>> instead of the `before-title` parameter.
* ''missing-location'' : (optional). Either `start` or `end`: where to insert <<.place T>> if <<.place B>> is not found in the list.

If the item <<.place B>> isn't present in the input list then the new item is inserted at the end of the list. <<.from-version "5.2.3">> The suffixes ''start'' and ''end'' can be spedified to control where the new item is inserted when <<.place B>> is not found. The suffix ''end'' is the default, inserting the new item at the end of the list. The suffix ''start'' will cause the new item to be inserted at the start of the list when <<.place B>> is not found.

TODO: Work on this phrasing.

<<.tip "Either [[parameter|Filter Parameter]] can be a string, a text reference or a variable">>

<<.tip "If <<.place B>> is specified as both a suffix and a parameter, the parameter takes precedence">>

<<.operator-examples "insertbefore">>

**Comment by Jermolene** [comment]
Hi @rmunn thanks for your patience. I think your draft is not bad; any further issues can be resolved as we work through the pR.

**Comment by AnthonyMuscio** [comment]
Bump.

It looks as if this can progress, who knows what next?

This came up here https://talk.tiddlywiki.org/t/how-to-insert-a-title-in-a-tag-list-before-something-without-tagging-that-title/3809?u=tw_tones

By the way if it were helpful in the case of both insertbefore and insertafter if the item is missing it simply cannot be placed before or after it, perhaps the item is yet to be added to the list I don't think front or back of list is implied. Arguably they could both do nothing. 

If we had a simple operator to test any "given title" is in the "list of titles" - ie we can test if the marker exists before inserting before or after we would be better off.

The contains operators seems appropriate on the surface however it says "filter the input by searching list fields for a value", ie only lists in field not input titles.

**Comment by pmario** [comment]
>The contains operators seems appropriate on the surface however it says "filter the input by searching list fields for a value", ie only lists in fields not input titles.

try match: `a b c d +[match[a]] `
