### ISSUE TITLE
[Idea] Make Import mechanism check if title exists for all imports

### ISSUE THREAD

**Issue by twMat** [Jermolene/TiddlyWiki5#6559]
Pasting multiple *texts* from the clipboard makes the import mechanism propose the titles `Untitled`, `Untitled 1`, `Untitled 2` ...
*...but...*
Pasting multiple *images* from the clipboard makes the import mechanism propose the titles `image.png`, `image.png`, `image.png` .... i.e there is no enumeration/differentiation.

This burdens the user to rename the title or/and even risks causing unintentional overwrites of tiddlers that can be next to impossible to detect afterwards. I don't know if the problem is limited to images only. 

**Proposal**: Evidently, the import mechanism *can* access the "enumeration mechanism" so I propose this is done consistently for all clipboard imports.

**Comment by saqimtiaz** [comment]
This is most definitely not a bug, though I grant the user experience could be better. That said, it isn't particularly straight forward to figure out how that would come about.

The browser supplies the filename `image.png` (or a localized version thereof) for every image pasted from the clipboard depending on the browser/operating system language. 
At this point there is no way for TiddlyWiki to know if a real file with name `image.png` is to be imported, or that the filename has been created by the browser. In comparison when we paste text, the browser does not offer a filename to go with it so TiddlyWiki creates ones.

There is also discussion around this in #6517. I have explored possibilities towards improving the user experience in the core but have not come up with a satisfactory path yet.

**Comment by twMat** [comment]
>This is most definitely not a bug,

OK, I removed the [bug] label in the title and also edited it to propose that the Import mechanism simply(?) checks if a tiddler with the title already exists... and if it does then just add enumeration to it. Is this also problematic? Why would TW need to accept the "browser offered" title *as is*?

**Comment by saqimtiaz** [comment]
> Why would TW need to accept the "browser offered" title _as is_?

There is no way to know if the title is one that the user would want to keep or not. Most users would not want files they are importing from their operating system to have their filenames changed.

> propose that the Import mechanism simply(?) checks if a tiddler with the title already exists... and if it does then just add enumeration to it.

This sounds like a more generic import option to always create unique titles for tiddlers being imported, regardless of whether they originate from a paste or drag and drop event. If this is what you have in mind, I would highly recommend closing this issue and creating a new one for clarity. This is an option that has had some discussion and has its own share of challenges but an issue to discuss it properly would be welcome.

**Comment by twMat** [comment]
>This sounds like a more generic import option to always create unique titles for tiddlers being imported, regardless of whether they originate from a paste or drag and drop event. If this is what you have in mind, I would highly recommend closing this issue and creating a new one for clarity. 

Thank you. Done - #6560
Closing.
