### ISSUE TITLE
[IDEA] Checkboxes can be in an "indeterminate" state

### ISSUE THREAD

**Issue by rmunn** [Jermolene/TiddlyWiki5#6564]
**Is your feature request related to a problem? Please describe.**
In https://github.com/Jermolene/TiddlyWiki5/pull/6561#issuecomment-1080122266 I made the decision that #6561 will not allow checkboxes to be in an "indeterminate" state, and that that feature will live in a different PR. This issue is to track that feature; I'll discuss my planned design of the `indeterminate` attribute here, then create a new PR with that implementation once the design has settled.

**Describe the solution you'd like**
The checkbox widget will grow a new `indeterminate` attribute. If that attribute is present and has a non-empty value, then the checkbox can be in [an indeterminate state](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/checkbox#indeterminate_state_checkboxes). If the attribute is absent, or is present but its value is the empty string, then the checkbox can only be true (checked) or false (unchecked).

The rules for indeterminate checkboxes are as follows:
* If the `indeterminate` attribute is present, *and* the `checked` and `unchecked` attributes are both present, *and* the value the checkbox is looking at (whether that's a `field`, an `index`, a `listField`, a `listIndex`, or a `filter` result) contains neither the `checked` nor `unchecked` value, then the checkbox will be indeterminate.
* Under *any other conditions*, the checkbox will have a determinate value, either checked or unchecked.

Note that TW's way of handling "bare" attributes (attributes with no equal sign) is to assign them the value of `"true"` (a string containing the letters "t", "r", "u", "e"). That means that `<$checkbox indeterminate checked="yes" unchecked="no">` would enable the indeterminate feature.

Note also that the value of the `indeterminate` attribute is **ignored** other than being checked for a non-empty string. That means that if you have `<$checkbox indeterminate checked="yes" unchecked="no">`, which is equivalent to `<$checkbox indeterminate="true" checked="yes" unchecked="no">`, then a value of `"maybe"` will set the checkbox to the indeterminate state. (As would any value other than `"yes"` or `"no"`). The reason for that is to make it easy to assign the result of a filter to the `indeterminate` attribute using `{{{ [filter-expression] }}}` syntax. There's already plenty of precedent in filters for interpreting an empty value as "false" and a non-empty value as "true", such as the behavior of the `else` operator. So I've decided that the `indeterminate` attribute on checkbox widgets should function the same way.

**Describe alternatives you've considered**
In #6561, I considered making `indeterminate` a feature of list mode and filter mode *only*, but ended up deciding to allow people to create indeterminate checkboxes in single-value mode as well. The only way to do that safely, without changing the behavior of existing wikis where people *will not* be expecting indeterminate values, is to make it an opt-in attribute. The fact that it will also simplify logic like the "sub-task 1 / sub-task 2" example in https://github.com/Jermolene/TiddlyWiki5/pull/6561#issuecomment-1080122266 (the most common reason for wanting indeterminate checkboxes) is a nice bonus.

**Comment by pmario** [comment]
a) The checkbox widget has a `default` value, to avoid the intermediate state. ... So from my point of view as soon as default is set it takes precedence. 

b) There are some more questions, which have to be answered. What happens if the state is intermediate and the user clicks the checkbox. There are 2 possibilities: check or uncheck is the next state ... This has to be defined somewhere, because the widget also have "checkactions" and "uncheckactions", which will be triggered, in the one way or the other.

The point I want to make is: Do we really need it? The MDN docs says: 

>There are not many use cases for this property. The most common is when a checkbox is available that "owns" a number of sub-options ...

The usecase mentioned at MDN also has the problem, that I mentioned in b) .. What happens, if I click the undefined checkbox. 

From my point of view, the intermediate parameter increases the complexity of the widget code, with no real win. ... At least I can't see it.

**Comment by rmunn** [comment]
a) Default is documented (and implemented) to be used if the field is empty (or doesn't exist). If the widget has `checked="yes" unchecked="no"` and the field contains `orange` then the `default` attribute won't be used. There, the current behavior is to have the checkbox be unchecked, because if nothing matches then the code defaults to `false` in the `getValue` function. My intent is to keep that exactly the same, *unless* the user opts-in by using the `indeterminate` attribute. So `default`, if used, would still keep its current behavior.

b) If the state is indeterminate, the checkbox value is treated as false, and checking will make it checked and run `checkactions`. That's not in the documentation yet, but it's got documentation-as-unit-tests in the code of PR #6561 (until I remove that part) to make sure that happens. That's consistent with how indeterminate checkboxes are treated in every example I found: clicking on an indeterminate checkbox turns it true (checked). I plan to include examples in the TW documentation to show how to make a three-way checkbox that can go from unchecked to indeterminate to checked (and then to unchecked again, completing the loop), and another example that shows the behavior of the "sub-task 1 / sub-task 2" example.

**Comment by rmunn** [comment]
> The usecase mentioned at MDN also has the problem, that I mentioned in b) .. What happens, if I click the undefined checkbox.

Their example doesn't show this happening, but https://css-tricks.com/indeterminate-checkboxes/, where they got it from, does show that. Interact with those examples and you'll see that clicking on an indeterminate checkbox makes it checked (true), and also triggers the same actions that would be triggered by going from false (unchecked) to true (checked). Scroll down to the example that has a "Giants" category containing "Andre" and "Paul Bunyan" and you can see that in action. I propose that the TW indeterminate checkboxes work exactly like that example: checking an indeterminate checkbox will turn it checked and trigger `checkactions`, if present. (And any click will trigger `actions` as usual).

**Comment by pmario** [comment]
I could live with that.
