### ISSUE TITLE
[BUG] Commit adcef4f8 breaks node.js

### ISSUE THREAD

**Issue by FlashSystems** [Jermolene/TiddlyWiki5#6579]
After commit adcef4f803ba84f6bfb47f4117eb7ccb50d8b9fb the call `node tiddlywiki.js` does not create any output. Creating a new wiki via `--build index` does not create any output file. The TW5 server was not tested.

**To Reproduce**
1. Check out the current master.
2. Switch into the TiddlyWiki5 directory.
3. Type `node tiddlywiki.js`.
4. Observe no output.

**Expected behavior**
`node tiddlywiki.js` should output usage information.

**TiddlyWiki Configuration**
 - Current master (commit ff42a9e4d44e659931372d4109852d266a18f82c) on node.js 17.8.0
 
**Additional context**
Bisecting shows that commit adcef4f803ba84f6bfb47f4117eb7ccb50d8b9fb is the culprit. After reverting this commit, the help output is displayed again and `--build index` creates the correct output file.

**Comment by Jermolene** [comment]
Thanks @FlashSystems. It appears that the fix in #4122 is not quite right, fix coming up.
