### ISSUE TITLE
[BUG] pasting content from a webpage creates 2 elements in the "paste" event, TW dropzone overwrites the first one

### ISSUE THREAD

**Issue by pmario** [Jermolene/TiddlyWiki5#6592]
I did just implement a simple "rename Untitled" function and found an issue. The paste-event actually contains 2 elements. The first one is a `text/html` snippet and the second one is "text/plain" ... 

Since the default import handler in TW uses the "Untiltled" name for both elements the "text/plain" elements wins. ... That's what we expected. .. So the issue didn't come up. 

Now I do rename Untitled it looks as shown in the screenshot. ... The first element is an HTML snippet and the second one is text. 

I think, since we actually want the `text/plain` representation the "dropzone" paste-handler should throw the `text/html` representation away. ... BUT I'm not sure.

@Jermolene @saqimtiaz ... What do you think?

![image](https://user-images.githubusercontent.com/374655/161608034-d9093a52-a233-44bf-8e6e-8eb99c75fbfe.png)

**Comment by saqimtiaz** [comment]
Do note that this isn't specific to pasting text, copying an image in the browser and pasting it also results in two elements being imported, the HTML fragment and the image. The dropzone in the texteditor doesn't exhibit this since it accepts only specific content types. The default global dropzone does exhibit this behaviour.

> I think, since we actually want the `text/plain` representation the "dropzone" paste-handler should throw the `text/html` representation away. ... BUT I'm not sure.

The tricky thing is, what happens if we are copying rendered HTML? Can we be sure that there is consistency amongst browsers and that we can always ignore `text/html` in the presence of `text/plain`, and that there is no scenario where the `text/html` might be useful??

**Comment by pmario** [comment]
> .. and that there is no scenario where the text/html might be useful??

Oh, it is useful. We can convert HTML to wikitext. eg. If the fragment contains an H1 element, we could create a wikitext `! element` and so on. But other than that, I think it's junk, **if** there is a text/plain version.

Especially for the function I want to implement, where I would like to convert a `dot tid` like text into a real tiddler, instead of importing plain text.

**Comment by pmario** [comment]
>.. The tricky thing is, what happens if we are copying rendered HTML?

I'll need to have a closer look, but I think it already works, since we didn't have a problem till now. The issue was always there, we just didn't see it.

**Comment by pmario** [comment]
>The tricky thing is, what happens if we are copying rendered HTML?

As expected. There are 2 versions the HTML snippet contains HTML-encoded chars for `< and >` and the text/plain contains the text only. ... 

So using text/plain only would be an option for now, since it doesn't alter the existing behaviour. ... BUT for a second step we could think about a possibility to use the text/html version for further processing in plugins.

**Comment by saqimtiaz** [comment]
Note that Chrome and Firefox already have inconsistent handling of pasting text copy from a website into TiddlyWiki.

Firefox imports it as plain text, Chrome imports it as HTML. So any changes are going to be a break in current behaviour for users of at least one browser.

**Comment by pmario** [comment]
>All of the following will need be to be tested (and this is why working on anything drag and drop related is so painful):

I think we can easily fix this. From my tests I know, that Edge and FireFox get the same info from the drop event. It only seems, that the order in the array is different. 

That's why Edge imports test/html and FF imports text/plain. ... 

>Furthermore if we are making any changes to address this we need to also consider the same for image imports.

Yea, that's why I'm investigating a different possibility. I want to let the plugin author decide, what to do. So the dropzone.js will only need to pass on the `type` info to the import-mechanism. 

The import mechanism can then decide what to do. ...

**Comment by pmario** [comment]
@saqimtiaz ... How do you copy / paste with Chrome on Android into the main "import dropzone" ... I only can paste from clipboard to a text element.

Copying from Chrome on Android to FireFox in split-screen isn't allowed on my phone. I do get a "no parking" sign as soon as I enter the FF app area.

**Comment by joshuafontany** [comment]
Following along, I remember my phone akways prompts a dialog if it has multiple clipboard entries & allows me to pick the one to paste. This would be seperate from $:/Import so you could build up an Import with multiple copy/pastes.

**Comment by pmario** [comment]
@joshuafontany ... That's probably a "special app". Which phone, which Android version do you use with this functions?

**Comment by joshuafontany** [comment]
Samsung Galaxy S9, and yeah it looks to be a custom Clipboard app (makes more sense that it only triggers the popup in certain contexts). Still, I think anytime a clipboard has an array of entries, it should be user choice which ones to "paste".

**Comment by pmario** [comment]
Closing this one since we did fix it -- We show both of them and let the user decide.
