### ISSUE TITLE
[IDEA] action-setfield should have a parameter, that forces "sync" when "dirty" is triggered. 

### ISSUE THREAD

**Issue by pmario** [Jermolene/TiddlyWiki5#6601]
The action-setfield widget doesn't trigger the wiki "sync" function, if fields are changed, but it triggers the "dirty" state

It would be nice to have a new parameter eg: `force-save` if the field value changed. If `force-save=yes` should trigger sync, as soon as the action triggers the wiki "dirty" state too 

To reproduce: 

- Download empty.html
- create new tiddler
- paste the code below
- click the button
- Have a look at the recent tab. The `application/json` tiddler is created

```
\define createName()$(currentTiddler)$.links

\define createTags()[[$(currentTiddler)$]] links

\define createContainerAction()
<$action-setfield $tiddler=<<createName>> tags=<<createTags>> type="application/json"/>
\end

\define createLinksTiddler()
<$button actions=<<createContainerAction>> tooltip="Create List" class="wltc-btn-big-green tc-btn-big-green">Create Links Container!
</$button>
\end

<<createLinksTiddler>>
```

**Comment by Jermolene** [comment]
Hi @pmario 

> The action-setfield widget doesn't trigger the wiki "sync" function, if fields are changed, but it triggers the "dirty" state

The action-setfield widget doesn't do anything special, it just calls `wiki.addTiddler()`.

Therefore, I'm not sure what you mean by it not triggering a sync but is triggering the dirty state. The two things are defined by separate filters that are slightly different.

Could you provide an example of something that doesn't work as expected?

**Comment by pmario** [comment]
>..Could you provide an example of something that doesn't work as expected?

I'll have to run more tests. But I have a wiki, that uses webdav put saver and if I modify a field, it triggers the dirty state but doesn't save. Creating a new tiddler does trigger the save mechanism

**Comment by pmario** [comment]
@Jermolene ... I did update the OP with some test code

**Comment by Jermolene** [comment]
Hi @pmario I followed the steps but I don't understand what I'm looking for. It looks like the tiddler is created as expected.

**Comment by pmario** [comment]
Yes, but the wiki is not autosaved

**Comment by pmario** [comment]
I think the problem is here: 

https://github.com/Jermolene/TiddlyWiki5/blob/e28af8d5943e9eab025659ccbfe1e8e546358096/core/modules/saver-handler.js#L57

self.numChanges is detected, but the `if(self.pendingAutoSave && self.wiki.getSizeOfTiddlerEventQueue() === 0)` doesn't trigger since .pendingAutoSave isn't set and .numChanges isn't part of the if clause. 

self.updateDirtyStatus() is done in the right way

**Comment by pmario** [comment]
hmmm, I think it's not possible to fix it in a backwards compatible way. ... May be I have to trigger a `tm-auto-save-wiki` instead, which also will be more flexible.

**Comment by Jermolene** [comment]
Ah I understand now – that's correct, autosaves have to be triggered explicitly with tm-auto-save-wiki, it isn't enough to simply modify some tiddlers.
