### ISSUE TITLE
[BUG] utils.formatDateString always return now

### ISSUE THREAD

**Issue by linonetwo** [Jermolene/TiddlyWiki5#6614]
**Describe the bug**

```js
> temp0[0].fields.created
Date Fri Aug 30 2013 16:42:00 GMT+0800

> $tw.utils.formatDateString(temp0[0].fields.created, "[UTC]YYYY0MM0DD0hh0mm0ssXXX")
"20220409165524954"
```

**To Reproduce**
1. Go to tiddlywiki.com
2. in console
3. type `$tw.utils.formatDateString(new Date('Fri Aug 30 2013 16:42:00 GMT+0800 (中国标准时间)'), "[UTC]YYYY0MM0DD0hh0mm0ssXXX")`
4. See `"20220409165524954"`

**Expected behavior**

Should be `2013xxxx`

**TiddlyWiki Configuration (please complete the following information):**
 - Version 5.2.2
 
**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Firefox
 - Version 100

**Additional context**

I'm developing a saver from HTML to nodejs, and I found all changed tiddler changed their created time to now by https://github.com/tiddly-gittly/tw-mobile-sync/blob/92038618aab1df072d4d9b9031812186000b41ae/src/browser-background-sync.ts#L202-L210 as described in https://talk.tiddlywiki.org/t/can-i-use-two-sync-method-together-to-sync-between-mobile-and-desktop/2813/2

**Comment by saqimtiaz** [comment]
Ouch. I actually remember discovering the same problem in late 2021 but I forgot to file a bug!

If I remember correctly the problem is specific to the UTC handling for the format [UTC]YYYY0MM0DD0hh0mm0ssXXX:
https://github.com/Jermolene/TiddlyWiki5/blob/56dae9042576d7af99ce3e68ca8b2b9fb25617d4/core/modules/utils/utils.js#L449-L454

**Comment by linonetwo** [comment]
Let me fix this...I went to bed last night after I fired this issue

**Comment by linonetwo** [comment]
And seems I can directly use \`$tw.utils._stringifyDate\`..._
