### ISSUE TITLE
[BUG] Drag and drop does not work in mobile Chrome

### ISSUE THREAD

**Issue by saqimtiaz** [Jermolene/TiddlyWiki5#6617]
Drag and drop in mobile Chrome does not work in Chrome 100.0.4896.79 on Android. However, it did work at least as recently as  Chrome 99.0.4844.88.

The `dragstart` event fires but after that no drag related events are fired (`dragenter`, `dragover`, `dragleave`, `dragend`).
I have verified that this is due to the fact that we set a data URI as the value of the `URL` data transfer format in our `dragstart` event handler:

https://github.com/Jermolene/TiddlyWiki5/blob/73138b79aaaafa32b3a0abf8ba80c96eb3a18d56/core/modules/utils/dom/dragndrop.js#L105

Commenting out this line or removing the `data:` prefix from the value assigned restores functionality.

There is a [similar bug](https://bugs.chromium.org/p/chromium/issues/detail?id=1293803) filed for Chrome on Android two months ago which describes any MIME type other than `text/plain` causing the exact same problem with drag and drop. 

Before we report this as a new or related bug, we should confirm that the specifications for the `URL` data transfer format/MIME type do not prohibit the `data:` prefix. In particular see items 6 and 9 in the specs for `getData` at https://html.spec.whatwg.org/multipage/dnd.html#dom-datatransfer-getdata and [RFC2483](https://datatracker.ietf.org/doc/html/rfc2483) for parsing `text/uri-list` data.

**Comment by Jermolene** [comment]
Thanks @saqimtiaz. It hadn't occurred to me that data URIs could be a problem in this context, but it does seem plausible.

**Comment by saqimtiaz** [comment]
It seems to be the combination of the `URL` MIME type and data URIs that cause problems.

For example the following usage of a data URI in the Chrome specific `DownloadURL` type works and allows dragging a link from the browser to the desktop as a JSON file containing the tiddler:
```
dataTransfer.setData("DownloadURL","application/json:tiddlers.json:data:application/json," + encodeURIComponent(jsonData));
```
