### ISSUE TITLE
[BUG] $Import preview pane in Edge looks different than the one in FF

### ISSUE THREAD

**Issue by pmario** [Jermolene/TiddlyWiki5#6620]
I think we need to adjust some CSS for Edge. I did test it with Edge 100 and 101 beta

![image](https://user-images.githubusercontent.com/374655/162716685-6ffad06d-c259-4a6e-b64e-b924ef46dc0b.png)

**Comment by saqimtiaz** [comment]
The problem is worse than a visual artifact. Firefox is importing the pasted context as plain text, Chrome imports it as HTML and therefore it is rendered in an iframe.

**Comment by pmario** [comment]
I found the problem. It's a bug in the code. PR incoming

**Comment by pmario** [comment]
I now know where it comes from .. so close it
