### ISSUE TITLE
[IDEA] $transclude with selector attribute

### ISSUE THREAD

**Issue by CodaCodr** [Jermolene/TiddlyWiki5#6630]
Wondering if `$transclude` could be extended to include a new attribute `selector`.

```
<$transclude tiddler=my-tiddler selector="span.my-class" />

<$transclude tiddler=my-tiddler selector="my-made-up-tag" />
```
The above assumes field=text though I guess any field is a possibility.

The proposal would allow a finer-grained slice and dice approach to transclusion. Plus, since `selector` is already in use elsewhere, the basic idea seems to be easily explained doc-wise.

_Prior history (if not "art")_ : I've implemented this in wikitext, but the macros are hardly what I'd call lightweight (if not outright cumbersome) and the prerequisites to using them (loading the target tiddler, slicing with regex filters) is not exactly easy reading -- a core addition would make a huge difference.

Thoughts?

**Comment by Jermolene** [comment]
Hi @CodaCodr I think that to do that the transclude widget would have to render the entire tiddler to a temporary DOM area, and then select out the DOM subtree corresponding to the selector, and then somehow splice that back into the real DOM tree.

The underlying trouble is that transclusion is a purely widget tree operation, and doesn't directly affect the DOM.

**Comment by CodaCodr** [comment]
Yes, the detail is what I'd imagined.

Okay, closing.
