### ISSUE TITLE
[ISSUE] probably a \parameters pragma parsing problem

### ISSUE THREAD

**Issue by pmario** [Jermolene/TiddlyWiki5#6672]
To reproduce:

```
title: test-template-a-b-c

{{template-a-b-c|x|y|z}}
{{template-a-b-c}}
```

```
title: template-a-b-c

\parameters (a:a, b:b, c:c)

<<a>> - <<b>> - <<c>>
```

result: 

![image](https://user-images.githubusercontent.com/374655/166225537-545c813d-8ac5-4784-bd18-cfafd0ae9d28.png)

**Comment by pmario** [comment]
related to: [Parameterised transclusions](https://github.com/Jermolene/TiddlyWiki5/pull/6666#)
#6666

**Comment by pmario** [comment]
As a user I would like to be allowed, to make the params pragma readable.

**Comment by Jermolene** [comment]
Thanks @pmario this is a bug whereby the comma is being parsed as part of the unquoted parameter value
