### ISSUE TITLE
[BUG] parameterized transclusion inconsisten output

### ISSUE THREAD

**Issue by pmario** [Jermolene/TiddlyWiki5#6673]
related to: Parameterised transclusions #6666

Input

```
title: template-a-b-c

\parameters (a:a,  b:b, c: "text with spaces")

<<a>> - <<b>> - <<c>>
```

These shortcuts produce a strange output

```
{{template-a-b-c|""""""|m|n}}

{{template-a-b-c|""|m|n}}

{{template-a-b-c|''|m|n}}
```

![image](https://user-images.githubusercontent.com/374655/166228342-db48fb39-35ca-4a6b-91e9-2ad57953afc9.png)

**Comment by pmario** [comment]
I do have the feeling, that positional syntax will be very errorprone. ... Is there some code for **named params** already?

**Comment by Jermolene** [comment]
Hi @pmario I don't think those issues have anything to do with positional parameters. All that's happening here is that you are passing various kinds of quotes as a parameter, and in each case they are being rendered exactly as the docs suggest:

* Six double quotes are interpreted as a pair of triple quotes. In wikitext the text inside such quotes is rendered raw; here there is no text between the quotes so nothing is rendered
* Two double quotes have no special meaning in wikitext and so are rendered raw
* Two single quotes are interpreted as the start of bold text. Again, there's no text to be bold

Looking at the HTML output of your example provides more of a clue as to what is going on:

```
<p> - m - n</p><p>"" - m - n</p><p><strong></strong> - m - n</p>
```

**Comment by Jermolene** [comment]
> I do have the feeling, that positional syntax will be very errorprone. ...

> Is there some code for **named params** already?

I'm not sure what you are asking. The code supports both named and positional parameters, and there are tests for each.

**Comment by pmario** [comment]
>- Six double quotes are interpreted as a pair of triple quotes. In wikitext the text inside such quotes is rendered raw; here there is no text between the quotes so nothing is rendered
>- Two double quotes have no special meaning in wikitext and so are rendered raw
>- Two single quotes are interpreted as the start of bold text. Again, there's no text to be bold

Ahhhh ... OK. ... What I wanted to do, was to define an empty parameter in the first position. Like: 

```
{{template-a-b-c| |m|n}}
```

most new users will start using it as follows, which won't work. 

```
{{template-a-b-c||m|n}}
```

Just some thoughts. We have to be very clear in the docs about that.
