### ISSUE TITLE
[BUG] RSOD with recursive macrocalls

### ISSUE THREAD

**Issue by pmario** [Jermolene/TiddlyWiki5#6676]
Related to:  Parameterised transclusions #6666 

To reproduce the RSOD -- **Warning Test can brick the wiki.** 

- create 2 tiddlers as shown below
- save both tiddlers -> Works as expected
- both tiddlers are open in story
- edit template-four
   - change params to: `\parameters(a:x  ...` -> **save** -> OK
- edit template-four
   - change macro from `<<x>>` to `<<a>>` -> **save**  --> RSOD - too much recursion

I'm not sure, why there is a recursion error. 

```
title: template-four

<!-- this template needs 4 params -->
\parameters (x:x,  y:y, z: "z: template four", aaa:aaa)

<<x>> - <<y>> - <<z>> - <<aaa>>
```

```
title: template-main

<!-- This template has 3 parameters -->
\parameters (a:a,  b:b, c: "main template")

<<a>> - <<b>> - <<c>>

{{template-four}}

{{template-four|<<a>>|<<b>>|<<c>>}}
```

**Comment by Jermolene** [comment]
Hi @pmario indeed, fixing the recursion detection is one of the two or three remaining tasks in #6666.

**Comment by pmario** [comment]
But there is _no_ recursion. I did change the parameters ... So my naive assumption is, that there is something wrong with the parameter handling.

**Comment by Jermolene** [comment]
Hi @pmario there is recursion going on, but it's subtle.

1. In template-main we invoke template-four, passing `<<a>>` as the parameter `a`
2. In template-four we transclude `<<a>>`, which wikifies to `<<a>>`, which then the process continues

Here's the test case I made from your examples:

```
title: Mario
description: Mario's Test
type: text/vnd.tiddlywiki-multiple
tags: [[$:/tags/wiki-test-spec]]

title: Output

{{template-main}}
+
title: template-four

<!-- this template needs 4 params -->
\parameters (a:x,  y:y, z: "z: template four", aaa:aaa)

<<a>> - <<y>> - <<z>> - <<aaa>>
+
title: template-main

<!-- This template has 3 parameters -->
\parameters (a:a,  b:b, c: "main template")

<<a>> - <<b>> - <<c>>

{{template-four}}

{{template-four|<<a>>|<<b>>|<<c>>}}
+
title: ExpectedResult

nothing
```

**Comment by Jermolene** [comment]
Hi @pmario to clarify, the recursion here is actually happening within the `<$macrocall>` widget that is rendered for `<<a>>`. We've never made any attempt to trap recursion when transcluding variables, only when transcluding tiddlers. So fixing the bug in this ticket will not be covered in #6666.

**Comment by pmario** [comment]
hmmm. I think I do have a big misunderstanding of the whole new system. Will probably need to single-step the new code :/

**Comment by Jermolene** [comment]
> hmmm. I think I do have a big misunderstanding of the whole new system. Will probably need to single-step the new code :/

All that's going on is that the `<<macroname>>` syntax doesn't use the new `<$transclude>` widget, it continues to use the existing `<$macrocall>` widget. So your original test reveals a bug in the macrocall widget, not the new transclusion stuff.

**Comment by pmario** [comment]
OK. But from my point of view, there shouldn't be a recursion at all. Not with macro call and not with a transclusion. So it also reveals a "bug in my mental model" ;)

I did want to test something completely different. Something like this. pseudocode follows

```
function template_main(a, b, c) {
  template_four(a, b, c, ...args)
}

main() {
template_main("a", "b", "c", "d", "e")
}
```

So I wanted to "call" the main template with more parameters than it needs and "call" the template-four with parameters passed to main. 

Hope that makes sense

**Comment by Jermolene** [comment]
@pmario 

> OK. But from my point of view, there shouldn't be a recursion at all. Not with macro call and not with a transclusion. So it also reveals a "bug in my mental model" ;)

Have another look at the [test case](https://github.com/Jermolene/TiddlyWiki5/issues/6676#issuecomment-1118401892):

* We start by invoking "template-main" with no parameters
* Inside "template-main", it's the third transclusion `{{template-four|<<a>>|<<b>>|<<c>>}}` that is the problem
* We invoke template-four with the value of our parameters, meaning: "<<a>>", "<<b>>", and "<<c>>" (note that these are literal strings here)
* Inside "template-four" the parameter "a" will therefore now have the value "<<a>>"
* Therefore the macrocall `<<a>>` in "template-four" will expand to `<<a>>`, and there's your recursion

> I did want to test something completely different. Something like this. pseudocode follows

There's no docs yet, but the parameters widget sets up the variables `paramNames` and `paramValues` that contain all of the parameters that were provided in the transclude widget. This makes it possible to write function definitions that don't know all of their parameter names in advance. No docs yet, so see the tests for details, and do please let me know if any of them aren't clear.

**Comment by pmario** [comment]
>Therefore the macrocall <<a>> in "template-four" will expand to <<a>>, and there's your recursion

OK

**Comment by pmario** [comment]
example does not brick the wiki anymore. So close
