### ISSUE TITLE
[Help Wanted] Generalise macrocall & widget parmeter handling in widget-tree

### ISSUE THREAD

**Issue by pmario** [Jermolene/TiddlyWiki5#6682]
This issue was created, so we don't forget about it

> It would really useful to make macro calls visible in the same way you did for transclusions. I took a stab at it, but it seems macrocalls using wiki syntax do not populate the widget tree with the attributes

Ouch! I had forgotten about that unsightly scar tissue from the past. See 55d479c540f5e0a05e6c59ef7eb14606b89857c3 for some background.

It's tricky to fix it; the macrocall widget uses the params array to manage positional parameters and so it isn't straightforward to map those broken parsetrees into ordinary widget parse tree nodes. So I'd be inclined to leave fixing that for a separate PR – and indeed would welcome help on that if anyone is able.

_Originally posted by @Jermolene in https://github.com/Jermolene/TiddlyWiki5/issues/6666#issuecomment-1120371771_

**Comment by Jermolene** [comment]
Thank you @pmario. My [new plan](https://github.com/Jermolene/TiddlyWiki5/pull/6666#issuecomment-1120401805) is to tackle this as part of the work in #6666.
