### ISSUE TITLE
TiddlyWiki v5.2.2 Browser Storage plugin detection code not working in HTA mode

### ISSUE THREAD

**Issue by whjou** [Jermolene/TiddlyWiki5#6701]
### Describe the bug

I have been using TiddlyWiki v5.1.17 as a [HTA](https://en.wikipedia.org/wiki/HTML_Application) for a while and recently upgraded to TiddlyWiki v5.2.2. However I noticed that a few official plugins throws JavaScript errors in HTA mode.

* Browser Storage - I am aware this probably won't work in HTA mode but the detection code to skip do not seem to work well: it is failing with this message "Unable to get property 'length' of undefined or null reference".

While I could disable it, I'd like very much to have Browser Storage enabled with the logic to skip the plugin work properly.

### Expected behavior

I'd expect to have Browser Storage plugin enabled and when I run TiddlyWiki as a HTA, the plugin (startup?) code will safely skip this unsupported functionality and continue to work.

### To Reproduce

1. Download TiddlyWiki v5.2.2 full edition from https://tiddlywiki.com/editions/full/
2. Rename file extension to .HTA
3. Execute on a Windows PC (e.g. Windows 10)

### Screenshots

![image](https://user-images.githubusercontent.com/696695/169656209-df7d6f64-49cd-4190-9760-b2c443b2a03e.png)

![image](https://user-images.githubusercontent.com/696695/169656214-1ab74d32-ef0b-43b3-8c57-06cb513a4637.png)

### TiddlyWiki Configuration

- Version - 5.2.2
- Saving mechanism - HTA
- Plugins installed - Full edition with nothing else

### Desktop (please complete the following information):

- OS - Wndows 10
- Browser - n/a (HTA)
- Version - n/a

**Comment by Jermolene** [comment]
Thanks @whjou I think 8fabcabebbd910c5ec08e1fc07d1851b0605aee6 should fix it – there will be a build for you to test at https://tiddlywiki.com/prerelease in about 10 minutes

**Comment by whjou** [comment]
Just confirming it works :) May I know when will v5.2.3 be released and how I can apply this change into my local copy if I can't wait? The idea of manually updating $:/plugins/tiddlywiki/browser-storage is very daunting!

**Comment by Jermolene** [comment]
> Just confirming it works :) May I know when will v5.2.3 be released and how I can apply this change into my local copy if I can't wait? The idea of manually updating $:/plugins/tiddlywiki/browser-storage is very daunting!

We don't have a scheduled date for v5.2.3 yet. In the meantime in this case you could use the v5.2.3 browser storage plugin with a v5.2.2 wiki.
