### ISSUE TITLE
[BUG] For some Chrome users, focusing the search box offers to autocomplete passwords

### ISSUE THREAD

**Issue by Jermolene** [Jermolene/TiddlyWiki5#6723]
### Describe the bug

For some users on Chrome, clicking into the search box in the sidebar or the menu bar can trigger Chrome to offer to autocomplete it as a password.

### To Reproduce

1. Click in the search box
2. Observe the password autocomplete dropdown

### TiddlyWiki Configuration

The problem manifests itself on online TiddlyWiki's that include a login capability (for example, https://manuals.annafreud.org/ambit shows the problem).

**Comment by CodaCodr** [comment]
It's a pain - seen sporadically in my day job, ONLY in Chrome(ium?)

We (so far) seem to be having success with...

https://stackoverflow.com/questions/54711475/chrome-autofills-username-into-random-text-input
