### ISSUE TITLE
[BUG] The tag editor allows tags starting/ending with blank space

### ISSUE THREAD

**Issue by FarukOzderim** [Jermolene/TiddlyWiki5#6725]
Thanks for the great open source project!

### Describe the bug

Creating a tiddly with the tag,`  $:/tags/RawMarkup` does not show up the text inside it in the html <head>. See the ss, and see the [documentation ](https://tiddlywiki.com/static/SystemTags.html)about tags

### Expected behavior

should show up the in the html 

### To Reproduce

See the ss and check the html file later

### Screenshots

![image](https://user-images.githubusercontent.com/44067394/173627400-65288369-6cf0-4a99-a379-0750b7d46c6c.png)

### TiddlyWiki Configuration

Html file got from tiddlywiki.org and serving in github pages

### Additional context
cc: @Jermolene

**Comment by Jermolene** [comment]
Hi @FarukOzderim that tiddler looks OK. Note that the rawmarkup tiddler is only processed when the wiki is saved; after creating a raw markup tiddler you need to save and reload the wiki.

**Comment by FarukOzderim** [comment]
Hmm, it looks like the space occurred while I was trying to get a ss of it, currently there is no space but it still does not show in html <head>, can you see it?

**Comment by FarukOzderim** [comment]
So, I think this still is a bug, could you see it in the html header?

**Comment by Jermolene** [comment]
Hi @FarukOzderim I actually confirmed it by looking at the source of the file. I do think it is a bug; we should trim whitespace from newly entered tags as we do for titles.

**Comment by FarukOzderim** [comment]
Hmm, strange that I can't find it in the html headers. And I cannot register my github pages to google search console because it cannot find my webpage (since it is not in html headers). 

## Correct Tag and Tiddly
![image](https://user-images.githubusercontent.com/44067394/173846318-2e7d860d-b2e9-481f-bce5-04f0cbc38221.png)
![image](https://user-images.githubusercontent.com/44067394/173846336-2e6deeb2-8aed-4398-9fd6-05052fef2878.png)

## HTML Headers
![image](https://user-images.githubusercontent.com/44067394/173846513-7a68ccbc-715b-464b-a092-d9b865190959.png)

**Comment by FarukOzderim** [comment]
> Hi @FarukOzderim try searching the HTML source for the string `"Google rank"`; you should find the JSON representation of the tiddlers in the file.

Yeah I can find it, however the functionality of RawMarkup is not that, or am I confused? It should add the related info to the html <head> section, please check [here](https://tiddlywiki.com/static/SystemTag%253A%2520%2524%253A%252Ftags%252FRawMarkup.html).

I am currently trying to add html tags to be able to show in google search.
![image](https://user-images.githubusercontent.com/44067394/173878244-4154ba5e-0e16-47e8-aec4-3dd2026fac89.png)

**Comment by FarukOzderim** [comment]
Hi @Jermolene thx for the help! 

I currently cannot rank my github tiddlywiki page in Google and I think this is a very critical feature. Is there somewhere I may ask more about this, since I could not find a solution in internet. 

Trying to add google index into <head> did not help either since RawMarkup does not include text into <head> section of the HTML as far as I can see, so I think its missing its elementary feature right now, and this is a bug.

**Comment by saqimtiaz** [comment]
> the problem is that there is a space at the start of the tag ` $:/tags/RawMarkup`. You'll need to edit that tiddler, remove the tag, and add it once again correctly as `$:/tags/RawMarkup`.

Have you followed these steps @FarukOzderim ? After removing and re-adding the tag without and leading or trailing spaces, you will need to save and reload your wiki **twice** for the raw markup to be inserted into the HTML of the file.

**Comment by FarukOzderim** [comment]
> > the problem is that there is a space at the start of the tag ` $:/tags/RawMarkup`. You'll need to edit that tiddler, remove the tag, and add it once again correctly as `$:/tags/RawMarkup`.
> 
> Have you followed these steps @FarukOzderim ? After removing and re-adding the tag without and leading or trailing spaces, you will need to save and reload your wiki **twice** for the raw markup to be inserted into the HTML of the file.

Yes, you can check it here, I also tried adding a new tiddler with the correct tag, but it also did not work.

Please also see this [comment](https://github.com/Jermolene/TiddlyWiki5/issues/6725#issuecomment-1156517186)

**Comment by saqimtiaz** [comment]
I downloaded your file and with the following steps everything worked and the raw markup appears in the source of the HTML:
* edited the tiddler "Google rank" to remove the tag
* manually typed in the tag "$:/tags/RawMarkup"
* saved the wiki and reloaded it.
* saved the wiki a second time and reloaded it.

**Comment by FarukOzderim** [comment]
> I downloaded your file and with the following steps everything worked and the raw markup appears in the source of the HTML:
> 
>     * edited the tiddler "Google rank" to remove the tag
> 
>     * manually typed in the tag "$:/tags/RawMarkup"
> 
>     * saved the wiki and reloaded it.
> 
>     * saved the wiki a second time and reloaded it.

That's great, to clarify did it appear in the <head> section of the HTML? See the image below

https://github.com/assets/44067394/7a68ccbc-715b-464b-a092-d9b865190959

**Comment by saqimtiaz** [comment]
> That's great, to clarify did it appear in the section of the HTML?

Yes.

**Comment by pmario** [comment]
I did test the same workflow as Saq, but I only did the first 3 steps and it worked with your wiki. Using Windows and FF latest.

**Comment by FarukOzderim** [comment]
It worked, thx a lot @saqimtiaz @pmario @Jermolene 💯 🔥 🥳 

It seems the bug is with autocomplete, because I also tried adding this tiddly, and it did not show up in the html as well.
So If I write it manually and click on `add` it works, but if I click enter on autocomplete i

**Comment by pmario** [comment]
>...but if I click enter on autocomplete it does not work..

Autocomplete uses the "existing" tags only. So you probably replaced the tag with the same "faulty" one. :/

**Comment by pmario** [comment]
@Jermolene 

>I think this qualifies as a bug; we already trim whitespace from the start and end of tiddler titles when editing a tiddler, and I think it would be reasonable to do the same thing with tags.

I think we fixed this in v5.0.9 .. https://github.com/Jermolene/TiddlyWiki5/commit/c3e24c1228b90c88c308b596753ff58d7c711045  Is it possible we missed something

**Comment by pmario** [comment]
>I think you fixed this in v5.0.9 .. https://github.com/Jermolene/TiddlyWiki5/commit/c3e24c1228b90c88c308b596753ff58d7c711045 Is it possible we missed something?

Uuuups, I did single step through the code and there seems to be a problem with the fieldmangler code. ... I'll create a new issue.

**Comment by FarukOzderim** [comment]
Closed for the sake of the new issue 👍
