### ISSUE TITLE
[BUG] fieldmangler doesn't get the right parameters if fields or tags are added

### ISSUE THREAD

**Issue by pmario** [Jermolene/TiddlyWiki5#6731]
### Describe the bug

Triggered by Issue #6725 ... I did single step through the fieldmangler.js code. 

-  It seems the UI doesn't send the right parameters with the tm-add-tag and tm-add-field anymore. 
-  It seems the tm-add-tag and tm-add-field aren't sent at all.

### To Reproduce

- crate a new tiddler eg: aaa
- add tag with a leading or trailing space
- hit add button 
- ---> Problem. 

---

- create a new tiddler 
- add tag with a leading or trailing space ... .BUT 
- DON'T click add. 
- Click "Done" in the tiddler toolbar 
- ---> No Problem

### TiddlyWiki Configuration

tiddlywiki.com was used to test

**Comment by pmario** [comment]
@Jermolene ... I did find a fast "hack" as a temporary fix. ... But it's only fighting the symptoms and no real fix. 

It could be done with adding 2 `trim[]` parameters to the UI. But as soon as someone uses some 3rd party theme mods, the problem could pop up again. 

 - The hack requires 1 little PR

---

 - The real fix will probably require 3 or 4 PRs since I would want to 
   - add new tests to catch DOM structure changes
   - 1 PR to make the involved UI code (3 tiddlers) more readable 
     - no tests should fail
   - 1 PR to remove redundant DOM elements
     - adjust the test because of new DOM structure
   - fix the problem
     - tests should stay green

**Comment by Jermolene** [comment]
Thanks @pmario 

> * It seems the UI doesn't send the right parameters with the tm-add-tag and tm-add-field anymore.
> * It seems the tm-add-tag and tm-add-field aren't sent at all.

Are you saying that the current UI no longer relies on the fieldmangler widget, but manipulates the fields directly? If so, I don't think that's a problem; I'd like to deprecate the fieldmangler widget.

> ### To Reproduce
> * crate a new tiddler eg: aaa
> * add tag with a leading or trailing space
> * hit add button
> * ---> Problem.

But this still needs fixing somehow.

> @Jermolene ... I did find a fast "hack" as a temporary fix. ... But it's only fighting the symptoms and no real fix.
> 
> It could be done with adding 2 `trim[]` parameters to the UI. But as soon as someone uses some 3rd party theme mods, the problem could pop up again.
> 
> * The hack requires 1 little PR
> 
> * The real fix will probably require 3 or 4 PRs since I would want to
>   
>   * 1 PR to add new tests to catch future DOM structure changes
>   * 1 PR to make the involved UI code (3 tiddlers) more readable
>     
>     * no tests should fail
>   * 1 PR to remove redundant DOM elements
>     
>     * adjust the test because of new DOM structure
>   * fix the problem
>     
>     * tests should stay green

Why does the DOM structure need to change? It would be helpful if you could describe the two alternative fixes in more detail.

**Comment by pmario** [comment]
>  It would be helpful if you could describe the two alternative fixes in more detail.

There are 3 tiddlers involved in the problem: EditTemplate.tid, tags.tid and tag-picker.tid ... 

Adding tags and field uses 2 different methods. 1st `action-sendmessage` in combination with the `fieldmangler` and 2nd `action-listops` directly writing to fields. The functions are scattered over those 3 tiddlers. 

From my point of view using fieldmangler and messages is the cleanest and more maintainable way, since trimming values can be done in 1 place in the fieldmangler code.

**Comment by Jermolene** [comment]
Hi @pmario our direction of travel is actually to deprecate the fieldmangler widget. Eventually, we can replace it with a wikitext shim, but for the moment we should continue to remove its usage in the core.

> the behaviour of action-listops commands is inconsistent

Can you expand on that?

> If we want to get rid of the fieldmangler widget, it would be easy to trim fields at the tiddler.js level. The code would be the same.

That does not sound correct. The UI may need to trim spaces but that does not mean that we should make it impossible to make such tiddlers.

**Comment by pmario** [comment]
There is one more decision to be made:  Should the existing TW UI remove the leading and/or trailing spaces if selected with the tag-dropdown UI.

to reproduce: 

- A tag with a leading spaces exists: eg: `   aa`
   - The leading spaces are _not_ shown in the UI atm, so the user doesn't know it.
- The tag is selected with the tag dropdown.
- Should the existing TW UI remove the leading space or not?

**Comment by Jermolene** [comment]
> There is one more decision to be made: Should the existing TW UI remove the leading and/or trailing spaces if selected with the tag-dropdown UI.

I thought we had established already that the answer is "yes, we should trim user entered tags in the UI", for consistency with the way that we handle titles.

**Comment by pmario** [comment]
> I thought we had established already that the answer is "yes, we should trim user entered tags in the UI", for consistency with the way that we handle titles.

OK. 

So it's OK if a plugin creates a tag with leading or trailing spaces and the UI will remove it, if the dropdown is used. .. Just to be sure.

**Comment by Jermolene** [comment]
> So it's OK if a plugin creates a tag with leading or trailing spaces and the UI will remove it, if the dropdown is used. .. Just to be sure.

I think you're asking whether existing tags shown in the dropdown should also be trimmed. That's a tricky one but I think that the answer is "no", they should not be trimmed. It's an edge case, but it seems that the semantics of the dropdown should be to respect the existing tags. Otherwise it would be impossible to use the tag dropdown to construct TOCs that incorporate titles that start or end with a space.

**Comment by pmario** [comment]
>... That's a tricky one but I think that the answer is "no", they should not be trimmed.

That's good, because I couldn't find the code involved anyway.
