### ISSUE TITLE
[IDEA] Add location hash to the info mecanism

### ISSUE THREAD

**Issue by Telumire** [Jermolene/TiddlyWiki5#6748]
I'd like to start my wiki in different mode, akin to the safe mode, using startup actions.

The info mechanism already provide the rest of the current url, only the location hash is missing. I think it would be great if it also provided the location hash (using the build-in function $tw.utils.getLocationHash() for example).

In addition to enable users to create their own startup mode, it could be used to react to perma-linking (using the location hash in a filter). 

I tried to do that with a startup action using the $:/StoryList to emulate this feature but I didnt manage to close the "location hash tiddler" (here, trying to create a new tiddler when starting the wiki with `#:new`, new cant be closed at startup and the new tiddler is not navigated to):

```
\import [[$:/core/ui/PageMacros]] [all[shadows+tiddlers]tag[$:/tags/Macro]!has[draft.of]]

<$list filter="[list[$:/StoryList]match[new]]">
<$action-createtiddler $basetitle="New tiddler"> --> works
<$action-navigate $to=<<createTiddler-title>>/> --> dont work
</$action-createtiddler>
</$list>
<$action-sendmessage $message="tm-close-tiddler" $param="new"/> --> dont work
```

## Example

URL = `file:///C:/Downloads/empty.html#:new`

Tiddler title : `$:/info/url/location`
Tiddler text (output from `$tw.utils.getLocationHash()` ): `#:new`

**Comment by pmario** [comment]
There is an open PR: [add location.hash to browser system info tiddlers](https://github.com/Jermolene/TiddlyWiki5/pull/4374#)
#4374  ... But read the last message from Jeremy https://github.com/Jermolene/TiddlyWiki5/pull/4374#issuecomment-855383176

**Comment by pmario** [comment]
I think it should be easy to create a plugin from this PR. It's only 3 little changes.

**Comment by pmario** [comment]
>In addition to enable users to create their own startup mode, it could be used to react to perma-linking (using the location hash in a filter).

As discussed at my PR it would only be a snapshot at startup. So this function would _not_ be possible with the current PR. .. Startup actions should be possible
