### ISSUE TITLE
[BUG] In SVG rendering foreignObject doesn't recognise HTML namespace without BODY element

### ISSUE THREAD

**Issue by pmario** [Jermolene/TiddlyWiki5#6753]
### Describe the bug

The following SVG code does NOT work:

```
<svg width="121px" viewBox="-0.5 -0.5 121 61">
  <g>
    <rect x="0" y="0" width="120" height="60" fill="rgb(255, 255, 255)" stroke="rgb(0, 0, 0)" pointer-events="all"/>
    <g transform="translate(-0.5 -0.5)">
        <foreignObject pointer-events="none" width="100%" height="100%" requiredFeatures="http://www.w3.org/TR/SVG11/feature#Extensibility" style="overflow: visible; text-align: left;">
          <div xmlns="http://www.w3.org/1999/xhtml" style="display: flex; align-items: center; justify-content: center; width: 118px; height: 1px; padding-top: 30px; margin-left: 1px;">
            <div data-drawio-colors="color: rgb(0, 0, 0); " style="box-sizing: border-box; font-size: 0px; text-align: center;">
              <div style="display: inline-block; font-size: 12px; font-family: Helvetica; color: rgb(0, 0, 0); line-height: 1.2; pointer-events: all; white-space: normal; overflow-wrap: normal;">Tiddlywiki</div>
            </div>
          </div>
        </foreignObject>
</svg>
```

**The following code works**. The only difference is the additional BODY element in the foreignObject, which switches the XMLNS back to HTML. So the created element will be created in the right way in the dom. 

```
<svg width="121px" viewBox="-0.5 -0.5 121 61">
  <g>
    <rect x="0" y="0" width="120" height="60" fill="rgb(255, 255, 255)" stroke="rgb(0, 0, 0)" pointer-events="all"/>
    <g transform="translate(-0.5 -0.5)">
        <foreignObject pointer-events="none" width="100%" height="100%" requiredFeatures="http://www.w3.org/TR/SVG11/feature#Extensibility" style="overflow: visible; text-align: left;">
<body>
          <div xmlns="http://www.w3.org/1999/xhtml" style="display: flex; align-items: center; justify-content: center; width: 118px; height: 1px; padding-top: 30px; margin-left: 1px;">
            <div data-drawio-colors="color: rgb(0, 0, 0); " style="box-sizing: border-box; font-size: 0px; text-align: center;">
              <div style="display: inline-block; font-size: 12px; font-family: Helvetica; color: rgb(0, 0, 0); line-height: 1.2; pointer-events: all; white-space: normal; overflow-wrap: normal;">Tiddlywiki</div>
            </div>
          </div></body>
        </foreignObject>
</svg>
```

I think the following code is responsible.

https://github.com/Jermolene/TiddlyWiki5/blob/1110fd50cfc4b61e61524323b4e309d72f1298dd/core/modules/widgets/element.js#L45-L68

### Expected behavior

We need to detect an embedded HTML element in an SVG by evaluating the XMLNS attribute from the first child of the foreignObject element and switch the NS if needed.

### To Reproduce

See working code above.

### TiddlyWiki Configuration

TW v5.2.2

**Comment by Jermolene** [comment]
Thanks @pmario. Does adding `foreignObject` to the namespace table resolve things?

```
var tagNamespaces = {
		svg: "http://www.w3.org/2000/svg",
		math: "http://www.w3.org/1998/Math/MathML",
		body: "http://www.w3.org/1999/xhtml",
		foreignObject: "http://www.w3.org/1999/xhtml"
	};
```

**Comment by pmario** [comment]
I'm not sure, what a foreignObject can contain. I think, there is a high chance that there are more possibilities: 

See: https://developer.mozilla.org/en-US/docs/Web/SVG/Element/foreignObject

>The <foreignObject> [SVG](https://developer.mozilla.org/en-US/docs/Web/SVG) element includes elements from a different XML namespace. In the context of a browser, it is most likely (X)HTML.

But what if it's a MATHML object :/

**Comment by Jermolene** [comment]
Hi @pmario we need some more test cases.

**Comment by pmario** [comment]
Just thought about it. If it's MathML then there should be a `<math>` element. right? ... which should be detected by our code in the right way already. .... So we may be pretty safe ... until the next "edge case" shows up ;)

**Comment by Jermolene** [comment]
> Just thought about it. If it's MathML then there should be a `<math>` element. right? ... which should be detected by our code in the right way already. .... So we may be pretty safe ... until the next "edge case" shows up ;)

That was the intent of the original code, but it probably needs more tests.

A quick bit of googling found at least one more namespaces we might need to know about: [IMSC](https://developer.mozilla.org/en-US/docs/Related/IMSC), a W3C language for subtitling, uses [its own namespace](https://developer.mozilla.org/en-US/docs/Related/IMSC/Namespaces).

We would also need more sophisticated namespace handling if we wishes to use wikitext to generate XML instead of HTML.

In any event, in order to fix anything we need a suitable test case.

**Comment by pmario** [comment]
I did test it with the HTML namespace assigned to `foreignObject` -> **does not work** probably because foreighObject is part of the SVG namespace. .. just a guess. 

If I use: 

var tagNamespaces = {
		svg: "http://www.w3.org/2000/svg",
		math: "http://www.w3.org/1998/Math/MathML",
		body: "http://www.w3.org/1999/xhtml",
		div: "http://www.w3.org/1999/xhtml"
	};

it works. BUT in line 55 it should be set that way anyway. .. SO may be our logic doesn't evaluate all code paths. ??!!

**Comment by Jermolene** [comment]
Hi @pmario can you a share a test case?

**Comment by ittayd** [comment]
Note that in my original question that led to the opening of this issue what I saw is that xmlns attributes where removed when rendering by TW. That is, if I input an SVG that starts with:
`<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1" width="121px" viewBox="-0.5 -0.5 121 61">`

The way it ends up in the DOM is `<svg version="1.1" width="121px" viewBox="-0.5 -0.5 121 61">`. If I load the original SVG by Chrome directly from file, the DOM has the attributes. So they are removed by TW handling, not by Chrome hiding them. Why not just keep them as is? 

Similarly, in my original example, this was the div: ` <div xmlns="http://www.w3.org/1999/xhtml" style="display: flex; align-items: unsafe center; justify-content: unsafe center; width: 118px; height: 1px; padding-top: 30px; margin-left: 1px;">`, again, and xmlns attribute that TW removed.

**Comment by pmario** [comment]
>Hi @pmario can you a share a test case?

I use the first code snippet from the OP. .. The first child of the `foreignObject` is a DIV that "switches back" to the HTML namespace. ... We ignore that switch because the code in line 54 shown in the permalink in the OP reads the namespace from the `namespace` variable. 

```
 	this.namespace = this.getVariable("namespace",{defaultValue: "http://www.w3.org/1999/xhtml"}); 
```

So even if the first child is a DIV, our existing code still defines it with an SVG namespace. .. That's the problem. 

We need to detect the namespace change and set the internal variable accordingly.

**Comment by pmario** [comment]
I think I have a fix. More testing will be needed then PR is on the way

**Comment by pmario** [comment]
>The way it ends up in the DOM is <svg version="1.1" width="121px" viewBox="-0.5 -0.5 121 61">. If I load the original SVG by Chrome directly from file, the DOM has the attributes. So they are removed by TW handling, not by Chrome hiding them. Why not just keep them as is?

I think that's a different oversight / issue in a different part of the code. .. _But_ that's not important for the functionality of the code. The important code for the functionality is `document.createElementNS(this.namespace, this.tag)` and that's wrong with the existing code. 

I think I do have a fix, but a bit more testing is needed. Adding the attribute probably has a similar problem, but that would need to be a different Issue and a different PR. More testing is needed here too.

**Comment by ittayd** [comment]
@pmario , well, the viz plugin creates SVG and that SVG has links rendered as xlink:href (see [here](https://talk.tiddlywiki.org/t/anchors-can-be-used-once/3732/2) ). So not sure if it impacts functionality (links seem to work), but it may.

**Comment by ittayd** [comment]
Awesome handling of this. Thanks!

**Comment by pmario** [comment]
fixed with: https://github.com/Jermolene/TiddlyWiki5/pull/6755
