### ISSUE TITLE
[BUG] TW ignores SVG namespace attributes - that shouldn't happen

### ISSUE THREAD

**Issue by pmario** [Jermolene/TiddlyWiki5#6754]
### Describe the bug

To reproduce

- use the following code
- copy paste into a tiddler
- right-click "Inspect"

```
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1" width="121px" viewBox="-0.5 -0.5 121 61">
    <rect x="0" y="0" width="120" height="60" fill="rgb(255, 255, 255)" stroke="rgb(0, 0, 0)" pointer-events="all"/>
</svg>
```

It looks like this: 

![image](https://user-images.githubusercontent.com/374655/177292460-3c214aa5-96f0-4b3e-a669-f2b5f56ed0f6.png)

### Expected behavior

The DOM tree should also contain the attributes, because if they are missing, it causes issue problems because there is a difference between the code and the DOM structure. 

### TiddlyWiki Configuration

TW v5.2.2

### Additional context

I think I know, where the problem is. In line 331 --- I think I know a fix too -- more testing will be needed

https://github.com/Jermolene/TiddlyWiki5/blob/1110fd50cfc4b61e61524323b4e309d72f1298dd/core/modules/widgets/widget.js#L321-L332

**Comment by Jermolene** [comment]
Hi @pmario I think the culprit is this code:

https://github.com/Jermolene/TiddlyWiki5/blob/a59ec3ebf7bb4d780543e7b93cd480f4c6ad880c/core/modules/widgets/widget.js#L340-L344

The problem is that adding the "xmlns" to an "svg" element causes an error.

**Comment by pmario** [comment]
see: https://developer.mozilla.org/en-US/docs/Web/API/Element/setAttributeNS#notes 

>setAttributeNS is the only method for namespaced attributes which expects the fully qualified name, i.e. "namespace:localname".

**Comment by pmario** [comment]
I'm still creating tests for the other issue. https://github.com/Jermolene/TiddlyWiki5/issues/6753

**Comment by pmario** [comment]
fixed with: https://github.com/Jermolene/TiddlyWiki5/pull/6755
