### ISSUE TITLE
[IDEA] Reduce DEFAULT_MIN_TEXT_AREA_HEIGHT

### ISSUE THREAD

**Issue by martinschniewind** [Jermolene/TiddlyWiki5#6759]
**Is your feature request related to a problem? Please describe.**
I am creating Forms using varios input widgets. Concerning TextAreas (edittext type="textarea") the control always has a minimun height of 100px.

Due to design aspects, I have to reduce the size of empty textareas. But neither there are relevant configuration options nore will CSS rules apply. TW sets the height attribute by adding 'style="height: 100px"' to the textarea-tag. This value cannot be overwritten by CSS rules.

This is done by $:/core/modules/editor/factory.js, where DEFAULT_MIN_TEXT_AREA_HEIGHT is set to 100px.

As soon as I modify this constant in factory.js to 20px, any empty textarea will get 'style="height:auto"', which is exactly what I need.

**Describe the solution you'd like**
So if there are no ojections, please reduce DEFAULT_MIN_TEXT_AREA_HEIGHT to 20px or something similar.

**Describe alternatives you've considered**
An alternative and perhaps more comfortable solution would be to make DEFAULT_MIN_TEXT_AREA_HEIGHT configurable via theme setting. Or at least simply save it to an configuration tiddler, e.g. $:/config/TextEditor/EditorHeight/DefaultMinTextAreaHeight.

Cheers, Martin

**Comment by pmario** [comment]
Which widget do you use `<$edit>` or `<$edit-text>`

See: https://tiddlywiki.com/#EditWidget:EditWidget%20EditTextWidget

**Comment by pmario** [comment]
Can you post one of your forms here?

**Comment by CodaCodr** [comment]
@martinschniewind 

> TW sets the height attribute by adding 'style="height: 100px"' to the textarea-tag. This value cannot be overwritten by CSS rules.

Agreed. It's quite annoying. I've meant to post a bug but keep forgetting, so thanks for this!

@pmario 
A picture is worth a thousand words (allegedly), so here's 2000 words ;)

![image](https://user-images.githubusercontent.com/436812/177578223-6db1556a-5a3d-44f3-946f-d3c6f364d5cd.png)

![image](https://user-images.githubusercontent.com/436812/177578333-2416141c-03bc-4521-a197-0fb822e89e51.png)

The commented out line will make it work, but we shouldn't need `!important` for something so basic.

Not sure how @Jermolene will view this in terms of legacy TWs, though.

**Comment by Jermolene** [comment]
Thanks @martinschniewind 

The default `DEFAULT_MIN_TEXT_AREA_HEIGHT` can be overridden by specifying a `minHeight` attribute on the text widget. See:

https://tiddlywiki.com/#EditTextWidget

There is currently no provision for changing the global default.

**Comment by martinschniewind** [comment]
Thanks @pmario @CodaCodr @Jermolene 
Sorry for not responding - notification settings in my GitHub account must be faulty ...
In deed, minHeight does the trick. Obviously I did not read properly the documentation...
