### ISSUE TITLE
[IDEA] Extend tiddler subtitle to be hackable with a tag for 5.2.3?

### ISSUE THREAD

**Issue by AnthonyMuscio** [Jermolene/TiddlyWiki5#6775]
**Is your feature request related to a problem? Please describe.**
There are a number of occasions people want to modify or add to what appears in the tiddler subtitle
* however this demands editing the core tiddler [$:/core/ui/ViewTemplate/subtitle](https://tiddlywiki.com/#%24%3A%2Fcore%2Fui%2FViewTemplate%2Fsubtitle)

**Describe the solution you'd like**
* Allow various solutions to place content in the subtitle distributed, without editing a core tiddler or clashing with other similar solutions.
* Move the current subtitle format to a new tiddler $:/core/ui/ViewTemplate/subtitle/default as follows
* Tag this new tiddler with $:/tags/tiddler-subtitle so it is again displayed by default.
```
<$link to={{!!modifier}} />
<$view field="modified" format="date" template={{$:/language/Tiddler/DateFormat}}/>
```
* Modify the contents of $:/core/ui/ViewTemplate/subtitle as follows;

```
\whitespace trim
<$reveal type="nomatch" stateTitle=<<folded-state>> text="hide" tag="div" retain="yes" animate="yes">
<div class="tc-subtitle">
<$list filter="[all[shadows+tiddlers]tag[$:/tags/ViewTemplate/Subtitle]!has[draft.of]]" variable=subtitle-tiddler><span title={{{ [<subtitle-tiddler>get[description]] }}}><$transclude tiddler=<<subtitle-tiddler>>/>&nbsp;</span></$list>
</div>
</$reveal>
```

**Describe alternatives you've considered**
Modifying the core tiddler as above.

**Additional context**
* The tag named in the above code $:/tags/tiddler-subtitle could be named differently
* The description field of each tiddler so tagged is used as a tooltip to the content displayed in the subtitle
  * Thus the new tiddler can be given the following description "Modifier and modified date"
* Another field name such as tooltip may be preferred over the description field.

**Examples of additional content in the subtitle**
* The inclusion of a characters or word count on the tiddler
* An indicator for different tiddler types, as a result of a tag or field
* Conditional help or more information buttons/Indicators
* Status indicator or information
* Other date and time information eg due-date

**Please note**
I have submitted this Issue: Feature request because I do not yet believe I have the capacity to submit PR's for the core, however if a I do secure the facility I plan to submit a PR. So please provide any feedback or submit a PR on my behalf thank you.

**Comment by Jermolene** [comment]
Thanks @AnthonyMuscio, that's a good idea. Perhaps the tag would be `$:/tags/ViewTemplate/Subtitle` for consistency with existing system tags.

**Comment by AnthonyMuscio** [comment]
Thanks @Jermolene I updated my above code to reflect you better naming of the tag.

Can someone else please run with this until I can submit PR's?
* It would be nice in TW 5.2.3
* It was recently raised here https://talk.tiddlywiki.org/t/help-regarding-caption-and-title/3920/13?u=tw_tones to display captions or alternative titles etc...
* I am preparing some minor changes which I will share here shortly (in this reply)
