### ISSUE TITLE
Add support for WikiCreole linebreaks

### ISSUE THREAD

**Issue by Jermolene** [Jermolene/TiddlyWiki5#678]
It is  proposed to adopt WikiCreole's double-backslash syntax for line breaks:

http://www.wikicreole.org/wiki/LineBreaks

See this discussion:

https://groups.google.com/d/topic/tiddlywiki/pU6rxeCvuLs/discussion

**Comment by pmario** [comment]
WikiCreole `\\` to create a  `<br>` has not been implemented for 9 years and it would probably clash with windows path names.

The GG discussion talks about hard-linebreaks with are easy to do [with a little bit of CSS](https://tiddlywiki.com/#Hard%20Linebreaks%20with%20CSS:%5B%5BHard%20Linebreaks%20with%20CSS%5D%5D%20%5B%5BHard%20Linebreaks%20with%20CSS%20-%20Example%5D%5D) for prose text.

So imo this issue should be a "will not be implemented" and should be closed.

**Comment by Jermolene** [comment]
Thanks @pmario
