### ISSUE TITLE
[IDEA]  Improve the Contributors Section in Release Tiddler

### ISSUE THREAD

**Issue by kookma** [Jermolene/TiddlyWiki5#6784]
Following to discussion here: https://github.com/Jermolene/TiddlyWiki5/discussions/6783

A solution has been given to improve the contribution section in Release Tiddler.

Here https://talk.tiddlywiki.org/t/tw-5-2-3-is-getting-ready-to-be-released/3867/18 a JSON file is attached and you try the solution in Tiddlywiki prerelease.

**Comment by Jermolene** [comment]
For reference, here's the screenshot you posted in #6783:

![image](https://user-images.githubusercontent.com/830394/179010013-6b9e3ee5-8dcb-4d32-b284-8ba02dced84b.png)

**Comment by kookma** [comment]
> Would you be willing to make a PR that works on top of those changes?

Sure. I will submit the PR.
