### ISSUE TITLE
[IDEA] Add a filter parameter to the tag-picker macro

### ISSUE THREAD

**Issue by AnthonyMuscio** [Jermolene/TiddlyWiki5#6791]
**Is your feature request related to a problem? Please describe.**
Currently the tag Picker macro is use in edit mode to select tags from the existing tags only. The result is divided into system and non system tags. From tiddlywiki release 5.1.23  the existing actions and now tagField can be provided to the picker. This is a nice feature because you can populate a separate "list field" like the tags field with the convenience of the drop down.
* To add a new tag not already a tag you must type exactly the new tag name, or if it is a tiddler go and copy the title and paste it into the tag picker field.
  * That is, it is not easy to add an existing tiddler, not already a tag, as a tag to the current tiddler. Otherwise the drop-down and search is great.

**Describe the solution you'd like**
It would be nice if an additional parameter were added to the tag picker macro through which we could provide a filter that determines the possible titles, either from existing tiddler titles or synthetic titles.
* The default for this filter could be "[tags[]]" and the results remain divided into system and non system tiddler in the drop down, thus no change to its existing use.
* However if an alternative filter was given, calling this macro, that it would instead be used to list the tiddlers that may be added as tags, if they are already tags or not. If it excludes either system or not system tags they will not be listed.
  * Typically this would be done with a call to the tag picker however in some circumstances a filter could be applied to the standard tag picker to restrict which tags a user can apply - eg: in a user mode they can't add system tags.
* With the ability to select the tagField this would become a universal way to select items to add to tags and other "list fields".

**Describe alternatives you've considered**
* Building my own are not as good as the sophisticated drop down list in the current tag picker, and I find it difficult to clone and build a second version.
* Hacking the existing macro has failed for me
* Making a separate tiddler picker faces the same complexity and is 90% the same code.

**Additional context**
Until a given title is already used as a tag, it can not be added as a tag from the drop down. 

Imagine for an example we had a wiki containing people tiddlers, each with a birth date. Then perhaps we want to tag the current person tiddler with its parents. 
* We could use the tag picker with a filter so the user can select from all the people tiddlers, with a birth-date before the current tiddler and they will be listed for selection as the current persons parent. This adding the parent tiddler as a tag to the current one.
* They can also be used to set a parents field or list, or any other desired fieldname, with the kin filter you would also be able to select a tag from a hierarchical list.
* There is value allowing both tag picking and other fields picking to be in the one macro to keep the code size small rather than creating a separate set of macros for a very similar purpose, and being able to filter the possible list of tags is powerful.

**Comment by pmario** [comment]
The new `tagListFilter` should do what you want. @AnthonyMuscio IMO this issue can be closed.

See: https://tiddlywiki.com/prerelease/#tag-picker%20Macro:%5B%5Btag-picker%20Macro%5D%5D%20%5B%5Btag-picker%20Macro%20(Examples)%5D%5D****

**Comment by AnthonyMuscio** [comment]
Closed as per tagListFilter in Prerelease 5.3.4 Thanks all.
