### ISSUE TITLE
[BUG] The color Field in 5.2.3 Works Different From 5.2.2-

### ISSUE THREAD

**Issue by kookma** [Jermolene/TiddlyWiki5#6802]
### Describe the bug

In TW 5.2.2 and before in edit mode you can select color field from drop down and then you are allowed to add color through a color picker.

In TW 5.2.3, you have to first add the color field with an empty value, then the color picker is available to choose the color.

### Expected behavior

I like 5.2.2 behavior. The color picker available.

### To Reproduce

1. Go to https://tiddlywiki.com/prerelease/
2. Click on add new tiddler
3. Scroll down to add fields at the bottom of tiddler
4. Select color for field name from drop down
5. See there is no color picker available

### TiddlyWiki Configuration

- Version [e.g. v5.1.24]
- Saving mechanism [e.g. Node.js, TiddlyDesktop, TiddlyHost etc]
- Plugins installed [e.g. Freelinks, TiddlyMap]

### Additional context

I suspect this is related to https://github.com/Jermolene/TiddlyWiki5/pull/6628

**Comment by kookma** [comment]
I realized if you enter a hex color code like `#ff0000` it works, but for other values like `red` or `#f00` it does not work.

**Comment by saqimtiaz** [comment]
@kookma the behaviour in 5.2.3 is supposed to be consistent with 5.2.1. The changes introduced to the editing of fields in 5.2.2 introduced several bugs and were therefore reverted.

Can you please confirm if the current behaviour is consistent with 5.2.1?

**Comment by kookma** [comment]
> Can you please confirm if the current behavior is consistent with 5.2.1?

Yes, TW5.2.3 works like TW 5.2.1 for this case, so this is intentional!
