### ISSUE TITLE
[BUG] Red Window of Death for $:/core/ui/ViewTemplate/body/rendered-plain-text

### ISSUE THREAD

**Issue by kookma** [Jermolene/TiddlyWiki5#6805]
### Describe the bug
In Tiddlywiki 5.2.3p
Try to opening [$:/core/ui/ViewTemplate/body/rendered-plain-text](https://tiddlywiki.com/prerelease/#%24%3A%2Fcore%2Fui%2FViewTemplate%2Fbody%2Frendered-plain-text)

cause the RSOD.

### Expected behavior

This tiddler can be displayed as code or plain text

### To Reproduce

1. Go to ['...'](https://tiddlywiki.com/prerelease)
2. Open $:/core/ui/ViewTemplate/body/rendered-plain-text
3. See the RSOD

### Screenshots

![image](https://user-images.githubusercontent.com/830394/180019344-b5a1d506-668f-4d09-915d-61fdd6b72a67.png)

### TiddlyWiki Configuration

TW 5.2.3

**Comment by Jermolene** [comment]
Thanks @kookma fix upcoming
