### ISSUE TITLE
[BUG] rendered-plain-text template gobbles up linebreaks

### ISSUE THREAD

**Issue by saqimtiaz** [Jermolene/TiddlyWiki5#6813]
### Describe the bug

The new $:/core/ui/ViewTemplate/body/rendered-plain-text template does not display double line breaks, i.e. insert an empty line,  when viewing CSS tiddlers which reduces the intended legibility improvements.

See https://tiddlywiki.com/prerelease/#%24%3A%2F_tw5.com-styles

![image](https://user-images.githubusercontent.com/68092/180383862-d9e14141-023f-48cb-8dde-5fc853a0f0ac.png)

### TiddlyWiki Configuration

- Version [e.g. v5.1.24]
- Saving mechanism [e.g. Node.js, TiddlyDesktop, TiddlyHost etc]
- Plugins installed [e.g. Freelinks, TiddlyMap]

**Comment by Jermolene** [comment]
Hi @saqimtiaz in one sense this is the expected behaviour; the purpose of this view is to show the stylesheets as seen by CSS, which means that the line breaks have been wikified out of existence. But of course it is not very friendly (although I notice that the syntax highlighting helps a lot).

I experimented by running the following snippet in dev tools:

```js
$tw.wiki.renderText("text/plain","text/vnd.tiddlywiki","{{$:/themes/tiddlywiki/snowwhite/base||$:/core/ui/ViewTemplate/body/rendered-plain-text}}")
```

The output shows that the wikification process removes the double line breaks:

```css
.tc-sidebar-header {\n\ttext-shadow: 0 1px 0 ;\n}.tc-tiddler-info {\n\t\n}@media screen {\n\t.tc-tiddler-frame {\n\t\t\n\t}\n}@media (max-width: 959px) {\n\t.tc-tiddler-frame {\n\t\t\n\t}\n}.tc-page-controls button svg, .tc-tiddler-controls button svg, .tc-topbar button svg {\n\t\n}.tc-tiddler-controls button.tc-selected,\n.tc-page-controls button.tc-selected {\n\t\n}.tc-tiddler-frame input.tc-edit-texteditor,\n.tc-tiddler-frame select.tc-edit-texteditor {\n\t\n}.tc-edit-tags {\n\t\n}.tc-tiddler-frame .tc-edit-tags input.tc-edit-texteditor {\n\t\n\tborder: none;\n\toutline: none;\n}textarea.tc-edit-texteditor {\n\tfont-family: ;\n}canvas.tc-edit-bitmapeditor  {\n\t\n}.tc-drop-down {\n\tborder-radius: 4px;\n\t\n}.tc-block-dropdown {\n\tborder-radius: 4px;\n\t\n}.tc-modal {\n\tborder-radius: 6px;\n\t\n}.tc-modal-footer {\n\tborder-radius: 0 0 6px 6px;\n\t;\n}.tc-alert {\n\tborder-radius: 6px;\n\t\n}.tc-notification {\n\tborder-radius: 6px;\n\t\n\ttext-shadow: 0 1px 0 rgba(255,255,255, 0.8);\n}.tc-sidebar-lists .tc-tab-set .tc-tab-divider {\n\tborder-top: none;\n\theight: 1px;\n\t\n}.tc-more-sidebar > .tc-tab-set > .tc-tab-buttons > button {\n\t\n}.tc-more-sidebar > .tc-tab-set > .tc-tab-buttons > button.tc-tab-selected {\n\t\n}.tc-message-box img {\n\t\n}.tc-plugin-info {\n\t\n}\n
```

I'm not sure the best solution. We could revert to showing the raw text, but then we lose the ability to easily see the CSS that is being processed. Or we could prettify the CSS on display, but that would seem to mean another library.

Or, perhaps we change the wikitext parsers so that in inline mode it leaves double line breaks alone, but that might present some backwards compatibility issues.

**Comment by saqimtiaz** [comment]
@Jermolene having had the opportunity to reflect on why I stopped what I was doing to create this issue, I realize the real concern from my perspective was that the display of the CSS led me try and debug what was wrong in the formatting of my CSS, i.e. the tiddler text.

Especially for casual users, it is a common problem that line-breaks do not appear as expected - either no line breaks or unexpected paragraph generation - and the answer is always that their tiddler content needs tweaking. It seems reasonable therefore to expect that other users may have the same reaction to the unexpected formatting of the CSS, that they are doing something wrong and need to debug their tiddler content.

Not a deal breaker by any means, but worth keeping in mind.

**Comment by Jermolene** [comment]
Thanks @saqimtiaz that makes perfect sense.

Another inconsistency that I just noticed is that the preview pane shows the old view. The obvious fix would be to use the view template body cascade in the preview pane, but that would have side effects I guess.

I don't have any objection to reverting the view template body change, and just retaining the improvements to the control panel stylesheet listing.

**Comment by saqimtiaz** [comment]
> I don't have any objection to reverting the view template body change, and just retaining the improvements to the control panel stylesheet listing.

I think this might be the best approach for the time being, and we can revisit the view template body change after 5.2.3

**Comment by Jermolene** [comment]
Hi @saqimtiaz on further reflection, I think the current behaviour may represent the lesser of two evils.

First, it's worth noting that the way that the stylesheet `$:/_tw5.com-styles` is displayed in v5.2.2 isn't much better than the screenshot in the OP. There are random code blocks, and no highlighting:

<img width="627" alt="image" src="https://user-images.githubusercontent.com/174761/181737144-89e1d772-3e07-4997-8973-b63bbd712c1b.png">

And v5.2.2 also collapses multiple line breaks into one.

One of the things that I find appealing about the current v5.2.3 behaviour is that it precisely mirrors the behaviour of wikitext tiddlers: by default one sees the rendered output, and clicks edit to see the source.

**Comment by Jermolene** [comment]
Hmmm one simple thing that might help is to rearrange the cascade so that authors can override the behaviour by adding a `code-body` field set to `yes` (that's not possible at present in v5.2.3).

**Comment by kookma** [comment]
Sorry for a side note:
Don't you think hide-body shall be the first in Cascade? If `hide-body=yes` then TW shall not proceed with other entries.

**Comment by Jermolene** [comment]
> Sorry for a side note:
> Don't you think hide-body shall be the first in Cascade? If `hide-body=yes` then TW shall not proceed with other entries.

That makes sense, I'll commit a fix shortly.

**Comment by simonbaird** [comment]
Maybe I'm missing something, but why are single line breaks preserved, and multiple line breaks removed? Wouldn't it make more sense to replace multiple line breaks with a single line break? That would solve the CSS rendering problem, right?

**Comment by Jermolene** [comment]
> Maybe I'm missing something, but why are single line breaks preserved, and multiple line breaks removed? Wouldn't it make more sense to replace multiple line breaks with a single line break? That would solve the CSS rendering problem, right?

All that's happening in v5.2.2 is the standard HTML whitespace coalescing rules: multiple runs of whitespace are merged to a single space.

In v5.2.3 the removal of double blank lines is the standard wikitext processing rules.

**Comment by kookma** [comment]
One example: I have a tiddler as below tagged with $:/tags/Stylesheet

```
.myclass {background-color:<<colour background>>;}

.yourclass{ font-weight:700;}
```

In view mode I see:

```
.myclass {background-color:#ffffff;}.yourclass{ font-weight:700;}
```

I prefer to see

```
.myclass {background-color:#ffffff;}
.yourclass{ font-weight:700;}
```

I realized, to remove the empty line to get the desired output! So for me

```
.myclass {background-color:<<colour background>>;}
.yourclass {font-weight:700;}
```

Produces

```
.myclass {background-color:#ffffff;}
.yourclass{ font-weight:700;}
```

**Comment by Jermolene** [comment]
Hi @kookma 

> I prefer to see

Indeed, the ideal thing would be to show a properly formatted, wikified version of the stylesheet. However we do not have a way to achieve that. There are two mutually exclusive goals here: to show the wikified output of the stylesheet, and to retain the original formatting.

I agree that the current behaviour of v5.2.3 is a big change, but I think it's important to note that in v5.2.2 and before the default rendering of stylesheets was also pretty useless, hence why so many people have taken to putting `code-body: yes` on their stylesheets. That will still work in v5.2.3.
