### ISSUE TITLE
[BUG] invalid path in tw5.com edition

### ISSUE THREAD

**Issue by saqimtiaz** [Jermolene/TiddlyWiki5#6819]
### Describe the bug

Working with the repository with Git or trying to install the master branch with npm install I am getting errors due the path for this file being invalid:
[editions/tw5.com/tiddlers/$:/editions/tw5.com/systemtag-template.tid](https://github.com/Jermolene/TiddlyWiki5/blob/master/editions/tw5.com/tiddlers/%24:/editions/tw5.com/systemtag-template.tid)

I cannot checkout the branch and therefore cannot make a PR. Deleting the offending directory via the Github directory may be one recourse open to us.

### TiddlyWiki Configuration

- Version [e.g. v5.1.24]
- Saving mechanism [e.g. Node.js, TiddlyDesktop, TiddlyHost etc]
- Plugins installed [e.g. Freelinks, TiddlyMap]

**Comment by saqimtiaz** [comment]
#6819 should resolve this, had to branch and create a PR via the GH interface which is rather painful.

**Comment by Jermolene** [comment]
Thanks @saqimtiaz 

This has happened a few times before. I wonder if we could introduce a test for valid filenames?
