### ISSUE TITLE
[IDEA] add support to --render for exporting to a single JSON file

### ISSUE THREAD

**Issue by kravlost** [Jermolene/TiddlyWiki5#6827]
**Is your feature request related to a problem? Please describe.**
The --render nodejs command doesn't support export to a single JSON file.

**Describe the solution you'd like**
If the filename filter is a fixed filename, the --render output should be a single JSON file containing an array of tiddlers in JSON format, rather than exporting every tiddler to the same filename so that its contents are those of the final matching tiddler.

**Describe alternatives you've considered**
None.

**Additional context**

**Comment by Jermolene** [comment]
Hi @kravlost it is actually possible to do render a single JSON file containing an array of tiddlers, but the approach is not at all obvious, and is not explicitly documented at present.

Here's an example:

```
tiddlywiki editions/tw5.com --render "." "tiddlers.json" "text/plain" "$:/core/templates/exporters/JsonFile" "exportFilter" "[tag[HelloThere]]"
```

The subtlety is that the first parameter identifying the tiddlers to be rendered is passed a dummy value; instead we use the template parameter to reference the template that we need, and then finally the last two parameters assign the filter of the tiddlers that we want to render to the "exportFilter" variable.

I'll look at adding a note to the docs.

**Comment by kravlost** [comment]
> Hi @kravlost it is actually possible to do render a single JSON file containing an array of tiddlers, but the approach is not at all obvious, and is not explicitly documented at present.
> 
> Here's an example:
> 
> ```
> tiddlywiki editions/tw5.com --render "." "tiddlers.json" "text/plain" "$:/core/templates/exporters/JsonFile" "exportFilter" "[tag[HelloThere]]"
> ```
> 
> The subtlety is that the first parameter identifying the tiddlers to be rendered is passed a dummy value; instead we use the template parameter to reference the template that we need, and then finally the last two parameters assign the filter of the tiddlers that we want to render to the "exportFilter" variable.
> 
> I'll look at adding a note to the docs.
> 
> 

Brilliant @Jermolene , thanks for the information!

**Comment by Jermolene** [comment]
Thanks for the prompt, it's a bit embarrassing that it wasn't documented

**Comment by kravlost** [comment]
@Jermolene I've just tried this using PowerShell 7.2.5 on Windows 10 and got an error:

```
tiddlywiki "WikiName" --render "." "tiddlers.json" "text/plain" "$:/core/templates/exporters/JsonFile" "exportFilter" "[!is[system]]"
ParserError:
Line |
   1 |  … "WikiName" --render "." "tiddlers.json" "text/plain" "$:/core/te …
     |                                                          ~~
     | Variable reference is not valid. '$' was not followed by a valid variable name character. Consider
     | using ${} to delimit the name.
```

**Comment by Jermolene** [comment]
Thanks @kravlost I'll update the docs to use single quotes for safety.
