### ISSUE TITLE
[IDEA] Markdown plugin to support wikitext links autocomplete

### ISSUE THREAD

**Issue by nicolnt** [Jermolene/TiddlyWiki5#6831]
**Is your feature request related to a problem? Please describe.**
The default tiddler supports internal link autocomplete (wikitext link)

**Describe the solution you'd like**
Integrate this tweak to support it in markdown tiddlers
https://groups.google.com/g/tiddlywiki/c/d3YxoeTgoOM/m/8w1WMaUmBAAJ

**Describe alternatives you've considered**
None at the moment

**Comment by saqimtiaz** [comment]
> The default tiddler supports internal link autocomplete (wikitext link)

The autocomplete behaviour is not provided by the TiddlyWiki core but rather by the EditCompText plugin.

Please close this issue and make the request at the repository for the plugin: https://github.com/snowgoon88/TW5-extendedit
