### ISSUE TITLE
[IDEA] Menu bar plugin Page controls: Save changes to indicate unsaved changes (color)

### ISSUE THREAD

**Issue by nicolnt** [Jermolene/TiddlyWiki5#6832]
**Is your feature request related to a problem? Please describe.**
I regret that in the "Page controls" option in the Menu bar plugin it doesn't change the "Save changes" icon color like TW does in the default toolbar.

Default TW toolbar when some changes are not saved
![image](https://user-images.githubusercontent.com/12377588/181213067-538bb513-af5e-4677-9308-daadefbf4a21.png)

Default Menu bar Page controls even when some changes are not saved
![image](https://user-images.githubusercontent.com/12377588/181212946-4e0f6f86-3f96-4de6-923d-477b47d63067.png)

**Describe the solution you'd like**
Change icon color when some changes need to be saved
![image](https://user-images.githubusercontent.com/12377588/181213526-6a28f7de-e92f-497e-a6ed-bf0f541d07c8.png)

**Comment by Jermolene** [comment]
Thank you @nicolnt, good catch. Fix is coming up momentarily.

**Comment by Jermolene** [comment]
The fix will be part of the next release, but you can preview it as part of the prerelease here:

https://tiddlywiki.com/prerelease/

(It will take approximately 10 minutes to rebuild as I write this)

**Comment by nicolnt** [comment]
> The fix will be part of the next release

I didn't expect it to be fixed that fast, you rock!

**Comment by Jermolene** [comment]
> I didn't expect it to be fixed that fast, you rock!

Thank you @nicolnt! Happily there's quite a big class of bugs that are just oversights, and relatively straightforward to fix. The tricky thing is identifying them and reporting them, so thank you for that!
