### ISSUE TITLE
[BUG] Docs for list-after Needs Improvement

### ISSUE THREAD

**Issue by kookma** [Jermolene/TiddlyWiki5#6836]
### Describe the bug

Read: https://tiddlywiki.com/#Order%20of%20Tagged%20Tiddlers

* In each remaining tiddler `T`, look for a `list-before` field. If this has a tiddler title as its value, place `T` just before that one.
  * As a special case, if the field exists but its value is empty, place `T` at the very start of the list.

I think this special case is also valid for `list-after` as below

> 
> * In each remaining tiddler `T`, look for a `list-after` field. If this has a tiddler title as its value, place tiddler `T` just after that one.
>   * As a special case, if the field exists but its value is empty, place `T` at the very end of the list.
> 

### TiddlyWiki Configuration

- Version [e.g. v5.2.3]

### Additional context

If this is correct let me to submit a PR.

**Comment by Jermolene** [comment]
Thanks @kookma – perhaps @rmunn could comment as you've been doing some updates here?

**Comment by rmunn** [comment]
https://github.com/Jermolene/TiddlyWiki5/pull/3219 implemented that change (if `list-after` is empty, then `T` goes at the end of the list), and that's still how it works. So yes, that change to the "Order of Tagged Tiddlers" documentation would be correct. Good idea; go ahead and submit the PR.

**Comment by kookma** [comment]
@rmunn 
Thank you Robin! I submit the PR.

**Comment by kookma** [comment]
Addressed here: https://github.com/Jermolene/TiddlyWiki5/commit/1acad41574ef86ff68e92fea1f91db4cd28988a5
