### ISSUE TITLE
[Proposal] decouple "retain story order" button from translatable texts with a new config tiddler

### ISSUE THREAD

**Issue by pmario** [Jermolene/TiddlyWiki5#6848]
## The Problem

While working on a new plugin to create an "Empty Story River" backdrop view, that allows users to click the "Home Button" I found the following problem. 

To reproduce.

- open https://tiddlywiki.com
- Open the https://tiddlywiki.com/#%24%3A%2FControlPanel
- Click the "retain story ordering" button in the DefaultTiddlers section

So your defaultTiddlers should look like this: `[list[$:/StoryList]]` --> Everything is OK. 

- Now Close all tiddlers --> Story list is empty. 
- Click -- Right Sidebar : Tools : Home Button ----> nothing happens ---> go on reading

The function is OK, but changing the behaviour of the "retain story ordering" button is hard for plugin authors because

[$:/language/ControlPanel/Basics/DefaultTiddlers/BottomHint](https://github.com/Jermolene/TiddlyWiki5/blob/e849aaab4db951e62089ac57484b1592ea89802a/core/language/en-GB/ControlPanel.multids#L10) ... Is hardcoded and translatable. So If I would like to change the behaviour of the button, I need to overwrite this core tiddler, and I loose the language switching possibility for that button.

The existing code is: 

```
Use &#91;&#91;double square brackets&#93;&#93; for titles with spaces. Or you can choose to <$button set="$:/DefaultTiddlers" setTo="[list[$:/StoryList]]">retain story ordering</$button>
```

## The proposed code is:

```
Use &#91;&#91;double square brackets&#93;&#93; for titles with spaces. Or you can choose to <$button set="$:/DefaultTiddlers" setTo={{$:/config/ControlPanel/Basics/DefaultTiddlers/setTo}}>retain story ordering</$button>
```

Advantages

 - Everyone can change the behaviour of the button, without loosing all translations
 - Plugin authors can change the button to set defaultTiddlers to eg: `[list[$:/StoryList]] ~GettingStarted` 
   - The setting above will open the GettingStarted tiddler if the StoryList is empty
 - Since some pages may have a different tiddler that may be shown eg: tiddlywiki.com ... It could be set to `[list[$:/StoryList]] ~HelloThere` 

The only thing that's needed is a new config tiddler, which may be part of the HiddenSettings

@Jermolene 
A PR that adjusts all ControlPanel.multids files for all languages can follow if you are willing to merge it.

**Comment by Jermolene** [comment]
Thanks @pmario, an interesting problem.

I'd prefer the string to be:

```
Use &#91;&#91;double square brackets&#93;&#93; for titles with spaces.
Or you can choose to <<retain-story-order-button "retain story ordering">>
```

That wouldn't help you override the functionality of the button, so how about this:

```
Use &#91;&#91;double square brackets&#93;&#93; for titles with spaces. Or you can choose to {{retain story ordering||$:/snippets/retain-story-ordering-button}}
```

**Comment by pmario** [comment]
hmm, I think both versions can work. So the code of both implementations would look as follows. 

I personally would prefer the first one, since it's easier for translation authors, to understand what should be translated. .. The strings

For the second example the translator needs to know that the first element of the transclusion needs to be translated.

```
title: find-a-macros-tiddler-to-add-you
tags: $:/tags/Macro

\define retain-story-order-button(text)
<$button set="$:/DefaultTiddlers" setTo={{$:/config/ControlPanel/Basics/DefaultTiddlers/setTo}}><<__text__>></$button>
\end
```

or

```
title: $:/snippets/retain-story-ordering-button

<$button set="$:/DefaultTiddlers" setTo={{$:/config/ControlPanel/Basics/DefaultTiddlers/setTo}} ><<currentTiddler>></$button>
```

**Comment by Jermolene** [comment]
> I personally would prefer the first one, since it's easier for translation authors, to understand what should be translated. .. The strings

I agree, but I don't much like having to make the macro be yet another global. That wouldn't be a problem with #6666.

In the meantime, translating the transclusion still seems clearer than figuring out which bits of `<$button set="$:/DefaultTiddlers" setTo="[list[$:/StoryList]]">retain story ordering</$button>` need translating.
