### ISSUE TITLE
[BUG] Switching between plugin libraries causes error if two are open and first one is subsequently closed

### ISSUE THREAD

**Issue by bp1189** [Jermolene/TiddlyWiki5#6855]
### Describe the bug

When using multiple plugin libraries, an error is produced if you open one, open the second one, and then go back and close the first one. I was able to generate the error in 5.2.2 and 5.2.3.

The error is: 

Internal JavaScript Error
Uncaught TypeError: Cannot read properties of undefined (reading 'getAttribute')

This is my first time filing a bug on GitHub, so please let me know if I am missing any information or if there is anything else you need from me. 

### Expected behavior

Selected plugin library should close.

### To Reproduce

1. Go to https://tiddlywiki.com/prerelease/
2. Open the control panel
3. Go to the Plugins tab
4. Click "Get More Plugins"
5. Go to the official plugin library tab
6. Click "open plugin library"
7. Go to the SQ plugin library tab
8. Click "open plugin library"
9. Go back to the official plugin library
10. Click  "Close Plugin Library"
11. See error

### TiddlyWiki Configuration

- Version [5.2.2, 5.2.3]
- Saving mechanism [default download saver]
- Plugins installed [default (reproducible on TiddlyWiki.com]

### Desktop (please complete the following information):

- OS: [Chrome OS]
- Browser [Chrome]
- Version [103.0.5060.61]

### Smartphone (please complete the following information):

- Device: [Pixel 4a5g]
- OS: [Android 12]
- Browser [Chrome]
- Version [103.0.5060.129]

**Comment by pmario** [comment]
Thanks for the info!

I can confirm the problem with FF on Windows. May be we need to add an action, that closes the open library if the tab is changed. So the problem can't happen anymore.

**Comment by Jermolene** [comment]
Thanks @bp1189, much appreciated. I've just committed a fix in 667da96c970283cbf0fc2b3672fba3812886be65  which will be available on https://tiddlywiki.com/prerelease in a few minutes.

**Comment by bp1189** [comment]
Thanks, @Jermolene !
