### ISSUE TITLE
[BUG] Typo in ListWidget.tid

### ISSUE THREAD

**Issue by amreus** [Jermolene/TiddlyWiki5#6859]
### Describe the bug

The word can is repeated twice.

https://github.com/Jermolene/TiddlyWiki5/blob/a3b294470f1a61faf560988d96d62d37e9dc1dae/editions/tw5.com/tiddlers/widgets/ListWidget.tid#L120

### TiddlyWiki Configuration

current tiddlywiki.com

**Comment by Jermolene** [comment]
Thanks @amreus
