### ISSUE TITLE
[BUG] Typo in How to customize TiddlyDesktop.tid

### ISSUE THREAD

**Issue by amreus** [Jermolene/TiddlyWiki5#6860]
### Describe the bug

The word "is" is repeated.

https://github.com/Jermolene/TiddlyWiki5/blob/a3b294470f1a61faf560988d96d62d37e9dc1dae/editions/tw5.com/tiddlers/howtos/How%20to%20customize%20TiddlyDesktop.tid#L11

### TiddlyWiki Configuration

current tiddlywiki.com

**Comment by Jermolene** [comment]
Thanks @amreus
