### ISSUE TITLE
[IDEA] Markdown-like [x] Wikitext Syntax for Checklist/Todolist

### ISSUE THREAD

**Issue by kookma** [Jermolene/TiddlyWiki5#6865]
**Is your feature request related to a problem? Please describe.**
Markdown support checklist/todolist syntax like GitHub Markdown

> For example
> 
> - [ ] Not finished item
> - [x] Finished item

In Tiddlywki there are several plugins support this

1. Shiraz using table-csv 
1.1. static checklist (first example in https://kookma.github.io/TW-Shiraz/#demo%2Fquick-table-taskify)
1.2. dynamic checklist (second example https://kookma.github.io/TW-Shiraz/#demo%2Fquick-table-taskify)
3. Kara using macro checklist (example https://kookma.github.io/TW-Kara/#A%20Simple%20Checklist)

The below plugin from @tgrosinger uses JS

3.  https://tgrosinger.github.io/tw5-checklist/

**Describe the solution you'd like**
I propose Tiddlywiki can have a simple Wikitext syntax as Markdown as below
* every line start with `[]` or `[ ]` represents an unfinished item
* every line start with `[x]` represents an unfinished item

**Describe alternatives you've considered**
The above examples can help to accelerate the implementation

**Additional context**
* No UI is required
* Only Wikitext syntax is required
* New syntax can be used for creating simple, plain in tiddler checklist

**Comment by pmario** [comment]
I think if there are already different solutions with plugins, there is no real need for it to be part of the core. Plugin authors can react much more flexible to user requests, than the TW core. 

For some very very basic list handling you can do this. 

*.todo some text
*.done some other text

See [some German examples](https://tiddlywiki.com/languages/de-AT/index.html#Task%20Management%20mit%20Listen:list-check.svg%20list-task.svg%20list-done.svg%20%5B%5BTask%20Management%20mit%20Listen%5D%5D%20%24%3A_TaskStylesheet) ... The very last paragraph. ... Which needs the right SVGs and some CSS ... 

That's very basic but it works out of the box.

**Comment by Jermolene** [comment]
Hi @kookma Markdown style `[x]` checkboxes seem like an attractive idea.

However, there are implementation difficulties. For example, how would one handle this:

```
\define left-bracket() [
\define right-bracket() ]
<$let todoItem={{{ [<left-bracket>addsuffix[ ]addsuffix<right-bracket>addsuffix[This is a todo list item }}}}>
<<todoItem>>
</$let>
```

The point being that wikified text doesn't always have a straightforward mapping to a source tiddler.

Another issue is that there's no easy way to reach into a tiddler to determine the status of a particular todo item. That makes it harder to make summaries etc.

**Comment by pmario** [comment]
For more specific usecases I would prefer some GettingStarted plugins similar to this one: https://u9t.github.io/editions/MDUe_basis/

Which contains some options for users to choose from. ... The GettingStarted is relatively straight forward. ... 

What's missing is a TiddlyWiki based interactive introduction system, similar to the [tutorial maker](to: https://talk.tiddlywiki.org/t/tiddlywiki-tutorial-maker/2407) you mentioned. 

So we could "lead" new users with some explanation texts, but they could use their own pace. 

It would also be possible to have some super short videos, much shorter as the following one, that can explain actions, but with text and video

![getting-started-howto](https://user-images.githubusercontent.com/374655/182111055-622c1205-7a24-4257-83c8-4f9bf84951bb.gif)

**Comment by kookma** [comment]
Thank you for clarification!
Should I close this idea?

**Comment by Jermolene** [comment]
> Thank you for clarification!
> Should I close this idea?

Yes. I've tweaked the title to make it easier to find in the future.

**Comment by kookma** [comment]
Thank you!
