### ISSUE TITLE
[IDEA] Filter run prefix `:mapif` or `:map-if` that applies changes selectively

### ISSUE THREAD

**Issue by rmunn** [Jermolene/TiddlyWiki5#6891]
**Is your feature request related to a problem? Please describe.**
When writing filter runs, I often find myself wanting to apply logic like "change only the titles that match condition X, and leave other titles untouched". For example, I might want to add the `$:/rmunn/my-namespace` prefix to a list of titles, but only if the titles don't already contain that prefix. Or only to the titles starting with the letter M. Or some other condition.

**Describe the solution you'd like**
I'd like to have a new filter run prefix, possibly called `:map-if` (or `:mapif` if hyphens in filter operator names would cause parsing issues), that would work much like the `:map` prefix does, except for how it handles filters that return an empty list as a result. The `map` prefix documentation says "Filter runs used with the `:map` prefix should return at least the same number of items that they are passed. Any missing entries will be treated as an empty string." What I'd like is for an empty result to mean "insert the original title unchanged".

E.g., to add prefix `X` only to titles that don't already start with X, I would write the filter `:map-if[!prefix[X]addprefix[X]]`. Then the input `AA BB XX YY" would produce the output "XAA XBB XX XYY", because when `:map-if` ran that filter against `XX` the `!prefix[X]` filtered it out, and so the original string was passed through unchanged.

**Describe alternatives you've considered**
Currently, to do something like this requires multiple steps. First I save the current list in a variable, then I apply two filters to that variable, one selecting for condition C and one selection for not-C. Then I apply a `:map` operation to the list that was selected for condition C, and then I concatenate the result with the not-C result to get the final output.

But this contains several steps, and it also ends up changing the order of the input titles (which often doesn't matter, but sometimes it does). So to get the original order back, I have to have a further step that uses `sortby` to try to reproduce the original order. The `:map-if` prefix I'm envisioning would preserve the original order of the input titles.

**Comment by saqimtiaz** [comment]
`:map[has[status]then{!!caption}else<currentTiddler>]`

You can always return the original value if the condition isnt met, I follow this pattern often.

Do you have examples of use cases where this would not suffice?

**Comment by rmunn** [comment]
I missed the fact that `else<currentTiddler>` would do exactly what I need. I think I was thinking about how the input title would be blank by the time you get to the `else` expression inside a `:map`, and didn't realize that it had been saved in the `currentTiddler` variable.

I don't have any use cases that would need a special prefix after all; `else<currentTiddler>` will do the trick very nicely for every use case I was thinking of. I'll close the issue, and reopen it if I think of anything where `else<currentTiddler>` wouldn't work.
