### ISSUE TITLE
[IDEA] Users should be able to use custom icons for the TOC open and closed indicators

### ISSUE THREAD

**Issue by pmario** [Jermolene/TiddlyWiki5#6907]
At the moment it's needed to overwrite the core toc macros, if users want their own open and closed icons, instead of the default ones. 

eg:
![image](https://user-images.githubusercontent.com/374655/184658325-9f83e336-33bf-4e2f-8d46-74522adadd6d.png)

It may be possible to define 2 variables at the beginning of the toc-macros

```
\define closed-icon() $:/core/images/right-arrow
\define open-icon() $:/core/images/down-arrow
```

Instead of using them with `{{$:/core/images/right-arrow}}` it should be possible to use them with `<$transclude tiddler=<<closed-icon>> mode="inline"/>`

So users should be able to overwrite these 2 variable before they call the toc-macros. So their variables should be used. 

No code tested yet. Just a proposal

**Comment by pmario** [comment]
It should work as proposed. @Jermolene ... Do you think that makes sense?

![image](https://user-images.githubusercontent.com/374655/184665013-7f4ca5a2-f78a-4520-92fb-00e96e03d0c5.png)

**Comment by Jermolene** [comment]
> It should work as proposed. @Jermolene ... Do you think that makes sense?

Thank you @pmario yes that's a good idea.

**Comment by joshuafontany** [comment]
> > It should work as proposed. @Jermolene ... Do you think that makes sense?
> 
> Thank you @pmario yes that's a good idea.

May I suggest we have or make a `selected-icon` for the tab header currently selected, and maybe a `focus-icon` for the tab in focus? I think this would open up a lot of UI ideas. Maybe as a separate feature PR.

**Comment by pmario** [comment]
>May I suggest we have or make a selected-icon for the tab header currently selected, and maybe a focus-icon for the tab in focus? I think this would open up a lot of UI ideas. Maybe as a separate feature PR.

The OP is about the "Table of Contents" macro. .. You seem to suggest to change elements "Tabs Macro" ... At least it looks like that for me. ... If it is about tabs, I thin a new issue should be created.

**Comment by joshuafontany** [comment]
Sorry, just a wring word choice. "Node" would have been better. I was,tracking the UI Focused Element conversation & it made me think if 2 more states for the ToC. I'll look into how feasible that is.
