### ISSUE TITLE
[BUG] Inconsistency in Naming of Color field and Colour Parameter

### ISSUE THREAD

**Issue by kookma** [Jermolene/TiddlyWiki5#6911]
### Describe the bug

While the field name for color is color, but the `tag-pill-body` in `$:/core/macros/tag`  for the this field uses `colour` attribute.

This causes troubles in programming! As it took me hours to find the source of this error in Shiraz dynamic table.

### Expected behavior

I may recommend to use consistent name! color.

### TiddlyWiki Configuration

- Version [e.g. v5.2.3]

**Comment by pmario** [comment]
The name "colour" is used 1772 times all over the places. ... So it's very unlikely, that we are able to change that.

**Comment by Jermolene** [comment]
Hi @kookma the inconsistency is unfortunate. We're stuck with the "color" field, but otherwise I've been trying to stick with "colour" wherever we can.

**Comment by kookma** [comment]
Thank you for clarification!
