### ISSUE TITLE
[BUG] In markdown tiddlers, `div`s within a table cell get wrapped into a paragraph

### ISSUE THREAD

**Issue by MaxGyver83** [Jermolene/TiddlyWiki5#6916]
### Describe the bug

In markdown tiddlers, `div`s within a table cell get wrapped into a paragraph.

I have defined these two macros:

```
\define v() <div style="color:green" class="cell positive">✔</div>
\define x() <div style="color:red" class="cell negative">✘</div>
```

Plus these CSS rules:

```css
/* Colored table cells */ /* compensating the cell padding */
.cell { margin:-1px -7px; padding:1px 7px; }
.positive { background-color:#afa; }
.negative { background-color:#faa; }
```

I use this in tables like that:

```
|         |True   |False  |h
|property | <<v>> | <<x>> |
```

And it gets rendered like this:

![2022-08-19 11 34 53 216x72 Region](https://user-images.githubusercontent.com/13970628/185618964-5439204c-f69a-486e-9214-ec74c5bc3583.png)

HTML:

```html
<tbody>
  <tr class="oddRow">
    <td align="left">property</td>
    <td align="center">
      <div style="color:green" class="cell positive">✔</div>
    </td>
    <td align="center">
      <div style="color:red" class="cell negative">✘</div>
    </td>
  </tr>
</tbody>
```

The same table migrated to Markdown:

```
|         |True   |False  |
|---------|-------|-------|
|property | <<v>> | <<x>> |
```

It gets rendered like this:

![2022-08-19 14 32 53 214x103 Region](https://user-images.githubusercontent.com/13970628/185619102-fa614132-553c-437b-a449-032f3d2f13af.png)

HTML:

```html
<tbody>
  <tr>
    <td>property</td>
    <td>
      <p>
        <div style="color:green" class="cell positive">✔</div>
      </p>
    </td>
    <td>
      <p>
        <div style="color:red" class="cell negative">✘</div>
      </p>
    </td>
  </tr>
</tbody>
```

### Expected behavior

I expect that a `<<v>>` in a table looks the same in a markdown and a WikiText tiddler.

### To Reproduce

1. Install the markdown plugin
2. Add a macro tiddler with this content:
```
\define v() <div style="color:green" class="cell positive">✔</div>
\define x() <div style="color:red" class="cell negative">✘</div>
```
3. Add these CSS rules to a CSS tiddler:
```css
/* Colored table cells */ /* compensating the cell padding */
.cell { margin:-1px -7px; padding:1px 7px; }
.positive { background-color:#afa; }
.negative { background-color:#faa; }
```
4. Create a markdown tiddler with this content:
```
|         |True   |False  |
|---------|-------|-------|
|property | <<v>> | <<x>> |
```
5. Save tiddler and see how it gets rendered

### Screenshots

![2022-08-19 14 32 53 214x103 Region](https://user-images.githubusercontent.com/13970628/185619102-fa614132-553c-437b-a449-032f3d2f13af.png)

### TiddlyWiki Configuration

- Version: v5.2.3
- Saving mechanism: Node.js
- Plugins installed: Markdown

### Desktop (please complete the following information):

- OS: Arch Linux
- Browser: Firefox
- Version: 103.0.2 (64-bit)

**Comment by pmario** [comment]
Thx for the very detailed report. 

I did a fast test at https://tiddlywiki.com/plugins/tiddlywiki/markdown/ with the default settings and it seems to work as expected. 

But I think, there is something wrong with your MD table syntax. Are you sure it's used that way?

Which MD settings do you use. Are there any additional MD plugins?

![image](https://user-images.githubusercontent.com/374655/185627550-17bf2484-4da4-4f4c-9182-2dbf5b6f95e0.png)

**Comment by MaxGyver83** [comment]
Although you tested at https://tiddlywiki.com/plugins/tiddlywiki/markdown/, your screenshot looks like you created a regular WikiText tiddler. When you create a Markdown tiddler (by clicking on ![image](https://user-images.githubusercontent.com/13970628/185629331-848ccebd-3069-4ed4-94e9-66db200ad34e.png)), it shows `Type: text/x-markdown` below the tiddler content. .... I just saw your edit.

**Comment by pmario** [comment]
It's a known problem, that the TW wikitext parser creates a bit too many P tags. .. When the MD parser sees the macros, which it doesn't know, it handles it over to the TW parser. 

The TW parser just sees the macro and has no idea, that it is in a MD table context, so it covers it with a P tag. Which is normally the right thing to do, but in this case it's not. 

There won't be a fast fix, but it should be possible to create a CSS rule, that removes the `margin-top` and `margin-bottom` from the P tag in the table ... I'm experimenting atm

**Comment by MaxGyver83** [comment]
Thanks for your quick answer and explanation. I imagined it would work in a way that the TW parser did the preprocessing and would hand over something like this to the Markdown parser:

```
|         |True   |False  |
|---------|-------|-------|
|property | <div style="color:green" class="cell positive">✔</div> | <div style="color:red" class="cell negative">✘</div>
 |
```

**Comment by pmario** [comment]
This works for me

```
.cell {
  margin: -14px -7px;
  padding: 1px 7px;
}
```

**Comment by MaxGyver83** [comment]
Thank you. But then I should not mix WikiText and Markdown tiddlers because with your CSS it looks strange in WikiText tiddlers:

![image](https://user-images.githubusercontent.com/13970628/185633028-ee0f9c0f-e4cc-4dc8-a56c-4d7633e48ab4.png)

**Comment by MaxGyver83** [comment]
> There won't be a fast fix, but it should be possible to create a CSS rule, that removes the margin-top and margin-bottom from the P tag in the table

Maybe this approach is better because it wouldn't affect WikiText tiddlers!?

**Comment by pmario** [comment]
>Maybe this approach is better because it wouldn't affect WikiText tiddlers!?

Yea, If you want to use the same macros for wikitext and MD the CSS will be a bit more complex. It should be doable.

Use this CSS

```
/* Colored table cells */ /* compensating the cell padding */
.cell { margin:-14px -7px; padding:1px 7px; }
.positive { background-color:#afa; }
.negative { background-color:#faa; }

.tw .cell { margin:-1px -7px; padding:1px 7px; }
```

The last line fixes the MD "hack"

Use this table for TW syntax, which defines the `tw` class to the table 

```
|tw|k
|         |True   |False  |h
|property | <<v>> | <<x>> |
```

**Comment by MaxGyver83** [comment]
Thanks again.

When I use this CSS, I don't even need to add the `tw` class to all existing tables:

```css
.cell { margin:-1px -7px; padding:1px 7px; }
td p { margin:0; }
```

**Comment by pmario** [comment]
If the problem is solved, you should close the issue.

**Comment by MaxGyver83** [comment]
OK, I close it although the underlying bug still exists. If somebody else is affected they can reopen it.

**Comment by pmario** [comment]
>OK, I close it although the underlying bug still exists. If somebody else is affected they can reopen it.

There are several issues that "talk" about the creation of redundant HTML P tags. The latest one is this one:  **[BUG] Slotted transclusion - no way to remove P tag** #6687 

I think I did track the problem down to 1 line in the parser, that uses a "wrong" logical assumption. It covers a newly created HTML block level element like an eg: DIV into a redundant P tag, which actually is invalid HTML code. Even if browsers are very forgiving here, it causes all sorts of problems with CSS stylesheets or the one you experience. 

The problem is a bit hard to fix, because there is a lot of manual work involved and it may result in some problems with backwards compatibility in the TW UI itself. That's usually a "red flag" for TW devs.

**Comment by MaxGyver83** [comment]
I have tested this one in <https://cdruan.github.io/TiddlyWiki5/>, too. No surrounding **p** tag.
So apparently, #6528 fixes this.

**Comment by pmario** [comment]
>So apparently, https://github.com/Jermolene/TiddlyWiki5/pull/6528 fixes this.

OK .. You should hop over to the PR and bump it ;)
