### ISSUE TITLE
[BUG] Menu bar plugin & ContextPlugin: search is not working in Menu bar

### ISSUE THREAD

**Issue by nicolnt** [Jermolene/TiddlyWiki5#6918]
### Describe the bug

_Not sure if it has something to do with TiddlyWiki's Menu Bar or ContextPlugin_

**Where**

Menu bar plugin, context search feature

**Problem**

Searching into context is not working, it doesn't take entered text in the Menu bar search bar into account.

Surprisingly it's connected to the side bar PageControls search field.

**Attached screenshots**

### Menu bar not taking keyword into account

![image](https://user-images.githubusercontent.com/12377588/185662802-4addefdc-85cf-469d-8847-bd3fdf4aac91.png)

### Menu bar search taking the wrong search into account

![image](https://user-images.githubusercontent.com/12377588/185664651-4a3b0151-705e-41dd-a50b-5f150a6e2ab8.png)

### Expected behavior

Menu bar search being independent from the side bar search.

### To Reproduce

1. Install ContextPlugin
2. Activate Menu bar
3. Click the search input in the Menu bar and Context 
4. Try to search
5. Tiddler list stays unchanged (eg. not filtered)
6. Type something in sidebar search and start again at step 3.

### TiddlyWiki Configuration

**Versions**
- TiddlyWiki version : 5.2.3
- Menu Bar version : 5.2.3
- ContextPlugin 2.1.0

### Desktop (please complete the following information):

- OS: Debian 11
- Browser Firefox 101.0

**Comment by Jermolene** [comment]
Hi @nicolnt thanks for the report. The Context Plugin is not part of the TiddlyWiki core distribution and so is not supported here. It would be better to post the report in the forum at https://talk.tiddlywiki.org/.

**Comment by nicolnt** [comment]
Posted on Context Plugin repo, see here: https://github.com/danielo515/TW5-contextPlugin/issues/21
