### ISSUE TITLE
[IDEA] Please add a option to to change tiddler title conveniently.

### ISSUE THREAD

**Issue by lilx2018** [Jermolene/TiddlyWiki5#6920]
I have 2000+ tiddlers in a file, everything seems good but if I need to change title, it take more than 20s to respones, it is totally unacceptable.

I do not know whether such a proposal is possible or not?

When change one tiddler's title,  popup an information dialog immediately before perform any long time various checks, with two button "change the title only (quick but maybe not safe)" and "change other associated titddlers with same tags and list fields ..."

**Comment by pmario** [comment]
Which TW version and which plugins do you use?

**Comment by lilx2018** [comment]
5.2.2-prerelease, 9 plugins. Actually I don't think it has anything to do with the version and plugins. From my understanding, it's only related to the number of tiddlers.

![image](https://user-images.githubusercontent.com/95909877/185742304-0534ae5a-d9cc-44c3-ab6f-ae1e55c76f69.png)

**Comment by Jermolene** [comment]
Thanks @lilx2018 I take it you are using the option `Update "oldtitle" to "newtitle" in the  tags and list fields of other tiddlers`?

![DB2A80D5-E769-42B5-9345-41A13A3FDB6F](https://user-images.githubusercontent.com/174761/185747510-d57dc59c-72c1-496b-8c16-52c55889b2d6.jpeg)

**Comment by lilx2018** [comment]
@Jermolene I hope it can popup a dialog immediately and I can make a choice to update title conveniently which only update its title. 

On my side, I must wait more than 20s (chrome tell me page has no response more the 3 times) to see the checkbox "Update HelloThere to HelloThere2 in tags and list fields of other tiddlers", it is too long time and I can't do anything but wait.

What I hope is that:
1. popup the option seletion immediately with no wait, the current situation is, I must wait 20s.
2. Provides a option to modify title quickly，if search and find what shall be simultaneously modify will spent lots of time, I can accept leave other tiddlers not update (maybe has invalid link, in my case, almost change 99% tiddler's are independent of each other, change it's title don't need to update any other tiddler's tag/fileds/...).

**Comment by lilx2018** [comment]
@Jermolene I hope it can popup a dialog immediately and I can make a choice to update title conveniently which only update its title. 

On my side, I must wait more than 20s (chrome tell me page has no response more the 3 times) to see the checkbox "Update HelloThere to HelloThere2 in tags and list fields of other tiddlers", it is too long time and I can't do anything but wait.

What I hope is that:
1. popup the option seletion immediately with no wait, the current situation is, I must wait 20s.
2. Provides a option to modify title quickly，if search and find what shall be simultaneously modify will spent lots of time, I can accept leave other tiddlers not update (maybe has invalid link, in my case, almost change 99% tiddler's are independent of each other, change it's title don't need to update any other tiddler's tag/fileds/...).

**Comment by Jermolene** [comment]
Hi @lilx2018 one solution would be make that checkbox more accessible. For example, create a tiddler with the tag `$:/tags/SideBarSegment` and the following content:

```
<$checkbox tiddler="$:/config/RelinkOnRename" field="text" checked="yes" unchecked="no" default="no">Update references to renamed tiddlers</$checkbox>
```

You should see a copy of the rename checkbox in the sidebar that you can access directly.

![ED1DCBD5-E939-43CF-B8CC-186AA4388759](https://user-images.githubusercontent.com/174761/185752768-0a3c1328-9bbe-49c2-8827-40aa3d861abe.png)

**Comment by lilx2018** [comment]
@Jermolene Thank you again, you solve me a very big problem. As your guidance，I see the checkbox on the sidebar, and I find if I set to not check , it popup the "Update xxx to yyy ... " almost immediately, not need to wait anymore.

**Comment by Jermolene** [comment]
Thanks @lilx2018 I am glad you got things working as you want.
