### ISSUE TITLE
"Add a new field" EditTextField shares too much state

### ISSUE THREAD

**Issue by ssokolow** [Jermolene/TiddlyWiki5#693]
In revision e3dc00573d9ea4db61e619b8f101168d1b4920a5, If you have two tiddlers in editing mode at the same time (eg. so you can manually copy various tag names and fields over), typing into one "Add a new field" field gets mirrored in the other.

As far as I can tell, that's because the EditTextField in question (inside `$:/core/ui/EditTemplate/fields`) is using `tiddler="$:/temp/newfieldname"` without incorporating QualifyMacro.

It looks like fixing it would just require changing three instances of `$:/temp/newfieldname` on lines 29 and 31 of `core/ui/EditTemplate/fields.tid` but I need to fix issues #680, #682, and #686 before I let myself get side-tracked figuring out how to share the same QualifyMacro output between three different locations.

**Comment by pmario** [comment]
3 years no fix and not many complains about it. Neither here nor in the group. So should we label it "flaw" instead of "bug" and close it?

**Comment by tobibeer** [comment]
I think it is quite an inconsistency that the same custom fields show up in various tiddlers being in edit mode... and more so, that if you decide to save the wrong one, you persist the wrong field along with it.

**Comment by Jermolene** [comment]
Per my comment above https://github.com/Jermolene/TiddlyWiki5/issues/693#issuecomment-49542333, we've now got the wikify widget so this could be fixed by anyone who feels strongly enough...

**Comment by BurningTreeC** [comment]
This could still be fixed :grin:

**Comment by pmario** [comment]
@Jermolene ... This issue doesn't exist anymore. We use different $:/temp variables now

**Comment by Jermolene** [comment]
Thanks @pmario
