### ISSUE TITLE
[IDEA] Full Customization of Tiddler Subtitle

### ISSUE THREAD

**Issue by kookma** [Jermolene/TiddlyWiki5#6937]
From TW 5.2.3, one can customize the tiddler subtitle without touching the core tiddler, but still there is one issue

See below image

<img src="https://user-images.githubusercontent.com/830394/188550012-102b4205-2078-4884-856b-57887febed60.png" alt="Smiley face" height="165" width="525">
Here I have put each piece of data in one line. This cannot be done with current configuration. Why? because the below two tiddlers are hardcoded:

$:/core/ui/ViewTemplate/subtitle/modified
$:/core/ui/ViewTemplate/subtitle/modifier

And according to `$:/core/ui/ViewTemplate/subtitle` those tiddlers are always listed. so I cannot remove them from listing without touching them (core tiddlers)

## Request
User can customize the subtitle without overriding the core tiddlers.

**Comment by kookma** [comment]
One solution is if there is a user define tiddler tagged with `$:/tags/ViewTemplate/Subtitle` then TW ignore listing the 
$:/core/ui/ViewTemplate/subtitle/modified
$:/core/ui/ViewTemplate/subtitle/modifier

User can add above tiddlers in his/her customization if required.

**Comment by amreus** [comment]
Would not a Cascade be an appropriate solution for this?

**Comment by pmario** [comment]
As far as I can see, that subtitle is defined using a list widget in line 7, which uses `$:/tags/ViewTemplate/Subtitle`

https://github.com/Jermolene/TiddlyWiki5/blob/9b7edfc1a78422676c20b770e370c5de2eec0e01/core/ui/ViewTemplate/subtitle.tid#L7-L12

The `$:/tags/ViewTemplate/Subtitle` looks like this: 

https://github.com/Jermolene/TiddlyWiki5/blob/9b7edfc1a78422676c20b770e370c5de2eec0e01/core/wiki/tags/ViewTemplateSubtitle.tid#L1-L2

So if you remove them from the list-field there, they should be gone, without the need to change the tiddlers themself. You only need to modify the list-field in the tag.

**Comment by Jermolene** [comment]
Hi @kookma 

I think this is a general problem; it is the same if one wished to hide view template segment like "title", "tags".

As things stand, the recommended mechanism for hiding core components is to override the tiddler. Are you finding problems with that approach?

> So if you remove them from the list-field there, they should be gone, without the need to change the tiddlers themself. You only need to modify the list-field in the tag.

That is not correct. The list field just determines the ordering of the tagged tiddlers, it has no role in determining which tiddlers carry the tag.

**Comment by pmario** [comment]
>That is not correct. The list field just determines the ordering of the tagged tiddlers, it has no role in determining which tiddlers carry the tag.

uups. ... You are right. I was confusing it with a mechanism that worked for one of my own templates. .. But it was a custom template.

**Comment by kookma** [comment]
> As things stand, the recommended mechanism for hiding core components is to override the tiddler. Are you finding problems with that approach?

Thank you @Jermolene.
I wish to customize the subtitle in a plugin! so I have to distribute the overridden core tiddlers. I always try to keep core tiddlers untouched, but if this is the only solution I will go for it.

One more question: As @amreus explained above, do you think a cascade mechanism for subtitle is good solution here?

**Comment by kookma** [comment]
Thank you @pmario
