### ISSUE TITLE
[BUG] Rendering Big Pdf Files Breaks The Page

### ISSUE THREAD

**Issue by FarukOzderim** [Jermolene/TiddlyWiki5#6940]
### Describe the bug

Rendering Big Pdf Files Breaks The Page and Tiddlywiki cannot render the pdf well.

### To Reproduce

Test it [here](https://farukozderim.github.io/pdf-cloud/#cse565-L2-Graph%20searching.pdf)

### Screenshots

<img width="711" alt="image" src="https://user-images.githubusercontent.com/44067394/188987883-952cc992-460e-4786-bfc1-8101fc248ffc.png">

### TiddlyWiki Configuration

html file and github pages

**Comment by pmario** [comment]
TW doesn't render PDFs it's the browser that does this. So its more a problem, that should be reported to the browser vendor. 

Do you have the same problem, if you open the PDF with the browser and not from within the wiki?

Since the PDF only has 22 pages, I think the PDF itself has a problem.

**Comment by Jermolene** [comment]
Hi @FarukOzderim @pmario the issue here is that TW renders embedded PDFs as base64 data URIs. Browsers struggle with long data URIs – in fact Chrome currently limits them to 1MB. For that reason, I wouldn't recommend trying to embed PDFs beyond very small ones. The alternative is to put the PDF files in a directory that can be referenced with a _canonical_uri tiddler.

**Comment by pmario** [comment]
It seems, you did embed your PDFs into the wiki itself. ... Is there a reason, why you didn't use _canonical_uri .. see: https://tiddlywiki.com/#How%20to%20embed%20PDF%20and%20other%20documents

**Comment by FarukOzderim** [comment]
Oh, I understand the problem now. I actually tried using _canonical_uri however github was not allowing me to fetch the pdf with the Web URL. And I did not know that I could also access files outside TW5 file from the directory. I can render it very easily now! And it also helped with decreasing the size of the TW5 file.

Thanks a lot @Jermolene and @pmario ❤️
