### ISSUE TITLE
[BUG] Checkbox in list mode breaks when listField is list

### ISSUE THREAD

**Issue by jc-ose** [Jermolene/TiddlyWiki5#6954]
### Describe the bug

I tried creating a list with checkboxes that when checked would insert the title of each checked item into the field “list”, implemented like this:

```
<$vars caller=<<currentTiddler>>  >
<ul>
<$list filter="[tag[Widgets]]">
<li><$checkbox tiddler=<<caller>> checked={{!!title}} listField="list" >
{{!!title}}
</$checkbox></li>
</$list>
</ul>
</$vars>
```

### Expected behavior

I expected the list field in the current tiddler to populate with each title per checked checkbox. If checkbox was unchecked, the title would be removed.

Instead, I got a JavaScript error after unchecking a checked item or checking multiple items.

This behavior seems to occur ONLY if I use the “list” field. Any other field appears to work as expected.

### To Reproduce

1. On tiddlywiki.com create a new tiddler 
2. Paste code above
3. Try clicking multiple checkboxes

### TiddlyWiki Configuration

- Version 5.2.4
- Saving mechanism: Irrelevant

### Desktop (please complete the following information):

- OS: Windows
- Browser: Chrome
- Version: 105

**Comment by Jermolene** [comment]
Thanks @jc-ose 

@rmunn is this related to the recent changes to the checkbox widget?

**Comment by Jermolene** [comment]
Thanks @rmunn!
