### ISSUE TITLE
[BUG] Tiddler "Tables in WikiText" broken?

### ISSUE THREAD

**Issue by MaxGyver83** [Jermolene/TiddlyWiki5#6955]
### Describe the bug

I just noticed that the tiddler "[Tables in WikiText](https://tiddlywiki.com/#Tables%20in%20WikiText)" seems to be broken. The rendering of some of the examples does not work:

![image](https://user-images.githubusercontent.com/13970628/192046981-ffcc4551-46ca-4726-9559-1c86c278af25.png)

### Expected behavior

I expect to see a rendered table here.

### To Reproduce

1. Go to https://tiddlywiki.com/#Tables%20in%20WikiText
2. See how some the examples don't get rendered correctly.

### TiddlyWiki Configuration

- Version: tiddlywiki.com

### Desktop (please complete the following information):

- OS: Arch Linux
- Browser: Firefox
- Version: 104.0.2 (64-bit)

### Smartphone (please complete the following information):

- Device: OnePlus Nord 2
- OS: Android 11
- Browser: Fennec (Firefox)
- Version: 104.1.0

**Comment by pmario** [comment]
Nice catch. .. There is a linebreak missing in the [wikitext-example-without-html macro](https://tiddlywiki.com/#%24%3A%2Feditions%2Ftw5.com%2Fwikitext-macros).

**Comment by Jermolene** [comment]
Thanks @MaxGyver83 @pmario
