### ISSUE TITLE
[IDEA] Add Snippets to Cascades ViewTemplateBodyFilters

### ISSUE THREAD

**Issue by kookma** [Jermolene/TiddlyWiki5#6964]
I may suggest to add snippets to `$:/config/ViewTemplateBodyFilters/system`
Snippets are tiddlers tagged with `$:/tags/TextEditor/Snippet`

These are like template and it is better to view as code!

**Comment by pmario** [comment]
@kookma -- Can you be more specific. As it is at the moment it's not really actionable. ATM I do have no idea what should be done, and how it should look like.

**Comment by kookma** [comment]
Hi @pmario 
This has been partially implemented. The OP states, show the content of snippet tiddlers through Cascades.
The current implementation uses `[prefix[$:/snippets/]]`  under `$:/config/ViewTemplateBodyFilters/system` to show them as system tiddler.

In this OP, I asked to use `[tag[$:/tags/TextEditor/Snippet]]` instead of `[prefix[$:/snippets/]]`.

But I am happy with current TW implementation. So, I close the this.
