### ISSUE TITLE
[BUG] Shortcut Alt+I Create a New Image Tagged with Journal

### ISSUE THREAD

**Issue by kookma** [Jermolene/TiddlyWiki5#6968]
### Describe the bug

Shortcut  <kbd>Alt+I</kbd> creates image tagged with Journal.

### Expected behavior

the `Journal` tag shall not be used.

### To Reproduce

1. Go to https://tiddlywiki.com/
2. Press <kbd>Alt+I</kbd>
3. A new image is created tagged with `Journal`

### Screenshots

`Journal` tag is the incorrect extra tag here.

### TiddlyWiki Configuration

- Version [e.g. v5.1.24]
- Saving mechanism [e.g. Node.js, TiddlyDesktop, TiddlyHost etc]
- Plugins installed [e.g. Freelinks, TiddlyMap]

### Desktop (please complete the following information):

- OS: Windows 10
- Browser Edge/Chrome 105
- Version TW 5.2.3

**Comment by pmario** [comment]
That's probably a "copy / paste" problem. ALT-J is create new Journal. ... which may have been used to create the ALT-I shortcut.

**Comment by pmario** [comment]
The responsible code is in tiddler: $:/core/ui/Actions/new-image .. 

@BurningTreeC ... do you remember the PR #3512  ... I think it was a copy/paste problem. But I'm not sure if it was intentional. ...

**Comment by Jermolene** [comment]
Thanks @kookma @pmario.
