### ISSUE TITLE
[BUG] SelectWidget class doesn't update if it uses a filter and the expected filter result changes

### ISSUE THREAD

**Issue by EvidentlyCube** [Jermolene/TiddlyWiki5#6986]
### Describe the bug

Create a SelectWidget with the `class` attribute value being a filter that depends on the value set by the select.

### Expected behavior

The widget's class should update if the result of the filter changes.

### To Reproduce

1. Open https://tiddlywiki.com/empty.html
2. Create an empty tiddler with the contents being set to the contents of the first comment in this issue.
3. Observer that all Selects correctly start with black color.
4. Change any of the Selects and notice that they don't change color. The filter results are updated though, as can be seen in the bullet list.
5. Close and reopen the tiddler and notice that the colors have updated.

## Starting state, everything is correctly black:
![image](https://user-images.githubusercontent.com/4552000/195820798-bed618ff-add6-463b-8bf0-81b7491ee804.png)

## Colors have not changed despite filters returning new values:
![image](https://user-images.githubusercontent.com/4552000/195820874-db5eccbf-6b40-47d8-a13b-0e50ccdb9c5f.png)

## Colors are updated after closing and reopening the tiddler:
![image](https://user-images.githubusercontent.com/4552000/195820921-a73157b8-0202-49ed-a284-18b361a7db38.png)

### TiddlyWiki Configuration

- **Version** 5.2.3
- **Saving mechanism:** None:
- **Plugins installed:** None

### Desktop 

- **OS:** Windows 10
- **Browser:** Chrome
- **Version:** Version 106.0.5249.103 (Official Build) (64-bit)

**Comment by EvidentlyCube** [comment]
The tiddler I used for testing:
``` 
<style>
.red {
    color: red;
}
.blue {
    color: blue;
}
.black {
    color: black;
}
</style>

* Color 1: {{{ [{!!select-color-1}] }}}
* Color 2: {{{ [{!!select-color-2}] }}}
* Color 3: {{{ [{!!select-color-3}] }}}

<$select 
    class={{{ [{!!select-color-1}] }}}
    field="select-color-1"
    default="red"
>
<option value="red">Red</option>
<option value="blue">Blue</option>
<option value="black">Black</option>
</$select>

<$select 
    class={{{ [{!!select-color-2}] }}}
    field="select-color-2"
    default="blue"
>
<option value="red">Red</option>
<option value="blue">Blue</option>
<option value="black">Black</option>
</$select>

<$select 
    class={{{ [{!!select-color-3}] }}}
    field="select-color-3"
    default="black"
>
<option value="red">Red</option>
<option value="blue">Blue</option>
<option value="black">Black</option>
</$select>
```

**Comment by Jermolene** [comment]
Thanks @EvidentlyCube 

> I'll see about fixing it myself

Great, do feel free to ask any questions

**Comment by saqimtiaz** [comment]
I recommend updating the class assigned to the DOM node without re-rendering the entire widget. 
Example:
https://github.com/Jermolene/TiddlyWiki5/blob/6f98edd6bd2b9d49f9120709dbd81fcc52af887b/core/modules/widgets/draggable.js#L91-L115

**Comment by EvidentlyCube** [comment]
@saqimtiaz since SelectWidget doesn't have any inherent classes in its case it'd probably be possible to just do `.setAttribute("class",this.getAttribute("class"))`. Posted a PR #6987, would love the feedback there :).
