### ISSUE TITLE
[BUG] Functions in Parameterized Transclusion Do Not Work as Custom Filter Operator

### ISSUE THREAD

**Issue by kookma** [Jermolene/TiddlyWiki5#6991]
### Describe the bug

Ref: https://github.com/Jermolene/TiddlyWiki5/pull/6666

The below code works as expected and `.mitra` function acts like a custom filter operator

```xml
\function .mitra() [get[title]split[]count[]]

Number of characters in Title:

<$list filter="[tag[Learning]limit[2]]">
<$link/>
: <$text text={{{[<currentTiddler>.mitra[]]}}} /><br>
</$list>
```

and returns

```text
Number of characters in Title:

Videos : 6
Introduction to filter notation : 31

```

BUT look at the below code

```
<$list filter="[tag[Learning]limit[2].mitra[]]">
```

returns

```
37
```

In other words, the custom filter operator does not operate on each input title! instead it treats all input as a single input!

Side note:

Both `[.mitra[]]` and `[.mitra<>]` work here! I expect the first format to be consistent with current behavior of filter operators

**Comment by saqimtiaz** [comment]
> In other words, the custom filter operator does not operate on each input title! instead it treats all input as a single input!

Thank you @kookma. This is indeed a design oversight and will be remedied.

**Comment by Jermolene** [comment]
Hi @kookma as it's turned out, I'm not so sure about this. If we did change things to invoke the custom function once per item then it would be impossible to create functions that accumulated results. For example, one could not construct an equivalent of the `count[]` operator.

If we keep things as they are then it is still possible to use the map operator/prefix to process each item separately.

**Comment by Jermolene** [comment]
It would be an interesting exercise to to do it without the `count` operator, presumably using reduce.

**Comment by saqimtiaz** [comment]
Something along these lines:

`\function .count-non-system() [all[]!is[system]] :reduce[[1]add<accumulator>]`

**Comment by kookma** [comment]
Thank you for clarification. I thought having the same behavior as core filter operator, make them consistent.

**Comment by saqimtiaz** [comment]
> Thank you for clarification. I thought having the same behavior as core filter operator, make them consistent.

The behaviour when used will be consistent with core filter operators, however the author of the function has to decide whether to consider all input titles at once or one at a time. Changing the behaviour to always be invoked once per input title would make it impossible to write a filter operator that considers all the input titles together, such as the example above with `.count-non-system[]`

While this is an extra aspect for the author of the function to consider, it offers more flexibility.

**Comment by kookma** [comment]
Just for curiosity: Why we need the selection constructor `[all[]]`?
I learned a selection constructor ignores its input and generates an independent output instead

Ref:
* https://tiddlywiki.com/prerelease/parameterised-transclusions/#Selection%20Constructors
* https://tiddlywiki.com/prerelease/parameterised-transclusions/#all%20Operator

**Comment by kookma** [comment]
Thank you Saq!

@Jermolene 
> Both `[.mitra[]]` and `[.mitra<>]` work here! I expect the first format to be consistent with current behavior of filter operators

The above issue still remained, so I leave this issue open.

**Comment by saqimtiaz** [comment]
@kookma as explained above, this behaviour will not change and this difference will remain so that custom operators can be written in a more flexible manner. It is up to the author of the function to write it appropriately for handling all input titles together, or one at a time.

The solution is to rewrite the .mitra operator as follows:
`\function .mitra() [all[]] :map[get[title]split[]count[]]`

**Comment by kookma** [comment]
Thank you for clarification Saq. 


> this behaviour will not change and this difference will remain so that custom operators can be written in a more flexible manner. It is up to the author of the function to write it appropriately for handling all input titles together, or one at a time.

This worth to be included in the documentation.

I close the issue now.

**Comment by Jermolene** [comment]
Thanks @kookma I've added a note here:

https://github.com/Jermolene/TiddlyWiki5/commit/149d6c2d7374144b300b5927a067281eff88fa48
