### ISSUE TITLE
[BUG] Error thrown in ZoomIn story view when first dom node is Text node

### ISSUE THREAD

**Issue by EvidentlyCube** [Jermolene/TiddlyWiki5#6992]
### Describe the bug

The setup is quite complicated. You need the following:

* Control Panel -> Appearance -> Story View set to **zoomin**
* A cascade `$:/tags/StoryTiddlerTemplateFilter` that causes a tiddler to use a new template
* A template where the first dom element is a text node (rather than a dom element)
* A tiddler that uses this template and another tiddler

Then you need the following setup:
* Open the tiddler using the template
* Open the tiddler that doesn't use the template
* Close the second tiddler

This causes `zoomin.js::remove()` to try to open the bugged tiddler and run this line of code:

```
$tw.utils.addClass(toWidgetDomNode,"tc-storyview-zoomin-tiddler");
```

`toWidgetDomNode` is a TextNode so it throws an exception inside because `getAttribute()` method does not exist on it.

### Expected behavior

No exception

### To Reproduce

1. Go to https://zoomin-story-template-bug.tiddlyhost.com/
2. In the right menu click on the **Bug** tiddler to open it
3. Close the tiddler

### TiddlyWiki Configuration

- **Version:** 5.2.3

**Comment by EvidentlyCube** [comment]
I'd like to solve this myself and I see a few ways to go:

1. The workaround could be that `$tw.utils.addClass()` checks if the first argument even has the `getAttributes()` method and, if not, ignore the rest of the method. This can cause other problems down the line though, with `$tw.utils.setStyle()` or just even setting `this.currentTiddlerDomNode` to a TextNode.
2. Should `findFirstDomNode()` even return TextNodes? Because if not then modifying this method would probably be a good solution.
3. If the tiddler begins with a text element just not use it at all.
4. Add a method `findFirstNonTextDomNode()` and use that.

But I think there is also a broader question - a tiddler that is not wrapped in a single dom element is unlikely to work with `zoomin` at all. This is a problem with having a text node, sure, but what if it had a few dom nodes at the top? Only the first one will have the class and CSS applied. This is probably an unsolvable problem though.

I feel like #4 is the best option though. It's likely that most problems will be caused by having accidental whitespace before the wrapping dom element, rather than having no wrapping element or having multiple elements.

**Comment by Jermolene** [comment]
Hi @EvidentlyCube this is an interesting problem that can crop up in several manifestations.

The fundamental issue stems from the fact that the list widget by design does not require individual items to be wrapped in a DOM element, but that the zoomin view does.

As you note, this situation generally only occurs due to an authoring error, and is easy to fix when it does occur. The challenge is that it is hard to give a useful error message to end users who encounter the problem.
