### ISSUE TITLE
There is a conflict between the freelinks plugin and the tiddlymap plugin

### ISSUE THREAD

**Issue by dongrentianyu** [Jermolene/TiddlyWiki5#6994]
### Describe the bug

Hello, I am a tiddlywiki user from China. I recently found a conflict between the freelinks plugin in the official plugin library and the tiddlymap plugin, which causes tiddlywiki to be completely unusable. I have submitted feedback on this to the tiddlymap plugin author.

Also, I really like tiddlywiki and thank you very much for developing a great piece of software. I don't speak English and this message was translated by machine. I am not a programmer and I do not know how to operate github.Please forgive my ignorance and send me a message if there are any errors or incomprehensions.

### TiddlyWiki Configuration

There is a conflict between the freelinks plugin and the tiddlymap plugin

**Comment by dongrentianyu** [comment]
This issue has now been resolved, and it was an oversight on my part not to discuss it with the developer first.

**Comment by Jermolene** [comment]
Hi @dongrentianyu good to hear from you, and thank you for the kind words which are much appreciated.
