### ISSUE TITLE
[IDEA] Better Audio Support

### ISSUE THREAD

**Issue by Fllamber** [Jermolene/TiddlyWiki5#6995]
I use the node.js implementation and it gives more freedom than the normal implementation, so I tested a wiki of sounds.

First thing, I do not understand why .mp3 is treated any diferent as other content. Any image is stored with almost no modification, but the .mp3 files become bloated and do not play. I understand this might be the product of the legacy and philosophy of the wiki, so I didn't know if this was a bug.

If I transfer manualy the files, using the _canonical_uri, they play without issue.

Second, .wav files also play without issue when transfered without "wiki drag-and-drop". I just had to add a line in the audioparser.js shadow tiddler: exports["audio/wav"] = AudioParser;
And both played without issue.

This is intentional? I'm new around here and do not know the development constrains.

**Comment by Jermolene** [comment]
Hi @Fllamber and welcome to the project. Please feel free to ask any questions.

MP3 files are treated exactly the same as image files by TW5. That is to say that when embedded in the wiki they are encoded with [base64 encoding](https://en.wikipedia.org/wiki/Base64), but they can also be referenced remotely with the `_canonical_uri`field. Base64 encoding does impose a roughly 33% increase in file size compared to binary files, but that's necessary because we can't directly embed binary files in an HTML file.

I'm happy to add the metadata for handling .wav files. I think the reason we don't support WAV files at the moment is because they are apt to be so big.

**Comment by pmario** [comment]
>I'm happy to add the metadata for handling .wav files. I think the reason we don't support WAV files at the moment is because they are apt to be so big.

We saw a lot of "wrong" assumptions using embedded images. With sound files it would probably be the same thing. So _cannonical_uri should be the preferred and recommended way to go. 

IMO .wav is a raw audio format and they would be even bigger ?!

**Comment by Fllamber** [comment]
> IMO .wav is a raw audio format and they would be even bigger ?!

They might be, the issue was I specificaly converted some songs and sounds to .mp3 to save on space, and noticed the file increase.
That's why I paid attention.
The .wav was extracted directly from a game and each individualy file was small, and I didn't wanted the trouble to change the encoding from hundreds of files.

There was not methodo in my experimentations, other than pushing the boundaries of the _nodejs_ implementation of tiddly wiki.
For my surprise it worked in the end.

**Comment by Fllamber** [comment]
Thanks @Jermolene, very insightful. For my specific use I heavily use the `_canonical_uri` field. It does lack usage examples and it is obscure, I understand why it might be underused, that's why I specified my usage of nodejs.

> I'm happy to add the metadata for handling .wav files. I think the reason we don't support WAV files at the moment is because they are apt to be so big.

I'm happy my suggestion was considered, the 'fix' was easy either way, but I thought it was better to ask around first.

**Comment by AnthonyMuscio** [comment]
I would have though the issues discussed in this issue was irrelevant if the wiki is node or single file.

**Comment by Jermolene** [comment]
> I would have though the issues discussed in this issue was irrelevant if the wiki is node or single file.

Hi @AnthonyMuscio the difference is that on Node.js we can both host the files and access them via `_canonical_uri`, which is not possible using the single file configuration.
