### ISSUE TITLE
[BUG] Visible Transclusions -- button has no effect

### ISSUE THREAD

**Issue by pmario** [Jermolene/TiddlyWiki5#6998]
### Describe the bug

Create TW v5.2.3 -- Open the "Visible Transclusions" tiddler and click the button. 

I did test it with and it didn't do anything. 

```
title: a

{{b}}
```

```
title: b

Some text
```

### Screenshots

![image](https://user-images.githubusercontent.com/374655/196661153-4e81a75c-4a9c-4ceb-9f7a-d133250de492.png)

### TiddlyWiki Configuration

TW v5.2.3
Related to #6666

**Comment by Jermolene** [comment]
Thanks @pmario fix upcoming
