### ISSUE TITLE
[BUG] Built-in methods on JavaScript's Object show up as variables for certain filters

### ISSUE THREAD

**Issue by hoelzro** [Jermolene/TiddlyWiki5#7005]
### Describe the bug

Similar to #6303, but instead of `[is[variable]]` failing to recognize an existing variable, it accidentally recognizes things like `toString` as variables when they're not.

### Expected behavior

Things like `toString` don't show up as variables (unless such a variable is actually defined)

### To Reproduce

1. Go to https://tiddlywiki.com/prerelease/
2. Create a new tiddler with the content `{{{test :filter[[isPrototypeOf]is[variable]]}}}`
3. Notice that `test` is displayed

### TiddlyWiki Configuration

- Version: prerelease
- Saving mechanism: none
- Plugins installed: none

### Desktop (please complete the following information):

- OS: Arch Linux
- Browser: Firefox
- Version: 105

### Additional context

I'm happy to contribute tests for this bug, but I think it'll be challenging to make sure future filters don't reproduce this behavior.

**Comment by pmario** [comment]
Funny -- I do get this in the AdvancedSearch filter tab

![image](https://user-images.githubusercontent.com/374655/197368601-10d26e5e-bbf0-4537-a4ce-5189c5ec870d.png)

**Comment by hoelzro** [comment]
@pmario That looks like a bug (#6303) that Jeremy fixed on the current `master` - did you do that test on the current tiddlywiki.com, or on the prerelease?

**Comment by pmario** [comment]
It's a problem with the prerelease but seems to be fixed with 5.3.0 pre

**Comment by pmario** [comment]
@hoelzro -- I did just test the code from the OP with v5.3.1 and v5.3.2-pre --> Both of them so _not_ show "test". So it seems to be fixed. Can you check again?

**Comment by hoelzro** [comment]
@pmario This looks good to me!
