### ISSUE TITLE
[IDEA] Advanced Search keyboard shortcut should always opaen and set focus to the advanced search tiddler

### ISSUE THREAD

**Issue by es-kha** [Jermolene/TiddlyWiki5#7008]
Hello,

**Is your feature request related to a problem? Please describe.**
In TiddlyWiki, pressing Ctrl + shift + A opens the advanced search tiddler.
However when this tiddler is already open, using the keyboard shortcut does not navigate to it (you have to manually scroll to it if you are farther away in the story river).

**Describe the solution you'd like**
My expectation would be that pressing Ctrl + shift + A always put the story river focus on the advanced search.

**Describe alternatives you've considered**
From my test, this can be achieved by adding a `$scroll="yes" `option inside the `$action-navigate` widget of `$:/core/ui/KeyboardShortcuts/advanced-search tiddler`:

```
<$navigator story="$:/StoryList" history="$:/HistoryList">
<$action-navigate $to="$:/AdvancedSearch" $scroll="yes"/>
<$action-sendmessage $message="tm-focus-selector" $param="""[data-tiddler-title="$:/AdvancedSearch"] .tc-search input""" preventScroll="true"/>
</$navigator>
```

**Additional context**
Suggestion initially posted on TiddlyWiki talk:
https://talk.tiddlywiki.org/t/suggestion-for-advanced-search-keyboard-shortcut-behaviour/4882

BR,

Eskha

**Comment by pmario** [comment]
@Jermolene @saqimtiaz ... I did just test it as described and it seems to work as expected. Does there speak anything against that change?

Should I crate a PR to be merged  after v5.2.24?

**Comment by Jermolene** [comment]
Thanks @es-kha @pmario I think this is a bug, and that does indeed seem like the correct fix. I'll do some more testing and commit shortly.

**Comment by es-kha** [comment]
Thank you @pmario and @Jermolene.
