### ISSUE TITLE
[IDEA] Let macro tiddlers view mode show the macro "heads"

### ISSUE THREAD

**Issue by twMat** [Jermolene/TiddlyWiki5#7015]
**Is your feature request related to a problem? Please describe.**
Macro tiddlers appear "blank" in view mode. It is annoying to have to open macro tiddlers to see what macros are in it, or to recall what parameter names are used, or other hints how to use it.

**Describe the solution you'd like**
I would like for the view mode to show a quick "summary" of the macros therein. If one is interested in their full implementation then, sure, one has to enter edit mode, but from view mode it would be neat to see: the pragma types, the defined names and their parameter lists, as well as comments (e.g `<!-- ... -->` sections). So a macro tiddler could in viewmode display extracted lines or line segments like so:

```
The following macros are defined in this tiddler:

\define foo(one, two:"three four")
------------------------------------------------------------
\define bar(five)
<!-- This bar serves until five o'clock -->
------------------------------------------------------------
\define baz(six)
```

**Describe alternatives you've considered**
1) I'm not sure about showing the comments since we don't have any best practice for how to comment (and because code commenting functionality is overall a bit lacking). So an option might be to use this view mode as a place to add comments in some field next to the listed macro heads.

2) For my macro tiddlers, I currently often include a `description` field and use a special viewtemplate to transclude this. But the OP would be better both because it was automated and also because I usually comment on how to use the macros there which is not ideal in a single line field.

**Note**
When "parametrized transclusions" are implemented, I'd think there's even more justification for this proposal.

**Comment by pmario** [comment]
IMO the easiest way to solve the problem is to set the field `code-body = yes`.

**Comment by twMat** [comment]
Fair enough. 
Thanks.
