### ISSUE TITLE
[IDEA] Relocate the type field in the edit view

### ISSUE THREAD

**Issue by twMat** [Jermolene/TiddlyWiki5#7021]
As discussed [here](https://talk.tiddlywiki.org/t/proposal-for-new-edittemplate-layout/4981), I'm proposing that the **type field** in edit view...
* is relocated to above the title field and 
* that its behaviour is somewhat modified

The image shows the new position above the title field, and after the user has clicked the arrow to open the dropdown. No type field appears below the main editor.

<img width="606" alt="image" src="https://user-images.githubusercontent.com/4534056/199474994-57f075c8-dbef-4395-8b72-e3d2d459301e.png">

**Note** Just like currently, if no selection is made then `TiddlyWiki 5 text/vnd.tiddlywiki` is default and this, just like currently, is *not* shown next to the Type label (for a clean UI). However, if the user selects anything then this is shown:

<img width="350" alt="image" src="https://user-images.githubusercontent.com/4534056/199472601-dd28c428-4abc-41eb-96f8-aa6fa53bda93.png">

**Reasons**
* The current location with the type field below the main editor makes for an asymmetrical and cluttery edit view. Consider how rarely it is used (by the average user) and that a new user directly faces edit view so it is important that the edit view is appealing.
* The current location makes the dropdown go below viewport forcing the user to scroll
* The current text area to type into is overkill and also adds clutter. Anyone savvy enough to create a custom type is likely also able to make this appear in the dropdown, i.e enabling selection rather than manual typing.
* It is natural workflow to set type *before* using the other fields, so it makes more sense to have it at top of tiddler.

**Comment by saqimtiaz** [comment]
> * The current location with the type field below the main editor makes for an asymmetrical and cluttery edit view. Consider how rarely it is used (by the average user) and that a new user directly faces edit view so it is important that the edit view is appealing.

We now allow users to override on a per field basis the editing interface, i.e. I could have dropdowns for other fields as well. So moving the type field above the textarea would make it impossible for me to group all the dropdowns together if so desired, potentially leading to a more cluttered looking edit template. I do not think such a subjective change makes sense unless the position of each field is made configurable.

From a UX perspective I would be much more inclined to support the affordance to hide less commonly used UI elements until needed, with what is less commonly used being configurable by the user.



> * It is natural workflow to set type _before_ using the other fields, so it makes more sense to have it at top of tiddler.
On what basis? I find it a very common workflow to change the type field after the fact if I do need to change the type field, commonly with CSS or SVG tiddlers.

Have you considered the tab order and what that would be and the associated usability, and how that would appear to screen readers if the tab order is not in sequence?

**Comment by twMat** [comment]
>From a UX perspective I would be much more inclined to support the affordance to hide less commonly used UI elements until needed, with what is less commonly used being configurable by the user.

Good point! I'm raising a discussion about this [here](https://talk.tiddlywiki.org/t/looking-for-a-standard-solution-and-ui-to-hide-stuff-in-tw/5013). I'd love to hear your thoughts on it.
