### ISSUE TITLE
[BUG] The Remove Operator Does Not Work with Tiddlers with Space in Their Title

### ISSUE THREAD

**Issue by kookma** [Jermolene/TiddlyWiki5#7031]
### Describe the bug

The [remove ](https://tiddlywiki.com/#remove%20Operator)operator does not work with tiddlers with space in their title.

### Expected behavior

The expected behavior is to work will all tiddlers title

### To Reproduce

1. Go to [https://tiddlywiki.com/](https://tiddlywiki.com/)
2. Create a new tiddler
3. Paste the below code as tiddler text and open preview pane

```
<$tiddler tiddler="Videos">
<$list filter="[tag[Learning]remove<currentTiddler>]" >

</$list>
</$tiddler>
```

The code works like a charm and removes the "Videos" from output result.

Now change the tiddler value in $tiddler widget as below

```
<$tiddler tiddler="Introduction to filter notation">
<$list filter="[tag[Learning]remove<currentTiddler>]" >

</$list>
</$tiddler>
```

4. See the issue, remove operator does not delete the "Introduction to filter notation" from the output.

### TiddlyWiki Configuration

- Version 5.2.3

### Desktop (please complete the following information):

- OS: Windows 10
- Browser Edge / Chrome 107

**Comment by pmario** [comment]
That's not a bug. .. The first list only works, because the **first** currentTiddler variable is Video

The list-widget internally redefines the currentTiddler variable. If you use the following code it works

```
<$let remove-me="Introduction to filter notation">
<$list filter="[tag[Learning]] -[<remove-me>]" >

</$list>
</$let>
```

**Comment by Jermolene** [comment]
Hi @kookma the problem here is that the "remove" operator parses the operand as a list, not as a single entry. So what actually works is this:

```
<$tiddler tiddler="[[Introduction to filter notation]]">
<$list filter="[tag[Learning]remove<currentTiddler>]" >

</$list>
</$tiddler>
```

@pmario's code works because it avoids using the remove operator.

**Comment by kookma** [comment]
Thank you @Jermolene.  So why not the above code does not work

```
<$tiddler tiddler="Introduction to filter notation">
<$list filter="[tag[Learning]remove<currentTiddler>]" >

</$list>
</$tiddler>
```

I assume here currentTiddler is a **title** am I right?

**Comment by Jermolene** [comment]
Hi @kookma, apologies it would have been clearer to say that the "remove" operator parses the operand as a double square bracketed list, not as a single entry.

Your example thus works if you change the assignment to `tiddler="[[Introduction to filter notation]]"`.

The reason it works like that is to enable multiple items to be removed in one operation. For example:

```
<$tiddler tiddler="[[Introduction to filter notation]] [[Sharing a TiddlyWiki on Dropbox]]">
<$list filter="[tag[Learning]remove<currentTiddler>]" >

</$list>
</$tiddler>
```

**Comment by kookma** [comment]
Much appreciated for clarification.
