### ISSUE TITLE
[IDEA] Turn On/Off SpellCheck for EditText Widget

### ISSUE THREAD

**Issue by kookma** [Jermolene/TiddlyWiki5#7036]
**Is your feature request related to a problem? Please describe.**
The input box created with `$edit-text` widget has spellcheck enabled by default (e.g. follows the browser settings), I like to optionally disable spellcheck for certain input boxes.

**Describe the solution you'd like**

The current solution I use is as below and it works with Tiddlywiki 5.2.3 and older.

```
<div spellcheck="true">
<$edit-text field="myfield" tag="textarea" />
</div>
```

I would prefer to use an attribute like below which is a TiddlyWiki way.

```
<$edit-text field="myfield" tag="textarea" spellcheck="false"/>
```

**Comment by pmario** [comment]
probably a duplicate of:  [IDEA] Toggle browser spell-checker on a per tiddler editor basis #6927 

Other open Issues: https://github.com/Jermolene/TiddlyWiki5/issues?q=is%3Aissue+is%3Aopen+spell+check

**Comment by kookma** [comment]
I close this in favor of https://github.com/Jermolene/TiddlyWiki5/issues/6927#issuecomment-1229470359
