### ISSUE TITLE
[BUG] Issue in UI Text for New Journal Tiddlers and Default Tiddlers

### ISSUE THREAD

**Issue by kookma** [Jermolene/TiddlyWiki5#7037]
### Describe the bug

The latest prerelease of 2022.11.15 shows issue for input boxes of 

* Text for New Journal Tiddlers
* Default Tiddlers

It seems the width set to auto

### Expected behavior

They need to have full width of parent!

### To Reproduce

1. Go to https://tiddlywiki.com/prerelease/
2. Open $:/ControlPanel
3. Info -> Basic tab

### Screenshots

![image](https://user-images.githubusercontent.com/830394/201822458-3dd23f1f-8e68-4cda-bc01-3df10f65d759.png)

### TiddlyWiki Configuration

Tiddlywiki 5.24 pre
Edge 107
Win 10

**Comment by Jermolene** [comment]
Thanks @kookma – @pmario is this is related to 10cb585dae7e71bd2c9969768307989828f56f52?

**Comment by ericshulman** [comment]
In TW5.2.3, $:/core/ui/ControlPanel/Basics, the textarea controls have ` class="tc-edit-texteditor"`.

In TW5.2.4prerelease, these class parameters were removed by change [10cb585](https://github.com/Jermolene/TiddlyWiki5/commit/10cb585dae7e71bd2c9969768307989828f56f52).

As a result, these textareas no longer fill the width of their containing table cells, as reported by @kookma

**Comment by Jermolene** [comment]
Oh dear. I'll revert #6912 and comment more there.

**Comment by pmario** [comment]
That's probably not the problem. I did download master and merged this PR. It looks like this.

![image](https://user-images.githubusercontent.com/374655/201921074-411950a1-b4bc-42f6-8ea0-7d5817671e39.png)

**Comment by pmario** [comment]
There seems to be a problem with the "hardcoded" styles that are applied to the text input area ... may be a codemirror problem needs more investigation

**Comment by pmario** [comment]
@Jermolene ... The actual problem is, that the 2 text areas used in $:/core/ui/ControlPanel/Basics are converted to codemirror editors, if the plugin is installed. I personally think that's a bug, but for backwards compatibility reasons I'll leave it that way.

They use the `$edit` widget instead of the `$edit-text` widget, which the rest of the table uses. So they are converted to cm-editors ... 

PR fix will follow shortly

**Comment by pmario** [comment]
@kookma -- IMO the problems described in the OP have been fixed. -- right?

**Comment by kookma** [comment]
Yes, it has been resolved.
