### ISSUE TITLE
[BUG] tiddlywiki.com style $:/_tw5.com-styles contains hardcoded colour so palette-manager doesn't work

### ISSUE THREAD

**Issue by pmario** [Jermolene/TiddlyWiki5#7041]
[$:/_tw5.com-styles](https://tiddlywiki.com/prerelease/#%24%3A%2F_tw5.com-styles) contains the styling for the "Big Downloads" button. 

The colour is hardcoded so it cannot be defined by the palette-manager. -> **That's a problem**

### At the end of the file it contains

```
.tc-btn-download {
...
	background: #1462ff;
}

.tc-btn-download:active {
	background: #1462ff;
}
```

### It should contain

```
.tc-btn-download {
...
	background: <<colour "download-background">>;
}

.tc-btn-download:active {
	background: <<colour "download-active">>;
}
```

As shown in the screenshot below. .. The default colour with the Vanilla-Palette is "green"

At tiddlywiki.com it's hardcoded to blue-ish -> The blue colour also is a problem for the ControlPanel Plugin overview.

<details><summary><b> show screenshot</b> </summary>

![image](https://user-images.githubusercontent.com/374655/202166360-6a8e284c-c979-4323-9bd3-656de782e5f4.png)

</details>

# Request

- We should change the blue button to a green button
- Which will enable palette handling
- The ControlPanel plugin overview will be much more readable as it is atm

![image](https://user-images.githubusercontent.com/374655/202167282-2dc387d2-def8-499b-ae12-80d89c467c1e.png)

@Jermolene

- Should I create a PR for the green-ish button and check all the existing palettes ?
- Do we want a green-ish button as the download button

IMO The blue colour causes a problem in the plugin overview, so it should not be blue ... just some thoughts

**Comment by Jermolene** [comment]
Thanks @pmario the fact that $:/_tw5.com-styles overrides tc-btn-big-green is definitely an oversight. We should be using the default core class, and fixing it if we need to.

> Should I create a PR for the green-ish button and check all the existing palettes ?

Great, yes please.

> Do we want a green-ish button as the download button

Do you mean do we want to style the download button with the vanilla tc-btn-big-green definition? If so, yes.
