### ISSUE TITLE
[BUG] Dropzone always picks the last item kind for a string, which might be the worst one

### ISSUE THREAD

**Issue by farcaller** [Jermolene/TiddlyWiki5#7050]
### Describe the bug

When pasting from Visual Studio Code,  there are 3 items in the clipboard:

```
Importing string 'hello world', type: 'vscode-editor-data'
dropzone.js:272 Importing string '<meta charset='utf-8'><div style="color: #657b83;background-color: #fdf6e3;font-family: JetBrains Mono NL, Input, Menlo, Monaco, 'Courier New', monospace, Menlo, Monaco, 'Courier New', monospace;font-weight: normal;font-size: 12px;line-height: 22px;white-space: pre;"><div><span style="color: #657b83;">hello world</span></div></div>', type: 'vscode-editor-data'
dropzone.js:272 Importing string '{"version":1,"isFromEmptySelection":false,"multicursorText":null,"mode":"c"}', type: 'vscode-editor-data'
```

As dropzone imports them one by one, the last one gets priority and it's the most useless one 😞 (loosely related to #6592).

### Expected behavior

Something more useful is pasted.

### To Reproduce

1. Copy text from e.g. vscode
2. Paste it into tiddlywiki

### Screenshots

<img width="550" alt="image" src="https://user-images.githubusercontent.com/693/202908283-b8f717a4-ff46-4c2c-8792-b583b828676b.png">

### TiddlyWiki Configuration

- Version: 5.2.3
- Saving mechanism: N/A
- Plugins installed: None

### Desktop (please complete the following information):

- OS: MacOS (reproduced on windows too)
- Browser: chrome
- Version: 107

**Comment by farcaller** [comment]
FWIW: on windows the types are less insane: `text/plain, text/html, vscode-editor-data`. Maybe the strategy should be:

- if there is text/html in types, load it;
- if there is text/plain in types, load it;
- otherwise load the first string

**Comment by pmario** [comment]
>As dropzone imports them one by one, the last one gets priority and it's the most useless one disappointed (loosely related to https://github.com/Jermolene/TiddlyWiki5/issues/6592).

Not loosely related, but 100% related. In FF it woks fine for me. ... 

There is a pending PullRequest, which got 2 new comments from Jeremy and Saq lately: https://github.com/Jermolene/TiddlyWiki5/pull/6622#issuecomment-1314111072

The main problem is, that a fix may be problematic for either FF users or Chrome users in an "opposite" way. 

So we need some new UI handling that will help both parties. ... But I didn't find out, how to do it yet. 

- May be show both or "all 3" examples 
- Deselect all of them
- Let the user decide, what to import .. They explicitely need to select those, they want to import. 
   -  may be it's all 3 or even more of them

**Comment by Jermolene** [comment]
Thanks @farcaller and welcome to the project.

The assumption that the first string is the most important seems like a reasonable fix.

The only concern is that drag and drop is a tricky area to work on because often a fix for one browser has unintended consequences for another. At this point we don't have the means to test changes automatically across all the browsers we target. The best we can do is to perform some systematic manual testing.

So I think the way to proceed might be to do as much testing as possible first, and then to merge this immediately after v5.2.4 has been released.

To simplify the testing, it would be useful to post a build of the change to Tiddlyhost, and then kick off a talk.tiddlywiki.org thread asking people to perform a set of test steps on their favourite browser. We can compile a matrix of the results.

I'd welcome other thoughts.

**Comment by pmario** [comment]
>The assumption that the first string is the most important seems like a reasonable fix.

**Comment by pmario** [comment]
>The assumption that the first string is the most important seems like a reasonable fix.

Not really, since the internal array structure is different between FireFox and Chrome-like browsers. So any element could be the one the user is after. We just don't know. For me FF works as it is intended. 

For Chrome users that's probably different, because they don't know better ;)

**Comment by farcaller** [comment]
Are there any other types that are commonly passed as string and not a file, other than html and plaintext? Can we special-case the two and import the rest as separate tiddlers, letting the user pick the correct one in the import UI?

**Comment by pmario** [comment]
If javascript is used to copy content to the clipboard, there can be any "type" in the clipboard. It will depend on the receiving scripts to identify them. .. BUT html and text are common if content is copy/pasted from a webpage.

**Comment by farcaller** [comment]
> If javascript is used to copy content to the clipboard, there can be any "type" in the clipboard. 

Chances are that will be the only content item then, no?

**Comment by farcaller** [comment]
> Let the user decide, what to import

This could be done as a setting that keeps the check on the types that user pre-approved. plaintext seems like a sensible default.

**Comment by pmario** [comment]
@farcaller ... I did just test this with v5.2.7 and it works now. With Edge there are 3 items which will be shown you can choose from. 

![image](https://user-images.githubusercontent.com/374655/227781742-5687169b-ef81-4020-9863-4ed1140b5853.png)

IMO this issue can be closed.

**Comment by pmario** [comment]
@farcaller ... This should be fixed now. IMO You should close the issue
