### ISSUE TITLE
[BUG] Visual regression in import table in 5.2.4 pre-release

### ISSUE THREAD

**Issue by saqimtiaz** [Jermolene/TiddlyWiki5#7056]
As reported on [talk,](https://talk.tiddlywiki.org/t/tiddlywiki-5-2-4p-issue-in-import-table/5259) the table rows in the $:/Import tiddler have gaps between them:
![image](https://user-images.githubusercontent.com/68092/203480777-52c799d7-48b2-4c23-ba98-49c26b23be7b.png)

The change seems to be caused by #7039 and in particular the following change in CSS:
https://github.com/Jermolene/TiddlyWiki5/pull/7039/files#diff-1608798fd26545169d67db97f5f4b2ed06e74bdf30c65b70d95482dddbbb06feR328-R331

**Comment by Jermolene** [comment]
Thanks @saqimtiaz – I'll revert #7039 for the moment. @pmario could you have a look at an alternative implementation that doesn't change the styling of existing classes/elements?

**Comment by pmario** [comment]
I think the visual integrity of all tables in general is much more important than the import dialogue, that is not used every day. ... I think the import table needs to be fixed instead of everytime a visual glitch comes up to revert the whole PR. 

eg: have a look at the initial screenshots at: https://github.com/Jermolene/TiddlyWiki5/pull/6912#issue-1342948905
which the PR does fix.

**Comment by Jermolene** [comment]
> It's not a problem of the PR it's a problem of the import table that included invisible rows instead of _not_ creating them. The PR only makes the problem visible.

For better or worse, that is how the import table has always worked, and we might expect that users will have copied it, so backwards compatibility is a concern.

> So everytime a problem shows up, my fixes get reverted instead of having a closer look at the "real" problem

The reason I tend to revert PRs immediately that we see a problem reported is to avoid other people seeing the same problem and reporting it again. It also gives the submitter more time to fix things.
