### ISSUE TITLE
[IDEA] Force inline mode in a tiddler

### ISSUE THREAD

**Issue by EvidentlyCube** [Jermolene/TiddlyWiki5#7058]
**Is your feature request related to a problem? Please describe.**
I want to avoid redundant `p` tags in tiddlers where I do almost everything with HTML. This is especially a pain point in plugins in cases like:
* Using `$:/tags/ViewTemplateBodyFilter` cascades which default to block mode
* Using other tags which insert things into the UI

**Describe the solution you'd like**
I'd like a way to control from within the tiddler if I want to force rendering in either mode. I was thinking of either of these solutions:
* New pragma `\transcludemode` which accepts either `block` or `inline`
* Or a special field in the tiddler, perhaps `transclude.mode` which controls it

**Describe alternatives you've considered**
* I can wrap the whole thing in a single div to have only one `<p>` around everything
* Or wrap it into another transclude with explicitly set mode but I still end up with one `<p>` around everything

**Additional context**
I think a pragma would be the best option. I've barely even touched parser code so far, but looking at things it seems like it could be fairly easily doable with the following:
* In `WikiParser` constructor store `options.parseAsInline` into `this.parseAsInline` 
* Then a pragma can be written to control that variable

**Comment by pmario** [comment]
We need a global fix and no workarounds. Coincidentally I'm preparing a talk-post about this problem at the moment. But it isn't finished. I need to find some code, which seems to hide somewhere in my local branches :(

**Comment by EvidentlyCube** [comment]
> We need a global fix and no workarounds

Is it a workaround though? I feel like that's exactly the type of thing pragma could be used for and I am not sure if there can exist a global solution that would give us the amount of granularity pragma does. But I'll await your post, I am very curious about other solutions, not trying to push this solution as **the one**.

**Comment by pmario** [comment]
Here's the post: https://talk.tiddlywiki.org/t/i-would-like-to-fix-the-redundant-p-tag-problem/5267

**Comment by EvidentlyCube** [comment]
Doh, I didn't think of the obvious - seriously limit `p` wrapping.

**Comment by pmario** [comment]
The main problem why I didn't propose it globally is, that we will need some CSS fixes for some elements where it was "convenient" to have the faulty DOM structure. 

Fixing the problem will cause some subtle change in behaviour. We will need to adjust some of our documentation, because most users to copy / paste anyway. So if your examples are right they won't even notice it. 

BUT some older wikis may get problems if udpate. So we need to try to catch all the problems and describe them in an "Known Incompatibility Problems" tiddler in the release notes.

**Comment by pmario** [comment]
If you transclude something as inline, you will loose formatting for eg: `! headers` and other block elements. I'm pretty sure you don't want that.

**Comment by milahu** [comment]
> We need a global fix and no workarounds.

html linter to replace all `<p>` with `<div>`?

https://github.com/BenoitZugmeyer/eslint-plugin-html

https://github.com/yeonjuan/html-eslint/blob/main/packages/eslint-plugin/lib/rules

https://eslint.org/docs/latest/developer-guide/working-with-rules#applying-fixes

**Comment by pmario** [comment]
>html linter to replace all <p> with <div>?

TW has it's own HTML parser, so the problem has to be solved there. It's not a developers problem, where ESLint can help. Every user can create arbitrary HTML code using HTML syntax or wikitext syntax mixed with HTML -- Similar what you can do with markdown, but much more flexible

**Comment by saqimtiaz** [comment]
Related tickets and comments to consider:
* https://github.com/Jermolene/TiddlyWiki5/pull/6135#issuecomment-950128144
* https://github.com/Jermolene/TiddlyWiki5/pull/6156
* https://github.com/Jermolene/TiddlyWiki5/pull/4285

**Comment by Jermolene** [comment]
Hi @EvidentlyCube interesting question. Currently it is up to caller of the parser methods to decide whether to use block or inline parsing. Controlling the parse mode from within the tiddler is consistent with the current controls we provide over which parse rules are recognised.
