### ISSUE TITLE
[BUG] :filter filter run does not always remove non-matching entries (linked-list.js issue)

### ISSUE THREAD

**Issue by btheado** [Jermolene/TiddlyWiki5#7059]
### Describe the bug

I expect the output of the filter expression `A =A B =A :filter[match[B]]` to be `B`, but the output is `B A`

Looks to me like an issue with `linked-list-.js` not removing items correctly. If I add this line to `editions/test/tiddlers/tests/test-linked-list.js`:

```js
compare(remove(newPair(["A", "A", "B", "A"]), ["A", "A", "A"])); // B
```

Then I get this test failure when running the test suite:

```
Failures:
1) LinkedList class tests can remove all instances of a multi-instance value
  Message:
    Expected $.length = 2 to equal 1.
    Unexpected $[1] = 'A' in array.
  Stack:
    Error: Expected $.length = 2 to equal 1.
    Unexpected $[1] = 'A' in array.
        at <Jasmine>
        at compare (test-linked-list.js:64:35)
        at UserContext.<anonymous> (test-linked-list.js:111:7)
        at <Jasmine>
  Message:
    Expected 2 to be 1.
  Stack:
    Error: Expected 2 to be 1.
        at <Jasmine>
        at compare (test-linked-list.js:65:32)
        at UserContext.<anonymous> (test-linked-list.js:111:7)
        at <Jasmine>
```

### Expected behavior

The `:filter` filter run should remove all non-matching entries from the input

### To Reproduce

1. Paste `A =A B =A :filter[match[B]]` into https://tiddlywiki.com/#%24%3A%2FAdvancedSearch filter tab
2. See the unexpected results `B A`

### TiddlyWiki Configuration

- Version v5.2.3

**Comment by Jermolene** [comment]
Ouch thank you @btheado. The linked list code is quite challenging to work with, might you be able to investigate a PR?

**Comment by Alzacon** [comment]
Other cases that return `B A`
`A =A B A :filter[match[B]]`
`A =A B A :filter[prefix[B]]`

Maybe the filter prefix `=` before the first match produces the bug in the prefix `:filter`,  because A B =A =A :filter[match[B]]` returns `B`

**Comment by btheado** [comment]
@Jermolene, I haven't figured out the fix yet, but I'll keep working on it. @Alzacon, I've already narrowed it down to the remove method of linked-list.js. The `:filter` prefix uses that method. I didn't looks to see what else might use it. The `=` is an important aspect of the reproduction of the bug because duplicates are required for it.

Here is a general description of the failing case:

When an item which has duplicates is to be removed from the input list and the 2nd-to-last duplicate instance is not first in the list and there is at least one item not removed between the 2nd-to-last and the last duplicate occurrence.

Or maybe this is a better way of wording it:

When there are one or more matches in between two duplicates and the first of those two duplicates is not the first item in the input.

For example, all of these cases fail:

```js
		compare(remove(newPair(["A", "A", "C", "B", "A"]), ["A", "C", "A", "A"])); // B
		compare(remove(newPair(["A", "A", "C", "B", "A"]), ["C", "A", "A", "A"])); // B
		compare(remove(newPair(["A", "A", "C", "B", "A"]), ["A", "A", "A"])); // CB
		compare(remove(newPair(["A", "A", "C", "B", "A"]), ["A", "A", "A", "C"])); // B
		compare(remove(newPair(["A", "A", "B", "A"]), ["A", "A", "A"])); // B
		compare(remove(newPair(["A", "A", "B", "A"]), ["A", "A", "A", "B"])); // 
		compare(remove(newPair(["C", "A", "B", "A"]), ["C", "A", "A"])); // B
		compare(remove(newPair(["C", "A", "B", "A", "C"]), ["C", "A", "A", "C"])); // B
		compare(remove(newPair(["B", "A", "B", "A"]), ["B", "A", "A"])); // B
```
but these do not fail:

```js
		compare(remove(newPair(["A", "C", "B", "A"]), ["A", "C", "A"])); // B
		compare(remove(newPair(["A", "A", "B", "A"]), ["A", "A", "B", "A"])); // 
```

It seems the `list.prev.A` array is getting two entries removed with a single call to `_removeOne` which doesn't seem right. I just tried commenting out this line here: https://github.com/Jermolene/TiddlyWiki5/blob/master/core/modules/utils/linked-list.js#L141

And it actually fixed the failing test cases. I don't have very much confidence that is the fully correct fix. I'll keep investigating as I find time.
