### ISSUE TITLE
The modern-normalize CSS reset breaks default focus rendering for select elements in Firefox

### ISSUE THREAD

**Issue by pmario** [Jermolene/TiddlyWiki5#7082]
As seen in the screenshots below there is a significant differnce between different browsers

Safari on macOS 

![image](https://user-images.githubusercontent.com/374655/205432754-e45f53b9-de25-4c33-b409-b5264a5c1f39.png)

FireFox on macOS ... The same is true for other OSes

![image](https://user-images.githubusercontent.com/374655/205432770-605597e4-40ab-44e5-8027-485e7aeb6900.png)

I think the problem is introduced by the reset.css we are using at the moment.
This should be investigated and discussed with the reset-upstream folks

**Comment by pmario** [comment]
Also see: discussion at: https://github.com/Jermolene/TiddlyWiki5/pull/7081

**Comment by Jermolene** [comment]
Thanks @pmario I can confirm Firefox on macOS renders focus indicators for unstyled select elements differently, so it would appear to be a problem with the reset.

<img width="101" alt="image" src="https://user-images.githubusercontent.com/174761/205432928-63acbcb9-8695-4f88-beb2-eb7ced7ecd6f.png">

**Comment by pmario** [comment]
I did some investigation already. It seems that FireFox internally handles changes to default styles differently than other browsers. 

It seems if a css-reset changes a "sub-parameter" eg. `border-left: xx` FireFox set's the whole `border` to undefined and only sets `border-left`. While other browsers handle the reset on a "per sub-element" level. 

... at least that's what I did understand from a bug/issue/report somewhere. ... I didn't save the link, so may be I just did misunderstand the whole thing. 

More investigation needed.

**Comment by Alzacon** [comment]
I think the problem is in the generic selector
```
:-moz-focusring {
  outline: 1px dotted ButtonText;
}
```
This is causing the issue in all focusable elements: select, input, button, anchor (link) ... 

Our reset is outdated, the last version of normalize only uses it for selector of buttons
```
button:-moz-focusring,
[type="button"]:-moz-focusring,
[type="reset"]:-moz-focusring,
[type="submit"]:-moz-focusring {
  outline: 1px dotted ButtonText;
}
```
Also the lastest normalize is outdated, from Nov 2018.

The [:-moz-focusring](https://developer.mozilla.org/en-US/docs/Web/CSS/:-moz-focusring) has been renamed, although this selector is fully functional.

**Comment by pmario** [comment]
>I think the problem is in the generic selector

Yes. That's right. .. The existing CSS option now is [focus-visible](https://developer.mozilla.org/en-US/docs/Web/CSS/:focus-visible) ... And the problem there is the word "heuristics" defined by the UA. 

Since browser vendors may use a different heuristics, this can cause differences in styling of the outline. ... That's exactly the problem I described. ..

>The :focus-visible pseudo-class applies while an element matches the [:focus](https://developer.mozilla.org/en-US/docs/Web/CSS/:focus) pseudo-class and the UA ([User Agent](https://developer.mozilla.org/en-US/docs/Glossary/User_agent)) determines via heuristics that the focus should be made evident on the element. (Many browsers show a "focus ring" by default in this case.)

I think, we should remove that "offending" setting from the reset, since it seems to cause more problems for us that it fixes. .. BUT we should first know, why the reset.css did define it in the first place.

**Comment by Alzacon** [comment]
> Also the lastest normalize is outdated, from Nov 2018.

I was wrong, because tiddlywiki doens't use it, tiddlywiki uses modern-normalize.

However, the reason of this use is in the original normalize https://github.com/necolas/normalize.css/issues/481

And here (https://github.com/sindresorhus/modern-normalize/issues/55) the open issue in modern-normalize where is pointed:
>This thin dotted gray line is inaccessible, outdated. Browsers have updated their default focus styles to be much more accessible, including Firefox.

**Comment by Jermolene** [comment]
Thanks @pmario @Alzacon – I think we should explore updating the our reset.css for v5.3.0, once we've got v5.2.4 released.
