### ISSUE TITLE
[BUG] AdvancedSearch Filter dropdown shows draft tiddlers and tiddlers without `description` or `filter` fields

### ISSUE THREAD

**Issue by ericshulman** [Jermolene/TiddlyWiki5#7083]
### Describe the bug

If a tiddler that is currently being edited is tagged with `$:/tags/Filter` then it appears TWICE in the dropdown list in $:/AdvancedSearch Filters (once for the tiddler, and again for the `draft.of` tiddler).

Also, if a tiddler is tagged with `$:/tags/Filter` and lacks `description` and/or `filter` fields, then it appears as a SELECTABLE blank line in the dropdown list.

### Expected behavior

Draft titles and tiddlers without non-blank `description` and `filter` fields should be excluded from the list.

To fix this, in `$:/core/ui/AdvancedSearch/Filter/FilterButtons/dropdown`, change
```
<$list filter="[all[shadows+tiddlers]tag[$:/tags/Filter]]">
```
to
```
<$list filter="[all[shadows+tiddlers]tag[$:/tags/Filter]has[filter]has[description]!has[draft.of]]">
```

### To Reproduce

For the first problem:
1. Edit an existing tiddler that defines a filter (e.g., `$:/core/Filters/AllTags`)
2. With the tiddler still in edit mode, open $:/AdvancedSearch > Filter tab
3. Click on downarrow to display droplist for selecting from defined filters
4. Note that "All tags except system tags" appears TWICE in the list

For the second problem:
1. Create a new tiddler (e.g., "TestFilter")
2. Add tag of `$:/tags/Filter`
3. Press Done button to complete editing
4. Click on downarrow to display droplist for selecting from defined filters
5. Note selectable blank line for TestFilter appears in the list

### TiddlyWiki Configuration

- Version [e.g. v5.1.24]
- Saving mechanism [e.g. Node.js, TiddlyDesktop, TiddlyHost etc]
- Plugins installed [e.g. Freelinks, TiddlyMap]

**Comment by Jermolene** [comment]
Thanks @ericshulman fix upcoming

**Comment by ericshulman** [comment]
@Jermolene what about the second part (excluding tiddlers that lack `description` or `filter` fields).

If `description` field is missing or blank, the list output contains a "ghost" link item that is still selectable because the link still has padding... and if `filter` is defined, then selecting this "ghost" line still sets the filter input field text; but if `filter` is missing or blank, the selecting this "ghost" line sets the input to blank.  I suppose this last case could be used to create a "clear filter input" choice, but it still strikes me as an error.
