### ISSUE TITLE
[Bug] There needs to be a visual indicator if a tiddler body is folded

### ISSUE THREAD

**Issue by pmario** [Jermolene/TiddlyWiki5#7084]
Over the time several users already had a problem with tiddler bodies missing, because the body was folded and they forgot about it, or they haven't been aware to fold the tiddler body. 

As written at [Talk TiddlyWiki](https://talk.tiddlywiki.org/t/help-needed-tagmanager-doesnt-work-as-expected/5349/5?u=pmario) it's problematic, that folded tiddlers don't have a visual indication, that they **are folded**

There is a view-toolbar setting, that shows an "unfold" indicator, but it is not activated by default. 

So the suggestion is, to "force" that button to be visible if a tiddler is folded

**Comment by twMat** [comment]
One idea would be to introduce a special css class to folded tiddlers, to enable styling to indicate state.

**Comment by pmario** [comment]
I would like to enable the "unfold banner" and even make the chevrons more visible like so

![image](https://user-images.githubusercontent.com/374655/205481664-805f529e-ad36-46cf-99d2-f2ddfe4d0a0e.png)

**Comment by pmario** [comment]
I think there is no explanation or additional documentation needed if a tiddler is shown like this. If the user clicks the button, everything is OK again. 

If they want the unfold buttons back, they can ask how to do it.

**Comment by Jermolene** [comment]
Thanks @pmario @twMat this has certainly given us some problems. Initially let's try just ensuring that the unfold indicator is always visible.

**Comment by pmario** [comment]
Great response. Thanks!
