### ISSUE TITLE
[BUG] Emptybox in

### ISSUE THREAD

**Issue by kookma** [Jermolene/TiddlyWiki5#7095]
### Describe the bug

See https://tiddlywiki.com/prerelease/#GettingStarted

Under: Available methods for saving changes with TiddlyWiki:

The box is empty at start with shadows! I may suggest a default OS value! or hide the empty box, or show it when some OS is selected

### Screenshots

![image](https://user-images.githubusercontent.com/830394/206090144-2dfe8866-10df-4df5-9652-f2dc163326c4.png)

### TiddlyWiki Configuration

- Version 5.2.4-prerelease
- Chrome 107, Edge 107
- Windows 10

**Comment by Jermolene** [comment]
Thanks @kookma – I've addressed it by adding an introductory message that is displayed when none of the checkboxes are checked:

<img width="802" alt="image" src="https://user-images.githubusercontent.com/174761/206860137-f1fbcd0b-9123-4fa4-8d53-9dccafb63912.png">
