### ISSUE TITLE
[IDEA] "Saving with the HTML5 fallback saver" improvements

### ISSUE THREAD

**Issue by ericshulman** [Jermolene/TiddlyWiki5#7107]
**Is your feature request related to a problem? Please describe.**
"Saving with the HTML5 fallback saver" should be non-judgemental.

**Describe the solution you'd like**
* Change `title`:
from "Saving with the HTML5 fallback saver"
to "Saving with the HTML5 saver"
* Change `description`:
from "Slightly awkward but universal technique that works on almost every browser"
to "Universal technique that works on almost every browser"
* Change `text`:
from "This method of saving changes is clunky because it requires manual intervention for each save. It has the advantage of working on almost all desktop browsers, and many mobile browsers."
to "This is the default method of saving if no other method is installed. It uses your browser's built-in "download a file" handler, and has the advantage of working on almost all desktop browsers, and many mobile browsers."
* Add "platform" tags: `Windows, Mac, Linux, Android, iOS`

**Comment by pmario** [comment]
It's probably not possible to completely remove that tiddler, but we can create a second one with the new title. 

The title "Saving with the HTML5 fallback saver" is linked 8 times in the existing wiki and there are probably a lot of external links ... 

The best way would be to implement a "link forwarder" into TW, similar to wikipedia, that links known deprecated "permalinks" to the new tiddler title. 

The short term solution will be to have 2 tiddlers and remove the old title from the docs. 

I am creating a PR atm

**Comment by pmario** [comment]
@Jermolene .. Can we remove the **InternetExplorer** tag from the tiddler?

**Comment by pmario** [comment]
see: https://github.com/Jermolene/TiddlyWiki5/pull/7109

**Comment by Jermolene** [comment]
I think this can be closed – let me know if this ticket was not fully addressed by #7109
