### ISSUE TITLE
[BUG] Search text too short

### ISSUE THREAD

**Issue by RodrigoWebDev** [Jermolene/TiddlyWiki5#7114]
### Describe the bug

I have a tiddler called "IV", when I try to search for it, it display a message "Search text too short"

### Expected behavior

I think it will be great if I can search for even one letter

### To Reproduce

1. Open your tiddly wiki
2. Create a tiddler with two or less letters in the title
3. Try to search for it
4. You will see a message: "Search text too short"

### Screenshots

![image](https://user-images.githubusercontent.com/30677819/207136865-565b7fbe-a19f-40b2-8d55-7d480254c4fe.png)

### TiddlyWiki Configuration

- Version 5.2.3
- Saving mechanism TiddlyHost
- Plugins: https://github.com/Jermolene/TiddlyWiki5/tree/master/plugins/tiddlywiki/markdown

### Desktop (please complete the following information):

- OS: Windows 10
- Browser: Brave 1.46.140

Not tested on smartphone

**Comment by saqimtiaz** [comment]
This is configurable, see https://tiddlywiki.com/#Hidden%20Setting%3A%20Search%20Minimum%20Length

**Comment by pmario** [comment]
You can also add a space at the end.

**Comment by RodrigoWebDev** [comment]
> This is configurable, see https://tiddlywiki.com/#Hidden%20Setting%3A%20Search%20Minimum%20Length

> You can also add a space at the end.

Thanks! I will close the PR
