### ISSUE TITLE
[BUG] Lazy-loading seems to wait for the 1 minute timeout when tiddler is shown in story-river

### ISSUE THREAD

**Issue by pmario** [Jermolene/TiddlyWiki5#7138]
### Describe the bug

As the title says: Lazy-loading seems to wait for the 1 minute timeout when tiddler is shown in story-river

The issue was reported as a performance problem at Talk: https://talk.tiddlywiki.org/t/lazy-all-performance/5516

**To reproduce **

- The wiki is online at: https://flux.wvwlogs.com/#20221202-WvW-Log-Review 
- open it.
- As you can see this tiddler loads instantly -> OK
- now select a different tiddler from the Recent Sidebar
- If you are lucky it will show up immediately .. since the 1 minute timeout happened.
- If you are not lucky you will need to wait up to 1 minute

I did debug the code. .. It seems the tiddler is scheduled for lazy-loading but the function `self.processTaskQueue();` which is part of syncer.js and called 7 times is not tirggered with the newly listed tiddler. 

I did set 7 breakpoints and it breaks for `$:/StoryList` but it doesn't break for the newly listed tiddler. 

It seems to wait till the timeout is over. ... 

Since I don't know the syncer code for lazy loading too well, someone else may jump in here. 

@Jermolene @saqimtiaz @Arlen22  .. any ideas?

**Comment by Drevarr** [comment]
Server info in case it helps:
Oracle Cloud Server
Ampere A1 Compute instance
4 OCPUs and 24gb memory

- Ubuntu-22.04
- NodeJS-12.22.9
- NPM-8.5.1
- NGINX-1.18.0
- Tiddlywiki-5.2.4

Currently 3 instances of TW5 server running

**Comment by Arlen22** [comment]
The problem is that the syncer is apparently not loading the tiddler until the next polling interval completes. My guess is that there is a code path that doesn't call processTaskQueue after setting the tiddler for lazy load.

**Comment by Arlen22** [comment]
Line 331 of syncer.js could be the culprit

```
				if(updates.modifications.length > 0 || updates.deletions.length > 0) {
					self.processTaskQueue();
				}	
```

**Comment by Drevarr** [comment]
Didn't know if I should start a new issue or add here, advise and I will adjust accordingly.


Wiki refreshes every 60ish seconds to the original tab that was opened on the tiddler when first accessed.

1. Navigate to [https://flux.wvwlogs.com/#20221226-WvW-Log-Review](url) it currently opens on "Cleanses / Heals / Boon Score" reveal for an echarts bubble chart that is in the dashboard tab.
2. Click on another tab (Enemies Downed as example) you get the appropriate table and echarts bar chart revealed
3. Wait ~60 seconds
4. Page refreshes  to the original "Cleanses / Heals / Boon Score" reveal

Console shows the following after 3 above:
![image](https://user-images.githubusercontent.com/16168556/209614117-8c5589c9-162d-42e7-b75b-be2cb3cbee7f.png)

**Comment by Jermolene** [comment]
Thanks @pmario @Arlen22 I think I can see the problem, and will push a fix for testing shortly.

> Didn't know if I should start a new issue or add here, advise and I will adjust accordingly.

I think it might be a slightly difference problem @Drevarr – does the problem occur if you don't use lazy loading?

**Comment by Drevarr** [comment]
> I think it might be a slightly difference problem @Drevarr – does the problem occur if you don't use lazy loading?

It does occur when not using lazy load.  I'll start a new issue.

Although I have not updated to the latest master which solved my problem with [BUG] Lazy-loading seems to wait for the 1 minute timeout when tiddler is shown in story-river #7138
