### ISSUE TITLE
[BUG] RSOE - is it already resolved?

### ISSUE THREAD

**Issue by twMat** [Jermolene/TiddlyWiki5#7139]
### Describe the bug

In ver 5.2.23 the following gives RSOE **but not in 5.2.24**:  https://rsoe-7139.tiddlyhost.com

I bring this up just to make sure that I happened to stumble over a bug that was *just* resolved in the latest release - right? I'll close this bug report ASAP if that is confirmed. I can see why the following syntax is problematic (i.e the code instructs both to modify the value *and* delete the tiddler)

```
<$checkbox tiddler="$:/core/ui/Buttons/control-panel" listField=tags 
checked="$:/tags/TopRightBar" 
unchecked="$:/tags/PageControls" 
uncheckactions="""<$action-deletetiddler $tiddler="$:/core/ui/Buttons/control-panel"/>"""
/>
```

### Expected behavior

...

### To Reproduce

...

### TiddlyWiki Configuration

(see demo link)

**Comment by pmario** [comment]
TW versions are v5.2.x at the moment

**Comment by pmario** [comment]
Your code doesn't create a problem with v5.2.5 at tiddlywiki.com

**Comment by twMat** [comment]
@pmario - sorry I meant to ask about 5.2.23. I've corrected the OP. 

But never mind, my concern is probably silly. I couldn't locate any merged PR that seemed to address this but the bug *has* evidently been resolved since it works in .24 so I'm closing this. Thanks regardless.
