### ISSUE TITLE
[BUG] The Gesnesis Widget Creates a RSOD

### ISSUE THREAD

**Issue by kookma** [Jermolene/TiddlyWiki5#7140]
### Describe the bug

1. open https://tiddlywiki.com/#GenesisWidget
2. Create a new tiddler
3. start writing `<$genesis $type="" />` DONOT specifiy the $type
4. See the error

![image](https://user-images.githubusercontent.com/830394/208682488-4dc88eb9-c0ef-43dd-b26b-4cd51184f89e.png)

-Tiddlywiki 5.2.5
-Chrome 108
-Windows 10

**Comment by pmario** [comment]
may be related to: https://github.com/Jermolene/TiddlyWiki5/pull/7122

**Comment by Jermolene** [comment]
Thanks @kookma

**Comment by pmario** [comment]
@Jermolene .. Will this commit be automatically published to prerelease? .. Otherwise IMO it would be better to create a PR and merge it immediately. PRs get a preview build we can test

**Comment by Jermolene** [comment]
Hi @pmario the official prerelease for master is at https://tiddlywiki.com/prerelease. Vercel also makes a build of master at https://tiddlywiki5.vercel.app/. Both builds are automatically rebuilt every time there is a commit to the branch (ie a PR is not required).
