### ISSUE TITLE
[BUG] #-prefixed property-name not correctly reloaded on node-TW5

### ISSUE THREAD

**Issue by rimi** [Jermolene/TiddlyWiki5#7144]
### Describe the bug

A property where the name starts with the #-character is stored to a .tid-File correctly. But when you restart the wiki (node) it is not loaded as a property anymore.

### Expected behavior

Should be loaded accordingly. Should maybe switch to JSON-Format for the tiddler if # is maybe something like a comment-introducer for the TID-Format?

### To Reproduce

1. Start node-Version of latest release (bug produced with 5.2.5)
2. Create a tiddler and create property **#xyz** with some value and save it (.tid-file created)
3. Restart node and reload Wiki in browser
4. Property not displayed (it seems to "know" that there is a change when trying to just edit-close the tiddler, because TW complains about "lost changes")

### TiddlyWiki Configuration

- Version [e.g. v5.2.5]
- Saving mechanism: Node.js
- Plugins installed: tiddlyweb, filesystem

### Desktop (please complete the following information):

- OS: Win10
- Browser firefox
- Version 108.0.1

**Comment by Jermolene** [comment]
Thanks @rimi 

The origin is this commit 5c9b0d62c4b6bf5d2a1dd40d7fd9693a428cc3b5 from 2022 which adds the ability to include comments in .tid files starting with a `#` symbol. At the time, field names had to be alphanumeric, and were prohibited from containing a `#` symbol. Several years later, we extended the core to support fields with arbitrary names, but this problem slipped through the net.

As you note, a reasonable fix would be to switch to JSON format if a tiddler has any fields starting with a `#`.

**Comment by rimi** [comment]
Wow, 16 minutes to read+understand and reply with analysis, commit# and fix-proposal - impressive! Thanks @Jermolene!

**Comment by Jermolene** [comment]
> Wow, 16 minutes to read+understand and reply with analysis, commit# and fix-proposal - impressive! Thanks @Jermolene!

Thank you @rimi, much appreciated – although to be fair (a) you wrote the ticket very clearly and (b) the problem was intriguing enough that I stopped what I was doing to figure it out :smile: "git blame" is incredibly useful, even though frequently I'm the one that is to blame...

**Comment by Jermolene** [comment]
Thanks for your patience @rimi. There's a fix in 8ef6d78beffb6496fe5daa2c81a529a79046ba3c, do let me know how you get on.

**Comment by rimi** [comment]
Hi @Jermolene, thanks for that!
