### ISSUE TITLE
[BUG] Save wiki button status not accessible for colour blind users

### ISSUE THREAD

**Issue by Jermolene** [Jermolene/TiddlyWiki5#7145]
The save wiki button indicates "dirty" status by colouring the icon red. The transition between red and black is not accessible for some colour blind users.

It is proposed to:

* make the icon additionally change shape to reflect the dirty status
* ensure that the tooltip for the save wiki button also reflects the dirty status

The challenge is that internally the dirty status is implemented as the addition of the class "tc-dirty" to the body element. This means that only CSS can be used to implement the status differences.

We cannot use a state tiddler to indicate the dirty status because changing that state tiddler would itself change the dirty status of the wiki.

**Comment by xcazin** [comment]
> We cannot use a state tiddler to indicate the dirty status because changing that state tiddler would itself change the dirty status of the wiki.

Naive question: can't we exclude such a dirty status state tiddler from $:/config/SaverFilter ?

**Comment by twMat** [comment]
>The challenge is that internally the dirty status is implemented as the addition of the class "tc-dirty" to the body element. This means that only CSS can be used to implement the status differences.

Is this an implied request for ideas?

**Comment by Jermolene** [comment]
> Naive question: can't we exclude such a dirty status state tiddler from $:/config/SaverFilter ?

It may be possible to rig something up along those lines, but I think it would be somewhat brittle.

> Is this an implied request for ideas?

No, not at all, I was just giving context for the ticket.

**Comment by pmario** [comment]
>We cannot use a state tiddler to indicate the dirty status because changing that state tiddler would itself change the dirty status of the wiki.

May be if there is a new `[is[dirty]]` filter operator, we probably can make the state wikitext only.

Which as a side effect will also allow users to read this info.

**Comment by Jermolene** [comment]
> May be if there is a new `[is[dirty]]` filter operator, we probably can make the state wikitext only. So it would be possible to change the class and the icon.
> 
> Which as a side effect will also allow users to read this info.

Even with the `[is[dirty]]` operator, a change of dirty state wouldn't trigger the refresh needed to change the display.

Just to be clear, there is no problem here. The issue described is easily fixable within the constraints I mentioned.

**Comment by pmario** [comment]
May be a better name may be `[wiki[state]]` which returns "dirty" or "ok"

**Comment by pmario** [comment]
It may be doable with a completely new icon, that contains several components, which are controllable with CSS. ... Some experiments would be needed. 

How should the new icon look like?

**Comment by pmario** [comment]
The save button has an aria-label, but does it also have accessible info about the wiki state somewhere. ... If we are at it, it may be worth a closer view.

**Comment by Jermolene** [comment]
The approach I was thinking of investigating providiing two separate buttons, switching between them with CSS. A disadvantage of the approach is that the focus wouldn't retained over the switch between the two buttons.

**Comment by Jermolene** [comment]
There's a draft PR at #7232, with a preview at https://tiddlywiki5-git-accessible-save-button-jermolene.vercel.app

<img width="364" alt="Screenshot 2023-01-24 at 11 10 46" src="https://user-images.githubusercontent.com/174761/214278651-754d1c87-2a2d-4173-988c-2b67af47650b.png">
