### ISSUE TITLE
Arbitrary attachments

### ISSUE THREAD

**Issue by altaic** [Jermolene/TiddlyWiki5#715]
I'm using tw5 as a project wiki and would very much like to attach/embed arbitrary files in tiddlers. My files are generally small (a meg or so on average). From [this discussion](https://groups.google.com/d/topic/tiddlywiki/Yn1rDLkaINY/discussion), it seems as though such a thing is not currently possible.

**Comment by manoflinux** [comment]
totally possible, wrote a script so you can turn any file into a tid that you can import into the newest tiddlywiki. 
Also created a tiddlywiki to explain how to setup the script. Its still a work in progress so bear with me. 
Any suggestions welcome. 
http://filetotid.tiddlyspot.com/
