### ISSUE TITLE
[BUG] With 8k+ tiddlers, in a NodeJS wiki everything is Slow 

### ISSUE THREAD

**Issue by linonetwo** [Jermolene/TiddlyWiki5#7151]
### Describe the bug

I have imported 8k+ google calendar events into my nodejs wiki, they are mostly metadata, no long texts. Then each click in my wiki becomes slow, saving is slow, and starting the wiki is slow too.

- Each click takes 1.2s to calculate
- Starting wiki takes 10s+
- Sync adaptor saving a tiddler takes 1.2s

### Expected behavior

Be as fast as a empty wiki when we have 10 - 100k tiddlers, in nodejs wiki.

### To Reproduce

I will prepare a github repo later, but now I'm debugging in my own wiki...

### Screenshots

1. It is [core/modules/wiki-bulkops.js](https://github.com/Jermolene/TiddlyWiki5/blob/master/core/modules/wiki-bulkops.js) that being so slow on client side, when clicking bottons

![截屏2022-12-25 00 08 04](https://user-images.githubusercontent.com/3746270/209443798-c2fe9742-dda7-4a65-9640-04ae275a768e.png)
![截屏2022-12-25 00 08 35](https://user-images.githubusercontent.com/3746270/209443799-d92f8369-eb6a-4320-baad-f80d83b2d3bd.png)
![截屏2022-12-25 00 09 26](https://user-images.githubusercontent.com/3746270/209443800-506378ff-6073-4a10-8b5f-2694e2219ef1.png)

2. Starting TBD, what happened on nodejs side?
3. Saving TBD, what happened on nodejs side?

### TiddlyWiki Configuration

- Version 5.2.5
- Saving mechanism [Node.js]
- Plugins installed [lots of]

### Desktop (please complete the following information):

TidGi (darwin)
Version v0.7.13.

- Electron Version: 22.0.0
- Node Version: 16.17.1
- Chromium Version: 108.0.5359.62

### Additional context

I'll do some metrics tomorrow, and come up with a plan. I must fix this, because I want to use tw as my diary tool to replace the google calendar.

**Comment by pmario** [comment]
Did you try to create a new server and import your data there. Is it still slow. If not you may have to look at your plugins.

**Comment by linonetwo** [comment]
Can we remove the `toLowerCase()` here?

![](https://user-images.githubusercontent.com/3746270/209444590-b43b4654-6366-44cb-b1e8-73a2caf5e26d.png)

**Comment by Jermolene** [comment]
Hi @linonetwo performance at that scale is definitely a problem, and we welcome investigations to identify and optimise performance hotspots.

One thing I'd love to experiment with is to use the new SQLLite JavaScript release as the basis for the wiki store object. It has a synchronous API which is needed for the TW store.

**Comment by Jermolene** [comment]
> Can we remove the `toLowerCase()` here?

It is certainly possible that there is a more performant way of making a case-insensitive sort, and again would welcome investigations.

**Comment by linonetwo** [comment]
@pmario You are right, some of friends in QQ group report lagging is caused by locator plugin and kin filter plugin. I will try this in a clean environment.

**Comment by Jermolene** [comment]
I should have added that there are three usages of wiki.getTiddlers() in the core, and it looks like the usage in `wiki.countTiddlers()` doesn't need to be sorted at all, but in the other two usages the sorting is visible to users, and so cannot be altered without changing the semantics.

**Comment by linonetwo** [comment]
> SQLLite JavaScript release

One thing I like about nodejs wiki is its file based storage, which is nice for git diff, so I don't really want to use sqlite to solve this problem.

**Comment by Jermolene** [comment]
> One thing I like about nodejs wiki is its file based storage, which is nice for git diff, so I don't really want to use sqlite to solve this problem.

We wouldn't necessarily need to use SQLLite as our persistence format; we could still save to the same file formats that we do today.

**Comment by linonetwo** [comment]
I get it, you mean use sqlite as memory cache to speedup querying?

I can see the sync adaptor is slow because get all tiddlers are slow. I'm going to add some server-timing tomorrow, and maybe PR it as a metric to core.

![](https://user-images.githubusercontent.com/3746270/209444968-a5d84cbc-4cb7-48d5-9bc0-41e71772b798.png)

![](https://user-images.githubusercontent.com/3746270/209444953-a2f6617c-03f0-4eb2-bc69-ca327c19ed9c.png)

**Comment by pmario** [comment]
>... is caused by locator plugin and kin filter plugin.

I don't know locator, but IMO ink filter should only be slow, if it is shown.  Similar to the Recent tab. So if Open tab is shown by default it may be speedier.

**Comment by linonetwo** [comment]
\[all\[shadows+tiddlers\]tag\[$:/tags/StartupAction\]!has\[draft.of\]\](12942times)

![](https://user-images.githubusercontent.com/3746270/209467092-4ee1af27-90c7-4259-a9c4-a31c8d87e323.png)

Don't know where this filter is constructed, but it takes long time during `GET /`

**Comment by linonetwo** [comment]
It is kin-filter that being slow, but why will it be called during starting?

<img width="1604" alt="截屏2022-12-25 21 40 18" src="https://user-images.githubusercontent.com/3746270/209470194-00e09663-edaa-4479-888d-7cc07e516c56.png">

[flamegraph.html.zip](https://github.com/Jermolene/TiddlyWiki5/files/10300042/flamegraph.html.zip)

**Comment by linonetwo** [comment]
My script to generate the flame graph prifiling:

```shell
0x -o ./tiddlywiki.js "+plugins/tiddlywiki/filesystem" "+plugins/tiddlywiki/tiddlyweb"  /Users/linonetwo/Desktop/wiki/wiki --listen anon-username= port=5212 host=0.0.0.0 root-tiddler=$:/core/save/lazy-images
🔥  Profilingsyncer-server-filesystem: Dispatching 'save' task: $:/StoryList
Serving on http://0.0.0.0:5212
(press ctrl-C to exit)
```

**Comment by saqimtiaz** [comment]
Are there any startup actions in the wiki that use the kin filter?

**Comment by linonetwo** [comment]
I added up the filter consumed times, its 1004ms in my wiki, so other code takes 1.5S, I need to add more perf timers.

![](https://user-images.githubusercontent.com/3746270/209471140-0c69a92c-f441-4ed5-a3ec-29d4d8485079.png)

**Comment by linonetwo** [comment]
try https://github.com/Jermolene/TiddlyWiki5/discussions/6550

**Comment by pmario** [comment]
>There are still something to optimize on server side. But it seems not very urgent now. I'm going to fix client side first.

@linonetwo ... Did you find the problem? It's not clear to me. 

Do we need to keep this issue open -- or do you create a new one when you have more data

**Comment by linonetwo** [comment]
On server side, it is mostly because of FileSystemPaths.

On client side it is not clear, I will find time for this, so keep this open for a while.

**Comment by yaisog** [comment]
@linonetwo: Depending on what you need `kin` for, you might want to look at
[https://talk.tiddlywiki.org/t/recursive-filter-operators-to-show-all-tiddlers-beneath-a-tag-and-all-tags-above-a-tiddler/3814](https://talk.tiddlywiki.org/t/recursive-filter-operators-to-show-all-tiddlers-beneath-a-tag-and-all-tags-above-a-tiddler/3814)
I made these as a replacement for some of `kin`'s functionality for large wikis, where `kin` becomes slow.
