### ISSUE TITLE
[IDEA] Empty type on the genesis widget shouldn't produce a span

### ISSUE THREAD

**Issue by Telumire** [Jermolene/TiddlyWiki5#7153]
`<$genesis $type="">content</$genesis>` produce `<span>content</span>`

In my opinion it would be better to just produce "content", without span. This would be great to dynamically choose whether or not the content of the genesis widget is wrapped in a container.

One example where it would be useful is if we want to choose between using the link widget (internal links) or the wikitext parsing (external links) : 

```
\define link(to)
<$let search={{{ [<__to__>minlength[3]]:map[all[tiddlers+shadows]search:title<__to__>] }}}>
<$genesis $type={{{ [<search>is[tiddler]then[$link]] }}} $names="to" $variables={{{ [<search>is[tiddler]] }}}>
<<__to__>>
</$genesis>
</$let>
\end

<<link "https://demos.tiddlyhost.com">>
```

**Comment by Jermolene** [comment]
Good idea @Telumire
