### ISSUE TITLE
[BUG] Genesis widget: names begining with "on" are not rendered

### ISSUE THREAD

**Issue by Telumire** [Jermolene/TiddlyWiki5#7154]
### Describe the bug

`<$genesis $type="div" $names="one two three" $values="1 2 3">Content</$genesis>`

produce

` <div three="3" two="2">Content</div>`

### Expected behavior

 ` <div one="1" three="3" two="2">Content</div>`

 Demo: https://demos.tiddlyhost.com/#/genesis-bug

### TiddlyWiki Configuration

- Version 5.2.6-prerelease

**Comment by Telumire** [comment]
As @pmario deduced,iIt seems like this issue is coming from the attribute sanitation that prevent inline javascript (onClick, ..). This is an issue if a user want to use a attribute beginning with "one". Maybe tiddlywiki should trim attribute based on a list of existing on.. event rather than simply using the prefix "on" ?

**Comment by pmario** [comment]
>Maybe tiddlywiki should trim attribute based on a list of existing [HTML Event Attributes](https://www.w3schools.com/tags/ref_eventattributes.asp) rather than simply using the prefix "on" ?

IMO that's not possible. We will also sanitize future `onxxx` elements with the same mechanism.

**Comment by pmario** [comment]
>Or simply put a warning in the doc to not use attributes starting with "on" if it's not feasible ?

I would vote for a message directly shown by the widget. eg: `parameter: "one" blocked because it is prefixed "on", which is not allowed`

**Comment by Jermolene** [comment]
Hi @Telumire @pmario the sanitisation takes place at the level of the `widget.assignAttributes()` method, which is used by the internal `<$element>` widget. See https://github.com/Jermolene/TiddlyWiki5/blob/6f9cf20e7737fc992ea9d11947ccdd8aadf8b6ce/core/modules/widgets/widget.js#LL325C2-L325C2

It would make things a good deal more complex if we wanted to display an error message in these cases. I'd prefer to have a more general purpose mechanism for flagging and logging wikitext issues. In particular, displaying an error message wouldn't work within action strings.
