### ISSUE TITLE
[BUG] import some binary file will corrupted the file (eg. mp3 file)

### ISSUE THREAD

**Issue by cs8425** [Jermolene/TiddlyWiki5#7157]
### Describe the bug

import a `.mp3` file, the file can not be play and the file is corrupted (content not encode in base64).

### Expected behavior

the file can be play normally, and is encoded in base64

### To Reproduce

1. get a empty wiki (`empty.html`)
2. drag a .mp3 file to wiki
3. import it
4. the imported file can not be played, and it's not encode in base64.

### TiddlyWiki Configuration

- Version: v5.1.24
- Saving mechanism: single file
- Plugins installed: none
- Browser: Chrome 108.0.5359.124 (64bit, Linux), Firefox 108.0 (64bit, Linux)

### Additional context

For `.mp3` file, MIME got from browser is `audio/mpeg` not `audio/mp3`
https://github.com/Jermolene/TiddlyWiki5/blob/0b1a4f3a4d80a58729ce5b399cf0d38b5f29a279/boot/boot.js#L2410

and `wiki.readFile()` will treat as text file, so the file will corrupted.
https://github.com/Jermolene/TiddlyWiki5/blob/35b0833e0cafc477e402309c006a163eb59a94ca/core/modules/wiki.js#L1464-L1465

Some other type will happened too,
so I think we should default to binary if the type is unknown.

I make a plugin using `th-importing-file` hook to fix this issue, but not fully fix,
the `th-importing-file` hook can not get the original `deserializer`,
maybe we should pass it to hook too?
https://github.com/Jermolene/TiddlyWiki5/blob/35b0833e0cafc477e402309c006a163eb59a94ca/core/modules/wiki.js#L1471-L1478

Here is the plugin for partial fix:
[$__plugins_tiddlywiki_fix-content-type-handle.json.gz](https://github.com/Jermolene/TiddlyWiki5/files/10317844/__plugins_tiddlywiki_fix-content-type-handle.json.gz)

Edit: update plugin and try to make a PR for fixing other related part in core

**Comment by Jermolene** [comment]
Thank you @cs8425 – in my testing it seems that a simpler fix is to modify boot.js immediately after the line `$tw.utils.registerFileType("audio/mp3","base64",".mp3");` to add the line:

```
$tw.utils.registerFileType("audio/mpeg","base64");
```

I'll do some more testing and commit the fix shortly.

**Comment by cs8425** [comment]
Change the line which define the MIME will fix this quickly, but I think we could make it better.
We can not list all MIME into `boot.js`, and user will noticed the file is corrupted only if they import and try to open/download it (and mostly the browser will freeze a while due to file size larger than 512KB or so).

Currently if user need to add more content-type, thery need to write a plugin set more type in `$tw.config.contentTypeInfo` or change `boot.js` and rebuild a wiki.
Both need the do a full reload for new added content-type work. << am I right?  I'm not sure..

If we treat imported file which MIME is not defined as binary, the file won't break and won't freeze the browser (PR #7158).
I think this will be more useful and we also don't need to maintain a huge list of MIME.

**Comment by Jermolene** [comment]
Hi @cs8425 you are absolutely correct, the current architecture is very brittle. We are constrained by backwards compatibility, so perhaps the best approach would be to introduce a new helper function `$tw.utils.isBinaryContentType(type)` (and possibly we might also need `$tw.utils.isBinaryFileExtension(extension`) that returns a boolean given a MIME type. It would use the existing logic to lookup the type and return the flag, but we could improve the handling for unknown MIME types to default to binary for certain prefixes (eg "image", "application"). Then we'd refactor the existing code to use that method.
