### ISSUE TITLE
[BUG] Rare exception using jsonget with "fixed" as extra parameter

### ISSUE THREAD

**Issue by Alzacon** [Jermolene/TiddlyWiki5#7160]
### Describe the bug

If I use jsonget with a extra parameter the normal return is a empty string because this extra doesn't exist in the json data. But if the extra parameter is "fixed" the return is `function fixed() { [native code] }`.

### Expected behavior

Return a empty string

### To Reproduce

1. Copy and paste in a new tiddler the following code :
```
\define my-json() 
{
"a": "1"
}
\end

\define test() fixed

{{{ [<my-json>jsonget[a],<test>] }}}
```
2. Save it (or open the preview)
3. See the exception

### TiddlyWiki Configuration

- Version:  v5.1.25
### Desktop
- OS: Windows7
- Browser: Firefox, Chrome

### Additional context

I discovered it because I was remaking my json with change the filter expression. I had(have) "fixed" as index in the json. Maybe there are others names of paramater that produces similar exception.

**Comment by Jermolene** [comment]
Thank you @Alzacon for the very clear and helpful bug report. Fix coming up.
