### ISSUE TITLE
Correction to Documentation SystemTag $:/tags/Filter

### ISSUE THREAD

**Issue by kookma** [Jermolene/TiddlyWiki5#7161]
### Describe the bug

In 
https://tiddlywiki.com/#SystemTag%3A%20%24%3A%2Ftags%2FFilter

The caption is empty, and it should be description.

### Expected behavior

Use description instead of caption

### To Reproduce

See https://tiddlywiki.com/#SystemTag%3A%20%24%3A%2Ftags%2FFilter

### Screenshots

![image](https://user-images.githubusercontent.com/830394/210078582-16e07d81-1ad8-46d3-a2a2-a460ed9565d5.png)

### TiddlyWiki Configuration

- TiddlyWiki 5.2.5

I can make a PR to correct this.

BUT, I think the tiddlers with $:/tags/Filter shall have caption instead of description. I am not sure if removing description is backward compatible or not.

**Comment by Jermolene** [comment]
Thanks @kookma. Tiddlers tagged $:/tags/Filter use a "description" field instead of the usual "caption" field. Fix coming up.
