### ISSUE TITLE
[BUG] Innerwiki $data widget with $tiddler attribute does not allow attribute override

### ISSUE THREAD

**Issue by btheado** [Jermolene/TiddlyWiki5#7171]
### Describe the bug

The documentation for the `$data` widget with the `$tiddler` attribute seems to say that remaining attributes will override the attributes from the original tiddler:
https://github.com/Jermolene/TiddlyWiki5/blob/04810667e6e5cb788b52652e6adb84a1ae0330bc/plugins/tiddlywiki/innerwiki/doc/docs.tid#L35

However, on https://tiddlywiki.com/plugins/tiddlywiki/innerwiki/ if I create the tiddler with this content:

```
<$innerwiki width="1024" height="400" style="width:100%;">
  <$data $tiddler="HelloThere" text=""/>
  <$data title="$:/DefaultTiddlers" text="HelloThere"/>
</$innerwiki>
```
then the HelloThere tiddler in the innerwiki has the text field copied from the outer wiki instead of blanked out by the `text=""` attribute.

The code looks like it is giving precedence to the fields in the original tiddler fields rather than the attributes in the `$data` widget:
https://github.com/Jermolene/TiddlyWiki5/blob/04810667e6e5cb788b52652e6adb84a1ae0330bc/plugins/tiddlywiki/innerwiki/innerwiki.js#L292-L299

### Expected behavior

It should be possible to override the tiddler fields when using `<$data $tiddler/>`

### To Reproduce

1. Go to https://tiddlywiki.com/plugins/tiddlywiki/innerwiki
2. Add a new tiddler with the content from this issue's description
3. The body of the HelloThere tiddler should be blank in the innerwiki but it is not.

### TiddlyWiki Configuration

browser TW version 5.2.5

**Comment by Jermolene** [comment]
Thanks @btheado that does seem to be bug; I think it should be `results.push($tw.utils.extend({},fields,item));`. A PR would be welcome.
