### ISSUE TITLE
[BUG] Button changing a field value on current tiddler refreshes to original state after delay

### ISSUE THREAD

**Issue by Drevarr** [Jermolene/TiddlyWiki5#7177]
### Describe the bug

Initial discussion here: https://talk.tiddlywiki.org/t/nodejs-lazy-all-interation-with-buttonwidget/5616

I am utilizing a button to set the value of field `curTab` to initiate a reveal as part of navigation scheme on long text tiddlers.

In "read-only" mode, after clicking a button the field value updates and the reveal works as expected, however after a delay the tiddler resets to the original saved state.

### Expected behavior

curTab field should retain the setting invoked by the button and maintain the reveal without resetting to the saved state.

This is how it works if you are logged in as an authenticated writer.

### To Reproduce

1. Go to 'https://wvwlogs.com/#Test%20Buttons'
3. Click on 'Session Overview button'
4. Wait for 1-60 seconds
5. Observe the change back to 'Squad Composition' reveal
6. If you were logged in as an authenticated user, this errant behavior wouldn't occur

- also occurs under lazyall configuration @ https://kdr.wvwlogs.com or https://flux.wvwlogs.com

### TiddlyWiki Configuration

- Version [e.g. v5.1.24]
- Saving mechanism [Node.js]
- Plugins installed [base nodejs server plugins] @ https://wvwlogs.com
- Plugins installed [Echarts, Shiraz] @ https://kdr.wvwlogs.com and https://flux.wvwlogs.com

### Server
-OS: [Ubuntu]

### Desktop (please complete the following information):

- OS: [Windos10]
- Browser [Firefox]

**Comment by Drevarr** [comment]
Upgraded to latest master branch (8ca0bf1) to take advantage of the fix for [BUG] Lazy-loading seems to wait for the 1 minute timeout when tiddler is shown in story-river #7138.

Issues above still persists, just wanted to update the version currently in use.

**Comment by Drevarr** [comment]
It appears that I can move from setting a field to utilizing a state tiddler and avoid the refresh while not logged in to the wiki.

**Replace:**

```
<$button set="!!curTab" setTo="Overview" selectedClass="" class="btn btn-sm btn-dark" style=""> Session Overview </$button>
```

**With this:**

```
<$button set="$:/state/curTab" setTo="Overview" selectedClass="" class="btn btn-sm btn-dark" style=""> Session Overview </$button>
```
However, this would require startup activity to establish the state tiddlers to ensure the tiddler opens to an initial state.  Multiple if I want each tiddler to have its own initial state.

A lot of activity to replace utilizing fields to work around the refresh issue.

**Comment by Drevarr** [comment]
Syncer logs showing loading tiddler, after navigating by button widget that updates a userfield to a reveal state other than the saved state.

```
2023 1 10 22:13:51.215: Retrieving skinny tiddler list
2023 1 10 22:13:51.472: Dispatching 'load' task: 20230109-WvW-Log-Review
2023 1 10 22:13:51.580: Checking dirty status
2023 1 10 22:13:51.592: Checking dirty status
2023 1 10 22:13:51.605: Checking dirty status
2023 1 10 22:13:56.925: Dispatching 'save' task: 20230109-WvW-Log-Review
2023 1 10 22:13:56.925: Checking dirty status
2023 1 10 22:13:56.935: Checking dirty status
2023 1 10 22:14:51.470: Retrieving skinny tiddler list
2023 1 10 22:14:51.711: Dispatching 'load' task: 20230109-WvW-Log-Review
2023 1 10 22:14:51.929: Checking dirty status
2023 1 10 22:14:51.940: Checking dirty status
2023 1 10 22:14:51.952: Checking dirty status
```

**Comment by pmario** [comment]
>However, this would require startup activity to establish the state tiddlers to ensure the tiddler opens to an initial state. Multiple if I want each tiddler to have its own initial state.

The tabs macro has a default value, that is used if the state doesn't exist. So no startup actions needed at all.

**Comment by Drevarr** [comment]
> The tabs macro has a default value, that is used if the state doesn't exist...

I didn't plan in a tiddlywiki mindset when I wrote the program to generate the .tid output.  The summary is a single large tiddler and 45 echart tiddlers.  So I don't have a `list of tiddlers` for the `tabsList` unfortunately.  Which is why I settled on recreating the equivalent of tabs with `$button` and `$reveal`.  Although at this point I could have rewritten the program to write each segment as a tiddler and utilized the tabs macro.

It's been a good learning experience, I managed to set up a linux server and get the wikis up and running, and i'm utilizing the `$button` work around above.  And a slightly different work around for `$radio`, due to a contributed PR, along the lines of:
`<$radio tiddler="$:/temp/BurstDamage" field="curBurstTableType" value="Cumulative">`

**Comment by pmario** [comment]
>It appears that I can move from setting a field to utilizing a state tiddler and avoid the refresh while not logged in to the wiki.

I think that's the only way to avoid the re-upload of the original tiddler, because the state cannot be saved back to the field if not logged in. It will reload the info after 1 minute. 

So I think there is no way other than tiddlers that are not synced.

**Comment by Drevarr** [comment]
My take-away from this learning opportunity:
- Any widget that adds/changes/deletes a field will work for authenticated writers but for `read only users` it will cause the tiddler to be dirty and thus refresh at the end of the current 60sec syncer action.   
- If the widget has the capability to work with a tiddler that is tagged such that is doesn't invoke the saver logic, then I can utilize it as intended.
- Review all widgets to identify those that can't work with state or temp tiddlers and avoid for read only purposes.

Have I missed the mark here?

**Comment by pmario** [comment]
The [syncFilter](https://tiddlywiki.com/#%24%3A%2Fconfig%2FSyncFilter) tiddler is responsible to trigger the dirty state for Node.js server setups. 

>Have I missed the mark here?

I think that's about it.

**Comment by Drevarr** [comment]
Thanks for providing the insight and letting me explore.
