### ISSUE TITLE
[BUG] Layout switcher doesn't work on mobile

### ISSUE THREAD

**Issue by pmario** [Jermolene/TiddlyWiki5#7178]
### Describe the bug

The layout switcher doesn't work on mobile because CTRL SHIFT L can't be used. 

### Expected behavior

There should be a button similar to the theme switcher.

**Comment by Jermolene** [comment]
Hi @pmario there is a button for the layout switcher in v5.2.4:

<img width="294" alt="image" src="https://user-images.githubusercontent.com/174761/210607758-673018c8-25a9-43ad-846d-8c4cdd311ad1.png">

See https://github.com/Jermolene/TiddlyWiki5/pull/7076

**Comment by pmario** [comment]
Nice. May have forgotten about it. I didn't recognise the icon. my bad.
