### ISSUE TITLE
[IDEA] Debug Logging for Filters

### ISSUE THREAD

**Issue by yaisog** [Jermolene/TiddlyWiki5#7184]
I'm sorry if this is a duplicate, but I have searched and found nothing.

I would _really_ like a logging functionality for filters, akin to `$log` and `$action-log`. I could imagine a `log[]` filter operator that does nothing but print the list of input tiddlers to the console. If one wanted to go further, the log could take variable names (like `currentTiddler` or `..currentTiddler`) as parameter(s) and log their value, too.

Filters can be a complex beast, especially with subfilters, reduce, map, especially where operators are defined elsewhere in the code. Such a debug logger could help a lot.

Have a nice day
Yaisog

**Comment by pmario** [comment]
The biggest problem I do have with complex filters, most of the time is "typos". IMO the best way to get that right is the AdvancedSearch -> Filters tab. ... 

IMO you can already log filter outputs if they are stored in variables if you use the `$log` widget. ... IMO it's easy to put filter outputs into variables. ... So I don't see a reason for a new widget. IMO `$log and $action-log` will work well for your usecase described.

**Comment by pmario** [comment]
While developing complex filters the biggest problem I do have to keep track of the versions that I did try already. .. For that usecase I do use my [advanced-search-plus](https://wikilabs.github.io/editions/advanced-search-plus/) plugin, which allows me to save a lot of different filtered searches and go back and forth between them. 

I'll publish a new version of that plugin soon. ... It does not work with variables atm.

**Comment by pmario** [comment]
Sometimes I also use the "tooltip" parameter of buttons or other elments, that have a tooltip parameter to store the filter-output. .. IMO it's an easy and convenient way to see  filter-output on hovering over elements. 

... Just a suggestion, that works well for me

**Comment by Jermolene** [comment]
Hi @yaisog that's a great idea, would you like to pursue a PR?

**Comment by ericshulman** [comment]
There is already a `log[]` filter operator.  Its a math function.  See https://tiddlywiki.com/#log%20Operator

**Comment by Jermolene** [comment]
> There is already a `log[]` filter operator. Its a math function. See https://tiddlywiki.com/#log%20Operator

Good point @ericshulman. We could go with `debug-log[]` which makes the intention clearer in any case.

**Comment by yaisog** [comment]
> Hi @yaisog that's a great idea, would you like to pursue a PR?

I'm not much of a JavaScript programmer. This would be a copy-paste job with some light supplementing by me. Are you sure that is what you want? *shy smile*

**Comment by Jermolene** [comment]
> I'm not much of a JavaScript programmer. This would be a copy-paste job with some light supplementing by me. Are you sure that is what you want? *shy smile*

No worries at all! I hadn't kept track of whether you'd made JS PRs before.

**Comment by CodaCodr** [comment]
`debug-log[]` seems a bit clunky.

`flog[]` / `logf[]` perhaps?

**Comment by yaisog** [comment]
I don't wanna toot my own horn, but this thing is pure gold. Now that I have an implementation running, I'm using it so much that I have no idea why I didn't come up with this a long time ago.
This will take my filter-writing to the next level!
![monkey_1f412](https://user-images.githubusercontent.com/1133745/211399332-4fe9e7cc-e71d-43e8-bab5-7c97e928fa1d.png)

Y'all have a nice day
Yaisog

**Comment by yaisog** [comment]
Here's another nice application for this filter operator:
If you use `\define tv-action-refresh-policy() always` without much care, it may happen that certain filters inside `$set` are calculated _often_ (I had a case where 10 expensive filter repetitions occured for a single button click, because there were a bunch of actionWidgets involved). This is not something you can easily see with `$action-log` and friends.

**Comment by yaisog** [comment]
For anyone stumbling upon this issue: Since an expeditious inclusion in the core is currently not likely, there is a plugin version of the current implementation available at [https://talk.tiddlywiki.org/t/concise-vs-readable-reveal-and/5934/18](https://talk.tiddlywiki.org/t/concise-vs-readable-reveal-and/5934/18).
