### ISSUE TITLE
[IDEA] Allow the use of variables in the rules pragma

### ISSUE THREAD

**Issue by Telumire** [Jermolene/TiddlyWiki5#7186]
For example: 

`\define rule-safe-css()  only filteredtranscludeinline transcludeinline macrodef macrocallinline macrocallblock`

then this could be used like this:

```
\rules <<rule-safe-css>>
```

The core could provide a few rules variable, which would be more readable / user friendly

**Comment by Jermolene** [comment]
Hi @Telumire sadly this wouldn't be possible. The problem is that the `rules` pragma needs to be fully interpreted at the time that the tiddler is parsed but at parse time we don't have access to variables.

I think the underlying issue might be addressed in a different way by #345.

**Comment by Telumire** [comment]
Yes this would work too ! I'll close this since it's kind of a duplicate of #345
