### ISSUE TITLE
[BUG] No action-navigate to createTiddler-title

### ISSUE THREAD

**Issue by twMat** [Jermolene/TiddlyWiki5#7199]
### Describe the bug

No navigation takes place after clicking this button. But if the `$to=` parameter value is exchanged for an existing title, it does navigate.

```
<$button>
<$action-createtiddler $basetitle="foo" $template="HelloThere" />
 <$action-navigate $to=<<createTiddler-title>>/>
+
</$button>
```
Same problem if `<<createTiddler-draftTitle>>` instead of -title.

I don't know *when* `<<createTiddler-title>>` is calculated but IF it is supposed to exist already before the button is clicked, then maybe the following gives a clue to the bug:

```
<$button>
<$action-createtiddler $basetitle="foo" $template="HelloThere" />
 <$action-navigate $to=<<createTiddler-title>>/>
No title seen here &rarr; <<createTiddler-title>> &larr;
</$button>
```

### Expected behavior

Navigation to the just created tiddler

### To Reproduce

Test on tiddlywiki.com

### TiddlyWiki Configuration

Brave Browser

**Comment by pmario** [comment]
No bug. The info is at [the docs](https://tiddlywiki.com/#ActionCreateTiddlerWidget): 

> New in: 5.2.0 -- Note that the attributes $savetitle and $savedrafttitle are no longer needed. Instead, any action widgets that need to use the title of the newly created tiddler should be contained within the action-createtiddler widget, and reference the variables createTiddler-title and createTiddler-draftTitle to obtain the title.

The variable `createTiddler-title` is only available inside the action-createtiddler widget **body**
The code needs to be 

```
\define actions()
<$action-createtiddler $basetitle="foo" $template="HelloThere">
    <$action-navigate $to=<<createTiddler-title>>/>
</$action-createtiddler>
\end

<$button actions=<<actions>> >+</$button>
```

**Comment by twMat** [comment]
>only available inside the action-createtiddler widget body

Ouch! That's obvious when you point it out. Thanx @pmario !

**Comment by twMat** [comment]
@pmario 
...hm... rather than making a fool of myself again by posting a new issue, let me just follow up with this here:

So does *this* code produce the intended result?

```
<$button>
<$action-createtiddler $basetitle="foo" $template="HelloThere">
 <$action-navigate $to=<<createTiddler-draftTitle>>/>
</$action-createtiddler>
+
</$button>
```

It navigates to a tiddler in **viewmode** titled `Draft of 'foo'`. I was expecting it to navigate to `foo` in editmode.
