### ISSUE TITLE
[PR] Add example #5 to ActionCreateTiddlerWidget.tid

### ISSUE THREAD

**Issue by twMat** [Jermolene/TiddlyWiki5#7200]
I know there are instructions on how to make a proper PR but I don't recall where to find them and, regardless, I remember they are still way to convoluted. So I hope this can be accepted.

The doc [ActionCreateTiddlerWidget](https://tiddlywiki.com/prerelease/#ActionCreateTiddlerWidget) lists several examples with buttons using this widget - but as detailed [here](https://talk.tiddlywiki.org/t/is-a-request-for-navigate-to-draft-justified/5832), it is not clear how to make a button that creates a tiddler **and navigates to its draft**.

This attached file is a single example for the ActionCreatTiddlerWidget doc to compliment the already existing four example tiddlers. (gh doesn't accept `.tid` so it is a *zipped* `.tid`)

[ActionCreateTiddlerWidget Example 5.zip](https://github.com/Jermolene/TiddlyWiki5/files/10393664/ActionCreateTiddlerWidget.Example.5.zip)

In addition, the actual doc tid https://tiddlywiki.com/prerelease/#ActionCreateTiddlerWidget should be suffixed with 

```
---

<<<
{{ActionCreateTiddlerWidget Example 5}}
<<<
```

**Comment by pmario** [comment]
See PR: https://github.com/Jermolene/TiddlyWiki5/pull/7202

**Comment by twMat** [comment]
Thanks @pmario !
