### ISSUE TITLE
[BUG] Share plugin generates stale urls

### ISSUE THREAD

**Issue by btheado** [Jermolene/TiddlyWiki5#7205]
### Describe the bug

The `$:/plugins/tiddlywiki/share/wizard` tiddler is rendered above the story one time at startup. The action widgets in the "Generate sharing link" are rendered at the same time and are never refreshed unless the sharing filter gets changed.

That means the list of tiddlers and the tiddler content to be shared (i.e. the share url) is generated only at startup. Any changes made to tiddlers matching the filter will not be included in the url when the "Generate sharing link" button is clicked.

### Expected behavior

The content of the share link should be refreshed whenever any of the content in the share filter changes.

### To Reproduce

1. Go to https://tiddlywiki.com/prerelease/share.html
2. Create and save a "New Tiddler"
3. Click the "Generate sharing link" button to copy the link to clipboard
4. Paste the clipboard contents somewhere
5. Notice the "New Tiddler" is not present in the pasted url. This is the bug.
6. Trigger a refresh by adding and then removing a space character to/from the sharing filter text box
7. Repeat steps 3 and 4.
8. Notice the "New Tiddler" is now present in the pasted url. This is a workaround.

### TiddlyWiki Configuration

https://tiddlywiki.com/prerelease/share.html - 5.2.6-prerelease

**Comment by btheado** [comment]
Note that decoding of urls in the share plugin is broken until #7204 gets merged.

**Comment by Jermolene** [comment]
Thanks @btheado. I had a brief look at the code, it seems possible that judicious use of `tv-action-refresh-policy` might help here. Would you be interested in investigating a fix?

**Comment by btheado** [comment]
Yes, @Jermolene! Thanks for the `tv-action-refresh-policy` tip. That got me unstuck. PR submitted.
