### ISSUE TITLE
[BUG] Deleting missing tiddler should close it

### ISSUE THREAD

**Issue by twMat** [Jermolene/TiddlyWiki5#7217]
### Describe the bug

Clicking "delete tiddler" from a *missing* tiddlers toolbar should close the tiddler. Currently, nothing happens.

While tiddlywikians might excuse this (hmmm), it would be the more confusing for non-tiddlywikians.

### To Reproduce

1. Go to tiddlywiki.com
2. Create a tiddler with `[[foo]]` as its text, and save the tiddler.
3. Click the foo link
4. In the missing foo tiddler, click the more tool and then the delete/garbage can. ---> nothing happens

### TiddlyWiki Configuration

(System config is likely irrelevant)

**Comment by Jermolene** [comment]
Good thinking, fix coming up.
