### ISSUE TITLE
[BUG] Really small flaw in $:/core/ui/Buttons/save

### ISSUE THREAD

**Issue by Flammonauta** [Jermolene/TiddlyWiki5#7220]
### Describe the bug

In the code of $:/core/ui/Buttons/save there is one line too many, which creates an unwanted space next to the save button if there is a button to the right of it in the EditToolbar. 

To remove it, just delete the last line of that code, after `<<save-tiddler-button>>`.

### To Reproduce

If anyone wants to see it, it happens even with the most recent empty.html on https://tiddlywiki.com/. (**5.2.5**)
Just go in `$:/ControlPanel > Appearance > Toolbars > EditToolbar` and move `$:/core/ui/Buttons/save` above the "delete" or "cancel" buttons, then edit a tiddler and you can see the space. Then if you edit `$:/core/ui/Buttons/save` and you delete the last empty line, that space goes away.

### TiddlyWiki Configuration

- Version [5.2.5]

### Additional context

```
\define save-tiddler-button()
\whitespace trim
<$fieldmangler><$button tooltip={{$:/language/Buttons/Save/Hint}} aria-label={{$:/language/Buttons/Save/Caption}} class=<<tv-config-toolbar-class>>>
<<save-tiddler-actions>>
<$list filter="[<tv-config-toolbar-icons>match[yes]]">
{{$:/core/images/done-button}}
</$list>
<$list filter="[<tv-config-toolbar-text>match[yes]]">
<span class="tc-btn-text"><$text text={{$:/language/Buttons/Save/Caption}}/></span>
</$list>
</$button></$fieldmangler>
\end
<<save-tiddler-button>>
HERE ONE LINE TOO MUCH (EMPTY)
```
I'm no expert, if that empty line is actually wanted for some reason, my bad

**Comment by Jermolene** [comment]
Thank you for the comprehensive report @Flammonauta, and welcome to the project. Your diagnosis is correct. I will investigate a more robust fix – I think it should be possible to use `\whitespace trim` to ensure that the rendering is consistent regardless of the presence of that final line break. If that's not possible then I might look at adding some tests that check for the terminating line breaks on the core tiddlers where it is required.

**Comment by Flammonauta** [comment]
I did a very quick test and adding `\whitespace trim` at the top works even without deleting that line break, you're right. And thanks for the welcome :)

**Comment by Jermolene** [comment]
Thanks @Flammonauta would you be interested in putting together a PR to fix this consistently across all the affected buttons? If so, please start with a PR to the 'tiddlywiki-com' branch with your signature for the Contributor License Agreement (see [contributing.md](https://github.com/Jermolene/TiddlyWiki5/blob/master/contributing.md)). Please feel free to ask for help.

**Comment by pmario** [comment]
@Flammonauta ... Welcome. I've seen that you probably created a GitHub account to post this issue. ... \o/

I don't know if you are comfortable with git and GitHub, to create pull requests. If you think you can do it, it would be very welcome. We can guide you if you are willing to take the challenge.

If you are not comfortable with the whole process, just tell us. ... There should be no pressure ;)

**Comment by Flammonauta** [comment]
Alas no, I hardly knew what a pull request is. But maybe in the future I'll try, I'm really enjoying TiddlyWiki and I'd be happy to help, but maybe in a future moment where I will have more time at my disposal (and then I will probably be a better help, I'm slowly but surely improving my knowledge with TiddlyWiki)
Thanks anyway for the proposal, maybe I'll come back

**Comment by Jermolene** [comment]
> Alas no, I hardly knew what a pull request is. But maybe in the future I'll try, I'm really enjoying TiddlyWiki and I'd be happy to help, but maybe in a future moment where I will have more time at my disposal (and then I will probably be a better help, I'm slowly but surely improving my knowledge with TiddlyWiki)
> Thanks anyway for the proposal, maybe I'll come back

No worries @Flammonauta – it's worth asking! There are many ways that people contribute to the TiddlyWiki community, and we're always happy to help you with any problems if that's the route you want to take.

Communities like ours greatly value the perspective of newcomers. Many of us have been living with TiddlyWiki for many years, and we're very close to it. Just asking questions as a newcomer can be incredibly helpful in helping us to understand the barriers faced by new users.

**Comment by pmario** [comment]
I'll create a PR for this one
