### ISSUE TITLE
[IDEA] it is proposed to add a "focusSelect" parameter to the edit-text widget

### ISSUE THREAD

**Issue by pmario** [Jermolene/TiddlyWiki5#7221]
At [Talk](https://talk.tiddlywiki.org/t/focus-on-the-body-when-entered-into-edit/5955/11) it is proposed to add a **focusSelect** parameter to the edit-text widget

From Eric Shulman at Talk

-------------

Currently, the $edit-text widget supports a focus="yes" parameter, which is handled by

$:/core/modules/editor/engines/simple.js, here:

```
SimpleEngine.prototype.focus  = function() {
	if(this.domNode.focus && this.domNode.select) {
		this.domNode.focus();
		this.domNode.select();
	}
};
```

and by $:/core/modules/editor/engines/framed.js, here:

```
FramedEngine.prototype.focus  = function() {
	if(this.domNode.focus && this.domNode.select) {
		this.domNode.focus();
		this.domNode.select();
	}
};
```

Note that these functions not only set the input focus on the domNode, but they also select the domNode contents.

In order to support the proposed new behavior, this handling would need to be re-written. I suggest adding a new select="no" parameter to the $edit-text text widget so that the current hard-coded behavior can be bypassed if desired.

Note that, for backward compatibility, the default when this new parameter is omitted must be to still select the domNode contents as it presently does.

**Comment by ericshulman** [comment]
Upon further thought, perhaps the new widget parameter should be called `focusSelect`, so that it makes it clear that the behavior it controls is handled when the edit-text widget gets the focus.  Thus, there would be three focus-related parameters:
* `focus=yes` - sets the focus when the widget is created
* `focusPopup=popupID`  - opens a popup when the widget is focused
* `focusSelect=no`  - prevents the content from being selected when the widget is focused

**Comment by ericshulman** [comment]
On [Talk](https://talk.tiddlywiki.org/t/focus-cursor-at-beginning-of-text-field/3823), it was requested to have a way to put the cursor at the beginning of an `$edit-text` field

To support this, I suggest that the proposed `focusSelect` parameter handle the following values when `focus=yes` is used:
* `focusSelect=yes` - field gets focus, content is selected (the current default behavior)
* `focusSelect=no` - field gets focus, cursor is placed where click occurs (default browser behavior)
* `focusSelect=start` - field gets focus, cursor is placed at start of content
* `focusSelect=end` - field gets focus, cursor is placed at end of content

**Comment by Jermolene** [comment]
Thanks @ericshulman that seems like a solid proposal. Do you have an implementation at hand?

**Comment by ericshulman** [comment]
`$:/core/modules/editor/factory.js` , in `EditTextWidget.prototype.execute`, add one line:
```
this.editFocusSelect = this.getAttribute("focusSelect","yes");
```

`$:/core/modules/editor/engines/simple.js`, in `SimpleEngine.prototype.focus` AND
`$:/core/modules/editor/engines/framed.js`, in `FramedEngine.prototype.focus`, replace function code with:
```
if(this.domNode.focus) {
	this.domNode.focus();
}
if(this.domNode.select) {
	if (this.widget.editFocusSelect==="start") {
		this.domNode.selectionStart = this.domNode.selectionEnd = 0;
	} else if (this.widget.editFocusSelect==="end" || this.widget.editFocusSelect==="no") {
		this.domNode.selectionStart = this.domNode.selectionEnd = this.domNode.value.length;
	} else {
		this.domNode.select();
	}
}
```

**Comment by Jermolene** [comment]
Thanks @ericshulman I've made a PR at #7222

**Comment by Jermolene** [comment]
> Thanks @ericshulman I've made a PR at #7222

There's a preview build at https://tiddlywiki5-git-edit-text-focus-select-attribute-jermolene.vercel.app/

**Comment by pmario** [comment]
@Jermolene .. The vercel.app link creates a RSOD for me with FF and Win11

![image](https://user-images.githubusercontent.com/374655/221167390-0ec534d9-8638-4b43-bfab-c7bd7ab88faa.png)
