### ISSUE TITLE
[BUG] Weird tag chooser behavior with thin space

### ISSUE THREAD

**Issue by yaisog** [Jermolene/TiddlyWiki5#7226]
### Describe the bug

When I enter a tag name with a thin space (unicode U+2009) in the tag chooser of a tiddler, multiple tags are added instead, split at the thin space.
![image](https://user-images.githubusercontent.com/1133745/214081361-8fef48c4-adee-4cdd-8a45-61daf0e9962f.png)
Here I have entered "My Tag" in the chooser and clicked _Add Tag_ (on tiddlywiki.com).
Entering tags with regular spaces works as expected.
The only way to enter such a tag name is by manually adding a `tags` field with [[My Tags]] to the tiddler via the fields editor part in tiddler edit mode.

### Expected behavior

There should be no different behavior to using regular spaces or to single words containing unicode.

### To Reproduce

See description.

### TiddlyWiki Configuration

tiddlywiki.com

### Additional context

I _think_ that maybe the tag chooser doesn't set the [[ ]] that are necessary when the name contains spaces when populating the `tags` field. The rest of TW5 (or some other part of the tag chooser) recognizes the thin space as a list separator and thus adds two tags (which are separated by a regular space in the `tags` field).

**Comment by yaisog** [comment]
If I find the time, I'll take a look at the code myself, to see what's happening, but the tag chooser is a _beast_.
I'll likely end up (again) trying to find a way to get rid of the text substitutions in the color-related macros...

**Comment by Jermolene** [comment]
Thanks @yaisog fix coming up.

**Comment by yaisog** [comment]
Whoa. Mind blown. I swear I would have spent hours on the tag chooser thingy and might never have arrived at stringify...
🤯

**Comment by Jermolene** [comment]
> Whoa. Mind blown. I swear I would have spent hours on the tag chooser thingy and might never have arrived at stringify...
> 🤯

Ha! Thank you. Over the years there have been a lot of issues with the crude way that we attempt to stringify lists so I fairly quickly narrowed down to that area. The fact that the problem occurs with the thin space but not a regular space suggested that this might be a problem where we were checking for a space character instead of allowing for the full range of characters that we class as whitespace.

**Comment by yaisog** [comment]
@Jermolene: There's a similar thing with the `words` and `some` suffixes for the search operator. Docs say tokens are separated by whitespace, but the code only looks for spaces.
I believe the relevant code is in `$:/core/modules/wiki.js`:
https://github.com/Jermolene/TiddlyWiki5/blob/95dc56d8508109a76c232cfbcd858889d32916a9/core/modules/wiki.js#L1270

Are you gonna make me open a new issue? 😢

**Comment by Jermolene** [comment]
> Are you gonna make me open a new issue? 😢

That would be very helpful thank you @yaisog :smile:
