### ISSUE TITLE
[BUG] ControlPanel Parser modes some spacing is missing

### ISSUE THREAD

**Issue by pmario** [Jermolene/TiddlyWiki5#7227]
### Describe the bug

[$:/ControlPanel](https://tiddlywiki.com/#%24%3A%2FControlPanel) → Info → Advanced → [Parsing → wikilink](https://tiddlywiki.com/#%24%3A%2Fcore%2Fui%2FControlPanel%2FParsing) some spacing got missing. 

### Screenshots

![image](https://user-images.githubusercontent.com/374655/214119626-a7ebfead-6c4c-40ac-b686-72f50e0a52a9.png)

**Comment by Jermolene** [comment]
Thanks @pmario it looks like we added a `\whitespace trim` without including an explicit space where needed.

**Comment by pmario** [comment]
I'll create PR soon
