### ISSUE TITLE
[IDEA] The checkbox widget should get a second class for the "inner text"

### ISSUE THREAD

**Issue by pmario** [Jermolene/TiddlyWiki5#7229]
## Proposal

It is proposed to add a second class eg: `inner-class` or `text-class` attribute to the checkbox-widget. This class should be assigned to the "native" SPAN element that is created by the widget. 

## Reasoning

As shown in the HTML code. If we assign a class to the following wikitext, the class is assigned to the "outer" label element. That's OK. 

BUT since we have whitespace trim the inner text is covered in a SPAN by the widget without any spacing. 

```
\whitespace trim

<$checkbox tag="done" class="tc-tiny-gap-right">Is it done?</$checkbox>
```

```
<p><label class="tc-checkbox tc-tiny-gap-right"><input type="checkbox"><span>Is it done?</span></label></p>
```

----------

The fix is like: 

```
\whitespace trim

<$checkbox tag="done" class="tc-tiny-gap-right"><span class="tc-tiny-gap-right">Is it done?<span></$checkbox>
```

BUT it creates 2 SPANS for the TEXT element. 

```
<p><label class="tc-checkbox tc-tiny-gap-right"><input type="checkbox"><span><span class="tc-tiny-gap-right">Is it done?<span>&lt;/$checkbox&gt;</span></span></span></label></p>
```

Screenshot **as it is now**

![image](https://user-images.githubusercontent.com/374655/214135563-58351f40-e1bf-4bf2-84a2-c8d39aa8f017.png)

**Comment by pmario** [comment]
@Jermolene What do you think?

**Comment by Jermolene** [comment]
Hi @pmario that seems reasonable. Are there any other widgets that create nested elements that might benefit from the same improvement?

I think it would be more consistent with the button widget's "selectedClass" to use "innerClass".

**Comment by pmario** [comment]
I'll check other widgets too.

**Comment by kookma** [comment]
Hi Mario,

> ```
> \whitespace trim
> 
> <$checkbox tag="done" class="tc-tiny-gap-right">Is it done?</$checkbox>
> ```
> 
> 
>     
>   
> 
> ```

> <p><label class="tc-checkbox tc-tiny-gap-right"><input type="checkbox"><span>Is it done?</span></label></p>
> ```

Is it possible to generate a better html like below? 

```
<div class="chk-class">
    <label>Do you like peas?</label>
    <input type="checkbox" name="peas" ...>
</div>
```

So I can simply use

```
.chk-class label{}
.chk-class input{}
```

I think the standard or the convention for checkbox is like what is given above

**Comment by pmario** [comment]
If you use your construction at TW-com, it's not possible to click the label text to check the input. ... If that's needed we would need IDs, which are generally a problem with TW, since they have to be unique. 

If you test the following example from MDN at TW-com it works as expected. BUT as you found out that's not what TW creates. 

[MDN says this](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/Input/checkbox)

```
<div>
    <input type="checkbox" id="horns" name="horns">
    <label for="horns">Horns</label>
</div>
```

The second problem is, that we need to create $checkbox widgets in inline and block mode. ... DIV is block mode only 

Creating your suggested structure IMO would not be backwards compatible. So I'm pretty sure it would be a no-go. 

If we would create a TW-like structure as shown at MDN we would need 3 class settings. 

 - class ... goes to label for backwards compatibility
 - wrapperClasse ... which goes to the outer DIV or SPAN depending on block-mode
 - innerClass ... which goes to the inner SPAN for the label text

@Jermolene ... What do you think?

**Comment by pmario** [comment]
The radio-widget IMO has the same problems as discussed here.

**Comment by kookma** [comment]
Thank you for clarification @pmario. I thought a closer to html common practice is better!

> The second problem is, that we need to create $checkbox widgets in inline and block mode. ... DIV is block mode only

Can't this have a class to initially set it to `display: inline-block`?

**Comment by pmario** [comment]
>Can't this have a class to initially set it to display: inline-block?

Yes but the HTML output should be semantically right too. It usually causes less problems with styling.

**Comment by pmario** [comment]
@Jermolene .. As written above at [checkbox example at MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/Input/checkbox) and [other places](url) is created like  this. 

```
<div>
    <input type="checkbox" id="scales" name="scales" checked>
    <label for="scales">Scales</label>
</div>
```

[TW uses the "implicit" version](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/label), which avoids the need for the `for and id` attributes. Eg:

```
<label class="tc-checkbox">
  Do you like peas?
  <input type="checkbox" name="peas" />
</label>
```

-------

So the new proposal is to create 3 new widget attributes: 

- innerClass ... for the input-text class as proposed in the OP
- wrapperClass ... for an outer div
- wrapper
   - inline or block mode is defined by the wrapper tag. DIV or SPAN
   - if **no** wrapperTag is set, the existing "implicit structure" is created
   - if a wrapper is set the new "explicit structure" is created. 

Since the default is as it is now, there should be no backwards compatibility problems.

The "input id" and the "label for" attributes are calculated internally and set to random value. The qualify-macro cannot be used, since it would duplicate IDs. 

The new structure would look like this. 

```
<div class="tc-checkbox-wrapper">
    <input type="checkbox" id="random-value" >
    <label for="random-value" class="tc-checkbox">Scales</label>
</div>
```

@Jermolene ... What do you think?

**Comment by Jermolene** [comment]
Hi @pmario are you proposing that the checkbox widget be updated to use IDs to associate the input with the label? We've gone to a lot of trouble so far to avoid using IDs in the way suggested, so I think I'd want to understand more about why the current markup isn't sufficient.

**Comment by pmario** [comment]
>Hi @pmario are you proposing that the checkbox widget be updated to use IDs to associate the input with the label?

I cannot believe it myself, but -- yes -- somehow. 

>We've gone to a lot of trouble so far to avoid using IDs in the way suggested, so I think I'd want to understand more about why the current markup isn't sufficient.

I did a bit more experimenting and found out, that the proposal won't improve the situation either. Adding an ID and a wrapper is still not flexible enough to solve the [accessibility problems](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/label#accessibility_concerns) I do have in mind.

I think we need a "template" parameter instead. With a template the user would have full control about the HTML code created. ... 

Thinking. ... I'll close this issue in favour of a new one.
