### ISSUE TITLE
[BUG] tm-import-tiddlers handler can't receive parameters from action-sendmessage widget

### ISSUE THREAD

**Issue by btheado** [Jermolene/TiddlyWiki5#7234]
### Describe the bug

#4741 extended the tm-import-tiddlers handler to allow customizations via `importTitle` and `autoOpenOnImport`. However, the handler looks for these values at the top-level of the `event` object rather than the standard way of using paramObject subkeys.

The `$action-sendmessage` widget can only send values via the paramObject field. That means the customized `importTitle` and `autoOpenOnImport` values sent by `action-sendmessage` will be ignored by the tm-import-tiddlers handler.

The `$dropzone` widget code is calling dispatchEvent directly and it is passing the two fields as `event` top-level keys. Therefore setting these values via `$dropzone` works fine (I didn't test, just assuming based on reading the code).

I think the tm-import-tiddlers handler in navigator.js can be changed to look for the fields in paramObject instead of at the top level. A matching change in the `$dropzone` widget would be required. It would need to use paramObject in its call to dispatchEvent

### Expected behavior

It should be possible to customize `importTitle` and `autoOpenOnImport` using the `$action-sendmessage` widget.

### To Reproduce

1. Go to https://tiddlywiki.com
2. Create a new tiddler with the following content
```
<$let  json=<<jsontiddlers filter:"[tag[Core Macros]first[2]]">>>

<pre><$text text=<<json>>/></pre>

<$button
  actions="""
    <$action-sendmessage
      $message="tm-import-tiddlers"
      $param=<<json>>
      importTitle="import-test"
      autoOpenOnImport="no"
    />
  """
>
Import tiddlers to the "import-test" tiddler
</$button>

`$:/Import`: <pre><$text text=<<jsontiddlers filter:"$:/Import">>/></pre>

`import-test`: <pre><$text text=<<jsontiddlers filter:"import-test">>/></pre>
</$let>
```
4. Click on the "Import tiddlers..." button
5. Notice the tiddlers are imported into `$:/Import` instead of `import-test` and the `$:/Import` tiddler is auto-opened contrary to the custom attributes.

### TiddlyWiki Configuration

tiddlywiki.com version 5.2.5

**Comment by pmario** [comment]
Did you try to use `myJson=<<json>>` instead of `$param=` ?

**Comment by btheado** [comment]
> Did you try to use `myJson=<<json>>` instead of `$param=` ?

I don't understand the reasoning behind this suggestion. What does the `myJson` attribute do? I don't see it documented.

I did try it to see if it would help me understand, but it only broke things worse. With it the json doesn't get imported at all.

When I find some time I will probably create a PR for the fix. If I'm right about the issue, it should be fairly straightforward.
