### ISSUE TITLE
[BUG?] Creating tiddler with (_canonical_uri refering to external file) creates "empty hull"+.meta instead of .tid in fs

### ISSUE THREAD

**Issue by rimi** [Jermolene/TiddlyWiki5#7238]
### Describe the bug

Hi,

when creating a tiddler using "_canonical_uri" (refer to /files/...) and e.g. type: application/pdf like this:

![image](https://user-images.githubusercontent.com/562738/214780959-0fbe4ddc-26d3-436e-aec0-2d89256e2f31.png)

creates a 0-byte .pdf-file accompanied by a .meta-file. I consider this as bug (not 100% sure, why it is as it is now) because deleting the 0-byte pdf and renaming .meta to .tid just works fine and reduces the clutter in my git-repo.

### Expected behavior

Create .tid-file if a value for _canonical_uri is provided and do not create to 0-byte pdf.

### To Reproduce

create tiddler like shown in the screenshot above

### TiddlyWiki Configuration

- Version 5.2.5
- Saving mechanism Node.js
- Plugins installed [e.g. Freelinks, TiddlyMap]

### Desktop (please complete the following information):

- OS: Win10
- Browser firefox & chrome
- Version latest

**Comment by Jermolene** [comment]
Thank you @rimi I'll post a fix momentarily.

**Comment by rimi** [comment]
Thanks for the fix! Any date already, when 5.2.6 will be released?

**Comment by Jermolene** [comment]
Hi @rimi 

> Thanks for the fix! Any date already, when 5.2.6 will be released?

We've recently been releasing new versions every 3 or 4 months, and so I'd hope to release v5.2.6 in March.
