### ISSUE TITLE
[BUG] application/json tiddler in edit mode -- copy paste to text area also creates an $:/Import tiddler

### ISSUE THREAD

**Issue by pmario** [Jermolene/TiddlyWiki5#7244]
### Describe the bug

As written in the title, "application/json tiddler in edit mode -- copy paste to text area also creates an $:/Import tiddler"

It seems the problem only comes up with CM installed. 

### Expected behavior

text should only be copied into the text area

### To Reproduce

- go to: https://paste.tiddlyhost.com/
- open the Json Test tiddler
- copy some text from the text area to the clipboard
- Paste the text. -> Problem

-----

Testing the same thing with tiddlywiki.com there is **no problem**

### Screenshots

![image](https://user-images.githubusercontent.com/374655/215328603-3443feeb-e6e3-406f-b0d5-5d450b1ea827.png)

### TiddlyWiki Configuration

TW v5.2.5 

### Additional context

> from [TTalk thread](https://talk.tiddlywiki.org/t/disable-import-on-paste/5943)
>
>... While I don’t fully grok the issue the PR fixes, in my case it doesn’t seem to be the type of the pasted element, but the fact that the dropzone that receives the event doesn’t filter by that type. I’m basically editing text and yet the dropzone behaves as if any sort of paste should be handled as an import. This manifests itself for me since the changes I made to CM mean that the event target is no longer a textarea.
>
>In an empty TW without these settings, if the content type of the tiddler that is being edited is empty, a dropzone with the contentTypeFilter is called, but because it doesn’t do anything, since the target is a textarea, the event gets propagated to another dropzone which again does nothing for the same condition. If the content type is for javascript, only the second dropzone is called and it does nothing.
>
>In my TW, when the tiddler’s content type is empty, the first dropzone gets called, it enters the “!textarea” condition but in there it calls readFileCallback that does nothing due to the content filter. But since it is in the condition body, it stops propagation so the second dropzone is not called. When the content type is for javascript, only the second dropzone is called, it goes into the condition, but since it doesn’t have a filtertype, it handles the import.
>
>I don’t know how to do it, but I think the first dropzone should remain when the tiddler that is edited has a content type of json/javascript (or other text formats). While were at the subject, it seems to me that import should trigger when the content type filter doesn’t match the pasted type (it should be a whitelist), and not the way it is now (when it acts as a blacklist).

**Comment by pmario** [comment]
Related settings due to info at Talk: 

TW system tiddlers: https://paste.tiddlyhost.com/#%24%3A%2Fconfig%2Fcodemirror%2Fspellcheck:%24%3A%2Fconfig%2Fcodemirror%2Fspellcheck%20%24%3A%2Fconfig%2Fcodemirror%2FinputStyle%20%5B%5BJson%20Test%5D%5D

TW Talk thread: https://talk.tiddlywiki.org/t/disable-import-on-paste/5943

**Comment by pmario** [comment]
- To replicate the problem at CM Demo page the config https://paste.tiddlyhost.com/#%24%3A%2Fconfig%2Fcodemirror%2Fspellcheck has to be imported. .. 
- The spell-check setting does not have any influence

**Comment by pmario** [comment]
I did add the more detailed description from Talk to the "Additional Context" in the OP

**Comment by Jermolene** [comment]
Thanks @pmario that's a very analysis.

**Comment by pmario** [comment]
I thin I did already find the problem, but it's a bit tricky. :/ ... The `event.target.isContentEditable` attribute from the event is `inherit` .. more testing needed.

**Comment by pmario** [comment]
@Jermolene ... There is something very strange going on. 

- Please set a breakpoint at: https://github.com/Jermolene/TiddlyWiki5/blob/d70b6a7d6c0afb2ad7281f87145b24febba9cb6b/core/modules/widgets/dropzone.js#L262
- check the `event.traget` variable in the "Dev tools scopes" 
  - check for `.parentNode` ... **recursively**. 
  - It will stop at the element with the `class="Codemirror-line"` .. <- This element doesn't have a parentNode ... 

So it's impossible to get this info since the `div class="Codemirror-code"` is the element that has the `contentEditable="true"` setting.

**Comment by pmario** [comment]
I did add this code to the pasteHandling. The funny thing is that `checkIsEditable(target)` stops after 2 iterations. :/

```
	var checkIsEditable = function(target) {
		if (!!target) return false;
		switch (target.contentEditable) {
			case 'inherit':
				return checkIsEditable(target.parentNode);
			break;
			case 'true':
				return true;
			break;
			case 'false':
			default: // intentional fallthrough
				return false;
		}
	};

	// Let the browser handle it if we're in a textarea or input box

var ce = event.target.isContentEditable,
	parentTest = checkIsEditable(event.target);

	if(["TEXTAREA","INPUT"].indexOf(event.target.tagName) == -1 && !checkIsEditable(event.target)) {
```

**Comment by Jermolene** [comment]
Hi @pmario worst case we could perhaps fix this by extending that test in line 262 to explicitly check for CodeMirror...

**Comment by ittayd** [comment]
About checkIsEditable stopping after two iterations: that is because the event target is detached.

**Comment by pmario** [comment]
>...worst case we could perhaps fix this by extending that test in line 262 to explicitly check for CodeMirror...

hmmm, That would be very hacky. The SPAN that triggers the paste event doesn't have a class. The first parent, which is accessible has `class="CodeMirror-line"` ... We could say that only the CM-editor has those elements. .. But that's not necessarily always true. 

CM has plugins like runmode.js and colorize.js which provide a view-only highlighter mode. .. They are not used atm, but that does not mean they will never used that way. .. I don't know if they use the same CSS, but if they do, detecting edit-mode using the "CodeMirror-line" class will break. 

-------

@Jermolene 

I would add a hook eg: `event = $tw.hooks.invokeHook("th-codemirror-pre-paste",event);` prior to line 262 and add an extra condition to the if statement like so:

```
	event = $tw.hooks.invokeHook("th-codemirror-pre-paste",event);

	if((["TEXTAREA","INPUT"].indexOf(event.target.tagName) == -1) && (!event.target.isContentEditable)) && (!(event.cmOptions && event.cmOptions.isEditable)) {
```

This would give any cm-plugin the possibility to modify the event-object and the current code should be backwards compatible. If there is no `cmOptions` object in the event it would be `falsy` as default

The codemirror library would need a new plugin that can handle the `$:/config/codemirror/inputStyle` config tiddler and implement the "th-codemirror-pre-paste" hook

I think that's a bit more complex as I would like it to be :/

What do you think?

**Comment by ittayd** [comment]
Can't there be a dropzone to any content tyoe that is edited as text with the same filter as the dropzone for tiddlywiky tiddlers?

**Comment by ittayd** [comment]
As I tried to explain in the original post, the paste problem doesn't happen for regular tiddlers. The editor has two dropzones in a hierarchy (I don't know where they are defined, just seeing this through the debugger). When the content type of a tiddler is empty, the first one gets triggered, goes into the condition with the text area but then it has a contentTypeFilter which only accepts images. Since what I'm pasting is not an image, it ignores the event and the other dropzone is not called. When the content type is not empty, there is only the second drop zone, which doesn't have a content filter, so it accepts the paste and triggers the import.

So one approach to solve this bug is to setup a dropzone with the content filter for all text based content types. It may even be that all edited content should have such a dropzone and let the editor handle any paste (either trivially, it it is text or otherwise)

**Comment by ittayd** [comment]
A grep shows two places where a dropzone is defined:
```
core/ui/PageTemplate.tid
22:<$dropzone enable=<<tv-enable-drag-and-drop>>>

core/ui/EditTemplate/body/default.tid
16:<$dropzone importTitle=<<importTitle>> autoOpenOnImport="no" contentTypesFilter={{$:/config/Editor/ImportContentTypesFilter}} class="tc-dropzone-editor" enable={{{ [{$:/config/DragAndDrop/Enable}match[no]] :else[subfilter{$:/config/Editor/EnableImportFilter}then[yes]else[no]] }}} filesOnly="yes" actions=<<importFileActions>> >
```
So it seems that for some reason, when changing the content type of a tiddler that is being edited, core/ui/EditTemplate/body/default.tid is not used (or maybe more precisely, the paste event goes to the dropzone that that is defined in PageTemplate directly)

**Comment by ittayd** [comment]
As mentioned, when the content type is empty, it doesn't. But it is due to the fact that the first dropzone enters the "textarea condition" but then ignores the paste due to contentTypeFilter. I suggested this should be the behaviour for all editors. 

FWIW, the workround I did was use this in the 'textarea condition' line: `&& (event.target.getRootNode().classList === undefined || !event.target.getRootNode().classList.contains('CodeMirror-line'))`

**Comment by pmario** [comment]
>FWIW, the workround I did was use this in the 'textarea condition' line: && (event.target.getRootNode().classList === undefined || !event.target.getRootNode().classList.contains('CodeMirror-line'))

Does this code still work if you remove the `$:/config/codemirror/inputStyle` tiddler? The DOM looks completely different if that tiddler is missing

**Comment by ittayd** [comment]
It's a workaround I did, so I'm not sure how well it will work across all variations. It works for me. 
Paste works if I remove $:/config/codemirror/inputStyle.

**Comment by Jermolene** [comment]
Thanks for your patience @ittayd.

@saqimtiaz would you be able to have a look at this? (Saq recently made some changes in this area to accommodate pasting images directly into the text area).

**Comment by saqimtiaz** [comment]
I'll make some time to investigate later this week.

**Comment by Jermolene** [comment]
Thanks @saqimtiaz
