### ISSUE TITLE
[BUG] Dynannotate searchCaseSensitive default is not as documented

### ISSUE THREAD

**Issue by yaisog** [Jermolene/TiddlyWiki5#7245]
### Describe the bug

The plugin readme says that the default for searchCaseSensitive is `no`, but in usage it is `yes`. 

### Expected behavior

Docs and code should be synchronized.
Personally, I'd prefer the doc default (search is case-insensitive).

### To Reproduce

1. Go to [https://tiddlywiki.com/prerelease/#%24%3A%2Fplugins%2Ftiddlywiki%2Fdynannotate](https://tiddlywiki.com/prerelease/#%24%3A%2Fplugins%2Ftiddlywiki%2Fdynannotate)
2. In the _Simple_ plugin examples, see the _Plain text searching_ example.
3. The inital "The" is not highlighted as its T is uppercase.

### TiddlyWiki Configuration

TW 5.2.6-prerelease

**Comment by Jermolene** [comment]
Thanks @yaisog that's unfortunate. We do of course have to fix the docs, not the implementation.

**Comment by yaisog** [comment]
> We do of course have to fix the docs, not the implementation.

Ah, dang. But I see why. ;-)
