### ISSUE TITLE
[IDEA] Make Dynannotate searchMode parameter consistent with search[] filter suffix

### ISSUE THREAD

**Issue by yaisog** [Jermolene/TiddlyWiki5#7256]
### Dynannotate
The search modes supported by the `searchMode` attribute are:
- **normal** - a literal string of plain text to match
- **regexp** - a JavaScript-style regular expression (without the quoting backslashes and flags)
- **whitespace** - a literal string to match while normalising runs of whitespace. This allows `a. b` to match `a.  b`

### `search` filter
Search mode - the first to be set of the following flags determines the type of search that is performed:
- **literal**: considers the search string to be a literal string, and requires an exact match
- **whitespace**: considers the search string to be a literal string, but will consider all runs of whitespace to be equivalent to a single space. Thus `A B` matches `A   B`
- **regexp**: treats the search string as a regular expression. Note that the regexp option obviates the need for the older [regexp](https://tiddlywiki.com/prerelease/#regexp%20Operator) operator.
- **words**: (the default) treats the search string as a list of tokens separated by whitespace, and matches if all of the tokens appear in the string (regardless of ordering and whether there is other text in between)
- **some**: treats the search string as a list of tokens separated by whitespace, and matches if at least one of the tokens appear in the string

Dynannotate's `normal` should be renamed to `literal`. I don't think it makes sense for Dynannotate to differentiate between `words` and `some`. Since `words` has been there longer, I would use that. That should also be the default mode in Dynannotate. Its function would be to highlight all words in the search string separately, not just when there is a literal match. That functionality is currently missing.

**Comment by pmario** [comment]
>Dynannotate's `normal` should be renamed to `literal`.

That's probably not possible because of backwards compatibility concerns. 

>I don't think it makes sense for Dynannotate to differentiate between `words` and `some`. Since `words` has been there longer, I would use that. That should also be the default mode in Dynannotate. Its function would be to highlight all words in the search string separately, not just when there is a literal match. That functionality is currently missing.

I think you are confusing this setting: `words` is a literal match. So if you search for "one two" it has to be an exact match .. 

>Its function would be to highlight all words in the search string separately, not just when there is a literal match. That functionality is currently missing.

What you describe here is the `some` setting

**Comment by Jermolene** [comment]
Hi @yaisog it would certainly be generally helpful to better align dynannotate with the search operator.

I think we could support "literal" as an alias for "normal". 

I am not sure that we should change the dynannotate default to "words"; that might make sense if dynannotate were being used to highlight search results but that's not the only use of dynannotate. As usual, there is also backwards compatibility to consider.

**Comment by yaisog** [comment]
I was just concerned with consistency. Backwards compatibility and its associated calculus trumps that. I am new to Dynannotate, so I'm not quite aware of its baggage...

@pmario: The definition for _words_ for the search operator is "treats the search string as a list of tokens separated by whitespace, and matches if all of the tokens appear in the string (_regardless of ordering and whether there is other text in between_)". It is not literal (also, _literal_ is the literal match).

**Comment by yaisog** [comment]
Also, I would really like _words_ or _some_ (whatever you would like to call it) as an option for Dynannotate. Maybe not the default, but available at all.

**Comment by Jermolene** [comment]
Indeed @yaisog I think extending dynannotate to match the search operator is a good idea. Might it be something you'd like to work on?

**Comment by pmario** [comment]
> yaisog wrote
>
>... (regardless of ordering and whether there is other text in between)". It is not literal (also, literal is the literal match).

You are right, but anyway 

- for "words" every token has to match to return a result
- for "some" only one of the token has to match to return a result. .. If the first token matches, it does not look for any of the others, since it already found a match. 

So the code for dynannotate will be different to the search code and imo so is the behaviour. So it would be OK if the configurations terms are different too. ... BUT ... For similar behaviour they should be the same. So it's less to learn.

**Comment by yaisog** [comment]
@Jermolene: I can try...

@pmario: Good points. We're not matching, we're finding.
We migh use `words` as the parameter value since we'll be highlighting _every_ token (if found on the page). One could of course also argue that since we'd still highlight if only one of multiple tokens is found, `some` may be better. One could also argue for something completely different like 'all', like you mentioned.

For familiarity and semantics I'd go with `words`, though. Who decides? Will there be a vote? 😉

**Comment by Jermolene** [comment]
Hi @yaisog there's some value in dynannotate accepting the same tokens as the search operator so I'd suggest adding a new option to dynannotate to highlight as many of the whitespace delimited words as it can, and making it available under the both "words" and "some".

**Comment by pmario** [comment]
IMO it's not really related to the search flags, because the flags have totally different consequences 

------

Reasoning .... Usually we do have a combination with "search" and "annotate". 

eg: we have 2 tiddlers "this" and "text" 

- search mode: `words" ... if you search for **"this text"** you'll get _no_ result so -> no annotation at all
  - `[all[tiddlers]!is[system]search::words[this text]]`
- search mode: `some` ... will give you both tiddlers. ... 
  - `[all[tiddlers]!is[system]search::some[this text]]`

So IMO the flag for annotation should be `every` which uses a whitespace separated list of words that are annotated in the text that has been found using search (which can have completely different params)

**Comment by yaisog** [comment]
I went with `words` and `some` (for now), because their description for `search` could be transferred almost 1:1 (leaving out the bit about the match); `words` was even closer.
A new flag `any` may be semantically more correct, but I found adding another name for a very similar concept too confusing. The purpose of this ticket was to align _Dynannotate_ and `search` better, not to create more definitions...
