### ISSUE TITLE
[BUG] "words" and "some" suffixes for the search operator do not work as documented

### ISSUE THREAD

**Issue by yaisog** [Jermolene/TiddlyWiki5#7263]
### Describe the bug

Docs say tokens in the search string are separated by whitespace, but the code only looks for spaces.
I believe the relevant code is in `$:/core/modules/wiki.js`:
https://github.com/Jermolene/TiddlyWiki5/blob/95dc56d8508109a76c232cfbcd858889d32916a9/core/modules/wiki.js#L1259
https://github.com/Jermolene/TiddlyWiki5/blob/95dc56d8508109a76c232cfbcd858889d32916a9/core/modules/wiki.js#L1270

### Expected behavior

Any whitespace character (except maybe with the exception of the non-breaking space) should work as a token separator.

### TiddlyWiki Configuration

5.2.6-prerelease

**Comment by yaisog** [comment]
See also the discussion in #7226

**Comment by pmario** [comment]
What is a "thin-space" used for. I know it's a unicode, but imo we need to stop somewhere. Unicode probably has 20+ more whitespace chars. If we test for all of them we will slow down the parsing process considerably. I didn't understand why the `thin-space` thing was implemented without much discussion.

**Comment by yaisog** [comment]
The `split` function takes a regexp as argument. The regexp for _all_ whitespace characters except the non-breaking space is `[^\S\xA0]`. There is no affordance for individual whitespace characters.

The PR changes about 10 bytes to include all the whitespace characters.

I don't believe that parsing of a single search string is slowed measurably by this change. 😉

**Comment by yaisog** [comment]
On the topic of "thin-space"... Wikipedia says:
> It is also used in the [International System of Units](https://en.wikipedia.org/wiki/International_System_of_Units) and in many countries as a [thousands separator](https://en.wikipedia.org/wiki/Thousands_separator) when writing numbers in groups of three digits, in order to facilitate reading.

Personally, I use a non-breaking thin space as separator between numbers and their units, e.g. 1 kg, 20 m, 60 s. Not only look these better when they're closer together in longer texts, but one of the worst typographic blunders one can make is a line break between a number and its unit.

**Comment by CodaCodr** [comment]
I think @yaisog's mission here is commendable.

I think @pmario's concerns are justified.

Is there a possibility it can be tested by conversant testers with many and/or large wikis?

**Comment by Jermolene** [comment]
Hi @yaisog @pmario this is a question of consistency. Most places in the core use `[^\S\xA0]` to match whitespace, notably  `$tw.utils.parseStringArray()` in boot.js, and we should indeed try to make other usages consistent. I'd be inclined to categorise the current situation as a bug, and thus fixing it would be acceptable from a backwards compatibility perspective.
