### ISSUE TITLE
[IDEA] Optional Wikitext-like links in Markdown

### ISSUE THREAD

**Issue by Gamer-Kold** [Jermolene/TiddlyWiki5#7275]
**Is your feature request related to a problem? Please describe.**
For the sake of software agnosticism, I wanted to use Markdown in my Tiddywiki. So that, if ever a time came to switch software, the process would be relatively painless. However the link syntax has quickly grown tiresome.

`[Tiddler Name][#Tiddler%20Name]` not only asks you to write the same information _twice_  but to also escape any spaces with URL encoding. I realize this is a limitation of markdown parsers, but other software (such as obsidian) support wikitext-like links anyway.

**Describe the solution you'd like**
I think the easiest solution, would be to have an option of `Enable wikitext linking` in the markdown plugin, like there is for CamelCase. If the option is enabled, transform all `[[Tidddler Title]]` into `[Tiddler Title](#Tiddler%20Title)` before passing it to Remarkable. To be clear, I am not asking for the actual text of the tiddler to be modified, just the markup that is passed to the parser.

**Additional context**
I am willing to implement this myself, but I looked at the Markdown plugin and couldn't make heads or tails  of the order of execution. I figured it would be faster to have someone with more experience with the codebase implement it themself or at the very least point me in the right direction.

**Comment by saqimtiaz** [comment]
> I think the easiest solution, would be to have an option of `Enable wikitext linking` in the markdown plugin, like there is for CamelCase. If the option is enabled, transform all `[[Tidddler Title]]` into `[Tiddler Title](#Tiddler%20Title)` before passing it to Remarkable. To be clear, I am not asking for the actual text of the tiddler to be modified, just the markup that is passed to the parser.

The feature exists but is missing a user friendly configuration dialog, see: 
https://github.com/Jermolene/TiddlyWiki5/issues/6045#issuecomment-922078343

**Comment by Gamer-Kold** [comment]
Ah that seems to work, thank you!

**Comment by Jermolene** [comment]
Thanks @saqimtiaz @Gamer-Kold I do wonder if we should add pretty link formatting by default. The current default is to recognise camelcase links in markdown but not explicit double square bracket links.

**Comment by Jermolene** [comment]
> Thanks @saqimtiaz @Gamer-Kold I do wonder if we should add pretty link formatting by default. The current default is to recognise camelcase links in markdown but not explicit double square bracket links.

@cdruan can you see any problems with enabling "prettylink" by default?

**Comment by Gamer-Kold** [comment]
>  I do wonder if we should add pretty link formatting by default. The current default is to recognise camelcase links in markdown but not explicit double square bracket links.
> 

My vote would be yes, it's a much nicer way of typing out links (especially on mobile), and it's probably the function that users expect from other Markdown based wiki software. It's certainly what I expected. 

But I think more important than turning it on by default is having a more user friendly way of turning it on. I think that by itself should do a lot.

**Comment by cdruan** [comment]
@Jermolene 

> @cdruan can you see any problems with enabling "prettylink" by default?

It'll be fine. There are two more tiddlywiki link related rules: `image` and `prettyextlink`. Should all three have the same default state&mdash;i.e. either all on or all off by default? That way, users aren't left wondering why one TW syntax works in markdown but another similar syntax rule doesn't work.

**Comment by Jermolene** [comment]
Thanks @cdruan
