### ISSUE TITLE
[BUG] Small visual glitch after changing dark/light palette settings

### ISSUE THREAD

**Issue by Flammonauta** [Jermolene/TiddlyWiki5#7276]
### Describe the bug

Really trivial bug, but maybe of interest

Dark or white bar appearing at the bottom of the text editor of a tiddler if palette is switched between a dark one and a light one.
it doesn't always happen, only sometimes (if the editor is already opened) when you switch from a light palette to a dark one or vice versa. (The unwanted bar will be dark if the palette is light and vice versa)
Not a big bug, but I'll report it if it might interest you.

(I'm using firefox on windows 10)

### Expected behavior

That bar of color should not appear

### To Reproduce

1. Go to [tiddlywiki](https://tiddlywiki.com/) or open an empty.html
2.  Open the editor of a tiddler
3. Switch palette between a dark one and a light one or vice versa
4. Scroll down to the bottom of the editor
5. See error

### Screenshots

![Immagine 2023-02-21 100305](https://user-images.githubusercontent.com/123161650/220301222-61235f42-964d-4e84-9677-6f2c4274ff0e.png)

![Immagine 2023-02-21 101758](https://user-images.githubusercontent.com/123161650/220302715-cdd907d7-c430-4627-ad34-c853de651f45.png)

### TiddlyWiki Configuration

- Version [e.g. v5.2.5]

### Desktop 

- OS: Windows 10
- Browser Firefox 109.0.1 (64 bit)

**Comment by pmario** [comment]
Hi, Could you add an issue title please. eg: Visual glitch after changing dark/light palette settings ... or something similar

**Comment by Flammonauta** [comment]
> Hi, Could you add an issue title please. eg: Visual glitch after changing dark/light palette settings ... or something similar

Yes, sorry, I didn't realize I left it blank. Thank you

**Comment by Jermolene** [comment]
Thanks @Flammonauta, fix coming up.
