### ISSUE TITLE
[BUG] Literal macro parameters do not always work in filter[] operator

### ISSUE THREAD

**Issue by yaisog** [Jermolene/TiddlyWiki5#7288]
### Describe the bug

When the parameter is a variable which itself contains a macro call with a literal parameter, like so:
```
\define year() [<now YYYY>debug-log[]]

{{{ [all[current]filter<year>] }}}
```
the log output will show

![image](https://user-images.githubusercontent.com/1133745/221349680-2d360cd0-3a51-44c4-9fcd-78845bf4aa66.png)

which is clearly not the "YYYY" format, but I'm guessing the default. With `subfilter[]` instead of `filter[]` it works fine.

The code as shown above makes no sense on its own and is only used as a minimal demonstration. The actual use is a compare operation with `now YYYY` as parameter, which fails to correctly match the current year.

You will need the `debug-log[]` plugin from [here](https://yaisog.tiddlyhost.com/), unless you're debugging directly into JavaScript.

### Expected behavior

The literal parameter to the macro should be used in its evaluation.

### To Reproduce

Install `debug-log[]` in a TW, enter the above WikiText in a new tiddler, observe the console output.

### TiddlyWiki Configuration

TW 5.2.5

**Comment by Jermolene** [comment]
Hi @yaisog I'm having trouble replicating this without the `debug-log` operator.

I placed the following text in a tiddler:

```
\define year() [<now YYYY>]

{{{ [all[current]filter<year>] }}}
```

I then placed a breakpoint in `$:/core/modules/macros/now.js` so that I could inspect the parameter. As expected, the "format" parameter has the value "YYYY" when invoked.

**Comment by yaisog** [comment]
Hmm, yeah, that example was no good for use without `debug-log`. Since `now` returns _something_, the `filter` passes its input along.

Try this on tiddlywiki.com:
```
\define is-same-year() [format:date[YYYY]compare:number:eq<now YYYY>]
	  
{{{ [[20230211000000000]filter<is-same-year>] }}}
```
With this, `debug-log` would show you that the output of `format` is correct (2023). But even without `debug-log` you can see that the `compare` fails and thus `filter[]` yields no output, though it should. And does when used with `subfilter`...

**Comment by Jermolene** [comment]
Hi @yaisog OK I think this is fixed on master - your example on tiddlywiki.com yields nothing, but on tiddlywiki.com/prerelease I'm seeing the expected result "2023021100000000".

I suspect that it is covered by https://github.com/Jermolene/TiddlyWiki5/commit/6f9cf20e7737fc992ea9d11947ccdd8aadf8b6ce

**Comment by yaisog** [comment]
OK, great. Sorry that I didn't find that myself...

**Comment by Jermolene** [comment]
> OK, great. Sorry that I didn't find that myself... Grabbing filter.js from prerelease made it work correctly.

No worries, but I would generally recommend testing with "master" (ie the prerelease) before submitting a bug report.
