### ISSUE TITLE
[BUG] Dynannotate searchCaseSensitive again

### ISSUE THREAD

**Issue by yaisog** [Jermolene/TiddlyWiki5#7289]
### Describe the bug

This code
```
<$dynannotate search="Mind" searchCaseSensitive="">
{{$:/plugins/tiddlywiki/dynannotate/example-text-1}}
</$dynannotate>
```
will make the search case insensitive in the prerelease.

### Expected behavior

I think every string that is not "no" should make the search remain case sensitive (the default).

### TiddlyWiki Configuration

TW 5.2.6-prerelease

### Additional context

May be related to #7245.

**Comment by Jermolene** [comment]
Hi @yaisog that would be a change from the current behaviour, which is to make the search case sensitive only if the "searchCaseSensitive" attribute is equal to the string "yes".  In other words, every string that is not "yes" makes the search case insensitive.

**Comment by yaisog** [comment]
Hi @Jermolene , hmm, OK. Backwards compatibility again.
I was thinking that everything that is undefined should fall back to the default value. Sort of like a `case` construct.
But if the current behavior is intentional, I'll close this issue.
