### ISSUE TITLE
Hovering over last time edited date should show the full date.

### ISSUE THREAD

**Issue by Dialga** [Jermolene/TiddlyWiki5#729]
Set the title attribute to the full date, so when you hover over the wiki's date it should show the full date under the cursor, such as "Wednesday, August 13, 2014 at 12:12pm".

Concept inspired by Facebook.

**Comment by Dialga** [comment]
Seems like this is already implemented.

**Comment by Jermolene** [comment]
Thanks @Dialga, it's good to see your continued interest in the project.
