### ISSUE TITLE
[IDEA] Allow for locale selection for the non-numerical DateFormat outputs

### ISSUE THREAD

**Issue by yaisog** [Jermolene/TiddlyWiki5#7298]
I'd find it helpful if there was a way to output e.g. the `MMM` DateFormat in a locale of the user's choice – in this example, instead of "February" I would like to see "Februar" in the `de-de` locale.

Hard part is to find a way to parameterize this locale. Since the suffix for `format` describes the input and not the output, that's not usable. An optional second parameter, maybe, for the `date` and `timestamp` suffixes?

Maybe my setup of a German wiki in an English browser is unusually exotic?

Right now the alternative is to set up a lookup data tiddler and chase everything though that. Not terribly horrific, but not beautiful, either...

**Comment by yaisog** [comment]
The lookup would look like this:
```
[format:date[MMM]subfilter<translate>]
```
with
```
\define translate() [all[]] :map[[TranslatedDateStrings]getindex<currentTiddler>else<currentTiddler>]
```
and a lookup data tiddler `TranslatedDateStrings` that has pairs like
```
February:Februar
```
That subfilter looks pretty convoluted, especially since single word lookup should be the "killer application" of a tiddler with application/x-tiddler-_dictionary_ type. I guess I probably missed the simple operator that would do just that? I don't tiddle around much with data tiddlers ever since they were ostracized by Jeremy...

**Comment by Jermolene** [comment]
Perhaps the easiest solution would be to extend the `format` operator to optionally support two operands, with the first operand being used instead of the suffix:

```
[[HelloThere]get[created]format[date],[DDth MMM YYYY]]
```

**Comment by yaisog** [comment]
But then where would you put the locale parameter?

Also, I'm guessing the old syntax has to supported, too? Backwards compatibility and all...

Also also, no reaction at all to my data tiddler gibe? 😞

**Comment by pmario** [comment]
But IMO if you use the German language you'll have the right conversion. ... I don't see the point here. 

![image](https://user-images.githubusercontent.com/374655/221643029-1a98b2b1-d5de-4791-9731-8817c48c7ff2.png)

**Comment by yaisog** [comment]
I use the original English edition of TW, and I want to keep doing it this way. It is the same with my Windows and applications installations. For reasons I can't really put my finger on I don't like translations.

Since the contents of my wikis is mostly German now, the verbose dates should be, too.

If there was a wiki-wide setting for the date locale, that would also work, I think (not too much else would change, I'd surmise).

**Comment by pmario** [comment]
>If there was a wiki-wide setting for the date locale, that would also work, I think (not too much else would change, I'd surmise).

For me it would be data and numbers, where 1,600 makes a huge difference to 1.600 depending on how you look at it :)

**Comment by Jermolene** [comment]
Hi @yaisog apologies I'd misread the OP. I think you're asking whether we can provide a means to format date strings with a different locale than the current one.

The thing that complicates this is an oddity of the implementation of language plugins: there is an elaborate mechanism whereby switching languages actually entirely switches in and out the appropriate language plugins, so only the shadow tiddlers of the current language plugin are loaded, with any other loaded language plugins being inert.

However, if you know the name of the language plugin then you should be able to use the `subtiddler` attribute of the transclude widget to access the individual translatable strings.

**Comment by yaisog** [comment]
I had wrong assumptions about how the generation of the names was implemented. I realize that the OP would require an unjustifiable amount of work and will close the issue.

@Jermolene: Thanks for the suggestion, but I think I'll stick to the dictionary tiddler approach, since it is only a handful of words that I'm concerned about. Loading a full language plugin would increase the wiki size too much.
