### ISSUE TITLE
[IDEA] Add fallback to StoryTiddlerTemplate

### ISSUE THREAD

**Issue by yaisog** [Jermolene/TiddlyWiki5#7311]
Both the `$:/config/StoryTiddlerTemplateFilters/default` cascade component as well as the current fallback in `$:/core/ui/StoryTiddlerTemplate` transclude the content of `$:/config/ui/ViewTemplate`. If the title set there doesn't exist, the wiki is bricked. Changing the PageTemplate will not bring it back.

I suggest adding this filter run at the end of `$:/core/ui/StoryTiddlerTemplate`:
```
:and[has[title]else[$:/core/ui/ViewTemplate]]
```
i.e. if the referenced tiddler does not exist as shadow or tiddller, fall back to the original core ViewTemplate.

**Comment by yaisog** [comment]
The same goes for the EditTemplate in `$:/config/StoryTiddlerTemplateFilters/draft`, which should get the fallback `$:/core/ui/EditTemplate`, in case someone changes the config tiddler to something non-existent.

**Comment by Jermolene** [comment]
Excellent thank you @yaisog, that's a great idea.
