### ISSUE TITLE
[IDEA] Add 'strict' mode to getindex to return empty values

### ISSUE THREAD

**Issue by yaisog** [Jermolene/TiddlyWiki5#7331]
If a data tiddler contains an index, but that index has no value, `getindex[]` doesn't return an empty string, but nothing. It is therefore impossible to distinguish between the data tiddler not containing the index and the index having no value.

For backwards compatibility, I propose to add a `strict` suffix to `getindex`, which when set returns an empty string in such cases.

I think the corresponding code is in `$:/core/modules/filters/getindex.js`:
```
data = options.wiki.extractTiddlerDataItem(tiddler,operator.operand);
if(data) {
	results.push(data);
}
```
I think the condition would have to be changed to check for `undefined` (or whatever is returned from `extractTiddlerDataItem` when the index doesn't exist).

**Comment by ericshulman** [comment]
Consider the following:
```
{{{ [[SomeTiddler]getindex[test]] ~[[SomeTiddler]has:index[test]then[]] ~[[no index]] }}}
```
* The first filter run returns a non-blank index value if one exists
* The second filter run returns a blank value for an index that exists but has no value
* The third filter run returns a fallback value if the index does not exist

**Comment by pmario** [comment]
I think we should document this somewhere.

**Comment by CodaCodr** [comment]
@yaisog I totally understand the need, but I don't like the idea of using `strict` to coerce (cast) either `undefined` (or anything null-ish) to a string. Semantically wrong and just sounds wrong just saying it.

**Comment by yaisog** [comment]
@CodaCodr: I think you might have misunderstood me. What I wanted to do is rewrite the condition in the OP to `if(data !== undefined)` –  assuming that's what `extractTiddlerDataItem` returns when the index doesn't exist – so it would push `data` into the `results` array if it was just an empty string. I don't propose to cast anything into something it doesn't want to be.

This was inspired by the `strict` flat of the `tag` operator which works sort of similar?

@ericshulman: Thank you. I think I can solve my problem with this. I totally forgot about the `index` suffix of `has`.

@pmario: I will add a tip to the `getindex` docs, mostly using Eric's example, OK?

**Comment by yaisog** [comment]
Since the check should work for any number of input tiddlers, I would use this example in the docs to "extend" the `getindex` operator to empty indices in a general way:
```
\define get-index-strict() [getindex[fieldName]] :else[has:index[fieldName]then[]]

[<filter run>]  :map[subfilter<get-index-strict>]
```
