### ISSUE TITLE
[IDEA] Show links in plugins detail

### ISSUE THREAD

**Issue by linonetwo** [Jermolene/TiddlyWiki5#7336]
**Is your feature request related to a problem? Please describe.**

In plugin library, we can see github link and doc page link

![截屏2023-03-07 14 18 36](https://user-images.githubusercontent.com/3746270/223337021-f31830cb-c429-4a67-99b6-9249b38b13e5.png)

But after installed, it is gone

![截屏2023-03-07 14 18 48](https://user-images.githubusercontent.com/3746270/223337106-b8b73532-3807-4c2a-bcab-c134e9fd2fa3.png)

**Describe the solution you'd like**

Always show this info, so goto doc site will be easier.

**Describe alternatives you've considered**

**Additional context**

Sometimes I want to see a plugin's doc.

**Comment by pmario** [comment]
None of the core plugins shows info like this one. So if something should be fixed, we should be able to replicate it at tiddlywiki.com

**Comment by linonetwo** [comment]
Not using official plugin management UI. Use CPL instead.
