### ISSUE TITLE
Tickets to be reviewed/merged after release of v5.2.7

### ISSUE THREAD

**Issue by Jermolene** [Jermolene/TiddlyWiki5#7345]
We've now entered the freeze period for v5.2.6 and so are no longer merging feature PRs (we will however continue to merge bug fixes for the new features included in v5.2.6).

These are tickets that will need reviewing/merging after v5.2.6 is released:

* #7253 
* #7260
* #7361
* #7215
* #7182
* #7365
* #7292
* #7332
* #7380
* #7378 
* #7400
* #7401 
* #4541
* #7409
* #7413 
* #4624
* #7422
* #6699 

See #7279 for the roadmap for the v5.2.6 and subsequent releases.

**Comment by saqimtiaz** [comment]
We should consider merging #7297 after making a decision about ECMAScript version we will support from v5.3.0 onwards (#7353),

**Comment by linonetwo** [comment]
How about https://github.com/Jermolene/TiddlyWiki5/pull/6699

**Comment by pmario** [comment]
@Jermolene ... this PR has been delayed since 5.2.6 --  **make import listing more configurable #7308** .. It would be nice to give it a new review. 

I've updated the PR comments with more info

**Comment by pmario** [comment]
IMO this one should be considered for a review:  **table-of-content macros -- make "exclude" an official macro parameter #7417**

**Comment by saqimtiaz** [comment]
https://github.com/Jermolene/TiddlyWiki5/pull/7468 should be reviewed and merged.

**Comment by Jermolene** [comment]
All the listed tickets have now been merged (including #7468).
