### ISSUE TITLE
Planning for v5.2.7 bug fix release

### ISSUE THREAD

**Issue by Jermolene** [Jermolene/TiddlyWiki5#7372]
@flibbles discovered a bug that was introduced in v5.2.6 that we think has sufficient impact that we should make a v5.2.7 bug fix release. See #7371 for details.

**I plan to release v5.2.7 on Sunday 26th March.**

At this point the only planned change will be this fix, unless anyone knows of any other problems introduced in v5.2.6.

Please reply here if you are aware of any such bugs.

**Comment by pmario** [comment]
@Jermolene .. IMO this issue can be closed

**Comment by Jermolene** [comment]
Thanks @pmario
