### ISSUE TITLE
[BUG] RSoE with `tm-scroll` when selector is invalid

### ISSUE THREAD

**Issue by yaisog** [Jermolene/TiddlyWiki5#7375]
### Describe the bug

With generated selectors, `tm-scroll` may generate an RSoE when the selector contains invalid characters because `escapecss[]` was not used.
I this particular case, `encodeuricomponent[]` was used with superficially valid results, but it looks like % in the selector attribute then led to the RSoE.

### Expected behavior

No scrolling, but also no RSoE when the selector contains invalid characters.

### To Reproduce

1. Go to tiddlywiki.com/prerelease
2. Create new tiddler
3. Paste this as text and save tiddler:
```
<$button>
    Click
    <$action-sendmessage $message="tm-scroll" selector=".doc-tabs-New%20Tiddler" />
</$button>
```
4. Click button

### TiddlyWiki Configuration

5.2.7-prerelease

**Comment by Jermolene** [comment]
Thanks @yaisog, a PR to trap that error would be welcome.

**Comment by yaisog** [comment]
Hi @Jermolene, I think so, too. 😁 
How would you go about it? Try / catch?

**Comment by Jermolene** [comment]
Hi @yaisog there's already been a similar fix to the handling of `tm-focus-selector`. At this point, we should create a new DOM utility methods `querySelectorSafe()` (and potentially `querySelectorAllSafe()`) that incorporate the error trapping (and log the error to the console), and then refactor both `tm-focus-selector` and `tm-scroll` to use the new methods.

**Comment by yaisog** [comment]
Hi @Jermolene, what if we applied `CSS.escape()` to the string instead of error trapping? Or both, just to make really, really sure?
