### ISSUE TITLE
[BUG] If the linkcatcher widget triggers an action-navigate and $scroll is set to "no", it scrolls anyway

### ISSUE THREAD

**Issue by pmario** [Jermolene/TiddlyWiki5#7388]
### Describe the bug

If the linkcatcher widget triggers an action-navigate and the $scroll parameter is set to "no", it scrolls anyway. 

To reproduce: 

- Copy / paste the following code to tiddlywiki.com
- Click any of the links
   - They will be opend and the UI scrolls -> OK
- CTRL-click the links 
   - They scroll even of they should not -> Bug

```
\define myActions()
<$action-navigate $to=<<navigateTo>> $scroll={{{ [<modifier>match[ctrl]then[no]else[yes]] }}} />
\end

<$linkcatcher actions=<<myActions>> >

* HelloThere
* [[Learning]]
* [[Features]]

</$linkcatcher>
```

### The offending code

https://github.com/Jermolene/TiddlyWiki5/blob/2a19c60e201571087b93a7c7111df6ee18d4400a/core/modules/widgets/linkcatcher.js#L94-L100

### should be

```
	} else {
		// This is a navigate event generated by the actions of this linkcatcher, so we don't trap it again, but just pass it to the parent
		this.parentWidget.dispatchEvent(event);
	}
```

### TiddlyWiki Configuration

v5.2.7

### Additional context

I'll prepare a PR soon.

**Comment by Jermolene** [comment]
Thanks @pmario
