### ISSUE TITLE
[BUG] NPM package size grows abnormally

### ISSUE THREAD

**Issue by FSpark** [Jermolene/TiddlyWiki5#7416]
### Describe the bug

https://www.npmjs.com/package/tiddlywiki/v/5.2.6?activeTab=code

Starting from 5.2.6, TiddlyWiki's package size suddenly increased to 89.3 MB, while in 5.2.5 it was only 25.7 MB.

Seems like it's because of extra content being generated in `/editions/zh-Hans/output/` .

### TiddlyWiki Configuration

...

**Comment by Jermolene** [comment]
Thanks @FSpark and apologies for the late reply. I wasn't planning to make another release just to resolve this, and so wondered if this was causing problems for you?

**Comment by FSpark** [comment]
Hi @Jermolene , there is no big problem. It's just that my internet connection is not good, so it's difficult to install it successfully in one go. Later, I figured out that the NPM package was too large. So let's wait for 5.3.0 instead.

**Comment by Jermolene** [comment]
Great thanks @FSpark
