### ISSUE TITLE
[IDEA] Also transclude widget content when $variable is not defined

### ISSUE THREAD

**Issue by yaisog** [Jermolene/TiddlyWiki5#7424]
From the current TranscludeWidget doc:
> If no slots values are specified within the `$transclude` widget then the entire content of the widget is used as the missing content.

This works for the `$tiddler` and `$field` attributes, but not if `$variable` is used and refers to a variable that is empty or even unset. I would like this to also be treated as missing content and thus for the TranscludeWidget to use its content or the `ts-missing` fill if defined.

To test, I used this code in the current (2023-05-04) prerelease:
```
<$transclude $variable="void">
	<$button actions="""<$action-sendmessage $message="tm-notify" $param="SampleNotification" />""">Click me!</$button>
</$transclude>
```

**Comment by pmario** [comment]
On the first look, this request seems to be sensible.

**Comment by Jermolene** [comment]
Thanks @yaisog I think that's a good idea. I'll add it to my list, unless you'd like to make a PR? I'm not sure if the docs would need changing too; the current wording already implies that the fallback is used for missing variables.

**Comment by yaisog** [comment]
Hi @Jermolene, I think I'll have to skip the PR on this one. I'm a bit busy with other things at the moment. If I find the time and the issue is still open, I will have a look at it. Don't know when this will be, though.

**Comment by Jermolene** [comment]
No worries at all @yaisog I'll attend to it soon.

**Comment by yaisog** [comment]
Hi @Jermolene, those were quite comprehensive code changes. Glad you took that on. I'd have likely broken more things than I'd have fixed... 😉

**Comment by Jermolene** [comment]
> Hi @Jermolene, those were quite comprehensive code changes. Glad you took that on. I'd have likely broken more things than I'd have fixed... 😉

The changes look much worse than they really are; I had to wrap a big block of code with an if statement which changed the indentation....

**Comment by pmario** [comment]
@yaisog ... If you switch to "split" view instead of "unified", you get a much better overview
