### ISSUE TITLE
markdown.js does not render tables on 5.0.14-beta

### ISSUE THREAD

**Issue by fullaware** [Jermolene/TiddlyWiki5#743]
TiddlyWiki version 5.0.14-beta
OS:  OSX 10.9.4
Browser: Firefox 31.00
Installed plugin today: Aug 20, 2014 
Plugin source:
http://tiddlywiki.com/markdowndemo.html#%24%3A%2Fplugins%2Ftiddlywiki%2Fmarkdown

Image of issue:
![screen shot 2014-08-20 at 7 49 38 am](https://cloud.githubusercontent.com/assets/2170644/3980299/55aa0af0-2860-11e4-8e46-78313c4b8973.png)

**Comment by Dahaniel** [comment]
Found this old thread while looking for help with tables.
Tables are not rendering for me in Markdown Tiddlers in Tiddlywiki 5.1.15. I tested both dialects with no luck.

**Comment by dev4light** [comment]
@Dahaniel - works fine with Maruku in 5.1.20:

| Header  | Another header |
|---------|----------------|
| field 1 | something      |
| field 2 | something else |
