### ISSUE TITLE
problem with thisTiddler and currenTiddler

### ISSUE THREAD

**Issue by pmario** [Jermolene/TiddlyWiki5#7431]
To reproduce

```
title: macro-definitions

\define test-define() this: <<thisTiddler>> -- current: <<currentTiddler>>

\procedure test-proc() this: <<thisTiddler>> -- current: <<currentTiddler>>
```

- at https://tiddlywiki.com/prerelease/ I did test
- `title: macro-defintions` ... 2 macros 1 using `\define` other one using `\procedure`
- `title: macro-call` ... calls the macros with `<<test-define>> and <<test-proc>>`
- `title: test-transclusions` uses: `{{macro-call}} and {{||macro-call}}`

With the rendered output there is no difference between `<<thisTiddler>>` and `<<currentTiddler>>`

I'm probably misunderstanding the intention. ... **I did expect to see `macrod-definitions` somewhere.**

![image](https://user-images.githubusercontent.com/374655/236624349-f71c8db0-809b-4028-b8e2-58c1da47bebb.png)

**Comment by Jermolene** [comment]
Hi @pmario I'm having trouble following this. I think you're saying that you expected `thisTiddler` to have the value `macro-definitions`, but I'm not sure where you expected to see that.

"thisTiddler" contains the title of the last tiddler that was transcluded. The tiddler "macro-definitions" is not transcluded at any point. "thisTiddler" is not affected by macros/procedures, just transclusions. I think this is covered in the docs but improvements are welcome.

**Comment by pmario** [comment]
It would be nice, if you could show me a situation, where the rendered output of `<<thisTiddler>> is different to <<currentTiddler>>` .... I'm completely unable to create an example where they are different.

**Comment by Jermolene** [comment]
Hi @pmario a simple example would be to insert the following string at the top of `./editions/prerelease/tiddlers/system/TiddlyWiki Pre-release.tid`:

```
{{||test-tiddler}}
```

And then define the tiddler test-tiddler as:

```
thisTiddler: <$text text=<<thisTiddler>>/>, currentTiddler: <$text text=<<currentTiddler>>/>
```

In my tests, this prints `thisTiddler: test-tiddler, currentTiddler: TiddlyWiki Pre-release`

**Comment by kookma** [comment]
The documentation in https://tiddlywiki.com/prerelease/#thisTiddler%20Variable seems also to be not clear. For example note to this sentence:

> This means that within a tiddler thisTiddler will contain the title of that tiddler.

I just confused reading this sentence. May be a better wording can help!
