### ISSUE TITLE
[IDEA] Globally switching of CamelCase linking and what happens with existing ~ "unwikilink" prefix

### ISSUE THREAD

**Issue by pmario** [Jermolene/TiddlyWiki5#7435]
The ~prefix is used to prevent autolinking CamelCase terms. 

eg: `~TiddlyWiki` is usually used when the word TiddlyWiki comes up many times in 1 tiddler. IMO only 1 link should be there.

I did just run a search where `~CamelCase` "prevention" is used in TW wikitext. 

It's about 2000 times in ~750 files, for docs in different languages. 
English (tiddlywiki.com), Spanish, French, German, ... So all languages that have their own doc-editions. ... 

If CamelCase linking is globally switched off, there will still be some occurrences, where we should add links **once** per tiddler for eg: `[[TiddlyWiki]]` or other CamelCase terms that will need them. 

So there will be a massive PR with about 800 doc and UI files that will best be fixed manually. ... Manually, because we should remove all ~ signs **and** add dedicated links eg: `[[TiddlyWiki]]` where we want them. IMO there is no automatic way to "fix that problem" 

IMO fixing it for TW itself is not too much of a problem. It will be several hours of work. 

BUT all 3rd party plugin devs will also have a hard time. 

Just some thoughts

**Comment by pmario** [comment]
related (just closed) PR:  **Improve global "wikilink" parser disabling #2844**

**Comment by kookma** [comment]
I am in favor of turning off the CameCase
