### ISSUE TITLE
[BUG] Visible transcludes does not display slot content correctly

### ISSUE THREAD

**Issue by btheado** [Jermolene/TiddlyWiki5#7449]
### Describe the bug

A transclusion containing slot references is not rendered correctly when passed through the custom version of the `$transclude` widget defined in visible transcludes.

```
<$let table_slot="
* depth1: '<$slot $name=slot1/>'
"
table_fill='<$transclude $variable=table_slot  $mode=block>
  <$fill $name=slot1>slot1 value</$fill>
</$transclude>
'>

!Normal transclusion

<$transclude $variable="table_fill"/>

!Visible transclusions

The values displayed here are different than the values above. Maybe
the [[$:/core/ui/VisibleTransclude]] introduces and "off-by-one" error with the
slot depth?

<$importvariables filter="$:/core/ui/VisibleTransclude">

<$transclude $variable="table_fill"/>
</$importvariables>
</$let>
```

The normal transclusion above fills the slot and is rendered correctly. In the visible transclusion version the slot is rendered as empty.

### Expected behavior

The content for the normal transclusion should be the same as for the visible transclusion.

### To Reproduce

1. Go to this [share site url](https://tiddlywiki.com/prerelease/share##%5B%7B%22created%22%3A%2220230511131052346%22%2C%22title%22%3A%22%24%3A%2Fstate%2Fshoweditpreview%22%2C%22text%22%3A%22yes%22%2C%22modified%22%3A%2220230511131052346%22%7D%2C%7B%22title%22%3A%22%24%3A%2FStoryList%22%2C%22created%22%3A%2220230511131535070%22%2C%22text%22%3A%22%22%2C%22list%22%3A%22%5B%5BDraft%20of%20%27SlotWidget%20visible%20transclude%20bug%27%5D%5D%20%24%3A%2Fcore%2Fui%2FVisibleTransclude%22%2C%22modified%22%3A%2220230512030655523%22%7D%2C%7B%22text%22%3A%22%3C%24let%20table_slot%3D%5C%22%5Cn%2A%20depth1%3A%20%27%3C%24slot%20%24name%3Dslot1%2F%3E%27%5Cn%2A%20depth2%3A%20%27%3C%24slot%20%24name%3Dslot1%20%24depth%3D2%3Emissing%3C%2F%24slot%3E%27%5Cn%2A%20depth3%3A%20%27%3C%24slot%20%24name%3Dslot1%20%24depth%3D3%3Emissing%3C%2F%24slot%3E%27%5Cn%5C%22%5Cntable_fill%3D%27%3C%24transclude%20%24variable%3Dtable_slot%20%20%24mode%3Dblock%3E%5Cn%20%20%3C%24fill%20%24name%3Dslot1%3Eslot1%20value%3C%2F%24fill%3E%5Cn%3C%2F%24transclude%3E%5Cn%27%3E%5Cn%5Cn%21Normal%20transclusion%5Cn%5Cn%3C%24transclude%20%24variable%3D%5C%22table_fill%5C%22%2F%3E%5Cn%5Cn%21Visible%20transclusions%5Cn%5CnThe%20values%20displayed%20here%20are%20different%20than%20the%20values%20above.%20Maybe%20the%20%5B%5B%24%3A%2Fcore%2Fui%2FVisibleTransclude%5D%5D%20introduces%20and%20%5C%22off-by-one%5C%22%20error%20with%20the%20slot%20depth%3F%5Cn%5Cn%3C%24importvariables%20filter%3D%5C%22%24%3A%2Fcore%2Fui%2FVisibleTransclude%5C%22%3E%5Cn%5Cn%3C%24transclude%20%24variable%3D%5C%22table_fill%5C%22%2F%3E%5Cn%3C%2F%24importvariables%3E%5Cn%3C%2F%24let%3E%5Cn%22%2C%22created%22%3A%2220230511122953498%22%2C%22title%22%3A%22Draft%20of%20%27SlotWidget%20visible%20transclude%20bug%27%22%2C%22caption%22%3A%22slot%22%2C%22modified%22%3A%2220230512030828420%22%2C%22tags%22%3A%22%22%2C%22type%22%3A%22text%2Fvnd.tiddlywiki%22%2C%22revision%22%3A%220%22%2C%22bag%22%3A%22default%22%2C%22draft.title%22%3A%22SlotWidget%20visible%20transclude%20bug%22%2C%22draft.of%22%3A%22SlotWidget%20visible%20transclude%20bug%22%7D%2C%7B%22created%22%3A%2220230511122953498%22%2C%22text%22%3A%22%3C%24let%20table_slot%3D%5C%22%5Cn%2A%20depth1%3A%20%27%3C%24slot%20%24name%3Dslot1%2F%3E%27%5Cn%2A%20depth2%3A%20%27%3C%24slot%20%24name%3Dslot1%20%24depth%3D2%3Emissing%3C%2F%24slot%3E%27%5Cn%2A%20depth3%3A%20%27%3C%24slot%20%24name%3Dslot1%20%24depth%3D3%3Emissing%3C%2F%24slot%3E%27%5Cn%5C%22%5Cntable_fill%3D%27%3C%24transclude%20%24variable%3Dtable_slot%20%20%24mode%3Dblock%3E%5Cn%20%20%3C%24fill%20%24name%3Dslot1%3Eslot1%20value%3C%2F%24fill%3E%5Cn%3C%2F%24transclude%3E%5Cn%27%3E%5Cn%5Cn%21Normal%20transclusion%5Cn%5Cn%3C%24transclude%20%24variable%3D%5C%22table_fill%5C%22%2F%3E%5Cn%5Cn%21Visible%20transclusions%5Cn%5CnThe%20values%20displayed%20here%20are%20different%20than%20the%20values%20above.%20Maybe%20the%20%5B%5B%24%3A%2Fcore%2Fui%2FVisibleTransclude%5D%5D%20introduces%20and%20%5C%22off-by-one%5C%22%20error%20with%20the%20slot%20depth%3F%5Cn%5Cn%3C%24importvariables%20filter%3D%5C%22%24%3A%2Fcore%2Fui%2FVisibleTransclude%5C%22%3E%5Cn%5Cn%3C%24transclude%20%24variable%3D%5C%22table_fill%5C%22%2F%3E%5Cn%3C%2F%24importvariables%3E%5Cn%3C%2F%24let%3E%5Cn%22%2C%22title%22%3A%22SlotWidget%20visible%20transclude%20bug%22%2C%22caption%22%3A%22slot%22%2C%22modified%22%3A%2220230512030824102%22%2C%22tags%22%3A%22%22%2C%22type%22%3A%22text%2Fvnd.tiddlywiki%22%2C%22revision%22%3A%220%22%2C%22bag%22%3A%22default%22%7D%5D)
2. Notice how the Visible transclude content is different from the normal transclude content

### TiddlyWiki Configuration

5.3.0 prerelease

**Comment by Jermolene** [comment]
Thanks @btheado that's very helpful. The use of the share site is very effective for these reports. (I wonder if it might be worth including a share wiki in the new version archive, so that it is possible to construct a share site URL that is pegged to a particular core version – @pmario?).

I've made a fix for the problem in the OP in #7451, but would welcome some feedback on a naming issue that is discused there.
