### ISSUE TITLE
Calling attention to the Beaker Browser shut down

### ISSUE THREAD

**Issue by twMat** [Jermolene/TiddlyWiki5#7453]
This is mostly a "heads up" and I don't know where else to post it, so FWIW;

Beaker Browser is officially [declared dead](https://github.com/beakerbrowser/beaker/blob/master/archive-notice.md) for some time. I note we have some additions to the TW code for BB e.g https://github.com/Jermolene/TiddlyWiki5/pull/4777 Maybe TW modfications should be revoked? Maybe the Bluesky project mentioned in the post is a replacement and TW mods should be adapted?

**Comment by Jermolene** [comment]
Thanks @twMat I think we have already removed all references to Beaker from both the code and the docs.

The Bluesky Project is (broadly) a decentralised Twitter clone, and is sadly not in the same space as Beaker.

**Comment by twMat** [comment]
Thanks. Got it.

closing
