### ISSUE TITLE
[BUG] RSOE DiffTextWidget when non-existing arg

### ISSUE THREAD

**Issue by twMat** [Jermolene/TiddlyWiki5#7462]
### Describe the bug

Both for 5.2.7 and 5.3.0
Attempting to insert a variable call to a non-existing variable (the `<<overwrite>>`) causes the following. (Actually, that `dest` argument *ought* really be some text but, regardless):

<img width="498" alt="image" src="https://github.com/Jermolene/TiddlyWiki5/assets/4534056/21832f0a-eea0-4dc7-96ba-812bb21fed16">

### Expected behavior

....

### To Reproduce

...

### TiddlyWiki Configuration

...

**Comment by Jermolene** [comment]
Great stuff thanks @twMat.
