### ISSUE TITLE
Cancel closing a HTA-TiddlyWiki with unsaved changes warning, loses data

### ISSUE THREAD

**Issue by pmario** [Jermolene/TiddlyWiki5#747]
content from: https://groups.google.com/forum/#!topic/tiddlywiki/PEyda9Ev0Fs

---

I have my TiddlyWiki (5.0.13) in a Windows-HTA-file.

When it has unsaved changes and I close it (ALT+F4), I'm prompted with popup saying "Are you sure you want to navigate away from this page? You have unsaved changes in TiddlyWiki. Press OK to continue, or Cancel to stay on the current page."

Surprisingly, pressing Cancel closes the TiddlyWiki. :-(

Is this a Windows "thing" that we just have to accept, or can this be detected/prevented in the "beforeunload" handler?

/JUJ

PS. Also happens with 5.0.15.
PPS. If the TiddlyWiki is in a HTML-file opened with Firefox/IE, Cancel behaves as expected.

**Comment by pmario** [comment]
@Jermolene 
Issues like this one, may get a "special label" eg: `enslaved`. Since these issues can't be closed, but are "kind of" polluting the issue list with "long standing" issues.

So we may have _one_ open summary issue, that collects those `enslaved` issues and this issue could be closed with a label. 

IMO the label itself is interesting enough, if someone sees it may have a closer look, to the "closed but probably" valid issues. So there may be a chance for fixes or workarounds in the future.

**Comment by Jermolene** [comment]
Perhaps @pmario in this case it would be useful to update the docs on tw.com, since it's a pretty catastrophic problem.

> Since these issues can't be closed, but are "kind of" polluting the issue list with "long standing" issues.

I do think we should close tickets that aren't actionable. Perhaps a better label might be "cantfix".

**Comment by pmario** [comment]
not sure if it is still a problem. .. but IE usage drops. ... so imo save to label "cantfix"

**Comment by pmario** [comment]
I think, we are not able to fix this one. So I'll close it.
