### ISSUE TITLE
[IDEA] When extract HTML wiki into nodejs wiki, place plugins in tiddlers/ folder in JSON format

### ISSUE THREAD

**Issue by linonetwo** [Jermolene/TiddlyWiki5#7472]
**Is your feature request related to a problem? Please describe.**

https://github.com/tiddly-gittly/TidGi-Desktop/issues/324

Some TidGi user report that using GUI to extract HTML wiki, extracted wiki's plugin can't be managed from GUI (delete in control panel and upgrade in plugin library is not working), which is very confusing.

While installing new plugins from plugin library and delete newly installed plugin still works, which is very weird.

**Describe the solution you'd like**

But later they found out why: 

When running `wikiInstance.boot.argv = ['--load', htmlWikiPath, '--savewikifolder', saveWikiFolderPath];`
Extracted plugins will be placed into `plugins/` folder and `tiddlywiki.info` file, which can't be managed from wiki GUI.

I hope there can be an option to place all things inside tiddlers/ folder, so they can be managed from GUI.

https://github.com/tiddly-gittly/TidGi-Desktop/blob/3094eb764b1ed6507be73fdfef7e8fda65c3d080/src/services/wiki/wikiWorker.ts#L201

I think the deeper reason cause this is that 

> https://talk.tiddlywiki.org/t/the-right-way-to-install-the-shiraz-plugin-on-nodejs/6961/9?u=linonetwo
> 
> I guess previously, only geek use nodejs wiki, because it requires user to access terminal command line shell, so adding plugin in a geek way is not a problem.
>
> But now with TidGi app, even normal user can use TW nodejs wiki in an Obsidian-like way, so I think this rule will need to change when target user is TidGi app user.
> 
> (If you are using terminal to start nodejs wiki…You can keep the geek way)

**Describe alternatives you've considered**

Or we may need to implement more logic to manage plugins in plugins folder from control panel, and logic to upgrade them.

**Additional context**

To make more "normal" people use tiddlywiki, I want nodejs wiki to be easy&self-contain as HTML wiki, while still being able to access each single file from fs (for "geek user"'s git backup or vscode edit)

**Comment by Jermolene** [comment]
Hi @linonetwo as you note, the best solution to this problem would be to add a GUI for managing plugins installed via the Node.js `wiki/plugins` folder. That is likely to be a substantial and complex piece of work.

In the meantime, we could explore adding an option for the `--savewikifolder` command that controls whether plugins are exploded into the plugins folder, or are retained as ordinary tiddlers. For example:

```
--savewikifolder ./mywikifile.html explodeplugins=no
```

**Comment by linonetwo** [comment]
I remember in 2021 I was not sure about the best way for nodejs wiki user to install plugin, I was even thinking about [Github or npm as plugin storage and discovery](https://github.com/Jermolene/TiddlyWiki5/issues/2817#issuecomment-853917642). But now I think most of people don't even know what they are, and don't want to mess up with cli and folder structure.

So I think I would implement `explodeplugins=no` first, because more "normal" people will like this experience.

**Comment by Jermolene** [comment]
> So I think I would implement `explodeplugins=no` first, because more "normal" people will like this experience.

Excellent, would you be interested in working on a PR?

**Comment by linonetwo** [comment]
Sorry I shouldn't say "I would" :P , because I've invited others in the Chinese community to try this... I personally don't use this feature much, but they do.

**Comment by linonetwo** [comment]
No, I haven't implemented it, and this seems to be hard for people in https://github.com/tiddly-gittly/TidGi-Desktop/issues/324 to try, so it might take some time before starting.

**Comment by Zacharia2** [comment]
hi, @Jermolene , about this feature, I tried to have implemented it, hope it works.

**Comment by linonetwo** [comment]
Works very well. Forget to close this issue.
