### ISSUE TITLE
[PROPOSAL] If javascript is disabled, tiddlywik.com should just point to the static HTML version

### ISSUE THREAD

**Issue by pmario** [Jermolene/TiddlyWiki5#7475]
It is proposed, that tiddlywiki.com with Javascript disabled **should look like this**: 

![image](https://github.com/Jermolene/TiddlyWiki5/assets/374655/9da5bc57-4365-4073-ba00-9948f90f05a2)

**At the moment it looks like this**

![image](https://github.com/Jermolene/TiddlyWiki5/assets/374655/2b5141f5-0ea0-4b7e-aad1-97380ac59306)

**Comment by Jermolene** [comment]
Thanks @pmario that is interesting, and I agree with the suggestion.

Are those images baked into the `<noscript>` area? Removing them might give us a significant weight saving on index.html.
