### ISSUE TITLE
[BUG] https://tiddlywiki.com/static.html -- shows menubar, which hides important info and does not work anyway

### ISSUE THREAD

**Issue by pmario** [Jermolene/TiddlyWiki5#7476]
### Describe the bug

https://tiddlywiki.com/static.html -- shows menubar, which hides important info and does not work anyway

### Expected behavior

**Should look like this**

![image](https://github.com/Jermolene/TiddlyWiki5/assets/374655/234cf514-bea6-4453-9721-d2dd58df6f34)

### To Reproduce

To reproduce 

- open https://tiddlywiki.com/static.html
- Click any link **except** GettingStarted

### Screenshots

![image](https://github.com/Jermolene/TiddlyWiki5/assets/374655/81fb95ac-5927-4d64-ab95-6383d1b6ba8a)

### TiddlyWiki Configuration

tiddlywiki.com/static.html

**Comment by pmario** [comment]
@Jermolene ... Before we build the next version, imo this one needs to be fixed

**Comment by Jermolene** [comment]
Thanks @pmario fix upcoming.

> @Jermolene ... Before we build the next version, imo this one needs to be fixed

This is not a regression, so I don't actually think it was particularly urgent.
