### ISSUE TITLE
[BUG] It seems there are 2 files in the repo, which use CRLF as line ending

### ISSUE THREAD

**Issue by pmario** [Jermolene/TiddlyWiki5#7541]
### Describe the bug

plugins/tiddlywik/xmldom/files/domparser.js
plugins/tiddlywik/xmldom/files/sax.js

IMO they should be changed to LF only. It's possible to achieve that with global git settings.

It results in 600 bytes of redundant content

### TiddlyWiki Configuration

5.3.0-pre

**Comment by Jermolene** [comment]
Hi @pmario generally we try to not to modify 3rd party files, but I think this is a bit of special case.

> It's possible to achieve that with global git settings.

It would be marvellous to avoid this happening again.

**Comment by pmario** [comment]
Those files seem to be external dependencies, which we do not modify. So I'll close this issue.
