### ISSUE TITLE
[BUG] function creates __variable__ in the widget tree

### ISSUE THREAD

**Issue by pmario** [Jermolene/TiddlyWiki5#7544]
### Describe the bug

@Jermolene ... I think this one needs to be fixed in v5.3.0

I did play around with functions and text substitution and "accidentally" found a problem in the widget tree. 

Code, that does not make much sense, but creates a redundant `__title__` variable in the widget tree. IMO this could cause problems.

See screenshot.

```
\function path(title) test/<<title>>

<<path asdf>>
```

### Expected behavior

There should be no `__title__` variable

### To Reproduce

- go to https://tiddlywiki.com/prerelease/
- create new tiddler with code
- Set "preview" type to "widget tree"
- see the problem

### Screenshots

![image](https://github.com/Jermolene/TiddlyWiki5/assets/374655/a76d38e9-4592-4a80-803b-a138d4637954)

### TiddlyWiki Configuration

v5.3.0-pre

**Comment by pmario** [comment]
@Jermolene ... I think this is a critical bug. It could cause problems with a variable that could cause side effects, but nobody knows about it.

**Comment by Jermolene** [comment]
Hi @pmario I am not sure that this is critical. The phantom double underscore parameter is not accessible within the function. For example, this example returns the empty string as expected:

```
\function example(p)
[<__p__>]
\end

<<example elephant>>
```

Anyhow, fix upcoming.

**Comment by pmario** [comment]
Thx for the fix \o/

>.. I am not sure that this is critical

hmm. I somehow managed to completely brick my wiki. May be there has been some other \function code that did not behave well. Anyhow it lead to the "discovery".
