### ISSUE TITLE
[BUG] CodeMirror plugin not working in HTA mode since TiddlyWiki v5.2.1

### ISSUE THREAD

**Issue by whjou** [Jermolene/TiddlyWiki5#7545]
### Describe the bug

Since https://github.com/Jermolene/TiddlyWiki5/issues/6702 where it was reported that CodeMirror plugin was not working  using Windows HTA Hack in TiddlyWiki v5.2.2, further investigation were done as documented in https://talk.tiddlywiki.org/t/hta-hack-and-codemirror/7001 and the issue was narrowed down to 1 line in https://github.com/Jermolene/TiddlyWiki5/pull/6278 which is using the arrow function that seems to be unsupported by the older Trident MSHTML engine on Windows; when it first appeared (TiddlyWiki v5.2.1); and that it is still present in TiddlyWiki v5.2.7.

### Expected behavior

Running latest version of TiddlyWiki (v5.2.7) using Windows HTA Hack with CodeMirror plugin enabled is expected to work.

### To Reproduce

1. Start with the empty edition at https://tiddlywiki.com/empty.html
2. Save it and rename file extension to .hta
3. Execute on a Windows PC (e.g. Windows 11)
4. From the Official TiddlyWiki Plugin Library, install the CodeMirror plugin.
6. Save and reload
7. See errors.

### Screenshots

![image](https://github.com/Jermolene/TiddlyWiki5/assets/696695/ca6cb9c2-af78-4eb2-8813-ab2b716d98e5)
![image](https://github.com/Jermolene/TiddlyWiki5/assets/696695/a983fb12-ece3-4c78-9168-84ee0cc3cabe)

### TiddlyWiki Configuration

- Version - 5.2.7
- Saving mechanism - Windows HTA Hack
- Plugins installed - Empty edition with CodeMirror plugin

### Desktop (please complete the following information):

- OS: Windows 11
- Browser : n/a (HTAs are rendered using Trident MSHTML engine on Windows)
- Version: n/a

### Additional context

The suggested fix to CodeMirror plugin is to rewrite the use of arrow function from

    setTimeout(() => cm.display.input.focus(), 20);

to the non-arrow function equivalent

    setTimeout(function() {cm.display.input.focus();}, 20);

**Comment by pmario** [comment]
@Jermolene @saqimtiaz ... I think the journey @whjou has gone through for digging up the issue in #6702 deserves a fix. 

The line is at: https://github.com/Jermolene/TiddlyWiki5/blob/f4626aa69e39fb439cad674aea596ab7fc5b15c4/plugins/tiddlywiki/codemirror/engine.js#L167

**Comment by saqimtiaz** [comment]
@pmario as I recall we copied that function from the codemirror repo and therefore left it untouched.

If you have the opportunity to create a PR that would be welcome.

**Comment by pmario** [comment]
@whjou ... Are you able to create a PR? If not I'll create one.

**Comment by whjou** [comment]
> @whjou ... Are you able to create a PR? If not I'll create one.

Apologies, no. You can proceed.

**Comment by pmario** [comment]
@whjou Here's an HTA for testing with the new patch

[codemirrordemo.zip](https://github.com/Jermolene/TiddlyWiki5/files/11782398/codemirrordemo.zip)

**Comment by whjou** [comment]
Look great and works!
There's still a long way to getting other favourite plugins to work in HTA mode...

@shadowforce62 hope this will help you.

**Comment by pmario** [comment]
>There's still a long way to getting other favourite plugins to work in HTA mode...

I think HTA mode is "outdated" and should not be used anymore. @whjou you did put a lot of effort into reporting the issue and find out how to fix it. ... I thought this effort deserves a fix. ... 

But it should not have been the start to invest more effort into fixing problems with other plugins. I'll not invest any more time as I did for this issue. Sorry. 

Microsoft does not maintain the docs about [HTA since 2013](https://learn.microsoft.com/en-us/previous-versions/ms536496(v=vs.85)) .. They don't even maintain the [Software Lifecycle info](https://learn.microsoft.com/en-us/lifecycle/products/?terms=HTML%20Applications) for HTA

**Comment by whjou** [comment]
@pmario I do agree with you HTA mode is outdated, and it is no longer my primary mode of using TW, but it is nevertheless still useful in some cases. Putting in effort into making various plugins work in HTA mode is indeed not the best productive use of time: it's just a "fun" exercise for the idle like me :) . Hopefully though, if there are fixes to make a plugin work in HTA mode and that it is not breaking other parts of TW, we'll keep an open mind in accepting them?

**Comment by pmario** [comment]
@whjou @Jermolene  IMO this one can be closed. The PR was merged.

**Comment by pmario** [comment]
@Jermolene -- Can be closed. A fix has been merged

**Comment by Jermolene** [comment]
Thank you @pmario
