### ISSUE TITLE
[IDEA] NodeJS loadTiddlersFromPath should be async

### ISSUE THREAD

**Issue by linonetwo** [Jermolene/TiddlyWiki5#7547]
**Is your feature request related to a problem? Please describe.**

In https://github.com/Jermolene/TiddlyWiki5/pull/7152#issuecomment-1594014536 I found node wasting many time doing sync operations

![](https://user-images.githubusercontent.com/3746270/246303597-b612be76-fcf4-446a-a518-1e8e468cb6a2.png)

I did a simple test that add async await and replace fs call to `fs.promises.readFile` and `fs.promises.stat`, the `$tw.loadTiddlersNode` cost reduce from 3s to 0.8s (4x faster)

<img width="439" alt="截屏2023-06-16 11 16 25" src="https://github.com/Jermolene/TiddlyWiki5/assets/3746270/ef8ea5a4-e43a-4f7e-8500-22f4cd30a96a">

So I guess there was a lot of time wasted for I/O (as we learned from computer class, millions of CPU clocks will be wasted if you do sync operation waiting for disk reading.), while the CPU could have done some tiddler parsing while waiting for readFile's callback.

**Describe the solution you'd like**

Make those fs operations async, at least using callbacks, if you don't want to involve Promise.

I think this modification will only happen in the boot.js file.

**Describe alternatives you've considered**

Or we read files from sqlite, and perform swr strategy later, to update possible changes from the disk and send them to the frontend.

> The name “SWR” is derived from stale-while-revalidate, a cache invalidation strategy popularized by [HTTP RFC 5861](https://tools.ietf.org/html/rfc5861). SWR first returns the data from cache (stale), then sends the request (revalidate), and finally comes with the up-to-date data again.

**Additional context**

Obsidian opens in less than 500ms, but my nodejs wiki (TidGi) needs 5s+ to open with 20k+ tiddlers.

**Comment by Jermolene** [comment]
Hi @linonetwo the problem here is that we cannot change existing functions from sync to async without breaking backwards compatibility.

It may still be worth doing, perhaps as part of a broader modernisation of boot.js.

**Comment by linonetwo** [comment]
Yes, I close this for now, just for a backlog. We can focus on alternative store implementation that can also solve this problem.
