### ISSUE TITLE
[BUG] Empty file should not contain a @TiddlyWiki Mastodon link

### ISSUE THREAD

**Issue by simonbaird** [Jermolene/TiddlyWiki5#7555]
### Describe the bug

The "empty" file at `https://tiddlywiki.com/empty.html` contains a Mastodon `rel="me"` link. I might be wrong, but I think this is unintentional.

### Expected behavior

The Mastondon link should not appear in the empty file.

### To Reproduce

```
curl -s https://tiddlywiki.com/empty.html | grep fossto
<p><a href="https://fosstodon.org/@TiddlyWiki" rel="me">Mastodon</a></p><div class=" tc-reveal" hidden="true"></div>
```

### Screenshots

n/a

### TiddlyWiki Configuration

n/a

**Comment by Jermolene** [comment]
Thanks @simonbaird, I've committed a fix for the prerelease
