### ISSUE TITLE
[BUG] Any usage of an undefined function in a filter triggers a red Internal JavaScript Error popup

### ISSUE THREAD

**Issue by saqimtiaz** [Jermolene/TiddlyWiki5#7566]
### Describe the bug

This code will trigger the error in v5.3.0 pre-release:

`{{{ [doesnot.exist[]] }}}`

The description is: `Uncaught Linked List only accepts string values, not undefined`.

**Comment by saqimtiaz** [comment]
https://github.com/Jermolene/TiddlyWiki5/blob/6bb0da07dc8ffb0eaece893f7bf45d4657a948dc/core/modules/filters/unknown.js#L29-L31

Both `resultList` and `text` properties of `variableInfo` are `undefined` and thus this is the value returned by the operator.

Furthermore @Jermolene, would it not be appropriate to fallback to the field[] operator, if the operator specified does have a dot character but no function what that name exists?

Otherwise filters of this form would start to fail: `[draft.of[New Tiddler]]` and this would be a backwards compatibility break.

**Comment by kookma** [comment]
> {{{ [doesnot.exist[]] }}}

I confirm the error. Win 10, Chrome 113

**Comment by Jermolene** [comment]
Thanks @AnthonyMuscio @saqimtiaz @kookma, fix coming up
