### ISSUE TITLE
Ability for upgrader modules to non-destructively uncheck tiddlers

### ISSUE THREAD

**Issue by danielo515** [Jermolene/TiddlyWiki5#758]
In order to let third-party developers create their own upgrader modules, this handler at the navigation widget should provide more flexibility. Currently the only way to uncheck a tiddler to be imported is deleting all its fields. This is maybe good for blocking purposes but it is too radical for other purposes. For example unchecking existing tiddlers. I think this can be an easy change with lots of useful possibilities.

**Comment by pmario** [comment]
@Jermolene ... I think this can be closed now, since the desired behaviour will ship with 5.2.0

**Comment by Jermolene** [comment]
Thanks @pmario
