### ISSUE TITLE
[BUG] compatibility problem with new icon transclusions as macro parameters using old text-substitution

### ISSUE THREAD

**Issue by pmario** [Jermolene/TiddlyWiki5#7580]
### Describe the bug

Copy / paste this code into a new tiddler at tiddlywiki.com

There are 2 macrocalls 

- the first one works, because it uses the macro definition default settings for the icons
- the second one fails, because it uses different icons that are transferred as macrocall parameters

```
\define toggleOkCancel(state openText:"Edit" okText:"OK" closeText:"Cancel" openActions okActions cancelActions openIcon:{{$:/core/images/chevron-down}} okIcon:{{$:/core/images/chevron-up}} cancelIcon:{{$:/core/images/cancel-button}} class)
<$reveal state="$state$" type="match" text="closed" default="closed">
<$button set="$state$" setTo="open" class="$class$ tc-btn-invisible" selectedClass="tc-selected" actions="""$openActions$""" >
$openIcon$  $openText$
</$button>
</$reveal>
<$reveal state="$state$" type="match" text="open" default="closed">
<$button set="$state$" setTo="closed" class="$class$ tc-btn-invisible" selectedClass="tc-selected" actions="""$cancelActions$""">
$cancelIcon$ $closeText$
</$button>&nbsp;
<$button set="$state$" setTo="closed" class="$class$ tc-btn-invisible" selectedClass="tc-selected" actions="""$okActions$""">
$okIcon$ $okText$
</$button>
</$reveal>
\end

<<toggleOkCancel state >>

<$macrocall $name="toggleOkCancel" state=test-state openText=" " okText=" " closeText=" " deleteText=" " openIcon={{$:/core/images/edit-button}} okIcon={{$:/core/images/save-button}} />
```

### Screenshots

![image](https://github.com/Jermolene/TiddlyWiki5/assets/374655/5526da6a-d50c-4133-9215-846d6d4a1345)

### TiddlyWiki Configuration

v5.3.0

**Comment by pmario** [comment]
I needed to modify the OP code, since a state-macro was missing. now the code should work to reproduce the problems

**Comment by btheado** [comment]
Even with the screenshot I was having trouble understanding, so I reduced the code to eliminate the noise:

```
\define iconInButton(openIcon:{{$:/core/images/chevron-down}})
<$button>
$openIcon$  Edit
</$button>
\end

<<iconInButton>>

<$macrocall $name="iconInButton" openIcon="{{$:/core/images/chevron-down}}" />

<$macrocall $name="iconInButton" openIcon={{$:/core/images/chevron-down}} />
```

The first two macro calls  render fine, but the third one has the `\parameters...` text showing.

I guess the problem is textual substitution won't arbitrarily work when the text contains pragmas. Pragmas will only be processed at the top of a transclusion. But in the third example there is no transclusion, only tiddler text retrieval during the macro argument processing.

**Comment by pmario** [comment]
@btheado ... Thanks for simplifying the code. I started to simplify the code, but then I decided to show the code as it is in the app. 

Some weeks ago I did change the app from 5.1.x to 5.2.7. The funny thing is, I use the app everyday, but wasn't even thinking about to test it with the pre-release. My bad. 

Now I wanted to see, how to update the code and found the problem :/

>I guess the problem is textual substitution won't arbitrarily work when the text contains pragmas. Pragmas will only be processed at the top of a transclusion. But in the third example there is no transclusion, only tiddler text retrieval during the macro argument processing.

I think that's right.

**Comment by pmario** [comment]
OK
