### ISSUE TITLE
[BUG] NodeJS fails with "Global assignment is not allowed within modules on node." since v5.3.0

### ISSUE THREAD

**Issue by flibbles** [Jermolene/TiddlyWiki5#7585]
### Describe the bug

Running on NodeJS on TiddlyWIki version 5.3.0. Running the battery of Relink Unit tests results in an aborted run with the warning "Global assignment is not allowed within modules on node.", which points to a semi-random file which clearly doesn't have the issue.

Something changed between TiddlyWiki v5.2.x and v5.3.0 which made NodeJS not function. A Google search on that error pulls up two results within the entire internet. One is issues #7465, the other is an issue submitted to TiddlyMap which I ignored until it went away.

### TiddlyWiki Configuration

NodeJS version: v15.5.1
TiddlyWiki version: v5.3.0

**Comment by pmario** [comment]
Did you try it with node 18 LTS, which is the [latest active](https://nodejs.dev/en/about/releases/) node version atm?

**Comment by flibbles** [comment]
I didn't, but is that really the solution? It looked like in #7465, the idea was to make it so TiddlyWiki didn't drop support for existing versions of NodeJS.

v5.3.0 has broken all the plugins I've ever made for TiddlyWiki. I *could* fix them all, but isn't TiddlyWiki supposed to be taking backward compatibility seriously?

**Comment by pmario** [comment]
I'm with you: https://github.com/Jermolene/TiddlyWiki5/issues/7465#issuecomment-1554203277 I wrote, that we should not try to support node versions that are officially dead. 

@Arlen22 ... can you have a closer look, since I do not really know what the PR #4624 does

**Comment by Arlen22** [comment]
Yes, this is a feature we introduced to cut down on startup times related to sandboxing. It is not an intended use case to have globals introduced into the node environment, however test engines often do so. 

Can you tell me how I can run these tests for myself so I can reproduce the issue?

**Comment by Arlen22** [comment]
> Yes, this is a feature we introduced to cut down on startup times related to sandboxing. It is not an intended use case to have globals introduced into the node environment, however test engines often do so.
> 
> Can you tell me how I can run these tests for myself so I can reproduce the issue?

@flibbles

**Comment by flibbles** [comment]
It's the Relink testing suite. I can also send you some of my output.
```
F.F.[ 'paramName' ]
Error executing boot module $:/plugins/flibbles/relink/js/utils/backupIndexer.js: "Global assignment is not allowed within modules on node."
```
```
......................[ 'match', 'result', 'template', 'builder' ]
Error executing boot module $:/plugins/flibbles/relink/js/filteroperators/orphans.js: "Global assignment is not allowed within modules on node."
```
```
...............
Error executing boot module $:/plugins/flibbles/relink/js/filteroperators/orphans.js: "Global assignment is not allowed within modules on node."
```
```
F..F................[ 'paramName', 'builder', 'match', 'result', 'template' ]
Error executing boot module $:/plugins/flibbles/relink/js/filteroperators/orphans.js: "Global assignment is not allowed within modules on node."
```

It's fun because it's giving slightly different output every time, even when the test fails on the same file.

Hope that helps. If the fault is in Relink, and it actually pointed to the correct files, I might fix it myself, but the files it's indicating do not seem to have any problems at all.

**Comment by flibbles** [comment]
If you actually want to run the tests, just check out https://github.com/flibbles/tw5-relink and run `tiddlywiki --build test` from the command line, though on v5.3.0, there will be a ton of failing tests right now because v5.3.0 introduced a lot of breaking changes.

**Comment by Arlen22** [comment]
Short preliminary answer is that there is a semi-colon instead of a comma on line 85 or so of tiddler `$:/plugins/flibbles/relink/js/relinkoperations/text/wikitext/transclude.js`.

Obviously this will pollute the browser scope, so I'm guessing it's a bug on your end. But let me see if there's an easier way to track down these kinds of errors, because the cause wasn't obvious at all and I had to define a setter on the global for the properties which were being added to figure out what was setting them.

**Comment by Arlen22** [comment]
This eslintrc.js file catches these errors. 

```js
module.exports = {
    "env": {
        "commonjs": true,
    },
    "rules": {
        "no-implicit-globals": "error",
    }
}
```

Place it in your root directory, then run the commend `npx eslint plugins`.

**Comment by Arlen22** [comment]
After fixing the errors indicated by this command, the tests apparently run: `459 specs, 59 failures`

**Comment by Arlen22** [comment]
> Hope that helps. If the fault is in Relink, and it actually pointed to the correct files, I might fix it myself, but the files it's indicating do not seem to have any problems at all.

You are correct. The error was thrown for whichever module happened to be evaluated next after the global was polluted. This particular error is always hard to track down. I think eslint is probably the best solution.

**Comment by flibbles** [comment]
Well, I guess that's fixed now. Thank you for tracking this down for me. Now I just have to contend with the fact that all my plugins are now *silently* broken because of v5.3.0. (There aren't normally 59 failures.)

**Comment by pmario** [comment]
>Now I just have to contend with the fact that all my plugins are now silently broken because of v5.3.0. (There aren't normally 59 failures.)

IMO you should create a new issue for this on. I'm sure it was not intended to be that way.

**Comment by Jermolene** [comment]
Thank you @flibbles @Arlen22 I'm sorry this has not gone smoothly. The pattern of a new release exposing latent issues with existing third party code is particularly insidious.

One takeaway is the importance of widespread user testing of prerelease versions. We particularly tried with v5.3.0 to encourage users to test the new version while it was in prerelease and so it's very disappointing to learn of this incompatibility three days after the release was made.

**Comment by flibbles** [comment]
@Jermolene, it did reveal latent issues with Relink, but the bulk my problem seems to be that the parseTree nodes made by transclusion wikitext are now very different. So any plugins that worked with the wikiparser at all can no longer handle them.

**Comment by flibbles** [comment]
Oh, and I realize these changes would have been much better to deal with before the release, and that is regrettable. I haven't been involved with TiddlyWiki development for a few months now, so I didn't realize a new release was coming.

**Comment by Jermolene** [comment]
> @Jermolene, it did reveal latent issues with Relink, but the bulk my problem seems to be that the parseTree nodes made by transclusion wikitext are now very different. So any plugins that worked with the wikiparser at all can no longer handle them.

Yes indeed, that could have been handled differently if we'd figured things out earlier.

> Oh, and I realize these changes would have been much better to deal with before the release, and that is regrettable. I haven't been involved with TiddlyWiki development for a few months now, so I didn't realize a new release was coming.

No worries, in an ideal world keeping things working shouldn't require constant attention to the project. Given that you have tests set up, perhaps what's needed here is to be running your tests in CI so that we get early warning of any problems.

**Comment by flibbles** [comment]
I'm reopening this.

I get that you all wanted a tighter ship with plugin handling, but listen. I'm getting a lot of people submitting bug reports to Tiddlymap because they can no longer open their tiddlywiki after updating to V5.3.0. This Global Assignment behavior was something that some plugins had (which can no longer be used), or in the case of vis-network, a *required* plugin for tiddlymap which is made by a 3rd party, it **uses** global assignment.

This sudden hardline in disallowing global assignment is breaking a lot of people's tiddlywikis.

**Comment by Jermolene** [comment]
Hi @flibbles yes indeed, I am now thinking that we should revert this change in a new v5.3.1 release in the next few days.

**Comment by flibbles** [comment]
Maybe at least downgrade it to a warning. If I recall from looking at the code, it's not like execution has to stop at that point. A warning might give people time to implement "use strict" and clean up.

For reference, besides the issue addressed in this thread, I've encountered this [here](https://github.com/tiddly-gittly/TidGi-Desktop/issues/385) and [here](https://github.com/felixhayashi/TW5-TiddlyMap/issues/450). I guess that's not *a lot*, but for everyone who submits a bug, who knows how many else encountered the issue.
