### ISSUE TITLE
[BUG] CheckboxWidget listIndex mode no longer working in 5.3.0

### ISSUE THREAD

**Issue by pmario** [Jermolene/TiddlyWiki5#7586]
### Describe the bug

As described at Talk: [CheckboxWidget listIndex mode no longer working in 5.3.0](https://talk.tiddlywiki.org/t/checkboxwidget-listindex-mode-no-longer-working-in-5-3-0/7460)

Test https://tiddlywiki.com/#CheckboxWidget%20%28listIndex%20Mode%29

The problem was introduced with commit: https://github.com/Jermolene/TiddlyWiki5/commit/fb10b1ee9183f1b9c0e5dc05ef7b586f26bab403

Since `this.checkboxTitle` does not exist and there is no fallback-value defined the next if - else-if construction in line 215 fails and returns. 

```
fieldContents = this.wiki.extractTiddlerDataItem(this.checkboxTitle,this.checkboxListIndex);
```

`exports.extractTiddlerDataItem = function(titleOrTiddler,index,defaultText) {` .. allows a defaultText value. So IMO it should be set. 

![image](https://github.com/Jermolene/TiddlyWiki5/assets/374655/6e572ed7-af6f-4cbf-9ba0-e8423df42648)

---- Just a gut feeling ----

For me it seems the whole widget has a bit of an initialisation problem. .. Testing in single step mode there are way to many undefined values. ..

@rmunn ... Most TW functions have a possibility to define a default value, if the tiddler, the field or index does not exist. 

### TiddlyWiki Configuration

v5.3.0

**Comment by rmunn** [comment]
This has been fixed by https://github.com/Jermolene/TiddlyWiki5/pull/7679. (I created #7678 because I didn't notice you'd already created this issue, sorry.)

**Comment by pmario** [comment]
should be fixed by: https://github.com/Jermolene/TiddlyWiki5/pull/7679
