### ISSUE TITLE
[BUG] DroppableWidget classes are not applied 

### ISSUE THREAD

**Issue by twMat** [Jermolene/TiddlyWiki5#7587]
### Describe the bug

I'm successfully(!) using the draggable and droppable widgets but applying a *class* using a **filtered transclusion** to droppable does not function properly. The following (simplified illustration) is intended to apply both classes `XXX` and `YYY` but only the first is applied:

```
<$list filter='one two three' >
    <$droppable class={{{ XXX YYY }}} >
       <$link/>
    </$droppable>
</$list>
```

### TiddlyWiki Configuration

(likely irrelevant)

**Comment by saqimtiaz** [comment]
Filtered attributes only use the first of the filter results. Join them into a single string to avoid the problem.

**Comment by twMat** [comment]
@saqimtiaz - with your reply I get it to work. Thank you.

What confuses me is that just typing {{{ XXX YYY }}} into a tiddler *does* output two links so I don't understand how this differs from the OP...?

**Comment by btheado** [comment]
> I don't understand how this differs from the OP...?

When used as attribute values, the behavior for the syntax is different than when used elsewhere in wikitext

1. `<$droppable class={{{ XXX YYY }}} > <$link/> </$droppable>` - execute the filter and use the first result as the attributes' value
1. `<$droppable class={{XXX}} > <$link/> </$droppable>` - retrieve the contents of the tiddler XXX and use as the attributes' value
1. `<$droppable class=<<XXX>> > <$link/> </$droppable>` - retrieve the contents of variable XXX and use as the attributes' value

vs.

1. `{{{ XXX YYY }}}` - synonym for `<$list filter="XXX YYY"/>`
2. `{{XXX}}` - retrieve the contents of tiddler XXX and render as wikitext
3.  `<<XXX>>` - retrieve the contents of variable XXX and render as wikitext

**Comment by twMat** [comment]
>When used as attribute values, the behavior for the syntax is different than when used elsewhere in wikitext

I was not expecting that! I can't find this in the docs - anybody know where?

Thank you @btheado

**Comment by saqimtiaz** [comment]
@twMat the key is that you cannot use arbitrary wikitext as a widget (or HTML element) attribute, instead specific types of attributes are supported, one of which is filtered attributes. The confusion comes in because filtered attributes have the same triple curly braces as filtered transclusions. They are similar but distinct mechanisms. Filtered attributes also do not support templates.

See https://tiddlywiki.com/#Widget%20Attributes:%5B%5BWidget%20Attributes%5D%5D%20%5B%5BFiltered%20Attribute%20Values%5D%5D
