### ISSUE TITLE
Import/Upgrade: Disable checkbox for blocked tiddlers

### ISSUE THREAD

**Issue by Jermolene** [Jermolene/TiddlyWiki5#759]
If an upgrader module blocks a tiddler from import it is still displayed with a checkbox that implies to the user that they can use the checkbox to override the blocking. In fact re-checking a blocked tiddler has no effect. It would be better to disable the checkbox.

**Comment by pmario** [comment]
@Jermolene ... This can be closed, since the existing UI takes care of this problem

**Comment by Jermolene** [comment]
Thanks @pmario.
