### ISSUE TITLE
[BUG] Transclude Widget doesn't render [[!!title]] as links

### ISSUE THREAD

**Issue by EHJ-52n** [Jermolene/TiddlyWiki5#7598]
### Describe the bug

I use the [transclude widget](https://tiddlywiki.com/static/TranscludeWidget.html) for rendering different tiddlers in an overview of my daily tasks, having the tiddler title as link to be able to easily access the specific tiddler from the overview one.

### Expected behavior

The tiddler titles should be rendered as links. Like it's done in the list of open tasks of the day in the screenshot below:

### To Reproduce

1. Create a new tiddler with the following content: `<$transclude field="text" mode="block" tiddler="ItIs20230710" />`
2. Create the tiddler with the title `ItIs20230710` with the following content: `* {{!!title}}`
3. See error: the first tiddler will contain a list with one single entry `ItIs20230710` which is not rendered as link to the according tiddler.

### Screenshots

![transclude_widget_tiddler_title_not_rendered_as_link](https://github.com/Jermolene/TiddlyWiki5/assets/3839896/0ca3b4e7-3526-4fcf-96a1-fffaa72f6c36)

### TiddlyWiki Configuration

- Version [e.g. v5.1.24]: `5.3.0`
- Saving mechanism [e.g. Node.js, TiddlyDesktop, TiddlyHost etc]: `Node.js`
- Plugins installed [e.g. Freelinks, TiddlyMap]:

<details><summary>installed plugins (22)</summary>

```
2click2edit: double click to edit tiddlers 
$:/plugins/danielo515/2click2edit
0.1

FontAwesome: FontAwesome embedded font support for TW5 
$:/plugins/TheDiveO/FontAwesome
1.2.22

CodeMirror: CodeMirror editor 
$:/plugins/tiddlywiki/codemirror
5.3.0

CodeMirror Autocomplete: Autocompletion for CodeMirror 
$:/plugins/tiddlywiki/codemirror-autocomplete
5.3.0

CodeMirror Close Brackets: Close brackets for CodeMirror 
$:/plugins/tiddlywiki/codemirror-closebrackets
5.3.0

CodeMirror Close Tag: Close tags automatically for CodeMirror 
$:/plugins/tiddlywiki/codemirror-closetag
5.3.0

CodeMirror Keymap Vim: Keymap compatible with Vim for CodeMirror 
$:/plugins/tiddlywiki/codemirror-keymap-vim
5.3.0

CodeMirror Mode CSS: CSS highlighting mode for CodeMirror 
$:/plugins/tiddlywiki/codemirror-mode-css
5.3.0

CodeMirror Mode HTML Embedded: Embedded HTML highlighting mode for CodeMirror 
$:/plugins/tiddlywiki/codemirror-mode-htmlembedded
5.3.0

CodeMirror Mode HTML Mixed: HTML mixed highlighting mode for CodeMirror 
$:/plugins/tiddlywiki/codemirror-mode-htmlmixed
5.3.0

CodeMirror Mode JavaScript: JavaScript highlighting mode for CodeMirror 
$:/plugins/tiddlywiki/codemirror-mode-javascript
5.3.0

CodeMirror Mode Markdown: Markdown highlighting mode for CodeMirror 
$:/plugins/tiddlywiki/codemirror-mode-markdown
5.3.0

CodeMirror Mode TiddlyWiki Classic: Tiddlywiki Classic highlighting mode for CodeMirror 
$:/plugins/tiddlywiki/codemirror-mode-x-tiddlywiki
5.3.0

CodeMirror Mode XML: XML highlighting mode for CodeMirror 
$:/plugins/tiddlywiki/codemirror-mode-xml
5.3.0

CodeMirror Search and Replace: Search and replace for CodeMirror 
$:/plugins/tiddlywiki/codemirror-search-replace
5.3.0

Core: TiddlyWiki5 core 
$:/core
5.3.0

DetailsWidget: Disclosure HTML element 
$:/plugins/telmiger/details
0.7.5

Filesystem: Synchronize changes from the node.js server to the local filesystem 
$:/plugins/tiddlywiki/filesystem
5.3.0

Highlight: Highlight.js syntax highlighting 
$:/plugins/tiddlywiki/highlight
5.3.0

Markdown: Markdown parser based on remarkable by Jon Schlinkert 
$:/plugins/tiddlywiki/markdown
5.1.23

TiddlyWeb: Sync changes from the browser to TW5 (node.js) or TiddlyWeb server 
$:/plugins/tiddlywiki/tiddlyweb
5.3.0

Trashbin: A trashbin mechanism for Tiddlywiki 
$:/plugins/kookma/trashbin
1.2.3
```
</details>

### Desktop

- OS: [e.g. iOS] `Ubuntu 22.04.2 LTS`
- Browser [e.g. chrome, safari] `Chromium`
- Version [e.g. 22] `Version 114.0.5735.198 (Official Build) for Linux Mint (64-bit)`

### Additional context

Downgrading to version 5.2.7 solves this issue.

**Comment by saqimtiaz** [comment]
Have you tried enabling CamelCase from the Control Panel? As of v5.3.0 it is disabled by default

**Comment by EHJ-52n** [comment]
This "solves" the problem.

1. Why the heck is a core wiki feature (automatic linking of CamelCase terms) disabled?
2. Why is it changed for existing installations, and not only disabled for new installations?

**Comment by pmario** [comment]
> 1) Why the heck is a core wiki feature (automatic linking of CamelCase terms) disabled?

hmmm, Because of user feedback. Since several years now, we do get feedback from new users, that CamelCase linking is confusing for them or their end-users. So with v5.3.0 we did change the default setting, knowing that it will be less of a problem for advanced users to activate it again ;)

> 2) Why is it changed for existing installations, and not only disabled for new installations?

The configuration is a shadow-tiddler, so we cannot really see it with an update from 5.x.y to v5.3.0. If you change the setting in your wiki now the configuration will become a system-tiddler and your next update should keep the setting.
