### ISSUE TITLE
[BUG] Attribute substitution doesn't substitute variables whose names contain dashes

### ISSUE THREAD

**Issue by btheado** [Jermolene/TiddlyWiki5#7604]
### Describe the bug

```
\define test-dash() dash
\procedure test() nodash

<$text text=`$(test-dash)$ - $(test)$`/>
```
renders as:

`$(test-dash)$ - nodash`

### Expected behavior

I expect it to render as 

`dash - nodash`

### To Reproduce

paste the above example into tiddlywiki.com

### TiddlyWiki Configuration

tiddlywiki.com 5.3.0

### Additional context

It seems to me the regexp here:
https://github.com/Jermolene/TiddlyWiki5/blob/f517497fe7cc2b9aec70e2a8390ebaf67fdee39f/core/modules/wiki.js#L1089

should be the same as the regexp here:
https://github.com/Jermolene/TiddlyWiki5/blob/f517497fe7cc2b9aec70e2a8390ebaf67fdee39f/core/modules/widgets/widget.js#L235

**Comment by saqimtiaz** [comment]
@btheado good catch, a PR would be most welcome. The original intent had been for the substitution to be refactored to call the widget base class method, but that is not possible due to backwards compatibility constraints.

One of the things I find odd about the original regular expression is that it allows white space in a variable name.

**Comment by pmario** [comment]
>One of the things I find odd about the original regular expression is that it allows white space in a variable name.

hmmm, I think we should not allow that. 

If the regexp is fixed, IMO the following code will work too. .. I'm not sure if it should work

```
<$set name="aa aa" value=x>

<$macrocall $name="aa aa" />

<$text text=`$(aa aa)$`/>

```

**Comment by saqimtiaz** [comment]
We can exclude white space characters in the regexp:

`\$\(([^\)\$\s]+)\)\$`

**Comment by Jermolene** [comment]
> One of the things I find odd about the original regular expression is that it allows white space in a variable name.

I'm pretty sure that that was intentional. Just like tiddler titles, we don't restrict the names of variables at all. Partly because there's no obvious way to do so. What should `widget.setVariable(name,value)` do if the name contains whitespace?
