### ISSUE TITLE
[BUG] code block syntax should allow adjacent to previous paragraph

### ISSUE THREAD

**Issue by linonetwo** [Jermolene/TiddlyWiki5#7614]
### Describe the bug

This is a wikitext generated by AI

 Here is an example of a JSON representing a game character:
```json
{
  "name": "Player",
  "age": 25,
  "gender": "Male",
  "race": "Human",
  "class": "Warrior",
  "level": 10,
  "experience": 1000,
  "equipment": [
    {
      "name": "Sword",
      "level": 1,
      "damage": 5
    },
    {
      "name": "Shield",
      "level": 1,
      "defense": 5
    },
    {
      "name": "Healing Potion",
      "level": 1,
      "healing": 10
    }
  ],
  "abilities": [
    {
      "name": "Strength",
      "level": 1,
      "damage": 5
    },
    {
      "name": "Agility",
      "level": 1,
      "damage": 2
    },
    {
      "name": "Healing",
      "level": 1,
      "healing": 5
    }
  ]
}
```
This JSON represents a game character with the following attributes:

* `name`: "Player"
* `age`: 25
* `gender`: "Male"
* `race`: "Human"
* `class`: "Warrior"
* `level`: 10
* `experience`: 1000
* `equipment`: an array of equipment items
* `abilities`: an array of abilities

Each equipment item has the following attributes:

* `name`: the name of the item
* `level`: the level of the item
* `damage`: the amount of damage dealt by the item

Each ability has the following attributes:

* `name`: the name of the ability
* `level`: the level of the ability
* `damage`: the amount of damage dealt by the ability
* `healing`: the amount of health restored by the ability

Note that this is just an example and the structure and attributes of the JSON can be modified to suit the specific needs of the game character representation.

<end>

![截屏2023-07-19 15 55 05](https://github.com/Jermolene/TiddlyWiki5/assets/3746270/ad7e80e0-1503-40ec-a68e-6d6bf9732447)

And is rendered bad because there is no \n between 

> Here is an example of a JSON representing a game character:

and 

> ```json

### Expected behavior

We should allow two paragraph adjacent without \n

### To Reproduce

1. Paste the code above
2. See preview

### TiddlyWiki Configuration

- Version [e.g. v5.1.24] 5.3.0

### Desktop (please complete the following information):

- OS: [e.g. iOS] Mac
- Browser [e.g. chrome, safari] Electron

### Additional context

Generated using AI which don't know rule that paragraph can't followed by codeblock

https://talk.tiddlywiki.org/t/tidgi-is-the-first-bi-link-note-taking-app-with-free-local-ai-that-works-totally-offline-and-privately/7600/2

**Comment by Jermolene** [comment]
Hi @linonetwo congratulations on your work on running AI in TidGi.

> And is rendered bad because there is no \n between

You're asking if the paragraph syntax can be changed to allow a single line break before a code block, instead of requiring a double line break.

Unfortunately, this change would not be backwards compatible. It is a popular request however. The approach that might be promising would be to add support for custom wikitext vocabularies, see #345 for details. Then we could have an alternate vocabulary that supports single line break as a paragraph separator.

**Comment by linonetwo** [comment]
Oh, I thought this was a bug, because I was only looking at this situation where a line break is between paragraph and codeblock.

```
 Here is an example of a JSON representing a game character:
\`\`\`json
{
  "name": "Player",
}
\`\`\`
This JSON represents a game character with the following attributes
```

But if this will have to touch all paragraph-related syntax, then we have to keep it.

**Comment by linonetwo** [comment]
Also, when translating plugin in this traditional approach

```wikitext
title: $:/plugins/linonetwo/tidgi-language-model/readme
type: text/vnd.tiddlywiki
caption: ChatGPT

<$list filter="[[$:/language]get[text]removeprefix[$:/languages/]else[en-GB]]" variable="lang">
<$list filter="[<lang>search[zh]]">

  {{$:/plugins/linonetwo/tidgi-language-model/readme/zh-Hans}}

</$list>

<$list filter="[<lang>!search[zh]]">

  {{$:/plugins/linonetwo/tidgi-language-model/readme/en-GB}}

</$list>
</$list>
```

If there is no line break between transclusion and list widget, like

```
<$list filter="[<lang>search[zh]]">
  {{$:/plugins/linonetwo/tidgi-language-model/readme/zh-Hans}}
</$list>
```

**Comment by linonetwo** [comment]
> Hi @linonetwo congratulations on your work on running AI in TidGi.

Thanks, it is all opensourced at https://github.com/tiddly-gittly/TidGi-Desktop/blob/baa4c95303a3d74dc1f25e8cd9a3e30da7cd8fb0/src/services/languageModel/llmWorker/llamaCpp.ts

just some glue code to use llama-node. The key feature I want to achieve is using https://github.com/noflo/noflo to create AI workflow, this is what I'm still working on.
