### ISSUE TITLE
[BUG] Advanced Search is always focused despite clicking away 

### ISSUE THREAD

**Issue by Dialga** [Jermolene/TiddlyWiki5#7656]
### Describe the bug

I wanted to try out the different themes in the palette, in order from top to bottom, however if the $:/AdvancedSearch tiddler is open at top then the page always scrolls back up.

Closest cause of this bug is https://github.com/Jermolene/TiddlyWiki5/issues/7008.

### Expected behavior

I can try all the different colored palettes in order without $:/AdvancedSearch stealing focus each time.

### To Reproduce

1. Go to https://tiddlywiki.com/prerelease/empty
2. Click on Control Panel
3. Click on Advanced Search
4. Go to Control Panel, Appearance, Palette
5. Click on each theme in order, once you reach the bottom of the screen focus will return back to the Advanced Search box by a knee jerk scroll.

### TiddlyWiki Configuration

- Version 5.3.1-prerelease
- Saving mechanism [e.g. Node.js, TiddlyDesktop, TiddlyHost etc]
- Plugins installed [e.g. Freelinks, TiddlyMap]

**Comment by Dialga** [comment]
> The second way to change that behaviour is a hidden-setting [Search AutoFocus](https://tiddlywiki.com/#Hidden%20Setting%3A%20Search%20AutoFocus:%5B%5BHidden%20Setting%3A%20Search%20AutoFocus%5D%5D%20%5B%5BHidden%20Settings%5D%5D) -- set it to **false**

Ah such a simple fix, just tried that and it works.
Though my feedback would be that search input should not default to auto-focus, primarily because it breaks the experience of trying out the different themes. On top of that Ctrl+Shift+A defaults to Advanced Search rather than the browser search tabs function, which I use more often than AS and it is really helpful in finding opening tabs.

**Comment by pmario** [comment]
>Though my feedback would be that search input should not default to auto-focus, [. . .]

Yea, that's why we made it configurable. We do get an issue like yours probably once every several years.  -- But we frequently got complains, that the AS tiddler did not get the focus. So users had to click twice. The setting was added about 8 years ago and usually works for most users.
