### ISSUE TITLE
[BUG] EditText widget - can't add ::before or ::after CSS pseudo elements

### ISSUE THREAD

**Issue by twMat** [Jermolene/TiddlyWiki5#7658]
It seems not possible to add a `::before` or `::after` CSS pseudo element to the EditTextWidget.
In the inspector tool you *can* see that there is indeed a pseudo element, it just doesn't show up.

### To Reproduce

Test by copy-pasting this:

```
<$edit-text tiddler=foo class=test />

<style>
.test::after {
content:"THIS JUST DOESNT APPEAR" !important;
display:block !important;
width:20px !important;
height:20px !important;
background:red !important;
}
</style>
```

### TiddlyWiki Configuration

Chrome / brave

**Comment by Alzacon** [comment]
It is a the behavior of CSS for some elements.
In the [documentation of :after in MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/::after) there is the following note:

> Note: The pseudo-elements generated by ::before and ::after are [contained by the element's formatting box](https://www.w3.org/TR/CSS2/generate.html#before-after-content), and thus don't apply to [replaced elements](https://developer.mozilla.org/en-US/docs/Web/CSS/Replaced_element) such as [`<img>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/img), or to [`<br>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/br) elements.

Tiddlywiki generate a `<textarea>` as output and `<textarea>` is a replaced element.

**Comment by twMat** [comment]
@Alzacon , it appears you are right! That was unknown to me, thank you.
Closing.
