### ISSUE TITLE
[BUG] Can't select specific text in edit mode text box in 5.3.1 on Android Firefox (maybe others)

### ISSUE THREAD

**Issue by Marxsal** [Jermolene/TiddlyWiki5#7675]
### Describe the bug

Typically, on Android, long pressing text in the edit box while editing will select the current text and create "handlebars" that will allow the user to expand or shrink the text as needed. Inf 5.3.1, this behaviour changed for Firefox on Android (and possibly other mobile platforms). A long press does not select anything. A rapid double or triple tap will select the current text, but without the handlebars that will allow selection of more or less text. This problem applies to other text fields as well.

### Expected behavior

A long press selects text and invokes handlebars to expand/shrink the selection.

### To Reproduce

Go to `tiddlywiki.com/prerelease` on Firefox Android. Edit a tiddler. Attempting to select text using a long press. You will not be able to select the text in this manner.

### TiddlyWiki Configuration

- Version 5.3.1 prerelease
- Plugins installed: Whatever comes by default at `tiddlywiki.com/prerelease`
- OS: Android 8 ~ 12 -- But might occur with iPhone (don't have a phone to test).
- Browser: Firefox 116.2.0

### Additional context

The title field still behaves as expected. So only test in the text field.

Reference: https://talk.tiddlywiki.org/t/error-in-5-3-1-prerelease-with-android/7785

**Comment by mateuszwilczek** [comment]
Isn’t this simply because the Prerelease uses CodeMirror and the main site not?

The fact that CodeMirror doesn’t play well with mobile text input is known I think. Selecting text in websites other than TW is not optimal in Firefox/Android as well IMO.

However, I have disabled CodeMirror, saved, and uploaded here: https://531-pre-ff.tiddlyhost.com/
I can’t see any real difference on Firefox/Android between this and v5.3.0.

**Comment by Marxsal** [comment]
I'll close, assuming that Tony must be using CM. Can always re-open if it turns out to not be the case.

I'm surprised that the plugin setup between `tiddlywiki.com` and `tiddlywiki.com/prerelease` is so different. I had always assumed they were the same, so we could see exactly what we would be getting in the next version.

**Comment by Marxsal** [comment]
I'll close, assuming that Tony must be using CM. Can always re-open if it turns out to not be the case.

I'm surprised that the plugin setup between `tiddlywiki.com` and `tiddlywiki.com/prerelease` is so different. I had always assumed they were the same, so we could see exactly what we would be getting in the next version.
