### ISSUE TITLE
[BUG] List widget counter-last not updated correctly when items added to list

### ISSUE THREAD

**Issue by rmunn** [Jermolene/TiddlyWiki5#7693]
### Describe the bug

When you use the counter attribute of a list widget, the `<<counter-last>>` value doesn't update correctly as items are added to the list. When a new item is added to the list, its `<<counter-last>>` value is correctly set to "yes", but the item that *used* to be last doesn't get its `<<counter-last>>` value set to "no".

### Expected behavior

The previously-last item should have `<<counter-last>>` set to "no".

### To Reproduce

Create a new tiddler and paste in the following content:

```
Items: <$edit field="items" /> <br/>
<$list filter="[enlist{!!items}]" counter="c" variable="item"><<c>>:<<item>><$text text={{{ [<c-last>match[yes]then[]else[, ]] }}} /></$list>
```

Open the preview pane and slowly type "a b c d e" into the text edit box in the preview (or in the field edit pane, that works too), pausing to watch the list update as you add each new item to the list. Note how there are no commas, because each list item still thinks it's the last item in the list.

Highlight the letter "c" in the text-edit box and change it to "x". Note how items x and d now realize they're not the last item and therefore have commas after them, but "a" and "b" still have no commas because they still think they're the last item.

### TiddlyWiki Configuration

- Version: 5.2.1
- Saving mechanism: any
- Plugins installed: none

### Desktop (please complete the following information):

- OS: any
- Browser: any
- Version: any

### Smartphone (please complete the following information):

- Device: any
- OS: any
- Browser: any
- Version: any

### Additional context

I first encountered this while trying to add a `join` attribute to the list widget, as suggested in https://github.com/Jermolene/TiddlyWiki5/discussions/7674. I re-used the existing logic in `handleListChanges` to process the `join` attribute, adding the join text if the `isLast` property was false on the list item's parse tree node, and omitting it if `isLast` was true. I thought for a while that my logic was wrong until I ran my reproduction on https://tiddlywiki.com/ and found that the bug was in the existing code.

The fix is going to be in the `handleListChanges` code. It currently deletes and re-creates the last item in the list if items were removed from the list (because that particular item used to be not-last and has now become last). But if items are *added* to the list then `handleListChanges` also needs to delete and re-create the item that used to be last and now is not-last, so that its `isLast` property will now correctly be false.

**Comment by Jermolene** [comment]
Thank you @rmunn it would be great to fix this independently of #7674 if we could.
