### ISSUE TITLE
[BUG] [Benign] per HTML spec, textarea does not have type attribute

### ISSUE THREAD

**Issue by CodaCodr** [Jermolene/TiddlyWiki5#7732]
### Describe the bug

`$edit-text` renders `type=text` when `tag=textarea`. There is no such attribute for HTML textarea elements.

### Expected behavior

No type attribute.

### To Reproduce

tiddlywiki.com

![image](https://github.com/Jermolene/TiddlyWiki5/assets/436812/3c403290-ef17-460b-b27a-dad2540cc5f5)

### Screenshots

![image](https://github.com/Jermolene/TiddlyWiki5/assets/436812/9c92beb8-6b0a-40f3-9703-d568e5abfeec)

### TiddlyWiki Configuration

tw .com

**Comment by pmario** [comment]
What's your suggestion? 

IMO it's too late to change it for compatibility reasons. There may be users, which use this info for CSS styling.

**Comment by CodaCodr** [comment]
> What's your suggestion?

What's yours? Neither Close options seem apt.

**Comment by Jermolene** [comment]
Hi @CodaCodr good catch. I agree that this sort of thing is a bit unnerving; like seeing a door handle carefully placed in the middle of a blank wall. I'm pretty sure it can be fixed, and will have a look as soon as I can.
