### ISSUE TITLE
[IDEA] render hooks

### ISSUE THREAD

**Issue by CodaCodr** [Jermolene/TiddlyWiki5#7739]
**Is your feature request related to a problem? Please describe.**
Not a problem, per se...

**Describe the solution you'd like**
Would it be deemed beneficial or, indeed, efficacious, for the core to introduce (more) hooks into the rendered output? I'm imagining something along the lines of `<<on-tiddler-begin-render>>` (and a corresponding on-end call). 

Obviously, _which_ parts of the UI render are exposed to these calls (and the naming of them) would need to be curated with extreme prejudice. Perhaps something like following might be considered:

Tiddler body
```text
<<on-tiddler-body-begin-render>>
<!-- normal {{tiddler!!text}} -->
<<on-tiddler-body-end-render>>
```
Then, notionally, a user might...

```text
\define on-tiddler-body-begin-render()
<$if value={{{ [<currentTiddler>tag[my-tag]] }}}>
  <<display-something-relevant>>
</$if>
\end
```
That's just one example (I don't even have a use for this one :blush: ).

The benefit, I think, is to avoid some CSS chicanery for some of the ostensibly simpler tasks involved in developing/customizing TW UIs.

**Comment by Jermolene** [comment]
Hi @CodaCodr hooks along those lines do exist through the view template mechanism. Rather than redefining macros, one creates tiddlers with tags like `$:/tags/ViewTemplate` and  `$:/tags/ViewTemplate/Body` to insert those tiddlers into the various render lists.

**Comment by CodaCodr** [comment]
I thought you'd say that :)
