### ISSUE TITLE
[BUG] The Vanilla Base Style Tiddler Overwrites User Styles as It Appears at the Bottom of TiddlyWiki Stylesheets 

### ISSUE THREAD

**Issue by kookma** [Jermolene/TiddlyWiki5#7757]
### Describe the bug

This issue has been raised before and has been resolved, but I see it returned again in 5.3.1
The **$:/themes/tiddlywiki/vanilla/base** shall be the first stylesheet to prevent overwriting user styles.

### Expected behavior

$:/themes/tiddlywiki/vanilla/base shall be appeared in very top of the style tiddlers in TiddlyWiki

### Screenshot
From https://tiddlywiki.com/

<img src="https://github.com/Jermolene/TiddlyWiki5/assets/830394/20313930-b8b7-442d-9b06-901aa51e1f36" height="400">

With installed plugins and many styles

<img src="https://github.com/Jermolene/TiddlyWiki5/assets/830394/1159b4b1-1867-4e23-ac9f-22d46a297d74" height="600">

See the place of $:/themes/tiddlywiki/vanilla/base in stylesheet list. 

Note that, the TW instance is created from empty.html or using node.js (create index.html)

### TiddlyWiki Configuration

TW 5.3.1
Windows 11
Edge 117

**Comment by pmario** [comment]
Once the build process is finished, you can have a look at the preview at: **fix 7757 vanilla styles should be first #7758**
