### ISSUE TITLE
[BUG] script for build static in tiddlywiki.info not work as expected

### ISSUE THREAD

**Issue by qaqland** [Jermolene/TiddlyWiki5#7759]
### Describe the bug

I'm using nodejs server edition, it comes with a `tiddlywiki.info` when `--init`

Run the command to build static HTML site:

```shell
$ tiddlywiki . --build static
```

Only get plain text in `output/static/*.html`, the commands in `tiddlywiki.info` is not work

### To Reproduce

```bash
$ tiddlywiki . --init server

# serve and do some edit ==

$ tiddlywiki . --build static
```

HTML files generated in output/static only conains some blank text

### Screenshots

Now(bug)
![image](https://github.com/Jermolene/TiddlyWiki5/assets/62464571/e8fdbf6e-2703-4035-88b7-572c6dd4c845)

Expect
![image](https://github.com/Jermolene/TiddlyWiki5/assets/62464571/ceb184c5-5060-425b-add1-af880f31b6bd)

### TiddlyWiki Configuration

- Version v5.3.0
- Saving mechanism Node.js

### Additional context

commit: https://github.com/Jermolene/TiddlyWiki5/commit/4a6e3d42812b92e0ad54508073e5035c7b9c395a

pr: https://github.com/Jermolene/TiddlyWiki5/pull/7124

in pr's comment, it works "well" because bin/*.sh do not use script here. They still use `RenderTiddler`, here maybe should also change later?

**Comment by qaqland** [comment]
edit to following works well

```
             "--render",
             "[!is[system]]",
             "[encodeuricomponent[]addprefix[static/]addsuffix[tiddler.html]]",
             "text/plain",
             "$:/core/templates/static.tiddler.html",
```

**Comment by qaqland** [comment]
here also need to update: https://tiddlywiki.com/static/Generating%2520Static%2520Sites%2520with%2520TiddlyWiki.html

**Comment by Jermolene** [comment]
Thank you @qaqland
