### ISSUE TITLE
[BUG] Problem with empty transclusions

### ISSUE THREAD

**Issue by AnthonyMuscio** [Jermolene/TiddlyWiki5#7767]
### Describe the bug

In a new tiddler, with preview/output on, Entering something followed by an empty transclusion `{{}}` (not the backticks used here) will generate a loop which appears to transclude the current tiddler text a large number of times.
* "Because the current tiddlers text transcludes the current tiddlers text"?
* A second copy of the same line in the same tiddler may result in a loss of the wiki stored in browser memory with an "Awe Snap" error.
* Something similar can occur when using automatic braces eg `{{` with create the closing pair and if preview output is open trigger this error. Please see the [talk.tiddlywiki discussion](https://talk.tiddlywiki.org/t/curious-and-potentialy-dangerouse-empty-transclusions/8141?u=tw_tones)

### Expected behavior

an empty transclusion would be expected to result in no output because there is no tiddler to transclude.

Previously we may have expected `{{}}` to transclude a tiddler with no title and not work.
* We needed to indicate the currentTiddler was to be used with `{{currenttitle||template}}` or {{||template}}

If you use the below instructions to reproduce but only include `{{}}` and nothing else you will see the red message `Recursive transclusion error in transclude widget `

### To Reproduce

1. Go to '.tiddlywiki.com'
2. add a tiddler
3. type the word something followed by {{}}
4. Close and view or open preview > output

### Screenshots

![Snag_69eaad6](https://github.com/Jermolene/TiddlyWiki5/assets/31584658/4734b410-a42c-46e9-8128-d33b2e047b49)

![Snag_69ebe9d](https://github.com/Jermolene/TiddlyWiki5/assets/31584658/c62bc86d-3609-4524-ae34-7f8a6cec7bec)

### TiddlyWiki Configuration

- Version [v3.5.1]
- Not applicable, Tiddlywiki.com and Empty.html
- Plugins installed as per tiddlywiki.com and empty.html (none)

### Desktop (please complete the following information):

- OS:Windows 11
- Browser FireFox  / Chrome
- Version 118.0.1 (64-bit) / Version 117.0.5938.150 (Official Build) (64-bit)

### Smartphone (please complete the following information):

Not tested

### Additional context

My suspicion is the default content on the shortcut transclude now defaults when empty to "transclude current tiddler"  rather than to an "empty template tiddler title", this is not surprising given the 5.3.x changes.

**Comment by Jermolene** [comment]
Thanks @AnthonyMuscio there's a fix in #7768, I'd appreciate if you could test the preview.

**Comment by AnthonyMuscio** [comment]
Please see comments of mine after testing #7768 partial resolution
