### ISSUE TITLE
[BUG] markdown linkfy error

### ISSUE THREAD

**Issue by oeyoews** [Jermolene/TiddlyWiki5#7786]
### Describe the bug

After upgrading markddown-leagcy to the new markdown plug-in, manually opening linkify will recognize the xxx.md file type as a link on codemirror

### To Reproduce

1. open https://tiddlywiki.com/editions/full website
2. change https://tiddlywiki.com/editions/full/#%24%3A%2Fconfig%2Fmarkdown%2Flinkify config to true
3. save wiki to local
4. open the saved wiki file on browser
5. create markdown tiddler
6. input `xxx.md` and switch editor preview

### Screenshots

<img width="458" alt="image" src="https://github.com/Jermolene/TiddlyWiki5/assets/72405338/1b0d510c-8faa-46d4-9c93-2ea77c0e5f63">

<img width="838" alt="image" src="https://github.com/Jermolene/TiddlyWiki5/assets/72405338/ca214414-fee7-4a7c-ba3b-0938af0538dd">

<img width="778" alt="image" src="https://github.com/Jermolene/TiddlyWiki5/assets/72405338/a504f0ca-7b3a-440a-985e-38a841415dc3">

### TiddlyWiki Configuration

- Version [e.g. v5.1.24]
- Saving mechanism [e.g. Node.js, TiddlyDesktop, TiddlyHost etc]
- Plugins installed [e.g. Freelinks, TiddlyMap]

**Comment by pmario** [comment]
I can **not** reproduce this behaviour with the editions/full version. 

Your configuration section in the report, should list the configuration and not the default text.

**Comment by Jermolene** [comment]
Thanks @oeyoews

> manually opening linkify will recognize the xxx.md file type as a link on codemirror

Can you clarify exactly what you mean? What are the precise steps needed to replicate the problem?
