### ISSUE TITLE
[BUG] - display grid and CodeMirror 5

### ISSUE THREAD

**Issue by BurningTreeC** [Jermolene/TiddlyWiki5#7793]
### Describe the bug

The CodeMirror 5 editor has some problems with the new grid usage

### Expected behavior

That it behaves "correctly" - the editor should take half of the available width

### To Reproduce

1. Go to 'https://tiddlywiki.com/prerelease'
2. Open the tiddler "TiddlyWiki Pre-release" for editing
3. Open the tiddler preview
4. Make the viewport more narrow
5. See that the editor doesn't fit half the width of the space but more

### Screenshots

<img width="969" alt="Screenshot 2023-10-18 174942" src="https://github.com/Jermolene/TiddlyWiki5/assets/9407182/d03213c3-f762-4f97-be7d-ceda9055cc0c">

### TiddlyWiki Configuration

- Version: current prerelease
- Plugins installed: codemirror 5

### Additional context

We could add the following CSS to the codemirror plugin:

```
.CodeMirror-line {
overflow-wrap: anywhere !important;
word-break: normal !important;
}
```

But I haven't yet tested how well it works with the various sub-plugins (autocomplete?)

I'll test

**Comment by BurningTreeC** [comment]
I'll also investigate if there's another way that doesn't force me to use `!important` on cm-internals

**Comment by BurningTreeC** [comment]
Ah 🙂 now I've found a solution. `overflow: auto;` on the CodeMirror container.
Should this solution be added to the vanilla base stylesheet or the codemirror plugin styles?

**Comment by pmario** [comment]
On my system Win11, FF latest it does not look as shown in your screenshot

It looks like this

![image](https://github.com/Jermolene/TiddlyWiki5/assets/374655/46169984-6448-4b24-87e6-9379a11468eb)

**Comment by pmario** [comment]
@BurningTreeC -- Are you sure, that you do not have imported any experiments in the page. Did you try it with SHIFT- reload button, so the cache is refreshed?

**Comment by BurningTreeC** [comment]
Hi @pmario - have you tried making the viewport more narrow?

**Comment by pmario** [comment]
>Hi @pmario - have you tried making the viewport more narrow?

Ahhh -- I see. If browser zoom is high, I can replicate the problem.

**Comment by BurningTreeC** [comment]
Yes @pmario - you can also minimize the browser window and play with its width...

**Comment by pmario** [comment]
Browser zoom and making the window smaller has the same effect.
