### ISSUE TITLE
[BUG] file saving format abnormality

### ISSUE THREAD

**Issue by oeyoews** [Jermolene/TiddlyWiki5#7799]
### Describe the bug

if tiddler field value has whitespace on first char(such as ` xxx`, always generate a json file. maybe need trim this whitespace

### To Reproduce

1. create a new tiddler
2. and create new field, the field's value is ` xxx`(note the first char is whitespace)
3. if save this tiddler, will generate a new json file(nodejs tiddlywiki), not md or tid extension

### Screenshots

![img](https://i.imgur.com/N1XouqC.png)
![img](https://i.imgur.com/aw0sVAP.png)

### TiddlyWiki Configuration

- Version [e.g. v5.1.24]
- Saving mechanism [e.g. Node.js, TiddlyDesktop, TiddlyHost etc]
- Plugins installed [e.g. Freelinks, TiddlyMap]

**Comment by Jermolene** [comment]
Hi @oeyoews that is the expected behaviour. Trimming a field without the user explicitly initiating the action violates a basic principle of the software: you always get back exactly what you put in.

**Comment by pmario** [comment]
>Is this also a field problem?

I think chances are high. Where are the source files?

**Comment by oeyoews** [comment]
https://oeyoews.github.io/tiddlywiki-codemirror6/#%24%3A%2Fplugins%2FBTC%2Ftiddlywiki-codemirror-6  When I import this json file to replace the previous codemirror-6 plug-in, this will happen.

**Comment by pmario** [comment]
![image](https://github.com/Jermolene/TiddlyWiki5/assets/374655/e0b67ab2-98cc-4350-9389-cf1e05b40ade)

**Comment by pmario** [comment]
As soon as there are upper-case characters the tiddler will be split into .json and .meta files.

**Comment by oeyoews** [comment]
No, I used the plugin json file built by moderndev instead of the BTC plugin file. The meta file disappeared. Maybe it was this special field `Modern.TiddlyDevxxx` that caused all the meta information to be placed in the json file, like The above md md.meta will all become json files when encountering non-standard fields.

**Comment by pmario** [comment]
@oeyoews -- Have a look at: https://github.com/Jermolene/TiddlyWiki5/issues/7808#issuecomment-1777556942 -- It's the `#` character that causes the problem.
