### ISSUE TITLE
[IDEA] It's requested to keep 1 .tid file per tiddler, if field-names violate v5.1.x rules

### ISSUE THREAD

**Issue by pmario** [Jermolene/TiddlyWiki5#7808]
Related to: **[BUG] file saving format abnormality** - #7799 

@Jermolene -- I think the restrictions to field-names did come from the "old v5.1.x wikistore" -- right? 

I think since we do have SCRIPT tags now, that contain a JSON structure, we could stop to convert tiddlers into JSON files if the **field name** violates the "old" rules. 

--- 

We are still forced to convert a `.tid` file into a `.json` file if the field-value contains multi-line content.

**Comment by pmario** [comment]
@Jermolene -- I had to change the OP text a little bit because I did confuse "convert to JSON" with "convert to .txt and txt.meta" rules

**Comment by Jermolene** [comment]
Hi @pmario the discussion at #7799 is about the filesystemadaptor saving `.tid` files. It is not affected by the use of script tags with the new JSON store area.

**Comment by pmario** [comment]
I know. But the main reason for changing .tid files to .JSON files was the problem of the "save and reload" round-trip using HTML attributes to store **field-names**. Now since we do not have the old-store mechanism anymore, there is no need to ever transit from .tid file to .json except if there are multi-line values in fields. 

My request is to remove the automatic transition from .tid to .json, just because the **filed-name** contains invalid characters.

**Comment by Jermolene** [comment]
Hi @pmario again, this is nothing to do with round-tripping fields to HTML attributes. There is entirely separate code to check for tiddlers that cannot be saved in a `.tid` file:

https://github.com/Jermolene/TiddlyWiki5/blob/4ebaba8e89b93cc94cb96661286a1a92ab6ebfb9/core/modules/utils/filesystem.js#L225-L232

As you can see, the conditions that trigger not being able to use a `.tid` file are:

* Any field name includes a control character from 0x00 to 0x1f
* Any field name starts or ends with whitespace
* Any field name includes the characters `:` or `#`
