### ISSUE TITLE
Add ability to export binary tiddlers, including images

### ISSUE THREAD

**Issue by tlwt** [Jermolene/TiddlyWiki5#781]
It seems to be impossible to access binary data stored in TW5. I get only the message mentioned before without any chance to download it.

**Comment by r1chard5mith** [comment]
I'd like to be able to do this - download individual binary tiddlers (in order to make a manual image externaliser). Most of the export functionality seems to have been added since this ticket was opened and I suspect it may already be possible to do?

**Comment by tlwt** [comment]
Hi @Jermolene, any news on this feature request? I would love to see it being scheduled for a milestone.

**Comment by Jermolene** [comment]
Hi @tlwt apologies for the late reply. I'm afraid that this is just one of those things that I've not got to myself. There's a few fiddly changes to get this running, but I'm happy to be reminded again once I've got 5.1.10 released!

**Comment by tlwt** [comment]
Hi @Jermolene, release is done (I already migrated to it). Here comes the reminder ;-)

**Comment by Jermolene** [comment]
I've done some exploration. Sadly, there's quite a few changes we need:

* Updates to the saver interface and all of the saver implementations to support saving binary files as well as the current support for saving text files
* Add a new `tm-download-tiddler` message that actually downloads the raw text of a tiddler
* Add a new view toolbar button to download the current tiddler

**Comment by Jermolene** [comment]
Fixed in #4423
