### ISSUE TITLE
[BUG] Running unit tests is slow now

### ISSUE THREAD

**Issue by rmunn** [Jermolene/TiddlyWiki5#7828]
### Describe the bug

The TW unit tests in CI, which run every time you push to a PR branch used to be fast, finishing in less than 10 seconds. Now that Playwright has been added, they take much longer: https://github.com/Jermolene/TiddlyWiki5/actions/runs/6717219522/job/18254693717?pr=7827 took over a minute to fail. If the `ci-test.sh` script were swapped to run `node ./tiddlywiki.js ./editions/test` first, and then do the `npm install playwright` and `npx playwright install` tests only later, then the CI test runs could finish fast when there's a test that fails under Node.js, and not have to go through the steps of downloading and installing Playwright dependencies. That way when a PR is in progress and still has failing tests, the submitter can get feedback in seconds instead of waiting over a minute to see the failure.

### Expected behavior

Failing tests fail fast, and only successful test runs under Node.js go through the process of downloading Playwright dependencies, installing browsers, and running the Playwright tests.

### To Reproduce

Rather than a reproduction, a suggested fix: move the `npm install playwright` and `npx playwright install` lines further down in the `ci-test.sh` script.

### TiddlyWiki Configuration

Not relevant

### Additional context

An alternative solution, that would involve more work, would be to split the ci.yml workflow into two steps: one that runs tests under Node.js, and a separate one that runs them in the browser. The default Github Actions config is to fail fast, so that if one step fails, any other still-running steps are cancelled. The advantage this would give is that *successful* tests would also show up fast: the "run tests under Node.js" check would show up in seconds, while the "run tests under Playwright" check would take a little bit longer — but the PR author would immediately have some confidence that the Playwright tests would, almost certainly, pass as well.

**Comment by pmario** [comment]
I usually run `tiddlywiki ./editions/test --build` if I need a fast check if the tests pass. -- Just a thought. 

We could add `npm run test` to `package.json`

**Comment by Jermolene** [comment]
Hi @rmunn would it be possible to run the Node.js and browser tests in parallel, but have the Node.js test results reported as soon as they are completed?

**Comment by rmunn** [comment]
Yes, it would. It'll be more work, but it's totally doable. (It's essentially what I mentioned in the "Additional context" section). I'd suggest merging #7829 in the meantime, as that will not prevent me from working on the parallel approach, but the parallel approach may take me several days whereas #7829 is ready now.
