### ISSUE TITLE
[BUG] 5.3.1 Actions attribute of tag-picker macro does not support nested procs (variables)

### ISSUE THREAD

**Issue by CodaCodr** [Jermolene/TiddlyWiki5#7853]
### Describe the bug

Please see https://talk.tiddlywiki.org/t/actions-attribute-of-tag-picker-macro-does-not-support-nested-procs-variables/8518

**Comment by CodaCodr** [comment]
Tests conducted at tiddlywiki.com

https://talk.tiddlywiki.org/t/actions-attribute-of-tag-picker-macro-does-not-support-nested-procs-variables/8518/4?u=codacoder

**Comment by pmario** [comment]
Just a reminder to avoid collisions: There is a pending PR **Fix and extend tag picker functions #7548** which also modifies the tag-picker macros.

**Comment by CodaCodr** [comment]
@Jermolene Sorry about that -- I mean, it's not like I don't know 🙄 

```
  \procedure update()
    <$action-setfield $field=coda $value=<<tag>> />
  \end update

\procedure tag-actions()
<<update>>
\end tag-actions

<$transclude $variable=tag-picker tagField="my-tags" actions=<<tag-actions>> />
```

Just put the `update` macro inside the `tag-actions` macro.

**Comment by CodaCodr** [comment]
Fixed published at https://github.com/Jermolene/TiddlyWiki5/pull/7855
