### ISSUE TITLE
[BUG] enlist cannot be used with `--commands` because removes duplicated entries, documentation

### ISSUE THREAD

**Issue by carlo-colombo** [Jermolene/TiddlyWiki5#7857]
### Describe the bug

Tryting to read commands from a tiddler to pass to the `--commands` command I noticed that it skips to return one of the e `--render`.  The documentation suggests to use `enlist` https://tiddlywiki.com/#CommandsCommand

### Expected behavior

If this is the expected behaviour of `enlist` it should be removed from the documentation as it's common to have multiple `--renders` or templates in a list of commands to generate static files.

### To Reproduce

Given an `example-tiddler` tiddler with content `–verbose cool –verbose –render cool cool` a filter `[elist{example-tiddler}]` only returns the first occurence of each duplicate `--verbose cool --render`.

### Screenshots

![Screenshot_20231126_111316](https://github.com/Jermolene/TiddlyWiki5/assets/505826/07b13ece-80d6-4de6-bea1-dd91ff489a78)

### TiddlyWiki Configuration

- Version [e.g. v5.3.1]

### Additional context

`splitregexp[\n]` seems to be a viable alternative to splits tokens from a tiddler with each command on a new line. `split[ ]` would only work for all the commands on a single line but also would split ``[[valid tiddlers]]`` that include a space

**Comment by saqimtiaz** [comment]
thank you @carlo-colombo, I have created a PR with a proposed fix in #7858

**Comment by carlo-colombo** [comment]
Thank you! I am not sure I how miss the `raw` suffix.
