### ISSUE TITLE
[BUG]: 5.3.2-prerelease tiddlywiki cli will not automatically exit after the build is completed.

### ISSUE THREAD

**Issue by oeyoews** [Jermolene/TiddlyWiki5#7867]
### Describe the bug

Using the latest 5.3.2-prelease tiddlywiki, the tiddlywiki cli will not automatically exit after the build is completed.

### Expected behavior

Automatically end

### To Reproduce

https://github.com/oeyoews/build-bug-tiddlywiki 
I made a minimal reproduction repo(use forked TiddlyWiki5 repo)

### Screenshots

![image](https://github.com/Jermolene/TiddlyWiki5/assets/72405338/c65b352d-a564-4635-a0c3-8e8ebecbbb3e)

### TiddlyWiki Configuration

- Version 5.3.2-prelease latest
- Saving mechanism NodeJs
- Plugins installed

### Desktop (please complete the following information):

- OS: Windows11

### Additional context

https://github.com/Jermolene/TiddlyWiki5/commit/4c2979286b6836f4331b31649e3d17b7b074ca6f I encountered this problem after upgrading from this commit, and looked at the commits in between, https://github.com/Jermolene/TiddlyWiki5/commit/d1c7f79dd2c138afeb6527236a3fcca23b4a1cf3 this commit It seems to be related, but this is just a plugin

**Comment by oeyoews** [comment]
Is process.exit(0) missing somewhere? @Jermolene

**Comment by oeyoews** [comment]
https://github.com/Jermolene/TiddlyWiki5/commit/ca41a8db047b67ccc2c0a2192bc0176448a30e02 I checked this commit by testing on codesanbox

**Comment by Jermolene** [comment]
Great thank you @oeyoews that's very helpful. Fix coming up.

**Comment by Jermolene** [comment]
Let me know if the fix works for you.

**Comment by oeyoews** [comment]
the fix works
