### ISSUE TITLE
[BUG] The \parameter stuff in SVG tiddlers is breaking old plugins

### ISSUE THREAD

**Issue by flibbles** [Jermolene/TiddlyWiki5#7871]
### Describe the bug

In PR #7413, all of the SVG icons were switched from being pure SVG to having tiddlywiki specific stuff like `\parameters` and such to control their size through transclusion. This broke some features in TiddlyMap, which was depending on those images being pure images (issue https://github.com/felixhayashi/TW5-TiddlyMap/issues/218).

This may be breaking other plugins too. TiddlyMap is just the one I'm getting bug reports for.

I know it seems nifty to be able to adjust the size of those SVG tiddlers when you transclude them. It might even save a few keystrokes, but should we really sacrifice their SVG quality to do this? Maybe their size is better adjusted through css and classes. I couldn't find a single instance in core where that size parameter is actually used (though I didn't look super hard).

### TiddlyWiki Configuration

TiddlyWiki V5.3.0 and up

**Comment by pmario** [comment]
@flibbles -- I think you need to mention @Jermolene for faster reactions.

**Comment by flibbles** [comment]
All right. You guys win. I flinched. I made TiddlyMap cope with this problem instead. Though I'll point out that the issue addressed in https://github.com/Jermolene/TiddlyWiki5/pull/8203 made coping with this problem kind of a chore.

I'll close this one out.

**Comment by joshuafontany** [comment]
I'm very busy with other things, but very impressed with how you are maintaining this plug-in. Mahalo (thanks) @flibbles .
