### ISSUE TITLE
[Review] Just finished to review _all_ open issues - _all_ of them \o/

### ISSUE THREAD

**Issue by pmario** [Jermolene/TiddlyWiki5#7881]
Just a marker -- Just finished to review _all_ open issues - _all_ of them. 

Many "old" issues could be resolved, because they where implemented in one way or the other \o/

**Comment by pmario** [comment]
Just a marker to find it. -> Close ;)

**Comment by Jermolene** [comment]
Thanks @pmario that was a tour de force, much appreciated.

**Comment by CodaCodr** [comment]
Yes, truly admirable @pmario. 🥇
