### ISSUE TITLE
[BUG] v5.3.2 the class attribute for SelectWidget does not take effect

### ISSUE THREAD

**Issue by yuzijie** [Jermolene/TiddlyWiki5#7890]
### Describe the bug

New version introduced bug in SelectWidget
Class attribute cannot be added to the select tag

### TiddlyWiki Configuration

- Version v5.2.3
- Saving mechanism Node.js
- Plugins installed No

### Desktop (please complete the following information):

- OS: Windows
- Browser Edge
- Version 120.0

**Comment by saqimtiaz** [comment]
Thank you for the bug report @yuzijie

The select widget needed to be refactored in the last release and a small typo has crept in:

https://github.com/Jermolene/TiddlyWiki5/blob/62bb8affa48aec958fc73104b060f6a90efc8e1b/core/modules/widgets/select.js#L46
