### ISSUE TITLE
[BUG] Preview broken when `$:/config/ShowEditPreview/PerTiddler` is set to `yes`

### ISSUE THREAD

**Issue by yaisog** [Jermolene/TiddlyWiki5#7893]
### Describe the bug

Previews don't work when the above setting is active.
This is likely related to #7747. The `qualify` macro results are not correct now that is has been moved into `$:/core/ui/EditorToolbar/preview`, so the wrong state tiddler is set.

### To Reproduce

1. Go to tiddlywiki.com
2. Enable the per-tiddler preview state
3. Edit a tiddler and turn on preview

### TiddlyWiki Configuration

v5.3.2

**Comment by Jermolene** [comment]
Thanks @yaisog – would you be able to have a look at this @BurningTreeC?

**Comment by AnthonyMuscio** [comment]
Possibly related to this is when the above is set to no or deleted, the preview works, however with both the "widget Tree Preview" and "Raw HTML" preview you can't see the edit panel and the previews are full width.
* I think there is a bug in the flex box, or columns for different screen sizes.

I am glad to know this bug exits, but it is quite substantial, so can we post about in talk.tiddlywiki and if possible, provide a temporary patch?
* Any tips?, I will create a simple patch
* I am just trying to evaluate [$:/core/ui/EditorToolbar/preview](https://tiddlywiki.com/#%24%3A%2Fcore%2Fui%2FEditorToolbar%2Fpreview) and `:else[<qualify "$:/state/showeditpreview">]`

I wasted hours going crazy by working on a set of advanced previews and thought I was going crazy with all sorts of weird behaviours not knowing it was not me, it was tiddlywiki.

Just now I noticed another bug;
* Open $:/core/ui/EditorToolbar/preview
* Open the preview and select RAW Html
* Resize the browser window to get the preview along side the editor
* I get the result below in FireFox , the preview is an HTML version of a SVG not the HTML of the content in the editor.

![Snag_1ddca396](https://github.com/Jermolene/TiddlyWiki5/assets/31584658/5c122eca-6ba8-4995-95ab-1c45d5b73c85)

**Comment by pmario** [comment]
@yaisog -- IMO we can close this one. The PR has been merged

**Comment by AnthonyMuscio** [comment]
> Possibly related to this is when the above is set to no or deleted, the preview works, however with both the "widget Tree Preview" and "Raw HTML" preview you can't see the edit panel and the previews are full width.

I can confirm the full screen and column issues are now resolved ion the pre-release, I can also see, given the tiddler was a button the html does naturally resolve to an SVG
