### ISSUE TITLE
[BUG] TW 5.3.2 shows empty page when lazy-loading images

### ISSUE THREAD

**Issue by mschwld** [Jermolene/TiddlyWiki5#7896]
### Describe the bug

Since version 5.3.2, starting Tiddlywiki using node.js (https://tiddlywiki.com/#Using%20TiddlyWiki%20on%20Node.js) and lazy-loading for images (https://tiddlywiki.com/#LazyLoading), it won't finish loading and show a blank page instead. The Wiki must contain an image subject to lazy-loading. There are no errors visible to me in the console.

### Expected behavior

The applications loads to a point where you can use it.

### To Reproduce

1. Get the empty version for 5.3.2 at https://tiddlywiki.com/#GettingStarted
2. Convert it for usage with node.js: `tiddlywiki --load empty.html --savewikifolder ./out`
3. Enter the folder: `cd out`
4. Start a server with lazy-loading for images: `tiddlywiki +plugins/tiddlywiki/filesystem +plugins/tiddlywiki/tiddlyweb --listen root-tiddler=$:/core/save/lazy-images`
5. See a working application on `http://localhost:8080`
6. Import any image
7. Stop the server, start it again
8. Point your browser to `http://localhost:8080`
9. See a blank page instead of the application

### TiddlyWiki Configuration

- Version: 5.3.2
- Saving mechanism: Node.js
- Plugins installed: filesystem, tiddlyweb

### Desktop

- OS: Debian
- Browser:  Chromium
- Browser Version: 120.0.6099.71

**Comment by Jermolene** [comment]
Hi @mschwld thank you for the report, I am investigating now.

**Comment by Jermolene** [comment]
This turns out to be a bug in #7694. I'll post a putative fix in a moment.

**Comment by Jermolene** [comment]
Hi @mschwld the fix is in #7897, let me know if you're able to verify that those changes fix things for you

**Comment by mschwld** [comment]
Hi @Jermolene, I checked out `fix-saving-skinny-tiddlers` and tested the fix for the empty version from tiddlywiki.com as well with one of my personal wikis, each time using: `node ./tiddlywiki.js +plugins/tiddlywiki/filesystem +plugins/tiddlywiki/tiddlyweb /path/to/a/wiki/ --listen root-tiddler=$:/core/save/lazy-images
`. Everything looks good  to me now, the application loads as it should and images show up when requested. Thank you very much for the quick response and solution! :thumbsup: :blush:
