### ISSUE TITLE
[DOCUMENTATION] AlphaReleases creates itself in the tabs macro

### ISSUE THREAD

**Issue by justin-hurd** [Jermolene/TiddlyWiki5#7899]
### Describe the bug

The current code used for the AlphaReleases tiddler creates several vertical tabs, including itself and it's draft.of counterpart, creating an infinite tabs effect, using the following macro:

`<<tabs "[tag[AlphaReleaseNotes]!sort[created]]" "Release 5.0.1-alpha" "$:/state/tab2" "tc-vertical" "ReleaseTemplate">>`

### Expected behavior

Excluding the tiddler from within the filter of the tabs macro fixes this.

`<<tabs "[!has[draft.of]tag[AlphaReleaseNotes]!title[AlphaReleases]!sort[created]]" "Release 5.0.1-alpha" "$:/state/tab2" "tc-vertical" "ReleaseTemplate">>`

### To Reproduce

1. Go to 'https://tiddlywiki.com/#AlphaReleases'
2. Click on 'Edit'
3. Scroll down to the tabs macro

### TiddlyWiki Configuration

- Version: v5.3.1
- Saving mechanism: N/A
- Plugins installed: N/A

- OS: Windows 11 Pro for Workstations
- Browser: Microsoft Edge
- Version: 120.0.2210.77

### Additional context

I imagine documentation changes like this would be fixed a different way on github, but I don't yet know how to do something like that, but felt not saying anything wouldn't be much better.

**Comment by pmario** [comment]
Good catch. I did create a PR:  fix #7899 recursive "release" tabs problem #7901

**Comment by Jermolene** [comment]
Thank you @justin-hurd much appreciated

**Comment by justin-hurd** [comment]
Happy to help 😁
