### ISSUE TITLE
Planning for v5.3.3 bug fix release

### ISSUE THREAD

**Issue by Jermolene** [Jermolene/TiddlyWiki5#7904]
We have now found five bugs that were introduced in v5.3.2. None of them are showstoppers, but they have all caused end users significant headaches. Therefore, I propose to release v5.3.3 as a bug fix release in the next few days.

The bugs that already have PRs:

* #7895
* #7897
* #7900
* #7903
* #7905

Please let me know if there are any other regressions introduced in v5.3.2 that need to be investigated.

**Comment by saqimtiaz** [comment]
I will create a PR for #7890 and #7887 tomorrow, both have to do with the select widget.

**Comment by Jermolene** [comment]
Thanks @saqimtiaz

**Comment by CodaCodr** [comment]
Just to confirm #7887 is fixed in this release.

**Comment by Jermolene** [comment]
Thanks @saqimtiaz @CodaCodr closing this as v5.3.3 is now released
