### ISSUE TITLE
[BUG] Filters don't use the variables set by filter run prefixes

### ISSUE THREAD

**Issue by yaisog** [Jermolene/TiddlyWiki5#7907]
### Describe the bug

If I have a tiddler with the fields

* title: Idiosyncrasy
* caption: Idiosyncrasy Caption Field

Then this code
```
\define demo-subfilter() [<currentTiddler>]
\function .demo-function() [<currentTiddler>]

{{{ [<currentTiddler>get[caption]!is[blank]else<currentTiddler>] :map[subfilter<demo-subfilter>] }}}

{{{ [<currentTiddler>get[caption]!is[blank]else<currentTiddler>] :map[.demo-function[]] }}}
```
will produce this output

> *Idiosyncrasy Caption Field*
> Idiosyncrasy

Now I thought that the `:map` filter run prefix will set `currentTiddler` inside the run to the currently processed input title, which in this case should be the caption field of the tiddler. This then is the output of the subfilter. However, the filter function outputs the title, which is the value of the `currentTiddler` variable outside the `:map` run, not inside where the filter function is called.

See [this discussion](https://talk.tiddlywiki.org/t/function-idiosyncrasy-bug-or-feature/8745) on TWTalk.

@saqimtiaz already provided a preliminary fix in #7906. 

### Expected behavior

Functions should use the variables set by filter run prefixes.

### To Reproduce

See this [Sharing Edition TW](https://tiddlywiki.com/share##%5B%7B%22title%22%3A%22%24%3A%2Fstate%2Fhttp-requests%22%2C%22text%22%3A%220%22%7D%2C%7B%22title%22%3A%22%24%3A%2FStoryList%22%2C%22created%22%3A%2220231224083913008%22%2C%22text%22%3A%22%22%2C%22list%22%3A%22Idiosyncrasy%22%2C%22modified%22%3A%2220231224083934208%22%7D%2C%7B%22created%22%3A%2220231224083214715%22%2C%22text%22%3A%22%5C%5Cdefine%20demo-subfilter%28%29%20%5B%3CcurrentTiddler%3E%5D%5Cn%5C%5Cfunction%20.demo-function%28%29%20%5B%3CcurrentTiddler%3E%5D%5Cn%5Cn%7B%7B%7B%20%5B%3CcurrentTiddler%3Eget%5Bcaption%5D%21is%5Bblank%5Delse%3CcurrentTiddler%3E%5D%20%3Amap%5Bsubfilter%3Cdemo-subfilter%3E%5D%20%7D%7D%7D%5Cn%5Cn%7B%7B%7B%20%5B%3CcurrentTiddler%3Eget%5Bcaption%5D%21is%5Bblank%5Delse%3CcurrentTiddler%3E%5D%20%3Amap%5B.demo-function%5B%5D%5D%20%7D%7D%7D%5Cn%5CnCode%20for%20the%20above%20output%20is%5Cn%5Cn%60%60%60%5Cn%5C%5Cdefine%20demo-subfilter%28%29%20%5B%3CcurrentTiddler%3E%5D%5Cn%5C%5Cfunction%20.demo-function%28%29%20%5B%3CcurrentTiddler%3E%5D%5Cn%5Cn%7B%7B%7B%20%5B%3CcurrentTiddler%3Eget%5Bcaption%5D%21is%5Bblank%5Delse%3CcurrentTiddler%3E%5D%20%3Amap%5Bsubfilter%3Cdemo-subfilter%3E%5D%20%7D%7D%7D%5Cn%5Cn%7B%7B%7B%20%5B%3CcurrentTiddler%3Eget%5Bcaption%5D%21is%5Bblank%5Delse%3CcurrentTiddler%3E%5D%20%3Amap%5B.demo-function%5B%5D%5D%20%7D%7D%7D%5Cn%60%60%60%5Cn%22%2C%22tags%22%3A%22%22%2C%22title%22%3A%22Idiosyncrasy%22%2C%22modified%22%3A%2220231224083757929%22%2C%22caption%22%3A%22Idiosyncrasy%20Caption%20Field%22%7D%5D)

### TiddlyWiki Configuration

TW v5.3.3

**Comment by pmario** [comment]
@yaisog -- There is a draft-PR ready for testing
