### ISSUE TITLE
[BUG] Allow permissable whitespace in style elements

### ISSUE THREAD

**Issue by CodaCodr** [Jermolene/TiddlyWiki5#7912]
### Describe the bug

`<style>` elements that appear in wikitext should allow (i.e. parse) whitespace where in HTML whitespace is allowed.

### To Reproduce

tw .com

```
<red>
This is red.
</red>

<style>

red { color:red; }
</style>
```
Note the empty line following `<style>`

### Screenshots

![image](https://github.com/Jermolene/TiddlyWiki5/assets/436812/ec75b593-6ec7-4da7-8103-f3601d619ea7)

### TiddlyWiki Configuration

5.3.3

### Additional context

I assume this is low-hanging fruit... it's been a bug for a long time.

**Comment by pmario** [comment]
For simple inline styles we do have a wikitext syntax. There should be no need for specialized STYLE tag handling.

See: [Styles and Classes in WikiText](https://tiddlywiki.com/#Styles%20and%20Classes%20in%20WikiText) -- The following code should do the trick without the need for a RED-tag

```
@@color:red; This is red.@@
```

For more complex styling needs we should use [Stylesheets](https://tiddlywiki.com/#Using%20Stylesheets), which do have a lot more possibilities.

**Comment by CodaCodr** [comment]
@pmario. Please climb down. I'm not a noob. This is not Talk. This is not a support request. It's not about inline-style, it's not about color:red.

This is a bug report about whitespace handling, like the topic title says. It's a tiny bug, true, but a bug nonetheless.

**Comment by Jermolene** [comment]
Hi @CodaCodr one could argue whether this is a bug. It is how TW5 has always behaved. The core docs don't mention or recommend using the inline `<style>` element.

The background is that a single parser component handles HTML elements like `<style>` and widgets like `<$list>`. It handles all elements/widgets consistently. The OP is asking that the parser recognise the `<style>` element and handle it differently by switching the parser mode such that it doesn't recognise wikitext within the element.

One issue with that approach would be that it is actually quite useful to be able to use wikitext to generate style definitions, and we'd lose that ability.

But my deeper concern is that it would introduce an inconsistency into the way that parsing is performed. Granted, HTML parsers behave in that way, but we're not trying to reproduce HTML here; HTML has incredibly complex parsing rules that few people understand, and so the goal for TW5 is to have simpler parsing rules that are easier to understand.

**Comment by CodaCodr** [comment]
Thanks @Jermolene 

> It handles all elements/widgets consistently. [...] it is actually quite useful to be able to use wikitext to generate style definitions, and we'd lose that ability.

Nuff said. Closing...
