### ISSUE TITLE
Introduce wikilink blacklist

### ISSUE THREAD

**Issue by Jermolene** [Jermolene/TiddlyWiki5#792]
It would be useful to be able to disable automatic wikilinking to specified tiddlers.

Discussion here:

https://groups.google.com/d/topic/tiddlywiki/vWCVIR3HXcw/discussion

This can't be done at the parsing level because the results of parsing a given tiddler needs to be independent of the state of any other tiddlers in order for our caching strategy to work. So, we need to modify the `<$link>` widget to create a `<span>` for disabled links.

**Comment by ght** [comment]
After >6 years without activity on this feature request, I guess it's fair to say that there is no longer any interest and this can probably be closed.

**Comment by Jermolene** [comment]
Thanks @ght
