### ISSUE TITLE
[BUG] Markdown Tiddler not support past/drop image, just text/vnd.tiddlywiki  tiddler support 

### ISSUE THREAD

**Issue by oeyoews** [Jermolene/TiddlyWiki5#7924]
### Describe the bug

markdown Tiddler not support past/drop image, just text/vnd.tiddlywiki  tiddler support 

### Expected behavior

like text/vnd.tiddlywiki tiddler, support paste image

### To Reproduce

Create new markdown tiddler on https://tiddlywiki.com/editions/full/, paste or drop image to editor

### TiddlyWiki Configuration

- Version [e.g. v5.1.24]
- Saving mechanism [e.g. Node.js, TiddlyDesktop, TiddlyHost etc]
- Plugins installed [e.g. Freelinks, TiddlyMap]

**Comment by saqimtiaz** [comment]
This is user configurable, see https://tiddlywiki.com/#Hidden%20Setting%3A%20Enable%20File%20Import%20in%20Editor

However, to get this to work in markdown tiddlers you will also need to clone and adapt `$:/core/ui/EditorToolbar/file-import` for markdown tiddlers and syntax, namely the replacement text and the condition field.
