### ISSUE TITLE
[BUG] Safari data loss from unexpected delete text behaviour

### ISSUE THREAD

**Issue by makiaea** [Jermolene/TiddlyWiki5#7942]
### Describe the bug

data loss: unselected text is silently deleted unintentionally

all current ios apps e.g. quine exhibit this issue so all ios users affected with no recourse or workaround

seems to affect all mac/ios, may be a longstanding undiscovered bug as previous versions of mac os also have this error (only occurs with safari and tiddlywiki, not other browsers)

this may because it is difficult to discover since the tiddler need to have been saved once before this bug kicks in

### Expected behavior

only the selected text is deleted

### To Reproduce

when selecting a PORTION of a line,
AND the preceding linebreak
(not sure if needs the blank line, please see gif)

and then using the backspace key,
the **_whole paragraph_** is deleted (i.e. unselected text is deleted), rather than just the selection

NB tiddler has to have been saved at least once

details:

copy the text of “GettingStarted” from [tiddlywiki.com](http://tiddlywiki.com/) and create a new tiddler in a freshly downloaded empty.html opened using safari

SAVE the tiddler (not the tiddlywiki): if you try this in the new tiddler before the tiddler is saved, it does not occur (yet)

select and delete the partial line + empty preceding line

notice the rest of the paragraph silently disappears, even though it is not selected for deletion

### Screenshots

![IMG_0062](https://github.com/Jermolene/TiddlyWiki5/assets/228018/4c644a36-4917-4dab-b349-32384fbce46c)

### TiddlyWiki Configuration

- Version v5.2.2, 5.2.1 many previous
- Saving mechanism: browser, rclone serve, quine (possibly any/not relevant)
- Plugins installed: none necessary, even fresh empty tiddlywiki affected

### Desktop (please complete the following information):

- OS: macos
- Browser: safari
- Version: 14.2, 14.2.1 all current versions and many previous

### Smartphone (please complete the following information):

- Device: iphone 15 pro, iphone x; jeremy also tested ipados
- OS: 17.2.1, 17.2, many previous
- Browser: safari and quine (safari based)
- Version: latest and many previous

### Additional context

this does not occur in firefox (mac) but ios users have no alternative to safari/quine so they are losing data

is the deletion code passing something that safari uniquely cannot handle? or misinterprets as “delete paragraph”?

why does the tiddler need to have been saved once before this bug kicks in?

https://talk.tiddlywiki.org/t/safari-unexpected-delete-text-behaviour-v5-3-2-5-3-1

**Comment by Jermolene** [comment]
Hi @makiaea thank you for the report. This is a frustrating problem.

As I said [over on your thread at Talk](https://talk.tiddlywiki.org/t/safari-unexpected-delete-text-behaviour-v5-3-2-5-3-1/8732/3), the really strange thing is that the problem only occurs for me with https://tiddlywiki.com/ and not https://tiddlywiki.com/empty.html

It would be very helpful to try to narrow down what components of tiddlywiki.com cause the problem. It should be possible to experiment with an empty wiki, gradually adding the content from tiddlywiki.com until the problem occurs.

**Comment by makiaea** [comment]
hi @Jermolene does the problem not occur with empty.html after the new tiddler has been saved once?

if the tiddler has not been saved once it does not appear to occur for me either

i.e. newly created tiddlers do not initially show this problem

**Comment by makiaea** [comment]
hi @Jermolene i've done a bit more testing and this bug occurs reliably with the GettingStarted tiddler content, if in its original tiddler or when copied (and saved) into a new tiddler

in some good news, this error does not appear to occur in safari technology preview
Release 186 (Safari 17.4, WebKit 19618.1.10.1.1)

**Comment by makiaea** [comment]
i tried updating to developer betas, but unfortunately
lastest sonoma 14.3 developer beta, with
Safari Version 17.3 (19617.2.4.11.8) still shows the error

latest ios 17.3 developer beta also shows the error

here's hoping (march?) ios/ipados 17.4 will bring safari 17.4 (same as in safari technology preview release 186, with webkit 19618, which seems to work) and it will fix this!


i had a quick search to see if i could identify the relevant change:
186 release notes: https://webkit.org/blog/14916/release-notes-for-safari-technology-preview-186/

includes webkit changes: https://github.com/WebKit/WebKit/compare/7b65ded5da4652028c62f0958983f84d38e753f8...dcca261c751d3a4af2154720f3f6cb43f9c47ac1

poss unrelated but could have fixed it: https://commits.webkit.org/272233@main

**Comment by makiaea** [comment]
seems like a webkit issue that could possibly be fixed by march 2024 in safari 17.4 using webkit 19618

**Comment by Jermolene** [comment]
Thanks @makiaea – I keep my iPad on the developer beta, so I'll try 17.4 when it's available.
