### ISSUE TITLE
[BUG] Upgrade to 5.3.3 made internal links to appear twice

### ISSUE THREAD

**Issue by oricou** [Jermolene/TiddlyWiki5#7946]
### Describe the bug

`[[Test]]` upgraded now display Test[Test](Test)

I have the same behavior with my browsers (Chromium or Firefox) or TiddlyWiki Desktop 0.18.

### Expected behavior

`[[Test]]` should display [Test](Test)

### To Reproduce

Get https://ricou.eu.org/iren/notes_rn.html and update it with https://tiddlywiki.com/upgrade.html

### Screenshots

![tiddlywiki_upgrade_bug](https://github.com/Jermolene/TiddlyWiki5/assets/7228177/1dcc0d19-ab04-49d7-ac81-0a99a4f48c35)

### TiddlyWiki Configuration

From 5.1.16 to 5.3.3

**Comment by saqimtiaz** [comment]
I would recommend updating the uni-link plugin after the upgrade: https://wikilabs.github.io/#%24%3A%2Fplugins%2Fwikilabs%2Funi-link

**Comment by pmario** [comment]
@oricou If this issue is resolved, please close it. If not let us know

**Comment by oricou** [comment]
Sorry for the delay. It works. Thanks.
