### ISSUE TITLE
[BUG] CSS for links works partially

### ISSUE THREAD

**Issue by oricou** [Jermolene/TiddlyWiki5#7958]
### Describe the bug

Style for links does not work as I expected. Here is my style tiddler:

```
.tc-tiddlylink {
    color: red;
    text-decoration:underline;
    background-color: gray;
}

.tc-tiddlylink-external {
    color: green;
    text-decoration:none;
    background-color: yellow;
}
```

See screenshot for result. The first 3 links are internal, the 2 last are external.
Note that the`background-color` works for internal links and that all (but it means my stylesheet is loaded).

### Expected behavior

Awful colors on links

### To Reproduce

I would say use this style...

### Screenshots

![style](https://github.com/Jermolene/TiddlyWiki5/assets/7228177/8650806a-2205-4485-a5e2-8487c7f387a8)

### TiddlyWiki Configuration

- Version 5.3.3
- Saving mechanism TiddlyDesktop
- Plugins installed Uni-Link (does not change if I disable it), MathJax

- OS: Linux
- Browser Chrome or TiddlyDesktop

**Comment by Jermolene** [comment]
Hi @oricou the core uses the following definition  to set the appearance of external links:

```css
a.tc-tiddlylink-external {
    text-decoration: underline;
    color: #0000ee;
    background-color: inherit;
}
```

If you want to override that definition, you have to do so with a selector that has more [specificity](https://developer.mozilla.org/en-US/docs/Web/CSS/Specificity). For example:

```
body.tc-body a.tc-tiddlylink-external {
    color: green;
    text-decoration:none;
    background-color: yellow;
}
```

**Comment by oricou** [comment]
Thanks for the information.

**Comment by Jermolene** [comment]
No problem, happy to help @oricou.
