### ISSUE TITLE
[BUG] Introduction edition does not allow navigation from the starting screen

### ISSUE THREAD

**Issue by lilscribby** [Jermolene/TiddlyWiki5#7965]
### Describe the bug

the starting tiddler (named with a space character) does not allow navigation to the rest of the intro flow. the "TiddlyWiki" text is not a link, and there is no other way to navigate besides going to the sidebar and selecting the next tiddler.

this may be because camelcase links are now off by default.

### Expected behavior

either the "TiddlyWiki" text should be a link, or the navigation should begin on the next tiddler in the intro flow (named TiddlyWiki).

### To Reproduce

go to [https://tiddlywiki.com/editions/introduction/](https://tiddlywiki.com/editions/introduction/)

click on the "TiddlyWiki" text and see it does not navigate you

see there is no way to navigate besides opening the sidebar (not expected for a new person being introduced to tiddlywiki to have to do)

### Screenshots

![image](https://github.com/Jermolene/TiddlyWiki5/assets/33818074/0c33c754-2ea2-4950-8476-4bd49ecedf81)

### TiddlyWiki Configuration

[https://tiddlywiki.com/editions/introduction/](https://tiddlywiki.com/editions/introduction/)

**Comment by Jermolene** [comment]
Thanks @lilscribby, the fixed version should be live at https://tiddlywiki.com/prerelease/editions/introduction/ in a few minutes.
