### ISSUE TITLE
[Bug] 1 button click creates 3 events - that's strange

### ISSUE THREAD

**Issue by pmario** [Jermolene/TiddlyWiki5#7969]
To reproduce

- Open https://tiddlywiki.com
- Create a tiddler with the code below
- Open Dev console F12
- Click the button 
- 3 events as shown in the screenshot -> IMO that is a problem and I do not know where this comes from

@Jermolene, @EricShulman @saqimtiaz do you have a clue?

```
title: test

\procedure test()
<$log />
\end

<$button actions=<<test>> >click me</$button>
```

![image](https://github.com/Jermolene/TiddlyWiki5/assets/374655/cbc2d475-f666-46eb-9d01-22890b6ec7e1)

**Comment by saqimtiaz** [comment]
Change the log widget to action-log.

**Comment by pmario** [comment]
ouuuuch :) - that hurts. Do we have a chance to detect if we are in an action, so `<$log` can do the right things?
