### ISSUE TITLE
[IDEA] TW setting items need a designated css class

### ISSUE THREAD

**Issue by twMat** [Jermolene/TiddlyWiki5#7976]
I want to style the "setting" items listed under `Ctrlpanel > Settings > TiddlyWiki` but there is no class applied to their divs, i.e [this tiddler](https://tiddlywiki.com/#%24%3A%2Fcore%2Fui%2FControlPanel%2FSettings%2FTiddlyWiki) generates the list like so:

```
<$list filter="[all[shadows+tiddlers]tag[$:/tags/ControlPanel/Settings]]">

<div style="border-top:1px solid #eee;">

!! <$link><$transclude field="caption"/></$link>

<$transclude/>

</div>

</$list>
```

So, instead of a proper class for each div, they're inline styled making it problematic to target.

**Describe the solution you'd like**
I am hoping a proper class can be applied instead.

**Describe alternatives you've considered**
I am currently using `div[style="border-top:1px solid #eee;"]` to target the items but this is not very good and a browser extension I use (to get browser "dark mode") interferes with this.

Thank you.

**Comment by CodaCodr** [comment]
Agreed and there's quite a few more like that that could be done better. Anything that places inline style into elements forces me to use `!important` where I shouldn't need to. For a while now, I've been adding `@layer tiddlywiki-defaults` to the core stylesheet.

Alternative to your solution:

```
div[data-tiddler-title='$:/core/ui/ControlPanel/Settings/TiddlyWiki'] h2 > a {
 color:red;
}
```

![image](https://github.com/Jermolene/TiddlyWiki5/assets/436812/91e334b4-a32d-4bc3-9550-3e4a30ae6fdb)

**Comment by Jermolene** [comment]
Hi @twMat @CodaCodr I would consider it a bug to have any DIVs that cannot be targeted with a reasonably straightforward selector, so I would welcome a PR to fix these ones.

**Comment by pmario** [comment]
IMO something like this should work. @Jermolene: Are you OK with 2 new classes. `tc-control-panel-setting` and `tc-control-panel-accent`

I personally would like `tc-cp-setting` and `tc-cp-accent`, but there are some `tc-control-panel` definitions already. 

```
\define lingo-base() $:/language/ControlPanel/Settings/

<<lingo Hint>>

<$list filter="[all[shadows+tiddlers]tag[$:/tags/ControlPanel/Settings]]">

<div class="tc-control-panel-setting" data-tiddler-title=<<currentTiddler>> style="border-top:1px solid #eee;">

!!.tc-control-panel-accent <$link><$transclude field="caption"/></$link>

<$transclude/>

</div>

</$list>
```

**Comment by Jermolene** [comment]
Hi @pmario yes those two classes would seem reasonable

**Comment by twMat** [comment]
@CodaCodr - thanks for your alternative, but it only works when you open that specific tiddler. Here's a variant for that tiddler when shown inside the Controlpanel:

`div[data-tiddler-title='$:/ControlPanel'] .tc-tab-content .tc-tab-content .tc-reveal > div`

I guess I'll use this but it is brittle (it is easy to modify the controlpanel tab structure) and it has the opposite problem of yours; it *only* works in the controlpanel.

So... OP.

**Comment by CodaCodr** [comment]
> Hi @twMat @CodaCodr I would consider it a bug to have any DIVs that cannot be targeted with a reasonably straightforward selector, so I would welcome a PR to fix these ones.

Thanks @Jermolene , and sorry for the gap... I was (still am) struggling to recall the gotchas that keep gotcha-ing me ;)

Here's one that resurfaced yesterday: 

`$:/config/TextEditor/EditorHeight/Height`

which becomes `style="Npx"` on editors. Only recourse for me is to clear this out completely (and try to remember to do so the _next_ time I'm setting up a wiki).

**Comment by CodaCodr** [comment]
Perhaps...

```
div.tc-editor-wrapper textarea {
/* overridable height et al */
    height: 500px;
/* or, if we need to keep the config setting... */
    height: {{$:/config/TextEditor/EditorHeight/Height}};
}
```
