### ISSUE TITLE
[BUG] sha256 filter fails on node.js

### ISSUE THREAD

**Issue by rmunn** [Jermolene/TiddlyWiki5#8001]
### Describe the bug

The sha256 filter contains the following code:

```js
return sjcl.codec.hex.fromBits(sjcl.hash.sha256.hash(text)).substr(0,length);
```

But on node.js (for example, when running in TiddlyDesktop with a wiki folder) there's no global sjcl object available until it's been `require()`d.

### Expected behavior

This can be solved by going into boot.js and adding `$tw.sjcl = sjcl;` right before the `this.setPassword = ...` line. Then edit core/modules/filters/crypto.js and change the two occurrences of `sjcl` to `$tw.sjcl`.

### To Reproduce

1. Install TiddlyDesktop
2. Create a new wiki folder
3. Open it
4. Hit F12 to open the developer console
5. Create a new tiddler

You'll see errors about sjcl not being found in the developer console.

### TiddlyWiki Configuration

- Version: v5.3.3
- Saving mechanism: TiddlyDesktop 0.18.0
- Plugins installed: None, default wiki folder in TiddlyDesktop

### Desktop (please complete the following information):

- OS: Linux
- Browser NW.js from TiddlyDesktop
- Version NW.js 0.84.0 (bug also occurs in NW.js 0.77.0 which is included in TiddlyDesktop 0.18.0)

### Additional context

I believe this may be the cause of https://github.com/TiddlyWiki/TiddlyDesktop/issues/285. I was experiencing that issue as well, but once I solved the sjcl issue, I was able to create new tiddlers just fine.

**Comment by Jermolene** [comment]
Thanks @rmunn that's excellent sleuthing, would you like to prepare a PR?

**Comment by rmunn** [comment]
@Jermolene - Sure. https://github.com/Jermolene/TiddlyWiki5/pull/8007
