### ISSUE TITLE
[bug] in PR #7915 -- MWS -- description fiels are url-encoded

### ISSUE THREAD

**Issue by pmario** [Jermolene/TiddlyWiki5#8011]
Related to PR: **Introduce "Multi Wiki Server" Plugin** #7915 

If I do create a new **bag** or a new **recipe**, the **description** field seems to be URL-encoded. 

![image](https://github.com/Jermolene/TiddlyWiki5/assets/374655/3ef2358e-6178-46e9-90fe-0cb8d1a91682)

**Comment by Jermolene** [comment]
Thanks @pmario, I noticed it the other day but forgot about it. I'll investigate.

**Comment by Jermolene** [comment]
This is fixed in 9facf4a067df8b19e8ec475ad97e01bab9a36e33
