### ISSUE TITLE
[BUG] Internal JavaScript Error when attempting to export missing tiddlers to CSV from the filter tab in $:/AdvancedSearch

### ISSUE THREAD

**Issue by Telumire** [Jermolene/TiddlyWiki5#8039]
### Describe the bug

![image](https://github.com/Jermolene/TiddlyWiki5/assets/31185220/7a326ee4-da2e-4d34-87b4-da1127f23f06)
![image](https://github.com/Jermolene/TiddlyWiki5/assets/31185220/f295ab6a-2411-4adc-bbe0-a00008c49661)

This bug affect the current release (5.3.3) & prerelease (5.3.4 pre), but only occur when attempting to export shadow tiddlers.

**Comment by Jermolene** [comment]
Thanks @Telumire

> This bug affect the current release (5.3.3) & prerelease (5.3.4 pre), but only occur when attempting to export shadow tiddlers.

In my testing I found the problem arises when attempting to export tiddlers that are missing. That happens with the example filter `[tags[]!is[system]sort[title]]`; I've highlighted the missing tiddlers below:

![image](https://github.com/Jermolene/TiddlyWiki5/assets/174761/a37dd4e1-b60e-428e-b236-4e8ad98f3fbd)
