### ISSUE TITLE
aws-sdk dependency merged into master - intended?

### ISSUE THREAD

**Issue by rmunn** [Jermolene/TiddlyWiki5#8040]
### Describe the bug

In https://github.com/Jermolene/TiddlyWiki5/commit/0710054e64b4f8b3a7b817cde7e594b45c8008fb, a commit just labeled "WIP" at the tail end of https://github.com/Jermolene/TiddlyWiki5/pull/7734, aws-sdk was added to TiddlyWiki's package.json dependencies. This results in node_modules suddenly acquiring about a dozen different packages that aws-sdk depends on. Given the disscussion at https://github.com/Jermolene/TiddlyWiki5/issues/6565#issuecomment-1087330715 I'm not sure if that was intended or not.

### Expected behavior

If the decision was made to add an NPM dependency, I'd have expected it to be done on purpose. But having it done in a commit with no commit message except "WIP" that comes as the very last commit of a large merge just makes me wonder.

### To Reproduce

1. Go to https://github.com/Jermolene/TiddlyWiki5/pull/7734/commits
2. Scroll down to the bottom of the commit list
3. See [the WIP commit](https://github.com/Jermolene/TiddlyWiki5/commit/0710054e64b4f8b3a7b817cde7e594b45c8008fb) that makes a large change to the number of dependencies in package-lock.json, with no explanation as to why it's necessary

### TiddlyWiki Configuration

N/A

### Additional context

It's entirely possible that this change was on purpose and everything's fine. I just wanted to make sure that it wasn't an accidental WIP commit that wasn't (yet) intended to get merged into `master`.

**Comment by Jermolene** [comment]
Agh, thanks @rmunn that was indeed an accident.

**Comment by rmunn** [comment]
Good to know. I've created https://github.com/TiddlyWiki/TiddlyDesktop/pull/296 to pull that version into TiddlyDesktop, and this time I've been able to include `package-lock.json` in the PR (I left it out of the previous PR precisely because the aws-sdk dependency graph had caused package-lock.json to explode in size, and I wasn't sure that was intended).
