### ISSUE TITLE
[Bug] If a procedure is imported with $importvariables widget it renders wrong

### ISSUE THREAD

**Issue by pmario** [Jermolene/TiddlyWiki5#8052]
@Jermolene -- I think that's a critical one, but I'm not really sure, where it comes from

A tiddler: `test-ok` with the following content **renders OK**

```
\procedure sayhi(name:"Bugs Bunny",address:"Rabbit Hole Hill")
Hi, I'm <<name>> and I live in <<address>>.
\end

<<sayhi>>
```

The following code in a second tiddler **does not work**

```
<$importvariables filter="test-ok">
<$codeblock code={{test-ok}}/>

<<sayhi>>
```

![image](https://github.com/Jermolene/TiddlyWiki5/assets/374655/22b0efc5-d9a7-4e22-84aa-bf1bbfd661d8)

**Comment by Jermolene** [comment]
Thanks @pmario I think this is a dupe of #7909

**Comment by pmario** [comment]
uups. You are right. I did forget about this one.
