### ISSUE TITLE
[BUG] links direct to wrong tiddlers on tiddlywiki.com

### ISSUE THREAD

**Issue by Rayme** [Jermolene/TiddlyWiki5#8058]
### Describe the bug

The HelloThere tiddler on tiddlywiki.com may have issues directing to other tiddlers, such as all tiddlers on section Quick Start and Find Out More. Tested on browsers Firefox, Edge and Chrome.

### To Reproduce

1. Go to 'https://tiddlywiki.com'
2. Click on 'Tiddlyhost, Desktop, etc'
3. See error: each directs to wrong tiddlers. For example, the Tiddlyhost card should link to [[Tiddlyhost]] instead of the current one [[Quick Start: Tiddlyhost]]

### Screenshots

![图片](https://github.com/Jermolene/TiddlyWiki5/assets/1947172/78d4f01e-2493-476b-aef1-836d7a375ea2)

### TiddlyWiki Configuration

- the main site of TiddlyWiki Version [v5.3.3]
- any browser [firefox, edge, chrome]
- any platform [Windows, Android]

**Comment by Jermolene** [comment]
Thanks @Rayme, that's very helpful.

@pmario I think this must be a result of the changes I merged over the weekend. Would you able to very kindly have a look at it?

**Comment by Jermolene** [comment]
The problem was #8033 which I have now reverted pending further testing.

**Comment by Jermolene** [comment]
Sorry @pmario are you saying that reverting #8033 didn't fix the issue? The bug potentially affected all visitors to tiddlywiki.com and so required urgent action.

**Comment by pmario** [comment]
Sure reverting did fix the issue. I was confused because the issue was gone. 
But instead of using more time here pls review #8059, which should fix the problem.
