### ISSUE TITLE
keyboard controls

### ISSUE THREAD

**Issue by FND** [Jermolene/TiddlyWiki5#808]
http://tiddlywiki.com/#KeyboardShortcuts claims that there are two keyboard shortcuts in edit mode - those don't seem to work (anymore?) though

also, it'd be great if TWC's accesskeys (or something similar*) could be reinstated

\* vi-like navigation would be excellent, of course

**Comment by BurningTreeC** [comment]
@Jermolene 

>I'm particularly keen to trap ctrl-S and cmd-S to avoid people accidentally using the browser file/save command).

Should I just go ahead and add these shortcuts?

**Comment by Jermolene** [comment]
Hi @BurningTreeC yes, that would be great, thank you
