### ISSUE TITLE
[BUG] Docs about how to use tag-picker missing

### ISSUE THREAD

**Issue by linonetwo** [Jermolene/TiddlyWiki5#8081]
### Describe the bug

Tag picker is frequently used by plugin authors, but it don't have a doc about how to use it. https://tiddlywiki.com/#tag-picker%20Macro:%5B%5Btag-picker%20Macro%5D%5D%20%5B%5Btag-picker%20Macro%20(Examples)%5D%5D

And using two tag-picker in same tiddler, will cause they open the dropdown together. I think it might be caused by

```
<div class="tc-block-dropdown-wrapper">
  <$reveal state=<<qualify "$:/state/popup/tags-auto-complete">> type="nomatch" text="" default="">
```

There might be workaround or a correct usage, I will update the doc once I know it.

### Expected behavior

I know half of how to use it:

```tid
  <$let tagField="list" newTagNameTiddler=<<qualify "$:/temp/NewTagName">>  currentTiddler=<<draft-tiddler>> saveTiddler=<<draft-tiddler>> currentTiddler=<<draft-tiddler>>>
    {{||$:/core/ui/EditTemplate/tags}}
  </$let>

  <$let tagField="tags" newTagNameTiddler=<<qualify "$:/temp/NewTagName">> currentTiddler=<<draft-tiddler>> saveTiddler=<<draft-tiddler>> currentTiddler=<<draft-tiddler>>>
    {{||$:/core/ui/EditTemplate/tags}}
  </$let>
```

Need to define many variables like `newTagNameTiddler` to ensure they don't conflict. (If without `newTagNameTiddler`, they all edit the first one's field, `list` in this case.)

But even so, when we have two tag picker like this, they will open the dropdown together.

### To Reproduce

1. Copy the code above to tw5-com create a new tiddler
2. click on second tag picker's input
3. you will see two open the dropdown together.

### Screenshots

![图片](https://github.com/Jermolene/TiddlyWiki5/assets/3746270/9adb0686-1d6e-4ddf-a07f-3633759632d9)

### TiddlyWiki Configuration

- Version 5.3.3

### Additional context

I'm using two tag pickers in a modal to create new tiddler in https://github.com/tiddly-gittly/tiddlywiki-calendar/blob/807725b49199409a19a1aa8077e9115612742f51/src/visualization-dashboard/tiddlywiki-ui/Modal/CreateGaugeModal.tid

**Comment by linonetwo** [comment]
@BurningTreeC you added this in https://tiddlywiki.com/#tag-picker%20Macro:%5B%5Btag-picker%20Macro%5D%5D%20%5B%5Btag-picker%20Macro%20(Examples)%5D%5D , do you know what's missing in my snippet?

**Comment by linonetwo** [comment]
Wait, why this works fine

![图片](https://github.com/Jermolene/TiddlyWiki5/assets/3746270/800ff523-0429-4027-8340-5501c6b5104a)

---

They use different currentTiddler, but if you try to edit same currentTiddler 's two different fields, there is bug.

**Comment by pmario** [comment]
See pending PR: Tag picker rewritten using new v5.3.x syntax #7978

**Comment by linonetwo** [comment]
Thanks @pmario , this does not reproduce in your fixed version.

**Comment by linonetwo** [comment]
Close this as this is tracking in #7978
