### ISSUE TITLE
[BUG] BackSubIndexer should ignore binary tiddler

### ISSUE THREAD

**Issue by linonetwo** [Jermolene/TiddlyWiki5#8091]
### Describe the bug

I find my wiki wasting lots of time processing a docx file.

Now that I've add doc xls ppt type as binary https://github.com/Jermolene/TiddlyWiki5/pull/7927
 , I think we can avoid process doc here by check if tiddler is binary here:

https://github.com/Jermolene/TiddlyWiki5/blob/36fc8170a4a86a74970d8ce5f57bcd791239f0d0/core/modules/indexers/back-indexer.js#L72-L78

### Expected behavior

Ignore all binary tiddler when building back indexer. But I'm not very sure about this, because seems it is not processing images?

### To Reproduce

1. In nodejs setup, copy a large docx file to tiddlers/
2. start wiki, and find browser wait for indexer building

### TiddlyWiki Configuration

- Version v5.3.3
- Saving mechanism Node.js
- Plugins installed Many...

**Comment by Jermolene** [comment]
Thank you @linonetwo, that's quite a significant bug!
