### ISSUE TITLE
[BUG] for PR #7915 -- MWS 

### ISSUE THREAD

**Issue by MagicJF** [Jermolene/TiddlyWiki5#8110]
### Describe the bug

server breaks if you try to load a recently created bag.
![breaks](https://github.com/Jermolene/TiddlyWiki5/assets/92638213/56f8182c-770a-4358-8932-f4a5d9f8e9fe)

Bypass Solution nº1:
if you create a recipe that includes an already working bag + the newly created bag, and you wait until the server syncs then it initializes OK
![solution](https://github.com/Jermolene/TiddlyWiki5/assets/92638213/14cb33cf-16c9-4269-a5bb-e63eb49cc56a)

### TiddlyWiki Configuration

MWS

**Comment by Jermolene** [comment]
Thanks @MagicJF, I've posted a fix, let me know how you get on.
