### ISSUE TITLE
[BUG ?] declarative shadow dom doesnt work with the wikitext parser

### ISSUE THREAD

**Issue by Telumire** [Jermolene/TiddlyWiki5#8114]
The [declarative shadow dom](https://developer.chrome.com/docs/css-ui/declarative-shadow-dom) is a baseline feature ([since February 20, 2024](https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Releases/123#html)) which allow to scope styles without the use of javascript (among other things): https://dev.to/wes_goulet/scoped-css-styles-with-declarative-shadow-dom-4p80

However, it doesn't work in a wikitext context ([demo on tiddlywiki.com/share](https://tiddlywiki.com/share##%5B%7B%22created%22%3A%2220240328203619348%22%2C%22text%22%3A%22%21%21%20text%2Fvnd.tiddlywiki%5Cn%5Cn%24%24%24text%2Fvnd.tiddlywiki%5Cn%3Cstyle%3E%5Cn%5Ct%3Awhere%28div%29%20%7B%5Cn%5Ct%5Ctcolor%3A%20blue%3B%5Cn%5Ct%7D%5Cn%3C%2Fstyle%3E%5Cn%5Cn%3Cdiv%3E%5Cn%5Ct%3Ctemplate%20shadowrootmode%3D%5C%22open%5C%22%3E%5Cn%5Ct%5Ct%3Cstyle%3E%5Cn%5Ct%5Ct%5Ct%3Ahost%20%7B%5Cn%5Ct%5Ct%5Ct%5Ctcolor%3A%20red%3B%5Cn%5Ct%5Ct%5Ct%7D%5Cn%5Ct%5Ct%3C%2Fstyle%3E%5Cn%5Cn%5Ct%5Ct%3Cp%3EThis%20is%20also%20blue%21%3C%2Fp%3E%5Cn%5Ct%5Ct%3Cslot%3E%3C%2Fslot%3E%5Cn%5Ct%3C%2Ftemplate%3E%5Cn%5Cn%5Ct%3Cp%3EThis%20is%20blue.%3C%2Fp%3E%5Cn%3C%2Fdiv%3E%5Cn%24%24%24%5Cn%5Cn%21%21%20text%2Fhtml%5Cn%5Cn%24%24%24text%2Fhtml%5Cn%3Cstyle%3E%5Cn%5Ct%3Awhere%28div%29%20%7B%5Cn%5Ct%5Ctcolor%3A%20blue%3B%5Cn%5Ct%7D%5Cn%3C%2Fstyle%3E%5Cn%5Cn%3Cdiv%3E%5Cn%5Ct%3Ctemplate%20shadowrootmode%3D%5C%22open%5C%22%3E%5Cn%5Ct%5Ct%3Cstyle%3E%5Cn%5Ct%5Ct%5Ct%3Ahost%20%7B%5Cn%5Ct%5Ct%5Ct%5Ctcolor%3A%20red%3B%5Cn%5Ct%5Ct%5Ct%7D%5Cn%5Ct%5Ct%3C%2Fstyle%3E%5Cn%5Cn%5Ct%5Ct%3Cp%3EThis%20is%20also%20blue%21%3C%2Fp%3E%5Cn%5Ct%5Ct%3Cslot%3E%3C%2Fslot%3E%5Cn%5Ct%3C%2Ftemplate%3E%5Cn%5Cn%5Ct%3Cp%3EThis%20is%20blue.%3C%2Fp%3E%5Cn%3C%2Fdiv%3E%5Cn%24%24%24%22%2C%22tags%22%3A%22%22%2C%22title%22%3A%22Demo%20declarative%20shadow%20root%22%2C%22modified%22%3A%2220240328203705595%22%7D%5D)):

```
$$$text/html
<style>
	:where(div) {
		color: blue;
	}
</style>

<div>
	<template shadowrootmode="open">
		<style>
			:host {
				color: red;
			}
		</style>

		<p>This is also blue!</p>
		<slot></slot>
	</template>

	<p>This is blue.</p>
</div>
$$$

$$$text/vnd.tiddlywiki
<style>
	:where(div) {
		color: blue;
	}
</style>

<div>
	<template shadowrootmode="open">
		<style>
			:host {
				color: red;
			}
		</style>

		<p>This is also blue!</p>
		<slot></slot>
	</template>

	<p>This is blue.</p>
</div>
$$$
```

![image](https://github.com/Jermolene/TiddlyWiki5/assets/31185220/c7e065de-0b5d-47af-b956-8cfc2c9758c5)

The html parser works as expected, but the wikitext parser does not. Is that intentional or is this a bug ?

Tested on edge with the current & 5.3.4-prerelease version of tiddlywiki.

**Comment by Jermolene** [comment]
Thanks @Telumire, an interesting problem.

TiddlyWiki handles HTML by (essentially) converting it into a sequence of DOM operations: createElement, setAttribute, and finally appendChild to add the element to the DOM. Until the advent of the shadow DOM, that process gave a 1:1 correspondence between the input HTML and the observed generated DOM elements.

The `<template>` element gets a lot of special handling in the HTML specification, which TiddlyWiki does not yet replicate. That means that your example ends up with a completely different representation in the DOM than when rendered in HTML.

It would require more investigation to figure out the best fix. It could be the the "element" widget needs special handling for the "template" element. It also occurs to me that much of the shadow DOM spec is not really applicable to TiddlyWiki, and so perhaps it would make more sense to introduce a higher level abstraction such as a `<$barrier>` widget that prevents the spread of CSS rules. It would of course be implemented via this same technique, but it might be simpler than trying to offer truly general support for the shadow DOM.

**Comment by Telumire** [comment]
@Jermolene the upcoming css selector `@scope` will solve the issue of  css "leaking" out of a component, so maybe it's not necessary to create a custom widget only for this .. I'm closing this for now, thanks for the clarification !

**Comment by Telumire** [comment]
0
