### ISSUE TITLE
Client-server data loss due to faulty cache handling

### ISSUE THREAD

**Issue by Jermolene** [Jermolene/TiddlyWiki5#8138]
NOTE This issue was originally written by @joshuafontany as a comment https://github.com/Jermolene/TiddlyWiki5/issues/1839#issuecomment-2044275924

----

@pmario @jermolene I ran into an issue with browser caches at work, and realized it may explain some client/server weirdness that I have seen with tiddlywiki. The current advice around this is to NOT use meta tags in the head element, but to have the server set the cache-control headers directly (as Jeremy suggested).

Tiddlywiki delivers the initial "package" of tiddler data inside the HTML, with no cache-control header specified. So the default "not specified" caching takes over, which is browser controlled via heuristic algorithms (unpredictable). As soon as a change is synced back to the server, the HTML in the browser cache is a race-condition-waiting-to-happen. If the page is refreshed and the tiddlers are re-loaded from the OLD cached HTML.... and then synced. Oops, just wiped out a bunch of work, didn't we?

This may be important to clear up for the MWS work. I am getting back into working with TW servers, so may be able to get an idea of where to include this. Are we sill using `tiddlywiki.info` files to define MWS wikis? Where else can we specify these configs?

https://www.cloudflare.com/learning/cdn/glossary/what-is-cache-control/

**cache-control: no-store**
A response with a ‘no-store’ directive cannot be cached anywhere, ever. This means that every time a user requests this data, a request must be sent to the origin server for a fresh copy. This directive is typically reserved for resources that contain extremely sensitive data, such as bank account information.

**cache-control: no-cache**
This directive means that cached versions of the requested resource cannot be used without first checking to see if there is an updated version. This is typically done using an ETag.

An ETag is another HTTP header which contains a token unique to the version of the resource at the time it was requested. This token is changed on the origin server whenever the resource is updated.

When a user returns to a page with a ‘no-cache’ resource, the client will always have to connect to the origin server and compare the ETag on the cached resource with one on the server. If the ETags are identical, the cached resource will be provided to the user. If not, this means that the resource has been updated and the client will need to download a fresh version to provide to the user. This process ensures that the user is always getting the most up-to-date version of that resource without requiring unnecessary downloads.

_Originally posted by @joshuafontany in https://github.com/Jermolene/TiddlyWiki5/issues/1839#issuecomment-2044275924_

**Comment by joshuafontany** [comment]
Issue can be closed.

**Comment by Jermolene** [comment]
Thanks @joshuafontany
