### ISSUE TITLE
[DOCS] Update TiddlerFields documentation to note that field names are unrestricted since 5.2.0

### ISSUE THREAD

**Issue by bluepenguindeveloper** [Jermolene/TiddlyWiki5#8146]
### Describe the bug

https://tiddlywiki.com/#TiddlerFields says:

> Field names must be lowercase letters, digits or the characters `-` (dash), `_` (underscore) and `.` (period).

This is only true in versions prior to [version 5.2.0](https://tiddlywiki.com/#Release%205.2.0):

> The major change in this release is that the format used to store tiddlers in [TiddlyWiki](https://tiddlywiki.com/#TiddlyWiki)'s HTML file has changed from an HTML DIV-based format to a new JSON-based format. The consequences of this change are far-reaching. They are thus the primary rationale for bumping the version number from v5.1.x to v5.2.0:
> 
> Firstly, the **characters that can be used in field names are now unrestricted** (just like tiddler titles), making it possible to use fieldnames like `My^Field` or `☃️`. This has become possible because every other part of [TiddlyWiki](https://tiddlywiki.com/#TiddlyWiki) was already capable of dealing with unrestricted field names apart from saving as an HTML file.

### Expected behavior

The documentation for [TiddlerFields](https://tiddlywiki.com/#TiddlerFields) should note that in versions 5.1.x, tiddler field names are restricted, but in 5.2.0 and above, they are unrestricted.

### To Reproduce

1. Go to https://tiddlywiki.com/#TiddlerFields and see what it says
2. Contrast with what it says as the first highlight here: https://tiddlywiki.com/#Release%205.2.0

### Screenshots

![image](https://github.com/Jermolene/TiddlyWiki5/assets/166951090/b8795441-9099-4f9f-9989-466eae0fd403)
![image](https://github.com/Jermolene/TiddlyWiki5/assets/166951090/00b8b28f-6292-4522-9c92-68532bf6446a)

### TiddlyWiki Configuration

The documentation (https://tiddlywiki.com/#TiddlerFields)

**Comment by Jermolene** [comment]
Thank you @bluepenguindeveloper, fix coming up.
