### ISSUE TITLE
[BUG] No way to remove the X-requested-with header from `tm-http-request` requests

### ISSUE THREAD

**Issue by mklauber** [Jermolene/TiddlyWiki5#8149]
### Describe the bug

Due to tightly configured Access-Control-Allow-Headers headers, extraneous headers can interfere with CORS validation when hitting external APIs.  In particular, I ran into an issue with the x-requested-with header not being permitted while playing with the stablehorde API described [here](https://stablehorde.net/api/).   

Unless there's a way to disable/remove these headers, it's probably better (i.e. most flexible) to require users to set them deliberately.

### Expected behavior

Only the explicitly configured headers are submitted, or there's a way to remove automatic headers

### TiddlyWiki Configuration

- Version 5.3.1
- Saving mechanism: Any

### Desktop (please complete the following information):
- OS: linux
- Browser firefox

### Additional context

https://github.com/Jermolene/TiddlyWiki5/pull/8148

**Comment by pmario** [comment]
You access the "horde api" from TW. That's interesting. I do have an internet facing horde server. Do you intend to publish some more info about that project. 

I would be extremely interested.

**Comment by saqimtiaz** [comment]
Resolved in https://github.com/Jermolene/TiddlyWiki5/pull/8152, @mklauber @Jermolene this issue should be closed.

**Comment by Jermolene** [comment]
Thanks @saqimtiaz
