### ISSUE TITLE
[BUG] filter prefixes don't properly set currentTiddler, I think

### ISSUE THREAD

**Issue by flibbles** [Jermolene/TiddlyWiki5#8178]
### Describe the bug

Filter prefixes are turning out to be something I use often, not so much because they're elegant, but because they're able to set variables in the middle of a filter expressions, which can be crucial for some operations.

But I'm noticing strange behavior. While a filter run may set currentTiddler within its own run, it doesn't set it within functions called within that run, or anything within that run really.

Is that expected behavior that currentTiddler is only set superficially?

### Expected behavior

```
old-current

new-current
```

When I would have thought it'd produce:

```
new-current

new-current
```

### To Reproduce

```
\define currentTiddler() old-current

\function .inner() [<currentTiddler>]
\function .outer() new-current :map[function[.inner]]

\function .alone() new-current :map[<currentTiddler>]


<<.outer>>
<<.alone>>
```

**Comment by saqimtiaz** [comment]
@flibbles can you confirm if this problem still occurs in the current pre-release? 

See https://github.com/Jermolene/TiddlyWiki5/pull/7906

**Comment by flibbles** [comment]
It appears to still be there. I take it then that this is indeed a problem to others?

**Comment by saqimtiaz** [comment]
This is most definitely a bug.

Note that with #7906 applied the following works while it doesn't in the current stable release:

```
\define currentTiddler() old-current

\function .inner() [<currentTiddler>]

<$text text={{{ new-current :map[function[.inner]] }}}/>
```

The issue seems to crop up when a function invokes another function, unfortunately I don't have the opportunity to debug this at present.

This will fail:
```

\define currentTiddler() old-current

\function .inner() [<currentTiddler>]
\function .outer() new-current :map[function[.inner]]

<$text text={{{ [.outer[]] }}}/>

```

**Comment by Jermolene** [comment]
Thanks @flibbles much appreciated – this seems to be an area that has been fertile in surfacing bugs...
