### ISSUE TITLE
[BUG]  Blockquote parsing fails on example

### ISSUE THREAD

**Issue by joshuafontany** [Jermolene/TiddlyWiki5#8183]
### Describe the bug

The Wiki Parser Rule for QuoteBlock does not parse the wikitext given in the example comments:
```
/*\
title: $:/core/modules/parsers/wikiparser/rules/quoteblock.js
type: application/javascript
module-type: wikirule

Wiki text rule for quote blocks. For example:

	<<<.optionalClass(es) optional cited from
	a quote
	<<<
	
	<<<.optionalClass(es)
	a quote
	<<< optional cited from

Quotes can be quoted by putting more <s


	<<<
	Quote Level 1
	
	<<<<
	QuoteLevel 2
	<<<<
	
	<<<
```

### Expected behavior

Block Quotes are parsed as expected.

### To Reproduce

1. Go to https://tiddlywiki.com
2. Click on New Tiddler
3. Paste the wikitext from the quoteblock.js header comments:
	<<<.optionalClass(es) optional cited from
	a quote
	<<<
	
	<<<.optionalClass(es)
	a quote
	<<< optional cited from

### TiddlyWiki Configuration

- Version [e.g. v5.1.24]
- Saving mechanism [e.g. Node.js, TiddlyDesktop, TiddlyHost etc]
- Plugins installed [e.g. Freelinks, TiddlyMap]

**Comment by pmario** [comment]
I think it works as expected.  The only problem is, that it should not be indented. Blockquotes have to start at the start of the line. Tabs at the "end quotes" are not allowed.

![image](https://github.com/Jermolene/TiddlyWiki5/assets/374655/5ca0ed99-1170-4006-8122-d832d4685e16)

**Comment by Jermolene** [comment]
Hi @joshua the comment there is out of date and misleading in two respects: the use of indentation, and the fact that the blockquote syntax does not support nesting. I think the entire comment can be reduced to "Wiki text rule for quote blocks"; these comments are not the place to explain the syntax.

**Comment by pmario** [comment]
>[. . .] and the fact that the blockquote syntax does not support nesting. 

I was surprised, but it actually works. 

![image](https://github.com/Jermolene/TiddlyWiki5/assets/374655/492be915-67db-41ff-aba9-6cfe0e1f35bd)

**Comment by joshuafontany** [comment]
Ack, it was late when I found this. I am re-writing =my VSCode-TW5-Syntax "grammar", and this jumped out at me now that I can colorize wkitext better. The actual bug is the other example:
```
	<<<
	Quote Level 1
	
	<<<<
	QuoteLevel 2
	<<<<
	
	<<<
```

Ah, it's the leading spaces/tabs, which breaks the closing pattern of the quotes. I actually really like the idea of indented quotes, maybe I can target a fix for this. Would that be worth it @Jermolene @pmario ?

**Comment by joshuafontany** [comment]
Based on this conversation, a minor code fix will help with end-markers with preceding spaces. I have also cleared up the documentation:
https://github.com/Jermolene/TiddlyWiki5/pull/8186
