### ISSUE TITLE
[BUG] $action-log always evaluates all functions in its context

### ISSUE THREAD

**Issue by yaisog** [Jermolene/TiddlyWiki5#8189]
### Describe the bug

When functions are defined in the context of an ActionLogWidget (usually globally defined functions), these are always evaluated, even if they are not used in the output. Also, their filter runs are given all[tiddlers] as input, so they might need much more computation time that they were designed for.

### Expected behavior

They should not be evaluated in order to keep things running fast.

### To Reproduce

1. Go to tiddlywiki.com
2. Create a tiddler tagged `$:/tags/Macro` with this content
```
\function .slow() [range[1000]] :map[all[tiddlers]search:*[TiddlyWiki]] +[first[]]
```
3. Create another tiddler with this content
```
<$button actions="""<$action-log message="Button pressed." />""">GO</$button>
```
4. Open browser console and press button
5. Wait

### TiddlyWiki Configuration

No configuration dependence.

**Comment by pmario** [comment]
I can confirm, that there is a significant slowdown, even if everything is in the same tiddler.
