### ISSUE TITLE
[BUG]  Uncaught TypeError: process.nextTick is not a function

### ISSUE THREAD

**Issue by solkmaaker** [Jermolene/TiddlyWiki5#8192]
### Describe the bug

Internal JavaScript Error
Well, this is embarrassing. It is recommended that you restart TiddlyWiki by refreshing your browser
Uncaught TypeError: process.nextTick is not a function

### To Reproduce

1. Go to 'https://tiddlywiki.com/'
2. Click on 'any place on page'
3. See error

### Screenshots

![324185071-5bb97d20-f6b2-41d2-b936-9bcbc74b1f83](https://github.com/Jermolene/TiddlyWiki5/assets/38507958/6f4c9622-8deb-480a-b97a-65fe16cbf827)

### TiddlyWiki Configuration

Version 1.52.130 Chromium: 114.0.5735.198 (Official Build) (64-bit)
Version 1.65.130 Chromium: 124.0.6367.159 (Official Build) (64-bit)

**Comment by Jermolene** [comment]
Hi @solkmaaker I was unable to duplicate the issue on Chrome 124.0.6367.203 on macOS. What operating system platform are you using? Do you have any browser extensions active?

**Comment by solkmaaker** [comment]
> Hi @solkmaaker I was unable to duplicate the issue on Chrome 124.0.6367.203 on macOS. What operating system platform are you using? Do you have any browser extensions active?

Hi
I'm using Debian 11, but one of my friends is using Win11 and he sees same thing.
But, thank you for pointing me in right direction, seems the problem comes when WebID is enabled, so it really is not tiddlywiki problem. I will contact WebID developers.
[https://www.id.ee/en/article/web-eid/](https://www.id.ee/en/article/web-eid/)

**Comment by pmario** [comment]
@solkmaaker -- You may close the issue, since it seems to be no issue anymore.
