### ISSUE TITLE
[IDEA] Meaningful Notifications for Permalink and Permaview Messages

### ISSUE THREAD

**Issue by kookma** [Jermolene/TiddlyWiki5#8208]
**Is your feature request related to a problem? Please describe.**
When you click on Permalink or Permaview, a notification appeared on the left top of screen saying `Copied to clipboard`. This confusing specially when these messages are used with custom buttons (like Utility plugin from kookma)

**Describe the solution you'd like**
Use a better meaningful notifications like:
Permalink copied to clipboard
Permaview copied to clipboard

**Additional context**
Customization would be an extra benefit. So, user can sand their custom notification.

**Comment by Jermolene** [comment]
Thanks @kookma that's a good idea. There is a proposed fix in #8211.

**Comment by kookma** [comment]
Closed as this is proposed in https://github.com/Jermolene/TiddlyWiki5/pull/8211
