### ISSUE TITLE
[TESTS] all tests for a plugin-type "in development" fail, with no possibility to fix it

### ISSUE THREAD

**Issue by pmario** [Jermolene/TiddlyWiki5#8209]
@Jermolene 

See:  https://github.com/Jermolene/TiddlyWiki5/blob/4d2aa1dc95af97241dde860404ea0e000934c04e/editions/test/tiddlers/tests/test-plugins.js#L27

@Jermolene -- I think there is a problem with this line in the test.  It basically means that every future plugin-type in development will cause this test to fail. 

There have been some discussions to distribute "content" as plugins. I do have a test plugin with `"plugin-type": "content"` which causes this test to fail. 

There is no way for me to fix this problem other than use "plugin", "language" or "theme" - which is not possible because it is "content"

--------

The other problem is, that there is no default path in the switch. So I would like to have the following default:

```
default:
	expect(!!(fields.name && fields.description)).toEqual(true);
	break;
```

**Comment by pmario** [comment]
I think the output of the test should be more verbose. 

- The line: `expect(fields["plugin-type"]).toMatch(/^(?:plugin|language|theme)$/);` is extremely sneaky. I did waste 15+ minutes with searching what's wrong with my field: `name, description list` -> Just to find out that the test is about "plugin-type". 
- The "switch" is so much more visible, that I did completely miss the first test
- There should also be more detailed info, what exactly is wrong. eg:
  - field "name" is missing or field "descriptions" ... 
 
At least the info: "every plugin should have the required standard fields" should be split into several tests eg:

- "every **plugin** should have the standard fields: name, description, list, stability
- "every **theme** and **language** should have the standard fields: name, description

**Comment by Jermolene** [comment]
Thanks @pmario 

> I think there is a problem with this line in the test. It basically means that every future plugin-type in development will cause this test to fail.

I disagree. It just means that this test would need updating if we were to include other plugin types in the core library.

> There have been some discussions to distribute "content" as plugins. I do have a test plugin with "plugin-type": "content" which causes this test to fail.

This test is not intended to be applied to third party plugins. It is enforcing the standards of the core. For example, in general the "stability" field is not mandatory in third party plugins.

> I think the output of the test should be more verbose.

I'll push some updates shortly.

> The line: expect(fields["plugin-type"]).toMatch(/^(?:plugin|language|theme)$/); is extremely sneaky. I did waste 15+ minutes with searching what's wrong with my field: name, description list -> Just to find out that the test is about "plugin-type".

I've refactored that line to not use regex.

**Comment by pmario** [comment]
>I disagree. It just means that this test would need updating if we were to include other plugin types in the core library.

OK. I can live with that. 
The messages should be much easier to fix now. Thx.
