### ISSUE TITLE
[BUG] Fix splitregexp operator JavaScript error on matches with undefined capture groups

### ISSUE THREAD

**Issue by bluepenguindeveloper** [Jermolene/TiddlyWiki5#8213]
### Describe the bug

When the regular expression parameter to the splitregexp argument contains a capture group that (due to a disjunction `|`) is undefined in a match, it throws an uncaught error `Linked List only accepts string values, not undefined`

### Expected behavior

The input should be split on the match (edit: and `undefined` capture groups should be safely handled, presumably by simply removing them from the output since unlike empty strings they wouldn't represent tiddler titles) with no "Red Screen of Embarrassment"

### To Reproduce

Copy and paste the following code into a new tiddler (with the preview pane open):
```
\define re() (color)|(colour)ed

\define str() Something coloured

{{{ [<str>splitregexp<re>] }}}
```

### Screenshots

![image](https://github.com/Jermolene/TiddlyWiki5/assets/166951090/40f1840c-5b7e-4780-8c0e-9fb568b73e74)

### TiddlyWiki Configuration

- Version v5.3.3
- Saving mechanism TiddlyDesktop, browser
- No plugins installed (except core and the en language)

### Desktop:

- OS: Windows 10
- Browser: Brave (Chromium)

**Comment by pmario** [comment]
There is an unrelated question. 
What would you expect from this filter? How should the output look like?

**Comment by joshuafontany** [comment]
The difference is in your capture groups: https://regexr.com/80r94
`(color)|(colour)ed` returns two capture groups, one of white will be null. Either $1 = `color` | $2 = `colour`.

**Comment by pmario** [comment]
I do know what's going on. I just wanted to know what the expectations where. There seems to be a bug in the implementation. And the assumption what the regexp does is wrong too. But what we know is, that there should be no RSOD no matter what.

**Comment by pmario** [comment]
RegExps are complex. That's why I was asking, what you expected as a result. With `splitregexp` capture groups are not really useful as it is implemented in the JS code. 

But as I wrote. There should be no RSOD anyway

**Comment by Jermolene** [comment]
Thanks @bluepenguindeveloper
