### ISSUE TITLE
[BUG] Tiddler editor layout has lost whitespace

### ISSUE THREAD

**Issue by Jermolene** [Jermolene/TiddlyWiki5#8217]
The current tiddler editor on https://tiddlywiki.com/empty.html looks like this:

<img width="706" alt="image" src="https://github.com/Jermolene/TiddlyWiki5/assets/174761/c3c8a539-25a3-4855-926f-7c44fe4c5793">

The tiddler editor on https://tiddlywiki.com/prerelease/empty.html looks like this:

<img width="706" alt="image" src="https://github.com/Jermolene/TiddlyWiki5/assets/174761/da1e8bc5-88c1-4534-b29a-cfed68f684fc">

Notice the way that in the prerelease the whitespace between elements has been lost, and the various boxes abut each other. I would not have knowingly agreed to these changes.

I would welcome any suggestions as to the offending PR before I dig into things – @BurningTreeC could this be an unintended consequence of #7787?

**Comment by Alzacon** [comment]
[This rule](https://github.com/Jermolene/TiddlyWiki5/blame/master/themes/tiddlywiki/vanilla/base.tid#L3377-L3379) removes these vertical margins. 

A solution would be to change the selector to `.tc-test-case-source  .tc-edit-texteditor`

**Comment by Jermolene** [comment]
Thanks @Alzacon
