### ISSUE TITLE
[BUG] testcase procedure: "test failed" message displayed even though no ExpectedResult is defined

### ISSUE THREAD

**Issue by mateuszwilczek** [Jermolene/TiddlyWiki5#8218]
### Describe the bug

Calling the testcase _procedure_ with a compound tiddler that contains no ExpectedResult, the "test failed" message is displayed.

### Expected behavior

Calling the testcase _procedure_ `<<testcase "Payload">>` should behave identically to using the testcase/data _widgets_ `<$testcase> <$data $compound-tiddler="Payload"/> </$testcase>`.

### To Reproduce

- go to prerelase
- clone `TestCases/TranscludeWidget/SimpleTransclusion`
- rename to `Payload`
- remove the ExpectedResul from its contents
- create a new tiddler with the following contents:

```
<<testcase "Payload">>

<$testcase>
	<$data $compound-tiddler="Payload"/>
</$testcase>
```

- the testcase called though the procedure shows the "test failed" message, but the one called through widgets shows none (as expected)

### Screenshots

![image](https://github.com/Jermolene/TiddlyWiki5/assets/36714554/629c6194-b91b-4c60-8a94-17e1c8abb20a)

### TiddlyWiki Configuration

- Version 5.3.4-prerelease
- Saving mechanism: not related to saving
- Plugins installed: multiple as in the prerelease

### Desktop:

- OS: Windows 10
- Browser: Edge
- Version: 122

### Additional context

Since the testcase procedure simply transcludes the `$:/core/ui/testcases/DefaultTemplate` and a similar issue (displaying "test failed" message even though there is no ExpectedResult) arises when simply viewing a compound tiddler (tagged `$:/tags/wiki-test-spec`) with no ExpectedResult, this bug might actually be a problem with the `$:/core/ui/testcases/DefaultTemplate`, not with the testcase procedure.

**Comment by Jermolene** [comment]
Thanks @mateuszwilczek that should be fixed now.
