### ISSUE TITLE
[IDEA] $action-log and $log widget should have "shortcut parameters"

### ISSUE THREAD

**Issue by pmario** [Jermolene/TiddlyWiki5#8241]
@saqimtiaz -- slightly related to:  **Modifies action-log to return text of functions** #8239 

I would like to have a convenience improvement for action logs and log widget. 

Most of the time my calls look like this: `<$action-log value=<<value>> my.function=<<my.function>>` and so on. 

What I would like is: `<$action-log my.function value` as a shortcut for the above call.

**Comment by saqimtiaz** [comment]
> What I would like is: `<$action-log my.function value` as a shortcut for the above call.

At present that would be `$action-log $$filter="my.function value`.

**Comment by pmario** [comment]
>At present that would be `$action-log $$filter="my.function value"`.

Oh.. nice I did forget about that possibility. close the issue
