### ISSUE TITLE
[IDEA] Make stability badges themeable

### ISSUE THREAD

**Issue by Leilei332** [Jermolene/TiddlyWiki5#8272]
The color of the color of the stability cannot be changed since they are fixed in the tidder `$:/themes/tiddlywiki/vanilla/base`.

**Describe the solution you'd like**

The stability badges should be themeable by using palettes. I think we can add palette color names (for example `stability-stable`) and edit the tiddler `$:/themes/tiddlywiki/vanilla/base` (replace `blue` with `<<color stability-stable>>`) to implement it.

For example, we can add the following code to the tiddler `$:/palettes/SolarizedLight` to let the stability badges use solarized colors.

```
stability-stable: #859900
stability-experimental: #b58900
stability-legacy: #268bd2
stability-deprecated: #dc322f
```

**Comment by Jermolene** [comment]
Thanks @Leilei332 this is fixed in c8cbf6853ecb9e634a65ee3120d4cf41415dd4b2
