### ISSUE TITLE
Need Help! When import many tiddlers, I hope to show the updated tiddlers only.

### ISSUE THREAD

**Issue by lilixiong2018** [Jermolene/TiddlyWiki5#8315]
I modify the funtion "overWriteWarning" of ImportListing.tid to:

```
\define overWriteWarning()
\define date-format() YYYY-0MM-0DD 0hh:0mm:0ss
<$list filter="[<currentTiddler>!has<suppressedField>]">
<$list filter="[subfilter<payloadTitleFilter>is[tiddler]]" variable="void">
<$text text={{{ [<lingo-base>addsuffix[Listing/Rename/OverwriteWarning]get[text]] }}}/>
<$set name="incomingDate" tiddler=<<currentTiddler>> subtiddler=<<payloadTiddler>> field="modified">
<$let currentDate={{{ [<payloadTiddler>get[modified]] }}} >
<% if <currentDate>:ne<incomingDate> %>
<br> &nbsp;&nbsp;&nbsp;currentDate: <$text text={{{ [<currentDate>format:date<date-format>] }}}/> 
<br> incomingDate: <$text text={{{ [<incomingDate>format:date<date-format>] }}}/> 
<% else %>
<br> ( Modified time not change )
<% endif %>
</$let>
</$set>
</$list>
</$list>
\end
```
It works with some bugs:
1. when the currentDate and incomingDate of the imported tiddler  are same, I hope it show the message of  "Modified time not change" or keep blank, but now it always show the currentDate and the incomingDate.
2. When the currentDate and incomingDate of the imported tiddler  are same, I hope it can set the "Select" checkbox to false by default.

Something like that:

![image](https://github.com/Jermolene/TiddlyWiki5/assets/40269098/0387efcb-5614-487c-b7ec-82f546a32928)

**Comment by lilixiong2018** [comment]
When the imported tiddler is not same as the current, is it enable to modify the current tiddler to combine the current tiddler and the imported tiddler with "merge" which include [ADD] and [DELETE] flag , and change the title of current tiddler to with prefix "[MERGE]" flag , so that I can manually modify later.

**Comment by pmario** [comment]
Your IF command is wrong - IMO should be 

```
<% if [<currentDate>compare:number:ne<incomingDate>] %>
```

See [compare operator docs](https://tiddlywiki.com/#compare%20Operator)

**Comment by pmario** [comment]
Once the $:/Import tiddler is created, you can add / modify `selection-*` fields in the tiddler, eg: `selection-Release 5.1.18: unchecked` 

If that field exists, the line will be shown as unchecked. 

See: https://talk.tiddlywiki.org/t/how-do-tws-json-formats-look-like/5998#import-tiddler-12 where the import tiddler structure is explained. 

Since you already know $:/core/ui/ImportListing you should be able to list all tiddlers that are contained in the import tiddler.

**Comment by lilixiong2018** [comment]
> Once the $:/Import tiddler is created, you can add / modify `selection-*` fields in the tiddler, eg: `selection-Release 5.1.18: unchecked`
> 
> If that field exists, the line will be shown as unchecked.
> 
> See: https://talk.tiddlywiki.org/t/how-do-tws-json-formats-look-like/5998#import-tiddler-12 where the import tiddler structure is explained.
> 
> Since you already know $:/core/ui/ImportListing you should be able to list all tiddlers that are contained in the import tiddler. `[[$:/Import]plugintiddlers[]sort[title]]`

Thank you very much! I modify the function handleImportTiddlersEvent of $:/core/modules/widgets/navigator.js, add this code which seem to work:

```
var td = $tw.wiki.getTiddler(title);
if (td && td.getFieldString("modified") == tiddler["modified"]) {
newFields["selection-" + title] = "unchecked";
}
```

**Comment by pmario** [comment]
You need to be careful with the modified state. TW has a setting that allows users to **disable timestamps**. 
So if you import tiddlers from someone, which did activate this option, you will run into problems.

So as long as you do not publish your wiki as a "basis" for others your changes will work. As soon as others will get your wiki it will cause problems. 

![image](https://github.com/Jermolene/TiddlyWiki5/assets/374655/2e4de553-0015-4759-a69e-6f0ff5666461)

have fun!
mario
