### ISSUE TITLE
[BUG] not-added tags are not saved when saving tiddler

### ISSUE THREAD

**Issue by twMat** [Jermolene/TiddlyWiki5#8328]
### Describe the bug

Typing in a new tag string in edit mode without clicking "Add" and without selecting anything from the dropdown to save it, but instead saving the tiddler, should also save the tag. Seems this behaviour has disappeared in 5.3.4. Please bring it back.

### Expected behavior

Same behaviour as 5.3.3, i.e that the not-added tag is stored when saving the tiddler.

### TiddlyWiki Configuration

- Version v5.3.4

**Comment by pmario** [comment]
I'll have a look at it

**Comment by pmario** [comment]
@twMat -- Fix has been merged. So can be closed

**Comment by twMat** [comment]
Wonderful! Thank you @pmario !
