### ISSUE TITLE
[BUG] when the $filter attribute returns non-existent tiddlers, the $data widget gives RSOD

### ISSUE THREAD

**Issue by btheado** [Jermolene/TiddlyWiki5#8330]
### Describe the bug

An `Uncaught TypeError: Cannot read properties of undefined (reading 'getFieldStrings')` exception is thrown if the filter attribute of the data widget returns entries which do not exist as tiddlers. For example:

```
<$data $filter="MissingTiddler"/>
```

Edit: Actually, now I'm seeing `TypeError: tiddler is undefined`. Not sure what I'm doing different now compared to before.

### Expected behavior

Tiddler with just a title field and no other fields should be generated and there should be no exception thrown.

### To Reproduce

1. Visit this [share link](https://tiddlywiki.com/share##%5B%7B%22title%22%3A%22%24%3A%2Fstate%2Fhttp-requests%22%2C%22text%22%3A%220%22%7D%2C%7B%22title%22%3A%22%24%3A%2FStoryList%22%2C%22text%22%3A%22%22%2C%22list%22%3A%22%5B%5BDraft%20of%20%27New%20Tiddler%27%5D%5D%22%7D%2C%7B%22created%22%3A%2220240703011738556%22%2C%22text%22%3A%22When%20the%20%24filter%20returns%20non-existent%20tiddlers%2C%20the%20%60%24data%60%20widget%20gives%20RSOD%20%28%60Uncaught%20TypeError%3A%20Cannot%20read%20properties%20of%20undefined%20%28reading%20%27getFieldStrings%27%29%60%29%5Cn%5Cn%3C%24data%20%24filter%3DMissingTiddler%2F%3E%22%2C%22draft.title%22%3A%22%24data%20%24filter%20bug%22%2C%22tags%22%3A%22%22%2C%22title%22%3A%22Draft%20of%20%27New%20Tiddler%27%22%2C%22draft.of%22%3A%22New%20Tiddler%22%2C%22modified%22%3A%2220240703011935427%22%7D%5D)
2. Click on the checkmark to save the tiddler
3. Observe the red screen of death

### TiddlyWiki Configuration

TW 5.3.4

**Comment by Jermolene** [comment]
Ouch, thank you @btheado

**Comment by btheado** [comment]
Fixed by #8333. Thanks @pmario!
