### ISSUE TITLE
[BUG] tag-picker enforces alphabetic sorting

### ISSUE THREAD

**Issue by twMat** [Jermolene/TiddlyWiki5#8346]
@pmario and @Jermolene - if this indeed is a bug then it is urgent before the release! (I'm stating this based on the impression that the tag-picker is one of those things that is being updated)

It seems that the tag-picker macro enforces a sorting!

`<<tag-picker tagListFilter:"""one two three""">>` - the tags are displayed as `one three two`

How would a user control the order if not by the tagListFilter?

**Comment by pmario** [comment]
The sort order is hardcoded at https://github.com/Jermolene/TiddlyWiki5/blob/eeeb9f97a9b517f5ed76267bb50d4d141c72c251/core/wiki/macros/tag-picker.tid#L177-L178

Since the rewrite, I did not change that. So it's _not_ a bug

**Comment by twMat** [comment]
Thanks. OK, no bug, good but bad - how is a user supposed to change it?

**Comment by pmario** [comment]
They don't -- The problem is, that at the moment that filter also bleeds into the keyboard handling. So there may be unknown side effects, if done poorly. So a lot more work will be needed. 

https://github.com/Jermolene/TiddlyWiki5/blob/eeeb9f97a9b517f5ed76267bb50d4d141c72c251/core/wiki/macros/tag-picker.tid#L1-L6

**Comment by twMat** [comment]
OK, thanks for your quick replies. I'll close this. 

I have a super cool application that I'll release shortly that depends on this to function properly (ironically, you, specifically, might be one of the few that I think might not like it ;-) we'll see). Will post a new isse then. Again, thanks.

**Comment by twMat** [comment]
closing
