### ISSUE TITLE
[BUG] New file "editions/tw5.com/tiddlers/Selection Constructors: Conditional.tid" breaks git checkout in Windows because it is an invalid file name

### ISSUE THREAD

**Issue by JulioCantarero** [Jermolene/TiddlyWiki5#8364]
### Describe the bug

A new file, "editions/tw5.com/tiddlers/Selection Constructors: Conditional.tid", was created last week. The file name is not good for windows, so I cannot do git checkout. 
I am not sure if this is a bug or not really. I just bumped into this while upgrading to 5.3.5 version by getting TW from github.
The check out of version 5.3.4 worked fine because this file did not exist.

### Expected behavior

"editions/tw5.com/tiddlers/Selection Constructors: Conditional.tid" should be a proper path name in major OS

### To Reproduce

1. Try git checkout v5.3.5
2. error: invalid path 'editions/tw5.com/tiddlers/Selection Constructors: Conditional.tid'

### TiddlyWiki Configuration

- Version v5.3.5
- Saving mechanism Not relevant
- Plugins installed Not relevant

### Desktop (please complete the following information):

- OS: Windows 11
- Browser Not Relevant
- Version Not Relevant

**Comment by pmario** [comment]
@Jermolene -- This is an important one, since it prevents checkout on Windows. There is an invalid character in the filename -- IMO the `:` is the culprit

**Comment by saqimtiaz** [comment]
This is a by product of the PR maker not being able to generate valid filenames.

Ideally we would want to reproduce the [same behaviour as on node.js](https://github.com/Jermolene/TiddlyWiki5/blob/7e2b035803438450509c57ec7d6db5b952644ec7/core/modules/utils/filesystem.js#L343-L386) via filter expressions/functions that we can use in the PR maker edition.

@pmario would you possibly have the time to look at this?

**Comment by pmario** [comment]
@JulioCantarero -- This one seems to be fixed

**Comment by Jermolene** [comment]
Thanks @JulioCantarero @saqimtiaz

**Comment by asampal** [comment]
Still happening for me under windows. I've deleted my local multiwiki branch from earlier, and tried to re-check it out, but get the reported error when doing so.

**Comment by saqimtiaz** [comment]
@asampal is the problem occurring only only the mws branch, or on master as well?

**Comment by asampal** [comment]
The master branch is fine, @saqimtiaz

**Comment by saqimtiaz** [comment]
@Jermolene I think you need to merge the changes from the master branch to the mws branch.

**Comment by Jermolene** [comment]
Thanks @asampal @saqimtiaz – the multi-wiki-support branch should be fixed now.
