### ISSUE TITLE
[IDEA] Make styleblocks benefit from "filtered transclusion as parameter" behaviour

### ISSUE THREAD

**Issue by twMat** [Jermolene/TiddlyWiki5#8379]
I now understand ([thanx](https://talk.tiddlywiki.org/t/why-let-only-outputs-first-item/10168)), and agree, with the logic to make "filtered transclusions used as parameters" only output the first item, and stringified. For this thread, let's refer to this as **"the behaviour"**

**Request**
I would like for the behaviour to also be applied for CSS **property values** in **style blocks**, e.g here:

`<style>[data-tiddler-title="foo"] {background:{{{ green }}}; } </style>`

The behaviour *is* applied for CSS property values when they appear in *full stylesheet tiddlers*, so for consistency and simplicity it should also be applied for style blocks.

I create a lot of solutions that rely on styleblocks because they can, for example, be inserted in listwidgets so that the style only applies to the currentTiddler.

**Comment by saqimtiaz** [comment]
This should give you what you need:
<style>[data-tiddler-title="foo"] {background:<$text text={{{ green }}}/>; } </style>

The filtered transclusion is not being used as a widget attribute here and therefore returns a link without the text widget, which is consistent with its behaviour elsewhere. If you open a stylesheet tiddler in the story and view it through the default view template, you will see the very same behaviour.

**Comment by twMat** [comment]
Thank you @saqimtiaz - not quite the request but I appreciate your reply and the solution will do.

By the way, in your solution the TextWidget ironically textifies an already pure string as it, in deed, gets the output from a "filtered transclusion as parameter" ;-)

closing
