### ISSUE TITLE
[IDEA] The number of blank lines in editing matches that in reading.

### ISSUE THREAD

**Issue by ker-j** [Jermolene/TiddlyWiki5#8381]
**Is your feature request related to a problem? Please describe.**
I'm from China and Tiddlywiki is my favorite taking note application but I'm always frustrated when I press Enter twice, it doesn't display two blank lines.

**Describe the solution you'd like**
when I press Enter twice, it can display two blank lines.——The number of blank lines displayed should match the number of blank lines in the editor.

**Describe alternatives you've considered**
I know `<br>` can easily solve this problem, but `<br>` affects the text during editing. I always have to use `<br>` instead of simply adding an extra space when editing.

**Additional context**
I need this feature because when I put Chinese poetry into TiddlyWiki, I always need blank lines to separate the stanzas.
But I don't want to use `<br>` to disrupt the text content.

Here is a Chinese poem.

进程
[北岛]

日复一日，苦难
正如伟大的事业般衰败
像一个小官僚
我坐在我的命运中
点亮孤独的国家

死者没有朋友
盲目的煤，嘹亮的灯光
我走在我的疼痛上
围栏以外的羊群
似田野开绽

形式的大雨使石头
变得残破不堪
我建造我的年代
孩子们凭借一道口令
穿过书的防线

>Thanks for the best Tiddlywiki

**Comment by pmario** [comment]
For poems you can use tripple double-quotes. https://tiddlywiki.com/#Hard%20Linebreaks%20in%20WikiText

```
"""
进程
[北岛]

日复一日，苦难
正如伟大的事业般衰败
像一个小官僚
我坐在我的命运中
点亮孤独的国家

...
"""
```
