### ISSUE TITLE
[BUG] When Import Canceled, TiddlyWiki Does not Delete SateTiddlers

### ISSUE THREAD

**Issue by kookma** [Jermolene/TiddlyWiki5#8398]
### Describe the bug

If user clicks `unselect all` checkbox and without importing cancel the operation TiddlyWiki does not delete `$:/state/import/select-all` tiddler.
This causes a problem for next import as the `unselect all` is unchecked!!

 

### Expected behavior

If user cancels import operation, TiddlyWiki shall delete the `$:/state/import/select-all` tiddler.

### To Reproduce

1. Go to https://tiddlywiki.com/
2. Import a tiddler by drag and drop
3. Unselect all
4. Cancel operation
5. Drag and drop another tiddler to trigger the $:/Import
6. See the error: the `unselect all` is unchecked

### Screenshots

![msedge_img_245_20240717](https://github.com/user-attachments/assets/5b466538-565b-4728-ad94-0a0e21a4c17c)

### TiddlyWiki Configuration

- Version 5.3.5
- https://tiddlywiki.com/

### Desktop (please complete the following information):

- OS: Win 11
- Browser Edge
- Version 126

### Additional context

Possible Solution:

1. edit $:/core/ui/ViewTemplate/body/import
2. correct 
```
\define confirmCancel()
\whitespace trim
<$action-confirm $message={{$:/language/Import/Listing/Cancel/Warning}} >
<$action-deletetiddler $tiddler=<<currentTiddler>>/>
<$action-sendmessage $message="tm-close-tiddler" title=<<currentTiddler>>/>
</$action-confirm>
\end
```

as

```
\define confirmCancel()
\whitespace trim
<$action-confirm $message={{$:/language/Import/Listing/Cancel/Warning}} >
<$action-deletetiddler $tiddler=<<currentTiddler>>/>
<$action-deletetiddler $tiddler="$:/state/import/select-all"/>                                        <-------------------------------------
<$action-sendmessage $message="tm-close-tiddler" title=<<currentTiddler>>/>
</$action-confirm>
\end
```

**Comment by pmario** [comment]
1. You can open: https://github.com/Jermolene/TiddlyWiki5/edit/master/core/ui/ViewTemplate/body/import.tid at GitHub
2. Then click the Edit-Button top right

- ![image](https://github.com/user-attachments/assets/3325bd8f-918a-477e-b959-3b1b10c29320)

3.  Change settings to Tabs - 4

- ![image](https://github.com/user-attachments/assets/826a9cea-0ff9-4ca9-b9b2-94d97d35c4cf)

4. Insert your code
5. Commit changes...

- ![image](https://github.com/user-attachments/assets/2cf2e4c2-3357-4692-a64e-41708055c0fb)

6. Prefill the form that pops up. -- Nothing bad can happen ;)
7. Propose changes

- ![image](https://github.com/user-attachments/assets/8c37d055-09cb-4b46-b8a2-f7ea1ef2fe0d)

8. It will create a new branch: "patch-x" in your repository and open the PR creation Page 
9. Create pull request 

- ![image](https://github.com/user-attachments/assets/90f219b3-fb36-4684-bfe5-7083a7e13bac)

10. There is your prefilled info, which you can check and change if needed
11. If you click "Create pull request" now it will **finally** create the PR, that you can still edit later in a very similar way

- ![image](https://github.com/user-attachments/assets/46e1c8fc-3adb-4511-afe3-c60b2baaf76b)

Hope that helps
BTW I did not create the PR -- That's your job ;)
