### ISSUE TITLE
filesystemadaptor.js: contentTypeInfo versus local typeInfo

### ISSUE THREAD

**Issue by TheDiveO** [Jermolene/TiddlyWiki5#845]
While hunting down my problem with a .jpeg image I came across https://github.com/Jermolene/TiddlyWiki5/blob/master/plugins/tiddlywiki/filesystem/filesystemadaptor.js#L149 and this looks fishy to me, but I'm not sure.

The sync adapter introduces its own tiny $tw.config.typeInfo while during boot the TW kernel establishes $tw.config.contentTypeInfo. The adapter uses mostly its own little table but also, as referenced above, the kernel content type info table. To me, this seems to be inconsistent, but as I'm unsure how the design is meant I cannot propose a fix here.

**Comment by pmario** [comment]
@TheDiveO ... very old link to code, that actually seems to be very different now. Can we close this issue?
