### ISSUE TITLE
Detect dragging within the same TiddlyWiki window

### ISSUE THREAD

**Issue by Jermolene** [Jermolene/TiddlyWiki5#846]
When a tiddler link is dropped within the same TiddlyWiki window we should:
- Not attempt to import the tiddler
- Use the "title" field rather than the text as the payload of the drag (this would make it possible to drag links from the sidebar into the textarea of a tiddler in edit mode)

**Comment by saqimtiaz** [comment]
@Jermolene seems to be resolved long since and can be closed.

**Comment by Jermolene** [comment]
Thanks @saqimtiaz
