### ISSUE TITLE
Add "transclusions" and "backtransclusions" filter operators

### ISSUE THREAD

**Issue by Jermolene** [Jermolene/TiddlyWiki5#847]
Similarly to the "links" and "backlinks" filter operators, we could support operators for reading the transclusions within a tiddler, and the tiddlers from which another tiddler was transcluded.

We could then divide the tiddler info "References" tab into subtabs for "All", "Links" and "Transclusions".

**Comment by pmario** [comment]
@Jermolene ... I think we can close this one, since the https://flibbles.github.io/tw5-relink/ plugin handles this

**Comment by Jermolene** [comment]
Thanks @pmario. I do still think we might want to add this to the core, it comes up fairly often, and there's a compelling logic to it.

**Comment by sobjornstad** [comment]
I agree with @Jermolene -- while the references tab provided by Relink is extremely useful, it doesn't provide a filter operator, unless I'm missing something. I would be interested in using this in my filters.
