### ISSUE TITLE
Refactor control panel layout

### ISSUE THREAD

**Issue by cbhushan** [Jermolene/TiddlyWiki5#892]
(Feature request)
During earlier version of beta, the encryption option used to appear in "Tools" tab. In recent versions (5.1.0) the encryption options are only accessible through toolbar (settings via Appearance->Toolbar). While it is useful to have ability to see encryption settings via toolbar, I feel that the 'natural' location of encryption settings is in "Saving" tabs. Also, as the encryption option is not available by default in toolbar, this highly useful feature may not be visible to new comers. 

Same goes with autosave settings, which as of 5.1.0 is available under "Settings" tab. "Saving" tabs sounds more nature for me for someone trying to find autosave settings. 

Also, just noticed that "Toolbar Buttons" is under "Settings" tab. A more natural location could be Appearance->Toolbar.

**Comment by pmario** [comment]
@Jermolene ... IMO this one can be closed. The ControlPanel looks very different now and the problems described in the OP are fixed.

**Comment by Jermolene** [comment]
Thanks @pmario
