### ISSUE TITLE
Extend upgrader to be able to install new plugins

### ISSUE THREAD

**Issue by Jermolene** [Jermolene/TiddlyWiki5#903]
It is proposed to extend http://tiddlywiki.com/upgrade.html so that it is also able to install new plugins. The idea is discussed here:

https://groups.google.com/d/msg/tiddlywiki/xNeS-QxXvMQ/vds5WcALO1UJ

**Comment by pmario** [comment]
I think, this would add way too much complexity to the upgrader. We know that some users already have problems using the TW upgrade mechanism in the right way. 

It hasn't been implemented for 6+ years, and I can't remember any new discussions about it. 

So IMO this issue should be closed.

**Comment by Jermolene** [comment]
I agree thanks @pmario
