### ISSUE TITLE
Avoid rendering certain system tiddlers in story view

### ISSUE THREAD

**Issue by Eucaly** [Jermolene/TiddlyWiki5#919]
- Opening tiddler PageTemplate shows text "Recursive transclusion error in transclude widget".
- suggest to add a mechanism (maybe SystemTag) on those special tiddlers, so that by default they will not been rendered in the Story view

That might include below system tiddlers (at least)
$:/core/ui/PageTemplate
$:/core/ui/ViewTemplate
$:/core/save/all
$:/core/save/empty
$:/core/save/lazy-images
$:/core/templates/static.content
$:/core/templates/store.area.template.html 

source: https://groups.google.com/forum/#!topic/tiddlywikidev/9uN1y7hpQgw

**Comment by pmario** [comment]
fix is on the way: http://tiddlywiki.com/prerelease/  ... after quite some time :)

**Comment by tobibeer** [comment]
@pmario: Where's that?

**Comment by pmario** [comment]
IMO has been removed again. Had to many side effects.

**Comment by pmario** [comment]
The new [ViewTemplate cascade handling](https://tiddlywiki.com/#%24%3A%2Fcore%2Fui%2FControlPanel%2FViewTemplateBody) shows those core tiddlers as code

```
[prefix[$:/boot/]] [prefix[$:/config/]] [prefix[$:/core/macros]] [prefix[$:/core/save/]] [prefix[$:/core/templates/]] 
[prefix[$:/core/ui/]split[/]count[]compare:number:eq[4]] [prefix[$:/info/]] [prefix[$:/language/]] [prefix[$:/languages/]]
[prefix[$:/snippets/]] [prefix[$:/state/]] [prefix[$:/status/]] [prefix[$:/info/]] [prefix[$:/temp/]] 
+[!is[image]limit[1]then[$:/core/ui/ViewTemplate/body/code]]
```

@Jermolene ... IMO can be closed

**Comment by Jermolene** [comment]
Thanks @pmario
