### ISSUE TITLE
caption vs subtitle

### ISSUE THREAD

**Issue by Evolena** [Jermolene/TiddlyWiki5#922]
I was wondering if spreading the use of the caption field to display alternative titles in lists (toc, ...) wouldn't have border effects on tabs, where it is used to have a very short label.

And here it is, it happens with commit https://github.com/Jermolene/TiddlyWiki5/commit/c26bd4c5a872f56c47e9f5cfc3fada468c53ddde: the caption on the Examples tiddler (added for displaying a more explicite title in the HelloThere tiddler with the list-link macro) has a border effect on the display of the tabs' labels in the Community tiddler (where the same Examples tiddler is referenced).

A subtitle field exists, which is currently only used for modal wizards.

Would it makes sense to use the caption field only for short labels (tabs, buttons) and the subtitle field for longer alternative titles? Or, if the wizard's subtitle has another meaning, proposing another field for these longer alternative titles?

The need of alternative titles has been expressed since a long time, and I think we should address it without interfering with the "short label" purpose of the caption field.

What is your opinion on the subject?

**Comment by Evolena** [comment]
Closed for clean up.
But I still think that the caption use is not always consistent (very short label, title substitution, ...), so the discussion remains open!

**Comment by Evolena** [comment]
Another related topic which leads to the proposal of a "quick fix" rather than a background discussion:
https://groups.google.com/d/msg/TiddlyWiki/Zah_tMeAdRs/BkYi6JiNEwAJ
I remember some changes since the previous discussion (a local macro in the toc-macros, maybe something on tabs-macro).
The risk is a lack of consistency (fields, their naming, macros using them), and opacity (ie the only way to know what field to use for display would be to look at the macro's code). If I find the time for that, I'll have a look at what is currently done on the subject.

**Comment by Jermolene** [comment]
Thanks @Evolena any help with those inconsistencies is very welcome!
