### ISSUE TITLE
 tc-tagged- classes need escaping

### ISSUE THREAD

**Issue by pmario** [Jermolene/TiddlyWiki5#958]
Not urgent. Just, that we don't forget it.

from: https://groups.google.com/d/msg/tiddlywikidev/YPbdR3b_u60/k6EMe014Dk8J

> > According to the grammar definition http://www.w3.org/TR/CSS21/grammar.html a class name imo can't have $:/
> 
> Ah, OK, that's significant. It looks like we also need to encode tc-tagged- classes differently.
> 
> Anyhow, in that case I think the answer would be either to introduce appropriate escaping, or for button tiddlers to have a "name" field that gives the short human readable name of the button.

**Comment by danielo515** [comment]
Is this issue still unresolved? do you mean that, currently, for weird tag names styling is not working? I made some tests and it works perfectly well. What is the problem with the current implementation?

**Comment by telmiger** [comment]
According to https://www.w3.org/TR/REC-CSS2/selector.html#attribute-selectors there seem to be only a few problematic characters: 

> A selector is a chain of one or more simple selectors separated by combinators. Combinators are: **whitespace, ">", and "+"**. Whitespace may appear between a combinator and the simple selectors around it.

**Comment by Jermolene** [comment]
Hi @telmiger that link doesn't address the escaping used for CSS selectors. See this link that I posted above:

https://mathiasbynens.be/notes/css-escapes

**Comment by pmario** [comment]
i'll close this in favor of: https://github.com/Jermolene/TiddlyWiki5/pull/2737
