### ISSUE TITLE
Avoid unnecessary scrolling at startup

### ISSUE THREAD

**Issue by Jermolene** [Jermolene/TiddlyWiki5#981]
As part of starting up, TiddlyWiki navigates to the first tiddler specified via `$:/DefaultTiddlers`. In the case of the classic storyview, it causes an unnecessary scroll operation to align the top of the tiddler to the top of the window. This disturbs the page layout and and hides any content tagged `$:/tags/BeforeStory` - see this discussion:

https://groups.google.com/d/topic/tiddlywiki/EAxbM575aO8/discussion

The fix is to avoid scrolling to the navigated tiddler if it is already substantially visible.

**Comment by sukima** [comment]
FYI This fix ignores any tiddlers tagged `$:/tags/AboveStory`. A discussion has been started on commit 65d81921 regarding this.
